### ISSUE TITLE
WARNING swManager_check_exit_status: worker#11 abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by troyscl** [swoole/swoole-src#1001]
Program terminated with signal SIGSEGV, Segmentation fault.
#0  xdebug_execute_ex (execute_data=0x7effe5614590) at /home/scl/workspace/ops/xdebug/xdebug.c:1825
1825                    fse->prev->user_defined = XDEBUG_EXTERNAL;
(gdb) bt
#0  xdebug_execute_ex (execute_data=0x7effe5614590) at /home/scl/workspace/ops/xdebug/xdebug.c:1825
#1  0x00000000007987ed in ZEND_CALL_TRAMPOLINE_SPEC_HANDLER () at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:1750
#2  0x0000000000754b0b in execute_ex (ex=<optimized out>) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:414
#3  0x00007effe4d1251f in xdebug_execute_ex (execute_data=0x7effe5614590) at /home/scl/workspace/ops/xdebug/xdebug.c:1900
#4  0x000000000079954d in ZEND_DO_FCALL_SPEC_HANDLER () at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:800
#5  0x0000000000754b0b in execute_ex (ex=<optimized out>) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:414
#6  0x00007effe4d1251f in xdebug_execute_ex (execute_data=0x7effe5614450) at /home/scl/workspace/ops/xdebug/xdebug.c:1900
#7  0x00000000007987ed in ZEND_CALL_TRAMPOLINE_SPEC_HANDLER () at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:1750
#8  0x0000000000754b0b in execute_ex (ex=<optimized out>) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:414
#9  0x00007effe4d1251f in xdebug_execute_ex (execute_data=0x7effe5614450) at /home/scl/workspace/ops/xdebug/xdebug.c:1900
#10 0x000000000079954d in ZEND_DO_FCALL_SPEC_HANDLER () at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:800
#11 0x0000000000754b0b in execute_ex (ex=<optimized out>) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:414
#12 0x00007effe4d1251f in xdebug_execute_ex (execute_data=0x7effe56140f0) at /home/scl/workspace/ops/xdebug/xdebug.c:1900
#13 0x000000000079954d in ZEND_DO_FCALL_SPEC_HANDLER () at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:800
#14 0x0000000000754b0b in execute_ex (ex=<optimized out>) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:414
#15 0x00007effe4d1251f in xdebug_execute_ex (execute_data=0x7effe5613de0) at /home/scl/workspace/ops/xdebug/xdebug.c:1900
#16 0x000000000079954d in ZEND_DO_FCALL_SPEC_HANDLER () at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:800
#17 0x0000000000754b0b in execute_ex (ex=<optimized out>) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:414
#18 0x00007effe4d1251f in xdebug_execute_ex (execute_data=0x7effe5613b50) at /home/scl/workspace/ops/xdebug/xdebug.c:1900
#19 0x000000000079954d in ZEND_DO_FCALL_SPEC_HANDLER () at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:800
#20 0x0000000000754b0b in execute_ex (ex=<optimized out>) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:414
#21 0x00007effe4d1251f in xdebug_execute_ex (execute_data=0x7effe56133d0) at /home/scl/workspace/ops/xdebug/xdebug.c:1900
#22 0x000000000079954d in ZEND_DO_FCALL_SPEC_HANDLER () at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:800
#23 0x0000000000754b0b in execute_ex (ex=<optimized out>) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:414
#24 0x00007effe4d1251f in xdebug_execute_ex (execute_data=0x7effe56132e0) at /home/scl/workspace/ops/xdebug/xdebug.c:1900
#25 0x00000000007061c4 in zend_call_function (fci=fci@entry=0x7fff84743c80, fci_cache=0x7fff84743bb0, fci_cache@entry=0x0) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_execute_API.c:866
#26 0x0000000000706579 in call_user_function_ex (function_table=<optimized out>, object=object@entry=0x0, function_name=<optimized out>, retval_ptr=retval_ptr@entry=0x7fff84743d00, param_count=param_count@entry=2,
    params=params@entry=0x7fff84743d10, no_separation=no_separation@entry=0, symbol_table=symbol_table@entry=0x0) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_execute_API.c:685
#27 0x00007effe47b25c9 in sw_call_user_function_ex (ymbol_table=0x0, no_separation=0, params=<synthetic pointer>, param_count=2, retval_ptr_ptr=<synthetic pointer>, function_name=<optimized out>, object_pp=0x0,
    function_table=<optimized out>) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/php7_wrapper.h:231
#28 php_swoole_onWorkerStart (serv=0x1aa1da0, worker_id=5) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/swoole_server.c:1081
#29 0x00007effe47f30a8 in swWorker_loop (factory=factory@entry=0x1aa21d0, worker_id=worker_id@entry=5) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/network/Worker.c:487
#30 0x00007effe47f02df in swManager_spawn_worker (factory=0x1aa21d0, worker_id=5) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/network/Manager.c:679
#31 0x00007effe47f0f75 in swManager_loop_sync (factory=0x1aa21d0) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/network/Manager.c:539
#32 swManager_start (factory=factory@entry=0x1aa21d0) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/network/Manager.c:183
#33 0x00007effe47e02f2 in swFactoryProcess_start (factory=0x1aa21d0) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/factory/FactoryProcess.c:86
#34 0x00007effe47e6ee9 in swServer_start (serv=serv@entry=0x1aa1da0) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/network/Server.c:648
#35 0x00007effe47b4ca9 in zim_swoole_server_start (execute_data=<optimized out>, return_value=0x7effe5613270) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/swoole_server.c:1864
#36 0x00007effe4d1306d in xdebug_execute_internal (current_execute_data=0x7effe5613280, return_value=0x7effe5613270) at /home/scl/workspace/ops/xdebug/xdebug.c:2050
#37 0x0000000000799420 in ZEND_DO_FCALL_SPEC_HANDLER () at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:844
#38 0x0000000000754b0b in execute_ex (ex=<optimized out>) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:414
#39 0x00007effe4d1251f in xdebug_execute_ex (execute_data=0x7effe56131b0) at /home/scl/workspace/ops/xdebug/xdebug.c:1900
#40 0x000000000079954d in ZEND_DO_FCALL_SPEC_HANDLER () at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:800
#41 0x0000000000754b0b in execute_ex (ex=<optimized out>) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:414
#42 0x00007effe4d1251f in xdebug_execute_ex (execute_data=0x7effe5613030) at /home/scl/workspace/ops/xdebug/xdebug.c:1900
#43 0x00000000007a8a87 in zend_execute (op_array=op_array@entry=0x7effe568b000, return_value=return_value@entry=0x0) at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:458
#44 0x0000000000714703 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /home/scl/workspace/ops/php-7.0.11/Zend/zend.c:1427
#45 0x00000000006b4cd0 in php_execute_script (primary_file=primary_file@entry=0x7fff847468d0) at /home/scl/workspace/ops/php-7.0.11/main/main.c:2494
#46 0x00000000007aa766 in do_cli (argc=2, argv=0x17e6b70) at /home/scl/workspace/ops/php-7.0.11/sapi/cli/php_cli.c:974
#47 0x0000000000432e24 in main (argc=2, argv=0x17e6b70) at /home/scl/workspace/ops/php-7.0.11/sapi/cli/php_cli.c:1344
(gdb) f 0
#0  xdebug_execute_ex (execute_data=0x7effe5614590) at /home/scl/workspace/ops/xdebug/xdebug.c:1825
1825                    fse->prev->user_defined = XDEBUG_EXTERNAL;
(gdb) f 1
#1  0x00000000007987ed in ZEND_CALL_TRAMPOLINE_SPEC_HANDLER () at /home/scl/workspace/ops/php-7.0.11/Zend/zend_vm_execute.h:1750
1750                            zend_execute_ex(call);
(gdb) 

-------------------------------------------------------------
php7 -v

PHP 7.0.11 (cli) (built: Nov  4 2016 16:07:22) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.11, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0-dev, Copyright (c) 2002-2016, by Derick Rethans
---------------------------------------------------------------
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.2' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)
------------------------------------------------------------------------
uname -a
Linux localhost 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by matyhtf** [comment]
去掉xdebug扩展，升级swoole版本尝试一下。
