### ISSUE TITLE
swReactorThread Error 1005

### ISSUE THREAD

**Issue by lujunjie521** [swoole/swoole-src#1002]
swReactorThread_send (ERROR 1005): send event$[4] failed, session#809 does not exist.

查看了一下源代码【1.9.3版本】
在.src\network\ReactorThread.c 文件中556行
![qq 20170104164743](https://cloud.githubusercontent.com/assets/4859178/21636381/87618868-d29d-11e6-8606-8622a7d88ed1.png)

从代码中，SW_EVENT_CLOSE定义为4，因此，既然已经关闭了，为啥还要建立呢。

除此之前，我在发送数据之前，我都做了连接检测的，存在才发送数据的。

**Comment by matyhtf** [comment]
这表示服务器端和客户端在同时关闭连接，因此会有一方失败。
