### ISSUE TITLE
swoole server使用TCP连接传输8K大小数据的时候报错

### ISSUE THREAD

**Issue by idonkeyliu** [swoole/swoole-src#1005]
WARN    swWorker_discard_data: [1]received the wrong data[8180 bytes] from socket#1

帮忙看看是啥问题呢，是哪里限制了吗？

**Comment by matyhtf** [comment]
这表示连接已经关闭了，收到的数据会被丢弃。

**Comment by idonkeyliu** [comment]
怎么才能解决这个问题啊，，是数据过大的原因吗？还是说是连接的时间要调整
