### ISSUE TITLE
php加入swoole扩展启动报错Segmentation fault

### ISSUE THREAD

**Issue by bluelifeleer** [swoole/swoole-src#1007]
[root@localhost etc]# gdb php core.2536
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/php/bin/php...done.

warning: core file may not match specified executable file.
[New LWP 2536]
Cannot access memory at address 0xd
Cannot access memory at address 0x5
Core was generated by `php-fpm'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f0530d850b5 in ?? ()
(gdb)
(gdb)
(gdb)
(gdb)
(gdb) f 1
#1  0x00007f053c0fd140 in ?? ()
(gdb) f 0
#0  0x00007f0530d850b5 in ?? ()
(gdb)

[root@localhost etc]# php -v
PHP 7.1.0 (cli) (built: Dec 20 2016 13:27:32) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

[root@localhost etc]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

[root@localhost etc]# uname -a
Linux localhost.localdomain 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by matyhtf** [comment]
无法重现此问题。检查swoole是否正确编译，并使用最新稳定版本。

**Comment by bluelifeleer** [comment]
谢谢！
