### ISSUE TITLE
swoole-1.9.3  安装 pecl install swoole  

### ISSUE THREAD

**Issue by kongdeyuan** [swoole/swoole-src#1010]
系统 Fedora25   php7 
执行 `pecl install swoole ` ，安装时的错误

`/var/tmp/swoole/swoole_http_client.c: 在函数‘http_client_onReceive’中:
/var/tmp/swoole/swoole_http_client.c:689:9: 警告：隐式声明函数‘inflateEnd’ [-Wimplicit-function-declaration]
         inflateEnd(&http->gzip_stream);
         ^~~~~~~~~~
/var/tmp/swoole/swoole_http_client.c:689:25: 错误：‘http_client {或称 struct <匿名>}’没有名为‘gzip_stream’的成员
         inflateEnd(&http->gzip_stream);
                         ^~
/var/tmp/swoole/swoole_http_client.c: 在函数‘http_client_free’中:
/var/tmp/swoole/swoole_http_client.c:1131:25: 错误：‘http_client {或称 struct <匿名>}’没有名为‘gzip_stream’的成员
         inflateEnd(&http->gzip_stream);
                         ^~
Makefile:224: recipe for target 'swoole_http_client.lo' failed
make: *** [swoole_http_client.lo] Error 1
ERROR: `make' failed
`

寻大神 求帮助～～～

**Comment by matyhtf** [comment]
请安装 zlib-dev
