### ISSUE TITLE
Mac OS X 10.11.6 源码编译 swoole-src-1.9.0-stable  开启 --enable-openssl 编译不通过

### ISSUE THREAD

**Issue by wakerman** [swoole/swoole-src#1011]
**gcc -v** 版本                                                 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**openssl version -a** 版本
OpenSSL 1.0.2j  26 Sep 2016
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx)
compiler: clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/etc/openssl"

**Mac OS X 版本**
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1108

**PHP版本**

PHP 5.6.29 (cli) (built: Dec  8 2016 23:03:30)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**编译参数：**

./configure --with-php-config=/usr/bin/php-config --enable-openssl

**报错信息：（有省略）**
/Users/ws/Downloads/swoole-src-1.9.0-stable/include/swoole.h/Users/ws/Downloads/swoole-src-1.9.0-stable/include/swoole.h::353353::1010::  fatal errorfatal error: : 'openssl/ssl.h''openssl/ssl.h'  filefile  notnot  foundfound

#include <openssl/ssl.h>#include <openssl/ssl.h>

         ^         ^

1 error generated.

/Users/ws/Downloads/swoole-src-1.9.0-stable/include/swoole.h:353:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^

/Users/ws/Downloads/swoole-src-1.9.0-stable/include/swoole.h:353:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
make: *** [swoole_websocket_server.lo] Error 1
1 error generated.
1 error generated.
make: *** [swoole_mmap.lo] Error 1
make: *** [src/protocol/MimeTypes.lo] Error 1
1 error generated.
make: *** [swoole_mysql.lo] Error 1
1 error generated.
make: *** [swoole_http_server.lo] Error 1
1 error generated.
1 error generated.
make: *** [swoole_module.lo] Error 1
make: *** [swoole_http_client.lo] Error 1
1 error generated.
1 error generated.
make: *** [swoole_server.lo] Error 1
make: *** [swoole_client.lo] Error 1
1 error generated.
make: *** [swoole.lo] Error 1

原来是通过 brew 安装的swoole

swoole

swoole support => enabled
Version => 1.8.11
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
rwlock => enabled
async http/websocket client => enabled
pcre => enabled
zlib => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608

现在想使用 wss ，所以想重新编译 开启 openssl 支持

**Comment by matyhtf** [comment]
你的系统没有安装openssl头文件，请先安装

**Comment by wakerman** [comment]
谢谢，解决方案：
下载 openssl-1.0.*
 ./config --prefix=/usr/local --openssldir=/usr/local/openssl
make 
make install

然后重新编译swoole
