### ISSUE TITLE
swoole客户端配置了证书就默认开启ssl加密

### ISSUE THREAD

**Issue by shiyanlin** [swoole/swoole-src#1018]
应该创建实例的时候指定SWOOLE_SSL才开启ssl加密才对吧

**Comment by matyhtf** [comment]
Client和Server不同，配置证书后就会启用SSL

**Comment by wakerman** [comment]
Server 里能否同时支持 ws和wss 协议而且用同一个端口？
或者是监听两个端口，一个是ws协议的，一个是wss 协议的，可有这种方法？

**Comment by matyhtf** [comment]
确实应该和Server的方式统一。感谢反馈。
