### ISSUE TITLE
Swoole\Coroutine\MySQL 在 ReflectionMethod->invokeArgs()  里卡死，无法返回

### ISSUE THREAD

**Issue by kilmas** [swoole/swoole-src#1020]
程序卡死无法执行到：$response->end($data);
代码如下：
```
class A {
    public function a ()  {
         $swoole_mysql = new \Swoole\Coroutine\MySQL();
         $connect = $swoole_mysql->connect();
         $res = $swoole_mysql->query();
         return [
            'test' => 'ok'
        ];
   }
}
$class   = new A();
$reflect = new \ReflectionMethod($class, 'a');
$data = $reflect->invokeArgs($args);
$response->end($data);
```

**Comment by yangxikun** [comment]
php5.x 不能再反射、魔术方法中使用协程client，用php7试试

**Comment by kilmas** [comment]
我用的是php7.0.2。我再研究研究swoole代码实现看看...

**Comment by yangxikun** [comment]
看了下，invokeArgs底层使用了zend_call_function，目前swoole的协程client没法在该场景使用

**Comment by kilmas** [comment]
这样是可以的返回的
class A {
  public function a () {
      $swoole_mysql = new \Swoole\Coroutine\MySQL();
      $connect = $swoole_mysql->connect();
      $res = $swoole_mysql->query();
      $response->end(json_encode($data));
   }
}
$class = new A();
$reflect = new \ReflectionMethod($class, 'a');
$data = $reflect->invokeArgs($args);
// $response->end($data);

**Comment by matyhtf** [comment]
反射函数中不支持协程 API，已加入文档。暂时无法解决。
