### ISSUE TITLE
\Swoole\Http\Client 无法在while(1)中执行

### ISSUE THREAD

**Issue by km3945** [swoole/swoole-src#1021]
swoole 1.94
```php
$i=0
while(1){
    $cli = new \Swoole\Http\Client($this->ip, 80);
     $cli->get('c'.$i,function($cli){
        echo strlen($cli->body);
     });
     sleep(1); 
    $i++;
}
```
为什么new \Swoole\Http\Client 不能在死循环里执行?
实际上这个死循环是一个消息队列监听器.
如果不是个死循环,那代码是正常的.
这是我实现思路有问题还是BUG?

我把while改成for($i=0;$i<1000;$i++)方式,又是正常的

在我理解中\Swoole\Http\Client是异步的.只要机器抗的住.就能一直给建新实例

**Comment by matyhtf** [comment]
http://wiki.swoole.com/wiki/page/502.html
