### ISSUE TITLE
[Request] An option for switching $swoole_http_request->server characters' case.

### ISSUE THREAD

**Issue by garveen** [swoole/swoole-src#1023]

**Comment by williamborba** [comment]
It is true, in PHP global $_SERVER contains values in uppercase
https://secure.php.net/manual/pt_BR/reserved.variables.server.php

In swoole "$request" the values are in lowercase causing confusing...

**Comment by matyhtf** [comment]
Uppercase character is not a good style.
Swoole is not compatible with php-fpm.
