### ISSUE TITLE
\Swoole\Coroutine\Redis  问题

### ISSUE THREAD

**Issue by xtgxiso** [swoole/swoole-src#1025]
https://github.com/xtgxiso/WebWorker-swoole 下面的demo.php中对redis?coroutine=0的访问，用的原生的redis同步扩展。当redis?coroutine=1启用协程库redis的时候，单个请求正常，用ab测试的时候当并发数超过工作进程数时会出问题

**Comment by matyhtf** [comment]
错误的用法。

**Comment by xtgxiso** [comment]
是的，多谢在群里的回答
