### ISSUE TITLE
error "Enable sockets support, require sockets extension."

### ISSUE THREAD

**Issue by w3yyb** [swoole/swoole-src#1027]
error: #error "Enable sockets support, require sockets extension."
 #error "Enable sockets support, require sockets extension."
  ^
Makefile:194: recipe for target 'swoole.lo' failed
make: *** [swoole.lo] Error 1

我的php已安装了 sockets扩展了，这是怎么回事？

**Comment by w3yyb** [comment]
ubuntu 16.04   安装 swoole 2.0.5

**Comment by w3yyb** [comment]
cd swoole
phpize
./configure --enable-sockets=/usr/include/php/20151012/ext/sockets 
make 
sudo make install
这样就好了

**Comment by matyhtf** [comment]
不仅需要sockets扩展，还需要源文件。建议编译PHP时增加--enable-sockets

**Comment by w3yyb** [comment]
我是  apt-get  install 安装的 ，在 cenos上 yum安装的没有 问题。

**Comment by matyhtf** [comment]
试试安装 php5-dev

**Comment by w3yyb** [comment]
我都是安装的 php7    也装了 php7.0-dev

**Comment by rovico** [comment]
Hi All! I need ssl support in swoole, and therefore i downloaded last version (2.1.1) and configured it with params ./configure  --enable-sockets --enable-openssl --with-php-config=/usr/local/php/bin/php-config

In result I got two errors:

In file included from /home/pavel/work/swoole-src-2.1.1/swoole_coroutine.c:17:0:
/home/pavel/work/swoole-src-2.1.1/php_swoole.h:136:2: error: #error "Enable sockets support, require sockets extension."
 #error "Enable sockets support, require sockets extension."
  ^
/home/pavel/work/swoole-src-2.1.1/php_swoole.h:142:2: error: #error "Enable http2 support, require nghttp2 library."
 #error "Enable http2 support, require nghttp2 library."

I tryied to install php7.2-sockets manually, but installer notified, that instead php7.2-sockets it will use php7.2-common and there is nothing to install.

With second error I have no idea too: I installed nghttp2 with command apt install nghttp2 but still got an error.

P.S. My environment: php 7.2 on Ubuntu 16.04;

What I am doing wrong? And what I need to do to solve this problems?

**Comment by guigui0326** [comment]
请问楼主解决了么，我也遇到一样的问题，同样的apt安装的7.0，php -m也存在sockets
