### ISSUE TITLE
WARNING swSSL_accept: swSSL_accept() failed. Error: DH lib[5]

### ISSUE THREAD

**Issue by hhxsv5** [swoole/swoole-src#1032]
大量相同的WARNING日志占满了硬盘：
[2017-01-20 13:03:19 #16877.3]	WARNING	swSSL_accept: swSSL_accept() failed. Error: DH lib[5]
[2017-01-20 13:03:21 #16877.3]	WARNING	swSSL_accept: swSSL_accept() failed. Error: DH lib[5]
[2017-01-20 13:03:24 #16877.3]	WARNING	swSSL_accept: swSSL_accept() failed. Error: DH lib[5]
[2017-01-20 13:03:25 #16877.3]	WARNING	swSSL_accept: swSSL_accept() failed. Error: DH lib[5]
[2017-01-20 13:03:25 #16877.3]	WARNING	swSSL_accept: swSSL_accept() failed. Error: DH lib[5]
[2017-01-20 13:03:48 #16877.3]	WARNING	swSSL_accept: swSSL_accept() failed. Error: DH lib[5]
[2017-01-20 13:03:48 #16877.3]	WARNING	swSSL_accept: swSSL_accept() failed. Error: DH lib[5]
[2017-01-20 13:03:48 #16877.3]	WARNING	swSSL_accept: swSSL_accept() failed. Error: DH lib[5]
[2017-01-20 13:03:48 #16877.3]	WARNING	swSSL_accept: swSSL_accept() failed. Error: DH lib[5]
[2017-01-20 13:03:48 #16877.3]	WARNING	swSSL_accept: swSSL_accept() failed. Error: DH lib[5]
[2017-01-20 13:03:49 #16877.3]	WARNING	swSSL_accept: swSSL_accept() failed. Error: DH lib[5]

Websocket Server配置：
```JSON
{
    "daemonize": false,
    "task_worker_num": 8,
    "worker_num": 8,
    "dispatch_mode": 2,
    "log_file": "./logs/swoole-2017-01-20.log",
    "log_level": 5, //虽然我指定的是5，但还是会报WARNING的错
    "user": "med",
    "group": "med",
    "enable_reuse_port": true,
    "heartbeat_idle_time": 10,
    "heartbeat_check_interval": 4,
    "ssl_cert_file": "./xxx.com.crt",
    "ssl_key_file": "./xx.com.key"
}
```

Swoole扩展信息
```
swoole

swoole support => enabled
Version => 1.9.4
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608
```

**Comment by hhxsv5** [comment]
另外，服务器阿里云的，经过slb转发443数据到此服务器上，猜测应该有健康检查。

**Comment by matyhtf** [comment]
使用gdb 和 strace 工具跟踪一下

**Comment by matyhtf** [comment]
方便地话请使用 1.9.5-alpha 进行测试。

**Comment by hhxsv5** [comment]
gettimeofday({1485069121, 894754}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069122, 895962}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069123, 896517}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069124, 897205}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069125, 897499}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069126, 898780}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069127, 899110}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069128, 899778}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069129, 900799}, NULL) = 0
epoll_wait(49, {{EPOLLIN, {u32=6, u64=4294967302}}}, 4096, 1000) = 1
accept4(6, {sa_family=AF_INET, sin_port=htons(7531), sin_addr=inet_addr("119.4.175.18")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 57
epoll_ctl(52, EPOLL_CTL_ADD, 57, {EPOLLIN, {u32=57, u64=57}}) = 0
accept4(6, 0x7ffce743f6a0, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
gettimeofday({1485069130, 96282}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069131, 96781}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069132, 97290}, NULL) = 0
epoll_wait(49, {{EPOLLIN, {u32=6, u64=4294967302}}}, 4096, 1000) = 1
accept4(6, {sa_family=AF_INET, sin_port=htons(41128), sin_addr=inet_addr("221.223.83.106")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 56
epoll_ctl(54, EPOLL_CTL_ADD, 56, {EPOLLIN, {u32=56, u64=56}}) = 0
accept4(6, 0x7ffce743f6a0, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
gettimeofday({1485069133, 19026}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069134, 20231}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069135, 20816}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069136, 22046}, NULL) = 0
epoll_wait(49, {{EPOLLIN, {u32=6, u64=4294967302}}}, 4096, 1000) = 1
accept4(6, {sa_family=AF_INET, sin_port=htons(36577), sin_addr=inet_addr("112.97.61.223")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 58
epoll_ctl(51, EPOLL_CTL_ADD, 58, {EPOLLIN, {u32=58, u64=58}}) = 0
accept4(6, 0x7ffce743f6a0, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
gettimeofday({1485069136, 979138}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069137, 980330}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069138, 981533}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069139, 981945}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069140, 982916}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069141, 983861}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069142, 985045}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069143, 986145}, NULL) = 0
epoll_wait(49, {{EPOLLIN, {u32=6, u64=4294967302}}}, 4096, 1000) = 1
accept4(6, {sa_family=AF_INET, sin_port=htons(7532), sin_addr=inet_addr("119.4.175.18")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 57
epoll_ctl(52, EPOLL_CTL_ADD, 57, {EPOLLIN, {u32=57, u64=57}}) = 0
accept4(6, 0x7ffce743f6a0, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
gettimeofday({1485069144, 145201}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0
gettimeofday({1485069145, 145792}, NULL) = 0
epoll_wait(49, {}, 4096, 1000)          = 0

**Comment by hhxsv5** [comment]
这日志增长速度要了运维哥哥的命

![image](https://cloud.githubusercontent.com/assets/7278743/22180815/4156410c-e0b6-11e6-9fae-fa0e240cd067.png)

**Comment by matyhtf** [comment]
使用`strace -f -p 进程ID`跟踪，这里无法看到reactor线程的运行状况。

**Comment by hhxsv5** [comment]
好的，
PID 19702

```
19735 restart_syscall(<... resuming interrupted call ...> <unfinished ...>
19734 gettimeofday({1485069819, 940441}, NULL) = 0
19734 stat("/etc/localtime",  <unfinished ...>
19732 epoll_wait(52,  <unfinished ...>
19702 epoll_wait(49,  <unfinished ...>
19734 <... stat resumed> {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87 <unfinished ...>
19733 epoll_wait(51,  <unfinished ...>
19731 epoll_wait(54,  <unfinished ...>
19734 <... write resumed> )             = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 941134}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 941527}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 942113}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 942466}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 943348}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 943652}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 944259}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 944474}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 945464}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 945772}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 946226}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 946612}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 946920}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 947083}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 947399}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 947546}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 947854}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 947995}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 948391}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 948944}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 949260}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 949396}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 949681}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 949833}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 950176}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 950324}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 950973}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 951104}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 951373}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 951494}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 951753}, NULL) = 0
19734 read(55, "", 34117)               = 0
19734 gettimeofday({1485069819, 951874}, NULL) = 0
19734 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
19734 write(8, "[2017-01-22 15:23:39 #19702.3]\tW"..., 87) = 87
19734 epoll_wait(53, {{EPOLLIN, {u32=55, u64=55}}}, 4096, -1) = 1
19734 gettimeofday({1485069819, 952129}, NULL) = 0
```


PID 19730

```
19730 wait4(-1,  <detached ...>
```

**Comment by hhxsv5** [comment]
另外，升级swoole从1.8.13到1.9.4，还是会有这个问题。

**Comment by matyhtf** [comment]
请加我的QQ 12811247，详细聊。

**Comment by hanye1310370** [comment]
我也遇到这个问题了？ 这个最后咋解决的？ php7.1.6   swoole4.2.9
