### ISSUE TITLE
duplicated swoole_init

### ISSUE THREAD

**Issue by lvht** [swoole/swoole-src#1034]
Are these `swoole_init` call duplicated ?

- https://github.com/swoole/swoole-src/blob/master/swoole.c#L759
- https://github.com/swoole/swoole-src/blob/master/src/network/Server.c#L732

**Comment by matyhtf** [comment]
This is for compatibility with C/C++ programs.
There is no MINIT in the C program.  It must execute `swoole_init` when calling `swServer_init`.
