### ISSUE TITLE
Swoole releases aren't synced with pecl releases

### ISSUE THREAD

**Issue by petk** [swoole/swoole-src#1042]
Hello, I was just browsing through the releases here:
https://github.com/swoole/swoole-src/releases
and here:
https://pecl.php.net/package/swoole

The latest stable is probably the version `1.9.5` which isn't available via GitHub yet.

For consistency, it would be really nice to have also the latest releases available via GitHub releases or the release process synced. So we know which is the latest and best release.

Thank you for your great work.

**Comment by matyhtf** [comment]
Thank you for your feedback. 
Synchronized now.
