### ISSUE TITLE
🚀 Static code analysis by Coverity Scan

### ISSUE THREAD

**Issue by tutanhamon** [swoole/swoole-src#1070]
Hi, I configured a static code analysis for my forked _swoole-src_ repo using [Coverity Scan](https://scan.coverity.com) service (it's free for open source projects).

Scan report is available here – [![Coverity Scan](https://scan.coverity.com/projects/11549/badge.svg)](https://scan.coverity.com/projects/tutanhamon-swoole-src) (1.x master branch compiled for PHP 7.0 on Linux). To access a list of defects you need to login with your GitHub account by pressing `"Add me to project"` button.

After recent fixes there are a few issues left, hope we can fix them all with the community help.

We can also configure a separate Coverity account for the original _swoole-src_ repository and [integrate it with Travis CI](https://docs.travis-ci.com/user/coverity-scan/) to [automate the Coverity Scan submissions](https://scan.coverity.com/travis_ci).

![image](https://cloud.githubusercontent.com/assets/845773/22601448/939b2b2c-ea47-11e6-8fed-e898e524d67e.png)

![image](https://cloud.githubusercontent.com/assets/845773/22601475/b35f893a-ea47-11e6-90be-9edde50d9815.png)

**Comment by matyhtf** [comment]
This is a good suggestion. I'll add it later. Thanks.

**Comment by hdogan** [comment]
And update for this issue? I think the project may need to be get in feature freeze state for some time and focus on solving these defects.

**Comment by matyhtf** [comment]
done.
