### ISSUE TITLE
【紧急！！！】Segmentation fault swoole-src-1.8.11

### ISSUE THREAD

**Issue by troyscl** [swoole/swoole-src#1074]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `novasvrd_task_work'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  swHeap_maxchild (heap=0x29a2b70, heap=0x29a2b70, heap=0x29a2b70, i=10756) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/core/heap.c:72
72          swHeap_node * child_node = heap->nodes[child_i];
(gdb) bt
#0  swHeap_maxchild (heap=0x29a2b70, heap=0x29a2b70, heap=0x29a2b70, i=10756) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/core/heap.c:72
#1  swHeap_percolate_down (heap=0x29a2b70, i=10756) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/core/heap.c:108
#2  0x00007f595e3cc8a3 in swHeap_remove (heap=<optimized out>, node=<optimized out>) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/core/heap.c:178
#3  0x00007f595e3e39bf in swTimer_del (timer=timer@entry=0x7f595e684920 <SwooleG>, tnode=tnode@entry=0x2bcaaf0) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/network/Timer.c:134
#4  0x00007f595e3aef87 in zif_swoole_timer_clear (execute_data=<optimized out>, return_value=0x7f595f213c60) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/swoole_timer.c:325
#5  0x000000000077958b in ZEND_DO_FCALL_SPEC_HANDLER () at /home/thomas/dev/osp/php-7.0.8/Zend/zend_vm_execute.h:842
#6  0x000000000073ba2b in execute_ex (ex=<optimized out>) at /home/thomas/dev/osp/php-7.0.8/Zend/zend_vm_execute.h:414
#7  0x00000000006f187b in zend_call_function (fci=fci@entry=0x7ffda3874110, fci_cache=0x2aaaab690a28, fci_cache@entry=0x0) at /home/thomas/dev/osp/php-7.0.8/Zend/zend_execute_API.c:866
#8  0x00000000006f1d98 in call_user_function_ex (function_table=<optimized out>, object=<optimized out>, function_name=<optimized out>, retval_ptr=retval_ptr@entry=0x7ffda3874200, param_count=param_count@entry=4, 
    params=params@entry=0x7ffda3874230, no_separation=no_separation@entry=0, symbol_table=symbol_table@entry=0x0) at /home/thomas/dev/osp/php-7.0.8/Zend/zend_execute_API.c:685
#9  0x00007f595e3a1d54 in sw_call_user_function_ex (ymbol_table=0x0, no_separation=0, params=0x7ffda3874210, param_count=4, retval_ptr_ptr=<synthetic pointer>, function_name=<optimized out>, object_pp=0x0, 
    function_table=<optimized out>) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/php7_wrapper.h:231
#10 php_swoole_onTask (serv=0x2993630, req=<optimized out>) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/swoole_server.c:812
#11 0x00007f595e3db073 in swProcessPool_worker_loop (pool=0x7f595d14e238, worker=0x7f595d1512c0) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/network/ProcessPool.c:345
#12 0x00007f595e3dbb5c in swProcessPool_spawn (worker=0x7f595d1512c0) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/network/ProcessPool.c:243
#13 0x00007f595e3dbca1 in swProcessPool_start (pool=0x7f595d14e238) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/network/ProcessPool.c:106
#14 0x00007f595e3e121c in swManager_start (factory=factory@entry=0x2993a60) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/network/Manager.c:135
#15 0x00007f595e3d02f2 in swFactoryProcess_start (factory=0x2993a60) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/factory/FactoryProcess.c:86
#16 0x00007f595e3d6ee9 in swServer_start (serv=serv@entry=0x2993630) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/network/Server.c:648
#17 0x00007f595e3a4ca9 in zim_swoole_server_start (execute_data=<optimized out>, return_value=0x7f595f213130) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/swoole_server.c:1864
#18 0x000000000077958b in ZEND_DO_FCALL_SPEC_HANDLER () at /home/thomas/dev/osp/php-7.0.8/Zend/zend_vm_execute.h:842
#19 0x000000000073ba2b in execute_ex (ex=<optimized out>) at /home/thomas/dev/osp/php-7.0.8/Zend/zend_vm_execute.h:414
#20 0x0000000000784dd7 in zend_execute (op_array=0x7f595f284000, op_array@entry=0x2aaaab4c0b80, return_value=return_value@entry=0x7f595f2130d0) at /home/thomas/dev/osp/php-7.0.8/Zend/zend_vm_execute.h:458
#21 0x00000000006ff534 in zend_execute_scripts (type=type@entry=8, retval=0x7f595f2130d0, retval@entry=0x0, file_count=file_count@entry=3) at /home/thomas/dev/osp/php-7.0.8/Zend/zend.c:1427
#22 0x00000000006a35f8 in php_execute_script (primary_file=primary_file@entry=0x7ffda3878bf0) at /home/thomas/dev/osp/php-7.0.8/main/main.c:2494
#23 0x00000000007869a8 in do_cli (argc=2, argv=0x27c9f80) at /home/thomas/dev/osp/php-7.0.8/sapi/cli/php_cli.c:974
#24 0x0000000000438b40 in main (argc=2, argv=0x27c9f80) at /home/thomas/dev/osp/php-7.0.8/sapi/cli/php_cli.c:1344
(gdb) source .gdbinit
.gdbinit: No such file or directory.
(gdb) f 1
#1  swHeap_percolate_down (heap=0x29a2b70, i=10756) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/core/heap.c:108
108         while ((child_i = swHeap_maxchild(heap, i))
(gdb) f 0
#0  swHeap_maxchild (heap=0x29a2b70, heap=0x29a2b70, heap=0x29a2b70, i=10756) at /home/thomas/dev/osp/swoole-src-1.8.11-stable-signal/src/core/heap.c:72
72          swHeap_node * child_node = heap->nodes[child_i];
(gdb)

**Comment by troyscl** [comment]
php7 -v

PHP 7.0.8 (cli) (built: Sep 29 2016 11:58:39) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8, Copyright (c) 1999-2016, by Zend Technologies

**Comment by troyscl** [comment]
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)

**Comment by troyscl** [comment]
uname -a
Linux LC-SVR-main 3.13.0-96-generic #143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by matyhtf** [comment]
QQ 12811247 ，详细聊

**Comment by troyscl** [comment]
非常感谢matyhtf 提供的帮助
