### ISSUE TITLE
2.0版本使用websocket server，connection_info的last_time不更新

### ISSUE THREAD

**Issue by z5864703** [swoole/swoole-src#1075]
应该是2.0所有版本都有这个问题，connection_info的last_time不更新。
明明客户端发了数据到服务器，而且服务器还响应了内容，但是last_time还是连接时间，没有更新到最后接收数据时间，导致心跳检测客户端不在线然后服务器强制断线。
一开始我总找自动断线原因，排除了环境，程序，然后回滚到1.9版本就正常了，希望作者能尽快修复

$this->websocket_server = new WebSocketServer("0.0.0.0", 9502, SWOOLE_PROCESS, SWOOLE_SOCK_TCP | SWOOLE_SSL);
 //设置SSL
$this->websocket_server->set([
            'ssl_cert_file' => storage_path('ssl_file/x.crt'),
            'ssl_key_file' => storage_path('ssl_file/x.key'),
            'heartbeat_check_interval' => 20,    //20秒侦测一次心跳
            'heartbeat_idle_time' => 50,    //50秒未向服务器发送数据切断连接
            'user' => 'www',    //worker运行用户
            'group' => 'www',   //worker运行用户组
            'worker_num' => 4,  //worker进程数量
            'log_file' => '/home/wwwlogs/swoole.log',
            //'daemonize' => 1,   //守护进程运行
        ]);

**Comment by z5864703** [comment]
补充一下，编译2.0时已启用协程

**Comment by matyhtf** [comment]
注册了哪些回调函数
