### ISSUE TITLE
压测时日志里出现大量WARNING swReactorThread_alloc: memory pool is full. Wait memory collect , alloc(188) ； master进程的cpu使用率一直就停留在了40%

### ISSUE THREAD

**Issue by forallthis** [swoole/swoole-src#1078]
我搭了一个nginx+swoole服务，项目用的是phalcon框架，用http_load压测，压测一轮后 ，日志里出现 大量WARNING swReactorThread_alloc: memory pool is full. Wait memory collect , alloc(188) ； master进程的cpu使用率一直就停留在了40%。 

问题产生原因：编译swoole的时候带上了 --enable-ringbuffer 
解决办法：重新编译，取消enable-ringbuffer， 压测显示正常。 （PS: 日志里会出现新的批量的 ERROR   swReactorThread_send (ERROR 1005): send event$[4] failed, session#3750396 does not exist.  但是请求输出正常）

**Comment by matyhtf** [comment]
请关闭`--enable-ringbuffer`配置参数
