### ISSUE TITLE
What the difference between SWOOLE_BASE,  SWOOLE_THREAD,  SWOOLE_PROCESS, SWOOLE_BASE, SWOOLE_THREAD, SWOOLE_PACKET ?

### ISSUE THREAD

**Issue by coollider** [swoole/swoole-src#1085]

**Comment by matyhtf** [comment]
Only SWOOLE_BASE and SWOOLE_PROCESS are valid.
The SWOOLE_BASE mode can be understood as node.js, it's single-process and single-thread.

**Comment by coollider** [comment]
Big thanks for fast answer. You can close.

**Comment by matyhtf** [comment]
The SWOOLE_PROCESS mode consists of a multi-thread reactor and multi-process worker.
