### ISSUE TITLE
编译时指定openssl版本报错 "Enable openssl support, require openssl library."

### ISSUE THREAD

**Issue by alexmango** [swoole/swoole-src#1087]
编译环境：
Ubuntu 12.04 Server LTS
gcc  4.6.3 
openssl 1.0.2j
swoole 1.9.5
php 5.4.15

1. 先编译 openssl：
cd /data/build/
wget wget -c --content-disposition https://www.openssl.org/source/openssl-1.0.2k.tar.gz
tar xzvf openssl-1.0.2k.tar.gz
cd openssl-1.0.2k/;
./config --prefix=/data/services/openssl-1.0.2k shared zlib
make;
sudo make install;

编译成功。

2. 再编译 swoole
cd /data/build/
wget wget -c --content-disposition https://github.com/swoole/swoole-src/archive/v1.9.5.tar.gz
tar xzvf swoole-src-1.9.5.tar.gz
cd swoole-src-1.9.5
phpize
./configure --enable-sockets --with-openssl-dir=/data/services/openssl-1.0.2k --enable-openssl
make
报错如下：
In file included from /data/build/swoole-src-1.9.5/swoole.c:16:0:
/data/build/swoole-src-1.9.5/php_swoole.h:120:2: error: #error **"Enable openssl support, require openssl library."**
make: *** [swoole.lo] Error 1

swoole 不能指定 openssl 版本吗？因为系统自带的openssl版本较老，有很多漏洞，所以才想指定openssl版本

**Comment by alexmango** [comment]
@matyhtf

**Comment by jonnywang** [comment]
```
cat config.h | grep SW_USE_OPENSSL
cat config.h | grep HAVE_OPENSSL
```

执行以上命令查看下输出什么

**Comment by matyhtf** [comment]
这是由于config.m4中编译检测不能使用指定的openssl导致，新版本已经解决了，可以修改`config.h`增加 `#def HAVE_OPENSSL 1`
