### ISSUE TITLE
swoole2编译会导致php7.1产生 Segmentation fault 

### ISSUE THREAD

**Issue by snowair** [swoole/swoole-src#1098]
本来php7.1是正常的, 但编译完swoole(试过2.0.5/2.0.6/1.9.5)以后, 

执行php二进制文件就会 **Segmentation fault**

**Comment by xyzhu1120** [comment]
请提供php和swoole的编译参数以及core的函数栈信息和复现方法

**Comment by snowair** [comment]
已排查出不是swoole引起的,是另一个扩展引起的.
