### ISSUE TITLE
WARNING swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by huangzhhui** [swoole/swoole-src#1100]
请求时不时会出现 WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11

(gdb) bt
#0  0x00007f2b299caad1 in ?? ()
#1  0x00007f2b12005b5e in swoole_mysql_coro_onRead (
    reactor=0x7f2b2a89b1a0, event=0x7ffff61101f0)
    at /root/swoole-src-2.0.6/swoole_mysql_coro.c:938
#2  0x00007f2b1203b81f in swReactorEpoll_wait (reactor=0x7f2b2a89b1a0, 
    timeo=<optimized out>)
    at /root/swoole-src-2.0.6/src/reactor/ReactorEpoll.c:258
#3  0x00007f2b1204b2cf in swWorker_loop (
    factory=factory@entry=0x7f2b2a865820, worker_id=worker_id@entry=0)
    at /root/swoole-src-2.0.6/src/network/Worker.c:518
#4  0x00007f2b120484dc in swManager_spawn_worker (
    factory=0x7f2b2a865820, worker_id=0)
    at /root/swoole-src-2.0.6/src/network/Manager.c:644
#5  0x00007f2b12048a3f in swManager_start (
    factory=factory@entry=0x7f2b2a865820)
    at /root/swoole-src-2.0.6/src/network/Manager.c:133
#6  0x00007f2b1203861a in swFactoryProcess_start (
    factory=0x7f2b2a865820)
    at /root/swoole-src-2.0.6/src/factory/FactoryProcess.c:86
#7  0x00007f2b1203f423 in swServer_start (
    serv=serv@entry=0x7f2b2a8653f0)
    at /root/swoole-src-2.0.6/src/network/Server.c:696
#8  0x00007f2b11ff406a in zim_swoole_http_server_start (
    ht=<optimized out>, return_value=0x7f2b11b15c10, 
    return_value_ptr=<optimized out>, this_ptr=0x7f2b11b22970, 
    return_value_used=<optimized out>)
    at /root/swoole-src-2.0.6/swoole_http_server.c:1477
#9  0x00007f2b299e344b in dtrace_execute_internal ()
#10 0x00007f2b29a9d4f4 in ?? ()
#11 0x00007f2b29a317f8 in execute_ex ()
#12 0x00007f2b299e3329 in dtrace_execute_ex ()
#13 0x00007f2b29a9d9a9 in ?? ()
#14 0x00007f2b29a317f8 in execute_ex ()
#15 0x00007f2b299e3329 in dtrace_execute_ex ()
#16 0x00007f2b299f60db in zend_execute_scripts ()
#17 0x00007f2b29990e32 in php_execute_script ()
#18 0x00007f2b29a9f408 in ?? ()
#19 0x00007f2b2986b17a in ?? ()
#20 0x00007f2b2633ab35 in __libc_start_main () from /lib64/libc.so.6
#21 0x00007f2b2986b215 in _start ()

**Comment by matyhtf** [comment]
swoole版本多少？

**Comment by xyzhu1120** [comment]
可以稳定复现吗？

**Comment by matyhtf** [comment]
请手动编辑Makefile，将CFLAGS = -Wall -pthread -g -O2替换为CFLAGS = -Wall -pthread -g -O2 -fno-strict-aliasing
