### ISSUE TITLE
swoole_http_client是否支持HTTP2

### ISSUE THREAD

**Issue by qiqizjl** [swoole/swoole-src#1107]
最近想用swoole做一个ios http2的推送
但是发现用swoole_http_client始终连不上apple服务器。
最后检查发现貌似是swoole_http_client不支持http2导致的。
请问swoole_http_client是否支持http2，若支持如何开启呢

**Comment by matyhtf** [comment]
暂时不支持http2

**Comment by qiqizjl** [comment]
有支持计划么 大概何时可以支持

**Comment by matyhtf** [comment]
已支持。

**Comment by qiqizjl** [comment]
get是可以了 但是post看起来有问题

nginx访问日志记录到post请求是
`https://xxx xxx - - [10/Mar/2017:08:51:49 +0800] "-" 400 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3026.3 Safari/537.36"
https://xxx xxx - - [10/Mar/2017:08:51:49 +0800] "GET / HTTP/2.0" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3026.3 Safari/537.36"`


nginx好像没有捕获到请求方式和协议

测试代码
`<?php
//$host = '127.0.0.1';
//$host = "wiki.swoole.com";
$host = 'xxxx';
//$port = 9501;
$port = 443;
//$ssl = false;
$ssl = true;
$array = array(
    "host" => $host,
    "accept-encoding" => "gzip, deflate",
    'accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'accept-language' => 'zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4,ja;q=0.2',
    'cache-control' => 'max-age=0',
    'user-agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3026.3 Safari/537.36',
);
$list = array();
for($i = 0; $i < 1; $i++) {
    $client = new swoole_http2_client($host , $port, $ssl);

    $client->setHeaders($array);
    //$client->setCookies(array("a" => "1", "b" => "2"));
    $client->get("/", function ($o) use($client) {
        echo "#{$client->sock} hello world 1\n";
        //var_dump($o);
        echo $o->body;
        $client->close();
    });
    $array  = ['111','222'];
    //$client->post("/", $array, function ($o) use($client) {
    //    echo "{$client->sock} hello world 2\n";
    //});

    $client->post("/", $array, function ($o) use($client) {
        var_dump('aaa');
        echo "{$client->sock} hello world 3\n";
        echo $o->body;
        $client->close();
    });
    $list[] = $client;
}
Swoole\Event::wait();
`

**Comment by matyhtf** [comment]
去掉 `$client->close();`

**Comment by qiqizjl** [comment]
试过 还是一样的效果
