### ISSUE TITLE
swoole wss除ie9都正常了

### ISSUE THREAD

**Issue by mienv567** [swoole/swoole-src#1110]
ie9下采用flash结合 但是报这个错误
WARNING	swSSL_accept: bad SSL client[39.xx.102.95:54652].
怎么处理呢
其它浏览器都正常接收发送

**Comment by matyhtf** [comment]
表示客户端连接用的不是SSL，检查是否支持SSL连接

**Comment by mienv567** [comment]
使用的websocketmain 是支持wss的. 你能给个flash嘛支持wss ssl的谢谢

**Comment by matyhtf** [comment]
flash的请自行解决。IE可以使用Comet实现推送的功能
