### ISSUE TITLE
swoole的HTTP服务停止响应

### ISSUE THREAD

**Issue by liupdhc** [swoole/swoole-src#1112]
使用swoole1.9.2版本+github上的hash值（f092787）搭建的HTTP服务，运行一段时间后，master、manager、worker、task进程都在，telnet响应端口也通，但是用http请求去访问服务时就无法连通，重启后过段时间就会出现。。通过strace去看master进程是一直在接受请求，截取了小段日志：
`epoll_wait(249, {{EPOLLIN, {u32=3, u64=4294967299}}}, 4096, 1000) = 1
accept4(3, {sa_family=AF_INET, sin_port=htons(16299), sin_addr=inet_addr("10.10.3.2")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 1615
setsockopt(1615, SOL_TCP, TCP_NODELAY, [1], 4) = 0
epoll_ctl(256, EPOLL_CTL_ADD, 1615, {EPOLLIN, {u32=1615, u64=1615}}) = 0
accept4(3, 0x7ffd75aa5a90, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)`

不清楚是什么原因或者从哪入手去排查。。

**Comment by kimkit** [comment]
你看看是不是 #1030 里面的问题

**Comment by liupdhc** [comment]
非常感谢，我先试一下升级到1.9.6版本看出现的频次。。从回复来看如果前置有nginx可能不会触发此bug

**Comment by matyhtf** [comment]
检查Worker进程处于什么状态，如果所有Worker进程挂住了不处理请求，会出现这种情况。
