### ISSUE TITLE
2.0.6版本Swoole\Serialize不能使用么？

### ISSUE THREAD

**Issue by tiaodeng** [swoole/swoole-src#1135]

**Comment by GXhua** [comment]
目前只集成在1.9 版本  ，你可以单独编译swoole_serialize扩展

**Comment by tiaodeng** [comment]
1.9.6版本Swoole\Serialize能够使用，但是发现sendMessage报错了，升级到了2.0.6发现未找到

**Comment by tiaodeng** [comment]
多谢，swoole_serialize扩展的地址麻烦告知下

**Comment by GXhua** [comment]
sendMessage报错信息 还有代码贴一下  https://github.com/swoole/swoole_serialize

**Comment by tiaodeng** [comment]
多谢提供swoole_serialize地址。
1.9.6报错代码：就是一个简单的 Process::$server->sendMessage($msg,$process_id);
以前用的是1.8.7，此处rpc通信用的是原生的serialize，昨天升级到1.9.6，发现报错，跟踪是到了这个位置。
刚刚又升级到了2.0.6，此处不报错。
详细的报错信息怎么查看？麻烦再告诉一下，谢谢！

**Comment by GXhua** [comment]
麻烦把$msg的具体内容提供下

**Comment by tiaodeng** [comment]
代码:var_dump($msg,$process_id);
        return Process::$server->sendMessage($msg,$process_id);
日志：
string(140) "a:4:{s:4:"type";s:5:"inner";s:6:"module";s:29:"module\timer\RoleTimerProcess";s:6:"method";s:6:"online";s:6:"params";a:2:{i:0;i:1;i:1;i:0;}}"
int(46)
[2017-03-13 11:54:04 $16644.0]  WARNING swManager_check_exit_status: worker#1 abnormal exit, status=0, signal=11

**Comment by GXhua** [comment]
不好意思 我表达错了，是在worker进程onpipMessage的时候  把数据打印下看看

**Comment by tiaodeng** [comment]
$serv->on('pipeMessage', function($serv, $src_worker_id, $message) {
    var_dump($message);
    echo PHP_EOL;
    $data=\core\message\MessageUtil::messageUnPack($message);

onpipMessage里也有打印。问题是现在还没有send成功进程就重启了。
这个是在task中使用的。

**Comment by GXhua** [comment]
已修复 多谢反馈  提交到了master分支

**Comment by tiaodeng** [comment]
客气了 应该的
