### ISSUE TITLE
new \swoole\http\server:Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by loyating** [swoole/swoole-src#1141]
warning: core file may not match specified executable file.
[New LWP 26420]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php ./server'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005651f9781f38 in _object_and_properties_init ()
(gdb) bt
#0  0x00005651f9781f38 in _object_and_properties_init ()
#1  0x00007f91d58d3835 in zim_swoole_server___construct (execute_data=0x7f91d5e13720, return_value=<optimized out>) at /tmp/pear/temp/swoole/swoole_server.c:1375
#2  0x00005651f9804e46 in ?? ()
#3  0x00005651f97bfaab in execute_ex ()
#4  0x00005651f9813fd7 in zend_execute ()
#5  0x00005651f977f593 in zend_execute_scripts ()
#6  0x00005651f971f030 in php_execute_script ()
#7  0x00005651f9815c97 in ?? ()
#8  0x00005651f9602154 in main ()

PHP - 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
swoole - 1.9.6

**Comment by matyhtf** [comment]
请测试一下github master分支的代码

**Comment by loyating** [comment]
好的 今天测试看看

**Comment by loyating** [comment]
更新至  1.9.7-alpha  
没有问题

**Comment by matyhtf** [comment]
OK
