### ISSUE TITLE
onShutdown 回调在Mac下未执行

### ISSUE THREAD

**Issue by wenpeng** [swoole/swoole-src#1150]
```
    public function serverStop()
    {
        $pid = file_get_contents($this->masterPid);
        return posix_kill($pid, SIGTERM);
    }
```
```
    public function onShutdown($server)
    {
        try {
            if (is_file($this->masterPid)) {
                echo unlink($this->masterPid) ? '删除成功' : '删除失败';
            } 
        }  catch (Error $e) {
            Console::echo($e->getTraceAsString(), '主程停止 [错误]:');
        } catch (Exception $e) {
            Console::echo($e->getTraceAsString(), '主程停止 [异常]:');
        }
    }
```
控制台无任何输出：
```
NOTICE	Server is shutdown now.
```

Debian, Centos 下实测无此问题

**Comment by wenpeng** [comment]
使用pecl 安装，版本：1.9.8

**Comment by wenpeng** [comment]
php 5.6.30  7.0.* 7.1.* 均测试不通过

**Comment by kimkit** [comment]
can you give me a simple test case ? the complete code. so I can try in my machine.
in your `onShutdown` function, please print something before `try {`, maybe the `masterPid` file not exist.

**Comment by wenpeng** [comment]
I have created a new repo include the above code, you can clone and test it.
https://github.com/wenpeng/swoole-test

**Comment by yunnian** [comment]
我多次测试下，mac下SIGTERM多次才会被kill掉，同事shutdown也会被执行，SIGTERM信号比较友好,假如进程正在进行作业而且不能中断，那么进程可以忽略这个SIGTERM信号

**Comment by matyhtf** [comment]
已修复。https://github.com/swoole/swoole-src/commit/81d48a6106e00542dbdc6c3c8ee0380fcdd0f7d7
