### ISSUE TITLE
php7.1，swoole2.0.5，centOS7使用HTTP协程并没有达到预期效果

### ISSUE THREAD

**Issue by limao777** [swoole/swoole-src#1151]
如果一个请求有多个new Swoole\Coroutine\Http\Client方法，执行时间不是max（请求1，请求2，请求3,...）,而是请求1+请求2+请求3+...

**Comment by andot** [comment]
这是你误会了，本来就是这样。在一个请求中，所有的协程都是顺序执行的，并不是并发执行的。不同请求之间才是并发执行的。

**Comment by matyhtf** [comment]
同一个协程内的代码是串行的。
