### ISSUE TITLE
建议 `Swoole\Table->get($key)` 方法增加一个 `$field` 字段

### ISSUE THREAD

**Issue by breath-co2** [swoole/swoole-src#1154]
现在 Swoole\Table->get($key) 方法只能获取完整的内容，希望能够增加一个 $field 字段，如果不传，则和原来一样返回，如果增加一个字段，则只返回当前字段内容

另外，是否可以考虑增加一个不加锁读取的方法？在写少读多的场景下对性能的提升还是非常有帮助的。

**Comment by matyhtf** [comment]
不加锁方法不安全，会读出脏数据

**Comment by breath-co2** [comment]
@matyhtf 是的，但是为此牺牲性能感觉有些不划算，不知读取频繁但更新较少的场景有什么更好的解决方案？比如服务器的一些配置信息、系统开关状态等等。
