### ISSUE TITLE
希望 Swoole\Table 能增加一个无符号类型的INT和 FLOAT 类型

### ISSUE THREAD

**Issue by breath-co2** [swoole/swoole-src#1159]
rt

**Comment by matyhtf** [comment]
没意义。无符号只是多一位存储。

**Comment by breath-co2** [comment]
有意义呀，我现在就碰到一个数字是40亿左右的（对应mysql里 int(10) 无符号的），在有符号情况下就存不下，结果现在只能用 8字节的 INT 类型来存储了，多占很多内存不说，一不小心还会碰到溢出（说实话，项目中基本上都是无符号的类型）

**Comment by matyhtf** [comment]
超过21亿那就用8字节整型存。

**Comment by breath-co2** [comment]
是的，现在就只能用8字节的了，如果不是很复杂建议还是支持一下，您可能用不上，但是也许有人能用到，特别是数据库里用的 int(10) 无符号而在 swoole_table 里用的却是 8 字节的看着也别扭

**Comment by patrickkh7788** [comment]
@breath-co2 看看是否可以在php层面做类型转换。
