### ISSUE TITLE
Swoole\Client 连接错误提示

### ISSUE THREAD

**Issue by breath-co2** [swoole/swoole-src#1163]
往一个不存在的端口上连（同步，tcp），第一次会提示
PHP Warning:  Swoole\Client::connect(): connect to server[10.211.55.2:13100] failed. Error: Connection refused[111].

再连则会提示：PHP Warning:  Swoole\Client::connect(): The client is already connected server. 但实际返回的仍旧是 false

如果执行 close() 方法还会报 PHP Warning:  Swoole\Client::connect(): The client is already connected server. 错误

php7.1.3, swoole 2.0.7, centos

**Comment by sylingd** [comment]
官方文档有相关说明https://wiki.swoole.com/wiki/page/30.html

**Comment by breath-co2** [comment]
好吧，谢谢。。。不过感觉这样的逻辑有点反人类
