### ISSUE TITLE
v1.9.8使用队列时设置message_queue_key无效

### ISSUE THREAD

**Issue by danbus** [swoole/swoole-src#1165]
发现问题的版本为1.9.8, 重新编译安装1.8.10正常
执行`php --ri swoole`发现缺少`swoole.message_queue_key => 0 => 0`

    ------ Message Queues --------
    key        msqid      owner      perms      used-bytes   messages   
    0x00000000 294912     root       666        730438       4844       
    0x00000000 327681     root       666        1823079      12066      
    0x00000000 360450     root       666        9115187      60040      
    0x00000000 393219     root       666        0            0          
    0x00000000 425988     root       666        0            0          
    0x00000000 458757     root       666        0            0          
    0x00000000 557062     root       666        0            0          
    0x00000000 589831     root       666        0            0          
    0x00000000 622600     root       666        0            0          
    0x00000000 655369     root       666        0            0          
    0x00000000 688138     root       666        0            0          
    0x00000000 720907     root       666        0            0          
    0x00000000 753676     root       666        0            0          
    0x00000000 786445     root       666        0            0          
    0x00000000 917518     root       666        0            0          
    0x00000000 950287     root       666        0            0          
    0x00000000 983056     root       666        0            0          
    0x00000000 1048594    root       666        0            0          
    0x00000000 1081363    root       666        0            0          
    0x00000000 1114132    root       666        0            0

**Comment by danbus** [comment]
是被移除了吗?

**Comment by matyhtf** [comment]
对，已经移除。请设置 server->set 参数数组。

**Comment by danbus** [comment]
不管是新版还是老版本(1.9.8和1.8.10) message_queue_key 设置的值都无效, 都是由程序自动生成,新版设置的值都为`0x00000000` , 运行多个实例时,只能由 msqid 进行区分, 重启后还是可以继续消费(前提不是ctrl+c结束),   遇到问题的朋友请注意
