### ISSUE TITLE
print  *COROG.current_coro Cannot access memory at address 0x7f00c8a81030

### ISSUE THREAD

**Issue by kilmas** [swoole/swoole-src#1168]
ab -n 1000 -c 200 http://127.0.0.1:9301/

php demo:

```
<?php
$pool = new SplQueue();
$server = new Swoole\Http\Server('127.0.0.1', 9301);
$server->set([
    'worker_num' => 1
]);

class test
{

    public static $instance;
    public $count;
}

$server->on('WorkerStart', function ($serv, $workerId) {
    $test = new test();
    $test->count = 0;
    test::$instance = $test;
});
$server->on('Request', function ($request, $response) use($pool) {
    if (count($pool) == 0) {
        if (test::$instance->count > 20) {
            $response->end("swoole coro over");
            return;
        } else {
            test::$instance->count ++;
            $client = new Swoole\Coroutine\MySQL();
            $result = $client->connect([
                'host' => '127.0.0.1',
                'port' => 3306,
                'user' => 'root',
                'password' => '123456',
                'charset' => 'utf8',
                'database' => 'dba'
            ]);
            if ($result == false) {
                test::$instance->count --;
                $response->end("mysql connect fail!");
                return;
            }
            $pool->push($client);
        }
    }
    
    $client = $pool->pop();
    $result = $client->query('select * from t limit 1');
    $pool->push($client);
    $response->end("swoole response is ok");
});

$server->start();
```

**gdb php core-php-31717**

#0  0x00007f00d81b52da in coro_close () at /app/swoole-src/swoole_coroutine.c:332
#1  sw_coro_resume (sw_current_context=0x7f00d9681700, retval=0x7f00d9661290, 
    coro_retval=<optimized out>) at /app/swoole-src/swoole_coroutine.c:480
#2  0x00007f00d81d4dea in swoole_mysql_coro_onRead (reactor=0x7f00d9661290, 
    event=0x7fff928fe980) at /app/swoole-src/swoole_mysql_coro.c:933
#3  0x00007f00d820b47c in swReactorEpoll_wait (reactor=0x55f7accad910, timeo=0x2b)
    at /app/swoole-src/src/reactor/ReactorEpoll.c:260
#4  0x00007f00d821b6b7 in swWorker_loop (factory=factory@entry=0x55f7acc79720, 
    worker_id=worker_id@entry=0) at /app/swoole-src/src/network/Worker.c:518
#5  0x00007f00d821877a in swManager_spawn_worker (factory=0x55f7acc79720, worker_id=0)
    at /app/swoole-src/src/network/Manager.c:644
#6  0x00007f00d8218ccf in swManager_start (factory=0x55f7acc79720)
    at /app/swoole-src/src/network/Manager.c:133
#7  0x00007f00d82080f1 in swFactoryProcess_start (factory=0x55f7acc79720)
    at /app/swoole-src/src/factory/FactoryProcess.c:86
#8  0x00007f00d820edfb in swServer_start (serv=0x55f7acc792f0)
    at /app/swoole-src/src/network/Server.c:701
#9  0x00007f00d81c3811 in zim_swoole_http_server_start (execute_data=0x7f00d9613190, 
    return_value=0x7fff928feb80) at /app/swoole-src/swoole_http_server.c:1548
#10 0x000055f7abb6b530 in ?? ()
#11 0x000055f7abb1187b in execute_ex ()
---Type <return> to continue, or q <return> to quit---
#12 0x000055f7abb6d520 in zend_execute ()
#13 0x000055f7abac8643 in zend_execute_scripts ()
#14 0x000055f7aba659c0 in php_execute_script ()
#15 0x000055f7abb6f756 in ?? ()
#16 0x000055f7ab75bfff in ?? ()
#17 0x00007f00dce30b45 in __libc_start_main (main=0x55f7ab75bb80, argc=3, 
    argv=0x7fff92902598, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fff92902588) at libc-start.c:287
#18 0x000055f7ab75c12d in _start ()

**print COROG**             
$1 = {uid = "58e4c8d1ec89a4.30179", coro_num = 11, max_coro_num = 3000, 
  origin_vm_stack = 0x7f00d9613000, origin_vm_stack_top = 0x7f00d96131e0, 
  origin_vm_stack_end = 0x7f00d9653000, allocated_return_value_ptr = 0x7f00d9661220, 
  origin_ex = 0x7f00d9613190, current_coro = 0x7f00c8a81030, require = 1 '\001'}

**print  *COROG.current_coro**
Cannot access memory at address 0x7f00c8a81030

**docker images**
php:7.1.0

**php --ri swoole**

swoole support => enabled
Version => 2.0.7
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

php -v
PHP 7.1.0 (cli) (built: Jan 17 2017 19:16:55) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10)

**uname -a**
Linux d10edfe4f6e3 4.4.47-boot2docker #1 SMP Tue Feb 7 18:40:48 UTC 2017 x86_64 GNU/Linux

**Comment by xyzhu1120** [comment]
试一下2.0分支的最新代码吧

**Comment by kilmas** [comment]
ok
