### ISSUE TITLE
1.9.8在并发下线程池模拟异步IO的DNS查询与swoole_timer_tick冲突

### ISSUE THREAD

**Issue by pinguo-xudianyang** [swoole/swoole-src#1170]
异步IO设置

```
        //设置异步IO模式
        swoole_async_set([
            'thread_num' =>  4,
            'aio_mode' => SWOOLE_AIO_BASE,
            'use_async_resolver' => false,
        ]);
```

```
        swoole_timer_tick(1000, function ($timerId) {
            // 遍历所有的http client请求，进行超时处理逻辑
        });
```
在ab -n 100 -c 10 -k http://xxx 无报错
在ab -n 100 -c 60 -k http://xxx 有10%左右的请求报错

报错信息大致是说http请求超时，如下：

```
client => swoole_http_client(errCode => 111, sock => 483, host => '127.0.3.159',...
```
errCode =111，表示拒绝连接，其中host为127.0.x.x，代表本地，说明dns解析出了问题。

当然我解决了

方法一：不检查http client请求是否超时，如果一个第三方服务出现故障会拖垮自己的服务（内存不断耗尽）

方法二：将master分支中的src/networker/DNS.c放到1.9.8里面重新编译，将use_async_resolver设置true，不使用线程池模拟的异步 IO，通过ab在高并发压测，没有出现请求处理。故我怀疑（没有追踪更多代码）**1.9.8在并发下线程池模拟异步IO的DNS查询与swoole_timer_tick冲突**

当然我采用了方法二，请韩少确认是否有这样的bug？

**Comment by matyhtf** [comment]
已修复 https://github.com/swoole/swoole-src/commit/8b128ed1fe9f1249c00cc4a0fbe82a6c7f4441dd
