### ISSUE TITLE
Phar包更新后，reload错误

### ISSUE THREAD

**Issue by zszyue** [swoole/swoole-src#1172]
将项目打成phar包， 在热更新的时候出现问题，测试：

```php
//bin.php:

$http = new swoole_http_server("0.0.0.0", 9502, SWOOLE_PROCESS);
$http->set(array(
    'worker_num' => 1,
    'daemonize' => 0,
    'package_max_length' => 1024*1024*10,
));

$http->on('start', function(swoole_server $server){

});

$http->on('workerStart', function($server,$workerId) {
    include __DIR__.'/T.php';
    include __DIR__.'/C.php';
    echo "worker start..".PHP_EOL;
});

$http->on('workerStop', function($server,$workerId) {
    print_r(get_included_files());
    echo "worker stop..".PHP_EOL;
    C::get();
});

$http->on('request', function ($request, $response) {
    $response->end('ok');
});

$http->start();


//T.php
class T
{
    public static function get()
    {
    }
}

//C.php
class C
{
    public static function get()
    {
    }
}

```

如果我更新了phar包，再去reload 的时候报错

PHP Parse error:  syntax error, unexpected 'func' (T_STRING), expecting variable (T_VARIABLE) in phar:///home/pro/sbin/test.phar/T.php on line 14
[2017-04-10 11:46:51 $8321.0]	NOTICE	Server is reloading now.
Array
(
    [0] => /home/pro/sbin/test.phar
    [1] => phar:///home/pro/sbin/test.phar/bin.php
)
worker stop..
PHP Fatal error:  Uncaught Error: Class 'C' not found in phar:///home/pro/sbin/test.phar/bin.php:26
Stack trace:
#0 [internal function]: {closure}(Object(swoole_http_server), 0)
#1 phar:///home/pro/sbin/test.phar/bin.php(34): swoole_http_server->start()
#2 /home/pro/sbin/test.phar(3): require('phar:///home/dd...')
#3 {main}
  thrown in phar:///home/pro/sbin/test.phar/bin.php on line 26

**Comment by matyhtf** [comment]
你的PHP代码存在错误。

**Comment by zszyue** [comment]
我简化一下测试，两个文件

centos 7.1
php 7.0.10
swoole 1.9.8

**bin.php**
```php
$http = new swoole_http_server("0.0.0.0", 9502, SWOOLE_PROCESS);
$http->set(['worker_num' => 1]);
$http->on('start', function(swoole_server $server){});
$http->on('workerStart', function($server,$workerId) {
    include __DIR__.'/C.php';
    echo "worker start..".PHP_EOL;
});
$http->on('workerStop', function($server,$workerId) {
    echo "worker stop..".PHP_EOL;
    C::get();
});
$http->on('request', function ($request, $response) {
    $response->end('ok');
});
$http->start();
```

**C.php**
```php
class C
{
    public static function get()
    {
    }
}
``` 

正常执行 `php bin.php` ，然后kill -10 进程多次，是没有问题的，如果打包成phar执行，然后在更新phar文件，再去kill -10进程，第一次没有报错，但是有异常，再次reload会报错


我这里生成的phar文件，test.phar是第一次生成，test.update.phar是更新后的文件
[Uploading test.phar.zip…]()
