### ISSUE TITLE
swoole_http_request POST [data] missing

### ISSUE THREAD

**Issue by mudassarkhan** [swoole/swoole-src#1177]
Recent update has broken POST data. 
swoole_http_request no longer see's POST Data

Before:
swoole_http_request Object
(
    [fd] => 24
    [header] => Array
        (
            [host] => xxxxxx
            [accept] => */*
            [content-type] => application/json
            [content-length] => 53
        )

    [server] => Array
        (
            [request_method] => POST
            [request_uri] => /
            [path_info] => /
            [request_time] => 1492008560
            [request_time_float] => 1492008560.1102
            [server_port] => 8080
            [remote_port] => 47712
            [remote_addr] => xxxxxxx
            [server_protocol] => HTTP/1.1
            [server_software] => swoole-http-server
        )

    [data] => POST / HTTP/1.1
Host: xxxxx:8080
Accept: */*
Content-Type: application/json
Content-Length: 53

{"0":["GETSERVERCPU","nodata"],"LOGIN":"USER"}
)

After:
swoole_http_request Object
(
    [fd] => 24
    [header] => Array
        (
            [host] => xxxxxx
            [accept] => */*
            [content-type] => application/json
            [content-length] => 0
        )

    [server] => Array
        (
            [request_method] => POST
            [request_uri] => /
            [path_info] => /
            [request_time] => 1492008560
            [request_time_float] => 1492008560.1102
            [server_port] => 8080
            [remote_port] => 47712
            [remote_addr] => xxxxxxx
            [server_protocol] => HTTP/1.1
            [server_software] => swoole-http-server
        )
)

**Comment by kimkit** [comment]
what's your swoole version ?
I test the latest code of master, it's OK.

```
object(swoole_http_request)#8 (5) {
  ["fd"]=>
  int(2)
  ["header"]=>
  array(5) {
    ["host"]=>
    string(14) "localhost:8000"
    ["user-agent"]=>
    string(11) "curl/7.47.0"
    ["accept"]=>
    string(3) "*/*"
    ["content-length"]=>
    string(1) "7"
    ["content-type"]=>
    string(33) "application/x-www-form-urlencoded"
  }
  ["server"]=>
  array(10) {
    ["request_method"]=>
    string(4) "POST"
    ["request_uri"]=>
    string(1) "/"
    ["path_info"]=>
    string(1) "/"
    ["request_time"]=>
    int(1492040037)
    ["request_time_float"]=>
    float(1492040037.2994)
    ["server_port"]=>
    int(8000)
    ["remote_port"]=>
    int(45112)
    ["remote_addr"]=>
    string(9) "127.0.0.1"
    ["server_protocol"]=>
    string(8) "HTTP/1.1"
    ["server_software"]=>
    string(18) "swoole-http-server"
  }
  ["post"]=>
  array(2) {
    ["a"]=>
    string(1) "1"
    ["b"]=>
    string(1) "2"
  }
  ["data"]=>
  string(154) "POST / HTTP/1.1
Host: localhost:8000
User-Agent: curl/7.47.0
Accept: */*
Content-Length: 7
Content-Type: application/x-www-form-urlencoded

a=1&b=2"
}
```

**Comment by matyhtf** [comment]
Only the "application/x-www-form-urlencoded" type request can be parsed.

You can parse it like this.

```php
$data = json_decode($request->rawContent());
```

**Comment by mudassarkhan** [comment]
before you could parse it from any type of request not just application/x-www-form-urlencoded 
(2 months ago but i'll need to confirm which version I have)
Why has this changed? Shouldn't it be able to accept for any content type?
