### ISSUE TITLE
Http request is end. 连接没有断开但是数据发送失败。

### ISSUE THREAD

**Issue by alexmango** [swoole/swoole-src#1178]
运行环境是这样的：
前端 nginx 反向代理到 swoole，nginx 与 swoole 之间保持长连接。

业务代码简化如下：
```php
//接收到 http 请求时的回调
$httpServer->on('request', function ($request, $response)use($httpServer) {
    //异步发送到其他服务器
    MyClient::sendAsync('{data:"6364132221823510359"}', function($jsonStr)use($request, $response,$httpServer) {
        $info=$httpServer->connection_info($response->fd);
        if($info)
        {
            $response->write($jsonStr)
            $response->end();
        }    
    });
});
```

查日志发现总是报错：swoole_http_response::write(): Http request is end. 或者 swoole_http_response::end(): Http request is end.
但是使用 swoole_server->connection_info($response->fd); 能获取到连接信息，这应该说明连接没有断开？另外在服务器上使用tcpdump抓到也发现连接确实没有断开。

不清楚这是 swoole 的bug，还是我使用 swoole 的方式不对？

**Comment by kimkit** [comment]
please provide `MyClient::sendAsync` method code.

**Comment by alexmango** [comment]
MyClient::sendAsync 是我这边自己封装的一个 tcp 客户端，send 一个数据包以后，接收到其他服务器的响应，就会回调sendAsync第二个函数参数。

**Comment by matyhtf** [comment]
http end 是已经发送过 http response 了
