### ISSUE TITLE
swoole 1.8.6       php 5.6.25  gc coredump

### ISSUE THREAD

**Issue by reynaldliu** [swoole/swoole-src#1188]
swoole debug log 

[2017-04-16 21:26:24 $17684.0]  WARNING swManager_check_exit_status: worker#28 abnormal exit, status=0, signal=11

gdb bt info:

#0  0x0000000000850de9 in gc_zval_possible_root (zv=0x366b8c8) at /data/tmp/update_php/php-5.6.25/Zend/zend_gc.c:143
#1  0x0000000000857072 in zend_objects_destroy_object (object=0x7fab5510d660, handle=<value optimized out>)
    at /data/tmp/update_php/php-5.6.25/Zend/zend_objects.c:131
#2  0x000000000085ca26 in zend_objects_store_call_destructors (objects=0x14ce640)
    at /data/tmp/update_php/php-5.6.25/Zend/zend_objects_API.c:57
#3  0x00000000008237dd in shutdown_destructors () at /data/tmp/update_php/php-5.6.25/Zend/zend_execute_API.c:216
#4  0x0000000000830a14 in zend_call_destructors () at /data/tmp/update_php/php-5.6.25/Zend/zend.c:944
#5  0x00000000007cf8d5 in php_request_shutdown (dummy=<value optimized out>) at /data/tmp/update_php/php-5.6.25/main/main.c:1840
#6  0x00000000008d587f in do_cli (argc=2, argv=0x1e56ae0) at /data/tmp/update_php/php-5.6.25/sapi/cli/php_cli.c:1177
#7  0x00000000008d6cf8 in main (argc=2, argv=0x1e56ae0) at /data/tmp/update_php/php-5.6.25/sapi/cli/php_cli.c:1378

**Comment by matyhtf** [comment]
请升级至 1.9.9 版本。
