### ISSUE TITLE
ERROR	swReactorEpoll_wait(:263): EPOLLIN handle failed. fd=9. Error: No such file or directory[2].

### ISSUE THREAD

**Issue by envomer** [swoole/swoole-src#1191]
I am having the following issue that appears after i open a socket and connect to it.
```
ERROR	swReactorEpoll_wait(:263): EPOLLIN handle failed. fd=9. Error: No such file or directory[2].
```

This only happens when i change the mode to SWOOLE_PROCESS. When the mode SWOOLE_BASE is used, then no error shows up.

My current code looks like this:
```php
$socketServer = new swoole_server("0.0.0.0", 9501, SWOOLE_PROCESS, SWOOLE_SOCK_TCP | SWOOLE_SSL);
$socketServer->set(array(
        'ssl_cert_file' => $config->sslCertFile ?: null,
        'ssl_key_file' => $config->sslKeyFile ?: null,
));

// some listeners
$socketServer->start();
```
The ssl certificate files exist and work.

Installed the swoole server using this snippet:
```
sudo apt-get install php5-dev
git clone https://github.com/swoole/swoole-src.git
cd swoole-src
phpize
./configure --enable-sockets --enable-openssl
sudo make && sudo make install
```
![screenshot 2017-04-19 at 13 26 42](https://cloud.githubusercontent.com/assets/5601749/25178906/08240996-2508-11e7-886b-9186ca1289c8.png)

Running on debian:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.5 (jessie)
Release:	8.5
Codename:	jessie
```

PHP version
```
PHP 5.6.29-0+deb8u1 (cli) (built: Dec 13 2016 16:02:08)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

Any help is appreciated.

**Comment by WenRuige** [comment]
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
使用swoole websocket 在连接(onopen)的时候报错
本地无错误,上到阿里云服务器就出错了
ERROR	swReactorEpoll_wait(:263): EPOLLIN handle failed. fd=5. Error: Success[0].

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/c35b0bc6e06ae5ed7056511d22f90aa851469c04

fixed.
