### ISSUE TITLE
Calling swoole_server->finish in onPipeMessage callback may causes segmentation fault.

### ISSUE THREAD

**Issue by AJSoft** [swoole/swoole-src#1198]
If swoole_server->finish is called in onPipeMessage callback, and the source process is a task worker, segfault may occurred.

问题描述：
Task进程A使用sendMessage向Task进程B发送消息;
在Task进程B的onPipeMessage回调中，如果使用了swoole_server->finish() （误用），会导致进程B崩溃，并且可能导致进程A死锁。

故障分析：
```
/src/network/TaskWorker.c
    int swTaskWorker_finish(swServer *serv, char *data, int data_len, int flags)
        ...
        /**
         * Use worker shm store the result
         */
        swEventData *result = &(SwooleG.task_result[source_worker_id]);
        ...
        result->info.type = SW_EVENT_FINISH;
```
source_worker_id对于数组task_result下标越界，对result->info.type的写入将引发segfault. 同时导致worker->lock未释放。

附上PR： #1199

**Comment by matyhtf** [comment]
merged, fixed.
