### ISSUE TITLE
swoole_http_client 调用post后如果其匿名回调函数不能执行会造成使用use引用传入的变量实例不能释放

### ISSUE THREAD

**Issue by eoqstub** [swoole/swoole-src#1215]
调用swoole_http_client post函数时候使用use将变量实例引用传入其匿名回调函数，由于某些原因（例如，ip 地址设置错误）post的匿名回调函数不能执行，致使use传入的变量实例引用不能清除，从而造成该变量实例不能被GC释放。

**Comment by matyhtf** [comment]
设置一个定时器，关闭超时的HttpClient，内存会自动释放。

**Comment by eoqstub** [comment]
无语，这是swoole的架构缺陷吧！

**Comment by matyhtf** [comment]
1.9.11 会支持 异步客户端连接超时检测。

**Comment by eoqstub** [comment]
谢谢，希望在新的一版可以解决这个问题，这个问题对我现在的实现造成不小的困扰。这个问题表面看来不会影响业务流程，只是内存被悄悄地被泄露了。如果不是我的代码一定会使用到PHP类的destruct函数，还不好发现这个问题。

另外我觉得这问题的解决不必等待客户端超时检测触发，其实在我的代码中调用post后都会直接触发onclose事件，是否可以在onclose或onerror事件触发时候检查post的callback是否有被执行，如果没有执行就释放掉post的callback中对use传入变量的引用呢？
