### ISSUE TITLE
TCP server执行 一直报check 之前运行没有问题

### ISSUE THREAD

**Issue by RandalTeng** [swoole/swoole-src#1221]
在本地虚拟机执行也没有报错，在公司测试服务器报错无法连接
`
[root@localhost test]# php ChipPro.php
[/usr/local/src/swoole-src-1.9.9/swoole_server.c:361@php_swoole_server_before_start]Create swoole_server host=0.0.0.0, port=6000, mode=3, type=1
[/usr/local/src/swoole-src-1.9.9/src/network/Server.c:359@swServer_start_proxy]hb timer start, time: 120 live time:600
[/usr/local/src/swoole-src-1.9.9/src/network/Server.c:1487@swHeartbeatThread_loop]check fd=3
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/network/Server.c:1487@swHeartbeatThread_loop]check fd=3
`
连接时报错
`
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/memory/ShareMemory.c:66@sw_shm_free]check:
[/usr/local/src/swoole-src-1.9.9/src/network/Server.c:1487@swHeartbeatThread_loop]check fd=3
[/usr/local/src/swoole-src-1.9.9/src/network/Server.c:1487@swHeartbeatThread_loop]check fd=3
[/usr/local/src/swoole-src-1.9.9/src/network/Server.c:145@swServer_master_onAccept][Master] Accept new connection. maxfd=3|reactor_id=4|conn=26
Segmentation fault (core dumped)
`

我代码应该没有问题- -  本地运行成功，对了  本地环境是php7 swoole 2.0.6
测试服务器当前版本php5.6 swoole 1.9.9  之前2.0.5不能用才换的1.9.9

**Comment by matyhtf** [comment]
请勿开启 `--enable-swoole-debug` 编译选项

**Comment by RandalTeng** [comment]
没有用啊- -  我重新编译了swoole模块- -  还是报一样的错- -
`
./configure --enable-async-redis --enable-coroutine --with-php-config=/usr/local/php5/bin/php-config  --enable-openssl  --enable-sockets  --enable-swoole
`

**Comment by nick-william** [comment]
make clean过？

**Comment by RandalTeng** [comment]
- -  好吧- -  没有clean- -   重新make可以了  谢谢大佬~~
