### ISSUE TITLE
sw_zval_ptr_dtor(&zrequest_object); 会core

### ISSUE THREAD

**Issue by xxyyboy** [swoole/swoole-src#1231]
同样的错误。
PHP 7.0.14，Swoole 1.9.2 还是出错，会core掉。
gdb的信息 跟上面的，一模一样。

sw_zval_ptr_dtor(&zrequest_object); 会core

**Comment by xxyyboy** [comment]
(gdb) 
1389	                swWarn("Unknown\n");
(gdb) 
1394	            sw_zval_ptr_dtor(&zrequest_object);
(gdb) print &zrequest_object
Address requested for identifier "zrequest_object" which is in register $r14
(gdb) print zrequest_object
$8 = (zval *) 0x7fcf4b570098
(gdb) print *zrequest_object
$9 = {value = {lval = 3565779415536200054, dval = 2.5530952370684926e-70, counted = 0x317c317c726f6976, str = 0x317c317c726f6976, arr = 0x317c317c726f6976, obj = 0x317c317c726f6976, res = 
    0x317c317c726f6976, ref = 0x317c317c726f6976, ast = 0x317c317c726f6976, zv = 0x317c317c726f6976, ptr = 0x317c317c726f6976, ce = 0x317c317c726f6976, func = 0x317c317c726f6976, ww = {w1 = 
    1919904118, w2 = 830222716}}, u1 = {v = {type = 124 '|', type_flags = 124 '|', const_flags = 124 '|', reserved = 124 '|'}, type_info = 2088533116}, u2 = {next = 876032380, cache_slot = 
    876032380, lineno = 876032380, num_args = 876032380, fe_pos = 876032380, fe_iter_idx = 876032380, access_flags = 876032380, property_guard = 876032380, extra = 876032380}}
(gdb) n




Breakpoint 2, http_onReceive (serv=0x27f0c50, req=0x7fffec9da4a0) at /root/swoole-src-2.0.2-alpha/swoole_http_server.c:1394
1394	            sw_zval_ptr_dtor(&zrequest_object);
(gdb) print *zrequest_object
$1 = {value = {lval = -4294967290, dval = -nan(0xfffff00000006), counted = 0xffffffff00000006, str = 0xffffffff00000006, arr = 0xffffffff00000006, obj = 0xffffffff00000006, res = 
    0xffffffff00000006, ref = 0xffffffff00000006, ast = 0xffffffff00000006, zv = 0xffffffff00000006, ptr = 0xffffffff00000006, ce = 0xffffffff00000006, func = 0xffffffff00000006, ww = {w1 = 6, 
      w2 = 4294967295}}, u1 = {v = {type = 224 '\340', type_flags = 98 'b', const_flags = 22 '\026', reserved = 161 '\241'}, type_info = 2702598880}, u2 = {next = 32559, cache_slot = 32559, 
    lineno = 32559, num_args = 32559, fe_pos = 32559, fe_iter_idx = 32559, access_flags = 32559, property_guard = 32559, extra = 32559}}

**Comment by xxyyboy** [comment]
在php7里面 zrequest_object 指向 结构题里面的一个实际的 Zval  _zobject;变量  如果是PHP7的话，这里不需要析构。
sw_zval_ptr_dtor(&zrequest_object);

**Comment by matyhtf** [comment]
sw_zval_ptr_dtor(&zrequest_object); 
这个不是释放 zval，而是对象

**Comment by matyhtf** [comment]
请使用 github 1.9 分支代码进行测试。

**Comment by xxyyboy** [comment]
是对象。 偶看下 github1.9的

**Comment by matyhtf** [comment]
fixed.
