### ISSUE TITLE
task中使用$serv->after出现定时器丢失

### ISSUE THREAD

**Issue by eancc** [swoole/swoole-src#1232]
'task_max_request' > 0时，在task中使用$serv->after(5000,function(){}); 会出现task接收任务达到task_max_request设置值时自动退出，未等待after定时器执行完毕

php 5.3.27
swoole 1.9.3

**Comment by eancc** [comment]
补充复现代码：
$swoole = new swoole_server('0.0.0.0', 9502, SWOOLE_PROCESS, SWOOLE_SOCK_TCP);
$swoole->set(array(
                    'worker_num' => 4,
                    'task_worker_num' => 4,
                    'task_max_request' => 10,
                    'max_request' => 10,
                    'task_ipc_mode' => 2,
));
$swoole->on('WorkerStart', function ($serv, $worker_id) {});

$swoole->on('Task', function ($serv, $task_id, $from_id, $data) {
    $id = $serv->after(5 * 1000, function () {
        echo "do task after" . PHP_EOL;
    });
    echo "add after " . $id . PHP_EOL;
});

$swoole->on('Receive', function ($serv, $fd, $from_id, $data) {
    $task_id = $serv->task($data);
});

$swoole->on('Finish', function ($serv, $task_id, $data) {});
$swoole->start();

**Comment by eancc** [comment]
循环次数要大于task_max_request
$client = new swoole_client(SWOOLE_SOCK_TCP);
$client->connect('127.0.0.1', 9502);
for($i=0;$i<2000;$i++){
    $client->send("timer test");
    echo $client->recv();
}
$client->close();

执行结果：
---------------------------------------------------
do task after
add after 10
add after 10
add after 10
add after 1
add after 1
add after 1
add after 1
add after 2
add after 2
add after 2
add after 2
add after 3
add after 3
add after 3
[2017-06-02 14:19:39 ^3329.4]   ERROR   swMsgQueue_pop(:67): msgrcv(163845, 8192, 5) failed. Error: Interrupted system call[4].
do task after
add after 3
[2017-06-02 14:19:39 ^3330.5]   ERROR   swMsgQueue_pop(:67): msgrcv(163845, 8192, 6) failed. Error: Interrupted system call[4].
do task after
add after 4
[2017-06-02 14:19:40 ^3331.6]   ERROR   swMsgQueue_pop(:67): msgrcv(163845, 8192, 7) failed. Error: Interrupted system call[4].
do task after
add after 4
[2017-06-02 14:19:40 ^3332.7]   ERROR   swMsgQueue_pop(:67): msgrcv(163845, 8192, 8) failed. Error: Interrupted system call[4].
do task after
add after 4
[2017-06-02 14:19:41 ^3329.4]   ERROR   swMsgQueue_pop(:67): msgrcv(163845, 8192, 5) failed. Error: Interrupted system call[4].

**Comment by eancc** [comment]
task_max_request=0时，使用SIGUSR2重启task时仍然存在丢失定时器的情况，有解决方法吗？现在完全不敢用定时器了

**Comment by blusewang** [comment]
task是同步的。定时器是异步。
文档里早就提过，同步代码与异步代码不能混用！

**Comment by blusewang** [comment]
文档在设计时，task用于在tcp连接时临时用于处理广播或远程请求的。
异步的包括定时器任务等集中在worker里处理！
https://wiki.swoole.com/wiki/page/p-server.html
自己去看！

**Comment by eancc** [comment]
@blusewang 你好，测试在onReceive中执行$serv->after，定时器只会执行一次
```
$swoole->on('Task', function ($serv, $task_id, $from_id, $data) {
    /*
    $id = $serv->after(10 * 1000, function () {
        echo "do task after" . PHP_EOL;
    });
     */
    echo "add after " . $id . PHP_EOL;
});

$swoole->on('Receive', function ($serv, $fd, $from_id, $data) {
    $id = $serv->after(10 * 1000, function () {
        echo "do task after" . PHP_EOL;
    });
    $task_id = $serv->task($data);
    $serv->send($fd, "Server:OK");
});
```

**Comment by eancc** [comment]
@blusewang 根据issues反馈和release说明判断作者允许在task进程中使用$serv->after方法，见：
1. #854  
2. 1.8.12-stable  Fixed Timer::after can only be executed once in the task process

@matyhtf 我的建议是，在set中增加一条配置选项task_force_quit => true
当设置为fase时，task退出步骤：
1.停止接收新任务投递
2.检测timer是否存在
3.等待所有timer执行完毕再退出，除非强制kill

**Comment by blusewang** [comment]
试试 https://wiki.swoole.com/wiki/page/239.html

**Comment by eancc** [comment]
@blusewang  感谢，等有空了测试下，貌似新版没有这个方法了，新版怎样使用呢？

**Comment by matyhtf** [comment]
Task退出时会清空所有定时器，如果你的定时器有逻辑，建议在 `onWorkerStop` 回调中进行清理。
