### ISSUE TITLE
交叉编译出现 找不到emmintrin.h  2.0.7版

### ISSUE THREAD

**Issue by scjtqs** [swoole/swoole-src#1234]
我在armhf(debian)下直接编译和
mac虚拟机下的ubuntu里面交叉编译都试了下，都出现了这个问题。
swoole_serialize.c:19:23: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
直接用pecl install swoole也出现这问题。
我在我的vps(centos7)上编译就没这问题啊。。。
请教这问题怎么解决？百度上搜 emmintrin.h基本上没资料。

**Comment by GXhua** [comment]
最新的master分支代码已经兼容这种情况，请升级

**Comment by scjtqs** [comment]
好吧，我在码云上下的就不行，重新在github上下的master就可以。我也是醉了
