### ISSUE TITLE
swoole process里使用不了Swoole\Redis

### ISSUE THREAD

**Issue by blusewang** [swoole/swoole-src#1241]
` (new Redis())->connect($host,$port,'connectOk')`
执行后，没有报错，也不执行`connectOk`回调。

**Comment by blusewang** [comment]
swoole2.0.8
swoole2.0.7
都是这样

**Comment by yangzhu6263736** [comment]
同样发现了。。centos 7 + php7.1+swoole 2.0.7

**Comment by matyhtf** [comment]
已修复。
