### ISSUE TITLE
swoole有计划支持PostgreSQL吗？

### ISSUE THREAD

**Issue by blusewang** [swoole/swoole-src#1243]
虽然php-pgsql可以异步，但代码还是有回调的黑洞。
而一个业务的处理常常需要多条SQL。线性的执行，且配上事务。
有swoole的Coroutine支持是最好的！
否则会比较痛苦。

**Comment by matyhtf** [comment]
暂时支持计划。使用 Swoole 2.0 TCP 协程客户端实现网络层， PHP的C/C++ 扩展解析协议，其他客户端会采用这种模式。不再内置支持。
