### ISSUE TITLE
1.9.13 php_swoole_onTimeout存在core dump

### ISSUE THREAD

**Issue by AJSoft** [swoole/swoole-src#1245]
#0  sw_call_user_function_ex (ymbol_table=0x0, no_separation=0, params=<synthetic pointer>,
    param_count=1, retval_ptr_ptr=<synthetic pointer>, function_name=0x700000001, object_pp=0x0,
    function_table=0x7f7a7ffb6ef0) at /root/swoole-src/php7_wrapper.h:266
#1  php_swoole_onTimeout (timer=<optimized out>, tnode=0x7f7a802b2fe0)
    at /root/swoole-src/swoole_timer.c:169

(gdb)f 1
(gdb) p &cb->data
$4 = (zval **) 0x7f7a56173e78
(gdb) p *0x7f7a56173e78
$6 = 10

**Comment by matyhtf** [comment]
最新的代码已修复了，是 异步客户端超时引起。1.9.14 近期会发布修复。
