### ISSUE TITLE
swoole_timer_tick/swoole_timer_after 平滑重启（kill -USR1 主进程PID）后任务丢失

### ISSUE THREAD

**Issue by danchaofan** [swoole/swoole-src#1246]
swoole_timer_tick/swoole_timer_after 有没有办法保障在平滑重启（kill -USR1 主进程PID）的时候不丢失timer。目前的现象是一定会丢失。

**Comment by matyhtf** [comment]
timer是进程生命周期的，使用reload，子进程退出，自然会销毁定时器。
