### ISSUE TITLE
heartbeat_idle_time && heartbeat_check_interval 组合使用，不生效

### ISSUE THREAD

**Issue by danchaofan** [swoole/swoole-src#1248]
server：swoole_websocket_server
swoole： 2.0.5
问题描述：
'heartbeat_idle_time' => 30,
'heartbeat_check_interval' => 5,

配置如上参数后，不管client端期间是否有包发过来，连接后30秒后一定会断开

**Comment by danchaofan** [comment]
websocket client模拟工具 日志：
服务器 16:46:47
连接已成功建立，正在等待数据...
你 16:46:50
1
服务器 16:46:50
16:46:52 收到收据
你 16:47:02
12
服务器 16:47:02
16:47:05 收到收据
你 16:47:10
12
服务器 16:47:10
16:47:12 收到收据
服务器 16:47:20
和服务器断开连接！

**Comment by matyhtf** [comment]
新版本已修复此问题。

**Comment by danchaofan** [comment]
新版本指的是哪个版本？

**Comment by matyhtf** [comment]
2.0.7 or master 分支

**Comment by danchaofan** [comment]
感谢！
