### ISSUE TITLE
swoole+yaf使用协程客户端,onrequest事件yafapp->dispatcher()后的程序不会执行

### ISSUE THREAD

**Issue by lgang06** [swoole/swoole-src#1250]
swoole: 2.0.7
yaf: 3.0.4
> onrequest代码
>> $httpS2Y = new HttpSwoole2Yaf($request);
            var_dump('--------------------yaf_dispatcher start-------------------------' . "\n");
            $this->_application->getDispatcher()->dispatch($httpS2Y->getYafHttp());
            $this->_setRpcRequestLog('http', microtime(true) - $startTime);
            var_dump("--------------------yaf_dispatcher end-------------------------\n");

> yaf中的处理代码
>> public function yaftestAction()
    {
        $host = 'rpc.10jqka.com.cn';
        $ip = gethostbyname($host);
        $httpclient = new Swoole\Coroutine\Http\Client($ip, 80);
        $httpclient->setHeaders(['Host' => $host]);
        $httpclient->set([ 'timeout' => 1]);
        $httpclient->get('/index/index');
        var_dump($httpclient->body);
        echo "\nthis is yaf action end\n";
    }

> swoole输出的日志
>> [/home/test/swoole-2.0.7/src/network/Server.c:145@swServer_master_onAccept][Master] Accept new connection. maxfd=4|reactor_id=5|conn=25
[/home/test/swoole-2.0.7/src/network/ReactorThread.c:1261@swReactorThread_dispatch]send string package, size=199 bytes.
[/home/test/swoole-2.0.7/src/network/ReactorThread.c:1320@swReactorThread_dispatch]dispatch, type=10|len=199
[/home/test/swoole-2.0.7/swoole_http_server.c:1008@http_onReceive]httpRequest 199 bytes: 
>> ---------------------------------------
>> GET /api/test/yaftest HTTP/1.1
User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Accept: */*
Host:syar1.10jqka.com.cn
 
>> string(66) "--------------------yaf_dispatcher start-------------------------
"
>> [/home/test/swoole-2.0.7/swoole_http_client_coro.c:815@http_client_coro_send_http_request][101]: GET /index/index HTTP/1.1
Connection: keep-alive
Accept-Encoding: gzip
Host: rpc.10jqka.com.cn

>> string(12) "hello world!"

>> this is yaf action end
>> [/home/test/swoole-2.0.7/swoole_coroutine.c:343@coro_close]closing coro and 0 remained. usage size: 1469232. malloc size: 4194304
客户端断开连接后输出
[/home/test/swoole-2.0.7/src/factory/FactoryProcess.c:285@swFactoryProcess_finish][Worker] send: sendn=12|type=4|content=(null)
[/home/test/swoole-2.0.7/src/network/ReactorThread.c:307@swReactorThread_close]Close Event.fd=25|from=0
[/home/test/swoole-2.0.7/src/network/ReactorThread.c:350@swReactorThread_close]set_maxfd=24|close_fd=25

**Comment by GXhua** [comment]
@xyzhu1120

**Comment by smalleyes** [comment]
记得yaf要改源码的，不然dispatcher会越来越大，最后内存泄漏。

**Comment by lgang06** [comment]
@smalleyes  这个有测试过，不过因为实际使用内存增加不多，且有设置max_request值，所以个人感觉这个影响不大。

**Comment by matyhtf** [comment]
调用 $response->end 输出结果。
