### ISSUE TITLE
client socket is closed.

### ISSUE THREAD

**Issue by nananjoy** [swoole/swoole-src#1252]
在1.9.14版本下HttpClient回调里$cli->close()报错：swoole_http_client::close(): client socket is closed. 在1.9.10版本下没这个问题。
是说新版本加入了timeout机制，无法手动close？或者说close之前已超时并自动关闭了？
如何在新版本手动close？不调close脚本会额外等待将近5秒才会自动结束，谢谢。

**Comment by matyhtf** [comment]
timeout 设置为 -1 试试。

**Comment by nananjoy** [comment]
那样的话，是不是就没有超时时间啦？timeout我设置的是2，这个还是需要的，最多等待2秒，超时就返回。

**Comment by matyhtf** [comment]
现在的超时机制可能还存在一些问题，正在确认中。

**Comment by nananjoy** [comment]
还有个问题，回调已经完成，为啥脚本没有及时结束？
手动close会及时关闭，swoole在一个一个关闭资源？

**Comment by matyhtf** [comment]
请使用 1.9.15 最新版本
