### ISSUE TITLE
addProcess 可否返回进程编号

### ISSUE THREAD

**Issue by jasonhe88** [swoole/swoole-src#1255]
当前的返回值是BOOL, 希望能返回进程编号(etc, work_num+task_worker_num+<n>) ，更加方便

**Comment by matyhtf** [comment]
在 `addProcess` 时 可能并未调用 `set` ，因此无法得到 `worker_num` 和 `task_worker_num` 的值。这并不需要底层实现，你可以在应用层设置一个 `$process->id` 属性
