### ISSUE TITLE
Data not received many time in 1.9.14

### ISSUE THREAD

**Issue by nullcall** [swoole/swoole-src#1259]
hi Team,
Many time i have not received any data from socket. Only connect and closed messages ...
Kindly help in this.

Terminal Output when :
Client:Connect.
Client:Connect.
Client:Connect.
Client: Close.
Client: Close.
Client: Close.

**Comment by matyhtf** [comment]
Paste your code.

**Comment by nullcall** [comment]
<?php

$serv = new swoole_server("0.0.0.0", 9129);

$serv->set(array(
    'worker_num' => 2,
    'daemonize' => false,
));

$serv->on('connect', function ($serv, $fd){
    echo "Client:Connect.\n";
});


$serv->on('receive', function ($serv, $fd, $from_id, $data) {
        echo $data;

        $udp_client = $serv->connection_info($fd, $from_id);
        print_r($udp_client);

    $serv->close($fd);
});

$serv->on('close', function ($serv, $fd) {
    echo "Client: Close.\n";
});

$serv->start();

**Comment by nullcall** [comment]
sometime data come but sometime not.plz find other output :
Client:Connect.
Client: Close.
Client:Connect.
Client: Close.
Client:Connect.
 ATL868004022707841,$GPRMC,0,1.1ATLOArray
(
    [server_port] => 9129
    [server_fd] => 3
    [socket_type] => 1
    [remote_port] => 45113
    [remote_ip] => 
    [reactor_id] => 0
    [connect_time] => 1498726459
    [last_time] => 1498726461
    [close_errno] => 0
)
\n ----------948Client: Close.
Client:Connect.
Client: Close.

**Comment by matyhtf** [comment]
Can not reproduce your problem.

**Comment by nullcall** [comment]
Hi Tain,

Thanx dfor support, but this I have not also revised the same again. 

 

Tx.
