### ISSUE TITLE
ERROR	swReactorKqueue_wait(:332): kqueue event read socket#6 handler failed. Error: Invalid argument[22]

### ISSUE THREAD

**Issue by wutiyang** [swoole/swoole-src#1260]
swoole：2.0.7
mac 10.10.5
php 7.1
报错：ERROR	swReactorKqueue_wait(:332): kqueue event read socket#6 handler failed. Error: Invalid argument[22]

**Comment by matyhtf** [comment]
请使用`2.0.8`或`1.9.18`版本，本地无法重现你的问题。
