### ISSUE TITLE
swoole 1.9.13 版本,swoole_http_server 如果没有进行urlencode,不会响应,不会触发onRequest

### ISSUE THREAD

**Issue by unfazed** [swoole/swoole-src#1262]
curl 'http://127.0.0.1:9051/api?start_time=2017-06-29&end_time=2017-06-29 11:11', 不会响应
curl 'http://127.0.0.1:9051/api?start_time=2017-06-29&end_time=2017-06-29%2011:11'  有响应

**Comment by matyhtf** [comment]
URL路径解析不支持空格，新版本已修复。

**Comment by unfazed** [comment]
@matyhtf  下了新版本（1.9.15) 并没有修复 

swoole
swoole support => enabled
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
swoole.use_namespace => Off => Off
OLDPWD => /home/unfazed/Downloads/swoole-src-1.9.15
_SERVER["OLDPWD"] => /home/unfazed/Downloads/swoole-src-1.9.15
