### ISSUE TITLE
swool redis_server 的bug

### ISSUE THREAD

**Issue by VigoXu** [swoole/swoole-src#1264]
1. redis-server 如果请求的字节数大于 3KB，并且swRedis_recv中swConnection_recv调用大于1次，指针p的值指向了最后一次recv开始位置（buffer->str + buffer->length），而不是buffer->str 开始位置，导致协议解析失败。
2. redis-server 如果请求的字节数大于 8kb，并且连续多次重复请求，会core, realloc(): invalid next size: 0x00007f8a0eb4f610。
3. redis-server 如果请求的字节数大于 136KB，子进程会直接退出。

**Comment by matyhtf** [comment]
感谢反馈，我们会尽快确认此问题。

**Comment by matyhtf** [comment]
已修复。https://github.com/swoole/swoole-src/commit/5482fffa24b13d22f9f1161e8d8f5fe01a6fcccb

**Comment by VigoXu** [comment]
给1万个赞，这么快就修复了
