### ISSUE TITLE
协程mysql客户端

### ISSUE THREAD

**Issue by stelin** [swoole/swoole-src#1270]
最近在项目里使用协程Mysql客户端，有部分业务必须使用事务操作，但是目前没有支持事务，请问下，有后续增加计划么。

**Comment by matyhtf** [comment]
在Swoole\MySQL中执行下列SQL语句可以实现事务处理。

启动事务：START TRANSACTION
提交事务：COMMIT
回滚事务：ROLLBACK

**Comment by stelin** [comment]
明白怎么做了，谢谢峰哥！
