### ISSUE TITLE
\Swoole\Coroutine::call_user_func_array函数调用问题

### ISSUE THREAD

**Issue by stelin** [swoole/swoole-src#1271]
hello,峰哥
     \Swoole\Coroutine::call_user_func_array这个函数我如下使用的时候，不能正常运行，不支持这种调用么，还是不应该有这种使用场景。

```
$data = "some data";
$client = new \Swoole\Coroutine\Client(SWOOLE_SOCK_TCP);
...
\Swoole\Coroutine::call_user_func_array([$client, 'send'], $data);
```

**Comment by xyzhu1120** [comment]
@stelin 提供一下swoole的版本和php的版本吧

**Comment by stelin** [comment]
PHP 7.0.15 (cli) (built: Feb 11 2017 09:29:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies


swoole

swoole support => enabled
Version => 2.0.8
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
jemalloc => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by matyhtf** [comment]
已支持兼容扩展函数的调用。
