### ISSUE TITLE
有没有计划支持orm/active record ?

### ISSUE THREAD

**Issue by coco101000000000** [swoole/swoole-src#1272]
现在swoole没有orm/active record，只支持手写SQL吧，手写对于复杂的多条件查询写起来不友好，手写的SQL有注入风险，是否考虑一下移植phalcon框架里的ORM，或者其他框架的ORM/AR，或者自己开发一个了？

**Comment by matyhtf** [comment]
可以使用 SwooleDistributed 框架。http://docs.sder.xin/mysqlasynpool.html

Swoole 本身专注于实现底层的通信引擎，不会涉及你说的这些方面。
