### ISSUE TITLE
swoole 1.9.15 ,swoole_http_server url路径或query_string 包含空格无响应

### ISSUE THREAD

**Issue by unfazed** [swoole/swoole-src#1274]
swoole 1.9.15
php 5.6.30及 7.1.6

swoole
swoole support => enabled
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
swoole.use_namespace => Off => Off
OLDPWD => /home/unfazed/Downloads/swoole-src-1.9.15
_SERVER["OLDPWD"] => /home/unfazed/Downloads/swoole-src-1.9.15

curl 'http://127.0.0.1:9051/api?start_time=2017-06-29&end_time=2017-06-29 11:11', 不会响应
curl 'http://127.0.0.1:9051/api?start_time=2017-06-29&end_time=2017-06-29%2011:11' 有响应

这个问题之前提过,峰哥说1.9.15已经修复,我下了最新的1.19.15仍是没有解决这个问题
另外尝试过使用原生的php的server,也是不支持url空格或者query_string空格,但会响应invalid request,状态码502
不过作为http server一般作法都是用nginx作反向代理, 所以还是需要支持 url路径或query_string 包含空格

**Comment by matyhtf** [comment]
URL中间不应该出现空格，之前解决的问题是URL末尾多出空格的问题。

**Comment by matyhtf** [comment]
最新代码已增加检测逻辑，发现此类错误，会报 `Bad Request`
