### ISSUE TITLE
swoole编译后运行提示symbol lookup error：undefined symbol: OPENSSL_init_ssl

### ISSUE THREAD

**Issue by benlee7** [swoole/swoole-src#1281]
按照文档说明，phpize后，configure加上enable-openssl参数后，make && make install
然后启动websocket server，提示symbol lookup error：undefined symbol: OPENSSL_init_ssl
机器环境：centos、php7.0.1、swoole 1.9.14

**Comment by matyhtf** [comment]
openssl存在问题，使用`--with-openssl-dir`指定目录
