### ISSUE TITLE
Does your web socket can support ZeroMQ?

### ISSUE THREAD

**Issue by tejastank** [swoole/swoole-src#1282]
Hello,

Looking forward to your great libarary with support of zeromq !

Does it already support zeromq or you plan to add it ?

Thanks,
Tejas Tank
@snippetbucket

**Comment by matyhtf** [comment]
Now will not, the future may be.

**Comment by tejastank** [comment]
Will be great and make Swoole more better ?

**Comment by tejastank** [comment]
Does it merged ?

**Comment by matyhtf** [comment]
No. You can use php zeromq extension, Get zeromq message, then forward to swoole.

**Comment by matyhtf** [comment]
https://github.com/swoole/zmq
I implemented `swoole/zmq` class library and you could use it.

**Comment by tejastank** [comment]
@matyhtf  thanks for sharing it, I will look soon and test it. 
Please if possible share some better example code which make me ready to use in apps
