### ISSUE TITLE
1.9.14版本websocket对象属性connections是null

### ISSUE THREAD

**Issue by loncool** [swoole/swoole-src#1284]
新版 的websockerserver $server->connections  没法获取连接的客户的对象数组。

**Comment by loncool** [comment]
测试了一下 php5.4 swoole 1.9.14   websocketserver->connections 是有值的。
而 php7.0.6  swoole 1.9.14  1.9.15 1.9.8 下是null。。看来是php7下swoole的websocketserver有bug？

**Comment by matyhtf** [comment]
使用`php --ri swoole`查看是否有`pcre`库，`connections`依赖`pcre`

**Comment by loncool** [comment]
确实没pcre  我centos 6.5系统。 为什么编译的时候没有pcre呢。。
是要系统装pcre么  可以看了下也装了。

**Comment by loncool** [comment]
可以了

**Comment by xiaomak** [comment]
我重装了也不行
php --ri swoole

swoole support => enabled
Version => 2.1.2
Author => tianfeng.han[email: mikan.tenny@gmail.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
openssl => enabled
http2 => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => 1 => 1
swoole.unixsock_buffer_size => 8388608 => 8388608
