### ISSUE TITLE
not found swoole_redis

### ISSUE THREAD

**Issue by chenyanlei** [swoole/swoole-src#1287]
PHP Fatal error:  Uncaught Error: Class 'swoole_redis' not found in

**Comment by matyhtf** [comment]
编译swoole需要增加`--enable-async-redis`

**Comment by yangw1990** [comment]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/swoole.so' - libhiredis.so.0.13: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by matyhtf** [comment]
安装 hiredis 库

**Comment by cimoing** [comment]
我在阿里云服务器Centos6.9也遇到过这个情况，解决办法是在**/etc/ld.so.conf.d/**目录下增加**libc.conf**, 内容为"/usr/local/lib", 然后再执行教程中的安装过程。可同时解决无法加载libhiredis库的问题
