### ISSUE TITLE
swoole主进程崩溃，子进程仍然存在

### ISSUE THREAD

**Issue by jocky4012** [swoole/swoole-src#1289]
软件环境：
CentOS Linux release 7.3.1611 (Core) 
php 7.1.6 
swoole 1.9.15 

主服务为websocket服务

服务部署两个星期，发生过两次崩溃，错误信息如下：
traps: php[13619] general protection ip:7fdabfc0cd12 sp:7fdabc443b98 error:0 in swoole.so[7fdabfbba000+97000]
traps: php[10561] general protection ip:7fcb97c0cd12 sp:7fcb93c42b98 error:0 in swoole.so[7fcb97bba000+97000]

用ps查看一下，发现主进程不在，子进程却还在

不知道是什么原因

**Comment by matyhtf** [comment]
请抓取一下core dump文件，然后用gdb查看调用栈。
https://wiki.swoole.com/wiki/page/p-issue.html

**Comment by jocky4012** [comment]
PHP升级到7.1.7，swoole升级到1.9.16后，观察了一个星期，问题暂时没有再出现。继续观察
