### ISSUE TITLE
Swoole\Client connecting to local socket(datagram) failed (Socket is already connected)

### ISSUE THREAD

**Issue by meanevo** [swoole/swoole-src#1292]
Env:
macOS 10.12.6
PHP 7.1.6 NTS / Zend Engine v3.1.0 with Zend OPcache v7.1.6
Swoole 2.0.7 running in CLI

![qq20170724-021657](https://user-images.githubusercontent.com/1898273/28501804-52510f38-7016-11e7-87df-36f7b0ab535c.jpg)

I've tried `SWOOLE_UNIX_STREAM` with an socat server and it worked as expected.
It seems this problem is only related with `SWOOLE_UNIX_DGRAM`.

I'd like to know if I was misunderstanding the protocol or something, thx

**Comment by matyhtf** [comment]
This bug has been fixed in the new version [2.0.8].
Today we will publish the new version.
