### ISSUE TITLE
2.0使用协程客户端访问https会报错误??

### ISSUE THREAD

**Issue by lost1987** [swoole/swoole-src#1293]
错误:
 Swoole\Coroutine\Http\Client::__construct(): require openssl library.

OS:ubuntu 12.04
已安装openssl libssl-dev
php版本7.1.0   php已启用openssl
swoole:2.0.8

    /**
     * test for swoole Coroutine
     */
    public function test(){
        $cli = new \Swoole\Coroutine\Http\Client('182.254.79.46', 443,true );
        $cli->setHeaders([
            'Accept'          => '*/*',
            'Accept-Encoding' => 'gzip, deflate',
            'Host'            => 'localhost',
            'User-Agent'      => '',
        ]);
        $cli->setDefer();
        $cli->set([ 'timeout' => 3]);
        $cli->get('/connect/oauth2/authorize?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&state=STATE&connect_redirect=1#wechat_redirect');
        $result = $cli -> recv();//$result is bool
        return $cli->body;
    }

**Comment by matyhtf** [comment]
使用 `php --ri swoole` 确实是否有`openssl`

**Comment by lost1987** [comment]
https://wiki.swoole.com/wiki/page/437.html
OK 我看到了 谢啦
