### ISSUE TITLE
php7.1.7 + swoole redis异步connect无响应

### ISSUE THREAD

**Issue by yangzhu6263736** [swoole/swoole-src#1294]
connect 始终不能执行到回调函数。swoole版本2.0.7
从git上拉master的代码发现编辑时make test 会卡死在
![image](https://user-images.githubusercontent.com/1215298/28538568-3bc51996-70e1-11e7-8c7e-861b20c82f72.png)应该是同样的问题
麻烦解决一下。

**Comment by yangzhu6263736** [comment]
另外补充一点，在普通进程中异步redis是可以回调的。但是在worker进程中就不回调了。

**Comment by matyhtf** [comment]
请使用 1.9.16 版本。

**Comment by yangzhu6263736** [comment]
刚我发现主线最新的版本虽然make test过不去，但实际上可用的。包括redis导步的这个问题也是OK的。

**Comment by matyhtf** [comment]
应该是 `2.0.7` 这个版本的BUG，现已修复。

**Comment by yangzhu6263736** [comment]
ok，谢谢。
