### ISSUE TITLE
无法序列化存在循环引用的类，即便循环引用的属性已在__sleep函数中排除

### ISSUE THREAD

**Issue by SyuTingSong** [swoole/swoole-src#1296]
例如：

```php
class Foo {
    public $bar;
    public $foo = 'aa';
    public function __sleep() {
        return ['foo'];
    }
}
$foo = new Foo();
$foo->bar = $foo;
$s = swoole_serialize::pack($foo);
```

结果抛异异常：
```
the object Foo have cycle ref!
```

是否可以只对`__sleep`返回的要序列化的属性作循环引用检查？

**Comment by GXhua** [comment]
问题以确认，我晚上看下怎么解决下

**Comment by GXhua** [comment]
我用最新的1.9.16无法重现你这个问题  请你也试下吧

**Comment by SyuTingSong** [comment]
刚才试了一下，用tag `v1.9.16`编译尝试依然存在此问题，`1.9`分支和`master`分支也存在此问题。

我看了一下`swoole_serialize.c`，在`swoole_serialize_object`的实现中，先[用`ZEND_HASH_GET_APPLY_COUNT`检查对象内是否存在循环引用](https://github.com/swoole/swoole-src/blob/1.9/swoole_serialize.c#L1087)，有的话会抛出异常，确定没有循环引用之后才[检查类里有无定义`__sleep`函数](https://github.com/swoole/swoole-src/blob/1.9/swoole_serialize.c#L1103)。

我的case恰好是对象的确存在循环引用，但`__sleep`声明要序列化的部分不涉及循环引用。

**Comment by GXhua** [comment]
报下你的php版本吧。我这为啥没事

**Comment by SyuTingSong** [comment]
PHP 7.0.21 with Zend OPcache v7.0.21

**Comment by GXhua** [comment]
/(ㄒoㄒ)/~~ 我用7.0.21+opcache依旧无法重现问题

**Comment by SyuTingSong** [comment]
经过逐一关闭extensions已确认同时开启swoole和tideways扩展就会出现这个问题，对方是闭源软件，我写Email给他们寻求支持吧，谢谢。

**Comment by SyuTingSong** [comment]
经过和tideways方面调试，确认这个问题和tideways扩展无关，即使关闭tideways扩展，也有可能触发这个问题。

我制作了一个[测试用例][1]。在这个例子中，`a.php`中有循环引用的类，并以`__sleep`排除循环引用的属性，`t.php`被`require_once`包含进来。运行`a.php`，`swoole_serialize::pack`会抛出循环引用的异常。但如果关闭opcahe，或者删除`t.php`中的类中的任意一个方法或属性甚至常量，此异常都不再抛出。

为了方便重现此问题，我基于PHP7.1制作了一个[docker镜像][2]，可以运行
```
docker run -ti syutingsong/swoole-debug
```
启动容器。在此容器中，swoole的源码用的是Github上的1.9.22版，下载到了`/tmp`目录下；php配置文件在`/usr/local/etc/php/conf.d`中；`a.php`和`t.php`文件在`/root`目录。

[1]: https://github.com/SyuTingSong/swoole-debug/tree/master/fs/root
[2]: https://hub.docker.com/r/syutingsong/swoole-debug/
