### ISSUE TITLE
swoole做RPC client端调用频繁发生8002或8009报错

### ISSUE THREAD

**Issue by congjunwei** [swoole/swoole-src#1299]
Swoole/Client/RPC.php
`
 /**
     * 尝试重连一次
     */
    for ($i = 0; $i < 2; $i++)
    {
        $ret = $socket->connect($host, $port, $this->timeout);
        if ($ret === false and ($socket->errCode == 114 or $socket->errCode == 115))
        {
            //强制关闭，重连
            $socket->close(true);
            continue;
        }
        else
        {
            break;
        }
    }
`
$socket->errCode返回114，115

请问这是什么原因

**Comment by matyhtf** [comment]
8002 表示连接失败，114/115 都表示连接超时了，你可以尝试把超时时间调大一些。
8009 表示服务器关闭了连接，检查你的代码逻辑

**Comment by congjunwei** [comment]
RPC.php里,
$socket->connect($host, $port, $this->timeout)
默认是timeout=0.5，我改成1了，感觉没有什么效果。也不应该有这么长时间吧~

架构大概是client连接aliyun的SLB转到后端的RPCServer。

**Comment by congjunwei** [comment]
swoole 扩展Version => 1.7.16

**Comment by matyhtf** [comment]
如果有条件更新版本，建议升级一下 1.9 最新版本。再来观察一下

**Comment by congjunwei** [comment]
升级至v1.7.20后问题解决。
