### ISSUE TITLE
在 linux 环境下 onRequest 回调函数加载不了其他类

### ISSUE THREAD

**Issue by abulo** [swoole/swoole-src#1300]
gcc versin :gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
Linux ubuntu 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
php:php-7.1.7
swoole:2.0.7
/usr/local/php/bin/php Webroot/launch/http.php  启动程序
在 Mac 下能够正常加载, Linux 下就不能加载了

程序已经发到 team@swoole.com

**Comment by matyhtf** [comment]
你的应用程序存在问题，检测错误日志。
