### ISSUE TITLE
ERROR	swFactoryProcess_finish (ERROR 1004): send 147 byte failed, because connection[fd=6415] is closed.

### ISSUE THREAD

**Issue by a569922982** [swoole/swoole-src#1301]
基本每一秒都出现 如果进程少直接就睡死了。。出现504
![image](https://user-images.githubusercontent.com/11918919/28741542-b8a59848-744a-11e7-8fb6-91e22501c13e.png)
![image](https://user-images.githubusercontent.com/11918919/28741548-e71924ec-744a-11e7-9111-3694e8eed1ef.png)

**Comment by matyhtf** [comment]
这个错误信息表示向已关闭的连接发送数据，检测你的代码，清除已关闭连接。

**Comment by mageguoshi** [comment]
我发发生这样问题。我用的是websocket的服务，如果用户在浏览器端连接之后，然后刷新浏览器就无法关闭了，原先的连接还在服务端保存着。然后服务端就不停的像这个连接发送数据看，服务端没有一个机制被动关闭连接吗！
![image](https://user-images.githubusercontent.com/3654652/38603891-759590a0-3da1-11e8-885e-181c8a2f8060.png)
