### ISSUE TITLE
rango的博客中有几点疑问

### ISSUE THREAD

**Issue by rymuscle** [swoole/swoole-src#1304]
rango博客http://rango.swoole.com/?s=epoll中明确表示epoll是异步非阻塞的  这貌似有问题啊, 明显是同步IO模型啊
还有reactor模型怎么又成了异步的了 它分明是同步的啊, proactor好像才是异步的吧

**Comment by matyhtf** [comment]
不要扣细节。
阻塞等待IO完成，是同步。
非阻塞使用epoll轮询通知，IO完成回调，是异步。
