### ISSUE TITLE
1.9.17版本导致 invalid pointer

### ISSUE THREAD

**Issue by huangzhhui** [swoole/swoole-src#1305]
问题由新版本导致，具体请参考 [issue](https://github.com/docker-library/php/issues/471)

**Comment by matyhtf** [comment]
https://wiki.swoole.com/wiki/page/p-issue.html
请贴出一下详细的gdb和valgrind跟踪信息吧

**Comment by matyhtf** [comment]
是否配置了 `upload_tmp_dir` 选项，去掉此选项后测试一下。
