### ISSUE TITLE
异步Redis客户端在定时器中执行Close不能触发onClose事件

### ISSUE THREAD

**Issue by chengdashun** [swoole/swoole-src#1306]
我不能确定是用法问题还是底层的bug,所以想确认下原因

swoole版本1.9.16 ,mac os

-----------------------------------------------------
```php
$client = new \Swoole\Redis();
$client->on('close', function () {
	echo 'on close...' . PHP_EOL;
});
$client->connect('127.0.0.1', 6379, function (\Swoole\Redis $client, $r) {
//	echo 'callback close...'. PHP_EOL;
//	$client->close();
});


swoole_timer_after(2000, function () use ($client) {
	echo 'call close...' . PHP_EOL;
	$client->close();
});
```
-----------------------------------------------------

定时器中调用close
![Uploading async_redis_affter_close.gif…]()

这段代码为什么不能触发'on close…' 但是如果在连接的回调里面打开注释代码 就可以正常触发on close

查询结果回调中调用close
![async_redis_close](https://user-images.githubusercontent.com/14008599/28808081-10a8d95c-76ac-11e7-8d09-53c6902bda9e.gif)

-----------------------------------------------------

如果是同样的逻辑

-----------------------------------------------------
```php
$client = new \Swoole\MySQL();

$client->on('close', function () {
	echo 'on close...' . PHP_EOL;
});
$config = [
	'host'     => '127.0.0.1',
	'port'     => 3306,
	'user'     => 'root',
	'password' => '123456',
	'database' => 'test',
];
$client->connect($config, function (\Swoole\MySQL $client, $r) {
//	echo 'callback close...'. PHP_EOL;
//	$client->close();
});


swoole_timer_after(2000, function () use ($client) {
	echo 'call close...' . PHP_EOL;
	$client->close();
});
```
-----------------------------------------------------

定时器中调用close
![Uploading async_mysql_after_close.gif…]()

查询结果回调中调用close
![async_mysql_close](https://user-images.githubusercontent.com/14008599/28808080-10a6a326-76ac-11e7-9763-5fe21a34552b.gif)

异步mysql是可以正常触发的

**Comment by maskwang** [comment]
mark

**Comment by matyhtf** [comment]
无法重现你的问题。

**Comment by augneb** [comment]
1.9.16 的确有这问题啊，但是 1.9.17 正常。
