### ISSUE TITLE
1.9.17重启worker进程时发生意外导致worker数量错乱 回退到1.9.13就没问题了

### ISSUE THREAD

**Issue by 948394154** [swoole/swoole-src#1309]
pecl安装的最新v1.9.17版本swoole，在第二次$server->reload()或者 kill -USR1 pid时，报错：ERROR	swManager_loop(:372): kill(14616, SIGTERM) failed. Error: No such process[3].

14616是第一次重启的时候被杀死的worker pid，看着像manager进程没有对woker进行有效管理，重复杀死了一个已经死掉的进程。

由于这个错误，不但重启中止，而且worker数量已经完全乱了

版本回退到1.9.13就没问题了

**Comment by matyhtf** [comment]
无法重现你的问题，使用了`SWOOLE_BASE`模式吗？

**Comment by 948394154** [comment]
用的应该是多进程模式。

**Comment by matyhtf** [comment]
worker进程数量不一致是有可能的，新版本实现了异步安全`reload`，底层会先创建新的worker进程，因此统一时间可能会出现 worker_num * 2 数量的进程，老的 worker 进程会自然消亡并退出。

**Comment by matyhtf** [comment]
https://wiki.swoole.com/wiki/page/775.html

**Comment by 948394154** [comment]
谢谢韩天峰老师 这个问题我会搜集更详细的一些日志发出来。

**Comment by 948394154** [comment]
http://way587.com/?p=310 复现了一下问题。而且这个问题在我这边是必现的。不确定是否是因为php 7.0.20的原因，我们在使用7.0.20的时候，fpm的进程管理也出现过一些问题。

**Comment by 948394154** [comment]
同事也复现了这个问题。但未必是第二次重启时发生。连续重启到第N次，这个错误会出现。

**Comment by yezuozuo** [comment]
补充：在发生“	swManager_loop(:372): kill(21332, SIGTERM) failed. Error: No such process[3].”错误之后，会多出一个永远不会被kill掉的进程，strace该进程，在reload master进程的时候该进程没有收到任何信号，过一段时间会出现`1086bb0, 4096, -1)       = -1 EINTR (Interrupted system call)
--- SIGTSTP {si_signo=SIGTSTP, si_code=SI_KERNEL, si_value={int=0, ptr=0x100000000}} ---
--- stopped by SIGTSTP ---`的日志，但是该进程仍然没有被回收，初步认为是重构异步安全重启时进程管理出现了问题

**Comment by matyhtf** [comment]
已修复。感谢反馈

**Comment by yezuozuo** [comment]
经测试，问题已修复，感谢韩老师~
