### ISSUE TITLE
http server 对端先关闭链接导致内存泄漏

### ISSUE THREAD

**Issue by AngusZhang082** [swoole/swoole-src#1310]
swoole_http_server.c文件中的 
static PHP_METHOD(swoole_http_response, end)方法中， 1918行

 ret = swServer_tcp_send(SwooleG.serv, ctx->fd, swoole_http_buffer->str, swoole_http_buffer->length);
        if (ret < 0)
        {
            ctx->send_header = 0;
            RETURN_FALSE;
        }
如果对端链接关闭，有变量未释放，是不是应该增加 swoole_http_context_free(ctx TSRMLS_CC);

   ret = swServer_tcp_send(SwooleG.serv, ctx->fd, swoole_http_buffer->str, swoole_http_buffer->length);
        if (ret < 0)
        {
            ctx->send_header = 0;
            swoole_http_context_free(ctx TSRMLS_CC);
            RETURN_FALSE;
        }

**Comment by matyhtf** [comment]
确实存在你说的这种问题，已修复。在 `response` 对象销毁时会进行检测。
