### ISSUE TITLE
发送10信号给manager进程重启偶尔会失败。

### ISSUE THREAD

**Issue by rookiejin** [swoole/swoole-src#1312]
`$server->set(array(
    'worker_num' => 4 ,
));

# 初始状态
     7 ?        Ss     0:00 /bin/bash
   309 ?        Sl+    0:00  \_ php index.php
   310 ?        S+     0:00      \_ php index.php
   315 ?        S+     0:00          \_ php index.php
   316 ?        S+     0:00          \_ php index.php
   317 ?        S+     0:00          \_ php index.php
   318 ?        S+     0:00          \_ php index.php

# 命令行直接发信号 
kill -s 10   310
# 第一次
     7 ?        Ss     0:00 /bin/bash
   309 ?        Sl+    0:00  \_ php index.php
   310 ?        S+     0:00      \_ php index.php
   321 ?        S+     0:00          \_ php index.php
   322 ?        S+     0:00          \_ php index.php
   323 ?        S+     0:00          \_ php index.php
   324 ?        S+     0:00          \_ php index.php
 
[2017-08-03 08:57:18 $310.0]    NOTICE  Server is reloading now.

# 第二次

     7 ?        Ss     0:00 /bin/bash
   309 ?        Sl+    0:00  \_ php index.php
   310 ?        S+     0:00      \_ php index.php
   321 ?        S+     0:00          \_ php index.php
   322 ?        S+     0:00          \_ php index.php
   323 ?        S+     0:00          \_ php index.php
   324 ?        S+     0:00          \_ php index.php
   326 ?        S+     0:00          \_ php index.php
   327 ?        S+     0:00          \_ php index.php
   328 ?        S+     0:00          \_ php index.php`
# 第一次能重启成功，第二次重启没成功 进程增加
就是重启偶尔会失败。

**Comment by matyhtf** [comment]
异步reload存在BUG导致，最新的代码已修复。
