### ISSUE TITLE
server->defer() 方法在自定义子进程里存在bug

### ISSUE THREAD

**Issue by breath-co2** [swoole/swoole-src#1316]
当使用 addProcess() 方法创建一个自已的子进程后，在这个进程里使用 `$server->defer($callback)` 返回 true 但是不生效，改用 `swoole_timer_after(1, $callback)` 可以回调

**Comment by matyhtf** [comment]
`defer`接口是在事件循环结束后才会执行，如果没有任何事件触发，`defer`不会被执行。

**Comment by breath-co2** [comment]
那这个就是我理解错误了，我在worker进程里测试也是不执行。我一直以为defer 会在进程空闲后立即被执行，但是等了老半天一直不被执行，这个会误导人

**Comment by matyhtf** [comment]
`defer`设计上是指 完全不关注什么时间会执行，这种情况下才使用`defer`，如果是关键性逻辑，不应该使用。

**Comment by matyhtf** [comment]
底层进行了兼容，发现是`onWorkerStart`或`Process`中，尚未进入EventLoop，会自动使用`after`定时器来替换`defer`
