### ISSUE TITLE
websocket为主协议时，子协议若是http，则子协议不能设置set项参数，同时还有其他问题

### ISSUE THREAD

**Issue by StartMoney** [swoole/swoole-src#1320]
有两个问题：
1、websocket为主协议时，子协议若是http，则子协议不能设置set项参数，设置后会异常（一直转圈，打不开）。
2、子协议http启用ssl（基于问题1，证书是放在主协议的set项里的），主协议的websocket不开启ssl时，可以用ws://访问到，当开启ssl后，用 wss://访问不到。

下面是代码：

```php
// Server
class Server {
	public $serv = NULL;
	public $port = NULL;
	public function __construct() {
		$config = array (
				"Websocket" => array (
						"ip" => "0.0.0.0",
						"port" => "19603",
 						"type" => SWOOLE_SOCK_TCP | SWOOLE_SSL,
//						"type" => SWOOLE_SOCK_TCP ,//
						"set" => array (
								'worker_num' => 2, //
								'log_file' => __DIR__ . '/log_Websocket.txt',
								'dispatch_mode' => 2, //
								'buffer_output_size' => 64 * 1024,
								'ssl_cert_file' => __DIR__.'/../certs/cert.pem',
								'ssl_key_file' => __DIR__.'/../certs/privkey.pem',
						)
				),

				"Http" => array ( // 做为子协议不能设置任何参数！否则访问不了(bug?)
						"ip" => "0.0.0.0",
						"port" => "19602",
						"type" => SWOOLE_SOCK_TCP | SWOOLE_SSL,
						// "type" => SWOOLE_SOCK_TCP,
// 						"set" => array (
// 								'ssl_cert_file' => __DIR__ . '/../certs/cert.pem',
// 								'ssl_key_file' => __DIR__ . '/../certs/privkey.pem'
// 						)
				)
		);

		$this->serv = new swoole_websocket_server ( $config['Websocket'] ['ip'], $config['Websocket']  ['port'] );
		$this->serv->set ( $config['Websocket'] ['set'] );
		$this->serv->on ( "Message", array (
				$this,
				"onMessageWebsocket"
		) );

		$port = $this->serv->listen ( $config['Http'] ['ip'], $config['Http'] ['port'], $config['Http']  ['type'] );
		if (isset ( $config['Http'] ['set'] ) && ! empty ( $config['Http']['set'] )) {
			$port->set ( $config['Http'] ['set'] );
		}

		$port->on ( "Request", array (
				$this,
				"onRequestHTTP"
		) );
		$this->serv->start ();
	}

	public function onOpenWebsocket(swoole_websocket_server $wserv, swoole_http_request $req) {
		echo __CLASS__ . ":" . __FUNCTION__ . "\r\n";
		$wserv->push ( $req->fd, "这是wss握手后，不正常" );

	}

	public function onMessageWebsocket(swoole_server $serv, swoole_websocket_frame $frame) {
		echo __CLASS__ . ":" . __FUNCTION__ . "\r\n";
		$serv->push ( $frame->fd, "这是wss收到消息，不正常" );
	}

	public function onRequestHttp($request, $response) {
		echo __CLASS__ . ":" . __FUNCTION__ . "\r\n";
		$response->end ( '这是https，正常的' );
	}
}

// 启动服务器
$server = new Server ();

```
版本：swoole  2.0.8  ， php  5.6.30
我想实现的是同一个服务里面包含 https访问的web服务器，wss://访问的websocket服务器。他两的证书可以分别颁发，也可以用同一个 。

**Comment by matyhtf** [comment]
你的程序运行不起来啊

**Comment by StartMoney** [comment]
<?php
date_default_timezone_set ( 'PRC' );

if (version_compare ( PHP_VERSION, '5.5.0', '<' )) {
	function cli_set_process_title($title) {
	}
}

// Server
class Server {
	public $serv = NULL;
	public $port = NULL;
	public function __construct() {
		$config = array (
				"Websocket" => array (
						"ip" => "0.0.0.0",
						"port" => "19603",
						"type" => SWOOLE_SOCK_TCP | SWOOLE_SSL,
						// "type" => SWOOLE_SOCK_TCP ,//
						"set" => array (
								'worker_num' => 2, //
								'log_file' => __DIR__ . '/log_Websocket.txt',
								'dispatch_mode' => 2, //
								'buffer_output_size' => 64 * 1024,
								'ssl_cert_file' => __DIR__.'/../certs/wifi.mianliu.men/cert-1502254509.pem',
								'ssl_key_file' => __DIR__.'/../certs/wifi.mianliu.men/privkey-1502254509.pem',
						)
				),

				"Http" => array ( // 做为子协议不能设置任何参数！否则访问不了(bug?)
						"ip" => "0.0.0.0",
						"port" => "19602",
						"type" => SWOOLE_SOCK_TCP | SWOOLE_SSL,
						// "type" => SWOOLE_SOCK_TCP,
// 						"set" => array (
// 								'ssl_cert_file' => __DIR__ . '/../certs/cert.pem',
// 								'ssl_key_file' => __DIR__ . '/../certs/privkey.pem'
// 						)
				)
		);

		$this->serv = new swoole_websocket_server ( $config['Websocket'] ['ip'], $config['Websocket']  ['port'] );
		$this->serv->set ( $config['Websocket'] ['set'] );
		$this->serv->on ( "Message", array (
				$this,
				"onMessageWebsocket"
		) );

		$port = $this->serv->listen ( $config['Http'] ['ip'], $config['Http'] ['port'], $config['Http']  ['type'] );
		if (isset ( $config['Http'] ['set'] ) && ! empty ( $config['Http']['set'] )) {
			$port->set ( $config['Http'] ['set'] );
		}

		$port->on ( "Request", array (
				$this,
				"onRequestHTTP"
		) );
		$this->serv->start ();
	}

	public function onMessageWebsocket(swoole_server $serv, swoole_websocket_frame $frame) {
		echo __CLASS__ . ":" . __FUNCTION__ . "\r\n";
	}

	public function onRequestHttp($request, $response) {
		echo __CLASS__ . ":" . __FUNCTION__ . "\r\n";
	}
}

// 启动服务器
$server = new Server ();

?>

**Comment by StartMoney** [comment]
<?php
date_default_timezone_set ( 'PRC' );

if (version_compare ( PHP_VERSION, '5.5.0', '<' )) {
	function cli_set_process_title($title) {
	}
}

// Server
class Server {
	public $serv = NULL;
	public $port = NULL;
	public function __construct() {
		$config = array (
				"Websocket" => array (
						"ip" => "0.0.0.0",
						"port" => "19603",
						"type" => SWOOLE_SOCK_TCP | SWOOLE_SSL,
						// "type" => SWOOLE_SOCK_TCP ,//
						"set" => array (
								'worker_num' => 2, //
								'log_file' => __DIR__ . '/log_Websocket.txt',
								'dispatch_mode' => 2, //
								'buffer_output_size' => 64 * 1024,
								'ssl_cert_file' => __DIR__.'/../certs/wifi.mianliu.men/cert-1502254509.pem',
								'ssl_key_file' => __DIR__.'/../certs/wifi.mianliu.men/privkey-1502254509.pem',
						)
				),

				"Http" => array ( // 做为子协议不能设置任何参数！否则访问不了(bug?)
						"ip" => "0.0.0.0",
						"port" => "19602",
						"type" => SWOOLE_SOCK_TCP | SWOOLE_SSL,
						// "type" => SWOOLE_SOCK_TCP,
// 						"set" => array (
// 								'ssl_cert_file' => __DIR__ . '/../certs/cert.pem',
// 								'ssl_key_file' => __DIR__ . '/../certs/privkey.pem'
// 						)
				)
		);

		$this->serv = new swoole_websocket_server ( $config['Websocket'] ['ip'], $config['Websocket']  ['port'] );
		$this->serv->set ( $config['Websocket'] ['set'] );
		$this->serv->on ( "Message", array (
				$this,
				"onMessageWebsocket"
		) );

		$port = $this->serv->listen ( $config['Http'] ['ip'], $config['Http'] ['port'], $config['Http']  ['type'] );
		if (isset ( $config['Http'] ['set'] ) && ! empty ( $config['Http']['set'] )) {
			$port->set ( $config['Http'] ['set'] );
		}

		$port->on ( "Request", array (
				$this,
				"onRequestHTTP"
		) );
		$this->serv->start ();
	}

	public function onMessageWebsocket(swoole_server $serv, swoole_websocket_frame $frame) {
		echo __CLASS__ . ":" . __FUNCTION__ . "\r\n";
	}

	public function onRequestHttp($request, $response) {
		echo __CLASS__ . ":" . __FUNCTION__ . "\r\n";
	}
}

// 启动服务器
$server = new Server ();

?>

**Comment by StartMoney** [comment]
`<?php
date_default_timezone_set ( 'PRC' );

if (version_compare ( PHP_VERSION, '5.5.0', '<' )) {
	function cli_set_process_title($title) {
	}
}

// Server
class Server {
	public $serv = NULL;
	public $port = NULL;
	public function __construct() {
		$config = array (
				"Websocket" => array (
						"ip" => "0.0.0.0",
						"port" => "19603",
						"type" => SWOOLE_SOCK_TCP | SWOOLE_SSL,
						// "type" => SWOOLE_SOCK_TCP ,//
						"set" => array (
								'worker_num' => 2, //
								'log_file' => __DIR__ . '/log_Websocket.txt',
								'dispatch_mode' => 2, //
								'buffer_output_size' => 64 * 1024,
								'ssl_cert_file' => __DIR__.'/../certs/cert.pem',
								'ssl_key_file' => __DIR__.'/../certs/privkey.pem',
						)
				),

				"Http" => array ( // 做为子协议不能设置任何参数！否则访问不了(bug?)
						"ip" => "0.0.0.0",
						"port" => "19602",
						"type" => SWOOLE_SOCK_TCP | SWOOLE_SSL,
						// "type" => SWOOLE_SOCK_TCP,
// 						"set" => array (
// 								'ssl_cert_file' => __DIR__ . '/../certs/cert.pem',
// 								'ssl_key_file' => __DIR__ . '/../certs/privkey.pem'
// 						)
				)
		);

		$this->serv = new swoole_websocket_server ( $config['Websocket'] ['ip'], $config['Websocket']  ['port'] );
		$this->serv->set ( $config['Websocket'] ['set'] );
		$this->serv->on ( "Message", array (
				$this,
				"onMessageWebsocket"
		) );

		$port = $this->serv->listen ( $config['Http'] ['ip'], $config['Http'] ['port'], $config['Http']  ['type'] );
		if (isset ( $config['Http'] ['set'] ) && ! empty ( $config['Http']['set'] )) {
			$port->set ( $config['Http'] ['set'] );
		}

		$port->on ( "Request", array (
				$this,
				"onRequestHTTP"
		) );
		$this->serv->start ();
	}

	public function onMessageWebsocket(swoole_server $serv, swoole_websocket_frame $frame) {
		echo __CLASS__ . ":" . __FUNCTION__ . "\r\n";
	}

	public function onRequestHttp($request, $response) {
		echo __CLASS__ . ":" . __FUNCTION__ . "\r\n";
	}
}

// 启动服务器
$server = new Server ();

?>`

**Comment by matyhtf** [comment]
监听端口调用 `set` 之后会覆盖主服务的协议设定，如果你的监听端口还想用 http协议，需要额外增加 
```php
				"Http" => array ( // 做为子协议不能设置任何参数！否则访问不了(bug?)
						"ip" => "0.0.0.0",
						"port" => "19602",
						"type" => SWOOLE_SOCK_TCP | SWOOLE_SSL,
						// "type" => SWOOLE_SOCK_TCP,
 						"set" => array (
 								'ssl_cert_file' => __DIR__ . '/../certs/cert.pem',
 								'ssl_key_file' => __DIR__ . '/../certs/privkey.pem',
 								'open_http_protocol' => true,
 								'open_websocket_protocol' => true,
 						)
				)
```

**Comment by StartMoney** [comment]
非常感谢 Rango。

设置了  open_http_protocol 和  open_websocket_protocol 后第一个问题解决了。

在主协议中开启了  SWOOLE_SOCK_TCP | SWOOLE_SSL   ，设置了证书 和 以上两个参数都为true后，仍然不能使用 wss://访问 websocket服务。 我在网上查了一下资，说要将wss://IP:端口  换成  wss://域名:端口 ，我试过后仍然不行。

**Comment by StartMoney** [comment]
主协议websocket的参数type参数不管设置成  SWOOLE_SOCK_TCP | SWOOLE_SSL     还是   SWOOLE_SOCK_TCP   都只能用 ws:// 访问，也就是ssl没有设置成功。。。。
而子协议里的type参数设置成不同的参数时，需要分别用http和https访问，说明子协议的ssl设置是成功的。

**Comment by matyhtf** [comment]
无法重现你说的问题，我本地测试 wss 是正常的。
