### ISSUE TITLE
使用 swoole 实现多进程,进程间数据通讯被截短

### ISSUE THREAD

**Issue by terryzwt** [swoole/swoole-src#1323]
Please answer these questions before submitting your issue. Thanks!
在提交Issue前请回答以下问题：

1. What did you do? If possible, provide a recipe for reproducing the error.
```php
<?php
$num = 4;
$data = range(1, 10000);

for($i=0; $i<$num ; $i++){
    $process = new Swoole\Process(function ($p) {
        $recv = $p->read();
        var_dump($recv);
        //$res = $recv * $recv;
        $res = json_decode($recv);
        $p->write(array_sum($res));
        //var_dump($p->pid);
        $p->exit(0); 
    },false);
    $pid = $process->start();
    $workers[$pid] = $process;
}
$chunk_data = array_chunk($data, ceil(count($data)/$num));
$i = 0;
foreach ($workers as $pid => $process) {
    $process->write(json_encode($chunk_data[$i]));
    echo "master send:" . $pid . ". worker calc result:" . $process->read() . PHP_EOL;
    $i++;
}
```

2. What did you expect to see?
计算结果异常,发送给子进程的数据被截断了.

3. What did you see instead?
发送给子进程的数据被截断了.自己诊断下,判断应该是大于8192个字节之后字节都会被截断.

4. What version of Swoole are you using (`php --ri swoole`)?
你所使用的Swoole版本号是什么（使用php --ri swoole可以获取）？
1.9.16

5. What is your machine environment used (including version of kernel & php & gcc) ? 
你使用的机器系统环境是什么（包括内核、PHP、gcc编译器版本信息）？
Debian GNU/Linux 8 \n \l
PHP 7.1.4 (cli) (built: Apr 18 2017 19:24:58) ( NTS )
gcc version 4.9.2 (Debian 4.9.2-10)

6. If you are using ssl, what is your openssl version?
如果你使用了SSL，你的openssl版本是什么？

**Comment by matyhtf** [comment]
管道通信有限制，每次`write`数据的长度在Linux系统下最大不超过8K，MacOS/FreeBSD下最大不超过2K。
https://wiki.swoole.com/wiki/page/216.html

**Comment by terryzwt** [comment]
补充一下,大神微信亲自指点迷津,结论如下:
**这是系统本身的限制,而且无法通过修改参数进行调整.**

建议绕过这个限制的方式是使用临时文件.
