### ISSUE TITLE
高并发往channel内push大于8k日志，kill 15 master时卡住

### ISSUE THREAD

**Issue by xcl3721** [swoole/swoole-src#1325]
Please answer these questions before submitting your issue. Thanks!
在提交Issue前请回答以下问题：

1. What did you do? If possible, provide a recipe for reproducing the error.
请详细描述问题的产生过程，贴出相关的代码，最好能提供可稳定重现的最小实例。

(gdb) bt
#0  0x00007f58cc6d61bd in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f58cc6d1d02 in _L_lock_791 () from /lib64/libpthread.so.0
#2  0x00007f58cc6d1c08 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007f58c1d6cce6 in swChannel_push (object=object@entry=0x7f58aaf79058, in=in@entry=0x7ffc71a20550, data_length=229)
    at /data/download/swoole-src-master/src/core/Channel.c:183
#4  0x00007f58c1d6777b in zim_swoole_channel_push (ht=<optimized out>, return_value=0x7f58a63288d0, return_value_ptr=<optimized out>,
    this_ptr=<optimized out>, return_value_used=<optimized out>) at /data/download/swoole-src-master/swoole_channel.c:101
#5  0x00000000008221ef in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>)
    at /data/download/php-5.6.8/Zend/zend_vm_execute.h:558
#6  0x00000000007b3358 in execute_ex (execute_data=0x7f58ce800430) at /data/download/php-5.6.8/Zend/zend_vm_execute.h:363
#7  0x000000000076ee93 in zend_call_function (fci=fci@entry=0x7ffc71a227c0, fci_cache=<optimized out>, fci_cache@entry=0x0)
    at /data/download/php-5.6.8/Zend/zend_execute_API.c:829
#8  0x000000000076f07e in call_user_function_ex (function_table=function_table@entry=0x2daa680, object_pp=<optimized out>,
    function_name=<optimized out>, retval_ptr_ptr=retval_ptr_ptr@entry=0x7ffc71a22858, param_count=<optimized out>,
    params=params@entry=0x309b228, no_separation=no_separation@entry=1, symbol_table=symbol_table@entry=0x0)
    at /data/download/php-5.6.8/Zend/zend_execute_API.c:617
#9  0x000000000076f0d2 in call_user_function (function_table=0x2daa680, object_pp=object_pp@entry=0x0, function_name=<optimized out>,
    retval_ptr=0x309c510, param_count=param_count@entry=1, params=params@entry=0x7ffc71a22888)
    at /data/download/php-5.6.8/Zend/zend_execute_API.c:590
#10 0x00007f58c16e9d13 in pcntl_signal_dispatch () at /data/download/php-5.6.8/ext/pcntl/pcntl.c:1270
#11 0x0000000000771502 in zend_llist_apply_with_argument (l=<optimized out>, func=func@entry=0x72c490 <php_tick_iterator>,
    arg=arg@entry=0x7ffc71a22a0c) at /data/download/php-5.6.8/Zend/zend_llist.c:234

2. What did you expect to see?
期望的结果是什么？

3. What did you see instead?
实际运行的结果是什么？

4. What version of Swoole are you using (`php --ri swoole`)?
你所使用的Swoole版本号是什么（使用php --ri swoole可以获取）？

swoole

swoole support => enabled
Version => 2.0.8
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 
你使用的机器系统环境是什么（包括内核、PHP、gcc编译器版本信息）？

CentOS Linux release 7.3.1611 (Core)
aliyun 服务器

6. If you are using ssl, what is your openssl version?
如果你使用了SSL，你的openssl版本是什么？

**Comment by matyhtf** [comment]
与 https://github.com/swoole/swoole-src/issues/1324 是同一问题，某个 worker crash 导致 锁未释放。已解决。
