### ISSUE TITLE
我安装1.7.22时 make时error: conflicting types for       'clock_gettime'

### ISSUE THREAD

**Issue by congjunwei** [swoole/swoole-src#1326]
Please answer these questions before submitting your issue. Thanks!
在提交Issue前请回答以下问题：

1. What did you do? If possible, provide a recipe for reproducing the error.
请详细描述问题的产生过程，贴出相关的代码，最好能提供可稳定重现的最小实例。
按照1.7.22，make时报错

```
In file included from ./php_swoole.h:41:
/data/src/swoole-1.7.22/include/swoole.h:69:5: error: conflicting types for
      'clock_gettime'
int clock_gettime(clock_id_t which_clock, struct timespec *t);
    ^
/usr/include/time.h:177:5: note: previous declaration is here
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    ^
1 error generated.
make: *** [swoole.lo] Error 1
```

2. What did you expect to see?
期望的结果是什么？
正常make

4. What version of Swoole are you using (`php --ri swoole`)?
你所使用的Swoole版本号是什么（使用php --ri swoole可以获取）？
swoole版本1.7.22

5. What is your machine environment used (including version of kernel & php & gcc) ? 
你使用的机器系统环境是什么（包括内核、PHP、gcc编译器版本信息）？
PHP5.5.16
Mac10.12.5

请问如何解决，并不希望安装新版本。

**Comment by matyhtf** [comment]
`1.7.22` 是较早期的版本，已经不再支持，你可以从最新的代码中对比差异，制作补丁。
