### ISSUE TITLE
Undefined property: swoole_http_request::$post

### ISSUE THREAD

**Issue by dark-flames** [swoole/swoole-src#1329]
在onRequest中使用$request->post发现$request并没有$post。
报错：Undefined property: swoole_http_request::$post
Client用的是swoole的httpClient，经抓包的确有post操作并且成功。
swoole_http_request->rawContent因为是application/x-www-form-urlencoded格式并不适用。

**Comment by matyhtf** [comment]
请按照 Issue 模板进行提交。
