### ISSUE TITLE
1.9.15 swoole_mysql bugs

### ISSUE THREAD

**Issue by pinguo-xudianyang** [swoole/swoole-src#1333]
## 测试环境：

Linux : CentOS release 6.5 (Final) 2.6.32-431.el6.x86_64 
PHP   : 7.0.18
Swoole: 1.9.15
gcc   : 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 

## 示例1

连接正确的MySQL配置

```php
#!/home/worker/php/bin/php
<?php
$client = new swoole_mysql();
$client->connect([
    'host' => '192.39.10.183',
    'port' => 3306,
    'user' => 'paygw',
    'password' => '-------',
    'charset' => 'utf8',
    'database' => 'paygw',
], function ($db, $result) {
  var_dump($result);
});
```

可以正常打印bool(true)，表示连接成功

## 示例2

在一的基础上只是修改了port参数，理论上应该回调打印bool(false)，但是coredump了

```php
#!/home/worker/php/bin/php
<?php
$client = new swoole_mysql();
$client->connect([
    'host' => '192.39.10.183',
    'port' => 3307,
    'user' => 'paygw',
    'password' => '-------',
    'charset' => 'utf8',
    'database' => 'paygw',
], function ($db, $result) {
  var_dump($result);
});
```

coredump信息

> #0  0x00007f2e47325a37 in swoole_mysql_onError (reactor=0x1bd8130, event=0x7fff4fcfeec0) at /home/worker/src/swoole-src/swoole_mysql.c:1298
> 1298        if (cli->socket->active)
> Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.5-7.el6_0.x86_64 cyrus-sasl-lib-2.1.23-15.el6_6.1.x86_64 db4-4.7.25-18.el6_4.x86_64 expat-2.0.1-13.el6_8.x86_64 fontconfig-2.8.0-5.el6.x86_64 freetype-2.3.11-17.el6.x86_64 glibc-2.12-1.149.el6_6.5.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-33.el6.x86_64 libX11-1.6.0-2.2.el6.x86_64 libXau-1.0.6-4.el6.x86_64 libcom_err-1.41.12-21.el6.x86_64 libcurl-7.19.7-53.el6_9.x86_64 libgcc-4.4.7-18.el6.x86_64 libgcrypt-1.4.5-11.el6_4.x86_64 libgomp-4.4.7-18.el6.x86_64 libgpg-error-1.7-4.el6.x86_64 libidn-1.18-2.el6.x86_64 libjpeg-turbo-1.2.1-3.el6_5.x86_64 libmcrypt-2.5.8-9.el6.x86_64 libpng-1.2.49-2.el6_7.x86_64 libselinux-2.0.94-5.8.el6.x86_64 libssh2-1.4.2-1.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64 libtool-ltdl-2.2.6-15.5.el6.x86_64 libxcb-1.9.1-2.el6.x86_64 libxml2-2.7.6-21.el6_8.1.x86_64 libxslt-1.1.26-2.el6_3.1.x86_64 net-snmp-libs-5.5-50.el6_6.1.x86_64 nspr-4.10.0-1.el6.x86_64 nss-3.15.1-15.el6.x86_64 nss-softokn-freebl-3.14.3-9.el6.x86_64 nss-util-3.15.1-3.el6.x86_64 openldap-2.4.39-8.el6.x86_64 openssl-1.0.1e-57.el6.x86_64 unixODBC-2.2.14-14.el6.x86_64 zlib-1.2.3-29.el6.x86_64
> (gdb) bt
> #0  0x00007f2e47325a37 in swoole_mysql_onError (reactor=0x1bd8130, event=0x7fff4fcfeec0) at /home/worker/src/swoole-src/swoole_mysql.c:1298
> #1  0x00007f2e4733e99c in swReactorEpoll_wait (reactor=0x1bd8130, timeo=<value optimized out>) at /home/worker/src/swoole-src/src/reactor/ReactorEpoll.c:289
> #2  0x00007f2e4730a6af in php_swoole_event_wait () at /home/worker/src/swoole-src/swoole_event.c:212
> #3  0x000000000083d772 in zend_call_function (fci=0x7fff4fcff050, fci_cache=0x7fff4fcfefd0) at /home/worker/src/php-7.0.18/Zend/zend_execute_API.c:878
> #4  0x000000000083dc9a in call_user_function_ex (function_table=<value optimized out>, object=<value optimized out>, function_name=<value optimized out>, 
>     retval_ptr=<value optimized out>, param_count=<value optimized out>, params=<value optimized out>, no_separation=1, symbol_table=0x0)
>     at /home/worker/src/php-7.0.18/Zend/zend_execute_API.c:675
> #5  0x000000000083dcb9 in call_user_function (function_table=<value optimized out>, object=<value optimized out>, function_name=<value optimized out>, 
>     retval_ptr=<value optimized out>, param_count=<value optimized out>, params=<value optimized out>) at /home/worker/src/php-7.0.18/Zend/zend_execute_API.c:657
> #6  0x00000000007402e7 in user_shutdown_function_call (zv=<value optimized out>) at /home/worker/src/php-7.0.18/ext/standard/basic_functions.c:4920
> #7  0x0000000000858d13 in zend_hash_apply (ht=0x7f2e50e552d8, apply_func=0x740220 <user_shutdown_function_call>) at /home/worker/src/php-7.0.18/Zend/zend_hash.c:1538
> #8  0x0000000000740216 in php_call_shutdown_functions () at /home/worker/src/php-7.0.18/ext/standard/basic_functions.c:5004
> #9  0x00000000007ee5d5 in php_request_shutdown (dummy=<value optimized out>) at /home/worker/src/php-7.0.18/main/main.c:1773
> #10 0x00000000008e27c7 in do_cli (argc=2, argv=0x1803c20) at /home/worker/src/php-7.0.18/sapi/cli/php_cli.c:1144
> #11 0x00000000008e3c8a in main (argc=2, argv=0x1803c20) at /home/worker/src/php-7.0.18/sapi/cli/php_cli.c:1347

## 示例3

host和port都能连通，但是连接为Redis服务，即TCP通信不是MySQL协议

```php
#!/home/worker/php/bin/php
<?php
$client = new swoole_mysql();
$client->connect([
    'host' => '192.39.10.183',
    'port' => 6379,
    'user' => 'paygw',
    'password' => '-------',
    'charset' => 'utf8',
    'database' => 'paygw',
], function ($db, $result) {
  var_dump($result);
});
```
运行代码不会执行回调，进程一直卡住，理论上应该回调打印bool(false)

**Comment by matyhtf** [comment]
已修复。
