### ISSUE TITLE
32-bits build is broken

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#1337]
Using latest 1.9.19 (previous 1.9.18 was ok)

```
builddir/build/BUILD/php-pecl-swoole-1.9.19/NTS/include/atomic.h:16:9: error: unknown type name 'atomic_int32_t'
 typedef atomic_int32_t                    sw_atomic_long_t;
         ^~~~~~~~~~~~~~

```

**Comment by remicollet** [comment]
There is also some other issue, the extension doesn't load (PHP 5.x, x86_64)

`php --no-php-ini --define extension=modules/swoole.so --modules | grep swoole
`
Swoole module is not llisted, so something got wrong during init.

**Comment by matyhtf** [comment]
Ok, tks, i will fix it later

**Comment by remicollet** [comment]
Thanks for the quick fix.

I confirm 1.9.20 is ok.

Tested with

* Fedora 24-27, RHEL 6-7
* PHP 5.4, 5.5, 5.6, 7.0, 7.1, 7.2
* i386, x86_64
* NTS, ZTS

**Comment by matyhtf** [comment]
:) 
Thanks for your issue.
My test plan is not good enough to cover all the platforms and versions.
I will be in the new version to solve the problem of test coverage.
