### ISSUE TITLE
ld:library not found for -lrt

### ISSUE THREAD

**Issue by QinXiaoXu** [swoole/swoole-src#1340]
I compile my SDK at MacOS,but it show me no librt,

$ld:library not found for -lrt
$clang:error:linker command failed with exit code 1 (use -v to see invocation)

$clang -v
Apple LLVM version 7.0.0 (clang-700.1.76)
Target:x86_64-apple-darwin14.5.0
Thread model:posix

How to do to solve it? #

**Comment by motecshine** [comment]
try 
`
xcode-select --install
`

**Comment by QinXiaoXu** [comment]
I tryed xcode-select --install,and how to reconfigure && remake swoole

**Comment by motecshine** [comment]
```shell 

make clean 
phpize 
./configure
make && make install 
```

**Comment by QinXiaoXu** [comment]
It show me "No rule to make target 'clean'.Stop",where should I do that?

**Comment by QinXiaoXu** [comment]
I installed swoole,but it still show me not found librt.

**Comment by matyhtf** [comment]
Download the swoole source, compile by your self.
Modify Makefile, remove `-lrt` flag.

**Comment by QinXiaoXu** [comment]
well,I have to remove -lrt flag at last.
