### ISSUE TITLE
websocket客户端没主动关闭的时候，getLastError没返回正确的错误码

### ISSUE THREAD

**Issue by imRainChen** [swoole/swoole-src#1350]
swoole版本：1.9.17
操作系统：centos
服务端是：websocket

请问韩老师，当websocket客户端没主动关闭的时候，调用push对这个客户端发消息会出现报错信息，想通过getLastError获取错误码删除掉内存里面的这个无效FD，但是结果发现获得错误码为0没法处理业务逻辑。请问是否还有什么方法解决？

```js
// $server->push()后出现错误消息：
PHP Warning:  swoole_websocket_server::push(): the connected client of connection[32] is not a websocket client. in /root/mega-filter/classes/Services/TextService.php on line 528

// 通过$server->getLastError()获得错误码是0
[2017-09-12 13:32:37.879][debug] - [WebSocket推送] 错误码:0
```

**Comment by imRainChen** [comment]
因为设置了dispatch_mode = 3可能是这个，导致出现这样的情况。

**Comment by matyhtf** [comment]
出现这个错误，表示连接不是WebSocket协议，但是正常的连接。

**Comment by Manlinup** [comment]
task push 一直有这个问题。百度谷歌文档了很久都找不到原因。这个fd是通过赋值变量传到task进程中，然后通过这个fd,push到客户端就会报这个错误。如果在message中直接获取$frame->fd,直接push就是正确的。同样都是websocket客户端连接。不知道问题在哪里。
