### ISSUE TITLE
coroutine segment fault

### ISSUE THREAD

**Issue by gouchaoer** [swoole/swoole-src#1351]
Please answer these questions before submitting your issue. Thanks!
在提交Issue前请回答以下问题：

1. What did you do? If possible, provide a recipe for reproducing the error.
请详细描述问题的产生过程，贴出相关的代码，最好能提供可稳定重现的最小实例。

centos7, php70
```
<?php
ini_set('memory_limit',-1);
for ($i = 0; $i < 2000; $i++) {
    Swoole\Coroutine::create(function() use ($i, &$v) {
        $redis = new Swoole\Coroutine\Redis();
        $res = $redis->connect('192.168.1.200', 6379);
        $ret = $redis->incr('coroutine');
        $redis->close();
        if ($i%10 == 0) {
            Swoole\Coroutine::create(function() use ($i) {
                $redis = new Swoole\Coroutine\Redis();
                $res = $redis->connect('192.168.1.200', 6379);
                $ret = $redis->incr('coroutine_i');
                $redis->close();
            });
        }
    });
}

register_shutdown_function(function () {
echo memory_get_usage() . PHP_EOL;
echo memory_get_peak_usage() . PHP_EOL;
});
```
As you can see I did not use coroutine in swoole server. I create 2200 coroutine and get Segmentation fault. I think I had created too much coroutines(if I create 1000 coroutine everything is OK). but the limit is 3000 in `https://github.com/swoole/swoole-src/blob/master/swoole_coroutine.c#L65`
2. What did you expect to see?

期望的结果是什么？

期望的结果是什么？

3. What did you see instead?
实际运行的结果是什么？

Segmentation fault

4. What version of Swoole are you using (`php --ri swoole`)?
你所使用的Swoole版本号是什么（使用php --ri swoole可以获取）？

```
swoole

swoole support => enabled
Version => 2.0.9
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

```

5. What is your machine environment used (including version of kernel & php & gcc) ? 
你使用的机器系统环境是什么（包括内核、PHP、gcc编译器版本信息）？

6. If you are using ssl, what is your openssl version?
如果你使用了SSL，你的openssl版本是什么？

**Comment by matyhtf** [comment]
Please test with the latest version (2.0.10-rc1)

**Comment by matyhtf** [comment]
It can't be reproduced now
