### ISSUE TITLE
swoole client connect域名解析怎样可以不使用缓存

### ISSUE THREAD

**Issue by mistypig** [swoole/swoole-src#1354]
`$swoole_cli = new \swoole_client(SWOOLE_SOCK_TCP,SWOOLE_SOCK_SYNC);`
`$swoole_cli->connect("example.com", $port, $time_out)`
第一次连接时example.com域名的IP地址为IP_ADDRESS_1，之后修改example.com的DNS解析为IP_ADDRESS_2，修改后无法连接，甚至在/etc/hosts文件中写死example.com的IP地址也不行。目前唯一解决办法只能重启应用，能否在不重启的情况下动态解析域名？

**Comment by matyhtf** [comment]
底层并没有缓存，可能是操作系统层面的机制。
