### ISSUE TITLE
swoole_async_dns_lookup 解析结果出错

### ISSUE THREAD

**Issue by hncg** [swoole/swoole-src#1356]
问题类似 [issue#1175](https://github.com/swoole/swoole-src/issues/1175)

现象描述：swoole_async_dns_lookup **获取ip地址有误**(偶现)
代码执行结果：

> swoole 版本:1.9.19
php 版本:5.6.26
string(23) **"mysql-master:127.0.0.10"**
string(16) "redis:127.0.0.10"
string(22) "mysql-master:127.0.0.9"
string(16) "redis:127.0.0.10"
string(16) "redis:127.0.0.10"
string(22) "mysql-master:127.0.0.9"
string(16) "redis:127.0.0.10"
string(22) "mysql-master:127.0.0.9"
string(16) "redis:127.0.0.10"
string(22) "mysql-master:127.0.0.9"
string(16) "redis:127.0.0.10"
string(22) "mysql-master:127.0.0.9"
string(16) "redis:127.0.0.10"
string(22) "mysql-master:127.0.0.9"
string(22) "mysql-master:127.0.0.9"
string(16) "redis:127.0.0.10"
string(22) "mysql-master:127.0.0.9"
string(16) "redis:127.0.0.10"

**错误地方：请注意结果的第三行，mysql-master:127.0.0.10 获取到了redis的地址.**

php代码：
```
<?php
$host = 'mysql-master';
$redisHost = 'redis';

$ext = new ReflectionExtension('swoole');

echo "swoole 版本:" . $ext->getVersion() . PHP_EOL;
echo "php 版本:" . phpversion() . PHP_EOL;

$count = 10;
while (--$count) {
    swoole_async_dns_lookup($host, function ($host, $ip) {
        var_dump($host .':'. $ip);
    });
    swoole_async_dns_lookup($redisHost, function ($host, $ip) {
        var_dump($host .':'. $ip);
    });
}


```
**/etc/hosts 配置文件：**

> 127.0.0.9 mysql-master
127.0.0.10 redis

内核信息：

> Darwin MacBook-Air.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

gcc信息：

> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 7.3.0 (clang-703.0.31)
> Target: x86_64-apple-darwin15.5.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> 

php版本：

> 5.6.26

swoole版本： 

> 1.9.19

PS： 
1 我自己在用php7.1和其它系统(ubuntu)包括 swoole2版本也测试过，均出现同样的问题。
2 现象是偶现,复现可能需要多执行几次，我本地测试是5次左右出现一次异常情况。

**Comment by matyhtf** [comment]
使用`1.9.23`版本，多次测试未能重现此问题。

**Comment by hncg** [comment]
我刚刚做了一个容器。可以不稳定重新此现象(我自己测试90%概率重现)。
重现步骤：
1 docker run -it  --rm  --add-host="mysql-master:172.0.0.2" --add-host="redis:172.0.0.3" registry.cn-qingdao.aliyuncs.com/hncg/swoole:1.9.23  bash

2 php /swoole-bug/test.php | grep 'mysql-master:172.0.0.3' -A 2 -B 2

所需环境： docker任意版本。
@matyhtf

**Comment by hncg** [comment]
> root@30970b2f230f:/var/www/html# php /swoole-bug/test.php | grep 'mysql-master:172.0.0.3' -A 2 -B 2
string(15) "redis:172.0.0.3"
string(22) "mysql-master:172.0.0.2"
string(22) "mysql-master:172.0.0.3"
string(22) "mysql-master:172.0.0.2"
string(15) "redis:172.0.0.3"
--
string(15) "redis:172.0.0.3"
string(15) "redis:172.0.0.3"
string(22) "mysql-master:172.0.0.3"
string(15) "redis:172.0.0.3"
string(15) "redis:172.0.0.3"


补充测试结果：mysql-master得到的结果有误 172.0.0.2 和172.0.0.3并存。

**Comment by matyhtf** [comment]
@hncg 请设置线程数为1再测试一下
```php
Swoole\Async::set(['thread_num' => 1]);
```

**Comment by matyhtf** [comment]
`gethostbyname2`非线程安全导致，已修复。
