### ISSUE TITLE
2.09 udp异步客户端

### ISSUE THREAD

**Issue by hemin3260** [swoole/swoole-src#1360]
Please answer these questions before submitting your issue. Thanks!
在提交Issue前请回答以下问题：

1. What did you do? If possible, provide a recipe for reproducing the error.
请详细描述问题的产生过程，贴出相关的代码，最好能提供可稳定重现的最小实例。
udp_server代码：

```php

    $serv = new swoole_server('0.0.0.0',60001,SWOOLE_BASE,SWOOLE_SOCK_UDP );
    $serv->set([
        'worker_num'=>1
    ]);
    $serv->on('Packet', function ($serv, $data, $clientInfo) {
         echo $data."\n";
         $serv->sendto($clientInfo['address'], $clientInfo['port'], "Server ".$data);
    });
    
    $serv->on('ManagerStart', function ($manager) {
        swoole_set_process_name("siva_udp_manager");
    });


    $serv->on('WorkerStart',function ($worker) {
        swoole_set_process_name("siva_udp_worker");
    });

    $serv->start();
```

tcp server:

```php
    $_server = new Swoole\Http\Server("127.0.0.1",60002,SWOOLE_BASE,SWOOLE_SOCK_TCP);

    $_server->set([
        'worker_num'=>1
    ]);

    $_server->on('Request',function($request, $response){
         $udp_client = new Swoole\Coroutine\Client(SWOOLE_SOCK_UDP);
         $udp_client->connect("127.0.0.1",60001);   
         $udp_client->send("write_log");
           
        $udp_client->close();
        $response->end("suc");
    });

    $_server->on('ManagerStart', function ($manager) {
        swoole_set_process_name("siva_test_udp_tcp_manager");
    });


    $_server->on('WorkerStart', function ($worker) {
        swoole_set_process_name("siva_test_udp_tcp_worker");
    });
    $_server->start();
```

ab请求10万次：
/opt/lampp/bin/ab -n 100000 -c 20 -v 4 'http://127.0.0.1:60002/'> 10w_5.txt

2. What did you expect to see?
期望的结果是什么？
正常返回

3. What did you see instead?
实际运行的结果是什么？
core dump
![image](https://user-images.githubusercontent.com/8153418/30894558-13f645ac-a377-11e7-9ef8-a8290f7fd8b5.png)

4. What version of Swoole are you using (`php --ri swoole`)?
你所使用的Swoole版本号是什么（使用php --ri swoole可以获取）？
![image](https://user-images.githubusercontent.com/8153418/30894452-67f65f44-a376-11e7-83fb-5d57c557c093.png)

5. What is your machine environment used (including version of kernel & php & gcc) ? 
你使用的机器系统环境是什么（包括内核、PHP、gcc编译器版本信息）？
```
php 5.6.24
gcc version 4.4.6 20110731 (Red Hat 4.4.6-4) (GCC)
Linux  2.6.32.43  #1 SMP Fri Jun 27 14:18:34 CST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

6. If you are using ssl, what is your openssl version?
如果你使用了SSL，你的openssl版本是什么？
```
OpenSSL 1.0.1e-fips 11 Feb 2013
```

**Comment by matyhtf** [comment]
使用最新的`master`分支代码，未能重现此问题。
