### ISSUE TITLE
swoole_process异步非阻塞模型下,某种情况父进程获取不到绑定的SIGCHLD信号,产生僵尸进程

### ISSUE THREAD

**Issue by mrwatcher** [swoole/swoole-src#1366]
Please answer these questions before submitting your issue. Thanks!
在提交Issue前请回答以下问题：

1. What did you do? If possible, provide a recipe for reproducing the error.
请详细描述问题的产生过程，贴出相关的代码，最好能提供可稳定重现的最小实例。

//异步非阻塞
```php
$work_num = 10;
$worker_func = function(swoole_process $worker)
{
	$current_work = $GLOBALS['current_work'];
	$worker->name("sw: worker-{$current_work}");
	//do something
	sleep(rand(1,3));
};

$master = new swoole_process(function(swoole_process $master)use($work_num,$worker_func){
	swoole_process::signal(SIGCHLD, function($signo) {
  		while ($ret = swoole_process::wait(false)) {print_r($ret);}; 
	});
	$master->name('sw: master');
	$workers_arr = [];
	for ($i=0; $i < $work_num; $i++) { 
		$worker = new swoole_process($worker_func,false,true);
		$GLOBALS['current_work'] = $i;
		$worker_id = $worker->start();
		$workers_arr[$worker_id] = $worker;
	}
	/****master do something start****/
       //当$i<1000000000时无法获取绑定的SIGCHLD信号,当$i<1000000时正常
       //是否是因为for while foreach为阻塞操作,信号捕捉timeout 
	for ($i=0; $i < 1000000000; $i++) { 
		
	}
	/****master do something end****/

},false,false);
$master->start();
```
2. What did you expect to see?
期望的结果是什么？

父进程获取SIGCHLD信号,wait回收子进程.

3. What did you see instead?
实际运行的结果是什么？

父进程获取不到SIGCHLD信号无法回收子进程,产生僵尸进程.

4. What version of Swoole are you using (`php --ri swoole`)?
你所使用的Swoole版本号是什么（使用php --ri swoole可以获取）？

Version => 1.9.3

5. What is your machine environment used (including version of kernel & php & gcc) ? 
你使用的机器系统环境是什么（包括内核、PHP、gcc编译器版本信息）？

PHP 5.6.20 (cli) (built: Jun  7 2016 20:21:12) 

gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)

**Comment by matyhtf** [comment]
`swoole_process::signal` 是异步信号处理。你的代码中存在死循环，会导致`EventLoop`出现异常。需要修改程序使用同步阻塞模式，或移除死循环。
