### ISSUE TITLE
希望增加swoole_http_client对response header解析的容错性

### ISSUE THREAD

**Issue by lgang06** [swoole/swoole-src#1368]
Please answer these questions before submitting your issue. Thanks!
在提交Issue前请回答以下问题：

1. What did you do? If possible, provide a recipe for reproducing the error.
请详细描述问题的产生过程，贴出相关的代码，最好能提供可稳定重现的最小实例。
接口header中返回不规范的内容key=val，正常应该是key:val，导致swoole客户端解析失败，连接超时。
官方调用例子：
$cli = new swoole_http_client('127.0.0.1', 80);

$cli->setHeaders([
    'Host' => "lg.test.com",
    "User-Agent" => 'Chrome/49.0.2587.3',
    'Accept' => 'text/html,application/xhtml+xml,application/xml',
    'Accept-Encoding' => 'gzip',
]);
$cli->set(
    ['timeout' => 3]
);
$cli->get('/index.php', function ($cli) {
    echo $cli->body;
    $cli->close();
});

模拟接口返回示例：
header('charset=utf8');
echo "this is test interface";
exit();

2. What did you expect to see?
期望的结果是什么？
输出：this is test interface

3. What did you see instead?
实际运行的结果是什么？
执行超时后swoole客户端断开

4. What version of Swoole are you using (`php --ri swoole`)?
你所使用的Swoole版本号是什么（使用php --ri swoole可以获取）？
swoole 2.0.8，2.0.9

5. What is your machine environment used (including version of kernel & php & gcc) ? 
你使用的机器系统环境是什么（包括内核、PHP、gcc编译器版本信息）？
php:7.0.12
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

6. If you are using ssl, what is your openssl version?
如果你使用了SSL，你的openssl版本是什么？

**Comment by matyhtf** [comment]
由于swoole底层使用了`http_parser`组件，而不是自己解析Http协议。在不修改第三方库代码的前提下，无法实现。暂时不支持。
