### ISSUE TITLE
How to prepare a statement using swoole-mysql?

### ISSUE THREAD

**Issue by shtse8** [swoole/swoole-src#1370]
I cannot find `prepare` method. Only `query` is available. any supports?

**Comment by gouchaoer** [comment]
没有prepare的确很尴尬，而且就算你要类似mysql_real_escape_string或者PDO:quote那样消毒也必须设置连接utf8否则还是可能注入，

**Comment by gouchaoer** [comment]
其实拿mysqli来给io打上协程patch是最好的

**Comment by gouchaoer** [comment]
use escape to sanitize use input

**Comment by shtse8** [comment]
escaping is not the same as prepare. prepare can be faster for the same query running multiple times with different bindings.

**Comment by heikezy** [comment]
sad enough, swoole doesn't have it.
mysql support for swoole is built from scratch, obviously prepare just has not been implemented.
so yeah, it's gonna take extra work and got worse performance to do it manually in PHP.

**Comment by gouchaoer** [comment]
prepare does not give a noticable performance improvement in most cases. pdo does emulated prepare by default for that reason. swoole has very limited contributors. you can manually implement a emulated prepare just like pdo.

**Comment by shtse8** [comment]
@gouchaoer for event-driven server side program, the performance increase a lot.

**Comment by matyhtf** [comment]
The `prepare method` is not currently supported. You can use `escape` and `query` instead of `prepare`.
We will support prepare in this version of 2.0.11

**Comment by shtse8** [comment]
@matyhtf That's great. I am looking forward to this.

**Comment by matyhtf** [comment]
Supported.
https://github.com/swoole/swoole-src/commit/a26f71c5961a437bd10777644e9910854f97df81
https://github.com/swoole/swoole-src/blob/master/examples/coroutine/mysql_prepare.php

**Comment by aolko** [comment]
@matyhtf is there going to be an info on that in the docs?
