### ISSUE TITLE
想问下swoole2.0使用的websocket协议版本

### ISSUE THREAD

**Issue by tcsp** [swoole/swoole-src#1373]
当前在使用swoole2.0,但是在android的一个机型上，无法建立连接，估摸是websocket版本不支持的问题，不知道swoole2.0支持的是哪些websocket协议版本

**Comment by kuofp** [comment]
目前大多建議使用13版本
```c
/*swoole_config.h*/
#define SW_WEBSOCKET_VERSION             "13"
```

**Comment by matyhtf** [comment]
默认握手协议版本为`13`，可自定义握手回调函数，支持更低版本的`WebSocket`协议。
