### ISSUE TITLE
http_client 1.9.17 以上 出现statusCode -3 使用1.9.14 没问题

### ISSUE THREAD

**Issue by qysf12345** [swoole/swoole-src#1375]
Please answer these questions before submitting your issue. Thanks!
在提交Issue前请回答以下问题：

1. What did you do? If possible, provide a recipe for reproducing the error.
请详细描述问题的产生过程，贴出相关的代码，最好能提供可稳定重现的最小实例。

<?php
$cli = new Swoole\Http\Client('120.132.61.243', 7070);
$cli->post('/third/getUserInfo', '{}', function ($cli) {
    var_dump($cli->body,$cli->statusCode);
});

2. What did you expect to see?
期望的结果是什么？

{
    "msg": "对不起,错误的请求数据.",
    "result": 2
}

3. What did you see instead?
实际运行的结果是什么？

string(0) ""
int(-3)

4. What version of Swoole are you using (`php --ri swoole`)?
你所使用的Swoole版本号是什么（使用php --ri swoole可以获取）？

1.9.18

5. What is your machine environment used (including version of kernel & php & gcc) ? 
你使用的机器系统环境是什么（包括内核、PHP、gcc编译器版本信息）？

centos 6.5  php5.6.31  gcc version 4.4.7

6. If you are using ssl, what is your openssl version?
如果你使用了SSL，你的openssl版本是什么？

未使用

**Comment by qysf12345** [comment]
不知道怎么搞的显示成 那个样子 编辑 打不开网不行， 代码如下
$cli = new Swoole\Http\Client('120.132.61.243', 7070);
$cli->post('/third/getUserInfo', '{}', function ($cli) {
    var_dump($cli->body,$cli->statusCode);
});

**Comment by qysf12345** [comment]
版本 1.9.18， 实测 1.9.17 和1.9.21 都不行

**Comment by qysf12345** [comment]
预期结果：
{
    "msg": "对不起,错误的请求数据.",
    "result": 2
}

**Comment by qysf12345** [comment]
时间结果：
string(0) ""
int(-3)
statusCode返回-3

**Comment by qysf12345** [comment]
centos 6.5 php5.6.31 gcc version 4.4.7

**Comment by matyhtf** [comment]
已修复。因为Http响应中没有`Content-Length`导致
