### ISSUE TITLE
Apache + swoole on Linux... possible?

### ISSUE THREAD

**Issue by simonhf** [swoole/swoole-src#1376]
I currently have a large PHP application running on Apache without problems. However, there are certain things I'd like to optimize and make async. I'm wondering if it's possible to use swoole from PHP running inside Apache? Will it 'just work'? Has anybody tried this? Or is anybody currently doing it? Thanks in advance for the feedback.

**Comment by matyhtf** [comment]
Swoole can only run on the command line environment.
You should use  the `swoole_http_server`.

**Comment by doubaokun** [comment]
@simonhf Swoole is quite different from the traditional PHP model, it is running in daemon mode like PHP cli. I am afraid Swoole server side can't run inside Apache. But I think the client side should be compatible with Apache mod_php.

We will add more 'how it works' documents in the future.
