### ISSUE TITLE
swoole reload之后出现  ERROR	swMsgQueue_pop(:67): msgrcv(3571712, 8192, 3) failed. Error: Interrupted system call[4]

### ISSUE THREAD

**Issue by lovephalcon1990** [swoole/swoole-src#1378]
service配置：

调用 swoole_server->reload 

PHP版本：
![image](https://user-images.githubusercontent.com/7123896/32091656-ad331e08-bb27-11e7-9dd1-f1961b3a436c.png)
Swoole版本：
![image](https://user-images.githubusercontent.com/7123896/32091687-cf01d858-bb27-11e7-8e2f-dd1993fe3676.png)

出错信息：
![image](https://user-images.githubusercontent.com/7123896/32091737-0b4a0a24-bb28-11e7-839a-73bae06ec128.png)

strace信息：
![image](https://user-images.githubusercontent.com/7123896/32091818-660616ce-bb28-11e7-8d52-a8f705609454.png)

**Comment by matyhtf** [comment]
请升级至 `1.9.21` 版本，已解决此类问题。
