### ISSUE TITLE
swoole_async_read read file contents cannot change the outter variables

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#1379]
1. 问题描述：
<pre>
<?php

//swoole_async_read 异步读，不能修改外层变量
$data = 'mmm';
$GLOBALS['m'] = 'ss';
$d = swoole_async_read("/tmp/td", function($filename, $content) use (&$data){
    //             echo "$filename: $content";
    global $data;
    $GLOBALS['m'] = $content;
    $data = $content;
    //var_dump($this->getObjectPool()->data);
});

    var_dump($data,$GLOBALS['m']);  //不能打印出异步获取的内容

$host_ip = '';
swoole_async_dns_lookup("www.baidu.com", function($host, $ip) use($host_ip) {
    echo "{$host} : {$ip}\n";
    $host_ip = $host.':'.$ip;
});

    var_dump($host_ip);

</pre>

2. What did you expect to see?

期望：swoole_async_read/swoole_async_dns_lookup 异步网络IO 可以修改外层变量

3. What did you see instead?
测试返回结果：
➜  www php test.php
string(3) "mmm"
string(2) "ss"
string(0) ""
www.baidu.com : 220.181.111.188

4. What version of Swoole are you using (`php --ri swoole`)?
www php --ri swoole

swoole

swoole support => enabled
Version => 2.0.7
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
rwlock => enabled
async http/websocket client => enabled
pcre => enabled
zlib => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 
macos、linux均存在此问题。
php7

➜  www gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

6. If you are using ssl, what is your openssl version?
没用ssl

**Comment by matyhtf** [comment]
无效问题。对异步回调理解存在偏差。
