### ISSUE TITLE
swReactorThread_free(:1444): pthread_cancel(x) failed. Error: Resource temporarily unavailable[11].

### ISSUE THREAD

**Issue by visoeclipse** [swoole/swoole-src#1384]
请教个问题， 现网环境出现的错误：

swReactorThread_free(:1444): pthread_cancel(140676143933184) failed. Error: Resource temporarily unavailable[11].

swoole相关配置：

swoole support => enabled
Version => 1.9.6
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
jemalloc => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by matyhtf** [comment]
请升级至 `1.9.22` 已解决此问题。shutdown阶段错误，不影响正常运行。
