### ISSUE TITLE
http server 一直报错swReactorKqueue_del(:238): kqueue->del(21, SW_EVENT_WRITE) failed. Error: No such file or directory[2]

### ISSUE THREAD

**Issue by jesusslim** [swoole/swoole-src#1387]
2.0.8版本

使用的是http server 一直报错 频率极高 
swReactorKqueue_del(:238): kqueue->del(21, SW_EVENT_WRITE) failed. Error: No such file or directory[2]

![image](https://user-images.githubusercontent.com/12554966/32593417-ca3d0852-c562-11e7-8fdd-eaf758d21ea1.png)

**Comment by matyhtf** [comment]
请升级至 `1.9.22` 或 `2.0.10-rc1` ，已解决。
