### ISSUE TITLE
"brew install swoole"  is not effect

### ISSUE THREAD

**Issue by heshiweij** [swoole/swoole-src#1389]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
install swoole by "brew install swoole" on macOS:

The error:
No formulae found in taps(on github)

2. What did you expect to see?
brew could found swoole and install it automatic

3. What did you see instead?
error

4. What version of Swoole are you using (`php --ri swoole`)?
Did't install swoole successfully

5. What is your machine environment used (including version of kernel & php & gcc) ? 
os version:
macOS  10.11.6

php -v: 
PHP 7.1.11 (cli) (built: Oct 27 2017 11:00:03) ( NTS )

gcc -version:
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

6. If you are using ssl, what is your openssl version?
no use openssl

既然官方文档写了在 mac 上使用 “brew install swoole” 进行安装，那么这个命令就可以安装成功，不需要其他附加操作。现在提示搜索不到包， 我认为这是个 bug。 谢谢！

**Comment by doubaokun** [comment]
Hi @heshiweij please install swoole extension on the MacOS with the commands based on the PHP version:

```
brew install homebrew/php/php53-swoole
...
brew install homebrew/php/php71-swoole
```
The idea is that brew shows the version based package names.

We will amend the documents based on your suggestion.

**Comment by mbence** [comment]
Since Homebrew/php is deprecated (as of [1.5.0](https://brew.sh/2018/01/19/homebrew-1.5.0/)) none of the above formulae is available. Any plans to restore brew support?

**Comment by MrNicodemuz** [comment]
Wanted to try out swoole. But it's quite a huge red flag when I cannot even complete the first step of the "Getting started" guide. Is this project still maintained?

How do I get going on Mac OSX?

**Comment by mbence** [comment]
It is not a swoole issue, brew officially stopped providing any php extensions. They say Pecl should be used instead.
But I found the easiest was to test it is docker:
https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=swoole&starCount=0

**Comment by avramovic** [comment]
Here's how I installed in on MacOS (High Sierra). Downloaded latest release (source) to `~/swoole` then run all the commands as described in the documentation:

    phpize
    ./configure
    make
    sudo make install

Two notes:

1. `phpize` failed for me first time. After running `brew install autoconf` it worked.
2. `sudo make install` gave me an error about not having permission to copy resulting .so file to the destination folder, but I still got it (compiled) in `~/swoole/modules/swoole.so` so I have installed it manually.

Now, PHP on MacOS does not use php.ini by default, however it does provide a default `/etc/php.ini.default` which you can use to get started:

```
cd /etc
sudo cp php.ini.default php.ini
echo "extension=/home/$USER/swoole/modules/swoole.so" | sudo tee -a php.ini
```

Then, to check if it's installed, you can run `php -i | grep swoole`

If you see something like this, it succeeded:

```
swoole
swoole support => enabled
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
swoole.use_namespace => On => On
swoole.use_shortname => On => On
```

**Comment by lezhnev74** [comment]
Well, on my MacOS 10.13.4 both automatic ways failed (brew and pecl). However the manual way also resulted in the error:
```
In file included from /Users/dmitriylezhnev/Code/tests/swoole-src/src/coroutine/boost.cc:2:
In file included from /Users/dmitriylezhnev/Code/tests/swoole-src/include/context.h:8:
/usr/include/ucontext.h:43:2: error: The deprecated ucontext routines require _XOPEN_SOURCE to be defined
#error The deprecated ucontext routines require _XOPEN_SOURCE to be defined
 ^
1 error generated.
make: *** [src/coroutine/boost.lo] Error 1
```

Is it something I need to install?

**Comment by avramovic** [comment]
@lezhnev74 Try to update XCode or take a look at this: https://stackoverflow.com/a/6330053/964777

**Comment by sshymko** [comment]
Looks like installation via PECL is the only option now:
```
pecl install swoole
```

Note that you need to [install PEAR](https://jason.pureconcepts.net/2012/10/install-pear-pecl-mac-os-x/) to get PECL.

**Comment by ikandars** [comment]
I have no luck install via home brew or pecl. So heres my step to install Swoole manually:

Make sure you php installed on your osx
```
php -v
phpize -v
```

Go to temporary folder
```
cd /tmp/
```

Download the source code
```
wget "https://github.com/swoole/swoole-src/archive/v4.0.3.tar.gz" -O swoole.tar.gz
```

Extract the file
```
tar xvzf swoole.tar.gz
```

Go to source folder
```
cd swoole-src-4.0.3/
```

Prepare the build environment for a PHP extension
```
phpize
```

Add configuration paramaters as needed
```
./configure
```

Run make. This will take some time. A successful result of make is swoole/module/swoole.so
make

Create Swoole extension directory
```
mkdir -p /usr/local/opt/php71-swoole/
```

Install the swoole into the PHP extensions directory
```
cp modules/swoole.so /usr/local/opt/php71-swoole/
```

Create config file for Swoole
```
touch /usr/local/etc/php/7.1/conf.d/ext-swoole.ini
echo "extension=/usr/local/opt/php71-swoole/swoole.so" > /usr/local/etc/php/7.1/conf.d/ext-swoole.ini
```
check if the swoole extension has been enabled
```
php -m | grep swoole
```

If succeed, tt will send you output something like "swoole"
