### ISSUE TITLE
无法序列化存在循环引用的类，即便循环引用的属性已在__sleep函数中排除

### ISSUE THREAD

**Issue by SyuTingSong** [swoole/swoole-src#1390]
因为我无法reopen #1296 号issue，所以只好重新提一个。

经过和tideways方面调试，确认这个问题和tideways扩展无关，即使关闭tideways扩展，也有可能触发这个问题。

我制作了一个新的[测试用例][1]。在这个例子中，[`a.php`][2]中有循环引用的类，并以`__sleep`魔术方法排除掉循环引用的属性，`t.php`被`require_once`包含进来。运行`a.php`，`swoole_serialize::pack`会抛出循环引用的异常。但如果关闭opcahe，或者删除`t.php`中的类中的任意一个方法或属性甚至常量，此异常都不再抛出。

为了方便重现此问题，我基于PHP7.1制作了一个[docker镜像][3]，可以运行
```
docker run -ti syutingsong/swoole-debug
```
启动容器。在此容器中，swoole的源码用的是Github上的1.9.22版，下载到了`/tmp`目录下；php配置文件在`/usr/local/etc/php/conf.d`中；`a.php`和`t.php`文件在`/root`目录。

[1]: https://github.com/SyuTingSong/swoole-debug/tree/master/fs/root
[2]: https://github.com/SyuTingSong/swoole-debug/blob/master/fs/root/a.php#L13
[3]: https://hub.docker.com/r/syutingsong/swoole-debug/

**Comment by GXhua** [comment]
不好意思 之前你说和其他扩展冲突 我就没再关注这事，感谢你非常详细的测试用例，目前确认到是opcache扩展的sse指令有问题 把内存写坏了 我想想怎么解决

**Comment by GXhua** [comment]
已修复  并提交到了1.9分支
