### ISSUE TITLE
Promise and yield

### ISSUE THREAD

**Issue by sinasalek** [swoole/swoole-src#1392]
Is there any plan to use yield and promise to avoid callback hell in swoole?

**Comment by doubaokun** [comment]
Hi Sina,

Swoole 2.0 supports the built-in coroutine, and you can use fully synchronized code to implement asynchronous programs.

Please check the examples in the README file.

**Comment by sinasalek** [comment]
Thanks for the quick response, yes i knew about coroutines, but that still requires callback. is there a reason why you decided to use callbacks instead of yield or promise? also is there any technical documentation regarding how coroutines works?
