### ISSUE TITLE
MySQL transcation

### ISSUE THREAD

**Issue by sinasalek** [swoole/swoole-src#1394]
Does swoole mysql supports MySQL transactions? if not is there any workaround? some libraries on nodejs solve it by using a new connection for each request

**Comment by sinasalek** [comment]
Here is an interesting example : https://github.com/amphp/mysql/issues/24

**Comment by doubaokun** [comment]
Please check the example: https://github.com/swoole/swoole-src/blob/master/examples/mysql/transaction.php

I would suggest to ask usage related questions at https://stackoverflow.com with the tag 'Swoole'.
