### ISSUE TITLE
onWorkerExit 事件无效

### ISSUE THREAD

**Issue by breath-co2** [swoole/swoole-src#1396]
1. What did you do? If possible, provide a recipe for reproducing the error.
按 https://wiki.swoole.com/wiki/page/775.html 页面提供的信息，在各种版本上尝试都没有触发 onWorkerExit 事件

2. What did you expect to see?
能够正确的触发此事件

3. What did you see instead?
onWorkerStop 事件会被正确触发，但是 onWorkerExit 没有被触发过

4. What version of Swoole are you using (`php --ri swoole`)?
1.9.22, 2.0.9

5. What is your machine environment used (including version of kernel & php & gcc) ? 
mac, centos

6. If you are using ssl, what is your openssl version?
no

**Comment by matyhtf** [comment]
需要设置`reload_async => true `  来启用

https://wiki.swoole.com/wiki/page/791.html

**Comment by breath-co2** [comment]
好吧，还真不知道。。。。。我自己改了下 https://wiki.swoole.com/wiki/page/775.html 文件说明~~
