### ISSUE TITLE
Redis Server 的 onTask 接收数据不正常

### ISSUE THREAD

**Issue by Daryl-L** [swoole/swoole-src#1398]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```php
<?php
use Swoole\Redis\Server;
use Swoole\Coroutine\Redis;

$serv = new Server('0.0.0.0', 10086, SWOOLE_PROCESS, SWOOLE_SOCK_TCP);
$serv->set(['task_worker_num' => 1]);
$serv->on('task', function ($serv, $taskId, $data) {
    var_dump($data);
});
$serv->on('finish', function ($serv, $taskId, $data) { });
$serv->setHandler('set', function ($fd, $data) {
    global $serv;
    if (is_array($data)) {
        $serv->task($data);
    }
    $serv->send($fd, Server::format(Server::INT, 1));
});
$serv->start();
```

2. What did you expect to see?

如果我执行 `set a a` 我希望看到一个数组被 `var_dump` 出来。

3. What did you see instead?

```bash
int(3)
```

4. What version of Swoole are you using (`php --ri swoole`)?

swoole

swoole support => enabled
Version => 2.0.10
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
pcre => enabled
zlib => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 

macOS 10.12.6
php 7.1.9

gcc
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

6. If you are using ssl, what is your openssl version?

not use.

**Comment by matyhtf** [comment]
`onTask`的参数顺序搞错了。
https://wiki.swoole.com/wiki/page/54.html
