### ISSUE TITLE
configure 增加 enable-openssl 参数，make时错误

### ISSUE THREAD

**Issue by jianzhenchen** [swoole/swoole-src#1408]
PHP：7.1.9
Swoole-src:1.9

./configure --enable-swoole-debug --enable-sockets --enable-async-mysql --enable-async-redis --enable-openssl
make

提示如下错误
/root/swoole-src/src/protocol/SSL.c:544: 错误：expected ‘)’ before ‘NGX_LOG_DEBUG_EVENT’
/root/swoole-src/src/protocol/SSL.c:544: 警告：格式字符串实参太少
make: *** [src/protocol/SSL.lo] 错误 1

切换到几天前的版本，安装正常，请检查。

**Comment by matyhtf** [comment]
已修复。
