### ISSUE TITLE
swoole协程http client 卡住

### ISSUE THREAD

**Issue by batcom** [swoole/swoole-src#1411]
$reponses = [];
        foreach ($urls as $url){
                $cli = new \Swoole\Coroutine\Http\Client('59.63.235.194', 80);
                $cli->setHeaders([
                    'Host' => "oytva6p7l.bkt.clouddn.com",
                    "User-Agent" => 'Chrome/49.0.2587.3',
                ]);
                $cli->set([ 'timeout' => 1]);
                $cli->setMethod("HEAD");
                $cli->execute('/'.$url);
                $reponses[] = $cli->headers['content-length'];
                $cli->close();
                unset($cli);
        }

不知道和原因，以上代码会卡住

**Comment by matyhtf** [comment]
`HEAD`方法不支持`Content-Length`导致，已修复。参见：https://github.com/swoole/swoole-src/issues/1412
