### ISSUE TITLE
协程2.0.10版本 dispatch_mode设置为1 或 2则会出现 WARNING swProcessPool_wait: [Manager]unknow worker[pid=-1]

### ISSUE THREAD

**Issue by HongjiangHuang** [swoole/swoole-src#1413]
当dispatch_mode 设置为 非 3选项时。
![image](https://user-images.githubusercontent.com/20190812/33892233-3cb98212-df93-11e7-8b0e-af2b317c7f08.png)
如图显示的错误.

![image](https://user-images.githubusercontent.com/20190812/33892272-5849eac6-df93-11e7-87bf-fd4a7b61a3a5.png)
![image](https://user-images.githubusercontent.com/20190812/33892277-5d873098-df93-11e7-80ea-1c5cf4b88f22.png)
![Uploading image.png…]()

**Comment by matyhtf** [comment]
请使用`2.0.10-rc3`版本

**Comment by HongjiangHuang** [comment]
使用的就是2.0.10-rc3 版本

**Comment by matyhtf** [comment]
请重新确认一下版本号码

**Comment by HongjiangHuang** [comment]
版本号没问题.已经发现重现方式. 应该是mysql服务器最大连接数超出了server并发数导致的.
把mysql的最大连接数增加就解决了以下是压测代码
![image](https://user-images.githubusercontent.com/20190812/34069744-0c0fcaac-e292-11e7-8003-b8ced28a2953.png)
![image](https://user-images.githubusercontent.com/20190812/34069750-16723a16-e292-11e7-9be9-3027ad149f8d.png)
ab -c 100 -n 1000 -k http://127.0.0.1:9999/
![image](https://user-images.githubusercontent.com/20190812/34069757-5e26617a-e292-11e7-80ca-b250bf2be4c4.png)

**Comment by HongjiangHuang** [comment]
只有再dispatch_mode=2 或 1 的时候会发生 为3时正常

**Comment by HongjiangHuang** [comment]
执行 server->reload 也会

**Comment by HongjiangHuang** [comment]
dispatch_mode无论为1 2 还是3 当执行 server reload 时. 也会发生

**Comment by HongjiangHuang** [comment]
通过dtrace 调试打印出来的信息

**Comment by matyhtf** [comment]
无法重现此问题。可能是由其他扩展引起的，请尝试`php -m`找出对应的扩展。`swoole`的`manager`进程并未开启`pthread`多线程
