### ISSUE TITLE
\Swoole\Coroutine::call_user_func_array($callback, $params);

### ISSUE THREAD

**Issue by HongjiangHuang** [swoole/swoole-src#1420]
当call_user_func_array调用的method 属性为protected时会报错.
跟原生call_user_func_array不兼容
比如. 原生的call_user_func_array 如果在当前类调用 protected 的method 是可以调用成功的。
![image](https://user-images.githubusercontent.com/20190812/34037156-a2ea469e-e1c2-11e7-92cf-54617305d5a8.png)
而替换成
\Swoole\Coroutine::call_user_func_array($callback, $params);
后
![image](https://user-images.githubusercontent.com/20190812/34037185-be42383e-e1c2-11e7-99d3-87b6fab06b28.png)
![image](https://user-images.githubusercontent.com/20190812/34037193-c7f7a49a-e1c2-11e7-8e2e-01d97c496660.png)
报错。

**Comment by yangxikun** [comment]
swoole版本、php版本？

**Comment by HongjiangHuang** [comment]
swoole-2.0.10-rc3
php 7.1
