### ISSUE TITLE
2.0.10版本onrequest内执行\Swoole\Coroutine\Redis后worker没处理完前就重启

### ISSUE THREAD

**Issue by lgang06** [swoole/swoole-src#1421]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
根据[#1415](1415)反馈的结果升级到2.0.10后
2.0.10版本下使用\Swoole\Coroutine\Redis,在执行到max_request次数时，当触发协程切换时，当前处理的请求直接丢弃，worker重启。客户端表现为无应答，直至请求处理超时

```php
$http = new swoole_http_server("0.0.0.0", 9701);

$setConfig = array(
            'worker_num' => 1, 
            'daemonize' => 0,
            'max_request' => 1, 
            'buffer_output_size' => 64 * 1024 * 1024,
            'package_max_length' => 64 * 1024 * 1024,
        );
$http->set($setConfig);
$http->on("start", function ($server) {
    echo "Swoole http server is started at http://127.0.0.1:9701\n";
});

$http->on("request", function ($request, $response) {
    $redis = new \Swoole\Coroutine\Redis();
var_dump(1);
    $res = $redis->connect('10.10.80.195', 52020);
 #   $data = $redis->set('test_test', str_repeat('-=1234567890-=', 3) . microtime(true));
    $data  = $redis->get('test_test');
var_dump($data);
    #$redis->expire('test_test', 100);
    #$redis->get('test_test');
    $response->header("Content-Type", "text/plain");
    $redis->close();
    $response->end('ok');
});

$http->start();
```
客户端直接执行 curl "127.0.0.1:9701"
2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?
swoole

swoole support => enabled
Version => 2.0.10
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => 1 => 1
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 
CentOS release 6.5 (Final): 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
PHP:7.0.12 | 7.1.9
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)

6. If you are using ssl, what is your openssl version?

**Comment by matyhtf** [comment]
启用 `reload_async` 试试。异步开启`max_request` 并不安全。
