### ISSUE TITLE
Please replace "127.0.0.1" address to "localhost" in guide

### ISSUE THREAD

**Issue by nskforward** [swoole/swoole-src#1422]
I tried to run swoole http server from the hello-world guide across Docker with custom network.
I always get "connection refused" error.
Fix is replacement "127.0.0.1" address to "localhost"

**Comment by noname007** [comment]
why not 0.0.0.0

**Comment by nskforward** [comment]
What is the difference?

**Comment by doubaokun** [comment]
The idea is limit the service access from the localhost since it is a simple hello world guide.
127.0.0.1 should be same as localhost if you have not modified the hosts file.
You can change it to be the public IP or private IP of the machine or instance if you like.
