### ISSUE TITLE
swoole make warning

### ISSUE THREAD

**Issue by gouchaoer** [swoole/swoole-src#1426]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
for commit:dfe877562410806640259a1f5bf7a5620db32e08
unzip swoole-src-master.zip
cd swoole-src-master
phpize
./configure --enable-coroutine --enable-mysqlnd --enable-debug
make

2. What did you expect to see?

3. What did you see instead?

```
/home/gou_chao/swoole-src-master/swoole_mysql.c: In function 'mysql_response':
/home/gou_chao/swoole-src-master/swoole_mysql.c:897:13: warning: 'len' may be used uninitialized in this function [-Wmaybe-uninitialized]
     ulong_t len;

```

4. What version of Swoole are you using (`php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ? 

centos7, php70, gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

6. If you are using ssl, what is your openssl version?

**Comment by matyhtf** [comment]
It has been fixed
