### ISSUE TITLE
swoole_client 支持访问https吗

### ISSUE THREAD

**Issue by a569922982** [swoole/swoole-src#1428]
swoole版本2.0.11
php版本7.0.26
![image](https://user-images.githubusercontent.com/11918919/34293788-e582205c-e740-11e7-9488-e0d1dd98cb57.png)

swoole_client 支持访问https吗?
http可以使用正常返回结果。但是https无任何结果，无法访问任何https。

![image](https://user-images.githubusercontent.com/11918919/34293743-c0d81ad6-e740-11e7-81c1-83945ea7ad57.png)

**Comment by matyhtf** [comment]
缺少参数。

```php
$cli = new swoole_client(SWOOLE_TCP | SWOOLE_SSL);
```

**Comment by a569922982** [comment]
![image](https://user-images.githubusercontent.com/11918919/34347034-2f50aa32-ea39-11e7-93a7-5a5291066439.png)
也不能使用啊。大神。无法访问的https。 @matyhtf
