### ISSUE TITLE
表字段是int,但swoole-mysql 查询出来的数据都是string ?

### ISSUE THREAD

**Issue by wuchuguang** [swoole/swoole-src#1430]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

表字段是int,但swoole-mysql 查询出来的数据都是string ?

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?

swoole

swoole support => enabled
Version => 2.0.9
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 

php 7.1.x

6. If you are using ssl, what is your openssl version?

**Comment by matyhtf** [comment]
MySQL 返回的就是字符串类型，你可以转为整型。

**Comment by yunnian** [comment]
现在 增加了strict_type参数 ，可参考：#1468
