### ISSUE TITLE
swoole_timer_after

### ISSUE THREAD

**Issue by livexk** [swoole/swoole-src#1432]
task 里面,swoole_timer_after重复调用(第一个运行完,再调用就不起作用了),只运行一次

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/blob/master/tests/swoole_timer/task_worker.phpt

官方的单元测试脚本无法重现你的问题。请按照 Issue 模板提交问题。贴出相关环境信息。贴出相关问题代码。
