### ISSUE TITLE
reload worker failed

### ISSUE THREAD

**Issue by hemin3260** [swoole/swoole-src#1434]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

http server，base模式。同时kill多个worker导致只能拉起一个worker。并且打乱内部逻辑，下次reload会失败或者部分失败。无论是否开启reload_async都出现此问题。
process 模式正常。
```
$pre = "test_reload_server";

$_server = new Swoole\Http\Server("0.0.0.0", 60003/*,SWOOLE_BASE*/);
$_server->set([
        'max_conn'=>1000,
        "worker_num"=>4,
        "reactor_num"=>1,
        "max_request"=>10000,
        "open_cpu_affinity"=>1,
        //"reload_async"=>true
]);
swoole_async_set(['enable_reuse_port'=>true]);

$_server->on('Request', function ($request, $response) {
        $response->end(sprintf("req:%s ip:%s port:%s",$request->rawContent(),$request->server['remote_addr'],$request->server['remote_port']));

});


$_server->on('Start', function ($server) {
        global $pre;
        swoole_set_process_name($pre."_master");
});

$_server->on('ManagerStart', function ($manager) {
        global $pre;
        swoole_set_process_name($pre."_manager");
});

$_server->on('WorkerStart', function ($worker) {
        global $pre;
        swoole_set_process_name($pre."_worker");
});

$_server->start();

```
kill -9 worker1 && kill -9 worker2
此种情况会出现在触发系统oom时，强制kill掉多个worker

2. What did you expect to see?
worker 1 和 worker2 正常拉起，reload成功

3. What did you see instead?
![image](https://user-images.githubusercontent.com/8153418/34427617-4c751920-ec7f-11e7-9a06-3920f009510d.png)

![image](https://user-images.githubusercontent.com/8153418/34427618-51eb818c-ec7f-11e7-8d11-bec9b493e7d7.png)

4. What version of Swoole are you using (`php --ri swoole`)?
![image](https://user-images.githubusercontent.com/8153418/34427626-6a5efc8a-ec7f-11e7-81dc-b9dfa68a5ecc.png)

5. What is your machine environment used (including version of kernel & php & gcc) ? 
`php 5.6.24
gcc version 4.4.6 20110731 (Red Hat 4.4.6-4) (GCC)
Linux  2.6.32.43  #1 SMP Fri Jun 27 14:18:34 CST 2014 x86_64 x86_64 x86_64 GNU/Linux
`

6. If you are using ssl, what is your openssl version?

`
OpenSSL 1.0.1e-fips 11 Feb 2013
`

**Comment by twose** [comment]
Before answering your question I have to be the bearers of bad news, the latest version of swoole no longer supports PHP5. In fact, I think PHP7 is the best choice of every PHPer.

**Comment by matyhtf** [comment]
请使用 PHP7 + Swoole 2.0.12 版本，经过测试未发现上述问题。
