### ISSUE TITLE
php 编译安装swoole后 php-fpm启动失败

### ISSUE THREAD

**Issue by siburuxue** [swoole/swoole-src#1436]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ? 

6. If you are using ssl, what is your openssl version?

**Comment by siburuxue** [comment]
环境 centos7 php5.5 编译安装后添加至php.ini文件 重启php-fpm服务提示：Starting php-fpm /etc/init.d/php-fpm: line 53: 4741 Segmentation fault $php_fpm_BIN --daemonize $php_opts failed

**Comment by matyhtf** [comment]
不再支持 PHP5 ，请使用 PHP7 + Swoole 2.0.12
