### ISSUE TITLE
Undefined error constant SW_ERROR_WEBSOCKET_BAD_CLIENT

### ISSUE THREAD

**Issue by sinasalek** [swoole/swoole-src#1438]
Should i be able to access SW_ERROR_* constants? the limited information i was able to find via google indicates that i should be able to use error constants but so far doesn't work

```
ERROR   zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught ErrorException: Use of undefined constant SW_ERROR_WEBSOCKET_BAD_CLIENT - assumed 'SW_ERROR_WEBSOCKET_BAD_CLIENT'
```
```php
foreach ($server->table as $u) {
  try {
	$server->push($u['fd'], $frame->data);//消息广播给所有客户端
  } catch (\ErrorException $e) {
	if ($e->getCode() == SW_ERROR_WEBSOCKET_BAD_CLIENT) {
	  $server->table->del($u['fd']);
	} else {
	  throw $e;
	}
  }
}
```

**Comment by sinasalek** [comment]
I'm using Swoole 2.0.10 and PHP 7.1

**Comment by twose** [comment]
You can find error enum in https://github.com/swoole/swoole-src/blob/master/include/error.h
But I'm not sure if it should have supported to use in PHP.

**Comment by sinasalek** [comment]
Yes i found that, then i must define it myself as you suggested. but it's a bit odd. If that's really the case i must create a feature request.

**Comment by matyhtf** [comment]
Thank you for your feedback, We will add these constants in the next version (2.0.13)
