### ISSUE TITLE
Coroutine HTTP Client throw a Segmentation fault when set an non array value to set() method

### ISSUE THREAD

**Issue by huangzhhui** [swoole/swoole-src#1439]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
When set an non array value to $client->set() method, will throw a Segmentation fault.
```
<?php
use Swoole\Coroutine;
use Swoole\Coroutine\Http\Client as CoHttpClient;

Coroutine::create(function () {
    $ip = swoole_async_dns_lookup_coro('www.baidu.com');
    $client = new CoHttpClient($ip, 80);
    $client->set(null);
    $client->get('/');
    $client->close();
    var_dump($client->body);
});
```

2. What did you expect to see?
not an error

3. What did you see instead?
Segmentation fault (core dumped)

4. What version of Swoole are you using (`php --ri swoole`)?
```
swoole support => enabled
Version => 2.0.12
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ? 
Kernel: 3.10.0-229.el7.x86_64
PHP: 7.1.12
GCC: gcc version 4.9.2 (Debian 4.9.2-10)

6. If you are using ssl, what is your openssl version?
none

**Comment by twose** [comment]
why not using this
```php 
$client->set(null ?? []);
```

**Comment by huangzhhui** [comment]
@twose I already wrote the code like this, but it is also a bug right ?
