### ISSUE TITLE
Task功能有问题.

### ISSUE THREAD

**Issue by ValliMoceniche** [swoole/swoole-src#144]
测试Task功能,输出成这样
代码请看后面.

210009854 -> OK...OK
210009796 -> OK...OK
210009858 -> OK...OK
210009862 -> OK...OK
210009800 -> OK...OK
210009804 -> OK...OK
210009808 -> OK...OK
210009812 -> OK...OK
210009866 -> OK...OK
210009870 -> OK...OK
210009874 -> OK...OK
210009878 -> OK...OK
210009816 -> OK...OK
210009820 -> OK...OK
210009824 -> OK...OK
210009828 -> OK...OK
210009882 -> OK...OK
210009832 -> OK...OK
210009886210009887210009888210009889210009890210009891210009892210009893210009894210009895210009896210009897210009898210009899210009900210009901210009902210009903210009904210009905210009906210009907210009908210009909210009910210009911210009912210009913210009914210009915210009916210009917210009918210009919210009920210009921210009922210009923210009924210009925210009926210009927210009928210009929210009930210009931210009932210009933210009934210009935210009936210009937210009938210009939210009940210009941210009942210009943210009944210009945210009946210009947210009948210009949210009950210009951210009952210009953210009954210009955210009956210009957210009958210009959210009960210009961210009962210009963210009964210009965210009966210009967210009968210009969210009970210009971210009972210009973210009974210009975210009976210009977210009978210009979210009980210009981210009982210009983210009984210009985210009986210009987210009988210009989210009990210009991210009992210009993210009994210009995210009996210009997210009998210009999210010000 -> OK...OK
210009836 -> OK...OK
210009840 -> OK...OK
210009844 -> OK...OK
210009848 -> OK...OK
210009852 -> OK...OK
210009856 -> OK...OK
210009860 -> OK...OK
210009864 -> OK...OK
210009868 -> OK...OK
210009872 -> OK...OK
210009876 -> OK...OK
210009880 -> OK...OK
210009884 -> OK...OK

client 代码:
        foreach(range(1,10000) as $id)
        {
                $this->client->send( $id );
        }

服务器代码:
..........
$serv->set(array( 'task_worker_num' => 4));
............
$serv->on('Task',
        function  ($serv, $task_id, $from_id, $data)
        {
                sleep(rand(0,7));
                $serv->finish("$data -> OK");
        });

另外,如果把消息的数量加大10倍,会马上出现:

WARN	swTaskWorker_finish: TaskWorker: send result to worker failed. Error: Resource temporarily unavailable[11]

**Comment by matyhtf** [comment]
请使用最新的1.7.9-stable测试一下，看看是否还存在此问题。
