### ISSUE TITLE
编译后PHP启动出现warning

### ISSUE THREAD

**Issue by yoigo** [swoole/swoole-src#1441]
pecl 安装swoole之后 启动php-fpm 出现如下警告
<img width="653" alt="default" src="https://user-images.githubusercontent.com/14148784/34608008-2f40e096-f251-11e7-8140-b02142179a84.png">

PHP 7.1.10  + ubuntu 16.04

**Comment by motecshine** [comment]
make install

**Comment by matyhtf** [comment]
`20170718` 这个显然是 `PHP-7.2` 的信息，请检测编译`swoole.so`使用的`PHP`版本，和运行的是否一致。
