### ISSUE TITLE
Swoole\Http\Server swoole_http_server is same？

### ISSUE THREAD

**Issue by godtail** [swoole/swoole-src#1442]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    I see use `Swoole\Http\Server` but not `swoole_http_server` in readme document.

    It means i can use `Swoole\Server` or `Swoole\Client` too ? I want know how many class i can use by the namespace way.

2. What did you expect to see?

    Changelog about this.

3. What did you see instead?

    none.

4. What version of Swoole are you using (`php --ri swoole`)?

    none.

5. What is your machine environment used (including version of kernel & php & gcc) ? 

    none.

6. If you are using ssl, what is your openssl version?

    none.

**Comment by matyhtf** [comment]
Yes, `swoole_http_server` is an alias for `Swoole\Http\Server`

**Comment by matyhtf** [comment]
<table>
<thead>
<tr>
<th>Class</th>
<th>Alias</th>
</tr>
</thead>
<tbody>
<tr><td>swoole_server</td><td>Swoole\Server</td></tr>
<tr><td>swoole_client</td><td>Swoole\Client</td></tr>
<tr><td>swoole_process</td><td>Swoole\Process</td></tr>
<tr><td>swoole_timer</td><td>Swoole\Timer</td></tr>
<tr><td>swoole_table</td><td>Swoole\Table</td></tr>
<tr><td>swoole_lock</td><td>Swoole\Lock</td></tr>
<tr><td>swoole_atomic</td><td>Swoole\Atomic</td></tr>
<tr><td>swoole_buffer</td><td>Swoole\Buffer</td></tr>
<tr><td>swoole_redis</td><td>Swoole\Redis</td></tr>
<tr><td>swoole_event</td><td>Swoole\Event</td></tr>
<tr><td>swoole_mysql</td><td>Swoole\MySQL</td></tr>
<tr><td>swoole_mmap</td><td>Swoole\Mmap</td></tr>
<tr><td>swoole_channel</td><td>Swoole\Channel</td></tr>
<tr><td>swoole_serialize</td><td>Swoole\Serialize</td></tr>
<tr><td>swoole_http_server</td><td>Swoole\Http\Server</td></tr>
<tr><td>swoole_http_client</td><td>Swoole\Http\Client</td></tr>
<tr><td>swoole_http_request</td><td>Swoole\Http\Request</td></tr>
<tr><td>swoole_http_response</td><td>Swoole\Http\Response</td></tr>
<tr><td>swoole_websocket_server</td><td>Swoole\WebSocket\Server</td></tr>
</tbody>
</table>

**Comment by godtail** [comment]
Thanks, It's excellent.

**Comment by twose** [comment]
| Class                      | Alias                           |
| -------------------------- | ------------------------------- |
| swoole_server              | Swoole\\Server                  |
| swoole_timer               | Swoole\\Timer                   |
| swoole_event               | Swoole\\Event                   |
| swoole_async               | Swoole\\Async                   |
| swoole_connection_iterator | Swoole\\Connection\\Iterator    |
| swoole_exception           | Swoole\\Exception               |
| swoole_atomic              | Swoole\\Atomic                  |
| swoole_atomic_long         | Swoole\\Atomic\\Long            |
| swoole_buffer              | Swoole\\Buffer                  |
| swoole_channel             | Swoole\\Channel                 |
| swoole_client              | Swoole\\Client                  |
| swoole_client_coro         | Swoole\\Client                  |
| swoole_http_client         | Swoole\\Http\\Client            |
| swoole_http_client_coro    | Swoole\\Coroutine\\Http\\Client |
| swoole_http_server         | Swoole\\Http\\Server            |
| swoole_http_response       | Swoole\\Http\\Response          |
| swoole_http_request        | Swoole\\Http\\Request           |
| swoole_http2_client        | Swoole\\Http2\\Client           |
| swoole_http2_response      | Swoole\\Http2\\Response         |
| swoole_lock                | Swoole\\Lock                    |
| swoole_mmap                | Swoole\\Mmap                    |
| swoole_mysql               | Swoole\\MySQL                   |
| swoole_mysql_exception     | Swoole\\MySQL\\Exception        |
| swoole_process             | Swoole\\Process                 |
| swoole_redis               | Swoole\\Redis                   |
| swoole_redis_server        | Swoole\\Redis\\Server           |
| swoole_serialize           | Swoole\\Serialize               |
| swoole_server_port         | Swoole\\Server\\Port            |
| swoole_table               | Swoole\\Table                   |
| swoole_table_row           | Swoole\\Table\\Row              |
| swoole_websocket_server    | Swoole\\WebSocket\\Server       |
| swoole_websocket_frame     | Swoole\\WebSocket\\Frame        |

replace ```SWOOLE_CLASS_ALIAS\(([\w_]+), *"([\w\\]+)"\);``` to  ```|$1|$2|```

it's full-fledged version.
Rango can consider completing Alias for coroutine Class.
