### ISSUE TITLE
mysql 异步查询卡住

### ISSUE THREAD

**Issue by batcom** [swoole/swoole-src#1443]
db->connect($server, function ($db, $r) {
    if ($r === false) {
        var_dump($db->connect_errno, $db->connect_error);
        die;
    }
    $i=0;
    while ($i>2) {
        $sql = "select reg_num,intcls from shangbiao limit 0,10";
        $db->query($sql, function (swoole_mysql $db, $r) {
            if ($r === false) {
                var_dump($db->error, $db->errno);
            } elseif ($r === true) {
                var_dump($db->affected_rows, $db->insert_id);
            }
            var_dump($r);
//            $db->close();
        });
        $i++;
    }
});

如果有使用错误请告知，已精简到最小了.就是发两边查询而已，如果不套while就可以，不明白为什么，否则如何并发呢?

**Comment by twose** [comment]
```php
$db->connect($server, function ($db, $r) {
    if ($r === false) {
        var_dump($db->connect_errno, $db->connect_error);
        die;
    }
    $i = 0;
    while ($i > 2) {
        $sql = "select reg_num,intcls from shangbiao limit 0,10";
        $db->query($sql, function (swoole_mysql $db, $r) {
            if ($r === false) {
                var_dump($db->error, $db->errno);
            } elseif ($r === true) {
                var_dump($db->affected_rows, $db->insert_id);
            }
            var_dump($r);
            // $db->close();
        });
        $i++;
    }
});
```
重新贴一下你的代码,编辑器支持md的啊喂.
还有while那句如何成立?不应该是<2?
