### ISSUE TITLE
How can I solve redirect in concurrent(multi) requests?

### ISSUE THREAD

**Issue by twose** [swoole/swoole-src#1446]
这个说起来比较复杂
根据 [#1314](https://github.com/swoole/swoole-src/issues/1314)
client没有底层实现的自动跟踪重定向,需要自己通过header中的location来重定向
在Coroutine Client中, defer特性可以实现多个请求并发, 但前提条件是这些请求是提前被设定好的.
这样一次并发请求, 网络IO的时间就接近于 ```MAX([请求1,请求2,请求3,....])```
但是如果在并发中请求1遭遇了重定向,就需要new一个client来重新请求.
那么网络IO时间就变成了 ```MAX([请求1,请求2,请求3,....]) + 重定向请求```

但是在一般使用的curl情境下, 设置CURLOPT_FOLLOWLOCATION自动实现了follow redirect,
使用curl_multi_*时也无需关心这一问题, 甚至可以在并发请求的过程中加入新的请求到并发队列中.
不过curl_multi使用的是select.
这样网络IO时间可能就等于``` MAX([请求1+重定向请求,请求2,请求3,....])```

想知道swoole能否从底层解决这一问题? 还是说这一问题并不重要?

**Comment by matyhtf** [comment]
协程版本，使用 PHP 代码实现重定向并不复杂，请使用 PHP 代码实现。
