### ISSUE TITLE
I hope Mysql query can return the data with type.

### ISSUE THREAD

**Issue by twose** [swoole/swoole-src#1447]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

### PDO
```php
$db = new \PDO('mysql:dbname='.$options['database'].';host='.$options['host'], $options['user'], $options['password']);
$db->setAttribute(\PDO::ATTR_EMULATE_PREPARES, false);
$r = ($db->query('SELECT cid FROM `user` LIMIT 1', \PDO::FETCH_ASSOC))->fetch();
var_dump($r);
```
```php
array(1) {
  ["cid"]=>
  int(16)
}
```

### Swoole
```php
co::create(function () use ($options) {
    $db = new \Swoole\Coroutine\Mysql();
    $db->connect($options);
    $r = $db->query('SELECT cid FROM `user` LIMIT 1');
    var_dump($r[0]);
    
    exit();
});
```

```php
array(1) {
  ["cid"]=>
  string(2) "16"
}
```

2. What did you expect to see?
like PDO.
```php
array(1) {
  ["cid"]=>
  int(16)
}
```

**Comment by gouchaoer** [comment]
that's not pdo's default implement
you hope to add a option like pdo

**Comment by twose** [comment]
@gouchaoer Yes, but in the famous article [The 2018 Guide to Building Secure PHP Software](https://paragonie.com/blog/2017/12/2018-guide-building-secure-php-software), it said that:
> make sure you're [not using emulated prepared statements](https://stackoverflow.com/questions/134099/are-pdo-prepared-statements-sufficient-to-prevent-sql-injection/12202218#12202218).

so, if MySQL version support prepares the statement, we should always make it enable. The strong-type data value is one of the good welfare of it.
I always want to stay everything the same instead of such changes. The best language should realize the best way.

**Comment by yunnian** [comment]
#1468 
you can use the  'strict_type => true'  ,like this : 

$swoole_mysql = new Swoole\Coroutine\MySQL();
$swoole_mysql->connect([
    'host' => '127.0.0.1',
    'port' => 3306,
    'user' => 'user',
    'password' => 'pass',
    'database' => 'test',
    'strict_type' => true
]);

**Comment by twose** [comment]
@yunnian You are so kind, thank you very much.
