### ISSUE TITLE
Can't run examples on PHP 7.2

### ISSUE THREAD

**Issue by gillygilly** [swoole/swoole-src#1456]
Thanks for the great work. It seems that we can finally get rid of node.js and make our codes 100% PHP by help of Swoole. I just can't imagine what I can do with Swoole! But I got some errors while I wanted to test it.

I've installed Swoole on PHP 7.2. It seems that it doesn't work at all. I tried to compile from source or pour from homebrew for several times, nothing changed.

macOS 10.12.6
PHP 7.2.1 (compiled from source)
Swoole 2.0.7 (compiled from source / poured by brew)

swoole info from `$ php -i`:

swoole support => enabled
Version => 2.0.7
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
rwlock => enabled
async http/websocket client => enabled
pcre => enabled
zlib => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
swoole.use_namespace => On => On

-----------------
As I said, none of the examples in the readme.md works.
After a few tests, it seems that even following line throws an error:

    $serv = new swoole_server('127.0.0.1', 9501);

Here is the error I get by running every sample:

Assertion failed: (((ht)->gc.refcount == 1) || ((ht)->u.flags & (1<<6))), function _zend_hash_index_add_or_update_i, file /private/tmp/php72-20180109-45951-ilcqfu/php-7.2.1/Zend/zend_hash.c, line 712.
Abort trap: 6
-----------------
Note that /private/tmp/php72-20180109-45951-ilcqfu/php-7.2.1/Zend/ directory doesn't exists at all. I tried to create that directory, but same error happened again.

Thanks.

**Comment by gillygilly** [comment]
I recompiled using PECL, it works now.
It seems that brew's formula is corrupted.

**Comment by matyhtf** [comment]
The latest version (2.0.12) is compatible with PHP7.2
