### ISSUE TITLE
MySQL 8.0.3 swoole_mysql::escape 方法 core dump

### ISSUE THREAD

**Issue by zcmzc** [swoole/swoole-src#1459]
切回 MySQL 5.5版本没问题

**Comment by zcmzc** [comment]
![image](https://user-images.githubusercontent.com/28561563/35181887-96c70bd6-fe05-11e7-85e5-4adf921320d3.png)
php 7.2.1
gcc 4.8.5
Linux VM_139_137_centos 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zcmzc** [comment]
sssss 是escape 参数 , swoole 2.0.10

**Comment by twose** [comment]
哇靠这么先进的吗, 8还没稳定吧, 生产环境不悬吗.
顺便拉一下最新版的分支编译吧, 还有就是作者主要精力应该在coroutine上, 而且我觉得escape方法相较于参数化并不完美.
