### ISSUE TITLE
Client Side Websocket example code?

### ISSUE THREAD

**Issue by daslicht** [swoole/swoole-src#1460]
Hi,
is there somewhere an example for client side code when using swoole websockets please?
| Marc

**Comment by matyhtf** [comment]
* sync-client : <https://github.com/swoole/swoole-src/blob/1.9/examples/websocket/client.php>
* async-client : <https://github.com/swoole/swoole-src/blob/1.9/examples/websocket/async_client.php>

**Comment by daslicht** [comment]
i see, so it is all php , no JS client

**Comment by matyhtf** [comment]
JS Client : <https://github.com/swoole/swoole-src/blob/master/examples/websocket/client.html>

```js
var wsServer = 'ws://127.0.0.1:9501';
var websocket = new WebSocket(wsServer); 
websocket.onopen = function (evt) { 
	console.log("Connected to WebSocket server.");
}; 
websocket.onclose = function (evt) { 
	console.log("Disconnected"); 
}; 
websocket.onmessage = function (evt) { 
	console.log('Retrieved data from server: ' + evt.data); 
}; 
websocket.onerror = function (evt, e) {
	console.log('Error occured: ' + evt.data);
};
```

**Comment by daslicht** [comment]
wao , awesome ! Thank you very much !

**Comment by Lukaum** [comment]
How can i send the data, for fire onmessage?

data = {
 'name' : 'test',
 'age': 99
}
websocket.send(JSON.stringify(data));
