### ISSUE TITLE
关于 心跳检测  机制 

### ISSUE THREAD

**Issue by chuanhaisoft** [swoole/swoole-src#1461]
心跳检测  机制 是根据 最后的收包时间检测的么？（文档中写的是），如果是的话这个时间从哪里看到
还是 根据  last_time  这个时间检测的？last_time 是最后发包时间

last_time  是指 $serv->connection_info($fd);  中的last_time

 $serv->connection_info($fd);  中只有   connect_time 和 last_time ，并没有最后收包时间

**Comment by matyhtf** [comment]
`last_time` 是最近一次收包时间。文档描述存在错误，谢谢反馈。
