### ISSUE TITLE
swoole2.0.12 use gethostbyname Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ghzhangyupeng** [swoole/swoole-src#1462]
php -v PHP 7.0.13
php --ri swoole Version => 2.0.12
centos7.0 Linux version 3.10.0-327.36.3.el7.x86_64
gcc:版本 4.8.5
code:
use Swoole\Coroutine as co;
$ip = co::gethostbyname("www.baidu.com");
报错：
段错误

**Comment by sagargulati** [comment]
Please post the error?

**Comment by matyhtf** [comment]
请测试一下 github master 分支代码是否还存在此问题

**Comment by sagargulati** [comment]
"Please check if there is still a problem with the github master branch code"
That doesn't reproduce much information for error.

**Comment by matyhtf** [comment]
The latest version has fixed this bug.
