### ISSUE TITLE
swoole/swoole-docs 不更新了吗?

### ISSUE THREAD

**Issue by zhuyuejianke** [swoole/swoole-src#1463]
目前我找到了4个文档，我都佩服我自己：
中文版：https://wiki.swoole.com/ 
英文版：https://www.swoole.co.uk/docs/
github版：https://github.com/swoole/swoole-docs 
ideHelper版：https://github.com/eaglewu/swoole-ide-helper
这三个版本的现状是，中文版万年不更新，英文版大块缺内容，github版貌似最全(虽然也有错误的url)，但是好像也不更新了，ideHelper版不能算是文档最多算是个提示。

我希望持续更新github版，毕竟这个版本还算全面，bug最少。

没有文档的swoole，让我们看C源码？还是等着大神亲自解答？

**Comment by twose** [comment]
对于新手的话文档确实难啃, 但是中文官方wiki还是勉强够看, 现在swoole主要更新的都是coroutine部分(最近就更新了一些内容, 看项目commit就可以知道项目大概的前进方向), 韩大去年也在微博里说了swoole重心全部转移到了2.0的协程版本上, 异步那边更新少也很正常.
可以看看基于swoole的一些框架的实现, 还有当前项目下的/test里的测试脚本.
swoole定义是高级PHPer的工具, 文档的缺失确实对大多数传统PHPer不友好, 而且韩大一个人亲力亲为维护这么多东西, 肯定是忙不过来的, 韩大又把swoole的后续崛起寄托在一定的商业化上面, 也不知道是不是好事.
维基或者group社区的代码都很老了, 使用体验也不好, 其它开发者也不愿意花时间贡献力量. swoole的群很多, 但可能都是进去学习的, 一堆框架作者只知道推销自己的框架, 也不愿意解答具体的问题, 基本上新人问一个问题很快就被淹没了, 没人解答, 只能等韩大什么时候会跳出来解答一二, 不过也是杯水车薪.

**Comment by matyhtf** [comment]
请首先阅读 wiki.swoole.com 文档，总量超过数百页，通读一遍再来评价。
