### ISSUE TITLE
Can Swoole handle HTTPS/WSS requests?

### ISSUE THREAD

**Issue by wodawi** [swoole/swoole-src#1467]
Can Swoole handle HTTPS and WSS requests internally, without using reverse proxy such as nginx?
Using nginx as a reverse proxy to Swoole, slows down the requests.

**Comment by guoyu07** [comment]
swoole can handle https and wss, i have used it in talk server with https and wss.
Using nginx as swoole's proxy, check: http://nginx.org/en/docs/http/websocket.html

**Comment by twose** [comment]
In the wiki, it said that: swoole_http_server is not completely supporting Http protocol, it is recommended only use it as an application server, then add Nginx in the front end as a proxy.
In fact, almost all base function is ready for you, but we want to be on the safe side, we use Nginx.

**Comment by wodawi** [comment]
@twose @guoyu07 
It seems that we better to go with nginx, at least for now. Thanks.
