### ISSUE TITLE
running swole http_server

### ISSUE THREAD

**Issue by mich4s** [swoole/swoole-src#1470]
I'm very new to swoole. My question is super newbie. How to run swoole application? Do I have to do this by nginx or php file.php? I can't find the info and nothing isn't working for me :/

**Comment by wodawi** [comment]
You should run Swoole in terminal.
Just install the extension, check php info ($ php -i) and make sure it's enabled.
Then run the php code ($ php file.php)
There are examples here: https://github.com/swoole/swoole-src

**Comment by fage1151** [comment]
`php file.php`
