### ISSUE TITLE
swoole_event_wait(): Aio Error: Unknown error: 705[705] in Unknown on line

### ISSUE THREAD

**Issue by gaecom** [swoole/swoole-src#1472]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

PHP 7.2.1 (cli) (built: Jan  5 2018 17:34:14) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologie

swoole_async_set(array(
    'disable_dns_cache' => true,
));
// Set the DNS server list
swoole_async_set(array(
    'dns_server' => '8.8.8.8',
));
// Lookup using random DNS server
swoole_async_set(array(
    'dns_lookup_random' => true,
));

// Lookup the DNS of www.google.com
swoole_async_dns_lookup("www.google.com", function($host, $ip){
    echo "{$host} : {$ip}\n";
});

2. What did you expect to see?

www.google.com : ip地址

3. What did you see instead?

swoole_event_wait(): Aio Error: Unknown error: 705[705] in Unknown on line

PHP Warning:  swoole_event_wait(): Aio Error: Unknown error: 705[705] in Unknown on line 0

Warning: swoole_event_wait(): Aio Error: Unknown error: 705[705] in Unknown on line 0
www.google.com :

4. What version of Swoole are you using (`php --ri swoole`)?
swoole support => enabled
Version => 2.0.13
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
sockets => enabled
openssl => enabled
http2 => enabled
pcre => enabled
zlib => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 
macos x high seria
10.13.2 (17C88)

6. If you are using ssl, what is your openssl version?

OpenSSL 1.1.0g  2 Nov 2017

**Comment by yunnian** [comment]
感谢反馈 ，跟踪了下  好像是 inet_ntop调用失败了，等我找到具体原因 修复后再和你说

**Comment by yunnian** [comment]
#1474 
fixed
