### ISSUE TITLE
onRequest callback run before server onClose callback

### ISSUE THREAD

**Issue by malacca** [swoole/swoole-src#1473]
不晓得有没有没帮助，先报一下开发环境

系统环境： VirtualBox 虚拟机中安装 的 Centos7
php版本：7.1
swoole版本及配置

> swoole support => enabled
> Version => 2.0.12
> Author => tianfeng.han[email: mikan.tenny@gmail.com]
> epoll => enabled
> eventfd => enabled
> timerfd => enabled
> signalfd => enabled
> cpu affinity => enabled
> spinlock => enabled
> rwlock => enabled
> async http/websocket client => enabled
> Linux Native AIO => enabled
> pcre => enabled
> zlib => enabled
> mutex_timedlock => enabled
> pthread_barrier => enabled
> futex => enabled
> 
> Directive => Local Value => Master Value
> swoole.aio_thread_num => 2 => 2
> swoole.display_errors => On => On
> swoole.use_namespace => On => On
> swoole.fast_serialize => Off => Off
> swoole.unixsock_buffer_size => 8388608 => 8388608

碰到的问题：
使用 swoole_http_server 并设置 了 worker_num=1 测试同步阻塞请求

期望流程：
1. 访问 /foo，此路由下执行了一个较为耗时的操作
2. 在 /foo 未返回结果之时，打开/bar，此时浏览器中两个页面均未加载状态
3. swoole work 运行 /foo  执行逻辑， /bar 处在排队等待中
4. /foo 处理完毕，通过 response 发送至客户端，
5. 触发 server 的 onClose 回调
6. /bar 触发 server 的 onRequest 并分配到 work 中执行逻辑
7. /bar 处理完毕, response 至客户端，
8. 触发 server 的 onClose 回调

实际结果：
5 与 6 的顺序相反

/foo 执行完毕并发送至客户端后， /bar 的 onRequest 立即相应，紧随其后 触发了 server 的 onClose回调

咨询：
这个流程本事就是这样的？还是需要对 server 进行什么设置才可以得到期望流程

**Comment by malacca** [comment]
@matyhtf 

回过头看，我的描述好啰嗦。后来我在官方文档里面找了一段描述

https://wiki.swoole.com/wiki/page/277.html

> dispatch_mode=1/3时，底层会屏蔽onConnect/onClose事件，原因是这2种模式下无法保证onConnect/onClose/onReceive的顺序

我是保持 dispatch_mode 为默认(2)的情况下测试的，用的是 HttpServer

这种情况下保证不了  onRequest onClose 顺序

忽略我上面的描述，简单讲来就是，同一个 worker (仅指定使用一个 worker 测试的)

第一个请求的处理完毕，还没触发 onClose，第二个请求 onRequest 触发了，然后第一个请求的 onClose 触发了

感觉应该是第一个请求 onClose 触发后，才会允许第二个请求进来，并触发 onRequest

**Comment by matyhtf** [comment]
使用 tcpdump 抓包，不要凭感觉

**Comment by malacca** [comment]
我确定的是：

第一个请求的处理完毕，还没触发 onClose，第二个请求 onRequest 触发了，然后第一个请求的 onClose 触发了

我感觉（应该描述为，按正常逻辑，应该是）：

第一个请求 onClose 触发后，才会允许第二个请求进来，并触发 onRequest
