### ISSUE TITLE
msg":"Call to undefined method Swoole\\Coroutine\\Redis::setOption(),  Can support it?

### ISSUE THREAD

**Issue by jmt33** [swoole/swoole-src#1476]
msg":"Call to undefined method Swoole\\Coroutine\\Redis::setOption(),  Can support it?

**Comment by matyhtf** [comment]
Which option do you want to set?

**Comment by jmt33** [comment]
Redis::OPT_PREFIX

**Comment by matyhtf** [comment]
This option does not support, not the functionality provided by redis, you can use php code to implement
