### ISSUE TITLE
在Cygwin环境下reload server产生 WARNING swSignal_callback: signal[30] callback is null.

### ISSUE THREAD

**Issue by HSwift** [swoole/swoole-src#1477]
我在windows的cygwin里用swoole_server做服务器
我想用swoole_server->reload()重新加载workerstart之后的代码
但是他报了一个 WARNING swSignal_callback: signal[30] callback is null.
并且代码没有重新加载
用kill -USR1 master_pid 还是产生了同样的问题

我把同样的代码在linux环境下测试，结果正常重新加载

PHP 7.1.13 (cli) (built: Jan  9 2018 17:08:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.13, Copyright (c) 1999-2017, by Zend Technologies

swoole

swoole support => enabled
Version => 2.0.12
Author => tianfeng.han[email: mikan.tenny@gmail.com]
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388

**Comment by HSwift** [comment]
根据我的测试SIGUSR在我的系统里的编号是30
所以我想是不是SIGUSR信号相应没有注册成功，导致他缺少回调函数

**Comment by HSwift** [comment]
我们最后发现是由于cygwin环境不支持PROCESS模式造成的

请问官方是否有计划在cygwin环境增加PROCESS支持

**Comment by 769344359** [comment]
cygwin 缺很多东西吧，你直接虚拟机都比这要好

**Comment by HSwift** [comment]
我们最终决定把项目移植到Linux
不好意思，打扰了
