### ISSUE TITLE
Swoole\WebSocket\Server startup and shutdown callback issue

### ISSUE THREAD

**Issue by mgrooms** [swoole/swoole-src#1478]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

I'm using swoole to write a service that needs to announce itself during startup and shutdown. This needs to happen before it starts accepting connections so the logical place would appear to be to do this in the start/shudown callbacks. However, when I attempt to use any of swoole's coroutine clients inside of the callbacks, I get an error:

```
coroutine client should use under swoole server in onRequet, onReceive, onConnect callback.
```

When I attempt to wrap the function in a Swoole\Coroutine, the coroutine client never executes:

```
Swoole\Coroutine::create( function() {
    $redis = new Swoole\Coroutine\Redis();
    $redis->connect( 'localhost', 6379 );
    $redis->publish( 'events', "startup" );
    $redis->close();
});
```

2. What did you expect to see?

I expect to be able to use a coroutine client inside a start/shutdown calback. I expect to at least be able to wrap a coroutine client in a coroutine to communicate the startup and shutdown events with service peers. I'd like to use a swoole supported method to do this. Otherwise, using swoole isn't an option if you need the ability to use network clients within the start/shutdown callbacks.

3. What did you see instead?

I either get an error or the coroutine client never executes.

4. What version of Swoole are you using (`php --ri swoole`)?

swoole

swoole support => enabled
Version => 2.0.12
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
openssl => enabled
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 

FreeBSD 10.3-RELEASE-p24

6. If you are using ssl, what is your openssl version?

n/a

```
<?php

class WSServer
{
    private $server;

    //--------------------------------------------------------------------------------
    // web socket callbacks
    //

    function wsockOpen( swoole_websocket_server $server, swoole_http_request $request )
    {
        echo "sock#{$request->fd}: open\n";
    }

    function wsockClose( swoole_websocket_server $server, $fd )
    {
        echo "sock#{$fd}: close\n";
    }

    function wsockMessage( swoole_websocket_server $server, $message )
    {
        echo "sock#{$message->fd}: recv {$message->data}\n";
    }

    //--------------------------------------------------------------------------------
    // server control callbacks
    //

    public function start( swoole_server $server )
    {
        echo "starting up ...\n";

        Swoole\Coroutine::create( function() {
            $redis = new Swoole\Coroutine\Redis();
            $redis->connect( 'localhost', 6379 );
            $redis->publish( 'events', "startup" );
            $redis->close();
        });
    }

    public function shutdown( swoole_server $server )
    {
        echo "shutting down ...\n";

        Swoole\Coroutine::create( function() {
            $redis = new Swoole\Coroutine\Redis();
            $redis->connect( 'localhost', 6379 );
            $redis->publish( 'events', "shutdown" );
            $redis->close();
        });
    }

    //--------------------------------------------------------------------------------
    // server public functions
    //

    public function __construct( $daemonize = false )
    {
        $this->server = new Swoole\WebSocket\Server( "0.0.0.0", 9501, SWOOLE_BASE );

        $this->server->on( 'open', array( $this, 'wsockOpen' ) );
        $this->server->on( 'close', array( $this, 'wsockClose' ) );
        $this->server->on( 'message', array( $this, 'wsockMessage' ) );

        $this->server->on( 'start', array( $this, 'start' ) );
        $this->server->on( 'shutdown', array( $this, 'shutdown' ) );

        session_start();
    }

    public function run()
    {
        $this->server->start();
    }
}

$server = new WSServer();
$server->run();

?>

```

**Comment by matyhtf** [comment]
Cannot call any asynchronous API in onShutdown callback. when onShutdown trigger, the underlying has destroyed epoll handler.

**Comment by mgrooms** [comment]
The asyn APIs don't appear to work from within the onStarup callback either. Do you plan to change this in the future? It severely limits the utility of having startup and shutdown callback functions if you can't use swoole API calls from within those callbacks. The only other option I can think of would be to use curl or something similar from within the callbacks.

**Comment by matyhtf** [comment]
The onStart callback is executed in the master process, If you executing too many asynchronous APIs, there will have many security risk.

**Comment by matyhtf** [comment]
CURL synchronous blocking relatively simple, not much dependence, it is recommended in onStart and onShutdown use PHP's synchronous blocking IO function
