### ISSUE TITLE
is it mandatory and immediate to longjmp jmp back? 协程切换回来，是强制的、立即发生的吗？

### ISSUE THREAD

**Issue by scil** [swoole/swoole-src#1480]
demo code for Coroutine client from swoole doc.
```
    $mysql = new Swoole\Coroutine\MySQL();
    #2
    $res = $mysql->connect([
        'host' => '127.0.0.1',
        'user' => 'root',
        'password' => 'root',
        'database' => 'test',
    ]);
    #3
    if ($res == false) {
        $response->end("MySQL connect fail!");
        return;
    }
```

suppose that, at `#2`, second routine starts and Swoole\Coroutine is not used in the second routine.
Then when the mysql conncted, the work in second routine would be paused and  `#3` run  immediately ?
假设在 `#2`，第二个协程开始运行，且第二个协程里没有使用 Swoole\Cotoutine的客户端或sleep等协程操作。那么在第一个协程完成mysql连接时，会无论如何马上暂停第二个协程并开始`#3`吗？

**Comment by xyzhu1120** [comment]
除了显示会做切出的点（比如connect）是不会做协程切换的，所以第一个协程要等第二协程yield

**Comment by scil** [comment]
Thank you very much.
