### ISSUE TITLE
swoole redis server 不能接收到返回值

### ISSUE THREAD

**Issue by dalebao** [swoole/swoole-src#1483]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
使用swoole官方代码，跑redis server。redis-cli 可以链接上服务，可以写入数据，但是redis-cli没有返回值。进行一些操作，都不能获得类似于 ‘ok‘，’nil‘ 之类的返回值。
[代码](https://www.swoole.co.uk/docs/modules/swoole-redis-server)

2. What did you expect to see?
应该和正常的redis一样可以设置查询并有返回值。

3. What did you see instead?
直接卡死不动，经过调试发现可以将数据写入文件，可以查询出数据，可以格式化数据，但是在setHandler的回调函数中返回数据，redis-cli 并不能接收到。

4. What version of Swoole are you using (`php --ri swoole`)?
2.0.7

5. What is your machine environment used (including version of kernel & php & gcc) ? 

Darwin DaledeMacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

6. If you are using ssl, what is your openssl version?

openssl: stable 1.0.2n (bottled) [keg-only]

**Comment by matyhtf** [comment]
协程模式 command handler，不支持 `return` 方式，请直接使用`$server->send`发送结果
