### ISSUE TITLE
Post and decode posted Json in Swoole server

### ISSUE THREAD

**Issue by mustanish** [swoole/swoole-src#1484]
Hi,

I am using swoole to write APIs, some API get parameters in body in JSON format 
{
    "social_id": "error",
    "social_platform": 404,
    "email": "The requested URL was not found on this server",
    "password": "The requested URL was not found on this server",
    "gender": "The requested URL was not found on this server",
    "full_name": "The requested URL was not found on this server"
    "fcm_id": "The requested URL was not found on this server",
    "vendor_id": "The requested URL was not found on this server",
}
I am able fetch these parameters using rawContent() but when I am using json_decode function. It is not working.Does swoole does not support this feature.Thanks in advance.

**Comment by matyhtf** [comment]
Paste the result of `rawContent` method, execute `json_last_error_msg` get more error info.

**Comment by mustanish** [comment]
It was my mistake, Now it is working thanks.
