### ISSUE TITLE
2.1.0   \Swoole\Coroutine::getuid() ===1 in onWorkerStart(),  why?

### ISSUE THREAD

**Issue by scil** [swoole/swoole-src#1486]
before, it return -1
```
        $this->server->on('WorkerStart', array($this, 'onWorkerStart'));

        $this->server->on('request', array($this, 'onRequest'));

    public function onWorkerStart()
    {
        echo \Swoole\Coroutine::getuid(); // now 1, not -1
     }


```

I use -1 for special purpose and 1,2,.. for requests.

Why it return 1 now  in onWorkerStart ?

Does it always return 1 onWorkerStart forever?  Will it Change?

**Comment by matyhtf** [comment]
The onWorkerstart callback now also creates a coroutine, so here it returns the coroutine's ID

**Comment by scil** [comment]
It's an earchquake for me.

then , how can I make a unique id for each request? 

I need an id to Distinguish data belongs to different request.

**Comment by matyhtf** [comment]
Request id ? 
You should add id in onRequest callback.
This should have nothing to do with onWorkerStart.

**Comment by scil** [comment]
It's about laravel refactor.  [LaravelFly](https://github.com/scil/LaravelFly)

laravel is bases on a service container.  any service may call app('name') to get a service. I need a request id to seprarate different services or memmbers in different requests.

swoole2's \Swoole\Coroutine::getuid() give me this tool ,  because it can be called anywhere, not just only in a callback or used as a paramter to send and send.

but now , maybe i'm losting this tool.

**Comment by matyhtf** [comment]
The coroutine ID [Coroutine::getUid()] is multiplexed, it can not be used as a unique id.

**Comment by scil** [comment]
If coroutine is used under control , it can be used as a request id.

**Comment by matyhtf** [comment]
There is a problem with your program. The coroutine ID is like the process ID. After the old coroutine ends, the ID is reused by the new coroutine. You can use a self-increment ID as the unique id for request.

```php
$requestId = 0;
$this->server->on('request', function () {
    global $requestId;
    $currentRequestId = $requestId ++;
});
```

**Comment by scil** [comment]
in LaravelFly,  some services are made and saved in an array like app::corDict[-1].

in the first request,  app::corDict[-1] is cloned and app::corDict[1] is made,  new services ared save in the new array. When request ends,   app::corDict[1]  is unset.

I need a tool like \Swoole\Coroutine::getuid() that can be called anywhere.

for example,   app('me') can get the service "me" in the current app array by using  app::corDict[co:getuid] .

it works well with the limitation of corouitne use.   It can seperate services and objects's members very well.

otherwize , refactor is too complicated。how a service use $requestId?  It can't be used like a global var or static method.

**Comment by scil** [comment]
i used the wrong words 'request id',   i use coroutine id just to distinguish different requests being handled by a workerr.

**Comment by scil** [comment]
when a request begins,  a new array is made.
```
        static::$corDict[$cid] = static::$corDict[-1];
```

when this request ends, the array is unset.
```
        unset(static::$corDict[$cid]);
```

coroutine id is not perfect , and coroutine should be used under control. 

But , \Swoole\Coroutine::getuid() is wonderful , because it's a static method, it can be called everywhere. 

A non-global var can't be used free.

Now, I'll use 1 to replace -1 and  check anything that may create new coroutines, except OnReqeust .

**Comment by matyhtf** [comment]
I can not give you a solution. You need to solve it yourself. 
String replacement is a good solution.
You can also use `spl_object_id` to get a unique ID.

`Coroutine::getUid` is used to distinguish between different coroutine contexts. I see no coroutine features in your code, You should not use `Coroutine::getUid`.

```php
$this->server->on('request', function (Swoole\Http\Request $req, Swoole\Http\Response $resp) {
     $requestId = spl_object_id($req);
});
```

**Comment by scil** [comment]
Thank you.

I was working on introducing coroutine dabase carefully.  

I think careful use of coroutine can help laravel run with swoole. Though I've not used coroutine, Coroutine::getUid is very wonderful to laravel refactor for avoiding data pollution.
