### ISSUE TITLE
Instantiate swoole_http_request and swoole_http_response

### ISSUE THREAD

**Issue by pachico** [swoole/swoole-src#1489]
I am trying to Instantiate response objects to write integration tests but I'm failing at seeing how to do it.
Once I try to manipulate the newly created object I get a warning.

Is it possible to do it? I understand it's quite important for having end-to-end integration tests.

My attempt:
```php
$swooleResponse = new \swoole_http_response();
$swooleResponse->initHeader(['foo' => 'bar']);
```
I get
```
Swoole\Http\Response::initHeader(): Http request is finished.
```

Running version
```
Version => 2.1.0
```

Thanks

**Comment by yangxikun** [comment]
swoole_http_request and swoole_http_response object just can be created by swoole_http_server::on('request', callback) when receive http request.

**Comment by matyhtf** [comment]
The `swoole_http_response` object is created by the swoole extension,  do not create it in php code

**Comment by pachico** [comment]
@matyhtf , this is hardly what I what I was asking.
My issue is not about if Swoole is able to create req/res objects but how to create them (yes, in PHP code) for functional tests.
It is a common practice to want to test an application starting from the request object or creating responses to test middlewares or parsers.
If you say it's not possible then I'd like to suggest it as a feature (especially because of some peculiarities I have found manipulating Swoole responses).
