### ISSUE TITLE
Memory increase?

### ISSUE THREAD

**Issue by Wulfklaue** [swoole/swoole-src#1491]
Is it normal for Swoole, to keep increasing memory ( benchmarked execution ).

```
<?php

$server = new Swoole\Http\Server('127.0.0.1', 9501);

$server->on("start", function ($server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$server->on('request', function ($request, $response) {
    $response->header('Content-Type', 'text/html; charset=utf-8');

    ob_start();
    $_SERVER['REQUEST_URI'] = $request->server[ 'request_uri' ];
    $_SERVER['REQUEST_METHOD'] = $request->server[ 'request_method' ];
    $_SERVER['REMOTE_ADDR'] = $request->server[ 'remote_addr' ];
    include ("index.php");
    $html = ob_get_contents();
    ob_end_clean();
    $response->end( $html );
});

$server->start();
```

Index loads a small framework. The more connections, the more the php7 executable in memory keep growing. Got it as far as 500MB per thread ( and it holds on to this memory ). Is their no automated memory limit for Swoole to restart excessive runaway threads?

**Comment by Wulfklaue** [comment]
This issue seems to be related to #441

As the user reported the exact same issues. 

Include as above will result in:
* Code execution
* Systematic memory increase

Include_once will result in:
* Code execution on the first time.
* No more data included or executed on the second time
* Stable memory ( as nothing gets included )

For some reason "include" will keep adding the same php script content into memory and execute it. A cumulative gain.

While "include_once" will only perform the script action one time and never perform any action after this. It looks almost like their is a issue with the way Swoole handles "include_once". You expect the bytecode to get included once and executed on each request after.

**Comment by timaelliott** [comment]
I'd suggest checking into if this is PHP7's slab allocation causing you issues. It doesn't free up allocated memory in the way PHP5 did (`gc_collect_cycle()`)

`gc_mem_caches()`
