### ISSUE TITLE
swoole_http_server不支持解析content-type:multipart/form-data类型的POST请求

### ISSUE THREAD

**Issue by getchu** [swoole/swoole-src#1493]
当POST请求的表单内容是如下时，无法通过 swoole_http_request->post 获取 类似CGI模式的$_POST['ss']

------WebKitFormBoundarycV4kt4FNbM3GiJd3
Content-Disposition: form-data; name="ss"

ddd
------WebKitFormBoundarycV4kt4FNbM3GiJd3
Content-Disposition: form-data; name="sdfsdf"

sdfsdfsdfsdf
------WebKitFormBoundarycV4kt4FNbM3GiJd3--

**Comment by HSwift** [comment]
你可以用swoole_http_request->rawContent()获取原始post数据

**Comment by matyhtf** [comment]
请提供完整的 Http 报文
