### ISSUE TITLE
Swoole\Async::writeFile内存泄漏问题

### ISSUE THREAD

**Issue by lgang06** [swoole/swoole-src#1494]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

循环使用Swoole\Async::writeFile写文件，php进程内存持续增加。
示例代码：

$str = str_repeat("===", 1000);
while (true) {
Swoole\Async::writeFile('/tmp/test_sync.log', $str, null, FILE_APPEND);
   echo ( memory_get_peak_usage(true)/ 1024/1024) . "\n";
   usleep(1000);
}

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?
swoole

swoole support => enabled
Version => 2.0.10
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => 1 => 1
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 

PHP 7.1.9 (cli) (built: Sep 11 2017 18:23:04) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

6. If you are using ssl, what is your openssl version?

**Comment by matyhtf** [comment]
使用方法存在问题，`while(true)`死循环后，无法切换到`EventLoop`，匿名回调函数对象和相关数据会持续累积。
