### ISSUE TITLE
docker下 php:php7.2.2-fpm 编译红色提示

### ISSUE THREAD

**Issue by hoseadevops** [swoole/swoole-src#1496]
安装swoole 2.1 编译通过 但是过程中 终端 有红色提示 

In file included from /tmp/swoole/swoole_ringqueue.c:20:0:
/tmp/swoole/swoole_ringqueue.c: In function 'zim_swoole_ringqueue_full':
/tmp/swoole/php_swoole.h:109:40: warning: comparison of constant '0' with boolean expression is always false [-Wbool-compare]
 #define SW_CHECK_RETURN(s)         if(s<0){RETURN_FALSE;}else{RETURN_TRUE;}return
                                        ^
/tmp/swoole/swoole_ringqueue.c:124:5: note: in expansion of macro 'SW_CHECK_RETURN'
     SW_CHECK_RETURN(swRingQueue_full(queue));
     ^~~~~~~~~~~~~~~

请问这代表什么

**Comment by matyhtf** [comment]
忽略`note`，关注一下`error`
