### ISSUE TITLE
swoole task 能否重置环境？

### ISSUE THREAD

**Issue by lanlin** [swoole/swoole-src#1504]
如题，我希望能够在每次投递给 task 的任务完成之后，
直接重置该 task 所在进程的环境，也就是说销毁上次执行后产生的一切常住内存的东西。
比如全局变量、常量、文件引用等等。

因为后续的逻辑比较复杂。
如果不这样做，下次投递过来的其他任务就会受到上次残留的污染。
导致程序始终不正常，而且内存越跑越多。

能有什么方法避免这个问题么？

**Comment by twose** [comment]
https://group.swoole.com/question/106561

**Comment by lanlin** [comment]
@twose 这。。不会是只能手动操作吧？能否通过 server 实例来操作？
要知道为了安全起见，很多 php 内置的系统函数都是被禁用掉了的。
swoole 本身有提供这种方法么？
比如， 在 onFinish 的时候，或者 onTask 内直接杀死该 task 的进程，再重新拉起一个？

**Comment by lanlin** [comment]
找到了个 swoole_process:kill()。我如果用这个方法来 kill 掉当前的 task 会不会造成某些不可预料的问题？

**Comment by matyhtf** [comment]
不建议使用 `kill`，重启进程消费非常大。如果你需要短生命周期，可以直接复用`php-fpm`，将请求以`fastcgi`协议的方式组包，发给`php-fpm`
