### ISSUE TITLE
central instant messaging platform for swoole developers

### ISSUE THREAD

**Issue by simonhf** [swoole/swoole-src#1505]
When I first discovered swoole then I wanted to figure out how to interact with other swoole developers across the internet. Here are my experiences:

Via QQ:

I discovered the Chinese developers hang out and do instant messaging using the QQ smart phone app. I had to go to a lot of trouble to get the international version of QQ working because although much of it is in English, there is a user validation step which is in Chinese only and therefore difficult to get through unless you have a Chinese speaking friend. I do have a Chinese speaking friend so I could get past this step.

The really good thing about QQ is that it has an auto translate feature which means I could interact with friendly swoole Chinese developers even though they don't speak English :-) And there seem to be lots of Chinese experienced swoole developers hanging out on QQ too.

However, negative things about QQ instant messaging are that it only seems to be available for smart phones, so no desktop possibility for easy cut and paste. And also, the QQ app on my android phone went crazy after a while and became unusable causing the entire phone to have problems :-(

Via github:

Github seems to be a good place to create tickets with various questions etc. But unfortunately it's English only which means that it alienates many Chinese swoole developers. And from the tickets I have created or contributed to, some go unanswered for months and some get answered very quickly. So definitely less interactive and not a good medium to develop friendly developer relationships :-(

Via slack:

There is a slack swoole group mentioned here [1] used by non-Chinese (which are unfortunately in a small minority) swoole developers. It's better than nothing but there are very few experienced swoole developers as compared to QQ. Also, there is no auto translate feature like QQ... although I think it might be possible to add it onto slack.

The issue:

The purpose of this ticket is to investigate if there's an international chat system -- i.e. with the translation feature -- which could facilitate international interaction between swoole developers. QQ seems too difficult and unreliable for international users to register and use, with a lack of desktop support. Not sure how easy or convenient slack is to use for Chinese swoole developers? And can auto translation be switched on / enabled for slack? If not slack, then which other chat system might come into question? Or is it preferable to segregate swoole developers by language?

Looking forward to comments!

[1] https://www.swoole.co.uk/community

**Comment by simonhf** [comment]
Looks like Telegram [1] has various bots [2] for doing translation. Is Telegram a convenient chat platform for Chinese swoole developers to use? This answer appears to be that Telegram is inconvenient according to here [3].

[1] https://telegram.orgtele
[2] http://tapto.me/telegram/translate.html
[3] https://www.comparitech.com/privacy-security-tools/blockedinchina/telegram/

**Comment by simonhf** [comment]
Looks like slack [1] has mixed results being accessed from China, at least in 2017.

[1] https://www.reddit.com/r/China/comments/66vatj/slack_blocked_in_china/

**Comment by twose** [comment]
In China, QQ and WeChat met the needs of most people. Telegram did not stable due to political reasons (in fact, all foreign communications are not available). 
My foreign friends prefer to use WeChat, but WeChat does not have a publicly searchable group feature, and I have not found the swoole WeChat group by the official. 
In fact, as far as I know, almost all of the Swoole groups are discussed in Chinese. Although the Chinese IT community is very much in favour of using GitHub in English (respecting the international community), most  Chinese developers have no intention of using the foreign live chat applications by striding the (damned) great-firewall. 
without any doubt, swoole is moving towards internationalization and work hard for that, I can see that you are an active foreigner developer and have made a huge effort in the development process. Like and I will learn from u.

**Comment by simonhf** [comment]
@twose "most Chinese developers have no intention of using the foreign live chat applications by striding the (damned) great-firewall"

I can see that and agree with you. While QQ International was working for me then I found it useful and interesting to communicate with Chinese swoole developers using the QQ translate feature. So maybe the way forward is to find an alternative to QQ with the translate feature which is based in China, and that actually works for foreign / non-Chinese users?

Or does the QQ chat platform use open standards? Are there other clients which can use it which are more reliable?

**Comment by twose** [comment]
I don't know why QQ app went crazy on your phone, 
but there are four QQ of diffrent platform which you can download, you can see http://www.imqq.com/#download, but international QQ for windows/mac haven't been updated for a long time.
QQ also has web version in http://web2.qq.com/, but it rely on mobile QQ to scan QR-code.

**Comment by doubaokun** [comment]
Thanks everyone.

Let's focus on Swoole development topics on Github.
