### ISSUE TITLE
swoole 2.1.0 client 连接不上 server

### ISSUE THREAD

**Issue by lanlin** [swoole/swoole-src#1509]
### 环境:
**centos**: 7.4.1708 (docker 镜像，docker 是跑在 ubuntu 上的)

**php**: 7.2.3

**swoole**: 2.1.0 (之前的 2.0.x 也连接不上)

**ubuntu**: 
Linux version 4.4.0-109-generic 
(buildd@lgw01-amd64-038) 
(gcc version 5.4.0 20160609
 (Ubuntu 5.4.0-6ubuntu1~16.04.5)

swoole server 的 log 没有任何错误被记录, php 错误日志里面记录到两种错误

`PHP Warning:  Swoole\Client::connect(): connect to server[/run/swoole.sock:0] failed. Error: No such file or directory[2].`

`PHP Warning:  Swoole\Client::connect(): connect to server[/run/swoole.sock:0] failed. Error: Permission denied[13].`

但是，这个文件确实是已经被创建了的，路径也是正确的。

![image](https://user-images.githubusercontent.com/3468024/37013781-e2976b7e-2136-11e8-8e2b-f6a08c876757.png)

### 代码demo:
```php
        $serv = new \Swoole\Server
        (
            '/run/swoole.sock',
            null,
            SWOOLE_PROCESS,
            SWOOLE_UNIX_STREAM
        );

         $client = new \Swoole\Client(SWOOLE_UNIX_STREAM, SWOOLE_SOCK_SYNC);
         $client->connect('/run/swoole.sock', null, 2);
```
尝试过直接用IP 127.0.0.1 来跑 server, 但是还是连接不上。

### 其他说明
已经多次重装，包括 php 等。
同样的镜像，在我本地的 mac 上面跑起来是可以正常连接到 server 的。
但是在 ubuntu 服务器上面跑这个 docker 镜像就出现了连不上的问题。

**Comment by twose** [comment]
demo代码不全吧, 换个路径放sock文件试试, 或者你是否有把sock文件挂载到宿主机上? 可能和docker某些权限配置有关?
比较有意思的是反而docker在macos上跑会出现unixsocket不可用的问题,可以参见[这个issue](https://github.com/docker/for-mac/issues/483)

**Comment by lanlin** [comment]
@twose 我明白你的意思，不过我应当是不需要挂载到宿主机上的。因为我的 client 和 server 都是只需要跑在同一个 docker 容器中就行，而这个容器的承载系统是 centos, 也就是说，实际上这个容器就包含了一个完整的系统环境。而 server 只针对本地（当前 centos 容器内）提供服务，换句话说就是 client 只需要连接本地 server. 我觉得应该不存在需要将 sock 文件挂载到宿主机实现共享之类的问题吧。

我先试试韩老师说的，直接授权 777 试下先。

**Comment by lanlin** [comment]
@matyhtf @twose 总算找到问题了。就是 sock 文件的权限引起的。

不过是我自己这边的问题，因为 swoole server 是在 cli 下 root 账户启动的。
而 client 部分的逻辑，有的是需要 cli 下面跑，有的是在 fpm 下面。

fpm 安全起见不是以 root 身份来运行的。
而我在本地测试的时候，一直用 phpunit 在 cli 下面跑的单元测试，导致一直没有发现这个问题。

抱歉了，这是我自己的问题。

**Comment by twose** [comment]
其实我想的刚好相反,文件不挂载的话在容器内同一个脚本同是root用户操作应该不会出现这种问题的,所以我之前说觉得你的demo是不完整的, 所以我猜想你可能是有挂载到了容器外之类的别的操作导致了这个问题.现在看来是fpm用户权限不足引起的.
所以提issue的时候 提供完整的demo/测试条件 很重要啊!
