### ISSUE TITLE
ERROR   zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught RedisException: protocol error, got '

### ISSUE THREAD

**Issue by guojianing** [swoole/swoole-src#1512]
' as reply type bytet RedisException: protocol error, got '
 in /meiktv/htdocs/www/meiktv_websocket/server.php:285
Stack trace:
#0 /meiktv/htdocs/www/meiktv_websocket/server.php(285): Redis->get('39.106.5.170_fd...')
#1 [internal function]: {closure}(Object(Swoole\WebSocket\Server), 1014, 0)
#2 /meiktv/htdocs/www/meiktv_websocket/server.php(309): Swoole\Http\Server->start()
#3 {main}
  thrown in /meiktv/htdocs/www/meiktv_websocket/server.php on line 285
' as reply type byte *15846.2]  ERROR   zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught RedisException: protocol error, got '
 in /meiktv/htdocs/www/meiktv_websocket/server.php:285
Stack trace:
#0 /meiktv/htdocs/www/meiktv_websocket/server.php(285): Redis->get('39.106.5.170_fd...')
#1 [internal function]: {closure}(Object(Swoole\WebSocket\Server), 1014, 0)
#2 /meiktv/htdocs/www/meiktv_websocket/server.php(309): Swoole\Http\Server->start()
#3 {main}
  thrown in /meiktv/htdocs/www/meiktv_websocket/server.php on line 28
[2018-03-08 17:23:30 $9433.0]   WARNING swManager_check_exit_status: worker#2 abnormal exit, status=255, signal=0

**Comment by twose** [comment]
看起来是phpredis抛出的异常,试试看升级到最新版本或者在redis.conf里设置protected-mode no
如果你的PHP代码有抛出异常逻辑，必须在事件回调函数顶层进行try/catch来捕获异常,否则进程会因为异常而退出.
```php
$serv->on('Receive', function() {
    try
    {
        //some code
    }
    catch(Exception $e)
    {
        //exception code
    }
}
```

**Comment by matyhtf** [comment]
* 多进程勿公用一个redis连接，在onWorkerStart中创建redis
* 捕获异常进行断线重连
