### ISSUE TITLE
coroutine redis client 断线重连的几个问题。

### ISSUE THREAD

**Issue by 8923052** [swoole/swoole-src#1513]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
问题核心代码(http server onworkerstart事件，woker_id=0执行)如下：排版有点问题，怎么调都没调好。
```php
		while (true) {
			if(! isset($redis)) {
				/**
				 *
				 * @var \Redis $redis
				 */
				$redis = new Swoole\Coroutine\Redis();
			}
			
			// 首先检查连接情况
			if(! $redis->connected) {
				$redis->close();
				$redis->connect('127.0.0.1', 6379, 1);
				if(! $redis->connected) {
					/**
					 * 1.此处必须重新实例化,否则warning。重新开启redis服务，问题依旧：
					 * PHP Warning: Swoole\Coroutine\Redis::connect(): connection to the server has already been established. in /mnt/hgfs/vm-share/test/index.php
					 */
					// $redis = new Swoole\Coroutine\Redis();
					echo("连接redis失败,3s后重连。");
					Swoole\Coroutine::sleep(3);
					continue;
				}
				echo("连接redis成功.");
			}
			
			$res = $redis->brPop('test', 0);
			
			// 超时
			if($res === NULL) {
				continue;
			}
			
			// 返回false,brPop时断开了连接
			if($res === FALSE) {
				/**
				 * 2.server在brpop时，redis服务关闭，但connected仍然为true???
				 * 
				 * object(Swoole\Coroutine\Redis)#10 (7) {
				 * ["setting"]=>
				 * NULL
				 * ["host"]=>
				 * string(9) "127.0.0.1"
				 * ["port"]=>
				 * int(6379)
				 * ["sock"]=>
				 * int(4)
				 * ["connected"]=>
				 * bool(true)
				 * ["errCode"]=>
				 * int(3)
				 * ["errMsg"]=>
				 * string(28) "Server closed the connection"
				 * }
				 */
				var_dump($redis);
				
				// 3.此处必须重置$redis，否CPU暴涨
				//$redis->close();
				//$redis = null;
				continue;
			}
			
			var_dump($res);
		}
```
2. 期望?
>1、代码中1处，断线重连，应该直接用原redis对象connect即可重连成功，但实际的情况是必须重新实例化redis才能connect
2、代码中2处，redis连接成功后，在brpop时，redis服务关闭，此时打印redis对象，connected属性仍然为true，应该为false；代码中3处，由于redis服务关闭，brpop返回false,实际已经断开redis连接，connected错误的为true,导致循环判断失败，CPU和内存暴涨。

3. 重现?

> 1、先启动redis服务
2、再运行上面的代码php test.php
3、console：2018-03-08 23:16:09 - 连接redis成功.
4、停止redis server
5、console：
```php
object(Swoole\Coroutine\Redis)#10 (7) {
  ["setting"]=>
  NULL
  ["host"]=>
  string(9) "127.0.0.1"
  ["port"]=>
  int(6379)
  ["sock"]=>
  int(4)
  ["connected"]=>
  bool(true)
  ["errCode"]=>
  int(3)
  ["errMsg"]=>
  string(28) "Server closed the connection"
}
```
2018-03-08 23:16:56 - 连接redis失败,3s后重连。
```
PHP Warning:  Swoole\Coroutine\Redis::connect(): connection to the server has already been established. in /mnt/hgfs/vm-share/test/index.php on line 95
```
6、重新启动redis服务。
7、console，持续输出失败提示，无法重连:
2018-03-08 23:16:59 - 连接redis失败,3s后重连。
PHP Warning:  Swoole\Coroutine\Redis::connect(): connection to the server has already been established. in /mnt/hgfs/vm-share/test/index.php on line 95
2018-03-08 23:17:02 - 连接redis失败,3s后重连。
PHP Warning:  Swoole\Coroutine\Redis::connect(): connection to the server has already been established. in /mnt/hgfs/vm-share/test/index.php on line 95
2018-03-08 23:17:05 - 连接redis失败,3s后重连。

4. What version of Swoole are you using (`php --ri swoole`)?
```
swoole

swoole support => enabled
Version => 2.1.1
Author => tianfeng.han[email: mikan.tenny@gmail.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
jemalloc => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```
5. What is your machine environment used (including version of kernel & php & gcc) ? 
PHP 7.2.3 (cli) (built: Mar  7 2018 16:05:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

Linux localhost.localdomain 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 Linux

gcc 6.4

**Comment by matyhtf** [comment]
感谢你的反馈，此问题已经解决了。在最新的代码中，可以在`close`之后直接`connect`重连。`2.1.1`或之前版本存在问题，必须`new $redis`重建实例。

**Comment by 8923052** [comment]
redis端口连接后，connected属性不正确的问题是否解决？

**Comment by matyhtf** [comment]
已解决。请测试一下，有问题可以向我们反馈。

**Comment by 8923052** [comment]
@matyhtf 

刚刚测试了一下最新版2.1.2-alpha。
**之前的两个问题**：1、redis服务关闭后,connect属性正确变化为false；2、断线后用原来的redis对象仍然无法连接，问题依旧。

**现在测试发现两个新问题**：
1、在redis connect之前调用close会导致worker退出。
onworkerstart回调使用：
> if($worker_id == 0) {
			$redis = new \Swoole\Coroutine\Redis();
			$redis->close();
			$redis->connect('127.0.0.1', 6379);
			var_dump($redis);
		}

提示信息[2018-03-15 20:12:26 $18278.0]	WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11
2、redis 连接后，close后connect属性仍然为true
> if($worker_id == 0) {
			$redis = new \Swoole\Coroutine\Redis();
			$redis->connect('127.0.0.1', 6379);
			var_dump($redis);
			$redis->close();
			var_dump($redis);
		}

console：
>object(Swoole\Coroutine\Redis)#10 (7) {
  ["setting"]=>
  NULL
  ["host"]=>
  string(9) "127.0.0.1"
  ["port"]=>
  int(6379)
  ["sock"]=>
  int(4)
  ["connected"]=>
  bool(true)
  ["errCode"]=>
  int(0)
  ["errMsg"]=>
  string(0) ""
}
object(Swoole\Coroutine\Redis)#10 (7) {
  ["setting"]=>
  NULL
  ["host"]=>
  string(9) "127.0.0.1"
  ["port"]=>
  int(6379)
  ["sock"]=>
  int(4)
  ["connected"]=>
  bool(true)
  ["errCode"]=>
  int(0)
  ["errMsg"]=>
  string(0) ""
}


php --ri swoole
swoole

swoole support => enabled
Version => 2.1.2-alpha
Author => tianfeng.han[email: mikan.tenny@gmail.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
jemalloc => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by matyhtf** [comment]
第一个问题是因为当前没有连接，不应该调用`close`。

**Comment by matyhtf** [comment]
已修复，底层的未检测，导致指针。

**Comment by 8923052** [comment]
刚刚测试。如果redis服务没有开启，直接connect就会致命错误，导致worker进程退出.
>$redis = new Swoole\Coroutine\Redis();
			$redis->connect('127.0.0.1', 6379);
			var_dump($redis);

[2018-03-16 12:36:57 $20408.0]	WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11

**Comment by matyhtf** [comment]
请再更新测试一下

**Comment by 8923052** [comment]
再次更新测试，其他问题都OK了，还剩下一个问题：

redis连接成功后，brpop时，关闭redis服务，此时打印redis对象，connected属性仍然错误的是true
**韩大辛苦了。。。**
object(Swoole\Coroutine\Redis)#10 (7) {
  ["setting"]=>
  NULL
  ["host"]=>
  string(9) "127.0.0.1"
  ["port"]=>
  int(6379)
  ["sock"]=>
  int(4)
  ["connected"]=>
  bool(true)
  ["errCode"]=>
  int(3)
  ["errMsg"]=>
  string(28) "Server closed the connection"
}

**Comment by matyhtf** [comment]
具体的代码是？可以直接使用 `go` 测试。
```php
go(function () {
    $redis = new Swoole\Coroutine\Redis();
    $redis->connect('127.0.0.1', 16379);
    var_dump($redis);
});
```

**Comment by 8923052** [comment]
重现：
1.开启redis服务
2.php test.php
3.关闭redis服务
4.查看输出
go(function () {
	while (true) {
		if(! isset($redis)) {
			/**
			 *
			 * @var \Redis $redis
			 */
			$redis = new \Swoole\Coroutine\Redis();
		}
		
		// 首先检查连接情况
		if(! $redis->connected) {
			$redis->close();
			$redis->connect('127.0.0.1', 6379, 1);
			
			if(! $redis->connected) {
				echo ("连接redis失败,3s后重连。" . PHP_EOL);
				\Swoole\Coroutine::sleep(3);
				continue;
			}
			echo ("连接redis成功." . PHP_EOL);
		}
		
		$res = $redis->brPop('test', 0);
		
		// 超时
		if($res === NULL) {
			continue;
		}
		
		// 返回false,brPop时断开了连接
		if($res === FALSE) {
			/**
			 * 2.server在brpop时，redis服务关闭，但connected仍然为true???
			 *
			 * object(Swoole\Coroutine\Redis)#10 (7) {
			 * ["setting"]=>
			 * NULL
			 * ["host"]=>
			 * string(9) "127.0.0.1"
			 * ["port"]=>
			 * int(6379)
			 * ["sock"]=>
			 * int(4)
			 * ["connected"]=>
			 * bool(true)
			 * ["errCode"]=>
			 * int(3)
			 * ["errMsg"]=>
			 * string(28) "Server closed the connection"
			 * }
			 */
			var_dump($redis);
			
			// 3.此处必须重置$redis，否CPU暴涨
			$redis->close();
			$redis = null;
			continue;
		}
	}
});

**Comment by matyhtf** [comment]
这个问题是无法解决的，受限于`hiredis`的实现，如果连接关闭，`hiredis`会先触发`onResult`，因此`brPop`会返回结果。然后在下一个事件回调中才执行`onClose`，这时连接才会被标记为`connected = false`

**Comment by 8923052** [comment]
好的，明白了，感谢感谢。
