### ISSUE TITLE
swoole开一个reactor_num，８个worker_num的时候为什么有时候读不到redis里的数据？

### ISSUE THREAD

**Issue by 252378189** [swoole/swoole-src#1515]
我用的swoole版本是Version => 2.0.11
使用websocket.在开发的时候读写redis时出出的问题．
设置服务时是：
dispatch_mode＝1
reactor_num＝1
worker_num=8
这时有时候同一个用户(同一个连接fd)通讯都有时读不出redis的数据．
但是如果我把设置改为：
dispatch_mode＝1
reactor_num＝1
worker_num=1
这样就没有问题．
redis的我是用phpredis的．
PHP Version => 5.6.22
phpredis的版本是：Redis Version => 2.2.7
redis server 的版本是：Redis server v=3.2.0
有人遇到这种问题吗？求助，谢谢．

**Comment by twose** [comment]
dispatch_mode=1是轮询模式, 会分配给不同的worker进程, 不同进程间是不可以共用redis客户端的,请检查你的代码.
还有请按issue模板发,最好能贴问题代码和错误信息.

**Comment by 252378189** [comment]
哦，感谢回复．格式问题下次一定注意．

有没有办法可以让不同的worker进程即时读取redis里的数据？如果把数据用swoole自带的Table来存是要以在不同的worker进程里读取的是吧？

**Comment by twose** [comment]
在当前进程中没有可用的redis客户端时新建一个redis客户端(连接)即可.
不同进程间没必要共享数据库连接, 除非你实现了一个外部的连接池(有进程间通信开销).

关于数据库的一些文档:
[在多个协程间共用同一个协程客户端](https://wiki.swoole.com/wiki/page/852.html)
[MySQL的连接池、异步、断线重连](https://wiki.swoole.com/wiki/page/350.html)

**Comment by 252378189** [comment]
谢谢了，就是在同一个进程内用同一个redis连接就好了．
