### ISSUE TITLE
redis类能不能增加geo相关功能的支持

### ISSUE THREAD

**Issue by AngusZhang082** [swoole/swoole-src#1518]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
现在的redis能不能增加geo（geoAdd，geoHash等）相关功能

2. What did you expect to see?

swoole的redis类能直接调用geo相关函数

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?

2.1.0

5. What is your machine environment used (including version of kernel & php & gcc) ? 
linux 3.10.0
php7.1
gcc 4.8.5

6. If you are using ssl, what is your openssl version?

**Comment by matyhtf** [comment]
`2.1.2`版本增加了`Co\Redis::request`方法，可以发送任意`Redis`指令
