### ISSUE TITLE
升级2.1.1版本后出现的问题

### ISSUE THREAD

**Issue by tsingsun** [swoole/swoole-src#1519]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
在2.0.12版本站点首页时正常运行,但在2.1.1版本中,发现无响应现象,在swoole log中,一请求马上有
   NOTICE  http_onReceive (ERROR 1005): connection[2] is closed.

但同样的站点,在mac用php内置服务时测试时,又一切正常.同时用以下脚本:
```php
<?php
$http = new swoole_http_server("127.0.0.1", 9501);
function testWeb(\Swoole\Http\Response $response)
{
    $response->header("Content-Type", "text/html");
    $response->end('<html>hello</html>');
}

$http->on("request", function (\Swoole\Http\Request $request, $response) {
    testWeb($response);
});
$http->start();
```
同时出现无响应及同样的ERROR 1005日志信息
2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?
swoole support => enabled
Version => 2.1.1
Author => tianfeng.han[email: mikan.tenny@gmail.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 
centos6.4 内核 2.6.32-358.el6.x86_64; php:7.1.8; gcc:4.4.7

**Comment by matyhtf** [comment]
无法重现你的问题。请使用 strace 跟踪

**Comment by tsingsun** [comment]
strace信息:
Process 32694 attached - interrupt to quit
epoll_wait(4, 
{{EPOLLIN, {u32=6, u64=21474836486}}}, 4096, 4294967295) = 1
read(6, "\1\0\0\0n\3\0\0\n\0\4\0GET /index.php HTTP/"..., 8192) = 890
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=405, ...}) = 0
write(5, "[2018-03-16 14:36:45 *32694.0]\tN"..., 92) = 92
brk(0x3292000)                          = 0x3292000
epoll_wait(4, {{EPOLLIN, {u32=6, u64=21474836486}}}, 4096, 4294967295) = 1
read(6, "\1\0\0\0\0\0\0\0\4\0\4\0", 8192) = 12
fcntl(6, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
fcntl(6, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
sendto(6, "\1\0\0\0\0\0\0\0\4\0\0\0", 12, 0, NULL, 0) = 12
epoll_wait(4, {{EPOLLIN, {u32=6, u64=21474836486}}}, 4096, 4294967295) = 1
read(6, "\2\0\0\0n\3\0\0\n\0\4\0GET /index.php HTTP/"..., 8192) = 890
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=405, ...}) = 0
write(5, "[2018-03-16 14:37:44 *32694.0]\tN"..., 92) = 92
epoll_wait(4, {{EPOLLIN, {u32=6, u64=21474836486}}}, 4096, 4294967295) = 1
read(6, "\2\0\0\0\0\0\0\0\4\0\4\0", 8192) = 12
sendto(6, "\2\0\0\0\0\0\0\0\4\0\0\0", 12, 0, NULL, 0) = 12
epoll_wait(4, {{EPOLLIN, {u32=6, u64=21474836486}}}, 4096, 4294967295) = 1
read(6, "\3\0\0\0n\3\0\0\n\0\4\0GET /index.php HTTP/"..., 8192) = 890
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=405, ...}) = 0
write(5, "[2018-03-16 14:38:25 *32694.0]\tN"..., 92) = 92
epoll_wait(4,

**Comment by tsingsun** [comment]
通过nginx proxy_pass 转发至  9501端口

**Comment by matyhtf** [comment]
`strace -s 1000 -p 进程ID`，字符串被截断了。
