### ISSUE TITLE
Http Server 接收multipart/form-data空表单时出错，parse multipart body failed

### ISSUE THREAD

**Issue by wengee** [swoole/swoole-src#1521]
[/root/src/swoole-src-2.1.1/swoole_http_server.c:1092@http_onReceive]httpRequest 841 bytes:
---------------------------------------
POST /api/test HTTP/1.1
Host: localhost:9501
Connection: keep-alive
Content-Length: 44
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Cache-Control: no-cache
Origin: chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo
X-Postman-Interceptor-Id: 32b93ba5-9a80-bc01-578d-b9510e1eb71b
Postman-Token: 0490ad54-c25c-c9b4-4626-d01312c86a40
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryhGypiC5Kk68My9Dk
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Cookie: vivo_cookie_unique_id=CgAAC1qZIC0SJH9qAwMFAg==; ab=WbQTKeMm_Pmc-KByo0_GId5rbKQ; Hm_lvt_a7471116b9007c038d41873ab9121a9e=1520907607; Hm_lpvt_a7471116b9007c038d41873ab9121a9e=1520907607

------WebKitFormBoundaryhGypiC5Kk68My9Dk--

PHP Fatal error:  Uncaught ErrorException: Unknown: parse multipart body failed. in Unknown:0
Stack trace:
#0 [internal function]: Application->handleError(2, 'Unknown: parse ...', 'Unknown', 0, NULL)
#1 {main}
  thrown in Unknown on line 0
[2018-03-15 11:39:01 *20898.0]  ERROR   zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught ErrorException: Unknown: parse multipart body failed. in Unknown:0

**Comment by matyhtf** [comment]
忽略此错误，POST 内容可能存在多余的字节。致命错误是因为 使用了 set_error_handler 导致了。
