### ISSUE TITLE
php7.2.3 --enable-maintainer-zts 版本,安装swoole1.10.2 版本 执行make test 210文件卡住了

### ISSUE THREAD

**Issue by v3u3i87** [swoole/swoole-src#1525]
执行提示：
FAIL swoole_server: shutdown [tests/swoole_server/shutdown.phpt]

如图：
![image](https://user-images.githubusercontent.com/1936834/37555590-c65c0068-2a24-11e8-95c9-1c7d278ac8bc.png)

**Comment by matyhtf** [comment]
请单独执行这个 phpt 文件试试。

```shell
php tests/swoole_server/shutdown.phpt
```
