### ISSUE TITLE
Does v2.1.1 supports build with option --enable-openssl on php 7.2?

### ISSUE THREAD

**Issue by rovico** [swoole/swoole-src#1528]
1. What did you do? If possible, provide a recipe for reproducing the error.

Hi All! I need ssl support in swoole, and therefore i downloaded last version (2.1.1) and configured it with params ./configure --enable-sockets --enable-openssl --with-php-config=/usr/bin/php-config7.2

error occured when i runned ./make.sh

2. What did you expect to see?

I expected successfully built swoole application with ssl option

3. What did you see instead?

After ./make.sh I got two errors:

```
In file included from /home/pavel/work/swoole-src-2.1.1/swoole_coroutine.c:17:0:
/home/pavel/work/swoole-src-2.1.1/php_swoole.h:136:2: error: #error "Enable sockets support, require sockets extension."
#error "Enable sockets support, require sockets extension."
^
/home/pavel/work/swoole-src-2.1.1/php_swoole.h:142:2: error: #error "Enable http2 support, require nghttp2 library."
#error "Enable http2 support, require nghttp2 library."
```
I tried to install php7.2-sockets manually, but installer notified, that instead php7.2-sockets it will use php7.2-common and there is nothing to install.

With second error I have no idea too: I installed nghttp2 with command apt install nghttp2 but still got an error.

What I am doing wrong? And what I need to do to solve this problems?

4. What version of Swoole are you using (`php --ri swoole`)?

v2.1.1

5. What is your machine environment used (including version of kernel & php & gcc) ? 

php 7.2 on Ubuntu 16.04;

kernel: Linux nataly-nb.lo 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

6. If you are using ssl, what is your openssl version?

OpenSSL 1.1.0g  2 Nov 2017

**Comment by emdfreeman** [comment]
Please try --with-openssl-dir:

`./configure --enable-openssl -with-openssl-dir=/usr/lib/ -with-php-config=/usr/bin/php-config7.2`

**Comment by rovico** [comment]
Thank you for your answer, but no, It doesn't helps... 

What i did:

./configure --enable-openssl --with-openssl-dir=/usr/lib/ssl --with-php-config=/usr/bin/php-config7.2
and then ./make.sh

Here is the more complete error output. May be it will help:

```
/home/pavel/work/swoole-src-2.1.1/src/protocol/SSL.c:145:13: warning: ‘swSSL_lock_callback’ defined but not used [-Wunused-function]
 static void swSSL_lock_callback(int mode, int type, char *file, int line)
             ^
/home/pavel/work/swoole-src-2.1.1/src/protocol/SSL.c:158:13: warning: ‘swSSL_id_callback’ defined but not used [-Wunused-function]
 static void swSSL_id_callback(CRYPTO_THREADID * id)
             ^
In file included from /home/pavel/work/swoole-src-2.1.1/swoole_timer.c:19:0:
/home/pavel/work/swoole-src-2.1.1/php_swoole.h:136:2: error: #error "Enable sockets support, require sockets extension."
 #error "Enable sockets support, require sockets extension."
  ^
/home/pavel/work/swoole-src-2.1.1/php_swoole.h:142:2: error: #error "Enable http2 support, require nghttp2 library."
 #error "Enable http2 support, require nghttp2 library."
  ^
In file included from /home/pavel/work/swoole-src-2.1.1/swoole_server.c:17:0:
/home/pavel/work/swoole-src-2.1.1/php_swoole.h:136:2: error: #error "Enable sockets support, require sockets extension."
 #error "Enable sockets support, require sockets extension."
  ^
/home/pavel/work/swoole-src-2.1.1/php_swoole.h:142:2: error: #error "Enable http2 support, require nghttp2 library."
 #error "Enable http2 support, require nghttp2 library."
```

and below is also

```
/home/pavel/work/swoole-src-2.1.1/php_swoole.h:136:2: error: #error "Enable sockets support, require sockets extension."
 #error "Enable sockets support, require sockets extension."
  ^
/home/pavel/work/swoole-src-2.1.1/php_swoole.h:142:2: error: #error "Enable http2 support, require nghttp2 library."
 #error "Enable http2 support, require nghttp2 library."
  ^
In file included from /home/pavel/work/swoole-src-2.1.1/swoole_http_v2_server.c:18:0:
/home/pavel/work/swoole-src-2.1.1/swoole_http.h:26:29: fatal error: nghttp2/nghttp2.h: No such file or directory

***

Makefile:258: failed to perform the recipe for the target «swoole_trace.lo»
make: *** [swoole_trace.lo] Error 1
In file included from /home/pavel/work/swoole-src-2.1.1/swoole_http_v2_client_coro.c:18:0:
/home/pavel/work/swoole-src-2.1.1/swoole_http.h:26:29: fatal error: nghttp2/nghttp2.h: No such file or directory
Makefile:256: failed to perform the recipe for the target «swoole_ringqueue.lo»
make: *** [swoole_ringqueue.lo] Error 1
Makefile:212: failed to perform the recipe for the target «swoole_event.lo»
make: *** [swoole_event.lo] Error 1
Makefile:234: failed to perform the recipe for the target «swoole_websocket_server.lo»
make: *** [swoole_websocket_server.lo] Error 1
Makefile:254: failed to perform the recipe for the target «swoole_channel_coro.lo»
make: *** [swoole_channel_coro.lo] Error 1
compilation terminated.
```

**Comment by rovico** [comment]
I tried to build swoole with the same config on Centos system and it works!!! 

Please don't close this question untill I write, thats ok and i know what was the trouble...

**Comment by rovico** [comment]
So... My first fault was the i runned ./make.sh instead of make.

The second I don't know why, but on ubuntu i have to hack file php_swoole.h to build swoole with ssl support.

Like written in https://github.com/swoole/swoole-src/issues/1403 and https://github.com/youzan/zan/issues/7 I added #define HAVE_SOCKETS  1 right after #ifdef SW_SOCKETS string and then swoole make was compilled successful. 

I think, this is not good, but the only fast solution for this problem.

**Comment by Teranode** [comment]
for the nghttp2 do: 
`apt install libnghttp2-dev`

im definitely not sure about the sockets thing case im getting the error for that too.
