### ISSUE TITLE
addProcess under the SWOOLE_BASE mode

### ISSUE THREAD

**Issue by RootYQ** [swoole/swoole-src#1529]
```
<?php 
$server = new swoole_server('127.0.0.1', 9501, SWOOLE_BASE);

$process = new swoole_process(function($process) use ($server) {
    while (true) {
        $msg = $process->read();
        foreach($server->connections as $conn) {
            $server->send($conn, $msg);
        }
    }
});

$server->addProcess($process);

$server->on('receive', function ($serv, $fd, $from_id, $data) use ($process) {
   
    $process->write($data);
});

$server->start();
 ?>
```
i use the telnet to send the data,  but  can't receive the same data,  the default mode SWOOLE_PROCESS  works fine. i don't know why, show me the right way, thanks

**Comment by RootYQ** [comment]
the version is 1.9.21

**Comment by matyhtf** [comment]
Please submit an issue in accordance with the issue template and post detailed environmental information.

I guess your system may not have pcre, and so you cannot use the connections iterator.

**Comment by matyhtf** [comment]
The server with BASE mode cannot use connections and send.
