### ISSUE TITLE
 undefined symbol: zim_swoole_connection_iterator_rewind)

### ISSUE THREAD

**Issue by yangshen1987** [swoole/swoole-src#1530]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
make and make install 

2. What did you expect to see?
OK

3. What did you see instead?
 undefined symbol: zim_swoole_connection_iterator_rewind)

4. What version of Swoole are you using (`php --ri swoole`)?
Unable to load dynamic library

5. What is your machine environment used (including version of kernel & php & gcc) ? 
php 7.2.3

6. If you are using ssl, what is your openssl version?
no

**Comment by matyhtf** [comment]
Recompile the swoole extension with the correct `phpize` and `php-config`

**Comment by yangshen1987** [comment]
恩 我重启了就好了，多谢了
