### ISSUE TITLE
ubuntu16.04 php7.2.3 swoole 2.1.1编译成功启动失败

### ISSUE THREAD

**Issue by zuozhehao** [swoole/swoole-src#1533]
Program received signal SIGSEGV, Segmentation fault.
0x00007fffeb9c322f in swShareMemory_mmap_create (object=<optimized out>, size=2097248, mapfile=<optimized out>)
    at /opt/swoole-2.1.1/src/memory/ShareMemory.c:122
122	/opt/swoole-2.1.1/src/memory/ShareMemory.c: 没有那个文件或目录.

**Comment by yunnian** [comment]
可以提供下 能复现的最少php代码吗

**Comment by zuozhehao** [comment]
@yunnian 
正常编译成功后,加载扩展,执行php -v / php --ri swoole 都无法正常.

**Comment by matyhtf** [comment]
请勿使用尚在实验中的编译参数，重新进行`configure`
