### ISSUE TITLE
请教关于Coroutine HTTP Client 内存不释放的问题

### ISSUE THREAD

**Issue by luoxiaojun1992** [swoole/swoole-src#1540]
问题描述：
执行get方法后内存增加，并且一直不释放，请教一下具体原因，谢谢。

环境配置：
1. Centos 7
2. CPU 2 cores
3. Memory 4GB
4. Swoole 2.1.0
5. PHP 7.2.0beta3

代码如下：
`<?php

$host = 'www.baidu.com';
$uri = '/';
$port = 443;
$ssl = true;

go(function () use ($host, $uri, $port, $ssl) {
    $cli = new Co\Http\Client($host, $port, $ssl);
    for ($i = 0; $i < 10; ++$i) {
        $start = microtime(true);
        $cli->get($uri);
        $cli->close();
        echo memory_get_usage() / 1000, 'KB', PHP_EOL;
    }
});`

执行结果：
410.024KB
410.12KB
410.184KB
410.248KB
410.312KB
410.376KB
410.44KB
410.504KB
410.568KB
410.632KB

**Comment by matyhtf** [comment]
只是`10`个请求无法断定是内存泄漏，建议写一个持续运行的程序，长时间观察内存的占用情况。

**Comment by luoxiaojun1992** [comment]
使用了beta版导致的内存泄漏

更新代码：
```php
<?php

ini_set('memory_limit', -1);

$host = 'www.baidu.com';
$uri = '/';
$port = 443;
$ssl = true;

go(function () use ($host, $uri, $port, $ssl) {
    $cli = new Co\Http\Client($host, $port, $ssl);

    $i = 0;
    while (true) {
        $start = microtime(true);
        $cli->get($uri);
        $cli->close();
        ++$i;
        echo memory_get_usage() / 1000, 'KB', PHP_EOL;
        if (memory_get_usage() > 2000000000) {
            echo '请求次数：' . $i, PHP_EOL;
            echo '内存占用超过2GB，', memory_get_usage() / 1000, 'KB', PHP_EOL;
            break;
        }
    }
});
```

测试结果：
php 7.1.3：
621.632KB
621.664KB
621.664KB
621.664KB
621.664KB
621.664KB
621.664KB
621.664KB
621.664KB
621.664KB
621.664KB
621.664KB
621.664KB
621.664KB
621.664KB
621.664KB
621.664KB
......

PHP 7.2.3：
402.888KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
402.92KB
......

PHP 7.2.0beta3：
411.12KB
411.216KB
411.28KB
411.344KB
411.408KB
411.472KB
411.536KB
411.6KB
411.664KB
411.728KB
411.792KB
411.856KB
411.92KB
411.984KB
412.048KB
412.112KB
412.176KB
412.24KB
412.304KB

**Comment by luoxiaojun1992** [comment]
补充更正：不是因为php版本导致内存泄漏，是因为安装了opencensus扩展导致的内存泄漏。
