### ISSUE TITLE
项目是好项目，但是编译的时候N多warning，能不能解决一下呢？

### ISSUE THREAD

**Issue by springleng** [swoole/swoole-src#1544]
项目是好项目，但是编译的时候N多warning，能不能解决一下呢？

**Comment by yunnian** [comment]
你的是什么环境，warning的问题我来解决吧

**Comment by springleng** [comment]
@yunnian MacOS 10.13.4、php 7.2.4 下编译参数  ./configure --enable-async-redis --enable-mysqlnd --enable-coroutine --enable-openssl --enable-http2 --with-openssl-dir=/usr/local/opt/openssl --enable-sockets
需要的第三方包hiredis、openssl、nghttp2都是通过brew安装的

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/pull/1545
