### ISSUE TITLE
Swoole locks never work - reproduced on two machines and different swoole versions

### ISSUE THREAD

**Issue by Davis-2018** [swoole/swoole-src#1552]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

A. Lock constants are not defined in swoole 2.1.1
```
echo SWOOLE_RWLOCK;
echo SWOOLE_MUTEX;
echo SWOOLE_SEM;
echo SWOOLE_SEM;
echo SWOOLE_FILELOCK;
// Warning: Use of undefined constant SWOOLE_***** - assumed 'SWOOLE_*****' (this will throw an Error in a future version of PHP) in *****/test.php on line *****
```
B. Locks not working:

```
$lock_1 = new swoole_lock(1);
$lock_2 = new swoole_lock(1);

var_dump($lock_1->lock_read());
// result: bool(false)

var_dump($lock_2->lock());
// result: bool(false)
```

```
$lock = new swoole_lock(4);

var_dump($lock->lock());
// Result: Assertion failed: (key != 0), function swSem_create, file /Users/***USER***/Desktop/pecl/swoole-src/src/lock/Semaphore.c, line 27. Abort trap: 6
```
I had a problem with mutex locks too, but surprisingly I can't reproduce it anymore

2. What did you expect to see?

A. Constants should be defined.
B. Locks should be acquired in normal conditions.

3. What did you see instead?
Errors!

4. What version of Swoole are you using (`php --ri swoole`)?

Tested on Swoole 2.1.1 and Swoole 1.10.3.
In Swoole 1.10.3 locks doesn't work.
In Swoole 2.1.1 locks doesn't work and above constants aren't defined.

5. What is your machine environment used (including version of kernel & php & gcc) ? 
PHP 7.2.4 on macOS Sierra.
Also errors reproduced by on another machine too (thanks to @makadev)

6. If you are using ssl, what is your openssl version?
Compiled by openssl 1.0.2o_1

-------------

Here is a short discussion in question's comments regarding this issue on stackoverflow:

https://stackoverflow.com/questions/49702175/using-swoole-locks-in-php?noredirect=1#comment86439328_49702175

**Comment by matyhtf** [comment]
Thank you for your feedback. There is a bug in rwlock, and  an invalid assertion in the semaphore.

**Comment by 977945676** [comment]
I recompiled the latest code and found the problem persists.
