### ISSUE TITLE
How to use swoole_http_client to connect to specific domain?

### ISSUE THREAD

**Issue by DrOctavius** [swoole/swoole-src#1555]
Hi,
one quick question:
How to use swoole_http_client to connect to specific domain?
On the server side i have Nginx that proxies the Swoole Server (through Javascript works well!) but through Swoole Client i don't understand how to also use WSS
Thank you!

$cli = new swoole_http_client('wss://mydomain.com/api_ws/',443);
$cli->upgrade('nanu.dev.wippo-it.net/api_ws/', function ....

**Comment by matyhtf** [comment]
```php
$ssl = true;
$cli = new swoole_http_client('mydomain.com', 443, $ssl);

$cli->setHeaders([
    'Host' => 'nanu.dev.wippo-it.net',
]);

$cli->on('message', function ($_cli, $frame) {
    var_dump($frame);
});

$cli->upgrade('/api_ws/', function ($cli) {
    echo $cli->body;
    $cli->push("hello world");
});

```

**Comment by DrOctavius** [comment]
Woah, amazing! :) thank you, 
but one thing: PHP Fatal error:  swoole_http_client::__construct(): require openssl library. in .......
Is it true? because usually it's being found in php-common package (Centos 6.9 Final)

**Comment by matyhtf** [comment]
Need to enable openssl support when compiling extension.

```php
./configure --enable-openssl
# or
./configure --with-openssl-dir=/your/path/to/openssl
```

**Comment by DrOctavius** [comment]
Thank you sir!
