### ISSUE TITLE
swoole2.1.1,post请求携带from-data参数报错

### ISSUE THREAD

**Issue by woann** [swoole/swoole-src#1556]
报错如下：
PHP Fatal error: Possible integer overflow in memory allocation (1 * 18446744073709551615 1) in /home/wwwroot/swoole/http.php on line 16 [2018-04-09 13:49:47 *22809.0] ERROR zm_deactivate_swoole (ERROR 503): Fatal error: Possible integer overflow in memory allocation (1 * 18446744073709551615 1) in /home/wwwroot/swoole/http.php on line 16. [2018-04-09 13:49:47 $22804.0] WARNING swManager_check_exit_status: worker#0 abnormal exit, status=255, signal=0

**Comment by woann** [comment]
php版本7.2.3

**Comment by woann** [comment]
不是执行php文件的过程中报错，服务可以正常启动，httpserver，发起请求时携带form-data的参数就会报错application/x-www-form-urlencoded的参数就正常

**Comment by matyhtf** [comment]
请使用 2.1.2 版本测试一下

**Comment by woann** [comment]
好的， 我重新安装swoole试试
