### ISSUE TITLE
Using corutine and http client

### ISSUE THREAD

**Issue by lotarbo** [swoole/swoole-src#1563]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Hello, i try use corutine as in exaple
```
go(function () {
    $http = new Co\Http\Client("api.tumblr.com", 80, false);
    $ret  = $http->get('/v2/blog/peacecorps.tumblr.com/posts/text?api_key=fuiKNFp9vQFvjLNvx4sUwti4Yb5yGutBN4Xh10LXZhhRKjWlV4&notes_info=true');
    $http->set(['timeout' => 5]);

    $http->close();
    var_dump(json_decode($http->body, true));
    var_dump($http->errCode);
});
```

2. What did you expect to see?

parsed json end errCode = 0

3. What did you see instead?
sometimes it work, sometimes i have 110 error
i mean i run
`php test.php`
end have 110 error
second time - all ok

4. What version of Swoole are you using (`php --ri swoole`)?

```
swoole support => enabled
Version => 2.1.2
Author => tianfeng.han[email: mikan.tenny@gmail.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
debug => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ? 

```
alpine 3.6.2
PHP 7.2.4
```

6. If you are using ssl, what is your openssl version?
`LibreSSL 2.5.5`

**Comment by lotarbo** [comment]
and where i can found more information about Co\Http\Client? This is alies for Swoole\Coroutine\Http\Client ?
and if i use go(), i must use Co\Http\Client? or i can use if want simple client?

**Comment by twose** [comment]
110 is UNIX error code, it means `timeout`, maybe your network is unstable.
You can use `socket_strerror($code)` to get error message.
Coroutine client must run in the coroutine env, such as `go`or another `event-callbacks`.

**Comment by lotarbo** [comment]
@twose thank you for explaining.
And Co\Http\Client is allies for Swoole\Coroutine\Http\Client ?
I found API documentation, https://wiki.swoole.com/wiki/page/p-coroutine.html
but it's in Chinese, but eng docs doesn't so full(

**Comment by twose** [comment]
@lotarbo Yes.
All of alias is here: 
|   Class   |   Alias   |
| ---- | ---- |
|swoole_server|Swoole\\Server|
|swoole_timer|Swoole\\Timer|
|swoole_event|Swoole\\Event|
|swoole_async|Swoole\\Async|
|swoole_connection_iterator|Swoole\\Connection\\Iterator|
|swoole_exception|Swoole\\Exception|
|swoole_atomic|Swoole\\Atomic|
|swoole_atomic_long|Swoole\\Atomic\\Long|
|swoole_buffer|Swoole\\Buffer|
|swoole_channel|Swoole\\Channel|
|swoole_client|Swoole\\Client|
|swoole_http_client|Swoole\\Http\\Client|
|swoole_http_server|Swoole\\Http\\Server|
|swoole_http_response|Swoole\\Http\\Response|
|swoole_http_request|Swoole\\Http\\Request|
|swoole_http2_client|Swoole\\Http2\\Client|
|swoole_http2_response|Swoole\\Http2\\Response|
|swoole_lock|Swoole\\Lock|
|swoole_mmap|Swoole\\Mmap|
|swoole_msgqueue|Swoole\\MsgQueue|
|swoole_mysql|Swoole\\MySQL|
|swoole_mysql_exception|Swoole\\MySQL\\Exception|
|swoole_process|Swoole\\Process|
|swoole_process_pool|Swoole\\Process\\Pool|
|swoole_redis|Swoole\\Redis|
|swoole_redis_server|Swoole\\Redis\\Server|
|swoole_ringqueue|Swoole\\RingQueue|
|swoole_serialize|Swoole\\Serialize|
|swoole_server_port|Swoole\\Server\\Port|
|swoole_table|Swoole\\Table|
|swoole_table_row|Swoole\\Table\\Row|
|swoole_websocket_server|Swoole\\WebSocket\\Server|
|swoole_websocket_frame|Swoole\\WebSocket\\Frame|

#1442
