### ISSUE TITLE
IDE helper 生成 2.1.1 版本的协程 Client 中，setDefer 方法有一个必填参数，但 demo 没有

### ISSUE THREAD

**Issue by withloveandjoy** [swoole/swoole-src#1572]
public function setDefer($defer){}

例子中使用 setDefer 并无参数，如：
https://wiki.swoole.com/wiki/page/p-coroutine_multi_call.html

但是运行了代码不填参数也可以通过。

**Comment by twose** [comment]
可以用 [swoole-ide-helper](https://github.com/eaglewu/swoole-ide-helper) 这个
协程部分已经更新了最新代码并且附有官方文档作为注释

**Comment by RobberPhex** [comment]
这个应该是在swoole扩展在申明`setDefer`method的时候参数个数搞错了。导致swoole/ide-helper拿method信息的时候搞错了。

Will fix at #1575
