### ISSUE TITLE
swoole-src 1.7.8stable  跟 swoole-src swoole-1.7.9-rc2 自己make失败

### ISSUE THREAD

**Issue by dplord** [swoole/swoole-src#158]
我先git clone了最新代码
phpize
./configure --with-php-config=
make
make install
之后
是用swoole出了问题

然后我就下一个稳定版本的
源码在
https://github.com/swoole/swoole-src/releases
下载的
编译swoole-src-swoole-1.7.8-stable， make 时候报错如下

 -I/home/dengpan/下载/swoole-src-swoole-1.7.8-stable -I/home/dengpan/opt/php-5.6.0/include/php -I/home/dengpan/opt/php-5.6.0/include/php/main -I/home/dengpan/opt/php-5.6.0/include/php/TSRM -I/home/dengpan/opt/php-5.6.0/include/php/Zend -I/home/dengpan/opt/php-5.6.0/include/php/ext -I/home/dengpan/opt/php-5.6.0/include/php/ext/date/lib -I/include -I/home/dengpan/下载/swoole-src-swoole-1.7.8-stable/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /home/dengpan/下载/swoole-src-swoole-1.7.8-stable/swoole_async.c  -fPIC -DPIC -o .libs/swoole_async.o
yacc  /home/dengpan/ 
/home/dengpan/:1.1: error: syntax error, unexpected end of file
/usr/bin/bison: input/output error
<builtin>: recipe for target '/home/dengpan/下载/swoole-src-swoole-1.7.8-stable/swoole_process.c' failed
make: *** [/home/dengpan/下载/swoole-src-swoole-1.7.8-stable/swoole_process.c] Error 1

编译swoole-src-swoole-1.7.9-rc2， make 时候报错如下
/home/dengpan/:1.1: error: syntax error, unexpected end of file
/usr/bin/bison: input/output error
<builtin>: recipe for target '/home/dengpan/下载/swoole-src-swoole-1.7.9-rc2/swoole_server.c' failed
make: *** [/home/dengpan/下载/swoole-src-swoole-1.7.9-rc2/swoole_server.c] Error 1

gcc 是 4.8.3版本的,  系统是 openSuse13.2 ,php 是自己编译的 php 5.6.0

**Comment by matyhtf** [comment]
请不要使用中文路径

**Comment by dplord** [comment]
@matyhtf   
挪到非中文路劲下
编译是成功了
但是总是爆段错误
8555 segmentation fault  php s1.php

php --re swoole | grep version
Extension [ <persistent> extension #49 swoole version 1.7.9-rc3

**Comment by dplord** [comment]
@matyhtf   现在不爆段错误了

使用1.7.8-stable 挪到中文路劲 编译成功了
但是1.7之后的几个版本都是

比如我用了一个demo例子
swoole官网的一段代码, 存为 2.php

root@linux-xsbw:/tmp # php 2.php 

那就长期卡在这里
![2](https://cloud.githubusercontent.com/assets/2518520/5592796/8325965c-921e-11e4-8dc5-3c3ad3cbc5f2.jpeg)

就是不动了
netstat -plunt也没看到相应的端口被监听

![1](https://cloud.githubusercontent.com/assets/2518520/5592797/9583229c-921e-11e4-8a8e-d16d3c62c555.jpeg)

我之前用swoole老版的时候 用的好好的， 不知道这次出了这个情况

pecl install swoole也是
php 2.php 半天卡着不动了

**Comment by dplord** [comment]
I have fixed it
@matyhtf  
github的上面的代码

```php
// create a server instance
$serv = new swoole_server("127.0.0.1", 9501); 

// attach handler for connect event, once client connected to server the registered handler will be executed
$serv->on('connect', function ($serv, $fd){  
    echo "Client:Connect.\n";
});

// attach handler for receive event, every piece of data received by server, the registered handler will be
// executed. And all custom protocol implementation should be located there.
$serv->on('receive', function ($serv, $fd, $from_id, $data) {
    $serv->send($fd, $data);
});

$serv->on('close', function ($serv, $fd) {
    echo "Client: Close.\n";
});

// start our server, listen on port and ready to accept connections
$serv->start();
```

运行不起来, 卡在 $serv->start();
http://www.swoole.com/ 的代码 运行的 起来
swoole 1.7.8-stable

Thx
