### ISSUE TITLE
使用docker编译安装swoole为什么会出现各种问题？

### ISSUE THREAD

**Issue by Veitor** [swoole/swoole-src#1586]
我自己编写Dockerfile，想构建特定的带有swoole的php环境，但试了很多次，无论是在本地windows机器上，还是在centos上，docker build 构建时在编译安装swoole环节总是报一些错误。哪怕我采用最小化的构建内容，只安装swoole，也会报错。。

有什么注意点吗？如只能配指定的PHP版本？

![image](https://user-images.githubusercontent.com/7483890/39343392-2a8a2c4a-4a0f-11e8-809d-c159ce8c5115.png)
![image](https://user-images.githubusercontent.com/7483890/39343432-54a4bf72-4a0f-11e8-9a4a-bff3dad5a7a1.png)
![image](https://user-images.githubusercontent.com/7483890/39343695-d4004bbe-4a10-11e8-9b1e-76b1e7a707fc.png)

Dockerfile内容：
```
FROM php:latest

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        openssl \
        libssh-dev \
        libpcre3 \
        libpcre3-dev \
        libnghttp2-dev \
        libhiredis-dev \
        curl \
        wget \
        zip \
        unzip \
        git && \
        docker-php-ext-install iconv && \
        docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && \
        docker-php-ext-install gd


# install swoole
RUN cd /usr/local/src && \
    curl -O -L https://github.com/swoole/swoole-src/archive/v2.1.3.tar.gz && \
    tar -zxvf ./v*.tar.gz && cd swoole-src* && \
    phpize && \
    ./configure && \
    make && make install && \
    docker-php-ext-enable swoole
```

**Comment by matyhtf** [comment]
warning 的信息可以忽略

**Comment by menghuan** [comment]
我也使用 pecl install swoole 报错
安装最新版  docker下面

compilation terminated.
Makefile:194: recipe for target 'src/core/array.lo' failed
make: *** [src/core/array.lo] Error 1
ERROR: `make' failed

https://github.com/swoole/swoole-src/issues/1586#issuecomment-444467633 同上

**Comment by twose** [comment]
@menghuan 
https://github.com/twose/swoole-docker

**Comment by menghuan** [comment]
> @menghuan
> https://github.com/twose/swoole-docker

thinks
