### ISSUE TITLE
swoole-2.1.0 :WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by fathpanus** [swoole/swoole-src#1591]
多端口监听(websocket + http)时出现，websocket那个端口的onRequest正常响应，http的这个端口无法正常响应.
code: 
$host = '192.168.2.109';
$port = 9800;

$server = new \Swoole\WebSocket\Server($host, $port);
$setting = [
    'pid_file' => __DIR__ . '/swoole.pid',
];
$server->set($setting);
//        $iHost = '127.0.0.1';
$iHost = $host;
$iPort = 9810;
// websocket connect
$server->on('open', function($server, $request) {
    $server->push('welcome');
});
$server->on('message', function ($server, $frame) {
    $msg = $frame->data;
    $server->push($frame->fd, $msg);
});
$server->on('request', function ($request, $response) {
    $body = "body";
    $response->end($body);
});
$innerServer = $server->addListener($iHost, $iPort, SWOOLE_SOCK_TCP);
$innerServer->set([
    'open_websocket_protocol' => false,
]);
$innerServer->on('request', function ($request, $response) {
    $response->end("wwww");
});

$server->start();

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?
swoole

swoole support => enabled
Version => 2.1.0
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 
uname -a : Linux localhost.localdomain 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PHP: PHP 7.0.29 (cli) (built: Mar 30 2018 08:06:59) ( NTS )
gcc: Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 

6. If you are using ssl, what is your openssl version?
Openssl version: 
OpenSSL 1.0.2k-fips
7. valgrind输出
[root@localhost src]# USE_ZEND_ALLOC=0 valgrind php server.php 
==13863== Memcheck, a memory error detector
==13863== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==13863== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==13863== Command: php server.php
==13863== 
==13863== Thread 2:
==13863== Syscall param write(buf) points to uninitialised byte(s)
==13863==    at 0x82ED6AD: ??? (in /usr/lib64/libpthread-2.17.so)
==13863==    by 0x13D51B42: swReactorThread_send2worker (ReactorThread.c:555)
==13863==    by 0x13D533F9: swReactorThread_dispatch (ReactorThread.c:1467)
==13863==    by 0x13D58832: swPort_onRead_raw (Port.c:259)
==13863==    by 0x13D50ECC: swReactorThread_onRead (ReactorThread.c:910)
==13863==    by 0x13D450C8: swReactorEpoll_wait (ReactorEpoll.c:251)
==13863==    by 0x13D52D67: swReactorThread_loop (ReactorThread.c:1351)
==13863==    by 0x82E6E24: start_thread (in /usr/lib64/libpthread-2.17.so)
==13863==    by 0x7E1134C: clone (in /usr/lib64/libc-2.17.so)
==13863==  Address 0x16068bc1 is on thread 2's stack
==13863==  in frame #2, created by swReactorThread_dispatch (ReactorThread.c:1370)
==13863== 
==13866== Invalid read of size 8
==13866==    at 0x13CDABEF: sw_coro_create (swoole_coroutine.c:249)
==13866==    by 0x13CC9494: php_swoole_onReceive (swoole_server.c:852)
==13866==    by 0x13CF120C: http_onReceive (swoole_http_server.c:1016)
==13866==    by 0x13D5763B: swWorker_onTask (Worker.c:308)
==13866==    by 0x13D57820: swWorker_onPipeReceive (Worker.c:808)
==13866==    by 0x13D450C8: swReactorEpoll_wait (ReactorEpoll.c:251)
==13866==    by 0x13D57D0D: swWorker_loop (Worker.c:766)
==13866==    by 0x13D54ADB: swManager_spawn_worker (Manager.c:488)
==13866==    by 0x13D551BD: swManager_start (Manager.c:146)
==13866==    by 0x13D41921: swFactoryProcess_start (FactoryProcess.c:86)
==13866==    by 0x13D49526: swServer_start (Server.c:724)
==13866==    by 0x13CED8D7: zim_swoole_http_server_start (swoole_http_server.c:1639)
==13866==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
==13866== 
==13866== 
==13866== Process terminating with default action of signal 11 (SIGSEGV)
==13866==  Access not within mapped region at address 0x8
==13866==    at 0x13CDABEF: sw_coro_create (swoole_coroutine.c:249)
==13866==    by 0x13CC9494: php_swoole_onReceive (swoole_server.c:852)
==13866==    by 0x13CF120C: http_onReceive (swoole_http_server.c:1016)
==13866==    by 0x13D5763B: swWorker_onTask (Worker.c:308)
==13866==    by 0x13D57820: swWorker_onPipeReceive (Worker.c:808)
==13866==    by 0x13D450C8: swReactorEpoll_wait (ReactorEpoll.c:251)
==13866==    by 0x13D57D0D: swWorker_loop (Worker.c:766)
==13866==    by 0x13D54ADB: swManager_spawn_worker (Manager.c:488)
==13866==    by 0x13D551BD: swManager_start (Manager.c:146)
==13866==    by 0x13D41921: swFactoryProcess_start (FactoryProcess.c:86)
==13866==    by 0x13D49526: swServer_start (Server.c:724)
==13866==    by 0x13CED8D7: zim_swoole_http_server_start (swoole_http_server.c:1639)
==13866==  If you believe this happened as a result of a stack
==13866==  overflow in your program's main thread (unlikely but
==13866==  possible), you can try to increase the size of the
==13866==  main thread stack using the --main-stacksize= flag.
==13866==  The main thread stack size used in this run was 8388608.
==13866== 
==13866== HEAP SUMMARY:
==13866==     in use at exit: 5,970,653 bytes in 15,986 blocks
==13866==   total heap usage: 21,094 allocs, 5,108 frees, 6,594,518 bytes allocated
==13866== 
==13866== LEAK SUMMARY:
==13866==    definitely lost: 64 bytes in 2 blocks
==13866==    indirectly lost: 4,096 bytes in 2 blocks
==13866==      possibly lost: 1,153,134 bytes in 11,511 blocks
==13866==    still reachable: 4,813,359 bytes in 4,471 blocks
==13866==         suppressed: 0 bytes in 0 blocks
==13866== Rerun with --leak-check=full to see details of leaked memory
==13866== 
==13866== For counts of detected and suppressed errors, rerun with: -v
==13866== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
[2018-05-01 16:08:48 $13864.0]	WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11

**Comment by twose** [comment]
```php
$host = '127.0.0.1';
$port = 9800;

$server = new \Swoole\WebSocket\Server($host, $port);
$setting = [
    'pid_file' => __DIR__ . '/swoole.pid',
];
$server->set($setting);
// $iHost = '127.0.0.1';
$iHost = $host;
$iPort = 9810;
// websocket connect
$server->on('open', function ($server, $request) {
    $server->push($request->fd, 'welcome');
});
$server->on('message', function ($server, $frame) {
    $msg = $frame->data;
    $server->push($frame->fd, $msg);
});

$innerServer = $server->addListener($iHost, $iPort, SWOOLE_SOCK_TCP);
$innerServer->set([
    'open_http_protocol' => true,
]);
$innerServer->on('request', function ($request, $response) {
    $response->end("wwww");
});

$server->start();
```
稍作修改后测试可以正常运行 open的push少了个fd, websocket多了一个request回调, 增加的监听没有开启http协议支持.
相关issue: #1581 
提案: https://github.com/swoole/rfc-chinese/issues/3

**Comment by fathpanus** [comment]
OK,已解决，谢谢！
