### ISSUE TITLE
建议协程MySQL客户端支持unix socket

### ISSUE THREAD

**Issue by povsister** [swoole/swoole-src#1595]
异步mysql客户端在文档中表示支持Unixsocket链接方式
Swoole\MySQL
$mysql->connect([
            'host' => 'unix:/run/mysqld/mysql.sock',
             ...
        ]);

但协程mysql客户端在文档中未列出该特性，使用会报错
Swoole\Coroutine\MySQL
$mysql->connect([
            'host' => 'unix:/run/mysqld/mysql.sock',
             ...
        ]);

ERROR        zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Swoole\Coroutine\MySQL\Exception: connect to mysql server[unix:/run/mysqld/mysqld.sock:3306]

看起来像是自动把port加到了socket后面。。

swoole版本 2.1.3 release

php 7.2.4

**Comment by matyhtf** [comment]
已修复，实际上是支持的，目前版本存在一个 BUG，需要使用 `unix://` 表示。
