### ISSUE TITLE
协程MySQL客户端query操作时，错误处理不明确

### ISSUE THREAD

**Issue by povsister** [swoole/swoole-src#1598]
业务需要维护了一个MySQL连接池，但一晚上过后，总会因为MySQL连接闲置超时被挂掉一部分连接。
连接池不会主动PING MySQL以维护连接，连接池设计为如若断线则重连。
逻辑操作如下
1. pop() 从连接池获得一个 $mysql 链接实例
2. 执行 $mysql->query('SELECT 1') 检查 errno 是否为2006/2013 （参考Swoole官方文档）
3. 如若未发生错误，返回该连接以使用
4. 若发生错误，新建一个连接实例返回

但实际测试中，故意杀掉该连接后，$mysql->query 时会直接抛出异常，无法通过errno来检查
而且抛出的异常无法通过 Swoole\MySQL\Exception捕获 ，只能通过\Exception捕获

建议在协程MySQL客户端文档中明确各种操作可能出现的Exception及其code

    PHP Fatal error:  Uncaught ErrorException: Swoole\Coroutine\MySQL::query(): mysql connection#16 is closed. in project/app/Pools/MySQLPool.php:85
    Stack trace:
    #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Swoole\\Coroutin...', '/var/www/npubit...', 85, Array)
    #1 project/app/Pools/MySQLPool.php(85): Swoole\Coroutine\MySQL->query('SELECT 1')
    #2 project/app/Console/Commands/Swoole.php(154): App\Pools\MySQLPool->get()
    #3 {main}
    thrown in project/app/Pools/MySQLPool.php on line 85
    In MySQLPool.php line 85:

    Uncaught ErrorException: Swoole\Coroutine\MySQL::query(): mysql connection#16 is closed. in project/app/Pools/MySQLPool.php:85
    Stack trace:
    #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Swoole\\Coroutin...', 'project...', 85, Array)
    #1 project/app/Pools/MySQLPool.php(85): Swoole\Coroutine\MySQL->query('SELECT 1')
    #2 project/app/Console/Commands/Swoole.php(154): App\Pools\MySQLPool->get()
    #3 {main}
     thrown

    [2018-05-07 00:46:35 *280869.0]        ERROR        zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught ErrorException: Swoole\Coroutine\MySQL::query(): mysql connection#16 is closed. in project/app/Pools/MySQLPool.php:85
    Stack trace:
    #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Swoole\\Coroutin...', 'project...', 85, Array)
    #1 project/app/Pools/MySQLPool.php(85): Swoole\Coroutine\MySQL->query('SELECT 1')
    #2 project/app/Console/Commands/Swoole.php(154): App\Pools\MySQLPool->
    [2018-05-07 00:46:35 $280864.0]        WARNING        swManager_check_exit_status: worker#0 abnormal exit, status=255, signal=0

**Comment by povsister** [comment]
而且connect方法也是，文档写的由返回值确定是否连接成功，实际上也是直接抛出异常。。。

**Comment by joyme123** [comment]
文档表达的意思应该是通过异常的getCode()方法来判断

**Comment by matyhtf** [comment]
`query` 方法并不会抛出异常，只会打印一个错误信息而已。你可以通过 `swoole.display_errors = Off` 关掉错误消息。

变成异常的主要原因是的框架设置了`error_handler`，将错误日志转为异常抛出了。

**Comment by povsister** [comment]
原来如此，感谢解惑！第一次用Laravel框架就踩了个坑哈哈
