### ISSUE TITLE
swoole_server->addProcess 是否可以考虑支持 Process\Pool ？

### ISSUE THREAD

**Issue by HuangStomach** [swoole/swoole-src#1602]
When I want to use `addProcess` and `Process\Pool` in the same time, this will throw an error
It's there any plan to support it in the `swoole_server->addProcess`?
This will help us to manage processes more comfortable
Or this suggest is not reasonable?

目前如果我想同时使用 `addProcess` 和 `Process\Pool` 实际上是无法实现的
可否有这样的计划？
这样可以在一个应用下方便进行管理
或者说这样其实是不合理的？

**Comment by matyhtf** [comment]
Process\Pool 相当于是 Manager 的功能，本身 Swoole\Server 已自带了。

**Comment by HuangStomach** [comment]
也就是说如果我想利用`Swoole\Server`来实现类似于`Process\Pool`的功能，
相当于其实可以指定一部分`work`去接收请求，另一部分可以为我处理其他的后台服务逻辑，如队列监听消费等功能？
可以这么去理解使用吧

**Comment by matyhtf** [comment]
可以这样用。
