### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Existence01** [swoole/swoole-src#1624]
/Users/existence/Desktop/git/swoole/src/os/sendfile.c:23:5: error: conflicting
      types for 'swoole_sendfile'
int swoole_sendfile(int out_fd, int in_fd, off_t *offset, off_t size)
    ^
/Users/existence/Desktop/git/swoole/include/swoole.h:2166:5: note: previous
      declaration is here
int swoole_sendfile(int out_fd, int in_fd, off_t *offset, size_t size);
    ^
1 error generated.
make: *** [src/os/sendfile.lo] Error 1

OSX: 10.13.4
PHP:7.1

**Comment by twose** [comment]
应该是之前的bug, 请使用release或者最新master分支代码编译

**Comment by Existence01** [comment]
@twose 非常感觉, 已解决.之前用码云的最新master编译不通过, 后来用github的master过了
