### ISSUE TITLE
shutdown server failed

### ISSUE THREAD

**Issue by mobliyishengyuan** [swoole/swoole-src#163]
http://wiki.swoole.com/wiki/page/138.html
按照这个kill -15 主进程PID
日志中提示[2014-12-31 16:56:42]   NOTICE  Server is shutdown now.
但是ps -ef 看，master进程仍存在。
请问是什么原因啊

**Comment by mobliyishengyuan** [comment]
看错了哈，即使不设置process name，stop后都剩下master进程。这个是怎么回事啊。

**Comment by matyhtf** [comment]
最新的代码测试没有发现此问题。
