### ISSUE TITLE
Coroutine Tcp and Redis Client can not recv result

### ISSUE THREAD

**Issue by amuluowin** [swoole/swoole-src#1634]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

server

$server = new swoole_server("127.0.0.1", 9503);
$server->set([
    'worker_num' => swoole_cpu_num(), //worker process num
    'backlog' => 1280, //listen backlog
    'daemonize' => 0,
    'open_length_check' => 0,
    'package_length_type' => 'N',
    'package_length_offset' => 0,
    'package_length_type_len' => 4,
    'package_body_offset' => 4,
    'package_max_length' => 2097152, // 1024 * 1024 * 2,
    'buffer_output_size' => 3145728, //1024 * 1024 * 3,
    'pipe_buffer_size' => 33554432, // 1024 * 1024 * 32,
    'open_tcp_nodelay' => 1,
    'log_file' => '/data/logs/swoole_tcp.log',
    'heartbeat_check_interval' => 5,
    'heartbeat_idle_time' => 60,
    'tcp_defer_accept' => 5,
    'enable_reuse_port' => true,
    'pid_file' => sys_get_temp_dir() . '/swooletcp.pid',
    'enable_unsafe_event' => false,
    'open_cpu_affinity' => 1,
    'reload_async' => true,
    'max_request' => 100000,
]);
$server->on('connect', function ($server, $fd) {
    echo "connection open: {$fd}\n";
});
$server->on('receive', function ($server, $fd, $reactor_id, $data) {
    $server->send($fd, $data);
    $server->close($fd);
});
$server->on('close', function ($server, $fd) {
    echo "connection close: {$fd}\n";
});
$server->start();

client

class TcpPack
{

    public static function encode($buffer)
    {
        $buffer = Swoole\Serialize::pack($buffer);
        $total_length = strlen($buffer);
        return pack('N', $total_length) . $buffer;
    }

    public static function decode($buffer)
    {
        $buffer = substr($buffer, 4);
        return Swoole\Serialize::unpack($buffer);
    }

}

function TcpSend()
{
    $client = new Swoole\Coroutine\Client(SWOOLE_SOCK_TCP);
    $client->connect('127.0.0.1', '9503', 1);
    if ($client->errCode !== 0) {
        echo socket_strerror($client->errCode);
        return;
    }
    $data = [
        'service' => 'test',
        'route' => 'TestLogic',
        'method' => 'testRpc',
        'fastCall' => false,
        'params' => 456,
    ];
    $client->send(TcpPack::encode($data));
    var_dump("Tcp send by function");
    var_dump($client->recv());
}

class TcpClient
{

    public function send()
    {
        $client = new Swoole\Coroutine\Client(SWOOLE_SOCK_TCP);
        $client->connect('127.0.0.1', '9503', 1);
        if ($client->errCode !== 0) {
            echo socket_strerror($client->errCode);
            return;
        }
        $data = [
            'service' => 'test',
            'route' => 'TestLogic',
            'method' => 'testRpc',
            'fastCall' => false,
            'params' => 456,
        ];
        $client->send(TcpPack::encode($data));
        var_dump("Tcp send by class function");
        var_dump($client->recv());
    }
}

function HttpSend()
{
    $client = new \Swoole\Coroutine\Http\Client('127.0.0.1', 8500);
    $client->setDefer();
    $client->get('/v1/health/service/test');
    $client->recv();
    var_dump("Http send by function");
    var_dump($client->body);
}

class HttpClient
{
    public function __call($name, $params)
    {
        $client = new \Swoole\Coroutine\Http\Client('127.0.0.1', 8500);
        $client->setDefer();
        $client->get('/v1/health/service/test');
        $client->recv();
        var_dump("Http send by class function");
        var_dump($client->body);
    }
}

function RedisSend()
{
    $redis = new Swoole\Coroutine\Redis();
    $redis->connect('127.0.0.1', 6379);
    $redis->setDefer();
    $redis->get('key');
    var_dump("Redis send by function");
    var_dump($redis->recv());
}

class RedisClient
{
    public function __call($name, $params)
    {
        $redis = new Swoole\Coroutine\Redis();
        $redis->connect('127.0.0.1', 6379);
        $redis->setDefer();
        $redis->get('key');
        var_dump("Redis send by class function");
        var_dump($redis->recv());
    }
}

go(function () {
    print_r('***************Tcp test***************' . PHP_EOL);
    $client = new TcpClient();
    $client->send();
    print_r(PHP_EOL);

    $tcp = new Swoole\Coroutine\Client(SWOOLE_SOCK_TCP);
    $tcp->connect('127.0.0.1', '9503', 1);
    if ($tcp->errCode !== 0) {
        echo socket_strerror($tcp->errCode);
        return;
    }
    $data = [
        'service' => 'test',
        'route' => 'TestLogic',
        'method' => 'testRpc',
        'fastCall' => false,
        'params' => 456,
    ];
    $tcp->send(TcpPack::encode($data));
    var_dump("Tcp send by inline");
    var_dump(TcpPack::decode($tcp->recv()));
    print_r(PHP_EOL);

    TcpSend();
    print_r(PHP_EOL);

    print_r('***************Http test***************' . PHP_EOL);
    $conn = new HttpClient();
    $conn->send();
    print_r(PHP_EOL);

    $http = new \Swoole\Coroutine\Http\Client('127.0.0.1', 8500);
    $http->setDefer();
    $http->get('/v1/health/service/test');
    $http->recv();
    var_dump("Http send by inline");
    var_dump($http->body);
    print_r(PHP_EOL);

    HttpSend();
    print_r(PHP_EOL);

    print_r('***************Redis test***************' . PHP_EOL);
    $redis = new RedisClient();
    $redis->send();
    print_r(PHP_EOL);

    $redis = new Swoole\Coroutine\Redis();
    $redis->connect('127.0.0.1', 6379);
    $redis->setDefer();
    $redis->get('key');
    var_dump("Redis send by inline");
    var_dump($redis->recv());
    print_r(PHP_EOL);

    RedisSend();
    print_r(PHP_EOL);

});

2. What did you expect to see?
client can recv current result

3. What did you see instead?
***************Tcp test***************
string(26) "Tcp send by class function"
NULL

string(18) "Tcp send by inline"
array(5) {
  ["service"]=>
  string(4) "test"
  ["route"]=>
  string(9) "TestLogic"
  ["method"]=>
  string(7) "testRpc"
  ["fastCall"]=>
  bool(false)
  ["params"]=>
  int(456)
}

string(20) "Tcp send by function"
NULL

***************Http test***************
string(27) "Http send by class function"
string(828) "[{"Node":{"Node":"albert-PC","Address":"192.168.0.107","TaggedAddresses":{"wan":"192.168.0.107"},"CreateIndex":3,"ModifyIndex":82},"Service":{"ID":"service-192.168.0.107:9503-test","Service":"test","Tags":[],"Address":"192.168.0.107","Port":9503,"EnableTagOverride":false,"CreateIndex":76,"ModifyIndex":82},"Checks":[{"Node":"albert-PC","CheckID":"serfHealth","Name":"Serf Health Status","Status":"passing","Notes":"","Output":"Agent alive and reachable","ServiceID":"","ServiceName":"","CreateIndex":3,"ModifyIndex":3},{"Node":"albert-PC","CheckID":"service:service-192.168.0.107:9503-test","Name":"Service 'test' check","Status":"critical","Notes":"","Output":"dial tcp 192.168.0.107:9503: getsockopt: connection refused","ServiceID":"service-192.168.0.107:9503-test","ServiceName":"test","CreateIndex":76,"ModifyIndex":82}]}]"

string(19) "Http send by inline"
string(828) "[{"Node":{"Node":"albert-PC","Address":"192.168.0.107","TaggedAddresses":{"wan":"192.168.0.107"},"CreateIndex":3,"ModifyIndex":82},"Service":{"ID":"service-192.168.0.107:9503-test","Service":"test","Tags":[],"Address":"192.168.0.107","Port":9503,"EnableTagOverride":false,"CreateIndex":76,"ModifyIndex":82},"Checks":[{"Node":"albert-PC","CheckID":"serfHealth","Name":"Serf Health Status","Status":"passing","Notes":"","Output":"Agent alive and reachable","ServiceID":"","ServiceName":"","CreateIndex":3,"ModifyIndex":3},{"Node":"albert-PC","CheckID":"service:service-192.168.0.107:9503-test","Name":"Service 'test' check","Status":"critical","Notes":"","Output":"dial tcp 192.168.0.107:9503: getsockopt: connection refused","ServiceID":"service-192.168.0.107:9503-test","ServiceName":"test","CreateIndex":76,"ModifyIndex":82}]}]"

string(21) "Http send by function"
string(828) "[{"Node":{"Node":"albert-PC","Address":"192.168.0.107","TaggedAddresses":{"wan":"192.168.0.107"},"CreateIndex":3,"ModifyIndex":82},"Service":{"ID":"service-192.168.0.107:9503-test","Service":"test","Tags":[],"Address":"192.168.0.107","Port":9503,"EnableTagOverride":false,"CreateIndex":76,"ModifyIndex":82},"Checks":[{"Node":"albert-PC","CheckID":"serfHealth","Name":"Serf Health Status","Status":"passing","Notes":"","Output":"Agent alive and reachable","ServiceID":"","ServiceName":"","CreateIndex":3,"ModifyIndex":3},{"Node":"albert-PC","CheckID":"service:service-192.168.0.107:9503-test","Name":"Service 'test' check","Status":"critical","Notes":"","Output":"dial tcp 192.168.0.107:9503: getsockopt: connection refused","ServiceID":"service-192.168.0.107:9503-test","ServiceName":"test","CreateIndex":76,"ModifyIndex":82}]}]"

***************Redis test***************
string(28) "Redis send by class function"
NULL

string(20) "Redis send by inline"
string(5) "value"

string(22) "Redis send by function"
NULL

4. What version of Swoole are you using (`php --ri swoole`)?
swoole support => enabled
Version => 4.0.0-alpha
Author => tianfeng.han[email: mikan.tenny@gmail.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
sockets => enabled
openssl => enabled
http2 => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core) 
Release:	7.3.1611
Codename:	Core

PHP 7.1.17 (cli) (built: May 18 2018 17:00:18) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.17, Copyright (c) 1999-2018, by Zend Technologies

gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

6. If you are using ssl, what is your openssl version?

**Comment by shiguangqi** [comment]
fixed
