### ISSUE TITLE
process exec 和 linux exec 函数执行结果不同

### ISSUE THREAD

**Issue by ppanphper** [swoole/swoole-src#1635]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

`$process = new swoole_process('callback_function', false);`
`$pid = $process->start();`
`function callback_function(swoole_process $worker)`
`{`
   `$bool = $worker->exec('/bin/cp', array('-rf', '/test/*', '/tmp/test/'));`
    `var_dump($bool);`
`}`
`swoole_process::wait();`

2. What did you expect to see?
cp success.

3. What did you see instead?
/bin/cp: cannot stat `xxxx': No such file or directory

4. What version of Swoole are you using (`php --ri swoole`)?
1.10.5

5. What is your machine environment used (including version of kernel & php & gcc) ? 
Linux iZ23qinwbndZ 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
php5.6.11
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)

6. If you are using ssl, what is your openssl version?

process exec 不支持*匹配

但是直接在命令行执行
exec /bin/cp -rf /test/* /tmp/test/
是可以的

**Comment by matyhtf** [comment]
使用

 $worker->exec('/bin/sh', array('cp', '-rf', '/test/*', '/tmp/test/'));

**Comment by ppanphper** [comment]
@matyhtf 不可以，报不允许执行二进制文件
/bin/cp: /bin/cp: cannot execute binary file

**Comment by matyhtf** [comment]
```php
$process = new swoole_process('callback_function', false);
$pid = $process->start();
function callback_function(swoole_process $worker)
{
    $bool = $worker->exec('/bin/sh', array('-c', "cp -rf /data/test/* /tmp/test/"));
    var_dump($bool);
}
swoole_process::wait();
```
