### ISSUE TITLE
关于  getClientInfo 和 onBufferFull 的建议和疑问

### ISSUE THREAD

**Issue by malacca** [swoole/swoole-src#1638]
一、建议：期望 getClientInfo 返回信息中带上 worker_id

没有这个，如果我想查看每个 worker 上有多少连接数，做不到，现在我只能用 Table 共享缓存自己去再存一份连接信息，这个信息对于服务端的健康状态检查，算作比较重要的了吧

二、疑问：Server 的 onBufferFull 和 onBufferEmpty 触发问题

测试发现这两个是在主进程上触发的，而不是在正在执行输出的 worker 内触发的，也就是说 worker 自己根本没办法知道自己是不是触发了 BufferFull ，没办法确定是不是应该暂停输出。如果不借助于额外的东西（Process, Table 等），有办法直接通知 worker 吗 ？

三、其他：我甚至不知道以上疑问，我理解的是否正确

官方文档好多地方语焉不详，这个我就不多说了，反正也不会改。
就比如这个 onBufferFull 的文档 https://wiki.swoole.com/wiki/page/745.html
提到了 server->buffer_high_watermark 来控制大小，但却不说单位是什么，kb ? mb?

之前提过一个 Issue， 几个月过去了，0回复惨案 （不知道该哭还是该笑.jpg），知道你们在大力搞协程，可基础功能也照顾一下呗

**Comment by xianqiangzhao** [comment]
我所知道的，
1、 worker 上没有连接数，worker 是处理reactor 线程发过来的请求。reactor 线程负责维护客户端连接。
2、onBufferFull  是主进程上触发的，触发条件是
 if (serv->onBufferFull && conn->high_watermark == 0 && conn->out_buffer->length >= port->buffer_high_watermark)  //  \src\network\ReactorThread.c
单位是字节。
希望能帮到你。

**Comment by malacca** [comment]
嗯，根据我的测试，应该就是你说的这样，所以我才提了这个 Issue

1、 reactor 线程维护的，他在客户端和 worker 之间架桥梁，他应该知道 fd 分配到的 worker_id，getClientInfo 没返回这个记录，实际运维，知道每个 worker 的连接状况，对调整分配策略很有参考价值，没说这个有什么问题，只是建议

2、onBufferFull 在主进程触发，所以具体 BufferFull 的 worker 进程完全瞎，根本没办法根据实际情况调整输出，目前看来只能用共享内存或者额外跑个 process 进行协调。还有就是，实际测试发现 onBufferFull(Swoole\Server $serv, int $fd)  中的 serv->worker_id 并不是 bufferFull 的 woker_id。
这个回调用起来真心累。

单位那个，我只是表示一下对文档的无奈，这个设置真的是个迷，要想知道怎么用，恐怕只能看源码了

我试了

$server = new server()
$serer->set(cofing) // 放这里
$server->buffer_high_watermark=  //放这里

最后结果一样，缓存区大概到 11M 左右的时候，触发 onBufferFul

**Comment by matyhtf** [comment]
感谢你的反馈。
一、由于 `fd` 现在是自增的 `session_id` ，所以无法用 `fd` 推算出在哪个 `worker` 进程，可以增加此项信息
二、这种情况下，使用`BASE`模式好了，`onBufferFull`和`onBufferEmpty`均在当前进程内触发
三、单位为 字节

哪个 issue ？

**Comment by matyhtf** [comment]
已增加 `socket_fd` 项，表示实际的 socket 文件描述符 id，可计算出对应的 reactor 线程和 worker 进程。

**Comment by malacca** [comment]
@matyhtf 

请恕我愚钝， 没看出通过  socket_fd 如何计算，我测试了，请求落到不同的 worker 上，这个值是一样的

**Comment by matyhtf** [comment]
worker_id = fd % worker_num
reactor_thread_id = fd % reactor_num

**Comment by malacca** [comment]
@matyhtf 

dispatch_mode = 2 时，这个计算方式应该没问题，但对于其他分配策略，不能获得正确结果。
这样的话，想要知道 worker_id, 还得根据不同分配策略用不同的计算公式，另外还有那种自定义分配函数的，对于框架层，也无力计算，我对 swoole 的运行原理没特别了解，不晓得有没有办法直接返回 worker_id

**Comment by twose** [comment]
@malacca 
https://wiki.swoole.com/wiki/page/235.html
https://github.com/swoole/swoole-src/blob/master/tests/swoole_client_async/buffer_full.php.phpt

你看看这两个

**Comment by malacca** [comment]
@twose 

这个我知道，可是跟我说的这个不是一码事。这个是当前请求的 worker_id， 我这个是通过指定的 客户端 fd 获取其 worker_id

比如通过 getClientList 先获取所有 fd， 循环获取每个 fd 的 worker_id，这样就大致知道了当前总请求数和每个 worker_id 分配到的请求数。若分配不均匀或者不符合预期，可适当调整 dispatch_mode

你说的这个我也想过，每个请求进来，立即记录其 fd 和 worker_id， 处理完了就删除掉，自己维护一份连接的映射表。但我不知道这个活  swoole 是不是已经做了，只是没返回信息而已，所以提了这个建议
