### ISSUE TITLE
It is possible to create a SWOOLE_PROCESS in another SWOOLE_PROCESS? 

### ISSUE THREAD

**Issue by DrOctavius** [swoole/swoole-src#1642]
Hi
It is possible to create a SWOOLE_PROCESS in another SWOOLE_PROCESS? :)
It creates everything ok, but it works in the same Process... :(

**Comment by matyhtf** [comment]
I do not understand what you mean, please post the demo code

**Comment by DrOctavius** [comment]
for example:

 $process = new \swoole_process(function (\swoole_process $worker)  {
     AND HERE i would like to create another swoole_process :) (kind of PThreads...)

     $internal_process = new \swoole_process(function (\swoole_process $worker2)  {

     });
});

**Comment by matyhtf** [comment]
It can be used like this. What problems have you encountered?

```php
 $process = new \swoole_process(function (\swoole_process $worker)  {
     $internal_process = new \swoole_process(function (\swoole_process $worker2)  {
        swoole_timer_tick(1000, function () {
            echo "process 2\n";
        });
     });

$internal_process->start();

    swoole_timer_tick(1000, function () {
        echo "process 1\n";
    });


});

 $process->start();
```

**Comment by matyhtf** [comment]
The process is heavy, you can try to use coroutines.

**Comment by DrOctavius** [comment]
Well, the problem is that the Internal Process is being executed by the same Process  => $process
So i suppose it didn't create another process but it remained in the same one...
I wanted to create:

MAIN PROCESS => SWOOLE PROCESS => MULTIPLE (INTERNAL) SWOOLE PROCESSES
                          => SWOOLE PROCESS => MULTIPLE (INTERNAL) SWOOLE PROCESSES
                          => SWOOLE PROCESS => MULTIPLE (INTERNAL) SWOOLE PROCESSES

**Comment by DrOctavius** [comment]
the tick (is still using the same process) :)
i don't need to pause $process  ...
Anyway thank you very much for your time... i though that is possible (maybe i'm missing smth...)
Will you somehow migrate or Adapt to PThreads? (is that even possible? Don't know the low Level things...)

**Comment by matyhtf** [comment]
When exec `$process->start` will call fork syscall to create a new process.

The ZendVM  does not have full support for multithreading. Adapting pthreads can be very difficult.

You can try pthreads extension. https://github.com/krakjoe/pthreads
