### ISSUE TITLE
SwooleHttpServer在无文件上传时与$_FILES表现不一致

### ISSUE THREAD

**Issue by hhxsv5** [swoole/swoole-src#1648]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
无文件上传

```
//POST请求头
------WebKitFormBoundarynHKxKnUmjNQBfSeW
Content-Disposition: form-data; name="file1"; filename=""
Content-Type: application/octet-stream


------WebKitFormBoundarynHKxKnUmjNQBfSeW
Content-Disposition: form-data; name="Submit"

提交
------WebKitFormBoundarynHKxKnUmjNQBfSeW--
```

2. What did you expect to see?
SwooleHttpServer与FPM在无文件上传时，$files与$_FILES表现一致。
[如文档所述](https://wiki.swoole.com/wiki/page/428.html)

3. What did you see instead?

打印出$request->files时，其中error应为4，但得到的是0
```
//Swoole Http Server下
array(1) {
  ["file1"]=>
  array(5) {
    ["name"]=>
    string(0) ""
    ["type"]=>
    string(24) "application/octet-stream"
    ["tmp_name"]=>
    string(25) "/tmp/swoole.upfile.hnDotd"
    ["error"]=>
    int(0)
    ["size"]=>
    int(0)
  }
}
```

```
//FPM下，$_FILES
array(1) {
  ["file1"]=>
  array(5) {
    ["name"]=>
    string(0) ""
    ["type"]=>
    string(0) ""
    ["tmp_name"]=>
    string(0) ""
    ["error"]=>
    int(4)
    ["size"]=>
    int(0)
  }
}
```

4. What version of Swoole are you using (`php --ri swoole`)?

```
swoole

swoole support => enabled
Version => 2.0.10
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ? 

Debian GNU/Linux 8 \n \l

PHP 5.6.35 (cli) (built: May  1 2018 00:33:31)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

gcc version 4.9.2 (Debian 4.9.2-10+deb8u1)

6. If you are using ssl, what is your openssl version?

no

**Comment by twose** [comment]
是Swoole默认设定了错误码为`HTTP_UPLOAD_ERR_OK`导致的, 已在PR中修正
修复后有一处`UPLOAD_ERR_INI_SIZE`无法保持与PHP一致, 因为包体过大的请求会被直接拒绝

**Comment by hhxsv5** [comment]
@twose 谢谢
