### ISSUE TITLE
co\Redis with `auth` not return errCode

### ISSUE THREAD

**Issue by daydaygo** [swoole/swoole-src#1655]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
if the redis need `auth`, the co\Redis not return errCode

```php
// co\Redis
go(function () {
    $redis = new Co\Redis;
    $res = $redis->connect('redis', 6379);
    var_dump($redis->get('key'), $redis->errCode, $redis->errMsg); // auth 并不会有 errCode
});

// phpredis
$redis = new \Redis();
$redis->connect('redis');
var_dump($redis->get('key'));
```

2. What did you expect to see?
in `phpredis`, i got `Fatal error: Uncaught RedisException: NOAUTH Authentication required`

3. What did you see instead?
with `errCode=0` and `errMsg=''`

4. What version of Swoole are you using (`php --ri swoole`)?
v2.1.3

5. What is your machine environment used (including version of kernel & php & gcc) ? 

6. If you are using ssl, what is your openssl version?

**Comment by twose** [comment]
@daydaygo 
solved  in #1663
