### ISSUE TITLE
swoole在coroutine切换的时候有没有一个事件机制，可以在切换前后做一些自定义操作？

### ISSUE THREAD

**Issue by eslizn** [swoole/swoole-src#1659]
如果没有的话能否增加一个，这样的话可以针对现有较多使用了单例模式的php框架实现一个上下文隔离和切换的补丁

**Comment by eslizn** [comment]
@twose 通过php自身实现是需要修改框架源码的，我是想通过补丁的形式自己完成上下文管理，这样可以无缝切换

**Comment by shiguangqi** [comment]
@eslizn 感谢提出问题，协程的作用是给予开发者用户态切换执行的能力，上下文是需要自己来管理维护。
