### ISSUE TITLE
php版本兼容性问题

### ISSUE THREAD

**Issue by chunhei2008** [swoole/swoole-src#166]
swoole最低版本支持多少？ 官方说5.3+ 我在5.3.3上测试，swoole_timer_add 定时器这块有问题，阻塞了，不往下继续执行。
php版本
PHP 5.3.3 (cli) (built: Oct 30 2014 20:12:53) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

swoole版本
 Constant [ string SWOOLE_VERSION ] { 1.7.9-rc4 }

**Comment by matyhtf** [comment]
用strace看一下程序执行的过程

**Comment by matyhtf** [comment]
5.3 确实如此，调用异步函数后会进入时间循环，请使用5.4以上版本。
