### ISSUE TITLE
建议 扩充定时器功能

### ISSUE THREAD

**Issue by Git-XiaoQin** [swoole/swoole-src#1660]
现在异步毫秒定时器挺强大，但某些功能实现不太方便，建议新增一下方法：

1.  动态修改定时器间隔
使用场景：使用定时器定时请求API，可以不重建定时器而调整请求频率

2.  暂停、继续定时器

**Comment by twose** [comment]
感觉都可以用php代码来实现定时器的管理

**Comment by matyhtf** [comment]
可以使用 PHP 代码实现，没必要底层实现。
