### ISSUE TITLE
swoole2.2.0编译 携带--enable-openssl参数，编译通过但是swoole ssl功能不能正常使用

### ISSUE THREAD

**Issue by CrazyWorkers** [swoole/swoole-src#1668]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   swoole2.2.0重新编译支持openssl,编译通过，swoole ssl功能不能正常使用。

2. What did you expect to see?

   php --ri swoole中可以看到openssl的支持，swoole1.10.5中可以看到。

3. What did you see instead?

   php --ri swoole中可以看不到openssl的支持，SWOOLE_SSL常量不识别。

4. What version of Swoole are you using (`php --ri swoole`)?

   swoole2.2.0

5. What is your machine environment used (including version of kernel & php & gcc) ? 

   centos7 php7.1.4  Linux 3.10.0-514.6.2.el7.x86_64   gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)

6. If you are using ssl, what is your openssl version?

   openssl1.0.2k

**Comment by twose** [comment]
还有个: `--with-openssl-dir=你的openssl路径`
加入这个参数看看是否可行? 注意一下make的时候是否有错误提示?
最好贴一下你的编译脚本怎么写的

**Comment by CrazyWorkers** [comment]
具体的编译命令是:  ./configure --enable-openssl --with-openssl-dir=/usr/local/openssl
执行完并未报错。之后使用make,make install没报错。而且使用 php --ri swoole显示支持中未出现openssl的支持。使用openssl的源码包编译：./configure --enable-openssl --with-openssl-dir=/usr/local/lnamp/openssl-1.0.2k，也是同样的问题，但是在swoole1.10.5中使用相同的命令，ssl功能可以使用。

**Comment by matyhtf** [comment]
请勿同时使用 `./configure --enable-openssl --with-openssl-dir=/usr/local/openssl` ，检查 `config.h` 中是否有 `HAVE_OPENSSL`

**Comment by CrazyWorkers** [comment]
config.h中有HAVE_OPENSSL，编译完成后不能正常使用swoole的ssl功能。

**Comment by zhangli1** [comment]
使用pecl install swoole安装吧， 我用源码死都装不上去，用pecl一装就行
