### ISSUE TITLE
php_coroutine_reactor_can_e xit in Unknown on line 0

### ISSUE THREAD

**Issue by aftabnaveed** [swoole/swoole-src#1685]
Please answer these questions before submitting your issue. Thanks!

1. I am trying to compile branch 2.x-lts  with `./configure --disable-coroutine` but I get this error when loading the extension and thests also fail.  

```
php -i | grep "swool"
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/swoole.so' - /usr/lib/php/20160303/swoole.so: undefined symbol: php_coroutine_reactor_can_e
xit in Unknown on line 0
```

4. 2.x-lts

5. What is your machine environment used (including version of kernel & php & gcc) ? 
 ```
PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep  2 2017 05:56:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

**Comment by twose** [comment]
You can't do that...
Coroutine is the **Core** of 2.x+

**Comment by matyhtf** [comment]
This is a bug and I will fix it soon

**Comment by matyhtf** [comment]
Please execute the `make clean` to cleanup project
