### ISSUE TITLE
Swoole HTTP /1.1 specifications Compliance

### ISSUE THREAD

**Issue by aftabnaveed** [swoole/swoole-src#1687]
According to the documentation, Swoole is not yet recommended to replace traditional HTTP servers such as nginx or Apache. 
`swoole_http_server does not support the complete HTTP protocol, Nginx is recommended to be used as a proxy for Swoole HTTP server.`

My question is what exactly is it missing in the implementation?

**Comment by twose** [comment]
**Details**

**Comment by aftabnaveed** [comment]
@twose What do you mean by details here?

**Comment by twose** [comment]
@aftabnaveed 
e.g. 
#1600 http2 static files support
#1606  if you send a non-standard HTTP package, swoole can't parse it but nginx can do more(auto fix the lost space).
too many details like these so I can't tell you every detail totally.
swoole keep the simple and fast, only do what it should do.

**Comment by aftabnaveed** [comment]
Nice, but the question is about Http /1.1  I guess it would be somewhat similar to what you just described for Http2.

**Comment by matyhtf** [comment]
It is difficult to give an explicit list, the HTTP protocol is very complicated, and web servers also need to be compatible with many bad cases
