### ISSUE TITLE
can not compile with "--enable-async-mysql"

### ISSUE THREAD

**Issue by greennyreborn** [swoole/swoole-src#170]
OS: ubuntu 14.04 LTS
php: 5.5.9
mysql: 5.6.x

最开始是报找不到 my_global.h 的错，后来在MakeFile中加入  -I/usr/include/mysql
开始报这个错：
swoole.c:758:67: error: 'MYSQLND' has no member named 'date'
stream = mysql->mysql->data->net->data->m.get_stream(mysql->mysql->data->net TSRMLS_CC);

我在1.7.9和1.7.8的stable版本中都测试过，结果都一样。

**Comment by matyhtf** [comment]
建议手工下一个PHP版本，然后编译安装，编译时需要启用mysqli和mysqlnd.
