### ISSUE TITLE
How to determine table size to use

### ISSUE THREAD

**Issue by bjacog** [swoole/swoole-src#1703]
Mods are welcome to mark as question, I don't think this is a bug.

1. What did you do? If possible, provide a recipe for reproducing the error.
Create a swoole_websocket_server to manage users in multiple channels.
Keep a swoole table for all connected users.
Keep a swoole table containing each channel that has a connected user.
Keep a swoole for each channel, that holds the users in that channel.

Here are the three table snippets:
When the websocket server is started these are created:

```
$stClients = new swoole_table(1024 * 1024);
$stClients->column('fd', swoole_table::TYPE_INT);
$stClients->column('token', swoole_table::TYPE_STRING, 128);
$stClients->create();

$stMemberships = new swoole_table(1024 * 1024);
$stMemberships->column('group_id', swoole_table::TYPE_INT);
$stMemberships->column('members', swoole_table::TYPE_STRING, 1024);
$stMemberships->create();
```

onConnect I add this:
```
$stGroupChannel = new swoole_table(1024 * 1024);
$stGroupChannel->column('fd', swoole_table::TYPE_INT);
$stGroupChannel->column('ugb_id', swoole_table::TYPE_INT);
$stGroupChannel->create();
```

When I create the tables, I have now idea what size to use, using 1024 * 1024 crashes when a user connects and one of the 2nd or 3rd channels are created with out of memory.

Changing the size of the table to 1024 solves this, but I am not sure this is adequate.

2. What did you expect to see?
I expected the size to allocate memory of the number specified, 1024 * 1024 = 1MB and not exceed the memory of the server.

3. What did you see instead?
Websocket server crashed when trying to create a 2nd table of size 1024 * 1024.
Output:
```
[2018-06-11 01:30:41 @24903.0]	WARNING	swShareMemory_mmap_create: mmap(1412641536) failed. Error: Cannot allocate memory[12]
```

4. What version of Swoole are you using (`php --ri swoole`)?
```
[ec2-user@ip-xxx-xxx-xxx-x ~]$ php --ri swoole

swoole

swoole support => enabled
Version => 2.2.0
Author => tianfeng.han[email: mikan.tenny@gmail.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
sockets => enabled
Linux Native AIO => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ? 
```
[ec2-user@ip-xxx-xxx-xxx-x ~]$ uname -a
Linux ip-xxx-xxx-xxx-xxx 4.9.27-14.31.amzn1.x86_64 #1 SMP Wed May 10 01:58:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
[ec2-user@ip-xxx-xxx-xxx-xxx  ~]$ php -v
PHP 7.1.17 (cli) (built: May 10 2018 17:38:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

```
[ec2-user@ip-xx-xxx-xxx-xxx  ~]$ php -i | grep memory
memory_limit => 128M => 128M
```

6. If you are using ssl, what is your openssl version?
No.

**Comment by vthorsell** [comment]
Is it not more like you create tables with "slots", meaning:
`
$stClients = new swoole_table(1024 * 1024);
$stClients->column('fd', swoole_table::TYPE_INT);
$stClients->column('token', swoole_table::TYPE_STRING, 128);
$stClients->create();
`

This will create a memory table with 1024 * 1024 = 1048576 slots of "token" (128 byte) and "fd" of unknown size, let's just assume 1 byte.  So how much memory are you using for this table alone?

1048576 * 128 bytes = 124MB (roughly) for this table alone just for the "token" part. Your specification for your PHP-CLI environment specifies you have 128MB of RAM for each running instance of this script. This is also why you exhaust your memory.  

Your second table does not fit in memory and your script crashes.

**Comment by bjacog** [comment]
@vthorsell I think you are right, if I understand correctly the size is actually maximum number of rows?

I added sizes for all of the columns. I fixed the size to 102400 because a lot of other samples I found online had that size.

if the size is the number of rows provisioned for, I can finally figure out how much traffic my server can handle.

**Comment by vthorsell** [comment]
Yes, exactly. It is the maximum that can be stored in that specific memory table.
You cannot change the size of a table while the script is running, so a bit of planning is needed here.

And (if you are running your own server), setting memory_limit to -1 (unlimited) in PHP-CLI might also help you a bit, but you should really know a bit more of what you are doing with the tables.

The best approach would be to clean the table out, for your onClose-function just add that you remove the slot taken by that connection. This way you can perhaps use a smaller table of 10000 or so (this is if you think you will have 10000 connections). And also, perhaps add time etc. to your table and run a "ticker" to check expired items and remove them as well, the key is to keep the table so it will fit in the memory you have available.

Your other table "$stMemberships" is also reserving a loooot of memory.

**Comment by bjacog** [comment]
@vthorsell Thanks so much for the input, how did you come about knowing this? Do you have a link to somewhere in the source that I could look at?

I do clean up the rows of all the tables onclose, it will come down to how users use the application, just wanted to know I have enough for an mvp of the feature. All of my tables have the optimizations I mentioned earlier now, the memory usage is signifficantly improved.

**Comment by matyhtf** [comment]
```c
size_t swTable_get_memory_size(swTable *table)
{
    /**
     * table size + conflict size
     */
    size_t row_num = table->size * (1 + table->conflict_proportion);

    /*
     * header + data
     */
    size_t row_memory_size = sizeof(swTableRow) + table->item_size;

    /**
     * row data & header
     */
    size_t memory_size = row_num * row_memory_size;

    /**
     * memory pool for conflict rows
     */
    memory_size += sizeof(swMemoryPool) + sizeof(swFixedPool) + ((row_num - table->size) * sizeof(swFixedPool_slice));

    /**
     * for iterator, Iterate through all the elements
     */
    memory_size += table->size * sizeof(swTableRow *);

    return memory_size;
}
```

* memory size = 1M * (1 + 20%) * (key[128] + sizeof(fd) + sizeof(token))
