### ISSUE TITLE
Enable sockets support, require sockets extension.

### ISSUE THREAD

**Issue by huye** [swoole/swoole-src#1710]
看了 make.sh 里的脚本，启用那几个参数编译的话会报错，到处找了没找到如何处理这里的编译错误，请官方出一个文档说明一下啊，求助了

**Comment by matyhtf** [comment]
使用最新版本 4.0.0-rc1 已去掉了此项检测。

**Comment by huye** [comment]
好吧，看来先不用这些功能，反正现在也用不到
