### ISSUE TITLE
Laravel project with "Unexpected token ." error

### ISSUE THREAD

**Issue by george-kar** [swoole/swoole-src#1712]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

php artisan swoole:http start

2. What did you expect to see?

the login screen

3. What did you see instead?

a broken login screen and an error on the console complaining about a javascript file "Uncaught SyntaxError: Unexpected token .". When I run as php artisan serve it works perfectly.

4. What version of Swoole are you using (`php --ri swoole`)?

2.2.0

5. What is your machine environment used (including version of kernel & php & gcc) ? 

MacOS High Sierra 10.13.4 with PHP 7.2.6 running on Laravel project  5.6

6. If you are using ssl, what is your openssl version?

no, no

**Comment by matyhtf** [comment]
`SyntaxError` 
Please check your php file for syntax errors
