### ISSUE TITLE
/usr/local/src/swoole/src/network/Client.c:457: swClient_close: Assertion `fd != 0' failed. 

### ISSUE THREAD

**Issue by jianhuihi** [swoole/swoole-src#1713]
swoole 4.0rc

/usr/local/src/swoole/src/network/Client.c:457: swClient_close: Assertion `fd != 0' failed. 

检查改行代码逻辑是否有问题。

**Comment by twose** [comment]
出现问题的PHP代码可否提供?

**Comment by matyhtf** [comment]
请提供gdb的完整调用栈信息

**Comment by matyhtf** [comment]
fixed,
 https://github.com/swoole/swoole-src/commit/2804785e18dd974372fc1587282be10728ab0eca

**Comment by matyhtf** [comment]
issue#1750
