### ISSUE TITLE
WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by youngkai** [swoole/swoole-src#1721]
stable4.0 异步任务出现此警告
**WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11**

        //开始投放任务
        $this->serv->on('Task', function (\Swoole\Server $serv, $task_id, $from_id, $data) {
            //处理数据
            $postData = json_decode($data, true);
            $version_id = $postData['version_id'];
            $last_version = $postData['last_version'];
            /**
             * @var 
             */
            $WechatMiniProgram = D('WechatMiniProgram', 'Service');
            if($version_id && $last_version) {
                var_dump($version_id, $last_version);
            }
            $serv->finish('finish');
        });

**Comment by matyhtf** [comment]
fixed https://github.com/swoole/swoole-src/commit/bf2c40f7cd4a2ed0c5000a55cb957002cbfbfb89
