### ISSUE TITLE
http服务post出现PHP Fatal error:  Possible integer overflow in memory allocation (1 * 18446744073709551615 + 1)

### ISSUE THREAD

**Issue by hkui** [swoole/swoole-src#1724]
`<?php
$http = new swoole_http_server("0.0.0.0", 8080);

$http->on('request', function ($request, $response) {
    echo "GET:".print_r($request->get,true).PHP_EOL;
    echo "POST:".print_r($request->post,true).PHP_EOL;
    echo "REQUEST:".print_r($request->request,true).PHP_EOL;
    $response->header("Content-Type", "text/html; charset=utf-8");
    $response->end("<h4>Hello Swoole ".date("Y-m-d H:i:s")."</h4>");
});

$http->start();`

PHP Fatal error:  Possible integer overflow in memory allocation (1 * 18446744073709551615 + 1) in /mnt/hgfs/www/web/thread/process_thread_study/swoole/http.php on line 12

Fatal error: Possible integer overflow in memory allocation (1 * 18446744073709551615 + 1) in /mnt/hgfs/www/web/thread/process_thread_study/swoole/http.php on line 12

php版本 7.1.3
swoole版本2.1.1

**Comment by twose** [comment]
没有复现, 请升级版本到4.0尝试一下

**Comment by hkui** [comment]
@twose 升级到4.0的 确实好了,4.0的稳定吗？

**Comment by twose** [comment]
@hkui 4.0是目前最稳定版本, 没有之一
https://www.oschina.net/news/97074/swoole-4-0-released

**Comment by matyhtf** [comment]
@hkui 确认了码？

**Comment by hkui** [comment]
@matyhtf 确认了，多谢
