### ISSUE TITLE
pecl install swoole 安装不成功？提示 openssl/ssl.h 不存在？

### ISSUE THREAD

**Issue by lakeui** [swoole/swoole-src#1731]
![image](https://user-images.githubusercontent.com/7123922/41650204-15264ffc-74b0-11e8-9c25-16c8ba114106.png)
![image](https://user-images.githubusercontent.com/7123922/41650228-1d6a4f06-74b0-11e8-9a19-00c4186dcc97.png)

环境：
![image](https://user-images.githubusercontent.com/7123922/41650283-3dadca0e-74b0-11e8-82f8-bc89f69d7174.png)

![image](https://user-images.githubusercontent.com/7123922/41650228-1d6a4f06-74b0-11e8-9a19-00c4186dcc97.png)

是什么情况？

**Comment by FuQingYun** [comment]
你的 Linux 没有安装 openssl 的开发库 openssl-devel，不是 swoole 的问题

**Comment by matyhtf** [comment]
先安装`openssl`相关头文件
