### ISSUE TITLE
websocketserver 无法获取 connections

### ISSUE THREAD

**Issue by bnubobby** [swoole/swoole-src#1736]
swoole版本: 2.2 
php 版本 7.2.6
运行环境： docker Version 17.09.0-ce-win33 
运行过程：
1. 启动 SwooleWebSocketServer
2. 当有websocket client链接上来的时候，向所有websocket client 发送通知
websocket client 已链接
执行函数:  $serv->connections  及 $serv->connection_list
返回结果： null 
预期结果：websocket 的  fd 列表
另外，调用$serv->push(1,$msg) 时，链接上来的第一个客户端能正常收到消息

**Comment by twose** [comment]
@bnubobby 
https://wiki.swoole.com/wiki/page/427.html
https://wiki.swoole.com/wiki/page/312.html

**Comment by bnubobby** [comment]
@twose  感谢回答
情况如下：
直接在容器中执行 apt-get install libpcre3 libpcre3-dev  安装库
但问题依旧
重新构建容器，先安装库，再安装swoole后，问题解决
