### ISSUE TITLE
php compile error when include swoole as static extention

### ISSUE THREAD

**Issue by kb667** [swoole/swoole-src#1739]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

**try build a PECL extension statically into your PHP binary.**

2. What did you expect to see?

**success php compile**

3. What did you see instead?

Error , only when i add `--with-swoole=/root/php/ext/swoole/`
**if i remove it will compile successfuly**
**also i try compile swoole alone, but its fail**

4. What version of Swoole are you using (php --ri swoole)?

**lastest now , updated 5 hours ago , from github
also i try php.net version**

5. What is your machine environment used (including version of kernel & php & gcc) ? 

**centos 6
uname -m = i686
uname -r = 2.6.32-042stab128.2**

**gcc 4.4**

**php 7.2.7
php 7.3 beta2**

6. If you are using ssl, what is your openssl version?

**--- i dont use SSL**
openssl-devel-1.0.1e-57.el6.i686
openssl-1.0.1e-57.el6.i686

**Comment by kb667** [comment]
its solved, when i update **gcc 4.4** to **gcc 4.8**

**Comment by kb667** [comment]
i compile swoole alone successfully
.
but **php+swoole** with **gcc 4.8** failed to compile
----------------------------------------------------------------------------------------------------

`sapi/cli/.libs/php_http_parser.o: In function `php_http_parser_execute':
/root/php/sapi/cli/php_http_parser.c:260: multiple definition of `php_http_parser_execute'
ext/swoole/thirdparty/.libs/php_http_parser.o:/root/php/ext/swoole/thirdparty/php_http_parser.c:327: first defined here
sapi/cli/.libs/php_http_parser.o: In function `php_http_should_keep_alive':
/root/php/sapi/cli/php_http_parser.c:1521: multiple definition of `php_http_should_keep_alive'
ext/swoole/thirdparty/.libs/php_http_parser.o:/root/php/ext/swoole/thirdparty/php_http_parser.c:1574: first defined here
sapi/cli/.libs/php_http_parser.o: In function `php_http_method_str':
/root/php/sapi/cli/php_http_parser.c:1542: multiple definition of `php_http_method_str'
ext/swoole/thirdparty/.libs/php_http_parser.o:/root/php/ext/swoole/thirdparty/php_http_parser.c:1595: first defined here
sapi/cli/.libs/php_http_parser.o: In function `php_http_parser_init':
/root/php/sapi/cli/php_http_parser.c:1548: multiple definition of `php_http_parser_init'
ext/swoole/thirdparty/.libs/php_http_parser.o:/root/php/ext/swoole/thirdparty/php_http_parser.c:1601: first defined here
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::SwapOut()':
/root/php/ext/swoole/src/coroutine/context.cc:59: undefined reference to `jump_fcontext'
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::Context(unsigned int, void (*)(void*), void*)':
/root/php/ext/swoole/src/coroutine/context.cc:22: undefined reference to `make_fcontext'
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::SwapIn()':
/root/php/ext/swoole/src/coroutine/context.cc:53: undefined reference to `jump_fcontext'
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::SwapOut()':
/root/php/ext/swoole/src/coroutine/context.cc:59: undefined reference to `jump_fcontext'
collect2: error: ld returned 1 exit status
make: *** [sapi/cli/php] Error 1
make: *** Waiting for unfinished jobs....
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::SwapOut()':
/root/php/ext/swoole/src/coroutine/context.cc:59: undefined reference to `jump_fcontext'
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::Context(unsigned int, void (*)(void*), void*)':
/root/php/ext/swoole/src/coroutine/context.cc:22: undefined reference to `make_fcontext'
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::SwapIn()':
/root/php/ext/swoole/src/coroutine/context.cc:53: undefined reference to `jump_fcontext'
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::SwapOut()':
/root/php/ext/swoole/src/coroutine/context.cc:59: undefined reference to `jump_fcontext'
collect2: error: ld returned 1 exit status
make: *** [sapi/cgi/php-cgi] Error 1
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::SwapOut()':
/root/php/ext/swoole/src/coroutine/context.cc:59: undefined reference to `jump_fcontext'
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::Context(unsigned int, void (*)(void*), void*)':
/root/php/ext/swoole/src/coroutine/context.cc:22: undefined reference to `make_fcontext'
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::SwapIn()':
/root/php/ext/swoole/src/coroutine/context.cc:53: undefined reference to `jump_fcontext'
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::SwapOut()':
/root/php/ext/swoole/src/coroutine/context.cc:59: undefined reference to `jump_fcontext'
collect2: error: ld returned 1 exit status
make: *** [sapi/fpm/php-fpm] Error 1`

**Comment by kb667** [comment]
sapi/cli/.libs/php_http_parser.o: In function `php_http_parser_execute':
/root/php/sapi/cli/php_http_parser.c:260: multiple definition of `php_http_parser_execute'
ext/swoole/thirdparty/.libs/php_http_parser.o:/root/php/ext/swoole/thirdparty/php_http_parser.c:327: first defined here
sapi/cli/.libs/php_http_parser.o: In function `php_http_should_keep_alive':
/root/php/sapi/cli/php_http_parser.c:1521: multiple definition of `php_http_should_keep_alive'
ext/swoole/thirdparty/.libs/php_http_parser.o:/root/php/ext/swoole/thirdparty/php_http_parser.c:1574: first defined here
sapi/cli/.libs/php_http_parser.o: In function `php_http_method_str':
/root/php/sapi/cli/php_http_parser.c:1542: multiple definition of `php_http_method_str'
ext/swoole/thirdparty/.libs/php_http_parser.o:/root/php/ext/swoole/thirdparty/php_http_parser.c:1595: first defined here
sapi/cli/.libs/php_http_parser.o: In function `php_http_parser_init':
/root/php/sapi/cli/php_http_parser.c:1548: multiple definition of `php_http_parser_init'
ext/swoole/thirdparty/.libs/php_http_parser.o:/root/php/ext/swoole/thirdparty/php_http_parser.c:1601: first defined here
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::SwapOut()':
/root/php/ext/swoole/src/coroutine/context.cc:59: undefined reference to `jump_fcontext'
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::Context(unsigned int, void (*)(void*), void*)':
/root/php/ext/swoole/src/coroutine/context.cc:22: undefined reference to `make_fcontext'
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::SwapIn()':
/root/php/ext/swoole/src/coroutine/context.cc:53: undefined reference to `jump_fcontext'
ext/swoole/src/coroutine/.libs/context.o: In function `swoole::Context::SwapOut()':
/root/php/ext/swoole/src/coroutine/context.cc:59: undefined reference to `jump_fcontext'
collect2: error: ld returned 1 exit status
make: *** [sapi/cli/php] Error 1

**Comment by kb667** [comment]
swoole alone compiled .so file : 

[root@z ~]# service php-fpm restart
Gracefully shutting down php-fpm . done
Starting php-fpm [23-Jun-2018 14:40:31] `NOTICE: PHP message: PHP Warning:  PHP Startup: swoole: Unable to initialize module`
Module compiled with module API=20170718
PHP    compiled with module API=20180606
These options need to match
 in Unknown on line 0
 done

**Comment by twose** [comment]
when swoole ver >= 4.x, need gcc ver >= 4.8
and you'd better run swoole in cli mode instead of fpm
```
Module compiled with module API=20170718
PHP compiled with module API=20180606
```
it shows that you have multi PHP version and you mixed it up

**Comment by kb667** [comment]
thanks dear twose

i installed **gcc**
but after some research i found sould install **gcc-c++**  also
i seems solved
compile php7+swoole was successful

i dont know `how use swoole in cli mode`
**which solution have max performance ?**
help please

**Comment by kb667** [comment]
/bin/sh /root/php/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -IZend/ -I/root/php/Zend/ -DPHP_ATOM_INC -I/root/php/include -I/root/php/main -I/root/php -I/root/php/ext/date/lib -I/usr/include/libxml2 -I/root/php/ext/mbstring/oniguruma -I/root/php/ext/mbstring/libmbfl -I/root/php/ext/mbstring/libmbfl/mbfl -I/root/php/ext/sqlite3/libsqlite -I/root/php/ext/swoole -I/root/php/ext/swoole/include -I/root/php/ext/zip/lib -I/root/php/TSRM -I/root/php/Zend    -Wall -pthread -I/usr/include -g -O2 -fvisibility=hidden -DZEND_SIGNALS   -c /root/php/Zend/zend_execute.c -o Zend/zend_execute.lo 
In file included from **/root/php/Zend/zend.h:29:0**,
                 from **/root/php/Zend/zend_execute.c:28**:
**/root/php/Zend/zend_vm_execute.h**: In function ‘**ZEND_CALL_TRAMPOLINE_SPEC_HANDLER**’:
**/root/php/Zend/zend_types.h:785:16**: _warning_: ‘**args**’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   Z_ARR_P(__z) = __arr;     \
                ^
In file included from **/root/php/Zend/zend_execute.c:3377:0**:
**/root/php/Zend/zend_vm_execute.h:1932:14**: _note_: ‘**args**’ was declared here
  zend_array *args;
              ^
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make: *** [Zend/zend_execute.lo] Error 1

**Comment by kb667** [comment]
i bought a new VPS with CentOS7 only for run swoole , but i only have errors **:(**

**Comment by twose** [comment]
@kb667 it not looks like a swoole bug, is it?
