### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by 117311730** [swoole/swoole-src#1748]
[New LWP 19626]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/php /home/www/qmhb/api/artisan swoole start'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007ff6395ff02b in php_swoole_server_get_cache (event_type=2, server_fd=0, serv=0x31d26e0) at /home/download/swoole-src-2.2.0/php_swoole.h:510
510	    swoole_server_port_property *property = (swoole_server_port_property *) port->ptr;
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 cyrus-sasl-lib-2.1.26-21.el7.x86_64 elfutils-libelf-0.168-8.el7.x86_64 elfutils-libs-0.168-8.el7.x86_64 freetype-2.4.11-15.el7.x86_64 glibc-2.17-196.el7_4.2.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libattr-2.4.46-12.el7.x86_64 libcap-2.22-9.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libcurl-7.29.0-42.el7_4.1.x86_64 libgcc-4.8.5-16.el7_4.2.x86_64 libgcrypt-1.5.3-14.el7.x86_64 libgpg-error-1.12-3.el7.x86_64 libicu-50.1.2-15.el7.x86_64 libidn-1.28-4.el7.x86_64 libjpeg-turbo-1.2.90-5.el7.x86_64 libpng-1.5.13-7.el7_2.x86_64 libselinux-2.5-11.el7.x86_64 libssh2-1.4.3-10.el7_2.1.x86_64 libstdc++-4.8.5-16.el7_4.2.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 libxslt-1.1.28-5.el7.x86_64 nspr-4.13.1-1.0.el7_3.x86_64 nss-3.28.4-15.el7_4.x86_64 nss-softokn-freebl-3.28.3-8.el7_4.x86_64 nss-util-3.28.4-3.el7.x86_64 openldap-2.4.44-5.el7.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 pcre-8.32-17.el7.x86_64 systemd-libs-219-42.el7_4.10.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007ff6395ff02b in php_swoole_server_get_cache (event_type=2, server_fd=0, serv=0x31d26e0) at /home/download/swoole-src-2.2.0/php_swoole.h:510
#1  php_swoole_onClose (serv=0x31d26e0, info=0x7fffe7f58d50) at /home/download/swoole-src-2.2.0/swoole_server.c:1681
#2  0x00007ff639684f7e in swFactoryProcess_end (factory=0x31d2b70, fd=<optimized out>) at /home/download/swoole-src-2.2.0/src/factory/FactoryProcess.c:327
#3  0x00007ff63969bbbf in swWorker_onTask (factory=factory@entry=0x31d2b70, task=task@entry=0x7fffe7f58df0) at /home/download/swoole-src-2.2.0/src/network/Worker.c:378
#4  0x00007ff63969bf31 in swWorker_onPipeReceive (reactor=<optimized out>, event=0x7fffe7f5ae60) at /home/download/swoole-src-2.2.0/src/network/Worker.c:824
#5  0x00007ff639688b31 in swReactorEpoll_wait (reactor=0x36872e0, timeo=<optimized out>) at /home/download/swoole-src-2.2.0/src/reactor/ReactorEpoll.c:255
#6  0x00007ff63969c41e in swWorker_loop (factory=factory@entry=0x31d2b70, worker_id=worker_id@entry=429) at /home/download/swoole-src-2.2.0/src/network/Worker.c:782
#7  0x00007ff63969913c in swManager_spawn_worker (factory=0x31d2b70, worker_id=429) at /home/download/swoole-src-2.2.0/src/network/Manager.c:507
#8  0x00007ff63969980f in swManager_start (factory=factory@entry=0x31d2b70) at /home/download/swoole-src-2.2.0/src/network/Manager.c:146
#9  0x00007ff639685302 in swFactoryProcess_start (factory=0x31d2b70) at /home/download/swoole-src-2.2.0/src/factory/FactoryProcess.c:86
#10 0x00007ff63968d04b in swServer_start (serv=serv@entry=0x31d26e0) at /home/download/swoole-src-2.2.0/src/network/Server.c:759
#11 0x00007ff6396293d8 in zim_swoole_http_server_start (execute_data=0x7ff640e1caa0, return_value=0x7fffe7f5b0c0) at /home/download/swoole-src-2.2.0/swoole_http_server.c:1686
#12 0x000000000093a895 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /home/download/php-7.2.3/Zend/zend_vm_execute.h:907
#13 execute_ex (ex=0x31d26e0) at /home/download/php-7.2.3/Zend/zend_vm_execute.h:59749
#14 0x0000000000886c8b in zend_call_function (fci=0x7ff640e1ca20, fci@entry=0x7fffe7f5b230, fci_cache=<optimized out>, fci_cache@entry=0x7fffe7f5b200) at /home/download/php-7.2.3/Zend/zend_execute_API.c:819
#15 0x000000000078a733 in zif_call_user_func_array (execute_data=0x7ff640e1c940, return_value=0x7ff640e1c930) at /home/download/php-7.2.3/ext/standard/basic_functions.c:4905
#16 0x000000000093aa8a in ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER () at /home/download/php-7.2.3/Zend/zend_vm_execute.h:816
#17 execute_ex (ex=0x31d26e0) at /home/download/php-7.2.3/Zend/zend_vm_execute.h:59746
#18 0x000000000093b903 in zend_execute (op_array=0x7ff640e732a0, op_array@entry=0x7ff6328f6ce0, return_value=return_value@entry=0x7ff640e1c8b0) at /home/download/php-7.2.3/Zend/zend_vm_execute.h:63760
#19 0x00000000008965a4 in zend_execute_scripts (type=type@entry=8, retval=0x7ff640e1c8b0, retval@entry=0x0, file_count=file_count@entry=3) at /home/download/php-7.2.3/Zend/zend.c:1496
#20 0x00000000008363b0 in php_execute_script (primary_file=primary_file@entry=0x7fffe7f5d700) at /home/download/php-7.2.3/main/main.c:2590
#21 0x000000000093dc15 in do_cli (argc=4, argv=0x31611a0) at /home/download/php-7.2.3/sapi/cli/php_cli.c:1011
#22 0x000000000044bc8f in main (argc=4, argv=0x31611a0) at /home/download/php-7.2.3/sapi/cli/php_cli.c:1404
(gdb) f 1
#1  php_swoole_onClose (serv=0x31d26e0, info=0x7fffe7f58d50) at /home/download/swoole-src-2.2.0/swoole_server.c:1681
1681	    zend_fcall_info_cache *cache = php_swoole_server_get_cache(serv, info->from_fd, SW_SERVER_CB_onClose);
(gdb) f 0
#0  0x00007ff6395ff02b in php_swoole_server_get_cache (event_type=2, server_fd=0, serv=0x31d26e0) at /home/download/swoole-src-2.2.0/php_swoole.h:510
510	    swoole_server_port_property *property = (swoole_server_port_property *) port->ptr;

**Comment by twose** [comment]
update your swoole to version 4 and show me your PHP code.

**Comment by 117311730** [comment]
这个问题只有在线上才会出现

**Comment by matyhtf** [comment]
现在 4.0 已解决此问题，这里不会出现 core

**Comment by 117311730** [comment]
每个长连接，创建一个定时器，定时器会读取redis，然后push

**Comment by matyhtf** [comment]
```php
        if (cache == NULL)
        {
            return;
        }
```
这应该是一种极端情况出现的问题，客户端和服务器端同时关闭，然后在并行环境中，发生了碰撞。
