### ISSUE TITLE
v4.0.1 write coroutine test with channel ，but get exception result 

### ISSUE THREAD

**Issue by nengwu765** [swoole/swoole-src#1749]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
ev: php7.1.15 , install swoole v4.0.1 extension

test code:

```php
$chan = new chan();

    go(function () use ($chan) {
        for ($i = 0; $i < 2; $i++) {
            $result = $chan->pop();
            var_dump($result);
        }
        echo 'pop over!'. PHP_EOL;
    });

    go(function () use ($chan){
       $retval = [2,23,2];
       $chan->push($retval);
    });

    go(function () use ($chan){
        $eee = "hello word";
        $chan->push($eee);
    });

    echo 'master end' . PHP_EOL;
    exit;
```

2. What did you expect to see?

the right ouput  (I have run this with in swoole v4.0.0, It is running in right way) :

```
master end
array(3) {
  [0]=>
  int(2)
  [1]=>
  int(23)
  [2]=>
  int(2)
}
string(10) "hello word"
pop over!

```

3. What did you see instead?

```
master end
array(3) {
  [0]=>
  int(2)
  [1]=>
  int(23)
  [2]=>
  int(2)
}
```

4. What version of Swoole are you using (`php --ri swoole`)?

swoole v4.0.1

5. What is your machine environment used (including version of kernel & php & gcc) ? 

kernel : Linux ubuntu 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
sys: ubuntu 16.04 LTS
php: php7.1.15
gcc:5.4.0

6. If you are using ssl, what is your openssl version?

no

**Comment by twose** [comment]
@nengwu765 
because you exit the script:
```php
echo 'master end' . PHP_EOL;
exit;
```
