### ISSUE TITLE
Cannot destroy a server instance

### ISSUE THREAD

**Issue by weierophinney** [swoole/swoole-src#1754]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

We are attempting to provide Swoole integration for [Expressive](https://getexpressive.org), a PHP middleware microframework. As part of that process, we are writing tests to ensure our integrations work as expected.

One such test is [here](https://github.com/zendframework/zend-expressive-swoole/blob/e1ea77074be27fc521e5a400c266a37441397f35/test/Container/SwooleHttpServerFactoryTest.php). It describes a factory that returns a `Swoole\Http\Server` instance, and that the instance is configured correctly.

2. What did you expect to see?

I expected the tests to pass without errors.

3. What did you see instead?

Under Swoole 2.2.0, everything works as expected. However, under Swoole 4.0.1, the second test results in the error "server is running. unable to create swoole_server."

4. What version of Swoole are you using (`php --ri swoole`)?

4.0.1

5. What is your machine environment used (including version of kernel & php & gcc) ? 

Linux 4.15.0-23, PHP versions 7.1.17 and 7.2.5, gcc 7.3.0. We've also witnessed the same problem on Travis-CI using default containers and both PHP versions 7.1 and 7.2 as used in those containers.

6. If you are using ssl, what is your openssl version?

N/A

----

In looking through the Swoole source code, it looks like the check that emits the error is here: 

- https://github.com/swoole/swoole-src/blob/ff78b10bbb72fe5cd74ec52251062d25bf698153/swoole_server.c#L1931-L1935

From what I can tell, even if we `unset($server)`, there is no `__destroy()` method defined on the `Swoole\Http\Server` class, so the `SwooleG` and/or `SwooleG.serv` singleton values are never reset, and cannot be reset.

For the record, I also attempted calling both `$server->stop()` and `$server->shutdown()`; both of these emitted the error "server is not running", indicating `serv->gs->start` is not set.

Interestingly, the same issues also arise if I attempt to create _different_ server instances, bound to _different_ ports: the constructor indicates a server is already running (even if `start()` was never called).

What would be useful is one or more of the following:

- A `__destroy()` method that would nullify the `SwooleG.serv` singleton.
- Having `stop()` and/or `shutdown()` nullify the `SwooleG.serv` singleton.
- Allowing multiple servers on _different ports_ to exist.

**Comment by twose** [comment]
usually, we use the `process` to manage swoole server then run our test, hardly anyone tries to run two swoole servers in one process.
such like this script:
```php
for ($i = 0; $i < 2; $i++) {
    $p = new swoole_process(function () use ($i) {
        $port = 9501 + $i;
        $http = new swoole_http_server('0.0.0.0', $port);
        $http->on('start', function () use ($port) {
            echo "Swoole is running on {$port}...";
        });
        $http->on('request', function (swoole_http_request $request, swoole_http_response $response) {
            $response->header('Content-type', 'text/plain');
            $response->end("Hello swoole!\n");
        });
    }, false, false);
    $p->start();
}
```

---

Or you can see: 
https://github.com/swoole/swoole-src/tree/master/tests/swoole_http_server

---

Or you can use 
```php
function swoole_server->addListener(string $host, int $port, $type = SWOOLE_SOCK_TCP);
```

But It's totally a problem but it has some reasons too, we will fix it soon.

**Comment by matyhtf** [comment]
Destruction is not supported now, and in version 5.0 we will provide a more convenient server class base on Coroutine.
