### ISSUE TITLE
register_shutdown_function，多线程继承问题

### ISSUE THREAD

**Issue by Git-XiaoQin** [swoole/swoole-src#1758]
在父进程注册"register_shutdown_function()"后，创建子进程，当子进程exit退出时，也会触发"register_shutdown_function()"事件

**Comment by twose** [comment]
你这个是多进程问题吧...
如果你是指主进程和worker进程, 在register_shutdown_function里增加判断一下当前在哪个进程就好了.
不知道你要做什么, 进程都有自己的退出事件可以注册.

**Comment by Git-XiaoQin** [comment]
在父进程注册register_shutdown_function，防止父进程exit意外退出导致子进程变成孤儿进程

**Comment by matyhtf** [comment]
子进程是继承父进程内存的，所以这是符合预期的。你需要在 register_shutdown_function 的函数中处理这个情况。
