### ISSUE TITLE
About fd

### ISSUE THREAD

**Issue by zizohassan** [swoole/swoole-src#1759]
when i connect to web socket every time i connect i have unique $request->fd

if there way to set it 

i try to pass id with url in connect 

like this 

```
 new WebSocket("ws://127.0.0.1:9502?id=4370971530347983");
```

then in server 

```
$server->on('open', function($server, $req) {
    $req->fd = $req->get["id"];
    echo "connection open: {$req->fd} {$req->get["id"]} \n";
});
```

but when i check 

```
$server->exist($id)
```

i did not found the id 

any idea how i do this

**Comment by matyhtf** [comment]
FD is the identifier of the TCP connection and cannot be set.
You can save with global array or swoole_table.

```php
$array = [];
$server->on('open', function($server, $req) {
    global $array;
    $array[$req->get["id"]] = $req->fd;
    echo "connection open: {$req->fd} {$req->get["id"]} \n";
});

isset($array[$id]);
```
