### ISSUE TITLE
Coroutine\Http\Client 功能建议

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/swoole-src#1772]
目前正在对类库进行改造，不知道`Coroutine\Http\Client`是否有下列功能，如果没有是否可以支持？

* http auth
* 上下行限速
* 是否允许重定向
* 最大重定向次数

**Comment by twose** [comment]
@Yurunsoft 
可以参考我的lib, 除了限速这些功能和底层是没有任何关系的
https://github.com/swlib/saber
这个类库和所有框架都可以兼容使用

**Comment by Yurunsoft** [comment]
好的，明白了，看来要自己实现重定向

**Comment by Yurunsoft** [comment]
`ssl_cert_file`和`ssl_key_file`如果有密码，目前是否支持设置？

**Comment by twose** [comment]
@Yurunsoft 什么密码?

**Comment by Yurunsoft** [comment]
@twose  在curl里是`CURLOPT_SSLCERTPASSWD`和`CURLOPT_SSLKEYPASSWD`

**Comment by twose** [comment]
没有这个选项，这个在http客户端里的应用场景没有见过，一般都是不再加密的吧。
可以作为enhancement
