### ISSUE TITLE
How to send data to all connected Sockets

### ISSUE THREAD

**Issue by jinoantony** [swoole/swoole-src#1780]
I have created a socket server. But how can I send data to all connected sockets ?

```
<?php

$server = new swoole_websocket_server("0.0.0.0", 9501);

$server->on('open', function (swoole_websocket_server $server, $request) {
    echo "server: handshake success with fd{$request->fd}\n";
});

$server->on('message', function (swoole_websocket_server $server, $frame) {
    echo "receive from {$frame->fd}:{$frame->data},opcode:{$frame->opcode},fin:{$frame->finish}\n";
    $server->push($frame->fd, "This message is from swoole websocket server.");
});

$server->on('close', function ($ser, $fd) {
    echo "client {$fd} closed\n";
});

$server->start(); 
```

**Comment by twose** [comment]
# example
```PHP
foreach($server->connections as $fd)
{
    $server->send($fd, "hello world\n");
}
```

if you meet error:

### pcre.h: No such file or directory

```
fatal error: pcre.h: No such file or directory
```


#### ubuntu/debian：

```
apt-get install libpcre3 libpcre3-dev
```

#### centos/redhat：

```
yum install pcre-devel
```

**Comment by jinoantony** [comment]
@twose Thanks for your help.

```
$server -> send($fd, "hello world\n") 
```
gives me error but 
``` 
$server->push($fd, "hello world\n")
```
 works fine.

**Comment by erlangparasu** [comment]
> # example
> 
> ```
> foreach($server->connections as $fd)
> {
>     $server->send($fd, "hello world\n");
> }
> ```
> 
> if you meet error:
> ### pcre.h: No such file or directory
> 
> ```
> fatal error: pcre.h: No such file or directory
> ```
> 
> #### ubuntu/debian：
> 
> ```
> apt-get install libpcre3 libpcre3-dev
> ```
> 
> #### centos/redhat：
> 
> ```
> yum install pcre-devel
> ```

@twose Thanks!
