### ISSUE TITLE
WAMP on Swoole

### ISSUE THREAD

**Issue by andreybolonin** [swoole/swoole-src#1784]
Any ideas how to implement WAMP https://wamp-proto.org/ on top of swoole?

**Comment by gouchaoer** [comment]
swoole noy support Windows

**Comment by twose** [comment]
I take a quick look at it, you can use `Swoole\Client` or `Co\Socket`?
maybe some difficulties, you can commit RFC here.

**Comment by flddr** [comment]
@andreybolonin have you some progress? Please share :)
