### ISSUE TITLE
WebSocket Server close 协议的问题

### ISSUE THREAD

**Issue by malacca** [swoole/swoole-src#1786]
根据 WebSocket 协议

https://developer.mozilla.org/zh-CN/docs/Web/API/WebSocket

客户端 close 方法

void close(in optional unsigned short code, in optional DOMString reason);

想问下,  swoole WebSocket Server 的 close 回调函数原型

function onClose(swoole_server $server, int $fd, int $reactorId);

那么，针对 WebSocket， 该如何获取 code 和 reason 呢？

**Comment by twose** [comment]
这是浏览器的WebSocket的API而不是协议吧

**Comment by malacca** [comment]
是协议啊，浏览器只是实现了协议而已。 rfc6455 7.1.5，7.1.6 有规定

**Comment by twose** [comment]
`$reactorId`参数，当服务器主动关闭连接时，底层会设置此参数为`-1`，可以通过判断`$reactorId < 0`来分辨关闭是由服务器端还是客户端发起的

不过你要的可能不是这个, 能指出一下具体的应用场景么, 可以写个示例.

**Comment by malacca** [comment]
就是希望 webSocket Server 能够支持协议，举栗子说吧

客户端主动发起的的关闭

```
const socket = new WebSocket('ws://localhost:8080');

socket.addEventListener('open', function (event) {
    socket.close(4002, 'custom reason')
});

``` 

那么服务端就应该是

```
swoole_websocket_server->on('close', function($server, $fd,$reactorId, $code, $reason){

     // $code = 4002;
    // $reason = 'custom reason';
})
```

因为 webSocket 关闭不只是客户端断开连接那么简单，还有可能是客户端发送了

0x8 - len - code - reason 协议数据请求关闭的，这时候服务端是可以获取 code 和 reason 的

同理的，反过来，当服务端主动关闭客户端连接，可以直接关闭 TCP连接，但也可以按照协议进行关闭，
发送 0x8 - len - code - reason 给客户端，进而关闭连接

我用下面代码测试了下，能关闭连接，但客户端没收到  code 和 reason

服务端伪代码

```
swoole_websocket_server->on('open', function($server, $request) {
    $server->send(0x8 . chr(5) . pack('n', 4001) . 'foo')
})

```

客户端代码

```
const socket = new WebSocket('ws://localhost:8080');

socket.addEventListener('close', function (ev) {
    // 没获取到
     console.log(ev.code, ev.reason)
});
````

所以这个问题其实有两个

一、服务端监听 客户端关闭事件，普通TCP连接没什么问题，但对于 webSocket， 回调参数其实是有缺失的，无法按照协议获取相关数据

二、服务端主动关闭连接，当然是可以用 server->close()，这个就肯定无法告知客户端关闭code 和 reason了，但我想不明白的是，为啥直接 send 符合 websocket 协议中关闭的数据，可以正常关闭连接，客户端却无法正确获取，估计是没有正确 send

**Comment by malacca** [comment]
另外，补充一个  关闭 code 和 reason 的文档

https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent#Status_codes

按照 swoole 现在的情况，  code 恒为 1006

**Comment by twose** [comment]
好的, 关于开发者自由度的问题, 稍后我确认一下

**Comment by malacca** [comment]
这个还真不是什么自由度问题，就是没有完全遵从协议处理 webSocket frame 数据，确切说，是"关闭帧"没有按照协议做处理。浏览器作为客户端是完全按照协议的，就连人家微信小程序的客户端都是遵从协议的 https://developers.weixin.qq.com/miniprogram/dev/api/network-socket.html#wxclosesocket

作为服务端，无法解包数据，说不过去吧，不能说这是一个Bug， 但至少也得是一个 Todo   :)

**Comment by malacca** [comment]
对于上面提到的，服务端无法正确发送关闭帧的问题，是我搞错了。重新测试发现该功能不存在问题，这里贴一下代码，希望能帮到有需要的人

```
function makeCloseFrame($code, $reason)
{
    $code = (int) $code;
    if ($code < 4000 || $code > 4999 ) {
        return chr(136) . chr(0);
    }
    return chr(136) . chr(2 + strlen($reason)) . pack('n', $code) . $reason;
}


$server = new swoole_websocket_server('0.0.0.0', 8080);
$server->on('open', function(swoole_websocket_server $server, swoole_http_request $request) {
    $server->send($request->fd, makeCloseFrame(4001, 'custom reason'));
    $server->close($request->fd);
});

```

客户端 

```
const socket = new WebSocket('ws://localhost:8080');

socket.addEventListener('close', function (ev) {
    // 可正常获取 code, reason
     console.log(ev.code, ev.reason)
});
```

不过对于客户端主动关闭，发送的 code  和 reason，只能 swoole 底层来解决了。

**Comment by twose** [comment]
@malacca  感谢反馈, 这个特性支持已经在计划列表中, 已经分配出去了, 很快底层也会支持.

**Comment by malacca** [comment]
1. 这只是处理服务端主动关闭的情况（并且上面我有提到，目前可以通过 server->send() 来兼容）
2. 对于客户端主动关闭, 服务端在 onClose 回调函数中，目前无法获得客户端发送的关闭帧(code, reason)

你提到的这个更新貌似只处理了情况1，请问情况2有处理吗

**Comment by Inokinoki** [comment]
正在实现中，近几天就会加上去 @malacca  感谢你的issue和持续关注
