### ISSUE TITLE
SWOOLE_SOCK_UNIX_STREAM for Websocket Client? (swoole_http_client)

### ISSUE THREAD

**Issue by DrOctavius** [swoole/swoole-src#1787]
Hi, is it possible to connect thorugh SWOOLE_SOCK_UNIX_STREAM to server using swoole_http_client?
with swoole_client it works :), with HTTP don't know how...

**Comment by twose** [comment]
No support now, it may be a todo.

**Comment by DrOctavius** [comment]
Thank you sir!
