### ISSUE TITLE
header setcookie 等获取不到设置的header信息

### ISSUE THREAD

**Issue by cclehui** [swoole/swoole-src#1793]
启动swoole 都是通过php  cli模式启动， 这样的话在通常的代码中用 header函数设置的 header信息， 如何才能拿到呢？  找了好多资料都没找到合适的方法

**Comment by twose** [comment]
@cclehui 
多查文档, 善用搜索
https://wiki.swoole.com/wiki/search/?q=header&type=wiki
https://wiki.swoole.com/wiki/search/?q=setcookie&type=wiki

**Comment by cclehui** [comment]
@twose  我问题的意思不是用swoole怎么设置header , 我知道可以用swoole的方式设置header（这个做法的问题是会修改原有的业务代码）, 我是想问以前的fpm方式编写的php代码中用php原生header() 函数方式设置的头， 在用swoole启动php（用swooke代替fpm的情况下）的时候如何能不改原有的业务代码获取到设置的header？

**Comment by twose** [comment]
@cclehui 有个办法，最新版本解决了协程使用全局ob的问题，可以在回调开始使用ob捕获所有输出，结束时统一输出。
