### ISSUE TITLE
针对使用swoole协程的项目获取代码覆盖率问题

### ISSUE THREAD

**Issue by Lingghh** [swoole/swoole-src#1795]
环境：PHP：5.6.24，xdebug：2.4.0，swoole：2.07

- 在php.ini增加xdebug.so，然后对使用了swoole协程的项目发起请求会被阻塞，无法得到响应。
- 如果不配置xdebug.so，则可以正常得到响应。

请问xdebug是否支持获取使用swoole协程的项目的代码覆盖率数据？如果不支持，可以采用什么方案获取采用了swoole协程的项目的覆盖率数据呢？

**Comment by huangzhhui** [comment]
请使用 PHP7 搭配 swoole 4 进行代码覆盖率测试

**Comment by Lingghh** [comment]
@huangzhhui 感谢解答！不过项目比较稳定，暂时没有升级PHP和swoole打算。如果基于上述环境（PHP：5.6.24，xdebug：2.4.0，swoole：2.07），是否有类似的方案呢？

**Comment by huangzhhui** [comment]
没有

**Comment by Lingghh** [comment]
明白，感谢解答！

**Comment by Lingghh** [comment]
@huangzhhui 请教一下哈，“PHP7 搭配 swoole 4 进行覆盖率测试” 是通过xdebug工具获取的吗？还是要通过其他工具呢？

**Comment by shiguangqi** [comment]
swoole协程不支持xdebug,因为xdebug使用了大量全局变量, 和协程上下文切换冲突 可以参考文档 https://wiki.swoole.com/wiki/page/851.html
