### ISSUE TITLE
How to use channel outside server

### ISSUE THREAD

**Issue by androlets** [swoole/swoole-src#1797]
I try to write a console script which will execute functions in coroutines and use channel to collect data from them. How can i use it outside server (http, udp, websocket etc)? I want that script utilizes all cores for his job.
```
<?php
$chan = new chan(1);

go(function() use ($chan) {
    $chan->push(1);
});

// Fatal error:  Swoole\Coroutine\Channel::pop(): must be called in the coroutine
echo $chan->pop();
```

2. What did you expect to see?
1

3. What did you see instead?
Fatal error:  Swoole\Coroutine\Channel::pop(): must be called in the coroutine

4. What version of Swoole are you using (`php --ri swoole`)?
2.2.0

**Comment by twose** [comment]
it must be called in the coroutine because it would schedule coroutine.
if you want to use it outside, you should use \Swoole\Channel (without coroutine).

**Comment by matyhtf** [comment]
Chan->pop may cause coroutine scheduling, so it must be executed in the coroutine
