### ISSUE TITLE
swoole_table->get does not support the second parameter

### ISSUE THREAD

**Issue by w3yyb** [swoole/swoole-src#1798]
swoole_table->get()  does not support the second parameter
when I run BaseApp::$table->get('runtasknum','runtactualasknum');
then report :

PHP Warning:  Swoole\Table::get() expects exactly 1 parameter, 2 given in /var/www/html/m3u8task/vendor/ping/swoole-task/src/HttpServer.php on line 318

swoole version:2.0.5 or 1.9.10.

**Comment by twose** [comment]
@w3yyb 
Please update your swoole version to the newest.
