### ISSUE TITLE
swoole 2.x lts cygwin make error

### ISSUE THREAD

**Issue by hastonewy** [swoole/swoole-src#1801]
log content:

Hastone@HSMC /cygdrive/z/tt
$ cd swoole-src-2.x-lts/

Hastone@HSMC /cygdrive/z/tt/swoole-src-2.x-lts
$ ll
总用量 1768
drwxr-xr-x+ 1 Hastone None      0 7月   9 20:19 benchmark
-rwxr-xr-x+ 1 Hastone None    308 7月   9 20:19 build.sh
-rwxr-xr-x+ 1 Hastone None    263 7月   9 20:19 clear.sh
-rw-r--r--+ 1 Hastone None   1784 7月   9 20:19 CMakeLists.txt
-rw-r--r--+ 1 Hastone None  17456 7月   9 20:19 config.m4
-rw-r--r--+ 1 Hastone None     62 7月   9 20:19 CREDITS
drwxr-xr-x+ 1 Hastone None      0 7月   9 20:19 examples
drwxr-xr-x+ 1 Hastone None      0 7月   9 20:19 include
-rw-r--r--+ 1 Hastone None  11362 7月   9 20:19 LICENSE
-rwxr-xr-x+ 1 Hastone None    154 7月   9 20:19 make.sh
-rw-r--r--+ 1 Hastone None  57397 7月   9 20:19 package.xml
-rw-r--r--+ 1 Hastone None  22583 7月   9 20:19 php_swoole.h
-rw-r--r--+ 1 Hastone None  18050 7月   9 20:19 php7_wrapper.h
-rw-r--r--+ 1 Hastone None  17718 7月   9 20:19 README.md
drwxr-xr-x+ 1 Hastone None      0 7月   9 20:19 src
-rw-r--r--+ 1 Hastone None  55473 7月   9 20:19 swoole.c
-rw-r--r--+ 1 Hastone None  33590 7月   9 20:19 swoole_async.c
-rw-r--r--+ 1 Hastone None  12562 7月   9 20:19 swoole_atomic.c
-rw-r--r--+ 1 Hastone None  11230 7月   9 20:19 swoole_buffer.c
-rw-r--r--+ 1 Hastone None   4939 7月   9 20:19 swoole_channel.c
-rw-r--r--+ 1 Hastone None  22865 7月   9 20:19 swoole_channel_coro.c
-rw-r--r--+ 1 Hastone None  77076 7月   9 20:19 swoole_client.c
-rw-r--r--+ 1 Hastone None  38178 7月   9 20:19 swoole_client_coro.c
-rw-r--r--+ 1 Hastone None   9938 7月   9 20:19 swoole_config.h
-rw-r--r--+ 1 Hastone None  22156 7月   9 20:19 swoole_coroutine.c
-rw-r--r--+ 1 Hastone None   5409 7月   9 20:19 swoole_coroutine.h
-rw-r--r--+ 1 Hastone None  41111 7月   9 20:19 swoole_coroutine_util.c
-rw-r--r--+ 1 Hastone None  22630 7月   9 20:19 swoole_event.c
-rw-r--r--+ 1 Hastone None   5497 7月   9 20:19 swoole_http.h
-rw-r--r--+ 1 Hastone None  71066 7月   9 20:19 swoole_http_client.c
-rw-r--r--+ 1 Hastone None   5637 7月   9 20:19 swoole_http_client.h
-rw-r--r--+ 1 Hastone None  65020 7月   9 20:19 swoole_http_client_coro.c
-rw-r--r--+ 1 Hastone None  83074 7月   9 20:19 swoole_http_server.c
-rw-r--r--+ 1 Hastone None  41513 7月   9 20:19 swoole_http_v2_client.c
-rw-r--r--+ 1 Hastone None   4552 7月   9 20:19 swoole_http_v2_client.h
-rw-r--r--+ 1 Hastone None  32668 7月   9 20:19 swoole_http_v2_client_coro.c
-rw-r--r--+ 1 Hastone None  24440 7月   9 20:19 swoole_http_v2_server.c
-rw-r--r--+ 1 Hastone None   7785 7月   9 20:19 swoole_lock.c
-rw-r--r--+ 1 Hastone None  10175 7月   9 20:19 swoole_memory_pool.c
-rw-r--r--+ 1 Hastone None   6256 7月   9 20:19 swoole_mmap.c
-rw-r--r--+ 1 Hastone None   5728 7月   9 20:19 swoole_msgqueue.c
-rw-r--r--+ 1 Hastone None  85711 7月   9 20:19 swoole_mysql.c
-rw-r--r--+ 1 Hastone None  17447 7月   9 20:19 swoole_mysql.h
-rw-r--r--+ 1 Hastone None  59313 7月   9 20:19 swoole_mysql_coro.c
-rw-r--r--+ 1 Hastone None  33842 7月   9 20:19 swoole_postgresql_coro.c
-rw-r--r--+ 1 Hastone None   1427 7月   9 20:19 swoole_postgresql_coro.h
-rw-r--r--+ 1 Hastone None  35693 7月   9 20:19 swoole_process.c
-rw-r--r--+ 1 Hastone None  12997 7月   9 20:19 swoole_process_pool.c
-rw-r--r--+ 1 Hastone None  33162 7月   9 20:19 swoole_redis.c
-rw-r--r--+ 1 Hastone None 148115 7月   9 20:19 swoole_redis_coro.c
-rw-r--r--+ 1 Hastone None  17738 7月   9 20:19 swoole_redis_server.c
-rw-r--r--+ 1 Hastone None   4906 7月   9 20:19 swoole_ringqueue.c
-rw-r--r--+ 1 Hastone None  50830 7月   9 20:19 swoole_serialize.c
-rw-r--r--+ 1 Hastone None   4375 7月   9 20:19 swoole_serialize.h
-rw-r--r--+ 1 Hastone None 114287 7月   9 20:19 swoole_server.c
-rw-r--r--+ 1 Hastone None  22417 7月   9 20:19 swoole_server_port.c
-rw-r--r--+ 1 Hastone None  36194 7月   9 20:19 swoole_socket_coro.c
-rw-r--r--+ 1 Hastone None  28387 7月   9 20:19 swoole_table.c
-rw-r--r--+ 1 Hastone None  12844 7月   9 20:19 swoole_timer.c
-rw-r--r--+ 1 Hastone None  14562 7月   9 20:19 swoole_trace.c
-rw-r--r--+ 1 Hastone None  20783 7月   9 20:19 swoole_websocket_server.c
drwxr-xr-x+ 1 Hastone None      0 7月   9 20:19 tests
drwxr-xr-x+ 1 Hastone None      0 7月   9 20:19 thirdparty
drwxr-xr-x+ 1 Hastone None      0 7月   9 20:19 tools
drwxr-xr-x+ 1 Hastone None      0 7月   9 20:19 travis
-rw-r--r--+ 1 Hastone None   5030 7月   9 20:19 Version2.md

Hastone@HSMC /cygdrive/z/tt/swoole-src-2.x-lts
$ phpize
Configuring for:
PHP Api Version:         20160303
Zend Module Api No:      20160303
Zend Extension Api No:   320160303

Hastone@HSMC /cygdrive/z/tt/swoole-src-2.x-lts
$ ./configure
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-cygwin
checking host system type... x86_64-unknown-cygwin
checking target system type... x86_64-unknown-cygwin
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib/php/20160303
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable swoole debug... no
checking Whether to enable trace log... no
checking enable sockets support... no
checking enable async_redis support... no
checking enable coroutine postgresql support... no
checking enable openssl support... no
checking enable http2.0 support... no
checking enable thread support... no
checking enable hugepage support... no
checking swoole support... yes, shared
checking swoole static compile support... no
checking swoole support... yes, shared
checking for libpq support... no
checking for OpenSSL support... no
checking for jemalloc support... no
checking enable mysqlnd support... no
checking whether to enable coroutine... yes
checking whether to enable asan... no
checking enable picohttpparser support... no
checking swoole support... yes, shared
checking enable timewheel support... no
checking if compiling with clang... no
checking for cpu affinity... no
checking for socket REUSEPORT... no
checking for futex... no
checking for linux aio... no
checking for clock_gettime in -lrt... yes
checking for accept4 in -lc... yes
checking for signalfd in -lc... no
checking for timerfd_create in -lc... no
checking for eventfd in -lc... no
checking for epoll_create in -lc... no
checking for poll in -lc... yes
checking for sendfile in -lc... no
checking for kqueue in -lc... no
checking for backtrace in -lc... no
checking for daemon in -lc... yes
checking for mkostemp in -lc... yes
checking for inotify_init in -lc... no
checking for malloc_trim in -lc... yes
checking for inotify_init1 in -lc... no
checking for gethostbyname2_r in -lc... no
checking for ptrace in -lc... no
checking for pthread_rwlock_init in -lpthread... yes
checking for pthread_spin_lock in -lpthread... yes
checking for pthread_mutex_timedlock in -lpthread... yes
checking for pthread_barrier_init in -lpthread... yes
checking for pcre_compile in -lpcre... no
checking for redisConnect in -lhiredis... no
checking for PQconnectdb in -lpq... no
checking for nghttp2_hd_inflate_new in -lnghttp2... no
checking for gzgets in -lz... no
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by cc... /usr/x86_64-pc-cygwin/bin/ld.exe
checking if the linker (/usr/x86_64-pc-cygwin/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 8192
checking how to convert x86_64-unknown-cygwin file names to x86_64-unknown-cygwin format... func_convert_file_noop
checking how to convert x86_64-unknown-cygwin file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-pc-cygwin/bin/ld.exe option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -DDLL_EXPORT -DPIC
checking if cc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands

Hastone@HSMC /cygdrive/z/tt/swoole-src-2.x-lts
$ make && make install
/bin/sh /cygdrive/z/tt/swoole-src-2.x-lts/libtool --mode=compile cc  -I. -I/cygdrive/z/tt/swoole-src-2.x-lts -DPHP_ATOM_INC -I/cygdrive/z/tt/swoole-src-2.x-lts/include -I/cygdrive/z/tt/swoole-src-2.x-lts/main -I/cygdrive/z/tt/swoole-src-2.x-lts -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/cygdrive/z/tt/swoole-src-2.x-lts -I/cygdrive/z/tt/swoole-src-2.x-lts/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /cygdrive/z/tt/swoole-src-2.x-lts/swoole.c -o swoole.lo
libtool: compile:  cc -I. -I/cygdrive/z/tt/swoole-src-2.x-lts -DPHP_ATOM_INC -I/cygdrive/z/tt/swoole-src-2.x-lts/include -I/cygdrive/z/tt/swoole-src-2.x-lts/main -I/cygdrive/z/tt/swoole-src-2.x-lts -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/cygdrive/z/tt/swoole-src-2.x-lts -I/cygdrive/z/tt/swoole-src-2.x-lts/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /cygdrive/z/tt/swoole-src-2.x-lts/swoole.c  -DDLL_EXPORT -DPIC -o .libs/swoole.o
In file included from /usr/include/php/ext/spl/spl_iterators.h:27:0,
                 from /cygdrive/z/tt/swoole-src-2.x-lts/swoole.c:26:
/usr/include/php/ext/pcre/php_pcre.h:29:10: 致命错误：pcre.h：No such file or directory
 #include "pcre.h"
          ^~~~~~~~
编译中断。
make: *** [Makefile:193：swoole.lo] 错误 1

Hastone@HSMC /cygdrive/z/tt/swoole-src-2.x-lts
$

**Comment by hastonewy** [comment]
the same error in swoole 4/master

**Comment by twose** [comment]
if you meet error:

### pcre.h: No such file or directory

```
fatal error: pcre.h: No such file or directory
```

because that you don't have PCRE extension


#### ubuntu/debian：

```
apt-get install libpcre3 libpcre3-dev
```

#### centos/redhat：

```
yum install pcre-devel
```

or go to http://www.pcre.org/
