### ISSUE TITLE
通过协程和channel实现对kafka消息生产消费时，会coredump、产生空消息，或者无消息

### ISSUE THREAD

**Issue by cesardeng** [swoole/swoole-src#1804]
韩大好，出现这么一个古怪的问题，不知道是不是我使用不对？环境：
环境：
swoole:4.01;
php：7.2.4
kafka:0.11.4

问题：
1、如果生产者的协程后面不跟swoole_event::wait()，则channel不会有消息；
2、如果生产者协程后面增加swoole_event::wait()，则消费者channel会收到消息，但进程不时会coredump，并且channel会有空消息产生；

分析：
没有用pool，直接单进程，采用官方源码来做的测试。几乎可以确定是和kafka消费有冲突。
相同代码拿出来单独执行正常，但是只要是放到kafka的消费处理就不行。
（项目也有用server来处理kafka的生产，是正常的）

构造函数里面，初始化channel
$send_chan = new Coroutine\Channel(1024);

Coroutine::create(function () use ($send_chan) {
	while (1) {
		$data = $send_chan->pop();
		//var_dump($data);
		echo "pop: {$data['index']}={$data['rand']}\n";
	}
});

在run里面
try {
	$send_chan = $this->send_chan ;
	while (true) {
		$message = $this->kafka->pull(); // 做了封装，这是kafka的consume返回

		// 放kafka的后续处理逻辑里面就会有这样问题
		Coroutine::create(function () use ($send_chan) {
			for ($i = 0; $i < 10; $i++) {
				//Coroutine::sleep(1.0);
				$send_chan->push(['rand' => rand(1000, 9999), 'index' => $i]);
				echo "push: $i\n";
			}
		});
	}
} catch (\Exception $e) {
	$this->log->warn('Exception message: ' .$e->getMessage(), __FILE__, __LINE__);
}

**Comment by twose** [comment]
能不能贴一下完整的复现代码, 减少沟通成本, 用markdown语法把代码包起来

**Comment by cesardeng** [comment]
把kafka和channel单独拿出来做测试，依然发现这样问题。还麻烦@twose大侠看看。
```php
$setting = require __DIR__ . '/setting.php';
$conf = new RdKafka\Conf();
$conf->set('sasl.mechanisms', 'PLAIN');
$conf->set('api.version.request', 'true');
$conf->set('sasl.username', $setting['sasl_plain_username']);
$conf->set('sasl.password', $setting['sasl_plain_password']);
$conf->set('security.protocol', 'SASL_SSL');
$conf->set('ssl.ca.location', __DIR__ . '/ca-cert');
$conf->set('group.id', $setting['consumer_id']);
$conf->set('metadata.broker.list', $setting['bootstrap_servers']);

$topicConf = new RdKafka\TopicConf();
$topicConf->set('auto.offset.reset', 'smallest');

$conf->setDefaultTopicConf($topicConf);

$consumer = new RdKafka\KafkaConsumer($conf);
$consumer->subscribe([$setting['topic_name']]);

use Swoole\Coroutine as co;
$chan = new co\Channel(1);

co::create(function () use ($chan) {
    while(1) {
        $data = $chan->pop();
	echo 'pop msg: '.$data."\n";
    }
});

while (true) {
    $message = $consumer->consume(120 * 1000);
    switch ($message->err) {
        case RD_KAFKA_RESP_ERR_NO_ERROR:            
            $msg = $message->payload;
            co::create(function () use ($chan,$msg) {
               echo 'push msg: '.$msg."\n";
               $chan->push($msg);
            });
            //swoole_event::wait(); 如果消费队列有数据，有这句会push成功，pop正常。但是后续新消息不会push

            break;
        case RD_KAFKA_RESP_ERR__PARTITION_EOF:
            echo "No more messages; will wait for more\n";
            break;
        case RD_KAFKA_RESP_ERR__TIMED_OUT:
            echo "Timed out\n";
            break;
        default:
            echo  rd_kafka_err2str(rd_kafka_errno2err($message->err));
            throw new \Exception($message->errstr(), $message->err);
            break;
    }
}

**Comment by twose** [comment]
这个代码是放在哪的? 为什么不把整个代码包在一个主协程(co)里? co::create是立即返回的, 底下那个while循环是不是有问题.

**Comment by cesardeng** [comment]
之前思路的是：收到kafka消息，就push给channel。希望尽可能快的接收kafka消息。
你说的思路：让kafka消息的接收和push都在co里面完成。我试试。

**Comment by cesardeng** [comment]
按照大侠说的思路，测试的demo可以正常跑起来。我业务的消息处理逻辑比较多，内存表、rpc。。。按照大侠思路，所有处理也只能放消费协程pop回调去处理了。改造有点费劲。。我试试。。。。谢谢大侠

**Comment by cesardeng** [comment]
性能不好，相当于接收还是单进程。感觉还是因为co监听的事件和kafka的监听事件重了，所以只能把两个合在一个逻辑处理。我再找找原因。

**Comment by cesardeng** [comment]
我把kafka消息拉取和处理分开处理，中间用thrift通信。sever采用co/channel，当没有消息时候正常，开始处理消息后，channel会pop空信息（没有数据，但是触发了pop的调用），循环30次后，worker就coredump了，堆栈信息：
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `php server_sender.php: worke'.
Program terminated with signal 11, Segmentation fault.
#0  zim_swoole_channel_coro_pop (execute_data=0x7f01b9241820, return_value=0x7f01b9241350) at /root/swoole-src-4.0.2/swoole_channel_coro.cc:489
489	    zval zdata = chan->data_queue->front();
Missing separate debuginfos, use: debuginfo-install php71w-cli-7.1.11-1.w7.x86_64
(gdb) f
#0  zim_swoole_channel_coro_pop (execute_data=0x7f01b9241820, return_value=0x7f01b9241350) at /root/swoole-src-4.0.2/swoole_channel_coro.cc:489
489	    zval zdata = chan->data_queue->front();
(gdb) f 1
#1  0x0000555eff5d8dc8 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER ()
(gdb) f 0
#0  zim_swoole_channel_coro_pop (execute_data=0x7f01b9241820, return_value=0x7f01b9241350) at /root/swoole-src-4.0.2/swoole_channel_coro.cc:489
489	    zval zdata = chan->data_queue->front();
(gdb) bt
#0  zim_swoole_channel_coro_pop (execute_data=0x7f01b9241820, return_value=0x7f01b9241350) at /root/swoole-src-4.0.2/swoole_channel_coro.cc:489
#1  0x0000555eff5d8dc8 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER ()
#2  0x0000555eff5873cb in execute_ex ()
#3  0x00007f01c9b89a4b in swoole::Context::context_func (arg=0x555f001b23b0) at /root/swoole-src-4.0.2/src/coroutine/context.cc:66
#4  0x00007f01c9bae841 in make_fcontext () at /root/swoole-src-4.0.2/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:64
#5  0x0000000000000000 in ?? ()

**Comment by cesardeng** [comment]
已下载chan分支编译运行，目前未发现异常。非常感谢。期望早日发布到正式版：）

**Comment by twose** [comment]
@cesardeng 已合并到master分支, 即将发布新版.

**Comment by Liudon** [comment]
> 我把kafka消息拉取和处理分开处理，中间用thrift通信。sever采用co/channel，当没有消息时候正常，开始处理消息后，channel会pop空信息（没有数据，但是触发了pop的调用），循环30次后，worker就coredump了，堆栈信息：
> 
> ```
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib64/libthread_db.so.1".
> Core was generated by `php server_sender.php: worke'.
> Program terminated with signal 11, Segmentation fault.
> #0  zim_swoole_channel_coro_pop (execute_data=0x7f01b9241820, return_value=0x7f01b9241350) at /root/swoole-src-4.0.2/swoole_channel_coro.cc:489
> 489	    zval zdata = chan->data_queue->front();
> Missing separate debuginfos, use: debuginfo-install php71w-cli-7.1.11-1.w7.x86_64
> (gdb) f
> #0  zim_swoole_channel_coro_pop (execute_data=0x7f01b9241820, return_value=0x7f01b9241350) at /root/swoole-src-4.0.2/swoole_channel_coro.cc:489
> 489	    zval zdata = chan->data_queue->front();
> (gdb) f 1
> #1  0x0000555eff5d8dc8 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER ()
> (gdb) f 0
> #0  zim_swoole_channel_coro_pop (execute_data=0x7f01b9241820, return_value=0x7f01b9241350) at /root/swoole-src-4.0.2/swoole_channel_coro.cc:489
> 489	    zval zdata = chan->data_queue->front();
> (gdb) bt
> #0  zim_swoole_channel_coro_pop (execute_data=0x7f01b9241820, return_value=0x7f01b9241350) at /root/swoole-src-4.0.2/swoole_channel_coro.cc:489
> #1  0x0000555eff5d8dc8 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER ()
> #2  0x0000555eff5873cb in execute_ex ()
> #3  0x00007f01c9b89a4b in swoole::Context::context_func (arg=0x555f001b23b0) at /root/swoole-src-4.0.2/src/coroutine/context.cc:66
> #4  0x00007f01c9bae841 in make_fcontext () at /root/swoole-src-4.0.2/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:64
> #5  0x0000000000000000 in ?? ()
> ```

分开的实现是有一个进程专门获取kafka消息，然后投递给消费者？
消费者采用协程实现？

**Comment by cesardeng** [comment]
分开。用进程池读取kafka，阻塞等待的。读到以后rpc投递给消费者处理。
