### ISSUE TITLE
onRequest回调中使用Coroutine::sleep引起worker重启

### ISSUE THREAD

**Issue by fengwanqing** [swoole/swoole-src#1805]
系统：macOS 10.13.3
PHP版本：PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Swoole版本：4.0.2（开启异步redis）

 重现步骤
1. 拉取 https://gitee.com/sosotec/swork 上面的代码
2. 新建测试数据库test（utf8），将 demo/app/Data/user.sql 导入数据库
3. 将 app/Controller/TestController.php 文件的mysql函数中只保留 $this->testModel->doQuery('select sleep(1);'); 和 return 'debug';
4. 执行 php demo/bin/swork start 启动服务
5. 多个浏览器窗口访问 http://127.0.0.1:8199/test/mysql ，即可发现后面的请求会导致worker重启，迟迟没有返回响应内容

**Comment by twose** [comment]
@fengwanqing server中使用`co::sleep`和mysql-client调用`select sleep(1)`访问多次都没有复现, 能提供一下单文件的复现脚本吗?

**Comment by twose** [comment]
Fixed in 28f1e3f

**Comment by twose** [comment]
@fengwanqing 麻烦拉master代码再试一下, 看看是否已正常
