### ISSUE TITLE
Add support for TLS_CHACHA20_POLY1305_SHA256 and TLS 1.3 Draft 28

### ISSUE THREAD

**Issue by josenobile** [swoole/swoole-src#1806]
Hello, 

Can you please add support for TLS_CHACHA20_POLY1305_SHA256 with [TLS 1.3 Draft 28](https://tools.ietf.org/html/draft-ietf-tls-tls13-28) ? 

TLS since version [1.3 Draft 08](https://tools.ietf.org/html/draft-ietf-tls-tls13-28) defined it. Almost 3 years ago.
OpenSSL since version [1_1_1-pre3](https://github.com/openssl/openssl/commit/7731e619fba2f9ea1e888bf906289be37c52e6ac) support it. 4 months ago.

I know TLS 1.3 still in draft but was already implemented by:
nghttp2 since version [v1.20.0](https://github.com/nghttp2/nghttp2/releases/tag/v1.20.0) support it. Almost 17 months ago.
Google Chrome supports TLS 1.3 Draft 28 since version [68.0.3438.0](https://github.com/chromium/chromium/commit/27ac5b6731e805ec1b31fd36876b9244ba97249f). Almost 2 months ago. and just the ciphers since version [49.0.2623](https://blog.chromium.org/2016/02/chrome-49-beta-css-custom-properties.html) 2.5 years ago.
[Nginx 1.13](http://nginx.org/en/CHANGES) Almost 2 years 3 months ago.
Cloudflare for everyone almost [2 years ago](https://blog.cloudflare.com/introducing-tls-1-3/), enabled by default.

**Comment by twose** [comment]
Swoole has already supported it, you need to upgrade your OpenSSL version, I give you an example here:

### code

```php
<?php

$http = new swoole_http_server('0.0.0.0', 9999, SWOOLE_BASE, SWOOLE_SOCK_TCP | SWOOLE_SSL);

$http->set([
    'log_level' => SWOOLE_LOG_INFO,
    'trace_flags' => 0,
    'ssl_cert_file' => __DIR__ . '/ssl.crt',
    'ssl_key_file' => __DIR__ . '/ssl.key',
    'worker_num' => 1,
    'open_http2_protocol' => true
]);

$http->on('start', function (swoole_http_server $server) {
    var_dump('start on http://127.0.0.1:9999');
});

$http->on('workerStart', function (swoole_http_server $server) {
    var_dump('start');
});

$http->on('request', function (swoole_http_request $request, swoole_http_response $response) {
    $response->end('ok');
});

$http->on('workerStop', function () {
    var_dump('stop');
});

$http->start();
```

### tool

then you can use `./testssl.sh -p https://127.0.0.1:9999/` to test it

the repo: https://github.com/drwetter/testssl.sh

![tls13](https://user-images.githubusercontent.com/25978241/42812498-7223a5e2-89f0-11e8-9cdb-009369f2293e.jpg)

if you see ↑, congratulations.

my OpenSSL version is `OpenSSL 1.1.1-pre8 (beta) 20 Jun 2018`, as you said, openssl version >= `OpenSSL 1.1.1-pre1` can work so.

**Comment by josenobile** [comment]
Hello, excuse me, my mistake, I wasn't using the right openssl version. Please close this.
