### ISSUE TITLE
 error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token

### ISSUE THREAD

**Issue by similarJ** [swoole/swoole-src#1807]
gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC)
centos6.8
php7.1.17
编译安装时出现：
/bin/sh /usr/local/src/swoole-src-4.0.2/libtool --mode=compile cc  -I. -I/usr/local/src/swoole-src-4.0.2 -DPHP_ATOM_INC -I/usr/local/src/swoole-src-4.0.2/include -I/usr/local/src/swoole-src-4.0.2/main -I/usr/local/src/swoole-src-4.0.2 -I/usr/local/php71/include/php -I/usr/local/php71/include/php/main -I/usr/local/php71/include/php/TSRM -I/usr/local/php71/include/php/Zend -I/usr/local/php71/include/php/ext -I/usr/local/php71/include/php/ext/date/lib -I/usr/local/src/swoole-src-4.0.2 -I/usr/local/src/swoole-src-4.0.2/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /usr/local/src/swoole-src-4.0.2/swoole.c -o swoole.lo 
mkdir .libs
 cc -I. -I/usr/local/src/swoole-src-4.0.2 -DPHP_ATOM_INC -I/usr/local/src/swoole-src-4.0.2/include -I/usr/local/src/swoole-src-4.0.2/main -I/usr/local/src/swoole-src-4.0.2 -I/usr/local/php71/include/php -I/usr/local/php71/include/php/main -I/usr/local/php71/include/php/TSRM -I/usr/local/php71/include/php/Zend -I/usr/local/php71/include/php/ext -I/usr/local/php71/include/php/ext/date/lib -I/usr/local/src/swoole-src-4.0.2 -I/usr/local/src/swoole-src-4.0.2/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /usr/local/src/swoole-src-4.0.2/swoole.c  -fPIC -DPIC -o .libs/swoole.o
In file included from /usr/local/src/swoole-src-4.0.2/swoole.c:16:

> /usr/local/src/swoole-src-4.0.2/php_swoole.h:471: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token

make: *** [swoole.lo] Error 1

**Comment by similarJ** [comment]
configure后在config.h中增加
#define HAVE_SOCKETS 1

**Comment by twose** [comment]
应该是缺少socket扩展或者未识别
