### ISSUE TITLE
Swoole\Coroutine\Http\Client::get(): connection#69 is closed.

### ISSUE THREAD

**Issue by chaiyanlin** [swoole/swoole-src#1812]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
创建Swoole\Coroutine\Http\Client发送请求，但没有调用close方法。

2. What did you expect to see?
我希望Swoole\Coroutine\Http\Client能够复用，不要在高并发场景下导致大量端口被占用，TIME_WAIT

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ? 

6. If you are using ssl, what is your openssl version?

**Comment by twose** [comment]
@chaiyanlin 试一下最新的master代码, http-client已经在4.0.2改为底层自动重连了

**Comment by chaiyanlin** [comment]
非常感谢！我去试试。

发自我的 iPhone

在 2018年7月19日，上午8:43，twosee <notifications@github.com<mailto:notifications@github.com>> 写道：


@chaiyanlin<https://github.com/chaiyanlin> 试一下最新的master代码, http-client已经在4.0.2改为底层自动重连了

**Comment by chaiyanlin** [comment]
@twose 请问您说的底层自动重连是指对于同一个`swoole\Coroutine\Http\Client`对象，重复使用的时候如果状态为断开则自动重连吗？

我想咨询一下使用swoole做网关的时候，需要将数据通过`swoole\Coroutine\Http\Client`分发给其他业务服务，在高并发场景下会出现大量短连接占用端口造成TIME_WAIT现象，有什么好方法去解决这个问题吗？内核参数已经做了调整，在代码层有什么需要注意的？比如做一个HTTPClient连接池，复用的形式。谢谢！

**Comment by twose** [comment]
@chaiyanlin 
肯定要自己实现连接池的, 否则肯定会出现大量连接, 你可以参考一下 https://github.com/swlib/saber 这个库, 你想要的东西应该都在里面了, 比如使用`channel`来做协程连接池, 可以控制连接池的最大容量, 等待资源时协程调度几乎无消耗.

**Comment by chaiyanlin** [comment]
谢谢我去试试这个库~

发自我的 iPhone

在 2018年7月19日，上午10:03，twosee <notifications@github.com<mailto:notifications@github.com>> 写道：


@chaiyanlin<https://github.com/chaiyanlin>
肯定要自己实现连接池的, 否则肯定会出现大量连接, 你可以参考一下 https://github.com/swlib/saber 这个库, 你想要的东西应该都在里面了, 比如使用channel来做协程连接池, 可以控制连接池的最大容量, 等待资源时协程调度几乎无消耗.

**Comment by chaiyanlin** [comment]
@twose 试了一下这个库，我现在有点疑惑，HTTP请求在对方WebServer不开启KeepAlive的情况下，只能是TCP短连接， 那做这个连接池有什么意义？因为每次都是断开重连，最终还是会出现大量端口TIME_WAIT。

**Comment by twose** [comment]
@chaiyanlin 既然服务器端不支持keep-alive当然会出现这个问题...这个没什么好疑惑的吧...
