### ISSUE TITLE
怀疑协程中eval()有BUG，附上代码和详细说明

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/swoole-src#1814]
### 问题描述

`imi-demo\vendor\yurunsoft\imi\src\Bean\BeanFactory.php` 中 `BeanFactory`类用到了`eval()`函数实例化匿名类。

然后就有偶发性的必现问题。问题现象就是`eval()`返回的对象类型，和预期不符，一般会成上一次实例化的对象。

遇到过很多次，从php7.0+swoole 2.2到php7.1+swoole 4.0.2问题依然不断。

曾经使用过一些奇葩方法临时解决，但依然治标不治本：

1. 修改实例化出错的类名
2. `$tpl`前加上`PHP_EOL`或特定注释

目前已知可以完美解决的方法是把$tpl写入文件，然后include，但考虑到性能问题和环境问题，不是很好。

希望`swoole`团队等有空能够帮`debug`一下，这`$tpl`没毛病，`eval($tpl)`返回就不对了，我真是无解。。。

### 项目配置

1. `imi-demo\WebSocketDemo\config\config.php` 可能需要修改`redis`连接参数，默认是`127.0.0.1`
2. 主服务和子服务的端口，默认是8083和8084

### 启动方式

`imi-demo/WebSocketDemo/bin/imi server/start`

### 复现步骤

1. `ab -c 100 -n 1000 http://127.0.0.1:8084/`
2. `ab -c 100 -n 1000 http://127.0.0.1:8083/`，执行过程中，就会报错了，如：

```
[error] Imi\Server\WebSocket\Listener\BeforeClose ; Imi\Server\Http\Listener\AfterRequest
```

输出这个错误信息的代码在`BeanFactory`类`27`行

### 项目代码

[imi-demo.zip](https://github.com/swoole/swoole-src/files/2208697/imi-demo.zip)

**Comment by shiguangqi** [comment]
运行了一下 include 的方式也有问题 
Fatal error: Allowed memory size of 134217728 bytes exhausted at /xxx/xxx/Zend/zend_arena.h:69 (tried to allocate 65568 bytes) in /tmp/dearP0 on line 1
是不是代码组织的有问题呢？另外最好不要用eval这种方式 
`If eval() is the answer, you're almost certainly asking the wrong question. -- Rasmus Lerdorf, BDFL of PHP`

**Comment by Yurunsoft** [comment]
@shiguangqi 谢谢，我再检查一下代码。但是有个问题，为什么php控制台没有输出内存不足的信息呢？
