### ISSUE TITLE
Documentation for Swoole\Coroutine\Http2\Request / swoole_http2_request

### ISSUE THREAD

**Issue by josenobile** [swoole/swoole-src#1816]
Hello, 

Where Can I found the documentation for Swoole\Coroutine\Http2\Request / swoole_http2_request class?

I want to send a http2 request with files vía POST, I think such class have the answer I'm looking for.

**Comment by twose** [comment]
@josenobile 
http2 request with files in coroutine has not implemented, it will release in the next version.

**Comment by josenobile** [comment]
And without?

**Comment by josenobile** [comment]
Or referring to my question about the documentation?

**Comment by twose** [comment]
@josenobile 
async HTTP client has not request object and document is here: https://www.swoole.co.uk/docs/modules/swoole-async-http2-client
English document of the coroutine is on the way...

**Comment by twose** [comment]
discuss in #1920
