### ISSUE TITLE
Please enable Brotli in addition to gzip

### ISSUE THREAD

**Issue by josenobile** [swoole/swoole-src#1817]
Hello, 
Please, enable [brotli](https://github.com/google/brotli). For HTTP client/server.

**Comment by twose** [comment]
@josenobile Hello:
Is it a niche demand? Maybe you can contribute one.

**Comment by josenobile** [comment]
I would like to contribute, however I'm not a high quality programmer in C/C++ as I do in PHP/JS(node.js).
