### ISSUE TITLE
swoole.h: No such file or directory

### ISSUE THREAD

**Issue by epstar** [swoole/swoole-src#182]
[root@host ~]# pecl install swoole
downloading swoole-1.7.9.tgz ...
Starting to download swoole-1.7.9.tgz (433,120 bytes)
........................................................................................done: 433,120 bytes
138 source files, building
running: phpize
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212
building in /var/tmp/pear-build-rootmUrTJz/swoole-1.7.9
running: /var/tmp/swoole/configure
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... gawk
checking whether to enable swoole debug... no
checking enable sockets support... no
checking enable ringbuffer shared memory pool support... no
checking enable async_mysql support... no
checking enable openssl support... no
checking swoole support... yes, shared
checking swoole support... yes, shared
checking if compiling with clang... no
checking for cpu affinity... yes
checking for ext/mysqli support... no
checking for ext/mysqlnd support... no
checking for accept4 in -lc... yes
checking for signalfd in -lc... yes
checking for timerfd_create in -lc... yes
checking for eventfd in -lc... yes
checking for epoll_create in -lc... yes
checking for sendfile in -lc... yes
checking for kqueue in -lc... no
checking for daemon in -lc... yes
checking for mkostemp in -lc... yes
checking for pthread_rwlock_init in -lpthread... yes
checking for pthread_spin_lock in -lpthread... yes
checking for pthread_mutex_timedlock in -lpthread... yes
checking for SSL_library_init in -lssl... yes
checking for clock_gettime in -lrt... yes
checking for aio_read in -lrt... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/sh /var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/libtool --mode=compile cc  -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /var/tmp/swoole/swoole.c -o swoole.lo
libtool: compile:  cc -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /var/tmp/swoole/swoole.c  -fPIC -DPIC -o .libs/swoole.o
/bin/sh /var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/libtool --mode=compile cc  -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /var/tmp/swoole/swoole_server.c -o swoole_server.lo
libtool: compile:  cc -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /var/tmp/swoole/swoole_server.c  -fPIC -DPIC -o .libs/swoole_server.o
/bin/sh /var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/libtool --mode=compile cc  -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /var/tmp/swoole/swoole_lock.c -o swoole_lock.lo
libtool: compile:  cc -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /var/tmp/swoole/swoole_lock.c  -fPIC -DPIC -o .libs/swoole_lock.o
/bin/sh /var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/libtool --mode=compile cc  -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /var/tmp/swoole/swoole_client.c -o swoole_client.lo
libtool: compile:  cc -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /var/tmp/swoole/swoole_client.c  -fPIC -DPIC -o .libs/swoole_client.o
/bin/sh /var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/libtool --mode=compile cc  -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /var/tmp/swoole/swoole_async.c -o swoole_async.lo
libtool: compile:  cc -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /var/tmp/swoole/swoole_async.c  -fPIC -DPIC -o .libs/swoole_async.o
/bin/sh /var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/libtool --mode=compile cc  -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /var/tmp/swoole/swoole_process.c -o swoole_process.lo
libtool: compile:  cc -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /var/tmp/swoole/swoole_process.c  -fPIC -DPIC -o .libs/swoole_process.o
/bin/sh /var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/libtool --mode=compile cc  -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /var/tmp/swoole/swoole_buffer.c -o swoole_buffer.lo
libtool: compile:  cc -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /var/tmp/swoole/swoole_buffer.c  -fPIC -DPIC -o .libs/swoole_buffer.o
/bin/sh /var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/libtool --mode=compile cc  -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /var/tmp/swoole/swoole_table.c -o swoole_table.lo
libtool: compile:  cc -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /var/tmp/swoole/swoole_table.c  -fPIC -DPIC -o .libs/swoole_table.o
/bin/sh /var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/libtool --mode=compile cc  -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /var/tmp/swoole/swoole_http.c -o swoole_http.lo
libtool: compile:  cc -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /var/tmp/swoole/swoole_http.c  -fPIC -DPIC -o .libs/swoole_http.o
/bin/sh /var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/libtool --mode=compile cc  -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /var/tmp/swoole/src/core/Base.c -o src/core/Base.lo
libtool: compile:  cc -I. -I/var/tmp/swoole -DPHP_ATOM_INC -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/include -I/var/tmp/pear-build-rootmUrTJz/swoole-1.7.9/main -I/var/tmp/swoole -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /var/tmp/swoole/src/core/Base.c  -fPIC -DPIC -o src/core/.libs/Base.o
/var/tmp/swoole/src/core/Base.c:17:20: fatal error: swoole.h: No such file or directory
 #include "swoole.h"
                    ^
compilation terminated.
make: *** [src/core/Base.lo] 错误 1
ERROR: `make' failed
[root@host ~]#

**Comment by matyhtf** [comment]
This is a bug, fixed in 1.7.10.

You can do:
```
pecl download swoole
tar xvf swoole-1.7.9.tgz
cd swoole-1.7.9
phpize
./configure
make && make install
```
