### ISSUE TITLE
无法加载swoole.so

### ISSUE THREAD

**Issue by kawais** [swoole/swoole-src#1820]
输入php -v显示
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/local/lib/php/extensions/debug-non-zts-20170718/swoole.so (Error relocating /usr/local/lib/php/extensions/debug-non-zts-20170718/swoole.so: __asan_stack_free_7: symbol not found), /usr/local/lib/php/extensions/debug-non-zts-20170718/swoole.so.so (Error loading shared library /usr/local/lib/php/extensions/debug-non-zts-20170718/swoole.so.so: No such file or directory)) in Unknown on line 0

php版本7.2.7
swoole版本4.0.1
操作系统docker alpine 3.7

**Comment by twose** [comment]
`swoole.so.so`显然后缀名不对, `php -i | grep ini` 找到你的配置文件然后自行检查配置.

**Comment by matyhtf** [comment]
去掉 `--enable-asan` 编译参数
