### ISSUE TITLE
gzip compression not working for http/2

### ISSUE THREAD

**Issue by josenobile** [swoole/swoole-src#1823]
Hello, 
When using http/2 and is used $response->gzip(9); swoole add content-encoding: gzip header but the body is uncompressed. With http/1.1 using http:// or https:// it works as expected. Can you confirm in your end this bug?

**Comment by twose** [comment]
@josenobile 
HTTP2 support has not complete, please use Nginx to proxy swoole_http_server.
swoole_http_server is just an application service element, you'd better not use it to be professional HTTP server at the top.

**Comment by josenobile** [comment]
Thank you for your advice. But, can you confirm this is a bug? And will be fixed?

**Comment by josenobile** [comment]
Is not an improvement. Because it adds the content-encoding header without compress, this behavior generates an error in browser unable to render the page.

Would be an improvement if the gzip method does not exist for HTTP/2 request, but it does.
