### ISSUE TITLE
Does swoole server store somewhere in memory traffic consumed for/by the connections?

### ISSUE THREAD

**Issue by DrOctavius** [swoole/swoole-src#1827]
Hi
Does swoole server store somewhere in memory traffic consumed for/by the connections?

**Comment by twose** [comment]
@DrOctavius  This question is too broad and vague, I can hardly understand it.

**Comment by DrOctavius** [comment]
@twose Sorry :) i'll try to formulate it more clearly!

Does swoole server (web socket server) has statistics about TX/RX in bytes for each connection?
It would be nice for me to know in TOTAL how much a connection has transmitted/received...

**Comment by twose** [comment]
@DrOctavius 
Do you mean network traffic statistics? maybe you should record it by yourself
and the connection is iterable:
# example
```PHP
foreach($server->connections as $fd)
{
    $server->send($fd, "hello world\n");
}
```

**Comment by DrOctavius** [comment]
@twose 
well i'm doing it already :) as you said...but though there was smth already implemented and i'm just consuming processing time for useless function :)..
Well, thank you, i did the right thing then! :)
