### ISSUE TITLE
在swoole_server的回调中对异常的处理忽略了通过set_exception_handler设置的异常处理方法

### ISSUE THREAD

**Issue by blankyao** [swoole/swoole-src#183]
https://github.com/swoole/swoole-src/blob/master/swoole_server.c#L337

在这里直接调用了zend_exception_error，通过set_exception_handler设置的没被执行

**Comment by matyhtf** [comment]
请在回调函数中进行try-catch，swoole在运行以后会接管系统控制权，回调函数相当与是最终的PHP出口和入口。异常无法到达PHP最外层。
