### ISSUE TITLE
swoole_http_client->download  error

### ISSUE THREAD

**Issue by w3yyb** [swoole/swoole-src#1830]
断点续传
$cli = new swoole_http_client('127.0.0.1', 80);
$file = __DIR__.'/video.avi';
$offset = filesize($file);
$cli->setHeaders([
    'Host' => "localhost",
    "User-Agent" => 'Chrome/49.0.2587.3',
    'Accept' => '*',
    'Accept-Encoding' => 'gzip',
    'Range' => "bytes=$offset-",
]);

$cli->download('/video.avi', $file, function ($cli) {
    var_dump($cli->downloadFile);
}, $offset);

when add the fourth params $offset then report error:

swoole_http_client::download() expects exactly 3 parameters, 4 given

 ps: swoole version:2.0.5

**Comment by twose** [comment]
@w3yyb 
请按issue模板提问, 你所使用的版本?
