### ISSUE TITLE
swoole_http_client->download error

### ISSUE THREAD

**Issue by w3yyb** [swoole/swoole-src#1831]
1. What did you do? If possible, provide a recipe for reproducing the error.
断点续传 download file
$cli = new swoole_http_client('127.0.0.1', 80);
$file = DIR.'/video.avi';
$offset = filesize($file);
$cli->setHeaders([
'Host' => "localhost",
"User-Agent" => 'Chrome/49.0.2587.3',
'Accept' => '*',
'Accept-Encoding' => 'gzip',
'Range' => "bytes=$offset-",
]);

$cli->download('/video.avi', $file, function ($cli) {
var_dump($cli->downloadFile);
}, $offset);

when add the fourth params $offset then report error:
swoole_http_client::download() expects exactly 3 parameters, 4 given
 

2. What did you expect to see?
 
download success

3. What did you see instead?
swoole_http_client::download() expects exactly 3 parameters, 4 given

 
4. What version of Swoole are you using (`php --ri swoole`)?

swoole 2.0.5

5. What is your machine environment used (including version of kernel & php & gcc) ? 
kernel : 4.15.0-29-generic,   php7.0  ,gcc version 7.3.0

6. If you are using ssl, what is your openssl version?
no use.

**Comment by twose** [comment]
@w3yyb 
升级你的swoole版本到最新(现在是4.0.3).
