### ISSUE TITLE
in docker mode, CTRL+C does not work 

### ISSUE THREAD

**Issue by millken** [swoole/swoole-src#1841]
```
#docker run --rm --name phptest -v C:\Code\php\ypf:/var/www/html -p 7000:7000 -it millken/php php /var/www/html/example/swoole.php
^C^C
^C^C^C
```

**Comment by twose** [comment]
@millken 
what is your script?

**Comment by millken** [comment]
i found this problem in docker issues [https://github.com/docker-library/php/issues/505#issuecomment-334274337](url), add `--init` to your command-line
