### ISSUE TITLE
Swoole\Coroutine\Redis 问题

### ISSUE THREAD

**Issue by bnubobby** [swoole/swoole-src#1848]
php 版本 7.2.5
swoole 版本 4.0.3
使用 Swoole\Coroutine\Redis 做token认证，会修改浏览器cookie
在做功能测试时正常。
但是在用apache ab 做压力测试时，请求失败率超高 (90%以上)
swoole报错：Warning: Swoole\Http\Response::cookie(): Http request is finished
                      Warning: Swoole\Http\Response::header(): Http request is finished. 

这时候如果访问页面，大概率是500错误 或者 没有命中缓存

同样的情况，使用 \Redis  请求失败率最多为千份之一，在做压测期间，访问页面正常

是我的处理有问题吗？

**Comment by twose** [comment]
是否使用了单例模式, 且没有正确处理上下文切换, 导致end了不该end的response.
不按issue模板提问和贴代码无法正确解答的问题, 只能猜测.

**Comment by Arealm** [comment]
@bnubobby 怎么解决的？
