### ISSUE TITLE
integer literal is too large to be represented in type 'long'

### ISSUE THREAD

**Issue by ryandesign** [swoole/swoole-src#1849]
1. What did you do? If possible, provide a recipe for reproducing the error.

compile swoole for 32-bit (use `-arch i386` in `CFLAGS`, `CXXFLAGS`, `LDFLAGS`)

2. What did you expect to see?

no warnings

3. What did you see instead?

```
src/reactor/ReactorSelect.c:209:30: warning: integer literal is too large to be represented in type 'long', interpreting as 'unsigned long' per C89; this literal will have type 'long long' in C99 onwards [-Wc99-compat]
            timeout.tv_sec = SW_MAX_UINT;
                             ^
include/swoole.h:160:32: note: expanded from macro 'SW_MAX_UINT'
#define SW_MAX_UINT            4294967295
                               ^
1 warning generated.
```

From what I can tell, the C standard does not specify a maximum value for `time_t`.

4. What version of Swoole are you using (`php --ri swoole`)?

4.0.3

5. What is your machine environment used (including version of kernel & php & gcc) ? 

macOS 10.13.6
php 7.2.8
clang "Apple LLVM version 9.1.0 (clang-902.0.39.2"

6. If you are using ssl, what is your openssl version?

1.0.2o

**Comment by twose** [comment]
Fixed in 4954f16
