### ISSUE TITLE
configure fail: "checking for /ext/sockets/php_sockets.h ... no"

### ISSUE THREAD

**Issue by diyism** [swoole/swoole-src#1853]
=======================configure error========================
git clone -b PHP-7.2 --depth 1 https://github.com/php/php-src.git
cd php-src/
git clone -b master --depth 1 https://github.com/swoole/swoole-src.git ext/swoole
./buildconf --force
./configure --prefix=/usr/local/php7 --disable-all --enable-cli --disable-cgi --disable-fpm --disable-phpdbg --enable-bcmath --enable-hash --enable-json --enable-mbstring --enable-mbregex --enable-mbregex-backtrack --enable-sockets --enable-pdo --with-sodium --with-password-argon2 --with-sqlite3 --with-pdo-sqlite --with-pcre-regex --with-zlib --with-openssl --enable-swoole-static --enable-openssl --with-swoole

checking /ext/sockets/php_sockets.h usability... no
checking /ext/sockets/php_sockets.h presence... no
checking for /ext/sockets/php_sockets.h... no
configure: error: cannot find /ext/sockets/php_sockets.h. Please check if sockets extension installed

=========================problem=======================

I found this:
https://github.com/swoole/swoole-src/commit/744c31cbf65bcff51740d61bdcb3b5831ec7d591#diff-788d457a20b110cc38e571dec9ddc68c 

any fix?

**Comment by twose** [comment]
Ping @petk

**Comment by petk** [comment]
Hm, indeed, building PECL extensions from the php-src/ext directory to statically building them into PHP directly... I think the new patch fixes this also then :) Thanks for reporting.

**Comment by twose** [comment]
Fixed in #1855
