### ISSUE TITLE
Variables are reset between http/websocket events

### ISSUE THREAD

**Issue by achlubek** [swoole/swoole-src#1858]
1. What did you do? If possible, provide a recipe for reproducing the error.
Here is the code that clearly shows the problem:
```<?php
$counter = 0;

$http = new swoole_http_server('php', 8080);
$http->on('request', function ($request, $response) use ($counter) {
    $response->header("Content-Type", "text/plain");
    $response->end($counter++);
});

$http->start();
```

2. What did you expect to see?
With every request, the response would return incremented counter, so 0, 1, 2, 3, and so on

3. What did you see instead?
Every response returns 0, as if $counter was reinitialized every time

4. What version of Swoole are you using (`php --ri swoole`)?
Version => 4.0.3

5. What is your machine environment used (including version of kernel & php & gcc) ? 
Docker, set up like this: https://github.com/achlubek/swoole_experiments/blob/master/php-image/Dockerfile

6. If you are using ssl, what is your openssl version?
Not using SSL

**Comment by twose** [comment]
You can't use global var, because requests would be dispatched to multi worker processes, so it always returns 0.
if you set `worker_num = 1`, it will comply with your expectations.
