### ISSUE TITLE
swoole 1.79在ubuntu 14.04 ,centos,及mac os 上 http_server 用SWOOLE_BASE 模式，都产生段错误，以下是错误信息

### ISSUE THREAD

**Issue by w3yyb** [swoole/swoole-src#186]
swoole 1.79在ubuntu 14.04 ,centos,及mac os 上 http_server 用SWOOLE_BASE 模式，都产生段错误，以下是错误信息，请查看

dmesg:
[ 1529.066050] php[10022]: segfault at 960d5e75 ip 08387a3d sp bf984230 error 4 in php5[8048000+81c000]
-------------------------

yangyanbin@yangyanbin-s5715cn:~/桌面/swoole-crontab-swoole-crontab-0.4 /test$ gdb php core
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 19664]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Core was generated by `php http_server.php'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x08387a3d in gc_zval_possible_root ()
(gdb) bt
#0  0x08387a3d in gc_zval_possible_root ()
#1  0x083581a7 in zend_call_function ()
#2  0x08358821 in call_user_function_ex ()
#3  0xb3f0e974 in http_onReceive (factory=0x8b64f14, req=0xbf9d0e9c)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable /swoole_http.c:810
#4  0xb3f17c0f in swFactory_dispatch (factory=0x8b64f14, task=0xbf9d0e98)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/factory /Factory.c:49
#5  0xb3f26e5d in swReactorThread_send_string_buffer (buffer=0xbf9d2f04, buffer=0xbf9d2f04,
    conn=0x8b654f8, conn=0x8b654f8, thread=<optimized out>)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/network /ReactorThread.c:1763
#6  0xb3f27f2c in swReactorThread_onReceive_http_request (reactor=0x8b6517c, event=0xbf9d4f84)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/network /ReactorThread.c:1287
#7  0xb3f1d1f7 in swReactorEpoll_wait (reactor=0x8b6517c, timeo=0xbf9d4fd8)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/reactor /ReactorEpoll.c:257
#8  0xb3f2992b in swReactorProcess_loop (pool=pool@entry=0xb3ce4120,
    worker=worker@entry=0xbf9d5020)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/network /ReactorProcess.c:236
#9  0xb3f29f80 in swReactorProcess_start (serv=serv@entry=0x8b64c18)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/network /ReactorProcess.c:96
#10 0xb3f20488 in swServer_start (serv=serv@entry=0x8b64c18)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/network /Server.c:511
#11 0xb3f0e236 in zim_swoole_http_server_start (ht=0, return_value=0xb6f3a340,
    return_value_ptr=0x0, this_ptr=0xb6f38008, return_value_used=0)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable /swoole_http.c:1132
#12 0x0841bb92 in execute_internal ()
#13 0x08356087 in dtrace_execute_internal ()
#14 0x0841f668 in ?? ()
#15 0x08392f17 in execute_ex ()
#16 0x08355f7d in dtrace_execute_ex ()
---Type <return> to continue, or q <return> to quit---
#17 0x0841d745 in zend_execute ()
#18 0x083680fe in zend_execute_scripts ()
#19 0x083038d5 in php_execute_script ()
#20 0x0842193f in ?? ()
#21 0x08099727 in main ()

(gdb) f 1
#1  0x083581a7 in zend_call_function ()
(gdb) f 0
#0  0x08387a3d in gc_zval_possible_root ()
(gdb) f 2
#2  0x08358821 in call_user_function_ex ()
(gdb) f 3
#3  0xb3f0e974 in http_onReceive (factory=0x8b64f14, req=0xbf9d0e9c)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable /swoole_http.c:810
810            if (call_user_function_ex(EG(function_table), NULL, php_sw_http_server_callbacks[called], &retval, 2, args, 0, NULL TSRMLS_CC) == FAILURE)
(gdb) f 4
#4  0xb3f17c0f in swFactory_dispatch (factory=0x8b64f14, task=0xbf9d0e98)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/factory /Factory.c:49
49        return factory->onTask(factory, &(task->data));
(gdb) f 5
#5  0xb3f26e5d in swReactorThread_send_string_buffer (buffer=0xbf9d2f04, buffer=0xbf9d2f04,
    conn=0x8b654f8, conn=0x8b654f8, thread=<optimized out>)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/network /ReactorThread.c:1763
1763            if (factory->dispatch(factory, &task) < 0)
(gdb) f 6
#6  0xb3f27f2c in swReactorThread_onReceive_http_request (reactor=0x8b6517c, event=0xbf9d4f84)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/network /ReactorThread.c:1287
1287 swReactorThread_send_string_buffer(swServer_get_thread(serv, SwooleTG.id), conn, buffer);

(gdb) f 7
#7  0xb3f1d1f7 in swReactorEpoll_wait (reactor=0x8b6517c, timeo=0xbf9d4fd8)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/reactor /ReactorEpoll.c:257
257                    ret = handle(reactor, &ev);
(gdb) f 8
#8  0xb3f2992b in swReactorProcess_loop (pool=pool@entry=0xb3ce4120,
    worker=worker@entry=0xbf9d5020)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/network /ReactorProcess.c:236
236        reactor->wait(reactor, &timeo);
(gdb) f 9
#9  0xb3f29f80 in swReactorProcess_start (serv=serv@entry=0x8b64c18)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/network /ReactorProcess.c:96
96            return swReactorProcess_loop(&SwooleGS->event_workers, &single_worker);
(gdb) f 10
#10 0xb3f20488 in swServer_start (serv=serv@entry=0x8b64c18)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable/src/network /Server.c:511
511            ret = swReactorProcess_start(serv);

(gdb) f 11
#11 0xb3f0e236 in zim_swoole_http_server_start (ht=0, return_value=0xb6f3a340,
    return_value_ptr=0x0, this_ptr=0xb6f38008, return_value_used=0)
    at /home/yangyanbin/下载/swoole-src-swoole-1.7.9-stable /swoole_http.c:1132
1132        ret = swServer_start(serv);
(gdb) f 12
#12 0x0841bb92 in execute_internal ()
(gdb) f 13
#13 0x08356087 in dtrace_execute_internal ()
(gdb) f 14
#14 0x0841f668 in ?? ()
(gdb) f 15
#15 0x08392f17 in execute_ex ()
(gdb) f 16
#16 0x08355f7d in dtrace_execute_ex ()
(gdb) f 17
#17 0x0841d745 in zend_execute ()
(gdb) f 18
#18 0x083680fe in zend_execute_scripts ()
(gdb) f 19
#19 0x083038d5 in php_execute_script ()

(gdb) f 20
#20 0x0842193f in ?? ()
(gdb) f 21
#21 0x08099727 in main ()

-------------------------------------
望你们早日 修复，谢谢。

**Comment by matyhtf** [comment]
Fixed in 1.7.10
