### ISSUE TITLE
swoole_client_coro.c 出现core sw_zval_ptr_dtor(&zobject);

### ISSUE THREAD

**Issue by highwayliu** [swoole/swoole-src#1860]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

高并发协程调用TCP
foreach ($requests as $v) {
            $client = new Swoole\Coroutine\Client(SWOOLE_SOCK_TCP);
            $client->set(['open_eof_check' => true, 'package_eof' => "\n"]);

            if (!$client->connect($v['ip'], $v['port'], 1)) {
                $response->status(500);
                $returns = array_fill(0, count($requests), $errReturn);
                return implode('&&&', $returns);
            }
            if (is_array($v['param'])) {
                $in = http_build_query($v['param']) . "\n";
            } else {
                $in = $v['param'] . "\n";
            }
            $client->send($in);
            $clients[] = $client;
}

        foreach ($clients as $k => $client) {
            $rs = $client->recv();
            parse_str($rs, $output);
            if (empty($output)) {
                $rs = 'result=500';
            }
            $returns[] = $rs;
            $client->close();
        }

2. What did you expect to see?
![image](https://user-images.githubusercontent.com/39515014/43561267-de78a5f8-9648-11e8-93b0-8fe282cc5434.png)

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?

2.0.11

5. What is your machine environment used (including version of kernel & php & gcc) ? 

kernel Linux version 2.6.32.57
php 5.6.8
gcc 4.4.6

6. If you are using ssl, what is your openssl version?

**Comment by twose** [comment]
请升级到`4.3`版本
