### ISSUE TITLE
使用 swoole_timer_tick 出现 debug信息

### ISSUE THREAD

**Issue by mrzxy** [swoole/swoole-src#1863]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

![image](https://user-images.githubusercontent.com/11501927/43674721-beb94a88-980a-11e8-9689-628b5ea339ef.png)

2. What did you expect to see?

3. What did you see instead?

![image](https://user-images.githubusercontent.com/11501927/43674768-0bb2e92a-980b-11e8-9ee6-46634ee51b8a.png)

4. What version of Swoole are you using (`php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ? 

PHP 7.2.5  
gcc 版本 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC)

6. If you are using ssl, what is your openssl version?

**Comment by twose** [comment]
编译的时候请不要加上debug和trace参数
