### ISSUE TITLE
协程client 如何做连接池

### ISSUE THREAD

**Issue by xiaoshenge** [swoole/swoole-src#1868]
server.php
```
$server = new swoole_server("127.0.0.1", 9503);
$server->on('connect', function ($server, $fd){
	echo "connection open: {$fd}\n";
});
$server->on('receive', function ($server, $fd, $reactor_id, $data) {
	$server->send($fd, "fd: {$fd} Swoole: {$data}");
});
$server->on('close', function ($server, $fd) {
	echo "connection close: {$fd}\n";
});
$server->start();
```
client.php
```
$pool = new SplQueue();

go(function ()use ($pool){

	if (count($pool) == 0){
		$client = new \Swoole\Coroutine\Client(SWOOLE_SOCK_TCP);
		$client->connect('127.0.0.1', 9503, 0.5);
	} else {
		$client = $pool->pop();
	}
	$client->send("hello");
	$resp = $client->recv();
	$pool->push($client);
	print_r($resp);

});
```
在执行client.php 时候发现client.php 一直没有结束执行。

请问这样实现连接池复用client，有什么问题么，还是有其他方式。

**Comment by twose** [comment]
你得把pool清空, 即让所有client的引用计数为0, 所有client都销毁时会退出事件循环, 脚本结束.
可以参考: "https://github.com/swlib/saber#注意在一次性脚本中释放连接池"

**Comment by xiaoshenge** [comment]
在http server 中，onRequest 里面自动启用协程序，我配置了worker的max_request，这个释放连接池是如何触发的呢

**Comment by twose** [comment]
@xiaoshenge 
- max_request只能用于同步阻塞、无状态的请求响应式服务器程序
- 纯异步的Server不应当设置max_request
- 使用Base模式时max_request是无效的

没有内存泄漏就无需启用max_request, 没有意义

**Comment by xiaoshenge** [comment]
不设置max_request， 连接池需要我手动释放么，一次性脚本我在脚本结束的地方释放连接池，如果是http server我应该在何处释放连接池呢

**Comment by twose** [comment]
@xiaoshenge 不需要释放, 为什么要释放? server本就是常驻内存长期运行的

**Comment by xiaoshenge** [comment]
如果server异常终止，也不用处理是吧

**Comment by twose** [comment]
1. 进程异常退出了所有东西自然都没了, 这种连接池是进程级别的, 没有跨进程不需要任何处理.
2. 请提供相关代码

**Comment by xiaoshenge** [comment]
2 这个问题刚试了不存在，应该是我之前测试的时候是在httpServer下运行，不是在一次性脚本里面

**Comment by xiaoshenge** [comment]
我想跨进程做连接池该怎么做

**Comment by twose** [comment]
跨进程连接池比较复杂, 实现和维护起来更有难度
有MySQL的: https://github.com/swoole/mysql-proxy

无法给出更详细的具体实现解答, 毕竟这里不是实战教学区
