### ISSUE TITLE
关于swoole上静态文件的问题

### ISSUE THREAD

**Issue by chenye2017** [swoole/swoole-src#1871]
```
'enable_static_handler' => true,
 'document_root' => PRO_STATIC_DIR
```
通过开启swoole上静态文件夹的配置，成功访问后，每次我修改静态文件夹中html的内容，页面没有变化，我的swoole版本是2.2。修改完html内容后，我有重启webserver，通过
1.ctrl + c 直接关闭
 2. 通过netstat -atnp|grep 端口号，查看进程号，然后 kill
 3. kill -9 'pid '/opt/pyspider/php/bin/php /home/code/login/bbs/server.php' 
这些方式都没能让我修改的静态文件生效，我不知道是我操作的原因，还是什么其他的原因

**Comment by twose** [comment]
请先使用curl命令或postman排除浏览器缓存问题

**Comment by twose** [comment]
只提供现象, 无法复现的BUG无法进行修复, 状态码为200时swoole没有提供任何缓存功能, 建议使用抓包工具分析查看

**Comment by chenye2017** [comment]
好的 ，谢谢

**Comment by chenye2017** [comment]
e，最近在整nginx上静态文件也出现了类似的问题，偶然谷歌到不是nginx的问题（nginx文件缓存关闭，浏览器禁用缓存），是我的虚拟机的问题，[关于vagrant中静态文件修改不生效的处理办法](http://shibing.github.io/2017/01/06/%E4%BD%BF%E7%94%A8vagrant%E5%92%8Cnginx%E5%BC%80%E5%8F%91%E9%9D%99%E6%80%81%E6%96%87%E4%BB%B6%E4%BF%AE%E6%94%B9%E4%B8%8D%E7%94%9F%E6%95%88%E9%97%AE%E9%A2%98/)，因为以前一直在虚拟机中开发接口，没有遇到这种问题，从来没考虑过是虚拟机的问题

**Comment by it-hjm007** [comment]
、

> e，最近在整nginx上静态文件也出现了类似的问题，偶然谷歌到不是nginx的问题（nginx文件缓存关闭，浏览器禁用缓存），是我的虚拟机的问题，[关于vagrant中静态文件修改不生效的处理办法](http://shibing.github.io/2017/01/06/%E4%BD%BF%E7%94%A8vagrant%E5%92%8Cnginx%E5%BC%80%E5%8F%91%E9%9D%99%E6%80%81%E6%96%87%E4%BB%B6%E4%BF%AE%E6%94%B9%E4%B8%8D%E7%94%9F%E6%95%88%E9%97%AE%E9%A2%98/)，因为以前一直在虚拟机中开发接口，没有遇到这种问题，从来没考虑过是虚拟机的问题

在vagrant下开发，nginx可以关闭sendfile，swoole要怎么解决静态资源修改不生效的问题呢？
