### ISSUE TITLE
Keep kafka connection open while running httpserver and push messages from onRequest

### ISSUE THREAD

**Issue by vrgenl** [swoole/swoole-src#1872]
I'm trying to implement kafka with rdkafka which i have working but with a major flaw. The connection while producing a message takes 1 second to close (https://github.com/arnaud-lb/php-rdkafka/issues/145).

I think the best option is to start a parallel process which keeps the kafka connection open so I can push messages from my controllers to kafka without creating/closing the kafka connection.

I've played with the Process, Pool and onWorkerStart httpserver listener but i'm not happy yet what I came up with.

If anyone can give me some pointers of the best setup for this specific scenario that would be great!

When I'm happy with my app I will publish my findings within a docker-compose file.

**Comment by patrickkh7788** [comment]
have you try AsyncTask ?

**Comment by lragon** [comment]
@rogierverbrugge  see https://github.com/weiboad/kafka-php/issues/260#issuecomment-485226757
