### ISSUE TITLE
Swoole\Coroutine\Redis setsockopt(TCP_NODELAY): Invalid argument

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/swoole-src#1881]
首先请原谅我又来提问题麻烦你们了( ﹁ ﹁ ) ~→

这个问题目前只出现在wsl上，两台用wsl的机器连`192.168.0.110`这个上面的redis都这样。但是连`127.0.0.1`是正常的……

在虚拟机里跑linux，连110没有毛病

本地和110那台机，都是windows，一模一样的版本号`3.2.100`

这是今天发现的问题，之前都是正常的没毛病，4.0.2、4.0.3、4.0.4都试过……突发问题

代码：

```php
<?php
go(function(){
	$redis = new \Swoole\Coroutine\Redis();
	var_dump($redis->connect('192.168.0.110', 6379, false));
	var_dump($redis->errCode, $redis->errMsg);
});
```

输出：

```php
bool(false)
int(1)
string(41) "setsockopt(TCP_NODELAY): Invalid argument"
```

**Comment by twose** [comment]
这是今天发现的问题，之前都是正常的没毛病什么意思?
`redis-cli -h 192.168.0.110 -p 6379` 这个能连上吗?

**Comment by twose** [comment]
是否开启了`open_tcp_nodelay`这个选项?

**Comment by Yurunsoft** [comment]
`open_tcp_nodelay`我在文档里看是`Server`用的吧？Redis客户端也能设置？

**Comment by twose** [comment]
看了下client有的, 但redis没有, 不清楚具体原因

**Comment by Yurunsoft** [comment]
让大佬们看下吧，说不定又是一个隐藏的问题，刚好让我碰到了，我这暂时先用本地的redis开发

**Comment by matyhtf** [comment]
这个问题是 hiredis 不兼容 WSL 导致的。需要 hiredis 或  WSL 进行适配，swoole 层面没有修改的空间。
