### ISSUE TITLE
http server on ssl miss https => on

### ISSUE THREAD

**Issue by zpqsunny** [swoole/swoole-src#1887]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

in http server when I use ssl , on `request->server` miss `https => on`

2. What did you expect to see?

i want to on `request->server` add key value with `https => on`

3. What did you see instead?

miss `https => on`

4. What version of Swoole are you using (`php --ri swoole`)?

2.2.0

5. What is your machine environment used (including version of kernel & php & gcc) ? 

php 7.2.5

6. If you are using ssl, what is your openssl version?

OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by twose** [comment]
why should it have https on? you have already known if it is https when you create the server.
