### ISSUE TITLE
redis set return null

### ISSUE THREAD

**Issue by highwayliu** [swoole/swoole-src#1888]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

redis set 

2. What did you expect to see?

return not null

3. What did you see instead?

return null
Return value of Swoft\\Redis\\Redis::set() must be of the type boolean, null returned

4. What version of Swoole are you using (`php --ri swoole`)?

4.0.3

5. What is your machine environment used (including version of kernel & php & gcc) ? 

kernel Linux version 2.6.32.57
php 7.1.1
gcc 4.4.6
hiredis 3.1

6. If you are using ssl, what is your openssl version?
no

**Comment by twose** [comment]
Go to https://github.com/swoft-cloud/swoft/issues
