### ISSUE TITLE
[compilation question] php binary is using poll not epoll

### ISSUE THREAD

**Issue by diyism** [swoole/swoole-src#1889]
```
reproduction procedure:

===============1.compile========
$git clone -b PHP-7.3 --depth 1 https://github.com/php/php-src.git
$cd php-src/
$mkdir ext/swoole && curl -s "https://codeload.github.com/swoole/swoole-src/tar.gz/v4.0.4" | tar xvz --strip 1 -C ext/swoole
$./buildconf --force
$./configure --prefix=/usr/local/php7 --disable-all --enable-cli --disable-cgi --disable-fpm --disable-phpdbg --enable-bcmath --enable-hash --enable-json --enable-mbstring --enable-mbregex --enable-mbregex-backtrack --enable-sockets --enable-pdo --with-sodium --with-password-argon2 --with-sqlite3 --with-pdo-sqlite --with-pcre-regex --with-zlib --with-openssl-dir --enable-swoole-static --enable-openssl --with-swoole
$time make -j `cat /proc/cpuinfo | grep processor | wc -l`
$sudo make install
$sudo rm -f /usr/bin/php
$sudo ln -s /usr/local/php7/bin/php /usr/bin/php

===============2.server.php========
<?php
$http = new swoole_http_server("127.0.0.1", 8080);
$http->on('request', function ($request, $response)
                     {
                          $response->end('hello');
                    }
         );
$http->start();
?>

===============3.run========
$strace php server.php
....
poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout) 
poll([{fd=3, events=POLLIN}], 1, 999) = 0 (Timeout)
....

===============4.curl, blocked, no response, no end========
$curl http://127.0.0.1:8080

===============5.envirionment========
$ cat /usr/include/bits/syscall.h |grep epoll
#define SYS_epoll_create __NR_epoll_create
#define SYS_epoll_create1 __NR_epoll_create1
#define SYS_epoll_ctl __NR_epoll_ctl
....

===============6.problem========
if the php binary is correct, it shoud print:
$strace php server.php
....
epoll_wait(6, {}, 4096, 999) = 0 
epoll_wait(6, {}, 4096, 999) = 0
....


```

**Comment by twose** [comment]
why you have to compile extension statically?
you'd better not run swoole server by this way, it's not fpm and you can't use `register_shutdown_function` like this.
and if the script can't find `epoll_create` function by `AC_CHECK_LIB` it will choose the other way.
try to compile swoole extension alone.

**Comment by diyism** [comment]
php-src/ext/swoole/config.m4:384: AC_CHECK_LIB(c, epoll_create, AC_DEFINE(HAVE_EPOLL, 1, [have epoll]))

maybe there's some problem in my linux, but i don't know how to debug AC_CHECK_LIB with command line

**Comment by diyism** [comment]
==================================compilation1: php7.3+swoole2.x-lts==================================
$git clone -b PHP-7.3 --depth 1 https://github.com/php/php-src.git
$cd php-src/
$git clone -b 2.x-lts --depth 1 https://github.com/swoole/swoole-src.git ext/swoole
$./buildconf --force
$./configure --prefix=/usr/local/php7 --disable-all --enable-cli --disable-cgi --disable-fpm --disable-phpdbg --enable-bcmath --enable-hash --enable-json --enable-mbstring --enable-mbregex --enable-mbregex-backtrack --enable-sockets --enable-pdo --with-sodium --with-password-argon2 --with-sqlite3 --with-pdo-sqlite --with-pcre-regex --with-zlib --with-openssl-dir --enable-swoole-static --enable-openssl --with-swoole
$grep epoll config.log
configure:83908: checking for epoll_create in -lc
ac_cv_lib_c_epoll_create=yes

==================================compilation2. php7.3+swoole4.0.4==================================
$git clone -b PHP-7.3 --depth 1 https://github.com/php/php-src.git
$cd php-src/
$mkdir ext/swoole && curl -s "https://codeload.github.com/swoole/swoole-src/tar.gz/v4.0.4" | tar xvz --strip 1 -C ext/swoole
$./configure --prefix=/usr/local/php7 --disable-all --enable-cli --disable-cgi --disable-fpm --disable-phpdbg --enable-bcmath --enable-hash --enable-json --enable-mbstring --enable-mbregex --enable-mbregex-backtrack --enable-sockets --enable-pdo --with-sodium --with-password-argon2 --with-sqlite3 --with-pdo-sqlite --with-pcre-regex --with-zlib --with-openssl-dir --enable-swoole-static --enable-openssl --with-swoole
$grep epoll config.log
configure:84677: checking for epoll_create in -lc
| char epoll_create ();
| return epoll_create ();
ac_cv_lib_c_epoll_create=no

==================================diff==================================
The only difference between compilation1 and compilation2 is swoole version,
which differnce in swoole4.0.4 compared to swoole2.x caused the failure of checking epoll_create?

**Comment by diyism** [comment]
=============swoole2===========
$ grep -C2 "checking for epoll_create" config.log
configure:83891: $? = 0
configure:83900: result: yes
configure:83908: checking for epoll_create in -lc
configure:83933: cc -o conftest -Wall -pthread -g -O2 -fvisibility=hidden   -lpthread -Wl,-rpath,/lib -L/lib conftest.c -lc  -lssl -largon2 -lresolv -lcrypt -lrt -lz -lrt -lm -ldl -lnsl  -lsodium -lcrypt -largon2 -lrt -lssl -lcrypto >&5
configure:83933: $? = 0

=============swoole4===========
$ grep -C2 "checking for epoll_create" config.log
| }
configure:84668: result: no
configure:84676: checking for epoll_create in -lc
configure:84701:  -o conftest    -lpthread -z now -Wl,-rpath,/lib -L/lib conftest.cpp -lc  -lssl -largon2 -lresolv -lcrypt -lrt -lz -lrt -lm -ldl -lnsl  -lsodium -lcrypt -largon2 -lrt -lssl -lcrypto >&5
./configure: line 2932: -o: command not found

======question=======
why is swoole4 using c++?

**Comment by patrickkh7788** [comment]
static build still not call epoll in the last release?

**Comment by diyism** [comment]
===========compilation: php7.3+swoole4.1.2===============
$sudo apt-get install re2c bison autoconf zlib1g-dev libssl-dev libcurl4-openssl-dev libargon2-0-dev libsodium-dev
$git clone -b PHP-7.3 --depth 1 https://github.com/php/php-src.git
$cd php-src/
$mkdir ext/swoole && curl -s "https://codeload.github.com/swoole/swoole-src/tar.gz/v4.1.2" | tar xvz --strip 1 -C ext/swoole
$./buildconf --force
$./configure --prefix=/usr/local/php7 --disable-all --enable-cli --disable-cgi --disable-fpm --disable-phpdbg --enable-bcmath --enable-hash --enable-json --enable-mbstring --enable-mbregex --enable-mbregex-backtrack --enable-sockets --enable-pdo --with-sodium --with-password-argon2 --with-sqlite3 --with-pdo-sqlite --with-pcre-regex --with-zlib --with-openssl-dir --enable-swoole-static --enable-openssl --with-swoole
$ grep epoll config.log
configure:84703: checking for epoll_create in -lc
| char epoll_create ();
| return epoll_create ();
ac_cv_lib_c_epoll_create=no

The problem is still there for swoole-4.1.2

**Comment by diyism** [comment]
I'm using php-swoole in android APK, it was cross-compiled with php 7.0.19 + swoole 1.9,
but the "musl-cross-compilers" only support statically compilation to php and swoole,
so i wish statically compile php 7.3+swoole 4.1.2 successfully first. @twose @matyhtf

**Comment by diyism** [comment]
Everything is ok now for php7.3+swoole4.3.0.
Great thanks to @matyhtf and the swoole team.

===========compilation: php7.3+swoole4.3.0===============
$sudo apt-get install re2c bison autoconf zlib1g-dev libssl-dev libcurl4-openssl-dev libargon2-0-dev libsodium-dev
$git clone -b PHP-7.3 --depth 1 https://github.com/php/php-src.git
$cd php-src/
$mkdir ext/swoole && curl -s "https://codeload.github.com/swoole/swoole-src/tar.gz/v4.3.0" | tar xvz --strip 1 -C ext/swoole
$./buildconf --force
$./configure --prefix=/usr/local/php7 --disable-all --enable-cli --disable-cgi --disable-fpm --disable-phpdbg --enable-bcmath --enable-hash --enable-json --enable-mbstring --enable-mbregex --enable-mbregex-backtrack --enable-sockets --enable-pdo --with-sodium --with-password-argon2 --with-sqlite3 --with-pdo-sqlite --with-pcre-regex --with-zlib --with-openssl-dir --enable-openssl --enable-swoole
$time make -j `cat /proc/cpuinfo | grep processor | wc -l`
$sudo make install
$sudo rm -f /usr/bin/php
$sudo ln -s /usr/local/php7/bin/php /usr/bin/php
