### ISSUE TITLE
源码编译swoole错误

### ISSUE THREAD

**Issue by Imagle** [swoole/swoole-src#189]
在centos上编译swoole会出现错误。
**gcc版本 ** 如下：
> Reading specs from /usr/lib/gcc/x86_64-redhat-linux/3.4.5/specs
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --disable-checking --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-java-awt=gtk --host=x86_64-redhat-linux
Thread model: posix
gcc version 3.4.5 20051201 (Red Hat 3.4.5-2)

**错误信息**如下：
> In file included from /home/img/swoole-src/src/factory/FactoryProcess.c:17:
/home/img/swoole-src/include/swoole.h: In function `sw_spinlock':
/home/img/swoole-src/include/swoole.h:1458: warning: implicit declaration of function `__sync_bool_compare_and_swap'
In file included from /home/img/swoole-src/src/factory/FactoryProcess.c:18:
/home/img/swoole-src/include/Server.h: In function `swServer_worker_schedule':
/home/img/swoole-src/include/Server.h:635: warning: implicit declaration of function `__sync_fetch_and_add'
/home/img/swoole-src/src/factory/FactoryProcess.c: In function `swFactoryProcess_notify':
/home/img/swoole-src/src/factory/FactoryProcess.c:832: error: unrecognizable insn:
(insn:HI 10 9 11 0 /home/img/swoole-src/src/factory/FactoryProcess.c:828 (set (reg/f:DI 61)
        (const:DI (plus:DI (symbol_ref:DI ("sw_notify_data") [flags 0x12] <var_decl 0x2a98b27ea0 sw_notify_data>)
                (const_int 8 [0x8])))) -1 (nil)
    (nil))
/home/img/swoole-src/src/factory/FactoryProcess.c:832: internal compiler error: in extract_insn, at recog.c:2083
Please submit a full bug report,
with preprocessed source if appropriate.
See <URL:http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/cctoJmkO.out file, please attach this to your bugreport.
make: *** [src/factory/FactoryProcess.lo] Error 1

**Comment by matyhtf** [comment]
你的gcc版本过低，请升级到最新的gcc。Swoole至少要求gcc 4.4 +
