### ISSUE TITLE
Cannot send message from php client to websocket server

### ISSUE THREAD

**Issue by Shkarbatov** [swoole/swoole-src#1893]
Hi all, I cannot connect to swoole_websocket_server

**1. What did you do?**

**This is my client:**

```
<script>
    // Then some JavaScript in the browser:
    var ws = new WebSocket('ws://site.ll:9502/?user=tester01');
    ws.onmessage = function(evt) { console.log(evt.data); };
    ws.onopen = function (event) { ws.send('test'); }
</script>
```

**This is my server:**

```
$server = new swoole_websocket_server("127.0.0.1", 9502);

$server->on("start", function ($server) {
    echo "Swoole http server is started at http://127.0.0.1:9502\n";
});

$server->on('connect', function($server, $req) {
    echo "connect: {$req}\n";
});

$server->on('open', function($server, $req) {
    echo "connection open: {$req->fd}\n";
});

$server->on('message', function($server, $frame) {
    echo "received message: {$frame->data}\n";
    $server->push($frame->fd, json_encode(["hello", "world"]));
});

$server->on('close', function($server, $fd) {
    echo "connection close: {$fd}\n";
});

$server->start();
```

**This is my client:**

```
$client = new swoole_client(SWOOLE_SOCK_TCP);

if (!$client->connect('127.0.0.1', 9502)) {
    exit("connect failed. Error: {$client->errCode}\n");
}

$client->send("hello world\n");
echo $client->recv();
$client->close();
```

**2. What did you expect to see?**
I need to send data from php client to php webSocket and than send it to WebClient.

**3. What did you see instead?**
Server works fine and I cant send message from WebClient to WebSocket server, but when I try to run php client and connect to my server I receive an error:
> PHP Warning:  Swoole\Client::recv(): recv() failed. Error: Resource temporarily unavailable [11]

**4. What version of Swoole are you using (`php --ri swoole`)?**

```
swoole support => enabled
Version => 4.0.4
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

**5. What is your machine environment used (including version of kernel & php & gcc) ?** 

```
PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

**6. If you are using ssl, what is your openssl version?**
Not using

**Comment by twose** [comment]
Not support Xdebug now.

**Comment by Shkarbatov** [comment]
Disable it, but still receive an error.

**Comment by twose** [comment]
Try to use Swoole\Coroutine\Http\Client with upgrade method.
```php
go(function(){
        $cli = new Swoole\Coroutine\Http\Client("127.0.0.1", $port);
        $cli->set(['timeout' => -1]);
        $ret = $cli->upgrade('/');
        assert($ret);
        echo $cli->recv()->data;
        for ($i = 0; $i < 5; $i++) {
            $cli->push("hello server\n");
            echo ($cli->recv(1))->data;
            co::sleep(0.1);
        }
        $cli->close();
});
```

if you want to run server in the internet, please listen on 0.0.0.0 or :: or use Nginx to proxy.

**Comment by Shkarbatov** [comment]
Update worker to 0.0.0.0 and change my controller with Coroutine

Remove timeout and receive next:

```
$ php controller.php 
PHP Notice:  Trying to get property of non-object in /srv/curex/websocket_backend_swoole/controller.php on line 20
["hello","world"]["hello","world"]["hello","world"]["hello","world"]["hello","world"]
```

**With this:**

    echo $cli->recv()->data;

**Comment by twose** [comment]
Sorry, I just give you a simple example...
you can post bugs here, but too many detail questions we may not be able to answer.

**Comment by Shkarbatov** [comment]
Works next: https://github.com/Shkarbatov/WebSocketPHPSwoole
Can you please check is it correct?

**Comment by twose** [comment]
you can `global $server` and just save `$frame->fd`, nothing else.

**Comment by Shkarbatov** [comment]
Thanks, and last.
https://github.com/swoole/swoole-wiki/blob/master/doc/2.3.2%20-%20worker_num.md
I run 4 process, what will be, if one of them will die?

**Comment by twose** [comment]
no, every worker process has its own global vars (independent memory), so if your global vars may lead to some problems.

**Comment by Shkarbatov** [comment]
No, the main question is: Will 1 of 4 process restart if it will die, or not?

**Comment by twose** [comment]
worker process always restart and keep its num

**Comment by Shkarbatov** [comment]
Thanks!
