### ISSUE TITLE
Too many connections with CLOSE_WAIT status

### ISSUE THREAD

**Issue by 117311730** [swoole/swoole-src#1901]
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/php/bin/php...done.
[New LWP 15018]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/php /home/www/qmhb/api/artisan swoole start'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f054e20132b in php_swoole_server_get_cache (event_type=2, server_fd=0, serv=0x24230f0) at /home/download/swoole-src-4.0.4/php_swoole.h:531
531	    swoole_server_port_property *property = (swoole_server_port_property *) port->ptr;
(gdb) bt
#0  0x00007f054e20132b in php_swoole_server_get_cache (event_type=2, server_fd=0, serv=0x24230f0) at /home/download/swoole-src-4.0.4/php_swoole.h:531
#1  php_swoole_onClose (serv=0x24230f0, info=0x2b286d0) at /home/download/swoole-src-4.0.4/swoole_server.c:1722
#2  0x00007f054e28785e in swFactoryProcess_end (factory=0x2423580, fd=<optimized out>) at /home/download/swoole-src-4.0.4/src/factory/FactoryProcess.c:328
#3  0x00007f054e28da85 in swServer_tcp_close (serv=<optimized out>, fd=<optimized out>, reset=<optimized out>) at /home/download/swoole-src-4.0.4/src/network/Server.c:1230
#4  0x00007f054e20525a in zim_swoole_server_close (execute_data=0x7f0542801220, return_value=0x2b287e0) at /home/download/swoole-src-4.0.4/swoole_server.c:3016
#5  0x000000000093a8a5 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /home/download/php-7.2.4/Zend/zend_vm_execute.h:907
#6  execute_ex (ex=0x24230f0) at /home/download/php-7.2.4/Zend/zend_vm_execute.h:59749
#7  0x00007f054e28431b in swoole::Context::context_func (arg=0x272b700) at /home/download/swoole-src-4.0.4/src/coroutine/context.cc:66
#8  0x00007f054e2a8e81 in make_fcontext () at /home/download/swoole-src-4.0.4/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:64
#9  0x0000000000000000 in ?? ()

netstat 
LAST_ACK 67
SYN_RECV 19
CLOSE_WAIT 2530
ESTABLISHED 8173
FIN_WAIT1 59
FIN_WAIT2 1
CLOSING 2
TIME_WAIT 557

**Comment by twose** [comment]
请用valgrind检查或贴一下能够复现的代码？

**Comment by twose** [comment]
Fixed in 49134f8

**Comment by 117311730** [comment]
虽然不会core dump，连接还是不会释放。CLOSE_WAIT 大量存在

**Comment by twose** [comment]
@117311730 请贴代码, 你这样只能猜测问题, 之前是防御性修复, 可能你使用了错误的写法引发.

**Comment by twose** [comment]
很有可能你onClose回调发生了致命错误, 会导致这个问题, 检查你的代码, 文档里有写.

**Comment by matyhtf** [comment]
@117311730 请贴出一下 Server 的配置项

**Comment by 117311730** [comment]
只在线上才会出现。
![image](https://user-images.githubusercontent.com/1248742/44784282-b0e98f80-abbf-11e8-8394-596c85d454ff.png)

**Comment by 117311730** [comment]
SWOOLE_PROCESS

**Comment by matyhtf** [comment]
最新版本已修复此问题。
