### ISSUE TITLE
使用协程偶现coredump

### ISSUE THREAD

**Issue by hustneverland** [swoole/swoole-src#1910]
环境php-7.1.16
Version => 4.0.1
gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC)

下面是堆栈信息

#0  0x00007f34188b27e0 in ?? ()
#1  0x000000000084a2cd in zend_hash_destroy (ht=0x7f34188db1c0) at /usr/local/src/php-7.1.16/Zend/zend_hash.c:1235
#2  0x000000000084ec1d in zend_array_destroy (ht=0x7f34188db1c0) at /usr/local/src/php-7.1.16/Zend/zend_hash.c:1295
#3  0x000000000084eb35 in i_zval_ptr_dtor (ht=0x7f34188b1770) at /usr/local/src/php-7.1.16/Zend/zend_variables.h:48
#4  zend_array_destroy (ht=0x7f34188b1770) at /usr/local/src/php-7.1.16/Zend/zend_hash.c:1305
#5  0x000000000084ebb9 in i_zval_ptr_dtor (ht=0x7f341890b930) at /usr/local/src/php-7.1.16/Zend/zend_variables.h:48
#6  zend_array_destroy (ht=0x7f341890b930) at /usr/local/src/php-7.1.16/Zend/zend_hash.c:1309
#7  0x0000000000874d37 in i_zval_ptr_dtor (object=0x7f34188b2620) at /usr/local/src/php-7.1.16/Zend/zend_variables.h:48
#8  zend_object_std_dtor (object=0x7f34188b2620) at /usr/local/src/php-7.1.16/Zend/zend_objects.c:68
#9  0x0000000000879de5 in zend_objects_store_del (object=0x7f34188b2620) at /usr/local/src/php-7.1.16/Zend/zend_objects_API.c:178
#10 0x000000000087935c in zend_assign_to_variable (object=0x7f340c8011a0, member=0x7f340c801200, value=<value optimized out>, 
    cache_slot=<value optimized out>) at /usr/local/src/php-7.1.16/Zend/zend_execute.h:104
#11 zend_std_write_property (object=0x7f340c8011a0, member=0x7f340c801200, value=<value optimized out>, 
    cache_slot=<value optimized out>) at /usr/local/src/php-7.1.16/Zend/zend_object_handlers.c:728
#12 0x00000000008890e4 in ZEND_ASSIGN_OBJ_SPEC_UNUSED_CV_OP_DATA_VAR_HANDLER (execute_data=0x7f340c801180)
    at /usr/local/src/php-7.1.16/Zend/zend_vm_execute.h:31935
#13 0x0000000000896bc8 in execute_ex (ex=<value optimized out>) at /usr/local/src/php-7.1.16/Zend/zend_vm_execute.h:432
#14 0x00007f34179570fb in swoole::Context::context_func (arg=0x1df5080) at /usr/local/src/swoole-src-4.0.1/src/coroutine/context.cc:66
#15 0x00007f341797b941 in make_fcontext () at /usr/local/src/swoole-src-4.0.1/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:64
#16 0x0000000000200010 in ?? ()

**Comment by twose** [comment]
请升级到最新版本, 贴出复现代码或使用valgrind跟踪
https://wiki.swoole.com/wiki/page/10.html
