### ISSUE TITLE
swoole_redis 连接不能被关闭

### ISSUE THREAD

**Issue by xwei3752** [swoole/swoole-src#1912]
Swoole\Redis::connect(): failed to connect to the redis-server[127.0.0.1:6379], Erorr: Can't create socket: Too many open files[2]

模拟常驻脚本代码：
<pre><code>
for($i=0;$i<10000;$i++) {
    $redis = new \swoole_redis();
    $redis->connect('127.0.0.1',6379,function(\swoole_redis $redis,$result) {
        if ($result === false) {
            echo "connect to redis server failed.\n";
            return;
        }
        $redis->select(0, function (\swoole_redis $client, $result) {
            $client->rpush('test-xxx', "xcxc",function(\swoole_redis $client,$result) {
                $client->close();
            });
        });

    });
}
</code></pre>

netstat 查看连接始终是ESTABLISHED

**Comment by twose** [comment]
错误提示很明显, Too many open files, 善用搜索, 调整你系统的ulimit配置
没有特殊需求不推荐使用异步, 可使用协程或runtime将phpredis异步化.
co/redis: https://wiki.swoole.com/wiki/page/589.html
runtime: https://wiki.swoole.com/wiki/page/965.html

**Comment by xwei3752** [comment]
ulimit 调整过了，因为是在一个常驻进程里，连接数会持续增加，client->close()不起作用。没用协程因为等待网络IO仍然慢，不能满足要求

**Comment by twose** [comment]
@xwei3752 
协程和异步性能几乎是一样的, 没有快慢之分, 应该是你理解出现了偏差
常驻内存连接数过大可以使用连接池, 文档里有说明
close不起作用稍后我确认一下

**Comment by twose** [comment]
@xwei3752 
确认了一下close是没有问题的, 有可能你的机子能承载的连接数就不到10000个, 这样写1w个异步连接和数据操作是同时发出, 在接近系统ulimited值时, 后面的连接会被前面已建立的大量的连接阻塞, 无法创建新的连接, 根本没有执行到close, 调小你的测试参数, 或使用连接池机制.
