### ISSUE TITLE
onWorkerStop事件在什么情况下会调用呢。

### ISSUE THREAD

**Issue by flyflyhe** [swoole/swoole-src#1916]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ? 

6. If you are using ssl, what is your openssl version?

**Comment by flyflyhe** [comment]
文档上说明不完全。

**Comment by matyhtf** [comment]
Worker进程正常退出时调用。
