### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state

### ISSUE THREAD

**Issue by anehkumar** [swoole/swoole-src#1917]
Hi, I implement swoole WebSocket for my application I am also using Cloudflare for SSL in WebSocket to make the connection secure everything is working fine but after a minute or less than a minute, my web socket gets disconnected automatically. can you please help me how we can prevent WebSocket to disconnect automatically.

**Comment by Inokinoki** [comment]
Hi, could you please provide the details?
We can assure that you've used Swoole WebSocket server. 
- Then what's the information when WebSocket closes automatically?
- Your Swoole version
- Where does it come from, your WebSocket connection (which is the client)

Thank you very much for further information

**Comment by anehkumar** [comment]
Hi, Thanks for the reply.
Swoole Version:- 4.0.2
When I connect with socket using IP address at that time it was working fine but when I point a domain and also include Cloudflare then it was disconnected connection automatically after 1 minute and I get this error WebSocket is already in CLOSING or CLOSED state.

Where does it come from, your WebSocket connection (which is the client)
I connect to socket from my web application.

Do you have any good tutorial in which you display how to use your swoole_mysql in WebSocket, I did not figure out how to do that I want to save user message in DB and also save socket information in DB.

Thanks

**Comment by twose** [comment]
Generally speaking, the client sends the ping frame and swoole websocket server will pong automatically.
Or you met some errors, you should check your close reason.
