### ISSUE TITLE
Ask a question, Swoole intend to support gRPC PHP Server?

### ISSUE THREAD

**Issue by EDDYCJY** [swoole/swoole-src#1918]
hello,

I heard that Swoole is doing PHP gRPC Server support normally. Is there any plan for this? If so, when is it expected?

thank you !

**Comment by twose** [comment]
[grpc-client](https://github.com/swoole/grpc-client) has released, the server is on the way (next version).

**Comment by EDDYCJY** [comment]
@twose When is the next version expected to be released?

**Comment by EDDYCJY** [comment]
@twose I heard that you are developing gRPC Server with PHP. Is this the next version? Really exciting.

In addition, it is a bit cumbersome to use Swoole directly to do gRPC Server, and there is no complete code framework?

**Comment by twose** [comment]
@EDDYCJY 我有点看不懂你的英文, 能用中文沟通吗?

**Comment by EDDYCJY** [comment]
@twose 非常抱歉，是我后面把问题搞复杂了

现在主要就想请教 Swoole 开发组，在开发的基于 PHP 的 gRPC Server 大概什么时候释出？
是否有较具体点的时间，因为我公司这边在观望和等待

感谢

**Comment by twose** [comment]
@EDDYCJY 
https://github.com/swoole/grpc-client
example中包含了服务端示例, 客户端已经给出完整的调用方法, 服务端底层已经支持HTTP2, 使用时需要自己实现业务框架, 如路由等.

**Comment by EDDYCJY** [comment]
@twose 前面不是说有在实现基于 PHP 的 gRPC  服务端吗 🤔
example 里的是基于 Swoole 的 gRPC 服务端

**Comment by twose** [comment]
@EDDYCJY 
https://github.com/swoole/grpc-client/blob/master/examples/grpc/greeter_server.php
Grpc的本质就是HTTP2+Protobuf, 底层只负责实现HTTP2, 已经提供了全套的协程客户端, 服务端需要和框架一起写, 已经提供了简单实现的demo.
你要的东西并不是Swoole这个网络引擎应该提供的, 你可能需要类似Tars或者Swoole的企业级服务框架这样的东西, 这些内容不在这个issue的讨论范围内.

**Comment by EDDYCJY** [comment]
@twose 了解，感谢您的解惑

**Comment by leocavalcante** [comment]
Hi folks, what is the current status?
I was planning to add this on [Siler](https://github.com/leocavalcante/siler), but if Swoole officially supports this would be way more awesome.

**Comment by twose** [comment]
@leocavalcante Http2 server is available basically, Http2 client implements RFC more completely, but both of these are not the main content of our work...

**Comment by leocavalcante** [comment]
@twose thank you!

**Comment by hetao29** [comment]
U can try this without swoole and other 3rd libraries , just use nginx and php-fpm.
https://github.com/hetao29/php-protobuf-server
