### ISSUE TITLE
Improve English documentation

### ISSUE THREAD

**Issue by moon0326** [swoole/swoole-src#1920]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

 read Chinese and English documentation

2. What did you expect to see?

I expected to find best practice for production usage

3. What did you see instead?

nothing

4. What version of Swoole are you using (`php --ri swoole`)?

latest.

5. What is your machine environment used (including version of kernel & php & gcc) ? 

ubuntu 

6. If you are using ssl, what is your openssl version?

latest

Hi,

I have a new product that is using Guzzle heavily. I would like to switch to swoole. I noticed that my worker exit time to time, but I wasn't sure if they get restarted or not.

Are there any documentations or blog posts that I can refer how I can recover or watch workers? 

And...please invite people to slack..me and other people have submitted the form, but still have no invitation yet.

Thanks!

**Comment by twose** [comment]
don't use exit in swoole server, and the worker will automatic restart

**Comment by moon0326** [comment]
@twose Thank you, but it seems those information are almost hidden despite having a lot of stars for this project. Where can I find more documentation or information if you know? Even Chinese documentation isn't good at all. It's hard to believe such project has so little documentation.

**Comment by moon0326** [comment]
@flddr that makes sense. I will try ask more specific questions from now on.

I just thought there must have been people like me who wanted to run Swool in production, but with a lot of questions and they must have received answers already.

Thank you both twose and flddr.

**Comment by flddr** [comment]
@moon0326 good issue :) now we could organize :+1: Please, do not understand me wrong - can you edit your initially issue and delete just the how-to-issue text? :) :) i will delete this comment here, too, after done - so, for others this issue becomes more clean to follow

**Comment by flddr** [comment]
BTW: i would like to have a github book for swoole, like this one https://crystal-lang.org/docs/overview/

So, if @twose or swoole team would like to maintain, we could talk about it and the content and can provide first class docs in future :) As far as it is public, its free with gitbook :) And they have already a good tooling about viewings etc. You simply add all pages online, markdown, very easy :+1:

**Comment by moon0326** [comment]
@flddr I don't understand what you part you want me to delete. Could you be more specific please?

**Comment by flddr** [comment]
@moon0326 the complete text _before_ you begin ... Hi, I have a new product that is using Guzzle ... :)

**Comment by flddr** [comment]
@moon0326 sorry - i didn't noticed you have answered in there - sorry - please let it stay - my bad ;)

**Comment by flddr** [comment]
@moon0326 if ok and you agree, lets delete these posts about your text - my bad - to be not confusing here - i will delete my comments in some hours ;)

**Comment by moon0326** [comment]
@flddr sure, I've deleted them :)

**Comment by flddr** [comment]
@twose need your help - found nothing in https://rawgit.com/tchiotludo/swoole-ide-helper/english/docs/classes/swoole_table.html and nothing in https://www.swoole.co.uk/docs/modules/swoole-table :)

The $sizes in the following table:

```php
$table = new swoole_table($table_size);
$table->column('id', swoole_table::TYPE_INT, $size_int);
$table->column('name', swoole_table::TYPE_STRING, $size_string);
$table->column('num', swoole_table::TYPE_FLOAT, $size_float);
$table->create();
```

#### TABLE
`$table_size = 1` does nothing concrete, table rows can grow > 1 row?

#### INT
`$size_int = 1`
`1, 2, 4, 8, 16, 32, 64, -128, 0, 0, 0, 0, ...`

`$size_int = 2`
`1, 2, 4, 8, 16, 32, ... 4096, 8192, 16384, -32768, 0, 0, 0, 0, ...`

So, `$size_int = 1` = 8 bit, `2` = 16 bit and then `3` = 32 bit -> per integer digits * 8 bit, signed?

#### STRING
`$size_string` -> maximum `chars` (unicode, php multibyte, wchar_t ... ?)

#### FLOAT
Is ignored? `$size_float = 0`, `1`, `2`, `3`, ... is ok for `float(1234.567890123456)`?

#### .
Whats _memory/performance optimizing_ here? BTW: the only _warning_ is given by _stringlength_ as `WARNING swTableRow_set_value: [key=k,field=...]string value is too long.`

**So, please, what are the following exactly doing?**
`$table_size`
`$size_int`
`$size_string` (unicode, php multibyte, wchar_t ... ?)
`$size_float`

**Comment by flddr** [comment]
@twose Ok, thats hard to understand right now:

I just tried to fill my RAM in a simple Array to test memory usage.

With this simple snippet

```php
<?php

$array = array();
for ($i=0; $i < 245000000; $i++) { 
    $array[$i] = "..."; # String 945 random bytes long
}

# ... here the http-server-code from docs
```

and starting the http_server, on my 4-core machine i got now 6 processes running 7.3 GiB. So, where is the right place to build only **_one_** global Cache or `table` or how to do **_shared data_** the right way?

![image](https://user-images.githubusercontent.com/42785945/44905400-44cb7080-ad12-11e8-89dd-510f13797ba9.png)

![image](https://user-images.githubusercontent.com/42785945/44905447-5ca2f480-ad12-11e8-9332-84eb268020dc.png)

I would expect, only the **_core-coroutine-process_** would have 7.3GiB, but **_all_** _workers_ are running the same script, like node cluster?

But why is `$table = new swoole_table(1<<23);` maximum table_size? Here all 6 processes are running simply 7.2MiB, not GiB:

![image](https://user-images.githubusercontent.com/42785945/44906100-49912400-ad14-11e8-9cff-6468a4c4228d.png)

But again (**_as in my comment above_**) with this code via `php server.php`

```php
<?php

$table = new swoole_table(1<<23);
$table->column('id', swoole_table::TYPE_INT, 2); //1,2,4,8
$table->column('name', swoole_table::TYPE_STRING, 1000);
$table->column('num', swoole_table::TYPE_FLOAT, 3);
$table->create();

$http = new swoole_http_server("127.0.0.1", 9501);

$http->on("start", function ($server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$http->on("request", function ($request, $response) {

    $response->header("Content-Type", "text/html");
    $response->end();
});

$http->start();

?>
```


![image](https://user-images.githubusercontent.com/42785945/44906478-4ba7b280-ad15-11e8-8cf7-8476e42ef40f.png)

The processes have again only 7.2MiB in gnome-system-monitor:

![image](https://user-images.githubusercontent.com/42785945/44906604-a9d49580-ad15-11e8-8cea-c794e594e6a4.png)

**_and_** there is **_no_** such object to find in gnome-system-monitor processes which is using such big amount of RAM? Where is it? Here is the size ordered, the biggest in this case is dart:

![image](https://user-images.githubusercontent.com/42785945/44906699-f1f3b800-ad15-11e8-9ca3-c6c578d89d8e.png)

But **table** seems to use 10+ GiB?

BTW: my machine is ThinkPad T420s with Intel i7 2640M and 16GB of RAM, linux this time is ubuntu (budgie) 18.04.

**Comment by flddr** [comment]
**twose**, btw. if it is easier, its ok if you explain in chinese, google translater does a good job for me to translate to german ;)

**Comment by twose** [comment]
in fact, I try to google translate but I still can hardly understand something you said...
to do my best, I try to explain these:
we have a plan to create a repository in Github and use markdown to write documentation, everyone can pr the repo, and the documentation can also show on the swoole website with the pretty HTML page.

about the swoole_table, maybe you can open a new issue next time.
```
Swoole_table is an ultra-high performance, concurrent data structure based on shared memory and locks. Used to solve multi-process / multi-thread data sharing and synchronization locking problems.
```
and when you use it, you must know the lifecycle of swoole, swoole's worker processes are forked from the main process, so if you create a table before server->start, all of the workers use the same swoole_table, if you create it in `onXXX` event callback, it's equivalent to create many tables on every worker process.
our example:
```php
$table = new swoole_table(1024);
$table->column('fd', swoole_table::TYPE_INT);
$table->column('from_id', swoole_table::TYPE_INT);
$table->column('data', swoole_table::TYPE_STRING, 64);
$table->create();
$serv = new swoole_server('127.0.0.1', 9501);
// here
$serv->table = $table;
$serv->on('receive', function ($serv, $fd, $from_id, $data) {
    $ret = $serv->table->set($fd, array('from_id' => $data, 'fd' => $fd, 'data' => $data));
});
$serv->start();
```

something else, if you can use google translation, you can see [Chinese documentation](https://wiki.swoole.com/) temporarily.

**Comment by flddr** [comment]
@twose why i cannot use more than 25% RAM?

I tried many things, but with this code:

```php
<?php

$table = new swoole_table(1000000);
$table->column('id', swoole_table::TYPE_INT); //1,2,4,8
$table->column('name', swoole_table::TYPE_STRING, 1000);
$table->column('num', swoole_table::TYPE_FLOAT);
$table->create();

$http = new swoole_http_server("127.0.0.1", 9501);

$http->table = $table;

$http->on("request", function ($request, $response) use ($http) {
    
    $http->table->set(...); # ... = data
    
    $response->header("Content-Type", "text/html");
    $response->end();
});

$http->start();

?>
```

i can run `wrk` to about ~500000 rows and as always:

if my **memory usage becomes 25%** it errors `Swoole\Table::set(): unable to allocate memory.` on my 4-core-machine.

So, why didn't i have a **single** table here?

25% seems to be 4 cores x 25% = > 100%.

**Comment by flddr** [comment]
Its curios. My RAM usage is always 25% in gnome-system-monitor.

I can run `wrk` again and again, above 500.000 rows it begins to `Swoole\Table::set(): unable to allocate memory.` but it seems to work for a percentual number of rows - now table is growing decreased, but it grows. I run 43k requests and it inserts about 10k rows now per `wrk`.

It seems, that is 1/4?

Why is everything here about 1/4 or 25%?

I am hanging.

BTW:

```bash
cat /proc/meminfo
MemTotal:       16300516 kB
MemFree:        12042888 kB
MemAvailable:   12807500 kB
Buffers:           73348 kB
Cached:          2579268 kB
SwapCached:            0 kB
Active:          1687012 kB
Inactive:        2305504 kB
Active(anon):    1354556 kB
Inactive(anon):  1660008 kB
Active(file):     332456 kB
Inactive(file):   645496 kB
Unevictable:         152 kB
Mlocked:             152 kB
SwapTotal:       2097148 kB
SwapFree:        2097148 kB
Dirty:               268 kB
Writeback:             0 kB
AnonPages:       1340124 kB
Mapped:          1926136 kB
Shmem:           1674668 kB
Slab:             123196 kB
SReclaimable:      75496 kB
SUnreclaim:        47700 kB
KernelStack:       10096 kB
PageTables:        66080 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    10247404 kB
Committed_AS:    9286560 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:     20480 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      139904 kB
DirectMap2M:    16513024 kB
```

**Comment by flddr** [comment]
@twose 

You wrote:

_we have a plan to create a repository in Github and use markdown to write documentation, everyone can pr the repo, and the documentation can also show on the swoole website with the pretty HTML page._

This is very nice to hear 💯 PLEASE: When deciding tag-format etc. Please check:

a) to print this side easily with a Printer (without broken pages and formatting)

b) to use (google) translator - if you chose **\<pre>** for tags for example those words would **_not_** be translated from original english to target language for example :) Please have a look at this before everything is written; **a automatic translation of language independet words or international naming should be avoided** :) (in H1-H6 etc. too :)

👍 

Actually i am translating your great chinese documents; its very detailed and much stuff 👍

**Comment by flddr** [comment]
BTW: for all who needs documents about swoole, the original chinese documents are really great and massive stuff, from bare metal to code samples

Have for all a look at https://wiki.swoole.com/wiki/index/prid-1 :100: 

I use translation to my language, its very well written and printed about 600 Pages :+1:

**Comment by xingxing1990** [comment]
遇到问题可以添加swoole学习群; 239642717，我们一起交流。

**Comment by doubaokun** [comment]
@flddr please check the document at https://www.swoole.co.uk/docs

**Comment by flddr** [comment]
@doubaokun thanks

> BTW: for all who needs documents about swoole, the original chinese documents are really great and massive stuff, from bare metal to code samples

Just the info for people who are feeling the english documentation is actually not enough :+1:

**Comment by flddr** [comment]
@twose 

> we have a plan to create a repository in Github and use markdown to write documentation, everyone can pr the repo, and the documentation can also show on the swoole website with the pretty HTML page.

What do you think about first public release time? :)

**Comment by hktr92** [comment]
it's may 2020 and me, as an enthusiast about this project, I'm pretty disappointed about the poor documentation in English. Sure, I get the idea of what does what, but here is something I've come across:
- documentation is not 100% straightforward, meaning that i have to experiment with functionality first;
- code examples are a mess. for example, I wanted to implement a pub-sub system for a project of mine and this is what i have found: https://www.swoole.co.uk/article/redis-swoole-pubsub. so I have more questions than answers:
-- how to push a subject to redis for subscribe?
-- how can i wrap `go()` in an OOP-like environment?
-- do I have to ditch OOP for using swoole?
- didn't really found a "migration guide" on synchronous vs async usage (I'd love to migrate some of my projects to use async feats, like redis pub/sub, mysql connector, websockets, http server and workers).

for now, this is the only way of working with swoole is to copy - paste code from documentation, fix it up myself and do the trial-and-error loop to see how swoole works, and it's discouraging newbies that doesn't know / have sufficient experience to work this way.

as a reference, symfony's documentation is clear and pretty straightforward. maybe a "how-to-basic" tutorial / article would be helpful, with explanation of how stuff works, so we can all have a glimpse of how we should work / interact with this project.

**Comment by matyhtf** [comment]
@doubaokun

**Comment by doubaokun** [comment]
> it's may 2020 and me, as an enthusiast about this project, I'm pretty disappointed about the poor documentation in English. Sure, I get the idea of what does what, but here is something I've come across:
> 
> * documentation is not 100% straightforward, meaning that i have to experiment with functionality first;
> * code examples are a mess. for example, I wanted to implement a pub-sub system for a project of mine and this is what i have found: https://www.swoole.co.uk/article/redis-swoole-pubsub. so I have more questions than answers:
>   -- how to push a subject to redis for subscribe?
>   -- how can i wrap `go()` in an OOP-like environment?
>   -- do I have to ditch OOP for using swoole?
> * didn't really found a "migration guide" on synchronous vs async usage (I'd love to migrate some of my projects to use async feats, like redis pub/sub, mysql connector, websockets, http server and workers).

Coroutine and async is new design, the migration is not straight forward.

We will add more examples about these use cases.

> 
> for now, this is the only way of working with swoole is to copy - paste code from documentation, fix it up myself and do the trial-and-error loop to see how swoole works, and it's discouraging newbies that doesn't know / have sufficient experience to work this way.
> 
> as a reference, symfony's documentation is clear and pretty straightforward. maybe a "how-to-basic" tutorial / article would be helpful, with explanation of how stuff works, so we can all have a glimpse of how we should work / interact with this project.

Thanks for the suggestion. We will add more details about the internal and basic dependency knowledge at https://www.swoole.co.uk/docs/

For the correction and question about the functions, please post to the comment section.
