### ISSUE TITLE
Parser protection - just thinking about

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#1922]
In more standard setups of PHP behind a server (apache, nginx, ...) there is the risk, that the PHP parser is dead and server sends the unparsed script to client - so we have to protect.

How about the typical swoole setup? (php run-file.php) Here it's not possible or is the parser a module which can be killed and script could be send somehow?

**Comment by twose** [comment]
Swoole's core is coroutine and high IO performance, Please use nginx to proxy it.

**Comment by flddr** [comment]
Hmm, generally i would like to avoid this :)

There are several kinds of problems by misconfiguration and system failures which ends in serving unparsed php-script-files or directly downloading them by the client, because the misconfiguration of proxy or because php itself is some kind of broken. So, generally, when using php behind a server/proxy, it is needed to protect it against reading usefull information out of those scripts, like DB-Access, Passwords, File-System-Architectur, and so on.

In opposite to this _is_ swoole the php-engine, so i would like to tend to say - a misconfig isn't possible, because there is no config this way _and_ i would like to tend to say, that, if swoole is broken, the php engine itself is broken _and would not work anymore_?

Or is it possible, that the command (with swoole) `php runfile.php` works and serves unparsed content after swoole.so is broken? I do not think that this is possible.

Generally - for my projects - i really see no benefit to proxy swoole by another software. As opposite i would have more software to maintain, to secure against ... and to be care of.

Every system and software can be broken - i see no relevance to protect swoole by another software that can be broken.

And my tests about the power of swoole are fundamenting, that swoole itself is as powerful as nginx (or Golang or Crystal) - if there is a gap of 10% - maybe... I would like to say that the concept of swoole is completely highest performance and IO and a minimum to maintain :+1: 

So, back to my initially question: is the command `php` able to send unparsed files _after_ swoole.so is some kind of broken? :)
