### ISSUE TITLE
Invitation for Slack - whats about gitter?

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#1923]
Maybe, actually swoole team would not invite me - ok :) but i tried yesterday two times and got no Invitation for _slack_ channel?

Whats about a _gitter_ channel? Gitter is sometimes a little bit laggy here and there, but its more kind of contributor-friendly as it is up to date with issues and so on :)

**Comment by twose** [comment]
Emmm, I don't know about it and rarely use these things, we have GFW and work hard...
Maybe you can create and maintain a discussion community and invite us.
