### ISSUE TITLE
Php start up error -  Kali linux

### ISSUE THREAD

**Issue by iampeters** [swoole/swoole-src#1924]
What did i do? 
i followed the online tutorial on your website <kbd>https://www.swoole.co.uk</kbd> on how to install swoole.
after adding <code>extension=swoole.so</code> to php.ini file, and running <code>php -m | grep swoole</code>, this was the output i got:
<code>
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/lib/php/20170718/swoole.so (/usr/lib/php/20170718/swoole.so: undefined symbol: spl_ce_Countable), /usr/lib/php/20170718/swoole.so.so (/usr/lib/php/20170718/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
</code>

i am using swoole 4.0.4 on Kali linux machine with php 7.2

**Comment by flddr** [comment]
For better help might be title including Kali linux better - i never had this on ubuntu. Kali is debian? Hmm

**Comment by twose** [comment]
if you use `--enable-asan` ?
if Y: disable it.

**Comment by flddr** [comment]
@iampeters did you solve your issue? Are you running _swoole_ now? :)

**Comment by qq447665722** [comment]
![image](https://user-images.githubusercontent.com/14967427/47343421-9839b980-d6d8-11e8-833b-dbe449ee55ff.png)
4.2.3安装后就出现楼主的问题,安装swoole 4.2.2没问题 @twose
