### ISSUE TITLE
New community channel on gitter

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#1925]
Hello everyone,

for all who are interested in talking about swoole on gitter:

https://gitter.im/swoole-php-community/Lobby#

Please join - its just to talk about this awesome swoole :100:

**Comment by twose** [comment]
emmm, we have [gitter](https://gitter.im/swoole/swoole-src?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by flddr** [comment]
Uuups - nice :)

Seems i have misunderstood https://github.com/swoole/swoole-src/issues/1923#issuecomment-416954351
