### ISSUE TITLE
Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0

### ISSUE THREAD

**Issue by woody712** [swoole/swoole-src#1927]
swoole 4.04
php 7.2

Note: 

> The $php_errormsg variable is created in the local scope whenever a non-fatal error is thrown, if the track_errors ini setting is enabled (disabled by default) and the error has not been consumed by an error handler.

> Apart from being ini-dependent language behavior, this behavior is highly magic and the error_get_last function provides a cleaner way of retrieving the last error. Since PHP 7 additionally the error_clear_last function is available, thus covering the last possible use-cases for $php_errormsg without magic scope manipulation.

Hope helpful for u

**Comment by twose** [comment]
I can't understand it, Deprecated warning about track_errors? check your code.

**Comment by woody712** [comment]
Yep

I think it cause by my PHP version, it's too new

**Comment by flddr** [comment]
Not to new for swoole ;)

**Comment by woody712** [comment]
Actually, I use swoole as a http server,  and set the property "log_level".
whenever I set 0 or 5, there is no any logs, and reports this warning.

**Comment by twose** [comment]
what too new? I use `PHP7.4-dev` without any problem.
please show your code and reduce our communication cost.
