### ISSUE TITLE
Where is a forum for ask something about swoole ? 

### ISSUE THREAD

**Issue by evgeniy123** [swoole/swoole-src#1929]
Where is a forum for ask something about swoole ?

**Comment by flddr** [comment]
They are answering every question here daily :)

There are some chatrooms, look at https://github.com/swoole/swoole-src/issues/1925#issuecomment-417242934 for gitter.

**Comment by doubaokun** [comment]
Please join the slack if any questions about how to use Swoole: https://www.swoole.co.uk/community Or submit feature requests or bug reports at the GitHub.

**Comment by flddr** [comment]
@doubaokun i tried the slack now 4 times in 4 weeks - i personally got no answer / invite to the slack channel ? :confused:
