### ISSUE TITLE
PHP5.5.17 pecl upgrade 升级失败

### ISSUE THREAD

**Issue by huangxiaoye** [swoole/swoole-src#193]
PHP 5.5.17-1~dotdeb.1 (cli) (built: Sep 19 2014 02:19:26) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
系统：debian7.1
这个环境下执行 pecl upgrade swoole 报错了如下：
libtool: compile: cc -I. -I/tmp/pear/temp/swoole -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/include -I/tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/main -I/tmp/pear/temp/swoole -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /tmp/pear/temp/swoole/swoole_http.c -fPIC -DPIC -o .libs/swoole_http.o
/bin/bash /tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/libtool --mode=compile cc -I. -I/tmp/pear/temp/swoole -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/include -I/tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/main -I/tmp/pear/temp/swoole -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /tmp/pear/temp/swoole/src/core/Base.c -o src/core/Base.lo
libtool: compile: cc -I. -I/tmp/pear/temp/swoole -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/include -I/tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/main -I/tmp/pear/temp/swoole -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /tmp/pear/temp/swoole/src/core/Base.c -fPIC -DPIC -o src/core/.libs/Base.o
/tmp/pear/temp/swoole/src/core/Base.c:17:20: fatal error: swoole.h: No such file or directory
compilation terminated.
make: *** [src/core/Base.lo] Error 1
ERROR: `make' failed

**Comment by betashepherd** [comment]
pecl确实会失败，推荐使用源码编译安装。

huangxiaoye <notifications@github.com>编写：

**Comment by huangxiaoye** [comment]
你们不打算解决这个问题吗？

**Comment by matyhtf** [comment]
这是1.7.9版本的BUG， 在1.7.10版本已修复。
你可以这样来安装升级：
```
pecl download swoole
tar xvf swoole-1.7.9.tgz
cd swoole-1.7.9
phpize
./configure
make && make install
```
