### ISSUE TITLE
task进程里的定时器被推迟执行

### ISSUE THREAD

**Issue by goldfishhomes** [swoole/swoole-src#1930]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

在单task中投递3次swoole_timer_after定时器，执行顺序，（1）执行15秒，（2）执行2秒，（3）当2秒定时器执行后，在投递一次2秒的定时器

2. What did you expect to see?

第三次定时器，在2秒的时候被执行

3. What did you see instead?

第三次的定时器，没有在2秒的时候执行，而是根据15秒的定时器剩余多少时间执行被推迟

4. What version of Swoole are you using (`php --ri swoole`)?

4.0.2

5. What is your machine environment used (including version of kernel & php & gcc) ? 

Linux version 2.6.32-696.6.3.el6.x86_64 (mockbuild@c1bl.rdu2.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) )

PHP 7.1.18 (cli) (built: Jun  2 2018 07:10:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

6. If you are using ssl, what is your openssl version?

N/A

![tim 20180831094058](https://user-images.githubusercontent.com/19575019/44888277-d501b980-ad02-11e8-844d-cb7c6e6e9a22.png)
![tim 20180831094757](https://user-images.githubusercontent.com/19575019/44888306-f95d9600-ad02-11e8-9e36-b37f9d1f75b6.png)

**Comment by twose** [comment]
能否提供可直接复现的代码, 减轻我们的工作负担

**Comment by LeoYang90** [comment]
代码不够全，猜测是你第一个 2s 时，不只是设定下一个 2s，还执行了其他操作
