### ISSUE TITLE
[4.1.0] broken build, missing files in pecl archive

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#1931]
```
/dev/shm/BUILD/php-pecl-swoole4-4.1.0/NTS/swoole_client_coro.cc:18:10: fatal error: socket.h: No such file or directory
 #include "socket.h"
          ^~~~~~~~~~
compilation terminated.

```

**Comment by remicollet** [comment]
Missing
* include/socket.h
* include/channel.h
* src/coroutine/socket.cc

**Comment by twose** [comment]
So sorry about this, I forgot to verify the pecl package, I post a new version 4.1.1 for PECL package, thank you very much, I will add a build test script for PECL to prevent recurrence.
