### ISSUE TITLE
swoole_http_client free 错误

### ISSUE THREAD

**Issue by fjmygame** [swoole/swoole-src#1934]
Please answer these questions before submitting your issue. Thanks!

1. 
*** Error in `demo_http': free(): invalid pointer: 0x00007f6c2c430a00 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c619)[0x7f6c3eab8619]
/usr/lib64/php/modules/swoole.so(swHashMap_add_int+0x24c)[0x7f6c3715525c]
/usr/lib64/php/modules/swoole.so(+0x66aa1)[0x7f6c37171aa1]
/usr/lib64/php/modules/swoole.so(+0x5cee3)[0x7f6c37167ee3]
/usr/lib64/php/modules/swoole.so(+0x3f635)[0x7f6c3714a635]
/usr/lib64/php/modules/swoole.so(+0x40281)[0x7f6c3714b281]
zombie_gs49_http(dtrace_execute_internal+0x2b)[0x55c4fbb9d2eb]
zombie_gs49_http(+0x335394)[0x55c4fbc57394]
zombie_gs49_http(execute_ex+0x38)[0x55c4fbbeb698]
zombie_gs49_http(dtrace_execute_ex+0x79)[0x55c4fbb9d1c9]
zombie_gs49_http(+0x335849)[0x55c4fbc57849]
zombie_gs49_http(execute_ex+0x38)[0x55c4fbbeb698]
zombie_gs49_http(dtrace_execute_ex+0x79)[0x55c4fbb9d1c9]
zombie_gs49_http(+0x335849)[0x55c4fbc57849]
zombie_gs49_http(execute_ex+0x38)[0x55c4fbbeb698]
zombie_gs49_http(dtrace_execute_ex+0x79)[0x55c4fbb9d1c9]
zombie_gs49_http(zend_call_function+0xb1f)[0x55c4fbb9efcf]
zombie_gs49_http(call_user_function_ex+0x5f)[0x55c4fbb9f1cf]
/usr/lib64/php/modules/swoole.so(+0x2c56c)[0x7f6c3713756c]
/usr/lib64/php/modules/swoole.so(+0x56069)[0x7f6c37161069]
/usr/lib64/php/modules/swoole.so(php_swoole_event_wait+0x54)[0x7f6c37137734]
/usr/lib64/php/modules/swoole.so(php_swoole_process_start+0x1b5)[0x7f6c3713cf85]
/usr/lib64/php/modules/swoole.so(swManager_spawn_user_worker+0x107)[0x7f6c3716f037]
/usr/lib64/php/modules/swoole.so(swManager_start+0x7d3)[0x7f6c3716f863]
/usr/lib64/php/modules/swoole.so(+0x529e2)[0x7f6c3715d9e2]
/usr/lib64/php/modules/swoole.so(swServer_start+0x2a3)[0x7f6c37165113]
/usr/lib64/php/modules/swoole.so(zim_swoole_server_start+0x8b)[0x7f6c3712ce7b]
zombie_gs49_http(dtrace_execute_internal+0x2b)[0x55c4fbb9d2eb]
zombie_gs49_http(+0x335394)[0x55c4fbc57394]
zombie_gs49_http(execute_ex+0x38)[0x55c4fbbeb698]
zombie_gs49_http(dtrace_execute_ex+0x79)[0x55c4fbb9d1c9]
zombie_gs49_http(+0x335849)[0x55c4fbc57849]
zombie_gs49_http(execute_ex+0x38)[0x55c4fbbeb698]
zombie_gs49_http(dtrace_execute_ex+0x79)[0x55c4fbb9d1c9]
zombie_gs49_http(zend_execute_scripts+0x18b)[0x55c4fbbaff7b]
zombie_gs49_http(php_execute_script+0x282)[0x55c4fbb4aca2]
zombie_gs49_http(+0x3372a8)[0x55c4fbc592a8]
zombie_gs49_http(+0xbcaba)[0x55c4fb9deaba]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f6c3ea5dc05]
zombie_gs49_http(+0xbcb55)[0x55c4fb9deb55]

2. What version of Swoole are you using (`php --ri swoole`)?

swoole support => enabled
Version => 1.9.23
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
jemalloc => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 
PHP 5.6.37 (cli)
gcc version 4.8.5 20150623

6. If you are using ssl, what is your openssl version?

3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by twose** [comment]
PHP5请升级到异步最新版1.10.5再提交issue, swoole最新版已移除PHP5支持

**Comment by fjmygame** [comment]
1.10.5 要升级到 php7?
