### ISSUE TITLE
please explain: what happens to a global var++ in swoole_http_server?

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#1942]
With this code

```php
<?php

$http = new swoole_http_server("127.0.0.1", 9501);

$i = 0;

$http->on("start", function ($server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$http->on("request", function ($request, $response) {

        global $i;
        $response->header("Content-Type", "text/plain");
        #$response->header("Connection", "close"); // changes nothing; not due to keep-alive
        $response->end("request counter: " . $i++);

    });

$http->start();

?>
```
and tens of testing methods, `$i` is incremented arbitrarily (feels like).

1.) Is there a way like this to use a global var directly in `$http->on("request", function ($request, $response)`?
2.) What happens in the code above with `$i`? Who does the `$i++` up to 30% of requests?

:)

**Comment by flddr** [comment]
By the way, i guess its done in main coroutine, but why changes keep-alive / "Connection: close" not the number it is incremented all in all? There must be a way to recognize every single request which is not keep-alive? :)

**Comment by twose** [comment]
if your `worker_num` is not `1`, please not use global var.

**Comment by flddr** [comment]
Ok, thank you 谢谢 :)
