### ISSUE TITLE
websocketServer出现The UDP connection_info is deprecated, use onPacket instead

### ISSUE THREAD

**Issue by Sanit1** [swoole/swoole-src#1945]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
我使用websocketServer来做一个轻型的IM 主要代码如下
```
$server = new \swoole_websocket_server("127.0.0.1", 9501);
$server->on('message', [$this, 'onMessage']);
public function onMessage(\swoole_websocket_server $server, $frame){
$pushToFd = $frame->fd;
$connectionInfo = $server->connection_info($pushToFd);
}
```
正常运行了一段时间 最近一直报
` Swoole\Server::connection_info(): The UDP connection_info is deprecated, use onPacket instead.`

但是websocket服务是正常的 也是能推的

2. What did you expect to see?
没有报错

3. What did you see instead?

只要代码运行到connection_info那段代码 一直报
` Swoole\Server::connection_info(): The UDP connection_info is deprecated, use onPacket instead.`

4. What version of Swoole are you using (`php --ri swoole`)?
swoole 2.1.1

5. What is your machine environment used (including version of kernel & php & gcc) ? 
php 7.1.16

Linux version 3.10.0-693.2.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) )

gcc version 4.8.5

6. If you are using ssl, what is your openssl version?

使用的是nginx代理了一层  没用ssl

**Comment by Sanit1** [comment]
我重启了下，这个错误没在出现了
我看了下文档，1.9.1以后移除了udp的connection_info
假设是一个udp的fd是不是就会报这样的错
我先close吧，等我能复现这个错误的时候我再open

**Comment by jiqinwj** [comment]
我也是 
![image](https://user-images.githubusercontent.com/16432577/57874720-d4369680-7843-11e9-8201-941bcbe18cba.png)
