### ISSUE TITLE
没人反映swoole_http_server的ws问题么

### ISSUE THREAD

**Issue by yahveh** [swoole/swoole-src#195]
群里反映一直被刷没，
就是chrome下经常会出现
WebSocket connection to 'ws://127.0.0.1:9501/' failed: Error during WebSocket handshake: Incorrect 'Sec-WebSocket-Accept' header value
刷新的时候原来的连接也不会立马关闭，关闭当前页面才会关闭当前页面刷新堵塞的所有连接。

而自定义 handshake 就没有这种问题

另外自定义handshake后刷新页面，会出现先创建连接再关闭旧的连接的问题：
log输出大致情况如下，
［打开页面］
1、10 fd connect open
［刷新］
2、11 fd connect open
3、10 fd connect close
［刷新］
4、10 connect open
5、11 connect close
...
疑惑，不应该先关闭再打开么？

**Comment by matyhtf** [comment]
Fixed. 在最新的代码中已经修复此BUG

**Comment by ruandao** [comment]
求教下，这个bug 的算法是怎样的？
我这边计算`Sec-WebSocket-Accept` 的时候，是 `base64(sha1(Sec-Websocket-Key + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11")`
但是提示这个错误，应该是我算法写错了。。。
```

   4.  If the response lacks a |Sec-WebSocket-Accept| header field or
       the |Sec-WebSocket-Accept| contains a value other than the
       base64-encoded SHA-1 of the concatenation of the |Sec-WebSocket-
       Key| (as a string, not base64-decoded) with the string "258EAFA5-
       E914-47DA-95CA-C5AB0DC85B11" but ignoring any leading and
       trailing whitespace, the client MUST _Fail the WebSocket
       Connection_.
```
