### ISSUE TITLE
minimum core swoole PHP deps on linux (ubuntu), not WSL

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#1950]
I am very big friend of minimal installation; what are minimum deps on linux / ubuntu?

This is from your great chinese docs for Windows WSL install a recommendation?

php7.0
php7.0-curl
php7.0-gd
php7.0-gmp
php7.0-json
php7.0-mysql
php7.0-opcache
php7.0-readline
php7.0-sqlite3
php7.0-tidy
php7.0-xml
php7.0-bcmath
php7.0-bz2
php7.0-intl
php7.0-mbstring
php7.0-mcrypt
php7.0-soap
php7.0-xsl
php7.0-zip

**Can i try to just let** `pecl install swoole` **work or become runtime-errors possible?**

Is needed to install `php-mysql` even if i use postgres or sqlite or swooles own mysql async version?

So i just want to know swoole core dependencies without my own php needs :)

**Comment by twose** [comment]
PHP7.0 and above can work properly with all of the standard extensions.
We have Travis CI tests here:
https://travis-ci.org/swoole/swoole-src/
![image](https://user-images.githubusercontent.com/25978241/45026248-4da0a700-b070-11e8-91e1-bc9eb0e82d58.png)

Some exts use global vars so we can't use it in swoole:
- xdebug
- phptrace
- aop
- molten
- xhprof

Some operation are blocked IO we can't use it in swoole:
* mysql、mysqli、pdo and others (without \Swoole\Runtime::enableCoroutine)
* sleep、usleep
* curl
* stream、socket
* swoole_client sync mode
* memcache、redis
* file_get_contents/fread
* swoole_server->taskwait
* swoole_server->sendwait

But we can use these:
* swoole\coroutine\client
* swoole\coroutine\mysql
* swoole\coroutine\redis
* swoole_timer_tick/swoole_timer_after
* swoole_event
* swoole_table/swoole_atomic/swoole_buffer
* swoole_server->task/finish
* swoole\coroutine\util (include some file operation functions)

**Comment by flddr** [comment]
@twose thank you, i just want to install libs / extensions **_as minimum as possible_** (fitting my own needs), so, if `pecl install swoole` works is everything ok then or later unknown runtime-errors? I just want to have the **minimalest setup** :)

**Comment by twose** [comment]
my poor English.. every option you choose no in pecl or you `make` with empty `./configure` is minimalist setup.

**Comment by flddr** [comment]
You are doing great work on swoole!

Everything is fine, i will try :+1:

**Comment by flddr** [comment]
I tried on a new virtual machine, on ubuntu 18.04 minimal setup for swoole on PHP 7.2.x was

```bash
apt install php php-pear php7.2-dev
pecl install swoole
```

(`sudo`), to _compile_ correct 👍 

but this evening i have no time to test for runtime-errors. I will make a notice here if there comes somewhat next weeks.

`php` is ubuntu package for newest PHP 7.x (since 18.04 standard)
`php-pear` provides `pecl`
`php7.2-dev` compiling dependencies

( @twose :)

**Comment by ClosetMonkey** [comment]
I understand your confusion. Http/2 requires and additional ext, mysql requires an additional ext, etc etc. I have the same basic question (not meaning to highjack the thread, I will start a new issue if not the same). What is the minimal PHP extension requirements and PHP configuration for a minimum swoole build?
