### ISSUE TITLE
https://wiki.swoole.com/wiki/page/326.html

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#1951]
Sorry, another question today:

You wrote:

swoole_http_server对Http协议的支持并不完整，建议仅作为应用服务器。并且在前端增加Nginx作为代理

Is this work-in-progress or complete as is? Actually this is exact my way - i just want a http parser as is in swoole and write my own handler logic, like

```php
if ($request->server['request_uri'] == '/test.txt')
    {
        $last_modified_time = filemtime(__DIR__ . '/test.txt');
        $etag = md5_file(__DIR__ . '/test.txt');
        // always send headers
        $response->header("Last-Modified", gmdate("D, d M Y H:i:s", $last_modified_time) . " GMT");
        $response->header("Etag", $etag);
```

**Will this stay in future?** Because i want to have the possibilities for doing exactly as i want (like _your example_ above) for the things i really need (_not_ automatic) ;)

**Comment by huangzhhui** [comment]
@flddr I just worte this in zend-expressive-swoole project, https://github.com/zendframework/zend-expressive-swoole/blob/master/src/StaticResourceHandler/ETagMiddleware.php reference for you

**Comment by twose** [comment]
your code is ok (except some blocked IO file functions)
the saying means you have better use Nginx to proxy it. 
for example, the client sent a wrong package (Not fully compliant with the protocol) missed one space,  nginx may fix it, but swoole maybe not.
Now Swoole's core is `coroutine`,  to resolve high-concurrency requirements.
If you want to in-depth design it, you can use TCP server/client.

**Comment by flddr** [comment]
@twose oh, this is old from your examples, i guess https://github.com/swoole/swoole-src/blob/master/examples/http/server.php

**For me is just for interest doing this myself today and futre** and _not automatic handling by server_ (because all done are my ressources and response) :)

```php
$last_modified_time = filemtime(__DIR__ . '/test.txt');
$etag = md5_file(__DIR__ . '/test.txt');
// always send headers
$response->header("Last-Modified", gmdate("D, d M Y H:i:s", $last_modified_time) . " GMT");
        $response->header("Etag", $etag);
```

@huangzhhui thank you very much i will look at this :+1:

**Comment by flddr** [comment]
My intention was to say: i like the swoole http parser because it does the base stuff, like parsing request and cookies, but headers etc. in response i like to do myself because i have control about it :) So, when swoole would change this to automatic, i have less control

:)

@huangzhhui thanks for sharing great work :+1:

**Comment by flddr** [comment]
Ok, i will close this issue - i am just hoping in future the swoole_http_server would let this on my side instead of doing it automatic without good control (like other webservers which do to much stuff by themself)

swoole_http_server as is 💯 

:)
