### ISSUE TITLE
Bad file roles

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#1954]
Noticed in 4.1.2 some files have strange role.

* `.github` directory is github specific, no need to be in package, especially as installed in a hiddent directory
* everything in `tests` directory, and needed to run test suite should have `role="test"` (installed in dedicated test directory)
* CMakeList.txt should have `role="src" `(not documentation)

**Comment by twose** [comment]
are there any pecl tools to do these? how can I see about these details?
thanks.

**Comment by remicollet** [comment]
> are there any pecl tools to do these?

Sorry, AFAIK: no

> how can I see about these details?

There is no strict rules, only common practices.

**Comment by twose** [comment]
Thanks, I thought you find these problems without your eyes before...
I have fixed the problems what you said.
