### ISSUE TITLE
Async http client header "content-length" can't be 0

### ISSUE THREAD

**Issue by s890510** [swoole/swoole-src#1955]
$client = new swoole_http_client(...)
$client->setHeaders($header = array(
    'Content-Type' => 'text/plain; charset=UTF-8',
    'Content-Length' => 0
));
$client->setMethod('PUT');
$client->execute(...)

上面寫法在v4.0.4 Coroutine\Http\Client 是可以正常執行 (發送到對方Server是可以正常運作)，
不過在切換成swoole_http_client後就會有問題...

由於目標Server有設定必須採用PUT模式且Content-length必須設定為0 

目前是嘗試在swoole_http_client.c  1164行附近加入
http_client_append_content_length(http_client_buffer, 0);
#1957 

不知是否有更好的解法呢？

**Comment by s890510** [comment]
都沒有其他的方法嗎....?

**Comment by twose** [comment]
这个问题源于#1915
看了一下的确是需要这样解决, 可以理解为底层不接受Content-Length的值防止错误的长度输入但接收其作为启用开关, 增加content_length的函数会自动添加`\r\n\r\n`所以你的代码其实是有问题的, 感谢贡献!

**Comment by s890510** [comment]
原來如此！難怪覺得哪裡怪怪的！
感謝 :)
