### ISSUE TITLE
Swoole coroutine 协程: Cannot access private property

### ISSUE THREAD

**Issue by SolitudeSword** [swoole/swoole-src#1958]
[demo.zip](https://github.com/swoole/swoole-src/files/2356249/demo.zip)

源码比较长，大约300来行，就放附件了

执行脚本的方式是```php demo.php 0 9999```，其中`0`表示完全用协程版的`Swoole\Coroutine\Http\Client`实现http请求，`1`表示中间穿插了一个异步查询DNS的过程，最后的`9999`表示启用的Server端口号，复现时自行传入即可

脚本的大致逻辑如下：
- 开一个子进程，在子进程中启动一个TCP服务器
- 主进程2秒后启动客户端去连接子进程的服务器，发去消息
- 子进程接收到数据到用协程发两个http请求，并回复客户端
- 主进程收到数据后，结束子进程的服务

前几天根据比较旧的文档，使用协程的http客户端，会结合异步函数`Async::dnsLookup`查询DNS，有大约0.14%的概率出段错误，（这个逻辑就是脚本的第一个参数传1时执行）

经开发团队的指点，了解到协程和异步相关代码是不可以混用的，所以使用了完全的协程版本，去除了`Async::dnsLookup`的调用（即脚本的第一个参数传0），这时神奇的发现脚本报错了：
```
Fatal error: Uncaught Error: Cannot access private property RecieveCallback::$server in demo.php:182
```
第182行的代码是
```php
$this->server->send($fd, $sendData);
```

这个确实不理解了，不知道是BUG还是说禁止这么写？因为`$this`不可以用自己的私有变量确实有点颠覆我对PHP的理解了 :sweat_smile:

相关环境：
- PHP 7.0.24
- Swoole 依次尝试过4.0.0、4.0.3、4.0.4、4.1.0.beta2、4.1.0、4.1.2
- gcc 4.8.2
- Linux cluster180 2.6.32-573.el6.x86_64 #1 SMP Thu Jul 23 15:44:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by twose** [comment]
你这个脚本我运行了什么也没发生
你可以提取出来模拟下问题, 看看在你机子上是否能复现
```php
<?php

namespace private_in_go;

class test
{
    private $foo = 'ok';

    public function foo()
    {
        try {
            go(function () {
                \co::sleep(.001);
                var_dump($this->foo);
            });
        } catch (\Exception $e) {

        }
    }
}

$test = new test();
$test->foo();
```

**Comment by SolitudeSword** [comment]
目前我还没办法很简单的demo复现这个问题，我刚刚又运行了一次我提交的demo.php，输出如下：

```
2018-09-07 12:37:20.4694	3562	waiting server start 2 second
2018-09-07 12:37:22.4703	2003	key = baidu
2018-09-07 12:37:22.4707	4867	baidu:www.baidu.com
2018-09-07 12:37:22.4708	3862	baidu getting...
2018-09-07 12:37:22.4711	1674	key = weibo
2018-09-07 12:37:22.4712	2245	weibo:weibo.com
2018-09-07 12:37:22.4712	717	weibo getting...
2018-09-07 12:37:22.4963	4892	baidu over
2018-09-07 12:37:22.4963	1371	baidu code = 200 body len = 13987
2018-09-07 12:37:22.4964	4298	baidu pop done
2018-09-07 12:37:22.5238	2407	weibo over
2018-09-07 12:37:22.5238	2164	weibo code = 301 body len = 276
2018-09-07 12:37:22.5238	1585	weibo pop done
2018-09-07 12:37:22.5239	2217	send data len = 15134
PHP Warning:  Swoole\Client::recv(): recv() failed. Error: Resource temporarily unavailable [11] in demo.php on line 38

Warning: Swoole\Client::recv(): recv() failed. Error: Resource temporarily unavailable [11] in demo.php on line 38
2018-09-07 12:37:23.4697	2465	recv len = 0
[2018-09-07 12:37:23 #4148.2]	NOTICE	Server is shutdown now.
```

虽然没有报之前那个，但是recv不应该没数据的，因为send已经执行到了，如果把$server改为public就没这个问题


我周末抽空尝试下用类似于上面的简易demo复现这个问题吧

**Comment by SolitudeSword** [comment]
完成了，下面的代码只有20行了，在我机器上是稳定复现的

```php
<?php

namespace private_in_go;

use Swoole\Coroutine\Http\Client;

(new RecieveCallback())->onRecieve();

class RecieveCallback
{
    private $private = 10;
    public $public = 15;

    public function onRecieve()
    {
        go(function () {
            $domain = "www.baidu.com";
            $cli = new Client($domain, 80);
            $cli->setHeaders(["Host" => $domain]);
            $cli->get("/");  # 如果注释掉这一句就不会报错了
        });

        go(function () {
            var_dump("public = {$this->public}");
            var_dump("private = {$this->private}");
        });
    }
}
```

运行情况，第一次执行是不注释get的，第二次是注释的，排除掉Chan了 @twose 
```
[vijay@cluster]$ php tinyDemo.php
string(11) "public = 15"
PHP Fatal error:  Uncaught Error: Cannot access private property private_in_go\RecieveCallback::$private in tinyDemo.php:25
Stack trace:
#0 {main}
  thrown in tinyDemo.php on line 25

Fatal error: Uncaught Error: Cannot access private property private_in_go\RecieveCallback::$private in tinyDemo.php:25
Stack trace:
#0 {main}
  thrown in tinyDemo.php on line 25

[vijay@cluster]$ php tinyDemo.php
string(11) "public = 15"
string(12) "private = 10"

```

**Comment by liuyibao** [comment]
闭包应该用use传进来吧， func() use $ext {}

**Comment by SolitudeSword** [comment]
那为什么public的字段可以访问，为什么不用协程的Client时没有问题（示例代码可以参考twose写，也可以把我的代码中第一个go函数去掉）

从我自己测试的结果来说，$this是不需要use的

@twose 我知道为什么你没复现了，我自己换了PHP7.1也没问题了，看来是7.0和swoole结合后出现的一个问题，看来我们项目升级PHP成为一定要做的事了

**Comment by twose** [comment]
@liuyibao $this是不需要use引入的
@SolitudeSword 确认了一下的确有这个问题, 可能PHP内核在这一部分有改动, 协程切换没有切换到

**Comment by xingxing1990** [comment]
到问题可以添加swoole学习群; 239642717，我们一起交流。

**Comment by twose** [comment]
> (get rid of EG(scope))[https://github.com/php/php-src/commit/6499162ff0d8aa6e862d3e3cdd2288b87636b8a1]
在PHP7.1及以上版本官方重构了EG(scope)相关代码, 把该部分切换通过其他方式优化掉了, 所以PHP70中需要做额外处理来兼容PHP70的scope切换
在 23cf12d 修复了此问题, 修改issue标题以便于他人检索.
