### ISSUE TITLE
src/core/channel.c 源码疑似会引起内存越界

### ISSUE THREAD

**Issue by LeoYang90** [swoole/swoole-src#1960]
![image](https://user-images.githubusercontent.com/16485583/45251544-9c08bb00-b37a-11e8-86e3-f178553d8f16.png)

请问这个源码中，如果 `object->tail >= object->size` 的话， `memcpy` 不会内存越界吗，`free` 的时候会引起崩溃吧，请大佬解惑

**Comment by xianqiangzhao** [comment]
这个问题我也发现了，
测试代码：

//chan1
$chan = new Swoole\Channel(8192); 
$chan->push(str_repeat('A',8100));
$chan->push(str_repeat('B',8100));

//chan2
$chan1 = new Swoole\Channel(8192);
$chan1->push(str_repeat('C',8100));
$chan1->push(str_repeat('D',8100));
 

var_dump( $chan->stats());
var_dump( $chan1->stats());
echo $chan->pop();
 运行结果
![image](https://user-images.githubusercontent.com/26996795/45259443-d49ea800-b3ff-11e8-9001-b06a0fcdc86a.png)

**Comment by LeoYang90** [comment]
`channel` 是 `worker` 进程和 `manager` 进程之间进行通信的重要数据结构，有没有人来看下啊

**Comment by xianqiangzhao** [comment]
其实我的解决办法是，
1，内存不够用时，自动扩容。
2，或者内存不够用时报错（有点不太友好）。

**Comment by LeoYang90** [comment]
这是个环形内存数据结构，你怎么扩容呢，新建一个 `channel` 嘛

**Comment by LeoYang90** [comment]
我上面贴的不就是源码吗？它并不是一个链表，是一个环形的内存表，结构类似于 `swoole` 共享内存的 `ring_buffer`，线线结构是啥？

**Comment by xianqiangzhao** [comment]
没有看出来“环形的内存表”，有head ，有tail的结构，数据存入就移动相应的指针（head  增大）。
head > tail 时， head = 0 ，从头在存储。

**Comment by LeoYang90** [comment]
你这个就已经是环形结构了，并不是一定 `tail` 和 `head` 的地址一致才是环形，还有你说的逻辑有问题：插入数据是 `tail` 增大，当 `tail` 比预定的 `size` 还要大的时候，`tail` 置 0；`pop` 数据是 `head` 增大，当 `head` 比预定的 `size` 还大的时候，`head` 置 0

**Comment by LeoYang90** [comment]
多谢韩老大

**Comment by xianqiangzhao** [comment]
@LeoYang90  谢谢！我刚又仔细看了，确实如你说的。
 韩老大的修改方法是申请是多申请了8K的内存。
如果我存放的数据大于8k 呢？原来 数据量大(大于8k)的话就会写入临时文件（php_swoole_task_pack->swTaskWorker_large_pack函数）
这个修改很妙！

**Comment by matyhtf** [comment]
最初设计就有溢出空间的逻辑，就是解决这种情况下，可以直接写入而且不会内存溢出的。

可能在重构的过程中，删除了这个代码，导致出现。

**Comment by LeoYang90** [comment]
哪里有 8k 啊？韩老大不是加了个 maxlen 么，这个是用 `swChannel_new` 时候设置的

**Comment by xianqiangzhao** [comment]
@LeoYang90    
实例化时
1， swChannel *chan = swChannel_new(size, SW_BUFFER_SIZE_STD, SW_CHAN_LOCK | SW_CHAN_SHM);

2，函数 swChannel* swChannel_new(size_t size, int maxlen, int flags)
   第二个参数是SW_BUFFER_SIZE_STD
  定义是   #define SW_BUFFER_SIZE_STD         8192

**Comment by LeoYang90** [comment]
ok 了解了，我看的是 worker 这里
