### ISSUE TITLE
异步task是否可以解决IO阻塞, 提升性能

### ISSUE THREAD

**Issue by shehuaqigai** [swoole/swoole-src#1964]
swoole1.10.4,centos7.4
在worker中投递了一个task,task里需要连接数据库做处理，压测发现，吞吐量与不用task是一样的，调试发现task确实是达到异步效果了，但是感觉task阻塞了worker的进程，等task干完,worker才响应，文档上说mysql连接是同步阻塞的，不能理解的是，难道不是每个进程里面的数据操作同步阻塞吗，怎么会影响到别的进程呢？这是一个迁移项目,如果使用异步mysql，这基本等于推到重来，有什么方式能达到丢到task里面的数据操作不影响worker的直接响应

**Comment by twose** [comment]
你这么搞当然没什么提升了, task进程是阻塞的, 所以它还是会长时间占用CPU, 尤其是在你核数少的时候, worker也会被阻塞
而且你所有请求都有阻塞IO的话, 就算你扔到task, worker省出来的CPU时间也干不了别的事情, 只能等task返回数据, 吞吐量当然没有变化, 加上进程间的数据传输消耗, 反而比同步写法更慢
除非你用协程/异步重构, 否则这种异步模式只是自己骗自己

**Comment by twose** [comment]
长连接只能解决频繁建立连接的CPU占用开销, 往task里丢任务马上返回也不过是后台任务模式, 如果像你想的这么简单就能无缝实现异步高性能....那就不用再搞什么协程了...

**Comment by LeoYang90** [comment]
简单粗暴的方法就是服务器加核加内存，然后提高 worker 和 tasker 的数量，提高并行的效率

**Comment by shehuaqigai** [comment]
今天对个别接口采用了swoole的异步mysql,结果让人沮丧，测试发现，没什么改善

**Comment by twose** [comment]
@shehuaqigai 大概率是你没理解, 写的不对.
