### ISSUE TITLE
swoole <=> ArangoDB ?

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#1965]
Short Question - i have no experience with, but does someone know the if and how about using ArangoDB with swoole? Or future plans from swoole?

**Comment by flddr** [comment]
No need to talk about ;)

**Comment by matyhtf** [comment]
ArangoDB uses the HTTP protocol to implement the client based on swoole_http_client.

**Comment by flddr** [comment]
@matyhtf thanks, my thoughts :+1: ArangoDB with coroutines could be interesting
