### ISSUE TITLE
redis subscribe回调函数调用swoole_process

### ISSUE THREAD

**Issue by zhang-bin** [swoole/swoole-src#1968]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
    请问在$redis->subscribe的回调函数里面是否可以使用swoole_process来创建和销毁进程？

2. What did you expect to see?

3. What did you see instead?
  我自己试验下来的情况，能创建，但是结束不了.

4. What version of Swoole are you using (`php --ri swoole`)?
4.0.4

5. What is your machine environment used (including version of kernel & php & gcc) ? 
mac os x 10.13.6
PHP 7.2.9
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

6. If you are using ssl, what is your openssl version?
没用

**Comment by matyhtf** [comment]
使用 swoole_prcocess::wait 回收子进程，或者使用 `pcntl_signal(SIGCHLD, SIG_IGN)` 忽略子进程退出。
