### ISSUE TITLE
make test does not complete

### ISSUE THREAD

**Issue by grikdotnet** [swoole/swoole-src#1972]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

I compiled swoole against 7.3

2. What did you expect to see?

test results

3. What did you see instead?

FAIL swoole_mysql_coro: reset test mysql database [tests/swoole_mysql_coro/z_reset.phpt]
SKIP swoole_process: exec [tests/swoole_process/process_exec.phpt] reason: if no python
FAIL swoole_process: sysv msgqueue [tests/swoole_process/process_msgqueue.phpt]
FAIL swoole_process: push [tests/swoole_process/process_push.phpt]
PASS swoole_process: select [tests/swoole_process/process_select.phpt]
PASS swoole_process: signal [tests/swoole_process/signal.phpt]
PASS swoole_process: close [tests/swoole_process/swoole_process_close.phpt]
PASS swoole_process: ctor [tests/swoole_process/swoole_process_ctor.phpt]
Killed02/430 [tests/swoole_process/swoole_process_deamon.phpt]

4. What version of Swoole are you using (`php --ri swoole`)?

4.1.2

5. What is your machine environment used (including version of kernel & php & gcc) ? 

Windows Subsystem for Linux

6. If you are using ssl, what is your openssl version?
 1.0.2g  1

**Comment by twose** [comment]
please show your diff

**Comment by grikdotnet** [comment]
> please show your diff

pardon, diff of what with what?

**Comment by twose** [comment]
if tests failed, it will output some log files in the dir.
we have Travis CI, all released versions tests were passed.

**Comment by grikdotnet** [comment]
Ok, so the team is not supporting.
