### ISSUE TITLE
4.0.4内存错误！

### ISSUE THREAD

**Issue by patrickkh7788** [swoole/swoole-src#1973]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

程序运行一段时间后出现这个：
php(11580,0x7fffac6c3380) malloc: *** error for object 0x7fbe5c41b408: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

2. What did you expect to see?

想要知道原因，如何防止这样的错误。

3. What did you see instead?

内存错误！

4. What version of Swoole are you using (`php --ri swoole`)?

php --ri swoole

swoole

swoole support => enabled
Version => 4.0.4
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
kqueue => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
pcre => enabled
zlib => enabled
mysqlnd => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 

mac 10.13.5 
hp -v
PHP 7.2.9 (cli) (built: Aug 23 2018 02:08:27) ( NTS )

6. If you are using ssl, what is your openssl version?

无

**Comment by twose** [comment]
升级版本

**Comment by patrickkh7788** [comment]
升级版本后没有在碰到过了。
