### ISSUE TITLE
1.10.5 运行时段错误

### ISSUE THREAD

**Issue by fjmygame** [swoole/swoole-src#1974]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
#0  0x00007f219732b1d7 in raise () from /lib64/libc.so.6
#1  0x00007f219732c8c8 in abort () from /lib64/libc.so.6
#2  0x00007f219736af07 in __libc_message () from /lib64/libc.so.6
#3  0x00007f2197372503 in _int_free () from /lib64/libc.so.6
#4  0x00007f218fa1025c in swRingBuffer_free (pool=0x2e0f, ptr=0x2e0f)
    at /home/swoole-src-1.10.5/src/memory/RingBuffer.c:183
#5  0x00007f218fcd6e00 in swoole_redis_server_ce () from /usr/lib64/php/modules/swoole.so
#6  0x0000000000001388 in ?? ()
#7  0x00007f218fa22150 in swThreadPool_loop (arg=<optimized out>)
    at /home/swoole-src-1.10.5/src/network/ThreadPool.c:148
#8  0x00000000ffffffff in ?? ()
#9  0x00007ffd0af908d8 in ?? ()
#10 0x00007f219c9f1ac8 in ?? ()
#11 0x00007f219c9e7468 in ?? ()
#12 0x00007f218fa22ee3 in swReactorThread_onWrite (reactor=0x7f219c9e7468, ev=<optimized out>)
    at /home/swoole-src-1.10.5/src/network/ReactorThread.c:923
#13 0x0000000000000000 in ?? ()

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?

1.10.5

5. What is your machine environment used (including version of kernel & php & gcc) ? 

php5.6

6. If you are using ssl, what is your openssl version?

**Comment by flddr** [comment]
3. should be 1., 1. should be your code to reproduce error and swoole version is >4 actually - maybe upgrading your swoole could help?

**Comment by twose** [comment]
> This setting is experimental and is mainly used to improve performance. Please do not open it in the production environment
