### ISSUE TITLE
swoole_http_request获取不到post方式参数为一个字母的参数

### ISSUE THREAD

**Issue by andy1219111** [swoole/swoole-src#1976]
和前端预定，参数为“q”,后端request对象获取不到该参数，但是如果是两个或者两个以上字母的参数就可以获取到。
版本信息如下：
swoole support => enabled
Version => 1.10.5
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by andy1219111** [comment]
![image](https://user-images.githubusercontent.com/8500235/45598587-39b25900-ba11-11e8-9b3d-5e819a665713.png)

**Comment by twose** [comment]
这个bug在4.x版本被修复了，如果你用的不是PHP5可以直接升级，php.ini配置加上swoole.enable_coroutine=off
