### ISSUE TITLE
Does \Co::getUid() has the possibility to return same number in a worker process?

### ISSUE THREAD

**Issue by scil** [swoole/swoole-src#1977]
for example:
\Co:;getUid() return 117, after some time, but before worker reload, may it return 117 again?

**Comment by twose** [comment]
no

**Comment by matyhtf** [comment]
Like the process id, It will be reused

**Comment by scil** [comment]
Thank you.

does the id start with 1 and grow by step 1, and  go back to 1  when reaching a max number ?

**Comment by twose** [comment]
@scil 
cid map uses the bitmap, it will find the first available position.
We have also considered this problem (use string like uuid is better?)

we can confirm it by
```php

co::set([
    'max_coroutine' => PHP_INT_MAX,
    'log_level' => SWOOLE_LOG_INFO,
    'trace_flags' => 0
]);
$map = [];
while (true) {
    if (empty($map)){
        $cid = go(function () {co::sleep(5);});
    }else{
        $cid = go(function () { });
    }
    if (!isset($map[$cid])) {
        $map[$cid] = $cid;
    } else {
        var_dump(end($map));
        var_dump($cid);
        exit;
    }
}
```

**Comment by twose** [comment]
We have MAX_CORO_NUM_LIMIT => 0x80000, coroutine num can not be bigger than 524288

**Comment by scil** [comment]
@twose Thank you! I've got it.  For me, bitmap is good enough!
