### ISSUE TITLE
非阻塞执行子进程后全变僵尸进程，无法回收

### ISSUE THREAD

**Issue by ajielee** [swoole/swoole-src#1978]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

我需要一个读 Redis 的程序，而且还能监听服务器上某一端口实现远程终止的功能。下面是 demo 代码：

```php
// Part 1: Fetch data from Redis
$mainProcess = new swoole_process(function (swoole_process $mainProcess) {      
  $redis = new Redis();
  $redis->pconnect('redis', 6379, 3, 'id_log');
  while (true) {
    $data = $redis->blPop('key_log', 3);    
    $log = json_decode($data[1], true);
    $childProcess = new swoole_process(function (swoole_process $childProcess) use ($log) {    
      // Child process logic goes here...
      $childProcess->exit(0);
    });
    $childProcess->start();
  }
});
$mainProcess->start();
$mainProcessPid = $mainProcess->pid;   

// Part 2: HTTP Server
$http = new swoole_http_server("127.0.0.1", 4444);
$http->on("request", function ($request, $response) use ($http, $mainProcessPid) {
    $response->header("Content-Type", "text/plain");
    $response->end("The world is end.\n");
    swoole_process::kill($mainProcessPid);
    $http->shutdown();
});
$http->start();
```

2. What did you expect to see?

以下三点:

- 从 Redis 读到数据后，创建子进程 （OK）
- 子进程完成后自动关闭，释放资源 （NOK）
- HTTP服务器收到请求将主程序关闭，终止运行 (OK)

3. What did you see instead?

一堆的僵尸进程，无法 kill 掉

```
F S   UID    PID   PPID  C PRI  NI ADDR SZ WCHAN  TTY          TIME CMD
0 S  1000  37496    348  0  80   0 - 315854 ep_pol pts/1   00:00:00 php
1 S  1000  37500  37496  0  80   0 - 157784 poll_s pts/1   00:00:00 php
1 S  1000  37501  37496  0  80   0 - 168331 do_wai pts/1   00:00:00 php
1 S  1000  37510  37501  0  80   0 - 164956 ep_pol pts/1   00:00:00 php
1 S  1000  37511  37501  0  80   0 - 164956 ep_pol pts/1   00:00:00 php
1 S  1000  37512  37501  0  80   0 - 164956 ep_pol pts/1   00:00:00 php
1 S  1000  37513  37501  0  80   0 - 164956 ep_pol pts/1   00:00:00 php
1 S  1000  37514  37501  0  80   0 - 164956 ep_pol pts/1   00:00:00 php
1 S  1000  37515  37501  0  80   0 - 164956 ep_pol pts/1   00:00:00 php
1 S  1000  37516  37501  0  80   0 - 164956 ep_pol pts/1   00:00:00 php
1 S  1000  37517  37501  0  80   0 - 164956 ep_pol pts/1   00:00:00 php
1 Z  1000  37518  37500  0  80   0 -     0 -      pts/1    00:00:00 php <defunct>
1 Z  1000  37519  37500  0  80   0 -     0 -      pts/1    00:00:00 php <defunct>
1 Z  1000  37520  37500  0  80   0 -     0 -      pts/1    00:00:00 php <defunct>
1 Z  1000  37521  37500  0  80   0 -     0 -      pts/1    00:00:00 php <defunct>
1 Z  1000  37522  37500  0  80   0 -     0 -      pts/1    00:00:00 php <defunct>
1 Z  1000  37523  37500  0  80   0 -     0 -      pts/1    00:00:00 php <defunct>
1 Z  1000  37524  37500  0  80   0 -     0 -      pts/1    00:00:00 php <defunct>
0 R  1000  37570   3188  0  80   0 - 13257 -      pts/0    00:00:00 ps
```

4. What version of Swoole are you using (`php --ri swoole`)?

`Version => 4.1.2`

5. What is your machine environment used (including version of kernel & php & gcc) ? 

- kernel: `Linux 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- php: `7.2.10`
- gcc: `gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)`

6. If you are using ssl, what is your openssl version?

没有

**Comment by xianqiangzhao** [comment]
用  $childProcess->start();的后面需要用
swoole_process::wait 进行回收
https://wiki.swoole.com/wiki/page/220.html

**Comment by ajielee** [comment]
@xianqiangzhao 我有尝试过加入 `swoole_process::wait()`。

- 当使用异步信号回调:

    ```php
    swoole_process::signal(SIGCHLD, function($sig) {
      while($ret =  swoole_process::wait(false)) {
          echo "PID={$ret['pid']}\n";
      }
    });
    ```

    把以上代码加入到 `$childProcess->start();` 后面，里面的 `echo` 永远都不会执行。

- 当加入 `swoole_process::wait(true)`，程序正常运行，但是子进程是阻塞运行的，跟需求不一致。

**Comment by xianqiangzhao** [comment]
- swoole_process::signal(SIGCHLD, function($sig) 的代码需要加在$childProcess->start() 之前。
这种方式的话就会进入事件循环，不会在执行您提供第二部分的代码（Part 2: HTTP Server）
 应该不是您要的需求

- swoole_process
 本身是作为创建进行并管理进程使用的，在这之后又创建 server ，我想两者不能能这样使用。

- 可以用swoole_server->addProcess 试试
https://wiki.swoole.com/wiki/page/390.html

**Comment by xianqiangzhao** [comment]
改成这样行么？
// Part 1: Fetch data from Redis
$mainProcess = new swoole_process(function (swoole_process $mainProcess) {      
  $redis = new Redis();
  $redis->pconnect('redis', 6379, 3, 'id_log');
  while (true) {
    $childProcess = new swoole_process(function (swoole_process $childProcess) use ($log, $redis) { 
     	 $data = $redis->blPop('key_log', 3);  //放到这里  阻塞等待3秒
    	 $log = json_decode($data[1], true);   //放到这里
      	// Child process logic goes here...
      	$childProcess->exit(0);
    });
    $childProcess->start();
    swoole_process::wait(true); //阻塞等待子进程退出，回收后，循环继续。
  }
});
$mainProcess->start();
$mainProcessPid = $mainProcess->pid;   

这里有一个问题是
 Part2 中的  swoole_process::kill($mainProcessPid); 
  会向mainProcessPid 发送SIGTERM 信号，mainProcessPid收到后，在向他的子进程发送信号。
 这块要确认一下是否OK。
