### ISSUE TITLE
服务器发生崩溃 WORKER EXIT UNEXPECTED Allowed memory size 

### ISSUE THREAD

**Issue by wuchuguang** [swoole/swoole-src#1980]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

WORKER EXIT UNEXPECTED Allowed memory size of

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?
swoole support => enabled
Version => 1.9.23
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ? 

php

6. If you are using ssl, what is your openssl version?
no

work能重启，但无法接收新的请求了。

**Comment by twose** [comment]
你这上古版本可以升级下再看看

**Comment by matyhtf** [comment]
这是因为你的 PHP 代码存在内存泄漏，建议检查全局变量相关代码，进行 review，排查问题。
https://wiki.swoole.com/wiki/page/324.html
