### ISSUE TITLE
[4.2.0] undefined symbol: zif_time_nanosleep

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#1982]
`PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/swoole.so' - modules/swoole.so: undefined symbol: zif_time_nanosleep in Unknown on line 0
`

**Comment by remicollet** [comment]
Happen with 7.1 and 7.3

**Comment by remicollet** [comment]
PHP_FUNCTION are not exported, so not part of the public API.

**Comment by twose** [comment]
How can you find these problems so fast?
Everything is ok in our mac and all the Travis tests passed so I have not found this problem.

**Comment by remicollet** [comment]
Another issue

`PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/swoole.so' - modules/swoole.so: undefined symbol: php_stream_mode_sanitize_fdopen_fopencookie in Unknown on line 0
`

Indeed, in  `main/streams/php_streams_int.h`

`void php_stream_mode_sanitize_fdopen_fopencookie(php_stream *stream, char *result);`

So not a public API (missing the PHPAPI attributes)

**Comment by twose** [comment]
HAVE_NANOSLEEP always exist, cannot use ifdef... fix it soon,

**Comment by remicollet** [comment]
> How can you find these problems so fast?

Because our build use RTLD_NOW, which imply all symbols are available at load time (avoid segfault later at runtime)

Some explanation on https://derickrethans.nl/undefined-symbol.html

**Comment by twose** [comment]
The key is not the "fast", I just thought you have some build tools are running on a variety of environments...

**Comment by remicollet** [comment]
> you have some build tools are running on a variety of environments...

I only build RPM packages for Fedora (26-29) and RHEL / CentOS (6-7) for PHP 5.6 to 7.3
