### ISSUE TITLE
[4.2.0] ZTS build is broken: undefined symbol: _Z14virtual_unlinkPKc 

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#1986]
Using master @ 4b8d52c1527298c0ddeaeb0350b11f0927d1ad31

`PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/swoole.so' - modules/swoole.so: undefined symbol: _Z14virtual_unlinkPKc in Unknown on line 0
`

Seems to be related to inclusion thirdparty/plain_wrapper.c which use VCWD_UNLINK

No issue with NTS build.

**Comment by twose** [comment]
@remicollet 
It should be all right now (master).
Try again with ZTS? (⊙o⊙)

**Comment by twose** [comment]
@remicollet 
Swoole have no thread safety, we remove the VCWD macro in hook, it works now.

**Comment by twose** [comment]
Fixed via 010f0a2

**Comment by remicollet** [comment]
I confirm the fix is ok, build OK
