### ISSUE TITLE
swoole-src-swoole-1.7.10-stable compile error

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#199]
/home/fan/www/server/php/swoole-src-swoole-1.7.10-stable/src/factory/FactoryProcess.c: In function ‘swFactoryProcess_finish’:
/home/fan/www/server/php/swoole-src-swoole-1.7.10-stable/src/factory/FactoryProcess.c:767:52: error: ‘sdata’ undeclared (first use in this function)
     swTrace("[Worker]input_queue[%ld]->in| fd=%d", sdata.pti, fd);
                                                    ^
/home/fan/www/server/php/swoole-src-swoole-1.7.10-stable/include/swoole.h:264:89: note: in definition of macro ‘swTrace’
 #define swTrace(str,...)       {printf("[%s:%d@%s]"str"\n",__FILE__,__LINE__,__func__,##__VA_ARGS__);}
                                                                                         ^
/home/fan/www/server/php/swoole-src-swoole-1.7.10-stable/src/factory/FactoryProcess.c:767:52: note: each undeclared identifier is reported only once for each function it appears in
     swTrace("[Worker]input_queue[%ld]->in| fd=%d", sdata.pti, fd);
                                                    ^
/home/fan/www/server/php/swoole-src-swoole-1.7.10-stable/include/swoole.h:264:89: note: in definition of macro ‘swTrace’
 #define swTrace(str,...)       {printf("[%s:%d@%s]"str"\n",__FILE__,__LINE__,__func__,##__VA_ARGS__);}
                                                                                         ^
make: *** [src/factory/FactoryProcess.lo] 错误 1

-------------------------------------------------------------------
系统环境如下:

fan@fan-ThinkPad-Edge-E440:~/www/server/php/swoole-src-swoole-1.7.10-stable$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 

fan@fan-ThinkPad-Edge-E440:~/www/server/php/swoole-src-swoole-1.7.10-stable$ uname -a
Linux fan-ThinkPad-Edge-E440 3.16.0-28-lowlatency #38-Ubuntu SMP PREEMPT Sat Dec 13 16:41:52 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by matyhtf** [comment]
请关闭swoole-debug编译选项，重新编译。
