### ISSUE TITLE
Unable to load dynamic library 'swoole'

### ISSUE THREAD

**Issue by ITwrx** [swoole/swoole-src#1991]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    `updated php from 7.1.x to 7.2.10 and rebuilt and reinstalled php-swoole AUR package`

2. What did you expect to see?
    `swoole ext loaded with php properly`

3. What did you see instead?
`PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole' (tried: /usr/lib/php/modules/swoole (/usr/lib/php/modules/swoole: cannot open shared object file: No such file or directory), /usr/lib/php/modules/swoole.so (/usr/lib/php/modules/swoole.so: undefined symbol: strpprintf)) in Unknown on line 0`

4. What version of Swoole are you using (`php --ri swoole`)?

    `4.2.1`

5. What is your machine environment used (including version of kernel & php & gcc) ? 
```
Arch Linux 
4.17.14.a-1-hardened x86_64
php 7.2.10
gcc 8.2.1+20180831-1
```

6. If you are using ssl, what is your openssl version?
    `openssl 1.1.1-1`

NOTE: `/usr/lib/php/modules/swoole.so does exist in filesystem.`
`swoole ext won't load whether i have .so in php.ini or not.`

Thanks

**Comment by twose** [comment]
if you `make clean` and rerun the right(new version's) `phpize` then `./configure xxx && make && sudo make install`?

check your phpize version, it may shows these:
```C
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
```

check your version num is PHP72

**Comment by ITwrx** [comment]
@twose just running "make clean" in the src directory of the previous build then re-running "makepkg" did the trick. thanks for the help.
