### ISSUE TITLE
why changed the strcture ? webroot staticdir ... and just one failed request and the http server is exit ... it's a stupid idea

### ISSUE THREAD

**Issue by kombany** [swoole/swoole-src#1993]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (`php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

6. If you are using ssl, what is your openssl version?

**Comment by twose** [comment]
What structure has changed?

**Comment by kombany** [comment]
'document_root' => publicdir.'/',
    'enable_static_handler' => true,

in 4.01 this config working and another version this config not working and have to define the headers manually and the directory

**Comment by kombany** [comment]
and chrome ccs.map is cause a fatal error

**Comment by twose** [comment]
about ssl
```php
$http = new swoole_http_server('127.0.0.1', 9501, SWOOLE_BASE, SWOOLE_SOCK_TCP | SWOOLE_SSL);
$http->set([
    'log_file' => '/dev/null',
    'open_http2_protocol' => true,
    'http_compression' => false,
    'ssl_cert_file' => SSL_FILE_DIR . '/server.crt',
    'ssl_key_file' => SSL_FILE_DIR . '/server.key',
]);
```

see:

**Comment by kombany** [comment]
but this is not redirect the http connection to https

**Comment by kombany** [comment]
server send only an empty response to the browser if the request is http://anything.com and I want to redirect https://anything.com

**Comment by twose** [comment]
swoole is a high-performance **application server**, please not use it to replace nginx

**Comment by flddr** [comment]
@kombany - this is simplest HTTP standard! Check for Port 80 and send `302` header!

**Comment by twose** [comment]
request with wrong protocol will be refused by swoole, so the request without ssl will never reach ssl server.
HTTP proxy is necessary before the user reach the swoole's server in production env.

**Comment by laurenti** [comment]
$server = new swoole_websocket_server("0.0.0.0", 443, SWOOLE_BASE, SWOOLE_SOCK_TCP | SWOOLE_SSL);
$port = $server->addlistener('0.0.0.0', 80, SWOOLE_SOCK_TCP);
$port->on('Request', function(swoole_http_request $request, swoole_http_response $response){
      $response->status(301);
      $response->end('<meta http-equiv="refresh" content="0;URL=https://anything.com">');
}); 

  $server->start();

**Comment by kombany** [comment]
thx guys !! that's what I find $server->addlistener ... sorry about my english

**Comment by twose** [comment]
@kombany this way is ok

**Comment by twose** [comment]
by the way, we have:
```php
function swoole_http_response->redirect(string $url, int $http_code = 302);
```

**Comment by kombany** [comment]
thx
