### ISSUE TITLE
Swoole MySQL SSL support?

### ISSUE THREAD

**Issue by hc-codersatlas** [swoole/swoole-src#1996]
Hi, is it possible for the MySQL SSL Async client to connect a MySQL secured by SSL? I couldn't see this in the configuration. Thanks.

**Comment by twose** [comment]
Use `Swoole\Coroutine\MySQL` is a better way, not async now.
SSL is not necessary, SSL will increase connection overhead, CPU usage, memory usage, and response time.
In a production environment, MySQL is generally deployed in an intranet environment, even for clusters. The MySQL handshake uses very secure RSA encryption, and MySQL has been enhancing the security of handshakes for a long time. For enterprises, no MySQL uses SSL connections as I know, and the existing methods are safe enough.
MySQL is always a performance bottleneck, we will support SSL in the future, but not the first priority.

**Comment by eduvpp** [comment]
Hello @twose , you have any idea when this feature is going to be released ? i use hyperf, and i need a PDO connection with SSL, but hyperf utilize swoole, and im getting the error access denied, but in PHP FPM this work fine, with the same credentials and certificates. You can see more here https://github.com/hyperf/hyperf/issues/7076
