### ISSUE TITLE
WARNING	sw_coro_create: xdebug do not support coroutine, please notice that it lead to coredump.

### ISSUE THREAD

**Issue by cwl168** [swoole/swoole-src#1998]
swoole 版本是 4.2.1 ，确认一下协程是不支持xdebug吗

**Comment by twose** [comment]
提示都这么明显了, 当然还是不支持啦, 轻量的使用不会引起coredump, 所以是warning.
现在有一些[调试函数](https://wiki.swoole.com/wiki/page/967.html)作为辅助, 未来计划会支持xdebug或产生类似的调试工具
