### ISSUE TITLE
Coroutine\Redis 相关问题

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/swoole-src#2003]
1. 通过反射获取不到方法的参数，无法通过反射生成IDE提示
2. `scan object sort migrate hscan sscan zscan`方法没有实现，不知道是什么原因

**Comment by twose** [comment]
```php
Class Redis extends \Redis
```

**Comment by Yurunsoft** [comment]
用`Redis`扩展是可以取到，但是取`Coroutine\Redis`也应该要可以取到比较好吧

**Comment by twose** [comment]
应该是可以获取到的, 除非你没装hiredis
https://github.com/swoole/ide-helper

**Comment by Yurunsoft** [comment]
https://github.com/swoole/ide-helper/blob/master/output/namespace/Coroutine/Redis.php

这个，比如`set`/`get`方法，参数都没有显示，明显没有读到

**Comment by twose** [comment]
看了下底层的确很多方法没有定义参数表, 但是不影响使用
还有就是扩展的参数信息通过反射获取是不带类型提示的, 比较麻烦

**Comment by Yurunsoft** [comment]
确实不影响使用，但如果能获取到参数名，至少也比没有强

**Comment by twose** [comment]
这个工作量比较大, 反射生成脚本可以适配下用extends

**Comment by twose** [comment]
这个工作量比较大, 反射生成脚本可以适配下用extends
