### ISSUE TITLE
\Swoole\Runtime::enableCoroutine() Version 4.2.1 Segmentation fault

### ISSUE THREAD

**Issue by onanying** [swoole/swoole-src#2005]
没问题的版本：

Version => 4.1.0，4.1.2

有问题的版本：

Version => 4.2.1

问题描述：

我在改造 GuzzleHttp 为协程，使用一键协程 `\Swoole\Runtime::enableCoroutine()` ，在 `Version => 4.1.0，4.1.2` 改造成功的代码，在 `Version => 4.2.1` 执行报 `Segmentation fault (core dumped)
` 错误，经debug发现，在执行完 `\Swoole\Runtime::enableCoroutine()` 后，操作类的静态属性与使用 new 都会引发  `Segmentation fault (core dumped)
` 错误。

**Comment by twose** [comment]
BUG反馈请参考 https://github.com/swoole/swoole-src/issues/2000
贴一下可复现的代码

**Comment by onanying** [comment]
我花了一天时间，还是无法用简单的代码重现这个问题，现在能确定的是与 composer 的自动加载有关，开启 `\Swoole\Runtime::enableCoroutine();` 后，在这行代码前 composer 已经载入的类，可以使用，没有载入的类，都不可使用，使用就 `Segmentation fault (core dumped)`。

我打印了这个core文件：

```
[root@localhost bin]# gdb php -c core.60169 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/php7.2.9/bin/php...done.
[New LWP 90797]
[New LWP 90799]
[New LWP 90798]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `mix-console: coroutine          '.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000008e757a in ZEND_INCLUDE_OR_EVAL_SPEC_CV_HANDLER () at /home/php-7.2.9/Zend/zend_vm_execute.h:33894
33894			new_op_array->scope = EX(func)->op_array.scope;
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-19.2.el7.x86_64 freetype-2.4.11-15.el7.x86_64 glibc-2.17-222.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-19.el7.x86_64 libcom_err-1.42.9-12.el7_5.x86_64 libcurl-7.29.0-46.el7.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libidn-1.28-4.el7.x86_64 libjpeg-turbo-1.2.90-5.el7.x86_64 libpng-1.5.13-7.el7_2.x86_64 libselinux-2.5-12.el7.x86_64 libssh2-1.4.3-10.el7.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 nspr-4.10.8-2.el7_1.x86_64 nss-3.19.1-18.el7.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 nss-util-3.19.1-4.el7_1.x86_64 openldap-2.4.40-8.el7.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
```

这里面有 `ZEND_INCLUDE_OR_EVAL_SPEC_CV_HANDLER` 相关。

**Comment by twose** [comment]
我大概清楚了, 你尝试拉取master分支重新编译, 然后
```php
\Swoole\Runtime::enableCoroutine(true, SWOOLE_HOOK_ALL ^ SWOOLE_HOOK_FILE);
```
这样来开启协程hook试试

**Comment by onanying** [comment]
用 master 分支测试，
使用 `\Swoole\Runtime::enableCoroutine(true, SWOOLE_HOOK_ALL ^ SWOOLE_HOOK_FILE);` 成功，没有错误了。
使用 `\Swoole\Runtime::enableCoroutine();` 还是有，应该是文件读写 hook 的问题了。

**Comment by twose** [comment]
你用valgrind跑一下, 贴一下日志

**Comment by onanying** [comment]
[test0927.log](https://github.com/swoole/swoole-src/files/2422402/test0927.log)

**Comment by matyhtf** [comment]
@onanying 使用`php -m` 和 `php -v` 帖出具体的信息。
请上传一个可以稳定复现的 demo 程序

另外，请测试一下 官方单元测试中的 `tests/swoole_runtime/file_hook/include.phpt` 看看是否可以重现

**Comment by onanying** [comment]
[root@localhost swoole-src-4.2.1]# php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gd
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
swoole
sysvsem
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

[Zend Modules]

**Comment by onanying** [comment]
[root@localhost swoole-src-4.2.1]# php -v
PHP 7.2.9 (cli) (built: Aug 22 2018 08:02:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by onanying** [comment]
[root@localhost swoole-src-4.2.1]# php --ri swoole

swoole

swoole support => enabled
Version => 4.2.1
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
redis client => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by onanying** [comment]
我尝试自己模拟 composer 依赖写个 demo，但是没有重现出来，只能把整个框架代码包含测试代码提交了。

以下命令即可重现

```
php demo/bin/mix-console coroutine exec
```
测试代码文件路径在：

```
demo/apps/console/commands/CoroutineCommand.php
```

文件内容

```
<?php

namespace apps\console\commands;

use mix\base\Channel;
use mix\console\ExitCode;
use mix\facades\Input;

/**
 * 协程范例
 */
class CoroutineCommand extends BaseCommand
{

    // 初始化事件
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 获取程序名称
        $this->programName = Input::getCommandName();
        // 设置pidfile
        $this->pidFile = "/var/run/{$this->programName}.pid";
    }

    // 执行任务
    public function actionExec()
    {
        // 预处理
        parent::actionExec();
        // 执行
        $this->execute();
        // 返回退出码
        return ExitCode::OK;
    }

    // 执行
    public function execute()
    {
        // 并行查询数据
        go(function () {
            // 并行查询数据
            list($foo, $bar) = [$this->foo(), $this->bar()];
            // 取出查询结果
            list($fooResult, $barResult) = [$foo->pop(), $bar->pop()];
            var_dump($fooResult);
            var_dump($barResult);
        });
    }

    // 查询数据
    public function foo()
    {
        $chan = new Channel();
        go(function () use ($chan) {

            var_dump(11111);
            \Swoole\Runtime::enableCoroutine(true);
            var_dump(22222);

            // \mix\task\BaseQueue 这个类是之前未加载过的类
            $object = new \mix\task\BaseQueue();

            var_dump(33333);

            $chan->push(1);
        });
        return $chan;
    }

    // 查询数据
    public function bar()
    {
        $chan = new Channel();
        go(function () use ($chan) {

            $chan->push(2);
        });
        return $chan;
    }

}

```

当执行到  `$object = new \mix\task\BaseQueue();` 时，因为这个类之前是没有加载过的，可以换成任意没有加载过的类，都能重现这个问题。

附件：

[demo.zip](https://github.com/swoole/swoole-src/files/2423718/demo.zip)

**Comment by matyhtf** [comment]
本地已重现，正在解决。

**Comment by matyhtf** [comment]
include/require 操作可能会读写栈上内存，导致出现了错误的内存访问。底层对 inlcude/require 操作，关闭了协程调度。
