### ISSUE TITLE
swoole_http_server $request->post 无法获取到post数据

### ISSUE THREAD

**Issue by icyboyxp** [swoole/swoole-src#201]
使用 $request->post无法获取到对应的post数据，用$request->rawContent()可以看到有对应的post请求数据。

path=123&type=release   //$request->rawContent()

swoole_http_request Object
(
    [header] => Array
        (
            [host] => 192.168.3.58:9502
            [user-agent] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0
            [accept] => application/json, text/javascript, */*; q=0.01
            [accept-language] => zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
            [accept-encoding] => gzip, deflate
            [content-type] => application/x-www-form-urlencoded; charset=UTF-8
            [referer] => http://auto.com/publish
            [content-length] => 21
            [origin] => http://auto.com
            [connection] => keep-alive
            [pragma] => no-cache
            [cache-control] => no-cache
        )

    [fd] => 8
    [server] => Array
        (
            [request_method] => POST
            [request_uri] => /pms/code_upgrade.php
            [path_info] => /pms/code_upgrade.php
            [request_time] => 1424934535
            [server_port] => 9502
            [remote_port] => 59726
            [remote_addr] => 192.168.3.73
            [server_protocol] => HTTP/1.1
            [server_software] => swoole-http-server
        )

)

**Comment by bixuehujin** [comment]
Fixed by https://github.com/swoole/swoole-src/commit/159c4e6873b3efa7c25b9672901d4c35596d1d2d

**Comment by icyboyxp** [comment]
修改swoole_http.c 中的strcasecmp(at, "application/x-www-form-urlencoded") == 0)为 strstr(at, "application/x-www-form-urlencoded") != NULL)

**Comment by sandacn** [comment]
https://github.com/swoole/swoole-src/pull/202/files
