### ISSUE TITLE
Daemon $http->start() won't continue

### ISSUE THREAD

**Issue by rogierverbrugge** [swoole/swoole-src#2011]
Please answer these questions before submitting your issue. Thanks!

**1. What did you do? If possible, provide a simple script for reproducing the error.**
I want to start a http server with the following script

```php
$http = new swoole_http_server("127.0.0.1", 9501);

$http->set([
    'daemonize' => true
]);

$http->on('request', function ($request, $response) {
    $response->end("<h1>Hello World. #".rand(1000, 9999)."</h1>");
});

$http->start();

echo 'test';

```

**2. What did you expect to see?**
I expect to see "test" in console (in my other apps more code)

**3. What did you see instead?**
[2018-09-27 15:53:03 @29654.0]	TRACE	php_swoole_server_before_start(:535): Create swoole_server host=127.0.0.1, port=8080, mode=3, type=1

**4. What version of Swoole are you using (show your `php --ri swoole`)?**
swoole

swoole support => enabled
Version => 4.2.1
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
debug => enabled
trace-log => enabled
kqueue => enabled
rwlock => enabled
pcre => enabled
zlib => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

**5. What is your machine environment used (including version of kernel & php & gcc) ?**
I tested this on my mac (fresh install Mojave) with PHP 7.2.10

Also tested it with docker
```
FROM php:7.2-cli-alpine

# Install rdkafka
RUN apk add --update --no-cache alpine-sdk autoconf && \
    pecl install swoole
```

**Comment by flddr** [comment]
`'daemonize' => 1` ;)

Then `php script.php`

**Comment by flddr** [comment]
Btw: i am not sure what do you want with `echo "test";`, but could be it would not be called after `start`

**Comment by rogierverbrugge** [comment]
'daemonize' => 1 does not work unfortunately.

Echo "test" is just for the example. I have inotify and want to enable it after starting my service so I can reload the server when some php file change.

**Comment by flddr** [comment]
Oh, hehe, it puts output to swoole.log - you can change this path :)

**Comment by flddr** [comment]
Thats because daemonizing

**Comment by huangzhhui** [comment]
Wrong practice, script will blocked when the server started.

**Comment by flddr** [comment]
Everything you echo in functions called async would be logged :)

**Comment by flddr** [comment]
My waittime for slack was about 4 weeks :) than i got thanks to @doubaokun @rogierverbrugge

**Comment by flddr** [comment]
@rogierverbrugge 

```php
$http = new swoole_http_server("127.0.0.1", 9501);

$http->set([
    'daemonize' => true,
    'log_file' => "/logfile"
]);

$http->on('request', function ($request, $response) {
    $response->end("<h1>Hello World. #".rand(1000, 9999)."</h1>");
    echo 'test text';
    abc();
    xyz();
});

$http->start();

function abc() {
  echo "hello ";
}

function xyz() {
  echo "again";
}
```

gives `test texthello again` in `/logfile`

**Comment by twose** [comment]
after you call to start, the script will enter the event loop, if you want to do something after start, you can write your code in `$server->on('start', function(){})` or `$server->on('workerStart', function(){})`.

you can't do too many things in onStart (can just output some log), but you can do anything in onWorkerStart.

**Comment by rogierverbrugge** [comment]
Thanks for the info guys! This can be closed 👍
