### ISSUE TITLE
master里的源码在alpine编译后出错

### ISSUE THREAD

**Issue by millken** [swoole/swoole-src#2014]
···
/tmp/swoole-src-master # php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so (Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so: swSem_create: symbol not found), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so.so: No such file or directory)) in Unknown on line 0
PHP 7.2.10 (cli) (built: Sep 29 2018 01:44:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
···
同样的参数pecl里的包是没有问题的

**Comment by flddr** [comment]
I had this 2 times while installing via an automatic cloudserver setup script on ubuntu - so could be, there were errors i had not seen. After manual `sudo pecl uninstall swoole` + `sudo pecl install swoole` it then works...

Maybe there were errors while installing swoole? Could help to see your setup for swoole and installed libs, but personally i am on ubuntu.

You maybe need separate libs if you chose options with `yes`.

:)

**Comment by millken** [comment]
I also encountered errors when I was building docker image. I used  pecl's swoole in the previous build, everything is ok. but due to some bugs in pecl, I decided to use the master build.


Dockerfile see: 
[https://hub.docker.com/r/millken/php/~/dockerfile/](https://hub.docker.com/r/millken/php/~/dockerfile/)

**Comment by flddr** [comment]
I have no experience with docker, but there were other questions about - maybe, you can find some help in closed issues

**Comment by twose** [comment]
@millken show your docker build log.

**Comment by millken** [comment]
> @millken show your docker build log.

https://hub.docker.com/r/millken/php/builds/bdbsjub2yhwp9heo8hh4rom/

**Comment by twose** [comment]
@millken 试一下master

**Comment by millken** [comment]
test ok,thanks!
