### ISSUE TITLE
The connection to ws was interrupted while the page was loading. 

### ISSUE THREAD

**Issue by EvgeniiR** [swoole/swoole-src#2019]
I write a websocket server, publish it to VPS http://62.109.21.96/
https://github.com/EvgeniiR/ws-chat/blob/master/app/WebsocketServer.php

1 minut after I connect, if i didn`t send or recieve any data, when trying to send message i see in browser console:
The connection to ws://my_token@62.109.21.96/ws/ was interrupted while the page was loading. 
Error code: 1006

I think that server does not send a "ping" commands.
I was tried to set heartbeat_check_interval =  10/30/60 in websocket config, but it didn`t change anything.

But when I wrote such a function:
public function sendPing()
    {
        $timestamp = time();
        $ids = $this->global_channel->peek();
        if (!$ids) return;
        foreach ($ids as $userId) {
            $this->ws->push($userId, $timestamp, WEBSOCKET_OPCODE_PING);
        }
    }
and manually called it every 20 seconds, it still works and keep connection.

How can i do this automatically?

What version of Swoole are you using (show your `php --ri swoole`)?
4.2.1

What is your machine environment used (including version of kernel & php & gcc) ?
Debian 9, php 7.0

Nginx config:
`server {
        listen 80; 
        server_name 62.109.21.96;
        root  /home/user/ws-chat;

        index index.php;
        # add_header Access-Control-Allow-Origin *;

        location / {
                # add_header Access-Control-Allow-Origin *;
                try_files $uri $uri/ /index.php?$query_string;
        }

        location /ws/ {
                proxy_pass http://localhost:9502;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }

        location ~* \.php$ {
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
`
And in "http" section of file nginx.conf i added proxy_read_timeout 950s;

**Comment by EvgeniiR** [comment]
Thanks for answer. But if i use the above code, where $server = my swoole_websocket_server i get the following error: swServer_tcp_send (ERROR 9009): can't send data to the connections in master process

**Comment by EvgeniiR** [comment]
Thanks for the answer. But if i use the aboce code, with $server = my swoole_websocket_server i got the following error:  swServer_tcp_send (ERROR 9009): can't send data to the connections in master process

**Comment by twose** [comment]
remove mt_rand, it just for test, choose one style.
you must write it in onWorkerStart event function.
