### ISSUE TITLE
解析空的POST请求报错 swoole_http_server::start(): parse multipart body failed

### ISSUE THREAD

**Issue by photondragon** [swoole/swoole-src#2020]
HTTP请求内容
```
POST /Sys/Authorization/Logout HTTP/1.1
Host: api.example.com:5200
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW--
```
这个请求是用Postman生成的，相当于POST了一个空的表单，但是HTTP body不为空。
这应该是一个合法的HTTP请求，不应该报错。
（这个请求实际上是调用了一个restful API接口（注销接口），这个接口不需要任何参数）

swoole 1.10.5 报错
```
swoole_http_server::start(): parse multipart body failed.
```

swoole 2.2.0 和 4.2.1 报错
```
Unknown: parse multipart body failed.
```

**Comment by photondragon** [comment]
php-fpm是可以正常解析这个请求的，得到的是一个空的`$_POST`

**Comment by forever-go** [comment]
换4.1.1就可以了，新版本有这么一个bug，我这边测试的结果

**Comment by twose** [comment]
@photondragon 
你是如何使用postman发起这个请求的, 使用postman的formdata模式不论如何都会带上`content-length: 0`的头, 你这个包的拼接好像是不符合协议规定的, fpm可以解析可能是在底层隐藏了解析错误, 并没有丢弃请求

@forever-go 请问你遇到的bug具体是什么呢, 可以贴一下吗

**Comment by photondragon** [comment]
我用的chrome版postman
![image](https://user-images.githubusercontent.com/4104462/46649223-dad49f80-cbca-11e8-83a2-69bcd6a42d1d.png)

或者把下面的这个文件后缀改成.json，用Postman导入即可：
[swoole_test.postman_collection.txt](https://github.com/swoole/swoole-src/files/2459027/swoole_test.postman_collection.txt)

**Comment by twose** [comment]
可能是postman的一个bug
我和你生成了同样的代码:
![image](https://user-images.githubusercontent.com/25978241/46650921-d90dda80-cbd0-11e8-887b-a47768088f06.png)
但是实际发送的包:
![image](https://user-images.githubusercontent.com/25978241/46650933-e4f99c80-cbd0-11e8-8368-b5122ceaf7e6.png)

正常情况下浏览器或者是任何客户端都不会用那种错误的方式发送空包, 并且必然带上content-length: 0
而且空包没必要使用form-data, 且包体不应该有任何内容

**Comment by twose** [comment]
我更新了postman 它们在最新版直接修复了这个问题
![image](https://user-images.githubusercontent.com/25978241/46651340-42421d80-cbd2-11e8-85af-1795423c45e2.png)
