### ISSUE TITLE
Cannot install swoole using pecl install swoole

### ISSUE THREAD

**Issue by mahmed-ntd** [swoole/swoole-src#2021]
Appreciate your hard work.
I'm having issue while installing the latest version of the swoole. 
your help will be much appreciated.

1. What did you do? If possible, provide a simple script for reproducing the error.
`pecl install swoole`

2. What did you expect to see?
I was supposing that it will install the swoole 4 (latest version).

3. What did you see instead?
System came up with some errors. (I'm able to install version 2.1.3, but cannot install latest version)
for further error information please check log file. [swoole.log](https://github.com/swoole/swoole-src/files/2458382/swoole.log)

4. What version of Swoole are you using (show your `php --ri swoole`)?
As i was not able to install the latest version, so i just installed the old version by cloning the repo and changing current branch to v2.1.3.
```
phpize
./configure
make && make install
```

```
[root@localhost ~]# php --ri swoole

swoole

swoole support => enabled
Version => 2.1.3
Author => tianfeng.han[email: mikan.tenny@gmail.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ?

> [root@localhost ~]# hostnamectl
>    Static hostname: localhost.localdomain
>          Icon name: computer
>   Operating System: CentOS Linux 7 (Core)
>        CPE OS Name: cpe:/o:centos:centos:7
>             Kernel: Linux 3.10.0-862.14.4.el7.x86_64
>       Architecture: x86-64
> 
> [root@localhost ~]# cat /etc/centos-release
> CentOS Linux release 7.5.1804 (Core) 
>
> gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 

> [root@localhost ~]# php -v
> PHP 7.2.10 (cli) (built: Sep 11 2018 11:22:20) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.2.10, Copyright (c) 1999-2018, by Zend Technologies
>

**Comment by twose** [comment]
Read Requirements, GCC 4.8 or later (Version >= 4)

**Comment by mahmed-ntd** [comment]
update the gcc to version: gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 
but still same

**Comment by mahmed-ntd** [comment]
after updating gcc to 7.3.1 `pecl install swoole` didn't worked.

So used `pecl download swoole` and then used ./make.sh file inside the swoole folder.
