### ISSUE TITLE
解析POST请求报错 parse multipart body failed 

### ISSUE THREAD

**Issue by forever-go** [swoole/swoole-src#2024]
swoole 4.2.1 php 7.1 

发包数据：
POST /contractB/system/upload HTTP/1.0
Host: 127.0.0.1:9803
Connection: close
Content-Length: 717
Content-Type: multipart/form-data; boundary=WABoundary+13CCF4C5D3DF61CCWA
Accept-Encoding: br, gzip, deflate
Accept: */*
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16A366 MicroMessenger/6.7.2 NetType/WIFI Language/zh_CN
Referer: https://servicewechat.com/wx750d7d77b2074763/7/page-frame.html
Accept-Language: zh-cn

--WABoundary+13CCF4C5D3DF61CCWA
Content-Disposition: form-data; name="token"

1642ce758a4b89e9190f765662c70efc
--WABoundary+13CCF4C5D3DF61CCWA
Content-Disposition: form-data; name="file_name-x"

tmp_bf506b9052956eb65727c9b137618197.jpg
--WABoundary+13CCF4C5D3DF61CCWA
Content-Disposition: form-data; name="file_content_type-x"

image/jpg
--WABoundary+13CCF4C5D3DF61CCWA
Content-Disposition: form-data; name="file_path-x"

/tmp/nginx_uploads/0035001100
--WABoundary+13CCF4C5D3DF61CCWA
Content-Disposition: form-data; name="file_md5-x"

c47ede7014f3b3cd2a3ca0d29f093e58
--WABoundary+13CCF4C5D3DF61CCWA
Content-Disposition: form-data; name="file_size-x"

62630
--WABoundary+13CCF4C5D3DF61CCWA--

报错 parse multipart body failed 

之前4.1.1版本没有此错误，升级4.2.0及4.2.1后出现

**Comment by flddr** [comment]
What's the processor of that multipart? Have you changed the content manually? It does not contain any data of your files?

Maybe this helps you for checking that multipart: https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2

**Comment by matyhtf** [comment]
fixed
