### ISSUE TITLE
swoole.log日志重新打开问题

### ISSUE THREAD

**Issue by loyating** [swoole/swoole-src#2026]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
服务器程序运行期间对日志文件进行了mv

2. What did you expect to see?
[如文档所示](https://wiki.swoole.com/wiki/page/280.html)
在服务器程序运行期间日志文件被mv移动或unlink删除后，日志信息将无法正常写入，这时可以向Server发送SIGRTMIN信号实现重新打开日志文件

3. What did you see instead?
进程异常退出，不断被重新拉起
swManager_check_exit_status:worker#9 abnormal exit,status=0, signal=34
最后kill -9退出 ， 重启了服务

4. What version of Swoole are you using (show your `php --ri swoole`)?
![11539092743_ pic](https://user-images.githubusercontent.com/5088390/46673599-b7324900-cc0c-11e8-90e7-fdc57e80aacc.jpg)

5. What is your machine environment used (including version of kernel & php & gcc) ?
kernel:Linux 4.15-34-generic
gcc version: 5.4.0
php:7.2.5

**Comment by matyhtf** [comment]
对 UserProcess 的处理中存在一个 BUG，已修复。

**Comment by loyating** [comment]
已更新至4.2.3
mv swoole.log 时候提示：Text file busy

**Comment by loyating** [comment]
@matyhtf

**Comment by loyating** [comment]
已解决，是我环境的问题
