### ISSUE TITLE
mqtt分包有问题

### ISSUE THREAD

**Issue by jesusslim** [swoole/swoole-src#2030]
swoole版本为最新的4.1.1
swoole_client接收mqtt数据包时 在数据量大的情况下会出现分包问题 即多条mqtt消息分隔有问题 出现不完整 或者多了数据的情况
数据打印出来多为如下情况：
{
  "src" : 3,
  "data" : {
    "objectdetail" : "{\n  \"version\" : 2,\n  \"element\" : {\n    \"color\" : 4279518910,\n    \"owner\" : \"1383150\",\n    \"page\" : 1,\n    \"size\" : 3,\n    \"type\" : 1,\n    \"ptArray\" : [\n      301664678,\n      301074893,\n      304155129,\n      324536879,\n      348064347,\n      384567923,\n      428477043,\n      484117073,\n      534252059,\n      567020020,\n      583076316,\n      589302221,\n      589892045,\n      586811824,\n      564529535,\n      523110739,\n      469895502,\n      411765080,\n      357960088,\n      315886039,\n      288688638\n    ]\n  }\n}",
    "objecttype" : 1,
    "classid" : "12988940"
  },
  "sequence" : 2,
  "video_local_play_capability" : 1,
  "sender" : "1383150",
  "version" : 2,
  "uuid" : "F46D9013-1F16-428D-B2E6-1D38A7B71C34",
  "type" : 300
}0?
结尾会多出字符(多为下一个包的头 如ACK,STX等)

这个问题很久以前的版本就提过（https://github.com/swoole/swoole-src/issues/1371） 一直没有解决 希望能重视一下 谢谢

**Comment by jesusslim** [comment]
正常情况下是每次onreceive到的是一个完整的包 但现在数据并发大的情况下会出现这个包的长度不对 比自身长度多 导致解析出现问题 并且因为多了一些本来不属于这个包的字节 将会导致后续所有的包都产生问题 所有的包

**Comment by matyhtf** [comment]
是否设置了 `open_mqtt_protocol`

**Comment by jesusslim** [comment]
> 是否设置了 `open_mqtt_protocol`

设置了
![image](https://user-images.githubusercontent.com/12554966/46798220-ea4b1880-cd83-11e8-99c2-582ee502fd53.png)

**Comment by matyhtf** [comment]
是否可以提供一个可稳定重现的demo程序呢？

**Comment by matyhtf** [comment]
或者提供一个可重现的测试方法

**Comment by jesusslim** [comment]
> 是否可以提供一个可稳定重现的demo程序呢？

现在无法稳定重现 已知就是在接收每秒几千条mqtt消息的时候会出现这个问题 而且两个相同的程序同时跑 出问题的点也不一定相同(比如A程序在第500条消息时出问题 但B可能到3000条都正常运行) 所以应该不是某个特定数据包的问题

**Comment by matyhtf** [comment]
出问题的消息，有什么相同点？你这个反馈的信息，没有有效的线索，也无法重现，不容易解决。

**Comment by jesusslim** [comment]
相似点可能都有\n这种 但我们很多消息都有\n 但不是每次都出问题 大部分都没问题 但我们每天大概有十几次出问题 有概率一次on reveive会收到这样的数据 头解析是正常的 是收到了publish 但是数据内容是如下的
{"data":{"classid":"13000133","highlight":1,"uid":"724706"},"sender":"13286","sequence":480,"src":0,"type":404,"uuid":"7d53d2c8-768c-4957-bc4c-ed66c9748f18","version":3,"video_local_play_capability":1}0?(tp/debug/signal/channel/12984362/message{"data":{"classid":"12984362","highlight":1,"uid":"1448493"},"sender":"65649","sequence":246,"src":0,"type":404,"uuid":"067ed829-5f72-4b5f-bb66-471454c0fcb1","version":3,"video_local_play_capability":1}0?(tp/debug/signal/channel/12998816/message{"data":{"classid":"12998816","mtlid":"7716","rect":[],"toPage":13},"sender":"9311","sequence":495,"src":0,"type":303,"uuid":"a4774fca-0d30-492b-9576-cf82167d5346","version":3,"video_local_play_capability":1}0?(tp/debug/signal/channel/12992247/message{
  "src" : 3,
  "data" : {
    "objectdetail" : "{\n  \"version\" : 2,\n  \"element\" : {\n    \"color\" : 4294967295,\n    \"owner\" : \"925094\",\n    \"page\" : 1,\n    \"size\" : 3,\n    \"type\" : 1,\n    \"ptArray\" : [\n      487528225,\n      488576802,\n      489822045,\n      491460570,\n      493885545,\n      496769286,\n      499259807,\n      502602296,\n      507124420,\n      510794555,\n      513088398,\n      513678279,\n      514137057,\n      514137060,\n      513088386,\n      510401286,\n      507517554,\n      504437203,\n      496179244,\n      495982572,\n      495982545\n    ]\n  }\n}",
    "objecttype" : 1,
    "classid" : "12992247"
  },
  "sequence" : 2,
  "video_local_play_capability" : 1,
  "sender" : "925094",
  "version" : 2,
  "uuid" : "A62981CC-7A9C-4CF0-A344-8E095FE76B74",
  "type" : 300
}0?(tp/debug/signal/channel/12991689/message{"data":{"classid":"12991689"},"sender":"1209651","sequence":13,"src":1,"type":111,"uuid":"10acdd51-3170-4f14-bfb0-ecafb9884932","version":3,"video_local_play_capability":1}0?tp/debug/signal/server{
  "src" : 3,
  "data" : {
    "description" : "...",
    "issueTags" : [
      2
    ],
    "classid" : "12990229",
    "users" : [
      {
        "userType" : 1,
        "uid" : "754531"
      }
    ]
  },
  "sequence" : 2,
  "video_local_play_capability" : 1,
  "sender" : "754531",
  "version" : 2,
  "uuid" : "9B3E539E-891A-4FEE-8608-44B85BF57DB6",
  "type" : 610
}0?(tp/debug/signal/channel/12983915/message{
  "src" : 3,
  "data" : {
    "classid" : "12983915"
  },
  "sequence" : 2,
  "video_local_play_capability" : 1,
  "sender" : "1451104",
  "version" : 2,
  "uuid" : "137B7DB8-9551-480D-BF0D-2D4809BB3448",
  "type" : 111
}0?(tp/debug/signal/channel/12983815/message{
  "src" : 6,
  "data" : {
    "atPage" : 87,
    "objecttype" : 1,
    "classid" : "12983815",
    "objectdetail" : "{\n  \"version\" : 2,\n  \"element\" : {\n    \"ptArray\" : [\n      283647210,\n      279059716,\n      274275617,\n      270343482,\n      267001170,\n      264445288,\n      262741364,\n      261954940,\n      261365121,\n      261299585,\n      261365121,\n      261430657,\n      261430657\n    ],\n    \"page\" : 87,\n    \"size\" : 3,\n    \"owner\" : \"24543\",\n    \"type\" : 1,\n    \"color\" : 4280281191\n  }\n}"
  },
  "sequence" : 588,
  "sender" : "24543",
  "version" : 3,
  "type_desc" : "LEARN_MESSAGE_WHITEBOARD_LINE_SEND",
  "uuid" : "DCC31E87-BDD2-4707-9DBD-7659CF4D3B4F",
  "type" : 300
}0?(tp/debug/signal/channel/12991105/message{
  "src" : 3,
  "data" : {
    "objectdetail" : "{\n  \"version\" : 2,\n  \"element\" : {\n    \"color\" : 4280281191,\n    \"owner\" : \"889298\",\n    \"page\" : 22,\n    \"size\" : 3,\n    \"type\" : 1,\n    \"ptArray\" : [\n      636295571,\n      637540731,\n      638785895,\n      640031060,\n      640620864,\n      641866024,\n      643111184,\n      643700978,\n      644356309,\n      644946109,\n      645535908,\n      646191253,\n      646191229,\n      646191210,\n      646191195,\n      646191170,\n      646191146,\n      646191117,\n      646191083,\n      646191043,\n      646191000\n    ]\n  }\n}",
    "objecttype" : 1,
    "classid" : "12991105"
  },
  "sequence" : 2,
  "video_local_play_capability" : 1,
  "sender" : "889298",
  "version" : 2,
  "uuid" : "C36E625C-F43B-4058-BEBA-824AFFB2ED6C",
  "type" : 300
}0?(tp/debug/signal/channel/12997481/message{
  "src" : 3,
  "data" : {
    "objectdetail" : "{\n  \"version\" : 2,\n  \"element\" : {\n    \"color\" : 4293291710,\n    \"owner\" : \"765843\",\n    \"page\" : 27,\n    \"size\" : 3,\n    \"type\" : 1,\n    \"ptArray\" : [\n      496175717,\n      509807207,\n      538577284,\n      560859617,\n      563284517,\n      565774900,\n      569510457,\n      571345465,\n      571345470,\n      569510462,\n      565774910,\n      555878974,\n      530516522,\n      492767713,\n      466225496,\n      438962364,\n      426641557,\n      422906049,\n      422906078,\n      422906098,\n      424741115\n    ]\n  }\n}",
    "objecttype" : 1,
    "classid" : "12997481"
  },
  "sequence" : 2,
  "video_local_play_capability" : 1,
  "sender" : "765843",
  "version" : 2,
  "uuid" : "0C0C2F84-0E28-45DD-B538-ED2C1BEE164D",
  "type" : 300
}0?(tp/debug/signal/channel/12987678/message{"data":{"classid":"12987678","type":0},"sender":"13607","sequence":1435,"src":0,"type":410,"uuid":"3632ec41-ddf8-4520-886d-8656b655a0e7","version":3,"video_local_play_capability":1}0?(tp/debug/signal/channel/12986475/message{
  "src" : 6,
  "data" : {
    "atPage" : 36,
    "objecttype" : 1,
    "classid" : "12986475",
    "objectdetail" : "{\n  \"version\" : 2,\n  \"element\" : {\n    \"ptArray\" : [\n      600443774,\n      600968062,\n      600968062\n    ],\n    \"page\" : 36,\n    \"size\" : 3,\n    \"owner\" : \"41785\",\n    \"type\" : 1,\n    \"color\" : 4281353205\n  }\n}"
  },
  "sequence" : 349,
  "sender" : "41785",
  "version" : 3,
  "type_desc" : "LEARN_MESSAGE_WHITEBOARD_LINE_SEND",
  "uuid" : "5C03B50B-5953-4AB5-BA1A-F704485235A7",
  "type" : 300
}0?(tp/debug/signal/channel/12993483/message{
  "src" : 6,
  "data" : {
    "toPage" : 17,
    "classid" : "12993483"
  },
  "sequence" : 489,
  "sender" : "32702",
  "version" : 3,
  "type_desc" : "LEARN_MESSAGE_WHITEBOARD_PAGE",
  "uuid" : "DB4F6200-325B-4D53-A25C-54DA70FCEA36",
  "type" : 301
}0?(tp/debug/signal/channel/13000010/message.....

即好几条mqtt消息连在一起了

**Comment by matyhtf** [comment]
mqtt 协议是有一个包头的，请将包头信息记录下来。是否包头的长度，和消息长度一致。另外，客户端是什么程序？

**Comment by matyhtf** [comment]
方便的话，请将消息内容全部保存下来发给我们。我们来做一个模拟测试。

**Comment by jesusslim** [comment]
> mqtt 协议是有一个包头的，请将包头信息记录下来。是否包头的长度，和消息长度一致。另外，客户端是什么程序？

我们客户端会是windows/mac/ipad等等 应该不是包长度不一致的问题 如果是长度不一致的话应该两个程序同时订阅 会在同一个地方出问题 但我们现在模拟两个程序同时订阅同一个topic 出问题的点是不同的 我明天再模拟一下看能否在本地重现

**Comment by jesusslim** [comment]
目前没有办法稳定重现 我们现在的解决方法是判断长度不对时 调用$client->recv再获取一次数据 但是仍然有问题，如下：
on receive收到的数据为:
0...(tp/landi/signal/channel/13019398/message{.  "src" : 3,.  "data" : {.    "objectdetail" : "{\n  \"version\" : 2,\n  \"element\" : {\n    \"color\" : 4294967295,\n    \"owner\" : \"925196\",\n    \"page\" : 2  
长度211
根据包头算出实际长度为631
因为调用$client->recv(631-211, \swoole_client::MSG_WAITALL);再去获取数据
但是获取到的数据为:
6,\n    \"size\" : 3,\n    \"type\" : 1,\n
长度仅为46 因此拼起来依然不完整
是否swoole针对mqtt并发量大时的分包有问题 并且 $client->recv使用MSG_WAITALL时也有不完整问题？

**Comment by matyhtf** [comment]
你用的时同步客户端吗？

**Comment by jesusslim** [comment]
使用的是异步非阻塞客户端(初始化传递了SWOOLE_SOCK_ASYNC)  这个问题会不会和缓冲区设置有关？ 目前用的是默认的2M

**Comment by jesusslim** [comment]
尝试调大了缓冲区 问题依然存在 一个是onreceive时一次收到不止一个包的内容且分隔有问题 其次是client->recv实际取到的内容短于传参长度的内容(目前做法是先client->sleep 发现包不全时调用client-recv 然后再wakeup)

**Comment by matyhtf** [comment]
请想办法构造一个可稳定复现的 demo 程序以及数据内容。

**Comment by HarveyHu-CN** [comment]
这里遇到了相同的问题，版本是1.10.6。
![1](https://user-images.githubusercontent.com/11242211/54110277-ee0ac600-441b-11e9-9be5-6ae154af00db.png)
测试中server只会发过来publish和pong两种包，qos=1
这个是读取出现错误的publish消息，长度103，没有mqtt固定头，如果按照'he'是固定头算，长度刚好满足：ascii('e')+2=103，但是type和flags完全不对了
![2](https://user-images.githubusercontent.com/11242211/54110344-1d213780-441c-11e9-9392-6a8dbd38ca60.png)
同时也抓了tcp包，长度不等于测试消息（len=263）的只有两个ping包，没有长度为101的包，说明包确实是swoole读取的时候出错了？
收包速度 2200条/s，接收了27w多条之后出现错误，偶发，没找出规律，但是1min之内基本必现

**Comment by HarveyHu-CN** [comment]
发现一个规律，第二个pong包接收到之后，再接收25个包，就会出现读取错误。尝试了三次，都是一样的
1：
![3](https://user-images.githubusercontent.com/11242211/54111423-bfdab580-441e-11e9-91e4-960d25d57494.png)
2：
![4](https://user-images.githubusercontent.com/11242211/54111439-c8cb8700-441e-11e9-974c-71e5fcf67dd3.png)
3：
![5](https://user-images.githubusercontent.com/11242211/54111448-cf59fe80-441e-11e9-9f27-9a5bd7947a03.png)
测试程序当检测到非mqtt包就会立即断开连接，后续不会再收到mqtt包
不知道这个算不算一个线索

**Comment by HarveyHu-CN** [comment]
又测试了一下，提供两个测试的case：
1、收包速率不变，不发送keepalive消息，挂测40min，收包总量520w左右，没有出现读消息错乱的问题

2、收包速率不变，将keepalive时间设置为1s，多次测试，消息分包错误出现在第1/2/3/4/10次ping包之后，出现问题的时间点也在1s/2s/3s/4s/10s上，但是出现在1-3次之后的概率很高。抓包看最后一次pong消息收到后，到第26~27次收到测试消息后，出现分包错误。
a. 
![6](https://user-images.githubusercontent.com/11242211/54121765-3f27b380-4436-11e9-9207-d9a7f9884078.png)
b.
![7](https://user-images.githubusercontent.com/11242211/54121781-4949b200-4436-11e9-93d5-6eb516ffee66.png)

从测试结果来看，由于pong包接收而引起分包错误的概率很大。错误出现在接收第几次pong包之后是随机的，pong包之后第几个测试包出现这个问题貌似也是随机的（25~27？？）

**Comment by weijianghu** [comment]
这个问题就不了了之了吗？ @matyhtf

**Comment by weijianghu** [comment]
> 这个问题就不了了之了吗？ @matyhtf

谢谢解决方案

**Comment by matyhtf** [comment]
已修复
