### ISSUE TITLE
PHP installation itself: NTS or ZTS?

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#2034]
I just want to be sure and did not found anything else:

https://wiki.swoole.com/wiki/page/7.html

The PHP version itself **should be** `NTS` or **must be** `ZTS`?

My version actually is: `PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )`

**Comment by ClosetMonkey** [comment]
I have tested using both zts and nts but mostly zts. I'm not sure about official support though.

**Comment by twose** [comment]
Both of them are ok.
Swoole offered no support for multithreaded, NTS is better.

**Comment by flddr** [comment]
Ok, thanks :)
