### ISSUE TITLE
v4.2.2 版本

### ISSUE THREAD

**Issue by limingxinleo** [swoole/swoole-src#2037]
$ php --ri swoole

swoole

swoole support => enabled
Version => 4.2.2-alpha
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1  11 Sep 2018
http2 => 1.33.0
pcre => enabled
zlib => enabled
brotli => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

这里显示是alpha版本

**Comment by twose** [comment]
对不起，它通过34c50a5修复
在Git中重新打了标签，但无法在PECL中修复它。
因此，我将很快发布一个新版本v4.2.3以及其他一些修复。
感谢您的反馈！
