### ISSUE TITLE
[4.2.2] Bad reported version

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#2038]
Probably since https://github.com/swoole/swoole-src/commit/47c125a4d

Which very probably break the check during package upload on pecl forge

4.2.2 report as 4.2.2-alpha

```
$ grep -r SWOOLE_VERSION swoole-4.2.2
...
swoole-4.2.2/include/swoole.h:#define SWOOLE_VERSION "4.2.2-alpha"
...
swoole-4.2.2/php_swoole.h:#define PHP_SWOOLE_VERSION SWOOLE_VERSION
...

```

**Comment by twose** [comment]
Sorry, make a mistake again, fixed via 34c50a5, re-tag in Git, but I can't fix it in PECL.
So I will release a new version v4.2.3 with some other fixes soon.
If anything all right now?
I just add an automated fixing script in 2736bd8, 
you can see the code in ff604c1.
