### ISSUE TITLE
my swoole problem

### ISSUE THREAD

**Issue by fsrmwhjh** [swoole/swoole-src#2040]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
An error occurred while linking swoole websocket.

2. What did you expect to see?
Normal link

3. What did you see instead?
WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11

4. What version of Swoole are you using (show your `php --ri swoole`)?
2.0.12

5. What is your machine environment used (including version of kernel & php & gcc) ?
php

**Comment by twose** [comment]
提供信息太少, 请升级你的swoole版本到最新版.
