### ISSUE TITLE
(bash?) Segfault when only SWOOLE_SOCK_TCP | SWOOLE_SSL ?

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#2043]
I have a new segfault in `4.2.3`, _reduced_ to:

```php
<?php

$server = new swoole_websocket_server('x.y.z.y', 443, SWOOLE_SOCK_TCP | SWOOLE_SSL);

$server->set([
  'ssl_cert_file' => '/etc/letsencrypt/live/mydomain/fullchain.pem',
  'ssl_key_file' => '/etc/letsencrypt/live/mydomain/privkey.pem',
]);

$server->on('request', function (swoole_http_request $request, swoole_http_response $response) {
  $response->end();
});

$server->on('message', function ($server, $frame) {
});

$server->start();
```

**fails** at first `request` with simply:

```bash
Segmentation fault
```

on `PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )`

This:

```php
$server = new swoole_websocket_server('x.y.z.y', 443, SWOOLE_BASE, SWOOLE_SOCK_TCP | SWOOLE_SSL);
```

works.

I tried from https://wiki.swoole.com/wiki/page/525.html

**Please close if not interesting** 😉

**Comment by flddr** [comment]
Maybe my swoole is damaged because of #2042 ?

But i did `pecl uninstall swoole` and `pecl install swoole` to `4.2.3` with

```bash
Build process completed successfully
Installing '/usr/lib/php/20170718/swoole.so'
Installing '/usr/include/php/20170718/ext/swoole/config.h'
install ok: channel://pecl.php.net/swoole-4.2.3
configuration option "php_ini" is not set to php.ini location
You should add "extension=swoole.so" to php.ini
```

`SWOOLE_BASE, SWOOLE_SOCK_TCP | SWOOLE_SSL` **works**, but
`SWOOLE_SOCK_TCP | SWOOLE_SSL` stays with:

```bash
me@u1:~$ sudo php segfault.php
Segmentation fault
me@u1:~$
```

**Comment by flddr** [comment]
This seems due to missing `'open_http_protocol' => true`

**Comment by flddr** [comment]
This code **segfaults** too:

```php
$server = new swoole_http_server("0.0.0.0", 80, SWOOLE_BASE);
$https = $server->addListener("0.0.0.0", 443, SWOOLE_SOCK_TCP | SWOOLE_SSL);

$https->set([
  'ssl_cert_file' => '/etc/letsencrypt/.../fullchain.pem',
  'ssl_key_file' => '/etc/letsencrypt/.../privkey.pem',
  ]);

$server->on('request', function ($req, $res) {
  $res->end("hello, both");
});

$server->start();
```

when missing `'open_http_protocol' => true`;

**Comment by flddr** [comment]
I tried `--enable-debug` and _gdb core_, neither helps

**Comment by flddr** [comment]
This way is **segfault** again:

```php
$server = new swoole_websocket_server('0.0.0.0', 443, SWOOLE_SOCK_TCP | SWOOLE_SSL);
$http = $server->addListener('0.0.0.0', 80, SWOOLE_BASE);
```

**`'open_websocket_protocol' => true` is set** on `$server`

This is **no segfault**:

```php
$server = new swoole_websocket_server('0.0.0.0', 80, SWOOLE_BASE);
$https = $server->addListener('0.0.0.0', 443, SWOOLE_SOCK_TCP | SWOOLE_SSL);
```

**`'open_websocket_protocol' => true` is set** on `$https`

**Comment by flddr** [comment]
Oups, correct is `SWOOLE_BASE, SWOOLE_SOCK_TCP | SWOOLE_SSL` 😉

**Comment by twose** [comment]
so much hack(illegal) usage, swoole lack the corresponding detection.
but thank you for your reporting, we must optimize these details, the more, the better.
