### ISSUE TITLE
4.2.3 版本进程模型addprocess报错

### ISSUE THREAD

**Issue by forever-go** [swoole/swoole-src#2044]
进程模型 选择 SWOOLE_BASE基本模式时
$server->addprocess报错，错误信息看不到，Segmentation fault

另：
httpserver的进程模型选择什么（性能推荐），按文档说的一般选base，今天一看模型选择从3中变成2中，是不是以后base进程模型不支持了？

**Comment by forever-go** [comment]
process模式下，又是之前的各种丢进程

root     26443  0.0  0.1 397172 12668 pts/1    S    15:06   0:00 do_http: inotify
root     26502  0.0  0.1 397172 12332 pts/1    S    15:09   0:00 do_http: master
root     26523  0.0  0.1 397172 12340 pts/1    S    15:13   0:00 do_http: master
root     26569  0.0  0.1 547256 12680 ?        Ssl  15:18   0:00 do_http: master
root     26577  0.0  0.1 401496 13912 ?        S    15:18   0:00 do_http: inotify
root     26641  0.0  0.1 393324 13776 ?        S    15:27   0:00 do_http: worker 0
root     26643  0.0  0.3 476524 25508 ?        S    15:27   0:02 do_http: worker 2
root     26644  0.0  0.2 399476 20168 ?        S    15:27   0:00 do_http: worker 3
root     27184  0.0  0.0  15952  1016 pts/3    S+   16:40   0:00 grep --color=auto http
root@iZ28ug2bgrjZ:/var/www/main-swoole/server# tail /tmp/swoole-http-0.0.0.0\:9803.log 
PHP Warning:  Swoole\Server::reload(): failed to send the reload signal. Error: No such process[3] in /var/www/main-swoole/core/Util/Inotify.php on line 108
PHP Warning:  Swoole\Server::reload(): failed to send the reload signal. Error: No such process[3] in /var/www/main-swoole/core/Util/Inotify.php on line 108
PHP Warning:  Swoole\Server::reload(): failed to send the reload signal. Error: No such process[3] in /var/www/main-swoole/core/Util/Inotify.php on line 108
PHP Warning:  Swoole\Server::reload(): failed to send the reload signal. Error: No such process[3] in /var/www/main-swoole/core/Util/Inotify.php on line 108
PHP Warning:  Swoole\Server::reload(): failed to send the reload signal. Error: No su

**Comment by matyhtf** [comment]
BASE 模式下使用 addProcess 存在一些问题，接下来会解决。
是否使用了 Task 进程，是否使用了 reload_async

**Comment by forever-go** [comment]
没有使用task进程，reload_async也没有使用

**Comment by matyhtf** [comment]
本地测试正常的，多次 reload 无问题。支持 SWOOLE_BASE  和 SWOOLE_PROCESS 两种模式。
SWOOLE_BASE 模式主要是作为单进程单线程程序来使用。

**Comment by forever-go** [comment]
仔细测试排查了下，发下丢进程是因为manager进程崩溃了，所以reload的进程也没有启动起来，感觉应该不是bug，我再运行一段时间再观察下，你说的 base单进程单线程使用怎么理解？

**Comment by forever-go** [comment]
看见了，是错误捕捉的类型不对引起的，修改后已经正常运行了好久了，这个地方没有问题
