### ISSUE TITLE
PHP Startup: Unable to load dynamic library 'swoole.so'

### ISSUE THREAD

**Issue by zhao459399177** [swoole/swoole-src#2045]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

docker alpine3.8
php 版本 7.2.11
swoole 版本4.2.3
pecl 安装swoole 
Dockerfile 脚本是从这里下载的
https://github.com/docker-library/php/tree/master/7.2/alpine3.8/fpm

安装是成功的没有报错
执行 docker run --rm my-php-swoole:latest php -m 
报错
2. What did you expect to see?
swoole 扩展可以用

3. What did you see instead?d

PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so (Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so.so: No such file or directory)) in Unknown on line 0

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole 版本4.2.3

5. What is your machine environment used (including version of kernel & php & gcc) ?
docker alpine3.8
php 版本 7.2.11
swoole 版本4.2.3
pecl 安装swoole

**Comment by twose** [comment]
alpine的docker坑很多, 缺少libstdc++
```Dockerfile
RUN apk add --no-cache libstdc++
```

**Comment by zhao459399177** [comment]
非常感谢！
