### ISSUE TITLE
trace_request(:59): failed to trace worker 48, error lint =274. Error: No error information[0].

### ISSUE THREAD

**Issue by denggang610** [swoole/swoole-src#2048]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

swoole 版本  4.2.1    PHP 版本 7.1.18     开启了慢日志参数 trace_event_worker 和  request_slowlog_file

2. What did you expect to see?

no error

3. What did you see instead?

no error

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole 版本  4.2.1

5. What is your machine environment used (including version of kernel & php & gcc) ?

  PHP 版本 7.1.18 ，centos7.2

**Comment by denggang610** [comment]
@twose   就是在swoole启动httpserver时候， 设置配置文件set()函数中加入
array(
    'request_slowlog_timeout' => 2, 
    'request_slowlog_file' => '/tmp/trace.log',
    'trace_event_worker' => true,
)
然后就大量在接收http请求中有大量这样的错误，  难道是我的业务导致的？ 还是我的环境哪里不正确导致的错误发生

**Comment by matyhtf** [comment]
此模块已移除。这里用 ptrace 读取内存的方式太 hack 了，而 php 又没有提供 ＡＰＩ，导致　ＰＨＰ　版本升级内存布局发生变化时就无法使用了。而且只能用于同步阻塞模式，价值不高。
