### ISSUE TITLE
websocket_server 会卡住

### ISSUE THREAD

**Issue by rainbowgamer** [swoole/swoole-src#205]
一个己经测试好的websocket_server正常运行,各种手机都能联上
此时,用一台ipad1去联接这个websocket,可以看到有新的connected,但是不会握手成功
再后面其它的设备也联接不上了
按ctrl+c 关闭server,再重新运行,会发现前面卡住的几台设备尽然收到了数据联上了,当然ipad1还是没有联接上
估计是ipad1的websocket版本太旧,服务端不能握手成功,就卡住了?

使用的是今天的master版本

**Comment by matyhtf** [comment]
仅支持最新版本的WebSocket握手协议。
