### ISSUE TITLE
安装编译swoole 4.2.3 报错

### ISSUE THREAD

**Issue by dafa168** [swoole/swoole-src#2052]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

phpize && ./configure --with-php-config=/usr/local/php/bin/php-config --enable-debug-log=yes --enable-sockets=yes --enable-openssl=yes --enable-http2=yes --enable-async-redis=yes --enable-mysqlnd=yes --enable-coroutine-postgresql=no

make: *** No rule to make target `/root/swoole-4.2.3/swoole.c', needed by `swoole.lo'.  Stop.

2. What did you expect to see?
nothing

3. What did you see instead?
nothing

4. What version of Swoole are you using (show your `php --ri swoole`)?
nothing

5. What is your machine environment used (including version of kernel & php & gcc) ?
centos 7.0 64bit

PHP 7.1.9 (cli) (built: Sep 15 2017 13:43:15) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by twose** [comment]
应该不存在编译问题, 请再自行检查一下
且编译参数后不应该有`=xxx` 请按照官方文档编译教程来编译
https://wiki.swoole.com/wiki/page/6.html

**Comment by matyhtf** [comment]
没有关键的 gcc 编译错误信息，无法判断。请检查是否缺少某些库和头文件，减少编译参数。
