### ISSUE TITLE
使用idea 开发，并打开xdebug 监控后，如果使用同一个端口做监听，会导致无法执行第二个php 命令

### ISSUE THREAD

**Issue by monkeycraps** [swoole/swoole-src#2055]
使用idea 开发，并打开xdebug 监控后，如果使用同一个端口做监听，会导致无法执行第二个php 命令

**Comment by twose** [comment]
1. 不能在swoole里使用xdebug
2.一个端口一个服务
3. 用idea开发和问题无关, 不属于swoole的bug, 想执行两个只能改端口

可以先去文档里搜索相关问题

**Comment by monkeycraps** [comment]
恩，只是表现很诡异，是直接卡主了，服务启动也正常，但是执行第二条 cli 的命令的时候，就会卡主，问题不太好找，所以，我提了个issue，方便大家确认问题
