### ISSUE TITLE
maybe problem，please check，thanks～

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#206]
diff --git a/src/factory/FactoryProcess.c b/src/factory/FactoryProcess.c
index 18d084b..f541016 100644
--- a/src/factory/FactoryProcess.c
+++ b/src/factory/FactoryProcess.c
@@ -764,7 +764,7 @@ int swFactoryProcess_finish(swFactory *factory, swSendData *resp)
 
     sendn = ev_data.info.len + sizeof(resp->info);
     //swWarn("send: sendn=%d|type=%d|content=%s", sendn, resp->info.type, resp->data);
-    swTrace("[Worker]input_queue[%ld]->in| fd=%d", sdata.pti, fd);
+    //swTrace("[Worker]input_queue[%ld]->in| fd=%d", sdata.pti, fd);
     ret = swWorker_send2reactor(&ev_data, sendn, fd);
     if (ret < 0)
     {
diff --git a/src/memory/Buffer.c b/src/memory/Buffer.c
index 41bd5e1..40aa1f9 100644
--- a/src/memory/Buffer.c
+++ b/src/memory/Buffer.c
@@ -112,7 +112,7 @@ void swBuffer_pop_trunk(swBuffer *buffer, swBuffer_trunk *trunk)
 int swBuffer_free(swBuffer *buffer)
 {
     volatile swBuffer_trunk *trunk = buffer->head;
-    void * *will_free_trunk;  //free the point
+    void *will_free_trunk;  //free the point
     while (trunk != NULL)
     {
         if (trunk->type == SW_CHUNK_DATA)
diff --git a/src/network/Connection.c b/src/network/Connection.c
index 03ee757..8f7c73b 100644
--- a/src/network/Connection.c
+++ b/src/network/Connection.c
@@ -65,7 +65,7 @@ int swConnection_onSendfile(swConnection *conn, swBuffer_trunk *chunk)
         {
         case SW_ERROR:
             swSysError("sendfile() failed.");
-            swBuffer_pop_trunk(conn->out_buffer, chunk);
+            swBuffer_pop_trunk(conn->out_buffer, chunk);//TODO why droped?
             return SW_OK;
         case SW_CLOSE:
             conn->close_wait = 1;
diff --git a/src/network/Server.c b/src/network/Server.c
index 7c0cac4..3505f96 100644
--- a/src/network/Server.c
+++ b/src/network/Server.c
@@ -749,7 +749,7 @@ void swServer_pipe_set(swServer *serv, swPipe *p)
     serv->connection_list[p->getFd(p, SW_PIPE_WORKER)].object = p;
     serv->connection_list[master_fd].object = p;
 
-    if (master_fd > swServer_get_minfd(serv))
+    if (master_fd < swServer_get_minfd(serv))
     {
         swServer_set_minfd(serv, master_fd);
     }
diff --git a/swoole_server.c b/swoole_server.c
index 2224f2a..b005030 100644
--- a/swoole_server.c
+++ b/swoole_server.c
@@ -1299,7 +1299,7 @@ PHP_FUNCTION(swoole_server_set)
     {
         convert_to_string(*v);
         serv->heartbeat_pong_length = Z_STRLEN_PP(v);
-        if (serv->heartbeat_pong_length > SW_HEARTBEAT_PING_LEN)
+        if (serv->heartbeat_pong_length > SW_HEARTBEAT_PONG_LEN)
         {
             php_error_docref(NULL TSRMLS_CC, E_ERROR, "heartbeat pong package too long");
             RETURN_FALSE;

**Comment by matyhtf** [comment]
可以详细说明一下。

**Comment by yiliaofan** [comment]
这个是宏定义手抖写错了应该：
if (serv->heartbeat_pong_length > SW_HEARTBEAT_PING_LEN)
if (serv->heartbeat_pong_length > SW_HEARTBEAT_PONG_LEN) { php_error_docref(NULL TSRMLS_CC, E_ERROR, "heartbeat pong package too long"); RETURN_FALSE;

另外，感觉master 的fd应该是<：
if (master_fd > swServer_get_minfd(serv))

if (master_fd < swServer_get_minfd(serv)) { swServer_set_minfd(serv, master_fd); } diff --git 

这个指针问题，不确定void * *will_free_trunk 是否void *will_free_trunk; 就够了：
void * *will_free_trunk; //free the point
void *will_free_trunk; //free the point while (trunk != NULL) { if (trunk->type == SW_CHUNK_DATA) diff --git a/src/network/Connection.c b/src/network/Connection.c index 03ee757..8f7c73b 100644 --- a/src/network/Connection.c +++ b/src/network/Connection.c @@ -65,7 +65,7 @@ int swConnection_onSendfile(swConnection *conn, swBuffer_trunk *chunk) { case SW_ERROR: swSysError("sendfile() failed.");

谢谢～

**Comment by matyhtf** [comment]
1. 这个2都是8字节
2. minfd是指正常的TCP连接fd最小值，所以是 > master_fd 重置
3. 没明白你表达的意思

**Comment by yiliaofan** [comment]
好的  那没问题了，可以close了  多谢回复啊  项目超赞～！！

**Comment by matyhtf** [comment]
感谢支持。
