### ISSUE TITLE
有没有考虑将异步调用方式使用 Promise呢

### ISSUE THREAD

**Issue by shanliu** [swoole/swoole-src#2065]
现在异步处理很多都使用 Promise 回调函数嵌套 层级多很痛苦啊

**Comment by matyhtf** [comment]
使用协程。

**Comment by shanliu** [comment]
用协程 那像
$serv->on('Connect', 'my_onConnect');
$serv->on('Receive', 'my_onReceive');
这类API会不会改成 yield 的PHP协程方式呢?
