### ISSUE TITLE
no need for [#pragma pack(4)] in line 58 of php_swoole.h

### ISSUE THREAD

**Issue by feilengcui** [swoole/swoole-src#207]
#pragma pack(4)
typedef struct
{
	uint16_t port;
	uint16_t from_fd;
} php_swoole_udp_t;
#pragma pack()
此处struct的成员中字节数都小于4，会按照最大字节数的成员进行对齐，所以没必要使用pack(4)

**Comment by matyhtf** [comment]
感谢你的提议，确实没必要。这是一个历史遗留代码。

**Comment by matyhtf** [comment]
Fixed. https://github.com/swoole/swoole-src/commit/9d1d1bbc30576b7acec50314adaa422e6e33f489
