### ISSUE TITLE
第二次协程访问出错问题

### ISSUE THREAD

**Issue by lizhichao** [swoole/swoole-src#2070]
环境：PHP 7.2.11; swoole 4.2.3
错误提示： WARNING recv: socket has already been bound to another coroutine.
复现方法：
启动一个 swoole_http_server 在 onRequest 调用两次协程函数go执行mysql查询，如果只调用一次不会出现问题。
curl 访问这个http服务 一次可以正常访问，第二次访问报错: WARNING recv: socket has already been bound to another coroutine.

**Comment by twose** [comment]
不允许同时在两个协程内使用同一个客户端
