### ISSUE TITLE
redis_coro HyperLoglog 算法支持

### ISSUE THREAD

**Issue by limingxinleo** [swoole/swoole-src#2076]
协程版Redis 似乎不支持pfadd pfcount 和 pfmerge三个算法

**Comment by limingxinleo** [comment]
swoole 4.2.3

**Comment by twose** [comment]
可以使用v4.2.5，配合runtime一键协程化，直接使用phpredis。

**Comment by limingxinleo** [comment]
我提了个pr，加了一下，麻烦帮我看看吧，因为是线上项目，runtime不太方便开

**Comment by matyhtf** [comment]
@limingxinleo 现在 redis_coro 已经进行了重构，请使用新的模式实现一下。

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/pull/2078

已实现
