### ISSUE TITLE
swoole_client能支持log_file配置吗

### ISSUE THREAD

**Issue by jesusslim** [swoole/swoole-src#2077]
版本2.0.8
目前使用swoole_client做mqttclient订阅消息 出现主进程crash的情况 代码中没有catch到异常 且php error日志中没有错误信息 所以请问swoole_client是否支持log_file配置以便于查看swoole执行过程中的异常

**Comment by twose** [comment]
请先升级到v4.2.5。

**Comment by matyhtf** [comment]
Swoole\Async::set 可以设置 log_file
