### ISSUE TITLE
Coroutine\MySQL->prepare() 返回 true

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/swoole-src#2080]
PHP: v7.1.23
Swoole: v4.2.1、v4.2.5

在并发情况下，`Coroutine\MySQL->prepare()`会偶尔返回`true`，我能保证多个协程没有操作同一个连接。

我知道的是开启`defer`后会返回`true`，但是我并没有开启`defer`。

同样的代码，使用一键协程化后的PDO是没有问题。

没有发现原因，无法给出复现代码，只能来这里寻求帮助了，不知道还有其它情况下这个方法会返回`true`吗？

**Comment by Yurunsoft** [comment]
节选代码：

```php
        $defer = $this->instance->getDefer();
        $stmt = $this->instance->prepare($execSql);
        if(true === $stmt)
        {
            var_dump($defer, $this->instance->getDefer());
        }
```
结果：
```
bool(false)
bool(false)
```

**Comment by Yurunsoft** [comment]
`valgrind -tool=memcheck HttpDemo/bin/imi server/start`

运行后，一直到出现 php 报错，并没有看到 valgrind 的错误信息

**Comment by Yurunsoft** [comment]
然后并发下，必现并发请求到一定次数，execute方法会卡死，设置timeout参数也没用，无限等待卡死

```php
var_dump('execute-1');
$result = $this->statement->execute($params, 1);
var_dump('execute-2');
```
输出：
```
省略……
string(9) "execute-1"
string(9) "execute-2"
string(9) "execute-1"
没了……一直卡死在这
```

太奇怪了

**Comment by twose** [comment]
Tip: 此BUG可复现于大量statement创建和析构时, 缓存mysql的statement对象可以提升一倍的性能且可在低版本中避免此BUG.

**Comment by Yurunsoft** [comment]
已经实现 statement 缓存化：https://github.com/Yurunsoft/IMI/commit/2a035bc2cd2e99ce47b201acc74566b630f5d8f6

性能确实提高不少，也没有出现问题了~而且亲测比pdo一键协程化性能更好！

**Comment by passerbyxp** [comment]
不好意思，因为没找到别的信息，所以挖个坟问一下，参考楼上 @Yurunsoft 的 imi 仓库的代码，是不是说多个 `Coroutine\MySQL()->prepare()` 的结果可以同时缓存？就是比如说：

```
go(function()use($db){
    getSavedStatementOrPrepare($db,"INSERT INTO...")->execute([...]);
    $stmt=getSavedStatementOrPrepare($db,"SELECT ...");
    $stmt->execute([...]);
    print_r($stmt->fetchAll());
    getSavedStatementOrPrepare($db,"UPDATE ...")->execute([...]);
    $stmt->execute([...]);
    print_r($stmt->fetchAll());
});
```

只要 `$db` 链接没断，这些 statement 就可以在其它地方用不同的参数重用？
