### ISSUE TITLE
[4.2.6] broken build with PHP 7.3.0RC4

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#2089]
Unable to load the module:

`PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/swoole.so' (tried: modules/swoole.so (modules/swoole.so: undefined symbol: _Z21zend_string_equal_valP12_zend_stringS0_), /opt/remi/php73/root/usr/lib64/php/modules/modules/swoole.so.so (/opt/remi/php73/root/usr/lib64/php/modules/modules/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

**Comment by remicollet** [comment]
Probably related to https://github.com/php/php-src/pull/3652

**Comment by twose** [comment]
Thank you for your correction, I didn't get this error when loading the extension but i got a runtime error. With the upcoming new version of PHP, we should enable the test of nightly version in travis.
