### ISSUE TITLE
DNS: SRV Record for forwarding wss:// in a cluster does not work

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#2093]
I am trying to separate the websocket logic from http logic (swoole server) to become more _cluster-ready_.

Principially, this is the `SRV` record i have set:

`_wss_.tcp.domain.tld -> Port: x -> machine.domain.tld`

But this gives the following error (in Chrome):

`connection to 'wss://domain.tld/' failed: Error during WebSocket handshake: Unexpected response code: 200`

Without `SRV`, simply: `wss://domain.tld:port` does work, but `SRV` would be much better option...

As far as i know: there is no RFC which defines this behavior including DNS LB.

Have you an idea? Is this due to _misconfiguration of the DNS loadbalancer_ **or** _feature request / configuration setting in swoole_?

**Comment by twose** [comment]
I don't know about this (SRV), but is it should use `wss://_wss_.tcp.domain.tld` ?

**Comment by flddr** [comment]
`SRV` is like an `A` or `TXT` Record which gives information about where to connect to a service. It's based on `_sheme.` `_proto.` `domain.tld` `port` `host`, so a `wss://domain.tld` should be handled internal like `wss://host:ip` on client side.

It seems that _Chrome_ does not request `SRV` from DNS.

I will check the situation on _browser-side_ :)

Thank you
