### ISSUE TITLE
response  write 函数压力测试不正常

### ISSUE THREAD

**Issue by bnubobby** [swoole/swoole-src#2095]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
   swoole 启动服务器，进行ab 压测
  swoole和ab 在同一个局域网内，不在同一台服务器

2. What did you expect to see?

http 服务器：
<pre>
$http = new swoole_http_server("0.0.0.0", 80);
$http->set([
        'reactor_num'     => 8, //监听进程数量 thread num
        'worker_num'      => 8,    //工作进程数量 process num
        'dispatch_mode'   => 3,
        'max_request'     => 10000,
]);
$http->on('request', function ($request, $response) {
    $response->write("Hello Swoole. #".rand(1000, 9999));
    $response->end();
 //   $response->end("Hello Swoole. #".rand(1000, 9999));
});
$http->start();
</pre>
ab 测试：
  ab -k -c 100 -n 100000 http://192.168.1.34:8084/
（注意： ab 是在另外一台服务器的 ）

3. What did you see instead?
   当on request 使用
    $response->end("Hello Swoole. #".rand(1000, 9999));
  
一切正常
  当 on request 里使用
  
 $response->write("Hello Swoole. #".rand(1000, 9999));
 $response->end();
  
ab测试会有概率会卡住，报错 
"apr_pollset_poll: The timeout specified has expired (70007)"
卡住的地方，是在后半段
Completed 90000 requests 
后 

大概率出现警告
"
WARNING: The median and mean for the processing time are not within a normal dev
iation
        These results are probably not that reliable.
"
 
另外，swoole 在压测下，会经常报
 WARNING swServer_master_onTimer (ERROR 9007): No idle worker is available.

4. What version of Swoole are you using (show your `php --ri swoole`)?
    swoole :  v4.2.5
    ab :  v2.3
    php : v7.2.8
5. What is your machine environment used (including version of kernel & php & gcc) ?
    使用 docker

**Comment by twose** [comment]
> https://wiki.swoole.com/wiki/page/62.html
- ab测试工具不支持Http-Chunk，在Http\Server中请勿使用response->write

write是chunk输出, 不能这么压测的
