### ISSUE TITLE
当server重启后，客户端调用失败

### ISSUE THREAD

**Issue by limingxinleo** [swoole/swoole-src#2101]
具体代码写在下面的git仓库里了。

php 7.2
swoole 4.2.5 

https://github.com/limingxinleo/swoole-bugs/tree/master/co_client_recv_fail

**Comment by twose** [comment]
https://wiki.swoole.com/wiki/page/268.html

**Comment by limingxinleo** [comment]
client->recv == '' && errCode == 5001
then
    client->reconnect;
    client->send(data);
    client->recv();
