### ISSUE TITLE
Coroutine redis error

### ISSUE THREAD

**Issue by s890510** [swoole/swoole-src#2104]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
協程版Redis若長時間使用後，會出現 Code: 2, Msg: redisCommandArgv() failed
(new完使用後會放到Channel中存放等待下此使用再取出)

2. What did you expect to see?
應無狀況或 redis->connected = false

4. What version of Swoole are you using (show your `php --ri swoole`)?
v4.2.6
v4.2.5 with hiredis 0.13 無此問題

**Comment by matyhtf** [comment]
这是因为 redis 连接关闭了，需要重新连接服务器。

**Comment by s890510** [comment]
目前是在使用前有先透過 $redis->ping() 做確認，
因為$redis->connected 都是回傳true，無法用做確認

**Comment by twose** [comment]
fixed via 9fe7397

**Comment by twose** [comment]
$redis->connected 无法作为真正断开的可靠凭据, 必须要在请求失败时重连
