### ISSUE TITLE
How to use Swoole coroutines and PHPUnit

### ISSUE THREAD

**Issue by vasily-kartashov** [swoole/swoole-src#2105]
What's the best way to test a DB code that uses `\Swoole\Coroutine\MySQL`. 

Ideally I'd like to have a TestCase with the following structure

```
class DBTest extends TestCase
{
    private function connect()
    {
        $db = new MySQL();
        $db->connect([...]);
        return $db;
    }

    public function setUp()
    {
        $db = $this->connect();
        ...
        // provision db
    }

    public function tearDown()
    {
        $db = $this->connect();
        ...
        // clean up db
    }

    public function testSomething()
    {
        $db = $this->connect();
        ...
        // run tests
    }
}
```

At the moment I get:

> Fatal Error: must be called in the coroutine

**Comment by flddr** [comment]
Are you asking for `$db = new Co\MySQL;`?

**Comment by vasily-kartashov** [comment]
> Are you asking for $db = new Co\MySQL;?

correct, ` \Swoole\Coroutines\MySQL`.

**Comment by flddr** [comment]
:+1:

**Comment by flddr** [comment]
Oh, no, i mean instead of `$db = new MySQL();`

**Comment by vasily-kartashov** [comment]
`$db = new \Swoole\Coroutine\MySQL();`, as in this example: https://github.com/TechEmpower/FrameworkBenchmarks/blob/0ff32b95e9c7f986db77ad9941767da40e7e21a9/frameworks/PHP/swoole/swoole-server.php#L248

**Comment by vasily-kartashov** [comment]
> It's just an idea, still need demonstration.

This works. Thank you!
