### ISSUE TITLE
WARNING swServer_signal_hanlder: Fatal Error: manager process exit. status=0, signal=0

### ISSUE THREAD

**Issue by nemo4247** [swoole/swoole-src#2107]
当前使用 swoole 向 app 发送消息，开了一个 swoole http server，并在其上加了2个 tcp 端口。
创建了4个 size 为 1024 的 swoole table。运行一段时间后，出现： 

`WARNING swServer_signal_hanlder: Fatal Error: manager process exit. status=0, signal=0.`

Ubuntu 16.04
PHP 7.1.12
swoole 2.1.3

**Comment by twose** [comment]
请先升级到最新版本
