### ISSUE TITLE
unable to enable swoole_ssl, crt file not found

### ISSUE THREAD

**Issue by nashgao** [swoole/swoole-src#2108]
I am trying to enable swoole_ssl to my tcp server, but this error occurs:

PHP Fatal error:  Swoole\Server\Port::set(): ssl cert file[/home/nash/Desktop/php/Space/key/private.crt] not found. in /home/nash/Desktop/php/Space/server.php on line 60

Fatal error: Swoole\Server\Port::set(): ssl cert file[/home/nash/Desktop/php/Space/key/private.crt] not found. in /home/nash/Desktop/php/Space/server.php on line 60

the private.crt is definitely under the directory

this is my php --ri swoole
swoole

swoole support => enabled
Version => 4.2.2-alpha
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.0h  27 Mar 2018
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

and I'm using php 7.2, thx.

**Comment by twose** [comment]
show your `ls -al /home/nash/Desktop/php/Space/key/private.crt`

**Comment by nashgao** [comment]
my ls -al /home/nash/Desktop/php/Space/key/private.crt:
-rwxrw-rw- 1 nash nash 1289 Oct  7 11:42 private.crt

**Comment by flddr** [comment]
There are three permission types; your running swoole, folder, file.

You can set everything allowed to point it out

**Comment by twose** [comment]
run
```php
var_dump(is_readable('/home/nash/Desktop/php/Space/key/private.crt'));
```

**Comment by flddr** [comment]
This kind of error message is some kind of misleading, it would help if _swoole_  could handle this with more explaining messages?

Do not know the way it's handled actually, but i feel to remember then and when there are some issues about?

**Comment by twose** [comment]
@flddr if you mean that it should show more details? I think so and I have been working hard for this (improve tips), some code is old and these errors are uncommon. this error is just the process can access the file, nothing else.
https://github.com/swoole/swoole-src/blob/8e43d902a61cc877367b9fd2cb524eada705d259/swoole_server_port.c#L425

**Comment by nashgao** [comment]
by running var_dump(is_readable('/home/nash/Desktop/php/Space/key/private.crt')); it returns true.

**Comment by flddr** [comment]
@twose 

> if you mean that it should show more details? I think so and I have been working hard for this (improve tips)

Exactly :+1: 

But maybe already helpfull to reduce misunderstanding if we got both way info like `"ssl key file[%s] not found or permission denied."` to better understand it could be several problems? Something like that? Is _format_ already problematic here?

(sorry not easy to view on my phone)

@nashgao it's a little bit strange, but can you test maximum permissions to folder and file? If this is ok, format maybe wrong?

**Comment by flddr** [comment]
Btw: **cert file** and **client cert file** give the same error message - maybe better to difference it in error message?

@nashgao are you using client cert file?

**Comment by nashgao** [comment]
@flddr 
I believe that is not the client cert file, but I will test the permission late, thx for ur advice, appreciate it.

**Comment by nashgao** [comment]
@flddr 
just wanna ask how do I test the permission of swoole?

**Comment by flddr** [comment]
@nashgao are you starting as _root_ or _user_?

If _as root_, this may help you

https://wiki.swoole.com/wiki/page/370.html
https://wiki.swoole.com/wiki/page/371.html
(browser translate)

https://www.swoole.co.uk/docs/modules/swoole-server/configuration

**Comment by twose** [comment]
port question: sudo

**Comment by nashgao** [comment]
@twose 
Yeah I've tried that, but the crt file is still not found smh

**Comment by flddr** [comment]
@nashgao thats irritating; have you still no success in this?

Just to be sure and complete: can you please

```bash
sudo chown -R nash:nash /home/nash/Desktop/php
chmod 777 /home/nash/Desktop/php/Space/key/private.crt
```

and please post again:

```bash
ls -ldh /home/nash/Desktop/php/Space/key/private.crt
```

and run swoole as _nash_ (... without some settings for `user`, `group`, `chroot` just to be sure)

btw... try something like simply
```php
<?php
echo file_get_contents('/home/nash/Desktop/php/Space/key/private.crt');
```

simply as _nash_ (`php test.php`). Gives it the content of `private.crt`? Or which _errors_ are upcoming?

**Comment by flddr** [comment]
> I assume this is due to the permission of the swoole.sock? or it's the swoole_tcp. How do I change the permission of that?

Is **not** related to `'/home/nash/Desktop/php/Space/key/private.crt'`

Otherwise, please post **all** upcoming errors, actually we are staying with

```bash
PHP Fatal error: Swoole\Server\Port::set(): ssl cert file[/home/nash/Desktop/php/Space/key/private.crt] not found. in /home/nash/Desktop/php/Space/server.php on line 60

Fatal error: Swoole\Server\Port::set(): ssl cert file[/home/nash/Desktop/php/Space/key/private.crt] not found. in /home/nash/Desktop/php/Space/server.php on line 60
```

**Comment by nashgao** [comment]
after running the commands that you provided, the result is:
ls -ldh /home/nash/Desktop/php/Space/key/private.crt
-rwxrwxrwx 1 nash nash 1.3K Oct  7 11:42

Running as nash, this command (<?php
echo file_get_contents('/home/nash/Desktop/php/Space/key/private.crt');) gives me the content of the private.crt file

There is no other errors, simply the one we are staying with. I've tried on my friends machine and it gives the same error as well.

**Comment by flddr** [comment]
@nashgao just to be sure, you ran `echo file_get_contents(...)` via swoole?

I do not know if a _cert error_ will be rised at same stage here.

@twose what do you think? He is able to echo the certfile. Could it be a cert-error, too? Or only file-read?

**Comment by asheroto** [comment]
Hello, I'm getting this error as well.  My cert files are readable according to PHP, but I get this error...

![image](https://user-images.githubusercontent.com/49938263/87730380-34e59a00-c78d-11ea-9506-318c7d601a0d.png)
