### ISSUE TITLE
4.2.7 swoole serialize

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#2109]
Oh no

> Swoole\Serialize will be forced to close in PHP73 (unsupported temporarily)

Do not understand... No future support actually?

I like swoole\serialize

**Comment by twose** [comment]
We haven't much more energy to face the constant changes in the PHP kernel, In order to save some memory, its stability is also difficult to guarantee.
No future support is possible, php serialize is good enough.

**Comment by flddr** [comment]
Ok, good to know :+1:
