### ISSUE TITLE
swoole_table lock error

### ISSUE THREAD

**Issue by JesseWjs** [swoole/swoole-src#2111]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

高并发的情况下，运行一段时间，请求就会有一个warning,进程被hang住。

2. What did you expect to see?

3. What did you see instead?

[2018-11-11 09:16:35 $4983.0]   WARNING swManager_check_exit_status: worker#18 abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.2.6, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

gdb 如下：
#0  swMutex_create (lock=lock@entry=0x7fa09cc05a08, use_in_process=use_in_process@entry=1) at /dockerdata/swoole-src-4.2.6/src/lock/mutex.c:27
#1  0x00007fa0c6a8ed3a in swTable_new (rows_size=1024, conflict_proportion=0.200000003) at /dockerdata/swoole-src-4.2.6/src/memory/table.c:67
#2  0x00007fa0c6b1715a in zim_swoole_table___construct (execute_data=0x7fa0c72d0a80, return_value=0x222b1a0) at /dockerdata/swoole-src-4.2.6/swoole_table.c:292
#3  0x00000000007a299b in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /dockerdata/php-7.1.9/php-7.1.9/Zend/zend_vm_execute.h:970
#4  0x000000000074ae0b in execute_ex (ex=<optimized out>) at /dockerdata/php-7.1.9/php-7.1.9/Zend/zend_vm_execute.h:429
#5  0x00007fa0c6ac313d in sw_coro_func (arg=<optimized out>) at /dockerdata/swoole-src-4.2.6/swoole_coroutine.cc:255
#6  0x00007fa0c6a8690b in swoole::Context::context_func (arg=0x202b240) at /dockerdata/swoole-src-4.2.6/src/coroutine/context.cc:82
#7  0x00007fa0c6b288c1 in make_fcontext () at /dockerdata/swoole-src-4.2.6/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:64
#8  0x0000000000000000 in ?? ()

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

swoole support => enabled
Version => 4.2.6
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by JesseWjs** [comment]
gcc version 7.3.0 (GCC) 
php version 7.1.9

**Comment by twose** [comment]
能否提供一下最简复现代码
