### ISSUE TITLE
子进程swoole_process启动后无效

### ISSUE THREAD

**Issue by jesusslim** [swoole/swoole-src#2113]
用的是最新版本(4.2.7) 子进程swoole_process启动后无效(能获取进程号 进程也在运行  但是无任何实际效果 设置的进程名也无效 显示为 defunct)  一模一样的代码用4.1.1版本是完全正常的 请问是否新版编译时需要加什么参数？或者用法做了改变 有没有4.2.x版本的更新文档呢？

**Comment by twose** [comment]
请问能否遵照提问模板或者贴一下代码?

**Comment by jesusslim** [comment]
都是比较基础的用法 

public function init(){
        $this->process = new swoole_process(function(){
            swoole_set_process_name(static::PROCESS_NAME);
            while(true){
                //循环处理业务逻辑
            }
            Log::info('UNDEAD end '.static::PROCESS_NAME);
        },false,static::USE_PIPELINE);
    }

    public function start(){
        $this->pid = $this->process->start();
        return $this->pid;
    }

使用场景是 swoole_client作为主进程 开一些子进程辅助执行一些io操作 例如写库等等 程序初始化的时候就调用init方法 client连接成功后调用start启动子进程
代码在4.1.1版本的swoole扩展下运行正常 在4.2.7下就不行了 也没有任何报错信息

**Comment by matyhtf** [comment]
请提供可稳定重现的php程序代码

**Comment by matyhtf** [comment]
@jesusslim 请使用 github master 代码测试一下
