### ISSUE TITLE
Guides and tips for contribution

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#2114]
I have done many things in my life as a programmer. There were several languages for bare system programming to do things more powerful than usal, cleaner, smaller, with better maintenance.

But, the truth, the world wide web has lot's of his power thanks to _Personal Home Page_, or as acronym: **PHP: Hypertext Preprocessor**. _PHP_ has it's advantages and disadventages, it's sometimes hard to maintain and less of power. In the past, i have often asked myself, why is nobody on earth changing this, pumping up the inbuilt _PHP server_. Maybe, the decades of _PHP_ are over?

And: it happens. It has changed. Thanks to _PECL_ and _coroutines_, we got a _PHP server_; easier to maintain and inconceivably powerful.

I love this project :heart: 

Today, thousands of developers can unleash this power by simply `PECL install swoole`. And thanks to _open source_ we can read the code, we can _trust_ and we can _learn_.

While the bare concepts of this powerful extension should be _developed and roadmapped_ by _swoole core team_ a strong community has the power to lift something to it's real level, to contribute for _saving time_, _to talk and discuss_, to heave it to it's _next level_.

To strengthen the community, to get _their_ power, it's needed to provide some guidelines:

How to _program_
What's the _roadmap_ and _timeline_
_Guide them_ to _ask_ and _discuss_

For me personally, i have never ever done _ZEND_. I left _PHP_ many years ago, because of it's disadvantages. _But those are gone now._

I would like to say: **let's build a place**, where people can step in, where they can follow a _thread_ from _beginner_ to _starter_ to _intermediate_, to _pro_.

So, let's begin with _Zend_ - what is needed to learn it? I found a good place to start: http://www.phpinternalsbook.com Is it the right one?

What are _technical facts_ about developing _swoole_? Which _versions_ of _what_ should be learned to _program_ as a _swoole contributor_?

Over time, i think, this can become a good place to _talk and follow_, to _expand our knowledge_, to _heartbeat_ the project and talk about _the small pieces_ **which can be done by community as next** :blush: 

Actually, my time is limited to my projects _running on_ swoole, but there maybe many people who like to contribute when they know _where to start_ and we should _motivate them to give their feedback_ and let them talk about their questions.

**Comment by flddr** [comment]
No likes or comments - let's close it :wink:

**Comment by twose** [comment]
Just have no time to reply, I will take the time to write a guide.
