### ISSUE TITLE
file swoole.h line 475 from_fd 类型应该是 uint16_t 吧

### ISSUE THREAD

**Issue by littlemiaor** [swoole/swoole-src#212]

**Comment by matyhtf** [comment]
是utf8_t，因为最大允许监听128个端口，不会超过 256。所以1个字节就可以存储

**Comment by littlemiaor** [comment]
这是一个FD啊 值很容易超过255吧 我看其它地方 都是 uint16, 
而且 如果 是 u8 serv->connection_info(fd) 得到信息里 from_fd 就不一定正确 你多开几个WORKER 就能试出来

**Comment by matyhtf** [comment]
不会超过255

**Comment by matyhtf** [comment]
swDataHead 里的from_fd仅在发送UDP包时用到，TCP不用此字段。UDP监听的socket必然小于255.
