### ISSUE TITLE
wrong typos of "hanlder" in master

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#2120]
This could be corrected next time:

https://github.com/swoole/swoole-src/blob/e61770017c040306574f8e29345029f9f717b019/src/network/server.c#L48

https://github.com/swoole/swoole-src/blob/e61770017c040306574f8e29345029f9f717b019/src/network/server.c#L1206-L1216

https://github.com/swoole/swoole-src/blob/e61770017c040306574f8e29345029f9f717b019/src/network/server.c#L1565

Serveral issues list this wrong typo :relaxed:

And there is

https://github.com/swoole/swoole-src/blob/e61770017c040306574f8e29345029f9f717b019/swoole_process_pool.c#L191

https://github.com/swoole/swoole-src/blob/e61770017c040306574f8e29345029f9f717b019/swoole_process_pool.c#L409-L411

**Comment by twose** [comment]
You can PR directly.
