### ISSUE TITLE
发现了一个不得了的BUG swoole redis

### ISSUE THREAD

**Issue by DioBrandoLong** [swoole/swoole-src#2122]
swoole 上有多次用到 redis，但是呢！官方API上竟然没有配置redis密码的选项！ 线上项目敢不配置密码 分分钟被当成矿机爆炸！希望swoole的开发者们赶紧修复一下吧。。。

**Comment by twose** [comment]
`$redis->auth`

**Comment by DioBrandoLong** [comment]
你这个直接给了root权限。。。我好不容易找了个大拿给了另外一种答案，亲测 有效
 private function __construct() {
        $this->redis = new \Redis();
        $result = $this->redis->connect(config('redis.host'),  config('redis.port'), config('redis.timeOut'));
        $password=$this->redis->auth(config('redis.password'));
        $key=$this->redis->get('password');
        if($result === false||$password=''||$key==='') {
            throw new \Exception('redis connect error');
        }
    }

**Comment by huangzhhui** [comment]
[黑人问号.jpg] 这……你开心就好……
