### ISSUE TITLE
swoole_websocket_server 配置 ssl 开启 wss模式失败

### ISSUE THREAD

**Issue by DioBrandoLong** [swoole/swoole-src#2125]
![b fwnl z if 0nseowwna](https://user-images.githubusercontent.com/27342144/48658904-64a64100-ea84-11e8-87ef-c41d7560ec58.png)
如图所示 我已经配置了 SSL的证书路径 但是开启的 websocket还是  ws! 
顺便说下 我的 swoole 是4.0版本以上的 按照官方的说法 不需要编译 配置 openssl了 （我配置过了 配置了也没反应！）

**Comment by twose** [comment]
不管是哪个版本SSL都需要在编译时指定openssl依赖的, 不知道你在哪看到的说法

**Comment by DioBrandoLong** [comment]
![xd 0q43k94 rjvx5d](https://user-images.githubusercontent.com/27342144/48660632-e192e400-ea9f-11e8-87fd-a4f19eae5a35.jpg)

**Comment by DioBrandoLong** [comment]
话说我给 swoole安装 openssl一直都不成功不知道为何啊 能帮忙看下么 这是我命令
./configure --enable-openssl --with-openssl-dir=/usr/local/openssl --with-php-config=/wwwrver/php/72/bin/php-config && make && make install

**Comment by twose** [comment]
贴出configure日志和报错信息

**Comment by DioBrandoLong** [comment]
可以了 已经装好了 openssl,官网上的那个命令不行的 我用的另外一个命令才装上了
