### ISSUE TITLE
Async Mysqli Prepare

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#2128]
The documentation discusses async mysql request as
```php
<?php
$db = new swoole_mysql;
$server = array(
    'host' => '192.168.56.102',
    'port' => 3306,
    'user' => 'test',
    'password' => 'test',
    'database' => 'test',
    'charset' => 'utf8',
    'timeout' => 2,
);

$db->connect($server, function ($db, $r) {
    if ($r === false) {
        var_dump($db->connect_errno, $db->connect_error);
        die;
    }
    $sql = 'show tables';
    $db->query($sql, function(swoole_mysql $db, $r) {
        if ($r === false)
        {
            var_dump($db->error, $db->errno);
        }
        elseif ($r === true )
        {
            var_dump($db->affected_rows, $db->insert_id);
        }
        var_dump($r);
        $db->close();
    });
});
```

How to carry out the same async functionality for Mysql Prepared Statement?

**Comment by twose** [comment]
no, the async mode may be removed in the next big version.

**Comment by jobs-git** [comment]
Why should the async mysql be removed?

**Comment by flddr** [comment]
Because everything will be based on `coroutines` when that's completely done. No need for _async_ code anymore :wink:

**Comment by jobs-git** [comment]
So will there be a co-routine that does mysqli prepared? How will swoole connector fit with mysql server or postgresql since these are async servers? Moreover communication via tcp seems to be very expensive in time.

And oh, nice job in Swoole 4.2.7 beats Nginx static more than twice whilst doing dynamic php.

**Comment by flddr** [comment]
What do you mean with

> since these are async servers?

They are using _threads_. Whatever they are doing while you are waiting for a query isn't relevant for your code because you are outsourcing this _blocking IO_ to a coroutine - and you can accelerate _thousands_ or _millions_ of them without blocking your backend.

**Comment by jobs-git** [comment]
its a typo, I mean synchronous servers or non async severs

**Comment by flddr** [comment]
If you build a **high-concurrency** backend to serve millions of requests, the question is how to handle those big numbers. We are **not** talking about **C10K**, swoole is build to solve **C1000K** :wink: 

Hmm, mysqli is long ago for me... You can look at examples and documentation for a deeper dive :blush:

**Comment by jobs-git** [comment]
That is true, based from the test I have made, Swoole was able to handle C1000k without timeout or read errors, that is impressive! I will be testing the sql requests soon and see what appears on my benchmark. This issue can be closed for now since it appears that the project is going in another direction. Thanks!

**Comment by flddr** [comment]
Maybe, your keyword is _Connection Pool_ :wink:

**Comment by jobs-git** [comment]
I will surely remember that keyword, i have read somewhere that swoole requests sql queries too fast that some connections get dropped.

**Comment by twose** [comment]
@jobs-git 
can you read the readme? runtime hook may help you.

**Comment by flddr** [comment]
> By the way, my requests to join the swoole slack group is not yet being accepted.

@doubaokun ping @jobs-git for slack
