### ISSUE TITLE
4.2.7版本在mac下报错

### ISSUE THREAD

**Issue by minxinqing** [swoole/swoole-src#2129]
![image](https://user-images.githubusercontent.com/3809601/48684172-7524fb80-ebeb-11e8-9f50-0dfa16bd945e.png)
[2018-11-19 11:02:03 #72701.0]	ERROR	swPort_onRead_http(:354): recv from connection#16 failed. Error: Socket operation on non-socket[38].

4.2.7版本在mac下报错，换成4.2.5版本后一切恢复正常

**Comment by minxinqing** [comment]
两个版本扩展信息如下
![image](https://user-images.githubusercontent.com/3809601/48684323-1744e380-ebec-11e8-830a-b9e5f43fa7dc.png)
![image](https://user-images.githubusercontent.com/3809601/48684335-2330a580-ebec-11e8-98fa-b1348b763ab6.png)

**Comment by twose** [comment]
信息太少, 无法定位, 请遵照issue模板提问或提供代码

**Comment by minxinqing** [comment]
> 信息太少, 无法定位, 请遵照issue模板提问或提供代码

4.2.7版本在mac下编译出来的没有sockets => enabled，我猜大概是这个原因导致的。
目前已用回4.2.5版本。
