### ISSUE TITLE
task_async and coroutines

### ISSUE THREAD

**Issue by flddr** [swoole/swoole-src#2130]
If i **do not need** `onFinish()` **in relevant cases** and only use `taskwait`, is it save to start coroutines in taskworkers?

https://wiki.swoole.com/wiki/page/1014.html

> task_async
不稳定特性: 不推荐使用
> 注意: 由于运行模式的改变, 可能会出现向下不兼容的表现 (如信号处理等)
> 该选项为true时, task进程会变为异步模式, 允许使用异步/协程API, onTask回调不会自动创建协程, 需要手动创建, 此时使用task->finish可能会产生问题.

Does this mean problems with `onFinish()` or `$server->finish()`? Is `task_async` completely marked as _unstable_ or is it just a notice because of handling of `$server`?

Help me ~~translate~~ understanding please ☺️

**Comment by jobs-git** [comment]
Task_async
Unstable characteristics: Not recommended
Note: Due to changes in the operating mode, there may be downward incompatibility (eg signal processing, etc.)
When this option is true, the task process will become asynchronous mode, allowing the use of the asynchronous / coroutine API, the onTask callback will not automatically create a coroutine, you need to create it manually, using task->finish may cause problems.

**Comment by flddr** [comment]
@jobs-git thank you, i use browser translation myself, it's a question about the _underlying_ morely in exact meaning of that :wink: 

As we are going to use coroutines wherever possible, maybe it's incomplete just actually. Maybe, it's about correct handling. Maybe some other differences which maybe erroring in only 1 of 1000 cases, do not know

**Comment by flddr** [comment]
@jobs-git btw: do you know https://wiki.swoole.com/wiki/index/prid-1 This documentation is great, too :+1: 

Understandig _source code_ completely is a little bit harder in such a complex fain-grained fast growing software :relaxed:

**Comment by jobs-git** [comment]
I could try to help it translate in the future, the google translator seems to be close in doing it.

**Comment by flddr** [comment]
It's not about translation, it's about **exactly meaning**

**Comment by twose** [comment]
if you are using the coroutine, you don't have to try to use the task processes.
Instead of sending tasks to other processes, why not send these tasks to the other coroutine?
No memory isolation, no serialization expenses, no interprocess communication expenses, so why do you have to use task processes to run the async codes?
Although developers really want to do this, I have always opposed, because many people don’t understand what is the coroutine, what it can bring to us.

**Comment by twose** [comment]
about `task->finish`, task processes were designed to synchronize API, if you run the async code and use it, how can we know which task was completed.

**Comment by twose** [comment]
Task processes are really helpful for using multicore.
But most developers don't have such deep demands, Swoole has no multithreaded, this is a trade-off in the difficulty of development, but it does lead to the problems when we have lots of CPU cores.
And channel's scope is the process to which it belongs to.

**Comment by twose** [comment]
I can't understand what you said at the end of the comment.

**Comment by flddr** [comment]
Deepest demands, twose :relaxed: 

I build **exactly** the same software as you, but not for PHP and before Golang pushes coroutines. As i was kicked out due to time-break, i stopped my work when http/2 arrives, because i felt to slow to write a parser again.

_But you are doing it for PHP and with coroutines._ That's why i love this project :relaxed: 

It's ok for me to go with nghttp2, because i do not like it anyway. Maybe, http/3 is the next big thing which is worth to do it...

**for this issue**: i will have following questions and after that, i will close it :wink: thx

**Comment by flddr** [comment]
No longer needed.

Previous case was a test to use `taskworker` as a _handler/queue_ for a limited DB like _sqlite_ which is not capable of _row-locking_ etc.

Now i have reconstructed to use `taskworker` `scope`s to handle _locks_. This delivers maximum power and stability, has their global availability, is very easy to maintain and the job itself could be done where it's written - in the script. The _lock_ itself can be defined like a _enumeration_; whatever needed.

Lifecycle of `taskworker` doesn't hit this; if _lock_ isn't available, that's just an _error_ that should be handled.

**Comment by flddr** [comment]
Just to close this issue

Initially idea was to queue sqlite. Therefore i have used `taskworker` (both, `task_async` _set_ and _unset_) by running _queue_ in a save _scope_ of a taskworker, whereby it's callable _globally_. This works perfectly due to referencing `$server` to each `finish()`. I have testet this (10 `worker`, 10 `taskworker`) by calling taskworkers thousands of times with requests of different queries (_insert x_, _update y_, _select z_) with random data from random workers via `$server->taskwait()` from several scripts - without any lost.

But this kind of queue makes no sense in general, as sqlite is called synchronously per se.

It was nice to test `taskworkers` in such a complex benchmark and get a feeling for their power :muscle: :relaxed: 

But lastly there is no relevance to queue sqlite this way, as it locks per write and nothing else.

But, nice game to study taskworkers :+1:
