### ISSUE TITLE
http服务使用postman不传任何参数会报错

### ISSUE THREAD

**Issue by sayid** [swoole/swoole-src#2133]
提交数据格式是：form-data。其他格式没有问题

提示以下错误信息
Uncaught ErrorException: Swoole\Server::start(): parse multipart body failed, n=40. in  
   /Users/zhangyubo/PhpstormProjects/user_center/vendor/gouuse_core/src/Swoole/Server.ph  
  p:195        

Swoole版本：4.2.7 4.2.8
php：7.2.11

**Comment by twose** [comment]
这只是一个warning, 为什么转换成了Error?
升级一下postman版本

**Comment by twose** [comment]
请看: https://github.com/swoole/swoole-src/issues/2020

**Comment by sayid** [comment]
不指定头信息Content-Type就会报这个

**Comment by sayid** [comment]
好的 谢谢

**Comment by twose** [comment]
非法的数据包就会报出警告 , 还有不要捕获warning再抛出error, 这样会导致worker进程退出
