### ISSUE TITLE
What's the purpose of forcing max connection lower than SW_MAX_CONNECTION

### ISSUE THREAD

**Issue by stormeyes** [swoole/swoole-src#2134]
After upgrading to v4.2.8, we got `WARNING	swServer_start_check: serv->max_connection is exceed the maximum value[10000]`. And we found this commit  [https://github.com/swoole/swoole-src/commit/bc7fcac06a69bd845c12e553f58d8c7a2115c432](url) cause this problem.

Our ulimit -n is 100001 and why adding SW_MAX_CONNECTION and force SwooleG.max_sockets lower than 10000 ? BTW, How can I change the SW_MAX_CONNECTION value on PHP level instead of changing the value in .c file and recompile the source code ?

**Comment by twose** [comment]
请通过set方法手动配置 `max_connection` 参数, 此修改是因为小内存机器上默认ulimit参数过大导致服务无法启动.

**Comment by stormeyes** [comment]
@twose still don't work, code as following:

```
<?php
$http = new swoole_http_server("127.0.0.1", 9501);

$http->set(['max_conn' => 50000]);

$http->on("start", function ($server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$http->on("request", function ($request, $response) {
    $response->header("Content-Type", "text/plain");
    $response->end("Hello World\n");
});

$http->start();
```

![image](https://user-images.githubusercontent.com/5072174/48766087-9e7a8000-ecee-11e8-8d83-8e94cafe9ac7.png)

**Comment by twose** [comment]
Rango's fault... it works but with a wrong warning, I will fix it.

**Comment by twose** [comment]
Sorry, it's a bug on commit 9e1ac6109d04acb0c98296ab5dfaff68748892a2.
