### ISSUE TITLE
Coroutine socket already used error using Mongodb hook

### ISSUE THREAD

**Issue by jrtp** [swoole/swoole-src#2141]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Followed this gist
https://github.com/swoole/swoole-wiki/blob/master/doc/4.17.1%20-%20MongoDB.md
with Mongodb

2. What did you expect to see?

More performance using Mongodb

3. What did you see instead?

Bad performance because the issued crashed most requests

4. What version of Swoole are you using (show your `php --ri swoole`)?

Mongodb 3.5.3 and Swoole 4.2.8 / Php 7.3

5. What is your machine environment used (including version of kernel & php & gcc) ?
4.18.0-2-amd64
PHP 7.3.0RC4 (cli) 
gcc (Debian 8.2.0-9) 8.2.0

**Comment by flddr** [comment]
I am glad to hear that you like **swoole** ☺️ 

Can you please provide some more information for this issue?

-----------------

> More performance using Mongodb

Would be helpful if you post your code (reduced to whats-needed). If you do not want to share it, it should be no problem to send to swoole team. Generally, you can request that here 😉 

---------------------

> Bad performance because the issued crashed most requests

Can you provide some samples or informations about _crashed most requests_?

--------------

> Coroutine socket already used error using Mongodb hook

Generally, error messages should be _copy-and-pasted_ to get as much informations as possible. It's easier to read an issue and provide help 👍 

Maybe, twosee knows already what happens here, but

```bash
Mongodb 3.5.3
PHP 7.3.0RC4 (cli)
gcc (Debian 8.2.0-9) 8.2.0
```
is out of my scope

**Comment by twose** [comment]
Please use released PHP version (or RC5)

**Comment by jrtp** [comment]
Ok, this is a stripped down version, I used Mongodb 1.5.3 and Swoole 4.2.8 (non master)
This is the error from swoole

Swoole startet[2018-11-23 19:57:54 *31343.0]    WARNING is_available (ERROR 10002): Socket#39 has already been bound to another coroutine.
[2018-11-23 19:57:54 $31334.0]  WARNING swManager_check_exit_status: worker#0 abnormal exit, status=255, signal=0

And this is the php code (error appears after a few times reloading)

$server = new swoole_http_server('0.0.0.0', 8000);
$server->on('start', function ($server) {
	echo 'Swoole started';
});
$server->set([
	'worker_num' => 16,
	'enable_coroutine' => true
]);
$server->on('request', function ($request, $response) {
	$mongodb = new MongoDB\Driver\Manager('mongodb://user:pass2000@127.0.0.1:27017');
	$query = new MongoDB\Driver\Query(['_id' => 'de']);
	$cursor = $mongodb->executeQuery('NEWPID_user.page', $query);
	$cursor->setTypeMap(['root' => 'array', 'document' => 'array', 'array' => 'array']);
	$docs = $cursor->toArray();
	$response->end('<pre>' . print_r($docs, true) . '</pre>');
});
$server->start();

**Comment by jrtp** [comment]
Another unrelated question (sorry :) ) - is there a benefit to bind swoole to unix domain sockets instead of ips? I heard that with reactphp this give more performance but some of my tests with swoole didnt show any changes in performance.

**Comment by jobs-git** [comment]
Hi, you are bottlenecked somewhere. In my tests, I get more performance when I am on unix domain socket.

**Comment by jrtp** [comment]
> Hi, you are bottlenecked somewhere. In my tests, I get more performance when I am on unix domain socket.

Can you provide an example on how you setup the server? I think I tried without db and other bottlenecks

**Comment by flddr** [comment]
> is there a benefit to bind swoole to unix domain sockets instead of ips?

The one is IPC, inter process communication, the other one is TCP(IP), transmission control protocol (internet protocol) - which should explain both _main-usages_ - with IPC you can connect programs (processes), the other one works nearly everwhere, but has transport overhead :wink:

**Comment by jrtp** [comment]
Thanks - but which specific code for the server setup did you use? I tried many combinations, maybe yours works better ;)

**Comment by jrtp** [comment]
Ok thank you, I use h2o in front of swoole, so I will look into that again

**Comment by twose** [comment]
obviously, you do not understand the socket cannot be operated by multi coroutines at the same time.
CSP mode is not so easy for starters to understand, so your code maybe syncs blocking.

**Comment by twose** [comment]
Many newcomers make such mistakes. They are always obsessed with simple stress tests without realizing that their code does not have the most basic optimization logic.
I think the swoole cannot act as smart as a high-level language, it's a so basic library, you must implement a connection pool by yourself, some details have already shown in the README, have a look and try it.

**Comment by flddr** [comment]
@jrtp for me feels the same :relaxed: People are binding two chainsaws - with the throttle full open :)

Start small. There are millions of servers online with far less powerful software as you are using now. So, start small, start save :+1:

**Comment by jrtp** [comment]
> @jrtp
> 
> Try the code below
> 
> ```
> $server = new swoole_http_server('0.0.0.0', 8000);
> $server->on('start', function ($server) {
> 	echo 'Swoole started';
> });
> $server->set([
> 	'worker_num' => 16,
> 	'enable_coroutine' => true
> ]);
> $server->on('request', function ($request, $response) {
> 	$mongodb = new MongoDB\Driver\Manager('mongodb://user:pass2000@127.0.0.1:27017',
>     ['appname' => 'co_' . Swoole\Coroutine::getUid()]
> );
> 	$query = new MongoDB\Driver\Query(['_id' => 'de']);
> 	$cursor = $mongodb->executeQuery('DB_name.collection', $query);
> 	$cursor->setTypeMap(['root' => 'array', 'document' => 'array', 'array' => 'array']);
> 	$docs = $cursor->toArray();
> 	$response->end('<pre>' . print_r($docs, true) . '</pre>');
> });
> $server->start();
> ```

Thanks, I actually use a connection pool :) - Using this code the issue is gone but the req/s drop from ~3000 to about 300 :( - With a bit more complex code using a connection pool its basically the same. No error but factor 10 slower.

**Comment by jrtp** [comment]
`$server = new swoole_http_server('0.0.0.0', 8000);
$server->on('start', function ($server) {
	echo 'Swoole started ' . date('d.m.y H:m:s');
});
$server->set([
	'worker_num' => 16,
	'enable_coroutine' => true
]);

$mongodbs = [];
$mongodbs_num = 10;
$query = new MongoDB\Driver\Query(['_id' => 'de']);

$server->on('request', function ($request, $response) {

	GLOBAL $mongodbs;
	GLOBAL $mongodbs_num;
	GLOBAL $query;

	$coroutine = 'x'; // 'co_' . Swoole\Coroutine::getUid();

	if (empty($mongodbs[$coroutine])) {
		$mongodbs[$coroutine] = [];
		for($i = 0; $i <= $mongodbs_num; $i++) {
			$mongodbs[$coroutine][] = new MongoDB\Driver\Manager('mongodb://user:pass@0.0.0.0:27017', ['appname' => $coroutine]);
		}
	}

	$mongodb = $mongodbs[$coroutine][rand(0, $mongodbs_num - 1)];

	$cursor = $mongodb->executeQuery('DB_user.page', $query);
	$cursor->setTypeMap(['root' => 'array', 'document' => 'array', 'array' => 'array']);
	$docs = $cursor->toArray();
	$response->end('<pre>' . print_r($docs, true) . '</pre>');
});
$server->start();`

This is what I used for testing. This works like a charm and gives 4300 req/s with the non_hook version of mongodb. If I enable the hook it throws errors. If I uncomment the $coroutine assignment the performance is extremely bad. Maybe I dont understand something fundamental here?

**Comment by flddr** [comment]
@jrtp sorry. I really like the way you are asking. If i got more time i would like to help you, but actually i found not enough time. I am only on phone actually

**Comment by flddr** [comment]
Isn't Mongo Driver limited to 1 client per process?

If so, you could use a `taskworker` instead? 

I do not use mongo, so, i am not sure about

**Comment by flddr** [comment]
Hmm. I am talking about http://php.net/manual/de/mongo.connecting.pools.php

> The latest versions of the driver have no concept of pooling anymore and will maintain only one connection per process, for each connection type (ReplicaSet/standalone/mongos), for each credentials combination.

**Comment by jrtp** [comment]
I see, actually the performance loss was the same using many connections or just one. I will see if taskworker can be used - thanks!

**Comment by flddr** [comment]
Just as an idea if you want to have **one** active connection (always running), available from all workers :wink: If you will only have _one_ worker, than it isn't really usefull

**Comment by matyhtf** [comment]
The mongodb driver is too complicated. There are many multiplexing mechanisms at the bottom. It may use memory incorrectly and does not support concurrency.

Socket hook cannot be used for mongodb

**Comment by jrtp** [comment]
Sorry to hear but thank you for looking into it. I can understand - unfortunatly mongodb became too complex in many aspects and hardly cleaned up. Since I use a DBAL over it I will see if at somepoint something like badger db is available for php and ideally async ready
