### ISSUE TITLE
Is swoole 2.x version continuing? Is swoole 4.x Backward compatibable to swoole 2.x?

### ISSUE THREAD

**Issue by tomjamescn** [swoole/swoole-src#2142]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
I want to use swoole in my business. We planned using TARS as service manager. But TARS only support swoole 1.x/2.x, NOT support 4.x.  Can I use swoole 4.x in TARS in future ?

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
TARS have already support swoole 4 now.
swoole 4 just refactor the kernel without any PHP API changes.

**Comment by matyhtf** [comment]
Version 2.0 is flawed, please use 4.0, 2.0 will not be maintained.
