### ISSUE TITLE
register_shutdown_function() 触发时机疑问

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/swoole-src#2144]
代码：

```php
<?php

use Swoole\Coroutine;

function test()
{
    Coroutine::sleep(1);
    var_dump('test gg');
}

register_shutdown_function(function(){
    var_dump('all gg');
});

go('test');
```

输出：

```php
string(6) "all gg"
string(7) "test gg"
```

我认为的正常的结果应该是协程里面的执行完，再触发`register_shutdown_function`吧？不知道是有意如此，还是bug

**Comment by matyhtf** [comment]
如果你的脚本末尾没有` swoole_event_wait() `，底层会将` swoole_event_wait() `注册`register_shutdown_function`，执行顺序就会变成上面的。

请在代码末尾加入 `swoole_event_wait();`

**Comment by twose** [comment]
@Yurunsoft 
现在swoole_event_wait永远都是第一位, 结果符合预期
