### ISSUE TITLE
1.7.12 stable task有个小问题，反馈下

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#215]
hi

task,这样可以回调finish
		$server->finish($response_str);
		return;

如果下面直接返回的话，不能回调finish
// 		return $response_str;

php版本5.6.6

gcc:
使用内建 specs。
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

**Comment by matyhtf** [comment]
$response_str 这是string类型吗。只有return string时才会被当成返回信息。.

**Comment by yiliaofan** [comment]
是string类型 已确认新版本1.7.13也有这个问题，帮看下，多谢！

**Comment by matyhtf** [comment]
请使用1.7.14版本。
