### ISSUE TITLE
mongodb error

### ISSUE THREAD

**Issue by rg1978** [swoole/swoole-src#2153]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
php developer.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.2.6

5. What is your machine environment used (including version of kernel & php & gcc) ?
php7.2.6+centos7

**Comment by matyhtf** [comment]
See https://github.com/swoole/swoole-src/issues/2141
