### ISSUE TITLE
Coroutine for other 3rd party server

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#2156]
I have a 3rd party server that swoole might not have a special coroutine class like Mysql & Redis.

In mysql
```swoole\coroutine\mysql```

In redis
```swoole\coroutine\redis```

For 3rd party server, I am expecting sometime like
```swoole\coroutine\others```

But I dont know if It can be done. How do we handle coroutine for other 3rd party servers?

**Comment by matyhtf** [comment]
Please provide more detailed information.I didn't understand your needs.

**Comment by jobs-git** [comment]
I am looking for something similar to `swoole\coroutine\redis` for other 3rd party applications

I will attempt to use `swoole\coroutine\client` for my 3rd party server and see if it works

**Comment by jobs-git** [comment]
I have attempted to use swoole\coroutine\client but it seems the structure was a bit different.

This is what I am trying to do

1.) I have a 3rd party server that does a calculations
2.) The 3rd party server is synchronous like the `mysql server`
3.) Communication to the server is done through IP address and its port
4.) I intend to make it compatible with swoole coroutine and connection pooling

However, to establish connection to the server, a class API needs to be created from within PHP file. It goes this way:

```
$myclient = new clientapi()
$myclient->connection('127.0.0.1',9802);
$myclient->setting1('something');
$myclient->setting2('something_else');
.
.
.
//other settings
```

I am attempting to fit it to swoole using `swoole\coroutine\client` using the code below:

```
        if ($pool_myclient->isEmpty()) {
            $swoole_client = new Swoole\Coroutine\Client(SWOOLE_SOCK_TCP);
            //stuck here
        } else {
            $swoole_client = $pool_myclient->pop();
        }
```

However, I am stuck in the implementation since I have got to communicate to `$myclient` but I should use $swoole_client for coroutine.

**Comment by ValiDrv** [comment]
The idea is to have your recv push the received data to some Swoole\Coroutine\Channel.

**Connect**
```
$client = new Swoole\Coroutine\Client(SWOOLE_SOCK_TCP);
$client->connect($ip, $port,$ timeout);
```
**Receive**
```
# Wait for data
go(function () {
            while (true) {
                $data = $client->recv(-1);
                if ($data === '' || $data === false) {
                    break;
                }
               # You got the data here, push it via Swoole\Coroutine\Channel
              $chan->push($data);
            }
        });
```

**Send**
```
# When you send, the server will reply, and you get it in the ->recv
$client->send($command);
```

I'm doing something similar, stuck on re-connecting... so if you find out how to detect that, please let me know.

**Comment by jobs-git** [comment]
Hey, that answers it, I think, I will be the one to update the PHP API
