### ISSUE TITLE
swoole_websocket_server->push这个多播怎么实现

### ISSUE THREAD

**Issue by chaegumi** [swoole/swoole-src#216]
swoole_websocket_server->push这个只能发给指定的客户端吗，不能所有连接的人吗？怎么做

**Comment by matyhtf** [comment]
可以使用$server->connection_list遍历所有websocket连接，然后循环调用$server->push进行发送。

**Comment by chaegumi** [comment]
好的，谢谢，看来我要多看前边server的文档。
