### ISSUE TITLE
Swoole performance hit when using php file

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#2160]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Tested performance when I move the code to another php file

```php
//18k req/s
$server = new swoole_http_server("127.0.0.1", 9501, SWOOLE_BASE);

$server->set([
    'worker_num' => 1,
    'chroot' => '/home/user'
]);

$server->on('request', function (swoole_http_request $req, swoole_http_response $response){

    switch ($req->server['request_uri']) {
        case '/':
            require 'a.php';
            //$response->end('$swoole_doc');
            break;
        case '/b':
            require 'b.php';
            break;
        .
        .
        .
        //20 other cases
        default:
            header('HTTP/1.0 404 Not Found');
            break;
    }
}
```

a.php
```php
<?php
    $response->end('$swoole_doc');
?>
```

Next I removed the `require 'a.php'` and replace that with the code that is inside `a.php`

```php
//33k req/s
$server = new swoole_http_server("127.0.0.1", 9501, SWOOLE_BASE);

$server->set([
    'worker_num' => 1,
    'chroot' => '/home/user'
]);

$server->on('request', function (swoole_http_request $req, swoole_http_response $response){

    switch ($req->server['request_uri']) {
        case '/':
            //require 'a.php';
            $response->end('$swoole_doc');
            break;
        case '/b':
            require 'b.php';
            break;
        .
        .
        .
        //20 other cases
        default:
            header('HTTP/1.0 404 Not Found');
            break;
    }
}
```

2. What did you expect to see?
Same performance

3. What did you see instead?
Different performance: 18k req/s for `a.php` while 33k for the same code but inside the `case`

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.2.7

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by need-sleep** [comment]
```require 'a.php'``` causes PHP to open and interpret a.php file on every request. File system functions are slow and so is the interpretation process. Also, at 18k+ req per sec it will effect overall system performance (including other PHP processes) from hitting the drive so much to open/read the file. You never want to use require/include in a loop, including a busy event-loop. There's always better ways.

**Comment by jobs-git** [comment]
How, can you suggest a better way so that a larger application could easily be managed?

**Comment by yellow1912** [comment]
Require can be placed outside the loop, then you can call the functions defined inside that required file in the loop.
