### ISSUE TITLE
Question about swoole_object_array (php_swoole.h)

### ISSUE THREAD

**Issue by need-sleep** [swoole/swoole-src#2161]
I need to access objects stored within the ```swoole_objects``` structure (defined in swoole-src/php_config.h) within thirdparty extensions that use the swoole C api. I am currently doing so by packing a pointer to ```swoole_objects``` within an PHP object and obtaining pointer within thirdparty ext from there. Does swoole already have a better way of doing this? Will ```swoole_objects``` still be out of scope if ```swoole_get_object()``` was made accessible with PHP_SWOOLE_API?

**Comment by twose** [comment]
Don't use it
Please see:
http://www.phpinternalsbook.com/classes_objects/custom_object_storage.html
https://wiki.php.net/phpng-upgrading
