### ISSUE TITLE
[bug]$process->start(); 的进程，无法随 master 而被kill掉

### ISSUE THREAD

**Issue by fanybook** [swoole/swoole-src#2163]
addProcess 的就可以

$process->start();的父进程是master
addProcess 的父进程是manager

**Comment by fanybook** [comment]
\Swoole\Process::kill($pid, SIGTERM) 后，start的还在，pid是 master的
swoole版本 4.2.7

**Comment by twose** [comment]
@fanybook 确认一下在v4.2.12下是否正常
