### ISSUE TITLE
Connection could not be established to mysql despite connection pooling

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#2166]
When you have a query that is a bit harder for mysql and a few thousands concurrent connected client. I get an error that connection could not be established, this is despite creating connection pool for mysql. Here is the error:

`PHP Warning:  Swoole\Coroutine\MySQL::prepare(): The MySQL connection is not established`

Then the swoole server dies out, I am expecting that It should not die out and the connection is always established

1. What did you do? If possible, provide a simple script for reproducing the error.

```php
<?php

$pool = new \SplQueue;
# 2: pool startup size

$server = new swoole_http_server("/home/user/swoole.sock", 0, SWOOLE_BASE, SWOOLE_UNIX_STREAM);

$server->on('request', function (swoole_http_request $request, swoole_http_response $response) use ($pool) {

    if ($pool->isEmpty()) {
        $mysql = new Swoole\Coroutine\MySQL;
        $mysql->connect([
          'host' => '127.0.0.1',
          'user' => 'user',
          'password' => 'pwd',
          'database' => 'test'
        ]);
    } else {
        $mysql = $pool->pop();
    }
    $stmt = $mysql->prepare('SELECT * FROM `table` where `col1`=1 ORDER BY `ID` desc LIMIT 20' );
    $result = $stmt->execute();
    # 1: mysql benchmark

    # 3: change to one requested query

    $response->end('whatever'.print_r($result,true));

    $pool->push($mysql);

});

$server->start();

```

2. What did you expect to see?
Connection are always established and swoole server always survives
None dying server is very important for 24/7 applications

3. What did you see instead?
I get an error that connection could not be established, this is despite creating connection pool for mysql. Here is the error:

`PHP Warning:  Swoole\Coroutine\MySQL::prepare(): The MySQL connection is not established`

The swoole server dies out

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.2.7

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
You need to check error after you query the database and try to reconnect and retry.

**Comment by jobs-git** [comment]
Hi, I could not query the error cause swoole server dies too, more over, if the query is very simple I can go upto 40k connections, if I have a bit difficult query, I get only upto 2000 connections/s but at 5k, I now get this error.
