### ISSUE TITLE
BUG! Connection could not be established to mysql despite connection pooling

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#2168]
This is similar to [this CLOSED issue](https://github.com/swoole/swoole-src/issues/2166`)

However, I found that the error seems to be inconsistent with the problem. We can avoid the error discussed in the issue by creating two worker process. Then when you send thousands of concurrent connection, the mysql connection w/ one of the worker process dies. This is also what happens when there is only one worker process `worker_num=>1`

What is unusual here is that when you send 2x more connected client than before, the remaining worker process does not die out. I am expecting that this time, the 2 worker process should get disconnection error. But this does not happen.

**Here is the discussion on the previously closed issue**
When you have a query that is a bit harder for mysql and a few thousands concurrent connected client. I get an error that connection could not be established, this is despite creating connection pool for mysql. Here is the error:

`PHP Warning:  Swoole\Coroutine\MySQL::prepare(): The MySQL connection is not established`

Then the swoole server dies out, I am expecting that It should not die out and the connection is always established

1. What did you do? If possible, provide a simple script for reproducing the error.

```php
<?php

$pool = new \SplQueue;
# 2: pool startup size

$server = new swoole_http_server("/home/user/swoole.sock", 0, SWOOLE_BASE, SWOOLE_UNIX_STREAM);

$server->on('request', function (swoole_http_request $request, swoole_http_response $response) use ($pool) {

    if ($pool->isEmpty()) {
        $mysql = new Swoole\Coroutine\MySQL;
        $mysql->connect([
          'host' => '127.0.0.1',
          'user' => 'user',
          'password' => 'pwd',
          'database' => 'test'
        ]);
    } else {
        $mysql = $pool->pop();
    }
    $stmt = $mysql->prepare('SELECT * FROM `table` where `col1`=1 ORDER BY `ID` desc LIMIT 20' );
    $result = $stmt->execute();
    # 1: mysql benchmark

    # 3: change to one requested query

    $response->end('whatever'.print_r($result,true));

    $pool->push($mysql);

});

$server->start();

```

2. What did you expect to see?
Connection are always established and swoole server always survives
None dying server is very important for 24/7 applications

3. What did you see instead?
I get an error that connection could not be established, this is despite creating connection pool for mysql. Here is the error:

`PHP Warning:  Swoole\Coroutine\MySQL::prepare(): The MySQL connection is not established`

The swoole server dies out

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.2.7

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
you have no error handler, event if it is just `if ($ret === false) { // xxx }`
and, when the error occurred, how many connections you have created? if it's bigger than max connections of MySQL server?
And, I have told you that you can see the example in README, the channel is better to limit the max connection num.
You have a good machine, but you may lack the ability to handle some simple questions.

**Comment by flddr** [comment]
@jobs-git 

Your questions are so much related to other stuff, like **PHP** _itself_, **TCP**/**HTTP**/**HTML**, **system-** and **network-programming** and **DB**.

This is a place for **issues about swoole** and the _understanding_ **_how to use swoole_**

What do you think about learning _those basics_?

--------------

I gave you this snippet above to _start a good way / first touch to learn about your MySQL server_, the timings _it needs_, the connections _it can handle_.

Have a look:

MySQL is _thread-based_ and has therefore other limits than swoole _coroutines_. As far as IO must be handled, maybe, hundreds of coroutines can handle hundreds of IO, while hundreds of threads can do this too. But this scheduling is much harder for threads and much easier for coroutines.

When you query a SQL statement, your MySQL server must load _table data_ into memory, to build new tables, to fullfill your query. With big tables this could take much costs of IO and memory.

If you have an query which will take 1 seconds of CPU, one thread is under pressure. This means _one core_ is 100%. On a 16/32 core machine that means in this case you are limited to around 15 - 30 queries **per second**. But, there is IO too, which must be handled, and scheduling. This has enormous costs. There are several other processes running, OS, swoole, and your benchmark-tool for example ... In this moment, your environment has so much costs in switching between all of them, it might slow down.

Maybe that you understand, that starting thousands of coroutines in swoole is easy to handle - you are right. But you cannot do this with _threads_ and you cannot handle this on a SQL server, which loads high volumes of dates into ram, build new tables, calculate and so on. This SQL server should be dozens of times bigger than your server/s swoole is running on. In a real setup, those things you are benchmarking, will run on serveral machines, not on _one_.

In generally, you are simply overloading your environment and you **must** handle **all those possible things** in **your code**.

This is called **error-handling**.

Please **start coding**.

--------------

If you found a bug in swoole, you will notice that. Please report the messages.

We do not know what you are exaclty doing, but it might pe possible, your code simply is inconsistent.

_Wrong code is no error of swoole_.

**Comment by jobs-git** [comment]
Thank you for the explanation! That means I must find an alternative to mysql for concurrent reads. I will keep looking for a best solution to mysql thread limitations.

**Comment by yellow1912** [comment]
Normally you should have a level of cache (or more) (Redis for example), that way you avoid touching the database as much as possible.

**Comment by flddr** [comment]
> Thank you for the explanation! That means I must find an alternative to mysql for concurrent reads. I will keep looking for a best solution to mysql thread limitations.

No, not directly. You need correct timing or a big machine. That's not a concrete problem of mysql. You simply need error-handling. That's how it's done the usual way.

(btw. and the correct setup to every problem)
