### ISSUE TITLE
Coroutine\Redis类的方法psubscribe没有被阻塞

### ISSUE THREAD

**Issue by 601806081** [swoole/swoole-src#2169]
1. What did you do? If possible, provide a simple script for reproducing the error.
在使用新版本的时候，发现Coroutine\Redis类的方法psubscribe没有被阻塞，于是下载了多个版本进行测试，v4.2.0、v4.2.5....v4.2.9，发现v4.2.6版本之后都有这个问题存在，下面是php脚本
        while (true) {
            $result = $this->redis->psubscribe(['*']);
            if (is_array($result) && count($result) == 4) {
                $taskId = rand(MAX_WORKER, MAX_WORKER + MAX_TASK_WORKER - 1);
                $this->server->sendMessage($result, $taskId);
            }
        }
这里，psubscribe始终返回一个false，进入死循环，cpu飙升，然后一会进程自动重启。

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
升级到最新版本v4.2.9发现有这个问题，然后使用了v4.2.0、v4.2.5、v4.2.6、v4.2.7、v4.2.8这几个版本，发现v4.2.6版本之后就一直有这个问题存在。php是7.2.1版本。

5. What is your machine environment used (including version of kernel & php & gcc) ?
php7.2.1、gcc 8.1.0、centos 6.8 64位

**Comment by matyhtf** [comment]
psubscribe 返回 false时，请检测一下 $redis->errCode 是否为3，如果是，需要调用`connect`方法重现连接服务器。

新的提交已重新更新`connected`属性值。

**Comment by 601806081** [comment]
> psubscribe 返回 false时，请检测一下 $redis->errCode 是否为3，如果是，需要调用`connect`方法重现连接服务器。
> 
> 新的提交已重新更新`connected`属性值。

connected属性一直为TRUE，errCode值为1。此外我启动心跳检测，检测connected的值如果不为TRUE，那么会自动重连

**Comment by 601806081** [comment]
> psubscribe 返回 false时，请检测一下 $redis->errCode 是否为3，如果是，需要调用`connect`方法重现连接服务器。
> 
> 新的提交已重新更新`connected`属性值。

这个和我redis版本有关系吗，我redis3.0.7版本，我使用swoole V4.2.5前的版本都没有，我测试了2.6~2.9版本都有这个问题，errMsg提示Resource temporarily unavailable
