### ISSUE TITLE
我要半路停止task如何操作

### ISSUE THREAD

**Issue by chaegumi** [swoole/swoole-src#217]
我有看到文档中有这个

在onTask回调函数中return字符串，等同于调用finish

那我要直接调用finish可以吗，那个参数是response不是任务id，我就不会做了

**Comment by chaegumi** [comment]
调用finish后，会出一个新的task
调用shutdown后，task照样还在跑

**Comment by matyhtf** [comment]
没明白你的意思。shutdown之后，会等待task执行完毕再退出。

**Comment by chaegumi** [comment]
能不等待task完成就直接把task结束吗

**Comment by matyhtf** [comment]
不可以停止，可以通过kill -9 强制杀死进程。
