### ISSUE TITLE
Swoole with Ioncube Encoded PHP Files

### ISSUE THREAD

**Issue by rebootcode** [swoole/swoole-src#2170]
Can PHP Swoole run PHP file which has been encoded with IonCube?

If yes, does it take ioncube loader automatically or do we need to configure something?

**Comment by twose** [comment]
I don't know too much about it, maybe you should ask IonCube, but the [swoole compiler](https://www.transfon.com/products/swoole-compiler) is the best way.

**Comment by rebootcode** [comment]
There are 100 problems with "swoole compiler"

- It doesn't have a single file compile option.
- It requires GitHub repo to compile the project.
- It's not at all private like "ioncube" has. Ioncube is like - Buy, Download and encode.

I can keep going with the disadvantage of "online swoole compiler". 

If there is any downloadable product of "Swoole compiler" which is personal, private and doesn't require Github repo, I would buy that any day.

**Comment by doubaokun** [comment]
Hi @rebootcode 

Thanks for the feedback about the [PHP Encoder](https://www.transfon.com/products/swoole-compiler). We will add more options regarding how to `upload` source codes.

Compare with other solutions, [Swoole compiler](https://www.transfon.com/products/swoole-compiler) has much better running performance and other advantages.

We will review the price of the self-hosted version, will let you know the price change.

Best,
Bruce
