### ISSUE TITLE
Connecting Redis using unix domain socket

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#2171]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
`$redis->connect('unix:/home/user/redis/redis.sock');`
`$redis->connect('unix:/home/user/redis/redis.sock',0);`
`$redis->connect('unix:/home/user/redis/redis.sock',6379);`

2. What did you expect to see?
I can set & get from Redis since redis is up and running, can also ping.

3. What did you see instead?
Nothings happening, works fine using TCP.

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.2.7

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
Please, print your connect return value and errCode, errMsg.

**Comment by jobs-git** [comment]
For any connection indicated on #1

connection return value: empty, errCode: 6, errMsg: connection is not available

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/04fbdd595979585dd9bc38e8362c4b70dabf1e53
fixed
