### ISSUE TITLE
swoole-http 服务reload 报错

### ISSUE THREAD

**Issue by dahuicyh** [swoole/swoole-src#2177]
PHP 7.2.8  swoole 4.0.4 lumen:5.6

执行reload命令：
 Process::kill($pid, 10);

然后报如下错误：
ERROR   swManager_loop(:443): kill(32499, SIGTERM) [2] failed. Error: No such process[3]

本地没有复现，线上部分机器出现过

**Comment by dahuicyh** [comment]
死循环在这里：不停的输出这条，后来没办法restart解决的
ERROR swManager_loop(:443): kill(32499, SIGTERM) [2] failed. Error: No such process[3]

**Comment by twose** [comment]
请升级到最新版本
