### ISSUE TITLE
Confusing document regarding swoole_timer_tick

### ISSUE THREAD

**Issue by yellow1912** [swoole/swoole-src#2178]
Perhaps due to the wording of this document but I found it very confusing:
https://www.swoole.co.uk/docs/modules/swoole-scheduler

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I have this function 

function test ($param1, $param2) {
   var_dump($param1, $param2);
}

2. What did you expect to see?

I would expect to be able to call it like this:
swoole_timer_tick(1500, "test", [$param1, $param2]);

This way of calling it is similar to call_user_func_array

3. What did you see instead?

Actually, the first variable passed into the callback is ALWAYS the timerId which is fine, but the the second parameter is the array of variable that you pass into the tick. This is kind of...weird because you would expect it to function like call_user_func_array.

One thing with this is that it's also impossible to pass by reference if you want to, unless you pass an object inside.

4. What version of Swoole are you using (show your `php --ri swoole`)?

Latest version from git as of the time this is posted

5. What is your machine environment used (including version of kernel & php & gcc) ?

I think this information is not relevant for this question.

**Comment by doubaokun** [comment]
Based on the API design, the first param for the callback function is the timerId, second param is an array of params passing into the callback function.

Passing by reference is not recommended practice.
