### ISSUE TITLE
onConnect onReceive 顺序异常

### ISSUE THREAD

**Issue by littlemiaor** [swoole/swoole-src#218]
swoole v1.7.12

$serv->set(['dispatch_mode' => 2]);
$serv->on('connect', function($serv, $fd, $from) { printf("fd %d from %d, callback connect\n", $fd, $from); }
$serv->on('receive', function($serv, $fd, $from, $message) { printf("fd %d from %d, callback receive\n", $fd, $from); }

有时 输出类似:

fd 13 from 1, callback receive
fd 13 from 1, callback connect

特别是在连接远程服务器时出现频率很高.

**Comment by matyhtf** [comment]
这个问题已经发现了，在1.7.13中已修复。我们近期会发版本。
