### ISSUE TITLE
php:7.2-alpine (arm) compiles but swapcontext: symbol not found

### ISSUE THREAD

**Issue by keithy** [swoole/swoole-src#2181]
1. What did you do? If possible, provide a simple script for reproducing the error.
```
$ docker run -d -name php72 php:7.2-fpm-alpine
$ docker exec -ti php72 sh
$> apk add --virtual build-dependencies \
	alpine-sdk linux-headers autoconf make gdb \
	libtool libzip-dev pcre-dev libxml2-dev \
	re2c strace tzdata zip pwgen \
	htop git nano #user tools
$> docker-php-source extract
$> pecl channel-update pecl.php.net
$> docker-php-ext-install sockets
$> pecl install swoole
downloading swoole-4.2.9.tgz ...
[answered no to all questions]
$> echo "extension=swoole.so" > /usr/local/etc/php/conf.d/swoole.ini
$> php -v
```
2. What did you expect to see?
```$> php -v
PHP 7.2.12 (cli) (built: Nov 16 2018 16:17:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```
3. What did you see instead?
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' 
(tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so (Error relocating 
/usr/local/lib/php/extensions/no-debug-non-zts-20170718/swoole.so: swapcontext: symbol not found),  ...
PHP 7.2.12 (cli) (built: Nov 16 2018 16:17:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```
4. What version of Swoole are you using (show your `php --ri swoole`)?
see above
5. What is your machine environment used (including version of kernel & php & gcc) ?
```
$ docker -v
Docker version 18.06.1-ce, build e68fc7a
$ uname -a
Linux rock64 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 
2018 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by keithy** [comment]
Version => 2.2.0 works

**Comment by twose** [comment]
We use these, have a try
https://github.com/swoft-cloud/alphp
https://github.com/twose/php-docker/blob/master/7.2-alpine/Dockerfile

**Comment by keithy** [comment]
Thanks, I have tried every pre-requisite package listed in the above examples. Could the problem be arm specific? K.

**Comment by andypost** [comment]
Just got the same issue (on x86 arch) making package for Alpine https://github.com/alpinelinux/aports/pull/5943

**Comment by andypost** [comment]
Log https://build.alpinelinux.org/buildlogs/build-edge-x86/testing/php7-pecl-swoole/php7-pecl-swoole-4.2.12-r0.log
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/buildozer/aports/testing/php7-pecl-swoole/src/swoole-4.2.12/modules/swoole.so' (tried: /home/buildozer/aports/testing/php7-pecl-swoole/src/swoole-4.2.12/modules/swoole.so (Error relocating /home/buildozer/aports/testing/php7-pecl-swoole/src/swoole-4.2.12/modules/swoole.so: swapcontext: symbol not found), /usr/lib/php7/modules//home/buildozer/aports/testing/php7-pecl-swoole/src/swoole-4.2.12/modules/swoole.so.so (Error loading shared library /usr/lib/php7/modules//home/buildozer/aports/testing/php7-pecl-swoole/src/swoole-4.2.12/modules/swoole.so.so: No such file or directory)) in Unknown on line 0
Extension 'swoole' not present.
```

**Comment by therselman** [comment]
On Fedora, I was getting a similar message but `undefined symbol: mysqlnd_find_charset_nr`

I did the following:
```
cd /etc/php.d
sudo nano 50-swoole.ini

extension=swoole
```

Basically I created a new "extension" file in the default location, and added the `extension=swoole` without `.so` (probably doesn't matter) ... but it worked (restarted as well just to make sure!)

**Comment by keithy** [comment]
Probably not important, but I just repeated the steps above with php 7.3 and there was a compilation warning:
```
/tmp/pear/temp/swoole/src/server/master.cc:1224:34: warning: array subscript 0 is above array bounds of 'char [0]' [-Warray-bounds]
     req->filename[filename_length] = 0;
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

**Comment by keithy** [comment]
Swoole 4.3.1 complied and loaded successfully into php7.3, and 7.2, on x86. 
(iMac2006 running Fedora Atomic Host + moby-engine)
Swoole 4.3.1 complied and still unsuccessful on rock64 (arm).

**Comment by andypost** [comment]
On builders the *4.3.1* & 7.2 for x86 & aarch64 it fails to load `swoole.so: swapcontext: symbol not found`
Ref https://github.com/alpinelinux/aports/pull/6826

**Comment by andypost** [comment]
Looks the issue in musl somehow https://www.openwall.com/lists/musl/2018/01/29/2
