### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/remi/php71/root/usr/lib64/php/modules/swoole.so' - /opt/remi/php71/root/usr/lib64/php/modules/swoole.so: undefined symbol: X509_check_host in Unknown on line 0 Extension 'swoole' not present.

### ISSUE THREAD

**Issue by shouhuori** [swoole/swoole-src#2182]
What version of Swoole are you using (show your `php --ri swoole`)?

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/remi/php71/root/usr/lib64/php/modules/swoole.so' - /opt/remi/php71/root/usr/lib64/php/modules/swoole.so: undefined symbol: X509_check_host in Unknown on line 0
Extension 'swoole' not present.
```

What is your machine environment used (including version of kernel & php & gcc) ?

- CentOS release 6.5 (Final)
- Linux ecs-9eca 2.6.32-431.el6.x86_64   SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
- PHP 7.1.24 (cli) (built: Nov  7 2018 18:18:58) ( NTS )
- gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)

**Comment by jobs-git** [comment]
Did you add swoole in your php.ini file?

**Comment by shouhuori** [comment]
@jobs-git  Yes，use pecl and aleady add ` extension=swoole.so` in php.ini.

**Comment by matyhtf** [comment]
What is the version of your OpenSSL and whether OpenSSL is enabled?

**Comment by shouhuori** [comment]
@matyhtf 
```OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL Header Version => OpenSSL 1.0.1e 11 Feb 2013
Openssl default config => /etc/pki/tls/openssl.cnf

**Comment by twose** [comment]
not php's openssl extension, need the openssl library.

**Comment by qingbofish** [comment]
@shouhuori 请问是如何解决的。我也遇到了这个问题

**Comment by shouhuori** [comment]
@shouhuori ，这个是OpenSSL动态链接库的问题。自己[编译安装](https://wiki.swoole.com/wiki/page/6.html)成功了。

**Comment by shuigunixiang** [comment]
> @qingbofish ，这个是OpenSSL动态链接库的问题。自己[编译安装](https://wiki.swoole.com/wiki/page/6.html)成功了。

我也遇到同样的问题  能否具体讲下解决方案 谢谢

**Comment by shuigunixiang** [comment]
> > @qingbofish ，这个是OpenSSL动态链接库的问题。自己[编译安装](https://wiki.swoole.com/wiki/page/6.html)成功了。
> 
> 我也遇到同样的问题 能否具体讲下解决方案 谢谢

@shouhuori

**Comment by shouhuori** [comment]
编译很简单的，按照[文档](https://wiki.swoole.com/wiki/page/6.html)走就可以。
