### ISSUE TITLE
Running swoole_timer_tick and swoole_http_server in the same file?

### ISSUE THREAD

**Issue by yellow1912** [swoole/swoole-src#2183]
I'm on the latest swoole compiled from gitsource, I wonder if it is possible to do something like:

// running some scheduled loop with tick
// we run this every 5 mins
swoole_timer_tick(300000, 'monitorProjectsTick', [$client, $logger, $projectHolder]);

// initiate a server here
$http = new swoole_http_server("monitor.mysite.com", 9501);

It seems like if I run the server, then the tick is not run anymore? If that is the case then what is the recommended way to have both the tick and the server running as the same time?

**Comment by yellow1912** [comment]
Okie, so I'm unsure if this is the right way to do it, but I figured I could create a child process for the tick and put it inside like this:
```
$process = new swoole_process(
    function () use ($client, $logger, $projectHolder) {
        swoole_timer_tick(300000, 'monitorProjectsTick', [$client, $logger, $projectHolder]);
    }
);
```

since the tick is now in a child process, it is executed in parallel with the soole_http_server. But is this the right away to do it? And even if it is, should I do some additional checking to ensure I dont have left over children running if the parent is killed?

**Comment by yellow1912** [comment]
The official document seems to strongly advises against using Process. I wonder if there is any way to use coroutine in this case? The way I see it is that since I want both monitorProjectsTick and the http server to run side by side it is NOT POSSIBLE without using process? Please advise.

**Comment by nkbrs** [comment]
@yellow1912 did you try to run both in a coroutine, then initiate the event loop?

I don't have your particular use case, I run multiple zeromq sockets that bind to an endpoint (a server that binds to multiple ports basically) and it works perfectly when I run each inside a coroutine.

**Comment by jowy** [comment]
If you're still having issues with this, please try the following:

```
$http->start();

$http = new swoole_http_server('127.0.0.1', 9501);

$http->on('start', function () {
    echo "HTTP server is started ... \n";

    swoole_timer_tick(1000, function() {
        echo "Hello from timer!";
    });
});
```

**Comment by yellow1912** [comment]
this is just perfect, thank you @jowy
