### ISSUE TITLE
Coroutine\Http\Client isConnected() 建議

### ISSUE THREAD

**Issue by s890510** [swoole/swoole-src#2184]
最近在調整ConnectionPool，有發現到如果Server端終止連線後，Client端會不清楚
因此能否在 isConnected 加上

	http_client_coro_property *hcc = (http_client_coro_property *) swoole_get_property(getThis(), 0);
	
	char data;
	if(hcc->socket->recv(&data, 1) == 0) {
		RETURN_FALSE;
	}

來做輔助判斷呢？

**Comment by s890510** [comment]
@twose 會這樣說是因為現行的isConnected完全沒有做到符合function name的功能，充其量只能做為isInitial的判斷

**Comment by s890510** [comment]
方便提供範例嗎？
因為我查詢了很久，coroutine/http/client所帶的recv必須要在websocket或是setdefer方能使用
因目前的isConnected看起來並沒有辦法達到確認的效用

**Comment by s890510** [comment]
@twose 
之所以不用PHP代碼實現是因為在整個 coroutine\http\client 無法直接採用recv來進行這動作，
coroutine\http\client 的recv() 根據文件是必須在setDefer或是webSocket模式下才能使用，
這部分無論使用上或是回傳內容都與Socket下的 recv有些許差別！

因為isConnected的使用時機大都是從Pool撈起來的在使用前進行狀態確認使用，
雖然可在得知對口Server以單方面關閉後，將pool中內容清除重置來解決下一個撈出來的client意識無法使用的問題
但這問題若能提早去取得狀態資訊不是更好嗎？

當然，如果認為這用來去Check的殘留物是不好的，那我也沒意見
(不過或許你們有甚麼解法可以去針對這部分做解決？)

**Comment by twose** [comment]
我忘了提http client是自动连接的, 开发者不需要感知是否连接, 这个没有意义.

**Comment by twose** [comment]
你是指连接断开之后的下一次请求会失败吗?

**Comment by twose** [comment]
@s890510 协程改造以后其表现和同步完全一致, 所以没有监测到连接断开事件, 这里需要额外处理, 底层应该自动进行重连, 连接不是客户端需要关心的事.

**Comment by twose** [comment]
是的 在长连接处理上出现了向下不兼容情况

**Comment by s890510** [comment]
最近又發現...
Swoole\Coroutine\Redis()
也是會有類似問題

**Comment by twose** [comment]
@s890510 更新到4.2.10, http 和 redis 底层都增加了keep_liveness, 会在请求前主动侦测连接是否被close.

**Comment by s890510** [comment]
目前測試看起來沒有問題！ Thanks!
