### ISSUE TITLE
fwrite疑似内存泄露

### ISSUE THREAD

**Issue by bnubobby** [swoole/swoole-src#2187]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
   
   测试代码运行后，进行ab 压力测试

2. What did you expect to see?
    应用占用内存平稳
3. What did you see instead?
     应用占用内存不断增大，并且断开测试后，内存占用没有降低
4. What version of Swoole are you using (show your `php --ri swoole`)?
    swoole 4.2.6
    swoole 4.2.9 
5. What is your machine environment used (including version of kernel & php & gcc) ?
     php 7.2

测试代码：
<pre>
<code>

class logger
{
    private static $instances = null;
    protected $stream = null;
    protected $useLocking=false;
    public static function getInstance()
    {
        if (self::$instances == null) {
            self::$instances = new self();
        }
        return self::$instances;
    }
    function info($message)
    {
        if (!is_resource($this->stream)) {
            $this->stream = fopen('/tmp/app.log', 'a');
        }
        if ($this->useLocking) {
            flock($this->stream, LOCK_EX);
        }
        fwrite($this->stream, $message);
        if ($this->useLocking) {
            flock($this->stream, LOCK_UN);
        }
    }
}
$http = new Swoole\Http\Server("0.0.0.0", 80);
$http->set([ 'worker_num'      => 2,'daemonize' => false]);
$http->on('request', function ($request, $response) {
    logger::getInstance()->info("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n");
    $response->end('ok');
});
$http->start();

</code>
</pre>

**Comment by twose** [comment]
先不说内存上涨情况, 你这个代码完全同步阻塞而且还加锁, 内存是否泄漏需要通过工具定位或者长期观察
(如一百万个请求后是否还持续上升? 是否有暴增?)
https://github.com/swoole/swoole-src/issues/2123#issuecomment-439762689
你可以用这个方法测试一下, PHP程序前期内存出现持续上涨是正常的

**Comment by bnubobby** [comment]
@twose 
没有加锁     if ($this->useLocking) {}  这个 useLocking 默认为false
长期观察，会持续上涨，从占用内存50多M，一直到1G多，之后没测试了，期间大概是500万次请求左右

**Comment by bnubobby** [comment]
另外，利用
\Swoole\Runtime::enableCoroutine();
进入协程，情况依旧

**Comment by twose** [comment]
用你的代码我这里没有出现内存持续上涨
```php
class logger
{
    private static $instances = null;
    protected $stream = null;
    protected $useLocking = false;

    public static function getInstance()
    {
        if (self::$instances == null) {
            self::$instances = new self();
        }
        return self::$instances;
    }

    function info($message)
    {
        if (!is_resource($this->stream)) {
            $this->stream = fopen('/tmp/app.log', 'a');
        }
        if ($this->useLocking) {
            flock($this->stream, LOCK_EX);
        }
        fwrite($this->stream, $message);
        if ($this->useLocking) {
            flock($this->stream, LOCK_UN);
        }
    }
}

$pid = getmypid();
$i = 0;
for ($n = 0; $n < 1000 * 1000; $n++) {
    logger::getInstance()->info(str_repeat('x', 10000));
    if ($n % 100 * 1000 === 0) {
        $use_mem = `top -b -n 1 -o RES -p {$pid}`;
        $use_mem = explode("\n", $use_mem);
        $use_mem = array_combine(preg_split('/\s+/', trim($use_mem[6])), preg_split('/\s+/', trim($use_mem[7])));
        echo "RES={$use_mem['RES']} before {$n} requests\n";
    }
}
```

你可以去掉swoole自测一下

**Comment by bnubobby** [comment]
@twose  
有点尴尬，去掉swoole后，用你的代码测试，也是如此
但找出原因了，我使用docker来测试，然后在docker 管理界面查看docker 内存占用，带宽情况等
管理界面显示有误
用系统命令，直接查看进程的情况，显示是正常的。误会一场。 谢谢！
