### ISSUE TITLE
BindParam in Swoole mysql coroutine

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#2194]
mysql `execute()` works fine but when I use `bindParam()` i get error

1. What did you do? If possible, provide a simple script for reproducing the error.
I get error when I use `bindParam()`

2. What did you expect to see?
bindParam works

3. What did you see instead?
```bash
ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Error: Call to a member function bindParam() on boolean
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.2.7

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
it's not pdo, thanks.
if you want to use pdo, please read README (runtime hook part).
