### ISSUE TITLE
timer interval事件触发的时候 后续会支持带参数触发回调么？

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#220]
hi,

看了下源码，目前最新1.7.13稳定版本 不能带一些参数来触发callback，后续有支持计划么？或者能变通实现这个功能么？

目前的interval，貌似使用场景是全局性的触发器？如果带上参数，可细化到一个逻辑操作或动作

如果这样就完美了！非常感谢！

设置定时器。
bool swoole_server->addtimer(int $interval);
bool swoole_server_addtimer(swoole_server $serv, int $interval);

面向对象风格：

$serv->addtimer(1000); //1s
$serv->addtimer(20); //20ms
$serv->on('Timer', 'my_OnTimer');

function my_OnTimer($serv, $interval)
{
    echo "Timer[$interval] is call\n";
}

**Comment by yiliaofan** [comment]
刚才简单的按照timer的interval先临时存下数据，后续触发的时候再拉出数据，暂时解决问题。。感觉有点别扭 非常感谢了！

**Comment by matyhtf** [comment]
1.7.14 版本增加了swoole_server->tick和swoole_timer_tick，和你想要的功能是相同的。
https://github.com/swoole/swoole-src/commit/3ab63b5a23340e318bd7d89f7f91fd1683ca1a13

**Comment by yiliaofan** [comment]
牛逼啊～～～ 超赞！ 多谢！
