### ISSUE TITLE
swProtocol_recv_check_length: package is too big

### ISSUE THREAD

**Issue by longxinH** [swoole/swoole-src#2201]
使用websocket做聊天室，聊天室里面使用tcp连接到其他服务，偶然日志会出现 WARNING	swProtocol_recv_check_length: package is too big, remote_addr=85.93.20.10:649, length=50331699.
swoole版本1.9.10

**Comment by twose** [comment]
版本实在是太低了, 可能有客户端发送了错误的包, 解析出来的长度不正确.
