### ISSUE TITLE
 ERROR   swMsgQueue_pop(:76): msgrcv(2785328, 65536, 0) failed. Error: Identifier removed[43].

### ISSUE THREAD

**Issue by lanjunjia4** [swoole/swoole-src#2202]
![image](https://user-images.githubusercontent.com/13013628/49928184-9501c380-fefa-11e8-9c0a-49f10b11f30a.png)

韩老师，之前看你回答过类似问题，现在我的swooles版本是2.2.也出现了这样的问题？有什么办法解决吗？

**Comment by twose** [comment]
可能是已经修复的问题, 可以先升级到最新版, 2.x版本已废弃.

**Comment by matyhtf** [comment]
消息队列被删除了，请重启服务。
