### ISSUE TITLE
gethostbyname(): must be called in the coroutin

### ISSUE THREAD

**Issue by sohaha** [swoole/swoole-src#2207]
```php
gethostbyname("www.baidu.com");
```

![image](https://user-images.githubusercontent.com/18098083/49989488-42d1a880-ffb5-11e8-8610-f553fc0f9ba6.png)

**Comment by twose** [comment]
写的很清楚了, 你必须在协程里调用该函数.

**Comment by sohaha** [comment]
> 写的很清楚了, 你必须在协程里调用该函数.

问题在于这函数php内置里函数,是可以不在协程里使用的

**Comment by sohaha** [comment]
算了,我直接使用   Runtime::enableCoroutine(false); 关闭了
