### ISSUE TITLE
使用ab压测时max_request到达后worker进程不会重启，并且处理不了请求

### ISSUE THREAD

**Issue by liuzesen** [swoole/swoole-src#2216]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

2. What did you expect to see?
the max_request and reload_async work well.

3. What did you see instead?
My swoole server has two worker process,
one of the worker processes do not restart by the manager process, the other work well.

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole support => enabled
Version => 4.2.1
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
mysqlnd => enabled
redis client => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
docker alpine 3.8 + php7.2

**Comment by twose** [comment]
标题都用中文了内容也用中文吧
需要能够复现的例子或者代码, 只提供现象没办法定位你的问题
现在最新版本是4.2.10-beta, 你可以更新一下再测试

**Comment by liuzesen** [comment]
我是在alpine3.8的环境测试的，看到swoole 4.2.2以有4.2.6版本都有对alpine环境做兼容处理，所以就升级到了4.2.9，现在没有出现worker卡死的问题。
