### ISSUE TITLE
在 Server 的事件处理里的对象会发生变化，请问是 bug 还是 feature

### ISSUE THREAD

**Issue by chrisyue** [swoole/swoole-src#2217]
1. What did you do? If possible, provide a simple script for reproducing the error.

对 Tcp Server 的例子稍微做了些修改：

```php
<?php

$arr = new ArrayObject();
$server = new Swoole\Server('0.0.0.0', 9999);
$server->set([
    'worker_num' => 2, // 我估计是跟 worker 有关，改成 1 之后的确没问题，但肯定不是实际想要的效果
]);
$server->on('connect', function ($server, $fd) use ($arr) {
    echo spl_object_hash($arr), PHP_EOL;
    $arr[] = $fd;
    echo 'connections: ', $arr->count(), PHP_EOL; // 返回链接服务器的客户端数，在多个 worker 的情况下不会返回预期结果，上面也用 spl_object_hash 获取 $arr 对象 id，不同的链接有可能得到不同的对象
});
$server->on('receive', function ($server, $fd, $reactor_id, $data) use ($arr) {
    foreach ($arr as $connected) {
        if ($connected !== $fd) {
            $server->send($connected, sprintf('%s: %s', $fd, $data));
        }
    }
});

$server->start();
```

2. What did you expect to see?

上面代码中，在 connect/receive 事件处理时 `$arr` 都应该是同一个对象

3. What did you see instead?

`$arr` 往往会变成不同的对象

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.2.9

5. What is your machine environment used (including version of kernel & php & gcc) ?

php 7.1.24

最后，如果此问题不是 bug， 请问哪里有相关文档？？

**Comment by lizhichao** [comment]
因为有两个进程，进程内的变量是不共享的。进程之间共享信息需要通过其他方式

**Comment by chrisyue** [comment]
@lizhichao 谢谢回复。这个现象我已经知道了，通过修改 work_num 我已经验证了此问题跟进程有关系（其实通过 spl_object_hash 得到不同的对象 id 也能说明问题）。

我想问的问题，大概有三个：

1. 从语言层面来说，得到这样的结果是正常的吗？
2. 如果是正常的，那么从语言层面本身，我应该通过什么方式共享信息（如果只是为了解决问题，我可以用别的方式，但我就想知道我还有没有办法，能拿到同一个变量，一个不需要数据库/Memcache/文件/... 以及不用 (un)serialize 直接就能拿能用的 PHP 变量）
3. 有文档吗？有可以事先知道这些注意事项的地方吗？

**Comment by twose** [comment]
这和语言没有任何关系, 这应该属于多进程开发的常识, 而且文档搜索功能很容易就可以搜到, 关键字`多进程`, 有很详细的解答
https://wiki.swoole.com/wiki/page/836.html
其实swoole的文档非常详实, 而且很多问题都是基础问题, 只是很多人不愿意去学去看去查, 而且搜索功能是很好用的...
swoole不像传统的php-fpm那么傻瓜, 需要开发者有一定的编程基础和能力, 善用搜索, 循序渐进.
