### ISSUE TITLE
请问 swoole 有没有提供协程版 RedisCluster 的计划？

### ISSUE THREAD

**Issue by photondragon** [swoole/swoole-src#2222]
Redis从3.0开始原生提供集群功能，PHP的集群客户端是 \RedisCluster 类。
目前swoole只提供了 \Swoole\Coroutine\Redis 类，尚未提供协程版 RedisCluster 类。

**Comment by twose** [comment]
predis应该有这个功能
https://wiki.swoole.com/wiki/page/965.html
https://github.com/swoole/swoole-src#-amazing-runtime-hook

**Comment by photondragon** [comment]
用predis或phpredis并开启Runtime::enableCoroutine()虽然能支持协程，但可能会有问题。

我需要创建少量RedisCluster对象，在大量协程之间共享。
**（不可能每个协程都创建一个RedisCluster对象，这样一个worker进程就会用掉大量的Redis连接，Redis服务器支撑不了多少worker进程）**

假设这样一个场景：
GET集群中的某个Key，RedisCluster对象就会访问集群中的某个节点，如果该Key不属于这个节点，节点会返回一个错误以及Key所在的正确的节点，然后RedisCluster再向正确的节点发送请求。

以上情况是一个GET操作实际上发送了两次网络请求，这两个请求应该是作为一个原子操作进行的，中间不可打断。但是如果RedisCluster对象在多个协程间共享，就没法保证这两个网络请求中间不会穿插其它网络请求。这样可能就会出错。

对于PDO对象也有这样的问题，比如事务操作，会有多个网络请求，这些请求应该是一个原子操作，中间不可穿插其它请求。但如果PDO对象在协程间共享，就没法保证了。

所以 Runtime Hook 机制是否有考虑到这种情况，还是说开启了 Runtime Hook，RedisCluster对象或PDO对象就不能在协程之间共享。

**Comment by lizhichao** [comment]
网络io协程都用连接池
