### ISSUE TITLE
Postgres Coroutine - prepared statements

### ISSUE THREAD

**Issue by sagesan** [swoole/swoole-src#2223]
MySQL client has prepared statements, which make SQL injections obsolete.
Having this in PostgreSQL client would be very cool, without it I can't really go into swoole.

**Comment by Indribell** [comment]
The issues with the PostgreSQL driver, do need some work. For instance the PostgreSQL submission for TechEmpowered benchmarks are also dormant to my understanding because off Swoole its old 2.1 PostgreSQL driver was under-developed. Not sure about the 4.2 version, not had time to look at it.

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/pull/2258
