### ISSUE TITLE
How to create something like 'rooms' ?

### ISSUE THREAD

**Issue by ShinJii89** [swoole/swoole-src#2227]
I have swoole 4.2.9

I get it worked - it reads history from mysql in first connect etc. send messages, but I don't know how to create here something like "rooms" ? because I have one server file and for example 100 webchats (rooms)... how to give information to server where it should send message and read history (from which room from database)?

I don't see anything like this in your Docs.... :/

**Comment by jobs-git** [comment]
Then you might have a column in your database that says this is the `room id` then all message on the same room gets the same `room id`. So when a user opens that particular room, your php will query the database about messages with that particular `room id` and displays which ever message you want to display.

This is something that is not tied to SWOOLE. 

You can make a chat room by just using php+ajax then use swoole to speed that UP.

Swoole is not an API for RAPID Development. So if you are expecting something as easy as

```php
swoole_create_chat_room();
swoole_retrieve_chat_messages();
```

then swoole is not for you yet. Those functions are something you CREATE YOURSELF on your OWN first or get somewhere else. Then use swoole to make the chat so FAST and EFFICIENT.

**Comment by ShinJii89** [comment]
Ok, I thought maybe there's something like in socket.io with "join room"... nevermind... I understand that now.

2 more questions:

1. Is this possible to not give a new client id everytime when authenticated user for example refresh a page?

2. It's maybe similar to first question - if someone is not writing anything in chat for 1-2 minutes then he is disconnected - why? How to change this to not disconnect him if he is just reading other people messages - how to change this? I have code like this `'heartbeat_idle_time' => 600,` but it seems not working because I'm disconnected after 1-2 minutes.

**Comment by ShinJii89** [comment]
I don't know... maybe I'm not understand in 100% this stupid websockets but I thought many things I can do with swoole in its settings or something.... in this 2 questions I meant something like this
`$this->server->on('connect', function ($server, $fd) {
            echo "client {$fd} connect\n";
        });`

`$this->server->on('close', function ($ser, $fd) {
            echo "client {$fd} closed\n";
        });`

After start server there's incrementation or something in this $fd... if I refresh page there's for example "client 1 connect", again refresh and there's 'client 1 closed, client 2 connect' etc. - I thought $fd parameter can be changed only somewhere in Swoole settings?... 
Maybe I have to spend more time on reading about websockets and understand it lol.

**Comment by yellow1912** [comment]
Everytime you refresh, the current connection should be closed and a new connection should be created. It will be up to you to detect that the new connection actually belongs to the same user. You can use a token as described above as a way to uniquely identify a user. There are other ways as well but generally speaking it all come back to a token (a unique string) to identify a user I think.

**Comment by ShinJii89** [comment]
Okey, but what about disconnecting people after some idle time? Where to change it? now it's 1-2 minutes without writing to chat and it disconnect me, then I have to refresh a page :/

**Comment by jobs-git** [comment]
use cookie

**Comment by ShinJii89** [comment]
Another question - why is 'max_conn' only 1024? What if I have 10 000 people online on chats? ....

**Comment by ShinJii89** [comment]
@jobs-git any ideas? ;)

**Comment by jobs-git** [comment]
Consider `$serv` is your server instance, I think you can do something like
```php
$serv->set(array(
            'max_conn' => 10000
));
```

Swoole has an excellent documentations in here https://www.swoole.co.uk/docs/modules/swoole-server/configuration

**Comment by ShinJii89** [comment]
Yes it has documentation but it doesn't work that's why I'm writing here.... max_conn is always 1024 if I have higher value ;/ 

> WARNING swServer_start_check: serv->max_connection is exceed the maximum value, it's reset to 1024

Also heartbeat_idle_time doesn't work... I have there value 600 but it still disconnect my clients within 1-2 minutes after no messages...

**Comment by ShinJii89** [comment]
`$this->server = new \swoole_websocket_server("test", 2096, SWOOLE_PROCESS, SWOOLE_SOCK_TCP | SWOOLE_SSL);
        $this->server->set([
            'ssl_cert_file' => '/etc/httpd/conf/ssl.crt/server.crt',
            'ssl_key_file' => '/etc/httpd/conf/ssl.key/server.key',
            'max_conn' => 30000,
            'heartbeat_idle_time' => 6000
                //'daemonize' => 1,
        ]);`

**Comment by jobs-git** [comment]
there is also another maximum connection that is imposed by the OS, you should change that as well. I have not used heartbeat_idle so I dont have idea about it.

**Comment by jobs-git** [comment]
there is also another maximum connection that is imposed by the OS, you should change that as well, and maybe php, but I could not remember well. I have not used heartbeat_idle so I dont have idea about it.

**Comment by ShinJii89** [comment]
Ok I changed limit of connections in some files in CentOS - now it works... but still don't know how to get these "heartbeat" working... it still  disconnects me after 1:40 minute of idle time....
