### ISSUE TITLE
swoole_table 保存，取出乱码

### ISSUE THREAD

**Issue by dahuicyh** [swoole/swoole-src#2231]
PHP7.2   swoole 4.0.4

swoole_table :
'scache' => [//表名，用于接口整个json串缓存
            'size' => 10,//表最大长度
            'columns' => [
                ['name' => 'value', 'type' => Table::TYPE_STRING, 'size' => 300000],//缓存内容最大长度
                ['name' => 'deadline', 'type' => Table::TYPE_INT, 'size' => 10],//缓存到期时间s
            ]
        ],
存进去和取出来长度是一致的，就是部分字符串乱码了导致json解析失败
存进去的json串如下：长度243098

**Comment by matyhtf** [comment]
请将可以重现的 PHP 代码打包，作为附件上传到 github，针对此问题，我们增加了单元测试，未能重现你的问题。

**Comment by mabu233** [comment]
应该是这个问题[#2290] (https://github.com/swoole/swoole-src/issues/2290)
