### ISSUE TITLE
PostgreSQL driver missing from Swoole Pecl

### ISSUE THREAD

**Issue by Indribell** [swoole/swoole-src#2233]
> PHP Fatal error:  Uncaught Error: Class 'Swoole\Coroutine\PostgreSql' not found in 

Source: https://pecl.php.net/package/swoole

The Swoole Pecl comes standard with the Mysql driver but anybody wanting to use the PostgreSQL needs to manually compile the source. This discrepancy between Mysql / PostgreSQL makes no sense. It is more logical to have the PostgreSQL driver also standard included. PostgreSQL, CockroachDB etc all rely on this driver.

**Comment by twose** [comment]
pecl will ask you if `enable postgresql coroutine client support?` and you enter `yes`.

**Comment by Indribell** [comment]
The issue is that pecl + Docker results in nothing being asking. So you are forced to write a big docker installation and compilation script ( and cleanup to prevent the image from bloating ).

Here is my custom solution for people looking at postgresql:

```
FROM php:7.3-alpine

ENV SWOOLE_VERSION=4.2.9

RUN apk upgrade --update \
    && apk add --no-cache --virtual .build-deps linux-headers autoconf libc-dev gcc g++ libstdc++ postgresql-dev make \
    && cd /tmp \
    && curl -sSL "https://github.com/swoole/swoole-src/archive/v${SWOOLE_VERSION}.tar.gz" | tar xzf - \
    && cd swoole-src-${SWOOLE_VERSION} \
    && phpize \
    && ./configure --enable-coroutine-postgresql \
    && make -j$(nproc) && make install \
    && docker-php-ext-enable swoole \
    && apk del .build-deps \
    && apk add --no-cache libstdc++ postgresql-dev libc-dev \
    && rm -r /tmp/swoole-src-${SWOOLE_VERSION} \
    && rm -rf /var/cache/apk/*
```

**Comment by twose** [comment]
If you want use pecl, see https://github.com/zendframework/zend-expressive-swoole/blob/master/.travis/install_swoole.sh
