### ISSUE TITLE
swoole4.2.10+php7.3环境执行preg_match报错

### ISSUE THREAD

**Issue by luoxiaojun1992** [swoole/swoole-src#2235]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
preg_match('/\s+/', '5');

$http = new \Swoole\Http\Server('127.0.0.1', 9501);

$http->on('start', function ($server){
});

$http->on('workerStart', function($server, $id) {
    var_dump(preg_match('//u', '/test2.txt'));
});

$http->on("request", function (\Swoole\Http\Request $request, \Swoole\Http\Response $response) {
});

$http->start();
```

2. What did you expect to see?

int(0)

3. What did you see instead?

[2018-12-21 22:44:26 $31364.0]	WARNING	swManager_check_exit_status: worker#7 abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.2.10, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

swoole support => enabled
Version => 4.2.10
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2q  20 Nov 2018
pcre => enabled
zlib => enabled
brotli => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (including version of kernel & php & gcc) ?

uanme -a
Darwin luoxiaojundeMacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

php -v
PHP 7.3.0 (cli) (built: Dec  7 2018 11:00:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies

gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

openssl -v
LibreSSL 2.6.4

gdb(bt)
#0  0x00007fff6f2c3549 in pthread_mutex_unlock ()
   from /usr/lib/system/libsystem_pthread.dylib
#1  0x00007fff6dff71c7 in objc_class::setInitialized() ()
   from /usr/lib/libobjc.A.dylib
#2  0x00007ffeef11d940 in ?? ()
#3  0x00007fff6c549a5a in libSystem_atfork_parent ()
   from /usr/lib/libSystem.B.dylib
Backtrace stopped: frame did not save the PC

**Comment by matyhtf** [comment]
本地使用 linux 测试上面代码没有问题，请再更新版本后执行 make clean
