### ISSUE TITLE
 client has already been bound to another coroutine#43, reading or writing of the same socket in multiple coroutines at the same time is not allowed.

### ISSUE THREAD

**Issue by louislivi** [swoole/swoole-src#2236]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```php
if ($data) {
    if (isset($this->mysqlClient[$fd][$key])) {
       //pop版本支持的封装
        $client = self::coPop($this->mysqlClient[$fd][$key], $this->dbConfig[$key]['serverInfo']['timeout']);
        if ($client->client->isConnected()) {
            $client->client->send($data);
        }
        $this->mysqlClient[$fd][$key]->push($client);
    } else {
        //里面有协程client
        $client = MySQLPool::fetch($key, $server, $fd);
        if ($client->client->isConnected()) {
            $result = $client->client->send($data);
            if ($result) {
                $this->mysqlClient[$fd][$key] = new Coroutine\Channel(1);
                $this->mysqlClient[$fd][$key]->push($client);
            }
        }
    }
}
```

2. What did you expect to see?

能够控制多协程client的使用

3. What did you see instead?

![image](https://user-images.githubusercontent.com/23403807/50376621-4ff03680-064a-11e9-99ab-832b9dcfdb22.png)
 client has already been bound to another coroutine#43, reading or writing of the same socket in multiple coroutines at the same time is not allowed.

4. What version of Swoole are you using (show your `php --ri swoole`)?

![image](https://user-images.githubusercontent.com/23403807/50376632-8c239700-064a-11e9-96ef-80dd3805e8b9.png)

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by lizhichao** [comment]
使用链接池 ， 推荐框架https://github.com/lizhichao/one

**Comment by twose** [comment]
代码写的不对, 多个协程不能同时使用一个客户端, 这不是支持不支持的问题, 多个协程不可能同时用一个socket发消息, 否则会串包或导致预期之外的严重错误
用fd作区别也是不对的, 同一个连接可能同时发来多个请求, README里有简易的连接池实现, 请去查阅

**Comment by louislivi** [comment]
我就是为了判断同一个fd保存client状态才这样做的。而且我使用了协程通道。为什么还会出现这类问题。。 recv和send在不同协程 也会出行问题吗，请问一下如果不是传统的一问一答client我需要怎么监听recv，之前异步有onRecv 目前协程采用的循环，但是这样我感觉就会有这个问题存在 因为recv需要一个协程挂起

发自我的iPhone


------------------ Original ------------------

**Comment by louislivi** [comment]
@twose

**Comment by twose** [comment]
最新版本由于SSL安全原因移除了读写分离, 这个问题是开发组内部讨论后出于安全性考虑决定暂不支持的, 我个人认为这是一个很重要的功能, 可以再进行讨论

**Comment by matyhtf** [comment]
最新的版本年已实现。
