### ISSUE TITLE
swoole4.2.10创建进程问题

### ISSUE THREAD

**Issue by kokofirst** [swoole/swoole-src#2241]
你好
我升级到4.2.10之后 创建进程时候 出现两个问题：
Fatal error: Swoole\Process::start(): must be forked outside the coroutine.
和
Fatal error: Swoole\Process::__construct(): unable to create process with async-io threads.
发现，4.2.10不能在协程和异步中创建进程了，这个以后还会改回来吗，影响太大了，如果不能在异步中创建进程，也就是说我想 兼顾子进程的回收与重建，还有 动态增加新的进程就不可能了，或是有别的方法可以处理这样的事情吗

**Comment by kokofirst** [comment]
可是 用 co::exec 创建的进程 和 无法进行通信， 也无法使用 swoole_table 共享数据

**Comment by kokofirst** [comment]
我写了一个进程管理器，通过进程管理器来调控子进程的数量，主要是不知道怎么改了，这个东西无法用现有的东西重写了.工作原理是，通过子进程的繁忙度，来和主进程通信，让主进程动态的增加或者减少子进程，现在 协程中不让创建子进程了，就无法同时创建子进程和 回收子进程了

**Comment by matyhtf** [comment]
这两个都是不安全的，因此底层禁止了这种行为。
* AIO 线程，会带线程 fork
* 协程，会复制协程栈，导致出现内存错误

只有 `exec` 是安装的。新的子进程可以使用 `php child.php` 创建一个新的环境。父子进程可以使用 tcp 或 unix socket 进行通信。

**Comment by matyhtf** [comment]
或者，在你的进程管理器中不要使用任何 AIO 和 协程 相关 API
