### ISSUE TITLE
pecl install swoole时报错

### ISSUE THREAD

**Issue by oneDayGo** [swoole/swoole-src#2246]
/usr/include/php/Zend/zend_portability.h:312:52: note: in definition of macro 'UNEXPECTED'
 # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
                                                    ^
make: *** [swoole_async.lo] Error 1
ERROR: `make' failed

**Comment by twose** [comment]
https://github.com/swoole/swoole-src/issues/2119
