### ISSUE TITLE
centos7 php7.2.4 编译安装可以成功， 运行 php --ri swoole 报 “Segmentation fault”

### ISSUE THREAD

**Issue by lklkdawei** [swoole/swoole-src#2247]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
编译安装 php7.2.4
执行的命令如下：
./configure --prefix=/usr/local/php7 --exec-prefix=/usr/local/php7 --bindir=/usr/local/php7/bin --sbindir=/usr/local/php7/sbin --includedir=/usr/local/php7/include --libdir=/usr/local/php7/lib/php --mandir=/usr/local/php7/php/man --with-config-file-path=/usr/local/php7/etc --with-mysql-sock=/var/run/mysql/mysql.sock --with-mhash --with-openssl --with-zlib --enable-zip --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-gd --with-iconv --with-zlib --enable-zip --enable-inline-optimization --disable-debug --disable-rpath --enable-shared --enable-xml --enable-bcmath --enable-shmop --enable-sysvsem --enable-mbregex --enable-mbstring --enable-ftp --enable-pcntl --enable-sockets --with-xmlrpc --enable-soap --without-pear --with-gettext --enable-session --with-curl --with-jpeg-dir --with-freetype-dir --enable-opcache --enable-fpm --disable-fileinfo --with-bz2 --enable-maintainer-zts

make && make install

然后配置了 php 和 php-fpm

安装 swoole
下载的版本 是 swoole-4.2.9

执行命令如下：
./configure --with-php-config=/usr/local/php7/bin/php-config --enable-mysqlnd  --enable-swoole --enable-sockets --enable-hugepage --enable-openssl --with-openssl-dir=/usr/include/openssl/ --enable-http2
make && make install

加入 php.ini 
extension=swoole.so (确实生成了 .so 文件)

执行 
`php --ri swoole
直接报错
Segmentation fault`

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

### php --ri swoole 
报错

5. What is your machine environment used (including version of kernel & php & gcc) ?

php -v(PHP 版本)

PHP 7.2.4 (cli) (built: Dec 26 2018 16:04:12) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

uname -a(内核版本)

Linux hh-jyh-test 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core)
Release:	7.6.1810
Codename:	Core

gcc -v(gcc 版本)
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

通过 gdb 查看的 错误日志

![image](https://user-images.githubusercontent.com/3435608/50438850-cc289980-092a-11e9-863d-b9b7081a45a3.png)

![image](https://user-images.githubusercontent.com/3435608/50440170-ea44c880-092f-11e9-978d-e3fd5f14cb0a.png)

![image](https://user-images.githubusercontent.com/3435608/50440564-bf5b7400-0931-11e9-8583-a70606473772.png)

**Comment by twose** [comment]
Linux 使用大内存页
