### ISSUE TITLE
swoole_http_server的request的bug？

### ISSUE THREAD

**Issue by mingxinkejian** [swoole/swoole-src#225]
ob_start();
$output=ob_get_contents();
ob_end_clean();
if (empty($output)){
	$response->end();
}else{
	$response->end($output);
}
在1.7.14版本中request回调方法里，如果不判断输出是不是空值，而直接将$output传入end方法中，会出现服务器错误。不知是否是bug？

**Comment by matyhtf** [comment]
1.7.15版本中已允许发送空的response.
