### ISSUE TITLE
swoole-4.2.10  build failed with http2

### ISSUE THREAD

**Issue by omyhub** [swoole/swoole-src#2255]
I  build  php5.7.x and swoole  with devtoolset-2 and gcc-4.8.x ，
before   swoole-4.2.10  ,  It works well . 
lastnight , it can't build successfully with  http2 

/apps/libs/nghttp2 -> /apps/libs/nghttp2-1.34.0/

the configure : 
 ./configure --enable-mysqlnd --enable-openssl --enable-http2 --enable-sockets --enable-swoole --with-php-config=/apps/svr/php/bin/php-config --with-nghttp2-dir=/apps/libs/nghttp2/ 
make -j2
...
In file included from /apps/src/swoole-src-4.2.10/swoole.c:16:0:
/apps/src/swoole-src-4.2.10/php_swoole.h:136:2: error: #error "Enable http2 support, require nghttp2 library."
 #error "Enable http2 support, require nghttp2 library."
  ^
make: *** [swoole.lo] Error 1
make: *** Waiting for unfinished jobs....
In file included from /apps/src/swoole-src-4.2.10/swoole_async.cc:17:0:
/apps/src/swoole-src-4.2.10/php_swoole.h:136:2: error: #error "Enable http2 support, require nghttp2 library."
 #error "Enable http2 support, require nghttp2 library."
  ^
make: *** [swoole_async.lo] Error 1

**Comment by matyhtf** [comment]
Need to install nghttp2

```shell
sudo apt install libnghttp2-dev
```
