### ISSUE TITLE
平滑重启后，onRequest里不启动协程了

### ISSUE THREAD

**Issue by mingmingxianseng** [swoole/swoole-src#2262]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
server.php code
```server.php
$server = new \Swoole\Http\Server('0.0.0.0', 9998);
$server->set(
    [
        'pid_file'  => __DIR__ . '/server.pid',
        'daemonize' => 1
    ]
);
$server->on(
    'request', function (\Swoole\Http\Request $request, \Swoole\Http\Response $response) {
    $response->end(\Co::getuid());
}
);

$server->start();
```
`php server.php`
此时访问127.0.0.1:9998  返回结果 是 1、3、5、7.....

reload.php code
```reload.php
swoole_process::kill(file_get_contents(__DIR__ . '/server.pid'), SIGUSR1);
```
这时候执行 `php reload.php`

期望结果  协程id重置  重新计数  1、3、5、7....

实际结果  一直返回-1

2. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

swoole support => enabled
Version => 4.2.11
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2p  14 Aug 2018
http2 => 1.33.0
pcre => enabled
zlib => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

3. What is your machine environment used (including version of kernel & php & gcc) ?
php 7.2.3 
mac
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix

**Comment by twose** [comment]
请更新到v4.2.12
