### ISSUE TITLE
Swoole 能不能实现 PROXY protocol 协议？

### ISSUE THREAD

**Issue by designinlife** [swoole/swoole-src#2269]
我用 Swoole 1.10.5 版本实现的 TCP Socket 服务器。
客户端和服务端之间有一层 TCP 代理转发，想知道这种网络架构下服务端如何获取到客户端的真实IP地址？
看了下 nginx / haproxy 都支持 [PROXY protocol](http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt)，不知道 Swoole 有没有办法在应用层支持？

**Comment by twose** [comment]
Swoole只是个网络通信引擎, 附带了一些简单流行的协议服务, 你需要自己实现.
