### ISSUE TITLE
注册了websocket的onhandshake函数后当websocket握手后没有调用注册的onopen函数

### ISSUE THREAD

**Issue by wisoch** [swoole/swoole-src#227]
服务端同时注册了onhandshake 和onopen函数，但是onhandshake执行了onopen并没有执行
如果不注册onhandshake 函数的话onopen能执行

**Comment by matyhtf** [comment]
感谢反馈，我们稍后会测试一下。

**Comment by matyhtf** [comment]
是这样的，onHandShake用户自定义握手函数中需要执行response->end()，调用此函数后就会销毁request/response对象，所以不会再触发onOpen事件。

需要自行在onHandShake中调用对应的onOpen回调函数。
