### ISSUE TITLE
tcp服务达到SW_SESSION_LIST_SIZE最大值后用户无法链接

### ISSUE THREAD

**Issue by rungao** [swoole/swoole-src#2275]
**php version：**`7.2.12`
**swoole version：**`4.2.9`

#### 场景
对TCP服务进行压力测试，达到100W链接后服务器内存使用和CPU都较少，需对承受压力进行继续测试

#### 问题
使用tcp服务并设置max_connection为200W后，当服务器TCP的链接达到`1*2024*1024`后新链接就无法链接了

#### 定位原因
max_connection设置大于`SW_SESSION_LIST_SIZE`值（1M）后，会自动重置为`SW_SESSION_LIST_SIZE`

#### 疑问
1、`SW_SESSION_LIST_SIZE` 为啥在编码里强制设置为1M？
2、`SW_SESSION_LIST_SIZE` 是否可以手动修改为更大的值来支持更多的用户TCP链接？

**Comment by matyhtf** [comment]
这是一个底层的硬性限制，实际项目单机 1M 几乎不会出现。
由于 Swoole 底层对于 SESSION_LIST 是预先分配的，超过 1M 可能要占用更多内存。

**Comment by rungao** [comment]
你好，韩老师！
我们目前遇到的问题就是实际链接达到1M后机器负载和内存都占用不到总量的50%，所以想继续扩大限制增加连接数，请问直接修改有哪些风险呢？

**Comment by matyhtf** [comment]
可以修改。你测试的目的是什么？

**Comment by rungao** [comment]
如果一台机器能维护更多的同时在线用户，比如本来支持1M，修改为2M后可以节省一半的硬件资源投入，何乐而不为呢。

**Comment by twose** [comment]
`swoole_config.h` 属于底层配置文件, 只是PHP层无法动态配置, 你这样的需求可以更改该值后再编译

**Comment by matyhtf** [comment]
暂时底层不会改变这里的设置，可以考虑使用 swoole_process_pool 开启两个 server 实例。
