### ISSUE TITLE
swoole读写redis cluster失败

### ISSUE THREAD

**Issue by hawkWen** [swoole/swoole-src#2276]
通过swoole连接redis cluster时，写数据返回null，命令有时也无法执行

**Comment by twose** [comment]
一句话问题无法解答

**Comment by hawkWen** [comment]
描述：
通过swoole连接redis cluster时，读写数据失败
swoole貌似无法通过hiredis驱动连接redis集群？

==============
php版本 PHP 7.2.7
swoole版本
swoole

swoole support => enabled
Version => 4.1.0
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled

redis cluster  4.0.12
========
跑的测试代码：
$client = new swoole_redis;
$client->__construct($options = [ 'password' => "********", ]);
$client->connect('*****', ****, function (swoole_redis $client, $result) {
    echo "connect\n";
    $client->set('key', 'swoole', function (swoole_redis $client, $result) {
        echo "set key ret:$result\n";
        $client->get('key', function (swoole_redis $client, $result) {
            var_dump($result);
            $client->close();
        });
    });
});
输出：
connect
set key ret:
bool(false)

**Comment by jesusphp** [comment]
这个问题最后是怎么解决呢？谢谢
