### ISSUE TITLE
How to enable tls on the fly ?

### ISSUE THREAD

**Issue by mcarbonneaux** [swoole/swoole-src#2278]
On [Swoole Server](https://www.swoole.co.uk/docs/modules/swoole-server-doc) how to enable tls on the fly, like they must do on SMTP protocole with STARTLS command  (on receive event)?

**Comment by matyhtf** [comment]
STARTTLS is not supported now

**Comment by tracenull** [comment]
Maybe you need wait for swoole5.0，it's later in the year

**Comment by matyhtf** [comment]
Not yet supported, it is recommended to use nginx to process ssl

**Comment by mcarbonneaux** [comment]
The interest of this is to implement protocol directly in swoole as ligth daemon without any external product...

**Comment by mcarbonneaux** [comment]
you have implemented enablessl in client part... can you add the same in server part ?
https://www.swoole.co.uk/docs/modules/swoole-client-enablessl

with that you can enable ssl on the fly (like client part!)!

**Comment by fakharak** [comment]
An updates on starttls ? Lets get rid of bottleneckings with "ngnix".

**Comment by TatianaOnix** [comment]
Will be STARTTLS supported in the future, it would be good to have it? Or how we can handle TLS encryption in SMTP with nginx or other way? Appreciate any help @matyhtf

**Comment by brightlycolor** [comment]
Will be STARTTLS supported in the future, it would be good to have it? Or how we can handle TLS encryption in SMTP with nginx or other way? Appreciate any help @matyhtf

**Comment by mcarbonneaux** [comment]
the problem are not the support of STARTLS in swoole, but the hability to enable TLS on socket already established to be abel to implement Opportunistic TLS protocol like LDAP, SMTP, IMAP, POP3, ManageSieve...

with this i can develop SMTP server in pure PHP with swolee as backend (i've already implemented with event php module)...
