### ISSUE TITLE
mac下跑examples/ssl 下的例子不能跑通双向认证

### ISSUE THREAD

**Issue by pkdog** [swoole/swoole-src#2280]
在mac下运行master分支的examples/ssl 下的server.php和async_client.php。async_client.php下应该是没有配置相关证书的，理论上它访问server.php应该是会被拒绝的。可是server.php下是配置了ca证书的，而async_client.php却可以在没有配置证书的情况下正常访问server.php。

php版本：7.1
swoole版本：4.2.11
os: macOS 10.13

php --ri swoole 命令的执行结果
`
swoole

swoole support => enabled
Version => 4.2.11
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2q  20 Nov 2018
pcre => enabled
zlib => enabled
brotli => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144
`

**Comment by shiguangqi** [comment]
为了向下兼容，如果客户端没有设置证书，服务端不会进行校验；只有客户端携带证书，底层才会校验。因为原来的逻辑是允许开发者在worker中通过Server->getClientInfo获取客户端证书，自己校验证书的合法性。
