### ISSUE TITLE
swoole读写redis cluster失败

### ISSUE THREAD

**Issue by hawkWen** [swoole/swoole-src#2286]
描述：
通过swoole连接redis cluster时，读写数据失败
swoole貌似无法通过hiredis驱动连接redis集群？

==============
php版本 PHP 7.2.7
swoole版本
swoole

swoole support => enabled
Version => 4.1.0
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled

redis cluster  4.0.12
========
跑的测试代码：
$client = new swoole_redis;
$client->__construct($options = [ 'password' => "123455", ]);
$client->connect('127.0.0.1', 9090, function (swoole_redis $client, $result) {
    echo "connect\n";
    $client->set('key', 'swoole', function (swoole_redis $client, $result) {
        echo "set key ret:$result\n";
        $client->get('key', function (swoole_redis $client, $result) {
            var_dump($result);
            $client->close();
        });
    });
});
输出：
connect
set key ret:
bool(false)

_Originally posted by @hawkWen in https://github.com/swoole/swoole-src/issue_comments#issuecomment-451848024_

**Comment by mabu233** [comment]
你可以试试打印 errCode 和 errMsg

**Comment by twose** [comment]
异步Redis即将移除, 请使用协程 @hawkWen , 并打印错误信息

**Comment by twose** [comment]
异步Redis即将移除, 请使用协程 @hawkWen , 并打印错误信息

**Comment by windrunner414** [comment]
支持了
