### ISSUE TITLE
[Bug]Cookie in swoole_http_request is different from $_COOKIE.

### ISSUE THREAD

**Issue by Uchihaha** [swoole/swoole-src#2287]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Thing is differnt from [document](https://wiki.swoole.com/wiki/page/335.html) said.
```
Http\Request->$cookie
HTTP请求携带的COOKIE信息，与PHP的$_COOKIE相同，格式为数组。
```

**request**
```
curl --cookie "user.name=ponny" "http://localhost"
```
**with php-fpm**
```
array(1) {
  ["user_name"]=>
  string(5) "ponny"
}
```
**with swoole**
```
array(1) {
  ["user.name"]=>
  string(5) "ponny"
}
```
**Why**
PHP replaces Dots (.) and spaces ( ) with underscores (_) when parsing http_header. But swoole parse the cookie in http_header directly. It's original.

2. What did you expect to see?
**with swoole**
```
array(1) {
  ["user_name"]=>
  string(5) "ponny"
}
```

3. What did you see instead?
**with swoole**
```
array(1) {
  ["user.name"]=>
  string(5) "ponny"
}
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
swoole

swoole support => enabled
Version => 4.2.9
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
kqueue => enabled
rwlock => enabled
pcre => enabled
zlib => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144
```

5. What is your machine environment used (including version of kernel & php & gcc) ?
mac10.13.6
php7.2.5

**Comment by twose** [comment]
There may be historical reasons for doing this in PHP, but Swoole not.
I think Swoole's way is better.
