### ISSUE TITLE
找不到 $_SERVER['HTTP_AUTHORIZATION'];

### ISSUE THREAD

**Issue by jinmarcus** [swoole/swoole-src#2293]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

我使用七牛云的业务后，七牛云会回调我的业务服务器，并且发送回调的签名信息
$_SERVER['HTTP_AUTHORIZATION'];

我在$request->server里没有找到这个参数，请问这个应该从哪里获取？

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole 4.2.9

5. What is your machine environment used (including version of kernel & php & gcc) ?
php 7.2

**Comment by twose** [comment]
`$reuqest->header['authorization']`

**Comment by jinmarcus** [comment]
我打印获取到的所有header字段只有：
 [host] => miaojun.vicp.cc:11684
 [user-agent] => qiniu-callback/1.0
 [content-length] => 571
            [content-type] => application/json
            [x-reqid] => bUgAANwdu9_f0HcV
            [x-trace] => 29c3be90ca6d4354/4fdd21d47fa33ae6|0
            [accept-encoding] => gzip

并没有 authorization

**Comment by twose** [comment]
贴一下 $request->getData();

**Comment by jinmarcus** [comment]
POST /godo/notify/cdn_video?token=201802131550 HTTP/1.1 Host: miaojun.vicp.cc:11684 User-Agent: qiniu-callback/1.0 Content-Length: 571 Content-Type: application/json X-Reqid: bUgAAH5Dv2pC_3cV X-Trace: dc11cfd78e0dc456/6d1ac388dd3fd35a|0 Accept-Encoding: gzip {"id":"z0.5c3520b738b9f349c8196c21","pipeline":"1381505097.histar_pipeline","code":0,"desc":"The fop was completed successfully","reqid":"bUgAAH5Dv2pC_3cV","inputBucket":"histar-private","inputKey":"Fov1PXYyVMmRnAMhjhYh8yweFN5B","items":[{"cmd":"avthumb/m3u8/s/544x720/segtime/60/hlsKey/OWNiNDBjZWIzYzI0YTg3NQ==/hlsKeyUrl/L2s=/hlsMethod/qiniu-protection-10|saveas/aGlzdGFyOkZvdjFQWFl5Vk1tUm5BTWhqaFloOHl3ZUZONUIubTN1OA==","code":0,"desc":"The fop was completed successfully","hash":"FmYZaDcui42APosBkCEpih5hUl2i","key":"Fov1PXYyVMmRnAMhjhYh8yweFN5B.m3u8","returnOld":1}]}

**Comment by twose** [comment]
报文里是否有你想要的信息? 可能是PHP或者别的代理模块进行了额外处理, swoole只提供简单的HTTP解析.

**Comment by jinmarcus** [comment]
就是没有，我需要authorization这个参数的值，请问swoole这个header或server里抽取的参数，是不是能在哪自定义？

**Comment by mabu233** [comment]
@jinmarcus 建议用tcpdump抓下数据包确定是不是swoole的问题 [https://wiki.swoole.com/wiki/page/p-tcpdump.html](url)

**Comment by twose** [comment]
@jinmarcus @mabu233 
`var_dump($request->getData());`就是HTTP的原始报文了, 不需要tcpdump查看, 客户端发送的所有数据都在这里, PHP里估计是抽取了其中的数据处理后赋值到了`$_SERVER['HTTP_AUTHORIZATION']`
