### ISSUE TITLE
Can swoole binds to other language?

### ISSUE THREAD

**Issue by 0polar** [swoole/swoole-src#2297]
In [your benchmark](https://github.com/swoole/swoole-src/issues/1401), swoole beats libuv (Node.js under the hood), even beats Nginx / Golang.

Personally I don't want PHP, so I want
- LuaJIT + swoole
- JVM + swoole
- V8 + swoole
- C + swoole

Is these possible?

**Comment by 0polar** [comment]
https://github.com/swoole/swoole-src/issues/1401

**Comment by windrunner414** [comment]
of course

**Comment by need-sleep** [comment]
As you may know most PHP extensions are written in C but mainly to just wrap existing libraries also written in C/C++. For example PHP's MySQL ext wraps functions from the standard libmysqlclient and PHP's Sodium ext wraps functions from the standard libsodium. Swoole on the other-hand created it's own C API for things such as async networking, coroutines, etc. It then exposes this C API to PHP. The underlying C API however does not require PHP and can be built into libswoole rather then the ext swoole.so using ```phpize && ./configure && cmake . && make```. This allows you to use around 99% of swoole's features without depending on PHP. The need for ```phpize``` confuses this as it is a utility for building PHP extensions but the resulting library does not depend on PHP and can be redistributed for use on systems without PHP installed on them. What you build with it is up to you - JNI for Java; native modules for Node.js/V8, duktape, etc; any other framework/language that extends through C/C++ modules, or just strait C or C++ alone. There is no documentation so you need to be ready for a lot of code surfing but they have been good at answering my questions so far.

**Comment by matyhtf** [comment]
Although we can do it, we don't have this plan.
Other languages have many libraries similar to swoole
