### ISSUE TITLE
A question regarding support for early Swoole versions

### ISSUE THREAD

**Issue by need-sleep** [swoole/swoole-src#2298]
I have noticed that you have LTS branches for both Swoole 1 and Swoole 2. How long do you plan to support these versions?

**Comment by matyhtf** [comment]
There's no time limit. If we find a bug, we'll fix it.

**Comment by need-sleep** [comment]
May I suggest that you add this to the default readme.md files for each branch?

**Comment by doubaokun** [comment]
@need-sleep We would suggest upgrade to 4.4.X which is more mature and the official LTS branch, will update README later.
