### ISSUE TITLE
在协程里使用MySQL连接池出现must be called in the coroutine的问题

### ISSUE THREAD

**Issue by haroldphp** [swoole/swoole-src#2301]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
使用自定义的process，逻辑是go(function(){....})

EasySwoole版本：3.0.10

使用EasySwoole框架的提供封装后的连接池，如果连接出错时（例如短暂的数据库不可用或网络波动等），会报PHP Fatal Error级别错误：connect to user@192.168.1.123 at port 3306 fail: 111 Connection refused in /var/www/code/vendor/easyswoole/mysqli/src/Mysqli.php:110

然后数据库或网络恢复后，会报：PHP Fatal error:  EasySwoole\Mysqli\Mysqli::__construct(): must be called in the coroutine，

接着每次协程执行时，就会报：Swoole\Coroutine\Channel::pop(): must be called in the coroutine.（每次执行都会报一次），swoole_server->reload()，process::kill($pid,SIGTERM)这些方式都不行。

大致看了下swoole源码，可能是is_in的逻辑可能没有考虑出现过一次或几次fatal error后的判断处理。

每次协程报这个错误后，协程id又会从1开始

3. What did you see instead?

PHP Fatal error:  Swoole\Coroutine\Channel::pop(): must be called in the coroutine. in /var/www/code/vendor/easyswoole/component/src/Pool/AbstractPool.php on line 181

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole版本：4.2.12

5. What is your machine environment used (including version of kernel & php & gcc) ?

PHP版本：7.2.13

**Comment by twose** [comment]
自定义process里没有协程环境 需要手动创建

**Comment by haroldphp** [comment]
是手动创建的，go(function(){....}); 
我可能没太说清楚，在自定义进程里逻辑执行，只要不出错，就没有任何问题，其中某次，一旦报fatal error错误，就会出现这个错误提示。

**Comment by haroldphp** [comment]
easyswoole自带的MySQL连接池就是基于swoole_mysql协程客户端的，如果自定义进程里面没有用协程，肯定直接就不能执行啊，我这里的问题是，自定义进程的协程环境里，正常执行没任何问题，只要有一次出现fatal error，下一次循环执行就会一直报这个错误。

` $this->addTick(5000,function(){
            Logger::getInstance()->log("Process running");
            \go(function (){
                $this->run();
            });

        });`

**Comment by twose** [comment]
提交了一个测试, 请看一下是否和你的情况一致
https://github.com/swoole/swoole-src/commit/72c995157f8f60bf0a374022697a45e751fb7fac

**Comment by windrunner414** [comment]
fatal error之后进程退出，重新创建新的，协程id就从1开始了

**Comment by haroldphp** [comment]
等周末的时候看下，我这里的是用server->tick定时隔几秒跑的go(function(){...})，go里面的逻辑里面抛出fatal错误

**Comment by haroldphp** [comment]
<?php
/**
 * Created by PhpStorm.
 * User: harold
 * Date: 2019-01-14
 * Time: 09:55
 */
use Swoole\Coroutine\Channel;
use Swoole\Process;



class MyProcess
{
    protected $chan;
    protected $client;


    private $swooleProcess;
    private $processName;
    private $async = null;
    private $args = [];

    final function __construct(string $processName,array $args = [],$async = true)
    {
        $this->async = $async;
        $this->args = $args;
        $this->processName = $processName;
        $this->swooleProcess = new \swoole_process([$this,'__start']);
    }

    public function getProcess():Process
    {
        return $this->swooleProcess;
    }

    function __start(Process $process)
    {
        if(PHP_OS != 'Darwin'){
            $process->name($this->getProcessName());
        }

        if (extension_loaded('pcntl')) {
            pcntl_async_signals(true);
        }

        $this->run($this->swooleProcess);
    }

    public function getProcessName()
    {
        return $this->processName;
    }

    public function run(Process $process)
    {
        $this->addTick(2000,function(){
            \go(function (){
                echo "\n\nCurrent Coroutine id is : ".\Swoole\Coroutine::getuid() . "\n";
                //直接运行代码，没有写捕获异常逻辑
                $this->runSomeCode();
            });

        });
    }

    public function addTick($ms,callable $call):?int
    {
        return self::loop(
            $ms,$call
        );
    }

    public static function loop($microSeconds,callable $func,$args = null){
        global $server;
        $new = function (...$args)use($func){
            try{
                call_user_func($func,...$args);
            }catch (\Throwable $throwable){
                echo $throwable->getMessage();
            }
        };
        return $server->tick($microSeconds,$new,$args);
    }

    //执行逻辑代码
    protected function runSomeCode()
    {
        //正常逻辑代码
        try {
            //定时执行，easyswoole的AbstractPool类有定时回收闲置连接池，测试代码只是模拟一下问题，定位是这里如果逻辑出现一次错误后，此处后面执行就会频繁报错\Swoole\Coroutine\Channel::pop(): must be called in the coroutine.
            swoole_timer_tick(2000,function(){
                echo "pop from channel\n";
                $this->chan->pop();
            });

            $this->getPool();
            mt_srand();
            //随机一次抛出异常
            $rand = mt_rand(1,3);
            echo "current rand is : ".$rand."\n";

            //此处是为了模拟多次情况下，其中某一次不正常的情况
            if ($rand != 3) {
                var_dump('execute some logic');
            } else {
                throw new \Exception("some error");
            }
        } catch (\Throwable $throwable) {
            throw $throwable;
        }
    }


    protected function getPool()
    {
        $this->chan = new Channel(5);
        $this->chan->push('test');
        return $this->chan->pop();
    }
}


$server = new \Swoole\Server('127.0.0.1', '9501', SWOOLE_PROCESS, SWOOLE_SOCK_UDP);
$server->set([
    'log_file' => '/tmp/swoole.log',
//    'daemonize'=> 1
]);
$server->on('packet', function () { });
$server->addProcess((new MyProcess('test'))->getProcess());
$server->start();
?>

说明：
1.这里的代码，只是精简模拟的代码

2. 如果捕获抛出的异常（easyswoole连接超时会抛一个异常），不会有这种问题，但如果代码层级很深，很复杂的逻辑有遗漏捕获异常的情况下，而且逻辑里面有定时逻辑，每次定时执行时就出现这种问题，只能重新启动server了；

3. 提这个issue，主要是想排查是不是因为swoole_time_tick由于没有捕获异常，而导致后续持续报这种Fatal error: Swoole\Coroutine\Channel::pop(): must be called in the coroutine.这种错误

**Comment by twose** [comment]
底层永远不会捕获异常 异常抛出后进程会直接结束并重启 用你的代码没有出现`must be called in the coroutine`

**Comment by mabu233** [comment]
@haroldphp 你看下这个测试和你的是不是一致 [0bdbc4e](https://github.com/swoole/swoole-src/pull/2310/commits/0bdbc4e59f27db3b79b0072e84f4fd25cb6ffb38)
#2310 我测试了你的代码，这个修复应该可以解决你的问题

**Comment by haroldphp** [comment]
我刚下班回来，特意回家用自己电脑重新跑了一遍，和之前的结果一样，跑的时候。多等一会儿就出现了@twose

**Comment by matyhtf** [comment]
由于 user process 和 task worker 一些状态未能正确设置导致，已修复。
