### ISSUE TITLE
当我在server的start回调方法中试图创建一个redis的协程,出现了问题!

### ISSUE THREAD

**Issue by Iamzz-cn** [swoole/swoole-src#2308]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

````
$server = new \Swoole\Server('0.0.0.0', 9501, SWOOLE_BASE, SWOOLE_SOCK_TCP);
$server->set([
    'debug' => true,
    'worker_num' => 4,
    'backlog' => 128,
    'log_level' => 2,
]);
$server->on('start', function () {
    \Swoole\Coroutine::create(function () {
        $redis = new \Swoole\Coroutine\Redis();
        $redis->connect('127.0.0.1', 6379);
        while (true) {
            $msg = $redis->subscribe(['task']);
        }
    });
});
$server->on('Receive',function (swoole_server $server, int $fd, int $reactor_id, string $data){
    //什么是都不做
});
$server->start();
````

2. What did you expect to see?

3. What did you see instead?

````
[2019-01-12 20:37:09 *13712.1]  ERROR   swReactorEpoll_add(:135): add events[fd=3#0, type=1, events=1] failed. Error: File exists[17].
[2019-01-12 20:37:09 *13712.1]  ERROR   swReactorEpoll_add(:135): add events[fd=8#1, type=5, events=1] failed. Error: File exists[17].
[2019-01-12 20:37:09 *13712.1]  ERROR   swReactorEpoll_add(:135): add events[fd=9#1, type=5, events=1] failed. Error: File exists[17].
[2019-01-12 20:37:10 #13694.0]  WARNING swProcessPool_wait: worker#3 abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.2.10, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.
````

4. What version of Swoole are you using (show your `php --ri swoole`)?

````

swoole

swoole support => enabled
Version => 4.2.10
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
debug => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
````

5. What is your machine environment used (including version of kernel & php & gcc) ?
`
Linux 10-9-75-196 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`
`
PHP 7.2.6 (cli) (built: Jul 25 2018 12:44:15) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
`
`
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 
`

**Comment by windrunner414** [comment]
不要在start回调里做这些，可以在workerStart中使用或者单独创建自定义进程
[https://wiki.swoole.com/wiki/page/p-event/onStart.html](https://wiki.swoole.com/wiki/page/p-event/onStart.html)

> onStart回调中，仅允许echo、打印Log、修改进程名称。不得执行其他操作。onWorkerStart和onStart回调是在不同进程中并行执行的，不存在先后顺序。

> onStart和onShutdown事件是在master进程的master线程内执行，执行过多异步IO操作可能会带来安全隐患，因此底层关闭了异步IO。

**Comment by matyhtf** [comment]
BASE 模式下，onStart 存在错误，这里是 Manager 进程，请勿使用任何异步和协程的 API

**Comment by matyhtf** [comment]
最新的代码，废弃 BASE 模式下的 onStart 事件回调，改为使用 onManagerStart 和 onManagerStop，禁止使用任何 异步协程 API
