### ISSUE TITLE
这个是什么错误，我看不懂这么高深的东西，求解答

### ISSUE THREAD

**Issue by chaegumi** [swoole/swoole-src#231]
[2015-04-03 14:33:52 #24955.0]	WARN	swFactoryProcess_manager_loop: worker#7 abnormal exit, status=0, signal=11

我netstat -anp|grep 9501 已经kill没了，再启动也不行

**Comment by chaegumi** [comment]
PHP Version 5.4.35
swoole support	enabled
Version	1.7.12
Author	tianfeng.han[email: mikan.tenny@gmail.com]
epoll	enabled
eventfd	enabled
timerfd	enabled
signalfd	enabled
accept4	enabled
cpu affinity	enabled
spinlock	enabled
rwlock	enabled
Linux Native AIO	enabled
Gcc AIO	enabled

Directive	Local Value	Master Value
swoole.aio_thread_num	2	2
swoole.display_errors	On	On
swoole.message_queue_key	0	0
swoole.unixsock_buffer_size	8388608	8388608

**Comment by matyhtf** [comment]
http://182.254.148.72:9501/wiki/page/10.html

**Comment by chaegumi** [comment]
新版的已经解决
