### ISSUE TITLE
Swoole MySQL Statement bindValue (bit type)

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/swoole-src#2315]
目前有用到了`bit`类型字段，在`PDO`中需要用`bindValue`指定类型为`BOOL`或`INT`才可正常查询。

但是 Swoole 的 MySQL Statement 并没有提供这样的功能，也没有对`execute`方法传入的参数做类型差异化处理。

**Comment by twose** [comment]
下个版本支持

**Comment by twose** [comment]
不是很好支持, 通过如`chr(255)`这样的方法, 将数字转为字符串, 传入参数, 即可正确设置比特位
此时比特为`1111 1111`
