### ISSUE TITLE
Http\Response buffer_output_size 问题反馈

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/swoole-src#2326]
代码：

```php
$server = new \Swoole\Http\Server('0.0.0.0', 21211);
$server->set([
    'http_compression'  => false,
    'buffer_output_size'=> 2 * 1024 * 1024,
]);
$server->on('request', function(swoole_http_request $request, swoole_http_response $response) use($server){
    $str = str_repeat('a', 2 * 1024 * 1024);
    $response->end($str);
});
$server->start();
```

警告信息：

```
WARNING swServer_tcp_send (ERROR 1202): More than the output buffer size[2097152], please use the sendfile.
```

返回数据略大时，想使用`write()`分批发送也是一样的问题，不知道每一次`write()`使用多大的数据为好。`Http Server` 发送数据的缓冲区，是否应该底层做一下处理。毕竟如果用`sendfile()`会很不方便，性能也不好。

**Comment by twose** [comment]
`buffer_output_size `是tcp的缓冲区长度, http使用write时会有冗余信息, 稍微减少几个字节就能发出去了.

**Comment by mabu233** [comment]
@twose 好像还得减去http header的长度

**Comment by Yurunsoft** [comment]
最好能有办法先发送掉header，或者获取待发送的header长度，这样就能够做处理了

**Comment by twose** [comment]
header和分块编码都不会太长 适当调大`buffer_output_size `即可

**Comment by matyhtf** [comment]
1. 可以调大 buffer_output_size 的值，也可以使用 write 分片，write 最大安全的长度是  `buffer_output_size - 头长度`，(CRLF[2 byte] + 16进制长度头[6 byte, 2**24=16M])
2. 使用 base 模式，最新的代码中 base 模式去掉了 buffer_output_size 的检测，仅受 `socket_buffer_size` 长度限制
