### ISSUE TITLE
websocket如何获取客户端ip

### ISSUE THREAD

**Issue by xxluan** [swoole/swoole-src#233]
在 examples/websocket/server.php 的on 'message' 方法里边，如何获得客户端ip

**Comment by matyhtf** [comment]
$server->connection_info($frame->fd)

**Comment by xxluan** [comment]
前面用nginx，通过 $server->connection_info($frame->fd)，获取到的ip是 127.0.0.1
怎么解决？

**Comment by matyhtf** [comment]
可以在onOpen事件中，读取 $req->header中的相关信息

**Comment by nfer** [comment]
通过var_dump($req->header);并未得到客户端的ip，实际上$req->header保存是客户端的Requst请求(已与Firefox中的Firebug中的显示进行对比)。
试问HTTP的Request请求中，怎么会包含自己的host信息呢？

**Comment by xyzj91** [comment]
请问下我在swoole\server中新增监听一个端口,启用了websocket协议解析.在onOpen的回调中拿到的server对象为什么是swoole\server对象而不是websocket\server对象,而在onMessage回调中拿到的却是websocket\server对象,按理来说在onOpen回调中的server对象不应该是websocket\server对象吗?
