### ISSUE TITLE
woker process not restart, after kill it

### ISSUE THREAD

**Issue by bobzhangyong** [swoole/swoole-src#2335]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
我用一个c代码拉起了swoole http server，kill worker 进程，不能自动拉起。
原因是 c 代码中 设置了 signal(SIGCHLD, SIG_IGN); 然后使用execl 函数拉起swoole，这个设置会被新拉起的进程 继承，导致swoole wait 函数没有返回。

execl 文档，建议新拉起的进程 在启动后，重新初始化 SIGCHLD 信号量设置。
[https://linux.die.net/man/3/execve](https://linux.die.net/man/3/execve)

> Signals set to the default action (SIG_DFL) in the calling process image shall be set to the default action in the new process image. Except for SIGCHLD, signals set to be ignored (SIG_IGN) by the calling process image shall be set to be ignored by the new process image. Signals set to be caught by the calling process image shall be set to the default action in the new process image (see <signal.h>). If the SIGCHLD signal is set to be ignored by the calling process image, it is unspecified whether the SIGCHLD signal is set to be ignored or to the default action in the new process image. After a successful call to any of the exec functions, alternate signal stacks are not preserved and the SA_ONSTACK flag shall be cleared for all signals.

c代码如下
```c++
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>  
#include <string.h>
#include <fcntl.h> 
#include <cerrno>

using namespace std;

static pid_t *childpid = NULL;/* ptr to array allocated at run-time */
#define SHELL   "/bin/sh"
#define CMDSTR   "/data/yong/yong_sw.sh"

int main(int argc, char const *argv[])
{
    signal(SIGCHLD, SIG_IGN);
    string sCmd = CMDSTR;
    execl(SHELL, "sh", "-c", sCmd.c_str(), (char *) 0);
    return 0;
}
```
shell 如下

```shell
#!/bin/sh

/data/env/runtime/php-7.1.7/bin/php /data/yong/yong.php
```

php 代码如下
```php
$server = new \swoole_http_server("0.0.0.0", 9095, SWOOLE_PROCESS, SWOOLE_SOCK_TCP);

$server->set([
    'worker_num' => 5,
    'dispatch_mode' => 3,
    'daemonize' => 1,
    'buffer_output_size' => 12582912,
    'open_tcp_nodelay' => true,
    'open_eof_check' => false,
    'open_eof_split' => false,
]);

$server->on('connect', function ($serv, $fd) {
    echo "Hello world! $fd \n";
});

$server->on("receive", function ($serv, $fd, $from_id, $data) {
    $serv->send($fd, 'Swoole: '.$data);
    echo "fd: $fd, from_id: $from_id, data: $data \n";
});

$server->on('close', function($serv, $fd) {
    echo "Client: close \n";
});

$server->on('Receive', function($serv, $fd) {
    echo "onReceive \n";
});

$server->on('Request', function($serv, $fd) {
    echo "onRequest \n";
});

$server->start();

```

2. What did you expect to see?

kill worker 后自动拉起

3. What did you see instead?

worker 没有自动拉起

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole
```
swoole support => enabled
Version => 2.1.3
Author => tianfeng.han[email: mikan.tenny@gmail.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```
5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by matyhtf** [comment]
我这里使用最新的master分支代码未能重现此问题，Swoole 底层并不依赖 SIGCHLD 信号。
