### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/swoole.so' - /usr/lib64/php/modules/swoole.so: undefined symbol: X509_check_host in Unknown on line 0

### ISSUE THREAD

**Issue by shuigunixiang** [swoole/swoole-src#2339]
centos6.5
php7.0
gcc 4.4.7
OpenSSL 1.0.2l  25 May 2017
安装swoole 2.2.0  打开enable-openssl选项
php --ri swoole 如下报错
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/swoole.so' - /usr/lib64/php/modules/swoole.so: undefined symbol: X509_check_host in Unknown on line 0
Extension 'swoole' not present.
请问是什么原因

**Comment by matyhtf** [comment]
```shell
which php
ldd /usr/bin/php
```

请查看php链接的openssl库是什么版本？可能你编译使用的是新版本，但运行时使用的是旧版本。
