### ISSUE TITLE
swoole开启协程会影响进程平滑重启

### ISSUE THREAD

**Issue by Dean0820** [swoole/swoole-src#2348]
CentOS 6.5 (Final)
PHP Version => 7.1.1
Swoole Version => 4.2.4 （升级到4.2.12还是一样）
gcc version 4.8.5 (GCC) 

1、问题描述
发现开启了协程在里面执行IO阻塞操作，程序还在执行中直接reload进程，这时候已经在执行的脚本会中断执行不能平滑重启，请问怎么操作才能保证进程平滑重启

2、具体使用示例
这个是swoole server的配置
// 退出等待时间
'max_wait_time' => 60,
// 异步安全重启
'reload_async' => true,

这是业务代码
go(function () {
Log::debug('Server start');
for($i = 0; $i < 5; $i++){
Log::debug('Server '.$i);
\Swoole\Coroutine::sleep(1);
}
Log::debug('Server end');
});

执行中没有reload的执行结果
[time] 2019-01-29 09:53:12 [message] Server start
[time] 2019-01-29 09:53:12 [message] Server 0
[time] 2019-01-29 09:53:13 [message] Server 1
[time] 2019-01-29 09:53:14 [message] Server 2
[time] 2019-01-29 09:53:15 [message] Server 3
[time] 2019-01-29 09:53:16 [message] Server 4
[time] 2019-01-29 09:53:17 [message] Server end

执行中有reload的执行结果
[time] 2019-01-29 09:53:25 [message] Server start
[time] 2019-01-29 09:53:25 [message] Server 0
[time] 2019-01-29 09:53:26 [message] Server 1

**Comment by twose** [comment]
贴出具体代码, reload有超时时间

**Comment by Dean0820** [comment]
> 贴出具体代码, reload有超时时间

这个是swoole server的配置
// 退出等待时间
'max_wait_time'    => 60,
// 异步安全重启
 'reload_async'     => true,

这是业务代码
go(function () {
    		Log::debug('Server start');
    		for($i = 0; $i < 5; $i++){
    			Log::debug('Server '.$i);
    			\Swoole\Coroutine::sleep(1);
    		}
    		Log::debug('Server end');
    	});

执行中没有reload的执行结果
[time] 2019-01-29 09:53:12 [message] Server start
[time] 2019-01-29 09:53:12 [message] Server 0
[time] 2019-01-29 09:53:13 [message] Server 1
[time] 2019-01-29 09:53:14 [message] Server 2
[time] 2019-01-29 09:53:15 [message] Server 3
[time] 2019-01-29 09:53:16 [message] Server 4
[time] 2019-01-29 09:53:17 [message] Server end

执行中有reload的执行结果
[time] 2019-01-29 09:53:25 [message] Server start
[time] 2019-01-29 09:53:25 [message] Server 0
[time] 2019-01-29 09:53:26 [message] Server 1

**Comment by matyhtf** [comment]
请按照 issue 模板提交问题，贴出相关环境信息。

**Comment by Dean0820** [comment]
> 请按照 issue 模板提交问题，贴出相关环境信息。

相关信息已经加上，感谢回复

**Comment by matyhtf** [comment]
底层 bug，已修复，请使用最新的代码进行测试。
