### ISSUE TITLE
swoole coroutine http2 concurrent request problem

### ISSUE THREAD

**Issue by ozgurhangisi** [swoole/swoole-src#2353]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

We use swoole on our production system for 6 months and I'm so happy with the performance. Perfect job guys. Thank you so much for this amazing library.

I try to send Apple Push Notifications using swoole http2 and apns http2 service with the code below. new apns2 service allows users to send concurrent request to the server. But I couldn't manage how to do this. If I try to create new go() function in foreach($Notifications as $notification)  loop I get an error from swoole (It says something like I can not send concurrent requests to http2 client) and the code below takes too much time to finish.
```php
<?php

use Swoole\Coroutine as co;
// SOME CODE TO PREPARE NOTIFICATIONS, AUTHENTICATIONS,ETC...
go(function () use ($Authentication,$apns2_url,$Notifications) {
    $cli = new co\Http2\Client($apns2_url[$Authentication['APNS']['ENVIRONMENT']]['url'], $apns2_url[$Authentication['APNS']['ENVIRONMENT']]['port'], $apns2_url[$Authentication['APNS']['ENVIRONMENT']]['ssl']);
    $cli->set([ 'timeout' => 5,
        'ssl_cert_file'=>$Authentication['APNS']['PEMFILE'],
        'ssl_key_file'=>  $Authentication['APNS']['PEMFILE']
    ]);
    $req = [];
    $resp = [];
    $i=0;
    $cli->connect();
    $req[$i] = new swoole_http2_request;
    foreach($Notifications as $notification) {
            $req[$i]->path = '/3/device/'.$notification->token;
            $req[$i]->headers = ['apns-topic'=>$Authentication['APNS']['WEBSITEID'],'Content-Type'=>'application/json','user-agent'=>'APNS2'];
            $req[$i]->data = $notification->getPayload();
            $req[$i]->method = 'POST';
            $res = $cli->send($req[$i]);
            $resp[$i] = $cli->recv();
            $notification->response = $resp[$i];
            $i++;
    }
    $cli->close();
});
Swoole\Event::wait();
?>
```
2. What did you expect to see?

Is it possible to send concurrent request with http2 like $cli->post('URLPath',$headers,$data,$responseCallback); 

So I don't need to wait for previous request to finish to send new push. I can send all of the pushes concurrently and I can process results in responseCallback function.

I also tried swoole_http2_server but I got Class swoole_http2_server not found error. 

3. What did you see instead?

I can not send concurrent requests to http2 server. If I send pushes one by one it takes too much time. (We have millions of push tokens and for 100 push notifications it takes 18 seconds to finish.)

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.2.12
Built => Jan 29 2019 20:54:51
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2q  20 Nov 2018
http2 => 1.35.1
pcre => enabled
zlib => enabled
brotli => enabled
mysqlnd => enabled
async_redis => enabled
```
5. What is your machine environment used (including version of kernel & php & gcc) ?

php 7.3.1, MacOsX Sierra

**Comment by twose** [comment]
```php
foreach() {
    // send
}
foreach() {
  // recv
}
```
or you can see:
https://github.com/swoole/swoole-src/blob/master/tests/swoole_http2_client_coro/multi.phpt
https://github.com/swoole/swoole-src/tree/master/tests/swoole_http2_client_coro
https://github.com/swoole/swoole-src/tree/master/tests/swoole_http2_server

**Comment by ozgurhangisi** [comment]
Thank you so much for the answer. I tested now and 1000 send & receive finished in 1 sec in my laptop. It's really good. Probably I'll get better results on our production servers.
