### ISSUE TITLE
Missing zero copy implementation in swoole

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#2356]

**Comment by matyhtf** [comment]
Please describe in detail, Where do you need to implement zero copy?

**Comment by jobs-git** [comment]
When there is a 1MB data in `$response->end()` the server performance  drops by about 15x. This is also in conjunction w/ high cpu usage indicating that data is being parsed by the cpu byte by byte instead of taking advantage of direct memory access

**Comment by matyhtf** [comment]
unable to apply in swoole, memory copy is very fast, DMA has side effects

**Comment by jobs-git** [comment]
Localhost can be about 40Gbit/s fast, but swoole can only do half of this.

In typical copy, there were about several DMA and two memory copy. If `zero copy` gets implemented, in theory, swoole could be about 2X faster since the cpu will not do the copying, though I am expecting less maybe about 30Gbit/s.

**Comment by matyhtf** [comment]
The default is to use the `SWOOLE_PROCESS` mode, there are 2 times the cost of ipc.

You can use the `SWOOLE_BASE` mode. In fact, there is still a need to copy from the PHP layer to the C layer, that cannot be reduced.

**Comment by matyhtf** [comment]
code
---
``php
<?php
define('PORT', 9501);

$http = new swoole_http_server('127.0.0.1', PORT, SWOOLE_BASE);

$http->set(['worker_num' => 1, 'enable_coroutine' => false, ]);

$http->on('start', function ($server) {
    echo 'Swoole http server is started at 127.0.0.1 on port ' . PORT;
});

$http->on('request', function ($request, $response) {
    $response->header('Content-Type', 'text/plain');
    $response->end(str_repeat('A', 1 * 1024 * 1024));
});

$http->start();
```

ab test
----
```shell
ab -c 100 -n 10000 http://127.0.0.1:9501/
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        swoole-http-server
Server Hostname:        127.0.0.1
Server Port:            9501

Document Path:          /
Document Length:        1048576 bytes

Concurrency Level:      100
Time taken for tests:   3.246 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      10487300000 bytes
HTML transferred:       10485760000 bytes
Requests per second:    3080.32 [#/sec] (mean)
Time per request:       32.464 [ms] (mean)
Time per request:       0.325 [ms] (mean, across all concurrent requests)
Transfer rate:          3154714.78 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.3      0       3
Processing:     1   32   8.5     28      53
Waiting:        0   16  12.2     23      31
Total:          3   32   8.7     28      53

Percentage of the requests served within a certain time (ms)
  50%     28
  66%     39
  75%     42
  80%     43
  90%     44
  95%     46
  98%     47
  99%     49
 100%     53 (longest request)
```
