### ISSUE TITLE
http2 client send timeout question - not waiting for user action

### ISSUE THREAD

**Issue by ozgurhangisi** [swoole/swoole-src#2359]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I try to send App Push using http2 client. I set timeout parameters for $client->connect to 6 seconds and $client->recv(3). When I do the tests If I try to connect to http2 server without network, timeout works and I get error after 6 seconds. But If I try to disconnect network after connected to the http2 server, it freezes and timeout doesn't work. (I wait for 10 minutes). Probably It freezes on $cli->send($req) method. Is there any timeout for $client->send method ? 

go(function () use ($Authentication,$apns2_url,$Notifications) {
    $cli = new co\Http2\Client($apns2_url[$Authentication['APNS']['ENVIRONMENT']]['url'], $apns2_url[$Authentication['APNS']['ENVIRONMENT']]['port'], $apns2_url[$Authentication['APNS']['ENVIRONMENT']]['ssl']);
    $cli->set([ 'timeout' => 6,
        'ssl_cert_file'=>$Authentication['APNS']['PEMFILE'],
        'ssl_key_file'=>  $Authentication['APNS']['PEMFILE']
    ]);

    $i=0;
    $cli->connect();
    $req = new swoole_http2_request;
    $notificationChunk = array_chunk($Notifications, 1000);

    for($chunk=0;$chunk<count($notificationChunk);$chunk++) {
        if (!$cli->connected) {
            $cli->connect();
        }
        foreach($notificationChunk[$chunk] as $notification) {
                $req->path = '/3/device/'.$notification->token;
                $req->headers = ['apns-topic'=>$Authentication['APNS']['WEBSITEID'],'Content-Type'=>'application/json','user-agent'=>'APNS2'];
                $req->data = $notification->getPayload();
                $req->method = 'POST';
                $res = $cli->send($req);
        }

        foreach($notificationChunk[$chunk] as $notification) {
            $resp = $cli->recv(3);
            
            if ($resp) {
                if (isset($resp->streamId) && is_numeric($resp->streamId)) {
                    $current_ntf = floor(($resp->streamId-1)/2);
                    $ntf = $notificationChunk[$chunk][$current_ntf];
                    $ntf->response = $resp;
                }
                if (isset($resp->statusCode)) {
                    if ($resp->statusCode == 200) {
                        $ntf->resultSuccess = true;
                        $success++;
                    } else {
                        $fail++;
                        if (in_array($resp->statusCode, [400,410])) {
                            $ntf->resultExpired = true;
                            $expired++;
                        }
                    }
                } else {$fail++;}
            } else {$fail++;}
            $i++;
        }
    }
    echo 'SUCCESS='.$success."\r\n";
    echo 'FAIL='.$fail."\r\n";
    echo 'EXPIRED='.$expired."\r\n";
    $cli->close();
});
Swoole\Event::wait();

2. What did you expect to see?

It should get timeout parameter from somewhere like $cli->set('sendingtimeout'=>X) or $cli->send($req,$timeout); 

3. What did you see instead?

If I disconnect from network after connection It just freezes and script never ends.

I can do additional tests if you need.

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.2.12

5. What is your machine environment used (including version of kernel & php & gcc) ?

MacOSX, php7.3.1

**Comment by ozgurhangisi** [comment]
Thanks for the answer. Now I noticed that I set 3 seconds timeout on $client->recv() method. When I send 1000 requests and if recv method waits for 3 seconds for each request (totally 3000 seconds) This can be the reason.  Now I close the issue because I'm busy this week. Next week I'll try some tests and if I find something I'm gonna reopen the case.

**Comment by ozgurhangisi** [comment]
Hi,

I found the problem. Like I said, If I send 1000 request to http2 server and receive the data with $client->recv(1); and if there is a network problem (which can happen in the real world apps) it waits for minutes (may be 1 second for each request). I think this timeout starts when I call $client->recv(1); So is there any option to start timeout when I send the request. 

We are push service provider and we send millions of pushes daily and we are planning to use swoole http2 to send apple push notifications. Waiting for minutes to send 1000 notification creates so many problems on our side.

We use guzzle library for webpush notifications and guzzle's timeout property starts when you send requests. So when we start sending requests with guzzle we only wait for a few seconds. (Even if there is a network error) 

I try $cli->set([ 'timeout' => 6]); But I think It's just for connection. If client connects to server and if we have network error in send receive process timeout doesn't work. We have to wait for minutes for process to complete. 

Is there any other option that we can use to add some cumulative timeout or something ?

**Comment by twose** [comment]
@ozgurhangisi 
Why not breaking when recv return false?

**Comment by ozgurhangisi** [comment]
@twose because if recv timeout happens, recv returns false. When I send 1000 request sometimes I see that a few responses are empty. But I can get other responses from the server. If timeout happens on 3rd recv call and I break the loop, I can not get other 997 responses.

**Comment by twose** [comment]
@ozgurhangisi 
Check $cli->errCode property, if it is `SOCKET_ETIMEDOUT`, the connection is still available, if not, maybe you should break it.

If you want to use `$cli->close()` to stop all recv operation?

**Comment by ozgurhangisi** [comment]
Thanks for the response. SOCKET_ETIMEDOUT worked. I Just wanted to add what I did If someone needs : 

```
            $resp = $cli->recv(0.5);
            if ($resp) {
// DO SOMETHING WITH RESPONSE
            } else {
                if ($cli->errCode == SOCKET_ETIMEDOUT) {
                    $fail++;
                } else {
                    $cli->close();
                    break;
                }
            }
```
