### ISSUE TITLE
swoole_http_server silently fails to read requests

### ISSUE THREAD

**Issue by mgrooms** [swoole/swoole-src#2360]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

If an http client posts a request over 2000 bytes or so, the swoole http server will never processes the request.

2. What did you expect to see?

I expected the swoole http server to read the complete request and then process it.

3. What did you see instead?

The swoole http server never reads the complete request, so it appears to do nothing. If this is due to a post body size limit that can be changed ( my posts are never more than 4kb ), I would expect to see the server produce some sort of warning, error or respond to the client with an error code. I suspect that the server is only attempting a single read operation on the socket so it never reads the complete request from the socket buffer. If the socket buffer contains more data than can be read in a single read request ( the read request buffer is smaller than the data in the socket buffer ), multiple read requests would be required. I believe data is being left in the socket buffer because the server does not close the client socket or respond with an error, it just leaves the socket open in a read-ready state.

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.2.13
Built => Feb  4 2019 12:10:14
coroutine => enabled
ucontext => enabled
kqueue => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2q  20 Nov 2018
http2 => 1.36.0
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled
coroutine_postgresql => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

FreeBSD 11.2-RELEASE-p8

PHP 7.3.1 (cli) (built: Jan 21 2019 14:03:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.1, Copyright (c) 1999-2018, by Zend Technologies

FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)
Target: x86_64-unknown-freebsd11.2
Thread model: posix
InstalledDir: /usr/bin

**Comment by mgrooms** [comment]
```
//
// HTTP server
//

$server = new swoole_http_server( '0.0.0.0', 9501 );

$server->on( 'request', function( $request, $response )
{
    $response->header(
        'Content-Type', 'application/json'
    );

    echo( "received {$request->header['content-length']} bytes\n" );

    $response->end(
        json_encode( array( 'result' => 'OK' ) )
    );
});

$server->start();

```

**Comment by mgrooms** [comment]
```
//
// HTTP client
//

function client()
{
        $httpClient = new Swoole\Coroutine\Http\Client( '127.0.0.1', 9501 );
        $httpClient->setHeaders(
                array(
                        'Host'                  => '127.0.0.1',
                        'Accept'                => 'application/json'
                )
        );

        $count = rand( 1024, 4096 );

        $data = '';
        for( $i = 0; $i < $count; $i++ )
                $data .= sprintf( '%01x', $i % 16 );

        $size = strlen( $data );

        echo( "posting {$size} bytes\n" );

        $httpClient->post( '/', $data );

        $httpClient->close();
}

swoole_timer_tick( 1000, 'client' );
```

**Comment by mgrooms** [comment]
Sample server output:
received 1509 bytes
received 1721 bytes
received 1695 bytes
received 1759 bytes
received 1180 bytes
received 1484 bytes
received 1789 bytes
received 1757 bytes
received 1665 bytes
received 1893 bytes
received 1903 bytes
received 1266 bytes
received 1851 bytes
received 1093 bytes
received 1839 bytes
received 1253 bytes
received 1566 bytes

Sample client output:
posting 2378 bytes
posting 2029 bytes
posting 3689 bytes
posting 2564 bytes
posting 3713 bytes
posting 3942 bytes
posting 2316 bytes
posting 3372 bytes
posting 3259 bytes
posting 2771 bytes
posting 3898 bytes
posting 2509 bytes
posting 1509 bytes
posting 3983 bytes
posting 2785 bytes
posting 2120 bytes
posting 1721 bytes
posting 3078 bytes
posting 3680 bytes
posting 3689 bytes
posting 1695 bytes
posting 2384 bytes
posting 2798 bytes
posting 3012 bytes
posting 3571 bytes
posting 3461 bytes
posting 1759 bytes
posting 2273 bytes
posting 3509 bytes
posting 1180 bytes
posting 1484 bytes
posting 1789 bytes
posting 1757 bytes
posting 1665 bytes
posting 1893 bytes
posting 1903 bytes
posting 1266 bytes
posting 2033 bytes
posting 3241 bytes
posting 3560 bytes
posting 2322 bytes
posting 3665 bytes
posting 1851 bytes
posting 1093 bytes
posting 3031 bytes
posting 3456 bytes
posting 2630 bytes
posting 2105 bytes
posting 3865 bytes
posting 4091 bytes
posting 1839 bytes
posting 3071 bytes
posting 1253 bytes
posting 3883 bytes
posting 3980 bytes
posting 2724 bytes
posting 2259 bytes
posting 2987 bytes
posting 3162 bytes
posting 1566 bytes
posting 3591 bytes

**Comment by mgrooms** [comment]
Note: The server only reports receiving post requests that are less than 2000 bytes.

**Comment by twose** [comment]
I just add a test for you but everything looks well. 
If you make clean before you upgrade your swoole?
may need more information (FreeBSD problem?)

**Comment by mgrooms** [comment]
Yes. It's not a problem with the build. I've tried several times on several different systems. I also tried to dig into the code but I'm not even sure where the socket read occurs. This very well may be related to FreeBSD in the sense that the async primitive is kqueue and not epoll. I assume that most of your development work is done on Linux so your tests would use epoll. Did you try to run your test on FreeBSD or OSX? When I try to run your test on a FreeBSD host it outputs ...

--TEST--
swoole_http_server: issue 2360 (swoole_http_server silently fails to read requests)
--SKIPIF--
--FILE--
[2019-02-05 07:52:05 @59809.0]  ERROR   swSocket_set_buffer_size(:438): setsockopt(3, SOL_SOCKET, SO_SNDBUF, 8388608) failed. Error: No buffer space available[55].
[2019-02-05 07:52:05 @59809.0]  ERROR   swSocket_set_buffer_size(:438): setsockopt(4, SOL_SOCKET, SO_SNDBUF, 8388608) failed. Error: No buffer space available[55].

Warning: assert(): assert($cli->post('/', $data) === true) failed in /usr/ports/brightfire/pecl-swoole4/work-php73/swoole-4.2.13/tests/swoole_http_server/issue_2360.phpt on line 24

Warning: assert(): assert($cli->statusCode === 200) failed in /usr/ports/brightfire/pecl-swoole4/work-php73/swoole-4.2.13/tests/swoole_http_server/issue_2360.phpt on line 25

Warning: assert(): assert($cli->body === $data) failed in /usr/ports/brightfire/pecl-swoole4/work-php73/swoole-4.2.13/tests/swoole_http_server/issue_2360.phpt on line 26
posting 60822 bytes

Warning: assert(): assert($cli->post('/', $data) === true) failed in /usr/ports/brightfire/pecl-swoole4/work-php73/swoole-4.2.13/tests/swoole_http_server/issue_2360.phpt on line 24

Warning: assert(): assert($cli->statusCode === 200) failed in /usr/ports/brightfire/pecl-swoole4/work-php73/swoole-4.2.13/tests/swoole_http_server/issue_2360.phpt on line 25

Warning: assert(): assert($cli->body === $data) failed in /usr/ports/brightfire/pecl-swoole4/work-php73/swoole-4.2.13/tests/swoole_http_server/issue_2360.phpt on line 26
posting 58019 bytes

Warning: assert(): assert($cli->post('/', $data) === true) failed in /usr/ports/brightfire/pecl-swoole4/work-php73/swoole-4.2.13/tests/swoole_http_server/issue_2360.phpt on line 24

Warning: assert(): assert($cli->statusCode === 200) failed in /usr/ports/brightfire/pecl-swoole4/work-php73/swoole-4.2.13/tests/swoole_http_server/issue_2360.phpt on line 25

Warning: assert(): assert($cli->body === $data) failed in /usr/ports/brightfire/pecl-swoole4/work-php73/swoole-4.2.13/tests/swoole_http_server/issue_2360.phpt on line 26
posting 43616 bytes

I'll try to dig into the swoole code more and see if I can figure out what's going on. But I think it would be much easier for a swoole developer to pinpoint the issue, especially since there is an easily repeatable test case that demonstrates the failure.

**Comment by mgrooms** [comment]
Also, I couldn't help but notice that it looks like swoole is trying to set the socket buffer to a very large value on Linux, That operation obviously fails on fails on FreeBSD ...

[2019-02-05 07:52:05 @59809.0]  ERROR   swSocket_set_buffer_size(:438): setsockopt(3, SOL_SOCKET, SO_SNDBUF, 8388608) failed. Error: No buffer space available[55].
[2019-02-05 07:52:05 @59809.0]  ERROR   swSocket_set_buffer_size(:438): setsockopt(4, SOL_SOCKET, SO_SNDBUF, 8388608) failed. Error: No buffer space available[55].

It's quite possible that by using a very large socket buffer ( 8mb ), you are masking a problem due to the fact that the buffer size is larger than the data being written/read. In other words, you may be writing and then reading all data using a single operation in each direction. If you changed your socket buffer size to be smaller than your data set, you may see the same issue that I'm seeing.

**Comment by mgrooms** [comment]
I think the socket buffer size is making a problem. After I applied the above patch, my test program now runs more reliably ...

Sample server output:
received 1181 bytes
received 3681 bytes
received 3685 bytes
received 1306 bytes
received 3334 bytes
received 3489 bytes
received 1328 bytes
received 3207 bytes
received 1872 bytes
received 1207 bytes
received 4002 bytes
received 2018 bytes
received 3818 bytes
received 3737 bytes
received 2390 bytes
received 1575 bytes
received 3419 bytes
received 2060 bytes

Sample client output:
posting 1181 bytes
posting 3681 bytes
posting 3685 bytes
posting 1306 bytes
posting 3334 bytes
posting 3489 bytes
posting 1328 bytes
posting 3207 bytes
posting 1872 bytes
posting 1207 bytes
posting 4002 bytes
posting 2018 bytes
posting 3818 bytes
posting 3737 bytes
posting 2390 bytes
posting 1575 bytes
posting 3419 bytes
posting 2060 bytes
posting 2526 bytes

So this is definitely a bug in swoole. It's being masked by setting the socket buffers to large values.

**Comment by twose** [comment]
The tests worked well on other Linux platforms and MacOS.
But no FreeBSD test env is available now, we will find a way to reproduce this problem.

**Comment by mgrooms** [comment]
Have you tried reducing your socket buffer size to be smaller than the size of your data set?

**Comment by twose** [comment]
7f6d53a was failed,  but the same test passed on my mac.
