### ISSUE TITLE
How can I get the worker_id in onRequest() method?

### ISSUE THREAD

**Issue by MiltonLai** [swoole/swoole-src#2365]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Need to get the worker ID in a HTTP request. 
I want to achieve this: when the http server starts, create persistent sockets associated with each workers, then when requests come in, each worker can send/recv on their own socket.

2. What did you expect to see?
Get the worker ID

3. What did you see instead?
I can not find the reference to this variable.

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.2.13

5. What is your machine environment used (including version of kernel & php & gcc) ?
Ubuntu18.04, PHP7.2

**Comment by matyhtf** [comment]
You can read the worker_id property of the swoole_http_server object.

```php
<?php
$http = new swoole_http_server("127.0.0.1", 9501);

$http->on("start", function ($server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$http->on("request", function ($request, $response) {
    $response->header("Content-Type", "text/plain");
    $response->end("Hello World\n");
    global $http;
    var_dump($http->worker_id);
});

$http->start();

```

**Comment by MiltonLai** [comment]
Thanks it works.

**Comment by fakharksa** [comment]
Another way to use $http inside onRequest event callback is through the use of function() use ($http) { ...} syntax.

Third way is when $http is a class property so it can be accessed directly inside callback using $this->http as callback inherits parent class properties

class someclass {
     // constructor and functions for http server initialization
             .......................
    
    protected function bindHttpRequestEvent() {
    
             $this->http->on('request', function (Swoole\Http\Request $request, Swoole\Http\Response $response) {
                      // $this->http is available / accessible here
           });
   }
        
     // functions to start server
           ................
}
