### ISSUE TITLE
4.2.13 task 投递消息有问题, onTask 收不到消息 php_error 也没报错!

### ISSUE THREAD

**Issue by designinlife** [swoole/swoole-src#2366]
使用 Swoole 4.2.13 版本发现 task 投递消息 onTask 不会触发! (4.2.12 版本是正常的)

PHP: 7.3.2
swoole.enable_coroutine = 1
task_enable_coroutine 没有设置
onTask 回调形式: function onTask(swoole_server $serv, int $task_id, int $src_worker_id, mixed $data);
也使用 $server->on('Task', function ($serv, Swoole\Server\Task $task) 测试过仍然不行

**Comment by twose** [comment]
第三个参数没有检查是否为null导致
Fixed in 53586a6b6dbdc02639a905afedd76303062ccb35
