### ISSUE TITLE
swoole的协程Redis类部分方法返回的格式和PHP的redis扩展返回的格式不一致

### ISSUE THREAD

**Issue by qihuajun** [swoole/swoole-src#2369]
本来想用swoole的协程Redis类替换PHP扩展的Redis类，但是发现hmget方法返回的数据格式和PHP扩展Redis类返回的格式不一样：

对于一个key-value的hash数据，swoole redis返回的格式：

```
[0 =>key, 1=> value]
```

PHP扩展Redis类返回的格式：

```
[key => value]
```

尤其是swoole的Redis类还继承了扩展的Redis类，这个方法返回的格式能跟扩展类返回的保持一致吗？

另外请检查下其他的方法有没有同样的问题？

**Comment by twose** [comment]
duplicated, see #1630.

**Comment by qihuajun** [comment]
@twose 根据 #1630 解决方案就是`Swoole\Runtime::enableCoroutine()`然后调用扩展的Redis类吗？

如果是这样的话能解决我的问题。谢谢！

还有，根据`eaglewu/swoole-ide-helper`这个package的代码：
```
class Redis extends \Redis
```

协程的Redis类是继承自扩展的Redis类，如果是继承的话最好还是能够跟父类的方法返回的格式保持一致。
