### ISSUE TITLE
Mac Mojave下 Unable to load dynamic library 

### ISSUE THREAD

**Issue by yumuchen8** [swoole/swoole-src#2371]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
在Mac自带的php下使用编译安装方式安装swoole扩展。

2. What did you expect to see?
将php.ini中extension=swoole.so开启后，并且已经在extension_dir目录下放置了编译好的swoole.so文件。运行php -m时报错

<img width="672" alt="wx20190218-174234 2x" src="https://user-images.githubusercontent.com/12460488/52941799-9b059c00-33a4-11e9-8692-586a175ddf64.png">

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole版本4.2.12 

5. What is your machine environment used (including version of kernel & php & gcc) ?
mac  Mojave 10.14.2
PHP 7.1.19 自带的php已安装CommandLineTools及一些开发库
gcc : 
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0

**Comment by matyhtf** [comment]
编译有问题，请重新编译。

**Comment by garming** [comment]
同样遇到这个问题，多次编译后，还是报这个错，可以确认php cli版本与php-config的版本是一致的

**Comment by garming** [comment]
> 编译有问题，请重新编译。

同样遇到这个问题，多次编译后，还是报这个错，可以确认php cli版本与php-config的版本是一
