### ISSUE TITLE
协程client如何像onReceive一样监听recv

### ISSUE THREAD

**Issue by louislivi** [swoole/swoole-src#2372]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

$client->recv();

2. What did you expect to see?

能够像onReceive 一样监听recv 返回值进行处理

3. What did you see instead?

每次recv 都要写，服务端如果主动推送消息不知该什么时候进行recv

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.2.12

5. What is your machine environment used (including version of kernel & php & gcc) ?

centos php7.2

**Comment by louislivi** [comment]
如果使用while(true) ，会出现协程读写冲突无法兼容4.2.12及以下

**Comment by matyhtf** [comment]
你可以配合使用 `channel` 和 `while(true)` 循环操作。不要多个协程同时操作同一个 `Client`，而是通过 `Channel`去做协程间通信。

举个例子
----

```php
go(function () use ($pm) {
    $client = new Co\Client(SWOOLE_SOCK_TCP);
    $client->connect("127.0.0.1",  $pm->getFreePort());

    $send_queue = new chan(150);
    $recv_queue = new chan(150);

    //读协程
    go(function () use ($recv_queue, $send_queue, $client) {
        while(true) {
            $data = $client->recv();
            if (empty($data)) {
                //连接关闭了，结束
                $send_queue->close();
                $recv_queue->close();
                $client->close();
                break;
            } else {
                $recv_queue->push($data);
            }
        }
        echo "read-co stop\n";
    });

    //写协程
    go(function () use ($send_queue, $client) {
        while(true) {
            $data = $send_queue->pop();
            if (empty($data)) {
                //通道已关闭
                break;
            } else {
                $client->send($data);
            }
        }
        echo "write-co stop\n";
    });

    //启动 $n 个协程做消费者
    $n = 100;
    while ($n--) {
        go(function () use ($recv_queue, $n) {
            for ($i = 0; $i < 100; $i++) {
                //收到了数据
                $data = $recv_queue->pop();
            }
            //echo "consumer-co $n stop\n";
        });
    }

    //启动 $n 个协程随机发送数据
    $n = 100;
    while ($n--) {
        go(function () use ($send_queue, $n) {
            for ($i = 0; $i < 100; $i++) {
                //投递任务
                $send_queue->push("hello world $i ".rand(1000000, 9999999)."\r\n");
            }
            //echo "producer $n stop\n";
        });
    }
});
```

**Comment by matyhtf** [comment]
协程对应的是 CSP 编程模型，不再是事件驱动。因此在编程的思路、程序设计上，可能都需要一些改变。

**Comment by louislivi** [comment]
@matyhtf  运行出现
```
 ERROR   check_bind (ERROR 10002): client has already been bound to another coroutine#2, reading or writing of the same socket in multiple coroutines at the same time is not allowed.

```

**Comment by matyhtf** [comment]
@louislivi 4.2.12 没有支持读写并发，你使用 master 编译试试呢

**Comment by louislivi** [comment]
低版本的话这种情况有办法兼容吗

**Comment by matyhtf** [comment]
不好兼容，你可以将 读写合并到一个协程里，但是 send 可能会滞后。

**Comment by matyhtf** [comment]
可以将 recv 的超时设置为 0.01 ，这样就能保证它可以快速响应 send 操作。

**Comment by louislivi** [comment]
测试使用4.2.13代码，并发协程client读写有延迟，比设置while(true) recv 延迟0.01更高,但是cpu消耗确实下降了

**Comment by ihipop** [comment]
@matyhtf 之前不是说 协程的客户端不能公用么？从什么版本开始客户端可以跨协程使用了？是不是只有内置的客户端不受到此限制？我之前为了绕过这个限制弄了很多个chan来控制收发tmc的消息..

**Comment by ihipop** [comment]
拜读了一下4.2.13的release note 也没提到这个关键特性啊

**Comment by louislivi** [comment]
@ihipop 
![image](https://user-images.githubusercontent.com/23403807/53853264-ab05b880-3fff-11e9-8b00-19d16962bad9.png)

**Comment by ihipop** [comment]
@louislivi 这个描述，，，，好吧。。 不过，这是全部的客户端还是只有内置客户端可以？支持那些通过hook socket API实现的一键协程客户端（比如那些内置的Pdo的一键协程）吗？这方面想知道详细

**Comment by matyhtf** [comment]
@ihipop 具体请查看 wiki 页面 https://wiki.swoole.com/wiki/page/p-runtime.html

**Comment by ihipop** [comment]
@matyhtf 知道一键协程这个特性，其实也就是一键协程的客户端也可以支持双工了。主要是想确认这个
