### ISSUE TITLE
段错误

### ISSUE THREAD

**Issue by ilikego** [swoole/swoole-src#2377]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
我在测试dos攻击，有时出现错误（4.2.13：段错误。4.2.12：ERROR   swReactorEpoll_del(:151): epoll remove fd[1670#0] failed. Error: No such file or directory[2].），当发生超时情况时大概率出现。
```
<?php
$cos = 1000;
$url = 'http://xxx.com/honor1.jpg';
$temp = parse_url($url);
$host = $temp['host'];
$port = isset($temp['port']) ? $temp['port'] : 80;
$ip = gethostbyname($host);
$path = $temp['path'] . (isset($temp['query']) ? ('?' . $temp['query']) : '');
$timeout = 70;
$c  = new chan($cos);
co::set([
    'max_coroutine' => 4096,
]);
$x = function() use($c, $ip, $host, $path, $timeout, $cos, $port) {
        go(function() use($c, $cos){
            $result = [];
            for($j=0;$j<$cos;$j++)
            {
                $result = array_merge($result, $c->pop());
            }
            defer(function() use($result){
                print_r(array_count_values($result));
            });
        });
        for($i=0;$i<$cos;$i++)
        {
            go(function() use($c, $i, $ip, $host, $path, $timeout, $port){
                $client = new Swoole\Coroutine\Http\Client($ip, $port);
                $client->set(['timeout'=>$timeout]);
                $client->setHeaders([
                    'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
                    'Accept-Encoding' => 'gzip, deflate',
                    'Accept-Language' => 'zh-CN,zh;q=0.9',
                    'Cache-Control' => 'max-age=0',
                    'Connection' => 'keep-alive',
                    'Host' => $host,
                    //'If-Modified-Since' => 'Tue, 17 Apr 2018 06:25:58 GMT',
                    //'If-None-Match' => '"5ad59376-ec3d"',
                    //'Upgrade-Insecure-Requests' => '1',
                    'User-Agent' => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
                ]);
                $client->download($path, "{$i}.da");
                $client->close();
                $c->push([(string) $i => $client->statusCode]);
            });
        }
};
$x();
swoole_timer_tick(($timeout+1) * 1000, $x);
```
2. What did you expect to see?
array[
     200 => xxx
     -2 => xxx
     ...
]

3. What did you see instead?
段错误

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.2.13

5. What is your machine environment used (including version of kernel & php & gcc) ?
Linux localhost.localdomain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
gcc-4.8.5-28.el7_5.1.x86_64
PHP 7.2.14 (cli) (built: Jan 24 2019 14:08:37) ( NTS )

**Comment by twose** [comment]
我随便替换了一个网址 没有复现 也没有跟踪到内存错误

**Comment by ilikego** [comment]
> 我随便替换了一个网址 没有复现 也没有跟踪到内存错误
> 尝试访问慢网速网站触发超时 也没有出现错误

是否有保持10分钟以上运行，我贴一下我的一个问题运行结果：
···
[root@localhost wow]# php dos.php 


Array
(
    [200] => 447
    [-3] => 30
    [-2] => 523
)


Array
(
    [-2] => 656
    [200] => 319
    [-3] => 25
)
Array
(
    [-2] => 638
    [200] => 331
    [-3] => 31
)
Array
(
    [-2] => 641
    [200] => 331
    [-3] => 28
)
Array
(
    [-2] => 646
    [200] => 335
    [-3] => 19
)
段错误
···

**Comment by twose** [comment]
协程客户端下载使用了协程写文件操作, 该操作(文件IO)不支持和客户端(网络IO)超时同时存在

**Comment by ilikego** [comment]
> 协程客户端下载使用了协程写文件操作, 该操作(文件IO)不支持和客户端(网络IO)超时同时存在, 请使用master的代码尝试, 应该不会再出现

你好，是要重新编译吗，我从pecl安装的，master的代码会不会编译不了，看官网的文档说不建议使用master代码。

**Comment by twose** [comment]
@ilikego master的代码是开发中的所以不建议使用, 你可以等下个版本发布

**Comment by ilikego** [comment]
重新编译后测试确实不会再报错了。

**Comment by ilikego** [comment]
> @ilikego master的代码是开发中的所以不建议使用, 目前来说没什么问题, 你可以等下个版本发布

还有想请问下，修改以后的download是同步操作吗

**Comment by twose** [comment]
@ilikego 后续修改恢复成异步操作了
