### ISSUE TITLE
Swoole-v4.2.13 [Segmentation fault: 11].

### ISSUE THREAD

**Issue by ITnpc** [swoole/swoole-src#2378]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

php  bin/laravels start

2. What did you expect to see?

ok

3. What did you see instead?

[2019-02-22 16:31:01 $32421.0]	WARNING	swManager_check_exit_status: worker#3 abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.2.13, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

[2019-02-22 16:31:01 #32403.8]	WARNING	swServer_signal_handler: Fatal Error: manager process exit. status=0, signal=[Segmentation fault: 11].

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.2.13

5. What is your machine environment used (including version of kernel & php & gcc) ?

mac 10.14.3
php 
PHP 7.3.0 (cli) (built: Dec  7 2018 11:00:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies
gcc
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix

**Comment by twose** [comment]
https://github.com/swoole/swoole-src/issues/2000#issuecomment-423807053
