### ISSUE TITLE
session is  bug

### ISSUE THREAD

**Issue by lenghua** [swoole/swoole-src#238]
使用swoole框架（已安装扩展）启用http服务器时session有一个bug，session不能保存（不管是保持文件还是cache，问题相同），应用层代码跟踪没有问题，查看源码发现问题出在: 服务器端Request::unsetGlobal()方法, 这里对$_SESSION 清空，导致保存内容丢失，如果这里不对$_SESSION 进行清空操作，会出现不同浏览器串改session的问题。

GoogleTranslation：
There session when using swoole framework (installed extensions) http server enable a bug, session can not be saved (either keep the file or cache, same issue), the application layer code tracking no problem, view the source code found in the problem: Server Request: : unsetGlobal () method, where for $ _SESSION emptied, resulting in the loss of stored contents, if there were not $ _SESSION flush operation, there will be a different browser session falsification issue

**Comment by matyhtf** [comment]
请在 framework 项目主页提交issue
