### ISSUE TITLE
mac下报错, WARNING	swKqueueSignal_set: kevent set signal[26] error

### ISSUE THREAD

**Issue by ppyupp** [swoole/swoole-src#2380]
4.2.13在mac下报错
同样版本,linux没问题

> WARNING	swKqueueSignal_set: kevent set signal[26] error

```
<?php

$server = new Swoole\WebSocket\Server( "0.0.0.0", 9981 );

$server->on('message', function (Swoole\WebSocket\Server $Server, $frame) {

});


go(function(){
	$redis = new Swoole\Coroutine\Redis();
	$redis->connect('127.0.0.1', 6379);
});

$server->start();


```

**Comment by twose** [comment]
MacOS Mojave 没有复现

**Comment by ppyupp** [comment]
php 7.1.7
Mojave 10.14.3 必现....
我一会升级下php试试

> [2019-02-25 10:03:19 @33767.0]	WARNING	swKqueueSignal_set: kevent set signal[15] error
> [2019-02-25 10:03:19 @33767.0]	WARNING	swKqueueSignal_set: kevent set signal[14] error
> [2019-02-25 10:03:19 @33767.0]	WARNING	swKqueueSignal_set: kevent set signal[26] error
> [2019-02-25 10:03:19 @33769.0]	WARNING	swKqueueSignal_set: kevent set signal[15] error
> [2019-02-25 10:03:19 @33769.0]	WARNING	swKqueueSignal_set: kevent set signal[14] error
> [2019-02-25 10:03:19 @33768.0]	WARNING	swKqueueSignal_set: kevent set signal[15] error
> [2019-02-25 10:03:19 @33768.0]	WARNING	swKqueueSignal_set: kevent set signal[14] error
> [2019-02-25 10:03:19 @33771.0]	WARNING	swKqueueSignal_set: kevent set signal[15] error
> [2019-02-25 10:03:19 @33769.0]	WARNING	swKqueueSignal_set: kevent set signal[26] error
> [2019-02-25 10:03:19 @33771.0]	WARNING	swKqueueSignal_set: kevent set signal[14] error
> [2019-02-25 10:03:19 @33771.0]	WARNING	swKqueueSignal_set: kevent set signal[26] error
> [2019-02-25 10:03:19 @33768.0]	WARNING	swKqueueSignal_set: kevent set signal[26] error
> [2019-02-25 10:03:19 @33773.0]	WARNING	swKqueueSignal_set: kevent set signal[15] error
> [2019-02-25 10:03:19 @33773.0]	WARNING	swKqueueSignal_set: kevent set signal[14] error
> [2019-02-25 10:03:19 @33773.0]	WARNING	swKqueueSignal_set: kevent set signal[26] error
> [2019-02-25 10:03:19 @33774.0]	WARNING	swKqueueSignal_set: kevent set signal[15] error
> [2019-02-25 10:03:19 @33774.0]	WARNING	swKqueueSignal_set: kevent set signal[14] error
> [2019-02-25 10:03:19 @33772.0]	WARNING	swKqueueSignal_set: kevent set signal[15] error
> [2019-02-25 10:03:19 @33772.0]	WARNING	swKqueueSignal_set: kevent set signal[14] error
> [2019-02-25 10:03:19 @33772.0]	WARNING	swKqueueSignal_set: kevent set signal[26] error
> [2019-02-25 10:03:19 @33770.0]	WARNING	swKqueueSignal_set: kevent set signal[15] error
> [2019-02-25 10:03:19 @33770.0]	WARNING	swKqueueSignal_set: kevent set signal[14] error
> [2019-02-25 10:03:19 @33770.0]	WARNING	swKqueueSignal_set: kevent set signal[26] error
> [2019-02-25 10:03:19 @33774.0]	WARNING	swKqueueSignal_set: kevent set signal[26] error

**Comment by ppyupp** [comment]
应该跟php版本没关系...
Mojave 10.14.3
php 7.3.2
swoole4.2.13

还是上面的错误
@twose

**Comment by matyhtf** [comment]
无法重新，请尝试 make clean 后重新 编译安装。
