### ISSUE TITLE
php7.3+swoole4.1.3 http_server启动失败

### ISSUE THREAD

**Issue by nihaibao** [swoole/swoole-src#2381]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

启动lumen+LaravelS服务时，发生错误

2. What did you expect to see?

swoole服务正常

3. What did you see instead?

WARNING	swServer_signal_handler: Fatal Error: manager process exit. status=0, signal=[Segmentation fault: 11].
WARNING	swManager_check_exit_status: worker#15 abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.2.13, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.2.13
Built => Feb 22 2019 22:59:04
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2q  20 Nov 2018
http2 => 1.36.0
pcre => enabled
zlib => enabled
brotli => enabled
mysqlnd => enabled
async_redis => enabled
coroutine_postgresql => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (including version of kernel & php & gcc) ?

OSX 18.2.0 Darwin Kernel Version 18.2.0 

PHP 7.3.2 

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix

**Comment by twose** [comment]
https://wiki.swoole.com/wiki/page/p-issue.html

**Comment by matyhtf** [comment]
请升级至最新版本测试一下
