### ISSUE TITLE
hGetAll Should return an associative array.

### ISSUE THREAD

**Issue by mahmed-ntd** [swoole/swoole-src#2382]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Trying to use hGetAll function it is returning the values but the return should be in associative array not a simple indexed array.

```
go(function () {
	$redis = new \Swoole\Coroutine\Redis();
	$redis->connect('redisdb', 6379);

	$redis->hMSet('hmhas', ['key1' => 'val1', 'key2' => 'val2']);
	$result = $redis->hGetAll('hmhas');
});
```

```
Array
(
    [0] => key1
    [1] => val1
    [2] => key2
    [3] => val2
)

```
2. What did you expect to see?
when using with phpredis

```
$redis = new Redis();
$redis->connect('redisdb', 6379);
$redis->hMSet('hmhas1', ['key1' => 'val1', 'key2' => 'val2']);
$result = $redis->hGetAll('hmhas1');
```

```
Array
(
    [key1] => val1
    [key2] => val2
)
```

3. What did you see instead?

```
Array
(
    [0] => key1
    [1] => val1
    [2] => key2
    [3] => val2
)
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

> swoole
> 
> Swoole => enabled
> Author => Swoole Team <team@swoole.com>
> Version => 4.3.0-alpha
> Built => Feb 15 2019 05:51:12
> coroutine => enabled
> epoll => enabled
> eventfd => enabled
> signalfd => enabled
> cpu_affinity => enabled
> spinlock => enabled
> rwlock => enabled
> sockets => enabled
> pcre => enabled
> mutex_timedlock => enabled
> pthread_barrier => enabled
> futex => enabled
> mysqlnd => enabled
> async_redis => enabled
> 
> Directive => Local Value => Master Value
> swoole.enable_coroutine => On => On
> swoole.display_errors => On => On
> swoole.use_shortname => On => On
> swoole.fast_serialize => Off => Off
> swoole.unixsock_buffer_size => 8388608 => 8388608
> 

5. What is your machine environment used (including version of kernel & php & gcc) ?

> PHP 7.2.15-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  8 2019 15:37:29) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.2.15-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by twose** [comment]
duplicated, see #1630, #2369 .

**Comment by twose** [comment]
For backward compatibility, we can't change the API results.

**Comment by nationdata-it** [comment]
Thanks for the response.

**Comment by mahmed-ntd** [comment]
oh sorry for creating a duplicate and thanks for your response.
