### ISSUE TITLE
进入redis协程客户端之后协程id不一致

### ISSUE THREAD

**Issue by highwayliu** [swoole/swoole-src#2384]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
监听onRequest方法，disPatch调用redis协程客户端执行了一次incr操作
```php
$register->set($register::onRequest,function (\swoole_http_request $request,\swoole_http_response $response)use($dispatcher){
            $request_psr = new Request($request);
            $response_psr = new Response($response);
            try{
                EasySwooleEvent::onRequest($request_psr,$response_psr);
                        file_put_contents("/tmp/ee.log", "put1\t" . SERVER_NAME . "\t" . Coroutine::getUid() . "\t" . var_export($response_psr,true) . "\n", FILE_APPEND);
                    $dispatcher->dispatch($request_psr,$response_psr);
            file_put_contents("/tmp/ee.log", "put2\t" . SERVER_NAME . "\t" . Coroutine::getUid() . "\t" . var_export($response_psr, true) . "\n", FILE_APPEND);
}
```

2. What did you expect to see?

协程id一致

3. What did you see instead?
```php
put1    Demo    52641   EasySwoole\Core\Http\Response::__set_state(array(
   'response' =>
  Swoole\Http\Response::__set_state(array(
     'fd' => 52640,
     'header' => NULL,
     'cookie' => NULL,
     'trailer' => NULL,
  )),
   'sendFile' => NULL,
   'isEndResponse' => 0,
   'statusCode' => 200,
   'reasonPhrase' => 'OK',
   'cookies' =>
  array (
  ),
   'protocolVersion' => '1.1',
   'headers' =>
  array (
  ),
   'body' => NULL,
))
put2    Demo    52632   EasySwoole\Core\Http\Response::__set_state(array(
   'response' =>
  Swoole\Http\Response::__set_state(array(
     'fd' => 52631,
     'header' =>
    array (
      'Content-Type' => 'application/json;charset=utf-8',
    ),
     'cookie' => NULL,
     'trailer' => NULL,
  )),
   'sendFile' => NULL,
   'isEndResponse' => 2,
   'statusCode' => 200,
   'reasonPhrase' => 'OK',
   'cookies' =>
  array (
  ),
   'protocolVersion' => '1.1',
   'headers' =>
  array (
    'Content-type' =>
    array (
      0 => 'application/json;charset=utf-8',
    ),
  ),
   'body' => NULL,
))
```
协程id和reponse fd不一致

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.2.10

5. What is your machine environment used (including version of kernel & php & gcc) ?

kernel  Linux version 3.10.106
php 7.1
gcc 4.8.5

**Comment by mabu233** [comment]
我记得你在es群说过这是压测时出现的，高并发的时候两个 file_put_contents之间可能会有另一个请求的file_put_contents插入，这不是很正常吗？

**Comment by highwayliu** [comment]
> 我记得你在es群说过这是压测时出现的，高并发的时候两个 file_put_contents之间可能会有另一个请求的file_put_contents插入，这不是很正常吗？

是多轮高并发之后停止策略，单独发一个curl，会出现这样的情况，这时候swoole的日志显示回包回不出去，连接已断开。
[2019-02-25 15:18:54 *30295.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=9172] does not exists.
[2019-02-25 15:18:54 *30295.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=9173] does not exists.
[2019-02-25 15:18:54 *30295.0]	NOTICE	swFactoryProcess_finish (ERROR 1005): connection[fd=9174] does not exists.

**Comment by highwayliu** [comment]
> 我记得你在es群说过这是压测时出现的，高并发的时候两个 file_put_contents之间可能会有另一个请求的file_put_contents插入，这不是很正常吗？

升级为4.2.13 在同样的多轮压测策略之后，没发现这样的问题

**Comment by matyhtf** [comment]
说明这是不同的请求。所以协程ID不一样。
