### ISSUE TITLE
swoole4.2.12  中channel 一些函数无效

### ISSUE THREAD

**Issue by YeDongaidiiqu** [swoole/swoole-src#2385]
![image](https://user-images.githubusercontent.com/25131877/53331505-09f66e00-392c-11e9-8b1e-0ccdc4630b58.png)

push 之后发现这里的length  和  isEmpty  为 0 和true
通道里已经push进去内容了啊

**Comment by twose** [comment]
你写的不对, 不是无效

**Comment by YeDongaidiiqu** [comment]
![image](https://user-images.githubusercontent.com/25131877/53331973-29da6180-392d-11e9-9144-3c6eacdf9e22.png)
为什么结果还是一样，
@twose

**Comment by twose** [comment]
尊重彼此时间, 请贴出所有代码

**Comment by YeDongaidiiqu** [comment]
ok，不好意思

function stkData(array $data, $demoRedis)
    {
        go(function () use($data,$demoRedis){
            $obj = $data["obj"];
            $filed = $data["field"];
            $field = explode(",", $filed);
            $obj = explode(",", $obj);
            $chan = new co\Channel(count($obj) * count($field));
            foreach ($obj as $code) {
                go(function () use ($code, $field, $chan, $demoRedis) {
                    //获取数据
                    foreach ($field as $scheme) {
                        go(function () use ($code, $scheme, $chan, $demoRedis) {
                            $da = $demoRedis->hGet($code, $scheme);
                            $res = $chan->push(["code" => $code, "field" => $scheme, "data" => $da]);
                            var_dump(9999999999);
                            var_dump($res);
                            var_dump($chan->length());
                            var_dump($chan->isEmpty());
                            var_dump(9999999999);
                        });
                    }
                });
            }
            \swoole_event::wait();
            var_dump($chan->isEmpty());
            var_dump($chan->length());
            $allData = [];
            while (1) {
                $poData = $chan->pop();
                $allData[$poData["code"]][$poData["field"]] = $poData["data"];
                var_dump($chan->isEmpty());
                var_dump($chan->length());
                var_dump(2222222);
            }
            var_dump(333333333);
            var_dump($allData);
            $chan->close();
        });
    }
@twose

**Comment by mabu233** [comment]
不是已经被你 pop出来了？

**Comment by YeDongaidiiqu** [comment]
ok 你再观察这段代码
 function stkData(array $data, $demoRedis):array
    {
        $re=go(function ()use($data,$demoRedis){
            $obj = $data["obj"];
            $filed = $data["field"];
            $field = explode(",", $filed);
            $obj = explode(",", $obj);
            $count=count($obj) * count($field);
            $chan = new co\Channel($count);
            foreach ($obj as $code) {
                go(function () use ($code, $field, $chan, $demoRedis) {
                    //获取数据
                    foreach ($field as $scheme) {
                        go(function () use ($code, $scheme, $chan, $demoRedis) {
                            $da = $demoRedis->hGet($code, $scheme);
                            $res = $chan->push(["code" => $code, "field" => $scheme, "data" => $da]);
                            var_dump($chan->isEmpty());
                            var_dump($chan->length());
                        });
                    }
                });
            }
            $allData = [];
//            for ($i=$count;$i>0;$i--) {
//                $poData = $chan->pop();
//                $allData[$poData["code"]][$poData["field"]] = $poData["data"];
//            }
//           \swoole_event::wait();
            $chan->close();
            var_dump($allData);
            return $allData;
        });
//        var_dump($re);
    }


![image](https://user-images.githubusercontent.com/25131877/53382864-9185c080-39b0-11e9-9456-e247c6570177.png)


这处的结果也一样

@twose

**Comment by YeDongaidiiqu** [comment]
![image](https://user-images.githubusercontent.com/25131877/53383014-1e307e80-39b1-11e9-9537-bcc41d977fa2.png)

我再pop之前也看了一下长度，也是一样的
![image](https://user-images.githubusercontent.com/25131877/53383083-50da7700-39b1-11e9-9fee-802c84d2977a.png)

@mabu233
