### ISSUE TITLE
Swoole hangs under WSL

### ISSUE THREAD

**Issue by codercms** [swoole/swoole-src#2386]
Swoole hangs under Windows Linux Subsystem when trying to send big amount of data by using chunks.

Reference to issue in Microsoft/WSL - https://github.com/Microsoft/WSL/issues/3858
All details (including trace and steps to reproduce) can be found in referenced issue.

Swoole version: 4.2.13
OS version: WSL Linux Ubuntu 18.04
PHP version: 7.2.15
Windows versions: 1803 and 1809

Simple example to reproduce:
```php
<?php
$http = new swoole_http_server("127.0.0.1", 1216);
$http->set(array(
    'reactor_num' => 1,
    'worker_num' => 1,
    'send_yield' => true
));

$http->on("start", function ($server) {
//    echo "Swoole http server is started at http://127.0.0.1:1216\n";
});

$http->on("request", function ($request, $response) {
    $response->header("Content-Type", "text/plain");

    $res = \random_bytes(2000000);
    $chunks = \str_split($res, 1024);

    foreach ($chunks as $chunk) {
        $response->write($chunk);
    }

    $response->end();
});

$http->start();
```
Trace available here - https://gist.github.com/codercms/369b21485022c7f01a9da3a47d9d74a5

Simple example to bypass issue:
```php
$http->on("request", function ($request, $response) {
    $response->header("Content-Type", "text/plain");

    $res = \random_bytes(2000000);
    $chunks = \str_split($res, 1024);

    foreach ($chunks as $chunk) {
        $response->write($chunk);
        // sleep for 1 microsecond (if it's still not work sleep time should be increased)
        \usleep(10);
    }

    $response->end();
});
```
Trace available here - https://gist.github.com/codercms/03326fb12600657412d5a8c4083b42f1

**Comment by matyhtf** [comment]
This may be a bug in wsl. According to strace's log, the pipeline cannot trigger writable events.

**Comment by codercms** [comment]
@matyhtf It would be great if you will provide information for MS engineers here - https://github.com/Microsoft/WSL/issues/3858

**Comment by matyhtf** [comment]
WSL2 solves this problem and now fully uses the linux virtual machine
