### ISSUE TITLE
[Swoole-v4.2.13]WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by to2false** [swoole/swoole-src#2387]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
使用Coroutine mysql
示例：
- https://github.com/to2false/swoole-issue-demo/blob/master/index.php 在命名空间下 `call_user_func_array`报错
- https://github.com/to2false/swoole-issue-demo/blob/master/swoole.php 正常

    完整例子: https://github.com/to2false/swoole-issue-demo
2. What did you expect to see?

    mysql query能运行成功

3. What did you see instead?

```
[2019-02-26 10:56:06 $40794.0]	WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.2.13, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

    v4.2.13

5. What is your machine environment used (including version of kernel & php & gcc) ?
    MacOS, version 10.14.3

    Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

    PHP 7.2.11

```
gcc --version

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by matyhtf** [comment]
请使用 github master 代码，或者使用 

```php
 $result = $this->mysql->{$name}(...$arguments);
```
代替`call_user_func_array`

**Comment by to2false** [comment]
@matyhtf 👌

**Comment by matyhtf** [comment]
@to2false 是 2.0 时代遗留的兼容代码存在一些问题，已经修复。
