### ISSUE TITLE
swoole4.2.13 swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by wjcgithub** [swoole/swoole-src#2388]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
程序在这里：https://github.com/wjcgithub/php-amqplib/tree/master/demo
阅读readme可安装具体环境

遇到的问题readme下面的问题2
报错是:
[2019-02-26 11:51:01 $11472.0]	WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.2.13, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

2. What did you expect to see?
期望得到的是每个进入协程中的rabbitmq client请求都能成功写入rabbitmq服务， 每个请求都能收到监听的ack  nack  return handler 回调，　即使达到max_request数量重启的过程中

3. What did you see instead?
[2019-02-26 11:51:01 $11472.0]	WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.2.13, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

valgrind.log
2269 ==17173== For counts of detected and suppressed errors, rerun with: -v
2270 ==17173== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
2271 ==17323== Invalid read of size 8
2272 ==17323==    at 0xC7282B6: swoole::Coroutine::get_current() (base.cc:101)
2273 ==17323==    by 0xC771CD4: is_in (swoole_coroutine.h:119)
2274 ==17323==    by 0xC771CD4: swoole::PHPCoroutine::check() (swoole_coroutine.cc:370)
2275 ==17323==    by 0xC767A84: zim_swoole_channel_coro_push(_zend_execute_data*, _zval_struct*) (swoole_channel_coro.cc:168)
2276 ==17323==    by 0x8F59E4: ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER (zend_vm_execute.h:1032)
2277 ==17323==    by 0x8F59E4: execute_ex (zend_vm_execute.h:59768)
2278 ==17323==    by 0xC77223E: swoole::PHPCoroutine::create_func(void*) (swoole_coroutine.cc:281)
2279 ==17323==    by 0xC72937A: swoole::Context::context_func(void*) (context.cc:87)
2280 ==17323==    by 0xC7DDCB0: make_fcontext (make_x86_64_sysv_elf_gas.S:64)
2281 ==17323==  Address 0xb8ca7078 is on thread 1's stack
2282 ==17323==
2283 ==17323==
2284 ==17323== Process terminating with default action of signal 11 (SIGSEGV): dumping core
2285 ==17323==  Access not within mapped region at address 0xB8CA7078
2286 ==17323==    at 0xC7282B6: swoole::Coroutine::get_current() (base.cc:101)
2287 ==17323==    by 0xC771CD4: is_in (swoole_coroutine.h:119)
2288 ==17323==    by 0xC771CD4: swoole::PHPCoroutine::check() (swoole_coroutine.cc:370)
2289 ==17323==    by 0xC767A84: zim_swoole_channel_coro_push(_zend_execute_data*, _zval_struct*) (swoole_channel_coro.cc:168)
2290 ==17323==    by 0x8F59E4: ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER (zend_vm_execute.h:1032)
2291 ==17323==    by 0x8F59E4: execute_ex (zend_vm_execute.h:59768)
2292 ==17323==    by 0xC77223E: swoole::PHPCoroutine::create_func(void*) (swoole_coroutine.cc:281)
2293 ==17323==    by 0xC72937A: swoole::Context::context_func(void*) (context.cc:87)
2294 ==17323==    by 0xC7DDCB0: make_fcontext (make_x86_64_sysv_elf_gas.S:64)
2295 ==17323==  If you believe this happened as a result of a stack
2296 ==17323==  overflow in your program's main thread (unlikely but
2297 ==17323==  possible), you can try to increase the size of the
2298 ==17323==  main thread stack using the --main-stacksize= flag.
2299 ==17323==  The main thread stack size used in this run was 8388608.
2300 ==17323==
2301 ==17323== HEAP SUMMARY:
2302 ==17323==     in use at exit: 375,767,998 bytes in 25,979 blocks
2303 ==17323==   total heap usage: 36,388 allocs, 10,409 frees, 731,495,862 bytes allocated

4. What version of Swoole are you using (show your `php --ri swoole`)?
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.2.13
Built => Feb 25 2019 11:08:30
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled
Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
Linux evolution 4.4.0-134-generic #160~14.04.1-Ubuntu SMP Fri Aug 17 11:07:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)

PHP 7.2.12 (cli) (built: Nov 20 2018 19:05:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by twose** [comment]
Fixed via 5458cbc
