### ISSUE TITLE
各位大神帮忙看下这个是不是swoole的一个bug

### ISSUE THREAD

**Issue by xyzj91** [swoole/swoole-src#2389]
请问下我在swoole\server中新增监听一个端口,启用了websocket协议解析.在onOpen的回调中拿到的server对象为什么是swoole\server对象而不是websocket\server对象,而在onMessage回调中拿到的却是websocket\server对象,按理来说在onOpen回调中的server对象不应该是websocket\server对象吗?

**Comment by twose** [comment]
没办法升级Server对象, 只能先使用Websocket\Server然后增加tcp的端口

**Comment by xyzj91** [comment]
> 没办法升级Server对象, 只能先使用Websocket\Server然后增加tcp的端口

好吧,也只能先这样实现了
