### ISSUE TITLE
swoole_event_dispatch在定时器存在时执行一次后并没有让出控制权

### ISSUE THREAD

**Issue by iam2c** [swoole/swoole-src#2390]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
<?php
    class Process extends Swoole\Process
    {
        public function __construct()
        {
            parent::__construct([$this, 'run']);
        }
        public function run()
        {
            swoole_set_process_name("process");

            swoole_timer_tick(800, function () {
                echo "Tick\n";
            });

            while(1) {
                echo "loop\n";
                sleep(1);
                swoole_event_dispatch();
            }
        }
    }
    $server = new Swoole\Server('0.0.0.0', 12341, SWOOLE_PROCESS, SWOOLE_SOCK_UDP);
    $server->set(['log_file' => '/dev/null']);
    $server->on('packet', function () { });
    $server->addProcess(new Process);
    $server->start();
```

2. What did you expect to see?

loop
Tick
loop
Tick
...
3. What did you see instead?
loop
Tick
Tick
Tick
...

4. What version of Swoole are you using (show your `php --ri swoole`)?

master

5. What is your machine environment used (including version of kernel & php & gcc) ?

php:7.0.32
centos 7

**Comment by iam2c** [comment]
我看了源码，应该是swReactorEpoll_wait（我现在系统用的epoll，其他IO多路复用应该存在同样问题），当`n = epoll_wait(epoll_fd, events, max_event_num, msec);`这里返回0时（因为只要定时器），那么走这个分支：
`else if (n == 0)
  {
       if (reactor->onTimeout != NULL)
       {
            reactor->onTimeout(reactor);
       }
       continue;
 }`
没有判断reactor->once，所以没有break跳出循环

**Comment by matyhtf** [comment]
感谢反馈，确实存在问题，已经修复。
