### ISSUE TITLE
跑定时器出现内存泄漏，如何定位是哪块代码有问题？

### ISSUE THREAD

**Issue by jqhph** [swoole/swoole-src#2396]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
>目前是使用swoft框架跑了个定时器，每隔几个小时就报内存超出，然后worker进程就重启，由于看不到代码追踪信息，无法定位到具体是哪里出现了问题，想问下有什么好的方法监控下进程

2. What did you expect to see?

3. What did you see instead?

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /var/www/swoft/vendor/swoft/db/src/Statement.php on line 465
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.2.12

5. What is your machine environment used (including version of kernel & php & gcc) ?
php 7.2
gcc version 6.3.0
使用docker容器

**Comment by twose** [comment]
检查代码中使用全局变量和静态变量的地方

**Comment by jqhph** [comment]
> 检查代码中使用全局变量和静态变量的地方

反复检查过多次，没有发现有问题的地方。除了检查代码逻辑，还有没有其他可以监控或定位问题代码块的方式？

**Comment by twose** [comment]
是否使用了`Timer::tick`方法并使用了传参的方法调用?

**Comment by jqhph** [comment]
> 是否使用了`Timer::tick`方法并使用了传参的方法调用?
只传了定时器间隔时间和匿名函数，添加方法如下：
```php
// 添加定时器
$timerId = swoole_timer_tick($interval, $taskHandler);
```

**Comment by twose** [comment]
那应该和底层无关 需要自检 进程退出时有内存分配不足的位置 大概率会在频繁申请内存的地方 可以自己加大频率试试
