### ISSUE TITLE
Files uploaded by swoole under macOS 10.12.6 system are detected by is_uploaded_file failed, but on Centos 7.6, there is no such problem.

### ISSUE THREAD

**Issue by PersiLiao** [swoole/swoole-src#2398]
RT

OS: macOS 10.12.6
PHP Version: php7.1.22
Swoole Version: 4.2.13

**Comment by twose** [comment]
unit test here: https://github.com/swoole/swoole-src/blob/master/tests/swoole_http_server/uploadFile.phpt

have a try.

**Comment by PersiLiao** [comment]
Solved this problem by setting upload_tmp_dir

`$serv->set([ 'upload_tmp_dir' => '/private/tmp' ]);`

**Comment by PersiLiao** [comment]
Solved this problem by setting upload_tmp_dir

```php
$serv->set([ 'upload_tmp_dir' => '/private/tmp' ]);
```
