### ISSUE TITLE
MySQL coroutine, select returns empty array

### ISSUE THREAD

**Issue by MarcFaussurier** [swoole/swoole-src#2400]
Please answer these questions before submitting your issue. Thanks!

**1. What did you do?** If possible, provide a simple script for reproducing the error.

```
go(function () {
    include_once __DIR__ ."/../vendor/autoload.php";
    $server = array(
        'host' => '127.0.0.1',
        'user' => 'root',
        'password' => '123456##',
        'database' => 'cde_code',
    );
    $db = new \Swoole\Coroutine\MySQL();
    $db->connect($server);
    if ($db == false) {
        throw new Exception("NOT CONNECTED");
    } else {
        echo "Connected";
    }
    $result = $db->query('SELECT * FROM user WHERE row_id = 1');
    var_dump($result);
});
```

2. What did you **expect to see?**

Connected array(1) {
 ...
}

3. **What did you see instead?**

Connected array(0) {
}

4. **What version of Swoole** are you using (show your `php --ri swoole`)?

4.2.13

5. **What is your machine environment used** (including version of kernel & php & gcc) ?

PHP 7.3.2 (NTS )

I am using MacOS High Sierra with MySQL 8.0.15

----

When I am using the mysql workbench, everything is just fine with the the correct output
'1','marcfsr','faussurier.marc@icloud.com','0000','2019-03-04 16:27:03','Marc','Faussurier'

Thank you for reading,, if you need something else just tell it to me.

**Comment by twose** [comment]
var_dump `$db->error` `$db->errno`

and the code should be `if (!$db->connect($server))`, not `if ($db == false)`

**Comment by MarcFaussurier** [comment]
Thank you. Its indeed working, the error was from my side.
