### ISSUE TITLE
undefined symbol: spl_ce_Countable

### ISSUE THREAD

**Issue by i-fail** [swoole/swoole-src#2404]
I did install swoole via pecl, got /usr/lib/php/20151012/swoole.so
Added it to php.ini

Now if I run PHP, I get this:

```
# php
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/swoole.so' (tried: 
/usr/lib/php/20151012/swoole.so (/usr/lib/php/20151012/swoole.so: undefined symbol: spl_ce_Countable),
/usr/lib/php/20180731//usr/lib/php/20151012/swoole.so.so (/usr/lib/php/20180731//usr/lib/php/20151012/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```
PHP info:

```
# php -v
PHP 7.3.2-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  8 2019 15:43:26) ( NTS )
Zend Engine v3.3.2
```

OS: Ubuntu 16.04.6 LTS

**Comment by twose** [comment]
PHP7.0.0 released on 20151204, but your extension dir is 20151012, check your `phpize` version.

**Comment by i-fail** [comment]
```
# phpize -v
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
```

**Comment by twose** [comment]
@i-fail  your phpize belong to another PHP5 version, there must be more than one PHP on your machine, check it by yourself.

**Comment by i-fail** [comment]
Are you sure? I found phpize7.0 left from the previous version

```
# phpize7.0 -v
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
```

**Comment by twose** [comment]
@i-fail You are right, but your php version is 7.3, it makes compiler choose 7.3 way to compile, but your are using phpize of 7.0.

**Comment by i-fail** [comment]
Thank you for your help, twose. I was finally able to install Swoole after messing with PHP versions on my server. On my quite old VPS I got these benchmarks for the trivial "hello world" app:

Swoole: 31K req/sec
NodeJS: 10K req/sec (with cluster and nodemon)
Regular PHP: 3K req/sec

Good job!
