### ISSUE TITLE
can not kill master

### ISSUE THREAD

**Issue by pantaovay** [swoole/swoole-src#2406]
version 4.2.12
`kill master process`, all worker processes and manager process are killed, but master process is not killed and always exists

**Comment by twose** [comment]
Lose respect for the template

**Comment by pantaovay** [comment]
Please answer these questions before submitting your issue. Thanks!

1. swoole websocket server

2. kill master and all processes should be killed

3. master process is not killed

4. swoole 4.2.12

5. ubuntu 18.04; php 7.2.14; gcc 7.3.0

**Comment by twose** [comment]
Can't reproduce your problem, as of now, I don’t have any clues about this.

**Comment by pantaovay** [comment]
> Can't reproduce your problem, as of now, I don’t have any clues about this.

I recorded a video about the condition: https://youtu.be/bKckCFi638Y

**Comment by woody712** [comment]
I also have this problem at Swoole 4.2.9

Sometimes it can be killed at once; sometimes I had to kill it twice, then it was killed.

if I didn't kill the master process first, I had no chance to kill it.

**Comment by woody712** [comment]
In my case, I start swoole as a HTTP server in docker container.

I typed a few words when the master process exited. 
`$http->on(
    'shutdown',
    function (swoole_server $server) {
        var_dump('shutdown');
    }
);`

It can be displayed at the first "docker stop"

after that, It will never be seen.

So I try to enter the container and kill the master process (PID 1) manually
like this: `kill -15 1` (mock "docker stop")

The master process can be killed more than one attempt.

**Comment by matyhtf** [comment]
Did you use addProcess to add a custom user process?

**Comment by matyhtf** [comment]
If yes, listen to the SIGTERM signal and exit the process when it receives the signal

**Comment by pantaovay** [comment]
Disable GRPC extension and master can be killed successfully.

😄

**Comment by xiangjihan** [comment]
Me too，and I am not install GRPC extension. Maybe others，it needs to be determined on the next.
