### ISSUE TITLE
php7.2 + swoole 4.3 设置心跳包参数无效

### ISSUE THREAD

**Issue by hongbin-hsu** [swoole/swoole-src#2408]
环境：php7.2 + swoole 4.3 
设置参数：
   'heartbeat_idle_time' => 3600,
    'heartbeat_check_interval' => 60,

1. 1分钟后，服务端自动断开，发送，Connection has been disconnected，php7.2 + swoole 4.2.12无此问题

2. 被心跳检测切断的连接依然会触发onClose事件回调，这个也未来被触发

**Comment by matyhtf** [comment]
外网有可能是你的网关层自动切断连接，可能与服务器无关。请使用 strace 和 tcpdup 抓包确认。
