### ISSUE TITLE
完善详细的文档，其实有益于提高推广度

### ISSUE THREAD

**Issue by 995933447** [swoole/swoole-src#2410]

**Comment by twose** [comment]
文档是完全开放编辑的, 除了开发组抽时间完善, 社区也可以贡献.
你提的建议是有道理, 而且以前我也曾提过, 现在我是开发组的一员, 我也花费了大量的时间编写单元测试和文档, 但我发现, 生态没有社区的贡献是不行的, 要理解开发组的精力是有限的, 我们不能都做伸手党, 大家应该一起把文档完善起来.
