### ISSUE TITLE
[4.3.0] Build issue on 32-bit

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#2411]
Build is ok, but unusable

`modules/swoole.so: undefined symbol: _ZN6swoole7Context15get_stack_usageEv`

64-bit builds are OK

**Comment by twose** [comment]
@remicollet 
We have 32-bit env, but unfortunately, this situation is not covered.
Can you have a try with the master branch? 
Thanks.

**Comment by remicollet** [comment]
>  Can you have a try with the master branch?

4.3.0 +  5fee743  is ok on 32-bit

Thanks for the quick fix
