### ISSUE TITLE
WARNING	swManager_check_exit_status: worker#1[pid=61008] abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by BlackDogLi** [swoole/swoole-src#2412]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by BlackDogLi** [comment]
PHP --ri swoole:

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.0
Built => Mar  7 2019 17:56:06
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2q  20 Nov 2018
http2 => enabled
pcre => enabled
zlib => enabled
brotli => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

uname -a：

Darwin liyudeMacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

php -v:

PHP 7.3.2 (cli) (built: Feb 14 2019 10:08:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2, Copyright (c) 1999-2018, by Zend Technologies

gcc -v:

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by BlackDogLi** [comment]
mac os系统,进程无线重启求解答

**Comment by matyhtf** [comment]
@BlackDogLi 请使用 Linux 系统，然后使用 `USE_ZEND_ALLOC=0 valgrind php your_file.php`跟踪程序的执行，将有关的错误信息，如`invalid read/write` 贴上来。

**Comment by BlackDogLi** [comment]
> @BlackDogLi 请使用 Linux 系统，然后使用 `USE_ZEND_ALLOC=0 valgrind php your_file.php`跟踪程序的执行，将有关的错误信息，如`invalid read/write` 贴上来。

Linux系统可以正常执行，但是我的mac os系统下不正常，是仅支持Linux系统么

**Comment by matyhtf** [comment]
你试试清理项目（`make clean`），重新编译。

**Comment by BlackDogLi** [comment]
@matyhtf php扩展：
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
phpdbg_webhelper
posix
pspell
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
swoole
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache


我用的laravel5.6框架
自己写的http_sever没有问题:
```
$http = new swoole_http_server('127.0.0.1', 1215);

$http->set([
    'worker_num' => 8,
    'max_request' => 5000,
]);

//工作进程启动
$http->on('WorkerStart', function ($server, $worker_id) {
    require __DIR__.'/../vendor/autoload.php';
    require_once __DIR__.'/../bootstrap/app.php';
});

//监听Http请求
$http->on('request', function ($request, $response) {

    //server信息
    if (isset($request->server)) {
        foreach ($request->server as $k => $v) {
            $_SERVER[strtoupper($k)] = $v;
        }
    }

    //header信息
    if (isset($request->header)) {
        foreach ($request->header as $k => $v) {
            $_SERVER[strtoupper($k)] = $v;
        }
    }

    //get请求
    if ($request->get) {
        foreach ($request->get as $k => $v) {
            $_GET[$k] = $v;
        }
    }

    //post请求
    if ($request->post) {
        foreach ($request->post as $k => $v) {
            $_POST[$k] = $v;
        }
    }

    //文件请求
    if ($request->files) {
        foreach ($request->files as $k => $v) {
            $_FILES[$k] = $v;
        }
    }

    //cookie请求
    if ($request->cookie) {
        foreach ($request->cookie as $k => $v) {
            $_COOKIE[$k] = $v;
        }
    }

    ob_start();//启用缓冲区

    //加载Laravel请求核心模块
    $kernel = app()->make(Illuminate\Contracts\Http\Kernel::class);
    $laravelResponse = $kernel->handle(
        $request = Illuminate\Http\Request::capture()
    );
    $laravelResponse->send();
    $kernel->terminate($request, $laravelResponse);

    $res = ob_get_contents();   //获取缓冲区的内容
    ob_end_clean(); //清除缓冲区

    $response->end($res);
});

$http->start();
```

但是用到swooletw/laravel-swoole(https://github.com/swooletw/laravel-swoole)这个插件的的时候便会报错

**Comment by twose** [comment]
尝试在php.ini中配置 `pcre.jit=0`
此外你的全局变量使用方式十分危险

**Comment by BlackDogLi** [comment]
@twose 在php.ini中配置 `pcre.jit=0`解决了问题，方便说下原因么，是因为php的jit即使编译器和os的有冲突么？

嗯嗯，那个只是方便测试临时写的一个文件。您有什么好的建议么，我不吝赐教

**Comment by matyhtf** [comment]
这可能是 `pcre` 的`bug`，暂时先关闭，等待官方发新版本解决。

**Comment by honglibin** [comment]
我在使用定时任务时也出现了这个问题，控制台每过一段时间就会报出这个错误
![image](https://user-images.githubusercontent.com/330451/57196665-b0e13100-6f91-11e9-8e51-8795fae9575d.png)
已经使用了守护进程的模型运行，也将pcre.jit设置成0了，但还是会报错
![image](https://user-images.githubusercontent.com/330451/57196702-ef76eb80-6f91-11e9-9e1f-b7a1531b9f9f.png)
