### ISSUE TITLE
关于协程http客户端设置超时的一点疑问

### ISSUE THREAD

**Issue by kant712** [swoole/swoole-src#2413]
我起4个协程http客户端，设置超时为10s，发post请求(即Coroutine\Http\Client->post，并set([ 'timeout' => 10 ]))，结果过了40s才返回，是不是应该10s返回呢？

下面是版本信息：
CentOS Linux release 7.3.1611 (Core) 

PHP 7.2.15 (cli) (built: Mar  1 2019 11:41:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15, Copyright (c) 1999-2018, by Zend Technologies

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.2.13
Built => Mar  1 2019 11:43:30
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled
Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by twose** [comment]
HTTP收发数据包含多个发送和读取过程, 在网络不佳时可能会有一定误差

**Comment by twose** [comment]
四个HTTP客户端串行了, 起四个协程并发执行才会是10s

**Comment by shenzhe** [comment]
代码片段贴出来

**Comment by kant712** [comment]
下述代码工作符合预期，总耗时3s：
```
<?php
$http = new Swoole\Http\Server( "127.0.0.1" , 9501 );
$http->on( "request" , function( $request , $response )
{
    $c1 = new Swoole\Coroutine\Http\Client( '1.1.1.1' , 8081 );
    $c1->set( [ 'timeout' => 5 ] );
    $c1->setDefer();
    $c1->post( '/sleep' , [
        'time' => 3000 , //该服务过3s返回
    ] );
    $c2 = new Swoole\Coroutine\Http\Client( '1.1.1.1' , 8081 );
    $c2->set( [ 'timeout' => 5 ] );
    $c2->setDefer();
    $c2->post( '/sleep' , [
        'time' => 3000 ,
    ] );
    $c1->recv();
    $c2->recv();
    $response->end( $c1->body . $c2->body );
} );
$http->start();
```
下述代码测试的是服务器端口不可达的情形，耗时10s：
```
<?php
$http = new Swoole\Http\Server( "127.0.0.1" , 9501 );
$http->on( "request" , function( $request , $response )
{
    $c1 = new Swoole\Coroutine\Http\Client( '2.2.2.2' , 8081 ); //端口不可达
    $c1->set( [ 'timeout' => 5 ] );
    $c1->setDefer();
    $c1->post( '/sleep' , [
        'time' => 10000 ,
    ] );
    $c2 = new Swoole\Coroutine\Http\Client( '2.2.2.2' , 8081 ); //端口不可达
    $c2->set( [ 'timeout' => 5 ] );
    $c2->setDefer();
    $c2->post( '/sleep' , [
        'time' => 10000 ,
    ] );
    $c1->recv();
    $c2->recv();
    $response->end( $c1->body . $c2->body );
} );
$http->start();
```

下述代码测试的是服务器端口可达，但是在指定超时时间内不返回的情形，耗时10s：
```
<?php
$http = new Swoole\Http\Server( "127.0.0.1" , 9501 );
$http->on( "request" , function( $request , $response )
{
    $c1 = new Swoole\Coroutine\Http\Client( '1.1.1.1' , 8081 ); //端口可达
    $c1->set( [ 'timeout' => 5 ] );
    $c1->setDefer();
    $c1->post( '/sleep' , [
        'time' => 10000 ,
    ] );
    $c2 = new Swoole\Coroutine\Http\Client( '1.1.1.1' , 8081 ); //端口可达
    $c2->set( [ 'timeout' => 5 ] );
    $c2->setDefer();
    $c2->post( '/sleep' , [
        'time' => 10000 ,
    ] );
    $c1->recv();
    $c2->recv();
    $response->end( $c1->body . $c2->body );
} );
$http->start();
```

**Comment by kant712** [comment]
> 四个HTTP客户端串行了, 起四个协程并发执行才会是10s

代码已贴，麻烦帮忙看看，谢谢！

**Comment by kant712** [comment]
> 代码片段贴出来

代码已贴，麻烦帮忙看看，谢谢！

**Comment by twose** [comment]
defer模式是支持并发收包(recv), 而你此处卡在了连接阶段, 并不能通过defer特性并发连接
defer模式并不是一个很好的特性, 只是一个有缺陷的历史产物, 你需要使用CSP的编程模式
```php

go(function () {
    $s = microtime(true);
    $chan = new Co\Channel;
    for ($n = 2; $n--;) {
        go(function () use ($chan) {
            $cli = new Co\Http\Client('2.2.2.2', 8081); //端口不可达
            $cli->set(['timeout' => 1]);
            $cli->get('/');
            $chan->push($cli);
        });
    }
    for ($n = 2; $n--;) {
        $result = $chan->pop();
        var_dump($result->errMsg);
    }
    var_dump(microtime(true) - $s);
});
```

**Comment by kant712** [comment]
> defer模式是支持并发收包(recv), 而你此处卡在了连接阶段, 并不能通过defer特性并发连接
> defer模式并不是一个很好的特性, 只是一个有缺陷的历史产物, 你需要使用CSP的编程模式
> 
> ```
> go(function () {
>     $s = microtime(true);
>     $chan = new Co\Channel;
>     for ($n = 2; $n--;) {
>         go(function () use ($chan) {
>             $cli = new Co\Http\Client('2.2.2.2', 8081); //端口不可达
>             $cli->set(['timeout' => 1]);
>             $cli->get('/');
>             $chan->push($cli);
>         });
>     }
>     for ($n = 2; $n--;) {
>         $result = $chan->pop();
>         var_dump($result->errMsg);
>     }
>     var_dump(microtime(true) - $s);
> });
> ```

学习了，我再试试，谢谢！

**Comment by kant712** [comment]
> defer模式是支持并发收包(recv), 而你此处卡在了连接阶段, 并不能通过defer特性并发连接
> defer模式并不是一个很好的特性, 只是一个有缺陷的历史产物, 你需要使用CSP的编程模式
> 
> ```
> go(function () {
>     $s = microtime(true);
>     $chan = new Co\Channel;
>     for ($n = 2; $n--;) {
>         go(function () use ($chan) {
>             $cli = new Co\Http\Client('2.2.2.2', 8081); //端口不可达
>             $cli->set(['timeout' => 1]);
>             $cli->get('/');
>             $chan->push($cli);
>         });
>     }
>     for ($n = 2; $n--;) {
>         $result = $chan->pop();
>         var_dump($result->errMsg);
>     }
>     var_dump(microtime(true) - $s);
> });
> ```

代码可以正常工作，非常感谢！
不过我还有一点想不通，这里先创建客户端，然后get/post，接着就直接push进通道里，然后再pop通道，这样就可以接收到正确的结果。为什么不需要recv呢？
