### ISSUE TITLE
WARNING	swSignalfd_onSignal (ERROR 707): Unable to find callback function for signal Broken pipe: 13.

### ISSUE THREAD

**Issue by anychange** [swoole/swoole-src#2414]
运行tcp服务之后，测试连接和发信息正常，然后tcp关闭客户端，服务继续运行，长时间没有请求，一个晚上没动（确切时间不清楚），第二条用客户端连接后首次发请求服务端提示WARNING	swSignalfd_onSignal (ERROR 707): Unable to find callback function for signal Broken pipe: 13.但能正常接收消息，不知道什么情况，之后的请求就不出现了，fd是onreceive 的回调参数，swoole4.2.13+php7.3+centos6.1

**Comment by twose** [comment]
这仅是一个警告 说明你向已关闭的连接发送了数据 每次发送数据时需要判断返回值 如发送失败不应再继续发送
