### ISSUE TITLE
Swoole\Client removed async APIs

### ISSUE THREAD

**Issue by marlonfan** [swoole/swoole-src#2415]
如果 async api被禁用 我原有的基于Client的异步时间监听就无法实现了

但是协程client又没有提供on方法. 无法进行事件监听. 官方建议的做法是怎样的呢? 自己通过新开一个 go 去做通道传递和触发么?

这个做法会导致大批的第三方库无法使用.

**Comment by matyhtf** [comment]
Swoole\Client 异步客户端没有移除。还可以继续使用。

**Comment by marlonfan** [comment]
![image](https://user-images.githubusercontent.com/9349370/54030094-77848300-41e5-11e9-90ae-4e8e122427a3.png)

@matyhtf  https://github.com/swoole/swoole-src/blob/master/swoole_client.cc#L933

**Comment by marlonfan** [comment]
在发布了 > 4.2.9 以后, Client 使用 async 模式会报 fatal error

**Comment by shenzhe** [comment]
移到另一个扩展里了吧，错误提示可以说明下好些。
