### ISSUE TITLE
swoole 线上应用需要注意的事项？

### ISSUE THREAD

**Issue by lizhanghu** [swoole/swoole-src#2423]
哪位swoole大神分享下成熟的线上应用。 怎么防止线上出现段错误或者进程假死呢

**Comment by matyhtf** [comment]
请阅读 https://wiki.swoole.com/wiki/page/p-instruction.html

**Comment by matyhtf** [comment]
段错误的问题，一般都是底层 bug ，这个情况请参照 https://wiki.swoole.com/wiki/page/p-issue.html 向我们提交 issue

程序假死，这个问题，你需要使用strace gdb 等工具跟踪进程。

**Comment by lizhanghu** [comment]
多谢大神回复

**Comment by lizhanghu** [comment]
> 段错误的问题，一般都是底层 bug ，这个情况请参照 https://wiki.swoole.com/wiki/page/p-issue.html 向我们提交 issue
> 
> 程序假死，这个问题，你需要使用strace gdb 等工具跟踪进程。

多谢大神回复
