### ISSUE TITLE
A bug occurred in Swoole-v4.2.13, please report it.

### ISSUE THREAD

**Issue by ppyupp** [swoole/swoole-src#2425]
WARNING	swManager_check_exit_status: worker#5 abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.2.13, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

```
<?php

$MainServer = new Swoole\WebSocket\Server( "0.0.0.0", 3988 );

class Test
{
	public function __construct()
	{
		preg_replace( '/(\/+)/', '/', "ss" );
	}
}

$Test = new Test();

$MainServer->on('start', function ( swoole_server $Server ) { });

$MainServer->on('message', function (Swoole\WebSocket\Server $Server, $frame) {
	preg_split( "/a/", "dd" );
});

$MainServer->start();
```

收到message就报错

PHP 7.3.2
Swoole 4.2.13
macOS Mojave 10.14.3

**Comment by twose** [comment]
```php
ini_set('pcre.jit', 0);
```

PHP pcre-jit BUG on MacOS
