### ISSUE TITLE
官方有考虑适配支撑GRpc thift吗

### ISSUE THREAD

**Issue by sayid** [swoole/swoole-src#2426]
官方有考虑适配支撑GRpc thift吗？
微服务上php欠缺的太多了，这两种rpc协议是用的最多的，官方做好适配，能完善php的微服务生态提升Swoole的受众群体。
现在很多php团队转java都是因为微服务

**Comment by matyhtf** [comment]
这属于应用开发问题。
参考 https://github.com/swoole/grpc-client
