### ISSUE TITLE
v4.2.13 redis client 跨协程 subscribe

### ISSUE THREAD

**Issue by onanying** [swoole/swoole-src#2428]
DEMO：

```
<?php

\Swoole\Runtime::enableCoroutine(true);

go(function(){
	$redis = new \Redis();
	$redis->connect('192.168.1.150', 6379);
	$redis->select(0);
	$GLOBALS["redis"] = $redis;
	$redis->subscribe(["room_1"], function ($instance, $channel, $message) {
		var_dump($message);
	});
	var_dump('end');
});

swoole_timer_after(2000, function(){
	var_dump('swoole_timer_after');
    $redis = $GLOBALS["redis"];
	$redis->unsubscribe(["room_1"]);
});
```

描述：

client 在一个协程中建立，执行订阅，需要在另一个协程中关闭这个订阅，当使用 unsubscribe 时抛出：

```
[2019-03-13 04:32:09 @28709.0]	ERROR	is_available (ERROR 10002): Socket#4 has already been bound to another coroutine#1, reading of the same socket in multiple coroutines at the same time is not allowed.
```

当使用 close 时：

```
PHP Fatal error:  Uncaught RedisException: read error on connection in /data/t.php:12
Stack trace:
#0 /data/t.php(12): Redis->subscribe(Array, Object(Closure))
#1 {main}
  thrown in /data/t.php on line 12

Fatal error: Uncaught RedisException: read error on connection in /data/t.php:12
Stack trace:
#0 /data/t.php(12): Redis->subscribe(Array, Object(Closure))
#1 {main}
  thrown in /data/t.php on line 12
```

不是说 v4.2.13 可以跨协程使用 client 了么？现在这个情况，导致我不知道该如何取消、更新订阅？

执行结果与环境：

```
[root@localhost data]# php t.php 
string(18) "swoole_timer_after"
[2019-03-13 04:32:09 @28709.0]	ERROR	is_available (ERROR 10002): Socket#4 has already been bound to another coroutine#1, reading of the same socket in multiple coroutines at the same time is not allowed.

[root@localhost data]# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.2.13
Built => Mar  5 2019 03:03:57
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

**Comment by twose** [comment]
取消订阅也是一个新的redis请求, 看样子只能close关闭连接, 然后try catch捕获异常

**Comment by ihipop** [comment]
@twose 多个协程同时读或者同时写可否考虑在底层加锁呢？某个协程发完其实可以让下一个协程继续发的？

**Comment by twose** [comment]
> @twose 多个协程同时读或者同时写可否考虑在底层加锁呢？某个协程发完其实可以让下一个协程继续发的？

底层很难做到, 你在多个协程里对同一个对象的任何操作, 都有可能破坏对象的状态, 就和多线程编程一样, 多个线程同时修改一个资源, 会造成混乱, 同时, 也不可能让操作系统自动对你的每一个操作去加锁, 这样性能会极大地下降. 协程虽然是协作式调度, 但道理也是差不多的, 所以在协程的世界, 要准守CSP编程模式, 即跨协程的操作尽量都通过channel去控制, 资源应绑定在某个特定的协程上, 通过`channel->pop`来读取外界传进来的指令, 通过`channel->push`向外界推送生产结果

**Comment by ihipop** [comment]
@twose 之前不支持安全双工的时候我也是通过chan控制的，想到既然可以支持安全的读写分离（好奇是怎么实现的？因为写和读也是资源修改为什么不会造成混乱？），要是可以支持安全的同时读和同时写就更方便了。现在就是得通过包装的方式，把发送和接收都通过chan中转，稍微麻烦一些。

**Comment by twose** [comment]
> @twose 之前不支持安全双工的时候我也是通过chan控制的，想到既然可以支持安全的读写分离（好奇是怎么实现的？因为写和读也是资源修改为什么不会造成混乱？），要是可以支持安全的同时读和同时写就更方便了。现在就是得通过包装的方式，把发送和接收都通过chan中转，稍微麻烦一些。

之前不支持全双工是因为考虑到SSL重协商的问题[详见](http://gad.qq.com/article/detail/24255), 现在底层对SSL增加了一些调度逻辑来增加一定的安全保障, 如果是非SSL的通信全双工是安全的

同时读同时写是不可能的, 每个连接都有它自己的状态, 这是一个很基本的问题, 多个协程同时写或同时读一个socket, 你无法保证它们的运行顺序

而比较于底层对每个组件都做加锁排队, PHP层只需要稍作封装实现一个连接池, 就可以无需关心这个问题了

**Comment by onanying** [comment]
@twose  close() 抛出 Uncaught RedisException: read error on connection 是 redis 本来的逻辑么？能不抛出错误么？

**Comment by twose** [comment]
@onanying PHPRedis本身如果有IO失败就会抛出这个异常

**Comment by onanying** [comment]
@twose  正常 phpredis 提供的 close() 不抛出异常的：`$instance->close();`

```
go(function(){
	$redis = new \Redis();
	$redis->connect('192.168.1.150', 6379);
	$redis->select(0);
	$GLOBALS["redis"] = $redis;
	$redis->subscribe(["room_1"], function ($instance, $channel, $message) {
		$instance->close();
	});
	var_dump('end');
});
```

**Comment by ihipop** [comment]
> @twose 正常 phpredis 提供的 close() 不抛出异常的：`$instance->close();`
> 
> ```
> go(function(){
> 	$redis = new \Redis();
> 	$redis->connect('192.168.1.150', 6379);
> 	$redis->select(0);
> 	$GLOBALS["redis"] = $redis;
> 	$redis->subscribe(["room_1"], function ($instance, $channel, $message) {
> 		$instance->close();
> 	});
> 	var_dump('end');
> });
> ```

twose 的意思是不是因为不允许跨协程同时读写，然后`close()`会对socket有写操作?然后写失败了，就抛出异常了。

**Comment by onanying** [comment]
还是希望能实现不抛出错误，更加友好一些 @twose

**Comment by twose** [comment]
@onanying 
问题关闭了...所以没看到
是这样的, 订阅协程应该处于持续读取的状态, 此时如果网络连接突然断开了, 就会抛出如上的异常
你在传统PHP里调用close是不会出现异常的, 因为顺序执行, IO已经结束了, 而协程中, A协程正在读取, B去关闭, 就会打断它的读取操作, 自然就抛出异常了
