### ISSUE TITLE
内存泄漏如何定位

### ISSUE THREAD

**Issue by jqhph** [swoole/swoole-src#2429]
能否考虑开发一个专门动态追踪PHP程序是否出现内存泄漏的工具呢？代码复杂了之后程序出现内存泄漏调试太难了
有些隐藏比较深的bug非常难找到，如果有一款能调试PHP内存泄漏的工具就好了

**Comment by sy-records** [comment]
内部有考虑，目前在做

**Comment by jqhph** [comment]
> 正在开发一款检测常驻PHP进程内存泄漏的工具

那就太好了，现在有计划什么时候发布上线吗

**Comment by twose** [comment]
一般将资源绑定在协程上下文中, 避免使用全局变量, 严格把控全局变量和静态变量的使用, 就可以轻松规避内存泄漏问题, PHP作为一个有GC的语言, 开发的心智负担相对来说已经很低了, 特别复杂的项目, 对程序员的要求也不会太低
至于工具, 目前还没有很好的工具能够实现你的需求

**Comment by jqhph** [comment]
> 一般将资源绑定在协程上下文中, 避免使用全局变量, 严格把控全局变量和静态变量的使用, 就可以轻松规避内存泄漏问题, PHP作为一个有GC的语言, 开发的心智负担相对来说已经很低了, 特别复杂的项目, 对程序员的要求也不会太低
> 至于工具, 目前还没有很好的工具能够实现你的需求

已经在尽量避免使用全局变量和静态变量了，但是项目复杂加上使用了各种框架和插件之后，各种对象传递，比较难靠肉眼看出哪部分代码有问题。如果没有工具辅助排查这种问题，真的很难解决

**Comment by maxinliang007** [comment]
> 一般将资源绑定在协程上下文中, 避免使用全局变量, 严格把控全局变量和静态变量的使用, 就可以轻松规避内存泄漏问题, PHP作为一个有GC的语言, 开发的心智负担相对来说已经很低了, 特别复杂的项目, 对程序员的要求也不会太低
> 至于工具, 目前还没有很好的工具能够实现你的需求

已经把变量尽量都定义在协程了，对于外部变量和对象使用也是通过use引入，然后使用完全部unset掉但程序运行半小时依然会报内存溢出，频繁重启
