### ISSUE TITLE
swoole4.3+进程关闭bug

### ISSUE THREAD

**Issue by a07061625** [swoole/swoole-src#2430]
运行环境：

- PHP 7.1.27
- swoole 4.3.0/4.3.1,在4.2.12没有出现问题

环境重现样例代码：

```
script1.php：
    ...
    $server = new swoole_websocket_server('0.0.0.0', 9501);
    $server->on('task', function(){
        ...
    });
    $server->on('workerStart', function(){
        ...
       if($workId >= $server->setting['work_num']) {
           cli_set_process_title('Taska019501');
       } else {
           cli_set_process_title('Workera019501');
       }
       $server->tick(1000, function() {
           $server->task($data);
        });
        ...
    });
    $server->on('managerStart', function(){
        ...
        cli_set_process_title('Managera019501');
        ...
    });
    $server->on('start', function(){
        ...
        cli_set_process_title('Maina019501');
        ...
    });
    $server->start();
    ...

script2.php：
    ...
        swoole_process::kill(script1->master_pid);
    ...
```

运行script1

···
    /usr/local/php7/bin/php script1.php
    //运行正常，通过命令 ps -ef|grep a01可以看到main，manager，worker，task都正常状态
···

运行script2

···
    /usr/local/php7/bin/php script2.php
    //执行正常，没有报错，但是通过命令 ps -ef|grep a01可以看到main，manager和一个worker进程,没有task进程,正常情况下通过该命令应该是看不到这3个进程的
    //通过测试发现只要script1.php的onWorkerStart中存在以下代码,就一定会出现上述情况
    $server->tick(1000, function() {
        $server->task($data);
    });
···

**Comment by a07061625** [comment]
$server的配置参数如下：
daemonize = 1
dispatch_mode = 3
enable_coroutine = false

**Comment by a07061625** [comment]
运行script2后重新运行script1会报端口已经被占用的错误

**Comment by matyhtf** [comment]
无法重现你的问题。

**Comment by matyhtf** [comment]
![2019-03-18 11-18-12 的屏幕截图](https://user-images.githubusercontent.com/2017766/54504720-c3ff5980-496f-11e9-8ff8-98540670f593.png)
![2019-03-18 11-18-32 的屏幕截图](https://user-images.githubusercontent.com/2017766/54504721-c497f000-496f-11e9-8444-8a95da55c93a.png)
![2019-03-18 11-19-04 的屏幕截图](https://user-images.githubusercontent.com/2017766/54504722-c497f000-496f-11e9-937b-3ff445bfe68c.png)
![2019-03-18 11-19-10 的屏幕截图](https://user-images.githubusercontent.com/2017766/54504723-c497f000-496f-11e9-8e99-65ac7c689400.png)

**Comment by matyhtf** [comment]
```php
<?php
$server = new swoole_websocket_server('0.0.0.0', 9501);
$server->set([
    'task_worker_num' => 4,
    //'daemonize' => 1,
    'dispatch_mode' => 3,
    'enable_coroutine' => false,
]);

$server->on('task', function(){

});

$server->on('workerStart', function($server, $workId){

    if($workId >= $server->setting['worker_num']) {
         cli_set_process_title('Taska019501');
    } else {
        cli_set_process_title('Workera019501');
        
        $server->tick(1000, function() use ($server) {
                $data = ["hello" => 'world'];
                $server->task($data);
        });
    }
});

$server->on('message', function(){


});

$server->on('managerStart', function(){
    cli_set_process_title('Managera019501');
});


$server->on('start', function(){
    cli_set_process_title('Maina019501');
});

$server->start();
```

**Comment by a07061625** [comment]
> ```
> <?php
> $server = new swoole_websocket_server('0.0.0.0', 9501);
> $server->set([
>     'task_worker_num' => 4,
>     //'daemonize' => 1,
>     'dispatch_mode' => 3,
>     'enable_coroutine' => false,
> ]);
> 
> $server->on('task', function(){
> 
> });
> 
> $server->on('workerStart', function($server, $workId){
> 
>     if($workId >= $server->setting['worker_num']) {
>          cli_set_process_title('Taska019501');
>     } else {
>         cli_set_process_title('Workera019501');
>         
>         $server->tick(1000, function() use ($server) {
>                 $data = ["hello" => 'world'];
>                 $server->task($data);
>         });
>     }
> });
> 
> $server->on('message', function(){
> 
> 
> });
> 
> $server->on('managerStart', function(){
>     cli_set_process_title('Managera019501');
> });
> 
> 
> $server->on('start', function(){
>     cli_set_process_title('Maina019501');
> });
> 
> $server->start();
> ```

我停止服务进程用的是swoole_process::kill()，这个和直接在命令行kill有区别么？

**Comment by matyhtf** [comment]
没有区别。检查是否写错了 pid

**Comment by a07061625** [comment]
> 没有区别。检查是否写错了 pid

好的，非常感谢，我再检查下自己的原因
