### ISSUE TITLE
Swoole\Coroutine\Client-errCode-errMsg错误码未更新

### ISSUE THREAD

**Issue by loyating** [swoole/swoole-src#2435]
调用send或recv时将返回对应的错误码：错误码未更新。
流程说明：
client连接失败-重连成功-send成功-获取errCode、errMsg还是连接失败时候的错误码

环境：
PHP 7.2.13 (cli)
Swoole-Version => 4.3.1

**Comment by twose** [comment]
只有出错时才会更新错误码, 操作成功时设置错误码没有意义

**Comment by loyating** [comment]
send前将对端服务关闭，然后发送，结果是成功的，发送数据的尺寸与send返回尺寸一致，到下一次调用才会返回错误码
实际上这次数据发送需要重发的，这里该如何判定？

**Comment by twose** [comment]
TCP发送成功是将数据拷贝到了Linux的内核缓冲区, 并不代表对端一定收到了数据, 这个是无法保证的, 不然就不会有 `请求` + `响应` 的流程了, 除非对端返回了成功响应, 不然你永远无法判断对端确实收到了数据

**Comment by loyating** [comment]
好的，谢谢
