### ISSUE TITLE
swoole4.2.13内存泄漏

### ISSUE THREAD

**Issue by maxinliang007** [swoole/swoole-src#2436]
使用swoole协程遇到如下问题：
1、mysql连接频繁断开（目前解决方式：通过递归重连，但是有时会报内存溢出）
2、onrequest、go事件回调通过数组调用对象方法实现，会造成内存溢出，只有通过匿名函数实现才会好些
程序中针对相关数据和对象都做了unset操作，但仍然无法解决内存溢出问题

**Comment by mabu233** [comment]
能给下代码吗？或者你更新到4.3.0试试

**Comment by maxinliang007** [comment]
> 能给下代码吗？或者你更新到4.3.0试试

现在4.3.0保证各方面都稳定吗？我这是生产环境

**Comment by twose** [comment]
没有版本号, 没有环境信息, 没有代码
