### ISSUE TITLE
swoole4.2.13 channel问题

### ISSUE THREAD

**Issue by maxinliang007** [swoole/swoole-src#2437]
channel提供的empty、full等操作不准确
channel中元素索引从0开始，但是empty会把0作为true，full会作为false
但此时channel已经有了元素了

**Comment by matyhtf** [comment]
请仔细阅读文档中的说明。
channel 只能 pop push，没有 “索引”，不清楚你具体指的是什么？

**Comment by maxinliang007** [comment]
> 请仔细阅读文档中的说明。
> channel 只能 pop push，没有 “索引”，不清楚你具体指的是什么？

channel提供的empty、full等操作不准确，当我的channel有一个值时，调用empty得到的结果确是true

**Comment by matyhtf** [comment]
请写出对应的示例代码
