### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function swoole_async_writefile() 

### ISSUE THREAD

**Issue by gzhh** [swoole/swoole-src#2439]
当我执行下面这段代码时
swoole_async_writefile(__DIR__."/access.log", json_encode($content).PHP_EOL, function($filename) {                                                                                                      
    // todo                                                                                                                                                                                             
}, FILE_APPEND);

出现这样的错误
PHP Fatal error:  Uncaught Error: Call to undefined function swoole_async_writefile() 

swoole版本4.3.1
系统环境: centos7, php7.2, gcc4.8.5

**Comment by mabu233** [comment]
4.3以后，异步相关的已经移除到 ext-async 扩展了

**Comment by gzhh** [comment]
Thx :)
