### ISSUE TITLE
反馈个1.7.16-alpha问题

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#244]
#define SW_REACTOR_NUM             SW_CPU_NUM
-#define SW_WRITER_NUM              SW_CPU_NUM                                        
 #define SW_PIPES_NUM               (SW_WORKER_NUM/SW_WRITER_NUM + 1) //每个写线程pipes数组大小
 #define SW_WORKER_NUM              (SW_CPU_NUM*2)

SW_WRITER_NUM删除 里面还有引用。。 谢谢

**Comment by yiliaofan** [comment]
还有个问题： 多了一个(uint16_t)
swoole_server.c:1892:        addr_in.sin_port = htons((uint16_t) (uint16_t) (udp_info.port));

**Comment by matyhtf** [comment]
多谢反馈。
