### ISSUE TITLE
编译加载后出错,请求帮助

### ISSUE THREAD

**Issue by scdn** [swoole/swoole-src#2440]
运行环境
php 7.2.15
CentOS Linux release 7.6.1810 (Core) 
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 

编译之后,可以在modules文件夹生成swoole.so,在/etc/php.ini中添加了extension=swoole.so,运行php -m时提示以下错误:
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/lib64/php/modules/swoole.so (/usr/lib64/php/modules/swoole.so: undefined symbol: sockets_strerror), /usr/lib64/php/modules/swoole.so.so (/usr/lib64/php/modules/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

求大佬帮助

**Comment by scdn** [comment]
[root@localhost ~]# php --ri openssl

openssl

OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL Header Version => OpenSSL 1.0.2k  26 Jan 2017
Openssl default config => /etc/pki/tls/openssl.cnf

Directive => Local Value => Master Value
openssl.cafile => no value => no value
openssl.capath => no value => no value

**Comment by scdn** [comment]
swoole 是4.3.1

**Comment by mabu233** [comment]
sockets扩展开了？

**Comment by scdn** [comment]
> sockets扩展开了？

开了
[root@localhost ~]# php --ri sockets

sockets

Sockets Support => enabled

**Comment by sy-records** [comment]
编译没问题的话，就是加载顺序的问题？把extension=swoole.so加到sockest的加载后面呢

**Comment by sy-records** [comment]
> > sockets扩展开了？
> 
> 开了
> [root@localhost ~]# php --ri sockets
> 
> sockets
> 
> Sockets Support => enabled

**Comment by twose** [comment]
Fixed via eeddac8
