### ISSUE TITLE
Swoole / Pthreads compatibility

### ISSUE THREAD

**Issue by MarcFaussurier** [swoole/swoole-src#2441]
Hello,

**I tried to run a swoole server inside a thread (using pthreads).** 
I tried that because I'd like to share vars betweens all my swoole services using pthreads::thread::synchronise instead of Redis.

If it is impossible to archive then I'll start using Redis (You even made it available as a PHP service ... THANKS !!)

**1. What did you do? If possible, provide a simple script for reproducing the error.**

my test.php file :

```
$fail = new class extends \Thread {
    public function run() {

        $http = new swoole_http_server("127.0.0.1", 9501);

      $http->on("start", function ($server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$http->on("request", function ($request, $response) {
    $response->header("Content-Type", "text/plain");
    $response->end("Hello World\n");
});

$http->start();

    }
};
$fail->start() && $fail->join();
```

`php test.php
`

**2. What did you expect to see?**

"Swoole started ... blabla"

**3. What did you see instead?**

"PHP Fatal error:  Swoole\Server::__construct(): swoole_server only can be used in PHP CLI mode. in /Users/marcfsr/phpsocket.io/test.php on line 7"

**4. What version of Swoole are you using (show your `php --ri swoole`)?**

 4.3.1

**5. What is your machine environment used (including version of kernel & php & gcc) ?**

pthreads@master
PHP 7.3.3 zts

**Comment by MarcFaussurier** [comment]
> PHP does not support multi-thread. Swoole uses a multi-process model. Different worker process cannot access other's memory.If you want to read and write data across processes, please use swoole_table or swoole_atomic (from @matyhtf at https://github.com/swoole/swoole-src/issues/1574 )

I guess that I have my answer already.. 

I will use swoole tables. 

Why is multi-threading a such pain in PHP ?

**Comment by sshymko** [comment]
@MarcFaussurier 
You could also use [APCu](http://us3.php.net/apcu) shared memory; it appears to be compatible with Swoole.

**Comment by MarcFaussurier** [comment]
Thank you really much.
