### ISSUE TITLE
CPU usage Increased around %12 on version update from 4.2.12 to 4.3.1

### ISSUE THREAD

**Issue by ozgurhangisi** [swoole/swoole-src#2442]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

We have many servers with php 7.2.14 + Swoole 4.2.12. We just updated one server's php to 7.2.16 and swoole to 4.3.1 and CPU usage on updated server increased around %12. (we restarted the updated server a few times. But nothing is changed.)

All of the servers are behind the load balancer, get same amount of traffic and exactly do the same job. When I look at the CPU usage latest swoole version uses around %12 more CPU regularly.

I'm not sure if it's related with the latest php version or latest swoole but I just wanted to inform you about this. 

2. What did you expect to see?

I just noticed the CPU usage on the latest version and wanted to share with you.

3. What did you see instead?

~%12 more CPU usage.

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.1
Built => Mar 13 2019 08:47:53
coroutine => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.1e-fips 11 Feb 2013
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

Amazon Linux, php 7.2.16

**Comment by twose** [comment]
can you provide a script?

**Comment by ozgurhangisi** [comment]
Actually it's thousands lines of code. Basically it uses memcached, php, mysql and swoole. Everything  are same on the servers (except php and swoole versions). I think I should dig in details to understand what causes more cpu usage. I'm gonna edit this ticket later.
