### ISSUE TITLE
Feature request: dispatch_func fallback to dispatch_mode

### ISSUE THREAD

**Issue by sshymko** [swoole/swoole-src#2451]
Custom dispatch function specified via `dispatch_func` supersedes the built-in dispatch modes configured as `dispatch_mode`. These features are mutually exclusive. That makes sense at the first glance, however, there're use cases when a custom dispatch function would want to delegate the dispatching to the dispatch mode.

Dispatching based on the _optional_ request data is the generalized use case. For example, the sticky session aka session affinity dispatch according to the session cookie, see [upscale/swoole-dispatch](https://github.com/upscalesoftware/swoole-dispatch). When the cookie is present, the dispatch function does the routing, otherwise, it would delegate the routing to a dispatch mode.

Inability to reuse the dispatch modes in combination with dispatch functions requires to re-implement the built-in dispatch modes as custom functions. The easiest way to implement them would be in PHP, but that comes with a performance hit compared to the C++ version. Moreover, certain dispatch modes cannot be replicated as not enough information is available in dispatch functions. For instance, the [preemptive mode](https://www.swoole.co.uk/docs/modules/swoole-server/configuration#dispatch_mode) cannot be imitated as the dispatch function does not have information on the workers availability.

**Proposed solutions:**
1. Fallback to the configured `dispatch_mode` when `dispatch_func` returns negative value:
    ```php
    function ($server, $fd, $type, $data) {
        if (strpos($data, session_name()) !== false) {
            // Dispatch according to the session ID cookie
            // ...
            return $workerId;
        }
        // Fallback to the configured dispatch_mode
        return -1;
    }
    ```
2. Fallback to the configured `dispatch_mode` when `dispatch_func` throws an exception:
    ```php
    function ($server, $fd, $type, $data) {
        if (strpos($data, session_name()) !== false) {
            // Dispatch according to the session ID cookie
            // ...
            return $workerId;
        }
        // Fallback to the configured dispatch_mode
        throw new \UnexpectedValueException('Missing session context.');
    }
    ```

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/pull/2467/files

**Comment by sshymko** [comment]
@matyhtf 
Thanks for implementing this!
A custom dispatch function needs to return `-3` to indicate the fallback, right?

**Comment by twose** [comment]
now we have `SWOOLE_DISPATCH_RESULT_DISCARD_PACKET`, `SWOOLE_DISPATCH_RESULT_USERFUNC_FALLBACK`.

https://github.com/swoole/swoole-src/releases/tag/v4.3.2
