### ISSUE TITLE
Incompatible with php7.3.3

### ISSUE THREAD

**Issue by to2false** [swoole/swoole-src#2452]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

https://doc.swoft.org/master/zh-CN/quickstart/install.html
就controller, 接收上传一个csv文件，然后直接return

或

直接返回一个值

2. What did you expect to see?

正常有返回值

3. What did you see instead?

卡住没有，然后cpu飙升，swoole.log里
```
[2019-03-24 20:39:21 $13728.0]	WARNING	swManager_check_exit_status: worker#5[pid=21222] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.3.1, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

```

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.1
Built => Mar 24 2019 20:36:36
coroutine => enabled
debug => enabled
trace_log => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2r  26 Feb 2019
http2 => enabled
pcre => enabled
zlib => enabled
brotli => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144
```
5. What is your machine environment used (including version of kernel & php & gcc) ?

MacOS, version 10.14.3

Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

```
PHP 7.3.3 (cli) (built: Mar  8 2019 16:40:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.3, Copyright (c) 1999-2018, by Zend Technologies

```

**Comment by twose** [comment]
能否提供可直接运行的代码压缩包

**Comment by matyhtf** [comment]
换成 Linux 系统测试一下有问题吗？

**Comment by to2false** [comment]
最近有点忙，我先暂时关闭下，大概几天后提供下反馈

**Comment by ofttryaj** [comment]
@to2false 我的系统：MacOS, version 10.14. make失败：
![image](https://user-images.githubusercontent.com/15887451/56025460-c1144080-5d44-11e9-955f-b75ac754d972.png)
求解决方法
