### ISSUE TITLE
$task->workerId   Undefined property: Swoole\Server\Task::$workerId ,

### ISSUE THREAD

**Issue by hooklife** [swoole/swoole-src#2453]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```
list($taskId, $workerId, $data) = [$task->id, $task->worker_id, $task->data];
```

2. What did you expect to see?

3. What did you see instead?

```
 Uncaught ErrorException: Undefined property: Swoole\Server\Task::$workerId 
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.1
Built => Mar 20 2019 19:06:29
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
http2 => enabled
pcre => enabled
zlib => enabled
brotli => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

```

5. What is your machine environment used (including version of kernel & php & gcc) ?

PHP 7.2.15 

Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix

Darwin hooklifedeMBP.lan 18.2.0 Darwin Kernel Version 18.2.0

---
i try doc example :https://wiki.swoole.com/wiki/page/54.html
``` $task->workerId ```
 Undefined property: Swoole\Server\Task::$workerId ,

but ``` $task->work_id ``` work fine

doc is wrong?

**Comment by twose** [comment]
感谢反馈, PHP属性按规则来说都是驼峰式的, 但由于向下兼容问题, 仅对文档进行了修正
