### ISSUE TITLE
swoole talbe 问题

### ISSUE THREAD

**Issue by kokofirst** [swoole/swoole-src#2454]
您好：
swoole table  sting 类型的长度 是 动长 还是 定长啊， 比如说 我申请一个字段 长度 为1000 但是我只存里1个字符， 实际占用 是 1 还是 1000啊

**Comment by twose** [comment]
共享内存是提前分配的, 申请地越大占用越大, 但实际占用的物理内存是按需的, 你可以写个脚本自己观察
