### ISSUE TITLE
swManager_check_exit_status

### ISSUE THREAD

**Issue by manyin** [swoole/swoole-src#2455]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Game server use 4.3 logs reports that A bug occurred in Swoole-v4.3.0.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.3.0

5. What is your machine environment used (including version of kernel & php & gcc) ?

centeos7     php7.3      gcc 4.8.5

**Comment by manyin** [comment]
[2019-03-25 17:02:29 $25310.0]	WARNING	swManager_check_exit_status: worker#0[pid=25578] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.3.0, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

**Comment by twose** [comment]
Can you update to v4.3.1 and try again?

**Comment by twose** [comment]
Can you update to v4.3.1 and try again?
