### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by jason-gao** [swoole/swoole-src#2456]
error:
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: src/core/.libs/error.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

system:
CentOS release 6.8 (Final) x86_64
PHP 7.2.1-dev
swoole 4.3.1

**Comment by jason-gao** [comment]
has resolved:
./configure --with-php-config=/usr/local/php7.2.1/bin/php-config CFLAGS=-fPIC

**Comment by dixyes** [comment]
I can't reproduce this with php7.2.1 built from source + swoole 4.3.1 on CentOS 6.8 x86-64,
Could you please describe which php you used for building swoole?(from source or remi repo or other method)
Sometimes, use --with(enable)-shared and --with(enable)-static at same time will cause this, but it may also a bug of swoole build scripts.
