### ISSUE TITLE
swoole运行一段时间后（1个月不到），出现大量报错内容

### ISSUE THREAD

**Issue by se7en6in** [swoole/swoole-src#2457]
![image](https://user-images.githubusercontent.com/8906471/54911744-17eadf00-4f2a-11e9-91f1-a48d1f284730.png)

![image](https://user-images.githubusercontent.com/8906471/54912113-e1619400-4f2a-11e9-97a1-986ce3283c0e.png)

运行一段时间后，就突然报错，必须终止程序，不然报错内容写爆磁盘

swoole版本：2.0.10 ;php5.6;centos

**Comment by twose** [comment]
这个只能升级版本了, 2.x不维护了, 同样的, PHP官方也不维护5版本了

**Comment by matyhtf** [comment]
请使用 4.3.1 版本和 PHP7，5 下面一直存在一些问题。这个情况应该是 PHP代码中跑出了一些异常未捕获。

**Comment by se7en6in** [comment]
好的，我用新版本试一下
