### ISSUE TITLE
有办法在每次请求后清理内存空间么?

### ISSUE THREAD

**Issue by diyism** [swoole/swoole-src#2459]
据我所知php-fpm的worker进程碰到exit()时实际是执行RSHUTDOWN来free所有跟请求相关的内存和资源而不是真正退出进程

我swoole4.3写了一段世界上最简单的php webserver: https://gist.github.com/diyism/319fbcc2352328f2357cc14bd0e6c859

但是在请求 http://127.0.0.1/index.php    的时候 会一次请求正常, 一次请求抛出异常, 又一次请求正常, 又一次异常 .....  异常是这样:
 WARNING	swManager_check_exit_status: worker#0[pid=1026] abnormal exit, status=255, signal=0

其中index.php的代码 很简单:
```
<?php
exit('jack');
function fun() {}
?>
```

根本原因就是因为php里的function都是global的, 而在swoole http server里没法在一次请求完成后像php-fpm那样refresh这个worker, 导致重复定义冲突, 而如果在web_server.php改成include_once也会导致第二次请求返回空白页面(虽然没有报错了), 问问看在swoole里有没有解决方法

**Comment by twose** [comment]
在onWorkerStart的时候require定义的源文件

你这样还不如用fpm, 这不是swoole的应用场景

**Comment by diyism** [comment]
有个php扩展 https://github.com/krakjoe/uopz/   可以用 uopz_del_function()函数 清理掉function定义, 如果集成到swoole里, 每个请求跑完之后 来一次delete all functions 岂不是搞定这个问题了, php里所有的东西都是局部的, 不像golang和nodejs那样变量空间都是瀑布式污染的, 这是我喜欢php的最大的原因, 只有这个function会 污染到 外部, 如果能把这个解决, 我这30行代码就真的是世界上最简单的web server了 @twose

**Comment by matyhtf** [comment]
可以使用 swoole + php-fpm 的模式实现。短生命周期的代码放到 fpm 里去执行。swoole 基本模式是长生命周期，这个不会改变的。

**Comment by diyism** [comment]
https://gist.github.com/diyism/319fbcc2352328f2357cc14bd0e6c859

找到一个扩展runkit可以清理functions,  可惜不能清理classes, 
只适合在手机上玩php+swoole, 不适合大量并发请求的情况, 否则functions的清理会互相干扰
