### ISSUE TITLE
swoole热更新太麻烦了 折腾了2天还是不会 建议直接默认热更新啊

### ISSUE THREAD

**Issue by a6965921** [swoole/swoole-src#246]
swoole热更新太麻烦了 折腾了2天还是不会 建议直接默认热更新啊 workerman就是直接热更新的 根本不需要设置什么  还有那个压测工具也有问题 报错的

unavailable [11] in /alidata/www/swooleceshi/swoole-src-swoole-1.7.15-stable/examples/bench/run.php on line 120
30173#8@ is lost

希望官方能尽快改善 swoole越来越强大

**Comment by sanpianye** [comment]
强烈要求默认热更新。
