### ISSUE TITLE
Proposal: non-standard PURGE method support

### ISSUE THREAD

**Issue by sshymko** [swoole/swoole-src#2462]
Currently, Swoole does not support non-standard HTTP methods, such as PURGE used by Varnish.
Once supported, applications that already support Varnish cache invalidation could be configured to also send PURGE requests to a stateful Swoole web-server.

**Steps to reproduce:**
1. Implement an HTTP server:
    ```php
    $server = new \Swoole\Http\Server('127.0.0.1', 8080);
    $server->on('request', function ($request, $response) use ($server) {
        $response->header('Content-Type', 'text/plain');
        $response->end("Served by worker $server->worker_id\n");
    });
    $server->start();
    ```
2. Send HTTP request with a non-standard method:
    ```bash
    curl -X PURGE http://127.0.0.1:8080/
    ```

**Actual result:**
- PURGE request never reaches the request handling middleware:
    ```bash
    <h1>400 Bad Request</h1>
    ```

**Expected result:**
- PURGE request is served by the request handling middleware:
    ```bash
    Served by worker 0
    ```

**Comment by twose** [comment]
it is not defined in the HTTP RFCs
