### ISSUE TITLE
Coroutines loosing parent's coroutine context

### ISSUE THREAD

**Issue by pervozdanniy** [swoole/swoole-src#2463]
Please answer these questions before submitting your issue. Thanks!

```
\Swoole\Runtime::enableCoroutine();
go(function() {
   $uid = \Co::getuid();
   go(function () use ($uid) {
      sleep(2);
      var_dump(\Co::getContext($uid));   //NULL
   });
});
```

I expected that child coroutine can access parent's context, but it returns `NULL`

I'm using Swoole 4.3.1 on ubuntu 16.04 (docker image php:7.2-fpm)

**Comment by twose** [comment]
after you call `sleep` with `enableCoroutine`, coroutine#2 would yield to coroutine#1, and coroutine#1 closed, so it returns `NULL` (not exist).
