### ISSUE TITLE
Swoole\Coroutine\Client 传入第二个参数SWOOLE_SOCK_ASYNC core dump

### ISSUE THREAD

**Issue by lackoxygen** [swoole/swoole-src#2466]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

new Swoole\Coroutine\Client(SWOOLE_SOCK_TCP, SWOOLE_SOCK_ASYNC);

2. What did you expect to see?

The system should throw an exception

3. What did you see instead?
coredumped

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole-4.3.0

5. What is your machine environment used (including version of kernel & php & gcc) ?
centos 7.6 php7.1  gcc4.8.36

**Comment by twose** [comment]
没有复现, 提示参数错误
