### ISSUE TITLE
Server and Client on the same eventloop

### ISSUE THREAD

**Issue by sauriio** [swoole/swoole-src#2483]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
i've tried to create a TCP server and a TCP client (both async) but i have no way to add the client to the eventloop and set the event handlers

2. What did you expect to see?
event handlers for TCP client running.

3. What did you see instead?
no entry point to the TCP client events.

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.1
Built => Mar 29 2019 16:30:09
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.0h  27 Mar 2018
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
Linux hitss-PC 4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018 x86_64 GNU/Linux 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 7.3.0-19' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Debian 7.3.0-19)

**Comment by windrunner414** [comment]
why not use coroutine client?
if u use php stream function, u can open coroutine hook or Swoole\Event
see: [https://wiki.swoole.com/wiki/page/119.html](https://wiki.swoole.com/wiki/page/119.html)

**Comment by windrunner414** [comment]
`bool swoole_event_add(mixed $sock, mixed $read_callback, mixed $write_callback = null, 
        int $flags = null);`

```
$fp = stream_socket_client("tcp://www.qq.com:80", $errno, $errstr, 30);
fwrite($fp,"GET / HTTP/1.1\r\nHost: www.qq.com\r\n\r\n");

swoole_event_add($fp, function($fp) {
    $resp = fread($fp, 8192);
    //socket处理完成后，从epoll事件中移除socket
    swoole_event_del($fp);
    fclose($fp);
});
echo "Finish\n"; 
```

**Comment by sauriio** [comment]
the problem with coroutines is that i need a persistent connection for the client, so i cannot open/close it as i need it, in addition with coroutines i don't have the event based async methods for this client and we need some of those for concurrence, i've added the client as a new process but now, the Wrapper obj that holds the client connection is not shared between them, any advices?

**Comment by sauriio** [comment]
btw, i'm using a TCP server and a TCP client (both async).

**Comment by ClosetMonkey** [comment]
I'm confused to why you think this can't be done using coroutines. Client will be in one coroutine and server will be in another. Once the server calls accept() it will block, yielding to the client coro which can then connect to remote end point. Not sure what your service will require at this point, but assuming client connects successfully you can call read() for example which will also put the client into a yielding state. At this point the server coro will be waiting for accept() and the client coro for read(), and the reactor will resume both coros as needed when accept()/read() can return.

**Comment by sauriio** [comment]
the client need to have a persistent connection, I've successfully made this service with the tcp server opening another process for the client connection and just sending the data to the process queue, thanks for the reply!
