### ISSUE TITLE
协程客户端post数据问题

### ISSUE THREAD

**Issue by Dean0820** [swoole/swoole-src#2489]
环境信息：
CentOS 6.5 (Final)
PHP Version => 7.1.1
Swoole Version => 4.2.4
gcc version 4.8.5 (GCC)

问题描述：
使用协程客户端发送post请求数据超过20多KB就一直没有响应了
Swoole\Coroutine\Http\Client->post
我想问一下协程客户端发送post请求对数据大小有限制吗

**Comment by twose** [comment]
升级一下swoole版本 已解决问题

**Comment by Dean0820** [comment]
> 升级一下swoole版本到最新 旧版本下的已解决问题

好的，谢谢
