### ISSUE TITLE
CentOS下编译报错You are running the test-suite with "safe_mode" ENABLED

### ISSUE THREAD

**Issue by stolendust** [swoole/swoole-src#249]
尽管php.ini 中safe_mode 设置为 Off, 依然报这个错，解决方法：
在Makefile中查找safe_mode， 删掉 即可

**Comment by betashepherd** [comment]
贴一下 ./php -i|grep configure

**Comment by stolendust** [comment]
Configure Command =>  './configure'  '--prefix=/usr/local/php' '--with-config-file-path=/usr/local/php/etc' '--enable-fpm' '--with-fpm-user=www' '--with-fpm-group=www' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-iconv-dir' '--with-freetype-dir' '--with-jpeg-dir' '--with-png-dir' '--with-zlib' '--with-libxml-dir=/usr' '--enable-xml' '--disable-rpath' '--enable-magic-quotes' '--enable-safe-mode' '--enable-bcmath' '--enable-shmop' '--enable-sysvsem' '--enable-inline-optimization' '--with-curl' '--enable-mbregex' '--enable-mbstring' '--with-mcrypt' '--enable-ftp' '--with-gd' '--enable-gd-native-ttf' '--with-openssl' '--with-mhash' '--enable-pcntl' '--enable-sockets' '--with-xmlrpc' '--enable-zip' '--enable-soap' '--without-pear' '--with-gettext' '--disable-fileinfo'

**Comment by matyhtf** [comment]
与swoole无关
