### ISSUE TITLE
swoole升级到最新版本加载出错

### ISSUE THREAD

**Issue by Dean0820** [swoole/swoole-src#2490]
环境信息：
CentOS 6.5 (Final)
PHP Version => 7.1.1
Swoole Version => github最新
gcc version 4.8.5 (GCC)

问题描述：
扩展文件夹swoole.so文件已经生成，加载的时候出现下面的错误。安装4.2.4版本一切正常
php --ri swoole

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php/lib/php/extensions/no-debug-zts-20160303/swoole.so' - /usr/local/php/lib/php/extensions/no-debug-zts-20160303/swoole.so: undefined symbol: _Z24to_zval_read_in6_pktinfoPKcP12_zval_structP12_res_context in Unknown on line 0
Extension 'swoole' not present.

**Comment by yunnian** [comment]
看下编译的时候是不是用了其他版本，比如phpize

**Comment by matyhtf** [comment]
重新执行 phpize ，make clean
