### ISSUE TITLE
swoole timer doesn't work

### ISSUE THREAD

**Issue by morozovsk** [swoole/swoole-src#2493]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```php
use Swoole\Server;
use Swoole\Timer;

$server = new Server('0.0.0.0', 30002, SWOOLE_BASE, SWOOLE_SOCK_UDP);

$server->on('Packet', function (Server $server, $data, $addr)
{
    var_export($data);
});

$server->tick(1000, function () {
    echo 1;
});

$id = Timer::tick(1000, function () {
    echo 2;
});

/*$server->on('Timer', function (Server $server, $data, $addr)
{
    echo 3;
});*/

swoole_timer_tick(1000, function() {
    echo 4;
});

$server->on('Start', function (Server $server)
{
    $server->tick(1000, function() {
        echo 5;
    });
});

$server->on('start', function (Server $server)
{
    $server->tick(1000, function() {
        echo 6;
    });
});
```

2. What did you expect to see?

1,2,3,4,5 or 6 in console

3. What did you see instead?

Only data from udp socket.

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.3.1

5. What is your machine environment used (including version of kernel & php & gcc) ?

centos7, php 7.2

**Comment by twose** [comment]
This is as expected, and you need to put it in the WorkerStart callback because the server will reopen a new event loop.
