### ISSUE TITLE
利用swoole完成和couchbase交互

### ISSUE THREAD

**Issue by leehomewl** [swoole/swoole-src#2496]
Hi：
    我希望可以使用 swoole来使用读取 couchbase的作用，请问可以直接使用 TCP Client来完成操作吗。 
   另外这种性能上是否有使用过测试呢。

**Comment by matyhtf** [comment]
可以使用 tcp client 实现 couchbase 协议的客户端

**Comment by leehomewl** [comment]
好的，谢谢
