### ISSUE TITLE
Is `set_error_handler` `restore_error_handler` Coroutine Safe?

### ISSUE THREAD

**Issue by ihipop** [swoole/swoole-src#2499]
When  some php function doesn't have exception to throw, Some Composer extension have the logic below to catch the error

![image](https://user-images.githubusercontent.com/423077/55952258-b649a500-5c8b-11e9-8434-7b31f67c5c87.png)

Is `set_error_handler` `restore_error_handler` Coroutine Safe?

Will this happen?

Coroutine B: `set_error_handler`

Coroutine A: `restore_error_handler`

Coroutine B:  execute the function that is  doesn't have exception to throw

![image](https://user-images.githubusercontent.com/423077/55952461-42f46300-5c8c-11e9-93f7-8e82830a9140.png)

If `set_error_handler` `restore_error_handler` is not Coroutine  Safe,Any way to make it Coroutine  isolated in Swoole?

**Comment by twose** [comment]
Obviously, this is a global configuration, and its switching cost is high, so it would not be scheduled.

**Comment by ihipop** [comment]
![image](https://user-images.githubusercontent.com/423077/55954411-38889800-5c91-11e9-88b4-a55c9cb977a1.png)

this `callback()` maybe a IO related event,So it will happen and not works well.

**Comment by ihipop** [comment]
I want to convert some php functions that have no exception  throw  (only have error returned when error)  
to my self defined exceptions,is there any Coroutine  safe way?

**Comment by twose** [comment]
no way...
I think this is not a good practice

**Comment by ihipop** [comment]
I know， but there is no way to catch these ‘exception mute’ function’s errors

**Comment by ihipop** [comment]
This is a historical  problem of php to have this native grandpa function that trigger error instead of throw exception born in previous century。
so many composer component have to use `set_error_handler` `restore_error_handler` trick to deal with them。 ；（

**Comment by ihipop** [comment]
add some test to prove this problem

```php
$errorCount = [
    'fail'   => 0,
    'errors' => 0,
];

$quit = false;

go(function () use (&$errorCount, &$quit) {
    $context = stream_context_create([
        'http' => [
            'timeout' => 0.1,
        ],
    ]);
    while (true) {
        set_error_handler(
            function ($a,$b) {
                throw new \RuntimeException('balabala');
            }
        );
        try {
            $resource = @fopen('http://4.4.4.4/', 'r', false, $context);
            if (!$resource) {
                $errorCount['fail']++;//normally is should not happen
            }
        } catch (\Throwable $e) {
            $errorCount['errors']++;
        } finally {
            set_error_handler(function ($a,$b){});
        }

        if ($quit || ($errorCount['fail'] > 0)) {
            $quit = true;
            break;
        }
    }
});

go(function () use (&$quit) {
    while (true) {
        set_error_handler(function ($a,$b){});
        \Co::sleep(0.001);
        if ($quit) {
            break;
        }
    }
});

foreach ([SIGHUP, SIGINT, SIGTERM, SIGQUIT] as $signal) {
    \Swoole\Process::signal($signal, function () use (&$quit, $signal) {
        $quit = true;
        \Swoole\Process::signal($signal, null);
    });
    swoole_timer_tick(1, function ($timeId) use (&$quit, $signal) {
        if ($quit) {
            swoole_timer_clear($timeId);
            \Swoole\Process::signal($signal, function () {
            });
            \Swoole\Process::signal($signal, null);
        }
    });
}

\Swoole\Event::wait();

var_export($errorCount);
```
