### ISSUE TITLE
Http2 Client Ping method to check connection

### ISSUE THREAD

**Issue by ozgurhangisi** [swoole/swoole-src#2504]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

We use co\Http2\Client to send push notification to apple devices. In Apple documentation 
 ( https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW17 ) 

Best Practices for Managing Connections section says that You can check the health of your connection using an HTTP/2 PING frame.

I couldn't see any Ping method on http2 client.

2. What did you expect to see?

Apple can blocks our servers if we open and close too many connections. Apple says that create one connection and keep it open as long as possible. But we should be sure that connection is still alive when we send push notification to apple servers on different times (Lets say I send push notification at 09:00 PM I kept connection open and when I try to send push notification again at 11:00 PM I should be sure that connection that I created at 09:00 PM is still alive). We can use Ping method on this case.

3. What did you see instead?

I couldn't see $res = $cli->ping(); (or similiar) method on http2 client

4. What version of Swoole are you using (show your `php --ri swoole`)?

v 4.2.13

5. What is your machine environment used (including version of kernel & php & gcc) ?

php 7.2.14 aws t2.micro 1GB RAM

**Comment by twose** [comment]
maybe you can try  v4.3.2-rc1

**Comment by ozgurhangisi** [comment]
Awsome :))) I'm gonna try it. Thank you so much.
