### ISSUE TITLE
编译成功 但是加载 swoole 模块出错

### ISSUE THREAD

**Issue by TestAdmin007** [swoole/swoole-src#2505]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
# /usr/local/php/bin/phpize  
# ./configure --with-php-config=/usr/local/php/bin/php-config
# make
# make test
# make install
# 在 php.ini 文件中引入 swoole.so
# /usr/local/php/bin/php -m |grep swoole

2. What did you expect to see?
swoole

3. What did you see instead?
swoole.so: undefined symbol: _Z24to_zval_read_in6_pktinfoPKcP12_zval_structP12_res_context in Unknown on line 0 Extension 'swoole' not present.

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.3.1

5. What is your machine environment used (including version of kernel & php & gcc) ?
Centos 7.3
php7.1

**Comment by twose** [comment]
run `php-config -v`

**Comment by twose** [comment]
可以尝试编译刚刚发布的v4.3.2, 是否有这个问题

**Comment by mabu233** [comment]
之前也有人遇过 [2490](https://github.com/swoole/swoole-src/issues/2490)

**Comment by twose** [comment]
我们现在有大多数系统环境下的编译测试, 不应该会出现这个问题

**Comment by dixyes** [comment]
请提供详细构建姿势 例如 发行版和版本 所用构建环境（cc c++类型，版本） 我看看能不能复现

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/22199332edacb4247529b83bec0fe24fbb0c59d2

已移除 IPv6相关宏，请使用 master 代码测试一下
