### ISSUE TITLE
Swoole can't be compiled on PHP 7.4

### ISSUE THREAD

**Issue by petk** [swoole/swoole-src#2506]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```
git clone git://github.com/php/php-src
cd php-src
git checkout PHP-7.4
./buildconf
./configure --disable-all
make
make install
cd ext
git clone git://github.com/swoole/swoole-src
cd swoole-src
phpize
./configure
make
```
2. What did you expect to see?

successfull compilation

3. What did you see instead?

```
/opt/php-src/ext/swoole-src/swoole_coroutine.cc: In static member function 'static void swoole::PHPCoroutine::create_func(void*)':
/opt/php-src/ext/swoole-src/swoole_coroutine.cc:290:5: error: too many arguments to function 'zend_execute_data* zend_vm_stack_push_call_frame(uint32_t, zend_function*, uint32_t, void*)'
     );
     ^
In file included from /usr/local/include/php/Zend/zend_API.h:29,
                 from /usr/local/include/php/main/php.h:37,
                 from /opt/php-src/ext/swoole-src/php_swoole.h:25,
                 from /opt/php-src/ext/swoole-src/php_swoole_cxx.h:3,
                 from /opt/php-src/ext/swoole-src/swoole_coroutine.cc:18:
/usr/local/include/php/Zend/zend_execute.h:245:46: note: declared here
 static zend_always_inline zend_execute_data *zend_vm_stack_push_call_frame(uint32_t call_info, zend_function *func, uint32_t num_args, void *object_or_called_scope)
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:369: swoole_coroutine.lo] Error 1
make: *** Waiting for unfinished jobs....
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

master branch 

5. What is your machine environment used (including version of kernel & php & gcc) ?

php 7.4.0-dev
Alpine Linux 3.9

**Comment by twose** [comment]
it was merged to branch 7.4 four days ago: https://github.com/php/php-src/commit/55cc280429c453a89e33de7357fa80589470dfc3

I fixed it a day ago (https://github.com/swoole/swoole-src/commit/2634da411a9b80cdfc00399eafcd69b0db30c775) but I did not expect it to be merged into 7.4...

**Comment by twose** [comment]
everything is ok now.

**Comment by petk** [comment]
It works. Thank you so much for the fix @twose I appreciate it.

**Comment by twose** [comment]
@petk https://travis-ci.org/swoole/swoole-src/jobs/520658644
the php-nightly test has been failed for a while, do you know why?

**Comment by petk** [comment]
@twose fix for nightly fails is sent to Travis CI here:
https://github.com/travis-ci/php-src-builder/pull/36

The oniguruma library is causing some issue I think...

**Comment by twose** [comment]
@petk I see. Thank you very much.
