### ISSUE TITLE
worker进程投递任务给task，一定时间后task不再工作

### ISSUE THREAD

**Issue by sayid** [swoole/swoole-src#2507]
worker进程投递任务给task，一定时间后task不在工作

![image](https://user-images.githubusercontent.com/362920/56198514-a9eb9080-606d-11e9-8a2f-fd757c33ac1d.png)

strace结果如下

```
root@email-service-cron-586c9d94c-9mh5l:/opt# strace -p 1442
Process 1442 attached
wait4(-1, 0x7ffe614d958c, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGUSR2 {si_signo=SIGUSR2, si_code=SI_USER, si_pid=1454, si_uid=0} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
wait4(-1, 0x7ffe614d958c, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGUSR2 {si_signo=SIGUSR2, si_code=SI_USER, si_pid=1454, si_uid=0} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
wait4(-1, 0x7ffe614d958c, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGUSR2 {si_signo=SIGUSR2, si_code=SI_USER, si_pid=1454, si_uid=0} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
```

Swoole版本:4.2.7
php:7.1

**Comment by matyhtf** [comment]
strace 跟踪不工作的 task 进程，你这里跟踪了 manager 进程，信息无效。

**Comment by sayid** [comment]
> strace 跟踪不工作的 task 进程，你这里跟踪了 manager 进程，信息无效。

![image](https://user-images.githubusercontent.com/362920/56253807-933a4d80-60f0-11e9-8583-b00f32188739.png)

**Comment by matyhtf** [comment]
gdb -p 跟踪，输入 bt 打印调用栈

**Comment by sayid** [comment]
> gdb -p 跟踪，输入 bt 打印调用栈

![image](https://user-images.githubusercontent.com/362920/56282620-2780d080-6142-11e9-94dc-4e2d180e8fe6.png)

另外manager进程不停的报-1 EINTR (Interrupted system call) 是什么问题呢

**Comment by sayid** [comment]
> gdb -p 跟踪，输入 bt 打印调用栈

![image](https://user-images.githubusercontent.com/362920/56282680-5139f780-6142-11e9-90b6-6f03afd0aedb.png)

我们是在容器中运行的

**Comment by keefe-wu** [comment]
我也是类似情况，兄弟你解决了吗？

**Comment by matyhtf** [comment]
你的 task 进程死循环或者阻塞了。
