### ISSUE TITLE
package_length_func为何不能返回包的部分内容

### ISSUE THREAD

**Issue by HBSpy** [swoole/swoole-src#2509]
https://github.com/swoole/swoole-src/blob/0c2f6f53511af75a9f27dd634b399070c7683ddb/swoole_client.cc#L1469

这里没有buf_len小于实际收到包长度的case，导致不能通过package_length_func实现拆分多个包的功能，这是个feature还是BUG

**Comment by matyhtf** [comment]
不要管这里的内容，你只需要返回 包长度就可以，拆分包的工作是由底层完成。
