### ISSUE TITLE
在一次请求中进行多次redis操作的最佳实践是什么？

### ISSUE THREAD

**Issue by kant712** [swoole/swoole-src#2514]
推荐的做法是不是起一个Swoole\Coroutine\Redis的连接池，好比我现在要进行5次redis操作，我就起5个协程，在每个协程中都从连接池中拿一个实例出来执行redis操作。
是这样吗？

**Comment by windrunner414** [comment]
并发操作才需要5个协程，如果不需要并发操作一个协程就好了
```
$redis = $pool->get();
$redis->set();
$redis->set();
$pool->put($redis);
```

**Comment by kant712** [comment]
> 并发操作才需要5个协程，如果不需要并发操作一个协程就好了
> 
> ```
> $redis = $pool->get();
> $redis->set();
> $redis->set();
> $pool->put($redis);
> ```

写法1：
```
$count = 5;
$value = '';
for ( $i = 1; $i <= $count; $i++ )
{
    $redis = RedisPool::get();
    $value .= $redis->get( 'xxx' );
    RedisPool::put( $redis );
}
```

写法2：
```
$count = 5;
$value = '';
$chan = new \Co\Channel( $count );
for ( $i = 1; $i <= $count; $i++ )
{
    go( function() use ( $chan )
    {
        $redis = RedisPool::get();
        $res = $redis->get( 'xxx' );
        RedisPool::put( $redis );
        $chan->push( $res );
    } );
}
for ( $i = 1; $i <= $count; $i++ )
{
    $value .= $chan->pop();
}
```

压测发现2性能更好一点，只是不知道会不会有什么坑，所以来请教一下推荐的做法是什么，

**Comment by windrunner414** [comment]
这里要看你是否需要/可以并发操作。第二种是并发get，第一种要等到上一次get完了，才会进行下一次。
事实上redis是单线程的，这里并发的效果应该不是很明显？如果用mysql就会更明显了。（或者多个redis实例）
两种都是可以的，看实际情况。

**Comment by twose** [comment]
1是串行, 2是并行
1的缺点是每个请求响应时间会变长
2的缺点是需要建立五个连接(但有连接池的话会好一些, 就不算缺点)

需要结合实际情况, 请求量不大的时候接口速度先行(连接池+2方案), 请求量大的时候需均衡负载(连接池调度+1方案)

**Comment by kant712** [comment]
谢谢楼上二位解惑！我的应用场景是需要进行多次get操作，且之间没有依赖关系。并且接口请求量还是很大的。
所以我还是使用 连接池+为每个操作都创建一个协程+每个协程内从连接池中拿一个实例 的做法。
