### ISSUE TITLE
获取 http client 请求的 sock

### ISSUE THREAD

**Issue by hooklife** [swoole/swoole-src#2516]
使用 swoole 操控docker
https://docs.docker.com/engine/api/v1.39/#operation/ContainerAttach
需要把 http 升级成 tcp，所以需要 http 请求的 sock。
upgrade 只能升级成  websocket，我想升级成 tcp

**Comment by twose** [comment]
不存在HTTP升级到TCP这种神奇的说法
用`Co\Socket`或`Co\Client`模块, 自己写

**Comment by hooklife** [comment]
@twose 
golang 的 http client 实现了这个功能，叫 hijack，有很多文章介绍了其中的用途
https://liqiang.io/post/hijack-in-go
我觉得这个也是有点用的，希望官方可以考虑一下。

**Comment by twose** [comment]
@matyhtf exportSocket, 并且此时socket应该和http客户端解除关系

**Comment by matyhtf** [comment]
@hooklife 建议直接使用 Swoole\Coroutine\Client 和 Swoole\Coroutine\Socket 去实现。这个功能不会添加到 Http\Client 中。
