### ISSUE TITLE
Class swoole_redis not found 

### ISSUE THREAD

**Issue by makbeth** [swoole/swoole-src#2517]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
I install swoole like pecl install swoole and try to use swoole_redis class like `$client = new swoole_redis;
`

2. What did you expect to see?
I want to see that's everything ok with the class

3. What did you see instead?
'Class 'swoole_redis' not found'
When I try to start websocket server with  
`$server = new \swoole_websocket_server("127.0.0.1", 9502);

        $server->on('open', function($server, $req) {
            echo "connection open: {$req->fd}\n";
        });

        $server->on('message', function($server, $frame) {
            echo "received message: {$frame->data}\n";
            $server->push($frame->fd, json_encode(["hello", "world"]));
        });

        $server->on('close', function($server, $fd) {
            echo "connection close: {$fd}\n";
        });

        $server->start();`
Everything is ok, but not ok with swoole_redis.

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.3.2

5. What is your machine environment used (including version of kernel & php & gcc) ?
macOS Mojave, php 7.3

**Comment by windrunner414** [comment]
async client has been moved to [async-ext](https://github.com/swoole/ext-async).

**Comment by makbeth** [comment]
Thank you! It will be nice if developers fix description of install that stuff on their website.

**Comment by matyhtf** [comment]
You should use the `Co\Redis` or `Swoole\Coroutine\Redis`
