### ISSUE TITLE
源码下载地址文件名 与 压缩文件内目录名 不统一

### ISSUE THREAD

**Issue by Alion548** [swoole/swoole-src#2518]
比如：最新版本下载地址：https://github.com/swoole/swoole-src/archive/ **v4.3.3** .tar.gz，解压后源码目录名为：swoole-src- **4.3.3**
建议：统一为“v4.3.3”，或统一为“4.3.3”

**Comment by matyhtf** [comment]
使用 `4.3.3` 会造成 `github` 无法识别。

**Comment by matyhtf** [comment]
<img width="314" alt="001" src="https://user-images.githubusercontent.com/2017766/56464064-f93a1400-6413-11e9-9f50-5cd112e6b5a6.png">

**Comment by twose** [comment]
试了一下 都是不带v的
