### ISSUE TITLE
【求教】如果task投递容量超过处理能力，task会塞满缓存区？能放到队列进行排序？谢谢

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#252]
官方文档上说： task操作的次数必须小于onTask处理速度，如果投递容量超过处理能力，task会塞满缓存区

使用swoole_server_task必须为Server设置onTask和onFinish回调，否则swoole_server->start会失败
task操作的次数必须小于onTask处理速度，如果投递容量超过处理能力，task会塞满缓存区，导致worker进程发生阻塞。worker进程将无法接收新的请求

压测的话容易成为瓶颈，能放到共享内存或队列进行排序么？是否有计划支持？
或者有什么替代方案，避免瓶颈么  谢谢！

谢谢！非常感谢～

**Comment by matyhtf** [comment]
这里的意思是task产生的速度务必要小于处理的速度。
这就是生产者消费者的关系，如果生产比消费更多，这个系统自然要崩溃。
swoole底层本身就是进行排队的。
