### ISSUE TITLE
swoole_mysql removed from main swoole module, but docs still refer to it

### ISSUE THREAD

**Issue by rubensr** [swoole/swoole-src#2520]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I saw the code example in [the documentation](https://www.swoole.co.uk/docs/modules/swoole-async-mysql-client), and tried to run that example.

2. What did you expect to see?

I expected no errors.

3. What did you see instead?

An error saying that "swoole_mysql" does not exist, which forced me to dig through code to figure out where that class is, and found out that it was moved to a separate undocumented module in [another repo](https://github.com/swoole/ext-async).

Either the documentation needs to indicate that this is not part of swoole and the user has to manually build the extension by hand to get it, or that has to be removed so users are not confused.

Nowhere in [here](https://www.swoole.co.uk/docs/module) it is clear that the async modules are not part of the default Swoole code.

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.3

5. What is your machine environment used (including version of kernel & php & gcc) ?

Not applicable.

**Comment by twose** [comment]
that is out of the date, please read readme.md

**Comment by rubensr** [comment]
Your readme.md still points to https://www.swoole.co.uk/docs

**Comment by rubensr** [comment]
In fact, the first thing I see when I go to https://github.com/swoole/swoole-src, is a link to https://www.swoole.com/, which takes me to the out of date documentation.
