### ISSUE TITLE
GitHub project page points to outdated documentation

### ISSUE THREAD

**Issue by rubensr** [swoole/swoole-src#2521]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I am looking for current, in-depth documentation about Swoole. 

2. What did you expect to see?

I am looking for detailed documentation on what (for example) Swoole\Event::wait(); does, since it seems to be pretty central to the examples on the GitHub page.
So as per requested in #2520, I went straight to https://github.com/swoole/swoole-src. 

3. What did you see instead?

The first thing on that page points users to https://www.swoole.com/, and further down the README.md file, points to https://www.swoole.co.uk/docs, both of which are outdated and incorrect (as per #2520).

I also cannot find (for example) complete, correct documentation about the wait() method above.

**Comment by twose** [comment]
if you are using https://github.com/mkoppanen/php-zmq, you can just run:
```php
Swoole\Runtime::enableCoroutine();
```
you can see the document here: https://github.com/swoole/swoole-src#-amazing-runtime-hook

Our English official website is maintained by @doubaokun 
but it has not been updated for a long time...

**Comment by doubaokun** [comment]
@rubensr 

Async clients are moved to separate PHP extension since version 4.3.0: https://github.com/swoole/ext-async

We will add the notice of this major change on website and README.
