### ISSUE TITLE
curl get方式第一参数会带有“?”

### ISSUE THREAD

**Issue by ncwsky** [swoole/swoole-src#2525]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
curl('http://xxx/a/b?id=1')

http://xxx/a/b 这里$_GET 的结果却是这样的 ['?id'=>1]

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.3.2

5. What is your machine environment used (including version of kernel & php & gcc) ?
php7.0 debian9

**Comment by twose** [comment]
swoole里没有`$_GET`

**Comment by ncwsky** [comment]
> swoole里没有`$_GET`

是在swoole使用curl请求外部的接口 我是在外部接口代码里输出得到的结果
现在生产环境是用的4.0.0是正常的
我在本地测试环境安装的是4.3.2就出现这个情况了 get请求方式?后的第一参数在$_GET里得到的就会多一个?在前面 造成这第一个参数的值无法获取

**Comment by ncwsky** [comment]
http://api.xxx.com/default/map?mch_id=1
我要获取mch_id这个的值 正常是$_GET['mch_id']是能获取的
但结果却需要$_GET['?mch_id']这样才能得到值
