### ISSUE TITLE
在swoole里使用curl请求外部接口get方式 第一参数会带有“?”

### ISSUE THREAD

**Issue by ncwsky** [swoole/swoole-src#2526]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

是在swoole使用curl请求外部的接口(如：http://api.xxx.com/default/map?mch_id=1) 

我要获取mch_id这个的值  使用$_GET['mch_id']是不能获取的
但如果使用$_GET['?mch_id']就能得到值

现在生产环境是用的4.0.0是正常的
我在本地测试环境安装的是4.3.2就出现这个情况了 get请求方式?后的第一参数在$_GET里得到的就会多一个?在前面 造成这第一个参数的值无法获取

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.3.2

5. What is your machine environment used (including version of kernel & php & gcc) ?
php7.0 debian9

**Comment by twose** [comment]
贴代码

**Comment by ncwsky** [comment]
这是swoole里的代码
    public function deskSkin(){
        //echo 'do deskSkin' . $this->fd . PHP_EOL;
        //print_r($this->data);
        $data = false;
        $uid = $this->uid ? $this->uid : redis()->hGet("fd_uid", $this->fd);
        //echo GetC('api_url').'/default/desk-skin?mch_id='.$uid.PHP_EOL;
        $res = json_decode(Http::doGet(GetC('api_url').'/default/desk-skin?mch_id='.$uid, 5, 'Accept: */*'),true);
        //var_dump($res);
        if(isset($res['code']) && $res['code']==0){
            $data = $res['data'];
        }else{
            $this->data['data'] = $res;
        }
        $this->data['data'] = $data;
        $this->data['a'] = 'json_down';
        $this->send();
    }


这是接口的代码
public function actionDeskSkin(){
        $mch_id = (int)$this->get('mch_id');
        //无json生成
        $ret = CloudDesktop::find()->where(['mch_id'=>$mch_id,'status'=>1])->orderBy('status asc, id desc')->all();
}

**Comment by ncwsky** [comment]
这是测试出来的结果 
[2019-04-22 15:40:25 $18731.0]	INFO	Server is reloading all workers now
Worker Stop clear
Worker Stop clear
Worker Stop clear
Worker Stop clear
http://192.168.0.219/default/desk-skin?mch_id=1
array(4) {
  ["code"]=>
  int(0)
  ["msg"]=>
  string(2) "ok"
  ["data"]=>
  array(1) {
    ["?mch_id"]=>
    string(1) "1"
  }
  ["ext"]=>
  array(0) {
  }
}

 是直接这样得到的结果
public function actionDeskSkin(){
var_dump($_GET);
}

**Comment by twose** [comment]
再问一次你用了什么框架还是什么? $_GET是哪来的?

**Comment by matyhtf** [comment]
无法重现你的问题。

**Comment by ncwsky** [comment]
就是在swoole 里通过curl 请求 http://192.168.0.219/default/desk-skin?mch_id=1

然后在 http://192.168.0.219/default/desk-skin 这里取这个mch_id的值 是取不到的
通过输出$_GET 得到
array(1) {
["?mch_id"]=>
string(1) "1"
}
所以我才说第一参数会多一个"?"

**Comment by ncwsky** [comment]
不好意思 麻烦你们了 找到原因了 是系统环境问题
