### ISSUE TITLE
Question about websocket server and async Redis

### ISSUE THREAD

**Issue by makbeth** [swoole/swoole-src#2528]
Hello! I've just started using websockets and asynс possibilities provided by Swoole. Can anybody tell me how to implemetn this case:

I start a websocket server and a Redis client
I create a subscription to a channel, e.g. User channel
User connects to the websocket server
On connection event I write some data to Redis (e.g. that this user is online) and call Redis publish method (pubsub) - here is the question:
Will publish method be called automatically or I must call this method manually each time I add data to Redis?
On publish event I send all users connected to the websocket server the data I store in Redis.
I think it will work for realtime notifications of online users on the website.
Can anybody tell me is this approach correct? Can I use it in a case like private chat between two users?
It will be great if anybody can show me an example how I can do my case in Swoole style. Like best practice for this case. Thank you! I really appreciate your help!

**Comment by doubaokun** [comment]
@makbeth 

You can implement a `pubsub` system with Redis and Swoole. You have to call `$redis->publish()` to notify the subscribers.
It is more a Redis question, please check more at: https://redis.io/topics/pubsub
