### ISSUE TITLE
failed. Error: No such process

### ISSUE THREAD

**Issue by scguang301** [swoole/swoole-src#2531]
Please answer these questions before submitting your issue. Thanks!

1.  环境： php7.1.3 + swoole 4.2.8， 也有其他的C++扩展库
2. 未知情况出现：[2019-04-26 18:13:34 $29164.0]	ERROR	swManager_loop(:452): kill(21454, SIGTERM) [29] failed. Error: No such process[3].
3.  什么时候会出现这种错误？目前发现coredump会出现这个问题，设置生成coredump后，有些时候出这个错误，没有生成coredump, 请问还有什么情况出现这种问题，以及怎么调试

**Comment by twose** [comment]
如果有coredump 你应该尝试升级 如果升级后仍有coredump 你应该根据https://github.com/swoole/swoole-src/issues/2000 的指引贴出coredump追踪信息
如果你使用了其它C扩展可能导致coredump的, 请想办法排除干扰

**Comment by matyhtf** [comment]
新版本已经解决了此问题。请使用 4.3.3 进行测试

**Comment by scguang301** [comment]
好的，谢谢

**Comment by scguang301** [comment]
更换swoole 4.3.3后出现问题
1. 环境： gcc:  4.8.5, php 7.1.3,  swoole:4.3.3
2. 某一个work进程出未知问题后，对所有请求报500错误，一直到进程退出
3.  出现概率比较低，无法重现。
