### ISSUE TITLE
Question about saving http2 client to file or redis for reuse

### ISSUE THREAD

**Issue by ozgurhangisi** [swoole/swoole-src#2532]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I have a php-cli code that connects to http2 server and send some information. I run this code with shell_exec("php send_data_to_http2.php") from my cron.php file;

Is it possible to save http2 client for reuse ? Client connection takes a few seconds and I want to save & reuse the connection if it's possible.

This is my current code in send_data_to_http2.php

```
go(function () use ($http2_info) {
    $cli = new co\Http2\Client($http2_info['http2_url'], $http2_info['http2_port'], $http2_info['http2_ssl']);
.....
.....
}
```

I want to do something like this 

```
go(function () use ($http2_info,$saved_connection_path) {
    if (file_exists($saved_connection_path)) {
       $cli = unserialize(file_get_contents($saved_connection_path));
       if (!$cli->ping()) {
          $cli->close();
          $cli = new co\Http2\Client($http2_info['http2_url'], $http2_info['http2_port'], $http2_info['http2_ssl']);           
      }
    } else {
     $cli = new co\Http2\Client($http2_info['http2_url'], $http2_info['http2_port'], $http2_info['http2_ssl']);
     save_to_file($saved_connection_path,serialize($cli));
    }
.....
.....
}
```

2. What did you expect to see?

I want to save my http2 client connection to somewhere and reuse it. It's not a http server it's a php-cli code and I run it with shell_exec.

3. What did you see instead?

---

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole v. 4.3.3

5. What is your machine environment used (including version of kernel & php & gcc) ?

php 7.2.17 swoole 4.3.3

**Comment by twose** [comment]
It's a dream, What you really need is a connection proxy.

**Comment by ozgurhangisi** [comment]
@twose I knew that :) Thanks for your answer.
