### ISSUE TITLE
The worker process of Server opens the bug of the coroutine by default.

### ISSUE THREAD

**Issue by MuBinGIT** [swoole/swoole-src#2533]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
$http = new Swoole\Http\Server("0.0.0.0", 8888);
$http->set([
    'worker_num' => 1,
    'max_request' => 1,
]);
$http->on('start', function(){
    swoole_set_process_name('LOCAL::master');
});
$http->on('managerstart', function(){
    swoole_set_process_name('LOCAL::manager');
});
$http->on('request', function ($request, $response)use($http) {
    printf("REQUEST: pid[%d] cid[%d] cnum[%d] uri[%s]\n", getmypid(), Co::getcid(), sizeof(Co::list()), $request->server['request_uri']);
    
    // Waiting for using a coroutine will be suspended
    Co::sleep(2);

    // In the same situation, the method of connecting data using the coroutine given by the official website will also be suspended.
    // $swoole_mysql = new Swoole\Coroutine\MySQL();
    // $swoole_mysql->connect([
    //     'host' => '127.0.0.1',
    //     'port' => 3306,
    //     'user' => 'user',
    //     'password' => 'pass',
    //     'database' => 'test',
    // ]);
    
    $response->end("<h1>Hello Swoole. #".rand(1000, 9999)."</h1>");
});
$http->on('workerstart', function($serv, $worker_id){
    swoole_set_process_name('LOCAL::worker');
    printf("WORKERSTART: pid[%d] cid[%d] cnum[%d]\n", getmypid(), Co::getcid(), sizeof(Co::list()));
});
$http->on('workerstop', function(swoole_server $server, int $worker_id){
    printf("WORKERSTOP: pid[%d] cid[%d] cnum[%d]\n", getmypid(), Co::getcid(), sizeof(Co::list()));
});
$http->start();
```
2. What did you expect to see?
    Fix this bug

3. What did you see instead?
    At the time the request reached the last time `max_request`, the request would be stuck because the `coroutine` might have been `destroyed`.
    When I test it, not only `Co::sleep` will get stuck, but the `connection database` will also get stuck.

4. What version of Swoole are you using (show your `php --ri swoole`)?
#### swoole

    Swoole => enabled
    Author => Swoole Team <team@swoole.com>
    Version => 4.3.1
    Built => Mar 13 2019 09:23:05
    coroutine => enabled
    trace_log => enabled
    epoll => enabled
    eventfd => enabled
    signalfd => enabled
    cpu_affinity => enabled
    spinlock => enabled
    rwlock => enabled
    sockets => enabled
    openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
    http2 => enabled
    pcre => enabled
    zlib => enabled
    mutex_timedlock => enabled
    pthread_barrier => enabled
    futex => enabled
    mysqlnd => enabled
    async_redis => enabled

    Directive => Local Value => Master Value
    swoole.enable_coroutine => On => On
    swoole.display_errors => On => On
    swoole.use_shortname => On => On
    swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
#### OS
    Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

#### PHP
    PHP 7.2.17 (cli) (built: Apr  3 2019 10:02:16) ( NTS )
    Copyright (c) 1997-2018 The PHP Group
    Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
        with Zend OPcache v7.2.17, Copyright (c) 1999-2018, by Zend Technologies

**Comment by matyhtf** [comment]
You should add `reload_async` option, There will be a bug when use max_request with coroutines.
```php
$http->set([
    'worker_num' => 1,
    'max_request' => 1,
]);
```
