### ISSUE TITLE
Redis5 Stream  Coroutine  Support

### ISSUE THREAD

**Issue by streambo** [swoole/swoole-src#2536]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

 Swoole\Coroutine\Redis    have not method xadd xack....

2. What did you expect to see?

add xadd xac.... to Swoole\Coroutine\Redis

3. What did you see instead?

add xadd xac.... to Swoole\Coroutine\Redis

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.3.0

5. What is your machine environment used (including version of kernel & php & gcc) ?

centos7 php7.2.9

**Comment by twose** [comment]
You can use phpredis after you call `Swoole\Runtime::enableCoroutine`

**Comment by matyhtf** [comment]
```php
$redis = Swoole\Coroutine\Redis;
$redis->request(['xadd', ...]);
```
