### ISSUE TITLE
如果在go函数中有new Server行为 会有core错误

### ISSUE THREAD

**Issue by php-lsys** [swoole/swoole-src#2539]
```
go(function(){
    new \Swoole\Server("127.0.0.1", "9898", SWOOLE_SOCK_TCP);
    $m=new \Swoole\Coroutine\MySQL;
    $m->connect(['host' => '127.0.0.1',
        'port' => 3306,
        'user' => '',
        'password' => '']);
});
```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffffdb00801 in __GI_abort () at abort.c:79
#2  0x00007ffffdaf039a in __assert_fail_base (fmt=0x7ffffdc777d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x7ffffa90e6b8 "swoole_objects.array[handle] == NULL",
    file=file@entry=0x7ffffa90e650 "/home/lonely/php/ext/swoole/swoole.cc", line=line@entry=396,
    function=function@entry=0x7ffffa90fa80 <swoole_set_object_by_handle::__PRETTY_FUNCTION__> "void swoole_set_object_by_handle(uint32_t, void*)") at assert.c:92
#3  0x00007ffffdaf0412 in __GI___assert_fail (assertion=0x7ffffa90e6b8 "swoole_objects.array[handle] == NULL",
    file=0x7ffffa90e650 "/home/lonely/php/ext/swoole/swoole.cc", line=396,
    function=0x7ffffa90fa80 <swoole_set_object_by_handle::__PRETTY_FUNCTION__> "void swoole_set_object_by_handle(uint32_t, void*)") at assert.c:101
#4  0x00007ffffa80315c in swoole_set_object_by_handle (handle=2, ptr=0x7ffffac86000)
    at /home/lonely/php/ext/swoole/swoole.cc:396
#5  0x00007ffffa861666 in swoole_mysql_coro_create_object (ce=0x966bc40)
    at /home/lonely/php/ext/swoole/swoole_mysql_coro.cc:408
#6  0x000000000872da93 in object_and_properties_init (arg=0x7ffffac82120, class_type=0x966bc40, properties=0x0)
    at /mnt/c/Users/PC/Downloads/php-7.3.3/Zend/zend_API.c:1335
#7  0x000000000872dad7 in object_init_ex (arg=0x7ffffac82120, class_type=0x966bc40)
    at /mnt/c/Users/PC/Downloads/php-7.3.3/Zend/zend_API.c:1343
#8  0x00000000087a0375 in ZEND_NEW_SPEC_CONST_UNUSED_HANDLER ()
    at /mnt/c/Users/PC/Downloads/php-7.3.3/Zend/zend_vm_execute.h:8825
#9  0x00000000087fd7e0 in execute_ex (ex=0x7ffffac820a0)
    at /mnt/c/Users/PC/Downloads/php-7.3.3/Zend/zend_vm_execute.h:56303
#10 0x00007ffffa82570e in swoole::PHPCoroutine::create_func (arg=0x7ffffffea6f0)
    at /home/lonely/php/ext/swoole/swoole_coroutine.cc:369
#11 0x00007ffffa792299 in swoole::Context::context_func (arg=0x9633b98)
    at /home/lonely/php/ext/swoole/src/coroutine/context.cc:125
#12 0x00007ffffa9028d1 in make_fcontext ()
    at /home/lonely/php/ext/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:64

**Comment by twose** [comment]
在v4.3.2以后, 类似操作会导致致命错误
```log
[2019-04-29 19:17:12 @34727.0]	ERROR	(PHP Fatal Error: 507):
Swoole\Coroutine\MySQL::connect: operation not support (reactor is not ready)
Stack trace:
#0  Swoole\Coroutine\MySQL->connect() called at [/Users/twosee/Toast/swoole-src/Debug/#2539.php:10]
```

**Comment by php-lsys** [comment]
刚从master分支拉下来的

**Comment by twose** [comment]
@php-lsys 不好意思 我是mysql分支 mysql客户端重构为协程后 不会再有这个问题

**Comment by php-lsys** [comment]
我觉得该在server的构造中判断下,如果是在协程环境下直接抛异常.不然有时候不小心NEW下.直接出core了.这真是很悲催的一件事.

**Comment by twose** [comment]
如我所说的 在MySQL分支已经修复了 是一个已知问题
