### ISSUE TITLE
swoole websocket 客户端是否支持数据gzip解压？

### ISSUE THREAD

**Issue by 2007lf** [swoole/swoole-src#2543]
问题描述
Version 4.3.1
websocket服务端返回的所有数据都进行了 GZIP 压缩，需要 client 在收到数据之后需要进行解压

相关代码
```
go(function () {
    $cli = new Co\http\Client("api.huobi.pro", 443, true);//需要上vpn
    $ret = $cli->upgrade("/ws");
    var_dump($cli->statusCode);
    if ($ret) {
        while (true) {
            var_dump($cli->push('{"sub": "market.btcusdt.kline.1min"}'));
            var_dump($cli->recv());
            co::sleep(1);
        }
    }
});
```
运行结果和我的理解
int(101) #连接成功
bool(true) #发送数据成功
bool(false) #$cli->recv()失败，怀疑是不是返回的是gzip数据，导致的失败
接着第二次push，握手失败错误信息
A PHP Error was encountered

Severity: Warning
Message: SwooleCoroutineHttpClient::push(): websocket handshake failed, cannot push data.

可以帮忙测试找下原因吗？非常感谢！

**Comment by twose** [comment]
估计是你发的消息不正确, 连接被对端关闭了
如果是gzip, 需要发送二进制的数据, 且需要你自己编码和解码

**Comment by xiaobozi** [comment]
> 问题描述
> Version 4.3.1
> websocket服务端返回的所有数据都进行了 GZIP 压缩，需要 client 在收到数据之后需要进行解压
> 
> 相关代码
> 
> ```
> go(function () {
>     $cli = new Co\http\Client("api.huobi.pro", 443, true);//需要上vpn
>     $ret = $cli->upgrade("/ws");
>     var_dump($cli->statusCode);
>     if ($ret) {
>         while (true) {
>             var_dump($cli->push('{"sub": "market.btcusdt.kline.1min"}'));
>             var_dump($cli->recv());
>             co::sleep(1);
>         }
>     }
> });
> ```
> 
> 运行结果和我的理解
> int(101) #连接成功
> bool(true) #发送数据成功
> bool(false) #$cli->recv()失败，怀疑是不是返回的是gzip数据，导致的失败
> 接着第二次push，握手失败错误信息
> A PHP Error was encountered
> 
> Severity: Warning
> Message: SwooleCoroutineHttpClient::push(): websocket handshake failed, cannot push data.
> 
> 可以帮忙测试找下原因吗？非常感谢！

握手失败应该是需要mock 下
$settings = ['websocket_mask' => true];

            $settings['ssl_host_name'] =  'api. huobi.pro';
            $cli->set($settings);

**Comment by twose** [comment]
没有设置mask和ssl_host_name可能也是对端切断连接的原因

**Comment by xiaobozi** [comment]
> 估计是你发的消息不正确, 连接被对端关闭了
> 如果是gzip, 需要发送二进制的数据, 且需要你自己编码和解码, php有相关的函数可以使用

使用gzdecode的这个函数么？始终提示我  date error  
我看swoole http client 源码里自动解码了。现在一头雾水啊

**Comment by twose** [comment]
http是自动解码的 websocket没有这个功能

**Comment by xiaobozi** [comment]
> http是自动解码的 websocket没有这个功能

大神，gzdecode  gzinflate 都不行，我是链接的 okex的wss接口
有没有啥思路 让我继续， 耗着两天了 没进展

**Comment by xiaobozi** [comment]
> http是自动解码的 websocket没有这个功能

大神能不能在 saber 的websocket 里加上自动解压

**Comment by twose** [comment]
没见过这种机制, 你需要找到别的语言标准库(比如js)的支持, 然后提个RFC

**Comment by 2007lf** [comment]
真是websocket_mask这个原因，多谢 @xiaobozi  我查了下文档，在老版本的swoole作为websocket客户端还有说到这个问题要注意，新版本只能使用协程方式，就比较简单，没有说明，希望官方可以整理下。
