### ISSUE TITLE
协程 不兼容XDEBUG 也不兼容PHPGDB 无法支持phpunit的代码覆盖

### ISSUE THREAD

**Issue by php-lsys** [swoole/swoole-src#2544]
如果不用phpunit的生成代码覆盖率报告 ,请问有其他什么好办法没有?

**Comment by k911** [comment]
Hello @php-lsys actually I found "pcov" extension working quite nice with swoole to generate code coverage via phpunit. 
Refs:
- PCOV Extension: https://github.com/krakjoe/pcov
- Project, in which I'm successfully using "pcov": https://github.com/k911/swoole-bundle

**Comment by shanliu** [comment]
> Hello @php-lsys actually I found "pcov" extension working quite nice with swoole to generate code coverage via phpunit.
> Refs:
> 
> * PCOV Extension: https://github.com/krakjoe/pcov
> * Project, in which I'm successfully using "pcov": https://github.com/k911/swoole-bundle

i try it,not worker....
test project: https://github.com/shanliu/tmp_test
xdebug ouput:
PHPUnit 8.0.6 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 149 ms, Memory: 6.00 MB

OK (2 tests, 2 assertions)


Code Coverage Report:
  2019-05-05 07:50:41

 Summary:
  Classes: 100.00% (1/1)
  Methods: 100.00% (2/2)
  Lines:   100.00% (4/4)

Mycode
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% (  4/  4)
PCOV output:
PHPUnit 8.0.6 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 130 ms, Memory: 6.00 MB

OK (2 tests, 2 assertions)


Code Coverage Report:
  2019-05-05 07:50:28

 Summary:
  Classes:  0.00% (0/1)
  Methods:  0.00% (0/2)
  Lines:    0.00% (0/6)

Mycode
  Methods:   0.00% ( 0/ 2)   Lines:   0.00% (  0/  6)

**Comment by k911** [comment]
According to https://github.com/krakjoe/pcov#notes, I think you should set these values in `php.ini`

```ini
pcov.enabled = 1
pcov.directory = /path/to/your/source/directory
```

**Comment by shanliu** [comment]
> According to https://github.com/krakjoe/pcov#notes, I think you should set these values in `php.ini`
> 
> ```ini
> pcov.enabled = 1
> pcov.directory = /path/to/your/source/directory
> ```

i set it.but it not working.

**Comment by matyhtf** [comment]
可以关注这个项目 https://github.com/mabu233/xdebug

**Comment by wanghaitao-git** [comment]
@matyhtf ,https://github.com/mabu233/xdebug这个项目是不是还没有解决swoole兼容Xdebug的问题啊？

**Comment by twose** [comment]
是xdebug不兼容Swoole
