### ISSUE TITLE
undefined symbol: swAio_handler_gethostbyname

### ISSUE THREAD

**Issue by yellow1912** [swoole/swoole-src#2548]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I was trying to install swoole on ubuntu 18 following the readme

2. What did you expect to see?

Working swoole

3. What did you see instead?

PHP Startup: Unable to load dynamic library 'swoole_async.so' (tried: /usr/lib/php/20170718/swoole_async.so (/usr/lib/php/20170718/swoole_async.so: undefined symbol: swAio_handler_gethostbyname), /usr/lib/php/20170718/swoole_async.so.so (/usr/lib/php/20170718/swoole_async.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.0-alpha
Built => May  2 2019 03:24:07
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1  11 Sep 2018
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

php 7.2, ubuntu 18, gcc version 8.3.0

**Comment by matyhtf** [comment]
Need to load swoole.so first
