### ISSUE TITLE
捕捉异常多次多次捕获到异常

### ISSUE THREAD

**Issue by linfasfasf** [swoole/swoole-src#2558]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```
function main()
{
    (new Test())->test();
}

class Test
{
    protected $test;
    public function test()
    {
        go(function (){
            $this->test = 'a';
            try {
                throw new \Exception('sss');
            } catch (\Exception $e){
                var_dump($this->test);
            }
        });
    }
}
```

2. What did you expect to see?

![image](https://user-images.githubusercontent.com/10447689/57230508-16452880-704b-11e9-9f45-e6dc78f24b52.png)

3. What did you see instead?

![image](https://user-images.githubusercontent.com/10447689/57230519-1fce9080-704b-11e9-8a31-12fd4ede610b.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.1
Built => Apr  3 2019 16:47:34
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.0j  20 Nov 2018
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

```
Linux hlg-dev 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
PHP 7.2.11 (cli) (built: Oct 16 2018 00:46:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by twose** [comment]
PHP冷知识: 和类名同名的方法被视为构造方法
