### ISSUE TITLE
http2->ping() method creates unnecessary Warning in the log file if server is not connected

### ISSUE THREAD

**Issue by ozgurhangisi** [swoole/swoole-src#2559]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

When I check http2 connection using ping() method it creates Warning on the log file if client is not connected. Actually I use ping method to check if connection is still valid. So I think this Warning in the log file is unnecessary.

Warning in the log file : 

Warning: Swoole\Coroutine\Http2\Client::ping(): client is not connected to server in XXXXX on line 378

Here is the function : 

```
    public function ping_connection(string $type,int $cid) : bool {
        if (isset($this->connection_pool[$type][$cid]['conn']) && isset($this->connection_pool[$type][$cid]['conn']->connected)) {
            return $this->connection_pool[$type][$cid]['conn']->ping();
        } else {
            return false;
        }
        
    }
```
2. What did you expect to see?

I expect not to see Warning on the log file if http2 client is not connected to server. I use many connections and I see a lot of unnecessary Warnings in the log file.

3. What did you see instead?

I see Warning: Swoole\Coroutine\Http2\Client::ping(): client is not connected to server in XXXXX on line 378

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.3
Built => Apr 27 2019 18:59:16
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1b  26 Feb 2019
http2 => enabled
pcre => enabled
zlib => enabled
brotli => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (including version of kernel & php & gcc) ?

MacOs Sierra 10.12.6, PHP 7.3.4

**Comment by twose** [comment]
Remove `isset`, the property `connected` always exists.

**Comment by ozgurhangisi** [comment]
Thanks. I'll remove isset.

**Comment by twose** [comment]
Already solved on the master branch.
