### ISSUE TITLE
example/eof/server.php 报错

### ISSUE THREAD

**Issue by byargv** [swoole/swoole-src#256]
[root@localhost eof]# php server.php 
[2015-05-15 14:49:32 *4415.0]	WARN	swReactorEpoll_add: add events[fd=59#0, type=5, events=1] failed. Error: Bad file descriptor[9].

[root@localhost eof]# php client.php 
serialize_data length=16473send length=16481

Warning: swoole_client::recv(): recv() failed. Error: Resource temporarily unavailable [11] in /media/sf_wwwroot/swoole/eof/client.php on line 54

**Comment by matyhtf** [comment]
修改一下 $mode ，改为SWOOLE_PROCESS
