### ISSUE TITLE
使用stream_select函数阻塞等待时，swoole进程不能stop

### ISSUE THREAD

**Issue by Dean0820** [swoole/swoole-src#2562]
环境信息：
CentOS 6.5
PHP版本=> 7.1.1 
Swoole版本=>  4.3.2
gcc版本4.8.5（GCC）

问题描述：
使用stream_select函数阻塞等待时，swoole进程不能stop

**Comment by twose** [comment]
阻塞了就无法操作, 除非关闭signalfd, 用信号打断

**Comment by Dean0820** [comment]
> 阻塞了就无法操作, 除非关闭signalfd, 用信号打断

感谢回复，我是发送SIGUSR1信号去停止进程的在4.3.2版本不能停止，但在4.3.0版本是可以停止的

**Comment by matyhtf** [comment]
task 进程启用了协程，就会开启异步信号，无法终止

**Comment by Dean0820** [comment]
> task 进程启用了协程，就会开启异步信号，无法终止

感谢大神回复，我这个不是task进程是worker进程，很想解决这个问题，因为我集成了Rabbitmq的PhpAmqpLib客户端，如果不能解决那每次stop就要等待超时了，我试了一下reload没有这种问题
