### ISSUE TITLE
Swoole\Coroutine\Http\Client 客户端 代理 连接超时。

### ISSUE THREAD

**Issue by Mr-LP** [swoole/swoole-src#2566]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

`go(function(){
    $cli = new Swoole\Coroutine\Http\Client('djphp.top', 80);
    // $cli->set(['proxy' => 'http://221.176.206.29:8060']);
    $cli->set(array(
        'http_proxy_host'     =>  '127.0.0.1',
        'http_proxy_port'     =>  8090,
        // 'timeout'     =>  -1,
    ));
    $cli->get('/');
    var_dump($cli);
    echo $cli->body;
    $cli->close();
});`

2. What did you expect to see?

 使用代理访问成功
 
succes

3. What did you see instead?

object(Swoole\Coroutine\Http\Client)#2 (18) {
  ["errCode"]=>
  int(0)
  ["errMsg"]=>
  string(0) ""
  ["connected"]=>
  bool(false)
  ["host"]=>
  string(9) "djphp.top"
  ["port"]=>
  int(80)
  ["ssl"]=>
  bool(false)
  ["setting"]=>
  array(2) {
    ["http_proxy_host"]=>
    string(9) "127.0.0.1"
    ["http_proxy_port"]=>
    int(8090)
  }
  ["requestMethod"]=>
  string(3) "GET"
  **["statusCode"]=>
  int(-1)**
。。。。。。。。
}

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.3

5. What is your machine environment used (including version of kernel & php & gcc) ?
php=>7.2   

Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016

去除掉 下面这段代码 就访问成功了， 我试过几个代理， 都是这样

` $cli->set(array(
        'http_proxy_host'     =>  '127.0.0.1',
        'http_proxy_port'     =>  8090,
        // 'timeout'     =>  -1,
    ));`

**Comment by huanghantao** [comment]
@Mr-LP 我觉得你应该是没走代理。因为我看了一下swoole的源码，set中并没有`proxy`这个配置选项。
你可以把你set proxy的那一行删了，也是可以访问你的网站的。

**Comment by huanghantao** [comment]
@Mr-LP 你或许可以通过抓包分析一下试试

**Comment by Mr-LP** [comment]
@huanghantao 
谢谢你的解答， 那个proxy 是被注释的。 我准备了一份新的代码
go(function(){
    $cli = new Swoole\Coroutine\Http\Client('djphp.top', 80);
    $cli->set(array(
        'http_proxy_host'     =>  '129.204.21.49',
        'http_proxy_port'     =>  80,
        // 'timeout'     =>  -1,
    ));
    $cli->get('/');
    var_dump($cli);
    echo $cli->body;
    $cli->close();
});
我查看了所有的信息， 没有任何报错。
我需要使用代理 去访问 一些地址， 但是使用代理就有点问题。 也没其他的配置。

**Comment by twose** [comment]
@Mr-LP 尝试使用master分支的代码, 可能你的代理不支持CONNECT方法, 已修正

**Comment by twose** [comment]
@Mr-LP 尝试使用master分支的代码, 可能你的代理不支持CONNECT方法, 已修正
