### ISSUE TITLE
客户端连接服务端报错

### ISSUE THREAD

**Issue by moxiaobai** [swoole/swoole-src#257]
环境
PHP Version 5.4.38
swoole  Version 1.7.16

编译： ./configure --enable-async-mysql --with-php-config=/usr/local/php/bin/php-config

服务端
/home/sofe/swoole-src-swoole-1.7.16-stable/examples/server/echo.php

客户端连接服务端，服务端报错
php: symbol lookup error: /usr/local/php/lib/php/extensions/no-debug-non-zts-20100525/swoole.so: undefined symbol: __sync_bool_compare_and_swap_4

**Comment by matyhtf** [comment]
Gcc版本太低

**Comment by moxiaobai** [comment]
gcc version 4.9.2 (GCC)
升级到很高版本l，还是报错

**Comment by moxiaobai** [comment]
问题解决，谢谢Rango大神
https://www.evernote.com/shard/s38/sh/6699d413-365a-489c-b90f-c3af70ef5365/fdc2a887d11218e6
