### ISSUE TITLE
4.3版本在php-fpm/apache中使用task功能，客户端如何关闭的问题

### ISSUE THREAD

**Issue by longit123** [swoole/swoole-src#2571]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

> 先说一下想法，由于业务代码都是基于PHP5.6的，不可能所有代码都改造成swoole（成本上不可能），只是准备将可能产生性能瓶颈的部分逻辑代码迁移到swoole执行，其他的代码还是在php-fpm中，通过在php-fpm中将数据传递到swoole中执行；

架构如下：

按照swoole[官方](https://wiki.swoole.com/wiki/page/671.html)文档，php7.2运行swoole 

>swoole 4.3.3版本，代码如下：

`<?php

date_default_timezone_set('Asia/Shanghai');

use Swoole\Redis\Server;

$server = new Server("127.0.0.1", 9501, SWOOLE_BASE);

$server->set(array(
                 'task_worker_num' => 32,
                 'worker_num' => 1,
                 'daemonize' => true,
                'task_enable_coroutine'=>false //因为公司其他开发对协程不熟悉，所以不准备使用协程
//                 'log_file'=>"/tmp/test_swoole.log"
             ));

$server->setHandler('LPUSH', function ($fd, $data) use ($server) {
    $taskId = $server->task($data);
    if ($taskId === false)
    {
        return Server::format(Server::ERROR);
    }
    else
    {
        return Server::format(Server::INT, $taskId);
    }
});

$server->on('Start', function() {
    swoole_set_process_name("test_server");
});

$server->on('receive', function (\Swoole\Server $serv, $fd, $reactor_id, $data) {
    $serv->send($fd, 'Swoole: '.$data);
    $serv->close($fd);
});
$server->on('close', function (swoole_server $server, int $fd, int $reactorId) {
//    echo "Client: Close.\n";
});

$server->on('Finish', function($response) {
//    var_dump("\nfinish-".$response);    
});

$server->on('WorkerStart', function() {
    swoole_set_process_name("test_worker");
});

$server->on('Task', function (\Swoole\Server $serv, $taskId, $workerId, $data) {
    swoole_set_process_name("test_async_task".$taskId);
    
    //处理任务
    file_put_contents("/tmp/test_swoole.log",var_export($data,1),FILE_APPEND);
    //完成任务，结束并返回数据
    $serv->finish([123, 'hello']);
    return;
});

$server->start();`

> 业务端是PHP5.6版本，使用文档上介绍的方式访问

`<?php

        $redis = new \Redis;
        $redis->connect('127.0.0.1', 9501);
        $taskId = $redis->lpush("myqueue".date("m-d H:i:s"), json_encode(array("hello", "swoole")));
`
2. What did you expect to see?

客户端接能够正常关闭

3. What did you see instead?

一直停留，然后超时后报"read error on connection"

服务端可以接收到客户端传递的数据，问题是客户端一直停留在那里，然后报错（如果用swoole低版本，2.0.10，客户端是可以自动关闭的）:Uncaught exception 'RedisException' with message 'read error on connection' 

> ps：我知道这里的Redis并不是真正意义上的Redis服务器，只是swoole实现了Redis协议

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole:4.3.3

5. What is your machine environment used (including version of kernel & php & gcc) ?

php: 5.6、7.2

线程模型：posix

gcc 版本 4.8.2 20131212 (Red Hat 4.8.2-8) (GCC) 

centos: 6.8

**Comment by twose** [comment]
服务器需要设置`'enable_coroutine' => false`,  把除task进程外的协程也关掉,  否则无法使用return的方法响应, 文档里有写
