### ISSUE TITLE
Swoole\Coroutine\Http\Client::execute(): ssl cert file[(null)] not found

### ISSUE THREAD

**Issue by browningweb** [swoole/swoole-src#2573]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

`$client = new Swoole\Coroutine\Http\Client($domain, 443, true);
$client->set('ssl_verify_peer' => true,
  'ssl_cafile' => 'xxxx.pem',
  'ssl_cert_file' => 'xxx.pem',
  'ssl_key_file' => 'xxxx.pem');`

2. What did you expect to see?

传入 ssl_cert_file，ssl_key_file 并没有加载出来。出现在 4.3.3 与 4.3.2

3. What did you see instead?

切换到 V4.3.1 就可以了。

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.3 / 4.3.2
Built => May 11 2019 08:15:28
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => LibreSSL 2.6.5
http2 => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
mysqlnd => enabled
async_redis => enabled

5. What is your machine environment used (including version of kernel & php & gcc) ?

centos, docker php:7.2-alpine

**Comment by twose** [comment]
感谢反馈, 已在master修复
