### ISSUE TITLE
Can you add more comments to the source code, such as explaining what this method is for? How to debug source code

### ISSUE THREAD

**Issue by opjklu** [swoole/swoole-src#2574]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
We are working on this.
The source code is very simple, but the wisdom you need to understand the source codes...
