### ISSUE TITLE
swoole_redis_server将来会去掉吗？

### ISSUE THREAD

**Issue by longit123** [swoole/swoole-src#2576]
听说将来可能会去掉，但感觉挺好用的，不同业务端PHP版本可以直接投递任务到swoole_redis_server里面，多进程异步处理，而不需要业务端（显示的）经过http或者TCP，而且业务端只要装个redis扩展就行，如果去掉了，有什么替代方案吗？

**Comment by matyhtf** [comment]
不会去掉。至少 Swoole5 没有这个计划。

**Comment by longit123** [comment]
这个redis server需要将协程都关闭掉，后续会考虑支持[协程](https://github.com/swoole/swoole-src/issues/2571)吗？
