### ISSUE TITLE
请教http2是否支持trailer，如何使用？

### ISSUE THREAD

**Issue by luoxiaojun1992** [swoole/swoole-src#2578]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

open_http2_protocol = true

$response->trailer('grpc-message', 'OK');

客户端没有响应，nghttp抓包显示没有END_STREAM

$response->trailer('grpc-message',  '');

可以正常返回，grpc-message为空

2. What did you expect to see?

返回grpc-message为ok

3. What did you see instead?

luoxiaojundeMacBook-Pro:~ luoxiaojun$ nghttp -nv --hexdump http://127.0.0.1:50051/helloworld/.Greeter/SayHello -H 'content-type: application/grpc' -H ':method: POST' -H 'transfer-encoding: chunked' -H 'TE: trailers'
[  0.001] Connected
[  0.001] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
[  0.001] send PRIORITY frame <length=5, flags=0x00, stream_id=3>
          (dep_stream_id=0, weight=201, exclusive=0)
[  0.001] send PRIORITY frame <length=5, flags=0x00, stream_id=5>
          (dep_stream_id=0, weight=101, exclusive=0)
[  0.001] send PRIORITY frame <length=5, flags=0x00, stream_id=7>
          (dep_stream_id=0, weight=1, exclusive=0)
[  0.001] send PRIORITY frame <length=5, flags=0x00, stream_id=9>
          (dep_stream_id=7, weight=1, exclusive=0)
[  0.001] send PRIORITY frame <length=5, flags=0x00, stream_id=11>
          (dep_stream_id=3, weight=1, exclusive=0)
[  0.001] send HEADERS frame <length=94, flags=0x25, stream_id=13>
          ; END_STREAM | END_HEADERS | PRIORITY
          (padlen=0, dep_stream_id=11, weight=16, exclusive=0)
          ; Open new stream
          :method: POST
          :path: /helloworld/.Greeter/SayHello
          :scheme: http
          :authority: 127.0.0.1:50051
          accept: */*
          accept-encoding: gzip, deflate
          user-agent: nghttp2/1.38.0
          content-type: application/grpc
          transfer-encoding: chunked
          te: trailers
00000000  00 00 12 04 00 00 00 00  00 00 03 00 00 00 80 00  |................|
00000010  04 00 00 ff ff 00 05 00  00 40 00                 |.........@.|
0000001b
[  0.334] recv SETTINGS frame <length=18, flags=0x00, stream_id=0>
          (niv=3)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):128]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
          [SETTINGS_MAX_FRAME_SIZE(0x05):16384]
[  0.334] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
00000000  00 00 5e 01 04 00 00 00  0d 88 5f 90 1d 75 d0 62  |..^......._..u.b|
00000010  0d 26 3d 4c 4d 65 64 ff  75 d8 74 9f 40 85 4d 83  |.&=LMed.u.t.@.M.|
00000020  35 05 b3 92 9a ca c8 b2  12 34 da 8f a5 26 b2 b2  |5........4...&..|
00000030  2d 49 50 81 cc 5f 76 8d  47 83 9e 82 ad 3a 53 5a  |-IP.._v.G....:SZ|
00000040  c8 2d 9d cb 67 61 96 d0  7a be 94 0b 2a 68 1f a5  |.-..ga..z...*h..|
00000050  04 00 be a0 43 70 41 b8  d8 94 c5 a3 7f 5a 83 9b  |....CpA......Z..|
00000060  d9 ab 0f 0d 02 37 35 00  00 4b 00 00 00 00 00 0d  |.....75..K......|
00000070  1f 8b 08 00 00 00 00 00  04 13 4b 4c 4c 4c e4 e5  |..........KLLL..|
00000080  e2 e5 f2 70 75 74 71 0d  0a 56 d0 48 cb 49 4c 2f  |...putq..V.H.IL/|
00000090  56 b0 55 70 f5 73 89 0f  0e 09 72 75 f4 d5 01 b3  |V.Up.s....ru....|
000000a0  a1 0a 34 79 b9 d2 8b 0a  92 75 8b 4b 12 4b 4a 41  |..4y.....u.K.KJA|
000000b0  ea 0c 00 24 dc 7d 28 42  00 00 00                 |...$.}(B...|
000000bb
[  0.334] recv (stream_id=13) :status: 200
[  0.334] recv (stream_id=13) content-type: application/grpc+proto
[  0.334] recv (stream_id=13) trailer: grpc-status, grpc-message
[  0.334] recv (stream_id=13) server: swoole-http-server
[  0.334] recv (stream_id=13) date: Mon, 13 May 2019 11:21:52 GMT
[  0.334] recv (stream_id=13) content-encoding: gzip
[  0.334] recv (stream_id=13) content-length: 75
[  0.334] recv HEADERS frame <length=94, flags=0x04, stream_id=13>
          ; END_HEADERS
          (padlen=0)
          ; First response header
[  0.334] recv DATA frame <length=75, flags=0x00, stream_id=13>

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.3
Built => May 13 2019 15:48:01
coroutine => enabled
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2r  26 Feb 2019
http2 => enabled
pcre => enabled
zlib => enabled
brotli => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (including version of kernel & php & gcc) ?

php -v

PHP 7.2.18 (cli) (built: May  2 2019 13:03:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.18, Copyright (c) 1999-2018, by Zend Technologies

uname -a
Darwin luoxiaojundeMacBook-Pro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

nghttp --version
nghttp nghttp2/1.38.0

**Comment by twose** [comment]
https://github.com/swoole/grpc/blob/master/examples/grpc/greeter_server.php

**Comment by luoxiaojun1992** [comment]
我看了swoole/grpc，grpc-message是空字符串？并没有实际作用？用node js的client请求greeter_server报获取不到status。

**Comment by twose** [comment]
@luoxiaojun1992 你改一下不就好啦

**Comment by luoxiaojun1992** [comment]
重现步骤：
```
#执行swoole grpc server
git clone git@github.com:swoole/grpc.git
php path/to/grpc/examples/grpc/greeter_client.php

#执行node js grpc client
git clone git@github.com:grpc/grpc.git
node path/to/grpc/examples/node/dynamic_codegen/greeter_client.js
```

nodejs client返回
Error: 2 UNKNOWN: No status received
    at Object.exports.createStatusError (/Users/luoxiaojun/php/grpc-swoole/grpc/examples/node/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/luoxiaojun/php/grpc-swoole/grpc/examples/node/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/luoxiaojun/php/grpc-swoole/grpc/examples/node/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/luoxiaojun/php/grpc-swoole/grpc/examples/node/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/luoxiaojun/php/grpc-swoole/grpc/examples/node/node_modules/grpc/src/client_interceptors.js:845:24) {
  code: 2,
  metadata: Metadata { _internal_repr: { 'grpc-message': [Array] } },
  details: 'No status received'
}

**Comment by luoxiaojun1992** [comment]
go和php原生的client也返回相同的错误

**Comment by twose** [comment]
不应当 https://github.com/swoole/grpc/tree/master/examples/grpc
这个目录下有各语言的例子 都能跑通 一会我再确认一下
