### ISSUE TITLE
master最新版及1.7.16-stable测试：swoole_server->task异步投递任务太慢，需要12～25ms? 谢谢～

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#258]
client_id: 1, task_id: 0, worker_id: 3, task_elapsed:0.023415803909302

如上，swoole_server->task异步投递任务太慢，需要12～25ms

投递的数据类似：

{"lid":"1431686505578243633","class":"task","method":"replace_sessions","task_type":1,"data":{"gtid":3698626402965279928,"rrrr":1,"uid":6025223,"eee":6501028,"uname":"zhangfan63","status":3,"cl_type":1,"aid":"","remote_ip":2130706433,"dd":40692,"user_agent":"curl\/7.19.7 (x86_64-redhat-linux-gnu) libcurl\/7.19.7 NSS\/3.16.2.3 Basic ECC zlib\/1.2.3 libidn\/1.18 libssh2\/1.4.2","ddss":"zh_CN","code":"CN","city":"city_name","recent_time":1431686505}}

这块是异步投递应该立即返回吧？ 

为啥这么慢呢，不理解，非常感谢！

**Comment by yiliaofan** [comment]
是否bug呢？ 之前历史版本没发现类似问题  请@韩老大 有空帮忙看看
非常感谢～

**Comment by matyhtf** [comment]
测试100次再看结果
