### ISSUE TITLE
4.3.3 不回调 register_shutdown_function 函数，并导致该进程之后所有请求都是500错误

### ISSUE THREAD

**Issue by scguang301** [swoole/swoole-src#2580]
环境： php: 7.1.3  swoole: 4.3.3
onRequest 中出现 Fatal error错误不回调 register_shutdown_function 注册的函数，然后该进程状态出错，进程之后接受到的请求都返回500错误。 目前已经通过try{} catch(\Throwable){} 处理掉了，但仍然希望能修复这个bug.
期望： 
1. 调用 register_shutdown_function 注册的函数
2. 如果不调用，进程异常，进程打印错误日志退出，不要出现接受的请求都返回500错误

**Comment by matyhtf** [comment]
最新版本已经修复了，这是因为 fatal error 发生在协程中无法 longjmp 到正确的位置，因此底层直接退出了。

**Comment by twose** [comment]
https://github.com/swoole/swoole-src/pull/2579
