### ISSUE TITLE
Malware present on swoole.co.uk/docs

### ISSUE THREAD

**Issue by ashbeats** [swoole/swoole-src#2597]
I believe there is some sort of malware that has infected https://www.swoole.co.uk/docs/get-started/prerequisites

Noticed this earlier as I was browsing the docs. 

![alt text](https://i.imgur.com/hFsaUHo.png "screenshot")

**Comment by twose** [comment]
I don't know the situation, @doubaokun Can you have a look?

**Comment by doubaokun** [comment]
Hi @ashbeats, we are testing a paywall product on this page. Thanks for reporting and Sorry for the inconvenience.
