### ISSUE TITLE
swoole-1.7.16-stable ./configure --enable-async-mysql 无法编译通过 fatal error: my_global.h: No such file or directory

### ISSUE THREAD

**Issue by nangua** [swoole/swoole-src#260]
环境
$ lsb_release -ds
Ubuntu 15.04
$ 
$ php -v
PHP 5.6.4-4ubuntu6 (cli) (built: Apr 17 2015 15:47:51) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
$ 
$ sudo dpkg -l | grep mysql
ii  libdbd-mysql-perl                                    4.028-2                                    amd64        Perl5 database interface to the MySQL database
ii  libmysqlclient18:amd64                               5.6.24-0ubuntu2                            amd64        MySQL database client library
ii  mysql-client                                         5.6.24-0ubuntu2                            all          MySQL database client (metapackage depending on the latest version)
ii  mysql-client-5.6                                     5.6.24-0ubuntu2                            amd64        MySQL database client binaries
ii  mysql-client-core-5.6                                5.6.24-0ubuntu2                            amd64        MySQL database core client binaries
ii  mysql-common                                         5.6.24-0ubuntu2                            all          MySQL database common files, e.g. /etc/mysql/my.cnf
ii  mysql-server                                         5.6.24-0ubuntu2                            all          MySQL database server (metapackage depending on the latest version)
ii  mysql-server-5.6                                     5.6.24-0ubuntu2                            amd64        MySQL database server binaries and system database setup
ii  mysql-server-core-5.6                                5.6.24-0ubuntu2                            amd64        MySQL database server binaries
ii  php5-mysqlnd                                         5.6.4+dfsg-4ubuntu6                        amd64        MySQL module for php5 (Native Driver)
$ 

$make -j2
..........
In file included from /media/developer/src/github.com/swoole/swoole/swoole.c:269:0:
/usr/include/php5/ext/mysqli/php_mysqli_structs.h:63:23: fatal error: my_global.h: No such file or directory
 #include <my_global.h>
                       ^
compilation terminated.
/bin/bash /media/developer/src/github.com/swoole/swoole/libtool --mode=compile cc  -I. -I/media/developer/src/github.com/swoole/swoole -DPHP_ATOM_INC -I/media/developer/src/github.com/swoole/swoole/include -I/media/developer/src/github.com/swoole/swoole/main -I/media/developer/src/github.com/swoole/swoole -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/media/developer/src/github.com/swoole/swoole/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /media/developer/src/github.com/swoole/swoole/swoole_client.c -o swoole_client.lo 
libtool: compile:  cc -I. -I/media/developer/src/github.com/swoole/swoole -DPHP_ATOM_INC -I/media/developer/src/github.com/swoole/swoole/include -I/media/developer/src/github.com/swoole/swoole/main -I/media/developer/src/github.com/swoole/swoole -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/media/developer/src/github.com/swoole/swoole/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /media/developer/src/github.com/swoole/swoole/swoole_client.c  -fPIC -DPIC -o .libs/swoole_client.o
Makefile:181: recipe for target 'swoole.lo' failed
make: *** [swoole.lo] Error 1
make: *** 正在等待未完成的任务....

**Comment by matyhtf** [comment]
http://wiki.swoole.com/wiki/page/436.html
