### ISSUE TITLE
Cygwin环境下编译最新版本的swoole报错

### ISSUE THREAD

**Issue by xami** [swoole/swoole-src#2600]
Please answer these questions before submitting your issue. Thanks!
Cygwin环境下编译最新版本的swoole报错
通过命令安装php模块:
pecl install swoole
自动下载的 swoole-4.3.4.tgz 开始安装

admin@N22501D1 ~
$ pecl install swoole
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
downloading swoole-4.3.4.tgz ...
Starting to download swoole-4.3.4.tgz (1,348,870 bytes)
..........................................................................................................................................................................................................................................................................done: 1,348,870 bytes
359 source files, building
running: phpize
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
enable sockets supports? [no] : yes
enable openssl support? [no] : yes
enable http2 support? [no] : yes
enable mysqlnd support? [no] : yes
enable postgresql coroutine client support? [no] : yes
building in /tmp/pear/temp/pear-build-admin7coo5o/swoole-4.3.4
running: /tmp/pear/temp/swoole/configure --with-php-config=/usr/bin/php-config --enable-sockets=yes --enable-openssl=yes --enable-http2=yes --enable-mysqlnd=yes --enable-coroutine-postgresql=yes

1. What did you do? If possible, provide a simple script for reproducing the error.
所有依赖都装完了,编译卡在下面这步退出:
libtool: link: g++ -shared -nostdlib /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/crtbeginS.o  src/core/.libs/array.o src/core/.libs/base.o src/core/.libs/channel.o src/core/.libs/error.o src/core/.libs/hashmap.o src/core/.libs/heap.o src/core/.libs/list.o src/core/.libs/log.o src/core/.libs/rbtree.o src/core/.libs/ring_queue.o src/core/.libs/socket.o src/core/.libs/string.o src/coroutine/.libs/base.o src/coroutine/.libs/boost.o src/coroutine/.libs/channel.o src/coroutine/.libs/context.o src/coroutine/.libs/file_lock.o src/coroutine/.libs/hook.o src/coroutine/.libs/socket.o src/coroutine/.libs/ucontext.o src/lock/.libs/atomic.o src/lock/.libs/cond.o src/lock/.libs/file_lock.o src/lock/.libs/mutex.o src/lock/.libs/rw_lock.o src/lock/.libs/semaphore.o src/lock/.libs/spin_lock.o src/memory/.libs/buffer.o src/memory/.libs/fixed_pool.o src/memory/.libs/global_memory.o src/memory/.libs/malloc.o src/memory/.libs/ring_buffer.o src/memory/.libs/shared_memory.o src/memory/.libs/table.o src/network/.libs/async_thread.o src/netw
ork/.libs/client.o src/network/.libs/connection.o src/network/.libs/dns.o src/network/.libs/process_pool.o src/network/.libs/stream.o src/network/.libs/thread_pool.o src/network/.libs/timer.o src/os/.libs/base.o src/os/.libs/msg_queue.o src/os/.libs/sendfile.o src/os/.libs/signal.o src/os/.libs/timer.o src/os/.libs/wait.o src/pipe/.libs/base.o src/pipe/.libs/eventfd.o src/pipe/.libs/unix_socket.o src/protocol/.libs/base.o src/protocol/.libs/base64.o src/protocol/.libs/http.o src/protocol/.libs/http2.o src/protocol/.libs/mime_types.o src/protocol/.libs/mqtt.o src/protocol/.libs/redis.o src/protocol/.libs/sha1.o src/protocol/.libs/socks5.o src/protocol/.libs/ssl.o src/protocol/.libs/websocket.o src/reactor/.libs/base.o src/reactor/.libs/defer_task.o src/reactor/.libs/epoll.o src/reactor/.libs/kqueue.o src/reactor/.libs/poll.o src/reactor/.libs/select.o src/server/.libs/base.o src/server/.libs/manager.o src/server/.libs/master.o src/server/.libs/port.o src/server/.libs/process.o src/server/.libs/reactor_process
.o src/server/.libs/reactor_thread.o src/server/.libs/static_handler.o src/server/.libs/task_worker.o src/server/.libs/worker.o src/wrapper/.libs/client.o src/wrapper/.libs/server.o src/wrapper/.libs/timer.o .libs/swoole.o .libs/swoole_async_coro.o .libs/swoole_atomic.o .libs/swoole_buffer.o .libs/swoole_channel_coro.o .libs/swoole_client.o .libs/swoole_client_coro.o .libs/swoole_coroutine.o .libs/swoole_coroutine_util.o .libs/swoole_event.o .libs/swoole_http_client_coro.o .libs/swoole_http_server.o .libs/swoole_http_v2_client_coro.o .libs/swoole_http_v2_server.o .libs/swoole_lock.o .libs/swoole_mysql_coro.o .libs/swoole_postgresql_coro.o .libs/swoole_process.o .libs/swoole_process_pool.o .libs/swoole_redis_coro.o .libs/swoole_redis_server.o .libs/swoole_runtime.o .libs/swoole_serialize.o .libs/swoole_server.o .libs/swoole_server_port.o .libs/swoole_socket_coro.o .libs/swoole_table.o .libs/swoole_timer.o .libs/swoole_trace.o .libs/swoole_websocket_server.o thirdparty/sockets/.libs/multicast.o thirdparty/sock
ets/.libs/sendrecvmsg.o thirdparty/sockets/.libs/conversions.o thirdparty/sockets/.libs/sockaddr_conv.o thirdparty/.libs/swoole_http_parser.o thirdparty/.libs/multipart_parser.o thirdparty/hiredis/.libs/async.o thirdparty/hiredis/.libs/hiredis.o thirdparty/hiredis/.libs/net.o thirdparty/hiredis/.libs/read.o thirdparty/hiredis/.libs/sds.o thirdparty/http2/.libs/nghttp2_hd.o thirdparty/http2/.libs/nghttp2_rcbuf.o thirdparty/http2/.libs/nghttp2_helper.o thirdparty/http2/.libs/nghttp2_buf.o thirdparty/http2/.libs/nghttp2_mem.o thirdparty/http2/.libs/nghttp2_hd_huffman.o thirdparty/http2/.libs/nghttp2_hd_huffman_data.o   -lpthread -lphp7 -lrt -lssl -lcrypto -lpq -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0 -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/lib -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../.. -lstdc++ -lgcc_s -lgcc -lcygwin -ladv
api32 -lshell32 -luser32 -lkernel32 -lgcc_s -lgcc /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/crtend.o  -pthread -g -O2   -pthread -o .libs/swoole.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/swoole.dll.a
.libs/swoole_client.o: In function `zim_swoole_client_getSocket':
/tmp/pear/temp/swoole/swoole_client.cc:1605: undefined reference to `php_sockets_le_socket'
/tmp/pear/temp/swoole/swoole_client.cc:1605:(.text+0x15b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `php_sockets_le_socket'
.libs/swoole_client_coro.o: In function `zim_swoole_client_coro_getSocket':
/tmp/pear/temp/swoole/swoole_client_coro.cc:1097: undefined reference to `php_sockets_le_socket'
/tmp/pear/temp/swoole/swoole_client_coro.cc:1097:(.text+0x154): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `php_sockets_le_socket'
.libs/swoole_event.o: In function `swoole_convert_to_fd':
/tmp/pear/temp/swoole/swoole_event.c:331: undefined reference to `php_sockets_le_socket'
/tmp/pear/temp/swoole/swoole_event.c:331:(.text+0x8f1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `php_sockets_le_socket'
.libs/swoole_event.o: In function `swoole_convert_to_fd_ex':
/tmp/pear/temp/swoole/swoole_event.c:398: undefined reference to `php_sockets_le_socket'
/tmp/pear/temp/swoole/swoole_event.c:398:(.text+0xaa1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `php_sockets_le_socket'
.libs/swoole_event.o: In function `swoole_php_socket_free':
/tmp/pear/temp/swoole/swoole_event.c:450: undefined reference to `php_sockets_le_socket'
/tmp/pear/temp/swoole/swoole_event.c:450:(.text+0xc19): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `php_sockets_le_socket'
.libs/swoole_server.o:/tmp/pear/temp/swoole/swoole_server.cc:3915: more undefined references to `php_sockets_le_socket' follow
.libs/swoole_server.o: In function `zim_swoole_server_getSocket':
/tmp/pear/temp/swoole/swoole_server.cc:3915:(.text+0xf40): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `php_sockets_le_socket'
.libs/swoole_server_port.o: In function `zim_swoole_server_port_getSocket':
/tmp/pear/temp/swoole/swoole_server_port.cc:656:(.text+0x46): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `php_sockets_le_socket'
.libs/swoole_socket_coro.o: In function `zim_swoole_socket_coro_getSocket':
/tmp/pear/temp/swoole/swoole_socket_coro.cc:1534:(.text+0x2b0): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `php_sockets_le_socket'
collect2: error: ld returned 1 exit status
make: *** [Makefile:454：swoole.la] 错误 1
ERROR: `make' failed

7.2.* 和 7.3.* 的版本都有测试,通不过,php也用的最新版本还是不行
$ php -v
PHP 7.3.4 (cli) (built: Apr 29 2019 07:40:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.4, Copyright (c) 1999-2018, by Zend Technologies

2. What did you expect to see?
能正常编译出swoole的扩展

3. What did you see instead?
编译过程中出错,退出

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.3.4

5. What is your machine environment used (including version of kernel & php & gcc) ?
win7专业版  
Cgywin64位最新版本 
PHP 7.3.4
gcc 7.4.0-1

**Comment by firedtoad** [comment]
你换32 位 Cgywin试一下

orzero <notifications@github.com> 于2019年5月27日周一 下午3:53写道：

**Comment by twose** [comment]
不要用32位
你这里缺少PHP的sockets扩展

**Comment by twose** [comment]
cygwin可以直接用我们提供的二进制包, 无需编译:
https://www.swoole.com/page/download

**Comment by xami** [comment]
@twose 好,我试试用你们给的编译包能不能用

但我用的php本身是包含sockets扩展的呢,这种也没法自己编译吗
$ php -m
[PHP Modules]
bz2
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
imap
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pgsql
Phar
readline
Reflection
session
sockets
SPL
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by xami** [comment]
没法直接用。

我用的php的扩展都是放置到 lib\php\20180731 这个目录的,官方提供的版本却是放到 lib\php\20160303\ 目录下面的，貌似用的编译器的版本不同，强行复制这个文件有，增加/etc/php.d/swoole.ini配置,引入也会报错：

 php -m
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.dll' (tried: /usr/lib/php/20180731/swoole.dll (No such file or directory), /usr/lib/php/20180731/swoole.dll.dll (No such file or directory)) in Unknown on line 0

**Comment by xami** [comment]
折腾了一天,自己下载源代码,通过下面命令编译成功,不过是去掉--enable-sockets=yes的情况下,可能socket服务会受影响,加上这个参数还是会失败

phpize
 ./configure --with-php-config=/usr/bin/php-config  --enable-openssl=yes --enable-http2=yes --enable-mysqlnd=yes
make
make install

**Comment by twose** [comment]
官方提供的二进制是直接可运行的PHP

出现编译问题是因为你自己依赖没有调整好
