### ISSUE TITLE
What is the reason to deprecate `Lock` in swoole 4.4 ?

### ISSUE THREAD

**Issue by abbychau** [swoole/swoole-src#2601]
I found 废弃Lock模块，废弃原因：在协程模式下加锁可能存在问题，可使用chan实现协程版本的锁.

What is the concrete reason? or what are the error instances?

**Comment by matyhtf** [comment]
Bad Case:
-----
```php
<?php
$lock = new Swoole\Lock();
$c = 2;

while ($c--) {
    go(function () use ($lock) {
        $lock->lock();
        Co::sleep(1);
        $lock->unlock();
    });
}
```

**Comment by matyhtf** [comment]
This will cause a deadlock

**Comment by abbychau** [comment]
I think the problem is because of `Co::sleep`, Locks are across the threads, a thread `sleep` could be more suitable.

after reading

```c
static void sleep_timeout(swTimer *timer, swTimer_node *tnode)
{
    ((Coroutine *) tnode->data)->resume();
}

int System::sleep(double sec)
{
    Coroutine* co = Coroutine::get_current_safe();
    if (swTimer_add(&SwooleG.timer, (long) (sec * 1000), 0, co, sleep_timeout) == NULL)
    {
        return -1;
    }
    co->yield();
    return 0;
}
```

the yield may not be resumed after the next coroutine comes in.

**Comment by huanghantao** [comment]
@abbychau 死锁的原因是Swoole的协程是在同一个线程里面跑，也就是说，这个线程把自己给锁住了。如果未来Swoole的协程可以在不同的线程里面跑，应该是不会死锁的。

**Comment by huanghantao** [comment]
@abbychau Swoole以后应该是会提供协程锁

**Comment by abbychau** [comment]
> @abbychau 死锁的原因是Swoole的协程是在同一个线程里面跑，也就是说，这个线程把自己给锁住了。如果未来Swoole的协程可以在不同的线程里面跑，应该是不会死锁的。

I think so too.

**Comment by abbychau** [comment]
> @abbychau Swoole以后应该是会提供协程锁

This will be very cool. 😎 kotlinx implemented it.
