### ISSUE TITLE
给 reactor 进程发送 kill 信号 reactor 进程自身不会退出

### ISSUE THREAD

**Issue by designinlife** [swoole/swoole-src#2604]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
kill 掉 reactor 进程时，发现 manager + worker 进程全部正常退出了，但 reactor 进程自身未退出!

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.4
Built => May 29 2019 01:23:47
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1b  26 Feb 2019
http2 => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 33554432 => 33554432

5. What is your machine environment used (including version of kernel & php & gcc) ?
OS: Alpine 3.9.4 (Docker)
Kernel: 4.4.177-1.el7.elrepo.x86_64
PHP: 7.3.5 & 7.3.6
GCC: 8.3

**Comment by twose** [comment]
代码, 操作步骤

**Comment by designinlife** [comment]
> 代码, 操作步骤

没具体测试代码，我们生产环境发现这个问题的！

**Comment by designinlife** [comment]
补充一下：Swoole 4.2.13 没这个问题

**Comment by designinlife** [comment]
与 #2406 一样的情况

**Comment by matyhtf** [comment]
无法重现你的问题。

**Comment by designinlife** [comment]
@matyhtf 是的，挂了UserProcess

**Comment by matyhtf** [comment]
你的 UserProcess 需要监听`SIGTERM`，在收到信号时应当退出。

**Comment by designinlife** [comment]
strace 跟踪了下关闭的过程

**Comment by designinlife** [comment]
找到问题根源了，gRPC扩展的问题导致的，我禁用掉 gRPC 就没问题了。
很奇怪，我只是载入了 gRPC 扩展，业务代码中没任何地方使用它，却有这个影响！

**Comment by twose** [comment]
是的，会和grpc冲突，以前遇到过，没找到原因，仅加载也会产生这个问题

**Comment by pantaovay** [comment]
> 是的，会和grpc冲突，以前遇到过，没找到原因，仅加载也会产生这个问题

禁用GRPC扩展，没有问题了

目前有定位问题吗？

**Comment by ninjacn** [comment]
swoole和grpc不能共存啊，这问题最好解决一下呢
