### ISSUE TITLE
Swoole 4.3.x的HttpServer中，无法访问软连接文件夹下的静态文件

### ISSUE THREAD

**Issue by fly-studio** [swoole/swoole-src#2608]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

启动HttpServer服务的时候使用如下参数
```
[
"document_root" => '/www/'
"enable_static_handler" => true,
]
```
比如制作软连接`ln -s /var/log/ /www/log`

在CentOS上使用 `ll /www/log/nginx/access.log` 可以正常访问到那个文件

然后使用`pecl instal swoole`安装`swoole 4.3.3`
但是启动http server之后 无法访问`http://xxxx/log/nginx/access.log`  但是：**非软连接下的静态文件**可以正常访问

软连接的文件URL被抛到了onRequest方法中

2. What did you expect to see?

Swoole 2.x可以正常访问到软连接下的静态文件
但是升级4.3.4之后，无法访问软连接下的静态文件

3. What did you see instead?

`404`

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.4
Built => May 31 2019 14:10:01
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.0h  27 Mar 2018
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ?

```
CentOS 7.x
PHP 7.1
gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)

```

**Comment by twose** [comment]
出于安全性考虑最新的几个版本中会将访问路径转换为真实路径, 导致软链接无效
