### ISSUE TITLE
代码中使用clone关键字时报bug警告

### ISSUE THREAD

**Issue by jansen-s** [swoole/swoole-src#2609]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
自建http server，在start前，读取敏感词列表，创建AC自动机实例，创建敏感词状态树，将AC自动机实例做为http server的属性存起来，在onrequest回调时，使用use关键字引用http server实例变量，以便request时可以访问AC自动机实例。但因AC自动机实例执行一个请求后，内部数据会发生变化，所以使用clone关键字复制http server实例

[code.zip](https://github.com/swoole/swoole-src/files/3245726/code.zip)

2. What did you expect to see?
期望能正常复制实例变量

3. What did you see instead?
报bug警告

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.3
Built => May 10 2019 16:40:35
coroutine => enabled
kqueue => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (including version of kernel & php & gcc) ?
系统：
Darwin JansenMacBook 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

PHP版本：
PHP 7.1.23 (cli) (built: Feb 22 2019 22:19:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

GCC：
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin14.4.0/5.1.0/lto-wrapper
目标：x86_64-apple-darwin14.4.0
配置为：../gcc-5.1.0/configure --enable-languages=c++,fortran
线程模型：posix
gcc 版本 5.1.0 (GCC)

**Comment by matyhtf** [comment]
```shell
Fatal error: Uncaught Error: Trying to clone an uncloneable object of class Swoole\Http\Server in /home/htf/下载/code/dict.php:49
Stack trace:
#0 [internal function]: {closure}(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#1 /home/htf/下载/code/dict.php(98): Swoole\Server->start()
#2 {main}
  thrown in /home/htf/下载/code/dict.php on line 49
```
请勿 clone 此对象。新版本已禁止
