### ISSUE TITLE
swoole_http_server kill主进程问题

### ISSUE THREAD

**Issue by zhanglei** [swoole/swoole-src#261]
swoole版本:1.7.16-stable
php版本:5.3.10
linux系统:Ubuntu 3.2.0-23-generic

测试代码:examples/http/server.php
测试过程中使用swoole_http_server的SWOOLE_BASE模式
worker_num设置为2

启动server.php
![image](https://cloud.githubusercontent.com/assets/241508/7745446/c0f62398-ffdd-11e4-8b3a-89cef103f9c6.png)

相关操作:
![image](https://cloud.githubusercontent.com/assets/241508/7745534/6fced4aa-ffde-11e4-8037-767397182365.png)

执行kill主进程后子进程没有退出

在mac os下
SWOOLE_BASE模块也会有问题，会直接core掉
使用默认模式，执行kill -15 主进程id后,manager,worker,task进程都会退出，但master进程没有退出

**Comment by matyhtf** [comment]
此问题已经在1.7.17分支中得到了解决。
