### ISSUE TITLE
How to implement ini_set()

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#2615]
I have got to set this
     ini_set('session.cookie_httponly',1);

but I dont know if this is compatible with swoole registered cookie like
     $res->cookie()

**Comment by twose** [comment]
This is a configuration item in FPM

in Swoole:
```php
function Http\Response->cookie(string $key, string $value = '', int $expire = 0 , string $path = '/', string $domain  = '', bool $secure = false , bool $httponly = false);
```

There is no global configuration item

**Comment by jobs-git** [comment]
this will do, thanks!
