### ISSUE TITLE
4.3.0 Process exit

### ISSUE THREAD

**Issue by lackoxygen** [swoole/swoole-src#2616]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
我之前用的是4.2.13没这个问题，碰到过一次无法处理新请求，后来尝试升级，升级4.3.0后运行一段时候主进程自动退出了
（pecl）下载的
2. What did you expect to see?

正常运行，现在我降级一个版本4.2.13恢复正常

3. What did you see instead?

自动退出

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.3.0

5. What is your machine environment used (including version of kernel & php & gcc) ?
php7.1
gcc version 4.8.5 20150623
centos 7.6.1810

**Comment by twose** [comment]
@lackoxygen 请升级到v4.3.4而不是v4.3.0

**Comment by lackoxygen** [comment]
> @lackoxygen请升级到v4.3.4而不是V4.3.0

好的 我升级4.3.4试试
