### ISSUE TITLE
大神们，一键协程化有没有支持sqlserver的计划？

### ISSUE THREAD

**Issue by sendee** [swoole/swoole-src#2619]
因工作需要， 想用协程框架访问sqlserver 2014，
目前用的是 unixODBC+microsoft ODBC 17 for sql server驱动 + microsoft pdo_sqlsrv
当然我知道还可以用 unixODBC+ freeTDS + pdo_dblib
但测试起来还是微软官方的最新版较快一点

那么问题来了， 一键协程化貌似只支持 mysql pg等流行的linux下的数据库的驱动， 何时可以支持微软的官方sqlserver ODBC驱动呢？不然我似乎只能在连sqlserver数据库时，使用同步模式而非异步模式了？

**Comment by sendee** [comment]
作为回答我问题的报答，分享一下刚亲身安装过的linux下php 7 通过两种PDO驱动访问windows服务器上运行的sql server 2014的办法， 两种都亲测通过：
==========================================
即php下有推荐有两种办法来访问sqlserver
一 :
unixODBC驱动管理器
+ 真正的驱动freeTDS(当前最新版1.1.6)
+ 安装php扩展pdo_dblib

(1) 装pdo_dblib扩展
编译pdo_dblib扩展参数为:
./configure --with-php-config=/usr/local/php73/bin/php-config --with-pdo-dblib=/usr/local/freetds/

(2) 装freeTDS
freeTDS是linux平台下根据TDS协议实现的sqlserver驱动,可以做为单独的组件, 不一定非要配合unixODBC驱动管理器才能使用,
若指定with-unixodbc=/usr(此路径取决于系统中unixODBC的lib安装位置)参数会
到指定目录寻找unixODBC的相关库,头文件,以生成tds的ODBC驱动库文件(libtdsodbc.so)
总之,如果 unixODBC是源码安装, 则一般需要指定--with-unixodbc=/path/to
但是如果 unixODBC是rpm安装, 则不需要该选项,会自行在默认路径下搜索
最新的编译参数类似这样(首先确保unixODBC已安装):
./configure --prefix=/usr/local/freetds --with-tdsver=7.4 --enable-msdblib
make && make install

#向unixODBC 登记 FreeTDS 驱动,编辑此文件并添加
vim /etc/odbcinst.ini

# Driver from FreeTDS package
[FREETDS]
Description    = ODBC of FreeTDS for MS SQL 2014
Driver             = /usr/local/freetds/lib/libtdsodbc.so
FileUsage       = 1




二: 从微软官网下载安装:
unixODBC驱动管理器
+ "Microsoft ODBC Driver 17 for SQL Server"
+ 安装php扩展(sqlsrv,pdo_sqlsrv)(这两个扩展都属于"Microsoft PHP Drivers 5.6 for SQL Server")
说明: SQLSRV扩展提供了一个过程接口，而PDO_SQLSRV扩展实现了PDO，用于访问所有版本的SQL Server 2008 R2及更高版本
（包括Azure SQL DB）中的数据。这些驱动程序依赖于SQL Server的Microsoft ODBC驱动程序来处理与SQL Server的低级通信。


(1) 装sqlsrv与pdo_sqlsrv
参考: https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-linux-2017

即使您已升级GCC，PECL中的问题也可能妨碍正确安装最新版本的驱动程序。要安装，请下载软件包并手动编译（pdo_sqlsrv类似步骤）
pecl download sqlsrv
tar xvzf sqlsrv-5.6.1.tgz
cd sqlsrv-5.6.1/
phpize
./configure --with-php-config=/usr/local/php73/bin/php-config
make
sudo make install
或者去官网项目下载源码编译: https://github.com/Microsoft/msphpsql/releases/tag/v5.6.0

(2) 装Microsoft ODBC Driver 17:
步骤指南: 
  https://docs.microsoft.com/zh-cn/sql/connect/odbc/linux-mac/installing-the-driver-manager?view=sql-server-2017
  https://docs.microsoft.com/zh-cn/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017
从以上指南中可知:
较新的13、13.1 和 17版本可通过以下方法安装, 较旧的11版本,则需要先删除系统中的unixODBC-2.3.1+版本, 重新下载unixODBC-2.3.0版源码编译安装(步骤见指南)

#RedHat Enterprise Server 7
curl https://packages.microsoft.com/config/rhel/7/prod.repo > /etc/yum.repos.d/mssql-release.repo

#to avoid conflicts,ACCEPT_EULA指代是否接受最终用户许可协议的环境变量
sudo yum remove unixODBC-utf16 unixODBC-utf16-devel
sudo ACCEPT_EULA=Y yum install msodbcsql17
#注意:安装后, 会自动在unixODBC驱动程序管理器配置文件/etc/odbcinst.ini中添加一项

# optional: for bcp and sqlcmd
sudo ACCEPT_EULA=Y yum install mssql-tools
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc

# optional: for unixODBC development headers
sudo yum install unixODBC-devel

--------------------------------------
编译安装好freetds后, 测试连接的命令语法
/usr/local/freetds/bin/tsql -H 192.168.0.110 -p 1433 -U sa -P thisispassword

安装好Microsoft ODBC Driver 17 for sql server后,测试连接的命令:
/opt/mssql-tools/bin/sqlcmd -S192.168.0.110 -Usa -Pxxxxxx
sqlcmd -S your_hostname -U your_login -P your_pass -Q "SELECT @@VERSION"

=========================================================
上测试代码 ， 两种访问方式的比对：
见附件

```
<?php

echo '<html><pre>';

//var_export(test_2());
echo '<br>';
var_export(test_1());

echo '</html></pre>';

function test_1() {
    $serverName = "192.168.0.110";
    $db = 'DB1';
    $user = 'sa';
    $pws = 'PWS1';

    try
    {
        $time1 = microtime();

        $conn = new PDO( "sqlsrv:server={$serverName};Database={$db}", "{$user}", "{$pws}");
        $conn->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

        $sql = "select * from [TABLE1]";

        $stmt = $conn->prepare($sql);
        
        $stmt->execute();
        
        $users = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $time2 = microtime();
        echo $time2 - $time1;

        $conn = null;
        return $users;
    }
    catch(Exception $e)
    {
        return $e->getMessage();
    }
}


function test_2() {
    $serverName = "192.168.0.110";
    $db = 'DB2';
    $user = 'sa';
    $pws = 'PWS1';

    try
    {
        $time1 = microtime();

        $conn = new PDO("dblib:host={$serverName};dbname={$db}","{$user}","{$pws}");
        $conn->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

        $sql = "select * from [TABLE2]";

        $stmt = $conn->prepare($sql);
        $stmt->execute();
        $users = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $time2 = microtime();

        echo $time2 - $time1;

        $res = null;
        $conn = null;
        return $users;
    }
    catch(Exception $e)
    {
        return $e->getMessage();
    }
}
```

**Comment by twose** [comment]
能否一键协程化取决于PHP扩展是否是使用`php_stream`实现的，如果不是，就无法支持

**Comment by matyhtf** [comment]
暂时无法支持。

**Comment by xiangdong2** [comment]
道路不同，无法支持




------------------ 原始邮件 ------------------
发件人: "韩天峰-Rango"<notifications@github.com>;
发送时间: 2019年6月11日(星期二) 下午2:58
收件人: "swoole/swoole-src"<swoole-src@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [swoole/swoole-src] 大神们，一键协程化有没有支持sqlserver的计划？ (#2619)




暂时无法支持。
