### ISSUE TITLE
Fatal error: swoole_server::tick(): cannot use async-io in task process?  请教下～

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#262]
Fatal error: swoole_server::tick(): cannot use async-io in task process. in /libs/Swoole/Network/protocol.php on line 172

请教下：
1、目前是woker启动的时候注入了tick 定时interval回调;
根据上面提示，task进程是不允许tick的，
那请问什么时机来触发这个比较好呢？能在启动时只注入woker进程中么？ 谢谢～

2、另外，关于onTimer回调，目前函数原型是：
<pre>
php_swoole_onTimerInterval(swTimer *timer, swTimer_node *event)
</pre>
event里面有void* data param数据，后续版本是否会加入回调时升级支持param回调呢？谢谢！
<pre>
void onTimer(resource $server, int $interval);
升级成：
void onTimer(resource $server, int $interval, mixed $params);
</pre>

非常感谢～

**Comment by smalleyes** [comment]
我这用到两种，一种主要是用在onworkerstart中的event worker，来代替timer,timer会在今后的某个版本取消掉，一种用在onreceive中来代替after的功能
