### ISSUE TITLE
Disable coroutines doesn't work as documented

### ISSUE THREAD

**Issue by nick-zh** [swoole/swoole-src#2621]
Is there a way to disable coroutines? The doc states: https://www.swoole.co.uk/coroutine
But when i do a `./configure --disable-coroutine` i get:
```
configure: WARNING: unrecognized options: --disable-coroutine
```
I sort of hijacked #1681 but i think this is a separate issue
Thanks in advance for the feedback :heart:

**Comment by twose** [comment]
add `swoole.enable_coroutine=Off` to your php.ini, the English doc is outdate.

**Comment by nick-zh** [comment]
@twose thx a lot :+1: , somehow it did not take my ini, but i was able with:
```
 $http->set([
    'enable_coroutine' => false,
]);
```
