### ISSUE TITLE
求放个支持20180731 API的windows扩展

### ISSUE THREAD

**Issue by cevin** [swoole/swoole-src#2622]
官方现在提供的在7.3.x不能用 😢

**Comment by matyhtf** [comment]
使用 WSL

**Comment by ShuiPingYang** [comment]
@cevin 你好，官方提供的那个是Cygwin吗？还是说是dll,如果是dll，能否发我一下？

**Comment by cevin** [comment]
我是docker使用的

ShuiPingYang ***@***.***> 于2022年5月7日周六 16:29写道：

**Comment by cevin** [comment]
> @cevin 你好，官方提供的那个是Cygwin吗？还是说是dll,如果是dll，能否发我一下？

我现在改docker了
