### ISSUE TITLE
用最新的4.3.4版本，没有注册onClose事件，出现大量的close_wait连接

### ISSUE THREAD

**Issue by kirachen1991** [swoole/swoole-src#2627]
用最新的4.3.4版本，没有注册onClose事件，出现大量的close_wait连接

持续运行一段时间之后，就会出现大量的close_wait的连接，然后就访问不了了

**Comment by matyhtf** [comment]
无法重现你的问题，对外网保留端口的服务器，请开启心跳检测设置。
