### ISSUE TITLE
Implement DPDK

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#2633]
With DPDK network performance can increase by about 3x.

https://www.dpdk.org/

**Comment by matyhtf** [comment]
This is a difficult job

**Comment by need-sleep** [comment]
3x over what? Looking briefly at dpdk it looks to do much of what swoole is already good at. Fine tuned management of memory, threads, processes etc, optimised event handling and optimised socket API. Hardware acceleration for  encryption and hashing comes down to how you have openssl configured I believe.

**Comment by jobs-git** [comment]
@matyhtf 
These are some TCP stack that I guess would lighten the dpdk implementation
https://openfastpath.org/
http://www.f-stack.org/

@need-sleep 
network performance, it got its own high performance driver that I dont think swoole can take advantage of yet.

**Comment by matyhtf** [comment]
Not in Roadmap

**Comment by jobs-git** [comment]
@matyhtf then please add in roadmap?
