### ISSUE TITLE
number of maximum connection we can use with swoole?

### ISSUE THREAD

**Issue by NR-Developer** [swoole/swoole-src#2638]
hello
i want to know how many is the maximum connection per second that swoole can support
we want use this framework for real-time game server and it is very important to know max number support connection/second for swoole framework.
thank you

**Comment by matyhtf** [comment]
It depends on the value of your system `ulimit -n` and your settings. The maximum limit is 1 million.

```shell
ulimit -n 100000
```

```php
$server = new Swoole\Server;

$server->set(["max_connection" => 100000]);
```

**Comment by NR-Developer** [comment]
thank you

**Comment by NR-Developer** [comment]
but we do not want to set limit for maximum connection
we want to know how many connection per second swoole can support

**Comment by need-sleep** [comment]
Not sure if I'm the best person to answer this, but Swoole's socket API only creates a thin layer over the actual system socket, so listening for and accepting new connections has little overhead. The accept call is a non-blocking coroutine but is still serialized, i.e. can only handle one accept call at a time per listening socket. You can have more than one listing socket accepting connections if needed which will then come down to how fast the host system/hardware can handle new connections. Some Swoole services in China handle hundreds of thousands of events per second from multiple millions of concurrent connections. I don't know the specifics, but I would imagine such systems handle a huge amount of client turn over as people come and go.

**Comment by NR-Developer** [comment]
I am thankful with your guidance 👍 
Good luck :)

**Comment by ClosetMonkey** [comment]
Also note that  `$socket>setOption(SOL_SOCKET, SO_REUSEPORT, true);` is needed to allow multiple sockets to listen on the same port. Using process manager, can effectively create many processes accepting connections on the same address:port.
