### ISSUE TITLE
How to assign custom data to each WebSocket connection

### ISSUE THREAD

**Issue by plashenkov** [swoole/swoole-src#2642]
Hi!

How is it possible to differ WebSocket connections from each other? For example, users connect to a WebSocket server (from a webbrowser), they provide their access token via the GET param.

I would like to assign this token to each WebSocket connection to be able to send the data only for those users who are eligible to this data (instead of sending the data to everyone).

```php
$server = new Server('0.0.0.0', 3002, SWOOLE_BASE);

$server->on('open', function (Server $server, Request $request) {
    $token = $request->get['token'] ?? null;
    if (someCheckIfTokenValid($token)) {
        // how to link connection and token? <---------------
    } else {
        $server->close($request->fd);
    }
});
```

Somewhere I want to send data only to a connection with specific token:
```php
$targetToken = '...some-token';
$someData = 'some-data'

foreach ($server->connections as $fd) {
    if ($server->isEstablished($fd) && /* connection is linked with $targetToken */) {
        $server->push($fd, $someData);
    }
}
```

Thanks!

**Comment by matyhtf** [comment]
You can save information using global variable data, using fd as the key

```php
$server = new Server('0.0.0.0', 3002, SWOOLE_BASE);

$tokens = [];

$server->on('open', function (Server $server, Request $request) {
    $token = $request->get['token'] ?? null;
    if (someCheckIfTokenValid($token)) {
         global $tokens;
         $tokens[$request->fd] = $token;
        // how to link connection and token? <---------------
    } else {
        $server->close($request->fd);
    }
});


$targetToken = '...some-token';
$someData = 'some-data'

foreach ($server->connections as $fd) {
    if ($server->isEstablished($fd) && /* connection is linked with $targetToken */) {
        global $tokens;
       $token =  $tokens[$fd];
        $server->push($fd, $someData);
    }
}
```

**Comment by plashenkov** [comment]
Aha! Thank you! It looks like I've done it right :)

**Comment by plashenkov** [comment]
If several workers (worker_num > 1) are used, is this method suitable? How do they share this global array? They are async, right?

**Comment by ClosetMonkey** [comment]
I don't see why this wouldn't be possible. It's technically similar to the concept of rooms if I'm understanding correctly. For example, streaming data to a list of clients based on a token ID (such as broadcasting a video?) is no different than sending messages to a group of chat recipients based on a room ID. Worker Processes won't be able to share an array as described (PHP arrays can be copied across threads but not shared) however a Swoole Table can be used to shared needed data regarding other clients. That still leaves an issue that child processes can't share TCP sockets with their siblings, but if the parent process handles IO to other clients this shouldn't be a problem.

**Comment by matyhtf** [comment]
If several workers (worker_num > 1) are used, You can use redis, Swoole\Table, MySQL or a file to save session information.
