### ISSUE TITLE
Database Management Tool in swoole?

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#2645]
Where can I find a database management system like phpmyadmin & adminer for swoole?

**Comment by deminy** [comment]
People can create one but I don't think it's necessary. You can easily launch a [phpMyAdmin](https://hub.docker.com/r/phpmyadmin/phpmyadmin) or [Adminer](https://hub.docker.com/_/adminer) Docker instance to manage MySQL databases without writing any PHP code. These management systems usually have very limited access, and most time users don't care that much about the response time (comparing to production sites/APIs).

Creating a reliable management system takes years of efforts. phpMyAdmin has been there for 20+ years, and it's very powerful and reliable. I don't see a good reason to invest time and effort to create a Swoole version of that.

**Comment by jobs-git** [comment]
Yes, than can be used but that requires you to launching php-fpm.

**Comment by deminy** [comment]
You don't need to launch a separate php-fpm process. The images have php-fpm and/or web server built in already.

**Comment by jobs-git** [comment]
yhea, just tested it and I can access it, I thought I need another back end server just for adminer. Thanks for that!
