### ISSUE TITLE
Mistake in swoole/php-amqplib

### ISSUE THREAD

**Issue by plashenkov** [swoole/swoole-src#2646]
Sorry that I post about it here, but issues are closed in https://github.com/swoole/php-amqplib repository.

Please take a look here:
https://github.com/swoole/php-amqplib/blob/master/PhpAmqpLib/Wire/IO/SwooleIO.php#L72
(constructor params)

and here:
https://github.com/swoole/php-amqplib/blob/master/PhpAmqpLib/Connection/AMQPSwooleConnection.php#L38,
where you use the constructor.

If I am not mistaken, you pass wrong parameters to the constructor.

**Comment by deminy** [comment]
Thanks @plashenkov for reporting that. We will get it addressed.

Also, I have enabled the `issues` feature under repository `php-amqplib`. Would you mind reporting the issue [over there](https://github.com/swoole/php-amqplib/issues) and becoming the first issue reporter of the repository?

**Comment by doubaokun** [comment]
@plashenkov Could you please submit a pull request to `swoole/php-amqplib` ? Btw, issues is enabled at `swoole/php-amqplib` repo. Close this thread for now.
