### ISSUE TITLE
请问对mongodb的协程自动切换支持计划如何呢？

### ISSUE THREAD

**Issue by hncg** [swoole/swoole-src#2647]
看官方文档里面有一些介绍:
```
此特性为实验性质，可能存在未知问题，请勿使用于生产环境。实际项目中可使用 Task 进程的特性实现协程 MongoDB 组件。
```
不知道是否有计划将mongo的io操作时候的协程切换,加到runtime里面去呢?

一直很喜欢swoole和mongo，mongo不能自动切换的话，总感觉少了点什么~

**Comment by matyhtf** [comment]
使用 Task 进程同步阻塞模式实现。
