### ISSUE TITLE
server->stats中tasking_num溢出

### ISSUE THREAD

**Issue by wssccc** [swoole/swoole-src#265]
监测发现
tasking_num         	4294966496

目测32位整数溢出

**Comment by wssccc** [comment]
ubuntu 14.04  64位，swoole 1.7.16

**Comment by smalleyes** [comment]
你生产者生产的数据远远大于消费者消费的数据了，建议多开些task进程

**Comment by wssccc** [comment]
start_time              1432541374
connection_num          0
accept_count            1
close_count             1
tasking_num             4294967294
request_count           1
worker_request_count    1
task_process_num        55

接受一次请求后

**Comment by wssccc** [comment]
这是在压力不是很大的时候测的，不像是task worker数量配置的问题。

**Comment by matyhtf** [comment]
回调函数中是否抛出了异常呢？

**Comment by wssccc** [comment]
没有异常，只是一个简单的echo server
