### ISSUE TITLE
*** Error in `php': munmap_chunk(): invalid pointer: 0x00007f9871001440 ***

### ISSUE THREAD

**Issue by 1007847538** [swoole/swoole-src#2650]
======= Backtrace: =========
/lib64/libc.so.6(+0x7f5d4)[0x7f9871c6f5d4]
php(zend_hash_destroy+0x1cd)[0x88f0bd]
php(php_request_shutdown+0x2aa)[0x81ceda]
php[0x92563b]
php[0x44b06f]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f9871c123d5]
php[0x44b0f4]
======= Memory map: ========
00400000-00c5d000 r-xp 00000000 fd:01 2104734                            /www/server/php/72/bin/php
00e5d000-00f19000 r--p 0085d000 fd:01 2104734                            /www/server/php/72/bin/php
00f19000-00f48000 rw-p 00919000 fd:01 2104734                            /www/server/php/72/bin/php
00f48000-00f6e000 rw-p 00000000 00:00 0 
01875000-01b18000 rw-p 00000000 00:00 0                                  [heap]
7f986a4ed000-7f986a6ee000 rw-s 00000000 00:04 556388                     /dev/zero (deleted)
7f986a6ee000-7f986a843000 r-xp 00000000 fd:01 2110215                    /www/server/php/72/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
7f986a843000-7f986aa42000 ---p 00155000 fd:01 2110215                    /www/server/php/72/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
7f986aa42000-7f986aa50000 r--p 00154000 fd:01 2110215                    /www/server/php/72/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
7f986aa50000-7f986aa56000 rw-p 00162000 fd:01 2110215                    /www/server/php/72/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
7f986aa56000-7f986aad6000 rw-p 00000000 00:00 0 
7f986aad6000-7f9871000000 r--p 00000000 fd:01 669563                     /usr/lib/locale/locale-archive
7f9871000000-7f9871200000 rw-p 00000000 00:00 0 
7f987139b000-7f98713aa000 r-xp 00000000 fd:01 659665                     /usr/lib64/libbz2.so.1.0.6
7f98713aa000-7f98715a9000 ---p 0000f000 fd:01 659665                     /usr/lib64/libbz2.so.1.0.6
7f98715a9000-7f98715aa000 r--p 0000e000 fd:01 659665                     /usr/lib64/libbz2.so.1.0.6
7f98715aa000-7f98715ab000 rw-p 0000f000 fd:01 659665                     /usr/lib64/libbz2.so.1.0.6
7f98715ab000-7f98715d0000 r-xp 00000000 fd:01 659661                     /usr/lib64/liblzma.so.5.2.2
7f98715d0000-7f98717cf000 ---p 00025000 fd:01 659661                     /usr/lib64/liblzma.so.5.2.2
7f98717cf000-7f98717d0000 r--p 00024000 fd:01 659661                     /usr/lib64/liblzma.so.5.2.2
7f98717d0000-7f98717d1000 rw-p 00025000 fd:01 659661                     /usr/lib64/liblzma.so.5.2.2
7f98717d1000-7f98717e8000 r-xp 00000000 fd:01 658682                     /usr/lib64/libpthread-2.17.so
7f98717e8000-7f98719e7000 ---p 00017000 fd:01 658682                     /usr/lib64/libpthread-2.17.so
7f98719e7000-7f98719e8000 r--p 00016000 fd:01 658682                     /usr/lib64/libpthread-2.17.so
7f98719e8000-7f98719e9000 rw-p 00017000 fd:01 658682                     /usr/lib64/libpthread-2.17.so
7f98719e9000-7f98719ed000 rw-p 00000000 00:00 0 
7f98719ed000-7f98719ef000 r-xp 00000000 fd:01 658380                     /usr/lib64/libfreebl3.so
7f98719ef000-7f9871bee000 ---p 00002000 fd:01 658380                     /usr/lib64/libfreebl3.so
7f9871bee000-7f9871bef000 r--p 00001000 fd:01 658380                     /usr/lib64/libfreebl3.so
7f9871bef000-7f9871bf0000 rw-p 00002000 fd:01 658380                     /usr/lib64/libfreebl3.so
7f9871bf0000-7f9871db2000 r-xp 00000000 fd:01 658656                     /usr/lib64/libc-2.17.so
7f9871db2000-7f9871fb2000 ---p 001c2000 fd:01 658656                     /usr/lib64/libc-2.17.so
7f9871fb2000-7f9871fb6000 r--p 001c2000 fd:01 658656                     /usr/lib64/libc-2.17.so
7f9871fb6000-7f9871fb8000 rw-p 001c6000 fd:01 658656                     /usr/lib64/libc-2.17.so
7f9871fb8000-7f9871fbd000 rw-p 00000000 00:00 0 
7f9871fbd000-7f9871fd2000 r-xp 00000000 fd:01 660466                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f9871fd2000-7f98721d1000 ---p 00015000 fd:01 660466                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f98721d1000-7f98721d2000 r--p 00014000 fd:01 660466                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f98721d2000-7f98721d3000 rw-p 00015000 fd:01 660466                     /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f98721d3000-7f98735a4000 r-xp 00000000 fd:01 673861                     /usr/lib64/libicudata.so.50.1.2
7f98735a4000-7f98737a3000 ---p 013d1000 fd:01 673861                     /usr/lib64/libicudata.so.50.1.2
7f98737a3000-7f98737a4000 r--p 013d0000 fd:01 673861                     /usr/lib64/libicudata.so.50.1.2
7f98737a4000-7f98737a5000 rw-p 013d1000 fd:01 673861                     /usr/lib64/libicudata.so.50.1.2
7f98737a5000-7f9873909000 r-xp 00000000 fd:01 673875                     /usr/lib64/libicuuc.so.50.1.2
7f9873909000-7f9873b09000 ---p 00164000 fd:01 673875                     /usr/lib64/libicuuc.so.50.1.2
7f9873b09000-7f9873b19000 r--p 00164000 fd:01 673875                     /usr/lib64/libicuuc.so.50.1.2
7f9873b19000-7f9873b1a000 rw-p 00174000 fd:01 673875                     /usr/lib64/libicuuc.so.50.1.2
7f9873b1a000-7f9873b1e000 rw-p 00000000 00:00 0 
7f9873b1e000-7f9873d0e000 r-xp 00000000 fd:01 673863                     /usr/lib64/libicui18n.so.50.1.2
7f9873d0e000-7f9873f0e000 ---p 001f0000 fd:01 673863                     /usr/lib64/libicui18n.so.50.1.2
7f9873f0e000-7f9873f1a000 r--p 001f0000 fd:01 673863                     /usr/lib64/libicui18n.so.50.1.2
7f9873f1a000-7f9873f1c000 rw-p 001fc000 fd:01 673863                     /usr/lib64/libicui18n.so.50.1.2
7f9873f1c000-7f9873f1d000 rw-p 00000000 00:00 0 
7f9873f1d000-7f9873f29000 r-xp 00000000 fd:01 673865                     /usr/lib64/libicuio.so.50.1.2
7f9873f29000-7f9874129000 ---p 0000c000 fd:01 673865                     /usr/lib64/libicuio.so.50.1.2
7f9874129000-7f987412a000 r--p 0000c000 fd:01 673865                     /usr/lib64/libicuio.so.50.1.2
7f987412a000-7f987412b000 rw-p 0000d000 fd:01 673865                     /usr/lib64/libicuio.so.50.1.2
7f987412b000-7f98741e2000 r-xp 00000000 fd:01 662479                     /usr/lib64/libfreetype.so.6.14.0
7f98741e2000-7f98743e2000 ---p 000b7000 fd:01 662479                     /usr/lib64/libfreetype.so.6.14.0
7f98743e2000-7f98743e9000 r--p 000b7000 fd:01 662479                     /usr/lib64/libfreetype.so.6.14.0
7f98743e9000-7f98743ea000 rw-p 000be000 fd:01 662479                     /usr/lib64/libfreetype.so.6.14.0
7f98743ea000-7f98743fa000 r-xp 00000000 fd:01 673918                     /usr/lib64/libcares.so.2.1.0
7f98743fa000-7f98745f9000 ---p 00010000 fd:01 673918                     /usr/lib64/libcares.so.2.1.0
7f98745f9000-7f98745fa000 r--p 0000f000 fd:01 673918                     /usr/lib64/libcares.so.2.1.0
7f98745fa000-7f98745fb000 rw-p 00010000 fd:01 673918                     /usr/lib64/libcares.so.2.1.0
7f98745fb000-7f987466c000 r-xp 00000000 fd:01 1710755                    /usr/local/curl/lib/libcurl.so.4.5.0Aborted

**Comment by matyhtf** [comment]
请升级至最新版本，按照下面的文档跟踪问题原因。

https://wiki.swoole.com/wiki/page/p-issue.html
