### ISSUE TITLE
Swoole\Server::bind(): uid can not be greater than 4294967295

### ISSUE THREAD

**Issue by crazePhper** [swoole/swoole-src#2651]
[warning] 2019-06-27 15:22:16 <9015> [message] Swoole\Server::bind(): uid can not be greater than 4294967295
uid能不能设置成 bigint类型。。。

**Comment by mabu233** [comment]
目前不能，最大只能是无符号32位

**Comment by matyhtf** [comment]
暂时不支持，你可以计算一下 crc32 的值
