### ISSUE TITLE
swoole客户端同步模式接收服务端数据不完整

### ISSUE THREAD

**Issue by 445271763** [swoole/swoole-src#2654]
这几天我碰到的swoole传输数据不完整的问题整理了一下，哪位大佬能帮忙看看？

1、swoole服务端返回50k数据

2、swoole客户端为同步模式时，不管有没有设置数据包最大长度和分隔符，也不管是http请求，还是命令行执行，都只能接收到不完整的19k数据

3、swoole客户端为异步模式时，如果有设置包最大长度和分隔符，则命令行执行可以接收到完整的50k数据，如果不设置包最大长度和分隔符则只能接受到40k的不完整的数据，而异步模式是不支持http请求的，所以这里不存在http请求的情况

4、目前客户端使用php的socket函数请求服务端一切正常，能返回服务端的50k完整数据，不需要配置数据包最大长度和分隔符可以正常通信传输

客户端代码：
![QQ图片20190629161910](https://user-images.githubusercontent.com/4819251/60381584-b5096680-9a89-11e9-95b8-d50636d06213.png)

服务端代码：
![QQ图片20190629161923](https://user-images.githubusercontent.com/4819251/60381586-be92ce80-9a89-11e9-8bcf-38deafffc72e.png)

环境信息：  

swoole:
```
root@1f6fc8c9361e:/var/www/html# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.4
Built => May 20 2019 06:21:42
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.0j  20 Nov 2018
http2 => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

```
docker php容器:
```
root@1f6fc8c9361e:/var/www/html# php -v
PHP 7.3.4 (cli) (built: Apr  6 2019 02:33:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies

```

dockers主机系统：CentOS Linux release 7.6.1810 (Core)

**Comment by matyhtf** [comment]
为什么要设置 `open_length_check => true` ？

**Comment by 445271763** [comment]
> 为什么要设置 `open_length_check => true` ？

```
'open_length_check' => true,
'open_eof_check' => true,
'package_eof' => "\r\n\r\n",
'open_eof_split' => true,
'package_max_length' => 5 * 1024 * 1024, 
```

这部分配置我是引用的别人demo里面的代码，我之前好像也尝试过关闭`open_length_check`， 是一样的情况，然后我刚刚又重新尝试了一下，还是不行，我也尝试了关闭`open_eof_check`和`open_eof_split`也同样不行。。我现在只能是用php的sockets扩展函数来做代替swoole客户端通信

**Comment by matyhtf** [comment]
这里都有单元测试的，没有重现你说的问题。你的客户端没有配置 `'open_eof_check' => true,`
