### ISSUE TITLE
swoole http server 1.7.16-stable bug

### ISSUE THREAD

**Issue by leo78** [swoole/swoole-src#266]
http server代码如下：

class Server
{
    private $serv;
    public function __construct() {
        $this->serv = new swoole_http_server("0.0.0.0", 9501);
        $this->serv->set(array(
            'worker_num' => 1,
            'daemonize' => false,
        ));
        $this->serv->on('start', array($this, 'onStart'));
        $this->serv->on('request', array($this, 'onRequest'));
        $this->serv->start();
    }
    public function onStart( $serv ) {
        // echo "Start\n";
    }
    public function onRequest( $request, $response ) {
    	$response->header("Content-Type", "text/html; charset=utf-8");
        print_r($request);
        $response->end("<h1>Hello World. #".rand(1000, 9999)."</h1>");
    }
}
$server = new Server();

访问：http://127.0.0.1:9501/?id=1001
打印$request对象后发现会出现两次数据，第一次数据有get对象，紧接着第二次数据就丢失了get对象，具体打印结果如下：
leodeMBP:test leo$ php server.php
swoole_http_request Object
(
    [header] => Array
        (
            [host] => 127.0.0.1:9501
            [connection] => keep-alive
            [cache-control] => max-age=0
            [accept] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
            [user-agent] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
            [accept-encoding] => gzip, deflate, sdch
            [accept-language] => zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4
        )

    [files] => Array
        (
        )

    [fd] => 1
    [server] => Array
        (
            [query_string] => id=1001
            [request_method] => GET
            [request_uri] => /
            [path_info] => /
            [request_time] => 1432543106
            [server_port] => 9501
            [remote_port] => 59141
            [remote_addr] => 127.0.0.1
            [server_protocol] => HTTP/1.1
            [server_software] => swoole-http-server
        )

    [get] => Array
        (
            [id] => 1001
        )

)
swoole_http_request Object
(
    [header] => Array
        (
            [host] => 127.0.0.1:9501
            [connection] => keep-alive
            [user-agent] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
            [accept] => */*
            [referer] => http://127.0.0.1:9501/?id=1001
            [accept-encoding] => gzip, deflate, sdch
            [accept-language] => zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4
        )

    [files] => Array
        (
        )

    [fd] => 1
    [server] => Array
        (
            [request_method] => GET
            [request_uri] => /favicon.ico
            [path_info] => /favicon.ico
            [request_time] => 1432543106
            [server_port] => 9501
            [remote_port] => 59141
            [remote_addr] => 127.0.0.1
            [server_protocol] => HTTP/1.1
            [server_software] => swoole-http-server
        )

)

如果我在server代码里使用$request->get['id']后就会出现php错误，但是能收到get数据，php bug如下：
server代码：
class Server
{
    private $serv;
    public function __construct() {
        $this->serv = new swoole_http_server("0.0.0.0", 9501);
        $this->serv->set(array(
            'worker_num' => 1,
            'daemonize' => false,
        ));
        $this->serv->on('start', array($this, 'onStart'));
        $this->serv->on('request', array($this, 'onRequest'));
        $this->serv->start();
    }
    public function onStart( $serv ) {
        // echo "Start\n";
    }
    public function onRequest( $request, $response ) {
    	$response->header("Content-Type", "text/html; charset=utf-8");
        // $arr = require('config.php');
        // print_r($request);
        $aaa = $request->get['id']."\n";
        // $html = $arr[$request->get['id']][1];
        $response->end("<h1>Hello World. #".rand(1000, 9999)."</h1>");
    }
}
$server = new Server();

php bug如下：
PHP Notice:  Undefined property: swoole_http_request::$get in /Users/leo/Desktop/workfile/test/server.php on line 23

Notice: Undefined property: swoole_http_request::$get in /Users/leo/Desktop/workfile/test/server.php on line 23

**Comment by smalleyes** [comment]
第二次应该是请求favicon.ico文件产生的请求

**Comment by matyhtf** [comment]
chrome会静默请求/favicon.ico

**Comment by leo78** [comment]
多谢大家

那么php的输出错误是什么情况呢？
php bug如下：
PHP Notice: Undefined property: swoole_http_request::$get in /Users/leo/Desktop/workfile/test/server.php on line 23

Notice: Undefined property: swoole_http_request::$get in /Users/leo/Desktop/workfile/test/server.php on line 23

**Comment by smalleyes** [comment]
当get提交参数为空的情况下不会生成swoole_http_request::$get属性，使用前需要先判断下swoole_http_request::$get是否存在，post也一样

**Comment by leo78** [comment]
@smalleyes 肯定存在啊，方式：http://127.0.0.1:9501/?id=1001，http server收到了id的值，但同时会输出错误
PHP Notice: Undefined property: swoole_http_request::$get in /Users/leo/Desktop/workfile/test/server.php on line 23

Notice: Undefined property: swoole_http_request::$get in /Users/leo/Desktop/workfile/test/server.php on line 23

**Comment by smalleyes** [comment]
对啊，我说的就是第二次请求ico文件的时候get提交参数为空

**Comment by leo78** [comment]
明白了，谢谢
