### ISSUE TITLE
grpc server do not return header grpc-status

### ISSUE THREAD

**Issue by ifcute** [swoole/swoole-src#2660]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

swoole grpc server code:
```php
'/test.HelloService/hello' => function (...$args) {
            [$server, $request, $response] = $args;
            /**@var $request_message \Test\HelloRequest */
            $request_message = Grpc\Parser::deserializeMessage([\Test\HelloRequest::class, null], $request->rawContent());
            if ($request_message) {
                $response_message = new \Test\HelloResponse();
                $response_message->setMsg('Hello ' . $request_message->getName());
                $response_message->setCode(1);
                $response->header('content-type', 'application/grpc');
                $response->header('trailer', 'grpc-status, grpc-message');
                $trailer = [
                    "grpc-status" => "0",
                    "grpc-message" => ""
                ];
                foreach ($trailer as $trailer_name => $trailer_value) {
                    $response->trailer($trailer_name, $trailer_value);
                }
                $response->end(Grpc\Parser::serializeMessage($response_message));
                return true;
            }
            return false;
        }
```
2. What did you expect to see?

this is golang server :
![image](https://user-images.githubusercontent.com/17122751/60510541-33703d80-9d02-11e9-86b9-ec2b7434f255.png)

3. What did you see instead?

this swoole server:
![image](https://user-images.githubusercontent.com/17122751/60510574-4a169480-9d02-11e9-8b22-0d5544ae63a4.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.5
Built => Jul  1 2019 11:02:38
coroutine => enabled
kqueue => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
brotli => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144
```

5. What is your machine environment used (including version of kernel & php & gcc) ?
php 7.2

**Comment by twose** [comment]
Duplicated with #2578, it has been fixed in v4.4.0

**Comment by cq-z** [comment]
curl http://localhost:50051/ -v --raw  
not get Trailer's values
[example](https://stackoverflow.com/questions/47341216/how-do-i-see-the-trailer-headers-with-curl)

php :
``  PHP 7.3.10 (cli) (built: Sep 26 2019 22:32:42) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.10, Copyright (c) 1999-2018, by Zend Technologies
 ``
swoole:
``
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.7
Built => Oct  3 2019 15:32:26
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
http2 => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.display_errors => On => On
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
swoole.use_shortname => On => On
``
system：
``  
Linux version 4.14.131-linuxkit (root@6d384074ad24) (gcc version 8.3.0 (Alpine 8.3.0)) #1 SMP Fri Jul 19 12:31:17 UTC 2019

``

**Comment by twose** [comment]
@cq-z 
it's HTTP2, not HTTP1.1

**Comment by cq-z** [comment]
clone  https://github.com/grpc/grpc-web
run  docker-compose up  envoy
exec "curl  -X POST  -HContent-Type:application/grpc-web+proto  http://localhost:8080/grpc.gateway.testing.EchoService/Echo -v  --raw"
grpc-status:0 has echo

```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /grpc.gateway.testing.EchoService/Echo HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type:application/grpc-web+proto
> 
< HTTP/1.1 200 OK
< grpc-accept-encoding: identity
< grpc-encoding: identity
< content-type: application/grpc-web+proto
< date: Thu, 10 Oct 2019 15:10:13 GMT
< x-envoy-upstream-service-time: 439
< server: envoy
< transfer-encoding: chunked
< 
7


df
??grpc-status:0
grpc-message:OK
user-agent:curl/7.54.0
accept:*/*
content-type:application/grpc
x-forwarded-proto:http
x-request-id:1ebb9807-3aba-4178-9d8d-ec8f54c1a4c5
te:trailers
grpc-accept-encoding:identity

0

* Connection #0 to host localhost left intact
```
