### ISSUE TITLE
【BUG】WARNING	swManager_check_exit_status: worker#0[pid=22659] abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by phper08** [swoole/swoole-src#2661]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```
<?php

use Swoole\Coroutine\Http\Client;
use Swoole\Coroutine\Channel;
use Swoole\Process;
use Swoole\Timer;
use Swoole\Http\Server;
use Swoole\Http\Request;
use Swoole\Http\Response;

$server = new Server('0.0.0.0');

$server->on('workerStart', function (Server $server, int $worker_id) {
    co::set([
        'socket_connect_timeout' => 1,
        'socket_timeout' => 5,
    ]);

    $client = new Client('www.zhe800.com', 443, true);

    function foo($ch, $client)
    {
        mt_srand();
        $rand = mt_rand(100000, 999999999);
        $path = "/email_subscribe?email=" . $rand . "@" . substr(md5(microtime(true)), 0, 8) . ".com";
        $client->get($path);
        echo "push is " . $path . "\n";
        $client->close();
        $ch->push($path);
    }

    function bar($client)
    {
        $length = 100;
        $ch = new Channel($length);
        for ($i = 0; $i < $length; $i++) {
            go('foo', $ch, $client);
        }

        for ($i = 0; $i < $length; $i++) {
            go(function ($ch) {
                $data = $ch->pop(1);
                echo "pop is " . $data . "\n";
            }, $ch);
        }
    }

    bar($client);
});

$server->on('request', function (Request $request, Response $response) {

});

$server->start();
```

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.3
Built => May  8 2019 19:49:55
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2r  26 Feb 2019
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

uname -a

Linux VM_0_17_centos 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

php -v

PHP 7.3.5 (cli) (built: May  8 2019 19:44:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.5, Copyright (c) 1999-2018, by Zend Technologies

gcc -v

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

**Comment by phper08** [comment]
[2019-07-03 21:51:56 $24986.0]	WARNING	swManager_check_exit_status: worker#0[pid=25653] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.3.3, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

**Comment by phper08** [comment]
I guess the $client caused it.

**Comment by phper08** [comment]
php -m

[PHP Modules]
bcmath
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
swoole
sysvsem
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by phper08** [comment]
php.ini

[Pcre]
; PCRE library backtracking limit.
; http://php.net/pcre.backtrack-limit
;pcre.backtrack_limit=100000

; PCRE library recursion limit.
; Please note that if you set this value to a high number you may consume all
; the available process stack and eventually crash PHP (due to reaching the
; stack size limit imposed by the Operating System).
; http://php.net/pcre.recursion-limit
;pcre.recursion_limit=100000

; Enables or disables JIT compilation of patterns. This requires the PCRE
; library to be compiled with JIT support.
pcre.jit=0

**Comment by phper08** [comment]
The code below works.

```
<?php

use Swoole\Coroutine\Http\Client;
use Swoole\Coroutine\Channel;
use Swoole\Process;
use Swoole\Timer;
use Swoole\Http\Server;
use Swoole\Http\Request;
use Swoole\Http\Response;

$server = new Server('0.0.0.0');

$server->on('workerStart', function (Server $server, int $worker_id) {
    co::set([
        'socket_connect_timeout' => 1,
        'socket_timeout' => 5,
    ]);


    function foo($ch)
    {
        $client = new Client('www.zhe800.com', 443, true);
        mt_srand();
        $rand = mt_rand(100000, 999999999);
        $path = "/email_subscribe?email=" . $rand . "@" . substr(md5(microtime(true)), 0, 8) . ".com";
        $client->get($path);
        echo "push is " . $path . "\n";
        $client->close();
        $ch->push($path);
    }

    function bar()
    {
        $length = 100;
        $ch = new Channel($length);
        for ($i = 0; $i < $length; $i++) {
            go('foo', $ch);
        }

        for ($i = 0; $i < $length; $i++) {
            go(function ($ch) {
                $data = $ch->pop(1);
                echo "pop is " . $data . "\n";
            }, $ch);
        }
    }

    bar();
});

$server->on('request', function (Request $request, Response $response) {

});

$server->start();
```

**Comment by phper08** [comment]
USE_ZEND_ALLOC=0 valgrind php client.php

==14699== Memcheck, a memory error detector
==14699== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==14699== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==14699== Command: php client.php
==14699==
==14699== Conditional jump or move depends on uninitialised value(s)
==14699==    at 0x8FF5E2: zend_string_equal_val (zend_string.c:403)
==14699==    by 0x8E9D54: zend_string_equal_content (zend_string.h:310)
==14699==    by 0x8E9D54: zend_hash_find_bucket (zend_hash.c:586)
==14699==    by 0x8E9D54: zend_hash_find (zend_hash.c:2090)
==14699==    by 0x8C934A: zend_get_constant_impl (zend_constants.c:279)
==14699==    by 0x8ACC2F: zend_ini_get_constant (zend_ini_parser.c:223)
==14699==    by 0x8ACC2F: ini_parse (zend_ini_parser.c:1927)
==14699==    by 0x8AD34C: zend_parse_ini_file (zend_ini_parser.c:309)
==14699==    by 0x882ACF: php_init_config (php_ini.c:630)
==14699==    by 0x87C3DD: php_module_startup (main.c:2270)
==14699==    by 0x95F14C: php_cli_startup (php_cli.c:420)
==14699==    by 0x48C85E: main (php_cli.c:1356)
==14699==
==14699== Conditional jump or move depends on uninitialised value(s)
==14699==    at 0x8FF5E2: zend_string_equal_val (zend_string.c:403)
==14699==    by 0x8E4BBB: zend_string_equal_content (zend_string.h:310)
==14699==    by 0x8E4BBB: zend_hash_find_bucket (zend_hash.c:586)
==14699==    by 0x8E4BBB: _zend_hash_add_or_update_i (zend_hash.c:669)
==14699==    by 0x8E4BBB: zend_hash_update (zend_hash.c:816)
==14699==    by 0x882063: php_ini_parser_cb (php_ini.c:239)
==14699==    by 0x8ACDE4: ini_parse (zend_ini_parser.c:1676)
==14699==    by 0x8AD34C: zend_parse_ini_file (zend_ini_parser.c:309)
==14699==    by 0x882ACF: php_init_config (php_ini.c:630)
==14699==    by 0x87C3DD: php_module_startup (main.c:2270)
==14699==    by 0x95F14C: php_cli_startup (php_cli.c:420)
==14699==    by 0x48C85E: main (php_cli.c:1356)
==14699==
==14699== Conditional jump or move depends on uninitialised value(s)
==14699==    at 0x8FF5E2: zend_string_equal_val (zend_string.c:403)
==14699==    by 0x8E9D54: zend_string_equal_content (zend_string.h:310)
==14699==    by 0x8E9D54: zend_hash_find_bucket (zend_hash.c:586)
==14699==    by 0x8E9D54: zend_hash_find (zend_hash.c:2090)
==14699==    by 0x8F0F47: zend_register_ini_entries (zend_ini.c:258)
==14699==    by 0x87C3F4: php_module_startup (main.c:2275)
==14699==    by 0x95F14C: php_cli_startup (php_cli.c:420)
==14699==    by 0x48C85E: main (php_cli.c:1356)
==14699==
==14699== Conditional jump or move depends on uninitialised value(s)
==14699==    at 0x8FF5E2: zend_string_equal_val (zend_string.c:403)
==14699==    by 0x8FF8D6: zend_string_equal_content (zend_string.h:310)
==14699==    by 0x8FF8D6: zend_interned_string_ht_lookup (zend_string.c:156)
==14699==    by 0x8FF8D6: zend_new_interned_string_permanent.part.5 (zend_string.c:196)
==14699==    by 0x8F0F9A: zend_register_ini_entries (zend_ini.c:261)
==14699==    by 0x87C3F4: php_module_startup (main.c:2275)
==14699==    by 0x95F14C: php_cli_startup (php_cli.c:420)
==14699==    by 0x48C85E: main (php_cli.c:1356)
==14699==
==14699== Conditional jump or move depends on uninitialised value(s)
==14699==    at 0x8FF5E2: zend_string_equal_val (zend_string.c:403)
==14699==    by 0x8FF8D6: zend_string_equal_content (zend_string.h:310)
==14699==    by 0x8FF8D6: zend_interned_string_ht_lookup (zend_string.c:156)
==14699==    by 0x8FF8D6: zend_new_interned_string_permanent.part.5 (zend_string.c:196)
==14699==    by 0x8F0F9A: zend_register_ini_entries (zend_ini.c:261)
==14699==    by 0x87C3F9: php_module_startup (main.c:2278)
==14699==    by 0x95F14C: php_cli_startup (php_cli.c:420)
==14699==    by 0x48C85E: main (php_cli.c:1356)
==14699==
==14699== Conditional jump or move depends on uninitialised value(s)
==14699==    at 0x8FF5E2: zend_string_equal_val (zend_string.c:403)
==14699==    by 0x8E9D54: zend_string_equal_content (zend_string.h:310)
==14699==    by 0x8E9D54: zend_hash_find_bucket (zend_hash.c:586)
==14699==    by 0x8E9D54: zend_hash_find (zend_hash.c:2090)
==14699==    by 0x8F0F47: zend_register_ini_entries (zend_ini.c:258)
==14699==    by 0x87C3F9: php_module_startup (main.c:2278)
==14699==    by 0x95F14C: php_cli_startup (php_cli.c:420)
==14699==    by 0x48C85E: main (php_cli.c:1356)
==14699==
^C==14699==
==14699== Process terminating with default action of signal 2 (SIGINT)
==14699==    at 0x5DCAA19: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.19)
==14699==    by 0x5DCC2A0: char* std::string::_S_construct<char const*>(char const*, char const*, std::allocator<char> const&, std::forward_iterator_tag) (in /usr/lib64/libstdc++.so.6.0.19)
==14699==    by 0x5DCC6D7: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (in /usr/lib64/libstdc++.so.6.0.19)
==14699==    by 0x124583DA: std::pair<std::string const, std::string>::pair<char const (&) [4], char const (&) [29], void>(char const (&) [4], char const (&) [29]) (stl_pair.h:145)
==14699==    by 0x1242CC1E: __static_initialization_and_destruction_0(int, int) [clone .constprop.42] (mime_types.cc:27)
==14699==    by 0x400F8F2: _dl_init (in /usr/lib64/ld-2.17.so)
==14699==    by 0x40144CD: dl_open_worker (in /usr/lib64/ld-2.17.so)
==14699==    by 0x400F703: _dl_catch_error (in /usr/lib64/ld-2.17.so)
==14699==    by 0x4013ABA: _dl_open (in /usr/lib64/ld-2.17.so)
==14699==    by 0x6796EEA: dlopen_doit (in /usr/lib64/libdl-2.17.so)
==14699==    by 0x400F703: _dl_catch_error (in /usr/lib64/ld-2.17.so)
==14699==    by 0x67974EC: _dlerror_run (in /usr/lib64/libdl-2.17.so)
==14699==
==14699== HEAP SUMMARY:
==14699==     in use at exit: 754,293 bytes in 5,283 blocks
==14699==   total heap usage: 5,598 allocs, 315 frees, 992,695 bytes allocated
==14699==
==14699== LEAK SUMMARY:
==14699==    definitely lost: 28 bytes in 1 blocks
==14699==    indirectly lost: 0 bytes in 0 blocks
==14699==      possibly lost: 571,600 bytes in 4,193 blocks
==14699==    still reachable: 182,665 bytes in 1,089 blocks
==14699==                       of which reachable via heuristic:
==14699==                         stdstring          : 25,099 bytes in 704 blocks
==14699==         suppressed: 0 bytes in 0 blocks
==14699== Rerun with --leak-check=full to see details of leaked memory
==14699==
==14699== For counts of detected and suppressed errors, rerun with: -v
==14699== Use --track-origins=yes to see where uninitialised values come from
==14699== ERROR SUMMARY: 67 errors from 6 contexts (suppressed: 0 from 0)

**Comment by matyhtf** [comment]
Do not send requests concurrently, and create a separate client for each coroutine.
