### ISSUE TITLE
Swoole\Coroutine\Http\Client set_cookie_headers 解析问题

### ISSUE THREAD

**Issue by mcpan** [swoole/swoole-src#2664]
## 复现
```php
$http = new Swoole\Http\Server("0.0.0.0", 9501);
$http->on('request', function ($request, $response) {
    $timeleft = time() + 84600;

    $response->cookie('key1', 'val1', $timeleft, '/', 'id.test.com');
    $response->cookie('key1', '', 0, '/', 'test.com');
    $response->cookie('key2', 'val2', $timeleft, '/', 'id.test.com');
    $response->cookie('key2', '', 0, '/', 'test.com');

    $response->end("<h1>Hello Swoole. #".rand(1000, 9999)."</h1>");
});
$http->start();
```
```php
go(function ()
{
    $client = new Swoole\Coroutine\Http\Client('localhost', 9501);
    $client->get('/');
    print_r($client->set_cookie_headers);
    $client->close();
});
```

## php 结果
    Array
    (
        [key1] => key1=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=test.com  
        [key2] => key2=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=test.com  
    ) 
## 浏览器结果
    HTTP/1.1 200 OK
    Server: swoole-http-server
    Connection: keep-alive
    Content-Type: text/html
    Date: Thu, 04 Jul 2019 19:44:36 GMT
    Content-Length: 28
    Set-Cookie: key1=val1; expires=Fri, 05-Jul-2019 19:14:36 GMT; path=/; domain=id.test.com
    Set-Cookie: key1=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=test.com
    Set-Cookie: key2=val2; expires=Fri, 05-Jul-2019 19:14:36 GMT; path=/; domain=id.test.com
    Set-Cookie: key2=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=test.com

    <h1>Hello Swoole. #3664</h1>

![批注 2019-07-05 034538](https://user-images.githubusercontent.com/1267341/60685743-661f5f00-9ed7-11e9-9c0d-ecd143cdf11e.png)

后面看了一下源码 add_assoc_stringl_ex 将已存在的key覆盖掉了
https://github.com/swoole/swoole-src/blob/7d1810cab85a4a01d2abd6ef1eee7a501a54530f/swoole_http.h#L232
试了下替换成 add_next_index_stringl 暂时解决
```c++
        add_next_index_stringl(set_cookie_headers, (char *) at, length);
```

    Array
    (
        [0] => key1=val1; expires=Fri, 05-Jul-2019 19:02:05 GMT; path=/; domain=id.test.com
        [1] => key1=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=test.com
        [2] => key2=val2; expires=Fri, 05-Jul-2019 19:02:05 GMT; path=/; domain=id.test.com
        [3] => key2=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=test.com
    )

**Comment by twose** [comment]
可以提个pr, `set_cookie_headers`一般用于自己解析, 键名作用不大, 但会造成向下不兼容
