### ISSUE TITLE
Best API for UDP threadpool

### ISSUE THREAD

**Issue by ClosetMonkey** [swoole/swoole-src#2665]
Hi, I have a basic UDP server that uses standard Linux sockets within a Swoole reactor based event loop. The server currently uses native Swoole coroutines as well. However I want to dispatch the read event handler into a threadpool without loosing coroutine features. I see that Swoole has both a custom threadpool API as well as an aio API. Which if these (or other?) would be best for what I'm looking for, and if possible, can you point me to a brief example of how the API is used within Swoole?

**Comment by matyhtf** [comment]
Aio thread is used for file reading and writing. 

You should use the `swoole::coroutine::Socket` class to implement udp socket operations.

**Comment by matyhtf** [comment]
example
-----
```cpp
#include "coroutine_socket.h"

using swoole::coroutine::Socket;

int main() {
        Socket sock(SW_SOCK_UDP);
        bool retval = sock.connect("127.0.0.1", 9501, -1);
        sock.send("echo", 5);
        char buf[128];
        int n = sock.recv(buf, sizeof(buf));
}
```

**Comment by ClosetMonkey** [comment]
I'm using an existing library and converting it completely to coroutine::Socket is more work than I'm currently willing to do, so I'm instead using Swoole reactor based event handling along with a read_coro, write_coro, and timer (basically similar to coroutine::Socket.) This works great currently. The problem is that each process can only access one RX queue within NIC unless multiple threads are used, creating a bottleneck. I'm not yet familiar with how the Swoole Process Manager class internally handles fork()ing but this can also be done using the multi-process model rather than multiple threads. Any advice to how PM can be used instead of multiple io threads? Thanks

**Comment by ClosetMonkey** [comment]
I'm sorry, but this issue is not closed. I understand that your policy is to keep threading to a minimum and to promote multi-process models in PHP userspace, but this is a problem that can only be addressed by using IO threads. Forking multiple processes with the full weight of PHP + included extensions (20-50+ mb of ram) is not the way to go when working on this level - when in the need of light IO threads and working with a framework that provides such facilities. Also note that this also touches on issue https://github.com/swoole/swoole-src/issues/2633 . You should be more forthcoming with advise on the lower levels of your framework (reactors, threading, etc)
