### ISSUE TITLE
install error: 'brotli/encode.h' not found

### ISSUE THREAD

**Issue by suntao395** [swoole/swoole-src#2670]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

pecl install swoole (ps: stable version)

2. What did you expect to see?

I want everything goes fine.

3. What did you see instead?

```shell
/private/tmp/pear/temp/swoole/swoole_http_request.cc:43:10: fatal error: 'brotli/encode.h' file not found
#include <brotli/encode.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [swoole_http_request.lo] Error 1
ERROR: `make' failed
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

Well, I haven't install it yet.

5. What is your machine environment used (including version of kernel & php & gcc) ?

mac os mojave / php@7.2.17 

gcc version:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by twose** [comment]
try
```shell
brew install brotli
brew link brotli
```

**Comment by suntao395** [comment]
> try
> 
> ```shell
> brew install brotli
> brew link brotli
> ```

Actually I already linked brotli in my mac, but still not working.

**Comment by suntao395** [comment]
It's been solved, you can `ln -s /usr/local/Cellar/brotli/include /usr/local/include`
