### ISSUE TITLE
Why swoole mysql return null instead of empty array after version v4.4.0

### ISSUE THREAD

**Issue by stormeyes** [swoole/swoole-src#2674]
in the older version, when the sql result is empty, the mysql will return empty array, but after version v4.4.0, it return null, which stop me from upgrading my project into latest swoole version, i just wonder why ?

```
<?php

$server = new Swoole\Http\Server('0.0.0.0', 9501, SWOOLE_BASE);

$server->set([
    'worker_num' => 2, 
]);

$server->on('request', function (Swoole\Http\request $req, Swoole\Http\response $resp) {
    
    $db = new Swoole\Coroutine\Mysql();
    $ret = $db->connect([
        'host' => '127.0.0.1',
        'user' => 'root',
        'password' => '002899',
        'timeout' => 1,
        'charset' => 'utf8mb4',
        'strict_type' => true,
        'database' => 'test',
    ]);

    $res = $db->query('select * from testtable');
    var_dump($res); // it return null after version v4.4.0 instead of array(0) {}
    $db->close();

    $resp->end(123);
});

$server->start();
```

**Comment by twose** [comment]
It's an unexpected change

Rule:

| condition                           | return value    |
| ----------------------------------- | --------------- |
| no data (fetch)                     | null            |
| no data (fetchAll := query/execute) | empty array     |
| io error                            | false           |
| error packet                        | false           |
| ok packet                           | true            |
| result packets                      | array with data |
