### ISSUE TITLE
sdebug not recognized for code coverage

### ISSUE THREAD

**Issue by nick-zh** [swoole/swoole-src#2680]
hey @mabu233 

It seems, when running phpunit, sdebug is not recognized as code coverage driver.
Might this be due to the rename from xdebug to sdebug?
I was unable to find if i can somehow configure another driver for phpunit.

Cheers,
Nick

**Comment by inhere** [comment]
:) on swoole 4.4+, you can use phpbdg output coverage:

```bash
phpdbg -dauto_globals_jit=Off -qrr /usr/local/bin/phpunit --coverage-text
```

**Comment by nick-zh** [comment]
@inhere thank you, actually we already use phpdbg, i still thought it might be worth mentioning :)
