### ISSUE TITLE
swoole4.4.0关闭进程bug

### ISSUE THREAD

**Issue by a07061625** [swoole/swoole-src#2681]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
服务启动正常,关闭进程的时候，使用\swoole_process::kill(main进程ID)关闭

2. What did you expect to see?
所有main,manager,task,worker进程全部关闭

3. What did you see instead?
所有main,manager,task,worker进程全部都没有关闭
如下两个操作进程全部正常关闭:
1.将swoole版本退回到4.3.2
2.exec('kill -9 ' . main进程ID)

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole 4.4.0

5. What is your machine environment used (including version of kernel & php & gcc) ?
centos7.6
php7.2.19
gcc4.8.5

**Comment by phper08** [comment]
未能重现Bug
使用ps -ef | grep 'php test.php'观察，10秒后3个进程消失

环境：
PHP 7.3.5
Swoole 4.4.0
CentOS 7.6 单核

```PHP
<?php

$server = new swoole_http_server('0.0.0.0', 60003);
$server->on('workerStart', function (swoole_http_server $server, int $worker_id) {
    if ($worker_id === 0) {
        echo $server->master_pid . "\n";
        echo $server->manager_pid . "\n";
        echo $server->worker_pid . "\n";

        swoole_timer_after(10000, function () use ($server) {
            swoole_process::kill($server->master_pid);
        });
    }
});
$server->on('request', function (swoole_http_request $request, swoole_http_response $response) {
    
});
$server->start();
```

**Comment by phper08** [comment]
![图片](https://user-images.githubusercontent.com/13127645/61115351-daa06200-a4c4-11e9-8be4-1c7f503f7fc7.png)

![图片](https://user-images.githubusercontent.com/13127645/61115370-e68c2400-a4c4-11e9-95b9-defe2e15e6fd.png)

**Comment by a07061625** [comment]
@phper08  ...哥们，应该是我没有说清楚，我的关闭进程操作不是用swoole_timer_after这个,我这边的关闭进程脚本是类似这样的
vim close.php
    <?php
    $pid = 1111; //该进程ID在服务启动成功后会写入到一个pid文件，关闭服务的时候会去读取该文件
    swoole_process::kill($pid);
php close.php

**Comment by a07061625** [comment]
@phper08 启动和关闭操作执行脚本的用户都是同一个

**Comment by huanghantao** [comment]
@a07061625 你更新到最新的代码，前几天好像修了这个bug

**Comment by phper08** [comment]
运行close.php后提示什么？或者能提供完整代码吗？

swoole_process::kill($pid, 0);
你可以看一下该进程是否存在

也许传的$pid不是master_pid

**Comment by a07061625** [comment]
@phper08　
    /**
     * 关闭服务
     */
    public function stop()
    {
        if (is_file($this->_pidFile) && is_readable($this->_pidFile)) {
            $pid = (int)file_get_contents($this->_pidFile);
        } else {
            $pid = 0;
        }

        $msg = ' \e[1;31m \t[fail]';
        if ($pid > 0) {
            if (\swoole_process::kill($pid)) {
                $msg = ' \e[1;32m \t[success]';
            }
            file_put_contents($this->_pidFile, '');
        }
        system('echo -e "\e[1;36m stop ' . SY_MODULE . ': \e[0m' . $msg . ' \e[0m"');
        exit();
    }

//启动写入
protected function basicStart(\swoole_server $server)
    {
        @cli_set_process_title(Server::PROCESS_TYPE_MAIN . SY_MODULE . $this->_port);

        if (file_put_contents($this->_pidFile, $server->master_pid) === false) {
            Log::error('write ' . SY_MODULE . ' pid file error');
        }
    }

**Comment by a07061625** [comment]
![image](https://user-images.githubusercontent.com/12109534/61118017-6b2d7100-a4ca-11e9-9a86-c74c394101a0.png)
@phper08

**Comment by a07061625** [comment]
@huanghantao 我就是用的最新版4.4.0扩展包，从pecl下载的

**Comment by huanghantao** [comment]
@a07061625 你用master分支的代码

**Comment by a07061625** [comment]
@huanghantao 你是说直接用github上的master分支，不用那个pecl扩展包是么？

**Comment by huanghantao** [comment]
@a07061625 对的

**Comment by a07061625** [comment]
@huanghantao 我知道了,非常感谢

**Comment by a07061625** [comment]
经过本人实际测试，代码参考上述截图，swoole4.4.1,swoole4.4.2依然存在上述问题，如果本人用法有问题，欢迎指正

**Comment by a07061625** [comment]
如下为swoole4.4.2时候的测试
![image](https://user-images.githubusercontent.com/12109534/62194751-0d939280-b3ad-11e9-8cda-ad4afe6d64de.png)
![image](https://user-images.githubusercontent.com/12109534/62194821-32880580-b3ad-11e9-8e58-d6a50c73402b.png)
![image](https://user-images.githubusercontent.com/12109534/62194883-52b7c480-b3ad-11e9-9ed6-5f19a8964810.png)
![image](https://user-images.githubusercontent.com/12109534/62194956-7f6bdc00-b3ad-11e9-980f-657dd58654f1.png)

**Comment by a07061625** [comment]
@huanghantao

**Comment by a07061625** [comment]
当swoole版本退回到4.3.2的时候，swoole_process::kill是正常的

**Comment by matyhtf** [comment]
注册`workerExit`回调，清理定时器，4.4 版本的退出机制更安全了，会检测是否有 事件和定时器，否则会持续等待，超时后会强制退出。

**Comment by shenzhe** [comment]
可以配置max_wait_time 这个选项来缩短强制退出的时间，默认是30s.
不过还是建议等事件或定时器完成后安全退出

**Comment by a07061625** [comment]
@matyhtf 好的，谢谢峰哥，我确实没有注册workerExit回调，我马上去测试下

**Comment by a07061625** [comment]
@shenzhe 我设置了max_wait_time 为60秒的，
![image](https://user-images.githubusercontent.com/12109534/62410224-85fc8c80-b615-11e9-9835-3e0c24aca55c.png)

**Comment by a07061625** [comment]
@matyhtf 峰哥，我刚才测试了下，貌似还是不行呢？能指导下是哪里出问题了么？

**Comment by a07061625** [comment]
![image](https://user-images.githubusercontent.com/12109534/62421409-cae6f880-b6d3-11e9-9ac7-0d89d7d1387c.png)
![image](https://user-images.githubusercontent.com/12109534/62421413-e05c2280-b6d3-11e9-9dc4-e3fe90738738.png)
![image](https://user-images.githubusercontent.com/12109534/62421417-eeaa3e80-b6d3-11e9-9e38-0bbd45a884c5.png)

**Comment by a07061625** [comment]
![image](https://user-images.githubusercontent.com/12109534/62421422-0bdf0d00-b6d4-11e9-8942-e475e1af80a5.png)

**Comment by a07061625** [comment]
其他的代码我都没有变动，只是增加了上述代码

**Comment by shenzhe** [comment]
配置短点，比如2秒

**Comment by a07061625** [comment]
@shenzhe 和配置的等待时间没有关系，不管配置多长时间，实际情况是在ｓｗｏｏｌｅ４．４．３版本，swoole_process::kill以后进程一直存在，我配置的六十秒，但是过了差不多十分钟后，依然存在,改成三十秒还是一样的，并没有杀死进程

**Comment by NHZEX** [comment]
> @shenzhe 和配置的等待时间没有关系，不管配置多长时间，实际情况是在ｓｗｏｏｌｅ４．４．３版本，swoole_process::kill以后进程一直存在，我配置的六十秒，但是过了差不多十分钟后，依然存在,改成三十秒还是一样的，并没有杀死进程

说明仍然有资源没被释放。
我之前也swoole升级时也遇到这个问题：
1. 定时器关闭，连接池释放，销毁事件监听，尝试退出协程。
2. 如果在自定义进程内，则监听信号，完成上述清理操作。

**Comment by a07061625** [comment]
在swoole4.4.6版本中,该问题已经被解决,其他版本未测试

**Comment by a07061625** [comment]
@matyhtf @shenzhe @NHZEX
