### ISSUE TITLE
How to determine what causes memory leak ?

### ISSUE THREAD

**Issue by ozgurhangisi** [swoole/swoole-src#2685]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

When I run the swoole server,  swoole worker eats all memory and server goes down a few days later. 

After downtime, 4-5 minutes later worker restarts automatically and everything is fine. But I get lots of downtime because of this issue.  My code uses swoole server that connects db, memcached and returns some html. But the code is so long so I can not copy here.

When I look at memory_get_usage its always around 2.5 MB memory_get_peak_usage always around 6 MB. It never changes. But when I look at php73 memory usage with top command it always increases and when memory usage is around %90 swoole worker goes down. But I can not see this metric with php memory commands. 

I noticed that when I disabled opcache_cli memory_get_usage increasing and I see the actual memory value that I see in top command. But when I enabled opcache_cli, memory_get_usage always around 2.5 MB. 

I checked all of the classes but nothing is increasing. Probably something stays in memory and never released but I can not see. May be It can be db resources. 

I also tried older swoole versions (4.3.5, 4.2.12) and it's the same. Probably it's not swoole's fault but is there any method that I can see what causes memory leak ? I can not see it from the php side.

The code is so long so I can not paste is here.

Thanks.

2. What did you expect to see?

RAM should be stable

3. What did you see instead?

RAM increasing so fast

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.0
Built => Jul  8 2019 07:04:07
coroutine => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

PHP 7.3.7 (cli) (built: Jul  3 2019 11:30:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.7, Copyright (c) 1999-2018, by Zend Technologies

**Comment by jobs-git** [comment]
It should not happen in random. Post part of the code that you suspect has memory leak.

**Comment by ozgurhangisi** [comment]
@jobs-git Thank you for your answer. Now I just separated requests with Load Balancer and I send different requests to different servers to see which part of my code has memory leak. So probably I will send the code next week. I use PDO for mysql connection and I highly suspect that PDO keep resources in memory even if I set it to null and unset the statement and connection variables.

**Comment by ozgurhangisi** [comment]
I close this issue now. When I find the problem I will reopen this issue again.
