### ISSUE TITLE
swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout

### ISSUE THREAD

**Issue by kirachen1991** [swoole/swoole-src#2686]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I use tick in the onWorkerStart，and push task in the tick callback function, when I remove the push task code, nothing change.

在woker里面使用了tick，tick里面投放task（注释了投放task的代码也一样）
```
$this->server->on( 'WorkerStart', function( $serv, $worker_id ){
	$serv->tick( 1000, function() use ( $serv ){
		$serv->task([]);
	}
});
```

2. What did you expect to see?

when I quit my application, the console show me 【INFO    Server is shutdown now】and wait for more than one minute. I saw the warning【WARNING swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate】
when I remove the tick code, this would not happen

退出程序的时候出现【INFO    Server is shutdown now】然后一分多钟后才退出退出
之后报
 WARNING swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate
移除tick之后不会出现

```
INFO    Server is shutdown now

WARNING swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate
```

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.0
Built => Jul 11 2019 12:58:54
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ?

```
# php -v
PHP 7.3.7 (cli) (built: Jul  9 2019 23:32:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies

# uname -a           
Linux linuxkit-025000000001 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 Linux

# gcc --version                                                                             
gcc (Alpine 8.3.0) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by kirachen1991** [comment]
clear timer in the tick callback function, that can solve the problem

```
\Swoole\Timer::tick( 1000, function() use ( $serv, $worker_id ){
    \Swoole\Timer::clearAll();
});
```

**Comment by loyating** [comment]
```shell
WARNING swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate
```
在reload时候，通过WorkerExit事件清理了所有定时器，max_wait_time 进程最大等待时间都还没超过就已经报上述warning了

**Comment by matyhtf** [comment]
已修复。

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/pull/2689

**Comment by kirachen1991** [comment]
用了今天刚发布的4.4.1版本，还是没有修复，在worker里面添加tick，还是无法正常退出，然后超时退出【WARNING swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate】
另外，原本4.4.0还可以在tick的回调方法里面增加\Swoole\Timer::clearAll();进行手动清除timer的方式解决这个问题，4.4.1之后手动调用也无法使worker自然退出。

**Comment by kirachen1991** [comment]
task_enable_coroutine设置为false或true貌似没有产生变化，是我使用方式不对吗？
