### ISSUE TITLE
Http\Server modifies GET/POST fields (dot to underline)

### ISSUE THREAD

**Issue by marc-mabe** [swoole/swoole-src#2688]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Using GET/POST fields and values.

2. What did you expect to see?

URL decoded GET/POST fields and values but not modified otherwise.

3. What did you see instead?

Dots gets replaced by underline in GET/POST field names.

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.4.0

5. What is your machine environment used (including version of kernel & php & gcc) ?

* PHP 7.3.6 (cli)
* Linux 4.15.0-54-generic
* GCC 8.3.0-r0

**Comment by twose** [comment]
Can be implemented by PHP code

**Comment by marc-mabe** [comment]
@twose Sorry, but I can't really follow you.

The following script shows that `Swoole\Http\Server->get` and `Swoole\Http\Server->post` contains wring field names.

```php
$server = new \Swoole\Http\Server('127.0.0.1', '8000', SWOOLE_BASE, SWOOLE_SOCK_TCP);
$server->on('request', function ($request, $response) {
    $response->write(var_export($request->get, true));
    $response->write(var_export($request->post, true));
    $response->end();
});
$server->start();
```
```
$ curl -d 'foo.bar=baz.test' 'http://127.0.0.1/?foo.bar=baz.test'
array (
  'foo_bar' => 'baz.test',
)array (
  'foo_bar' => 'baz.test',
)
```

As you can see `foo.bar` got modified with `foo_bar` and it's not possible to differ between `foo.bar` and `foo_bar`.
