### ISSUE TITLE
Set Content-Length for HEAD request manually

### ISSUE THREAD

**Issue by yueyuzhao** [swoole/swoole-src#2690]
Hello, thanks for this amazing project. 
But I'm making a HEAD request to check the `Content-Length` field in the headers, but swoole won't accept `Content-Length` field. I don't want to flush the full content to swoole or I don‘t have the content but I do have the content length. How can I do that? 

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
<?php

$http = new swoole_http_server("127.0.0.1", 1337, SWOOLE_BASE);

$http->set([
    'worker_num' => 4,
]);

$data = json_encode([
  'code' => 'ok',
  'error' => false,
  'payload' => 'Hello World'
]);

$http->on('request', function ($req, swoole_http_response $resp) use ($data) {
    $resp->header('Content-Type', 'application/json');
    if ($req->server['request_method'] == 'HEAD') {
        $resp->header('Content-Length', strlen($data));
        $resp->end();
        return;
    }
    $resp->end($data);
});

$http->start();
```

```sh
$ curl -I http://127.0.0.1:3737/
```

2. What did you expect to see?

`Content-Length: 51`

3. What did you see instead?

`Content-Length: 0`

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.4.1-alpha

5. What is your machine environment used (including version of kernel & php & gcc) ?

PHP 7.2.16

**Comment by yueyuzhao** [comment]
From #958 , I know that swoole would set `Content-Length` automatically.

**Comment by twose** [comment]
This does not conform to the HTTP RFC

**Comment by yueyuzhao** [comment]
From the manual, one way I can come with: 
```php
$http->on('request', function ($req, swoole_http_response $resp) use ($http, $data) {
    $resp->header('Content-Type', 'application/json');
    if ($req->server['request_method'] == 'HEAD') {
        $resp->detach();
        $length = strlen($data);
        $http->send($resp->fd, "HTTP/1.1 200 OK\r\nContent-Length: {$length}\r\nServer: server\r\n\r\n");
        return;
    }
    $resp->end($data);
});
```
But is there a nicer way?

**Comment by twose** [comment]
sorry, I didn't notice this was a HEAD request

**Comment by yueyuzhao** [comment]
@twose  Many thanks for your quick response!
