### ISSUE TITLE
I can't stop server by sigterm while I start a timer in onWorkerStart callback

### ISSUE THREAD

**Issue by manyin** [swoole/swoole-src#2691]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I add a timer in onWorkerStart callback, but Server can not be kill by sigterm once.

2. What did you expect to see?
Server exit normaly.

3. What did you see instead?
The worker with timer not be killed.

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.4

5. What is your machine environment used (including version of kernel & php & gcc) ?
centos 7  and php7.3 
[root@localhost tools]# gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

**Comment by twose** [comment]
You must clear all of the timers in onWorkerStop
Otherwise, the forced exit may break your program logic
You can call `Swoole\Timer::clearAll`

**Comment by manyin** [comment]
Yes I have allready clear all timer,but nothing changes.

$this->on("workerStart",function (swoole_websocket_server $server, $id){

            $this->initMysqlPool();
            $this->initRedisPool();
            $this->autoload($id);
            if ($id == 0)
            {
                //$this->tick(1000,function (){
                foreach ($this->plugins as $pn=>$p)
                {
                    if(method_exists($p,"onTick") && is_callable([$p,"onTick"]))
                    {
                        LGLog::info("启动插件定时器 $pn::onTick()");
                        $this->tick(1000,[$p,"onTick"]);
                    }
                }
                //});

            }

            $this->onWorkerStart($server,$id);

        });
$this->on("workerStop",function (){
            Swoole\Timer::clearAll();
        });

**Comment by manyin** [comment]
I know is because the timer , when I delete the timer, it is killed normaly.

**Comment by kingIZZZY** [comment]
+1 this is an issue for me as well

SIGTERM cannot even each `onWorkerStop` as long as timers exist...

**Comment by kingIZZZY** [comment]
Workaround: Apparently timers should be created within workers, not the main master process
https://github.com/swoole/swoole-src/issues/4451#issuecomment-962228224
