### ISSUE TITLE
Build for s390x and ppc64le

### ISSUE THREAD

**Issue by andypost** [swoole/swoole-src#2692]
1. What did you do? If possible, provide a simple script for reproducing the error.

I'm packaging extension for Alpinelinux https://github.com/alpinelinux/aports/pull/9501 where enabled build for all platforms after https://github.com/swoole/swoole-src/issues/2181

2. What did you expect to see?

That `php7 -d extension="$builddir"/modules/swoole.so --ri swoole` will pass after build

3. What did you see instead?

- https://build.alpinelinux.org/buildlogs/build-edge-ppc64le/testing/php7-pecl-swoole/php7-pecl-swoole-4.4.1-r0.log
- https://build.alpinelinux.org/buildlogs/build-edge-s390x/testing/php7-pecl-swoole/php7-pecl-swoole-4.4.1-r0.log
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/buildozer/aports/testing/php7-pecl-swoole/src/swoole-4.4.1/modules/swoole.so' (tried: /home/buildozer/aports/testing/php7-pecl-swoole/src/swoole-4.4.1/modules/swoole.so (Error relocating /home/buildozer/aports/testing/php7-pecl-swoole/src/swoole-4.4.1/modules/swoole.so: swapcontext: symbol not found), /usr/lib/php7/modules//home/buildozer/aports/testing/php7-pecl-swoole/src/swoole-4.4.1/modules/swoole.so.so (Error loading shared library /usr/lib/php7/modules//home/buildozer/aports/testing/php7-pecl-swoole/src/swoole-4.4.1/modules/swoole.so.so: No such file or directory)) in Unknown on line 0
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.4.1 and previous

5. What is your machine environment used (including version of kernel & php & gcc) ?

php 7.3.7, kernel 4.19.58, gcc 8.3.0

**Comment by andypost** [comment]
As I see `AS_CASE([$host_cpu]` has no mentions about ppc64 and s390x

**Comment by andypost** [comment]
@matyhtf commit fixes PPC but not s390x

**Comment by matyhtf** [comment]
I don't know if the s390x architecture supports gcc ucontext

**Comment by andypost** [comment]
As I see others using to try migrate to `ucontext_t` but yep, no idea how to fix it right

**Comment by matyhtf** [comment]
Test passed, can be used

![2019-07-31 11-35-00 的屏幕截图](https://user-images.githubusercontent.com/2017766/62181870-4d478380-b387-11e9-8ac8-9b3bedee39f0.png)

**Comment by andypost** [comment]
Probably it needs some dependency to add for this arches, because it builds but fails to load extension with `php7 -d extension="$builddir"/modules/swoole.so --ri swoole`

Logs will be available for some time
- https://build.alpinelinux.org/buildlogs/build-edge-ppc64le/testing/php7-pecl-swoole/php7-pecl-swoole-4.4.3-r0.log
- https://build.alpinelinux.org/buildlogs/build-edge-s390x/testing/php7-pecl-swoole/php7-pecl-swoole-4.4.3-r0.log

**Comment by dixyes** [comment]
@andypost if boost context cannot be used in that platform, ucontext will be used. In alpine, [libucontext](https://pkgs.alpinelinux.org/packages?name=libucontext&branch=edge) may provide that.

**Comment by andypost** [comment]
@dixyes thanks a lot! I will try, missed this library
