### ISSUE TITLE
swoole-v4.4.0执行make test时，全部skip

### ISSUE THREAD

**Issue by yunnzi** [swoole/swoole-src#2695]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

2. What did you expect to see?

3. What did you see instead?
....
SKIP swoole_websocket_server: ping loop [tests/swoole_websocket_server/pingloop.phpt] reason: swoole extension is required
SKIP swoole_websocket_server: websocket ping pong (auto) [tests/swoole_websocket_server/pingpong.phpt] reason: swoole extension is required
SKIP swoole_websocket_server: query [tests/swoole_websocket_server/query.phpt] reason: swoole extension is required
SKIP swoole_websocket_server: websocket server full test [tests/swoole_websocket_server/recv_decode.phpt] reason: swoole extension is required
SKIP swoole_websocket_server: websocket server full test [tests/swoole_websocket_server/send_encode.phpt] reason: swoole extension is required
SKIP swoole_websocket_server: websocket server full test [tests/swoole_websocket_server/send_encode_async.phpt] reason: swoole extension is required
=====================================================================
TIME END 2019-07-17 02:06:03

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   49
---------------------------------------------------------------------

Number of tests :  832                 0
Tests skipped   :  832 (100.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :    0 (  0.0%) (  0.0%)
---------------------------------------------------------------------
Time taken      :   54 seconds
=====================================================================

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by huanghantao** [comment]
阅读这个：https://github.com/swoole/swoole-src/tree/master/tests

**Comment by twose** [comment]
都没有把swoole加入php.ini中

**Comment by yunnzi** [comment]
已解决，谢谢
