### ISSUE TITLE
1.7.16-stable 使用 websocket 会出现worker异常退出

### ISSUE THREAD

**Issue by msxcms** [swoole/swoole-src#270]
PHP和脚本都没有问题，无报错
worker异常退出后会被重新拉起

worker退出频率不定

[2015-05-29 14:04:21 *12494.3]  WARN    swFactoryProcess_finish: send 4984 byte failed, because session#501 is closed.
[2015-05-29 14:04:40 $12482.0]  WARN    swManager_check_exit_status: worker#3 abnormal exit, status=0, signal=11
[2015-05-29 14:04:42 *12493.2]  WARN    swFactoryProcess_finish: send 5339 byte failed, because session#594 is closed.
[2015-05-29 14:04:54 $12482.0]  WARN    swManager_check_exit_status: worker#2 abnormal exit, status=0, signal=11
[2015-05-29 14:05:29 $12482.0]  WARN    swManager_check_exit_status: worker#5 abnormal exit, status=0, signal=11

下面是core dump 数据

(gdb) bt
#0  0x000000000073761b in zend_is_callable_ex ()
#1  0x0000000000724c44 in zend_call_function ()
#2  0x0000000000725e10 in call_user_function_ex ()
#3  0x00007fe78cac40b4 in http_onReceive (factory=<value optimized out>, req=<value optimized out>)
    at /data/home/kamichen/swoole-src-swoole-1.7.16-stable/swoole_http.c:1031
#4  0x00007fe78cadd4f2 in swWorker_onTask (factory=0x30c1aa0, task=0x7fffa9615d40) at /data/home/kamichen/swoole-src-swoole-1.7.16-stable/src/network/Worker.c:154
#5  0x00007fe78cadd5f1 in swWorker_onPipeReceive (reactor=<value optimized out>, event=0x7fffa9617da0)
    at /data/home/kamichen/swoole-src-swoole-1.7.16-stable/src/network/Worker.c:452
#6  0x00007fe78cad17d0 in swReactorEpoll_wait (reactor=0x30c0310, timeo=<value optimized out>)
    at /data/home/kamichen/swoole-src-swoole-1.7.16-stable/src/reactor/ReactorEpoll.c:267
#7  0x00007fe78caddfd4 in swWorker_loop (factory=<value optimized out>, worker_id=<value optimized out>)
    at /data/home/kamichen/swoole-src-swoole-1.7.16-stable/src/network/Worker.c:399
#8  0x00007fe78cacdbb8 in swManager_spawn_worker (factory=0x30c1aa0, worker_id=3) at /data/home/kamichen/swoole-src-swoole-1.7.16-stable/src/factory/FactoryProcess.c:619
#9  0x00007fe78cace7fc in swManager_start (factory=0x30c1aa0) at /data/home/kamichen/swoole-src-swoole-1.7.16-stable/src/factory/FactoryProcess.c:201
#10 swFactoryProcess_start (factory=0x30c1aa0) at /data/home/kamichen/swoole-src-swoole-1.7.16-stable/src/factory/FactoryProcess.c:111
#11 0x00007fe78cad3ed4 in swServer_start (serv=0x30c15c0) at /data/home/kamichen/swoole-src-swoole-1.7.16-stable/src/network/Server.c:585
#12 0x00007fe78cac0ecc in zim_swoole_http_server_start (ht=<value optimized out>, return_value=0x30b4038, return_value_ptr=<value optimized out>, this_ptr=0x3094960, 
    return_value_used=<value optimized out>) at /data/home/kamichen/swoole-src-swoole-1.7.16-stable/swoole_http.c:1373
#13 0x000000000075703a in zend_do_fcall_common_helper_SPEC ()
#14 0x000000000075669c in execute ()
#15 0x000000000072fdbd in zend_execute_scripts ()
#16 0x00000000006ddc2d in php_execute_script ()
#17 0x00000000007b6095 in main ()

(gdb) f 1
#1  0x0000000000724c44 in zend_call_function ()
(gdb) f 0
#0  0x000000000073761b in zend_is_callable_ex ()

PHP 5.3.22
Swoole Stable 1.7.16
OPCache 7.0.4

**Comment by matyhtf** [comment]
升级到最新版本
