### ISSUE TITLE
MySQL Prepare is not throwing an error when connection is lost form v4.4.0

### ISSUE THREAD

**Issue by antoniaMarkova** [swoole/swoole-src#2700]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Hi,
I'm trying to catch MySQL errors 2006 and 2013 so if the connection to the DB is lost while executing a query the connection to be reestablished. In the previous versions of Swoole it worked fine but since v4.4.0 no exception is thrown while preparing the query.

I have a class for the MySQL where the connection is established in the constructor and a method for preparing the queries. If the connection to the DB is lost before prepare() is called it doesn't throw an exception:

   protected $MysqlCo;
   public function __construct()
    {
        parent::__construct();
        $this->initialize();
    }

    private function initialize()
    {
        $this->MysqlCo = new \Swoole\Coroutine\Mysql();

        $ret = $this->MysqlCo->connect([MySQL DB OPTIONS]);
        if (!$ret) {
            throw new ConnectionException(sprintf('Connection could not be established due to error: [%s] %s .'), $this->MysqlCo->connect_errno, $this->MysqlCo->connect_error );
        }
    }

    public function prepare(string $query) : StatementInterface
    {
        try {
            $NativeStatement = $this->MysqlCo->prepare($query);
        } catch (ErrorException $exception) {
            if ($this->MysqlCo->errno === 2006 || $this->MysqlCo->errno === 2013) {
                // If connection is lost, try to reconnect and prepare the query again
                print(sprintf(t::_("MySQL Connection is Lost with Error No %s. Trying to reconnect ...\n"), $this->MysqlCo->errno));
                $this->initialize();
                return $this->prepare($query);
            } else {
                throw new QueryException($exception->getMessage());
            }
        }
        if (!$NativeStatement) {
            // THE CODE GOEAS HERE!
            throw new QueryException(sprintf(t::_('Preparing query "%s" failed with error: [%s] %s.'), $query, $this->MysqlCo->errno, $this->MysqlCo->error ));
        }
        $Statement = new StatementCoroutine($NativeStatement, $query, $expected_parameters);
        return $Statement;
    }

and code to run some simple queries with Coroutine::sleep(30); between them.

2. What did you expect to see?

If connect_timeout is set to 20 sec (for example) I expect to see the message: 
MySQL Connection is Lost with Error No 2006. Trying to reconnect ...
then to reestablish the connection and move on

3. What did you see instead?

I see "Preparing query "SELECT * FROM some_table" failed with error: [2006] SQLSTATE[HY000] [2006] MySQL server has gone away."

4. What version of Swoole are you using (show your `php --ri swoole`)?

This issue is only on Swoole 4.4.0 and 4.4.1

5. What is your machine environment used (including version of kernel & php & gcc) ?

Thank you in advance.

**Comment by twose** [comment]
Your code is wrong, you must have converted warning to an exception, we don't recommend it
The code should be:
```php
$NativeStatement = $this->MysqlCo->prepare($query);
if (!$NativeStatement) {
        if ($this->MysqlCo->errno === 2006 || $this->MysqlCo->errno === 2013) {
            // If connection is lost, try to reconnect and prepare the query again
            print(sprintf(t::_("MySQL Connection is Lost with Error No %s. Trying to reconnect ...\n"), $this->MysqlCo->errno));
            $this->initialize();
            return $this->prepare($query);
        } else {
            throw new QueryException($exception->getMessage());
        }
}
```

**Comment by antoniaMarkova** [comment]
Yes, indeed, this code works as expected, but only with Swoole 4.4.0 and 4.4.1.
With older versions it is throwing an error: **Swoole\Coroutine\MySQL::prepare(): The MySQL connection is not established in ...**

Of course I can repeat the code so it will work both with 4.4.0 and 4.3.6 like that:

try {
    $NativeStatement = $this->MysqlCo->prepare($query);
} catch (ErrorException $exception) {
    if ($this->MysqlCo->errno === 2006 || $this->MysqlCo->errno === 2013) {
        // If connection is lost, try to reconnect and prepare the query again
        print(sprintf(t::_("MySQL Connection is Lost with Error No %s. Trying to reconnect ...\n"), $this->MysqlCo->errno));
        $this->initialize();
        return $this->prepare($query); 
    } else {
        throw new QueryException($exception->getMessage());
    }
}

if (!$NativeStatement) {
    if ($this->MysqlCo->errno === 2006 || $this->MysqlCo->errno === 2013) {
        // If connection is lost, try to reconnect and prepare the query again
        print(sprintf(t::_("MySQL Connection is Lost with Error No %s. Trying to reconnect ...\n"), $this->MysqlCo->errno));
        $this->initialize();
        return $this->prepare($query);
    } else {
        throw new QueryException($exception->getMessage());
    }
}

I just wanted to point out that there are incompatibilities between the versions.

Regards

**Comment by twose** [comment]
You may be using a framework, then the framework converts the warning into the exception, Swoole never throws any exceptions unless there is a parameter error.

**Comment by antoniaMarkova** [comment]
Yes, our framework converts the warnings into exceptions and removing the warnings is a major change. You may want to add it in the Changelog so the others know too.
Thank you.

**Comment by twose** [comment]
I will remind developers in the next update, thanks
