### ISSUE TITLE
swoole协程http客户端 把回调函数去掉了，onclose和onerror事件怎么监听？

### ISSUE THREAD

**Issue by longyue188** [swoole/swoole-src#2701]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

想监听http client 的onclose事件

2. What did you expect to see?

可以做到监听onclose事件

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
首先，HTTP客户端是自动重连的。
其次，协程的编程模式和同步模式如出一辙，不要因为写多了异步就转换不了思维，比如：CURL怎么监听onClose和onError？同步编程里不需要这些东西，当请求出错了立即处理就好了。
