### ISSUE TITLE
compile swoole.so v4.3.6 failed in Alpine 3.10.1 x86

### ISSUE THREAD

**Issue by skyjust** [swoole/swoole-src#2702]
**compile swoole.so v4.3.6 failed in Alpine 3.10.1 x86。**
1.show error：
thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S  -fPIC -DPIC -o thirdparty/boost/asm/.libs/make_x86_64_sysv_elf_gas.o
/tmp/pear/temp/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S: Assembler messages:
/tmp/pear/temp/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:40: Error: bad register name `%rdi'
/tmp/pear/temp/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:43: Error: bad register name `%rax'
/tmp/pear/temp/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:48: Error: bad register name `%rax)'
/tmp/pear/temp/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:51: Error: bad register name `%rdx'
/tmp/pear/temp/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:54: Error: bad register name `%rax)'
/tmp/pear/temp/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:56: Error: bad register name `%rax)'
/tmp/pear/temp/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:59: Error: bad register name `%rip)'
/tmp/pear/temp/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:62: Error: bad register name `%rcx'
/tmp/pear/temp/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:68: Error: bad register name `%rdi'
make: *** [Makefile:452: thirdparty/boost/asm/make_x86_64_sysv_elf_gas.lo] Error 1

2. my machine environment：
Docker version 18.09.7 + [Alpine 3.10.1 x86](https://github.com/alpinelinux/docker-alpine/tree/34fd41e9b9901d7b346a22c670e5875a84ecfc35/x86)
gcc version 8.3.0 
PHP 7.3.7 (cli)  ( NTS ) x86 32bit

**Comment by dixyes** [comment]
swoole project is originally designed for x86_64, there's no enough efforts on x86 development.

fastest way to resolve this is using x86_64 instead

(for myself: i dont even have a running x86 OS to reproduce your problem)

swoole一开始就是为x86_64设计的，并没有太多精力维护x86开发

最快的解决方法是换用x86_64机器

（就我而言，我甚至没有可用的32位os来复现你的问题

**Comment by skyjust** [comment]
谢谢您，这其实已经是我要的答案了。
