### ISSUE TITLE
MySQL client fetchAll issue

### ISSUE THREAD

**Issue by pervozdanniy** [swoole/swoole-src#2703]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```
        $client = new \Swoole\Coroutine\MySQL();
        $client->connect([
            'host' => 'mysql',
            'port' => 3306,
            'user' => 'pervozdanniy',
            'password' => 'secret',
            'database' => 'yii2basic',
            'charset' => 'utf8',
            'fetch_mode' => true
        ]);
        $stmt = $client->prepare('SELECT * FROM user LIMIT 1000');
        $result = $stmt->execute();
        var_dump($stmt->fetchAll());
        var_dump($stmt->fetchAll()); 
        exit;
```

2. What did you expect to see?
Statement returns fetched rows on every `fetchAll` call like in PDO

3. What did you see instead?
`fetchAll` returns `NULL` after it was called once

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.4
Built => May 25 2019 11:52:08
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2r  26 Feb 2019
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

5. What is your machine environment used (including version of kernel & php & gcc) ?

php:7.2-fpm image based docker build

**Comment by twose** [comment]
Why not using `$statement->fetch()` ?
V4.4.x is recommended

**Comment by pervozdanniy** [comment]
@twose I'd like to get all rows altogether
and later when I need them once more just fetch them again without storing into a variable by myself
Is there a possibility that it will be done in future or such behavior will stay forever?)
P.S. I've upgraded to version 4.4.x and receive empty array instead of `NULL`))

**Comment by twose** [comment]
I think no, I don't know what the benefits are.
