### ISSUE TITLE
Fragment of URI is missing

### ISSUE THREAD

**Issue by huangzhhui** [swoole/swoole-src#2704]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
$http = new Swoole\Http\Server("127.0.0.1", 9501);
$http->on('request', function ($request, $response) {
    var_dump($request);
    $response->end("<h1>Hello Swoole. #".rand(1000, 9999)."</h1>");
});
$http->start();
```
Send a request `http://127.0.0.1:9501/#bar`

2. What did you expect to see?

The fragment of URI `bar` should exist in the swoole request.

3. What did you see instead?

The fragment of URI `bar` is missing.

4. What version of Swoole are you using (show your `php --ri swoole`)?

`4.3.4`

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by inhere** [comment]
fragment 好像是不会发给服务端的。。。

**Comment by huangzhhui** [comment]
> fragment 好像是不会发给服务端的。。。

是吗？但 PSR-7 有 fragment 这一块的内容啊

**Comment by inhere** [comment]
这只是支持完整的url解析，当你吧psr的对象作为客户端位置的使用时。可以用来解析或者构造url

**Comment by huangzhhui** [comment]
嗯，查了下，服务端的确不处理 fragment

**Comment by thexpand** [comment]
@huangzhhui How did you resolve your issue? I am having the same problem - I make an HTTP request to `/bar`, but it detects the URI only as `/`. How to make routing work in such a case?
