### ISSUE TITLE
Menu items and dashboard cards are duplicated each page reload

### ISSUE THREAD

**Issue by juberjj** [swoole/swoole-src#2705]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Implemented Swoole to a current PHP App. Part of the app uses Laravel Nova.

2. What did you expect to see?

Page should render accordingly

3. What did you see instead?

Duplication of menu items and dashboard cards

4. What version of Swoole are you using (show your `php --ri swoole`)?
![image](https://user-images.githubusercontent.com/16324958/61636071-cca0cd00-ac8c-11e9-8650-1b604ec997e8.png)

5. What is your machine environment used (including version of kernel & php & gcc) ?

PHP-FPM 7.3 on Alpine 
gcc (Alpine 8.3.0) 8.3.0

![image](https://user-images.githubusercontent.com/16324958/61636218-15588600-ac8d-11e9-89d3-9f5e5226aa79.png)

Many thanks in advance

**Comment by doubaokun** [comment]
@juberjj Could you send the errors you have seen?

**Comment by juberjj** [comment]
Hey @doubaokun the screenshot above will show you the duplication of items, cards in one side and menu elements in the other whereas you should see only one.

**Comment by doubaokun** [comment]
There’s not enough information about the question is relevant to Swoole.

**Comment by juberjj** [comment]
@doubaokun What information would be needed for you? I sent everything I have and also the information you requested and after two weeks you just close it and dismissed it. Don't even know what else to say.

**Comment by toxmc** [comment]
Because Swoole is Resident memory program. If you use global or static variables. After the request, you must reset global and static variables or Initialize the returned variables before request. Otherwise, the last request will contaminate this one. 
Why PHP-FPM is ok because PHP-FPM did that for you!

**Comment by marianoarga** [comment]
@juberjj did you find the solution? I'm facin similar but my queries and elocuent models are getting duplicated, I got 2 upstreams behind a reverse proxy nginx
