### ISSUE TITLE
Menu items not rendering on Voyager page.

### ISSUE THREAD

**Issue by juberjj** [swoole/swoole-src#2708]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Installation of swoole as described on git. Serving an app that has multiple frameworks attached to it Nova and Vayager. The issue below is rendering Voyager page.

2. What did you expect to see?

![image](https://user-images.githubusercontent.com/16324958/61722982-2c69a780-ad63-11e9-9bc5-635fddc42c71.png)

3. What did you see instead?

![image](https://user-images.githubusercontent.com/16324958/61722929-12c86000-ad63-11e9-8be4-26a34fc31534.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?

![image](https://user-images.githubusercontent.com/16324958/61723299-c6c9eb00-ad63-11e9-9fa7-48804d2f0e46.png)

5. What is your machine environment used (including version of kernel & php & gcc) ?

![image](https://user-images.githubusercontent.com/16324958/61723220-a69a2c00-ad63-11e9-96e1-10ae54004a15.png)

![image](https://user-images.githubusercontent.com/16324958/61723343-dcd7ab80-ad63-11e9-9156-f2e0b8a81313.png)

I have tried to include the provider into it's section within config file but it didn't work. It works fine if serving using "php artisan serve"

**Comment by juberjj** [comment]
Just to add something here, I can install a package called "laravels" that wraps swoole and that page renders just fine. The downside for me is to have another package installed. Please let me know if am I missing something here.

**Comment by doubaokun** [comment]
@juberjj Could you clarify what `Nova` and `Vayager` are?

**Comment by juberjj** [comment]
Hey @doubaokun, just laravel frameworks.

**Comment by doubaokun** [comment]
There’s not enough information about the question is relevant to Swoole.

**Comment by juberjj** [comment]
@doubaokun Again, another dismissive attitude. Didn't even formulate relevant questions to try to address / investigate it.

**Comment by doubaokun** [comment]
Hi @juberjj The bugs you have reported are related to bugs of your application but not Swoole. Please remove all application layer logics before reporting bugs of Swoole.
