### ISSUE TITLE
global variables and threads

### ISSUE THREAD

**Issue by rspadim** [swoole/swoole-src#2712]
Hi folks,

I'm trying to understand thread and swoole

i did this counter at global variable. It's the right way? should i consider other option (swoole table/atomic)? is "thread safe" do this, or a lock should be used when $counter++ ?

code:
```php
<?php
@dl('swoole.so');

$counter = 0;
$http = new swoole_http_server('php', 8080);
$http->set([
    'worker_num' => 4,
]);

$http->on('request', function ($request, $response) use (&$counter) {
#    echo "counter:";
#    print_r($request);
#    echo "\n";
    $response->header("Content-Type", "text/plain");
    $response->end($counter++);
});
$http->start();

```

**Comment by huanghantao** [comment]
@rspadim 
Because the parameters in the closure are passed by reference, you need to lock.
You can print the value of counter, then use the script swoole-src/benchmark/co_run.php to perform a pressure test, for example:
```shell
php co_run.php -n 10000 -s http://127.0.0.1:8080 -v
```
You will find that the value of counter is less than 10000.

**Comment by huanghantao** [comment]
By the way, I use xdebug to print the reference count of $counter, there are some questions.
code show as below:
```php
<?php

$counter = 0;
xdebug_debug_zval('counter');
$http = new swoole_http_server('php', 8080);
$http->set([
    'worker_num' => 4,
    'enable_coroutine' => false,
]);

$http->on('request', function ($request, $response) use (&$counter) {
    xdebug_debug_zval('counter');
    $response->header("Content-Type", "text/plain");
    $response->end($counter++);
});
xdebug_debug_zval('counter');
$http->start();
```
When I start the server, the output is as follows:
```shell
~/codeDir/phpCode/test/swoole # php issue_2712.php 
counter: (refcount=0, is_ref=0)=0
counter: (refcount=2, is_ref=1)=0
```
When I use curl to request a server, the output is as follows:
```shell
counter: (refcount=3, is_ref=1)=0
```
Why is the reference count here changed to 3?

**Comment by rspadim** [comment]
Probably chrome favico.ico 403 return that you didn’t checked at network traffic

**Comment by doubaokun** [comment]
@rspadim The global variable are isolated within each worker process, but should not be updated crossing workers. Please use external storage like `swoole_table` or Redis, MySQL.

**Comment by doubaokun** [comment]
@huanghantao xdebug is not supported by Swoole yet. Could you please open a new thread about xdebug?

**Comment by huanghantao** [comment]
@doubaokun 
I have disable the coroutine.

**Comment by doubaokun** [comment]
I am closing this thread for now, feel free to open a new issues about the xdebug issue.
