### ISSUE TITLE
kill master process sub process 也退出了

### ISSUE THREAD

**Issue by salterping** [swoole/swoole-src#2713]
Please answer these questions before submitting your issue. Thanks!

swoole  版本
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.5
Built => Jul 19 2019 09:24:42
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.0j  20 Nov 2018
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

process进程管理的时候，主进程kill后，子进程直接退出了，这个可以设置吗？主进程kill后，子进程事情处理完成后再退出？

**Comment by matyhtf** [comment]
监听一下 SIGTERM 信号，自行退出。

**Comment by salterping** [comment]
> 监听一下 SIGTERM 信号，自行退出。

我这个是跑在容器里面的，然后swoole的启动是采用非守护进程的方式，容器重启的时候，会发送SIGTERM信号，可是无法捕获这个信号哈？这个要怎么处理
`/**
 * 启动进程管理
 */
public function start()
{
    if (! $this->_configName) {
        die("please set config name first");
    }
    $this->processCheck();
}

/**
 * 进程检测
 */
public function processCheck()
{

    $this->initProcess();
    while($ret = \swoole_process::wait(false)) {
        switch ($ret['signal']){
            case SIGUSR1:
                $this->restartWorker();
                break;
            case SIGTERM:
                $this->gracefulExit();
                break;
            default:
                $this->workerExit($ret);
                break;
        }
    }
    swoole_process::signal(SIGINT, function($signo) {
        echo 'ProcessSignoSIGINT' . "\n";
    });
    swoole_process::signal(SIGTERM, function($signo) {
        echo 'ProcessSignoSIGTERM' . "\n";
    });
    sleep(1);
    $this->processCheck();
}`

**Comment by matyhtf** [comment]
在 UserProcess 进程中使用 pcntl_signal 或 Process::signal 监听 SIGTERM 信号，实现退出逻辑。
