### ISSUE TITLE
\Swoole\Timer::tick下执行Swoole\Process，PHP Fatal error:  Uncaught Swoole\Error: must be forked outside the coroutine in Swoole\Process->start()

### ISSUE THREAD

**Issue by kcloze** [swoole/swoole-src#2716]
swoole 4.4.2 默认开启了协程，不允许在协程环境下 Swoole\Process->start()，造成之前的代码不兼容，有什么好的办法？全局禁用协程也不行

swoole-jobs之前基于\Swoole\Timer::tick下调用Swoole\Process实现，代码见这里：
[Swoole\Timer::tick]](https://github.com/kcloze/swoole-jobs/blob/master/src/Process.php#L252)
[Swoole\Process](https://github.com/kcloze/swoole-jobs/blob/master/src/Process.php#L152

)

**Comment by twose** [comment]
`Swoole\Coroutine::set(['enable_coroutine' => false]);`

**Comment by kcloze** [comment]
> `Swoole\Coroutine::set(['enable_coroutine' => false]);`

这个方法无效，测试了几种方法:
无效

- Swoole\Coroutine::set(['enable_coroutine' => false]);

- ini_set('swoole.enable_coroutine ','Off');

有效
- 修改php.ini 增加 swoole.enable_coroutine = 'Off'

**Comment by kcloze** [comment]
问题没解决就关了呢？

**Comment by twose** [comment]
Sorry, 前面的回答写错了, 由于现在推全协程, 所以只能通过老的异步API或是php.ini关闭, 还有一个方法是`swoole_async_set(['enable_coroutine' => false])`, 推荐使用你指出的php.ini配置的方法
这块内容有专门的文档和RFC: 
https://wiki.swoole.com/wiki/page/949.html
https://wiki.swoole.com/wiki/page/352.html

**Comment by kcloze** [comment]
那就是不能在运行灵活关闭协程，这会影响部署（其他swoole 4应用就不能同时部署），能否给用户运行时关闭协程的开关呢？

**Comment by Yurunsoft** [comment]
协程不能开进程，确实很难受

**Comment by twose** [comment]
@kcloze 
`swoole_async_set(['enable_coroutine' => false])`就是运行时的开关，协程外可以fork, 协程内多进程fork会产生安全问题
设计上可以专门部署一个manager进程来负责fork, 而不是工作进程动态fork

**Comment by huangzhhui** [comment]
> @kcloze
> `swoole_async_set(['enable_coroutine' => false])`就是运行时的开关，协程外可以fork, 协程内多进程fork会产生安全问题
> 设计上可以专门部署一个manager进程来负责fork, 而不是工作进程动态fork

那其实 Swoole 是不是就可以这样去处理？如果在协程内 fork 就改成非 Worker 进程 fork ？

**Comment by twose** [comment]
不行 不同进程上下文不一样 需要自己设计

就和SWOOLE_PROCESS的模式一样 专门有个manager进程去fork，但是一些预备工作要在start之前做好；如果是动态fork，就不是很好把控，可能一些工作做到了一半fork了，复杂的环境下，不一定能正确清理，不清理直接fork肯定会产生意料之外的问题

还有一种是使用exec，上下文无关的，安全的fork，但是不是很灵活

**Comment by hezll** [comment]
楼上写的3种办法都没有成功，老版本请用如下代码设置。
https://wiki.swoole.com/wiki/page/p-4.0.1.html

$http = new swoole_http_server('127.0.0.1', 9501);
$http->set([
    'enable_coroutine' => false, // close build-in coroutine
]);


swoole

swoole support => enabled
Version => 1.10.2

升级成功

php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.0

**Comment by kcloze** [comment]
swoole-jobs的多进程模块，没有用到http server
