### ISSUE TITLE
Swoole working perfectly on my local server but not on AWS Elasticbeanstalk

### ISSUE THREAD

**Issue by kinglexy** [swoole/swoole-src#2718]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
I installed swoole perfectly, added the extension to php.ini. I am using lumen. After running the server to test using /var/app/current php artisan swoole:http start. The server started with the response 

Starting swoole http server...
Swoole http server started: <http://0.0.0.0:9501>

And I added the 9501 port to my elasticbeanstalk loadbalancer

2. What did you expect to see?
I expect the speed to increase like on local server after hitting the port 9501

3. What did you see instead?
It's the same speed when hitting port 80 too, so its like the swoole server is not working

4. What version of Swoole are you using (show your `php --ri swoole`)?
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.3-alpha
Built => Jul 28 2019 10:19:55
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
64bit Amazon Linux/2.8.12

How can I use swoole on AWS EBS, please this is my last hope, My codebase is much, i can't risk rewriting in node... Again swoole is faster than node to my test

**Comment by doubaokun** [comment]
Swoole works in AWS Elastic beanstalk.

I think you have sorted this issues after receiving the answers in the Slack channel. Thus close this thread.

**Comment by lexy10** [comment]
I was able to solve it using EC2 directly and choosing ubuntu as my machine, not Elasticbeanstalk.

Swoole works well only in ubuntu servers and not in default Elasticbeanstalk(CentOS) except you use a custom environment.
