### ISSUE TITLE
Request: Can we make swoole.co.uk docs accessible for improvement?

### ISSUE THREAD

**Issue by stefanos82** [swoole/swoole-src#2719]
I have found a number of typos and issues that need improvement and correction; unfortunately I cannot fix them.

Can we make docs accessible so people can start fixing such typos and code issues?

This is from [Swoole Documents](https://swoole.co.uk/docs/):

![image](https://user-images.githubusercontent.com/1777466/62010627-eacb6900-b175-11e9-85d6-450898c14e8f.png)

It should be `ext-async`; also `async-src` is wrong, it should be `ext-async`.

**Comment by doubaokun** [comment]
@stefanos82 Thanks for the feedback, it is fixed on the live site. For fixing typo etc, please leave comment on the page.

**Comment by stefanos82** [comment]
It asks me to register to leave a comment.

Can't we have something simpler, that I could just insert my name, email, and message, much like we have with other commenting mechanisms that don't ask for registration? :thinking: 

I could help with documentation if it were in markdown format and was available in a repo...
