### ISSUE TITLE
Redis subscribe

### ISSUE THREAD

**Issue by crmsoft** [swoole/swoole-src#2721]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

[Code sample taken from here](https://github.com/swoole/swoole-src/blob/master/examples/coroutine/redis/sub.php)

```php
<?php
go(function () {
$redis = new  Swoole\Coroutine\Redis();
$redis->connect('127.0.0.1', 6379);
//while (true) 
{
	$msg = $redis->subscribe(array("msg_1"));
	var_dump($msg);
}
});
```

2. What did you expect to see?

After I do publish from other app to see message printed by above code

3. What did you see instead?

bool(true), in case while(true) is comment out it's printing continuously the same 

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.5
Built => Jul  2 2019 10:58:40
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1  11 Sep 2018
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 

Also I am confused what I should use Swoole\Coroutine\Redis or I should follow instructions [here](https://www.swoole.co.uk/docs/modules/swoole-async-redis-client). I did tried to follow the instructions there but without any success

**Comment by matyhtf** [comment]
sub example
----
```php
$redis = new Swoole\Coroutine\Redis();
$redis->connect('127.0.0.1', 6379);
if ($redis->subscribe(['channel1', 'channel2', 'channel3'])) {
    while ($msg = $redis->recv()) {
        list($type, $name, $info) = $msg;
        if ($type == 'subscribe') {

        }
        else if ($type == 'unsubscribe' && $info == 0) {
            break;
        }
        else if ($type == 'message') {
            var_dump($name);
            var_dump($info);
        }
    }
}
```

**Comment by crmsoft** [comment]
Thank you for quick response !
