### ISSUE TITLE
swoole 4.4.2 http2 SSL Connection Problem

### ISSUE THREAD

**Issue by ozgurhangisi** [swoole/swoole-src#2725]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I use swoole to send push notifications to Apple devices. I have 2 different servers with swoole 4.3.4 and 4.4.2. Code works very well in 4.3.4 but doesn't work in 4.4.2 

I get 403 MissingProviderToken from Apple for swoole ver 4.4.2. 

```php
        $con = new co\Http2\Client('api.push.apple.com' 443, true);
        $con->set([ 
            'timeout' => 5,
            'ssl_cert_file'=>$certFilePath,
            'ssl_key_file'=>$certFilePath,
            'ssl_hostname'=>'api.push.apple.com'
        ]);
        $con->connect();
        if (!$con->connected) {
            $last_error = 'Client Couldnt Connected Error='.$con->errMsg;
            return null;
        } else {
            $last_info = 'NEW CONNECTION';
        }
        $req = $this->push_manager()->create_push_request($topic,$notificationData);
        $cli->send($req);
        $res = $cli->recv(1);

```

2. What did you expect to see?

I see that I can successfully connect to Apple service. But when I try to send notification I get 403 MissingProviderToken from Apple for all pushes. Apple website says that this error can be related with the certificate. But same code was working for swoole 4.3.4. and I am sure that certificate file is exists and exactly same with other server. 

3. What did you see instead?

I can connect to apple service but when I tried to send notification I get 403 MissingProviderToken error. 

I saw that you changed something on  swoole http2 client in ver 4.4.2.  Can it be the reason for the error above ?

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.2
Built => Jul 26 2019 09:59:23
coroutine => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

php 7.3.8
Aws linux

**Comment by twose** [comment]
How can I test it?

**Comment by ozgurhangisi** [comment]
@twose if it works for you, I can send you valid Apple certificate, sample push token and sample code to validate the case above. But It is risky to send it from here because It will be a valid certificate and if someone do wrong things with this certificate apple can block my account. 

How can I send you these files ?

**Comment by twose** [comment]
@ozgurhangisi 
twosee@swoole.com
Thanks for your cooperation

**Comment by ozgurhangisi** [comment]
Hi @twose 

I sent sample code and pem file to your email. 

Thanks.

**Comment by twose** [comment]
@ozgurhangisi 
Thank you for your feedback, I quickly found the bug through the demo you gave.
I only requested about ten times, now you can reset your certificate.
The reason for this bug is that we refactored the HTTP2 Client in 4.4 (from async to coroutine in the kernel). Unfortunately, its testing is not enough, a stupid logic problem caused the configuration not to take effect.

**Comment by twose** [comment]
We will release a patch version this week (v4.4.3)
