### ISSUE TITLE
Worker error, exitCcode=255

### ISSUE THREAD

**Issue by juberjj** [swoole/swoole-src#2726]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Working with laravel-s serving a PHP app

2. What did you expect to see?
Version 4.3.6 works ok, no error messages no issues.

3. What did you see instead?
Updated to latest version 4.4.2 and I'm getting the following issue

![image](https://user-images.githubusercontent.com/16324958/62213793-9efa0900-b39b-11e9-851b-b712b60d36be.png)

![image](https://user-images.githubusercontent.com/16324958/62213874-d8cb0f80-b39b-11e9-9a4d-5b37f9c14c52.png)

5. What is your machine environment used (including version of kernel & php & gcc) ?

![image](https://user-images.githubusercontent.com/16324958/62213833-bfc25e80-b39b-11e9-932a-abb03c368e95.png)

Many thanks in advance

**Comment by twose** [comment]
开启RuntineHook后，IO操作全部变为由协程调度的异步操作，即所有IO操作必须在协程中进行，请阅读文档，自行修改代码。
