### ISSUE TITLE
Swoole4.4.2 Swoole\Mysql模块无法使用呢

### ISSUE THREAD

**Issue by laohekou** [swoole/swoole-src#2727]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by laohekou** [comment]
![image](https://user-images.githubusercontent.com/32082656/62269894-07fa8300-b467-11e9-9d3d-4d4387e7c152.p

**Comment by sy-records** [comment]
4.3.0版本移除了所有异步模块, 详见 [独立异步扩展](https://wiki.swoole.com/wiki/page/p-async_ext.html) 或 [4.3.0更新日志](https://wiki.swoole.com/wiki/page/p-4.3.0.html#entry_h2_5)
