### ISSUE TITLE
swoole request中mysqli连接数据库

### ISSUE THREAD

**Issue by chenye2017** [swoole/swoole-src#2728]
swoole版本是4.3.5

你好，我用swoole 生成了一个http server， 我在onRequest事件中用mysqli连接了数据库，没有close，然后逻辑执行时间比较长，超过了mysql 的wait_timeout, mysql主动断开了连接，netstat查看的时候发现php连接mysql 是close_wait状态，过了一会这个tcp连接消失了，可是我看处理这个request的work进程id也没变，是因为work进程重启了吗，到这tcp连接消失，类似php-fpm 单个进程接受了某一数量请求（我记得swoole好像也能配置，但我的配置项中没有添加这个参数）

当我在回调事件外写mysqli的连接的时候,没有close， 这个tcp连接一直存在也是close_wait状态，符合预期，不知道为什么回调事件中那个tcp连接会主动消失

**Comment by matyhtf** [comment]
在代码中进行 mysql 断线重连

**Comment by matyhtf** [comment]
https://wiki.swoole.com/wiki/page/350.html

**Comment by chenye2017** [comment]
可能我表达的不清楚，其实是想问: 为什么request 事件中我连接mysql的tcp在close_wait之后 过了一小会主动消失，我看 work进程id没有改变，是重启了嘛~，但是直接写在request事件外这个close_wait的tcp会一直存在（全程都只有mysqli->connect，没有mysqli->close ）

**Comment by GXhua** [comment]
你又再次使用这个连接了把 比如发送数据之类的，服务端会直接发送rst分节  结束掉这个连接




------------------ 原始邮件 ------------------
发件人: "四月是谁的谎言"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 下午5:41
收件人: "swoole/swoole-src"<swoole-src@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [swoole/swoole-src] swoole request中mysqli连接数据库 (#2728)




可能我表达的不清楚，其实是想问: 为什么request 事件中我连接mysql的tcp在close_wait之后 过了一小会主动消失，我看 work进程id没有改变，是重启了嘛~，但是直接写在request事件外这个close_wait的tcp会一直存在（全程都只有mysqli->connect，没有mysqli->close ）
