### ISSUE TITLE
Socialite plugin function fails with Swoole

### ISSUE THREAD

**Issue by juberjj** [swoole/swoole-src#2729]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Socialite plugin function fails

2. What did you expect to see?

Page should open social media connection - Dropbox, Google, OneDrive and so on

3. What did you see instead?

![image](https://user-images.githubusercontent.com/16324958/62352324-cec22180-b4ff-11e9-965a-b1e749a4fdd8.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.4.2

5. What is your machine environment used (including version of kernel & php & gcc) ?

Fedora 29 - PHP 7.3 

![image](https://user-images.githubusercontent.com/16324958/62352556-5740c200-b500-11e9-95c6-929629e6d6b4.png)

**Comment by twose** [comment]
It looks like DNS resolve failed, but I can't see it has anything to do with swoole.

**Comment by juberjj** [comment]
hi @twose  It does work if I use php artisan serve, only when I have swoole behind that I get that error.

There's a redirection in place that pushes the user to localhost, when then I change it to the right callback uri it pops the message from the provider

![image](https://user-images.githubusercontent.com/16324958/62369530-d1387180-b527-11e9-8e7a-142c6460ddd5.png)

**Comment by juberjj** [comment]
hey @twose  just to give you an update, by changing the dispatch_mode on swoole section it did sort this issue. I'm still doing some tests and investigations but I'll get back here with a bit more feedback.

**Comment by twose** [comment]
I still can't understand your question, I want to know you change `dispatch_mode` from what to what

**Comment by juberjj** [comment]
Hi @twose , I'm using swoole under the hood but I'm using now laravel-s in order to serve  the application. Within their config file they have a section dedicated to swoole configuration, pretty much the same as swooletw (another server). Following the information from the link below that I've decided to tweak the dispatch_mode achieving the desired result. Although I'm using those servers the part that was causing the error is totally swoole related.
 https://www.swoole.co.uk/docs/modules/swoole-server/configuration

**Comment by doubaokun** [comment]
@juberjj please remove the application layer logics and provide a minimum php script to reproduce the issue.
