### ISSUE TITLE
能不能把源码的注释都改成英文的

### ISSUE THREAD

**Issue by jerryli1** [swoole/swoole-src#273]
因为编码问题，我下载的源码里面的中文，都变成乱码了。

**Comment by matyhtf** [comment]
正在改，之前由于历史原因遗留了部分中文注释。

**Comment by firedtoad** [comment]
我有一份 翻译好的

2016-07-13 0:56 GMT+08:00 WANJO CHAN <notifications@github.com>:

**Comment by ipersi** [comment]
不如改成双语的，这样也方便英文不好的同学查看源码，虽然注释的源码比较简单，但是觉得还是有用的。
