### ISSUE TITLE
Coroutine\Redis->set的一点小问题

### ISSUE THREAD

**Issue by ppyupp** [swoole/swoole-src#2730]
文档上写着返回值是bool, 当我使用了options参数

例>$redis->set( 'key', '123', [ 'nx', 'ex' => 20 ] );

如果key存在,返回的是null, 而不是false, 这点上卡了好久,,,建议失败后都返回false

-_-

**Comment by juberjj** [comment]
Hey @ppyupp, what version of swoole do you have installed?
I had a similar issue on 4.4.2 but it did work with 4.3.6.

**Comment by matyhtf** [comment]
```
Return value
Simple string reply: OK if SET was executed correctly. Null reply: a Null Bulk Reply is returned if the SET operation was not performed because the user specified the NX or XX option but the condition was not met.
```

根据 Redis 官方文档，当操作不允许时，返回 NULL
