### ISSUE TITLE
Process主进程自动退出

### ISSUE THREAD

**Issue by shenyisyn** [swoole/swoole-src#2731]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
  //swoole 版本升级到4.4.2。执行如下代码

```php
use Swoole\Process;
cli_set_process_title("master");
$manager=new Process(function(Process $process){
    cli_set_process_title("manager");
    while(true) {
        echo "a".PHP_EOL;
        sleep(1);
    }
});
Process::signal(SIGCHLD, function($sig) { //文档代码
    //必须为false，非阻塞模式
    while($ret =  Process::wait(false)) {
        echo "PID={$ret['pid']}\n";
    }
});
$manager->start();
```
2. What did you expect to see?
   主进程不退出
  

3. What did you see instead?
   实际上运行的时候，主进程(master)直接退出了。只留下manager在不断的echo a;

4. What version of Swoole are you using (show your `php --ri swoole`)?

   swoole 版本 4.4.2

5. What is your machine environment used (including version of kernel & php & gcc) ?
  PHP版本PHP 7.2.10
  操作系统 centos7装docker18.03，容器操作系统 alpine 3.6 、内核3.10.0-327.el7.x86_64
  gcc版本 6.4 
  使用pecl install swoole-4.4.2 安装扩展（一律为默认设置）

**Comment by matyhtf** [comment]
从`4.4`版本开始底层将不再将信号监听作为 EventLoop Exit 的 block 条件。有两个解决方案：

1. 添加一个 tick 定时器
2. 改为阻塞等待进程退出

```php
use Swoole\Process;
cli_set_process_title("master");
$manager=new Process(function(Process $process){
    cli_set_process_title("manager");
    while(true) {
        echo "a".PHP_EOL;
        sleep(1);
    }
});

   $ret =  Process::wait();
        echo "PID={$ret['pid']}\n";
    

```
