### ISSUE TITLE
In SWOOLE_KEEP mode, asynchronous security restart invalid

### ISSUE THREAD

**Issue by laynefyc** [swoole/swoole-src#2738]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Server: max_request=10
Client: $swooleClient = new swoole_client(SWOOLE_SOCK_TCP|SWOOLE_KEEP)

客户端请求时添加 SWOOLE_KEEP 配置，服务端在请求达到max_request时会异步重启进程，此时客户端recv()会得到false，服务端的旧Worker没完成所有事件就自行退出了。

2. What did you expect to see?

客户端请求时添加 SWOOLE_KEEP 配置，在 max_request触发时也可以实现异步安全重启。

3. What did you see instead?

服务端max_request触发时客户端recv()得到了false

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.0-alpha
Built => May 13 2019 15:06:20
coroutine => enabled
kqueue => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
brotli => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (including version of kernel & php & gcc) ?

mac与linux问题都存在

**Comment by twose** [comment]
这版本号太迷了, 不补充信息此issue直接忽略了

**Comment by laynefyc** [comment]
应该不是特定版本的关系，我尝试过 4.4.0-alpha，1.9.23， 4.3.5  都有该问题。

**Comment by matyhtf** [comment]
你需要設置 length 或 eof 协议处理，这样 worker 进程在 onReceive 收到的就是完整的包。max_request 就可以正确处理。另外，如果你用了 SWOOLE_KEEP ，那需要验证 request id

**Comment by laynefyc** [comment]
> 你需要設置 length 或 eof 协议处理，这样 worker 进程在 onReceive 收到的就是完整的包。max_request 就可以正确处理。另外，如果你用了 SWOOLE_KEEP ，那需要验证 request id

感谢解答。我需要使用SWOOLE_KEEP，但是不知道验证 request id是在哪里做？异步安全重启时 onReceive 已经不能触发，只看到触发了onWorkerStop。
