### ISSUE TITLE
问题解决，监听 WorkerExit 事件，完成清理即可正常退出。

### ISSUE THREAD

**Issue by baoqianduan666** [swoole/swoole-src#2739]
问题解决，监听 WorkerExit 事件，完成清理即可正常退出。

_Originally posted by @NHZEX in https://github.com/swoole/swoole-src/issues/2714#issuecomment-515655225_
老哥，你咋解决的，贴个代码呗

**Comment by NHZEX** [comment]
> 问题解决，监听 WorkerExit 事件，完成清理即可正常退出。
> 
> _Originally posted by @NHZEX in [#2714 (comment)](https://github.com/swoole/swoole-src/issues/2714#issuecomment-515655225)_
> 老哥，你咋解决的，贴个代码呗

建议参考这里：https://wiki.swoole.com/wiki/page/775.html
