### ISSUE TITLE
最新的1.7.17 任务投递出错

### ISSUE THREAD

**Issue by rainbowgamer** [swoole/swoole-src#274]
在1.7.16下用 $server->task($data,0) 正常的,到了1.7.17就发现 投递到的taskworker 不是我所需要的那个taskworker,应该是有bug了; 因为我专门指定了0号taskworker作为一个逻辑处理器,所以需要指定正确的taskworker

**Comment by matyhtf** [comment]
第2个参数是超时时间，并不是目标Worker进程ID。http://wiki.swoole.com/wiki/page/145.html

**Comment by matyhtf** [comment]
感谢你的反馈。这里确实存在BUG

**Comment by matyhtf** [comment]
请检查 你的 server配置中是否有
    'task_ipc_mode' => 3,
    'message_queue_key' => 0x70001001,

**Comment by matyhtf** [comment]
最新版本测试不存在此问题。
