### ISSUE TITLE
Send message to swoole http server process from other script

### ISSUE THREAD

**Issue by roquie** [swoole/swoole-src#2741]
It's a just question to development team. Not a bug.

I would like to reload server (http) when it turned on. From other script. How I do it? 

I need an analogue to 
https://til.hashrocket.com/posts/714e96633c-reload-the-nginx-configuration

P.S. Server running in Docker and I would like to `reload` it when I connect to running container. Without restart of main process.

**Comment by matyhtf** [comment]
kill -USR1 master_PID

**Comment by roquie** [comment]
Thanks.
