### ISSUE TITLE
[疑问]block or unblock?

### ISSUE THREAD

**Issue by jp928** [swoole/swoole-src#2742]
```$serv = new Swoole\Http\Server("127.0.0.1", 9502);

$serv->on('Request', function($request, $response) {
    //等待10 seconds后向浏览器发送响应
    Swoole\Coroutine::sleep(10);
    $response->end("<h1>Hello Swoole!</h1>");
});

$serv->start();
```

我在浏览器开了4个tab.（4个worker) 理想状态下4个tab应该同时响应。但是事实上确实每隔10秒响应一个。是不是哪里有问题？

**Comment by jp928** [comment]
Just rewrite in english in case someone can explain.
I made a snippet as below to test concurrency.
```
$serv->on('Request', function($request, $response) {
    //waiting for 10 seconds
    Swoole\Coroutine::sleep(10);
    $response->end("<h1>Hello Swoole!</h1>");
});

$serv->start();
```

Then I opened 4 tabs in browser to test. My expectations is after 10 seconds, all tabs should be able to get response. However, they are blocked. After every 10 seconds I will get a tab works.

**Comment by Yurunsoft** [comment]
用 ab 测试一下，浏览器有时候有并发限制

**Comment by sy-records** [comment]
用的chrome浏览器吗？chrome会对完全一样的url做并发请求限制。可以在请求时加上一个随机数，例如127.0.0.1:9501/?t=1,127.0.0.1:9501/?t=2,127.0.0.1:9501/?t=3 @jp928

**Comment by jp928** [comment]
@sy-records 谢谢回复。
我查了一下 chrome 并发数量是6。 为什么我4个tab 就不行了？

**Comment by matyhtf** [comment]
使用 curl 或者 ab 测试，请勿使用 chrome
