### ISSUE TITLE
swoole_http_server() dynamic worker_num possible

### ISSUE THREAD

**Issue by petrich** [swoole/swoole-src#2744]
Wonderfull Project :+1: 

Question:

Is there any way configure swoole_http_server() having dynamic "worker_num" ?

Like php-fpm.

Example: 
- Start 2 worker process of the http server
- Grow up dynamicly to, lets say, 30 worker process... (in case of many concourent requests)
- But kill them again after ttl of seconds of inacitivity

Thank you.

**Comment by matyhtf** [comment]
Thanks for your proposal, the dynamic management process is very complex.
May cause a bug. We will consider this feature

**Comment by sshymko** [comment]
Just an idea. A custom [dispatch function](https://www.swoole.co.uk/docs/modules/swoole-server/configuration#dispatch_func) can implement worker process management. It will not be able to spawn or kill worker processes, however, it may choose to not route any requests to some workers to idle them (and restart if necessary). The dispatch function can aggregate statistics of incoming requests and use to decide how to route them to the pool of available workers. Setting `worker_num` would then define the limit of active worker processes.

**Comment by matyhtf** [comment]
It is difficult to implement this feature and there are no plans at this time

**Comment by foremtehan** [comment]
Wish this happens in swoole
