### ISSUE TITLE
swManager_check_exit_status: worker#4[pid=30410] abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by LYH950812** [swoole/swoole-src#2746]
WARNING	swManager_check_exit_status: worker#4[pid=30410] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.4.3, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

**Comment by twose** [comment]
You can read How to report a bug doc before submitting any bug reports: #2000

**Comment by matyhtf** [comment]
@LYH950812 https://wiki.swoole.com/wiki/page/p-issue.html 
请按照上面的步骤跟踪问题，将信息发到 issue 中
