### ISSUE TITLE
Swoole with SlimFramework latents slower than normal

### ISSUE THREAD

**Issue by ismummy** [swoole/swoole-src#2748]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I setup swoole with slim framework on Aws EC2, and start successfully, I run a benchmark on it and the speed is extremely slow compared to the normal slim setup without swoole, the same setup works perfectly on my local machine.

**Slim Swoole Benchmark**
```
Running 10s test @ http://18.130.186.62:8081/
  4 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.24s   386.20ms   2.00s    56.87%
    Req/Sec    60.33     58.31   267.00     84.72%
  992 requests in 10.10s, 311.25KB read
  Socket errors: connect 151, read 0, write 0, timeout 308
Requests/sec:     98.26
Transfer/sec:     30.83KB
```

**Slim without Swoole on same server**
```
Running 10s test @ http://18.130.186.62/swoole
  4 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   175.38ms  137.63ms   1.50s    91.18%
    Req/Sec   107.30     92.91   370.00     72.52%
  3646 requests in 10.07s, 1.82MB read
  Socket errors: connect 151, read 0, write 0, timeout 141
Requests/sec:    362.03
Transfer/sec:    185.26KB
```

2. What did you expect to see?

I expect the swoole setup to me faster than the normal setup as promise by swoole

3. What did you see instead?

The speed is slower than the normal slim setup

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.3
Built => Aug  8 2019 09:33:15
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1c  28 May 2019
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

PHP 7.3.8-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug  7 2019 09:52:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.8-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by twose** [comment]
I don't know much about slim.
If you have not parallelized your code, Swoole can not improve your performance
Swoole is not magic, you may need to understand how it works

**Comment by ismummy** [comment]
The codebase has been restructured with async in mind and yet not improvement

**Comment by twose** [comment]
can you show me your code, otherwise I don't know how to answer your question

**Comment by ismummy** [comment]
[Slim_swoole](https://github.com/ismummy/slim_swoole)

**Comment by twose** [comment]
I can't find `Swoole\Runtime::enableCoroutine`

**Comment by twose** [comment]
But you are using sync blocked PDO, you need to call `Swoole\Runtime::enableCoroutine`, and use the connection pool.
You should read README.md

**Comment by ismummy** [comment]
I enabled Swoole\Runtime::enableCoroutine and commented Db connection, yet no improvement

**Swoole Benchmark** 
`Running 10s test @ http://18.130.186.62:8081/
  4 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   243.83ms   31.05ms 627.97ms   86.72%
    Req/Sec   253.37    126.35   696.00     69.87%
  9990 requests in 10.09s, 2.91MB read
  Socket errors: connect 151, read 0, write 0, timeout 0
Requests/sec:    990.12
Transfer/sec:    295.32KB`

**Slimframework without swoole**

`Running 10s test @ http://18.130.186.62/swoole
  4 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   126.02ms   53.91ms   1.74s    96.06%
    Req/Sec   162.09    135.13   520.00     69.13%
  4958 requests in 10.10s, 2.48MB read
  Socket errors: connect 151, read 0, write 0, timeout 137
Requests/sec:    491.01
Transfer/sec:    251.26KB
`

**Comment by doubaokun** [comment]
There’s not enough information about the question is relevant to a bug or issue of Swoole.
