### ISSUE TITLE
swoole_event_add must run in cli?

### ISSUE THREAD

**Issue by w3yyb** [swoole/swoole-src#275]
I use https://github.com/swoole/mysql-async  ,find  swoole_event_add  can't work with php-fpm & nginx ,and will halt the remain php code running any more.,,,  but can run in cli.

**Comment by w3yyb** [comment]
swoole version:   1.7.17-rc1 ,php 5.5.25

**Comment by matyhtf** [comment]
yes, cannot use event loop api in php-fpm/apache.
