### ISSUE TITLE
How can I see coroutine http2_client GOAWAY payload data ?

### ISSUE THREAD

**Issue by ozgurhangisi** [swoole/swoole-src#2759]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

We use http2_client to send push notification to apple devices. Apple closes the connection in the middle of the sending/receiving process. Apple document says that : APNs may also terminate a connection by sending a GOAWAY frame. The payload of the GOAWAY frame includes JSON data with a reason key. 

How can we see GOAWAY frame payload data ? Because it's happening so much and we can not see the root cause to fix the problem. 

2. What did you expect to see?

I need to see GOAWAY frame payload data to fix the connection problem.

3. What did you see instead?

I can not see GOAWAY payload data.

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.3
Built => Aug  3 2019 08:09:04
coroutine => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

php 7.3.8,  aws linux

**Comment by twose** [comment]
after the connection closed, you can read the following properties to get the information of goaway frame:
$client->errCode
$client->errMsg
$client->serverLastStreamId

**Comment by ozgurhangisi** [comment]
@twose Thanks for the response. Now there is another problem.

I see lots of errCode=3 and errMsg=Window size overflow for stream: 0. errors. Almost every request that I send to apple notification system has problem. Connection is closing  and I see Window size overflow for stream: 0. message on error log ($client->errMsg value) 

So I'm not sure but I suspect that this error can be related with swoole http2 client?

**Comment by twose** [comment]
Can you give me the code?
The problem may be related to the HTTP2 flow control window size, Apple may have special restrictions

**Comment by ozgurhangisi** [comment]
@twoose I'm quite busy this week but next week I'll try to reproduce the error with my apple certificate and send you to the summarized code via email.

Thanks,
Ozgur.

**Comment by twose** [comment]
@ozgurhangisi Thanks for your feedback
