### ISSUE TITLE
why swoole_timer_tick can't use together with while

### ISSUE THREAD

**Issue by xuanxuan2016** [swoole/swoole-src#2766]
function timeout($tm) {
    echo time() . ": Timeout #$tm\n";
}
//no output
$timer1 = swoole_timer_tick(1000, 'timeout', 1);

while(1){
    sleep(1);
   //output
    echo "ff\n";
}

**Comment by matyhtf** [comment]
请阅读 Swoole 文档，使用 协程相关 API 实现程序代码，使用 hook_flags 设置
