### ISSUE TITLE
EPOLLIN handle failed、Resource temporarily unavailable、swTaskWorker_onPipeReceive

### ISSUE THREAD

**Issue by bain2018** [swoole/swoole-src#2767]
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.4
Built => Aug 19 2019 04:23:23
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

目前出现

WARNING	swTaskWorker_onPipeReceive(:226): read(192, 8192) failed, Error: Resource temporarily unavailable[11]
WARNING	swReactorEpoll_wait(:260): EPOLLIN handle failed. fd=192, Error: Resource temporarily unavailable

在多的信息，水平有限哦

**Comment by matyhtf** [comment]
请提供一个可以稳定重现的 demo 程序代码。

**Comment by Maplejay** [comment]
请问如何解决的呢
