### ISSUE TITLE
How to detect if client disconnected from HTTP server?

### ISSUE THREAD

**Issue by RWGuy** [swoole/swoole-src#2769]
Please answer these questions before submitting your issue. Thanks!

**Goal:**
I need to be able to make sure the client is still live. Right now it appears swoole will send data to even dead (disconnected) clients. Is there any way to verify that the http client is actually still connected?

1. What did you do? If possible, provide a simple script for reproducing the error.

I tested an HTTP server like the following:

```
$http = new swoole_http_server('127.0.0.1', 9501, SWOOLE_BASE);
$http->on('start', function ($server) {
    echo "Swoole https server is started at http://127.0.0.1:9501\n";
});

$http->on('request', function ($request, $response) use ($http) {
    sleep(30); // simulate a lot of work to finish request
    // WANT TO MAKE SURE CLIENT STILL CONNECTED
    var_dump($http->getClientInfo($request->fd));
});

$http->start();
```

2. What did you expect to see?
I want to be able to verify if the client is connected or not, but there does not appear to be any way to do this. This is because part of the request can be stopped if the client disconnects and other work may need to be done if the client disconnects (like rolling back the work done)

3. What did you see instead?
No method to detect client disconnect

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.4.4

**Comment by twose** [comment]
Swoole will generate a NOTICE when sending data to a disconnected connection, we usually ignore it (unless a lot of clients are disconnected)

In general, you only need to check the return value.

**Comment by RWGuy** [comment]
I am testing the return values of the write operations and they return "true" even when the client is disconnected. Is there really no way to tell if the client socket is still active? It is very important especially in the case of long-polling applications.

If swoole is currently incapable of this, do you think it is something that could be added? I think at a minimum even if there is not a direct way to test this that write operations should return "false" when writing to a dead socket. This is standard behavior for PHP sockets, so it makes sense it should be replicated when writing to swoole sockets: https://www.php.net/manual/en/function.socket-write.php

```
$http = new swoole_http_server('127.0.0.1', 9501, SWOOLE_BASE);
$http->on('start', function ($server) {
    echo "Swoole https server is started at http://127.0.0.1:9501\n";
});

$http->on('request', function ($request, $response) use ($http) {
    sleep(30); // simulate a lot of work to finish request
    // WANT TO MAKE SURE CLIENT STILL CONNECTED
    var_dump($http->getClientInfo($request->fd));
    var_dump($response->header('Content-Type', 'text/plain'));
    var_dump($response->write(sprintf("TEST\n")));
    var_dump($response->end('.'));
});

$http->start();
```

**Comment by twose** [comment]
Your sleep blocks the event loop and causes it to have no chance to update the connection state
If your program is completely sync blocked, I suggest you use fpm

**Comment by doubaokun** [comment]
@RWGuy this should be sorted out at application rather than the transport layer.

For long-polling applications, a token or offset can be used to sync the status from server-side to client-side, eventually consistent if the exception happens.

**Comment by sshymko** [comment]
If Swoole notice of client disconnect is undesirable, it can be prevented by configuring a reverse proxy in front of Swoole (if there's one) to maintain the connection when the client drops off.

Nginx config:
```nginx
proxy_ignore_client_abort   on;
proxy_pass                  swoole_backend;
```

**Comment by GHLover** [comment]
Thanks guys. The was caused by using sleep(). Once Co::sleep() was used it detected disconnected clients well.
