### ISSUE TITLE
swoole_websocket_server

### ISSUE THREAD

**Issue by lizhichao** [swoole/swoole-src#277]
在swoole_websocket_server保留send方法

**Comment by matyhtf** [comment]
无效的问题，请详细说明。

**Comment by lizhichao** [comment]
计划用swoole_websocket_server做im的后端，swoole_websocket_server继承值swoole_http_server 和 swoole_server。在客户端支持websocket 就用websocket，如果不支持websocket 就用Ajax长连接。swoole_websocket_server继承swoole_http_server 很容易能获取到Ajax发生过来的信息。但是在当前请求不会回复操作其他后台挂起的请求。打算用swoole_server的send来响应http请求。send可以指定一个fd发送信息。但是在swoole_websocket_server里面send被重写了。让我用push。但是push不能响应Ajax请求。每当我做的时候要把 swoole_websocket_server 重写的send 删了。 希望swoole_server的send在他得子类里面能保存可用用

**Comment by matyhtf** [comment]
你用的swoole版本是多少，最新的1.7.17 已经去掉了重写，允许直接调用send方法了。

**Comment by lizhichao** [comment]
感谢！！！
