### ISSUE TITLE
[Request] DTLS support

### ISSUE THREAD

**Issue by neoteknic** [swoole/swoole-src#2774]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Support DTLS (example : connecting with hue entertainment)

2. What did you expect to see?
DTLS support

3. What did you see instead?
no support ?

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.4.4

5. What is your machine environment used (including version of kernel & php & gcc) ?
WSL debian php 7.3

**Comment by need-sleep** [comment]
I second this. For one thing, WebRTC Datachannels are just SCTP over UDP/DTLS.

**Comment by need-sleep** [comment]
> I second this. For one thing, WebRTC Datachannels are just SCTP over UDP/DTLS

With DTLS coro sockets [usrsctp](https://github.com/sctplab/usrsctp) can be used to create native swoole datachannels

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/8b052d15b37d53f3c0d6f4237cbc88b8ee86fa30
