### ISSUE TITLE
Proposal: upload filename generation function

### ISSUE THREAD

**Issue by sshymko** [swoole/swoole-src#2775]
## Problem

Swoole setting `upload_tmp_dir` allows to configure a directory containing uploaded files. Temporary filenames are generated randomly to protect from unauthorized access to files.
However, randomness of filenames prevents tests from comparing against fixture contents.
Tests become more complicated as they have to override random filenames with fixture path:
- [tests/swoole_http_server/upload_file_array_default.phpt](https://github.com/swoole/swoole-src/pull/2773/files#diff-fddc401c9b41a2a551d08a332faa1363R54)
- [tests/swoole_http_server/upload_file_array_parsed.phpt](https://github.com/swoole/swoole-src/pull/2773/files#diff-16e1a2ab23b28eecccf722a8b3def22fR55)

## Solution

Introduce configuration for custom filename generation function, for example:
```php
$server->set([
    'upload_tmp_func' => function ($path) {
        $name = strtr(base64_encode(random_bytes(6)), '+/', '-_');
        return "$path/swoole.upfile.$name";
    }
]);
```

Fixture upload filename in tests:
```php
$count = 0;
$server->set([
    'upload_tmp_func' => function () use (&$count) {
        return '/var/swoole.upfile.fixture' . ++$count;
    }
]);
```

**Comment by sshymko** [comment]
@twose 
This proposal is related to PR #2773 because its tests are good use case for the feature.

**Comment by matyhtf** [comment]
Uploading files depends on the tmpname function provided by the OS.
User-defined file names may be duplicated
