### ISSUE TITLE
进程信号退出问题

### ISSUE THREAD

**Issue by foxconndmd** [swoole/swoole-src#278]
在监听事件后调用swoole_process::wait()不等待子进程完成：
<?php
function callback_function(swoole_process $worker)
{
  for ($i = 1; $i <= 10; $i++) {
    echo $i.PHP_EOL;
    sleep(1);
  }
  $worker->exit(0);
}

$process = new swoole_process('callback_function');
$pid = $process->start();
$workers[$pid] = $process;
swoole_process::signal(SIGINT, function($signo) {
  echo "shutdown.";
  $ret = swoole_process::wait();
  $pid = $ret['pid'];
  echo "Worker Exit, PID=".$pid.PHP_EOL;
});

**Comment by matyhtf** [comment]
子进程退出并不触发SIGINT，而是SIGCHLD

**Comment by foxconndmd** [comment]
谢谢回复，我的问题没描述清楚。
我测试 的是在cli下运行进程时通过ctrl-c发送SIGINT希望父进程等待子进程完成并退出，但是父进程在收到SIGINT信号后不等待子进程完成就直接退出了。
另通过kill发送SIGINT信号正常。

**Comment by matyhtf** [comment]
如果想要杀掉子进程应该使用 swoole_process::kill 。父进程处理完信号后并不会退出，它会继续等待新的信号。所以你需要调用 swoole_event_exit 强制退出。
