### ISSUE TITLE
编译发布版4.4.4出错

### ISSUE THREAD

**Issue by aLoNeIT** [swoole/swoole-src#2780]
在git上和oschina上下载4.4.4的源码包，进行编译。
使用编译器gcc9.2.0.
但是编译途中报错
/server/reeactor_process.cc:416:14:error: label '_fail' used but not defined
请问下如何解决这个问题？
4.4.3版本顺利编译。

**Comment by sayhero** [comment]
请问解决了吗？我也出现了这个问题

**Comment by aLoNeIT** [comment]
> 请问解决了吗？我也出现了这个问题

目前解决方案是换成4.4.3编译

**Comment by twose** [comment]
系统不支持RESUE_PORT导致, 已在master修复, 请在下个版本(v4.4.5)升级
