### ISSUE TITLE
运行hyperf框架报错的问题

### ISSUE THREAD

**Issue by wilbur-oo** [swoole/swoole-src#2781]
1. What did you do? If possible, provide a simple script for reproducing the error.

composer create-project hyperf/hyperf-skeleton
php bin/hyperf.php start

2. What did you expect to see?

报错提示这是一个swoole错误,但是我不太确定,希望答疑

3. What did you see instead?

![image](https://user-images.githubusercontent.com/7148309/63680557-8956f280-c826-11e9-97c0-e0806cb17a7f.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?

![image](https://user-images.githubusercontent.com/7148309/63680596-9a9fff00-c826-11e9-9c7e-547b7b6be7fa.png)

5. What is your machine environment used (including version of kernel & php & gcc) ?

![image](https://user-images.githubusercontent.com/7148309/63680666-c7541680-c826-11e9-93ed-d9e09e5ffeb3.png)

**Comment by twose** [comment]
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前make clean了
2. 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴上来
```shell
USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php bin/hyperf.php start
```

**Comment by twose** [comment]
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前make clean了
2. 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴上来
```shell
USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php bin/hyperf.php start
```

**Comment by twose** [comment]
MAC下无法使用valgrind, 需要你提供能够复现的PHP代码

**Comment by wilbur-oo** [comment]
> MAC下无法使用valgrind, 先确认你是否在升级前make clean了

swoole版本更新后,本地切换了tag,都会make clean &&sudo phpize clean

刚刚rm了swoole-src,重新clone

sudo phpize
./configure \
--enable-sockets \
--enable-http2 \
--enable-mysqlnd \
--enable-debug-log
make && sudo make install

完成:

**Comment by twose** [comment]
@wilbur-oo 请将Swoole更新到master后尝试

**Comment by wilbur-oo** [comment]
> @wilbur-oo 请将Swoole更新到master后尝试

从tag4.4.4切换到master后正常了.

这类问题在mac上有跟踪的方法吗?

**Comment by twose** [comment]
MAC只能通过日志跟踪和lldb调试, 或用同等例子在Linux下跟踪
应该是AIO多线程问题导致, 已在master修复
