### ISSUE TITLE
Compile error for version 4.4.4 on Alpine linux

### ISSUE THREAD

**Issue by tehnodev** [swoole/swoole-src#2782]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
In my dockerfile:
FROM php:7.3-zts-alpine
RUN apk add build-base && apk add autoconf && pecl install swoole-4.4.4

2. What did you expect to see?
That compilation succeeded and i can add extension=swoole.so bla bla bla
Version swoole-4.4.3 compiles without problems

3. What did you see instead?
/tmp/pear/temp/swoole/swoole_http_client_coro.cc: In member function 'void http_client::reset()':
/tmp/pear/temp/swoole/swoole_http_client_coro.cc:1380:5: error: 'compress_method' was not declared in this scope
     compress_method = HTTP_COMPRESS_NONE;
     ^~~~~~~~~~~~~~~

4. What version of Swoole are you using (show your `php --ri swoole`)?
I try to compile version 4.4.4

5. What is your machine environment used (including version of kernel & php & gcc) ?
4.15.0-55-generic
php 7.3.8 with zts enabled
gcc 8.3.0

**Comment by matyhtf** [comment]
You should install `zlib-dev`

```shell
apt install zlib-dev
yum install zlib-devel
```

**Comment by zhangliang2012** [comment]
nc
