### ISSUE TITLE
开启TCPSERVER后客户端的连接被重置

### ISSUE THREAD

**Issue by lg430** [swoole/swoole-src#2787]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
当我以tcpserver的方式开始服务后, 客户端连接有千分之四的概念被重置,
linux信号104, 排查了不是backlog的问题, 
我是在docker环境中10核8G机器开启server, 客户端两个并发请求过来

> server
$serv = new \Swoole\Server($host, $port, SWOOLE_BASE, SWOOLE_SOCK_TCP);

> setting
'worker_num'           => 10,         
'reactor_num'          => 10,          
'daemonize'            => 1,         
'max_request'          => 10000,      
'dispatch_mode'        => 3,          
'log_file'             => LOG_PATH . '/error.log',   
'request_slowlog_file' => LOG_PATH . '/slow.log',
'reload_async'         => true,
'max_wait_time'        => 20,
'buffer_output_size' => 20 * 1024 * 1024,   
'socket_buffer_size' => 20 * 1024 * 1024,  

连接被重置时的信息
> swoole_last_error
"errno: 0 Success

> getClientinfo()
{"server_port":18140,"server_fd":7,"socket_fd":40,"socket_type":1,"remote_port":55563,"remote_ip":"10.9.194.138","reactor_id":8,"connect_time":1566969797,"last_time":1566969797,"close_errno":104}

> $ ss -lt
State      Recv-Q Send-Q                            Local Address:Port                                             Peer Address:Port                
LISTEN     0      128                                           *:ssh                                                         *:*                    
LISTEN     0      128                                           *:18140                                                       *:*                    
LISTEN     0      128                                          :::ssh                                                        :::*                

> $ netstat -s
Ip:
    24895300 total packets received
    0 forwarded
    0 incoming packets discarded
    24895300 incoming packets delivered
    34142854 requests sent out
Icmp:
    4 ICMP messages received
    0 input ICMP message failed.
    ICMP input histogram:
        echo requests: 2
        echo replies: 2
    5 ICMP messages sent
    0 ICMP messages failed
    ICMP output histogram:
        echo request: 3
        echo replies: 2
IcmpMsg:
        InType0: 2
        InType8: 2
        OutType0: 2
        OutType8: 3
Tcp:
    4396395 active connections openings
    48967 passive connection openings
    0 failed connection attempts
    232 connection resets received
    332 connections established
    24894906 segments received
    34921773 segments send out
    0 segments retransmited
    0 bad segments received.
    29680 resets sent
Udp:
    392 packets received
    0 packets to unknown port received.
    0 packet receive errors
    2034 packets sent
    0 receive buffer errors
    0 send buffer errors
UdpLite:
TcpExt:
    4186295 TCP sockets finished time wait in fast timer
    6 packets rejects in established connections because of timestamp
    76469 delayed acks sent
    19 delayed acks further delayed because of locked socket
    Quick ack mode was activated 3 times
    6861068 packet headers predicted
    5567536 acknowledgments not containing data payload received
    1565111 predicted acknowledgments
    3 DSACKs sent for old packets
    9 connections reset due to unexpected data
    TCPRcvCoalesce: 1747774
    TCPOFOQueue: 1
    TCPOrigDataSent: 14435385
    TCPHystartTrainDetect: 5
    TCPHystartTrainCwnd: 90
    TCPDelivered: 18828596
IpExt:
    InOctets: 12585946649
    OutOctets: 5205335879
    InNoECTPkts: 27654262

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.6
Built => Aug 26 2019 16:10:16
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.1e-fips 11 Feb 2013
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

> uname -a
Linux xx.org 4.18.7-1.el7.elrepo.x86_64 #1 SMP Sun Sep 9 09:02:34 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

> cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)

> php -v
PHP 7.1.2 (cli) (built: Mar 17 2017 15:28:02) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2, Copyright (c) 1999-2017, by Zend Technologies

**Comment by lg430** [comment]
另外还有一个问题, `使用Base模式时max_request是无效的`那这种情况下随着worker处理请求的增多, 内存占用也越来越多, 如何防止内存溢出呢?

**Comment by shenzhe** [comment]
连接被重置，swoole和php的error log 有啥信息没？

**Comment by shenzhe** [comment]
> 另外还有一个问题, `使用Base模式时max_request是无效的`那这种情况下随着worker处理请求的增多, 内存占用也越来越多, 如何防止内存溢出呢?

内存占用多，应该是代码上有static之类没释放吧，检查一下。

**Comment by lg430** [comment]
@shenzhe 内存溢出问题, 因为项目会有多人写代码, 无法保证每人的代码都不存在内存溢出的问题, 所以只能设置max_request来解决, 但是我发现在base模式下worker达到max_request重启时, reactor线程仍然会分配请求给该重启的worker ?? 我这里表现出来的就是每次worker达到max_request重启时会有一定数量的连接失败

**Comment by lg430** [comment]
@shenzhe 是不是因为在base模式下并处理worker达到max_request重启时的请求分发处理呢, 我看文档上面说 "使用Base模式时max_request是无效的"

**Comment by matyhtf** [comment]
描述不清晰，是客户端关闭，还是服务器端关闭？

**Comment by lg430** [comment]
@matyhtf 服务端关闭
