### ISSUE TITLE
How to shutdown everything from within runninng server?

### ISSUE THREAD

**Issue by RWGuy** [swoole/swoole-src#2788]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```
$http = new Server("127.0.0.1", 9501);
$http->on('request', function ($request, $response) {
    // SHUTDOWN HERE as if pressed CTRL-C
});
$http->start();
```

Basically, I need to reload SSL certs. It appears this is not possible based on #2046

So, my solution is to shutdown as if I pressed CTRL-C every X days and it will auto-reload from cronjob with minimal downtime. It is okay if current connections get killed.

The problem is that I cannot find a way to do this. I have tried $server->shutdown(), $server->stop(), etc. None of these appear to work and some will leave ghost processes (like workers) still running even if main process is shutdown.

Is there a mechanism to just shutdown everything (main process, workers, etc)?

**Comment by leocavalcante** [comment]
The `shutdown()` method should work:
```php
$server->on('request', function (Request $request, Response $response) use ($server) {
    if ($request->server['request_uri'] === '/stop') {
        $response->end();
        return $server->shutdown();
    }

    $response->end();
});
```

**Comment by twose** [comment]
```php
$server->set([ 'pid_file' => __DIR__. '/server.pid']);
```
write a script: send SIGTERM to master (kill `cat server.pid`), then restart your application
