### ISSUE TITLE
【swoole-1.7.17-rc1】swoole_system_random: Assertion `dev_random_fd != -1' failed.

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#279]
exception： 
swoole-src-git/src/core/base.c:295: swoole_system_random: Assertion `dev_random_fd != -1' failed.

用的swoole-1.7.17-rc1，是否bug？帮忙看看，多谢～

**Comment by smalleyes** [comment]
swoole-1.7.17-stable出来了，先升级成swoole-1.7.17-stable
https://github.com/swoole/swoole-src/releases/tag/swoole-1.7.17-stable

**Comment by yiliaofan** [comment]
<pre>
int swoole_rand(int min, int max)
{
    static int _seed = 0;
    assert(max > min);

    if (_seed == 0)
    {
        _seed = time(NULL);
        srand(_seed);
    }

    int _rand = rand();
    _rand = min + (int) ((double) ((double) (max) - (min) + 1.0) * ((_rand) / ((RAND_MAX) + 1.0)));
}
</pre>
这个函数不需要return _rand？

**Comment by matyhtf** [comment]
@yiliaofan 需要。

**Comment by matyhtf** [comment]
已修改。
