### ISSUE TITLE
使用多进程连接数据库报错

### ISSUE THREAD

**Issue by biankemi** [swoole/swoole-src#2791]
php 7.2.9
swoole 4.4.4
mbp
yii2 框架  oracle 
打算用swoole开启多进程 写入数据库

非swoole可正常写入数据库
用以下代码写
`

     public function actionTest()
     {
        $workerNum = 2;
        $pool = new Pool($workerNum);
        $start = new Atomic(0);
        $stop = new Atomic(0);
       
        $pool->on("WorkerStart", function ($pool, $workerId) use ($start, $stop) {
            while (true) {
                $index = $start->add() - 1;
                if (empty($orderno[$index])) {
                    $stop->add();
                    break;
                }
                Yii::$app->db->createCommand()->insert('API_DEAL_TEST', ['ID' => 'bbb', 'NAME' => 'CCCC'])->execute();
                echo 'success';
            }
        });
        $pool->on("WorkerStop", function ($pool, $workerId) use ($stop) {
            if ($stop->get() >= 8) {
                $pool->shutdown();
            }
        });

        $pool->start();
    }
`
报错:

`
    PHP Fatal error:  Uncaught PDOException: SQLSTATE[01002]: Disconnect error: 3114 
    OCIStmtExecute: ORA-03114: not connected to ORACLE
    (/Users/bg/Downloads/php-7.2.19/ext/pdo_oci/oci_statement.c:159) in 
   /data/micro_yii/vendor/yiisoft/yii2/db/Command.php:1290
`

/Users/bg/Downloads/php-7.2.19 是php源码的目录,不知道为何会找到这里来

有时候会报

`
    [2019-08-29 14:21:48 @35676.0]  WARNING swProcessPool_wait: worker#1 abnormal exit, 
    status=0, signal=11
    A bug occurred in Swoole-v4.4.4, please report it.
    The Swoole developers probably don't know about it,
    and unless you report it, chances are it won't be fixed.
    You can read How to report a bug doc before submitting any bug reports:
    >> https://github.com/swoole/swoole-src/issues/2000
    Please do not send bug reports in the mailing list or personal letters.
    The issue page is also suitable to submit feature requests.
`

实在不知道从什么地方入手解决这个问题,所以来这里咨询一下

**Comment by twose** [comment]
@biankemi 使用master的代码编译(v4.4.5-alpha)看看是否还有问题

**Comment by biankemi** [comment]
@twose 我重新检查了代码,如果在开启多进程之前有数据库操作,会报这个错误

`    

    public function actionTest()
    {
        $workerNum = 2;
        $pool = new Pool($workerNum);
        $start = new Atomic(0);
        $stop = new Atomic(0);
       // 这里进行数据库查询
        $orderno = Yii::$app->db->createCommand('API_DEAL_TEST', ['SELECT order_no FROM post 
    WHERE id>10'])->queryColumn();

        $pool->on("WorkerStart", function ($pool, $workerId) use ($start, $stop,$orderno) {
            while (true) {
                $index = $start->add() - 1;
                if (empty($orderno[$index])) {
                    $stop->add();
                    break;
                }
                Yii::$app->db->createCommand()->insert('API_DEAL_TEST', ['ID' => 'bbb', 'NAME' => 
     'CCCC'])->execute();
                echo 'success';
            }
        });
        $pool->on("WorkerStop", function ($pool, $workerId) use ($stop) {
            if ($stop->get() >= 8) {
                $pool->shutdown();
            }
        });
        $pool->start();
    }

`
