### ISSUE TITLE
关于onClose回调函数reactor_id的问题

### ISSUE THREAD

**Issue by gutao1994** [swoole/swoole-src#2792]
我测试发现在 open_tcp_keepalive 和 heartbeat_check_interval 这两种方式关闭连接的时候，server的onClose回调函数的$reactorId 是reactor线程的id，而通过server->close() 方式关闭连接的时候，server的onClose回调函数的$reactorId为-1

按理说都是服务端关闭连接，应该都为-1吧

这个是bug吗？

**Comment by twose** [comment]
看了下实现, 这里应该是心跳线程去通知连接所属的reactor去关闭这个连接, 应该是个feature...

**Comment by gutao1994** [comment]
@twose 这么实现，感觉有点奇怪

**Comment by gutao1994** [comment]
@twose 
文档里说的：swoole-1.9.7版本修改了$reactorId参数，当服务器主动关闭连接时，底层会设置此参数为-1，可以通过判断$reactorId < 0来分辨关闭是由服务器端还是客户端发起的。

实际表现和文档不符啊。。。

**Comment by twose** [comment]
这个文档我知道 但是实现就是这样的
心跳检测线程是在master的, 而onClose事件是发生在worker的, 如果不是调close方法触发的onClose, 都是从外部来的
文档的说法不严谨
你可以说说你的需求是什么, 判断来源要做什么用, 我们再来讨论要不要单独为这个做优化
