### ISSUE TITLE
Static way to obtain worker_id

### ISSUE THREAD

**Issue by kenashkov** [swoole/swoole-src#2793]
Hi,
As of Swoole 4.4.4 there seems to be no way to statically obtain the worker_id.
I know this can be obtained from Swoole\Server but this is only valid if we have this object in the current object.

To me, it makes sense to have a static method like:
```php
Swoole\Server::getWorkerId()
```
Or a static property... To avoid breaking backward compatibility the $SwooleServer->worker_id property should stay dynamic but perhaps a static method getWorkerId() could be added?
Thank you

**Comment by kenashkov** [comment]
Swoole\Server::getWorkerId() should return 0 or -1 (to be consistent with Co::getCid()) if it is not in worker context.

**Comment by twose** [comment]
I don't think this makes sense

**Comment by kenashkov** [comment]
The reason Im looking for this is that in a similar way we can obtain the Coroutine ID without having to pass any additional dependencies I need to know the ID of the worker. I could use getmypid() for the sake of obtaining unique ID but I actually need to have the actual worker_id as this need to be stored for use and reference by other workers. If I use pid I will need to have a mapping between each worker_id and its pid to make a crossreference. And because we already have a static method for obtaining the coroutine ID (we do not need to obtain $Context) I thought we could have the same for Worker ID. As it is currently it will require to pass one more argument/dependency to a long chain of methods.

**Comment by twose** [comment]
I know, but why not just add a line of code by yourself?
```php
Server::$server = new Server(...xxx)
```

**Comment by kenashkov** [comment]
We are trying to avoid singletons completely and depend either on method arguments (and dependencies injected through arguments) or the standard PHP/Swoole runtime. This is to say that having a custom class static var defined can work but is making the library dependent on an external entity instead of being dependent only on the Swoole module. So having $worker_id passed around is inconvenient and in our view is something that pertains to the runtime and should be obtained like getmypid() and Co::getCid().

So indeed this request is raised due to the implementation approach we have, not because there is no way to obtain & pass it.
Thanks

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/01cfa32aa6e003f6aaa86285b7caca011edea43e

**Comment by Appla** [comment]
the \Swoole\Server object has many api related to whole Swoole service, for framework author who may would not want to expose this to all users for prevents some inappropriate uses.

what about add an option switch for \Swoole\Server::getInstance() ?
@matyhtf

**Comment by matyhtf** [comment]
@Appla We have decided not to provide this method

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/d664f34f87b3a1761514fc28c2db0825789df664

**Comment by kenashkov** [comment]
Maybe it is a valid issue that the Server contains many methods that should not always be accessible in certain libraries (like issuing stop() ...) but I still think worker_id should be available at any time during execution just like getmypid() is. The worker ID I think is important even if just for proper error reporting.
Perhaps just a static method Server::getWorkerId() can be exposed.
Thanks

**Comment by kenashkov** [comment]
Hi,
getWorkerId() should be static - currently on 4.5.0 it is not.
Thanks
