### ISSUE TITLE
Swoole 4.4.5 在 CentOS 7 上编译未出错，执行 php --ri swoole 时出现段错误!

### ISSUE THREAD

**Issue by designinlife** [swoole/swoole-src#2795]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
php --ri swoole

2. What did you expect to see?

3. What did you see instead?
Segmentation fault (core dumped)

Program terminated with signal 11, Segmentation fault.
#0  0x0000000000856a83 in zend_hash_index_find ()

4. What version of Swoole are you using (show your `php --ri swoole`)?
Swoole 4.4.5

5. What is your machine environment used (including version of kernel & php & gcc) ?
CentOS 7.6.1810 + PHP 7.3.9 + GCC 4.8.5

以下是 core 数据文件的 gzip 压缩包：
[core.58787.gz](https://github.com/swoole/swoole-src/files/3563281/core.58787.gz)

**Comment by matyhtf** [comment]
请检查是否安装了其他扩展，升级　Ｓｗｏｏｌｅ　版本后，对应的 async, postgresql 等都需要重新编译。

**Comment by designinlife** [comment]
没有安装async扩展，postgresql是用的mysqlnd pdo pgsql，依赖的postgresql-lib库，整个php及扩展都是全新编译的

**Comment by matyhtf** [comment]
是否执行了 make clean

**Comment by designinlife** [comment]
全新编译的，不存在执行 make clean 这一步。解压后直接 cd 进入源码目录，就 phpize && ./configure --enable-sockets --enable-swoole --enable-mysqlnd --enable-http2 && make && make install 了

**Comment by matyhtf** [comment]
请使用 USE_ZEND_ALLOC=0 valgrind php your_file.php 跟踪问题。

可以参考这里的文档 https://wiki.swoole.com/wiki/page/p-issue.html
