### ISSUE TITLE
PostgreSQL cannot be connected when using Swoole 4.4.5 and latest pgsql swoole extension

### ISSUE THREAD

**Issue by curtis18** [swoole/swoole-src#2798]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Try to update Swoole 4.4.4 to 4.4.5 and latest Swoole extension for Postgresql.

2. What did you expect to see?
Should work the same as previous version

3. What did you see instead?
No response

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.5
Built => Sep  2 2019 12:05:24
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1  11 Sep 2018
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
Linux b27e0f0f8a99 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**Comment by matyhtf** [comment]
fixed
https://github.com/swoole/ext-postgresql/commit/665592a3a24274098309fe0652dae85d04143bd8

**Comment by curtis18** [comment]
@matyhtf Thanks a lot. It is also found that binding variables do not work.
$pg -> prepare("sqlquery","select * from  test where testid > $1 and testid < $2");
$res = $pg->execute("sqlquery", array(1,3));
$arr = $pg -> fetchAll($res);
