### ISSUE TITLE
在协程环境下，使用curl出错[swoole 4.4.5]

### ISSUE THREAD

**Issue by bnubobby** [swoole/swoole-src#2800]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
    开启协程，使用curl上传文件，在执行下面代码时出错
    ` curl_setopt($curl_handle, CURLOPT_FRESH_CONNECT, false);` 

2. What did you expect to see?

  成功上传文件
 
3. What did you see instead?

抛出错误如下：
Exception: option[69] not supported
#0 @swoole-src/library/ext/curl.php(17): Swoole\Curl\Handler->setOption(69, true) 
#1 [internal function]: swoole_curl_setopt(Object(Swoole\Curl\Handler), 69, true) 

4. What version of Swoole are you using (show your `php --ri swoole`)?
   swoole 4.4.5
5. What is your machine environment used (including version of kernel & php & gcc) ?
   php 7.2

**Comment by matyhtf** [comment]
去掉此参数试试

**Comment by bnubobby** [comment]
> 去掉此参数试试
@matyhtf 
去掉此参数后，还有另外的参数出错：
curl_setopt($curl_handle, CURLOPT_FILETIME, true);
curl_setopt($curl_handle, CURLOPT_FRESH_CONNECT, false);
curl_setopt($curl_handle, CURLOPT_NOSIGNAL, true);
curl_setopt($curl_handle, CURLOPT_NOBODY, 1);
都去掉后，会导致功能无法正常使用
应用使用的是阿里OSS的扩展包，如果需要自己写代码实现协议，会比较麻烦

另外，使用4.2.13 版本，此功能是正常的，在4.2.13后至4.4.0之间的版本，超过1M的文件上传，使用nginx代理时，出现time-out （没有尝试过直接上传至swoole，我稍后再试），没有进入到onRequest

**Comment by matyhtf** [comment]
@bnubobby 1M 的问题，请单独创建新的 issue，请贴出详细的可复现的 demo 程序
