### ISSUE TITLE
Warning: Redis::connect(): socket_set_option: unsupported option 3 with value 0

### ISSUE THREAD

**Issue by Uchihaha** [swoole/swoole-src#2802]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```
<?php


use Swoole\Coroutine\Channel;
use Swoole\Http\Request;
use Swoole\Http\Response;
use Swoole\Http\Server;
use Swoole\Process;

$server = new Server('127.0.0.1', '6369', SWOOLE_BASE);
$server->set([
    'worker_num' => 1,
    'hook_flags' => SWOOLE_HOOK_ALL
]);
$server->on('request', function (Request $request, Response $response) {
    $redis = new Redis();
    $redis->connect('127.0.0.1', 6379);
    $response->end("hello".$redis->get('name'));
});
$server->start();
```

2. What did you expect to see?
I expected to see no "Warning" reported.

3. What did you see instead?
I saw a "Warning" like ```Warning: Redis::connect(): socket_set_option: unsupported option 3 with value 0```.

4. What version of Swoole are you using (show your `php --ri swoole`)?
Swoole 4.4.4

5. What is your machine environment used (including version of kernel & php & gcc) ?
php 7.2.22
redis 4.3.0

**The reason maybe below.**
#### redis
In the `library.c`, there is a `php_stream_set_option` call. It's second option is `PHP_STREAM_OPTION_WRITE_BUFFER`.
```
PHP_REDIS_API int redis_sock_connect(RedisSock *redis_sock TSRMLS_DC)
{
    ......
    php_stream_set_option(redis_sock->stream,
        PHP_STREAM_OPTION_WRITE_BUFFER, PHP_STREAM_BUFFER_NONE, NULL);

    redis_sock->status = REDIS_SOCK_STATUS_CONNECTED;

    return SUCCESS;
}
```

#### swoole
We can see in the `swoole_runtime.cc`, there is no `PHP_STREAM_OPTION_WRITE_BUFFER` case. So switch statement went into default and reported a `E_WARNING`.
```
static int socket_set_option(php_stream *stream, int option, int value, void *ptrparam)
{
    switch (option)
    {
    ......

    default:
#ifdef SW_DEBUG
        php_swoole_fatal_error(E_WARNING, "socket_set_option: unsupported option %d with value %d", option, value);
#endif
        break;
    }
    
    return PHP_STREAM_OPTION_RETURN_OK;
}
```

Maybe we can add a `PHP_STREAM_OPTION_WRITE_BUFFER` case and do nothing inside to prevent this warning.

**Comment by twose** [comment]
https://github.com/swoole/swoole-src/blob/5babb586f1a99f60d7f8fc46f8fd7c6f0fd408d5/swoole_runtime.cc#L900

Thanks for your feedback, but I have already done this in the latest version

and this option may be useless in Swoole due to the different implementation and it is DEBUG only
