### ISSUE TITLE
协程Mysql支持类似命令行的参数 如-A

### ISSUE THREAD

**Issue by xuanyanwow** [swoole/swoole-src#2803]
因为在es用户群用户反馈：有一个库`有非常多表 4K+个`，连接操作有时候出现6s等待

在命令行中连接，如果太慢，会提示以下信息，增加`-A`参数 快速启动，

![7E01C4F0C4C945798768B432B1B4B7B2](https://user-images.githubusercontent.com/28777109/64141140-96cd3780-ce39-11e9-9484-cacbcce719b9.png)

读取表信息以完成表名和列名
您可以关闭此功能以使用-a快速启动
```
  -A, --no-auto-rehash 
                      No automatic rehashing. One has to use 'rehash' to get
                      table and field completion. This gives a quicker start of
                      mysql and disables rehashing on reconnect.
```

已知：同一个库，在TP3.2中PDO没有出现类似慢的问题。

**Comment by twose** [comment]
经测试和表数量应该无关, 此选项为命令行自动补全功能开关, 推测是由其它原因导致
