### ISSUE TITLE
asnyc编译一堆错误

### ISSUE THREAD

**Issue by UncleZh** [swoole/swoole-src#2805]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
swoole4.3.5  想要安装async扩展，make的时候报了一堆错误

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
  4.3.5

5. What is your machine environment used (including version of kernel & php & gcc) ?

centos7，PHP7.2，gcc 4.8.5

**Comment by twose** [comment]
swoole和async扩展的版本要对应

此外, 你把错误发出来啊

**Comment by UncleZh** [comment]
看了文档知道怎么回事了
