### ISSUE TITLE
http context is unavailable

### ISSUE THREAD

**Issue by amirbagh75** [swoole/swoole-src#2807]
```Warning: Swoole\Http\Response::header(): http context is unavailable (maybe it has been ended or detached)```

what the meaning of this warning? i use swoole docker v4.4.5.

**Comment by twose** [comment]
you have called `$response->end()`, so you can't send any more information.

**Comment by ljfreelancer88** [comment]
Hi, what are the approaches on how to eliminate this kind of error? 
In the documentation, it shows only the usage but it doesn't say anything regarding `warning`. 

Thank you

**Comment by arku31** [comment]
Maybe someone else will struggle with it as well :)

$response->setHeader() and $response->header() acts different. I haven't seen a confirmation in docs but seems that first, one sends header immediately and another one store it first and send it with end().

That was quite unclear as in my case end() was called in the middleware and header was supposed to set before what led to the exact message
