### ISSUE TITLE
[4.4.6-Alpha] 无法进入task

### ISSUE THREAD

**Issue by chaopi** [swoole/swoole-src#2811]
[4.4.6-Alpha] 在centos 6.1 final
$server->task($data)；
无法进入onTask事件。用php --ri swoole发现是Alpha版本后，找到4.4.5版swoole下载重新编译安装后，问题解决。

**Comment by twose** [comment]
感谢反馈, 当前的matser(位于 dddf63aa) 是否表现正常呢?
拉取开发分支前需要确认build标志是否为pass状态, 否则是不可用的
