### ISSUE TITLE
在phpunit中需要启动多个Server(一个TestCase一个)，在Server shutdown后无法再启动

### ISSUE THREAD

**Issue by amuluowin** [swoole/swoole-src#2812]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
我这边写了个日志组件，支持tcp,udp,kafka,websocket等的Target，在写单元测试的时候，启动了一个Server后(已经shutdown)无法再启动别的Server。

2. What did you expect to see?
希望能在一个脚本里面启动多个Server。
或者phpunit配置是否支持。

3. What did you see instead?
启动一个TCPServer，执行完测试，Shutdown后
再启动一个WebSocketServer
Swoole\Exception: eventLoop has already been created. unable to create Swoole\WebSocket\Server

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.5
Built => Sep  5 2019 17:02:56
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
Linux k8s-rke 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.3.7 (cli) (built: Aug  6 2019 20:39:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.7, Copyright (c) 1999-2018, by Zend Technologies
    with Sdebug v2.7.3-dev, Copyright (c) 2002-2019, by Derick Rethans

gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

**Comment by matyhtf** [comment]
参照 swoole 官方 tests 单测的实现方法，使用进程管理的模式，开启单独进程去 创建 server

**Comment by amuluowin** [comment]
噢，对，采用进程管理方式启动Server已经解决。
