### ISSUE TITLE
php7.3-cli with swoole return code may error.

### ISSUE THREAD

**Issue by javalaw** [swoole/swoole-src#2814]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

the php-cli command with swoole extension will return code 1 even not using any feature /method of swoole. this situation may occur when using composer autoload and guzzle package. this is  a minial reproducing example:
```bash
mkdir test
cd test
composer require guzzlehttp/guzzle
```
then add a index.php
```php
<?php
require "vendor/autoload.php";
```
then
```bash
#php with swoole installed
$ php index.php
$ ehco $? #this will return 1
#php without swoole
$ php index.php
$ ehco $? #this will return 0
```

2. What did you expect to see?
if there are errors,the extension should report the error. or it should return code 0.

3. What did you see instead?
it return 0 and no error message are reported.

4. What version of Swoole are you using (show your `php --ri swoole`)?
```bash
root@926f38173b65:/# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.5
Built => Sep  6 2019 11:19:39
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1c  28 May 2019
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ?
docker container with base image phusion/baseimage:master
kernel: 4.9.184-linuxkit
php: php7.3
gcc: version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**Comment by twose** [comment]
I didn’t reproduce this mistake

**Comment by javalaw** [comment]
> I didn’t reproduce this mistake
> try to set error_reporting to E_ALL in php.ini

i have set error_reporting to E_ALL but still noting reported.
to reproduce the mistake i have made a docker image.
```bash
$ docker run -it -d javalaw2010/bugreproduce:latest
$ docker exec -it [your-container] bash
```
and then follow the before reproduce steps you will get the mistake.

**Comment by twose** [comment]
I have recreated this problem but I have no idea how to fix it
