### ISSUE TITLE
同一台服务器起多个Swoole Server实例出现异常

### ISSUE THREAD

**Issue by mysteriouss** [swoole/swoole-src#282]
一个实例中task响应不正确，
$this->swoole_serv = new swoole_server("0.0.0.0", 8883);
        $this->swoole_serv->set(array(
            'worker_num' => 4,
            'task_worker_num' => 1,
            'task_ipc_mode' => 2,
            'heartbeat_idle_time' => 60,
            'heartbeat_check_interval' => 10,
        ));

另一个实例中出现 swServer_get_worker: worker_id is exceed serv->worker_num + SwooleG.task_worker_num
$this->swoole_serv = new swoole_server("0.0.0.0", 9501);
        $this->swoole_serv->set(array(
            'worker_num' => 1,
            'task_worker_num' => 1,
            'task_ipc_mode' => 2,
            'heartbeat_idle_time' => 60,
            'heartbeat_check_interval' => 10,
        ));

服务器配置单核，是因为worker开太多导致的么？谢谢

**Comment by matyhtf** [comment]
去掉'task_ipc_mode'看看

**Comment by mysteriouss** [comment]
可能是由于是1.7.14-beta版本的原因? 

另外发现task_ipc_mode => 2是争抢模式，
而task_ipc_mode => 3没发生争抢并且$serv->task($data, $task_worker_id)到了指定的task_worker_id.

已经更新到1.7.17-stable了，task_ipc_mode=>2恢复正常，发现问题再反馈吧，谢谢！

还有一个问题： 
测试了一下open_mqtt_protocol, 
如果一个mqtt client(dispatch_mode默认)发送大量数据过程中强制断开客户端，因服务器积累了大量的task,而未到close回调，在我自己的逻辑中在线$fd的哈希仍然存在，所以还是会调用$serv->send($fd,$data) 产生 WARN    swFactoryProcess_finish: send 4 byte failed, because session#1 is closed.的警告

主要代码如下：

                            $msg_msb = $raw[$i];
                            $msg_lsb = $raw[$i+1];
                            $i += 2;

                            $fdinfo  = $serv->connection_info($fd);
                            if($fdinfo){
                                $data = chr(MQTT_MSG::$PUBACK).chr(2).$msg_msb.$msg_lsb;
                                $serv->send($fd,$data);
                            }

想问 既然 swFactoryProcess_finish 可以判断连接已关闭，在php中$fdinfo  = $serv->connection_info($fd); 返回值不为false, 如何检测$fd对应的连接已经关闭?
