### ISSUE TITLE
抢占式调度问题, 希望能解惑

### ISSUE THREAD

**Issue by zhanghaomin** [swoole/swoole-src#2822]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/21331884/64584241-87646600-d3c6-11e9-9317-617da507c60b.png">
触发vm_interrupt时, 调用orig_interrupt_function是否会与一些扩展冲突?

**Comment by twose** [comment]
相当于在原有interrupt之前让出了一段时间, 有什么扩展用到了这个么? 应该不会冲突, 没有影响逻辑

**Comment by zhanghaomin** [comment]
我看到pcntl扩展也有使用这个，但是我还没去看他具体实现，不知道会不会影响

**Comment by matyhtf** [comment]
你可以测试一下。
