### ISSUE TITLE
table key乱码

### ISSUE THREAD

**Issue by lg430** [swoole/swoole-src#2826]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

        $table = new Table(102400);
        $table->column('total', Table::TYPE_INT, 8);
        $table->create();
        $key = 'sucMhozlYhsLz60ctUdZecTOTEGsC5cy:WirelessService.getListForSixGrid';
        $table->set($key, ['total' => 1]);
        foreach ($table as $k => $v) {
            var_dump($k, $v);
        }

2. What did you expect to see?

string(65) "sucMhozlYhsLz60ctUdZecTOTEGsC5cy:WirelessService.getListForSixGrid"
array(1) {
  ["total"]=>
  int(1)
}

3. What did you see instead?

string(65) "sucMhozlYhsLz60ctUdZecTOTEGsC5cy:WirelessService.getListForSixGr"
array(1) {
  ["total"]=>
  int(1)
}

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.6
Built => Aug 26 2019 16:10:16
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.1e-fips 11 Feb 2013
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

PHP 7.1.2 (cli) (built: Mar 17 2017 15:28:02) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2, Copyright (c) 1999-2017, by Zend Technologies

Linux  3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Installed:
  pcre-devel.x86_64 0:8.32-15.el7_2.1

**Comment by matyhtf** [comment]
@lg430  key 的最大长度超过底层的限制了，最多只能存储 `63` 字节的 key
