### ISSUE TITLE
Tracking coroutine switching

### ISSUE THREAD

**Issue by kenashkov** [swoole/swoole-src#2827]
Hi,
Is there currently a way to track when a coroutine switch occurs? Having this will allow for profiling and stats.
For example profiling code in coroutine context that contains methods that yield to another coroutine can not be done with simple code like:
```php
$start = microtime(true);
Co::readFile('bla.txt');
$end = microtime(true);
print $end - $start;
```
This does not take into account the time which the coroutine waits for the scheduler to give back control to it (even if the file reading is done there will be other coroutines).

I imagine something like:
```php
go(function() {
    onEnter(function($cid, $from_cid = NULL){
        //worker is now executing $cid
    });
    onYield( function($cid, $to_cid = NULL) {
        //worker has now left $cid
    });
});
```
And these can be invoked multiple times during coroutine execution. If possible a second argument can be provided for the previous or next coroutine that is beign executed.

**Comment by twose** [comment]
I have to say... This is a proposal that has been rejected by the development team...
The goal of Swoole is consistent with the sync blocking.
 There is no such thing in Go

**Comment by kenashkov** [comment]
Yes, this was proposed just for the purpose of profiling, no other reason. Thanks for looking into this!

**Comment by matyhtf** [comment]
This is a security risk. If the coroutine feature is used in the callback function of coroutine switching, this will cause an endless loop.
