### ISSUE TITLE
Methods must be changed to static in Coroutine\System

### ISSUE THREAD

**Issue by kenashkov** [swoole/swoole-src#2831]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Just to let you know that the new class Swoole\Coroutine\System it seems has most of the methods as dynamic, not static. We know it is not official yet (pending 4.4.6) but for the purpose of a static analyzer, we were dumping all Swoole classes and noticed this.

2. What did you expect to see?
```php
<?php
namespace Swoole\Coroutine;
class System
{
    public static function gethostbyname( $domain_name, $family, $timeout) { }

    public static function dnsLookup( $domain_name, $timeout) { }

    public static function exec( $command, $get_error_stream) { }

    public static function sleep( $seconds) { }

    public static function fread( $handle, $length) { }

    public static function fwrite( $handle, $string, $length) { }

    public static function fgets( $handle) { }

    public static function getaddrinfo( $hostname, $family, $socktype, $protocol, $service, $timeout) { }

    public static function readFile( $filename) { }

    public static function writeFile( $filename, $data, $flags) { }

    public static function statvfs( $path) { }

}
```

3. What did you see instead?
```php
<?php
namespace Swoole\Coroutine;
class System
{
    public static function gethostbyname( $domain_name, $family, $timeout) { }

    public static function dnsLookup( $domain_name, $timeout) { }

    public function exec( $command, $get_error_stream) { }

    public function sleep( $seconds) { }

    public function fread( $handle, $length) { }

    public function fwrite( $handle, $string, $length) { }

    public function fgets( $handle) { }

    public function getaddrinfo( $hostname, $family, $socktype, $protocol, $service, $timeout) { }

    public function readFile( $filename) { }

    public function writeFile( $filename, $data, $flags) { }

    public function statvfs( $path) { }

}
```
And of course and error is produced if used:

Non-static method Swoole\Coroutine\System::sleep() cannot be called statically

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.5
Built => Sep  3 2019 15:15:53
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
It has been fixed on master (https://github.com/swoole/swoole-src/commit/97c1444ac843acecf9e452fc4f8550728184075c)
Because most people (even unit tests) are using the old API, we have not found this problem.
Thanks for your feedback!
