### ISSUE TITLE
[4.4.5] Segmentation fault on arm32v7

### ISSUE THREAD

**Issue by suconghou** [swoole/swoole-src#2832]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

compile succeed, see dockerfile  https://github.com/suconghou/docker/blob/e87d184a0e36d0111aba1d0c98fb4aa6a4490d4f/php/Dockerfile-swoole-arm32v7

amd64 build succeed, and works fine, but arm32 not. 

both these  test code Segmentation fault
```
<?php 

$http = new Swoole\Http\Server('127.0.0.1', 9090, SWOOLE_BASE);

$http->on('WorkerStart',function(){
    echo "WorkerStart";
});
    

$http->on(
	'request',
	function ($request, $response)
	{
		echo "req";
	}
);

$http->start();
```

```
<?php

$s = new Co\Scheduler();
$s->add(function () {
    Co::sleep(1);
    go(function () {
        echo "Co 2\n";
    });
});
$s->start();
```

I build it one rpi2 , it may be take one hour to build 

and the docker images here https://hub.docker.com/layers/suconghou/php/arm32v7_swoole/images/sha256-e6a191f06ef19dd74e6d2ff49b1c142c88a6f9df3a9bb17049dad609abab4396

you can try it directly 

2. What did you expect to see?

common php code works well, but swoole function and class case Segmentation fault

3. What did you see instead?

Segmentation fault

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.5
Built => Sep 15 2019 10:00:08
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ?

```
PHP 7.3.9 (cli) (built: Sep 15 2019 10:24:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
Linux e3e126b22f9e 4.14.78-4-osmc #1 SMP PREEMPT Wed Dec 12 17:58:11 UTC 2018 armv7l Linux
```

**Comment by twose** [comment]
@suconghou 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by suconghou** [comment]
是全新编译的, 使用 arm32v7 上 docker 编译的 , 已下载4.4.6 编译,同样的问题,可以使用上面提供的docker image 或者dockerfile 复现

**Comment by matyhtf** [comment]
请使用 4.4.13 测试，如果发生 core dump，请使用gdb 和 valgrind 跟踪

**Comment by suconghou** [comment]
==14== Memcheck, a memory error detector
==14== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==14== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==14== Command: php 1.php
==14== Parent PID: 1
==14== 
disInstr(thumb): unhandled instruction: 0xEFA0 0x0E00
==14== valgrind: Unrecognised instruction at address 0x4fa0df.
==14==    at 0x4FA0DE: ??? (in /usr/local/bin/php)
==14== Your program just tried to execute an instruction that Valgrind
==14== did not recognise.  There are two possible reasons for this.
==14== 1. Your program has a bug and erroneously jumped to a non-code
==14==    location.  If you are running Memcheck and you just saw a
==14==    warning about a bad jump, it's probably your program's fault.
==14== 2. The instruction is legitimate but Valgrind doesn't handle it,
==14==    i.e. it's Valgrind's fault.  If you think this is the case or
==14==    you are not sure, please let us know and we'll try to fix it.
==14== Either way, Valgrind will now raise a SIGILL signal which will
==14== probably kill your program.
disInstr(thumb): unhandled instruction: 0xFFB0 0x0300
==14== valgrind: Unrecognised instruction at address 0x4fa0cd.
==14==    at 0x4FA0CC: ??? (in /usr/local/bin/php)
==14== Your program just tried to execute an instruction that Valgrind
==14== did not recognise.  There are two possible reasons for this.
==14== 1. Your program has a bug and erroneously jumped to a non-code
==14==    location.  If you are running Memcheck and you just saw a
==14==    warning about a bad jump, it's probably your program's fault.
==14== 2. The instruction is legitimate but Valgrind doesn't handle it,
==14==    i.e. it's Valgrind's fault.  If you think this is the case or
==14==    you are not sure, please let us know and we'll try to fix it.
==14== Either way, Valgrind will now raise a SIGILL signal which will
==14== probably kill your program.
disInstr(thumb): unhandled instruction: 0xEF00 0x0C40
==14== valgrind: Unrecognised instruction at address 0x4fa0d3.
==14==    at 0x4FA0D2: ??? (in /usr/local/bin/php)
==14== Your program just tried to execute an instruction that Valgrind
==14== did not recognise.  There are two possible reasons for this.
==14== 1. Your program has a bug and erroneously jumped to a non-code
==14==    location.  If you are running Memcheck and you just saw a
=14==    warning about a bad jump, it's probably your program's fault.
==14== 2. The instruction is legitimate but Valgrind doesn't handle it,
==14==    i.e. it's Valgrind's fault.  If you think this is the case or
==14==    you are not sure, please let us know and we'll try to fix it.
==14== Either way, Valgrind will now raise a SIGILL signal which will
==14== probably kill your program.
disInstr(thumb): unhandled instruction: 0xFF00 0x0C40
==14== valgrind: Unrecognised instruction at address 0x4fa0d9.
==14==    at 0x4FA0D8: ??? (in /usr/local/bin/php)
==14== Your program just tried to execute an instruction that Valgrind
==14== did not recognise.  There are two possible reasons for this.
==14== 1. Your program has a bug and erroneously jumped to a non-code
==14==    location.  If you are running Memcheck and you just saw a
==14==    warning about a bad jump, it's probably your program's fault.
==14== 2. The instruction is legitimate but Valgrind doesn't handle it,
==14==    i.e. it's Valgrind's fault.  If you think this is the case or
==14==    you are not sure, please let us know and we'll try to fix it.
==14== Either way, Valgrind will now raise a SIGILL signal which will
==14== probably kill your program.
disInstr(thumb): unhandled instruction: 0xEC51 0x0F1E
==14== valgrind: Unrecognised instruction at address 0x4fa0c7.
==14==    at 0x4FA0C6: ??? (in /usr/local/bin/php)
==14== Your program just tried to execute an instruction that Valgrind
==14== did not recognise.  There are two possible reasons for this.
==14== 1. Your program has a bug and erroneously jumped to a non-code
==14==    location.  If you are running Memcheck and you just saw a
==14==    warning about a bad jump, it's probably your program's fault.
==14== 2. The instruction is legitimate but Valgrind doesn't handle it,
==14==    i.e. it's Valgrind's fault.  If you think this is the case or
==14==    you are not sure, please let us know and we'll try to fix it.
==14== Either way, Valgrind will now raise a SIGILL signal which will
==14== probably kill your program.
==14== Conditional jump or move depends on uninitialised value(s)
==14==    at 0x7D1562: ??? (in /usr/local/bin/php)
==14== 
==14== Warning: client switching stacks?  SP change: 0x7d9e6358 --> 0x4d02fa8
==14==          to suppress, use: --max-stackframe=2026779568 or greater
==14== Conditional jump or move depends on uninitialised value(s)
==14==    at 0x365C3E: ??? (in /usr/local/bin/php)
==14== 
==14== Warning: client switching stacks?  SP change: 0x4d02c90 --> 0x4f03fa8
==14==          to suppress, use: --max-stackframe=2102040 or greater
==14== Warning: client switching stacks?  SP change: 0x4f03fa8 --> 0x4d02c90
==14==          to suppress, use: --max-stackframe=2102040 or greater
==14==          further instances of this message will not be shown.
==14== 
==14== HEAP SUMMARY:
==14==     in use at exit: 0 bytes in 0 blocks
==14==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==14== 
==14== All heap blocks were freed -- no leaks are possible
==14== 
==14== Use --track-origins=yes to see where uninitialised values come from
==14== For lists of detected and suppressed errors, rerun with: -s
==14== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
