### ISSUE TITLE
Implement RFC 7692 - Compression Extensions for WebSocket

### ISSUE THREAD

**Issue by aZcjUZY93RUeWqX2** [swoole/swoole-src#2834]
The permessage-deflate WebSocket extension ([RFC 7692 - Compression Extensions for WebSocket](https://tools.ietf.org/html/rfc7692)) is supported by Chrome since 32 and Mozilla Firefox since 37.
The extension allows to optionally and transparently compress WebSocket messages and would greatly help reduce the size of e.g. larger json transfers.

Please consider implementing this extension.

Thank you for your consideration.

**Comment by Kapsonfire** [comment]
just one question.
when does permessage deflate take in?
is there a minimum size the message has to be to get compressed?
is there a way to test effiency?
