### ISSUE TITLE
建议server配置增加"pid_file"

### ISSUE THREAD

**Issue by yeaha** [swoole/swoole-src#284]
建议在server配置内增加"pid_file"，把server进程号保存到"pid_file"指定的文件内，这样写服务进程管理脚本比较方便

**Comment by matyhtf** [comment]
此功能在PHP代码中实现更合适。

**Comment by 23335096** [comment]
能否给出个服务进程管理脚本的实现，php server.php start|stop|restart

**Comment by matyhtf** [comment]
可以参考swoole_framework中的实现。
