### ISSUE TITLE
Swoole关于错误追踪问题

### ISSUE THREAD

**Issue by qifengzhang007** [swoole/swoole-src#2840]
####    2. 目前swoole程序运行中出现的错误官方提供的解决方案是在  register_shutdown_function  回调函数中捕获最近一次错误，问题就在这里，这个回调函数，只能捕获最近一次错误，并且该函数的触发，是内存中的栈信息已经释放，无法继续调用 debug_backtrace() 函数（本人已经测试、查询PHP官方文档），那么请问，从最近一次错误，如果追踪到错误触发的源头文件、行、参数？

**Comment by leafmirror** [comment]
> #### 1.普通的 PHP 代码发生错误，只需要全局拦截，在set_error_handler回调中就可以自定义处理错误，并且可以使用debug_backtrace() 函数，从最近一次错误一直追踪到触发错误的原始文件、行、参数。
> #### 2. 目前swoole程序运行中出现的错误官方提供的解决方案是在 register_shutdown_function 回调函数中捕获最近一次错误，问题就在这里，这个回调函数，只能捕获最近一次错误，并且该函数的触发，是内存中的栈信息已经释放，无法继续调用 debug_backtrace() 函数（本人已经测试、查询PHP官方文档），那么请问，从最近一次错误，如果追踪到错误触发的源头文件、行、参数？

坐等开发者回复

**Comment by twose** [comment]
Server模式下致命错误进程退出后会输出最后一个错误的详细日志
经测试set_error_handler, set_exception_handler也可以正常执行
文档是早期由其他贡献者编撰的, 我也不是很清楚为什么要那么写

**Comment by qifengzhang007** [comment]
> Server模式下致命错误进程退出后会输出最后一个错误的详细日志
> 经测试set_error_handler, set_exception_handler也可以正常执行
> 文档是早期由其他贡献者编撰的, 我也不是很清楚为什么要那么写

多谢，明天继续复测一下。

**Comment by matyhtf** [comment]
在 PHP 中绝大部分错误都是使用 try catch 捕获，你可以先尝试捕获这些错误。

https://wiki.swoole.com/wiki/page/1521.html
