### ISSUE TITLE
Question about upgrading swoole over pecl that causes segfault

### ISSUE THREAD

**Issue by stefanos82** [swoole/swoole-src#2842]
Hey folks,

I hope you are doing well.

I have tried to upgrade swoole and managed to get a segfault.

Here are the steps I followed:

- I run `sudo pecl channel-update pecl.php.net` to fetch the latest updates for swoole.
- I then run `sudo pecl upgrade swoole` and during the finish, it informed me that everything went OK, but right after the message to add the extension in php.ini file, it segfaulted.

My suspicion was the existing symlink `20-swoole.ini` I personally created in `/etc/php/7.3/cli/conf.d/` directory and the very existence of `swoole.ini` in `/etc/php/7.3/mods-available/`.

After removing symlink, cleaning `/tmp/` directory from any `pear` directory, and moving `swoole.ini` file to `swoole.ini.bak`, I repeated the whole procedure and worked as expected.

Do we know whether this is the expected behavior or could it be a bug somewhere?

**Comment by twose** [comment]
I don't know, but you said it works fine now, so there is no problem
May be due to wrong cache or a wrong link target?

**Comment by stefanos82** [comment]
But `sudo pecl upgrade swoole` shouldn't work out of the box without such issues?

Anyhow, it's something that needs further investigation.

**Comment by deminy** [comment]
I tried following commands to upgrade and downgrade Swoole back and forth locally, 

```bash
pecl install -f swoole-4.4.5
pecl install -f swoole-4.4.6
```
Everything works fine under PHP 7.3. Unfortunately we don't have enough information to tell how the segfault was triggered in your case, and we don't see a way to reproduce it for further investigation. @stefanos82 Have you tried to downgrade swoole to a previous version and see if it is still broken?

**Comment by stefanos82** [comment]
Hey @deminy, I hope you are doing great.

If you are on GNU / Debian, did you follow my procedure with symlink and such? That's when it segfaults.

If you remove the symlink and comment out the .ini file so it cannot be found by PHP, it works as expected.

**Comment by stefanos82** [comment]
@deminy to verify my issue, I've setup a virtual machine and followed your steps:

As you can see in the screenshot below, it segfaults when you have symlinked `/etc/php/7.3/mods-available/swoole.ini` to `/etc/php/7.3/cli/conf.d/20-swoole.ini`.

![problematic-swoole](https://user-images.githubusercontent.com/1777466/67143210-b695af00-f271-11e9-9bc7-73415583c95e.png)

It seems my hypothesis is valid, because the following screenshot of version `4.4.6` is without symlink of `swoole.ini` in the aforementioned directory.

![image](https://user-images.githubusercontent.com/1777466/67143249-2f950680-f272-11e9-83af-d791a53f69c5.png)

**Comment by deminy** [comment]
Thanks @stefanos82 for the updates. Based on your feedback, I was able to reproduce the issue with following `Dockerfile`:

```docker
FROM php:7.3.10-cli

RUN \
    pecl update-channels && \
    pecl install swoole-4.4.5 && \
    printf "extension=swoole.so\n" > /swoole.ini && \
    ln -s /swoole.ini /usr/local/etc/php/conf.d/. && \
    ls -la /usr/local/etc/php/conf.d && \
    php --ri swoole && \
    pecl upgrade swoole-4.4.6
```

Assigning the ticket to @twose for further investigation.

**Comment by twose** [comment]
Reproduced successfully. Thanks @deminy 
Hi, @stefanos82 :
This bug seems to be caused by the update of dynamic link library
I think it may be the bug of PECL, not Swoole
It should disable the extension before update it

Thank you for your feedback!
