### ISSUE TITLE
非root用户如何实现热重启（reload）？

### ISSUE THREAD

**Issue by 15521956291** [swoole/swoole-src#2845]
如题，最近更新到4以后的版本后开始出现无法热重启了，也不知道是版本4的问题
具体是在server::set的时候用户设置为普通的用户，比如 webuser（非root）
`
server->set(['user'=>'webuser']);
`
每次执行reload都提示
`
PHP Warning:  Swoole\Server::reload(): failed to send the reload signal, Error: Operation not permitted[1]

`
但是如果把
`
server->set(['user'=>'root']);
`
则不会报错，出于安全考虑，所以以非root用户启动服务器，但是遇到这个问题，大家是怎么解决的呢？

**Comment by matyhtf** [comment]
使用 root 账户给 master 进程发送信号
