### ISSUE TITLE
环境配置好以后,运行代码提示：Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by chenfei528** [swoole/swoole-src#2846]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
$db = new swoole_mysql;
$server = array(
    'host' => '127.0.0.1',
    'user' => 'root',
    'password' => 'root',
    'database' => 'test',
);
$r = $db->connect($server, function ($db, $result)
{
echo 'test';
});
2. What did you expect to see?
test
3. What did you see instead?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `php mysql.php'.
Program terminated with signal 11, Segmentation fault.
#0  swoole_mysql_onWrite (reactor=<optimized out>, event=0x7ffe8b20f150) at /root/software/async-ext/swoole_mysql.c:3054
3054            client->connector.error_code = SwooleG.error;
Missing separate debuginfos, use: debuginfo-install libargon2-20161029-3.el7.x86_64

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.7-alpha
Built => Sep 22 2019 12:57:31
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
PHP 7.2.22 (cli) (built: Sep 11 2019 18:11:52) ( NTS )
Linux iZ8vb9cbo4fjmavy94em7xZ 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

![sw1](https://user-images.githubusercontent.com/14284430/65397637-516eab00-dde4-11e9-9205-30c45ea89bab.png)

**Comment by twose** [comment]
@chenfei528 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by chenfei528** [comment]
total 324
srwxr-xr-x 1 root root      0 Sep 22 16:31 Aegis-<Guid(5A2C30A2-A87D-490A-9281-6765EDAD7CBA)>
drwx------ 3 root root   4096 Sep 22 16:31 systemd-private-d323c6286a2d43418c3be0d35ea889e3-chronyd.service-YLQMp0
-rw-r--r-- 1 root root   3566 Sep 23 09:32 valgrind.log
-rw------- 1 root root   2479 Sep 22 12:23 yum_save_tx.2019-09-22.12-23.uRhdEg.yumtx
-rw------- 1 root root 156744 Sep 22 22:53 yum_save_tx.2019-09-22.22-53.PRDXue.yumtx
-rw------- 1 root root 156744 Sep 23 06:39 yum_save_tx.2019-09-23.06-39.kKyd0P.yumtx
[root@iZ8vb9cbo4fjmavy94em7xZ tmp]# tail valgrind.log 
==6812==    indirectly lost: 1,409 bytes in 56 blocks
==6812==      possibly lost: 2,159,277 bytes in 19,997 blocks
==6812==    still reachable: 2,662,367 bytes in 14,565 blocks
==6812==                       of which reachable via heuristic:
==6812==                         stdstring          : 27,227 bytes in 764 blocks
==6812==         suppressed: 0 bytes in 0 blocks
==6812== Rerun with --leak-check=full to see details of leaked memory
==6812== 
==6812== For counts of detected and suppressed errors, rerun with: -v
==6812== ERROR SUMMARY: 2 errors from 1 contexts (suppressed: 0 from 0)

**Comment by twose** [comment]
为什么不用cat?

**Comment by matyhtf** [comment]
升级 swoole 后，需要重新编译安装 ext-async

**Comment by matyhtf** [comment]
已修复 ext-async 的问题，请更新
