### ISSUE TITLE
is there anyway to store multidimensional array inside swoole table ?

### ISSUE THREAD

**Issue by ermya** [swoole/swoole-src#2848]
if i use swoole table like array ! i can not access it in other proccess ! 
if i use swoole table with set and get model face me an error when i use multidimensional array

for example : 

look at this array 

```
array(1) {
  [3]=>
  array(3) {
    ["username"]=>
    string(4) "test"
    ["session"]=>
    string(20) "test"
    ["tableNo"]=>
        array(1) {
             ["LefSide1"]=>
                       array(8) {
                              ["seat"]=>
                              int(1)
                              ["order1"]=>
                              string(2) "Cooca"
                              ["order2"]=>
                              string(2) "coola"
                              ["order3"]=>
                               string(2) "Moola"
                              ["orderTime"]=>
                              string(16) "123456"
                              ["garcon"]=>
                              string(7) "17552-1"
      }
    }
  }
}

```

i can create an use it when i use basic model swoole table  like this : 

`$this->table[1]['tableNo']['LefSide1']['order1'] = 'coola';`

its working like this but the problem is i can not  access it on all proccess

another way is use set and get but the problem is will not accept multidimensional array

look at this 

`$srv->table->set($fd, array('tableNo' => array('LeftSide1' => array('order1' => 'coola', 'order2' => 'moola' , etc .... ))));`

this one face me an error for couldn't converting array to string 

is there any hint ?!

**Comment by ermya** [comment]
as can i see there is no any implementation for multidimensional array 
thanks guys
i hope you will be add this one

**Comment by Magaav** [comment]
By now I am igserializing it and storing as string...
