### ISSUE TITLE
aarch64 上编译swoole boost出错

### ISSUE THREAD

**Issue by xywf221** [swoole/swoole-src#2850]
环境信息:
系统是通过 linuxdeploy 安装的 
OS: Debian 
Kernel: aarch64 Linux 3.18.124-BlackScreen-6.1.1+
CPU: Qualcomm Technologies, Inc MSM8996 @ 4x 1.5936GHz
gcc version : gcc version 8.3.0 (Debian 8.3.0-6)

错误内容 : 
![AEE1ADD1639D74B3D0ADCE8805259545](https://user-images.githubusercontent.com/17561378/65486910-4ac16000-ded8-11e9-9832-641ef85b9909.jpg)

**Comment by ClosetMonkey** [comment]
For what it's worth I've installed Swoole on an Amlogic S905W board which is aarm64 running Armbian 5.74 (Debian Stretch). It worked without a problem.

**Comment by xywf221** [comment]
> For what it's worth I've installed Swoole on an Amlogic S905W board which is aarch64 running Armbian 5.75 (Debian Stretch). It worked without a problem.

Can you name your gcc version?

**Comment by ClosetMonkey** [comment]
Not at the time, but It would have been the default. The exact release was `Armbian_5.75_Aml-s905_Debian_stretch_default_4.20.5_desktop_20190211.img.xz`, I'm sure someone can answer at https://forum.armbian.com/

**Comment by ClosetMonkey** [comment]
GCC 6.3.0

**Comment by twose** [comment]
看起来更像是编译环境的问题
暂时没有头绪

**Comment by deminy** [comment]
Tried building an arm64v8 Docker image manually and didn't see any problem:

```bash
git clone https://github.com/swoole/docker-swoole.git
cd docker-swoole
composer update -n
./bin/generate-dockerfiles.php master
IMAGE_NAME=swoole SWOOLE_VERSION=master ./bin/build.sh arm64v8
docker run --rm -t swoole "gcc -v" # gcc version 8.3.0 (Debian 8.3.0-6)
```

I'd suggest using a new version of gcc and try again.

**Comment by ClosetMonkey** [comment]
I agree with @twose. Specifically, Arm support is fairly limited compared to other chips in Linux so your better off using a more developed/supported distribution.

**Comment by matyhtf** [comment]
@xywf221 试试修改编译配置，改为使用 ucontext 实现方式？
