### ISSUE TITLE
websocket服务端内存使用大于10M报错

### ISSUE THREAD

**Issue by forgetyn** [swoole/swoole-src#2851]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
使用swoole作为服务端对接一个考勤机硬件,使用单进程,从mysql数据库里面读取用户数据,当一次性读取的用户数量大于3000的时候读取就会报错,此时内存占用到10M左右,用户数据为基本信息,无长数据字段(name,userid,face_img(人脸地址)),请问下设置那个参数可以扩大这个限制?

2. What did you expect to see?
期望不要报错,或设置一个参数增加内存限制

3. What did you see instead?
2019-09-24 16:25:29 1 .memory_get_usage:4324456,

2019-09-24 16:25:29 2 .memory_get_usage:5038776,

2019-09-24 16:25:29 getSynUserInfo 1 .memory_get_usage:5103880,

2019-09-24 16:25:29 getSynUserInfo 2 .memory_get_usage:5171048,

2019-09-24 16:25:29 getSynUserInfo unset begin .memory_get_usage:8699784,

2019-09-24 16:25:29 getSynUserInfo unset last .memory_get_usage:8692056,

2019-09-24 16:25:29 getSynUserInfo stuid .memory_get_usage:10867024,

2019-09-24 16:25:29 getSynUserInfo unset stuid .memory_get_usage:8425760,

2019-09-24 16:25:29 getSynUserInfo unset begin 2:8989280,

2019-09-24 16:25:29 getSynUserInfo unset last 2:8693936,

//再这里读取了大概3000个用户 造成内存大于10M多久报一下错误,我调试把读取的用户缩小到1000就不会报错了
[2019-09-24 16:25:29 $24616.0] WARNING swManager_check_exit_status: worker#0[pid=24618] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.4.6, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:

gdb
(gdb) bt
#0  gc_mark_grey (ref=0x7fe0d0d10bc4) at /root/lnmp1.4/src/php-7.1.14/Zend/zend_gc.c:571
#1  0x000000000087d416 in gc_mark_grey (ref=<optimized out>) at /root/lnmp1.4/src/php-7.1.14/Zend/zend_gc.c:511
#2  0x000000000087d416 in gc_mark_grey (ref=<optimized out>) at /root/lnmp1.4/src/php-7.1.14/Zend/zend_gc.c:511
#3  0x000000000087e338 in gc_mark_roots () at /root/lnmp1.4/src/php-7.1.14/Zend/zend_gc.c:598
#4  zend_gc_collect_cycles () at /root/lnmp1.4/src/php-7.1.14/Zend/zend_gc.c:1072
#5  0x000000000087df9e in gc_possible_root (ref=0x7fe0bdd24508) at /root/lnmp1.4/src/php-7.1.14/Zend/zend_gc.c:286
#6  0x00000000008b2098 in zend_assign_to_variable (value_type=16 '\020', value=0x7fe0bdcc7d88, 
    variable_ptr=0x7fe0be250830) at /root/lnmp1.4/src/php-7.1.14/Zend/zend_execute.h:110
#7  ZEND_FE_FETCH_R_SPEC_VAR_HANDLER () at /root/lnmp1.4/src/php-7.1.14/Zend/zend_vm_execute.h:16890
#8  0x000000000089c21b in execute_ex (ex=<optimized out>) at /root/lnmp1.4/src/php-7.1.14/Zend/zend_vm_execute.h:429
#9  0x00007fe0c1177020 in swoole::PHPCoroutine::main_func (arg=0x7fff16cd3b50)
    at /tmp/pear/temp/swoole/swoole_coroutine.cc:736
#10 0x00007fe0c112e32b in swoole::Context::context_func (arg=0x5107168)
    at /tmp/pear/temp/swoole/src/coroutine/context.cc:130
#11 0x00007fe0c11f5ce1 in make_fcontext ()
    at /tmp/pear/temp/swoole/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:64
#12 0x0000000000200010 in ?? ()
#13 0x0000000000000091 in ?? ()
#14 0x39c9253c218a652f in ?? ()
#15 0x000000000399d6e8 in ?? ()
#16 0x000000000399d6e8 in ?? ()
#17 0x0000000000000000 in ?? ()

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.6
Built => Sep 21 2019 18:40:57
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
uname -a
Linux izuf6dzfht7fynoiraajezz 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
php -v
PHP 7.1.14 (cli) (built: Feb  5 2018 10:56:58) ( NTS )
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

**Comment by forgetyn** [comment]
第二点这边目前还没有安装好,我这边输出调试了,内存大于10Mb左右就会报这个错误,可以很好重现,

**Comment by twose** [comment]
看起来像是PHP内核GC时发生的错误

是否有可重现的代码可以打包发送过来?

**Comment by forgetyn** [comment]
可以, 我发到你邮件里面 这个邮件吗?：twosee <notifications@github.com>

**Comment by twose** [comment]
发送到 team@swoole.com

**Comment by forgetyn** [comment]
已经发送到你邮件了,辛苦你看下

**Comment by forgetyn** [comment]
感谢@twose的耐心指导, 问题已经找到, 我这边再onWorkStar里面 把table存到了server属性,
通过升级php版本以及把table要在Server创建前create 解决这个问题
