### ISSUE TITLE
print_r打印websocket实例报错

### ISSUE THREAD

**Issue by JesusuAllen** [swoole/swoole-src#2853]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
使用swoole开启websocket服务，写一个简易聊天室的demo，在使用过程中用print_r打印websocket的实例导致报错。

以下代码中的$_POST['http_server']是在onRequest时将websocket实例存进去的。

$user_name = $res['user_name'] ?? '';
        $content = $_POST['content'] ?? '';
        $serv = $_POST['http_server'];

        $data = [
            'status' => '1',
            'msg'    => '成功',
            'data'   => [],
        ];
//        这里使用print_r打印websocket的实例就会报错
//        print_r($serv);
        var_dump($serv);
        return;
//        foreach ($serv->ports[1]->connections as $fd) {
//            $data['user_name'] = $user_name;
//            $data['content'] = $content;
//            $serv->push($fd, json_encode($data));
//        }

2. What did you expect to see?
正常打印

3. What did you see instead?
[2019-09-25 14:22:42 $17839.0]	WARNING	swManager_check_exit_status: worker#0[pid=17843] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.4.7-alpha, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

4. What version of Swoole are you using (show your `php --ri swoole`)?
Version => 4.4.7-alpha

5. What is your machine environment used (including version of kernel & php & gcc) ?
阿里云服务器，linux centos7 php 7.2

**Comment by twose** [comment]
@JesusuAllen 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by twose** [comment]
请提供一个可以直接运行复现的脚本

**Comment by JesusuAllen** [comment]
开启对应端口后请求这个端口触发onRequest后报错

代码如下：
<?php
/**
 * Created by PhpStorm.
 * User: Linwl <linwl@imageco.com.cn>
 * Date: 2019/09/19
 * Time: 10:03
 */

class WebSocket
{

    public $ws = null;

    public function __construct()
    {
        date_default_timezone_set('PRC');

        $this->ws = new Swoole\WebSocket\Server("0.0.0.0", 9501);
//        $this->ws->listen("0.0.0.0", 9502, SWOOLE_SOCK_TCP);

        $this->ws->set(
            [
                'worker_num'      => 2,
                'task_worker_num' => 2,
            ]
        );

        $this->ws->on('message', [$this, 'onMessage']);
        $this->ws->on('request', [$this, 'onRequest']);
        $this->ws->on('task', [$this, 'onTask']);
        $this->ws->on('finish', [$this, 'onFinish']);
        $this->ws->start();
    }



    public function onMessage(Swoole\WebSocket\Server $server, $frame){}

    public function onTask(Swoole\WebSocket\Server $server, $task_id, $worker_id, $data){}

    public function onRequest($request, $response)
    {
        echo "连接成功![" . getmypid() . ']' . PHP_EOL;
        $_POST['ws'] = $this->ws;
        print_r($_POST['ws']);
    }

    public function onFinish(Swoole\WebSocket\Server $server, $task_id, $data){}

    public function onClose($ser, $fd){}
}


$ws = new WebSocket();

**Comment by twose** [comment]
@JesusuAllen 用master最新的代码编译Swoole再试试

**Comment by JesusuAllen** [comment]
OK了~

**Comment by twose** [comment]
感谢反馈
