### ISSUE TITLE
swoole里面使用Soap报错

### ISSUE THREAD

**Issue by st-tree** [swoole/swoole-src#2857]
报错信息如下：
 [2019-09-26 21:42:52] SD.ERROR: WORKER Error SoapClient::__doRequest(): connect() failed: Connection timed out (/var/www/src/app/Models/Common/TranslatedModel.php:459) [] []
swoole4.0.0下使用soap请求超时
代码如下：
try{
            $translateClient = new \SoapClient(null, array('location' =>$location, 'uri' => $uri,'connection_timeout'=>10));
            $res = $translateClient->sendHttpRequest($url, $param, $headers, $post);
            return $res;

        }catch(\SoapFault $fault){
            return $this->_errorSOAP.$fault->faultcode.','.$fault->faultstring;
        }
设置超时时间，如何捕捉这个错误？

**Comment by twose** [comment]
这和Swoole有什么关系?

**Comment by st-tree** [comment]
会有内存泄漏的情况发生
