### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by zhangjiangyuan** [swoole/swoole-src#2858]
//监听连接进入事件
$serv->on('Connect', function ($serv, $fd) {  
    echo "Client: Connect.\n";
});
//监听数据接收事件
$serv->on('Receive', function ($serv, $fd, $from_id, $data) {
    $serv->send($fd, "Server: ".$data);
});

以上代码取自官网，我使用gdb，打断点输入  "b  zim_swoole_server_send" 和 "b php_swoole_onConnect"都没用，我该如何调试呢？（有有客户端建立连接并且发送数据）

**Comment by twose** [comment]
@zhangjiangyuan 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by twose** [comment]
需要设置为SWOOLE_BASE模式且worker_num调成1, 关闭task进程

否则事件是在worker进程触发 而你gdb跟踪的是master进程, 你需要attach到想要跟踪的进程
