### ISSUE TITLE
demon running problem , NOTICE	php_swoole_server_rshutdown (ERRNO 9003): worker process is terminated by exit()/die()

### ISSUE THREAD

**Issue by ermya** [swoole/swoole-src#2859]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
i just use this simple TCP proxy example was wrote by matyhtf: 
https://github.com/swoole/proxy-server/blob/master/tcp-proxy.php

codes are here 
```
<?php
class ProxyServer
{
    protected $frontends;
    protected $backends;
    /**
     * @var swoole_server
     */
    protected $serv;
    protected $index = 0;
    protected $mode = SWOOLE_BASE;
    protected $backendServer = array('host' => '127.0.0.1', 'port' => '80');
    function run()
    {
        $serv = new swoole_server("127.0.0.1", 9509, $this->mode);
        $serv->set(array(
            'worker_num' => 8, //worker process num
            //'backlog' => 128, //listen backlog
            //'open_tcp_keepalive' => 1,
            //'log_file' => '/tmp/swoole.log', //swoole error log
        ));
        $serv->on('WorkerStart', array($this, 'onStart'));
        $serv->on('Receive', array($this, 'onReceive'));
        $serv->on('Close', array($this, 'onClose'));
        $serv->on('WorkerStop', array($this, 'onShutdown'));
        $serv->start();
    }
    function onStart($serv)
    {
        $this->serv = $serv;
        echo "Server: start.Swoole version is [" . SWOOLE_VERSION . "]\n";
    }
    function onShutdown($serv)
    {
        echo "Server: onShutdown\n";
    }
    function onClose($serv, $fd, $from_id)
    {
        //清理掉后端连接
        if (isset($this->frontends[$fd]))
        {
            $backend_socket = $this->frontends[$fd];
            $backend_socket->closing = true;
            $backend_socket->close();
            unset($this->backends[$backend_socket->sock]);
            unset($this->frontends[$fd]);
        }
        echo "onClose: frontend[$fd]\n";
    }
    function onReceive($serv, $fd, $from_id, $data)
    {
        //尚未建立连接
        if (!isset($this->frontends[$fd]))
        {
            //连接到后台服务器
            $socket = new swoole_client(SWOOLE_SOCK_TCP, SWOOLE_SOCK_ASYNC);
            $socket->closing = false;
            $socket->on('connect', function (swoole_client $socket) use ($data)
            {
                $socket->send($data);
            });
            $socket->on('error', function (swoole_client $socket) use ($fd)
            {
                echo "ERROR: connect to backend server failed\n";
                $this->serv->send($fd, "backend server not connected. please try reconnect.");
                $this->serv->close($fd);
            });
            $socket->on('close', function (swoole_client $socket) use ($fd)
            {
                echo "onClose: backend[{$socket->sock}]\n";
                unset($this->backends[$socket->sock]);
                unset($this->frontends[$fd]);
                if (!$socket->closing)
                {
                    $this->serv->close($fd);
                }
            });
            $socket->on('receive', function (swoole_client $socket, $_data) use ($fd)
            {
                //PHP-5.4以下版本可能不支持此写法，匿名函数不能调用$this
                //可以修改为类静态变量
                $this->serv->send($fd, $_data);
            });
            if ($socket->connect($this->backendServer['host'], $this->backendServer['port']))
            {
                $this->backends[$socket->sock] = $fd;
                $this->frontends[$fd] = $socket;
            }
            else
            {
                echo "ERROR: cannot connect to backend server.\n";
                $this->serv->send($fd, "backend server not connected. please try reconnect.");
                $this->serv->close($fd);
            }
        }
        //已经有连接，可以直接发送数据
        else
        {
            /**
             * @var $socket swoole_client
             */
            $socket = $this->frontends[$fd];
            $socket->send($data);
        }
    }
}
$serv = new ProxyServer();
$serv->run();
```

without any customization

2. What did you expect to see?

nothing, just simply working as proxy in daemon

3. What did you see instead?

is working fine when is run by root user on terminal , but when i run it as daemon in background like this:
php tco.php & and then close terminal
or use demonize property in code then close terminal 
the program will goes in background for working , it works perfectly but when i send 200 user connection  for test connection , after successful connection then  i kill all of them from backend server and start test connection again , face me a lot of this error in swoole error log 

[2019-09-27 08:27:19 *5115.1]	NOTICE	php_swoole_server_rshutdown (ERRNO 9003): worker process is terminated by exit()/die()
[2019-09-27 08:27:19 *5834.1]
 
and cpu usage will be 100% , when i check in htop i saw child process of swoole will close create then close and create too fast

i try this test a lot of times with a lotf of customization and without customization but every time is same  , when is run from terminal with putty , everything works perfect and fast, when i try as daemon the problem will be happened!

4. What version of Swoole are you using (show your `php --ri swoole`)?

#swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.6
Built => Sep 23 2019 07:50:18
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
#uname -a 
Linux static.18.37 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

# php -v
PHP 7.1.32 (cli) (built: Aug 28 2019 13:15:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.32, Copyright (c) 1999-2018, by Zend Technologies

#gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

cpu info : Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz  
64G memory 
32G swp

**Comment by twose** [comment]
@ermya 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by ermya** [comment]
here you are 
[valgrind.log](https://github.com/swoole/swoole-src/files/3661411/valgrind.log)

**Comment by twose** [comment]
Swoole中不能使用exit和die
https://wiki.swoole.com/wiki/page/501.html

exit在cli模式中相当于终止当前进程, 会造成进程不断退出并且不断被拉起

**Comment by ermya** [comment]
@twose thank you for your answer , i just copy and past the php code what i used ! did you see any exit or die in the code ?

**Comment by ermya** [comment]
the problem is exactly here 

```
function onClose($serv, $fd, $from_id)
    {
        //清理掉后端连接
        if (isset($this->frontends[$fd]))
        {
            $backend_socket = $this->frontends[$fd];
            $backend_socket->closing = true;
            $backend_socket->close();
            unset($this->backends[$backend_socket->sock]);
            unset($this->frontends[$fd]);
        }
        echo "onClose: frontend[$fd]\n";
    }

```

this will try to close connection from backend server ! if backend server already closed the connection  before swoole knows it then swoole will close none handle connection and that's why it will be happened in my opinion 

because there is no any exit or die in php code !

**Comment by ermya** [comment]
i found this error line also in swoole error log file 

WARNING	swSignalfd_onSignal (ERRNO 707): Unable to find callback function for signal Hangup: 1

**Comment by twose** [comment]
Sorry, I read your issue again.
The problem is your wrong operation
https://wiki.swoole.com/wiki/page/278.html
If the daemon is not enabled, the program will be terminated when the ssh terminal exits

**Comment by ermya** [comment]
@twose  thank you for your attention , i just test with and without demonize => true ,  before but same problem happened 

finally i found the exact problem ! its correct there is a hidden exit() in the code !
this one ->>>>>
> echo 
-----------------------
 when the sell exited the process goes to run in daemon and echo is not working in daemon so if there is no output, then php bottom-level encounter echo failure and will exit immediately and that's why the problem was only happened in daemon mode
