### ISSUE TITLE
关于废弃 swoole_event_wait() 的一点小疑问

### ISSUE THREAD

**Issue by xchl** [swoole/swoole-src#2864]
想知道swoole_event_wait() 为什么要废弃？是因为名字和协程不搭吗，一些老业务改协程的时候或者协程嵌套较多的场景下 swoole_event_wait() 方式明显比写Scheduler 或者 waitgroup 要方便的多。

**Comment by twose** [comment]
和名字没有关系
event_wait和waitgroup不是一个性质

event_wait是等待事件循环结束的
waitgroup是控制协程调度的

event_wait结束代表着整个事件循环结束 所有事件循环的设施都会**销毁**
event_wait后在此之前创建的连接等资源都会被释放

scheduler是为了隔离多个事件循环, 保证程序能够干净地运行, 而不是混杂在一起

良好设计的程序, 整个生命周期应该只有一次事件循环, 而不是多次, 其余的调度完全可以交由协程处理, 而不是暴露出事件循环的设施

**Comment by matyhtf** [comment]
4.4 版本不会废弃 Event::wait
