### ISSUE TITLE
\Process\Pool daemon 子进程输出问题

### ISSUE THREAD

**Issue by km3945** [swoole/swoole-src#2867]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```php
\Swoole\process::daemon();
$pool = new \Swoole\Process\Pool($3);
```
子进程的echo  一直在输出. 怎么处理?
按代码的意思就是以守护进程方式运行.所有输出都重定向

2. What did you expect to see?

子进程的echo 一直在转出

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.7
Built => Sep 29 2019 00:00:21
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/ae2e96eefaad3a8671564ebd5ffbcafd58af167a

**Comment by matyhtf** [comment]
需要重定向，已支持
