### ISSUE TITLE
Cygwin下编译安装swoole-4.4.7的问题

### ISSUE THREAD

**Issue by pechn** [swoole/swoole-src#2868]
- 编译swoole-4.4.7后可以正常安装和启动swoole_server，但无法接受client的连接
- 在相同的cygwin环境下安装PHP-7.1.6和swoole-2.2.0，运行swoole_server一切正常，客户端和服务端收发信息都正常

以下是swoole_server的基本设置：
```
$this->serv = new swoole_server('0.0.0.0', 9501);
$this->serv->set(array(
            'worker_num'               => 4, // 开启的进程数量
            'max_request'              => 0, // TCP/UDP最大链接请求数
            'task_worker_num'          => 64, // 任务处理最大进程请求数
            'task_max_request'         => 0, // 设置task进程的最大任务数。一个task进程在处理完超过此数值的任务后将自动退出。这个参数是为了防止PHP进程内存溢出。如果不希望进程自动退出可以设置为0。
            'daemonize'                => 1, // 是否作为守护进程,此配置一般配合log_file使用
            'log_file'                 => $path, // 作为守护进程的日志
            'backlog'                  => 1024,
            'open_eof_split'           => true,
            'open_eof_check'           => true, // 开启分包校验，8个#号表示一次网络通信结束
            'package_eof'              => "########",
            'heartbeat_check_interval' => 60, // 表示每60秒，遍历所有连接
            'heartbeat_idle_time'      => 300, // 一个连接如果300秒内未向服务器发送任何数据，此连接将被强制关闭
            'package_max_length'       => 1024 * 1024 * 2, // 发送及接收缓冲区最大为2M
        ));
```
是否需要针对swoole 4.x和swoole 2.x进行代码调整？或者编译参数和选项有哪些需要调整的地方？

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Windows 10 1903 + Cygwin-3.0.7下通过源码编译安装Swoole-4.4.7
PHP-7.3.7

2. What did you expect to see?
a) 编译成功
b) make install成功装swoole.dll
c) 正常启动swoole_server
d) 客户端、服务端发送和接收正常

3. What did you see instead?
a) 编译成功
b) make install成功装swoole.dll
c) 正常启动swoole_server
**d) 客户端、服务端发送和接收异常**

4. What version of Swoole are you using (show your `php --ri swoole`)?
$ php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.7
Built => Oct  7 2019 16:17:23
coroutine => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
Windows 10 1903 
Cygwin 3.0.7
PHP 7.3.7
gcc 7.4.0
Make 4.2.1

**Comment by twose** [comment]
尝试去掉所有的max_request选项?

信息太少没办法继续追踪, 最好能提供可复现的代码

**Comment by pechn** [comment]
> 
> 
> 尝试去掉所有的max_request选项?
> 
> 信息太少没办法继续追踪, 最好能提供可复现的代码

你好，同样的代码在swoole-2.2.0下是没问题的，在swoole-4.4.7下就无法建立连接。
我看到官方有提供cygwin编译好的bin包，但使用的是PHP 7.1，能否提供一个PHP 7.3+Swoole 4.4版本？

**Comment by twose** [comment]
暂无, PHP版本由cygwin上游决定

应该有其它因素导致, 可以看看官网文档的向下不兼容部分

信息太少没办法给出更多建议

**Comment by matyhtf** [comment]
Cygwin 下不支持 SWOOLE_PROCESS 模式，请改为 SWOOLE_BASE 模式就可以了。

**Comment by pechn** [comment]
> 
> 
> Cygwin 下不支持 SWOOLE_PROCESS 模式，请改为 SWOOLE_BASE 模式就可以了。

@matyhtf 
我试着通过源码编译不同的版本，发现swoole-4.2.4以前的版本，在cygwin下使用SWOOLE_PROCESS模式，可以正常运行，代码如下：

`$this->serv = new swoole_server('0.0.0.0', 9501); // 默认使用SWOOLE_PROCESS模式`

但使用swoole-4.2.4以后的版本，需显示使用SWOOLE_BASE模式才可以正常运行，代码如下：

`$this->serv = new swoole_server('0.0.0.0', 9501, SWOOLE_BASE);`

是因为swoole-4.2.4之前的版本，在cygwin下强制使用SWOOLE_BASE模式吗？

**Comment by pechn** [comment]
@matyhtf @twose 
我简单对比了swoole-4.2.4和swoole-4.2.3的源码，发现在4.2.4的swoole_server.c中函数：**PHP_METHOD(swoole_server, __construct)**，移除了对宏__CYGWIN__的判断。

而在4.2.3的相同函数中，有下面的代码：
```
#ifdef __CYGWIN__
    serv_mode = SW_MODE_SINGLE;
#elif !defined(SW_USE_THREAD)
    if (serv_mode == SW_MODE_THREAD || serv_mode == SW_MODE_BASE)
    {
        serv_mode = SW_MODE_SINGLE;
        swoole_php_fatal_error(E_WARNING, "can't use multi-threading in PHP. reset server mode to be SWOOLE_MODE_BASE");
    }
#endif
```

如果在4.2.4及后续的版本中，加入下面的判断，应该就可以解决我提到的问题：
```
#ifdef __CYGWIN__
     serv_mode = SW_MODE_BASE;
#endif
```

根据目前最新发布的swoole-4.4.7，我在swoole_server.cc的第1956行加入上述判断，重新编译，服务启动和数据收发一切正常！

**Comment by pechn** [comment]
@matyhtf @twose 
针对多数情况下在windows环境中进行swoole开发的团队，cygwin环境比较重要，今后发布的版本是否可以考虑在函数**PHP_METHOD(swoole_server, __construct)**中重新增加对宏__CYGWIN__的判断？

**Comment by pechn** [comment]
@matyhtf 有看到提交了相关修复，[cygwin_with_process](https://github.com/swoole/swoole-src/compare/cygwin_with_process)，后续版本可以在cygwin中支持SWOOLE_PROCESS模式了吗？

**Comment by matyhtf** [comment]
正在支持。
