### ISSUE TITLE
WARNING swProcessPool_wait: worker#17 abnormal exit

### ISSUE THREAD

**Issue by joanhey** [swoole/swoole-src#2869]
In the Thechempower benchmark the Swoole have a lot of errors.
https://tfb-status.techempower.com/unzip/results.2019-10-05-23-14-37-606.zip/results/20191002030153/swoole/run/swoole.log

I send the bug like say the message.

Perhaps it's an error in the code and not in Swoole.

Please, could anybody from the community update de code? 
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/swoole/swoole-server.php

Thank you.

**Comment by twose** [comment]
A boundary problem caused by a fatal error.
I noticed that you have already requested the PHP code patch, it is right.
