### ISSUE TITLE
进程间使用 Socket 通信遇到 (32) Broken pipe 错误

### ISSUE THREAD

**Issue by NHZEX** [swoole/swoole-src#2873]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
进程1使用`exportSocket()->sendAll`发送数据到进程2，如果进程2发生重启，进程1发送数据会产生`Broken pipe`错误。

2. What did you expect to see?
子进程重启后进程通信能正常工作

3. What did you see instead?
socket->errCode: 32
socket->errMsg: Broken pipe

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.6
Built => Sep 19 2019 01:32:34
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1c  28 May 2019
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ?
```
PHP 7.3.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:04) ( NTS )
```

---
如何重新获取正确的`Socket`（还是这个用法是错误的）？

**Comment by twose** [comment]
没有复现, 贴一下代码

**Comment by NHZEX** [comment]
> 没有复现, 贴一下代码

https://gist.github.com/NHZEX/86c2dc20747637055a35c729e61ce357

composer require nhzex/zsw-core
composer require symfony/var-dumper

**Comment by twose** [comment]
还少了Monolog

装完运行报错

`Swoole\Process::exportSocket(): no pipe, cannot export stream` (没有设置IPC类型?)

`Fatal error: Uncaught Error: Call to undefined method Worker1::sendIPCMessage()`

**Comment by NHZEX** [comment]
> 还少了Monolog
> 
> 装完运行报错
> 
> `Swoole\Process::exportSocket(): no pipe, cannot export stream` (没有设置IPC类型?)
> 
> `Fatal error: Uncaught Error: Call to undefined method Worker1::sendIPCMessage()`

抱歉啊，我昨天改了一下版本，贴下正确的composer.json
```
{
    "require": {
        "nhzex/zsw-core": "v1.2.0",
        "symfony/var-dumper": "^4.3",
        "monolog/monolog": "^2.0"
    }
}
```

**Comment by NHZEX** [comment]
目前实现的通信工作稳定，这个问题之后在找时间重新测试。
