### ISSUE TITLE
centos swoole-4.3.5 possibly undefined macro: AS_CASE 

### ISSUE THREAD

**Issue by codezm** [swoole/swoole-src#2875]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
config.m4:288: warning: AC_CANONICAL_HOST invoked multiple times
configure:7523: error: possibly undefined macro: AS_CASE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

2. What did you expect to see?

phpize is pass

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.3.5

5. What is your machine environment used (including version of kernel & php & gcc) ?
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-54)
PHP 7.0.33 (cli) (built: Oct  9 2019 10:22:28) ( NTS )
CentOS release 5.8 (Final)

**Comment by twose** [comment]
1. autoconf可能需要升级
2. GCC版本太低

**Comment by codezm** [comment]
请问有最低版本推荐吗？
- autoconf
- GCC

**Comment by codezm** [comment]
目前 autoconf version:
autoconf-2.59-12

**Comment by twose** [comment]
autoconf 2.69
gcc 4.8

README和文档里都有, 请自行查看

**Comment by codezm** [comment]
autoconf 和 gcc 升级后 phpize pass
make 时报如下错误, 是 openssl 版本过低吗？
swoole-4.3.5/src/coroutine/socket.cc:1194:73: 错误：‘swSSL_option’没有名为‘tls_host_name’的成员
     if (ssl_option.tls_host_name && swSSL_check_host(socket, ssl_option.tls_host_name) < 0)

**Comment by codezm** [comment]
README 中有 gcc version 要求，但没有 autoconf version 要求，文档是[官网](https://wiki.swoole.com/wiki/page/6.html)吗？

**Comment by codezm** [comment]
openssl 问题，升级后可解决，最终还是放弃了，因为 ` require linux kernel version 2.6.32 or later` system `2.6.18-308.el5`， 非常感谢答复 @twose

**Comment by twose** [comment]
系统太旧了
ssl版本的问题已修复
