### ISSUE TITLE
swoole_server的php_swoole_onReceive没有做fci_cache空值判断出错

### ISSUE THREAD

**Issue by z5864703** [swoole/swoole-src#2881]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
基于swoole做代理服务器，正常的收发数据，但是会出现WARNING	php_swoole_server_get_fci_cache: invalid server_fd[3]错误，紧接着
PHP Fatal error:  Uncaught ErrorException: Swoole\Server::start(): Bad function in

通过看swoole源码，应该是在swoole_server.cc的php_swoole_onReceive方法中没有判断fci_cache结构体是否空值，导致zend::function::call调用产生bad function错误。
然后看php_swoole_onConnect和php_swoole_onClose方法是有判断fci_cache空值的。

我只注册了三个事件：Connect、Receive、Close

2. What did you expect to see?
进程正常工作

3. What did you see instead?
进程退出

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.7
Built => Oct 10 2019 10:21:02
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ?
PHP 7.2.17 (cli) (built: Jun 28 2019 12:02:01) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.17, Copyright (c) 1999-2018, by Zend Technologie

**Comment by z5864703** [comment]
还有一个问题，为什么会导致server_fd不存在？根因应该在这里，其次才是对空值做异常处理

**Comment by huanghantao** [comment]
@z5864703 有最小的可复现代码吗？

**Comment by z5864703** [comment]
> @z5864703 有最小的可复现代码吗？

没有，逻辑也不算复杂，说下大概逻辑吧

客户端 -> 服务端 -> 设备端 -> 代理目标网站

服务端是基于swoole实现的代理服务器，收到客户端的代理请求，将数据通过长连接转发到设备端，由设备端去访问代理目标网站，并将响应结果发送到服务端，服务端再响应给用户。

这里有一个情况就是大量的创建连接和关闭连接，存在客户端已经关闭到服务端连接的情况下，服务端收到设备端的数据转发给客户端，会发送失败，这个是正常，因为客户端已经关闭连接了。

所以我推测是在大量连接开关的情况下，swoole接收数据缓冲区有残留数据，触发onReceive事件，但是连接对象早已释放，所以获取不到server_fd了

**Comment by twose** [comment]
php_swoole_onReceive没有空值判断是因为这是一个必须注册的事件而非可选

**Comment by huanghantao** [comment]
> php_swoole_onReceive没有空值判断是因为这是一个必须注册的事件而非可选

在注册的时候应该是已经判断不能为空，如果为空直接`Warning`。

**Comment by z5864703** [comment]
> php_swoole_onReceive没有空值判断是因为这是一个必须注册的事件而非可选

所以后面我回复补充问题根因应该在server_fd空值问题，server_fd依赖的是swEventData req对象，这个请求对象应该在触发onReceive事件前已经被销毁了，导致server_fd没值继而出现异常退出进程

**Comment by z5864703** [comment]
> > php_swoole_onReceive没有空值判断是因为这是一个必须注册的事件而非可选
> 
> 在注册的时候应该是已经判断不能为空，如果为空直接`Warning`。

问题上我已说明，我注册了Receive事件，所以不是没注册事件导致的

**Comment by z5864703** [comment]
忘记说明，不是服务器一启动就报错，是在大量连接数据交互情况下出现

**Comment by twose** [comment]
> > php_swoole_onReceive没有空值判断是因为这是一个必须注册的事件而非可选
> 
> 在注册的时候应该是已经判断不能为空，如果为空直接`Warning`。

为空会直接Error

**Comment by twose** [comment]
@z5864703 最后确认下, 是否使用了dispatch_mode 1 或 3

**Comment by z5864703** [comment]
> @z5864703 最后确认下, 是否使用了dispatch_mode 1 或 3, 这两种情况下事件回调是无序的, 容易出现receive回调时连接已被释放

dispatch_mode使用的是2

**Comment by twose** [comment]
2的话仍待确认

**Comment by matyhtf** [comment]
是否存在 跨worker进程 close 的逻辑。dispatch_mode = 2的模式，fd 会分配给固定的 worker，是否有不是当前 worker 关闭的逻辑

**Comment by z5864703** [comment]
> 是否存在 跨worker进程 close 的逻辑。dispatch_mode = 2的模式，fd 会分配给固定的 worker，是否有在非当前 Worker 关闭连接的逻辑？

是的，有这种逻辑

**Comment by twose** [comment]
@z5864703 master修复了这个问题 可以试试

**Comment by matyhtf** [comment]
@z5864703 已修复此问题。这里存在一个技术细节，非当前 Worker 需要通过消息传递到对应的 Worker 进程执行 onClose 并关闭连接，否则会出现以上问题。

感谢你的问题反馈！
