### ISSUE TITLE
互斥锁的使用限制问题

### ISSUE THREAD

**Issue by lg430** [swoole/swoole-src#2884]
我想使用跨进程的互斥锁, 目前php可以通过flock或借助redis实现, 但不是太想使用这两种方式,

swoole提供了基于内存的lock, 但文档说明不能用于协程环境,

请问后续swoole会支持无任何限制的lock吗, 或者有其他方式实现全局互斥锁吗?

**Comment by huanghantao** [comment]
目前的锁如果开发者使用不当，会造成同一个进程与自己死锁。
今年的PHP大会上，好像说是不打算实现协程之间的锁机制。推荐使用channel。

**Comment by huanghantao** [comment]
@lg430 目前的锁如果开发者使用不当，会造成同一个进程与自己死锁。
今年的PHP大会上，好像说是不打算实现协程之间的锁机制。推荐使用channel。

**Comment by lg430** [comment]
@huanghantao 是全局互斥锁, 跨进程跨协程, 这个使用场景太多了, 很需要 (开发者使用不当这个是开发者的问题)

**Comment by Yurunsoft** [comment]
+1，强烈建议增加跨进程的，支持协程的锁

**Comment by twose** [comment]
能用于协程环境, 死锁问题需要自己编程解决

**Comment by matyhtf** [comment]
channel + 进程间通信的方式实现起来有一些复杂，而且只能本应用内使用。

建议使用 redis 或者 Swoole\Server 实现分布式锁，客户端使用 Coroutine\Client 

CSP 编程的核心理念就是用 消息通信代替 数据同步和锁的机制。

**Comment by huanghantao** [comment]
> @huanghantao 是全局互斥锁, 跨进程跨协程, 这个使用场景太多了, 很需要 (开发者使用不当这个是开发者的问题)

其实进程之间怎么用，不同进程中的协程里面就可以怎么用。在同一个进程里面的多个协程里面使用就需要注意了，因为同一个进程里面的协程切来切去就自己锁死自己了，毕竟不是这个锁的粒度不是协程级别的。
