### ISSUE TITLE
ubuntu16.04安装swoole.4.4.6

### ISSUE THREAD

**Issue by daylight890307** [swoole/swoole-src#2887]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
ubuntu16.04安装swoole.4.4.6，PHP版本是7.1，当执行到make这一步的时候，就会报错，autoconf，automake，libtool，pcre均已安装，现在不知道是什么原因了，求帮助

2. What did you expect to see?
成功安装，之前编译过2.x和1.x的版本，没出现过这个问题

3. What did you see instead?
错误信息
No rule to make target '/data/swoole/swoole.c', needed by 'swoole.lo'. Stop.

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole.4.4.6

5. What is your machine environment used (including version of kernel & php & gcc) ?
PHP 7.1.4 (cli) (built: Apr 21 2017 11:33:02) ( NTS )
Linux version 4.4.0-63-generic (buildd@lcy01-31) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #84-Ubuntu SMP Wed Feb 1 17:20:32 UTC 2017

**Comment by matyhtf** [comment]
请贴出完整的 gcc 错误日志

**Comment by daylight890307** [comment]
root@iZbp1fw4l7pwlu16fqes9iZ:/data/swoole# ./configure --with-php-config=/usr/local/php71/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php71
checking for PHP includes... -I/usr/local/php71/include/php -I/usr/local/php71/include/php/main -I/usr/local/php71/include/php/TSRM -I/usr/local/php71/include/php/Zend -I/usr/local/php71/include/php/ext -I/usr/local/php71/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php71/lib/php/extensions/no-debug-non-zts-20160303
checking for PHP installed headers prefix... /usr/local/php71/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable swoole debug... no
checking enable sockets support... no
checking enable async_redis support... no
checking enable openssl support... no
checking enable http2.0 support... no
checking enable thread support... no
checking enable hugepage support... no
checking swoole support... yes, shared
checking swoole static compile support... no
checking swoole support... yes, shared
checking for OpenSSL support... no
checking for jemalloc support... no
checking enable mysqlnd support... no
checking whether to enable coroutine... yes
checking enable picohttpparser support... no
checking swoole support... yes, shared
checking enable timewheel support... no
checking if compiling with clang... no
checking for cpu affinity... yes
checking for socket REUSEPORT... yes
checking for futex... yes
checking for clock_gettime in -lrt... yes
checking for accept4 in -lc... yes
checking for signalfd in -lc... yes
checking for timerfd_create in -lc... yes
checking for eventfd in -lc... yes
checking for epoll_create in -lc... yes
checking for poll in -lc... yes
checking for sendfile in -lc... yes
checking for kqueue in -lc... no
checking for backtrace in -lc... yes
checking for daemon in -lc... yes
checking for mkostemp in -lc... yes
checking for inotify_init in -lc... yes
checking for malloc_trim in -lc... yes
checking for inotify_init1 in -lc... yes
checking for gethostbyname2_r in -lc... yes
checking for ptrace in -lc... yes
checking for pthread_rwlock_init in -lpthread... yes
checking for pthread_spin_lock in -lpthread... yes
checking for pthread_mutex_timedlock in -lpthread... yes
checking for pthread_barrier_init in -lpthread... yes
checking for pcre_compile in -lpcre... yes
checking for redisConnect in -lhiredis... no
checking for nghttp2_hd_inflate_new in -lnghttp2... no
checking for gzgets in -lz... yes
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
root@iZbp1fw4l7pwlu16fqes9iZ:/data/swoole# make
make: *** No rule to make target '/data/swoole/swoole.c', needed by 'swoole.lo'.  Stop.
root@iZbp1fw4l7pwlu16fqes9iZ:/data/swoole# make
make: *** No rule to make target '/data/swoole/swoole.c', needed by 'swoole.lo'.  Stop.
root@iZbp1fw4l7pwlu16fqes9iZ:/data/swoole# make
make: *** No rule to make target '/data/swoole/swoole.c', needed by 'swoole.lo'.  Stop.
root@iZbp1fw4l7pwlu16fqes9iZ:/data/swoole# ./configure --with-php-config=/usr/local/php71/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php71
checking for PHP includes... -I/usr/local/php71/include/php -I/usr/local/php71/include/php/main -I/usr/local/php71/include/php/TSRM -I/usr/local/php71/include/php/Zend -I/usr/local/php71/include/php/ext -I/usr/local/php71/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php71/lib/php/extensions/no-debug-non-zts-20160303
checking for PHP installed headers prefix... /usr/local/php71/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable swoole debug... no
checking enable sockets support... no
checking enable async_redis support... no
checking enable openssl support... no
checking enable http2.0 support... no
checking enable thread support... no
checking enable hugepage support... no
checking swoole support... yes, shared
checking swoole static compile support... no
checking swoole support... yes, shared
checking for OpenSSL support... no
checking for jemalloc support... no
checking enable mysqlnd support... no
checking whether to enable coroutine... yes
checking enable picohttpparser support... no
checking swoole support... yes, shared
checking enable timewheel support... no
checking if compiling with clang... no
checking for cpu affinity... yes
checking for socket REUSEPORT... yes
checking for futex... yes
checking for clock_gettime in -lrt... yes
checking for accept4 in -lc... yes
checking for signalfd in -lc... yes
checking for timerfd_create in -lc... yes
checking for eventfd in -lc... yes
checking for epoll_create in -lc... yes
checking for poll in -lc... yes
checking for sendfile in -lc... yes
checking for kqueue in -lc... no
checking for backtrace in -lc... yes
checking for daemon in -lc... yes
checking for mkostemp in -lc... yes
checking for inotify_init in -lc... yes
checking for malloc_trim in -lc... yes
checking for inotify_init1 in -lc... yes
checking for gethostbyname2_r in -lc... yes
checking for ptrace in -lc... yes
checking for pthread_rwlock_init in -lpthread... yes
checking for pthread_spin_lock in -lpthread... yes
checking for pthread_mutex_timedlock in -lpthread... yes
checking for pthread_barrier_init in -lpthread... yes
checking for pcre_compile in -lpcre... yes
checking for redisConnect in -lhiredis... no
checking for nghttp2_hd_inflate_new in -lnghttp2... no
checking for gzgets in -lz... yes
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged
root@iZbp1fw4l7pwlu16fqes9iZ:/data/swoole# make
make: *** No rule to make target '/data/swoole/swoole.c', needed by 'swoole.lo'.  Stop.
root@iZbp1fw4l7pwlu16fqes9iZ:/data/swoole# make
make: *** No rule to make target '/data/swoole/swoole.c', needed by 'swoole.lo'.  Stop.
root@iZbp1fw4l7pwlu16fqes9iZ:/data/swoole# ./configure --with-php-config=/usr/local/php71/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php71
checking for PHP includes... -I/usr/local/php71/include/php -I/usr/local/php71/include/php/main -I/usr/local/php71/include/php/TSRM -I/usr/local/php71/include/php/Zend -I/usr/local/php71/include/php/ext -I/usr/local/php71/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php71/lib/php/extensions/no-debug-non-zts-20160303
checking for PHP installed headers prefix... /usr/local/php71/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable swoole debug... no
checking enable sockets support... no
checking enable async_redis support... no
checking enable openssl support... no
checking enable http2.0 support... no
checking enable thread support... no
checking enable hugepage support... no
checking swoole support... yes, shared
checking swoole static compile support... no
checking swoole support... yes, shared
checking for OpenSSL support... no
checking for jemalloc support... no
checking enable mysqlnd support... no
checking whether to enable coroutine... yes
checking enable picohttpparser support... no
checking swoole support... yes, shared
checking enable timewheel support... no
checking if compiling with clang... no
checking for cpu affinity... yes
checking for socket REUSEPORT... yes
checking for futex... yes
checking for clock_gettime in -lrt... yes
checking for accept4 in -lc... yes
checking for signalfd in -lc... yes
checking for timerfd_create in -lc... yes
checking for eventfd in -lc... yes
checking for epoll_create in -lc... yes
checking for poll in -lc... yes
checking for sendfile in -lc... yes
checking for kqueue in -lc... no
checking for backtrace in -lc... yes
checking for daemon in -lc... yes
checking for mkostemp in -lc... yes
checking for inotify_init in -lc... yes
checking for malloc_trim in -lc... yes
checking for inotify_init1 in -lc... yes
checking for gethostbyname2_r in -lc... yes
checking for ptrace in -lc... yes
checking for pthread_rwlock_init in -lpthread... yes
checking for pthread_spin_lock in -lpthread... yes
checking for pthread_mutex_timedlock in -lpthread... yes
checking for pthread_barrier_init in -lpthread... yes
checking for pcre_compile in -lpcre... yes
checking for redisConnect in -lhiredis... no
checking for nghttp2_hd_inflate_new in -lnghttp2... no
checking for gzgets in -lz... yes
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged
root@iZbp1fw4l7pwlu16fqes9iZ:/data/swoole# make
make: *** No rule to make target '/data/swoole/swoole.c', needed by 'swoole.lo'.  Stop.

好的，这些行吗

**Comment by matyhtf** [comment]
请重新执行一下 phpize

**Comment by daylight890307** [comment]
root@iZbp1fw4l7pwlu16fqes9iZ:/data/swoole# /usr/local/php71/bin/phpize
Configuring for:
PHP Api Version:         20160303
Zend Module Api No:      20160303
Zend Extension Api No:   320160303
root@iZbp1fw4l7pwlu16fqes9iZ:/data/swoole# ./configure --with-php-config=/usr/local/php71/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php71
checking for PHP includes... -I/usr/local/php71/include/php -I/usr/local/php71/include/php/main -I/usr/local/php71/include/php/TSRM -I/usr/local/php71/include/php/Zend -I/usr/local/php71/include/php/ext -I/usr/local/php71/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php71/lib/php/extensions/no-debug-non-zts-20160303
checking for PHP installed headers prefix... /usr/local/php71/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for OpenSSL support... yes, shared
checking for Kerberos support... no
checking whether to use system default cipher list instead of hardcoded value... no
checking for RAND_egd... no
checking for pkg-config... /usr/bin/pkg-config
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
root@iZbp1fw4l7pwlu16fqes9iZ:/data/swoole# make
make: *** No rule to make target '/data/swoole/openssl.c', needed by 'openssl.lo'.  Stop.

重新执行过了，执行前把文件夹清空重新解包了，开始提示没有config.m4，把openssl里config0.m4复制过来，是因为这个的问题吗

**Comment by matyhtf** [comment]
请按照官方提供的编译方法 进行编译。

**Comment by daylight890307** [comment]
嗯，是用官方的方法一步步来的，只是解压缩的swoole文件夹内没有config.m4，所以就找了个放进去了

**Comment by huanghantao** [comment]
@daylight890307 你不能找其他扩展的`config.m4`文件。因为每个扩展的`config.m4`文件是这个扩展特有的。
