### ISSUE TITLE
sendto to reactor failed

### ISSUE THREAD

**Issue by lg430** [swoole/swoole-src#2889]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

[2019-10-16 02:00:22 *590.6]    WARNING swFactoryProcess_finish(:472): sendto to reactor failed, Error: No buffer space available[105]

网上并没有搜索到这个错误信息, 请问是哪里的问题呢 ?

```
        self::$serv = new \Swoole\Server(self::$sconfig['server']['host'], self::$sconfig['server']['port']);
        self::$serv->set([
            'daemonize'             => 1,
            'reactor_num'           => 8,
            'worker_num'            => 8,
            'max_request'           => 0,
            'dispatch_mode'         => 1,
            'log_file'              => LOG_PATH . '/error.log',
            'open_length_check'     => true,
            'package_max_length'    => 1024 * 1024 * 2,
            'package_length_offset' => 6,
            'package_length_type'   => 'V',
            'package_body_offset'   => 10,
            'socket_buffer_size'    => 1024 * 1024 * 64,
            'buffer_output_size'    => 1024 * 1024 * 10,
            'open_tcp_nodelay'      => true,
            'enable_reuse_port'     => true,
            'open_cpu_affinity'     => true,
        ]);
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.6
Built => Aug 26 2019 16:10:16
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.1e-fips 11 Feb 2013
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

linux kernel: 4.18.7
php: 7.1.2

**Comment by twose** [comment]
内存不够用了 你这设置的buffer尺寸太大了 参数不是这么乱调的

**Comment by matyhtf** [comment]
请看一下内核参数怎么设置的

```
net.ipv4.tcp_mem  =   379008       505344  758016
net.ipv4.tcp_wmem = 4096        16384   4194304
net.ipv4.tcp_rmem = 4096          87380   4194304
net.core.wmem_default = 8388608
net.core.rmem_default = 8388608
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
```

系统内存是否不足

**Comment by lg430** [comment]
@matyhtf  这是昨晚2点的日志, 存在大量客户端主动断开了链接导致swoole服务端send失败, 持续了一分钟就正常了, 监控显示系统内存只占了3%, 所以应该不是内存不足.

我这由于运维不让修改线上机器内核参数(Docker模板), 所以都是默认.
net.ipv4.tcp_mem = 1538709	2051613	3077418
net.ipv4.tcp_wmem = 4096	65536	16777216
net.ipv4.tcp_rmem = 4096	87380	16777216
其他的查不到了

只是想确认下什么情况下会出现这个问题, 是socket缓冲区满了吗, 只能通过修改内核参数处理吗

**Comment by matyhtf** [comment]
这是由于内核 大块连续内存不足引起的。

**Comment by twose** [comment]
socket_buffer_size
buffer_output_size
调的也忒大了

**Comment by lg430** [comment]
@twose 之前这两个参数都没设置(默认), 发现上面的错误日志后才加上的, 结果两种情况下都有上面这个错误

**Comment by minguo** [comment]
我也遇到这个问题,版本也是4.3.6,然后过了一段时间发现用swoole client连接server,发现连接被拒绝了

现在也找不到原因~~~~
