### ISSUE TITLE
swoole 热重启 处理完请求到断开连接有短暂的时间差造成部分请求损失

### ISSUE THREAD

**Issue by caozhipan** [swoole/swoole-src#2895]
## 背景说明：
- 线上k8s服务（swoole process模式 48 worker）执行kill -TERM 后 仍有部分请求失败

- 针对Connection: keep-alive类的请求，nginx 和swoole在reload时都是处理完当前请求后给client发一个Fin包断开连接，而不是在当前请求的response header里设置Connection: close
这种断开方式经常会造成client会复用一个即将断开的连接发请求，导致请求失败，

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
- server.php，client.go 代码见附录

- server 采用process模式
- client 使用go1.12.6 http.DefaultClient

操作过程：
- 整个过程使用tcpdump抓包
- 使用client.go 串行连续发送两次请求(keep-alive), server 端每个请求sleep 30s 再返回
- 第一个请求刚发出，等待response期间, server端执行 kill -SIGTERM

2. What did you expect to see?
我们希望server处理完第一个请求后即断开连接，发送第二个请求时尝试重新建立连接
比较优雅的做法时第一个请求的response header 中设置 Connection: close

3. What did you see instead?
如下图，client 在收到第一个请求的response(此时 response header 为Connection: keep-alive)后，在尚未收到server 发的FIN包时 即使用此连接继续发送请求，随后又收到后端发送的FIN包，导致第二次请求失败
![image](https://user-images.githubusercontent.com/5044014/67010311-fb113580-f11f-11e9-93b8-c30919462397.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole版本：v4.4.8

5. What is your machine environment used (including version of kernel & php & gcc) ?
php version: php-7.1.12
kernel: Linux test-qa-web01 2.6.32-358.6.2.el6.x86_64 #1 SMP Thu May 16 20:59:36 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

## 
## 附录：
1. server.php

```php
<?php
/**
 * Created by PhpStorm.
 * User: caozhipan
 * Date: 2019/10/17
 */

$http = new swoole_http_server('0.0.0.0', 9704);


$http->set(array(
    'worker_num' => 48,   //工作进程数量
    'daemonize' => false,
    'max_request' => 12000,
    'log_file' =>   __DIR__.'/storage/logs/server.log'
));

$app = null;

$http->on('start', function() use ($http){
    $pid_f = fopen('/var/run/test_gracefull.pid', 'w');
    $pid_f && fwrite($pid_f, $http->master_pid);
});

$http->on('WorkerStart', function ($serv, $worker_id){
    global $app;
    $app = null;
    function_exists('opcache_reset') && opcache_reset();
});

$http->on('request', function ($request, $response){
	sleep(30);
	$response->end('{"code":1000,"err":false,"msg":null,"data":"ok"}');
});

$http->start();
```

2. client.php (本质是模拟线上服务发请求，使用golang http.DefaultClient )

```go
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"sync"
)


func worker(sw *sync.WaitGroup, num int){

	for i:=0; i<num; i++{
		resp, err := http.Post("http://10.20.11.127:9704/article/test", "application/json;", nil)

		if err != nil {
			fmt.Println("ERROR:", err)
		}else{

			ioutil.ReadAll(resp.Body)
			resp.Body.Close()

			fmt.Println("请求成功")
			//time.Sleep(time.Second*1)
		}
	}
	sw.Done()
}

func main()  {
	sw := sync.WaitGroup{}
	sw.Add(1)
	go worker(&sw, 2)
	sw.Wait()

}
```

**Comment by caozhipan** [comment]
@twose 我可能没有表述清楚，问题的本质是swoole针对keepalive 类型的请求，在kill -SIGTERM 信号后是通过发送FIN包来断开当前连接的，而不是给最后一个请求的response header 里设置Connection: close, 这两个包之间存在短暂的时间差，这期间很大几率客户端会使用此链接发送第二个请求，导致第二个请求失败， 
![image](https://user-images.githubusercontent.com/5044014/67010311-fb113580-f11f-11e9-93b8-c30919462397.png)

**Comment by twose** [comment]
由于异步信号可能发生在响应之后(一轮事件循环之后), 所以响应没有机会能马上改变状态

我想这是异步服务器的一个缺陷, 除非采用中断信号设置flag

否则用户的代码总是会先执行

**Comment by caozhipan** [comment]
server接到SIGTERM后会修改running状态
SwooleG.running = 0;
这个状态能否暴露给php， 如果在on request 里获取到这个状态就可以自行修改header了

**Comment by twose** [comment]
@caozhipan 

根据我说的, 你的代码会先于SwooleG.running置0之前执行

**Comment by caozhipan** [comment]
@twose 新版本解决了这个问题吗？

**Comment by twose** [comment]
需要客户端自己处理错误情况重连
