### ISSUE TITLE
Coroutine\Http\Client 发送HEAD请求，响应得头部不对

### ISSUE THREAD

**Issue by HeKunTong** [swoole/swoole-src#2897]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

想要通过Coroutine\Http\Client 模拟head请求获取头部信息，下面是代码：
 获取头部代码
```php
require_once "vendor/autoload.php";
co::create(function() {
    $client = new \Swoole\Coroutine\Http\Client('127.0.0.1', 9501);
    $client->setMethod('HEAD');
    $client->execute('/test');
    var_dump($client->getStatusCode());
    var_dump($client->getHeaders());
    var_dump($client->getBody());
});
```

服务代码：
```php
$http = new \Swoole\Http\Server('127.0.0.1', 9501);

$http->on('request', function($request, $response) {
    $response->end('HEAD');
});

$http->start();
```

2. What did you expect to see?

HTTP/1.1 200 OK
Server: swoole-http-server
Connection: keep-alive
Content-Type: text/html
Date: Fri, 18 Oct 2019 07:54:31 GMT
Content-Length: 4

3. What did you see instead?

int(-3)
array(6) {
  ["server"]=>
  string(18) "swoole-http-server"
  ["connection"]=>
  string(10) "keep-alive"
  ["content-type"]=>
  string(9) "text/html"
  ["date"]=>
  string(29) "Fri, 18 Oct 2019 07:55:40 GMT"
  ["content-length"]=>
  string(2) "24"
  ["content-encoding"]=>
  string(4) "gzip"
}
string(0) ""

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.8
Built => Oct 16 2019 14:25:35
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

kernel ：CentOS Linux release 7.5.1804 (Core)
php：7.2.12 
gcc： 4.8.5

**Comment by twose** [comment]
@HeKunTong 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by HeKunTong** [comment]
执行USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php curl.php，出现以下结果：
int(-3)
array(6) {
  ["server"]=>
  string(18) "swoole-http-server"
  ["connection"]=>
  string(10) "keep-alive"
  ["content-type"]=>
  string(9) "text/html"
  ["date"]=>
  string(29) "Fri, 18 Oct 2019 08:10:18 GMT"
  ["content-length"]=>
  string(2) "24"
  ["content-encoding"]=>
  string(4) "gzip"
}
string(0) ""

**Comment by HeKunTong** [comment]
==61035== Memcheck, a memory error detector
==61035== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==61035== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==61035== Command: php curl.php
==61035== Parent PID: 60413
==61035== 
==61035== Warning: client switching stacks?  SP change: 0x1ffeffc5d0 --> 0x13474748
==61035==          to suppress, use: --max-stackframe=137098722952 or greater
==61035== Warning: client switching stacks?  SP change: 0x13473a20 --> 0x1ffeffc5d0
==61035==          to suppress, use: --max-stackframe=137098726320 or greater
==61035== Warning: client switching stacks?  SP change: 0x1ffeffe4d0 --> 0x13473a20
==61035==          to suppress, use: --max-stackframe=137098734256 or greater
==61035==          further instances of this message will not be shown.
==61035== 
==61035== HEAP SUMMARY:
==61035==     in use at exit: 690,406 bytes in 137 blocks
==61035==   total heap usage: 43,229 allocs, 43,092 frees, 10,062,270 bytes allocated
==61035== 
==61035== LEAK SUMMARY:
==61035==    definitely lost: 525,064 bytes in 12 blocks
==61035==    indirectly lost: 65,536 bytes in 1 blocks
==61035==      possibly lost: 0 bytes in 0 blocks
==61035==    still reachable: 99,806 bytes in 124 blocks
==61035==         suppressed: 0 bytes in 0 blocks
==61035== Rerun with --leak-check=full to see details of leaked memory
==61035== 
==61035== For counts of detected and suppressed errors, rerun with: -v
==61035== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by twose** [comment]
结果是符合预期的

由于客户端请求自动携带了gzip支持选项, 服务器端返回了gzip压缩后的内容, 导致长度为24

客户端的错误信息为 Protocol error, 说明服务端返回的包协议有误(HEAD请求不应该响应内容), 导致body被客户端丢弃, 所以body是空的

**Comment by twose** [comment]
感谢你的反馈, 如有疑问可以继续贴出

**Comment by huanghantao** [comment]
@HeKunTong 这里有一份代码你或许可以试一下：
`server.php`：
```php
<?php

$http = new \Swoole\Http\Server('127.0.0.1', 9501);

$http->on('request', function($request, $response) {
    $data = json_encode([
        'code' => 'ok',
        'error' => false,
        'payload' => 'Hello World'
    ]);
    $response->header('Content-Type', 'application/json');
    if ($request->server['request_method'] == 'HEAD') {
        $response->header('Content-Length', strlen($data));
        $response->end();
        return;
    }
    $response->end($data);
});

$http->start();
```

`client`：
```php
<?php

co::create(function() {
    $client = new \Swoole\Coroutine\Http\Client('127.0.0.1', 9501);
    $client->setMethod('HEAD');
    $client->execute('/test');
    var_dump($client->getStatusCode());
    var_dump($client->getHeaders());
    var_dump($client->getBody());
});
```

**Comment by twose** [comment]
如楼上代码所示, 正确书写PHP处理代码即可解决

你的预期是错的, HEAD请求不应该预期到返回Content-Length不为0的响应

**Comment by HeKunTong** [comment]
嗯嗯，demo例子是可以解决这个问题，我看下怎么套用到我这边过来。

**Comment by HeKunTong** [comment]
> 如楼上代码所示, 正确书写PHP处理代码即可解决
> 
> 你的预期是错的, HEAD请求不应该预期到返回Content-Length不为0的响应

按照上面的代码，执行以下curl命令：、
1.执行 curl -I http://127.0.0.1:9501/test
输出结果：
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 51
Server: swoole-http-server
Connection: keep-alive
Date: Mon, 21 Oct 2019 01:27:02 GMT
2.执行curl -X HEAD http://127.0.0.1:9501/test
输出结果：无
两个都是获取头部命令，为何有这种区别。
