### ISSUE TITLE
协程客户端并发请求单 worker 协程服务端 swWorker_reactor_is_empty (ERRNO 9012)

### ISSUE THREAD

**Issue by codezm** [swoole/swoole-src#2901]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
- swoole http server config:
```php
'worker_num' => 1,
'task_worker_num' => 0,
'daemonize' => false,
'max_request' => 3,
'dispatch_mode' => 1,
```
`onRequest` code
```php
\Swoole\Coroutine\System::sleep(3);
$response->end('ok!');
```
- swoole coroutine http client
```php
use \Swoole\Coroutine\Scheduler;
use \Swoole\Coroutine\Http\Client;
$config = [
    'coroutine_num' => 3,
    'url' => 'http://www.test.com/test',
];

$scheduler = new Scheduler();
$scheduler->parallel($config['coroutine_num'], function($config) {
    $parseUrls = parse_url($config['url']);
    $client = new Client($parseUrls['host'], 80);

    $client->get((isset($parseUrls['path']) ? $parseUrls['path'] : '') . '?' . (isset($parseUrls['query']) ? $parseUrls['query'] : http_build_query([])));
    echo $client->body;
}, $config);
$scheduler->start();
```
2. What did you expect to see?

协程客户端并发请求服务端三次，服务端受 `max_request` 配置项会自动重启 `worker`, 当 `worker` 重启时服务端不等待响应吗？

3. What did you see instead?

- 服务端第一次启动 + 客户端第一次请求
有的时候启动服务端后，客户端请求就失败了，客户端直接响应504(三次均 504)。
服务端收到三次请求但有警告信息: `WARNING	swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate`
- 服务端第一次启动 + 客户端第 `2 +` 次请求
```bash
WARNING	swWorker_reactor_is_empty (ERRNO 9012): worker exit timeout, forced to terminate
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

- swoole: 4.4.8

5. What is your machine environment used (including version of kernel & php & gcc) ?
- gcc: 8.3.0
- php: 7.1.20
- kernel: Alpine Linux 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux

**Comment by twose** [comment]
https://wiki.swoole.com/wiki/page/1082.html

**Comment by codezm** [comment]
这个我有看过，不知是不是我概念理解的不对，麻烦给纠正下

- reactor 线程接收到请求后，若 worker 进程正在重启均响应 504吗？
- `max_wait_time` 参数解决的是 阻塞 worker 无法强制杀死的问题吧？

**Comment by twose** [comment]
不是的
max_wait_time是指不论如何worker超过3s没有退出, 都会强制杀死 (也包括你有未完成的异步任务等)

**Comment by codezm** [comment]
首先感谢答复，那我碰到的这种情况属于正常逻辑吗？总感觉怪怪的...
