### ISSUE TITLE
Swoole\Coroutine\Http\Client 头部cookie出现问题

### ISSUE THREAD

**Issue by HeKunTong** [swoole/swoole-src#2902]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
服务端：
$http = new \Swoole\Http\Server('127.0.0.1', 9502);

$http->on('request', function($request, $response) {
    $data = json_encode([
        'code' => 'ok',
        'error' => false,
        'payload' => 'Hello World'
    ]);
    $response->header('Content-Type', 'application/json');
    if ($request->server['request_method'] == 'HEAD') {
        $response->header('Content-Length', strlen($data));
        $response->cookie('name', 'blank', time() + 3600, '/');
        $response->cookie('age', '12', time() + 3600, '/');
        $response->end();
        return;
    }
    $response->end($data);
});

客户端：
co::create(function() {
    $client = new \Swoole\Coroutine\Http\Client('127.0.0.1', 9502);
    $client->setMethod('HEAD');
    $client->execute('/test');
    var_dump($client->getStatusCode());
    var_dump($client->getHeaders());
    var_dump($client->getBody());
});
2. What did you expect to see?
执行curl -I http://127.0.0.1:9502/test
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 51
Server: swoole-http-server
Connection: keep-alive
Date: Mon, 21 Oct 2019 02:42:34 GMT
Set-Cookie: name=blank; expires=Mon, 21-Oct-2019 03:42:34 GMT; path=/
Set-Cookie: age=12; expires=Mon, 21-Oct-2019 03:42:34 GMT; path=/

3. What did you see instead?
执行client.php
int(200)
array(6) {
  ["content-type"]=>
  string(16) "application/json"
  ["content-length"]=>
  string(2) "51"
  ["server"]=>
  string(18) "swoole-http-server"
  ["connection"]=>
  string(10) "keep-alive"
  ["date"]=>
  string(29) "Mon, 21 Oct 2019 02:44:10 GMT"
  ["set-cookie"]=>
  string(53) "age=12; expires=Mon, 21-Oct-2019 03:44:10 GMT; path=/"
}
string(0) ""

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team team@swoole.com
Version => 4.4.8
Built => Oct 16 2019 14:25:35
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips 26 Jan 2017
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

kernel ：CentOS Linux release 7.5.1804 (Core)
php：7.2.12
gcc： 4.8.5

**Comment by twose** [comment]
@HeKunTong 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by HeKunTong** [comment]
valgrind.log:
==68194== Memcheck, a memory error detector
==68194== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==68194== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==68194== Command: php client.php
==68194== Parent PID: 67868
==68194== 
==68194== Warning: client switching stacks?  SP change: 0x1ffeffc5d0 --> 0x1333a148
==68194==          to suppress, use: --max-stackframe=137100010632 or greater
==68194== Warning: client switching stacks?  SP change: 0x13339420 --> 0x1ffeffc5d0
==68194==          to suppress, use: --max-stackframe=137100014000 or greater
==68194== Warning: client switching stacks?  SP change: 0x1ffeffe4d0 --> 0x13339420
==68194==          to suppress, use: --max-stackframe=137100021936 or greater
==68194==          further instances of this message will not be shown.
==68194== 
==68194== HEAP SUMMARY:
==68194==     in use at exit: 690,406 bytes in 137 blocks
==68194==   total heap usage: 38,325 allocs, 38,188 frees, 9,102,174 bytes allocated
==68194== 
==68194== LEAK SUMMARY:
==68194==    definitely lost: 525,064 bytes in 12 blocks
==68194==    indirectly lost: 65,536 bytes in 1 blocks
==68194==      possibly lost: 0 bytes in 0 blocks
==68194==    still reachable: 99,806 bytes in 124 blocks
==68194==         suppressed: 0 bytes in 0 blocks
==68194== Rerun with --leak-check=full to see details of leaked memory
==68194== 
==68194== For counts of detected and suppressed errors, rerun with: -v
==68194== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by huanghantao** [comment]
@HeKunTong 应该是`getHeaders`这个函数的问题，你可以先用`getCookies`

**Comment by HeKunTong** [comment]
> @HeKunTong 应该是`getHeaders`这个函数的问题，你可以先用`getCookies`

这个更不行。
输出结果：
Array
(
    [name] => blank
    [age] => 12
)

连个过期时间，作用域之类的信息都没有。

**Comment by huanghantao** [comment]
@HeKunTong 我刚才看了下代码，是解析header的时候出问题了，后面解析的会覆盖前面的。

**Comment by HeKunTong** [comment]
> @HeKunTong 我刚才看了下代码，是解析header的时候出问题了，后面解析的会覆盖前面的。

嗯嗯，这个bug啥时能够解决？

**Comment by twose** [comment]
```php
var_dump($client->set_cookie_headers);
```
