### ISSUE TITLE
Http\Response->status 请求http status code 放开允许用户自己设置

### ISSUE THREAD

**Issue by erDong01** [swoole/swoole-src#2903]
以前业务用laravel框架写的有 自定义http status code状态 如480其他等  现在想swoole提升性能
但状态码无法自定义 是一个很大限制 请求放开
地址：https://wiki.swoole.com/wiki/page/338.html

**Comment by huanghantao** [comment]
@erDong01 你这个状态码`480`不能从返回的数据里面得到吗？我理解的是你们自己业务定义的一个状态码，而不是`http`协议里面的那个。

**Comment by erDong01** [comment]
@huanghantao 是的 是我们自己根据自己的业务定义的一个状态码 不在http协议里。我们前期开发的业务已经跟前端约定了 返回放在了 http status code   没放在body里面    Swoole\Http\Response->status(int $http_status_code);限制了状态码   这里个人浏览器都支持了觉得swoole也不要限制了吧 比较不同用户有不用开发需求

**Comment by twose** [comment]
```php
use Swoole\Http\Request;
use Swoole\Http\Response;

$http = new \Swoole\Http\Server('127.0.0.1', 9501);
$http->on('request', function (Request $request, Response $response) {
    $response->status(999, 'Swoole');
    $response->end();
});
$http->start();
```

![image](https://user-images.githubusercontent.com/25978241/67266645-4a21e680-f4e3-11e9-82d0-8b2a737d666a.png)

文档已更新
