### ISSUE TITLE
协程Http客户端请求https时代理无效

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/swoole-src#2904]
```php
<?php
go(function(){
    $cli = new Swoole\Coroutine\Http\Client('ip.cn', 443, true);
    $cli->set([
        'http_proxy_host' => '127.0.0.1',
        'http_proxy_port' => '8580',
    ]);
    $cli->setHeaders([
        'Host'          =>  'ip.cn',
        'User-Agent'    =>  'GuzzleHttp/6.3.3 curl/7.47.0 PHP/7.3.6-1+ubuntu16.04.1+deb.sury.org+1',
    ]);
    $cli->get('/');
    var_dump($cli->body, $cli->errCode);
    $cli->close();
});
```

**Comment by twose** [comment]
目前跟踪到的情况 

Swoole使用代理时的行为和CURL没有显著区别, 但CURL能够请求成功 (查询IP的网站对CURL的请求有特殊处理, 只返回ip而不返回HTML页面)

访问其他查询HTTP的网站没有问题如 `https://api.ipify.org`

开启http proxy 和 socks5 proxy都会被 `ip.cn` 返回 403 响应, 看起来更像是服务器由于检测出了非CURL的特征而拒绝了这个请求, 而不是proxy失败

原因尚不明确

**Comment by Yurunsoft** [comment]
微信接口也有问题，这是用户的反馈：https://github.com/Yurunsoft/Guzzle-Swoole/issues/8

**Comment by matyhtf** [comment]
Server 端能返回 403 HTML 页面说明通信是正常的。说明不是链路层问题。是否需要添加特殊的 Http Header ？

**Comment by matyhtf** [comment]
`ssl_host_name`的问题，请设置一下`ssl_host_name`

**Comment by twose** [comment]
proxy由于特殊原因底层没有自动设置, 现已修正
