### ISSUE TITLE
when open_http2_protocol=TRUE enable_static_handler seems stops working

### ISSUE THREAD

**Issue by kenashkov** [swoole/swoole-src#2907]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

We enabled both open_http2_protocol = TRUE (along with SSL) and enable_static_handler = TRUE and we set document_root.

```php
<?php
    $http = new Swoole\Http\Server('0.0.0.0', 8081, SWOOLE_PROCESS, SWOOLE_SOCK_TCP | SWOOLE_SSL);
    $options = [
        'enable_static_handler'         => TRUE,
        'document_root'                 => dirname(__FILE__),
        'open_http2_protocol'           => TRUE,
        'ssl_cert_file'                 => './localhost.crt',
        'ssl_key_file'                  => './localhost.key',
    ];
    $http->set($options);
    $http->on('request', function (Swoole\Http\Request $request, Swoole\Http\Response $response) {
        $response->end('this is swoole worker');
    });
    $http->start();
```

Then load "https://localhost:8081/file.txt" (the file exists)

2. What did you expect to see?

output: "static content" (this is the content of "file.txt" - to be served by the static handler)

3. What did you see instead?

output: "this is swoole worker"
The request gets served by Swoole Worker instead of the static handler.

If just open_http2_protocol is set to FALSE it works as expected.

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.9-alpha
Built => Oct 22 2019 09:51:51
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.0l  10 Sep 2019
http2 => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

(it was built from Master)

PHP 7.4.0RC4

5. What is your machine environment used (including version of kernel & php & gcc) ?

Linux LOCAL_DEV_SWOOLE 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 GNU/Linux

PHP 7.4.0RC4 (cli) (built: Oct 18 2019 11:40:42) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0RC4, Copyright (c), by Zend Technologies

gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

**Comment by twose** [comment]
static_handler only support HTTP1.1 now

**Comment by matyhtf** [comment]
fixed

**Comment by kenashkov** [comment]
Thank you for fixing this!
Now the server can start with both HTTP2 and static handler but in this mode it doesnt return the correct header for content type. Accessing /someimage.png returns content-type: "text/html" instead of the correct "image/png"

**Comment by matyhtf** [comment]
Missing content type, resolved
