### ISSUE TITLE
WARNING swManager_check_exit_status: worker#3[pid=4874] abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by cxjhk** [swoole/swoole-src#2908]
[2019-10-24 15:01:31 $4858.0]   WARNING swManager_check_exit_status: worker#3[pid=4874] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.4.8, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

**Comment by twose** [comment]
@cxjhk 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理
