### ISSUE TITLE
swoole的process模块未来能否提供支持sigaction()注册信号函数和sigqueue()函数？

### ISSUE THREAD

**Issue by bingcool** [swoole/swoole-src#2913]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

主要是在某些场景中发信号需要附带额外的信息，而signal()无法支持

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
Swoole使用的是异步信号, 不是中断信号, 信号回调在事件循环后触发, 不如直接使用进程间通信来触发回调

**Comment by matyhtf** [comment]
暂时不会提供。目前 Swoole 扩展本身只会在 协程的方向上发展。不再考虑支持 同步模型。另外，不建议使用信号传递信息，改为使用 Unix socket
