### ISSUE TITLE
CentOS 下 swoole_http_server 内存不释放

### ISSUE THREAD

**Issue by Zz1994zZ** [swoole/swoole-src#2920]
代码如下：
```
<?php
$http = new swoole_http_server("0.0.0.0", 9501);
$http->set(array(
    'worker_num' => 8,    //worker process num
));
$http->on("request", function ($request, $response) {
   $response->end('test');
});
$http->start();
```
机器环境为:  
CentOS Linux release 7.2 
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
swoole 依次尝试了三个版本:
 PHP 7.0.7 (cli)+swoole 2.0.10
 swoole 4.4.3  二进制版本
 swoole 4.4.8  二进制版本 
均发现有处理请求后内存不释放的现象：
初始情况：
![image](https://user-images.githubusercontent.com/14341553/67683401-4fdc6800-f9cc-11e9-89ee-8f645c92d1a4.png)
ab -c 1000 -n 50000 'http://127.0.0.1:9501/' 之后：
![image](https://user-images.githubusercontent.com/14341553/67683454-65519200-f9cc-11e9-8356-a47df9a8a4e1.png)

再次 ab -c 1000 -n 50000 'http://127.0.0.1:9501/' 之后：
![image](https://user-images.githubusercontent.com/14341553/67683490-71d5ea80-f9cc-11e9-8f8d-4a5fef69d3ed.png)

**Comment by twose** [comment]
能截图完整吗?

我们有更复杂的例子去测试内存泄漏

不会出现这么简单的泄露

一般来说程序内存占用是会随着请求增多而上涨的

但都会有一个峰值, 到达峰值后不再上升

你的测试次数不够多, 建议不断压测跑几分钟以上再看内存变化

**Comment by matyhtf** [comment]
不要和冷启动进程对比内存，你可以以第一次压测后的内存占用为基准，连续压测，观察内存是否上涨。

**Comment by Zz1994zZ** [comment]
学习到了，这里没有内存泄漏问题，是我的测试方式不对。持续压测到一定程度后内存可以维持稳定~
