### ISSUE TITLE
Swoole\Client::recv(): recv() failed. Error: Resource temporarily unavailable

### ISSUE THREAD

**Issue by lovecucu** [swoole/swoole-src#2924]
swoole 版本 ： 4.2+
php版本：php7.0
现象：多进程版tcp server，有1/100的概率会报上述错误
尝试修复方法：调整worker_num（24 -> 48），并没有用，错误数未见减少

问题点：如何修复这个问题，可以从哪方面入手？

**Comment by twose** [comment]
https://wiki.swoole.com/wiki/page/234.html

按照模板提问
