### ISSUE TITLE
增强的 open_length_check 功能

### ISSUE THREAD

**Issue by andot** [swoole/swoole-src#293]
我打算为hprose 的 tcp 版本增加一个全双工的支持，为了能够跟半双工版本一起工作，我是这样修改的通讯协议：https://github.com/andot/hprose/wiki/Hprose-Specification#Full_Duplex_Socket_Binding

但现在问题来了，这样做之后，其他语言下没什么问题（因为其他语言没有 swoole 这么高级的功能，本来就需要自己手工搞），但是在 swoole 下就不能使用[“固定包头+包体协议自动分包”](http://wiki.swoole.com/wiki/page/224.html)了，所以我想是否可以把自动分包功能改的更高级一点，比如增加一个 `package_length_callback` 的选项，像这样工作：

```php
$serv->set(array(
    'open_length_check' => true,
    'package_length_type' => 'N',
    'package_length_offset' => 0,
    'package_length_callback' => function ($length) {
        if ($length & 0x80000000 != 0) {
            $length = $length & 0x7FFFFFFF;
            return array(
                'package_body_length' => $length,
                'package_body_offset' => 8
            );
        }
        return array(
            'package_body_length' => $length,
            'package_body_offset' => 4
        );
    },
    'package_max_length' => 800000)
);
```
其中 `package_length_callback` 可以让用户设置一个用来根据读出的`包体长度`来改写`(包体偏移，包体长度)`的回调。

我看了一下 swoole 代码的这部分，好像不是很难改，而且这个修改对原有功能不会有任何影响，可以在既不影响性能，又不影响兼容性的情况下，有效的增强 open_length_check 的功能。

如果觉得增加这个功能可以的话，那我可以来实现这个功能。

**Comment by yiliaofan** [comment]
能这样的话，这个功能就超赞了～ 哈哈  帮顶～

**Comment by shenzhe** [comment]
不太合适，swoole底层和php代码不应该有耦合。

**Comment by andot** [comment]
这个跟 swoole 的其它事件一样，是可以跟 php 代码解耦合的。

**Comment by matyhtf** [comment]
这个特性只能用于BASE模式，因为BASE模式是单线程的，默认的SWOOLE_PROCESS模式，主进程是多进程的，存在并行问题，无法直接提供PHP的回调函数。

**Comment by andot** [comment]
哦，明白。如果只能用于 Base 模式的话，那加上这个特征就不是很实用了。我还是用 php 来分包吧。

**Comment by matyhtf** [comment]
最新版本的swoole提供了一个实现方式，可以写一个C/C++的函数，去解析原始数据中的长度。
https://github.com/swoole/swoole-src/blob/master/examples/c_module/test.c
