### ISSUE TITLE
Accept PSR3/LoggerInterface in \Swoole\Http\Server configuration

### ISSUE THREAD

**Issue by vasily-kartashov** [swoole/swoole-src#2932]
Instead of having separate log_level and log_file settings, would it be possible to accept a PSR3/LoggerInterface instead?

**Comment by twose** [comment]
not implemented yet
but this log will only output the error of kernel (not PHP)
you can handle PHP log by yourself

**Comment by vasily-kartashov** [comment]
> but this log will only output the error of kernel (not PHP)

That's still something I'd like to see in the log. At the moment is rather difficult to see the what swoole does behind the scenes and how it correlated with what the application is doing.

**Comment by twose** [comment]
The contents of the log describe things which the PHP layer can't control
If possible, the kernel will try to output as php error instead of log
