### ISSUE TITLE
swoole 协程http cookie 模拟登陆

### ISSUE THREAD

**Issue by lizhanghu** [swoole/swoole-src#2934]
http cookie这块官网上一笔带过，小弟实在是不知道怎么使用
求一个带入cookie的例子（下面是我写的，求大神指点）

    $cliLogin = new \Swoole\Coroutine\Http\Client('XXX.com');
    $cliLogin->setHeaders([
        "Accept"=>"application/json"
    ]);
    $cliLogin->set([
        'timeout' => 60,
    ]);
    $data = '{"username":"111inc.com","password":"111"}';
    $cliLogin->post('/login',$data);
    $cookie = $cliLogin->getCookies();
    $url = "/index";
    $cli = new \Swoole\Coroutine\Http\Client('XXX.com',80);
    $cli->setCookies($cookie);
    $cli->set([
        'timeout' => 300,
        "Accept"=>"application/json"
    ]);
    $cli->get($url);
    echo $cli->body;

**Comment by twose** [comment]
不会用就去找现成的爬虫库 各大框架都有 或者 https://github.com/swlib/saber 文档里有提到

这和你会不会用没啥关系, 设置cookie就是这么一回事, 没有啥可以说道的, cookie只不过是header中的一种而已, 你自己构造也可以

我推测下你可能不是不会用, 是搞不清cookie, session 和 爬虫

**Comment by lizhanghu** [comment]
我用curl模拟了登录，保存的cookie文件内容中有一个字段是
SYSTEM_USER eyJTWVNURU1fVVNFUl9JRCI6ImhlemlsaWFuZ0B5dWFueGluLWluYy5jb20iLCJTWVNURU1fVVNFUiI6eyJzaXRlaWQiOiIzODIyNTk4YTkwNmRlNmUxMzgxYzU1NjZjNzQzODc1MSIsImlzX3Byb2hpYml0IjowLCJwcm9oaWJpdF90aW1lIjoiIiwicm9sZWlkIjoyLCJ1c2VyX2lkIjoiaGV6aWxpYW5nQHl1YW54aW4taW5jLmNvbSIsInVzZXJfbmFtZSI6IuWmmeaJi+WMu+eUnyIsInNpdGUiOiJtaWFvc2hvdS5uZXQiLCJpbmR1c3RyeSI6Im1pbmd5aSIsInNob3dfaW5jb21lIjp0cnVlLCJjb250cmFjdFN0YXR1cyI6IjEifSwiX2V4cGlyZSI6MTU3MzQ0NDEyMzY5MSwiX21heEFnZSI6NjA0ODAwMDAwfQ==

我用ew \Swoole\Coroutine\Http\Client同样getCookies()返回的这个字段内容是
eyJTWVNURU1fVVNFUl9JRCI6ImhlemlsaWFuZ0B5dWFueGluLWluYy5jb20iLCJTWVNURU1fVVNFUiI6eyJzaXRlaWQiOiIzODIyNTk4YTkwNmRlNmUxMzgxYzU1NjZjNzQzODc1MSIsImlzX3Byb2hpYml0IjowLCJwcm9oaWJpdF90aW1lIjoiIiwicm9sZWlkIjoyLCJ1c2VyX2lkIjoiaGV6aWxpYW5nQHl1YW54aW4taW5jLmNvbSIsInVzZXJfbmFtZSI6IuWmmeaJi WMu eUnyIsInNpdGUiOiJtaWFvc2hvdS5uZXQiLCJpbmR1c3RyeSI6Im1pbmd5aSIsInNob3dfaW5jb21lIjp0cnVlLCJjb250cmFjdFN0YXR1cyI6IjEifSwiX2V4cGlyZSI6MTU3MzQ0NTY0MzI4NiwiX21heEFnZSI6NjA0ODAwMDAwfQ==

两者的对比差异就是第一个是+WMu+ ，下面的是空格加 WMu 。

然后我用    
$cli->setHeaders(["Cookie"=>"SYSTEM_USER=..."]);方法分别用两个cookie验证，curl的cookie是可以验证通过的。协程客户端getCookies得到的不能通过。

然后我继续用$cli->setCookies($cookie);对比两者发现都不能验证通过。

我怀疑是协程客户端生成的cookie有些字符进行了替换 我的swoole版本是 4.4.7

**Comment by twose** [comment]
按照HTTP的规定cookie要进行编码
此处是客户端 所以`+`被urldecode解析为空格
你需要通过 `$client->set_cookie_headers` (https://wiki.swoole.com/wiki/page/1516.html) 获取原始的Cookie信息

**Comment by lizhanghu** [comment]
可以了 非常感谢！
我建议$client->getCookies(),$client->setCookies($cookie); 在文档上做个编码说明~

**Comment by twose** [comment]
已补充文档
