### ISSUE TITLE
Swoole\Table是否可以提供一个获取已经设置的keys函数

### ISSUE THREAD

**Issue by bingcool** [swoole/swoole-src#2939]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

主要是在做一些监控时，需要能够获取已经设置的key有哪些，从而可以获取对应的值。

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
这个问题 我更推荐用redis

**Comment by bingcool** [comment]
我的想法是提供一个swoole\ table:: keys()，获取已设置的key。当然在业务层也是能封装一层实现，如果原生底层能提供最好。



---原始邮件---
发件人: "twosee"<notifications@github.com&gt;
发送时间: 2019年11月5日(星期二) 晚上10:30
收件人: "swoole/swoole-src"<swoole-src@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"黄增冰"<2437667702@qq.com&gt;;
主题: Re: [swoole/swoole-src] Swoole\Table是否可以提供一个获取已经设置的keys函数 (#2939)



这个问题 我更推荐用redis

**Comment by twose** [comment]
我的意见还是redis更好

**Comment by matyhtf** [comment]
你需要遍历。

**Comment by bingcool** [comment]
OK，可以实现了



---原始邮件---
发件人: "韩天峰-Rango"<notifications@github.com&gt;
发送时间: 2019年11月7日(星期四) 上午10:15
收件人: "swoole/swoole-src"<swoole-src@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"黄增冰"<2437667702@qq.com&gt;;
主题: Re: [swoole/swoole-src] Swoole\Table是否可以提供一个获取已经设置的keys函数 (#2939)



你需要遍历。
