### ISSUE TITLE
MySQL numerical columns returning as strings

### ISSUE THREAD

**Issue by osrec** [swoole/swoole-src#2941]
When using the MySQL coroutine client, if I query a table with numerical columns, I get strings in the resulting array. 

Is there a way to get metadata for the columns so that we can parse the numerical columns as actual numbers?

**Comment by twose** [comment]
MySQL server always return data as strings if you use `query`
But you can get numerical columns by `$client->connect([..., 'strict_type' => true])`
Or you can use `prepare` + `execute` (it's better)

**Comment by osrec** [comment]
Thanks @twose ! Is the prepare method now part of the swoole mysql class?

**Comment by deminy** [comment]
@osrec method `prepare` is defined in the [\Swoole\Coroutine\MySQL](https://github.com/swoole/ide-helper/blob/4.4.12/output/swoole/namespace/Coroutine/MySQL.php#L86) class.

**Comment by osrec** [comment]
Great, thank you
