### ISSUE TITLE
Request named parameters for prepared statements in Co\Mysql

### ISSUE THREAD

**Issue by Kapsonfire** [swoole/swoole-src#2948]
**This is the current way to use:**

`$stmt = $mysql->prepare('INSERT INTO users SET name = ?, password = ?');`
`$stmt->execute([
                $name,
                hashPassword($password)
            ]);`

**This is what I want**
`$stmt = $mysql->prepare('INSERT INTO users SET name = :name, password = :pass');`
`$stmt->execute([
               'name' => $name,
                'pass' => hashPassword($password)
            ]);`

This may be in this example not be very important, but it gets more important if you use a value multiple times in your statement like:
`SELECT * FROM users WHERE name = :name OR oldname = :name`

Even though, named statements make long queries easier to understand.

**Comment by matyhtf** [comment]
This is the pdo client simulation implementation, mysql does not support. 

You can use the PDO client with runtime hook.
