### ISSUE TITLE
v4.4.3 Swoole\Coroutine\Http\Client 使用set方法配置参数后请求多次内存一直上涨

### ISSUE THREAD

**Issue by Zz1994zZ** [swoole/swoole-src#2949]
机器环境为:
CentOS Linux release 7.2
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
PHP 7.0.7 (cli)+swoole 2.0.10
swoole 4.4.3 二进制版本

代码如下
```
<?php
$http = new swoole_http_server("0.0.0.0", 9501);
$http->set(array(
    'worker_num' => 8,    //worker process num
));
$http->on("request", function ($request, $response) {
         $cli = new Swoole\Coroutine\Http\Client("api.twitter.com", 443 , true);
         $cli->setHeaders(array(
                        "Authorization" => 'test'
         ));
         $cli->set(['timeout'=> 1]); //不加此行内存稳定
         $cli->post('/oauth/request_token',array());
         $cli->close();
         $response->end(json_encode($cli->body));
});
$http->start();
```
压测配置 ab -c 10000 -n 100000
首次压测后内存情况：
![image](https://user-images.githubusercontent.com/14341553/68542643-d1c78a80-03e9-11ea-8350-833f70ee4dc8.png)
第二次压测后：
![image](https://user-images.githubusercontent.com/14341553/68542654-ed329580-03e9-11ea-8553-4e2a31c6ba9f.png)
第三次压测后：
![image](https://user-images.githubusercontent.com/14341553/68542672-1a7f4380-03ea-11ea-8393-1ac9470d198b.png)
第四次压测后：
![image](https://user-images.githubusercontent.com/14341553/68542688-48648800-03ea-11ea-939d-f26d55764c53.png)

删除 $cli->set(['timeout'=> 1]);  后 
第一次压测后：
![image](https://user-images.githubusercontent.com/14341553/68542711-819cf800-03ea-11ea-9e2b-f9de7d599249.png)
第二次压测后：
![image](https://user-images.githubusercontent.com/14341553/68542744-b6a94a80-03ea-11ea-92e2-b7cdf00fe12c.png)
第三次压测后：
![image](https://user-images.githubusercontent.com/14341553/68542753-d6d90980-03ea-11ea-9425-31927e484248.png)
第四次压测后：
![image](https://user-images.githubusercontent.com/14341553/68542781-02f48a80-03eb-11ea-97ac-2ee1e59805e1.png)

这种情况是我的使用set的方式有问题吗？该如何正确配置client的参数呢？求解答～

**Comment by twose** [comment]
没有复现，请先升级到最新版（目前为v4.4.12）重新测试
