### ISSUE TITLE
connection_aborted(), connection_status(), ignore_user_abort() 等函数支持有问题

### ISSUE THREAD

**Issue by breath-co2** [swoole/swoole-src#295]
使用 swoole_http_server 异步启动后，程序中执行 connection_aborted() 不管是否客户端真的断开了都返回的是0
connection_status() 方法也是的。

ignore_user_abort() 的问题是：apache/nginx/php-fpm等启动php默认都是如果浏览器断开都会强制中断php执行，只有php中执行ignore_user_abort()后才会在断开后继续执行。而 swoole 里默认是不管浏览器断开与否的，都会继续执行，这样似乎就没有 ignore_user_abort 什么事情了。。。
可是这样的设定似乎会给一些phper困扰，有可能也会导致迁移环境后出现异常问题。

**Comment by matyhtf** [comment]
不支持 这些函数。

**Comment by flexchar** [comment]
Any alternative solutions?

I'm implementing SSE (Server Sent Events) stream for updates and there's a great chance of client leaving too many open connections since updates are streamed in long lived loop.
