### ISSUE TITLE
当 Process recv 的时候，程序抛错导致进程退出，重新拉起进程时，Socket未连接

### ISSUE THREAD

**Issue by limingxinleo** [swoole/swoole-src#2953]
我也不太清楚这里算不算是 bug，我项目里已经改成让 Process 正常退出了。

```php
<?php

use Swoole\Process;

\Swoole\Runtime::enableCoroutine();

$server = new swoole_http_server('0.0.0.0', 9501);
$process = new Process(function (Process $process) {
    \Swoole\Coroutine::create(function () use ($process) {
        $socket = $process->exportSocket();
        var_dump(microtime(true));
        $recv = $socket->recv(65535, 5);
        var_dump($recv, microtime(true));
    });
    \Swoole\Coroutine::sleep(2);
    throw new \Exception('xxx');
}, false, SOCK_DGRAM, true);

$server->addProcess($process);
$server->on('request', function ($request, $response) use ($process) {
    $socket = $process->exportSocket();
    $socket->send("asdf");
    $response->end("adsf");
});

$server->start();
```

执行结果，第一次还是正常的，时间相差 2秒，但后面的就都会直接 返回空字符串，应该就是说 Socket 是无法连接的状态。

```
$ php worker.php
float(1573619506.2459)
PHP Fatal error:  Uncaught Exception: xxx in /Users/limx/Applications/GitHub/limingxinleo/hyperf-demo/worker.php:16
Stack trace:
#0 {main}
  thrown in /Users/limx/Applications/GitHub/limingxinleo/hyperf-demo/worker.php on line 16

Fatal error: Uncaught Exception: xxx in /Users/limx/Applications/GitHub/limingxinleo/hyperf-demo/worker.php:16
Stack trace:
#0 {main}
  thrown in /Users/limx/Applications/GitHub/limingxinleo/hyperf-demo/worker.php on line 16
[2019-11-13 12:31:48 $44297.0]  WARNING swManager_check_exit_status: worker#8[pid=44306] abnormal exit, status=255, signal=0
float(1573619508.2687)
string(0) ""
float(1573619508.2688)
PHP Fatal error:  Uncaught Exception: xxx in /Users/limx/Applications/GitHub/limingxinleo/hyperf-demo/worker.php:16
Stack trace:

```

**Comment by limingxinleo** [comment]
@twose 昨天说的问题，我这里有复现的代码了，帮我看下吧

**Comment by xiangdong2** [comment]
管道类型是SOCK_STREAM时，多个进程同时写入一个进程的管道，可能存在风险，可能会产生数据错乱。存在交叉写入时可以使用SOCK_DGRAM格式的管道，或者进行加锁??
二）这个场景是用来干嘛的？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"李铭昕"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月13日(星期三) 中午12:35
收件人:&nbsp;"swoole/swoole-src"<swoole-src@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[swoole/swoole-src] 当 Process recv 的时候，程序抛错导致进程退出，重新拉起进程时，Socket未连接 (#2953)




我也不太清楚这里算不算是 bug，我项目里已经改成让 Process 正常退出了。
 <?php  use Swoole\Process;  \Swoole\Runtime::enableCoroutine();  $server = new swoole_http_server('0.0.0.0', 9501); $process = new Process(function (Process $process) {     \Swoole\Coroutine::create(function () use ($process) {         $socket = $process-&gt;exportSocket();         var_dump(microtime(true));         $recv = $socket-&gt;recv(65535, 5);         var_dump($recv, microtime(true));     });     \Swoole\Coroutine::sleep(2);     throw new \Exception('xxx'); }, false, SOCK_DGRAM, true);  $server-&gt;addProcess($process); $server-&gt;on('request', function ($request, $response) use ($process) {     $socket = $process-&gt;exportSocket();     $socket-&gt;send("asdf");     $response-&gt;send("adsf"); });  $server-&gt;start();
 
执行结果，第一次还是正常的，时间相差 2秒，但后面的就都会直接 返回空字符串，应该就是说 Socket 是无法连接的状态。
 $ php worker.php float(1573619506.2459) PHP Fatal error:  Uncaught Exception: xxx in /Users/limx/Applications/GitHub/limingxinleo/hyperf-demo/worker.php:16 Stack trace: #0 {main}   thrown in /Users/limx/Applications/GitHub/limingxinleo/hyperf-demo/worker.php on line 16 Fatal error: Uncaught Exception: xxx in /Users/limx/Applications/GitHub/limingxinleo/hyperf-demo/worker.php:16 Stack trace: #0 {main}   thrown in /Users/limx/Applications/GitHub/limingxinleo/hyperf-demo/worker.php on line 16 [2019-11-13 12:31:48 $44297.0]  WARNING swManager_check_exit_status: worker#8[pid=44306] abnormal exit, status=255, signal=0 float(1573619508.2687) string(0) "" float(1573619508.2688) PHP Fatal error:  Uncaught Exception: xxx in /Users/limx/Applications/GitHub/limingxinleo/hyperf-demo/worker.php:16 Stack trace:

**Comment by limingxinleo** [comment]
@xiangdong2 这里用来 woker 进程与 process 通信的，通常都是小数据。所以用的 SOCK_DGRAM，场景比较合适。

**Comment by matyhtf** [comment]
完全没明白你的意思。

**Comment by limingxinleo** [comment]
预期是这样的，recv 等待 5s，但2s时抛出错误，所以进程重启，则永远不会输出 recv 的值。

实际是这样，首次recv等待5s，2s后抛出错误，进程重启，但recv会立马返回空字符串，等待时间无效。

就是感觉 recv 时，如果进程被关闭，再拉起来的时候就有问题了。

**Comment by matyhtf** [comment]
这符合预期呀，recv 返回空值，表示socket被关闭。

**Comment by limingxinleo** [comment]
嗯嗯好的，框架里，这里已经兼容处理了。

**Comment by matyhtf** [comment]
exportSocket 导出的 socket 是一个新的 fd，只是原来管道的 dup ，当关闭这个 socket 时不影响进程管道。但是可能会收到一个 close 信号。通过 strace 分析得到，系统调用确实 recv 返回了 0

**Comment by lw006** [comment]
我遇到了类似的问题。其中一个工作进程异常退出  重新拉起后   socket -> recv 持续收到空字符串  并且不会阻塞  导致死循环

**Comment by limingxinleo** [comment]
@lw006 Swoole 最新版本已经没有这个问题了，你可以再试试
