### ISSUE TITLE
System::fread bug

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/swoole-src#2958]
Swoole: 4.4.12

问题：

* fread 返回结果比预期多 1
* 指针位置不会往后移

代码：

```php
<?php

use \Swoole\Coroutine\System;

file_put_contents(__DIR__ . '/1.txt', '1234567890');

go(function(){
    $fp = fopen(__DIR__ . '/1.txt', 'r');
    var_dump(System::fread($fp, 3));
    var_dump(System::fread($fp, 3));
    fclose($fp);
});
```

输出：

```
string(4) "1234"
string(4) "1234"
```

**Comment by tracenull** [comment]
> ```
> <?php
> 
> use \Swoole\Coroutine\System;
> 
> file_put_contents(__DIR__ . '/1.txt', '1234567890');
> 
> go(function(){
>     $fp = fopen(__DIR__ . '/1.txt', 'r');
>     var_dump(System::fread($fp, 3));
>     var_dump(System::fread($fp, 3));
>     fclose($fp);
> });
> ```

<?php

Swoole\Runtime::enableCoroutine(true, SWOOLE_HOOK_ALL);
file_put_contents(__DIR__ . '/1.txt', '1234567890');

go(function(){
    $fp = fopen(__DIR__ . '/1.txt', 'r');
    var_dump(fread($fp, 3));
    var_dump(fread($fp, 3));
    fclose($fp);
});   使用hook方式没问题结果如下：
string(3) "123"
string(3) "456"

**Comment by tracenull** [comment]
<?php

Swoole\Runtime::enableCoroutine(true, SWOOLE_HOOK_ALL);
file_put_contents(__DIR__ . '/1.txt', '1234567890');

go(function(){
    $fp = fopen(__DIR__ . '/1.txt', 'r');
    var_dump(fread($fp, 3));
    var_dump(fread($fp, 3));
    fclose($fp);
});


使用hook方式是对的
结果
string(3) "123"
string(3) "456"

**Comment by tracenull** [comment]
hook方式是对的，不知道为什么上条显示不出来
