### ISSUE TITLE
How to execute swoole code in php-fpm?

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#2959]
I have a php-fpm compatible php file that is too big to port to swoole code.

So these are the approaches I am attempting.

1. Run the php-fpm compatible php file in swoole, but I dont know how to make swoole execute such code. This is my preferred method, but I just dont know how.

2. I can port my swoole code in a php-fpm compatible php file but it is also to huge to port back to regular php file.

So this is my recent attempt run the php file from php-fpm and create a code that looks like this:

index.php
```php
<?php
start swoole
my swoole codes
end swoole

#include php-fpm-compatible.php

start swoole
other swoole code
end swoole

?>
```

How do I include a swoole code and run it from php-fpm? Solution to no. 1 would also be appreciated.

**Comment by twose** [comment]
We have no plan to support FPM anymore
Only sync Client is available in FPM

**Comment by jobs-git** [comment]
Yes, I understand the plan, I dont want it either, I am just stuck with the FPM old code. I dont know sync client, how does it work in FPM? Is it possible to run my swoole codes from php-fpm?

**Comment by twose** [comment]
The conversion between the two modes takes time to refactor
I think you could give up this idea
