### ISSUE TITLE
swoole_http_server 里 onClose 事件无效

### ISSUE THREAD

**Issue by breath-co2** [swoole/swoole-src#296]
```php
for($i = 1; $i< 10 ; $i++)
    {
        var_dump(connection_status());
        $response->write(microtime(1)."\n");
        sleep(1);
    }
```

这样分片输出，如果浏览器在中间断开，程序就会报错
Warning: swoole_http_response::write(): http client#1 is not exist. in ....

但是即便监听了 onClose 方法，也没触发过，所以需要考虑在中断连接后需要的支持。

**Comment by matyhtf** [comment]
swoole的代码是串行的，你的循环未退出之前不会执行任何其他代码。
