### ISSUE TITLE
WebSocketServer启动异常

### ISSUE THREAD

**Issue by a07061625** [swoole/swoole-src#2961]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

![image](https://user-images.githubusercontent.com/12109534/69032096-ab6fa380-0a16-11ea-89f2-9c5e5bbf76fe.png)
![image](https://user-images.githubusercontent.com/12109534/69032185-dc4fd880-0a16-11ea-9946-90dfd0eb367b.png)

2. What did you expect to see?

正常启动

3. What did you see instead?

启动失败，用ps命令看到的只有main和manager进程，且manager进程数量多达四五个
swoole的日志如下：
![image](https://user-images.githubusercontent.com/12109534/69032311-22a53780-0a17-11ea-8e33-1c8708f3e43b.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.4.6

5. What is your machine environment used (including version of kernel & php & gcc) ?

![image](https://user-images.githubusercontent.com/12109534/69032384-4b2d3180-0a17-11ea-930b-6c1d9b509671.png)

**Comment by twose** [comment]
先升级一下版本

**Comment by a07061625** [comment]
@twose 。。。大哥，这个是给公司在用的，现在要升级版本的话要告知运维，走工单太麻烦了，也不是什么不可接受的问题，大不了以后注意下不要这么用，要升级测试的话，估计要等下班回去了在自己家里电脑上测试了

**Comment by twose** [comment]
@a07061625 
因为如果版本很旧，有大概率是修过的问题，所以升级是必要的，否则会造成开发组的重复工作，对于你们来说是一个问题，而我们开发组有很多工作在不断推进，希望理解

当然你也可以使用valgrind给我们提供有效信息

https://github.com/swoole/swoole-src/blob/master/.github/ISSUE-CN.md#%E5%86%85%E5%AD%98%E5%88%86%E6%9E%90-%E5%BC%BA%E7%83%88%E6%8E%A8%E8%8D%90

**Comment by matyhtf** [comment]
@a07061625 可以考虑使用 docker 的方式，应用独立一份 php 和 swoole
