### ISSUE TITLE
异步tcp异常

### ISSUE THREAD

**Issue by qingdi** [swoole/swoole-src#2965]
**异常：**
PHP Fatal error:  Swoole\Client::__construct(): please install the ext-async extension, using Swoole\Async\Client in /Users/xx/workerspace/cli/sw/async_client.php on line 9

Fatal error: Swoole\Client::__construct(): please install the ext-async extension, using Swoole\Async\Client in /Users/xx/workerspace/cli/sw/async_client.php on line 9

**运行环境**
~/workerspace/cli/sw(master ✗) php --ri swoole
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.12
Built => Nov 20 2019 14:19:55
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2t  10 Sep 2019
http2 => enabled
pcre => enabled
zlib => 1.2.11
brotli => 16777223/16777223
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.display_errors => On => On
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144
swoole.use_shortname => On => On

~/workerspace/cli/sw(master ✗) php --ri swoole_async 

swoole_async

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.12
Built => Nov 20 2019 13:14:08
debug => enabled
trace_log => enabled
mysqlnd => enabled
async_redis => enabled

PHP 7.3.11 (cli) (built: Oct 24 2019 11:29:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies

系统是MAC

大家知道是什么原因吗？
安装了几次。报同样的错误？

**安装过程**
swoole-src
phpize
./configure --enable-openssl --enable-http2 --enable-mysqlnd --enable-sockets --enable-debug-log --with-php-config=/usr/local/Cellar/php/7.3.11/bin/php-config
make && make install

async-ext
phpize
./configure
make && make install 

**运行的代码是官方示例：**
$client = new swoole_client(SWOOLE_SOCK_TCP, SWOOLE_SOCK_ASYNC);

//注册连接成功回调
$client->on("connect", function($cli) {
    $cli->send("hello world\n");
});

//注册数据接收回调
$client->on("receive", function($cli, $data){
    echo "Received: ".$data."\n";
});

//注册连接失败回调
$client->on("error", function($cli){
    echo "Connect failed\n";
});

//注册连接关闭回调
$client->on("close", function($cli){
    echo "Connection close\n";
});

//发起连接
$client->connect('127.0.0.1', 9501, 0.5);

**Comment by matyhtf** [comment]
请安装 `ext-async`扩展,最新的版本中已经彻底移除了异步回调的 API,或者使用 协程 API

**Comment by qingdi** [comment]
版本问题：统一使用了4.4.7。async，swoole都使用了4.4.7版本。解决了。多谢。多谢。

**Comment by mitsh** [comment]
@matyhtf can you provide an example for coroutine tcp client like identical to Swoole\Async\Client?
