### ISSUE TITLE
swoole_http_request获取get参数错误

### ISSUE THREAD

**Issue by titrxw** [swoole/swoole-src#2967]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
获取请求get参数
curl http://127.0.0.1/test?sign=PM+Tt8hSD2LQQEOdz2K+RFaSqfk+maWsrM/LI1WOS1v2rlFFzD3Hb+Ey23/qugpk3lPFMUp3SNcvFakeYqUh8GUTjHAbD7wIfgc0aiVF1Xmf5itj+8jnpIqh1Wp2qdn3ENAh/xSHYhjy3eDzB/Lv/iivgUNI6Pc6bIIBat11zNg=

2. What did you expect to see?
sign: PM+Tt8hSD2LQQEOdz2K+RFaSqfk+maWsrM/LI1WOS1v2rlFFzD3Hb+Ey23/qugpk3lPFMUp3SNcvFakeYqUh8GUTjHAbD7wIfgc0aiVF1Xmf5itj+8jnpIqh1Wp2qdn3ENAh/xSHYhjy3eDzB/Lv/iivgUNI6Pc6bIIBat11zNg=

3. What did you see instead?
sign:
PM Tt8hSD2LQQEOdz2K RFaSqfk maWsrM/LI1WOS1v2rlFFzD3Hb Ey23/qugpk3lPFMUp3SNcvFakeYqUh8GUTjHAbD7wIfgc0aiVF1Xmf5itj 8jnpIqh1Wp2qdn3ENAh/xSHYhjy3eDzB/Lv/iivgUNI6Pc6bIIBat11zNg=

4. What version of Swoole are you using (show your `php --ri swoole`)?

- Swoole => enabled
- Author => Swoole Team <team@swoole.com>
- Version => 4.4.8
- Built => Nov 21 2019 19:07:17
- coroutine => enabled
- epoll => enabled
- eventfd => enabled
- signalfd => enabled
- cpu_affinity => enabled
- spinlock => enabled
- rwlock => enabled
- sockets => enabled
- openssl => OpenSSL 1.1.1d  10 Sep 2019
- http2 => enabled
- pcre => enabled
- zlib => enabled
- mutex_timedlock => enabled
- pthread_barrier => enabled
- futex => enabled
- mysqlnd => enabled
- async_redis => enabled
- 
- Directive => Local Value => Master Value
- swoole.enable_coroutine => On => On
- swoole.enable_library => On => On
- swoole.enable_preemptive_scheduler => Off => Off
- swoole.display_errors => On => On
- swoole.use_shortname => On => On
- swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
PHP 7.2.24-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 24 2019 18:29:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**Comment by eslizn** [comment]
应该是RFC1738和RFC2396的区别

**Comment by twose** [comment]
`Swoole\Http\Server`使用PHP的urlencode和urldecode对url参数进行编码和解码

请客户端进行正确编码后请求

**Comment by titrxw** [comment]
这个请求是从浏览器直接发起的
