### ISSUE TITLE
Swoole\Runtime::enableCoroutine() and cURL

### ISSUE THREAD

**Issue by osrec** [swoole/swoole-src#2969]
Hi Swoole Team

Does `Swoole\Runtime::enableCoroutine()` make all socket communication async? For example, would it make cURL requests in PHP async?

Thanks!

**Comment by huangzhhui** [comment]
`\Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_ALL | SWOOLE_HOOK_CURL)`

**Comment by osrec** [comment]
Thank you!
