### ISSUE TITLE
onReceive在数据包较大的时候会不会有问题?

### ISSUE THREAD

**Issue by ronalfei** [swoole/swoole-src#297]
// attach handler for receive event, every piece of data received by server, the registered handler will be
// executed. And all custom protocol implementation should be located there.
$serv->on('receive', function ($serv, $fd, $from_id, $data) {
    $serv->send($fd, $data);
});

这里接收到的data, 是一片数据, 这一片数据并不一定是完整的逻辑数据吧. 所以当一个完整的数据内容是大于tcp缓冲区的, 这里直接把接收到的一片数据进行后续的逻辑处理是不是就会出问题了.
如何解决数据完整性的问题?

**Comment by andot** [comment]
如果设置了 open_length_check，那么这里收到的数据就是完整的数据内容。否则，你需要在这里自己来进行数据组装，之后再处理。

**Comment by ronalfei** [comment]
意思是得通过这个package_length_offset的设置来直接解决这个问题吧?

**Comment by ronalfei** [comment]
还有一个问题顺便写到这里吧.我压测的时候日志里有大量的warn:
swFactoryProcess_finish: send failed, because connection[120] has been closed.
一般什么原因会导致?

**Comment by andot** [comment]
不仅仅是设置 package_length_offset 这一个参数，还有几个参数是一起来组合使用的。你可以查看swoole的wiki，上面有写。

压测的时候出现那个警告，是因为压测的客户端连接提前断开了，所以出现这个警告是正常的，不用理会。

**Comment by ronalfei** [comment]
多谢回复, 我先close了
