### ISSUE TITLE
tcp_server中添加自定义进程问题

### ISSUE THREAD

**Issue by lg430** [swoole/swoole-src#2976]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```
$serv = new \Swoole\Server($host, $port);
$serv->addProcess($processA);
$serv->addProcess($processB);

public function onWorkerStart()
{
// ...

$processA->setBlocking(false);
$processB->setBlocking(false);
}

public function onReceive()
{
// ...

$processA->write($msg)
$processB->write($msg)
}
```

2. What did you expect to see?
3. What did you see instead?
我现在使用了两个额外的进程来分别处理写日志和上报数据, 每当我在onReceive完成处理后, 就分发数据给这两个进程, 问题是我在onReceive这里连续发送两次消息貌似有点不合理且费时, 能一次发送广播给这两个进程吗?

另外我之前是通过在onReceive发送给$processA, 然后$processA再发送给$processB, 这样虽然只在onReceive发送一次, 但是$processB->setBlocking(false);这一行就失效了, 也就是在processA中发送给processB的管道始终是阻塞的, 请问有其他方法实现worker和process通信的方式吗或者我应该如何改呢

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole => 4.3.6

5. What is your machine environment used (including version of kernel & php & gcc) ?
php 7.1.2

**Comment by twose** [comment]
为什么不用协程

**Comment by lg430** [comment]
文档如是说
```
添加一个用户自定义的工作进程。此函数通常用于创建一个特殊的工作进程，用于监控、上报或者其他特殊的任务。
```

而我确实是需要一个进程单独上报注册中心呢

**Comment by twose** [comment]
不要死读书，协程是更好的选择

**Comment by matyhtf** [comment]
1. 循环发送
2. 已经是非阻塞的，不需要再次设置
