### ISSUE TITLE
PHP7.0.0编译swoole扩展的时候报错

### ISSUE THREAD

**Issue by zhaoxiong123** [swoole/swoole-src#298]
Makefile:194: recipe for target 'swoole.lo' failed

php_swoole.h:203:5: error: unknown type name ‘zend_object_handle’
     zend_object_handle handle = Z_OBJ_HANDLE_P(object);

PHP版本：7.0.0

**Comment by matyhtf** [comment]
PHP版本是否为php7.0-aphal1

**Comment by zhaoxiong123** [comment]
PHP版本为php7.0-aphal2

**Comment by matyhtf** [comment]
PHP7需要用github上最新的代码。

**Comment by zhaoxiong123** [comment]
oo
