### ISSUE TITLE
通过walle2自动部署平台部署本机应用，server进程/自定义进程无法启动，无报错

### ISSUE THREAD

**Issue by phenixsoul** [swoole/swoole-src#2980]
walle2自动部署平台使用www用户自动部署swoole应用，
当发布对象为本机（和walle2同一服务器）时，执行到$server->start();时，自动结束，无任何报错，相关server进程不启动。
当发布对象为其他服务器时，进程正常启动

试过两个swoole版本，4.4.4和4.4.11

**Comment by twose** [comment]
给出的信息太少 无法解答
