### ISSUE TITLE
socket: received a frame that is not masked as expected

### ISSUE THREAD

**Issue by phixcn** [swoole/swoole-src#2982]
![image](https://user-images.githubusercontent.com/1789175/69620877-050c4980-1079-11ea-9353-2d2122e62d04.png)

![image](https://user-images.githubusercontent.com/1789175/69620859-fde53b80-1078-11ea-9561-05343e9710d5.png)
刚升级到 4.4.12 版本就出现上面问题了
我的旧版本是 4.4.7，是正常的，其他版本没测试过
期待大神解答

**Comment by twose** [comment]
升级时是否make clean

请按照模板贴出相关信息

**Comment by twose** [comment]
使用对象的方式发送时flag产生了丢失，正在修复中

**Comment by phixcn** [comment]
大佬，赞赞赞。。。

**Comment by twose** [comment]
已在master修复，将包含在下个版本中发布
