### ISSUE TITLE
Accept-Encoding 判断错误

### ISSUE THREAD

**Issue by apetab** [swoole/swoole-src#2988]
http请求头：
```
Accept-Encoding: gzip, deflate
Accept: */*
```

gzip判断出错：[出错位置](https://github.com/swoole/swoole-src/blob/4ad77ae42f5cde60c383cf39a888e219d8f758ee/swoole_http_request.cc#L518)

**Comment by twose** [comment]
?

**Comment by apetab** [comment]
这个请求时应该识别成： accept_compression=1，  可是最后识别成了：accept_compression=0，  因为`Accept: */*` 也通过了判断条件， 进入了：`swoole_http_get_compression_method`

**Comment by twose** [comment]
还是没懂你在说什么 补丁也没看懂

**Comment by apetab** [comment]
用程序解释吧：
```
header_len = 15
header_name = "accept-encoding"
if (strncmp(header_name, "accept-encoding", header_len) == 0) {
    // passs
}
header_len = 6
header_name = "accept"
if (strncmp(header_name, "accept-encoding", header_len) == 0) {
    // passs
}
```

**Comment by twose** [comment]
抱歉，现在看明白了，这个问题需要一个彻底的修复（不仅仅是Accept）
