### ISSUE TITLE
build error as php7 extension  on mac os x 10.10.3

### ISSUE THREAD

**Issue by zhangjunlei26** [swoole/swoole-src#299]
ld: library not found for -lcrypt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [swoole.la] Error 1

**Comment by tangxunye** [comment]
the same error in mac os x 10.10.11 with php 5.5.23

**Comment by tangxunye** [comment]
ps: compile with --enable-openssl

**Comment by matyhtf** [comment]
新版本已经修复此问题。mac 使用 -lmcrypt
