### ISSUE TITLE
关于 Swoole\Timer::clear 定时器两个问题

### ISSUE THREAD

**Issue by 2007lf** [swoole/swoole-src#2992]
![image](https://user-images.githubusercontent.com/4098647/69923187-cb569b00-14dd-11ea-8525-3ea48269e8e9.png)
第一个问题如上图。
第二个问题，我这么写 Swoole\Timer::clear 提示找不到，Timer::clear 这么写和workman冲突，我该怎么写？

**Comment by twose** [comment]
`\Swoole\Timer::clear`

**Comment by 2007lf** [comment]
好的，谢谢，我试试，\Swoole\Timer::clearAll(); 可以回答下第一个问题吗

**Comment by twose** [comment]
当前进程

**Comment by 2007lf** [comment]
> 当前进程
多谢
