### ISSUE TITLE
PHP 7.4 zend_mm_heap corrupted

### ISSUE THREAD

**Issue by camry** [swoole/swoole-src#2996]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

use php start HTTP Server.

2. What did you expect to see?

`zend_mm_heap corrupted`

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.12
Built => Dec  2 2019 07:50:57
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
http2 => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 33554432 => 33554432

5. What is your machine environment used (including version of kernel & php & gcc) ?

php version: 7.4.0
gcc version: 9.2.0-r3

**Comment by twose** [comment]
@camry 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by camry** [comment]
@twose 您好，非常感谢您的回答。

1. 是首次编译
2. 用的是 Docker 服务做的镜像。
docker version: 19.03.5
FROM alpine:3.10
php version: 7.4.0
swoole version: 4.4.12

因为是用容器启动的服务，报错了，容器启动失败，暂提供不了 valgrind.log 日志。
之前用的 php 7.3.11 做的 swoole 4.3.6 可以正常运行。

现在将 php 升级 7.4.0，用 swoole 4.3.6 编译过不了，然后把 swoole 升级到 4.4.12 之后，编译没问题，但是在启动 HTTP 服务时，报错 zend_mm_heap corrupted.

**Comment by twose** [comment]
没有日志没办法定位问题
有可能是你编译的不正确
我一直在使用7.4的PHP，没有发现这种基础性的问题

**Comment by camry** [comment]
@twose 不好意思，我刚试了下不启动 swoole 服务，还是有这个错误，可能是安装了其它扩展导致的。
非常感谢您的回复。
