### ISSUE TITLE
php(86227,0x10e4a5dc0) Abort trap: 6 after PHP 7.4.0 on macOS 10.15.1

### ISSUE THREAD

**Issue by panosru** [swoole/swoole-src#3002]
After I updated my dev environment to PHP 7.4.0 I'm getting the following message when I'm running `php -v`:

```
PHP 7.4.0 (cli) (built: Nov 29 2019 16:18:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0, Copyright (c), by Zend Technologies
    with Xdebug v2.8.1, Copyright (c) 2002-2019, by Derick Rethans
    with blackfire v1.29.1~mac-x64-non_zts74, https://blackfire.io, by Blackfire
php(86227,0x10e4a5dc0) malloc: *** error for object 0x106965450: pointer being freed was not allocated
php(86227,0x10e4a5dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

if I run `php --ri swoole` I'm getting:
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.13-alpha
Built => Dec  3 2019 00:05:39
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
http2 => enabled
pcre => enabled
zlib => 1.2.11
brotli => 16777223/16777223
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144
php(86438,0x10853edc0) malloc: *** error for object 0x10af3d450: pointer being freed was not allocated
php(86438,0x10853edc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

and `php --ri swoole_async` returns:
```
swoole_async

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.13-alpha
Built => Dec  4 2019 15:20:12
debug => enabled
trace_log => enabled
mysqlnd => enabled
async_redis => enabled
php(86860,0x10b510dc0) malloc: *** error for object 0x108d6a450: pointer being freed was not allocated
php(86860,0x10b510dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

`gcc --version` outputs:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

and I'm on macOS 10.15.1

Is anyone facing the same issue?

**Comment by twose** [comment]
Execute the following command and show your log
```
USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php -v
```

**Comment by panosru** [comment]
@twose sorry for my late reply, I tried to install valgrind but is not compatible with my OS
![image](https://user-images.githubusercontent.com/400362/70245678-29ee7400-177f-11ea-8df9-87b8505fa727.png)

**Comment by panosru** [comment]
I have just tested with v4.4.13RC1 but I'm getting the same errors:
![image](https://user-images.githubusercontent.com/400362/70263843-ece6a980-179f-11ea-8abf-3ba0ba6170be.png)

**Comment by twose** [comment]
Sorry, valgrind can not work on macOS
and, do not use Xdebug, it conflicts with Swoole extension

**Comment by panosru** [comment]
I'm getting the same error even without xdebug...

![image](https://user-images.githubusercontent.com/400362/70325205-2c61d400-183a-11ea-88f0-dd6d1a929d2d.png)

Also, for the record, I never had any issue with swoole and xdebug being enabled together :/

**Comment by twose** [comment]
Sorry, I can't reproduce this problem on my Mac, it's stranger
Have you tried `make clean`?

**Comment by panosru** [comment]
@twose, it seems that swoole-src is not responsible for the error, ext-async is.. so I tried to compile ext-async but I got some errors.

I will open an issue there since apparently it is not this repo issue.

**Comment by panosru** [comment]
Actually, the issue was with v4.4.13 alpha on swoole_async, now that I updated swoole_async to v4.4.13RC1 I no longer get that error :)
