### ISSUE TITLE
运行中的协程websocket客户端，如何在另一个进程中进行push操作

### ISSUE THREAD

**Issue by 2007lf** [swoole/swoole-src#3003]
在一个命令行运行着一个协程websocket客户端，那我想在另一个命令行中运行的php程序中来操作这个客户端进行push数据，如何做到这个？

**Comment by twose** [comment]
建立IPC或网络通信

**Comment by 2007lf** [comment]
> 建立IPC或网络通信
是同一台服务器，不是远程的
