### ISSUE TITLE
用swoole4.4.12配合tcpdf生成pdf导致的内存溢出

### ISSUE THREAD

**Issue by lxyzsl** [swoole/swoole-src#3004]
在用swoole4.4.12的框架导出pdf时，发现内存会随着文件的写入而增加，最后直到撑爆了ini设定的内存值。请问如何解决？

**Comment by twose** [comment]
和swoole有什么关系？描述清楚点

**Comment by lxyzsl** [comment]
之前使用php-fpm的形式去批量生成pdf文件只需要设置set_time_limit(0)即可，底层逻辑就是fopen，fwrite，fclose。可是在swoole环境下，成一个PDF文件后，内存的文件流貌似没有被回收。就导致每生成一个pdf文件的文件流都会被叠加缓存。最后撑破了ini默认设置的128M。这是在之前fpm下没有出现过的。

**Comment by lxyzsl** [comment]
> 和swoole有什么关系？描述清楚点

之前使用php-fpm的形式去批量生成pdf文件只需要设置set_time_limit（0）就可以了，允许逻辑就是fopen，fwrite，fclose。可在swoole环境下，成一个PDF文件后，内存的文件流貌似没有被回收。就导致每个生成一个pdf文件的文件流都会被重叠缓存。最后撑破了inini默认设置的128M。这是在之前fpm下没有出现过的。

**Comment by twose** [comment]
fpm下每个请求结束都会自动释放内存
swoole是常驻内存的，全局变量静态变量需要你自行释放

**Comment by lxyzsl** [comment]
> fpm下每个请求结束都会自动释放内存
> swoole是常驻内存的，变量变量静态变量需要你自行释放

这我知道，那请问文件流怎么释放，我怀疑是文件流的问题，我也在网上看到别人也在讨论使用fwrite或者file_put_content写文件，内存没有得到释放
