### ISSUE TITLE
swoole 4.2.1 版本 Coroutine\Redis bug

### ISSUE THREAD

**Issue by shh12580** [swoole/swoole-src#3007]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

在调用redis的任何方法时，故意让多个协程同时调用单个redis实例，目的是让其出现错误，比如会出现以下警告错误信息：
errorCode:2;
errorMsg:redis client is waiting for response.
这个警告是准确的，问题在于，出现这个错误后，再次使用单个协程调用redis时，当redis执行成功后，redis实例的errorCode和errorMsg没有被重置，还是返回上次失败时的信息

2. What did you expect to see?

在redis调用失败后，再次调用没有重置上次的错误信息

3. What did you see instead?

期望是在redis调用失败后，再次调用之前能重置上次的错误信息

4. What version of Swoole are you using (show your `php --ri swoole`)?

版本 4.2.1

5. What is your machine environment used (including version of kernel & php & gcc) ?

php 7.1

**Comment by twose** [comment]
错误信息是配合返回值查看的，返回值不为false时错误信息无效
