### ISSUE TITLE
swoole 4.4.13 compile failed

### ISSUE THREAD

**Issue by oblind** [swoole/swoole-src#3008]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

./make.sh

2. What did you expect to see?

compile & install successfully

3. What did you see instead?

swoole-src/swoole_http_response.cc:1250:80: error: ‘struct http_context’ has no member named ‘websocket_compression’
         if (php_swoole_websocket_frame_object_pack(http_buffer, zdata, 0, ctx-
websocket_compression) < 0)

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.4.13

5. What is your machine environment used (including version of kernel & php & gcc) ?

unbuntu 18.04
php 7.4
gcc 7.4.0

看到4.4.13有官方的连接池，小激动了一把，然而编译不通过，请韩老大指点

**Comment by twose** [comment]
make clean了吗

**Comment by twose** [comment]
感谢反馈，通过apt/yum安装zlib或更新到master即可解决
