### ISSUE TITLE
hypery 报错

### ISSUE THREAD

**Issue by libaipeng1314** [swoole/swoole-src#3010]
[DEBUG] Event Hyperf\Database\Events\QueryExecuted handled by App\Listener\DbQueryExecutedListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Retrieved handled by Hyperf\ModelListener\Listener\ModelHookEventListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Retrieved handled by Hyperf\ModelListener\Listener\ModelEventListener listener.
[2019-12-06 10:58:12 $46252.0]	WARNING	swManager_check_exit_status: worker#0[pid=46254] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.4.12, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

**Comment by twose** [comment]
@libaipeng1314 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by libaipeng1314** [comment]
是自动编译的 centos 6.5 系统  PHP 7.2.24 (cli) (built: Oct 29 2019 15:20:05) ( NTS )

**Comment by twose** [comment]
如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

**Comment by libaipeng1314** [comment]
==2552== Memcheck, a memory error detector
==2552== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==2552== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==2552== Command: php bin/hyperf.php start
==2552== Parent PID: 2403
==2552== 
==2552== Invalid read of size 1
==2552==    at 0x1398339D: apm_execute_ex (apm.c:2270)
==2552==    by 0x926090: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:892)
==2552==    by 0x8F25D7: execute_ex (zend_vm_execute.h:59743)
==2552==    by 0x13983398: apm_execute_ex (apm.c:2265)
==2552==    by 0x925BE0: ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER (zend_vm_execute.h:1017)
==2552==    by 0x8F25D7: execute_ex (zend_vm_execute.h:59743)
==2552==    by 0x13983398: apm_execute_ex (apm.c:2265)
==2552==    by 0x949A11: ZEND_INCLUDE_OR_EVAL_SPEC_TMPVAR_HANDLER (zend_vm_execute.h:48935)
==2552==    by 0x8F25D7: execute_ex (zend_vm_execute.h:59743)
==2552==    by 0x13983398: apm_execute_ex (apm.c:2265)
==2552==    by 0x957BD2: zend_execute (zend_vm_execute.h:63780)
==2552==    by 0x8AA8F2: zend_execute_scripts (zend.c:1498)
==2552==  Address 0x14b861ac is 60 bytes inside a block of size 320 free'd
==2552==    at 0x4C28430: free (vg_replace_malloc.c:446)
==2552==    by 0x8E9CD8: zend_objects_store_del (zend_objects_API.c:196)
==2552==    by 0x958344: zend_leave_helper_SPEC (zend_objects_API.h:76)
==2552==    by 0x8F25D7: execute_ex (zend_vm_execute.h:59743)
==2552==    by 0x13983398: apm_execute_ex (apm.c:2265)
==2552==    by 0x926090: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:892)
==2552==    by 0x8F25D7: execute_ex (zend_vm_execute.h:59743)
==2552==    by 0x13983398: apm_execute_ex (apm.c:2265)
==2552==    by 0x925BE0: ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER (zend_vm_execute.h:1017)
==2552==    by 0x8F25D7: execute_ex (zend_vm_execute.h:59743)
==2552==    by 0x13983398: apm_execute_ex (apm.c:2265)
==2552==    by 0x949A11: ZEND_INCLUDE_OR_EVAL_SPEC_TMPVAR_HANDLER (zend_vm_execute.h:48935)
==2552== 
==2552== Conditional jump or move depends on uninitialised value(s)
==2552==    at 0x4060EDD: ???
==2552==    by 0x161AC1B7: ???
==2552==    by 0x161AC1B7: ???
==2552==    by 0x161AC1CA: ???
==2552==    by 0x7FEFFBDBF: ???
==2552==    by 0x161AFF5F: ???
==2552== 
==2552== Conditional jump or move depends on uninitialised value(s)
==2552==    at 0x4060F12: ???
==2552==    by 0x161AC1B7: ???
==2552==    by 0x161AC1B7: ???
==2552==    by 0x161AC1CA: ???
==2552==    by 0x7FEFFBDBF: ???
==2552==    by 0x161AFF5F: ???
==2552==

**Comment by libaipeng1314** [comment]
太长不能全部复制

**Comment by matyhtf** [comment]
看样子是 apm 软件，swoole tracker 的问题，已反馈给相关开发者。

**Comment by GXhua** [comment]
@libaipeng1314  加微信聊下，这应该是tracker的问题 15811413647

**Comment by libaipeng1314** [comment]
已加




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"郭新华"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 下午3:49
收件人:&nbsp;"swoole/swoole-src"<swoole-src@noreply.github.com&gt;;
抄送:&nbsp;"☀sunny☀"<1073091707@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [swoole/swoole-src] hypery 报错 (#3010)




@libaipeng1314  加微信聊下，这应该是tracker的问题 15811413647
