### ISSUE TITLE
请问一下swoole2.2.0能否支持php7.3.8

### ISSUE THREAD

**Issue by zhaomengqiao** [swoole/swoole-src#3015]
使用alpine7.3.8的docker镜像pecl安装swoole2.2.0一直报错

FROM php:7.3-fpm-alpine
。。。
。。。
pecl install swoole-2.1.3 
docker-php-ext-enable swoole 

报错：
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20180731/swoole.so (Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20180731/swoole.so: _zend_hash_add_or_update: symbol not found), /usr/local/lib/php/extensions/no-debug-non-zts-20180731/swoole.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20180731/swoole.so.so: No such file or directory)) in Unknown on line 0

请问一下swoole2.2.0能否支持php7.3.8？如果要是使用swoole2的话，需要换php7.2吗？

**Comment by twose** [comment]
版本太低
