### ISSUE TITLE
Is there a possible conflict between php_swoole and php_zookeeper?

### ISSUE THREAD

**Issue by Timandes** [swoole/swoole-src#302]
I wrote a small program to explain this.

After I run this:

```
<?php
swoole_process::signal(SIGTERM, function() {
        echo "TERM\n";
});

swoole_event_wait();
```

I opened another terminal and send a TERM signal by:

```
kill <pid>
```

And the original terminal printed:

```
TERM
```

But when I added only one line:

```
$zk = new \Zookeeper('106.39.209.43:2182');
```

The program was terminated directly after sending TERM signal.
It seems that after creating Zookeeper instance, the swoole_process::signal() fails.

Could you guys help me to solve this?

**Comment by Timandes** [comment]
```
$ uname -a
Linux xxx 2.6.32-220.el6.x86_64 #1 SMP Tue Dec 6 19:48:22 GMT 2011 x86_64 x86_64 x86_64 GNU/Linux

$ php -v
PHP 5.4.29 (cli) (built: Apr  9 2015 17:17:25)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.4, Copyright (c) 2002-2014, by Derick Rethans
```

**Comment by Timandes** [comment]
This only happens under PHP 5.4.

Program under PHP 5.3 does not have this issue.

**Comment by matyhtf** [comment]
disable signalfd
```php
Swoole\Async::set([
    'enable_signalfd' => false,
]);
```
