### ISSUE TITLE
[question] Send HTTP traffic to specific dedicated workers?

### ISSUE THREAD

**Issue by ValiDrv** [swoole/swoole-src#3021]
Hello

Is there a way to send HTTP traffic to certain specific dedicated workers?

Example, say I start an HTTP server with 500 workers on a 24 core/64GB RAM server.
(it can handle the load fine).

- Requests on `^/rules/` should be sent to workers number **0** to **10**, they would each business rules in memory and take `~1sec` to process and hold `~5GB` of rules in memory.
- Requests on `^/scrapes/` should be sent to workers number **11** to **450**, they would mainly run sequential CURL jobs waiting for results, they would take `1sec -1min` to wait for the data, and about `~50MB ram`.
- and the rest would be normal `web workers`, that would connect to the DB/serve some cached results, they would take under `~100ms` to reply with `~50MB ram`.

Are there any best practices be to split this workload? Or should I only run the `^/rules/` jobs in swoole and the rest using nginx/apache?

**Comment by twose** [comment]
@ValiDrv 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by twose** [comment]
1. nginx + multi servers
2. dispatch_func
```php
$server->set([
    'dispatch_func' => function (Server $serv, int $fd, int $type, string $data) {
        var_dump($fd, $type, $data);
        return $worker_id;
    },
]);
```
3. $server->task($data, int $dst_worker_id);

**Comment by ValiDrv** [comment]
**Awesome**, thank you very much.

There is a bug in the wiki, unless it's a translation error.

Page: https://wiki.swoole.com/wiki/page/698.html

> However dispatch_func, only the **previous** 8Kcontent of the data packet can be passed in the function, and the complete packet content cannot be obtained.

Since it returns 0-8180 bytes, it should probably be:
> However dispatch_func, only the **first** 8Kcontent of the data packet can be passed in the function, and the complete packet content cannot be obtained.
