### ISSUE TITLE
服务平滑关闭的问题

### ISSUE THREAD

**Issue by lg430** [swoole/swoole-src#3023]
Please answer these questions before submitting your issue. Thanks!

开启一个process模式下的tcp server, 当我向master发送"kill -15 主进程PID"关闭服务的一瞬间, 
外部客户端是否还能与此server建立成功tcp连接, 以及此与server已建立的tcp连接发送数据过来, 
master进程是否会将数据分发给worker处理 ?

在这一瞬间, 有相应的事件函数可用吗, 用于处理服务最后关闭前的一些善后工作

或者说使用"kill -15 主进程PID"这种方式来关闭服务正确吗

**Comment by matyhtf** [comment]
可以建立连接，因为3次握手是内核处理的。但是 Server 不会accept 这个连接，也就是不会处理。客户端可以发送数据，在shutdown阶段，会被强制关闭关闭连接，收到 connection reset 信号。你要做到绝对无损，需要有一个 LB 层，从外部摘除，彻底切断入口流量。
