### ISSUE TITLE
希望ssl_method选项增加TLS方法支持

### ISSUE THREAD

**Issue by z5864703** [swoole/swoole-src#3024]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
无

2. What did you expect to see?
希望ssl_method选项可以支持TLS_method(), TLS_server_method(), TLS_client_method()三个方法，这个也是openssl官方推荐的方法，可以自动协商出双方都支持的最高版本，而不是指定某个版本。

3. What did you see instead?
无

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.4.13

5. What is your machine environment used (including version of kernel & php & gcc) ?
无

**Comment by twose** [comment]
默认应该是自动协商吧?
是否有PHP官方实现的参考?

**Comment by twose** [comment]
新增常量
`SWOOLE_TLS_METHOD`
`SWOOLE_TLS_SERVER_METHOD`
`SWOOLE_TLS_CLIENT_METHOD`

低版本Swoole可使用别名
`SWOOLE_SSLv23_METHOD`
`SWOOLE_SSLv23_SERVER_METHOD`
`SWOOLE_SSLv23_CLIENT_METHOD`
