### ISSUE TITLE
swoole-src-swoole-1.7.17-stable FactoryProcess.c:430@swManager_loop]wait() failed

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#303]
[/home/work/env/php/extensions/swoole-src-swoole-1.7.17-stable/src/factory/FactoryProcess.c:430@swManager_loop]wait() failed. Error: Interrupted system call [4]

不清楚影响，请帮忙看看，是否有影响？ 非常感谢～

<pre>
   while (SwooleG.running > 0)
    {
        pid = wait(&status);

        if (pid < 0)
        {
            if (ManagerProcess.reloading == 0)
            {
                swTrace("wait() failed. Error: %s [%d]", strerror(errno), errno);
            }
            else if (ManagerProcess.reload_event_worker == 1)
            {

</pre>

**Comment by matyhtf** [comment]
这是trace信息，可以忽略。error 4 是中断，表示进程收到了信号，这是很正常的。
