### ISSUE TITLE
SWOOLE_ERROR_SSL_BAD_CLIENT 

### ISSUE THREAD

**Issue by caichudong** [swoole/swoole-src#3032]
hello，I had encounter a strange problem, I hope get some tips.
I wrote a sever (call A) with swoole. I use HttpClient to request  other services.
When the data packet exteeds 50KB, return the HttpCode is 1013(SWOOLE_ERROR_SSL_BAD_CLIENT ), if the packet less than 50KB，always right.
Why so strange? Could u give some tips to slove this problem?

**Comment by caichudong** [comment]
Why the error is SWOOLE_ERROR_SSL_BAD_CLIENT?

**Comment by twose** [comment]
respect issue template please
