### ISSUE TITLE
请求https域名，在post方式下提交的数据包到几十KB的时候触发错误，SWOOLE_ERROR_SSL_BAD_CLIENT，能给点提示如何解决这个问题吗？

### ISSUE THREAD

**Issue by caichudong** [swoole/swoole-src#3033]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

我使用swoole的HttpClient作为服务的http和https请求发起的客户端。

2. What did you expect to see?

包括在几百KB数据包的情况下也可以使用，但是遇到一个问题。

3. What did you see instead?

我从服务发起https请求，post方式提交的数据包到50KB+的时候触发一个错误SWOOLE_ERROR_SSL_BAD_CLIENT，数据包小的时候都是正常的。请问下，具体是什么原因？

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole 4.3.3  使用的是 easyswoole 3.3.2

5. What is your machine environment used (including version of kernel & php & gcc) ?

Ubuntu & php 7.2

**Comment by caichudong** [comment]
@twose 你好，有空的时候麻烦帮我看下这个问题，是我哪里有问题吗？

**Comment by twose** [comment]
先升级到最新版本

**Comment by matyhtf** [comment]
低版本中存在的 bug ，已经解决了，请升级至 高版本。

**Comment by caichudong** [comment]
好的，谢谢。我升级到4.4.13看看。
