### ISSUE TITLE
当我在server中addProcess后，希望对自定义进程加入自定义信号处理，收到SIGTERM信号做平滑停止处理，官网好像并没有提供server中自定义的信号处理

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [swoole/swoole-src#3037]
\swoole_process::signal(SIGTERM,[$this,"shutdown"]);
        $this->swoole_process = new \swoole_process([$this,"run"],false,SOCK_DGRAM,true);

这样好像并不可以解决这个问题，swoole_process的signalfd事件循环和server的不是一个

[2019-12-26 12:27:00 @10246.0]	WARNING	bind(:982): unixSocket 0, Error: Success[0]
[2019-12-26 12:27:06 #10240.1]	INFO	Server is shutdown now
[2019-12-26 12:27:06 #10240.1]	WARNING	swSignalfd_setup: signalfd has been created

收到信号后没有触发我注入的函数

**Comment by huanghantao** [comment]
@LeiZhang-Hunter 

我这里有一份代码可以，用的是最新的`master`分支的代码：

```php
<?php

use Swoole\Process;
use Swoole\Server;

$server = new Server('127.0.0.1', 9501);

$process = new Process(function ($process) use ($server) {
    while (true) {
        $msg = $process->read();
        foreach ($server->connections as $conn) {
            $server->send($conn, $msg);
        }
    }
});

Process::signal(SIGTERM,[$server, "shutdown"]);
$server->addProcess($process);
$server->on('receive', function ($serv, $fd, $reactor_id, $data) use ($process) {
    $process->write($data);
});

$server->start();
```

```shell
[root@aaeb2c267d0f server]# kill 19955
```

```shell
[2019-12-26 05:45:07 #19955.6]	INFO	Server is shutdown now
```

**Comment by LeiZhang-Hunter** [comment]
好的感谢
