### ISSUE TITLE
Redis连接池

### ISSUE THREAD

**Issue by zhuchenglin** [swoole/swoole-src#3038]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
    1. Redis连接池可以多个进程共用一个连接池吗。
     2. 共享内存存储的大多数都是字符串类型，不能存储变量的值。

2. What did you expect to see?
 可以使某种方法使得程序全局变量变为在进程中读取和写入，外部也修改吗

**Comment by twose** [comment]
1. 不能, 除非做外部的本地连接池
2. 进程间内存隔离, 进程上下文也不同, 数据交换必须序列化

**Comment by zhuchenglin** [comment]
感谢回复
现在想做一个所有worker进程都可以共用的一个连接池，使用进程通信，socket对象从一个进程传到另一个进程发现是不可用的
将socket序列化之后只能得到一个数字，不用使用

您说的外部的本地连接池是指什么，望大神不吝赐教

**Comment by twose** [comment]
做不了的 你想的太简单了 如果有这么容易大家都跨进程共享数据用跨进程连接池了

外部连接池是指本地起一个专门的数据库代理服务器去连接其它数据库服务器, 这个数据库代理服务器还能支持单连接并发, 降低实际连接数据库服务器的连接数

**Comment by zhuchenglin** [comment]
收到，感谢赐教，我再想想
