### ISSUE TITLE
WARNING swManager_check_exit_status: worker#0[pid=11652] abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by 26597925** [swoole/swoole-src#3039]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
==11653== Warning: client switching stacks?  SP change: 0x16aa1090 --> 0x1ffeffc8d0
==11653==          to suppress, use: --max-stackframe=137041918016 or greater
==11652== Warning: client switching stacks?  SP change: 0x1ffeffc7c0 --> 0x17202ff8
==11652==          to suppress, use: --max-stackframe=137034176456 or greater
==11652==          further instances of this message will not be shown.
==11652== Invalid read of size 1
==11652==    at 0x7EA2F89: ??? (in /usr/lib64/libz.so.1.2.7)
==11652==    by 0x7EA358F: ??? (in /usr/lib64/libz.so.1.2.7)
==11652==    by 0x7EA4623: deflate (in /usr/lib64/libz.so.1.2.7)
==11652==    by 0x11BEB519: swoole_http_response_compress(_swString*, int, int) (swoole_http_response.cc:647)
==11652==    by 0x11BEB7E7: swoole_http_response_end(http_context*, _zval_struct*, _zval_struct*) (swoole_http_response.cc:736)
==11652==    by 0x8E6DA7: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:984)
==11652==    by 0x8E6DA7: execute_ex (zend_vm_execute.h:55505)
==11652==    by 0x11BCF583: swoole::PHPCoroutine::main_func(void*) (swoole_coroutine.cc:764)
==11652==    by 0x11B80B49: swoole::Context::context_func(void*) (context.cc:125)
==11652==    by 0x11C4BD80: make_fcontext (make_x86_64_sysv_elf_gas.S:64)
==11652==  Address 0x114599ff8 is on thread 1's stack
==11652== 
==11652== 
==11652== Process terminating with default action of signal 11 (SIGSEGV)
==11652==  Access not within mapped region at address 0x114599FF8
==11652==    at 0x7EA2F89: ??? (in /usr/lib64/libz.so.1.2.7)
==11652==    by 0x7EA358F: ??? (in /usr/lib64/libz.so.1.2.7)
==11652==    by 0x7EA4623: deflate (in /usr/lib64/libz.so.1.2.7)
==11652==    by 0x11BEB519: swoole_http_response_compress(_swString*, int, int) (swoole_http_response.cc:647)
==11652==    by 0x11BEB7E7: swoole_http_response_end(http_context*, _zval_struct*, _zval_struct*) (swoole_http_response.cc:736)
==11652==    by 0x8E6DA7: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:984)
==11652==    by 0x8E6DA7: execute_ex (zend_vm_execute.h:55505)
==11652==    by 0x11BCF583: swoole::PHPCoroutine::main_func(void*) (swoole_coroutine.cc:764)
==11652==    by 0x11B80B49: swoole::Context::context_func(void*) (context.cc:125)
==11652==    by 0x11C4BD80: make_fcontext (make_x86_64_sysv_elf_gas.S:64)
==11652==  If you believe this happened as a result of a stack
==11652==  overflow in your program's main thread (unlikely but
==11652==  possible), you can try to increase the size of the
==11652==  main thread stack using the --main-stacksize= flag.
==11652==  The main thread stack size used in this run was 8388608.
==11652== 
==11652== HEAP SUMMARY:
==11652==     in use at exit: 18,716,957 bytes in 26,240 blocks
==11652==   total heap usage: 31,042 allocs, 4,802 frees, 27,784,230 bytes allocated
==11652== 
==11652== LEAK SUMMARY:
==11652==    definitely lost: 0 bytes in 0 blocks
==11652==    indirectly lost: 0 bytes in 0 blocks
==11652==      possibly lost: 2,197,881 bytes in 16,730 blocks
==11652==    still reachable: 16,519,076 bytes in 9,510 blocks
==11652==                       of which reachable via heuristic:
==11652==                         stdstring          : 27,409 bytes in 769 blocks
==11652==         suppressed: 0 bytes in 0 blocks
==11652== Rerun with --leak-check=full to see details of leaked memory
==11652== 
==11652== For counts of detected and suppressed errors, rerun with: -v
==11652== Use --track-origins=yes to see where uninitialised values come from
==11652== ERROR SUMMARY: 154984 errors from 119 contexts (suppressed: 0 from 0)
[2019-12-26 16:24:35 $11649.0]  WARNING swManager_check_exit_status: worker#0[pid=11652] abnormal exit, status=0, signal=11

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?
centos7.7 
PHP 7.3.12
gcc version 4.8.5

**Comment by twose** [comment]
@26597925 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by twose** [comment]
Swoole版本号是?

**Comment by 26597925** [comment]
swoole 4.4.13

**Comment by twose** [comment]
建议更新zlib库后重新从头编译swoole

**Comment by twose** [comment]
反馈通过更新zlib已解决

相关参考: 
1. [【zlib】CentOS7.x 上编译升级zlib](https://blog.csdn.net/michaelwoshi/article/details/96460299) (zlib 安全漏洞 CVE 2016-9843)
2. [centos libz.a(compress.o): relocation R_X86_64_32 against `.rodata.str1.1'](https://blog.csdn.net/Nankys/article/details/86575544)
