### ISSUE TITLE
swProcessPool_wait: worker#7 abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by hanyh2004** [swoole/swoole-src#304]
1，客户端代码
 ab -c 100 -n 1000  "http://127.0.0.1:9168/"

2，出错提示
2015-07-03 14:31:47 #15066.0]	WARN	swProcessPool_wait: worker#9 abnormal exit, status=0, signal=11
[2015-07-03 14:31:47 #15066.0]	WARN	swProcessPool_wait: worker#8 abnormal exit, status=0, signal=11
.......

3，服务器代码
<?php

function biz($request,$response) {

    $im = imagecreatetruecolor(100, 100);

    imagefilledrectangle($im, 0, 0, 99, 99, 0xFFFFFF);

    imagestring($im, 3, 40, 20, 'GD Library', 0xFFBA00);
    $response->header('Content-Type', 'image/gif');
    imagegif($im);
    imagedestroy($im);
}

function dealRequest($request,$response) {
    ob_start();
    biz($request,$response);
    $data = ob_get_contents();
    ob_end_clean();
    return $data;

}

$options = array(
    'worker_num'=>10,
    'daemonize'=>false,
    'package_max_length'    => 2000000,  //协议最大长度
);

$server = new \swoole_http_server("0.0.0.0", 9168,SWOOLE_BASE, SWOOLE_SOCK_TCP);
$server->setGlobal(HTTP_GLOBAL_ALL); //已经设置了全局变量
$server->set($options);
$server->on('request', function ($request, $response) {
    $data = dealRequest($request,$response);
    $response->write($data);
    $response->end();
    unset($_POST);
    unset($_GET);
    unset($_SERVER);
    unset($_COOKIE);
});
$server->start()

**Comment by Atriedes** [comment]
It seem random error, I got that too when benchmarking with apache benchmark but after couple trying it often works

**Comment by Atriedes** [comment]
I think the problem is relate with `ob_*` function, I have several request hanged when use `ob_*`

@matyhtf  could you please take a look this issue

**Comment by matyhtf** [comment]
使用1.7.22版本
