### ISSUE TITLE
 \Swoole\Process\Pool 与 \Swoole\Async\Client 不能正常运行

### ISSUE THREAD

**Issue by km3945** [swoole/swoole-src#3047]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
        $pool = new \Swoole\Process\Pool($this->workerNum);
        $pool->on("WorkerStart", function (Pool $pool, $workerId) {
            echo 'WorkerStart: '. $workerId."\n";

            $socket = new \Swoole\Async\Client(SWOOLE_SOCK_TCP);
            $socket->on("connect", function(swooleClient $cli) {
                $this->output->writeln('connect start');
            });
            $socket->on("receive", function(swooleClient $cli, $data){
                echo 'receive'."\n";
            });
            $socket->on("error", function(swooleClient $cli){
                echo "error\n";
            });
            $socket->on("close", function(swooleClient $cli){
                echo "Connection close\n";
            });
            $socket->connect('106.11.210.209', 8003);
        });

        $pool->on("WorkerStop", function ($pool, $workerId) {
            echo 'WorkerStop '.$workerId."\n";
        });

        $pool->start();
```

2. What did you expect to see?
我需望子进程中的 异步客户端能正常运行.

我的原始需求是.建多信进程,每个程序都连接到服务上面,等待接收数据并处理
(或是按我的需求给出解决方案 ^!^)
3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.14
Built => Dec 27 2019 10:20:15
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

swoole_async

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.14
Built => Dec 31 2019 11:07:29
debug => enabled
trace_log => enabled
mysqlnd => enabled
async_redis => enabled

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by matyhtf** [comment]
在 `onWorkerStart`回调函数 末尾添加 `Swoole\Event::wait()`
