### ISSUE TITLE
socket超时问题

### ISSUE THREAD

**Issue by lg430** [swoole/swoole-src#3048]
Please answer these questions before submitting your issue. Thanks!

```
linux  4.18.20
swoole 4.3.6
php 7.1.2
```

我发现有一些通过Client创建的tcp连接, 线上超时很多, 而超时发生的时刻, tcp连接对方表示没有收到socket数据, 我怀疑是write_timeout这个参数没设置好, 导致未完成快速重传

就是假如tcp包被ip层分为了几个分片, 其中一个分片在传输过程中丢失, 而此时write_timeout时间已过, 导致未完成重传, 对方就未收到完整的包

还是说write_timeout只是将待发送数据放入到发送队列的超时时间, 底层tcp重传完全由linux内核负责?

这种对方表示未收到数据, 而我这里send返回值等于发送数据字节数的情况下, 有什么办法排查呢? 线上持续开一个tcpdump抓包吗?

```
$sConn = new \Swoole\Coroutine\Client(SWOOLE_SOCK_TCP);
$sConn->set([
    'connect_timeout'       => 0.1,
    'write_timeout'         => 0.3,
    'read_timeout'          => 0.7,
    'open_length_check'     => true,
    'package_length_type'   => 'V',
    'package_length_offset' => 6,
    'package_body_offset'   => 10,
    'package_max_length'    => 1024 * 1024 * 4,
    'socket_buffer_size'    => 1024 * 1024 * 8,
    'open_tcp_nodelay'      => true,
]);
```

recv超时连接错误信息
```
{
    "conn": {
        "errCode": 110,
        "errMsg": "Connection timed out",
        "sock": 38,
        "type": 1,
        "setting": {
            "connect_timeout": 0.1,
            "write_timeout": 0.3,
            "read_timeout": 0.7,
            "open_length_check": true,
            "package_length_type": "V",
            "package_length_offset": 6,
            "package_body_offset": 10,
            "package_max_length": 4194304,
            "socket_buffer_size": 8388608,
            "open_tcp_nodelay": true
        },
        "connected": true
    }
}
```

**Comment by twose** [comment]
write_timeout是指超过这个时间没有等待到socket可写事件(缓冲区持续未空), 不再继续尝试写入数据

> 还是说write_timeout只是将待发送数据放入到发送队列的超时时间, 底层tcp重传完全由linux内核负责?

所以是的, 只是写到写缓冲区的超时

> 这种对方表示未收到数据, 而我这里send返回值等于发送数据字节数的情况下, 有什么办法排查呢? 

外网不稳定因素太多了, send返回值只表示成功写入缓冲区的长度, 不代表对端一定能收到, 除非对端收完后返回一个response, 这就是上层的协议问题了, 排查的话自然能自己抓包监控流量是最好的

**Comment by twose** [comment]
如果你的带宽不够, write_timeout可以大一点, 太小了
socket_buffer_size有点太大了, 协程其实不需要那么大, 当然视你的具体情况而定

**Comment by lg430** [comment]
@twose 好的,我抓包排查下呢

**Comment by giantwu** [comment]
@lg430  请问您的问题有结果了吗？我们线上的 Swoole\Coroutine\Http\Client  也发现了类似的问题，内网调用。
