### ISSUE TITLE
swoole.so: undefined symbol: php_http_parser_init

### ISSUE THREAD

**Issue by xooass** [swoole/swoole-src#305]
symbol lookup error: /usr/local/php5/lib/php/extensions/no-debug-non-zts-20131226/swoole.so: undefined symbol: php_http_parser_init

php5.5.26  php5.6.10

code:
<?php

$http = new swoole_http_server("0.0.0.0", 9501);

$http->on('request', function ($request, $response) {
    $response->header("Content-Type", "text/html; charset=utf-8");
    $response->end("<h1>Hello Swoole. #".rand(1000, 9999)."</h1>");
});

$http->start();

**Comment by xooass** [comment]
换了另外一台服务器  系统老点  是centos5   没上面那个错误了  但是出现新错误

/usr/local/php56/bin/php: symbol lookup error: /usr/local/php56/lib/php/extensions/no-debug-non-zts-20131226/swoole.so: undefined symbol: __sync_bool_compare_and_swap_4

**Comment by matyhtf** [comment]
gcc版本过低，请升级到最新的GCC

**Comment by matyhtf** [comment]
http://wiki.swoole.com/wiki/page/452.html

**Comment by guojianing** [comment]
4.4.7 不低吧～
