### ISSUE TITLE
Can we rely on websocket FD number not being repeated?

### ISSUE THREAD

**Issue by osrec** [swoole/swoole-src#3052]
This is a general question, not a bug, so I don't think the issue template applies.

For reference, I am using the latest version of swoole with PHP 7.4.0 on Alpine Linux (Docker).

My question: When running a websocket server, like so:

```php
$server = new Swoole\WebSocket\Server("0.0.0.0", 9501);

$server->on('message', function (Swoole\WebSocket\Server $server, $frame) 
{
    echo "receive from {$frame->fd}:{$frame->data},opcode:{$frame->opcode},fin:{$frame->finish}\n";
    $server->push($frame->fd, "this is server");
});
```
is it safe to assume that `$frame->fd` will be the same for messages for the same connection?

Also, if a particular `$frame->fd` is re-used, will this only be after an explicit `onClose` event?

The background for this question is that we want to allow users to log in via a websocket, and want to check whether it is sufficient to just authenticate users at the start and maintain a list of authenticated FDs on the backend, or whether we need to get the client to send us a session ID/token with every frame.

Thanks!

**Comment by twose** [comment]
> is it safe to assume that $frame->fd will be the same for messages for the same connection?

yes, fd is almost never reused (Unless it exceeds 16000k)

**Comment by osrec** [comment]
Great, thank you! So basically only after FD > 16 million will it repeat?

**Comment by matyhtf** [comment]
@osrec Yes,  it will skip the fd in use

**Comment by osrec** [comment]
thanks for your help @matyhtf and @twose :)
