### ISSUE TITLE
swoole在守护模式下rabbitmq cpu使用率达到100%

### ISSUE THREAD

**Issue by geek377148474** [swoole/swoole-src#3053]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

不开守护模式不会，使用rabbitmq通讯，只要swoole setting开启了守护模式，就会在使用一定时间后，CPU使用率上升到100%。

2. What did you expect to see?
我期待的是守护模式能跟不开启的效果保持一致，CPU不会被占用100%

3. What did you see instead?
守护模式下使用rabbitmq，CPU会被占用100%

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.4.12,   4.4.14   ，当前4.5

5. What is your machine environment used (including version of kernel & php & gcc) ?
php7.3

**Comment by geek377148474** [comment]
不开守护模式不会，只要挂后台了，就会在一定时间后，CPU使用率上升到100%。应该是跟这部分有关

**Comment by sy-records** [comment]
有fatal error，进程挂掉了重新拉起了吧。请按模板提交问题

**Comment by geek377148474** [comment]
没有fatal error

**Comment by geek377148474** [comment]
> 有fatal error，进程挂掉了重新拉起了吧。请按模板提交问题

没有fatal error

**Comment by geek377148474** [comment]
> 有fatal error，进程挂掉了重新拉起了吧。请按模板提交问题

已按模板提交问题

**Comment by twose** [comment]
信息太少 无法回答 请提供可重现的例子

**Comment by matyhtf** [comment]
@geek377148474 请使用 gdb strace 等工具进行初步跟踪

**Comment by shenzhe** [comment]
用Swoole Tracker看看？ https://www.swoole-cloud.com/tracker/index

**Comment by matyhtf** [comment]
可能是 PHP 代码中存在死循环，请自行调试一下。配合使用 gdb strace 等工具进行解决。
