### ISSUE TITLE
swoole table内存占用疑问，为什么每个worker都占用相近大小的内存块，不应该是只有一份吗？

### ISSUE THREAD

**Issue by caichudong** [swoole/swoole-src#3056]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
我想使用swoole table作为共享内存表存储数据，但是发现每个worker都会占用同大小的内存。

2. What did you expect to see?
既然是共享内存表，我理解是主进程维护的一块内存占用。

3. What did you see instead?
但是我看到是每个worker使用都会占用相近大小的内存块。

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.3.3

5. What is your machine environment used (including version of kernel & php & gcc) ?
osx（mac笔记本）
php7.2

**Comment by twose** [comment]
你怎么看的

**Comment by caichudong** [comment]
> 你怎么看的

top命令，看对应worker进程的内存占用，然后测试不同worker进程，发现对应Mem数据一直增长到和之前的worker进程占用相近。
![image](https://user-images.githubusercontent.com/26949885/72034948-6b6bc500-32d1-11ea-91f7-d8a4ea3aa26c.png)

**Comment by twose** [comment]
贴代码 给个复现例子

**Comment by caichudong** [comment]
> 截图截全图 贴代码 给个复现例子 别挤牙膏 反馈一次性到位

1、测试接口，sleep占用worker，输出worker_id
![image](https://user-images.githubusercontent.com/26949885/72035404-bb975700-32d2-11ea-8912-0885fc2a22a4.png)
2、初始化table
![image](https://user-images.githubusercontent.com/26949885/72035697-92c39180-32d3-11ea-89be-b2ad929c19cd.png)

3、启动端口监听
4、访问接口，触发5W次table写入
![image](https://user-images.githubusercontent.com/26949885/72035480-f600f400-32d2-11ea-8f73-9b15df557ba2.png)
5、新开浏览器tab，访问接口，触发5W次table写入
![image](https://user-images.githubusercontent.com/26949885/72035534-26e12900-32d3-11ea-9ce1-b5ca976af3fa.png)
6、比对第四第五步worker，观看top命令对应启动php的进程
![image](https://user-images.githubusercontent.com/26949885/72035677-86d7cf80-32d3-11ea-9719-de6353592a00.png)

请看看。

**Comment by twose** [comment]
table要在主进程创建 (启动server之前)

**Comment by caichudong** [comment]
> table要在主进程创建 (启动server之前)

好的，我测试看，谢谢。

**Comment by caichudong** [comment]
> table要在主进程创建 (启动server之前)

我放到启动脚本run之前跑，是在主进程创建的(启动server之前)，也是一样的结果。
![image](https://user-images.githubusercontent.com/26949885/72046677-e04ff680-32f3-11ea-9c57-f280d000567e.png)

![image](https://user-images.githubusercontent.com/26949885/72046706-eb0a8b80-32f3-11ea-9f7a-211cd0bb8eb2.png)

使用的easyswoole3.3.2的框架。

**Comment by twose** [comment]
确认全局只有一个table实例

打印一下php memory usage, 看看是否为PHP内存上涨

**Comment by caichudong** [comment]
> 确认全局只有一个table实例
> 
> 打印一下php memory usage, 看看是否为PHP内存上涨

测试代码，只有一个swoole table，确认全局只有一个table单例。可以根据不同worker获取同一个table的行数确定，疑惑是操作同一个table，两个worker都占用了内存。
请看截图，test2接口，用于获取swoole table占用内存和进程内存
![image](https://user-images.githubusercontent.com/26949885/72049482-fc569680-32f9-11ea-8e6d-1b0eb95e5ae2.png)
![image](https://user-images.githubusercontent.com/26949885/72049502-05476800-32fa-11ea-9bfb-575cdff647c7.png)
![image](https://user-images.githubusercontent.com/26949885/72049517-11332a00-32fa-11ea-9961-b598cbd1973a.png)

php内存并无明显上涨，进程内存约为2M，swoole table 申请了43M左右的内存。

**Comment by twose** [comment]
忘记看版本了, 请升级到最新版再测试

**Comment by matyhtf** [comment]
请使用 ps 或者 top 进行观察，这里的内存 43M 全部为 shm，也就是多个进程共用一块内存，虽然每个进程看到的都是 43M，实际上多个进程复用的。
