### ISSUE TITLE
Is it possible to gzip file data when using Response->sendFile() ? 

### ISSUE THREAD

**Issue by osrec** [swoole/swoole-src#3081]
With `http_compression` enabled, I am successfully able to send responses with compressed JSON/HTML. 

However, if I use the sendFile() method to send a PDF, data appears to be sent to the client uncompressed.

```php
$filePath = '/path/to/file.pdf';
$response->sendfile($filePath);
```
Is there a way in which I can send compressed file data? Do I just compress it myself before sending and add the appropriate header to the response?

Thanks very much!

**Comment by twose** [comment]
`sendfile` is a syscall, It can send files directly to save memory
but you can't sell the cow and drink the milk.
if you want to compress the file, you must load the file to memory and then compress it, this way you can't get any from `sendfile`
