### ISSUE TITLE
Debugging and PHP7.4

### ISSUE THREAD

**Issue by nick-zh** [swoole/swoole-src#3082]
So far we have been able to debug with sdebug provided by @mabu233,
i have tried to provide a PR for xdebug 2.9 (which has `PHP:7.4` compatibility) but i failed.
Are there any plans to have debugging options for Swoole on `PHP:7.4` ?
Thanks in advance for the help & feedback guys

**Comment by deminy** [comment]
The Swoole team is considering to fork the repository and maintain it. We will post an update here once it's there. Thanks

**Comment by deminy** [comment]
@nick-zh could you please submit your PRs to https://github.com/swoole/sdebug ?

**Comment by deminy** [comment]
Sdebug has been forked. [A pull request](https://github.com/swoole/sdebug/pull/1) was made to merge changes from  `nick-zh:sdebug_2_9` but there were unresolved conflicts.

**Comment by nick-zh** [comment]
Thank you very much for the update @deminy , i will be busy for the next couple of weeks. I will get to it probably in March unless somebody gets it working before me
The branch i created was failing, i wanted mabu's feedback, since i am not that versed with xdebug anyway.

**Comment by nick-zh** [comment]
I will also open my second PR again, which adds the `xdebug:2.9` branch, since my PR is branched on `xdebug:2.9`, this is why there are conflicts, since the current default branch is `xdebug:2.7`

**Comment by nick-zh** [comment]
@deminy silly me, i cannot add a non-exsting branch to your sdebug fork since i am not a contributor, can maybe one of you guys create and push the current xdebug_2_9 branch to sdebug as well? thx a lot in advance :heart:

**Comment by deminy** [comment]
I was told that some Swoole team members were reviewing the changes. Since there are too many commits involved, it could take a while. Thanks

**Comment by nick-zh** [comment]
@deminy you can disregard the old pr, there are so many changes because the master is still xdebug_2_7 but my pr was based on xdebug_2_9. This is why i need you guys to copy the xdebug_2_9 branch from xdebug to sdebug and also create an sdebug_2_9 branch from xdebug_2_9 so i can start merge the changes again. I can't create a PR against branches that don't exist.
I am not sure if you need to review my PR against the master, i simply synced the newest xdebug changes from master.

**Comment by doubaokun** [comment]
@nick-zh `xdebug_2_9` is created and synced with Xdebug. Branch `sdebug_2_9` is also created.

**Comment by nick-zh** [comment]
@doubaokun thank you very much!

**Comment by doubaokun** [comment]
Closing this thread now.

**Comment by jobs-git** [comment]
why was it?

**Comment by nick-zh** [comment]
just as an update, the `sdebug_2_9` (https://github.com/swoole/sdebug) can now be used to debug with `php:7.4`
