### ISSUE TITLE
Deploy Swoole on Real Server

### ISSUE THREAD

**Issue by mrmarchone** [swoole/swoole-src#3089]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
i'm trying to build real time chat

2. What did you expect to see?
i need to make project working online in my vps

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
last version

5. What is your machine environment used (including version of kernel & php & gcc) ?
centOS 7

**Comment by jobs-git** [comment]
What are you asking?

**Comment by doubaokun** [comment]
@mrmarchone Please provide more details, I am closing this thread for now.

**Comment by mRamadan0101** [comment]
deploy in real server like amazon or digitalocean
after deployment can not connect with socket

**Comment by deminy** [comment]
We have Swoole based microservices running in AWS smoothly for months, so I doubt it's a bug in Swoole. And, without more technical details, the Swoole team and other community members can hardly give any useful suggestions. If you still experience the same issues and need help, please kindly open a new issue. Thanks

**Comment by ljfreelancer88** [comment]
Maybe he's trying to ask about deploying or creating a Swoole web service in `systemd` and reverse proxy it using NGINX.
