### ISSUE TITLE
Coredumop with this title WARNING swProcessPool_wait: worker#0 abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by FogoQueima** [swoole/swoole-src#3090]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
I tried to go up the simple swoole and call the configured port.

```
<?php
$server = new Swoole\Http\Server("127.0.0.1", 9501, SWOOLE_BASE);
$server->set(array(
    'worker_num' => 4, // The number of worker processes
    'daemonize' => true, // Whether start as a daemon process
	'log_level' => 0,
	'log_file' => '/tmp/swoole_teste.log',
	'pid_file' => '/tmp/swoole_teste.pid',
));

$server->on('Request', function ($request, $response) use ($server) {
    $tasks[0] = "hello world";
    $tasks[1] = ['data' => 1234, 'code' => 200];
    $result = $server->taskCo($tasks, 0.5);
    $response->end('Test End, Result: '.var_export($result, true));
});

$server->start();
```

and curl:
`curl -kvss 'http://127.0.0.1:9501'`

and the error:

> [2020-02-06 15:12:19 $86663.0]	WARNING	swProcessPool_wait: worker#0 abnormal exit, status=0, signal=11
> A bug occurred in Swoole-v4.4.15, please report it.
> The Swoole developers probably don't know about it,
> and unless you report it, chances are it won't be fixed.
> You can read How to report a bug doc before submitting any bug reports:
> >> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
> Please do not send bug reports in the mailing list or personal letters.
> The issue page is also suitable to submit feature requests.
> 

2. What did you expect to see?
"Hellow Word"

3. What did you see instead?
Coredump

4. What version of Swoole are you using (show your `php --ri swoole`)?

> swoole
> 
> Swoole => enabled
> Author => Swoole Team <team@swoole.com>
> Version => 4.4.15
> Built => Jan 31 2020 14:47:33
> coroutine => enabled
> kqueue => enabled
> cpu_affinity => enabled
> spinlock => enabled
> rwlock => enabled
> sockets => enabled
> pcre => enabled
> zlib => 1.2.11
> mutex_timedlock => enabled
> pthread_barrier => enabled
> mysqlnd => enabled
> async_redis => enabled
> 
> Directive => Local Value => Master Value
> swoole.enable_coroutine => On => On
> swoole.enable_library => On => On
> swoole.enable_preemptive_scheduler => Off => Off
> swoole.display_errors => On => On
> swoole.use_shortname => On => On
> swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (including version of kernel & php & gcc) ?

> root@free:~ # php -v
> PHP 7.3.13 (cli) (built: Jan  2 2020 01:30:34) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies

> root@free:~ # uname -a
> FreeBSD free.php.7 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  i386

**Comment by twose** [comment]
On my mac:

```
Warning: Swoole\Server::taskCo(): task method can't be executed without task worker
```

you should call `$server->set(['task_worker_num' => 4]);`
