### ISSUE TITLE
websocket不能设置package_max_length吗？

### ISSUE THREAD

**Issue by juminut** [swoole/swoole-src#3096]
package_max_length虽然设了，并且设置了成功，但是设置open_length_check=true和open_eof_check=true，但是都不生效。是websocket不支持吗？还是我的配置有问题呢？
设置如下：
[
        'open_http_protocol' => false,
		"open_mqtt_protocol"=> false,
        'open_eof_check' => true,// 当发现内存占用已超过package_max_length时，将直接丢弃此数据，并关闭连接
        'open_length_check' => true, //当发现包长度超过package_max_length，将直接丢弃此数据，并关闭连接，不会占用任何内存
		"open_websocket_protocol"=> true,
		"worker_num"=> 4, // 进程数
        'task_worker_num' => 4,
		"buffer_output_size"=> 10240,
		"max_connection"=> 1024,
        'daemonize' => false,
        'backlog' => 128,
        'user' => 'coding',

        'package_eof' => "\r\n", //设置EOF
        'package_max_length' => 5,// 设置最大数据包尺寸，单位为字节
        //'heartbeat_idle_time' => 300,//表示连接最大允许空闲的时间
        'heartbeat_check_interval' => 30000,//启用心跳检测，此选项表示每隔多久轮循一次，单位为秒，如果该连接在120秒内（heartbeat_idle_time未设置时默认为interval的两倍），没有向服务器发送任何数据，此连接将被强制关闭。
        'package_length_type' => 'N',
        'package_length_offset' => 8,
        'package_body_offset' => 16,
    ]

{
	"setting": {
		"open_http_protocol": true,
		"open_mqtt_protocol": false,
		"open_eof_check": false,
		"open_length_check": false,
		"open_websocket_protocol": true,
		"worker_num": 4,
		"task_worker_num": 4,
		"buffer_output_size": 10240,
		"max_connection": 1024,
		"daemonize": false,
		"backlog": 128,
		"user": "coding",
		"package_eof": "\r\n",
		"package_max_length": 5,
		"heartbeat_check_interval": 30000,
		"package_length_type": "N",
		"package_length_offset": 8,
		"package_body_offset": 16
	},
	"connections": {},
	"host": "0.0.0.0",
	"port": 9502,
	"type": 1,
	"mode": 2,
	"ports": [{
		"host": "0.0.0.0",
		"port": 9502,
		"type": 1,
		"sock": 4,
		"setting": {
			"open_http_protocol": false,
			"open_mqtt_protocol": false,
			"open_eof_check": true,
			"open_length_check": true,
			"open_websocket_protocol": true,
			"worker_num": 4,
			"task_worker_num": 4,
			"buffer_output_size": 10240,
			"max_connection": 1024,
			"daemonize": false,
			"backlog": 128,
			"user": "coding",
			"package_eof": "\r\n",
			"package_max_length": 5,
			"heartbeat_check_interval": 30000,
			"package_length_type": "N",
			"package_length_offset": 8,
			"package_body_offset": 16
		},
		"connections": {}
	}],
	"master_pid": 14530,
	"manager_pid": 14531,
	"worker_id": 4,
	"taskworker": true,
	"worker_pid": 14534
}

**Comment by matyhtf** [comment]
package_max_length 最小值为 `64K`

**Comment by juminut** [comment]
设置了package_max_length =65536后，open_length_check=true和open_eof_check=true，还是不生效。

**Comment by huanghantao** [comment]
@juminut 你是不是希望把`hello\r\n\world\r\n`拆分为`hello`和`world`。如果是的话，可以试一试在配置中加入：

```php
$serv->set([
    'open_eof_split' => true,
]);
```

**Comment by juminut** [comment]
不，我是为了防止传大数据量的数据的攻击。所以限制下最大允许大小

**Comment by juminut** [comment]
所以想设置open_length_check=true，来限制下
