### ISSUE TITLE
Closing websocket connection inside a process

### ISSUE THREAD

**Issue by akrz** [swoole/swoole-src#3104]
**1. What did you do? If possible, provide a simple script for reproducing the error.**
I'm trying to handle the close connection of a websocket when the user closes the browser tab or refresh the page.
First I tried to catch that client event with the 'close' event but is never fired when the browser tab or a page refresh is done. So currently I'm using the response of the push method (if its false I want to close the connection)

```php
$server->on('message', static function (swoole_websocket_server $server, $frame) use ($accounts) {
    $requestData = JSON::decode($frame->data);
    echo "\nGetting data...\n";

    foreach ($accounts as $account) {
        $process = new \Swoole\Process(function ($worker) use ($requestData, $account, $server, $frame) {
            echo "[child $worker->pid] started\n";
            $worker->name('child process '. $worker->pid);
            try {
                $data = getData($requestData, $account);

                $res = $server->push($frame->fd, JSON::encode($data));
                var_dump($res);
                if (!$res) {
                    $server->close($frame->fd); // this wont close the websocket connection
                }
                $worker->exit(0);
            } catch (Exception $e) {
                echo "\nERROR from Account {$account}. {$e->getMessage()}\n";
            }
        });

        $pid = $process->start();
        $childProcesses[(string)$pid] = $process;
    }

    $workerNum = count($vendorAccounts);
    for ($i = 0; $i < $workerNum; $i++) {
        \Swoole\Process::wait(true);
    }

    $server->close($frame->fd);
});

$server->on('close', function($ser, $fd) {
    echo "\nclient {$fd} CLOSED\n";
});
```

**2. What did you expect to see?**
I expect that the 'close' event being fired, so I can handle and kill all the child processes

**3. What did you see instead?**
close event is never fired. It seems like I can't close the server connection inside a process.

**4. What version of Swoole are you using (show your `php --ri swoole`)?**
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.15
Built => Jan 22 2020 10:23:44
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

**5. What is your machine environment used (including version of kernel & php & gcc) ?**
OS: Ubuntu 18.04.01
Kernel: 5.1.21-050121-generic
PHP: 7.3.14-6+ubuntu18.04.1+deb.sury.org+1
GCC: 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**Comment by twose** [comment]
onClose event is triggered based on the dispatch_mode, and your code is illegal
you can fork child process and let it send some messages to its parent but you can not share resources between them
