### ISSUE TITLE
[Question] Determining Swoole\Table size

### ISSUE THREAD

**Issue by ValiDrv** [swoole/swoole-src#3109]
Please answer these questions before submitting your issue. Thanks!

**1.** What did you do? If possible, provide a simple script for reproducing the error.

How can we determine the **minimum SwooleTable size needed** if we know in advance the number of rows and the columns?

```
// Example
$rowSize = (sizes: 8+8+16+256) + (column label: 2+6+4+11) + overhead ??;
$rowCount = 1 to 1.000.000.000; // comes from a config on startup

$table = new Swoole\Table($rowSize*$rowCount); // 64/128/256/n*2
$table->column('id', Swoole\Table::TYPE_INT);
$table->column('number', Swoole\Table::TYPE_INT);
$table->column('name', Swoole\Table::TYPE_STRING, 16);
$table->column('description', Swoole\Table::TYPE_STRING, 256);
```

**4.** What version of Swoole are you using (show your `php --ri swoole`)?
```
Version => 4.4.13RC2
Built => Feb 11 2020 20:50:11
```

**5.** What is your machine environment used (including version of kernel & php & gcc) ?

```
php --version
PHP 7.4.0 (cli) (built: Nov 28 2019 20:31:53) ( NTS )
gcc --version
gcc (Debian 8.3.0-6) 8.3.0
```

**Comment by twose** [comment]
https://wiki.swoole.com/wiki/page/254.html

Here is the result of Google translation:

Capacity calculation
-----
The bottom layer of `Table` is a` HashTable` data structure built on shared memory. The maximum number of rows in $ size determines the total number of rows in HashTable. Because `Table` is above shared memory, it cannot be dynamically expanded. The `$size` must be set before creation.

The total number of rows that `Table` can store depends on the` Key` collision rate of the data. If the conflict rate exceeds `20%`, the reserved `hash` conflicting memory block capacity is insufficient, and an` Unable to allocate memory` error will be reported, and `false` will be returned, and the storage fails.

**Comment by ValiDrv** [comment]
`function Table->__construct(int $size, float $conflict_proportion = 0.2)`
According to the google translate, `$size` should be the number of rows, but that is wrong.

With a `$conflict_proportion` of 0.2 (default), it will fail for sizes: **45-64** and **92-98**

1. What did you do? If possible, provide a simple script for reproducing the error.
```
<?php

for ($rows = 1; $rows < 100; $rows++) {
    # Create table
    $table = new Swoole\Table($rows, 0.2);
    $table->column('id', Swoole\Table::TYPE_INT);
    $table->column('number', Swoole\Table::TYPE_INT);
    $table->column('name', Swoole\Table::TYPE_STRING, 16);
    $table->column('description', Swoole\Table::TYPE_STRING, 256);
    $table->create();
    # Add data
    for ($i = 0; $i < $rows; $i++) {
        $r = $table->set($i, [
            'id'          => $i,
            'number'      => $i * 2,
            'name'        => bin2hex(openssl_random_pseudo_bytes(8)),
            'description' => bin2hex(openssl_random_pseudo_bytes(128)),
        ]);
    }

    # Check if the rows were added
    $count         = $table->count();
    # Cleanup
    $table->destroy();
    if ($count !== $t) {
        echo "\n $rows != $count \t MISMATCH -- ";
        # break;
    } else {
        echo "\n $rows \t OK --";
    }
}
```
2. What did you expect to see?
` $rows 	 OK --` for 0-n

3. What did you see instead?
` $rows != $count 	 MISMATCH -- PHP Warning:  Swoole\Table::set(): failed to set...`

**Notes:** 

- The number/labels of the table columns have no effect on how many rows it can hold.
- Google translate of https://wiki.swoole.com/wiki/page/254.html comments have a few people asking the same thing.
- The table key can be 1 to 62 characters, and that length has no effect on the number of rows it can hold.
- If I set the `$conflict_proportion` to 1, it seems that I can set the `$size` to the total number of rows and all values are set (up to 10k), but what exactly does it do?

**So the question stands:**
How can I calculate the `$size` and what exactly is `$conflict_proportion`?

**Comment by matyhtf** [comment]
Table uses a fixed size memory, you can use getMemorySize to get the memory length

```php
$rowSize = (sizes: 8+8+16+256) + (column label: 2+6+4+11) + overhead ??;
$rowCount = 1 to 1.000.000.000; // comes from a config on startup

$table = new Swoole\Table($rowSize*$rowCount); // 64/128/256/n*2
$table->column('id', Swoole\Table::TYPE_INT);
$table->column('number', Swoole\Table::TYPE_INT);
$table->column('name', Swoole\Table::TYPE_STRING, 16);
$table->column('description', Swoole\Table::TYPE_STRING, 256);

$table->getMemorySize();
```
