### ISSUE TITLE
max_request on swoole_http_server not working

### ISSUE THREAD

**Issue by Atriedes** [swoole/swoole-src#311]
Hi,

I discovered that worker can auto restarted when reached certain amount of request. I look this article http://wiki.swoole.com/wiki/page/300.html (im using google translate) by setting max_request it will automatically restart worker but it seem not work in swoole_http_server.

here is output that prove worker not restarted, it hit php memory max limit

```
jowy@Rainwall:~/Project/swoole-server$ php index.php 
server started on http://localhost:8000
1.7.17
PHP Fatal error:  Allowed memory size of 16777216 bytes exhausted (tried to allocate 8203 bytes) in /home/jowy/Project/swoole-server/vendor/zendframework/zend-diactoros/src/Stream.php on line 268
```

My swole configuration

```
"server.config" => [
            "worker_num" => 4,
            "max_request" => 1
        ]
```

As I understand it will automatically restart worker after receive 1 request, Since worker is restarted it will release its memory.

related issue #310

**Comment by matyhtf** [comment]
Fixed, thank you.
