### ISSUE TITLE
[Question] Process::signal() doesn't work sometime in centos

### ISSUE THREAD

**Issue by Littlesqx** [swoole/swoole-src#3129]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```php
<?php

use Swoole\Process;
use Swoole\Timer;

Timer::tick(2000, function () {
    echo "master is running\n";
});

$process = new Process(function () {
    Timer::tick(2000, function () {
        echo getmypid() . " is running\n";
    });
    Process::signal(SIGUSR1, function () {
        echo getmypid() . " recv SIGUSR1\n";
    });
}, false, 2, true);

$process->start();


Process::signal(SIGCHLD, function () {
    while ($ret = Swoole\Process::wait(false)) {
        echo "PID={$ret['pid']}\n";
    }
});
```

2. What did you expect to see?

kill -USR1 ${sub-process pid}, and then output "${sub-process pid} recv SIGUSR1" in console.

3. What did you see instead?

When I repeat running `kill -USR1 ${sub-process pid}`, console will show warning log as follow:

```
[2020-02-24 17:56:35 @20264.0]	WARNING	swSignalfd_onSignal(:294): read from signalfd failed, Error: Resource temporarily unavailable[11]
```

The sub-process even quits.

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.14
Built => Feb 11 2020 23:24:02
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

PHP 7.3.11 (cli) (built: Nov  5 2019 17:45:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies

gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

CentOS Linux release 7.7.1908 (Core)

**Comment by twose** [comment]
@Littlesqx 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by Littlesqx** [comment]
==22648== Invalid read of size 8
==22648==    at 0x12FC0157: DecExecCtxCount (fork.cc:88)
==22648==    by 0x12FC0157: grpc_core::Fork::DoDecExecCtxCount() (fork.cc:197)
==22648==    by 0x12FC1612: DecExecCtxCount (fork.h:59)
==22648==    by 0x12FC1612: ~ExecCtx (exec_ctx.h:128)
==22648==    by 0x12FC1612: grpc_shutdown_internal_locked() (init.cc:190)
==22648==    by 0x12FC1841: grpc_shutdown_blocking (init.cc:231)
==22648==    by 0x12FBBBF4: postfork_child (php_grpc.c:183)
==22648==    by 0x76B6A5D: fork (in /usr/lib64/libc-2.17.so)
==22648==    by 0x11D21B7C: swoole_fork (base.c:203)
==22648==    by 0x11DAAD86: zim_swoole_process_start(_zend_execute_data*, _zval_struct*) (swoole_process.cc:810)
==22648==    by 0x8C5237: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:984)
==22648==    by 0x8C5237: execute_ex (zend_vm_execute.h:55493)
==22648==    by 0x8C5DD7: zend_execute (zend_vm_execute.h:60889)
==22648==    by 0x840CF3: zend_execute_scripts (zend.c:1568)
==22648==    by 0x7E494F: php_execute_script (main.c:2639)
==22648==    by 0x8C8174: do_cli (php_cli.c:997)
==22648==  Address 0x34183930 is 96 bytes inside a block of size 104 free'd
==22648==    at 0x4C2AF9D: free (vg_replace_malloc.c:540)
==22648==    by 0x12FC0036: Delete<grpc_core::internal::ExecCtxState> (memory.h:58)
==22648==    by 0x12FC0036: grpc_core::Fork::GlobalShutdown() (fork.cc:182)
==22648==    by 0x12FC1584: grpc_shutdown_internal_locked() (init.cc:190)
==22648==    by 0x12FC1841: grpc_shutdown_blocking (init.cc:231)
==22648==    by 0x12FBBBF4: postfork_child (php_grpc.c:183)
==22648==    by 0x76B6A5D: fork (in /usr/lib64/libc-2.17.so)
==22648==    by 0x11D21B7C: swoole_fork (base.c:203)
==22648==    by 0x11DAAD86: zim_swoole_process_start(_zend_execute_data*, _zval_struct*) (swoole_process.cc:810)
==22648==    by 0x8C5237: ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (zend_vm_execute.h:984)
==22648==    by 0x8C5237: execute_ex (zend_vm_execute.h:55493)
==22648==    by 0x8C5DD7: zend_execute (zend_vm_execute.h:60889)
==22648==    by 0x840CF3: zend_execute_scripts (zend.c:1568)
==22648==    by 0x7E494F: php_execute_script (main.c:2639)
==22648==  Block was alloc'd at
==22648==    at 0x4C29EA3: malloc (vg_replace_malloc.c:309)
==22648==    by 0x12FBD4FE: gpr_malloc (alloc.cc:57)
==22648==    by 0x12FBFF79: New<grpc_core::internal::ExecCtxState> (memory.h:36)
==22648==    by 0x12FBFF79: grpc_core::Fork::GlobalInit() (fork.cc:175)
==22648==    by 0x12FC1321: grpc_init (init.cc:135)
==22648==    by 0x12FBBD6D: zm_activate_grpc (php_grpc.c:400)
==22648==    by 0x845E5F: zend_activate_modules (zend_API.c:2611)
==22648==    by 0x7E3185: php_request_startup (main.c:1829)
==22648==    by 0x8C7952: do_cli (php_cli.c:968)
==22648==    by 0x45284E: main (php_cli.c:1389)
==22648==
==22648== Warning: client switching stacks?  SP change: 0x1ffeffca60 --> 0x35eacff8
==22648==          to suppress, use: --max-stackframe=136517581416 or greater
==22648== Warning: client switching stacks?  SP change: 0x35eacff0 --> 0x1ffeffca60
==22648==          to suppress, use: --max-stackframe=136517581424 or greater
==22644== Warning: client switching stacks?  SP change: 0x1ffeffe870 --> 0x35cabff8
==22644==          to suppress, use: --max-stackframe=136519690360 or greater
==22644== Warning: client switching stacks?  SP change: 0x35cabff0 --> 0x1ffeffe870
==22644==          to suppress, use: --max-stackframe=136519690368 or greater
==22648== Warning: client switching stacks?  SP change: 0x1ffeffc8d0 --> 0x362acff8
==22648==          to suppress, use: --max-stackframe=136513386712 or greater
==22648==          further instances of this message will not be shown.
==22644== Warning: client switching stacks?  SP change: 0x1ffeffe870 --> 0x360abff8
==22644==          to suppress, use: --max-stackframe=136515496056 or greater
==22644==          further instances of this message will not be shown.
==22648==
==22648== Process terminating with default action of signal 10 (SIGUSR1)
==22648==    at 0x7627607: kill (in /usr/lib64/libc-2.17.so)
==22648==    by 0x867C50: zend_signal_handler (zend_signal.c:207)
==22648==    by 0x867D2A: zend_signal_handler_defer (zend_signal.c:104)
==22648==    by 0x76273AF: ??? (in /usr/lib64/libc-2.17.so)
==22648==    by 0x7BCD9F4: pthread_cond_wait@@GLIBC_2.3.2 (in /usr/lib64/libpthread-2.17.so)
==22648==    by 0x12FBF011: gpr_cv_wait (sync_posix.cc:128)
==22648==    by 0x12FDEAB6: grpc_core::Executor::ThreadMain(void*) (executor.cc:246)
==22648==    by 0x12FC0DC2: grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::{lambda(void*)#1}::_FUN(void*) (thd_posix.cc:139)
==22648==    by 0x7BC9E64: start_thread (in /usr/lib64/libpthread-2.17.so)
==22648==    by 0x76EF88C: clone (in /usr/lib64/libc-2.17.so)
==22648==
==22648== HEAP SUMMARY:
==22648==     in use at exit: 5,515,059 bytes in 37,759 blocks
==22648==   total heap usage: 71,837 allocs, 34,078 frees, 25,773,959 bytes allocated
==22648==
==22648== LEAK SUMMARY:
==22648==    definitely lost: 31,011 bytes in 760 blocks
==22648==    indirectly lost: 416 bytes in 13 blocks
==22648==      possibly lost: 3,478,900 bytes in 26,823 blocks
==22648==    still reachable: 2,004,732 bytes in 10,163 blocks
==22648==                       of which reachable via heuristic:
==22648==                         stdstring          : 27,409 bytes in 769 blocks
==22648==         suppressed: 0 bytes in 0 blocks
==22648== Rerun with --leak-check=full to see details of leaked memory
==22648==
==22648== For counts of detected and suppressed errors, rerun with: -v
==22648== Use --track-origins=yes to see where uninitialised values come from
==22648== ERROR SUMMARY: 21566 errors from 104 contexts (suppressed: 0 from 0)
==22644==
==22644== Process terminating with default action of signal 2 (SIGINT)
==22644==    at 0x7627607: kill (in /usr/lib64/libc-2.17.so)
==22644==    by 0x867C50: zend_signal_handler (zend_signal.c:207)
==22644==    by 0x867D2A: zend_signal_handler_defer (zend_signal.c:104)
==22644==    by 0x76273AF: ??? (in /usr/lib64/libc-2.17.so)
==22644==    by 0x76EFE62: ??? (in /usr/lib64/libc-2.17.so)
==22644==    by 0x11D51045: swReactorEpoll_wait(_swReactor*, timeval*) (epoll.cc:221)
==22644==    by 0x11D80DC0: php_swoole_event_wait (swoole_event.cc:295)
==22644==    by 0x11D80E6A: zif_swoole_event_wait (swoole_event.cc:775)
==22644==    by 0x11D80E6A: zif_swoole_event_rshutdown(_zend_execute_data*, _zval_struct*) (swoole_event.cc:783)
==22644==    by 0x83349E: zend_call_function (zend_execute_API.c:770)
==22644==    by 0x833AA4: _call_user_function_ex (zend_execute_API.c:598)
==22644==    by 0x748B34: user_shutdown_function_call (basic_functions.c:5060)
==22644==    by 0x850022: zend_hash_apply (zend_hash.c:1689)
==22644==
==22644== HEAP SUMMARY:
==22644==     in use at exit: 5,513,307 bytes in 37,750 blocks
==22644==   total heap usage: 71,702 allocs, 33,952 frees, 27,776,962 bytes allocated
==22644==
==22644== LEAK SUMMARY:
==22644==    definitely lost: 30,899 bytes in 758 blocks
==22644==    indirectly lost: 400 bytes in 12 blocks
==22644==      possibly lost: 3,479,600 bytes in 26,830 blocks
==22644==    still reachable: 2,002,408 bytes in 10,150 blocks
==22644==                       of which reachable via heuristic:
==22644==                         stdstring          : 27,409 bytes in 769 blocks
==22644==         suppressed: 0 bytes in 0 blocks
==22644== Rerun with --leak-check=full to see details of leaked memory
==22644==
==22644== For counts of detected and suppressed errors, rerun with: -v
==22644== Use --track-origins=yes to see where uninitialised values come from
==22644== ERROR SUMMARY: 21566 errors from 103 contexts (suppressed: 0 from 0)

**Comment by Littlesqx** [comment]
测试了一下，禁用 grpc 扩展后好了

**Comment by Littlesqx** [comment]
Conflict with grpc extension
