### ISSUE TITLE
Http 服务器无法正确处理静态文件

### ISSUE THREAD

**Issue by kiss291323003** [swoole/swoole-src#3131]
# 问题描述
开启静态处理器时，无法正确处理空文件，和其他非常见拓展名文件，都会导致认定文件不存在。
## 复现代码
```php
<?php
$http = new swoole_http_server("127.0.0.1", 9501);
$http->set([
    'document_root'            => __DIR__.'/',
    'enable_static_handler'    => true,
]);
$http->on("request", function ($request, $response) {
    $response->end("swoole hello");
});

$http->start();
```
### a.txt
a.txt 内容为 hello
### empty.txt
empty.txt为空text文件
### moc.moc
moc.moc内容为 this is moc.moc

**Comment by twose** [comment]
Fixed via https://github.com/swoole/swoole-src/pull/3084

**Comment by kiss291323003** [comment]
然鹅、刚刚安装了4.4.16、、、并没有fix .
对moc.moc

moc.moc内容为 this is moc.moc

这个文件的测试，依旧是没有走静态处理器。也就是对位置拓展文件的处理有问题

**Comment by twose** [comment]
https://github.com/swoole/swoole-src/pull/3134
