### ISSUE TITLE
在php中建立swoole客户端，给swoole服务端发送数据，经常出现错误

### ISSUE THREAD

**Issue by wo642436249** [swoole/swoole-src#3136]
弄一堆英文，搞的挺高端的啊！
    public function allcode()
    {
        $client = new \swoole_client(SWOOLE_SOCK_TCP | SWOOLE_KEEP);

        if (!$client->connect('127.0.0.1', 9683)) {
            exit("connect failed. Error: {$client->errCode}\n");
        }
        $arr = ['cpbd', 'gbgd', 'fhrz'];
        $newcode = $this->redis->lrange('NewF10:newcode', 0, -1);
        $all_code = array_merge($this->allstock, $newcode);
        $data = [
            'controller' => 'Ften',
            'type' => 'all_code_all_page',
            'codes' => $all_code,
            'functions' => $arr
        ];
        $client->send(json_encode($data) . "###");
        return $client->recv();
        $client->close();
    }

经常报错，但不是每次都报错

**Comment by twose** [comment]
请按照模板提问
