### ISSUE TITLE
使用httpServer无法启动http2

### ISSUE THREAD

**Issue by ren-jimmy** [swoole/swoole-src#3137]
1.我使用的是swoole4.4.16，同时编译时已启用--enable-http2 
![image](https://user-images.githubusercontent.com/25098996/75321534-ec941100-58ab-11ea-9b6d-5089d9dabd2d.png)

2.使用浏览器查看header，协议还是用http1.1
![image](https://user-images.githubusercontent.com/25098996/75321709-51e80200-58ac-11ea-8027-0ccedd442f81.png)

**Comment by Yurunsoft** [comment]
浏览器不支持无ssl的http2，建议用http2 client尝试
