### ISSUE TITLE
http server中使用tcp client访问该http server,出现段错误

### ISSUE THREAD

**Issue by titrxw** [swoole/swoole-src#3142]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```
<?php
define('RUNTIME_PATH', '/tmp');
$http = new Swoole\Http\Server("127.0.0.1", 9501);
$http->set([
	'pid_file' => '/tmp/swoole.pid',
	'max_request' => 10000,
	'worker_num' => 2,
	'pname' => 'w7-rangine',
	'daemonize' => 0,
	'dispatch_mode' => 3,
	'log_file' => RUNTIME_PATH . '/run.log',
	'log_level' => 0,
	'request_slowlog_timeout' => 2,
	'request_slowlog_file' => RUNTIME_PATH . '/slow.log',
	'trace_event_worker' => true,
	'upload_tmp_dir' => RUNTIME_PATH ,
	'document_root' => RUNTIME_PATH,
	'enable_static_handler' => true,
	'task_tmpdir' => RUNTIME_PATH ,
	'open_http2_protocol' => false,
	'mode' => SWOOLE_PROCESS,
	'sock_type' => SWOOLE_SOCK_TCP
]);
$http->on('request', function ($request, $response) {
	$client = new Swoole\Client(SWOOLE_SOCK_TCP);
	if (!$client->connect('127.0.0.1', 9501, -1)) {
		exit("connect failed. Error: {$client->errCode}\n");
	}
	$client->send('{"cmd":"\/rpc-server?re=asd&sd=34","data":{"test":"1"}}');
	echo $client->recv();
	$client->close();
	return 1;
});
$http->start();
```
2. What did you expect to see?
HTTP/1.1 400 Bad Request

3. What did you see instead?
段错误

4. What version of Swoole are you using (show your `php --ri swoole`)?

- Swoole => enabled
- Author => Swoole Team <team@swoole.com>
- Version => 4.4.16
- Built => Feb 21 2020 14:58:56
- coroutine => enabled
- epoll => enabled
- eventfd => enabled
- signalfd => enabled
- cpu_affinity => enabled
- spinlock => enabled
- rwlock => enabled
- openssl => OpenSSL 1.1.1d  10 Sep 2019
- pcre => enabled
- mutex_timedlock => enabled
- pthread_barrier => enabled
- futex => enabled
- async_redis => enabled
- 
- Directive => Local Value => Master Value
- swoole.enable_coroutine => On => On
- swoole.enable_library => On => On
- swoole.enable_preemptive_scheduler => Off => Off
- swoole.display_errors => On => On
- swoole.use_shortname => On => On
- swoole.unixsock_buffer_size => 8388608 => 8388608
- 

5. What is your machine environment used (including version of kernel & php & gcc) ?
PHP 7.3.14-6+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb  5 2020 16:51:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14-6+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**Comment by twose** [comment]
@titrxw 首先感谢您的BUG反馈, 我是无情的自动回复机器人，请您快速确认以下几点来帮助我们定位您的问题：
1. 如你是手动升级编译的而不是首次编译, 确保你在编译前运行`make clean`清理了上次编译的内容

2. 如你使用的是Linux系统, 使用以下命令运行你的程序, 以能够复现BUG的方式操作你的程序, 并在程序运行一定时间后, 将位于/tmp目录的valgrind.log日志内容贴在此issue中

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. 如你使用的是macOS系统，将无法使用valgrind, 请提供能够复现问题BUG的PHP代码

4. 若以上需求都无法满足，请您在此表明, 我们将快速接入人工处理

**Comment by twose** [comment]
由于宏展开顺序导致的问题 已修复

可以调高日志级别(`log_level`)来规避此问题 (触发BUG的为调试日志(`SWOOLE_LOG_TRACE`), 默认是`SWOOLE_LOG_INFO`级别)
