### ISSUE TITLE
数据库连接闲置8小时被断后，Connection::close会抛出没有捕获的throwable

### ISSUE THREAD

**Issue by konglingdashi** [swoole/swoole-src#3143]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

数据库连接闲置8小时被断后，Connection::close会抛出没有捕获的throwable，
具体是这句：
$this->pdo = null

2. What did you expect to see?

应该正常关闭，然后创建新的连接

3. What did you see instead?

可以考虑在Connection::close里边对这句话try一下。之后可以继续执行，不会有任何影响。
这种情况在假期或者系统初期访问人少的情况下，是必报的错误，所以需要处理一下。

4. What version of Swoole are you using (show your `php --ri swoole`)?

2.0.8

5. What is your machine environment used (including version of kernel & php & gcc) ?

所有版本都会报些错误

**Comment by twose** [comment]
版本太低, 而且不知道你在说什么
