### ISSUE TITLE
[Question] 编译安装swoole4.4.16，报错swoole-src/src/protocol/ssl.cc:210:33: error: invalid conversion from ‘void (*)()’ to ‘void (*)(int, int, const char*, int)’ [-fpermissive]

### ISSUE THREAD

**Issue by JinPengCN** [swoole/swoole-src#3154]
操作系统 ubuntu 18.04
gcc 版本7.5.0
PHP版本7.4.3
swoole版本4.4.16
报错：
/soft/swoole/swoole-src/src/protocol/ssl.cc: In function ‘void swSSL_init_thread_safety()’:
/soft/swoole/swoole-src/src/protocol/ssl.cc:210:33: error: invalid conversion from ‘void (*)()’ to ‘void (*)(int, int, const char*, int)’ [-fpermissive]
     CRYPTO_set_locking_callback((void (*)()) swSSL_lock_callback);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/comp.h:5:0,
                 from /usr/include/openssl/ssl.h:149,
                 from /soft/swoole/swoole-src/include/swoole.h:613,
                 from /soft/swoole/swoole-src/src/protocol/ssl.cc:17:
/usr/include/openssl/crypto.h:437:6: note:   initializing argument 1 of ‘void CRYPTO_set_locking_callback(void (*)(int, int, const char*, int))’
 void CRYPTO_set_locking_callback(void (*func) (int mode, int type,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:310: recipe for target 'src/protocol/ssl.lo' failed
make: *** [src/protocol/ssl.lo] Error 1

求解答，谢谢

**Comment by twose** [comment]
可能是openssl版本太低 新版本的openssl这个宏是无用的 建议更新一下试试

**Comment by JinPengCN** [comment]
> 可能是openssl版本太低 新版本的openssl这个宏是无用的 建议安装一个新版本的openssl 在编译swoole时指定openssl的路径

openssl版本是1.1.1
