### ISSUE TITLE
phpize 报错

### ISSUE THREAD

**Issue by ezqliin** [swoole/swoole-src#3156]
php版本 7.2.26
操作系统centos7
swoole 4.4.16

Package libtool-2.4.2-22.el7_3.x86_64 already installed and latest version
Package automake-1.13.4-3.el7.noarch already installed and latest version
Package autoconf-2.69-11.el7.noarch already installed and latest version

需要的软件都装了，但是在执行phpize的时候会报措如下：

[root@lnp swoole]# phpize
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
unknown channel 9: _AC_PROG_LIBTOOL is expanded from...
aclocal.m4:3326: AC_PROG_LIBTOOL is expanded from...
configure.ac:149: the top level])
obsolete at /usr/share/autoconf/Autom4te/Channels.pm line 638.
	Autom4te::Channels::msg('9: _AC_PROG_LIBTOOL is expanded from...\x{a}aclocal.m4:3326: AC_P...', 'configure.ac:149', 'warning: The macro `AC_LANG_RESTORE\' is obsolete.\x{a}You should...', 'partial', 1) called at /usr/bin/autom4te line 1026

求问解决办法，谢谢

**Comment by huanghantao** [comment]
@ezqliin 这个问题我前几天遇到过，你是不是在虚拟机里面跑的`phpize`？

**Comment by ezqliin** [comment]
@huanghantao 是的，mac下用vagrant里跑的centos。

**Comment by huanghantao** [comment]
@ezqliin 你下载的`swoole-src`存放的目录不对。我当时遇到这个问题是因为我把`swoole-src`下载在了本机挂载在虚拟机的一个目录里面。估计你也是把`swoole-src`下载在了错误的目录里。

**Comment by huanghantao** [comment]
@ezqliin 你把`swoole-src`移到虚拟机的`/tmp`目录下执行`phpize`试试。

**Comment by ezqliin** [comment]
@huanghantao  卧槽 牛逼！我想起来了，我上次是在虚拟机里执行的git 然后拉取的目录是虚拟机里的目录，这次是在共享目录中操作的，现在可以了！感谢！！！

**Comment by huanghantao** [comment]
@ezqliin 不客气。这个问题确实挺坑的。
