### ISSUE TITLE
Swoole\WebSocket\Server 接收到数据和预期不一致

### ISSUE THREAD

**Issue by 0xffc2** [swoole/swoole-src#3159]
##  测试过程
前端用websocket send二进制流
本地测试没有任何问题 
在服务器上面测试通过不了 试过了ubuntu 18.04 , Centos8 x64 都有同样问题
上传的测试文件 [gzdata](https://github.com/0xffc2/swoole_websocket_issue/raw/master/gzdata)  md5:f600aaf99d8c3ca1a0154039892d2394 length:1226847 (1.16m)

其他测试相关文件
[https://github.com/0xffc2/swoole_websocket_issue](https://github.com/0xffc2/swoole_websocket_issue)

[valgrind.log](https://github.com/0xffc2/swoole_websocket_issue/blob/master/valgrind.txt)

上传两次文件 服务器返回

    string(68) "uncompress error md5:0284c74609a052b98e2ae0ed5bb6d325 length:1226847"
    string(68) "uncompress error md5:463289c346de53abea63bdd1ba47d19f length:2453694"

服务器环境

    gcc version 8.3.1 20190507 (Red Hat 8.3.1-4) (GCC)
    
    Linux iZm5e6vlyyrn5ta7pop9gbZ 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
    
    PHP 7.2.11 (cli) (built: Oct  9 2018 15:09:36) ( NTS )
    Copyright (c) 1997-2018 The PHP Group
    Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    
    swoole
    
    Swoole => enabled
    Author => Swoole Team <team@swoole.com>
    Version => 4.5.0-alpha
    Built => Mar  3 2020 23:43:19
    coroutine => enabled
    epoll => enabled
    eventfd => enabled
    signalfd => enabled
    cpu_affinity => enabled
    spinlock => enabled
    rwlock => enabled
    pcre => enabled
    zlib => 1.2.11
    mutex_timedlock => enabled
    pthread_barrier => enabled
    futex => enabled
    async_redis => enabled
    
    Directive => Local Value => Master Value
    swoole.enable_coroutine => On => On
    swoole.enable_library => On => On
    swoole.enable_preemptive_scheduler => Off => Off
    swoole.display_errors => On => On
    swoole.use_shortname => On => On
    swoole.unixsock_buffer_size => 8388608 => 8388608
    

```php
class UploadServer
{
	public function __construct()
	{
		$this->test();

		$this->server = new Swoole\WebSocket\Server('0.0.0.0', 50000);
		$this->server->on('message', [$this, 'onMessage']);
		$this->server->start();
	}

	public function test()
	{
		$data = file_get_contents('gzdata');
		var_dump(md5($data) == 'f600aaf99d8c3ca1a0154039892d2394');
		if ($data = gzuncompress($data)) {
			var_dump(md5($data) == 'a3f4c0bc2ac78b4ed71307eed6ec28a8');
		}
	}

	public function onMessage(Swoole\WebSocket\Server $server, Swoole\WebSocket\Frame $frame)
	{
		$result = "uncompress success";
		if ($frame->data) {
			if (!@gzuncompress($frame->data)) {
				$result = "uncompress error md5:" . md5($frame->data) . " length:" . strlen($frame->data);
				var_dump($result);
			}
		} else {
			$result = "upload error";
		}

		$server->push($frame->fd, $result);
		$server->disconnect($frame->fd);
	}
}

new UploadServer;
```

```html
<!DOCTYPE html>
<html>
<head>
	<title>upload</title>
</head>
<body>
	<a href="gzdata">gzdata</a>
	<h3>拖拽上传</h3>
<script>
    document.ondrop = document.ondragover = function (event) {
        event.preventDefault();
    };

    document.body.parentNode.ondrop = function (event) {
        upload(event.dataTransfer.files[0]);
    };

    function upload(file) {
    	var ws = new WebSocket('ws://'+document.location.host+':50000');
    	ws.onmessage = function (e) {
            console.log(e.data);
        };

        ws.onerror = ws.onclose = function () {
            console.log('onclose');
        };

        ws.onopen = () => {
            console.log('onopen');

            var fileReader = new FileReader();
            fileReader.onload = function () {
                ws.send(fileReader.result);
            };
            fileReader.readAsArrayBuffer(file);
        };
    }
</script>
</body>
</html>
```

**Comment by 0xffc2** [comment]
还还有几种不确定情况 服务器会直接挂掉

```
# PHP Fatal error:  Uncaught Swoole\Exception: failed to listen server port[0.0.0.0:50000], Error: Address already in use[98] in /var/www/static/upload.php:20
Stack trace:
#0 /var/www/static/upload.php(20): Swoole\Server->__construct('0.0.0.0', 50000)
#1 /var/www/static/upload.php(51): UploadServer->__construct()
#2 {main}
  thrown in /var/www/static/upload.php on line 20
```

**Comment by huanghantao** [comment]
@0xffc2 你的这个客户端怎么跑？没明白

**Comment by 0xffc2** [comment]
@huanghantao 把下载的 gzdata 拖到网页里面就上传了 按F12可以看返回消息

**Comment by twose** [comment]
> 上传时还还有几种不确定情况 服务器会直接挂掉
> 
> ```
> # PHP Fatal error:  Uncaught Swoole\Exception: failed to listen server port[0.0.0.0:50000], Error: Address already in use[98] in /var/www/static/upload.php:20
> Stack trace:
> #0 /var/www/static/upload.php(20): Swoole\Server->__construct('0.0.0.0', 50000)
> #1 /var/www/static/upload.php(51): UploadServer->__construct()
> #2 {main}
>   thrown in /var/www/static/upload.php on line 20
> ```

这个错误很明显是你的端口被占用了

**Comment by twose** [comment]
根据valgrind日志4.5确实有内存错误 感谢反馈 我们会跟踪修复

**Comment by 0xffc2** [comment]
> > 上传时还还有几种不确定情况 服务器会直接挂掉
> > ```
> > # PHP Fatal error:  Uncaught Swoole\Exception: failed to listen server port[0.0.0.0:50000], Error: Address already in use[98] in /var/www/static/upload.php:20
> > Stack trace:
> > #0 /var/www/static/upload.php(20): Swoole\Server->__construct('0.0.0.0', 50000)
> > #1 /var/www/static/upload.php(51): UploadServer->__construct()
> > #2 {main}
> >   thrown in /var/www/static/upload.php on line 20
> > ```
> 
> 这个错误很明显是你的端口被占用了

这个我知道, 并不是在启动服务器的时候报错, 而是在上传时有一定几率报这个错
