### ISSUE TITLE
CPU_SET doesn't always exists

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#317]
Hi,

Building RPM packages of swoole 1.7.18, I notice this issue in RHEL/CentOS 5

Buildtime:

    swoole_process.c:737: warning: implicit declaration of function 'CPU_ZERO'
    swoole_process.c:746: warning: implicit declaration of function 'CPU_SET'
    swoole_process.c:749: warning: implicit declaration of function 'sched_setaffinity'
    swoole_server.c:1330: warning: implicit declaration of function 'strndup'

Runtime:

    PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/swoole.so' - modules/swoole.so: undefined symbol: CPU_SET in Unknown on line 0

(in previous versions, arch need to be set to i686, as i386 was also broken)

I understand RHEL/CentOS 5 is really old.. more recent version (6 and 7) are ok.
So mostly, only for your information.

**Comment by matyhtf** [comment]
Your gcc version may be too low.

**Comment by remicollet** [comment]
>  Gcc 4.4 or later required

So, please, update the README ;)

**Comment by matyhtf** [comment]
Ok, I will update the readme at later. Thank you. 
:)
