### ISSUE TITLE
设置swoole.so后报错

### ISSUE THREAD

**Issue by zznan0o0** [swoole/swoole-src#3173]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
添加了swoole.so到php.ini之后报错了
PHP Warning:  PHP Startup: Unable to load dynamic library '../20180731/swoole' (tried: ../20180731/swoole (../20180731/swoole: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/../20180731/swoole.so (/usr/lib/php/20170718/../20180731/swoole.so: undefined symbol: zend_string_init_interned)) in Unknown on line 0

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?
php7.2 使用pecl安装的swoole版本忘记了没有指定应该是4.x

**Comment by huanghantao** [comment]
@zznan0o0 你的问题应该和这个一样#2722

**Comment by zznan0o0** [comment]
可以了，我再问一个问题7.4-dev怎么装啊ubuntu的apt里根本没这个包

**Comment by huanghantao** [comment]
@zznan0o0 源码安装

**Comment by zznan0o0** [comment]
@huanghantao 给个php7.4-dev的源码链接谢谢

**Comment by huanghantao** [comment]
@zznan0o0 https://www.php.net/releases/index.php

**Comment by zznan0o0** [comment]
。。。不是这个是php7.4的开发插件 不安装这个 就没有phpize 就安装不了swoole

**Comment by huanghantao** [comment]
@zznan0o0 你下载下来编译完里面就有。

**Comment by huanghantao** [comment]
@zznan0o0 这个问题到此结束，超出了`Swoole`项目。

**Comment by zznan0o0** [comment]
好的谢谢
