### ISSUE TITLE
tcp_server自定义进程如何关闭

### ISSUE THREAD

**Issue by lg430** [swoole/swoole-src#3174]
Please answer these questions before submitting your issue. Thanks!

环境: 
php7.1
swoole4.3.6  tcp process模式
centos 7

如题, 请问如何关闭processA进程, 而不被会manager重新拉起
$serv = new \Swoole\Server($host, $port);
$serv->addProcess($processA);
$serv->start();

**Comment by twose** [comment]
不要add不就不会拉起了

**Comment by lg430** [comment]
@twose 没看懂呢, processA这个进程是一定要有的, 但我想在某个时间点, 如接收到信号的方式关闭这个进程而不被manager重新拉起, 请问可以实现吗

**Comment by lg430** [comment]
我通过类似如下的代码, 好像不太行
```
Process::signal($signo, function () use ($process) {
    // do something 
});
```
当$signo = 99信号好像捕捉不到, 但是已定义的如SIGINT, SIGTERM, SIGINFO又会杀死进程然后被manager拉起.

有哪些信号可以让Process::signal接收到, 但是又不会杀死进程呢 ?

**Comment by huanghantao** [comment]
@lg430 意思应该是，你通过`add`的进程，就是会被`manager`进程管的。所以你创建用户进程不要用`add`的方式，而是自己`new Process`来创建进程。

**Comment by lg430** [comment]
@huanghantao 好的, 有没有好的方法实现shell与php进程通信呢, 我上面用的Process::signal貌似不合适, 如上面所说

**Comment by matyhtf** [comment]
@lg430 可以在 wenda.swoole.com 中提问
