### ISSUE TITLE
PHP Warning:  Swoole\Server::task(): worker_id must be less than task_worker_num[4]

### ISSUE THREAD

**Issue by tianyu2014214** [swoole/swoole-src#3176]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
<?php
class Ws
{
    public $host = '192.168.1.8';
    public $port = 8081;

    public $ws = null;
    public function __construct()
    {
        $this->ws = new Swoole\WebSocket\Server($this->host, $this->port);

        $this->ws->set([
            'worker_num' => 1,
            'task_worker_num' => 4
        ]);

        $this->ws->on('open', [$this, 'onOpen']);
        $this->ws->on('message', [$this, 'onMessage']);
        $this->ws->on('task', [$this, 'onTask']);
        $this->ws->on('finish', [$this, 'onFinish']);
        $this->ws->on('close', [$this, 'onClose']);

        $this->ws->start();
    }

    public function onOpen($ws, $request)
    {
        var_dump($request->fd);
    }

    public function onMessage($ws, $frame)
    {
        echo "client-message: {$frame->data}\n";
        // todo 10s
        $data = [
            'task' => 1,
            'fd' => $frame->fd
        ];
        $ws->task($data);
        $ws->push($frame->fd, "server-message: " . date('Y-m-d h:i:s'));
    }

    public function onTask($serv, $taskid, $workerid, $data)
    {
        sleep(10);
        return 'on task finish';
    }

    public function onFinish($serv, $taskid, $data)
    {
        echo "taskid: {$taskid}\n";
        echo "finish-data-success: {$data}";
    } 

    public function onClose($ws, $fd)
    {
        echo "client-id: {$fd}\n";
    }
}

$obj = new Ws();
```

2. What did you expect to see?
Call func onTask and onFinish when client send message to websocket server. Thus the server will output taskid and data.

3. What did you see instead?
PHP Warning:  Swoole\Server::task(): worker_id must be less than task_worker_num[4]

4. What version of Swoole are you using (show your `php --ri swoole`)?
Version => 4.5.0-alpha

5. What is your machine environment used (including version of kernel & php & gcc) ?
Linux version 4.19.97-v7l+ 
gcc version 4.9.3
PHP 7.4.3

**Comment by matyhtf** [comment]
Could not reproduce your problem, please check the task method parameter is correct

**Comment by zymeli** [comment]
你好，我也遇到此问题，我查看了源代码，应该是有bug
==================== swoole_server.cc ===========================
static sw_inline int php_swoole_check_task_param(Server *serv, zend_long dst_worker_id) {
    if (UNEXPECTED(serv->task_worker_num == 0)) {
        php_swoole_fatal_error(E_WARNING, "task method can't be executed without task worker");
        return SW_ERR;
    }
    if (UNEXPECTED(dst_worker_id >= serv->task_worker_num)) {
        php_swoole_fatal_error(E_WARNING, "worker_id must be less than task_worker_num[%u]", serv->task_worker_num);
        return SW_ERR;
    }
    if (UNEXPECTED(serv->is_task_worker())) {
        php_swoole_fatal_error(E_WARNING, "Server->task() cannot use in the task-worker");
        return SW_ERR;
    }
    return SW_OK;
}
==========================================================
Swoole\Server->task(mixed $data, int $dstWorkerId = -1, callable $finishCallback): int
参数: int $dstWorkerId
功能：可以指定要给投递给哪个 Task 进程，传入 ID 即可，范围参考 $worker_id
==============================================================
$worker_id
得到当前 Worker 进程的编号，包括 Task 进程。
提示
这个属性与 onWorkerStart 时的 $workerId 是相同的。
Worker 进程编号范围是 [0, $serv->setting['worker_num']-1]
Task 进程编号范围是 [$serv->setting['worker_num'], $serv->setting['worker_num'] + $serv->setting['task_worker_num']]
======================================================================
以上，手册是正确的，但swoole_server.cc里，中间明显有BUG。
=============================================
我目前绕过这个bug的方法是：
$server->set([
            'task_worker_num' => count($this->productIds) + 10, // 保证每个产品有一个task进程对应
        ]);
===========================
以上，请查证，谢谢。

**Comment by matyhtf** [comment]
@zymeli  文档中的表述可能存在一些错误，实际上这里的 `dst_worker_id` 是指 Task 进程的编号，是 `[0-task_worker_num -1]` 之间的一个数字

**Comment by zymeli** [comment]
好的，谢谢你。



---Original---
