### ISSUE TITLE
how to get a uniq id on every http request ? 

### ISSUE THREAD

**Issue by scil** [swoole/swoole-src#318]
for example
```
$http->on('request',function ($request,$response) {
          echo call_some_thing();
}

function call_some_thing(){
         return swoole_request_id();
}

```

I have tried php session, but it does mix different request together. for example
```
$http_server->on('request', function ($request, $response) use ($app,$kernel) {
           session_start();
           echo session_id();
}
```
First, I use browser firefox to visit web page , and everything ok.
Second, i use browser Chrome to visit, and error occur:
```
 'A session had already been started - ignoring session_start()' 
```
That's say: php session can't diff different requests.

I thinks the cause is the $_SESSION, which is a global var.

is it possible that a handy function like swoole_request_id ? Maybe it's not availabel on nodejs , but i think it's useful for php style world .

**Comment by Atriedes** [comment]
if you need generate unique id per request you can use this

$http->on('request',function ($request,$response) {
          echo $request->fd;
}

**Comment by scil** [comment]
Thank you!  I studied swoole framework and learned some.
