### ISSUE TITLE
Sending a very long trailer

### ISSUE THREAD

**Issue by supersmile2009** [swoole/swoole-src#3187]
Hi.
I'm developing a gRPC service based on Swoole. The standard way to send error details to the client seems to encode those details into Grpc-Status-Details-Bin trailer. In certain cases that trailer may be quite long, especially if debug info is encoded in non-prod environments. However swoole seems to set a limit on header/trailer size.

I've tracked it down to this line https://github.com/swoole/swoole-src/blob/6a19e0782552dd3de72919f11cf4a79562475752/swoole_http_response.cc#L1185
Is there a way configure a different value for the SW_HTTP_HEADER_VALUE_SIZE constant without recompiling swoole? Something like `Swoole\Http\Server::set()` or an alternative way to deal with this issue? I took a quick glance at the source code but couldn't find anything.

1. What did you do? If possible, provide a simple script for reproducing the error.
```
$encodedDetails = 'very long base64 encoded string';
$swooleResponse->trailer('Grpc-Status-Details-Bin', $encodedDetails);
```
2. What did you expect to see?
Trailer is sent correctly.
3. What did you see instead?
ErrorException is thrown with a message "Warning: Swoole\Http\Response::trailer(): trailer value is too long"
4. What version of Swoole are you using (show your `php --ri swoole`)?
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.16
Built => Mar 16 2020 15:34:16
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```
5. What is your machine environment used (including version of kernel & php & gcc) ?
GCC 8.3.0
PHP 7.3.11
Kernel 5.0.0-38-generic

**Comment by twose** [comment]
Most server or client implementations have a limitation on the max length of the header (usually 8K)
If we are compatible with large headers, the implementation has to extend the capacity of many static buffers, which cannot be done at runtime (or we have to move the memory from the stack to the heap)

In most cases, we don't need such a large header, so this feature was not considered at first
