### ISSUE TITLE
Swoole\Http\Response  http context is unavailable

### ISSUE THREAD

**Issue by kuzne4ik537** [swoole/swoole-src#3199]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
I run load (stress) tests on this using Jmeter.
      ```
           $setting = [
                'timeout' => self::CLIENT_TIMEOUT,
                'connect_timeout' => self::CLIENT_CONNECT_TIMEOUT,
            ];
            $cli = new \Swoole\Coroutine\Http\Client($uri, 80);
            $cli->set($setting);
            $cli->setMethod(strtoupper($method));
            $cli->execute($this->prepareRoute($route));
            $return = [
                'headers'       => $cli->getHeaders(),
                'body'          => $cli->getBody(),
                'statusCode'    => $cli->getStatusCode()
            ];
            $cli->close();
            return $return;

2. What did you expect to see?
No errors


3. What did you see instead?
More than 40% of exception: 
<img width="1077" alt="Screen Shot 2020-03-24 at 1 01 19 PM" src="https://user-images.githubusercontent.com/15640988/77455018-b45ef000-6dcf-11ea-82b2-47fc4a36faf3.png">

 Here's my Swoole response from Controller:
   ```  
        foreach ($headers as $name => $values) {
            if ('Transfer-Encoding' !== $name) {
                $this->response->header($name, $values);
            }
        }
        $this->response->status($code);
        $data = isset($data) ? json_encode($data) : null;
        $this->response->end($data);

4. What version of Swoole are you using (show your `php --ri swoole`)?

Version 4.4.16

5. What is your machine environment used (including version of kernel & php & gcc) ?
PHP 7.3.11
gcc (Alpine 8.3.0) 8.3.0

**Comment by matyhtf** [comment]
Coroutines are executed concurrently, and a controller must be created for each request. Controller objects cannot be saved in global variables.
