### ISSUE TITLE
swoole_async_write* 异步写文件数据丢失

### ISSUE THREAD

**Issue by eaglewu** [swoole/swoole-src#320]
源代码中 swoole_async_write\* 函数，并未对写入文件进行加锁。
在多进程同时写文件时，会出现数据数据丢失问题。

**Comment by terrywh** [comment]
遇到类似问题，我这里希望用异步 IO 写日志（多进程状态），offset = -1 并没有实现 ”追加“；看源代码当 offset <0 时，获得当时文件大小，然后将 offset 该大小来实现的。
