### ISSUE TITLE
SWOOLE_HOOK_CURL and Microsoft-IIS/10.0 requests fail

### ISSUE THREAD

**Issue by rsjohn** [swoole/swoole-src#3201]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```php
public function runMe()
    {   
        Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL);
        $this->url = 'https://apilegion.px.com/px'; 

        $this->queryString = '<?xml version="1.0" encoding="UTF-8"?>
                <LeadData Target="Lead.Insert" partner="testing" Password="headers">
                </LeadData>';

        $this->_timeOut = 30;
        $this->_httpHeaderArray[] = 'Content-Type: text/xml';
        //$this->_httpHeaderArray[] = 'Expect: ';

        $this->_ch = curl_init();
        curl_setopt($this->_ch, CURLOPT_URL, $this->url );
        curl_setopt($this->_ch, CURLOPT_POST, 1 );
        curl_setopt($this->_ch, CURLOPT_POSTFIELDS, $this->queryString );

        curl_setopt($this->_ch, CURLOPT_HTTPHEADER, $this->_httpHeaderArray);

        curl_setopt($this->_ch, CURLOPT_CONNECTTIMEOUT, $this->_timeOut);
        curl_setopt($this->_ch, CURLOPT_TIMEOUT, $this->_timeOut);
        curl_setopt($this->_ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($this->_ch, CURLOPT_HEADER, 0);

        curl_setopt($this->_ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($this->_ch, CURLOPT_SSL_VERIFYHOST, 0);


        $debug = true;
        $debugData = '';
        if($debug)
        {
            ob_start(); //open a buffer; WE MUST CLOSE IT!
            curl_setopt($this->_ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($this->_ch, CURLOPT_VERBOSE, 1);
            curl_setopt($this->_ch, CURLOPT_HEADER, 1);
            curl_setopt($this->_ch, CURLINFO_HEADER_OUT, true);
        }

        $data = curl_exec($this->_ch);

        if($debug)
        {
            $debugData  .= print_r(curl_getinfo($this->_ch) , 1);
            $debugData  .= print_r(curl_error($this->_ch), 1);
            $debugData  .= ob_get_clean();//close buff
        }

        $this->responses['data'] = $data . ' '. $debugData;
       
    }
```

2. What did you expect to see?
      This is normal cUrl running the same code:

-------------response----------
```
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Content-Type: text/xml
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Wed, 25 Mar 2020 14:49:07 GMT
Connection: close
Content-Length: 379

<?xml version="1.0" encoding="utf-8"?>
<Response>
<Result Value="BaeNOK">
<Error>
<Reason>Login failed, user not found.</Reason>
<Param></Param>
<ExtraInfo></ExtraInfo>
</Error>
<Error>
<Reason>Partner login Failed, API access denied.</Reason>
<Param>Partner</Param>
<ExtraInfo>Param=Partner, Value=xxxxx, PassWord=******.</ExtraInfo>
</Error>
</Result>
</Response> Array
(
    [url] => https://apilegion.px.com/px
    [content_type] => text/xml
    [http_code] => 200
    [header_size] => 196
    [request_size] => 126
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.591275
    [namelookup_time] => 0.060669
    [connect_time] => 0.126817
    [pretransfer_time] => 0.362938
    [size_upload] => 1974
    [size_download] => 379
    [speed_download] => 640
    [speed_upload] => 3338
    [download_content_length] => 379
    [upload_content_length] => 1974
    [starttransfer_time] => 0.433412
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 13.92.245.170
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 172.17.0.2
    [local_port] => 38280
    [request_header] => POST /px HTTP/1.1
Host: apilegion.px.com
Accept: */*
Content-Type: text/xml
Content-Length: 1974
Expect: 100-continue
)
```
//////
Notice the 2 header responses (HTTP/1.1 100 Continue and HTTP/1.1 200 OK)  at the top.
Also the request headers are different from swoole (Accept: */* and Expect: 100-continue) are sent.

3. What did you see instead?
    When running the same code on swoole we get:
```
-------------response----------
 Array
(
    [url] => https://apilegion.px.com/px
    [content_type] => 
    [http_code] => 0
    [header_size] => 0
    [request_size] => 0
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.38715887069702
    [namelookup_time] => 0
    [connect_time] => 0
    [pretransfer_time] => 0
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 
    [certinfo] => Array
        (
        )

    [primary_port] => 0
    [local_ip] => 
    [local_port] => 0
    [http_version] => 0
    [protocol] => 0
    [ssl_verifyresult] => 0
    [scheme] => 
)
```
////////////////////////
I have tried various headers and curl settings.  I believe the issue lies with the "Expect: 100-continue" mechanism.  Microsoft servers are known to need this.  
See:  https://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/more_examples/expect_100_continue_server.html

also https://curl.haxx.se/mail/lib-2017-07/0064.html
The take away is Expect: 100-continue is here to stay and swoole should support it. 

Until this issue is fixed swoole Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL); can not be trusted in applications that communicate with IIS servers. 

4. What version of Swoole are you using (show your `php --ri swoole`)?
5. What is your machine environment used (including version of kernel & php & gcc) ?

php -r 'phpinfo();' | grep -A 20 'Swoole Team <team@swoole.com>'
Author => Swoole Team <team@swoole.com>
Version => 4.5.0-alpha
Built => Mar 17 2020 07:34:44
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

centos-release-7-6.1810.2.el7.centos.x86_64 
Linux 4.9.27-moby #1 SMP Thu May 11 04:01:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by twose** [comment]
Generally, this is not necessary and we have never supported it on the client

Have any examples can be run directly on mine mac?

I just tried `curl -v -d "<?xml version=\"1.0\" encoding=\"UTF-8\"?><LeadData Target=\"Lead.Insert\" partner=\"testing\" Password=\"headers\"></LeadData>" https://apilegion.px.com/px`

**Comment by rsjohn** [comment]
I full working code to demonstrate the problem:

`<?php

$test = new Test();


class Test
{

    public function __construct()
    {
        Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL); //hook curl for swoole side
        $this->sServer = new swoole_server('0.0.0.0', 9999);
        $this->sServer->set(array(
            'worker_num' => 5,
            'daemonize' => true,
            'log_file' => 'cli.txt',
            'heartbeat_idle_time' => 180,
            'heartbeat_check_interval' => 60,));


        //$this->sServer->on( 'workerError', array( $this, 'workerError' ) );
        //for swoole_server() type
        $this->sServer->on( 'connect', array( $this, 'connect' ) );
        $this->sServer->on( 'receive', array( $this, 'receive' ) );
        $this->sServer->on( 'close', array( $this, 'close' ) );
        $this->sServer->on( 'start', array( $this, 'start' ) );
        //^^ + below for swoole_http_server() type
        //$this->sServer->on( 'request', array( $this, 'request' ) );

        $this->sServer->on( 'ManagerStart', array( $this, 'ManagerStart' ) );
        $this->sServer->on( 'ManagerStop', array( $this, 'ManagerStop' ) );
        $this->sServer->on( 'WorkerStart', array( $this, 'WorkerStart' ) );
        $this->sServer->on( 'WorkerStop', array( $this, 'WorkerStop' ) );

        $this->sServer->start();
        echo 'started';
    }

    public function start()
    {
        //echo 'Started';
        //$this->_shutdownHard();
    }
    public function ManagerStart()
    {  }
    public function ManagerStop()
    {   }
    public function  WorkerStart($server , $worker_id)
    {   }
    public function  WorkerStop()
    {   }
    public function workerError($serv, $worker_id, $worker_pid, $exit_code, $signal)
    {  }
    public function connect($server, $fd)
    {   }
    public function close($server, $fd)
    {   }
    public function receive($server, $fd, $from_id, $data)
    {
        echo 'recieve';
        $this->url = 'https://apilegion.px.com/px';

        $this->queryString = '<?xml version="1.0" encoding="UTF-8"?>
                <LeadData Target="Lead.Insert" partner="testing" Password="headers">
                </LeadData>';

        $this->_timeOut = 30;
        $this->_httpHeaderArray[] = 'Content-Type: text/xml';
        //$this->_httpHeaderArray[] = 'Expect: ';

        $this->_ch = curl_init();
        curl_setopt($this->_ch, CURLOPT_URL, $this->url );
        curl_setopt($this->_ch, CURLOPT_POST, 1 );
        curl_setopt($this->_ch, CURLOPT_POSTFIELDS, $this->queryString );

        curl_setopt($this->_ch, CURLOPT_HTTPHEADER, $this->_httpHeaderArray);

        curl_setopt($this->_ch, CURLOPT_CONNECTTIMEOUT, $this->_timeOut);
        curl_setopt($this->_ch, CURLOPT_TIMEOUT, $this->_timeOut);
        curl_setopt($this->_ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($this->_ch, CURLOPT_HEADER, 0);

        curl_setopt($this->_ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($this->_ch, CURLOPT_SSL_VERIFYHOST, 0);


        $debug = true;
        $debugData = '';
        if($debug)
        {
            //ob_start(); //open a buffer; WE MUST CLOSE IT!
            curl_setopt($this->_ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($this->_ch, CURLOPT_VERBOSE, 1);
            curl_setopt($this->_ch, CURLOPT_HEADER, 1);
            curl_setopt($this->_ch, CURLINFO_HEADER_OUT, true);
        }

        $ch = $this->_ch;
        $chan = new \Swoole\Coroutine\Channel(1);

        go( function() use ( $ch, $debug, $chan ) {

            $data = curl_exec($ch);
            if($debug)
            {
                $data  .= print_r(curl_getinfo($this->_ch) , 1);
                $data  .= print_r(curl_error($this->_ch), 1);
                //$data  .= ob_get_clean();//close buff
            }
            $chanPushResult = $chan->push( $data );
        });

        $chanData =  $msg = $chan->pop(20);
        echo $chanData . '-------';

    }
    public function request( swoole_http_request $httpRequest ,  swoole_http_response $httpResponse)
    { }
    private function _shutdownHard($server)
    {
    }
}`

you will need to run this code. Then wget 127.0.0.1:9999    You also have to tail the cli.txt file in local directory with the above code.   You will see output like so:
Array
(
    [url] => https://apilegion.px.com/px
    [content_type] =>
    [http_code] => 0
    [header_size] => 0
    [request_size] => 0
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.3862190246582
    [namelookup_time] => 0
    [connect_time] => 0
    [pretransfer_time] => 0
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0
    [redirect_time] => 0
    [redirect_url] =>
    [primary_ip] =>
    [certinfo] => Array
        (
        )

    [primary_port] => 0
    [local_ip] =>
    [local_port] => 0
    [http_version] => 0
    [protocol] => 0
    [ssl_verifyresult] => 0
    [scheme] =>
)
-------

**Comment by rsjohn** [comment]
Perhaps the issue is not with the Expect: 100-continue but instead deeper in swoole curl implementation?

**Comment by twose** [comment]
output on my PC
```php
HTTP/1.1 200 OK
content-type: text/xml
server: Microsoft-IIS/10.0
x-powered-by: ASP.NET
date: Thu, 02 Apr 2020 06:51:51 GMT
connection: close
content-length: 381

<?xml version="1.0" encoding="utf-8"?>
<Response>
<Result Value="BaeNOK">
<Error>
<Reason>Login failed, user not found.</Reason>
<Param></Param>
<ExtraInfo></ExtraInfo>
</Error>
<Error>
<Reason>Partner login Failed, API access denied.</Reason>
<Param>Partner</Param>
<ExtraInfo>Param=Partner, Value=testing, PassWord=******.</ExtraInfo>
</Error>
</Result>
</Response>Array
(
    [url] => https://apilegion.px.com/px
    [content_type] => text/xml
    [http_code] => 200
    [header_size] => 171
    [request_size] => 0
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.95615911483765
    [namelookup_time] => 0
    [connect_time] => 0
    [pretransfer_time] => 0
    [size_upload] => 0
    [size_download] => 381
    [speed_download] => 398.46924438376
    [speed_upload] => 0
    [download_content_length] => 381
    [upload_content_length] => -1
    [starttransfer_time] => 0
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 
    [certinfo] => Array
        (
        )

    [primary_port] => 0
    [local_ip] => 
    [local_port] => 0
    [http_version] => 0
    [protocol] => 0
    [ssl_verifyresult] => 0
    [scheme] => 
    [request_header] => POST /px HTTP/1.1
Host: apilegion.px.com
Content-Type: text/xml
Connection: keep-alive
Accept-Encoding: gzip, deflate, br
Content-Length: 151


)
```

**Comment by rsjohn** [comment]
To make sure you are testing this correctly, I have made a video.  The code must be in deamon mode and the curl must happen inside a go() with SWOOLE_HOOK_CURL enabled.  This bug was originally found in a production CentOS 7 server. The bug is repeatable on local development environments.   Our swoole application does go()+curl requests to around 100 different remote servers.  I found these null/empty responses coming from 3 remote servers, all of which are appear to be running IIS servers.  These 3 servers respond correctly with a normal php+curl request.  The bug only happens with the "parallel"/background go()+curl requests.
https://www.youtube.com/watch?v=DTYc_25lCxc

Thank you for your time.

**Comment by deminy** [comment]
As described [here](https://gms.tf/when-curl-sends-100-continue.html#curl-logic),

> Curl doesn't touch the 'Expect' header if it is explicitly set.
> 
> Otherwise, curl automatically sets it, if either
> 
> * the request is a PUT, or
> * the request is a POST and the data size is larger than 1024 bytes

The sample code in the original post won't work since the XML doc is too short. Here is a curl command to check the expected output:

```bash
curl -i \
    -H "Content-Type: text/xml" \
    -d "<?xml version=\"1.0\" encoding=\"UTF-8\"?><LeadData Target=\"Lead.Insert\" partner=\"testing\" Password=\"headers\"><aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa /></LeadData>" \
    https://apilegion.px.com/px
```

**Comment by rsjohn** [comment]
So, I think you are testing wrong.  The is problem is not a system call to ‘curl’.  If you run swoole without Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL) then everything works good. (This line commented out:  //Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL);  is good )

(GOOD)
If :  //Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL);
     ^^^ “//” commented out
Then: (echo $chanData . '-------'; outputs:
 
startedrecieveHTTP/1.1 200 OK
Content-Type: text/xml
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Mon, 13 Apr 2020 15:21:43 GMT
Connection: close
Content-Length: 381

<?xml version="1.0" encoding="utf-8"?>
<Response>
<Result Value="BaeNOK">
<Error>
<Reason>Login failed, user not found.</Reason>
<Param></Param>
<ExtraInfo></ExtraInfo>
</Error>
<Error>
<Reason>Partner login Failed, API access denied.</Reason>
<Param>Partner</Param>
<ExtraInfo>Param=Partner, Value=testing, PassWord=******.</ExtraInfo>
</Error>
</Result>
</Response>Array
(
    [url] => https://apilegion.px.com/px
    [content_type] => text/xml
    [http_code] => 200
    [header_size] => 171
    [request_size] => 256
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.423266
    [namelookup_time] => 0.012269
    [connect_time] => 0.092937
    [pretransfer_time] => 0.340762
    [size_upload] => 153
    [size_download] => 381
    [speed_download] => 900
    [speed_upload] => 361
    [download_content_length] => 381
    [upload_content_length] => 153
    [starttransfer_time] => 0.423232
    [redirect_time] => 0
    [redirect_url] =>
    [primary_ip] => 13.92.245.170
    [certinfo] => Array
        (
        )
    [primary_port] => 443
    [local_ip] => 172.17.0.2
    [local_port] => 55876
    [request_header] => POST /px HTTP/1.1
Host: apilegion.px.com
Accept: */*
Content-Type: text/xml
Content-Length: 153
)
-------

(BAD)
If :   Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL);
       ^^^ running
Then: (echo $chanData . '-------'; outputs:

recieveArray
(
    [url] => https://apilegion.px.com/px
    [content_type] =>
    [http_code] => 0
    [header_size] => 0
    [request_size] => 0
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.32759284973145
    [namelookup_time] => 0
    [connect_time] => 0
    [pretransfer_time] => 0
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0
    [redirect_time] => 0
    [redirect_url] =>
    [primary_ip] =>
    [certinfo] => Array
        (
        )

    [primary_port] => 0
    [local_ip] =>
    [local_port] => 0
    [http_version] => 0
    [protocol] => 0
    [ssl_verifyresult] => 0
    [scheme] =>
)
-------'


See full working code attached.
[testint.txt](https://github.com/swoole/swoole-src/files/4470389/testint.txt)
--------------------------------------------------------------------------------------------
<?php
$test = new Test();
class Test
{
    public function __construct()
    {
----->//Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL); //(GOOD)
vs
----->Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL); //(BAD)        
       $this->sServer = new swoole_server('0.0.0.0', 9999);
     ......
---------------------------------------------------------------------------------------------

Note the SWOOLE_HOOK_CURL is needed to have NON-BLOCKING or parallel curl calls in side php/swoole.  This is a special feature of swoole and required for my project.

**Comment by doubaokun** [comment]
@rsjohn Can't reproduce what you are seeing. Could you upgrade Swoole to v4.4.15 and test it again?

**Comment by rsjohn** [comment]
@doubaokun  Thank you so much for your time.  I truly do appreciate you looking into this.  This is a very hard bug to explain, I will try my best.  I am currently running 4.5.0-alpha which is ahead of your recommendation of v4.4.17   I can confirm it was broken in v4.4.(14-15), I will revert to v4.4.17 tonight and post back with my results. For clarification, can you confirm your testing methods:
(deamon = swoole server running as a background process)
Are you running my test code?
Are you running my test code as a deamon? 
Are your using wget or web browser to simulate a request to my deamon?
Are you stopping (destroying all running deamon/swoole instances), toggling the Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL);  line and re starting the deamon to see difference (bug)?

If you answer ‘no’ to any of my questions above then you will not see the issue.  I will try to explain why:
In php a ‘curl’ call is a system call that blocks the main php thread - this is also true in swoole!  I was very surprised to find that even a curl call inside a go() was in fact blocking the main swoole thread:
`$ch = (some curl obj that will take 10 seconds to return);       
        go( function() use ( $ch, $debug, $chan ) {
            $data = curl_exec($ch); //<<BLOCKS!  L123 
        });
	//This like will take 10 seconds to reach becase we are blocked at L123
	//https://apilegion.px.com/px response is good!
	

	Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL); //L1
	$ch = (some curl obj that will take 10 seconds to return);       
        go( function() use ( $ch, $debug, $chan ) {
            $data = curl_exec($ch); //<<now blocks only the go thread!  L123 
        });
	//This like will take 0 seconds to reach becase we set (SWOOLE_HOOK_CURL); on L1
	//when $data does come back after waiting the response is BAD!` 

As you can see, it is very hard to replicate this bug! You must set Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL); ,  you must setup a go() function that curls,  you must setup a channel to wait for the curl response,  you must be curling a server that responds with something that beaks swooles custom non-blocking curler! Known bad server is https://apilegion.px.com/px

Again thank you for your time.

**Comment by rsjohn** [comment]
OMG!   Updated 4.5.0-alpha => 4.5.0RC1 - on local this is working!  Please hold further testing.  I will confirm in production and close this ticket.  Thank you so much.

**Comment by rsjohn** [comment]
This is working! I walked it back various tags:
v4.5.0RC1 (working)
4.5.0-alpha ( known BAD)(branch/tag removed)
v4.4.17(working)
v4.4.16( BAD)

Thank you so much!
