### ISSUE TITLE
协程channel push异常

### ISSUE THREAD

**Issue by kiss291323003** [swoole/swoole-src#3202]
版本：mac os + php7.3 + swoole 4.4.x master 
```php
use Swoole\Coroutine\Scheduler;
use Swoole\Coroutine\Channel;
$scheduler = new Scheduler();
$scheduler->add(function() {
    $chan = new Channel(1);
    $chan->push(1,-1);
    var_dump('push success');
    $chan->push(1,-1);

});
$scheduler->start();
var_dump('Scheduler end');
```
预期结果：
```
string(12) "push success"
```
实际结果：
```
string(12) "push success"
string(13) "Scheduler end"
```
描述：理论上通道满了后，push超时-1的时候，协程应该一直挂起，直到channel被消费可以push

**Comment by twose** [comment]
这是一个死锁程序 没有解锁的可能性 程序会结束并发出报警
```php
WARNING	~Channel (ERRNO 10003): channel is destroyed, 1 producers will be discarded
```

**Comment by xiangdong2** [comment]
[root@swoole_server_10_10_0_45:/tmp]
#cat scheduler.php 
<?php
use Swoole\Coroutine\Scheduler;
use Swoole\Coroutine\Channel;
$scheduler = new Scheduler();
$scheduler->add(function() {
    $chan = new Channel(1);
    $chan->push(1,-1);
    var_dump('push success');
    $chan->push(1,-1);

});
$scheduler->start();
var_dump('Scheduler end');

[root@swoole_server_10_10_0_45:/tmp]
#php scheduler.php
string(12) "push success"
string(13) "Scheduler end"

能讲讲通道怎么满了么？普及下。

**Comment by huanghantao** [comment]
@xiangdong2 因为这里设置的`Channel`的大小是1，然后他`push`了一个数据进去，没有其他协程进行消费，`Channel`自然就是满的。
