### ISSUE TITLE
 $process->exportSocket()->getsockname()返回空对象

### ISSUE THREAD

**Issue by Reasno** [swoole/swoole-src#3205]
Swoole 4.4.16

Swoole/Process $process->exportSocket() 导出的socket，调用$socket-> getsockname()返回空对象。

**Comment by huanghantao** [comment]
这是我的测试脚本：

```php
<?php

use Swoole\Process;

$process = new Process(function (Process $process) {
    $sock = $process->exportSocket();
    var_dump($sock->getsockname());
});

$pid = $process->start();

$sock = $process->exportSocket();
var_dump($sock->getsockname());
```

输出：

```bash
[root@592b0366acbf process]# php test.php
array(2) {
  ["address"]=>
  string(0) ""
  ["port"]=>
  int(0)
}
array(2) {
  ["address"]=>
  string(0) ""
  ["port"]=>
  int(0)
}
[root@592b0366acbf process]#
```

请按照模板提问。

**Comment by Reasno** [comment]
就是想说 没有address

**Comment by huanghantao** [comment]
@Reasno 底层用的是`udg`进行通信，所以没有地址信息。

**Comment by huanghantao** [comment]
> @Reasno 底层用的是`unix socket`进行通信，所以没有地址信息。

**Comment by Reasno** [comment]
> @Reasno 底层用的是`unix socket`进行通信，所以没有地址信息。

嗯嗯 我实际是想问 怎么手动连接这个unix socket的地址，我想多开几个连接。如果getsockname能获取到地址，我自己new几个socket就行了。

有点跑题，

改在swoole问答上提问了。https://wenda.swoole.com/detail?id=107315

**Comment by twose** [comment]
没有地址是因为这个unix socket并没有绑定到固定的地址
一般也没有必要 因为一般只有服务端会绑定一个地址供其他进程访问, 会在本地生成一个sock文件

正确的设计思路已经回复在问答中了
