### ISSUE TITLE
希望能提供 Windows 的开发调试环境

### ISSUE THREAD

**Issue by huye** [swoole/swoole-src#321]
因为 swoole 中用了 Linux 特性的功能，而在 Windows 上是没有的，所以不知道 Windows 平台，但是开发的人还是有一部分在 Windows的。本人原来用了两年的 Linux，但是因为买的这台电脑用 Linux 有很多限制，所以又改用了 Windows。我希望 swoole 能提供给开发和测试的专用版，所以性能不那么重要，能把 Linux 下的特性模拟出来都没关系，为方便在 Windows 下开发。

**Comment by andot** [comment]
装个 linux 虚拟机或者 cygwin 吧。这个问题已经是月经问题了。

**Comment by Lynnworld** [comment]
vagrant 大法好

**Comment by wanjochan** [comment]
cygwin下编译可用，就是有点麻烦。可是更大的问题是不能 生产用途很浪费，毕竟很多windows服务器还在使用中，至少10-15年。。。

**Comment by jimcry** [comment]
服务器可以装linux虚拟机

**Comment by matyhtf** [comment]
- 使用VirtualBox安装Linux虚拟机（推荐方式）
- 使用cygwin

**Comment by sindey1982** [comment]
docker大法更好
