### ISSUE TITLE
connect socket.io

### ISSUE THREAD

**Issue by mRamadan0101** [swoole/swoole-src#3217]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
i want to connect between api and swoole without using socket.io server ( using node js)

2. What did you expect to see?
connected and auth user displayed

3. What did you see instead?
nothing 

4. What version of Swoole are you using (show your `php --ri swoole`)?
2.6

5. What is your machine environment used (including version of kernel & php & gcc) ?
php laravel

**Comment by twose** [comment]
upgrade

**Comment by Reasno** [comment]
@twose Even the latest version doesn't natively support socket.io as a protocol. However all underlying transportations of socket.io are supported by swoole.

I am currently working on a hyperf socket.io adapter https://github.com/hyperf/hyperf/issues/1518
