### ISSUE TITLE
当服务器完全断网时,协程客户端 请求不成功,不会立即退出

### ISSUE THREAD

**Issue by azhuang321** [swoole/swoole-src#3219]
php  7.2   swoole:4.4.16

官方示例
![抚顺](https://user-images.githubusercontent.com/63149232/78439894-3261a780-76aa-11ea-8163-a3f664180698.png)
![TIM截图20200404190635](https://user-images.githubusercontent.com/63149232/78439958-368dc500-76aa-11ea-8028-40a0b3825e6d.png)
第二张图片就是已经打印出来却没结束

**Comment by twose** [comment]
**为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
