### ISSUE TITLE
配置选项 enable_delay_receive 在swoole 4.4.16版本中无效

### ISSUE THREAD

**Issue by waimaolang** [swoole/swoole-src#3220]
php7.3版本，swoole 4.4.16 版本中，开启enable_delay_receive 配置选项后，未触发onConnect回调。

**Comment by twose** [comment]
**为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
