### ISSUE TITLE
Messages not received in full

### ISSUE THREAD

**Issue by chanar** [swoole/swoole-src#3223]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I sent base64 encoded image

```
$server->on('receive', function ($server, $fd, $from_id, $rawdata) {

    echo $rawdata . "------------------------------ LINE END -----------------";
```

2. What did you expect to see?

Base64 encode string full output

3. What did you see instead?

<img width="713" alt="Screenshot 2020-04-05 at 15 43 51" src="https://user-images.githubusercontent.com/2478747/78498662-4235c600-7754-11ea-8692-b2403615f2bc.png">

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.17
Built => Apr  4 2020 17:04:32
coroutine => enabled
kqueue => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777223/D16777223
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144
```

**Comment by huanghantao** [comment]
@chanar Can you provide a complete client and server code?

**Comment by chanar** [comment]
This is basically all the code in my web.php (using Laravel 7.4 fresh install)

```
$server = new Swoole\Server("127.0.0.1", 9503);


$server->on('connect', function ($server, $fd) {
    echo "connection open: {$fd}\n";
});

$server->on('receive', function ($server, $fd, $from_id, $rawdata) {

    echo $rawdata . "------------------------------ LINE END -----------------";

});
$server->on('close', function ($server, $fd) {
    echo "connection close: {$fd}\n";
});
$server->start();
```

The client is C++ but copied the base64 from there and used program PacketSender on Mac, same thing. 

Basically what it looks like it doesn't keep the connection "line" open for whole message and gets the message in junks.

**Comment by huanghantao** [comment]
@chanar Since your server is TCP, you need to design your own application-layer protocol to ensure that the entire data is collected. For example, use the length protocol provided by Swoole and start it with`open_length_check `。

**Comment by matyhtf** [comment]
TCP is a streaming protocol with no packet boundaries. Your program needs to split or merge data.
