### ISSUE TITLE
Benchmark Support DTLS Protocol

### ISSUE THREAD

**Issue by wk331100** [swoole/swoole-src#3231]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I need DTLS Protocol Benchmark to test the qps

2. What did you expect to see?

add function dtls() to benchmark/bin/sync.php 

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole 4.5.0 RC

5. What is your machine environment used (including version of kernel & php & gcc) ?

centos 7.4 && PHP 7.3.16 && Gcc 8

**Comment by matyhtf** [comment]
https://github.com/swoole/benchmark/blob/master/src/Base.php#L199
