### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Co\run() 

### ISSUE THREAD

**Issue by allowing** [swoole/swoole-src#3238]
![微信截图_20200411112741](https://user-images.githubusercontent.com/20262949/79034298-81966380-7be7-11ea-97b2-fad2910527dd.png)

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by sy-records** [comment]
cli下运行 `php --ri swoole | grep shortname` 查看。
或者查看文档说明：https://wiki.swoole.com/#/question/use?id=call-to-undefined-function-corun
