### ISSUE TITLE
I am getting Installation problem 

### ISSUE THREAD

**Issue by coinbreze** [swoole/swoole-src#3244]
Hi, 
 
 I am getting error while running "pecl install swoole"  _#error "require PHP version 7.1 or later" but my php version is 7.1.33_

PHP Version 7.1.33-14+ubuntu16.04.1+deb.sury.org+1
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
kernal version - 4.15.0-29-generic
![Screenshot from 2020 04 14 12 29 00](https://user-images.githubusercontent.com/43780708/79195835-99225600-7e4c-11ea-8b41-3808636d4c86.png)

Kindly do needful for installation

**Comment by twose** [comment]
You used the phpize of low PHP version (20151012)

There must be multiple PHP versions on your machine, please check them

**Comment by coinbreze** [comment]
Thank you for your quick response.

Yes, I am using multiple PHP version 7.0.33 for my project. To use swoole only I have added another PHP version 7.1.33.

is it possible to use swoole in PHP version 7.033 ?

In my project I need asynchronous data process and queue in php

**Comment by twose** [comment]
No, We are consistent with the official PHP, no longer maintain the abandoned PHP version

https://www.php.net/supported-versions.php
