### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Swoole\HTTP\Server' 

### ISSUE THREAD

**Issue by coinbreze** [swoole/swoole-src#3246]
Hi,

I am getting below error, Kindly do the needful
Fatal error: Uncaught Error: Class 'Swoole\HTTP\Server' not found in /var/www/html/try/ru.php:5

PHP 7.2.29-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar 20 2020 13:54:16) ( NTS )
```

Code:
<?php 
   `error_reporting(-1);`
	ini_set('display_errors', 1);
$server = new Swoole\HTTP\Server("127.0.0.1", 9501);

$server->on("start", function (Swoole\Http\Server $server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$server->on("request", function (Swoole\Http\Request $request, Swoole\Http\Response $response) {
    $response->header("Content-Type", "text/plain");
    $response->end("Hello World\n");
});

$server->start();
```

![Screenshot_2020-04-14 phpinfo()](https://user-images.githubusercontent.com/43780708/79218492-22965000-7e6e-11ea-976f-f221e80e578e.png)

**Comment by Yurunsoft** [comment]
The class is `Swoole\Http\Server`

**Comment by coinbreze** [comment]
I have to use like below ?
use Swoole\Http\Server;

**Comment by coinbreze** [comment]
> The class is `Swoole\Http\Server`

Need to extend the class or need to enable in phpinfo

**Comment by sy-records** [comment]
Most functions need to run in `cli` mode @coinbreze 
You need to check `php --ri swoole`

**Comment by coinbreze** [comment]
php --ri swoole throws _Extension 'swoole' not present._
But php info swoole is diplaying

**Comment by sy-records** [comment]
So you may be two `php.ini` files, Please check.
You can refer to the [documentation](https://wiki.swoole.com/#/question/install?id=%e5%9c%a8phpinfo%e4%b8%ad%e6%9c%89%e5%9c%a8php-m%e4%b8%ad%e6%b2%a1%e6%9c%89)

**Comment by coinbreze** [comment]
Ok, Thankyou
I will check
