### ISSUE TITLE
can't able to run php file

### ISSUE THREAD

**Issue by coinbreze** [swoole/swoole-src#3252]
Hi,

I am getting below error while runnig php file through browser but in terminal it working fine.
PHP 7.2.29-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar 20 2020 13:54:16) ( NTS )

_Fatal error: Uncaught Error: Call to undefined function Co\run()_ 

Kindly do the needful

`<?php
error_reporting(-1);
ini_set('display_errors', 1);
$chan = new Swoole\Coroutine\Channel(1);
Co\run(function () use ($chan) {
    echo $cid = Swoole\Coroutine::getuid();

    $i = 0;
    while ($i<7) {
        co::sleep(1.0);
        $r = ['rand' => rand(1, 10), 'index' => $i,'key'=>'sample'];
        $chan->push($r);
        echo date('Y-m-d H:i:s').'==r==';
        print_r($r);
        // echo "[coroutine $cid] - $i\n";
        $i++;
    }

});
Co\run(function () use ($chan) {
    echo $cid = Swoole\Coroutine::getuid();

    while(1) {
        $data = $chan->pop();
        //echo "[coroutine $cid]\n";
        echo date('Y-m-d H:i:s').'==s==';
        print_r($data);
    }

});`

**Comment by twose** [comment]
Please respect the issue template

show your `php --ri swoole`

**Comment by twose** [comment]
> I am getting below error while runnig php file through browser but in terminal it working fine.

Swoole can only run in cli mode

**Comment by coinbreze** [comment]
> Please respect the issue template
> 
> show your `php --ri swoole`

![Screenshot from 2020 04 16 11 18 17](https://user-images.githubusercontent.com/43780708/79419282-2a700480-7fd4-11ea-9129-51b481d77702.png)

**Comment by coinbreze** [comment]
> > I am getting below error while runnig php file through browser but in terminal it working fine.
> 
> Swoole can only run in cli mode

Then how can I use asyn for loop like node js ?
