### ISSUE TITLE
测试发现 Swoole 4.4.17 与 uopz 6.1.1 有冲突！

### ISSUE THREAD

**Issue by designinlife** [swoole/swoole-src#3254]
CentOS 7 上安装 PHP 7.3.17 + Swoole 4.4.17 与 uopz 6.1.1 有冲突。直接运行 php --ri 任何扩展，都会出现 Segmentation fault (core dumped)

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
