### ISSUE TITLE
CURL_HOOK不支持CURLOPT_FAILONERROR

### ISSUE THREAD

**Issue by nsnake** [swoole/swoole-src#3261]
PHP:7.2
swoole:4.4.17
出现的错误：
PHP Fatal error:  Uncaught Swoole\Curl\Exception: swoole_curl_setopt(): option[45] is not supported in @swoole-src/library/core/Curl/Handler.php:545

原始php代码:
$ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_FAILONERROR, false);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
