### ISSUE TITLE
Dose  CURL_HOOK not support CURLOPT_FAILONERROR?

### ISSUE THREAD

**Issue by nsnake** [swoole/swoole-src#3262]
PHP:7.2
swoole:4.4.17

when i used like this:
```
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_FAILONERROR, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
```

PHP Fatal error: Uncaught Swoole\Curl\Exception: swoole_curl_setopt(): option[45] is not supported in @swoole-src/library/core/Curl/Handler.php:545

**Comment by sy-records** [comment]
swoole v4.5 version will support.
