### ISSUE TITLE
一键协程化有没有可能在不适宜的地方自动关闭？

### ISSUE THREAD

**Issue by Reasno** [swoole/swoole-src#3263]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

在自动加载过程中只要出现协程切换就会在并发时出现致命错误。由于一键协程化是个全局状态，而自动加载函数很多时候在vendor中，所以很难逐一避免。

```php
<?php
Co::set(['hook_flags'=> SWOOLE_HOOK_ALL]);
$load = function ($name) {
    sleep(1); // or file_get_content('path/to/source.php');
    eval('class InexistentClass{}');
};
spl_autoload_register($load);
Co\run(function () {
    go(function () {
        new InexistentClass;
    });
    go(function () {
        new InexistentClass;
    });
});
```

2. What did you expect to see?

InexistentClass 成功加载

3. What did you see instead?

Fatal error: Uncaught Error: Class 'InexistentClass' not found in /test.php:13

4. What version of Swoole are you using (show your `php --ri swoole`)?

```php
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.16
Built => Mar 14 2020 23:18:06
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2s  28 May 2019
http2 => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777223/D16777223
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144
```

5. What is your machine environment used (including version of kernel & php & gcc) ?

不相关。

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
