### ISSUE TITLE
WARNING swSocket_write_blocking(:201)

### ISSUE THREAD

**Issue by Hetystars** [swoole/swoole-src#3268]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
WARNING swSocket_write_blocking(:201): write 20 bytes failed, Error: Resource temporarily unavailable[11]
WARNING swTaskWorker_finish(:425): TaskWorker: send result to worker failed, Error: Resource temporarily unavailable[11]

    worker进程是调用了异步task,  qps 200左右,近期大量报上述warning

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
	swoole

	Swoole => enabled
	Author => Swoole Team <team@swoole.com>
	Version => 4.4.16
	Built => Mar  6 2020 01:52:47
	coroutine => enabled
	epoll => enabled
	eventfd => enabled
	signalfd => enabled
	cpu_affinity => enabled
	spinlock => enabled
	rwlock => enabled
	openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
	zlib => 1.2.11
	mutex_timedlock => enabled
	pthread_barrier => enabled
	futex => enabled
	async_redis => enabled

	Directive => Local Value => Master Value
	swoole.enable_coroutine => On => On
	swoole.enable_library => On => On
	swoole.enable_preemptive_scheduler => Off => Off
	swoole.display_errors => On => On
	swoole.use_shortname => On => On
	swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
php 7.1.3

        Linux version 4.9.81-35.56.amzn1.x86_64 (mockbuild@gobi-build-64010) (gcc version 7.2.1 
        20170915 (Red Hat 7.2.1-2) (GCC) ) #1 SMP Fri Feb 16 00:18:48 UTC 2018

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
