### ISSUE TITLE
undefined symbol: multipart_parser_free 报错

### ISSUE THREAD

**Issue by zhang-bin** [swoole/swoole-src#327]
php -m 报错：PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/swoole.so' - /usr/lib64/php/modules/swoole.so: undefined symbol: multipart_parser_free in Unknown on line 0

swoole扩展make & make install都没报错

环境: php 5.6.11, centos 6.5, swoole 1.7.18

PS: 安装swoole 1.7.17版本正常的

**Comment by matyhtf** [comment]
使用最新版本，重新执行编译指令
```shell
phpize 
./configure 
make clean 
make install
```
