### ISSUE TITLE
Unable to process request

### ISSUE THREAD

**Issue by iotap** [swoole/swoole-src#3283]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

`
'enable_static_handler' => true,
`

2. What did you expect to see?

Process PHP requests while working with static files.

3. What did you see instead?

> HTTP 404 Not Found
> Powered by Swoole

4. What version of Swoole are you using (show your `php --ri swoole`)?

`
swoole v4.5.0
`

5. What is your machine environment used (including version of kernel & php & gcc) ?

`
docker pull hyperf/hyperf:7.2-alpine-v3.9-cli
`

Swoole v4.4 is normal.

**Comment by twose** [comment]
Please provide a simple script for reproducing the error

**Comment by matyhtf** [comment]
```
$server->set([
    "static_handler_locations" => ['/static', '/app/images'],
]);
```
Please check if this configuration is correct
