### ISSUE TITLE
Safely restarting workers in HTTP2 server

### ISSUE THREAD

**Issue by supersmile2009** [swoole/swoole-src#3284]
1. What did you do? If possible, provide a simple script for reproducing the error.
- Start Swoole server with HTTP2 enabled.
```
'reload_async' => true,
'open_http2_protocol' => true,
// and some other keepalive options, which are unrelated
```
- Start a test client continuously sending some concurrent requests to the server.
- Reload server with `kill -USR1 $PID`
OR
Reload worker from the code after handling request
```
$response->end($content);
$server->close($response->fd, false);
$server->stop();
```

2. What did you expect to see?
I expect the worker to send the request successfully, close connection, restart and handle new requests without errors.

3. What did you see instead?
I get connection termination errors on client during the restart. It only happens when I send many requests concurrently. Apparently client gets connected to a worker which is being stopped.

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.0
Built => Apr 29 2020 13:03:24
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ?

`php -v`
```
PHP 7.3.11-1+ubuntu19.04.1+deb.sury.org+1 (cli) (built: Oct 24 2019 18:23:41) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-1+ubuntu19.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.31.0~linux-x64-non_zts73, https://blackfire.io, by Blackfire
```
`gcc -v`
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.2.1-9ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)
```
`uname -r`
```
5.3.0-46-generic
```

UPD:
To clarify my actual goal:
I'm trying to port a legacy app to run on Swoole and use gRPC at the same time (which needs HTTP2). The app has some memory leaks and it's going to take a lot of time to get rid of all of them. Therefore I'm trying to find a workaround to restart workers from time to time. `max_request` config doesn't work properly with `'dispatch_mode' => 2` according to the documentation. In practice it has even worse connection termination issues when compared to closing connection and restarting worker from PHP code. And I can't use dispatch_mode 1 or 3, because they aren't compatible with HTTP2.

**Comment by matyhtf** [comment]
http2 is a stateful service, it is recommended to use SWOOLE_BASE mode.

Session data will be lost when the worker process restarts, the connection needs to be closed, and the client reconnects.
