### ISSUE TITLE
求助,经常报错:sendto to reactor failed, Error: No buffer space available[105],

### ISSUE THREAD

**Issue by minguo** [swoole/swoole-src#3287]
WARNING	swFactoryProcess_finish(:472): sendto to reactor failed, Error: No buffer space available[105]

使用unixsocket监听服务的方式，但是经常会出线这个问题，然后监听服务就挂了(.socket文件不见了)，但是服务本身没崩溃，请问是怎么回事呢？

swoole版本是4.3.6
系统:ubuntu 18.04.2 LTS

net.core.rmem_max = 268435456
net.core.wmem_max = 268435456
net.ipv4.tcp_wmem = 4096        16384   268435456
net.ipv4.tcp_rmem = 4096        87380   268435456
net.ipv4.tcp_mem = 383913       511884  268435456

			"package_max_length"=>32*1024*1024,//接收数据包的最大尺寸
			"buffer_output_size"=>32*1024*1024,//发送数据包的最大尺寸
//            "socket_buffer_size"=>32*1024*1024,//发送数据包的最大尺寸，这个参数打开好像有问题

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
