### ISSUE TITLE
Typo found

### ISSUE THREAD

**Issue by nashgao** [swoole/swoole-src#3288]
测试swoole event的时候出现这个报错
[debug][warning]:[Swoole\Event::add(): both read and write callbacks are emoty

经查在swoole_event.cc第508行emoty应为empty吧

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
