### ISSUE TITLE
【master】swEventTimer_select ?

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#329]
<pre>
swSocket_is_stream/swSocket_is_dgram 刚好取反了 请修复
+static sw_inline int swSocket_is_stream(uint8_t type)
+{
+    return (type == SW_SOCK_UDP || type == SW_SOCK_UDP6 || type == SW_SOCK_UNIX_DGRAM);
+}
+
+static sw_inline int swSocket_is_dgram(uint8_t type)
+{
+    return (type == SW_SOCK_TCP || type == SW_SOCK_TCP6 || type == SW_SOCK_UNIX_STREAM);
+}
+
</pre>

<pre>
if else是一样的？？
@@ -178,7 +178,15 @@ static int swEventTimer_select(swTimer *timer)
             if (!tmp->remove)
             {
                 tmp->restart = 1;
-                tmp->exec_msec = now_msec + tmp->interval;
+                int _now_msec = swEventTimer_get_relative_msec();
+                if (_now_msec > 0)
+                {
+                    tmp->exec_msec = now_msec + tmp->interval;
+                }
+                else
+                {
+                    tmp->exec_msec = now_msec + tmp->interval;
+                }
</pre>

**Comment by matyhtf** [comment]
已修改。
