### ISSUE TITLE
Swoole TCP server, figuring out no. of workers for devices to meet scalability

### ISSUE THREAD

**Issue by keshav-boss** [swoole/swoole-src#3293]
1. What did you do? If possible, provide a simple script for reproducing the error.

I am using swoole TCP server for receving data packet over TCP by devices. 
Each Device sending data packet every 10 seconds.
After making connection with server devices sends data packet in HEX.
I parse this data packet and store it in MySQL DB using script written inside on receive callback.
Now I have 1000 devices for which I am using 16 workers? Is this no. of worker is too small or too large?
script excecution time are as follows
// avg execution time : 0.018135791 secs
// max exceution time : 0.195485115 secs
// min exceution time : 0.001955032 secs

What can be optimum no of workers should I set so that I dont get any error and able to handle each data packet from devices?
How to find relationship between no. of workers, no of devices, data frequency and script exceution time?

Script as below

$serv = new swoole_server("0.0.0.0", self::PORT_NO);
$serv->set(array(
	'worker_num' => 16,
	'daemonize' => false,
	'heartbeat_check_interval' => 30,
	'heartbeat_idle_time' => 1800,
	'log_file' => $filepath
));

$serv->on('connect', function ($serv, $fd) {
	$tcp_client = $serv->connection_info($fd);	
});

$serv->on('receive', function ($serv, $fd, $from_id, $data) {	
	// Script processing received data packet
	// avg execution time : 0.019338155 secs
	// max exceution time : 0.161221981 secs
	// min exceution time : 0.161221981 secs
});

$serv->on('close', function ($serv, $fd) {   
});

$serv->on('shutdown', function () {	
});

$serv->start();		

2. What did you expect to see?

How many maximum devices can be handle on given server? OR How do I scale TCP server to handle 50000 devices? 
How Many Workers Do I need? 
Is there any other configuration I have to set?
Can I use task worker? Then how mny worker or task worker needed? What is relation?
also how do I test 50000 devices?
How can I manage statistics of connections, errors? CPU, Memory load to understand any limit reached before getting any error?
Server details mentioned in envionment below.

3. What did you see instead?

Not able to find how many no. of workers to set when devices grows.

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

swoole support => enabled
Version => 1.9.21
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

Linux version 2.6.32-504.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) ) #1 SMP Wed Oct 15 04:27:16 UTC 2014

PHP 5.6.31 (cli) (built: Sep 14 2017 18:31:45)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

CPU info : 

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Stepping:              4
CPU MHz:               3300.183
BogoMIPS:              6599.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31

Memory info (in GB) :

             total       used       free     shared    buffers     cached
Mem:           125         68         57          0          0          4
-/+ buffers/cache:         62         63
Swap:            9          0          9

**Comment by twose** [comment]
I'm sorry that I don't quite understand what you said
maybe you need to adjust the config and test it on your own mac, find out the best config for you

**Comment by keshav-boss** [comment]
Thanks @twose for reply.

Can you tell me how do I test whether configured no. of workers are enough?
When to use task worker? and when not to use it?

**Comment by twose** [comment]
if your code is sync blocked or there are not sync blocking code on your application so you should never use task-workers
If your code has both sync-blocking and async non-blocking things, put the async code on worker processes, use task-worker to handle the sync blocking things

> how do I test whether configured no. of workers are enough
it depends on you, you need to observe your CPU usage, memory, request time, etc.
