### ISSUE TITLE
Connection to swoole_http_server hanging

### ISSUE THREAD

**Issue by djiele** [swoole/swoole-src#3294]
[valgrind.log](https://github.com/swoole/swoole-src/files/4582959/valgrind.log)
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
	public function finalize(Server $server, Request $request, Response $response)
	{
		$fp = fopen($this->filename, 'rb');
		$sentLen = 0;
		while(!feof($fp) && false !== ($chunk = fread($fp, 8192))) {
			$sentLen += strlen($chunk);
			$sentOK = $response->write($chunk);
			if(!$sentOK) {
				echo 'Something went wrong', PHP_EOL;
				break;
			}
		}
		$response->end();
		$this->bodySent = true;
		echo 'close sent ', $sentLen,' bytes of ', $this->filesize, PHP_EOL;
		fclose($fp);

	}
```
Note that if i echo a char + linefeed right after each $response->write($data) and after $response->end() everything is OK, but nagging the console is not a clean solution in my opinion. It goes the same for $server->send($fd, $data). According to my tests, problem occurs after 160000 chars sent to the browser.

2. What did you expect to see?
The request fully served

3. What did you see instead?
Browser and PHP scripts waiting for data infinitely

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.0RC1
Built => Apr 24 2020 08:12:34
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1e-dev  xx XXX xxxx
http2 => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.display_errors => On => On
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
swoole.use_shortname => On => On

swoole_async

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.0RC1
Built => Apr 24 2020 11:36:41
debug => enabled
trace_log => enabled
mysqlnd => enabled
async_redis => enabled

5. What is your machine environment used (including version of kernel & php & gcc) ?
Intel I9 14 cores, 32Gb RAM
Windows 10 / WSL2 running Ubuntu 20.04 LTS
Linux rozhenko 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.3.11 (cli) (built: Nov 17 2019 15:03:13) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies

gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by djiele** [comment]
[valgrind.log](https://github.com/swoole/swoole-src/files/4582914/valgrind.log)

**Comment by matyhtf** [comment]
Please use the chrome dev-tool to debug and send the error message here.

**Comment by djiele** [comment]
Hi, 
problem is that i have no answer from server, just browser saying "pending"
![image](https://user-images.githubusercontent.com/40306999/81267810-56b4f900-9047-11ea-9e5a-c6255be077c4.png). 
As i said for output less than +/- 160000 bytes all is fine. What i don't understand is why if i put echos arround the response::write i got the full response from server
```php
	public function finalize(Server $server, Request $request, Response $response)
	{
		$fp = fopen($this->filename, 'rb');
		$sentLen = 0;
		while(!feof($fp) && false !== ($chunk = fread($fp, 8192))) {
			$sentLen += strlen($chunk);
			echo "magic\n"; //magical trick
			$sentOK = $response->write($chunk);
			echo "magic\n"; //magical trick, buffer is flushed
			if(!$sentOK) {
				echo 'Something went wrong', PHP_EOL;
				break;
			}
		}
		$response->end();
		$this->bodySent = true;
		echo 'close sent ', $sentLen,' bytes of ', $this->filesize, PHP_EOL;
		fclose($fp);

	}
```

**Comment by djiele** [comment]
I also should note that the issue does not happen when the server is in SSL mode. Hoping this will help...

**Comment by djiele** [comment]
Here is a trace of the issue. The script output a 30Mb file by chunk of 1Mb
```php
	
	public function sendChunked(Server $server, Request $request, Response $response)
	{
		$fp = fopen($this->filename, 'rb');
		$sentLen = 0;
		$loops = 0;
		while(!feof($fp) && false !== ($chunk = fread($fp, 1024*1024))) {
			$sentLen += strlen($chunk);
			$sentOK = $response->write($chunk);
			if(!$sentOK) {
				echo 'Something went wrong', PHP_EOL;
				echo 'Err ', $server->getLastError(), PHP_EOL;
				break;
			}
		}
		$response->end();
		$this->bodySent = true;
		echo 'close sent ', $sentLen,' bytes of ', $this->filesize, PHP_EOL;
		fclose($fp);
	}
```
Server config:
[server-config.php.txt](https://github.com/swoole/swoole-src/files/4598962/server-config.php.txt)
Trace:
[response-write-30mb.log](https://github.com/swoole/swoole-src/files/4598955/response-write-30mb.log)

**Comment by matyhtf** [comment]
Check if the Response::write() method returned false. 

Try enable the `send_yield` option

**Comment by djiele** [comment]
Hi sorry for my late response. Well, Response::write() always return true and send_yield option doesn't help. I tried many things to figure out what was happening and my conclusion is that sockets under Windows WSL2 are not reliable. 
Send() errors happen when looping with small packets of 256 bytes, most of the time EAGAIN. So unsent bytes are buffered, but the buffer never get emptied. `swReactor_add_write_event(reactor, socket);` seems to never get fired. So i tried :
` if (swBuffer_append(buffer, ptr, n) < 0)
        {
            return SW_ERR;
        }
       swReactor_wait_write_buffer(reactor, socket); // force buffer processing
`
The problem is that chunks are the same size that the first time they were sent, so `send()` fails again and the connection hang.
There may be also a speed problem because sending little packets enclosed in printfs
`
printf("somestring\n");
send();
printf("somestring\n")
`
there is no send() error as if printfs slow the process and the kernel has time to send packets

I guess Windows WSL has a low rank in the list of supported environments, but it may be a challenging task to fix the issues.

**Comment by matyhtf** [comment]
Are you sure you are using wsl2? Or wsl1?  There is indeed such a problem under wsl1.

Under wsl1 is a known issue, Try switching Server mode to SWOOLE_BASE

```php
$server = new Swoole\Server("0.0.0.0", 9501, SWOOLE_BASE);
```

**Comment by djiele** [comment]
My bad! I thought i was running WSL2, but it's indeed WSL1. WSL 2 will be released to public this summer with W10 20H1, so i close the issue.
