### ISSUE TITLE
\Swoole\Server::getWorkerId() shoudld be static

### ISSUE THREAD

**Issue by kenashkov** [swoole/swoole-src#3301]
As per #2793 I think \Swoole\Server::getWorkerId() should be static. Currently in v4.5.0 it is dynamic.
Thanks

**Comment by twose** [comment]
@matyhtf thought that static methods should not be provided, some frameworks do not want to expose the existence of `Swoole\Server`, it is invisible unless you can get the instance.

**Comment by twose** [comment]
it is an opinion that the ability to restrain is also a kind of ability

**Comment by kenashkov** [comment]
Hi,
I understand the considerations of not exposing the $server with Server::getInstance() and the removal of the method, but my point in #2793 is to have access just to the worker ID. This will not allow for any actions on the server like stopping it or changing anything.

The reason I keep going back to this is that the worker ID is like the OS pid.  While $server may not be exposed we can not hide the fact that there are workers in the same way like we can not hide the fact the script is running on some OS and this OS has processes and these processes have IDs.

A static Server::getWorkerId() is equivalent to getmypid(). I find it very useful to know the worker ID (for example for error reporting, locking and others). Currently instead of worker ID I use PID but when the worker is restarted he PID changes and this doesnt give much info...

**Comment by twose** [comment]
@matyhtf It seems that the static `getWorkerId` method is reasonable

**Comment by matyhtf** [comment]
This is different from getpid, which is the operating system level, it is part of the process. workerId is only related to the `$server` object and must depend on `Swoole\Server` environment.

This static method will break our API design principles, and it does not require low-level support, can be implemented using PHP code.

The workerId is just a static variable. You can save it in a private variable of a custom class and provide a static method to get its value.

```php
class MyServer 
{
    private static $workerId = -1;

    static function setWorkerId(Swoole\Server $server) {
        self::$workerId = $server;
    }

    static function getWorkerId() {
        return self::$workerId;
    }
}

$server->on('WorkerStart', function ($serv, $workerId) {
    MyServer::setWorkerId($serv);
    var_dump(MyServer::getWorkerId());
});
```

**Comment by kenashkov** [comment]
Hi,
I understand this but speaking about API consistency we have Coroutine::XXX() static methods meaning that the Coroutine API is statically exposed thus every piece of code/library be it part of a framework or not can be made coroutine aware, while a library has to be part of a framework to be Worker aware. This seems inconsistent to me. In order a library to know the worker ID it must be dependent on a specific framework. We cant have a pure library. Or the $worker_id has to be injected in some way (which is not the case for example with $coroutine_id - it can always be retrieved and no need to be injected or pulled from a custom framework).

The reason I keep coming back to this is that Swoole has persistent memory model, meaning that in the ordinary PHP it really doesnt matter much the PID as every request has clean memory. In Swoole on the other hand the workers have state and for example for error reporting and debuggin the Worker ID matters a lot. Knowing the worker ID from the error message from the library I can connect to the given worker and inspect the memory state (given the needed methods for that are provided).
