### ISSUE TITLE
Channel pop call with timeout

### ISSUE THREAD

**Issue by erodriguezds** [swoole/swoole-src#3304]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
I have a coroutine/channel based consumer, and a Swoole HTTP server. Every HTTP request generates a job wich is pushed into the consumer channel. Inside the consumer, if I pop a job with NO timeout, it works fine. However, if a specify a timeout, the program crashes as soon as a job is pushed into the channel.
```php
<?php
$PORT = (int) ( getenv('PORT') ?: 80 );
$http = new Swoole\HTTP\Server("0.0.0.0", 80);
$channel = new Swoole\Coroutine\Channel(1000);

// Consumer
go(function() use ($channel){
    while(true) {
        $data = $channel->pop(5000); // 5 seconds ?
        var_dump($data);
    }
});

$http->on('request', function ($request, $response) use($channel) {
    $channel->push($request->get);
    $response->end('<h1>200 Success</h1>');
});

echo "Starting HTTP server on port {$PORT}...\n";
$http->start();
```

2. What did you expect to see?
I just expect to pop messages from a channel using a timeout, without the program crashing.

3. What did you see instead?
The program crashes with the following message:
```
[2020-05-07 21:43:27 $7063.0]   WARNING swManager_check_exit_status: worker#3[pid=7071] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.5.0, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.0
Built => Apr 26 2020 18:19:23
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
http2 => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ?
I'm using Docker on Windows 10. The Docker image I'm using is: phpswoole/swoole:4.5.0-php7.3

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by twose** [comment]
Your code is illegal, It just bypassed the check of Swoole kernel, now we have banned this behavior

correct code:
```php
$channel = new Swoole\Coroutine\Channel(1000);

$PORT = (int) (getenv('PORT') ?: 9501);
$http = new Swoole\HTTP\Server("0.0.0.0", $PORT);

$http->on('workerStart', function () use ($channel) {
    while (true) {
        $data = $channel->pop(5); // 5 seconds
        var_dump($data);
    }
});

$http->on('request', function ($request, $response) use ($channel) {
    $channel->push($request->get);
    $response->end('<h1>200 Success</h1>');
});

echo "Starting HTTP server on port {$PORT}...\n";
$http->start();
```

**Comment by erodriguezds** [comment]
Thank you guys for your prompt support.
