### ISSUE TITLE
nikic/php-parser 解析器内存耗尽导致进程退出

### ISSUE THREAD

**Issue by 729343861** [swoole/swoole-src#3306]
Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in /www/wwwroot/pro/vendor/nikic/php-parser/lib/PhpParser/Parser/Php5.php on line 1817
[2020-05-08 06:16:05 $4263.0]	WARNING	swManager_check_exit_status: worker#31[pid=20342] abnormal exit, status=0, signal=11

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
