### ISSUE TITLE
Is there any way to delete only read event or only write event from a socket?

### ISSUE THREAD

**Issue by codercms** [swoole/swoole-src#3309]
For now the Event API (http://wiki.swoole.com/#/event?id=del) provides the ability to only delete all callbacks from a socket.
But when it becomes necessary to remove only read event or only write event, you have to do the following:

```php
$hasRead = Event::isset($fd, SWOOLE_EVENT_READ);

// want to remove only SWOOLE_EVENT_WRITE: Event::del($fd, SWOOLE_EVENT_WRITE);
Event::del($fd);

if ($hasRead) {
   // need to add SWOOLE_EVENT_READ back
   Event::add($fd, $readCallback, null, SWOOLE_EVENT_READ);
}
```

The `Event::set` method (http://wiki.swoole.com/#/event?id=set) cannot be used for this purpose, because it ignores null.

**Comment by matyhtf** [comment]
You don't need to delete the callback, you only need to adjust the event type. Unset events only occupy memory and will not be triggered.
