### ISSUE TITLE
【swoole-1.7.17】swoole进程，虚拟内存占用过大，实际使用内存小？有问题么 謝謝

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#331]
目前猜测是内存池开始预先分配了一大块内存，后续从内存池里拿。。 这块不知道优化下不？一开始请求很低，内存不用分配那么多；后期在缓慢2x扩张 另外， 看top是cache 占用的内存，这种内存是可以回收的，是否存在内存泄露？我也跟进下，先发出来，多谢老大了！ @matyhtf 
<pre>

top - 10:03:51 up 17 days, 14:11,  1 user,  load average: 0.00, 0.02, 0.05
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.4%us,  0.1%sy,  0.0%ni, 99.5%id,  0.1%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  15404796k total, 15245440k used,   159356k free,   127792k buffers
Swap:        0k total,        0k used,        0k free, 13585328k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                             
12852 work      20   0 2649m 9084 2716 S  0.0  0.1   0:15.87 php 

</pre>

**Comment by matyhtf** [comment]
虚拟内存的问题可以忽略，只需要关注实际内存的占用。
