### ISSUE TITLE
Swoole table deletions failing

### ISSUE THREAD

**Issue by geshub** [swoole/swoole-src#3317]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I'm logging the user id of my websocket server in a swoole table.

`      $this->users = new swoole_table(1024 * 10);
        $this->users->column('uid', swoole_table::TYPE_INT, 4);
        $this->users->create();
`

Users are added on the connection open event,
then on the close event I'm simply removing the users from the table

`         if (false === $this->users->del((string)$fd)) {
                echo date('d-m-Y H:i:s') . " | [WS] Can't delete connection id {$fd} from user " . $uid .  " table count is " . $this->users->count() . " table size: " . round(($this->users->getMemorySize()/(1024 * 1024))) . "Mb \n";
            }`

I noticed the rows are not always deleted and after running the server for a while the table keeps growing up. The rows that don't get deleted exists on the table and I only start getting those failures after 2000 connections.
If I set a bigger size for the table I'm getting the error but after more connections.
Is there any sort of locking that could prevent the deletion ?

2. What did you expect to see?
Rows should be deleted each time when calling $this->users->del((string)$fd)

3. What did you see instead?
Some existing rows are not deleted and the table keeps growing up with time.

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.0
Built => May  3 2020 03:49:56
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
2× Intel® Xeon E5 2640v4 CPU - 20C/40T - 2.4 GHz 192 Go DDR4 ECC
Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
CENTOS 7.8

PHP 7.2.30 (cli) (built: May  5 2020 19:25:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.30, Copyright (c) 1999-2018, by Zend Technologies

gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Comment by geshub** [comment]
Just seen version 4.5.1 is out with a fix in table, will try this version first.

**Comment by matyhtf** [comment]
Has been fixed in the new version
