### ISSUE TITLE
Swoft::trigger 执行过程，参数被切换了

### ISSUE THREAD

**Issue by ctfang** [swoole/swoole-src#3319]
版本 swoft 2.0.8   swoole 4.4.5

调用开始
`Swoft::trigger('user.login', $udi)`

报错位置
`
    public function login(EventInterface $event): void
    {
        $uid = $event->getTarget();
        $this->userDao->setOnline($uid);
`
可以看到，我传入的是int类型参数，$event->getTarget()拿到的是MySqlConnection对象报错信息

`
app/Listener/UserListener.php(126): App\\Model\\Dao\\UserDao->setOnline(Object(Swoft\\Db\\Connection\\MySqlConnection))
vendor/swoft/stdlib/src/Helper/PhpHelper.php(56): App\\Listener\\UserListener->login(Object(Swoft\\Event\\Event))
vendor/swoft/event/src/Listener/LazyListener.php(50): Swoft\\Stdlib\\Helper\\PhpHelper::call(Array, Object(Swoft\\Event\\Event))
vendor/swoft/event/src/Manager/EventManager.php(736): Swoft\\Event\\Listener\\LazyListener->handle(Object(Swoft\\Event\\Event))
vendor/swoft/event/src/Manager/EventManager.php(331): Swoft\\Event\\Manager\\EventManager->triggerListeners(Object(Swoft\\Event\\Listener\\ListenerQueue), Ob
vendor/swoft/framework/src/Swoft.php(178): Swoft\\Event\\Manager\\EventManager->trigger(Object(Swoft\\Event\\Event), 459, Array)
app/Model/Dao/TokenDao.php(64): Swoft::trigger('user.login', 459)
`

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by ctfang** [comment]
![image](https://user-images.githubusercontent.com/18717080/81889096-55e70e80-95d5-11ea-88a3-9535aa334371.png)
