### ISSUE TITLE
inconsistency method name

### ISSUE THREAD

**Issue by Atriedes** [swoole/swoole-src#332]
Hi,

I recognize there are few inconsistency method name in swoole

for eaxample ins `swoole_server` class

camelCase format:

```php
public function addProcess(swoole_process $process) {}
```

lowercase format:

```php
public function addtimer($interval) {}
```

snake_case format:

```php
public function connection_info($fd, $from_id = -1) {}
```

I think is better to standardize those method naming or follow current convention (PSR-2) using `camelCase`

**Comment by Atriedes** [comment]
@matyhtf any thought about this?

**Comment by matyhtf** [comment]
This is a historical problem, We can add an alias name.

**Comment by Atriedes** [comment]
what about completely standardize method name in swoole  v2?

**Comment by matyhtf** [comment]
In the next version to do this job.

**Comment by Atriedes** [comment]
Thanks! could please also read this issue https://github.com/swoole/swoole-doc/issues/5
