### ISSUE TITLE
swoole 4.5 静态文件请求bug 返回404

### ISSUE THREAD

**Issue by godblessu** [swoole/swoole-src#3322]
![image](https://user-images.githubusercontent.com/4978287/82030661-5366e080-96cb-11ea-99dd-9dc194582a1b.png)

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
