### ISSUE TITLE
config service static_handler_locations  return error 404

### ISSUE THREAD

**Issue by godblessu** [swoole/swoole-src#3323]
![image](https://user-images.githubusercontent.com/4978287/82031076-e738ac80-96cb-11ea-8987-7134049c3950.png)

swoole version 4.5
return errorerror 404

**Comment by sy-records** [comment]
It's not a bug, the documentation for this configuration has been removed in hyperf v1.3.0.
https://github.com/hyperf/hyperf/commit/e7ed38b550acacd3ad6b5aed0f6fe036facba582

![image](https://user-images.githubusercontent.com/33931153/82036172-23234000-96d3-11ea-84f3-adaddb7b6e3f.png)
