### ISSUE TITLE
在thinkphp5.1中使用,  执行时打印的执行时间有疑问

### ISSUE THREAD

**Issue by huchenghua** [swoole/swoole-src#3325]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```
\Co::set(['hook_flags' => SWOOLE_HOOK_ALL | SWOOLE_HOOK_CURL]);//真正的hook所有类型，包括CURL
```

下面这里调起协程
` go(function () use ($id, $order_id) {
                    $t1 = microtime(true);
                    Leshua::changeStatus($id, $order_id);
                    $t2 = microtime(true);
                    $t3 = round($t2 - $t1, 5);
                    trace("{$t1}--{$t2}" . 'changeStatus:' . $t3, 'changeStatus');
                });`

这里执行了一个thinkphp的model,find查询的时候打印的时间不正常
```
 public static function changeStatus($id = null, &$order_id)
    {
        $t1 = microtime(true);
        $model = new OrderCallbackLeshua();
        $t4 = microtime(true);
        //取出一个订单
        if ($id) {
            $notify = $model->find($id);
        } else {
            $notify = $model->where('is_used', 0)->find();
        }
        if (empty($notify)) {
            $t2 = microtime(true);
            $t3 = round($t2 - $t1, 6);
            trace("$t1,$t4,$t2,$t3", __METHOD__);
            return;
        }
}
```
2. What did you expect to see?

每个协程间隔10秒执行的,日志打印的执行时间不应该是1秒以下的吗? 

3. What did you see instead?

打印出来的时间不对,时间不应该是立刻执行完成吗, 怎么是都是同一个时间结束的
```
[2020-05-17T01:34:45+08:00][ app\common\logic\Leshua::changeStatus ] 1589650485.2811,1589650485.2811,1589650485.3347,0.053596
app\common\logic\Leshua::changeStatus
[2020-05-17T01:34:45+08:00][ app\common\logic\Leshua::changeStatus ] 1589650475.2593,1589650475.2593,1589650485.3349,10.075558
app\common\logic\Leshua::changeStatus
[2020-05-17T01:34:45+08:00][ app\common\logic\Leshua::changeStatus ] 1589650465.2363,1589650465.2404,1589650485.335,20.098744
app\common\logic\Leshua::changeStatus
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.1
Built => May 16 2020 22:10:40
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.1e-fips 11 Feb 2013
http2 => enabled
pcre => enabled
zlib => 1.2.3
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

centos 6

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
