### ISSUE TITLE
协程下如何遍历所有websocket连接用户的fd，给所有用户推送

### ISSUE THREAD

**Issue by hkargv** [swoole/swoole-src#3332]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
$this->server->connections 遍历所有websocket连接用户的fd，给所有用户推送

print_r($request);
                    print_r($ws);
                    print_r($server);  没有关于这一块的

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
