### ISSUE TITLE
Swoole\Coroutine\Http\Server does not support $server->connections

### ISSUE THREAD

**Issue by hkargv** [swoole/swoole-src#3333]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Swoole\Coroutine\Http\Server does not support $server->connections

2. What did you expect to see?

How can i send messages to other connections in Coroutine websocket server

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by matyhtf** [comment]
Save connection objects to php array
