### ISSUE TITLE
DTLS协议，UDP socket端口不释放

### ISSUE THREAD

**Issue by wk331100** [swoole/swoole-src#3334]
环境：Centos7.4,  PHP7.3.16, Swoole4.5.0RC1
问题：开启DTLS服务，服务端UDP Socket 不是释放， 这种情况如何解决？

[root@localhost dnsapi]# ss -s
Total: 2845 (kernel 3009)
TCP:   21 (estab 6, closed 1, orphaned 0, synrecv 0, timewait 0/0), ports 0

Transport Total     IP        IPv6
*	  3009      -         -        
RAW	  1         0         1        
UDP	  1095      1093      2        
TCP	  20        13        7        
INET	  1116      1106      10       
FRAG	  0         0         0        

ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47345                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47345                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47345                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47345                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47345                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47345                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47345                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47099                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47099                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47099                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47099                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47099                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47099                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47099                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47099                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47099                
ESTAB      0      0                                                                                                 127.0.0.1:pds                                                                                                             127.0.0.1:47099

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
