### ISSUE TITLE
Swoole\Coroutine\Http\Client can't use UNIX_SOCK to connect

### ISSUE THREAD

**Issue by hkargv** [swoole/swoole-src#3336]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Server:
try{
    $server = new Swoole\WebSocket\Server($ip, 3000, SWOOLE_PROCESS, SWOOLE_SOCK_TCP|SWOOLE_SSL);
    $server->addListener('/tmp/qot_websocket_server.sock', null, SWOOLE_SOCK_UNIX_STREAM);
}catch (Exception $e){
    die();
}
$server->set([
    'daemonize' => true,
    'pid_file' => '/tmp/qot_websocket_server.pid',
    'log_file' => '/tmp/qot_websocket_server.log',
    'worker_num' => 2,
    'ssl_cert_file' => __DIR__ . '/../config/fullchain.pem',
    'ssl_key_file' => __DIR__ . '/../config/privkey.pem',
]);
$server->on('WorkerStart', function(Swoole\WebSocket\Server $server, $worker_id){

});
$server->on('open', function(Swoole\WebSocket\Server $server, Swoole\Http\Request $request){
    
});
$server->on('request', function(Swoole\Http\Request $request, Swoole\Http\Response $response) {
    $response->status('302');
    $response->header('Location', 'https://www.chapuwu.com/');
    $response->end("");
});
$server->on('message', function(Swoole\WebSocket\Server $server, Swoole\WebSocket\Frame $frame){
    wlog($frame->data);
    foreach ($server->connections as $fd){
        if($fd == $frame->fd){ //自己
            continue;
        }
        if(! $server->isEstablished($frame->fd)){
            continue;
        }
        $server->push($fd, $frame->data);
    }
});
$server->on('close', function(Swoole\WebSocket\Server $server, $fd, $reactorId){
    
});
$server->start();

Client:
Swoole\Coroutine::create(function(){
    $client = new Swoole\Coroutine\Http\Client("/tmp/qot_websocket_server.sock", null, false);
    //$client = new Swoole\Coroutine\Http\Client("192.168.2.128", 3000, true);
    /* $client->set([
        'ssl_verify_peer' => false,
        'ssl_allow_self_signed' => false,
        'ssl_cert_file' => PATH_CFG.'fullchain.pem',
        'ssl_key_file' => PATH_CFG.'privkey.pem',
    ]); */
    if($client->upgrade("/")){
        while(true) {
            $s = $client->push($GLOBALS['data']);
            var_dump($s);
            $client->close();
            break;
        }
    }else{
        echo 3;
    }
});
It get " echo 3"

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
