### ISSUE TITLE
Repeated Coroutine ID assignment in websocket server

### ISSUE THREAD

**Issue by Reasno** [swoole/swoole-src#3338]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```php
<?php

$server = new Swoole\WebSocket\Server("0.0.0.0", 9502);

$server->addProcess(new Swoole\Process(function () {
    Co\run(function () {
        while (true) {
            $client = new Swoole\Coroutine\Http\Client("127.0.0.1", 9502);
            $ret = $client->upgrade("/");
            if ($ret) {
                $client->push("hello");
                co::sleep(1);
            }
        }
    });
}));

$server->on('message', function (Swoole\WebSocket\Server $server, $frame) {
    $id = Co::getCid();
    echo "receive from fd: {$frame->fd} in cid: {$id};\n";
    $server->disconnect($frame->fd);
});

$server->on('close', function ($ser, $fd) {
    sleep(2);
    $id = Co::getCid();
    echo "close fd: {$fd} in cid: {$id}; \n";
});

$server->start();
```

2. What did you expect to see?

each onMessage and onClose call should run in a different coroutine with a different coroutine id.

3. What did you see instead?

Two consecutive calls share the same coroutine id. In `hyperf/socketio-server` I tried to clean up Redis in onClose. This behavior would cause Redis connections to be shared between different onClose calls, which in turn crash the server.

```
receive from 1, cid: 1;
receive from 2, cid: 1;
close 1 in cid: 2
receive from 3, cid: 3;
close 2 in cid: 2
receive from 4, cid: 3;
close 3 in cid: 4
receive from 5, cid: 5;
close 4 in cid: 4
receive from 6, cid: 5;
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.4.17

5. What is your machine environment used (including version of kernel & php & gcc) ?

php7.3 on macOS.

**Comment by huanghantao** [comment]
@Reasno 

```php
$server->set([
    'worker_num' => 1,
]);
```

**Comment by Reasno** [comment]
> @Reasno
> 
> The coroutine id can be repeated in different processes.
> 
> ```
> $server->set([
>     'worker_num' => 1,
> ]);
> ```

you are right.. I am having trouble to reproduce, but I do have this:

```
[2020-05-21 18:07:09 $51013.0]	WARNING	swProcessPool_wait: worker#0 abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.4.17, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

```

**Comment by huanghantao** [comment]
@Reasno 
My macos can run this script normally. May be you should execute `make clean`, then recompile.

**Comment by Reasno** [comment]
I will comeback with another example.
