### ISSUE TITLE
QUESTION: HTTP request buffer?

### ISSUE THREAD

**Issue by ValiDrv** [swoole/swoole-src#3344]
Is there a way for Swoole to process incoming HTTP requests in a job queue fashion, where job bursts over the number of started workers would be buffered and still get processed instead of returning "no workers available" error?

I have a system that starts bursts of jobs, then waits 10-60 sec for replies, and these bursts are sometimes bigger than the number of available workers.

**Comment by twose** [comment]
put the `Swoole\Http\Request/Response` objects to a queue
