### ISSUE TITLE
官方是否会支持mongodb协程化？

### ISSUE THREAD

**Issue by phper666** [swoole/swoole-src#3347]
目前我们在项目里面大量用到mongodb，都是在task里面使用，但是发现每个task进程占用的内存特别高，初始的时候是130M左右，处理几次任务后会变成180M左右。开一百个task的时候，内存会猛涨，开得少又处理不过来。官方是否会支持mongodb协程化呢？

**Comment by twose** [comment]
**[自动回复] 为了Github社区各国友人的参与理解和问题的存档检索所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
