### ISSUE TITLE
websocket 服务器使用listen监听 tcp 9501端口,client只发送hello world ,显示包的长度为1.6个G

### ISSUE THREAD

**Issue by lvzhihuisyn** [swoole/swoole-src#3364]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by lvzhihuisyn** [comment]
只是监听一个端口, 发现1201错误码,length居然达到了1.6g,请问怎么检查错误!

**Comment by matyhtf** [comment]
请使用 http/websocket 客户端与 websocket 服务器通信，而不是用 tcp client

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
