### ISSUE TITLE
swoole 1.8.10版本编译带enable-openssl后，swoole_http_client发https请求coredump(100%复现)

### ISSUE THREAD

**Issue by jaki2012** [swoole/swoole-src#3366]
centos版本：7

glibc 2.17

openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

coredump信息：
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/services/TSF2_qidian-1.0/runtime/php/bin/php...done.
[New LWP 25174]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `php translate_svr worker process                                              '.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fbf6d269046 in __strcmp_sse42 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-20.el7_2.x86_64 glibc-2.17-196.tl2.3.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-10.el7.x86_64 libcom_err-1.42.9-7.el7.x86_64 libcurl-7.29.0-25.el7.centos.x86_64 libgcc-4.8.5-5.tl2.x86_64 libidn-1.28-4.el7.x86_64 libjpeg-turbo-1.2.90-5.el7.x86_64 libpng12-1.2.50-7.el7_2.x86_64 libselinux-2.2.2-6.el7.x86_64 libssh2-1.4.3-10.el7.x86_64 libstdc++-4.8.5-5.tl2.x86_64 libtool-ltdl-2.4.2-21.el7_2.x86_64 nspr-4.10.8-2.el7_1.x86_64 nss-3.19.1-19.el7_2.x86_64 nss-softokn-3.16.2.3-13.el7_1.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 nss-sysinit-3.19.1-19.el7_2.x86_64 nss-util-3.19.1-4.el7_1.x86_64 openldap-2.4.40-8.el7.x86_64 openssl-libs-1.0.2k-19.tl2.x86_64 pcre-8.32-15.el7.x86_64 sqlite-3.7.17-8.el7.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0x00007fbf6d269046 in __strcmp_sse42 () from /lib64/libc.so.6
#1  0x00007fbf6f209999 in lh_insert () from /usr/local/services/TSF2_qidian-1.0/runtime/openssl/lib/libcrypto.so.1.0.0
#2  0x00007fbf6f18708b in OBJ_NAME_add () from /usr/local/services/TSF2_qidian-1.0/runtime/openssl/lib/libcrypto.so.1.0.0
#3  0x00007fbf6a8cd973 in SSL_library_init () from /lib64/libssl.so.10
#4  0x00007fbf62c381b9 in swSSL_init () at /root/ft_local/swoole-src-1.8.10-stable/src/protocol/SSL.c:91
#5  0x00007fbf62c38581 in swSSL_get_context (method=0, cert_file=0x0, key_file=0x0) at /root/ft_local/swoole-src-1.8.10-stable/src/protocol/SSL.c:151
#6  0x00007fbf62c29f0e in swClient_enable_ssl_encrypt (cli=cli@entry=0x9a69800) at /root/ft_local/swoole-src-1.8.10-stable/src/network/Client.c:161
#7  0x00007fbf62c2a26b in swClient_onWrite (reactor=<optimized out>, event=0x7fffbdf6a8f0) at /root/ft_local/swoole-src-1.8.10-stable/src/network/Client.c:903
#8  0x00007fbf62c2389c in swReactorEpoll_wait (reactor=0x92e84f0, timeo=<optimized out>) at /root/ft_local/swoole-src-1.8.10-stable/src/reactor/ReactorEpoll.c:268
#9  0x00007fbf62c337e3 in swWorker_loop (factory=factory@entry=0x92e6050, worker_id=worker_id@entry=1)
    at /root/ft_local/swoole-src-1.8.10-stable/src/network/Worker.c:496
#10 0x00007fbf62c3083c in swManager_spawn_worker (factory=0x92e6050, worker_id=1) at /root/ft_local/swoole-src-1.8.10-stable/src/network/Manager.c:679
#11 0x00007fbf62c31445 in swManager_loop_sync (factory=0x92e6050) at /root/ft_local/swoole-src-1.8.10-stable/src/network/Manager.c:539
#12 swManager_start (factory=factory@entry=0x92e6050) at /root/ft_local/swoole-src-1.8.10-stable/src/network/Manager.c:183
#13 0x00007fbf62c208da in swFactoryProcess_start (factory=0x92e6050) at /root/ft_local/swoole-src-1.8.10-stable/src/factory/FactoryProcess.c:86
#14 0x00007fbf62c27269 in swServer_start (serv=serv@entry=0x92e5c20) at /root/ft_local/swoole-src-1.8.10-stable/src/network/Server.c:648
#15 0x00007fbf62c082fc in zim_swoole_http_server_start (ht=<optimized out>, return_value=0x9225e88, return_value_ptr=<optimized out>, this_ptr=0x9223748, 
    return_value_used=<optimized out>) at /root/ft_local/swoole-src-1.8.10-stable/swoole_http_server.c:1352
#16 0x00007fbf62ee7a95 in xdebug_execute_internal (current_execute_data=0x7fbf6f7e8ef0, fci=0x0, return_value_used=0)
    at /usr/local/services/cov_plugin/CoverageTest/xdebug-2.4.0/xdebug.c:2043
#17 0x00000000008391fa in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>) at /data/web_deployment/download/php-5.5.25/Zend/zend_vm_execute.h:552
#18 0x000000000082ac80 in execute_ex (execute_data=0x7fbf6f7e8ef0) at /data/web_deployment/download/php-5.5.25/Zend/zend_vm_execute.h:363
#19 0x00007fbf62ee7022 in xdebug_execute_ex (execute_data=0x7fbf6f7e8ef0) at /usr/local/services/cov_plugin/CoverageTest/xdebug-2.4.0/xdebug.c:1890
#20 0x00000000008398d6 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fbf6f7e8d00) at /data/web_deployment/download/php-5.5.25/Zend/zend_vm_execute.h:584
#21 0x000000000082ac80 in execute_ex (execute_data=0x7fbf6f7e8d00) at /data/web_deployment/download/php-5.5.25/Zend/zend_vm_execute.h:363
#22 0x00007fbf62ee7022 in xdebug_execute_ex (execute_data=0x7fbf6f7e8d00) at /usr/local/services/cov_plugin/CoverageTest/xdebug-2.4.0/xdebug.c:1890
#23 0x00000000007b6949 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /data/web_deployment/download/php-5.5.25/Zend/zend.c:1327
#24 0x00000000007581ca in php_execute_script (primary_file=0x7fffbdf6e570) at /data/web_deployment/download/php-5.5.25/main/main.c:2525
#25 0x0000000000868aec in do_cli (argc=2, argv=0x2eba5d0) at /data/web_deployment/download/php-5.5.25/sapi/cli/php_cli.c:994
#26 0x0000000000869288 in main (argc=2, argv=0x2eba5d0) at /data/web_deployment/download/php-5.5.25/sapi/cli/php_cli.c:1378

swoole版本version

swoole

swoole support => enabled
Version => 1.8.10
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by twose** [comment]
升级

**Comment by matyhtf** [comment]
已经不维护了，请使用 1.10.5 版本，或者使用 4.5.2
