### ISSUE TITLE
Swoole\Redis\Server::format( Server::STRING,"xxxxxx") 无法独立使用问题

### ISSUE THREAD

**Issue by zqe** [swoole/swoole-src#3367]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
<?php

declare(strict_types=1);

use Swoole\Server;
use Swoole\Redis\Server as RedisServer;
$server = new Server("0.0.0.0",8000);


$port = $server->addlistener('0.0.0.0',6379);


$port->on('receive',function($server, $fd, $rid, $data) {
	$server->send($fd,RedisServer::format(RedisServer::STRING,"1234"));
});

$server->start();
```
```
[2020-06-05 01:20:10 $4663.0]	WARNING	swManager_check_exit_status: worker#0[pid=4665] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.5.0, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
```

I need to implement a custom redis server service on 'swoole \ server \ port'

In the response encapsulation step, you want to borrow the 'swoole \ redis \ server:: format' method

A segment error will occur, causing the whole swoole process to be interrupted

2. What did you expect to see?
```php 
Server::format(Server::STRING,"111")
```
I hope that 'server:: format' can work independently when called as a static method

By viewing swoole_ redis_ server.cc Find the format that depends on in the foramt function_ This problem is caused by buffer initialization in the 'swoole \ redis \ server:: start' startup phase

3. What did you see instead?

略

4. What version of Swoole are you using (show your `php --ri swoole`)?

略

5. What is your machine environment used (including version of kernel & php & gcc) ?

略

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
