### ISSUE TITLE
Swoole\Redis\Server::format(Server::string, "xxxxx") cannot be used independently

### ISSUE THREAD

**Issue by zqe** [swoole/swoole-src#3368]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
<?php

declare(strict_types=1);

use Swoole\Server;
use Swoole\Redis\Server as RedisServer;
$server = new Server("0.0.0.0",8000);


$port = $server->addlistener('0.0.0.0',6379);


$port->on('receive',function($server, $fd, $rid, $data) {
	$server->send($fd,RedisServer::format(RedisServer::STRING,"1234"));
});

$server->start();
```
```
[2020-06-05 01:20:10 $4663.0]	WARNING	swManager_check_exit_status: worker#0[pid=4665] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.5.0, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
```

I need to implement a custom redis server service on 'swoole \ server \ port'

In the response encapsulation step, you want to borrow the 'swoole \ redis \ server:: format' method

A segment error will occur, causing the whole swoole process to be interrupted

2. What did you expect to see?
```php 
Server::format(Server::STRING,"111")
```
I hope that 'server:: format' can work independently when called as a static method

By viewing swoole_ redis_ server.cc Find the format that depends on in the foramt function_ This problem is caused by buffer initialization in the 'swoole \ redis \ server:: start' startup phase

4. What version of Swoole are you using (show your `php --ri swoole`)?

```

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.0
Built => May  7 2020 14:04:04
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs
