### ISSUE TITLE
swoole/library  error

### ISSUE THREAD

**Issue by 729343861** [swoole/swoole-src#3370]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

![image](https://user-images.githubusercontent.com/35519825/83964095-f41c7a80-a8dc-11ea-884c-86bb6ee41f12.png)

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

![image](https://user-images.githubusercontent.com/35519825/83964127-14e4d000-a8dd-11ea-8512-c5dd24236e04.png)

5. What is your machine environment used (including version of kernel & php & gcc) ?

centos7.4  php7.2

**Comment by huanghantao** [comment]
@729343861 

you should disable swoole.enable_library in php.ini:

```ini
swoole.enable_library = off
```

**Comment by 729343861** [comment]
Shouldn't it need to be turned on, dizzy

**Comment by huanghantao** [comment]
If you need to use the Library in Composer, you should close it. If you need to use it in a Swoole extension way, you need to open it.

**Comment by 729343861** [comment]
thank ， Does the redis connection pool create a pool in each process

**Comment by huanghantao** [comment]
> thank ， Does the redis connection pool create a pool in each process

yes

**Comment by 729343861** [comment]
How to clean up invalid connections in connection pool
