### ISSUE TITLE
Custom process cannot be killed

### ISSUE THREAD

**Issue by 729343861** [swoole/swoole-src#3371]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Daemonize = 1 after the daemons are started, kill the main process, but the custom single process is not killed

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

![image](https://user-images.githubusercontent.com/35519825/83965074-950e3400-a8e3-11ea-94ac-16ac799a6fa9.png)

5. What is your machine environment used (including version of kernel & php & gcc) ?

centos7.4 php7.2

**Comment by huanghantao** [comment]
Ask questions by format.
