### ISSUE TITLE
Ability to construct `Swoole\Http\Request` yourself

### ISSUE THREAD

**Issue by hvt** [swoole/swoole-src#3373]
Hello there, love this project. Was wondering about this though: for testing purposes, I'm creating `Swoole\Http\Request` objects myself. Looking at the [source](https://github.com/swoole/swoole-src/blob/master/swoole_http_request.cc#L296), I see that all attributes of the class are `public`. So this all works just fine:

```php
$request = new Swoole\Http\Request();
$request->server['request_method'] = 'POST';
$request->server['request_uri'] = '/hello-world';
$request->header['authorization'] = 'bearer foobar-token';
$request->get['foo'] = 'bar';
```

However, the code I am actually testing, fetches the request's body, i.e. does `$request->rawContent()`. And that results in this error:

> Swoole\Http\Request::rawContent(): http request is unavailable (maybe it has been ended)

Is there any way to set the content of a HTTP request manually?

**Comment by huanghantao** [comment]
@hvt 
Maybe you shouldn't use `Swoole\Http\Request` directly, we don't have provide a body-like property for `Swoole\Http\Request`.

**Comment by hvt** [comment]
Mmm, it would be inconvenient to create a wrapper just for the purpose of testing code depending on the request.

Would it be possible to create a `setRawContent()`, or to provide the content through the class' (currently non-existing) constructor?

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/pull/3938
