### ISSUE TITLE
Question: async Swoole client

### ISSUE THREAD

**Issue by idealogica** [swoole/swoole-src#3378]
I have used Swoole\Client\Async for async SSL TCP connections. Recently I've noticed that it is deprecated. So I have the following questions:

- How long will it be supported? 
- Is there any reason to replace it by a coroutine client? 
- What coroutine client is better to replace Swoole\Client\Async SSL (Co\Socket or Swoole\Coroutine\Client)?
- Does Swoole\Coroutine\Client support SSL?
- Is there any example which demonstrates the best way to migrate?

Thank you!

**Comment by matyhtf** [comment]
Q: How long will it be supported?
------
A: We just don’t develop new features, but if there are bugs, we will fix them, there is no end time

**Comment by matyhtf** [comment]
Does Swoole\Coroutine\Client support SSL?
----
Yes, Here is the example

```php
Co\run(function(){
  $client = new Swoole\Coroutine\Client(SWOOLE_SOCK_TCP | SWOOLE_SSL);
  if (!$client->connect('127.0.0.1', 9501, 0.5))
  {
      echo "connect failed. Error: {$client->errCode}\n";
  }
  $client->send("hello world\n");
  echo $client->recv();
  $client->close();
});
```

**Comment by matyhtf** [comment]
Is there any reason to replace it by a coroutine client?
-----
Async client will cause callback hell, Coroutine client is easier to use

**Comment by idealogica** [comment]
> ## Q: How long will it be supported?
> 
> A: We just don’t develop new features, but if there are bugs, we will fix them, there is no end time

Then why the documentation has been removed from the docs section? https://www.swoole.co.uk/docs/module. For example https://www.swoole.co.uk/docs/modules/swoole-client/methods async client methods list gives 404 error. We still use this client, so it would be good to keep the Swoole\Client\Async documentation. 

Also recent versions of ide-helper package don't include Swoole\Client\Async helpers. So it looks like Swoole\Client\Async is gone :(

**Comment by idealogica** [comment]
> ## Does Swoole\Coroutine\Client support SSL?
> 
> Yes, Here is the example
> 
> ```
> Co\run(function(){
>   $client = new Swoole\Coroutine\Client(SWOOLE_SOCK_TCP | SWOOLE_SSL);
>   if (!$client->connect('127.0.0.1', 9501, 0.5))
>   {
>       echo "connect failed. Error: {$client->errCode}\n";
>   }
>   $client->send("hello world\n");
>   echo $client->recv();
>   $client->close();
> });
> ```

Are there any options to control SSL behaviour? No such options mentioned in the docs. I'm using the following with Swoole\Client\Async:
```
                'ssl_verify_peer' => false,
                'ssl_allow_self_signed' => true,
                'ssl_verify_peer_name' => false,
                'ssl_host_name' => $this->requestUri->getHost(),
                'verify_peer' => false,
                'allow_self_signed' => true,
                'verify_peer_name' => false,
                'timeout' => 20,
                'debug_mode'=> DEBUG,
                'keep_alive' => false,
                'socket_buffer_size' => 16 * 1024 * 1024,
```
Are they supported?

**Comment by doubaokun** [comment]
@idealogica although async clients will be maintained and fixing the bugs, but we would recommend move to the coroutine client which is much more simple.

These SSL settings are still supported as is. We will update the docs soon.

**Comment by idealogica** [comment]
Thank you so much for the responses and for updating the docs! :)

**Comment by idealogica** [comment]
I have migrated successfully btw ;)

**Comment by sauriio** [comment]
@idealogica, how do you implement the changes from one client to another? I'm trying to use the coroutine client, but i was somehow depending from the events, I think you only need one connection to the server.

**Comment by idealogica** [comment]
@sauriio I just have replaced all the calls. If you still need to run coroutine client in async mode, I guess you can call its methods inside a coroutine and call defer() to simulate event callback:
```
go(function () {
        $client->connect();
        defer(function () {
            echo "connected!";
        });
});
```
