### ISSUE TITLE
swoole子进程0信号是什么场景下面产生的

### ISSUE THREAD

**Issue by salterping** [swoole/swoole-src#3379]
1、swoole版本信息
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.5
Built => Mar 21 2020 23:30:42
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.0l  10 Sep 2019
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
2、问题描述
主进程监控子进程信号，$result = swoole_process::wait(false)，有时候，子进程$result会接收到这样子的信号：{"pid":6,"code":0,"signal":0}，请问下，这个0信号是什么情况下面才会发送的，正常都是接收到15的信号。

**Comment by twose** [comment]
自己退出了 没有收到信号
