### ISSUE TITLE
http客户端 download 方法的一点建议

### ISSUE THREAD

**Issue by wayren-chan** [swoole/swoole-src#3380]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```
go(function () {
    $host = 'www.swoole.com';
    $client = new \Swoole\Coroutine\Http\Client($host, 443, true);
    $client->set(['timeout' => -1]);
    $client->setHeaders([
        'Host' => $host,
        'User-Agent' => 'Chrome/49.0.2587.3',
        'Accept' => '*',
        'Accept-Encoding' => 'gzip'
    ]);
    $ret = $client->download('/aas', __DIR__ . '/logo.svg');
    
    print_r($ret); //这里会返回true;
    if ($client->statusCode!=200) {
		shell_exec('rm -rf '.__DIR__ . '/logo.svg');
		$ret = false;
    }  else {
        $ret = true;
    }

    print_r($ret); //这里才是我想要的返回结果
    return $ret;
});
```

2. What did you expect to see?

我在想，能不能 咱们在download的时候就判断下statusCode，如果statusCode状态异常就直接返回false

3. What did you see instead?

目前来说请求一个不存在的远程文件，这个方法也会返回成功，会保存一个无法识别的文件到本地，我只有在这个方法执行后再获取statusCode，如果statusCode不为200则删除文件，但是很麻烦。

--------------------------------
系统版本：centos8
Swoole版本：4.4.16
php版本：7.4

**Comment by matyhtf** [comment]
有些用户可能是希望保留非 200 结果页面的，底层删除并不合适。

另外，我们做了一些改进，在 http 连接被拒绝时，不再生成空文件。

**Comment by wayren-chan** [comment]
> 有些用户可能是希望保留非 200 结果页面的，底层删除并不合适。
> 
> download 返回 true 只表示服务器返回了响应内容。而 statusCode 是更高层的逻辑状态。
> 
> 另外，我们做了一些改进，在 http 连接被拒绝时，不再生成空文件。

对 就是不要生成空文件
