### ISSUE TITLE
Getting swFactoryProcess_finish (ERROR 1004) send byte failed, connection closed error how to check if connection is closed or not

### ISSUE THREAD

**Issue by keshav-boss** [swoole/swoole-src#3386]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
I am using swoole TCP server for receving data packet over TCP by devices.
Script as below
=============================================================
$serv = new swoole_server("0.0.0.0", self::PORT_NO);
$serv->set(array(
'worker_num' => 16,
'daemonize' => false,
'heartbeat_check_interval' => 30,
'heartbeat_idle_time' => 1800,
'log_file' => $filepath
));
$serv->on('connect', function ($serv, $fd) {
    $tcp_client = $serv->connection_info($fd);
});
$serv->on('receive', function ($serv, $fd, $from_id, $data) {    
	// check if connection exist or not
	if($serv->connection_info($fd))								
	{
		$serv->send($fd, $send_data);
	}	
});
$serv->on('close', function ($serv, $fd) {
   // echo "Client: Close.\n";			
  //$this->log_raw_string("on closed\tconnection\t".$fd);			
  $tcp_client = $serv->connection_info($fd);
  $this->log_raw_string_new("on closed\tconnection\t".$fd."\tconnection_info  \t".json_encode($tcp_client));			
});
$serv->on('shutdown', function () {
});
$serv->start();
=============================================================

**Getting 1004 error when connection is closed**

[2020-06-12 15:58:46 *96050.7]	NOTICE	swFactoryProcess_finish (ERROR 1004): send 10 byte failed, because connection[fd=774] is closed.

I am logging when on close callback. getting Reactor id is 7 i.e. greater than 0 means connection is close by client.
2020-06-12 15:58:46	on closed	connection	774	connection_info	{"server_port":9131,"server_fd":3,"socket_type":1,"remote_port":13784,"remote_ip":"42.106.193.76","reactor_id":7,"connect_time":1591957697,"last_time":1591957725,"close_errno":0}

**My question is how do I check if connection $fd is closed or not?
If it return false I wont send data over connection and won't get error.
I tried using both below fucntions to check connection closed but they always return true even if connection is closed.**
$serv->exist($fd)
$serv->connection_info($fd)

**Note: Using Swoole Version => 1.9.21**

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

swoole support => enabled
Version => 1.9.21
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

Linux version 2.6.32-504.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) ) #1 SMP Wed Oct 15 04:27:16 UTC 2014

PHP 5.6.31 (cli) (built: Sep 14 2017 18:31:45)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

CPU info :

Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 32
On-line CPU(s) list: 0-31
Thread(s) per core: 2
Core(s) per socket: 8
Socket(s): 2
NUMA node(s): 2
Vendor ID: GenuineIntel
CPU family: 6
Model: 62
Stepping: 4
CPU MHz: 3300.183
BogoMIPS: 6599.00
Virtualization: VT-x
L1d cache: 32K
L1i cache: 32K
L2 cache: 256K
L3 cache: 25600K
NUMA node0 CPU(s): 0-7,16-23
NUMA node1 CPU(s): 8-15,24-31

Memory info (in GB) :

         total       used       free     shared    buffers     cached

Mem: 125 68 57 0 0 4
-/+ buffers/cache: 62 63
Swap: 9 0 9

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by twose** [comment]
Please see: https://github.com/swoole/swoole-src/blob/master/SUPPORTED.md
