### ISSUE TITLE
Questions: heartbeat_check_interval and worker_num

### ISSUE THREAD

**Issue by keshav-boss** [swoole/swoole-src#3387]
I am using Swoole Version 1.9.21 in my project, Using TCP/Server.
I have following questions:

1. What is the difference between heartbeat_check_interval and heartbeat_idle_time?
2. When connection between server and client will be closed? After exceeding which time?
3. If receving data packets at frequeny of 10 secs, 1 minute and 3 minute on same listener, then what value of  heartbeat_check_interval and heartbeat_idle_time should I set in order to maintain active connection and close old idle or unused connections?
4. What is max value for worker_num?
5. What error will be received or cons if configured more workers than max value?
6. What is max value for task_worker_num?
7. What error will be received or cons if configured more task workers than max value?

**Comment by huanghantao** [comment]
> I am using Swoole Version 1.9.21 in my project, Using TCP/Server.
> I have following questions:
> 
> 1. What is the difference between heartbeat_check_interval and heartbeat_idle_time?
> 2. When connection between server and client will be closed? After exceeding which time?
> 3. If receving data packets at frequeny of 10 secs, 1 minute and 3 minute on same listener, then what value of  heartbeat_check_interval and heartbeat_idle_time should I set in order to maintain active connection and close old idle or unused connections?
> 4. What is max value for worker_num?
> 5. What error will be received or cons if configured more workers than max value?
> 6. What is max value for task_worker_num?
> 7. What error will be received or cons if configured more task workers than max value?

1. heartbeat_check_interval represents how often to check the connection for data; `heartbeat_idle_time` represents the maximum amount of time the connection is allowed to be idle, if the connection does not send data beyond the `heartbeat_idle_time `, the server closes the connection.

2. After `heartbeat_idle_time`.

3. I didn't catch your meaning.

4. `4294967295`.

5. No error will be received because we have limited the maximum value to `4294967295`.

6. `4294967295`.

7. No error will be received because we have limited the maximum value to `4294967295`.

**Comment by keshav-boss** [comment]
Thanks @huanghantao.

Need more clarity for following questions

Regarding max value for worker_num, documentation says **"set the worker_num to the value from one time to four times of CPU cores"** Why so?

Regarding 3rd question If receiving data packets at different frequencies means some packet at every 10 secs, some packet at every 1 minute some at every 3 minute on same listener, then what value of heartbeat_check_interval and heartbeat_idle_time should I set?

**Comment by huanghantao** [comment]
> Thanks @huanghantao.
> 
> Need more clarity for following questions
> 
> Regarding max value for worker_num, documentation says **"set the worker_num to the value from one time to four times of CPU cores"** Why so?
> 
> Regarding 3rd question If receiving data packets at different frequencies means some packet at every 10 secs, some packet at every 1 minute some at every 3 minute on same listener, then what value of heartbeat_check_interval and heartbeat_idle_time should I set?

Because too many processes are created, will increases the overhead of process switching. But the actual worker_num you should test based on your scene, there is no standard answer.

May be you should set `heartbeat_idle_time` to `3` minutes.

**Comment by keshav-boss** [comment]
Thanks @huanghantao for answering my queries.
