### ISSUE TITLE
How can I set an outgoing interface for HTTP/Client?

### ISSUE THREAD

**Issue by nezarati** [swoole/swoole-src#3388]
How can I set an outgoing interface for `HTTP/Client`? I know for this, I need to have `getSocket`, but unfortunately `Swoole\Coroutine\HTTP\Client` doesn't give me `getSocket`
Now I don't know how I can have its?

I used this way but it didn't work:
```php
$client = new Swoole\Coroutine\HTTP\Client;
$socket = $client->getSocket();
socket_bind($socket, $outgoingNetworkInterfaceAddress);
```
Thanks for cooperation

**Comment by huanghantao** [comment]
@nezarati Swoole do not provide a method for http client to export socket.

**Comment by nezarati** [comment]
So for changing outgoing interface what can I do?

**Comment by huanghantao** [comment]
For now, you can't do that.

**Comment by huanghantao** [comment]
> So for changing outgoing interface what can I do?

```php
$client->set([
    'bind_address' => $bindAddress,
]);
```
