### ISSUE TITLE
Handle Back-Pressure in WebSocket Server

### ISSUE THREAD

**Issue by ljfreelancer88** [swoole/swoole-src#3389]
Hi, I'm just wondering how to implement back-pressure in swoole websocket server.

Reference: https://web.dev/websocketstream/

**Comment by doubaokun** [comment]
The link you have provided has actually provided several approach to handle back-pressure.

Github issues only accept bug report or feature requests. Please join the Slack channel for general questions, community members may answer your questions: https://docs.google.com/forms/d/e/1FAIpQLScqpkPJeFG-ss3P-KhFECDSNLyo1iKmU1DToIQX9YRWbuetjw/viewform
