### ISSUE TITLE
multiple processes in same event loop

### ISSUE THREAD

**Issue by rbro** [swoole/swoole-src#3392]
Hello,

I am new to Swoole and trying to find an example of how to run multiple processes in the same event loop.  For example, let's say in the same event loop, I want to:

- run a websocket server
- run a timer every 1 second
- poll a redis message queue and send data to clients connected to the websocket server
- run an external process and send data to clients connected to the websocket server

Do you have an example or documentation of how multiple processes like this can be run through Swoole in the same event loop?  I see how I can run each of the above items individually, but not seeing how I can do all of them in the same event loop.

Thanks,
Ryan

**Comment by twose** [comment]
set `enable_coroutine` to false and create coroutine by yourself, or you can not fork process on coroutine

**Comment by huanghantao** [comment]
@rbro 

```php
<?php

use Swoole\Coroutine;
use Swoole\Coroutine\Channel;
use Swoole\Coroutine\Http\Client;
use Swoole\WebSocket\Server;

use function Swoole\Coroutine\run;

$workerNum = 3;

$pool = new Swoole\Process\Pool($workerNum);

$pool->on("WorkerStart", function ($pool, $workerId) {
    if ($workerId === 0) {
        $server = new Server('127.0.0.1', 9501);
        $server->on("message", function ($serv, $frame) {
            var_dump($frame);
        });
        $server->start();
    } elseif ($workerId === 1) {
        run(function () {
            $client = new Client('127.0.0.1', 9501);
            while (!$client->upgrade('/')) {}
            while (true) {
                Coroutine::sleep(1);
                // poll redis queue, and get data
                $data = 'data';
                $client->push($data);
            }
        });
    } else {
        // run a process
        run(function () {
            $client = new Client('127.0.0.1', 9501);
            while (!$client->upgrade('/')) {}
            while (true) {
                Coroutine::sleep(2);
                $client->push('a process');
            }
        });
    }
});

$pool->start();
```

**Comment by rbro** [comment]
Thank you, so I would need to define the number of workers in advance, and then start each based on the $workerId?  Is there a way to add a worker directly so that you don't have to define the number of workers in advance and basically do a switch on the $workerId?

Could I also do this via Coroutines?  I saw documentation about a Coroutine Server, but I wasn't able to run a Swoole\WebSocket\Server in a coroutine as I got an error "eventLoop has already been created" when I tried to start the websocket server.

**Comment by huanghantao** [comment]
> Thank you, so I would need to define the number of workers in advance, and then start each based on the $workerId? Is there a way to add a worker directly so that you don't have to define the number of workers in advance and basically do a switch on the $workerId?
> 
> Could I also do this via Coroutines? I saw documentation about a Coroutine Server, but I wasn't able to run a Swoole\WebSocket\Server in a coroutine as I got an error "eventLoop has already been created" when I tried to start the websocket server.

if you want to use `Swoole\Process\Pool`，you must set the worker num. If you don't want to set worker num, you can use `Swoole\Process`, https://www.swoole.co.uk/docs/modules/swoole-process

**Comment by rbro** [comment]
Thanks, do you have an example of using `Swoole\Process` to start multiple processes?  I only found an example to start 1 process.

Also, I found this using Coroutines - https://github.com/swoole/swoole-src/blob/master/examples/coroutine/websocket/co_server.php.  What would it be used for?

**Comment by huanghantao** [comment]
> Thanks, do you have an example of using `Swoole\Process` to start multiple processes? I only found an example to start 1 process.
> 
> Also, I found this using Coroutines - https://github.com/swoole/swoole-src/blob/master/examples/coroutine/websocket/co_server.php. What would it be used for?

```php
<?php

use Swoole\Coroutine;
use Swoole\Coroutine\Http\Client;
use Swoole\Coroutine\Http\Server;
use Swoole\Http\Request;
use Swoole\Http\Response;
use Swoole\Process;

$proc1 = new Process(function (Process $process) {
    $server = new Server("127.0.0.1", 9501);
    $server->handle('/websocket', function (Request $request, Response $response) {
        $response->upgrade();
        while (true) {
            $frame = $response->recv();
            var_dump($frame);
        }
    });
    $server->start();
}, false, 0, true);

$proc2 = new Process(function (Process $process) {
    $client = new Client('127.0.0.1', 9501);
    $client->set(['timeout' => 5]);
    assert($client->upgrade('/websocket'));
    while (true) {
        Coroutine::sleep(1);
        // poll redis queue, and get data
        $data = 'data';
        $client->push($data);
    }
}, false, 0, true);

$proc3 = new Process(function (Process $process) {
    $client = new Client('127.0.0.1', 9501);
    $client->set(['timeout' => 5]);
    assert($client->upgrade('/websocket'));
    while (true) {
        Coroutine::sleep(2);
        $client->push('a process');
    }
}, false, 0, true);

$proc1->start();
$proc2->start();
$proc3->start();

$proc1->wait();
$proc2->wait();
$proc3->wait();
```

**Comment by huanghantao** [comment]
> Thanks, do you have an example of using `Swoole\Process` to start multiple processes? I only found an example to start 1 process.
> 
> Also, I found this using Coroutines - https://github.com/swoole/swoole-src/blob/master/examples/coroutine/websocket/co_server.php. What would it be used for?

Maybe you want us to provide a method like:

```php
Process\pool->add(function () {
});
```

**Comment by rbro** [comment]
Yes, adding a pool add function may help.  I have previously used Ratchet and React, where you create an event loop, add items onto that event loop, and run it.  A couple examples are:

- https://github.com/reactphp/event-loop#usage
- http://socketo.me/docs/push#tying_it_together

Is creating multiple processes in a pool the equivalent of running multiple items on the event loop?  Or is there a different way to do this with swoole?

How does your above code with processes differ from using coroutines such as the example on https://www.swoole.co.uk/docs/modules/swoole-coroutine#example?

Also, is there a way to run your above code without running wait 3 times?  With react in those examples above, you run your loop at the end with 1 call.

Thanks again for your help.
