### ISSUE TITLE
http get json's async loop

### ISSUE THREAD

**Issue by karabest** [swoole/swoole-src#3393]
Hello, I recently installed swoole. We need to make a lot of API requests without having to wait for response. We need to make around 80,000 different API requests total, 10 requests each second (because we have a limit), but without blocking I/O. There are very few examples, unfortunately, of how to process a huge amount of data from http get requests asynchronously. How Swoole can help us accomplish this task?

Basic logic: send HTTP GET requests (10) each second -> while waiting for response, process responses that came earlier -> repeat

**Comment by huanghantao** [comment]
The Swoole HTTP Server will create a separate coroutine for each HTTP request to handle, which will not cause the IO to block.

**Comment by huanghantao** [comment]
Swoole version >= `v4.5.0`:

```php
$http = new Swoole\Http\Server("0.0.0.0", 9501);

$http->on('request', function ($request, $response) {
    var_dump($request->getContent());
});

$http->start();
```

Swoole version < `v4.5.0`:

```php
$http = new Swoole\Http\Server("0.0.0.0", 9501);

$http->on('request', function ($request, $response) {
    var_dump($request->rawContent());
});

$http->start();
```

**Comment by karabest** [comment]
thank you for the response

we used file_get_contents("api-url") before, what is the equivalent in Swoole HTTP Server?

**Comment by huanghantao** [comment]
```php
<?php

use Swoole\Coroutine;

use function Swoole\Coroutine\run;

Coroutine::set(['hook_flags' => SWOOLE_HOOK_FILE]);

run(function () {
    file_get_contents("api-url");
});
```

**Comment by huanghantao** [comment]
> thank you for the response
> 
> we used file_get_contents("api-url") before, what is the equivalent in Swoole HTTP Server?

```php
<?php

use Swoole\Coroutine;

use function Swoole\Coroutine\run;

Coroutine::set(['hook_flags' => SWOOLE_HOOK_FILE]);

run(function () {
    file_get_contents("api-url");
});
```

**Comment by karabest** [comment]
how do we integrate it with the Http Server? I don't get the overall logic

**Comment by huanghantao** [comment]
> how do we integrate it with the Http Server? I don't get the overall logic

```php
use Swoole\Coroutine;

use function Swoole\Coroutine\run;

Coroutine::set(['hook_flags' => SWOOLE_HOOK_FILE]);

$http = new Swoole\Http\Server("0.0.0.0", 9501);

$http->on('request', function ($request, $response) {
    var_dump($request->rawContent());
    file_get_contents("api-url");
});

$http->start();
```

**Comment by karabest** [comment]
create Swoole Http Server -> configure on request event -> initiate request to Swoole Http Server -> Swoole Http Server performs  on request event and returns response
Is this logic correct?

**Comment by huanghantao** [comment]
> create Swoole Http Server -> configure on request event -> initiate request to Swoole Http Server -> Swoole Http Server performs on request event and returns response
> Is this logic correct?

yes

**Comment by karabest** [comment]
how do I trigger on request event?

**Comment by huanghantao** [comment]
> how do I trigger on request event?

I don't see what you mean?

**Comment by karabest** [comment]
create Swoole Http Server -> configure on request event -> THIS PART (initiate request to Swoole Http Server) -> Swoole Http Server performs on request event and returns response

**Comment by huanghantao** [comment]
> create Swoole Http Server -> configure on request event -> THIS PART (initiate request to Swoole Http Server) -> Swoole Http Server performs on request event and returns response

Any HTTP client can trigger a request.

**Comment by karabest** [comment]
Swoole Coroutine HTTP Client will work?

**Comment by huanghantao** [comment]
> Swoole Coroutine HTTP Client will work?

yes

**Comment by karabest** [comment]
Thank you so much, I will try it out
