### ISSUE TITLE
Proxy http -> async tcp client

### ISSUE THREAD

**Issue by yuskamal** [swoole/swoole-src#3405]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
I want to implement proxy server  as http server from clients and forwarding to Async TCP Server that only accept one connection (Connection Oriented)
I have try example app from https://github.com/swoole/proxy-server/blob/master/tcp-proxy.php
but it's always open new connection for every http client that  sending request

2. What did you expect to see?

For every client that sending http request just using same connection of TCP Client

3. What did you see instead?
please take a look the image
![SwooleProxy](https://user-images.githubusercontent.com/30690463/85092612-40888400-b214-11ea-9482-66400e6e7191.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Jun  3 2020 07:06:03
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1g  21 Apr 2020
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?
PHP 7.4.7 (cli) (built: Jun 12 2020 07:44:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies

Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by eldadfux** [comment]
@yuskamal Can you share your Swoole server and TCP socket connection code?

**Comment by yuskamal** [comment]
@eldadfux I can't continue .... it's need swoole async that was separated from swoole core
and when I try to install swoole async it was never success.
curently i continue this requerenment with workerman ... and it's to be done
thanks
