### ISSUE TITLE
404 Pages on the Swoole Docs

### ISSUE THREAD

**Issue by eldadfux** [swoole/swoole-src#3406]
Some links on the docs site are returning 404 error: https://www.swoole.co.uk/docs/modules/swoole-http-request

This are the broken links:
Swoole\HTTP\Request->rawContent
Swoole\HTTP\Request->getContent
Swoole\HTTP\Request->getData

![image](https://user-images.githubusercontent.com/1297371/85103210-e507c780-b20e-11ea-9eea-d867a9f6c99b.png)

**Comment by doubaokun** [comment]
Thanks for reporting, the links are fixed.

**Comment by sy-records** [comment]
@doubaokun hi,I also found two 404 pages.

https://www.swoole.co.uk/docs/modules/swoole-coroutine-client-set
https://www.swoole.co.uk/docs/modules/swoole-coroutine-client-isConnected
