### ISSUE TITLE
FastCGI Client not executing properly

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#3413]
So I was executing FastCGI client in swoole 4.5.2 this way

```php
$server->on('request', function (swoole_http_request $req, swoole_http_response $res){
    switch ($req->server['request_uri']) {
        case '/adminer':
            $res->end(
                \Swoole\Coroutine\FastCGI\Client::call(
                     '127.0.0.1:9000', 
                     '/location/adminer.php',
                     ['who' => 'Swoole']
                 )
             };
             break;
        default:
            break;
    }
});
```

What I get

![Screenshot from 2020-06-21 17-13-46](https://user-images.githubusercontent.com/13552004/85221068-89426780-b3e3-11ea-84d4-426ecf92231c.png)

This is what is expected

![Screenshot from 2020-06-21 17-18-53](https://user-images.githubusercontent.com/13552004/85221079-92cbcf80-b3e3-11ea-93ad-156266269e50.png)

I tried to catch with this, but no error was emitted

```php
try {
    $client = new Swoole\Coroutine\FastCGI\Client('127.0.0.1', 9000);
    $request = (new Swoole\FastCGI\HttpRequest())
        ->withScriptFilename('/location/adminer.php')
        ->withMethod('POST')
        ->withBody(['who' => 'Swoole']);
    $response = $client->execute($request);
    $body = $response->getBody();
    $res->end(     $body                   );
    
} catch (\Swoole\Coroutine\FastCGI\Client\Exception $exception) {
    $res->end("Error: {$exception->getMessage()}\n");
}
```

**Comment by matyhtf** [comment]
Please use chrome dev-tools to debug, whether there is a style file that fails to load

**Comment by jobs-git** [comment]
@matyhtf its not POSTing or GETing the correct page properly, so I could not login from there as well, I think these are not only style problems.
