### ISSUE TITLE
MacBook Pro install swoole

### ISSUE THREAD

**Issue by saiye** [swoole/swoole-src#3414]
**1. What did you do? If possible, provide a simple script for reproducing the error.**

MacBookPro install swoole 
dowload 
https://github.com/swoole/swoole-src/archive/master.zip

cd swoole-src-master

 /usr/bin/phpize
./configure --with-openssl-dir=/usr/local/ssl --enable-sockets --enable-http2 --enable-mysqlnd --with-php-config=/usr/bin/php-config

sudo make

**2. What did you expect to see?**
swoole installl success

**3. What did you see instead?**

usr/bin/phpize
./configure --with-openssl-dir=/usr/local/ssl --enable-sockets --enable-http2 --enable-mysqlnd --with-php-config=/usr/bin/php-config

The results of:

creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common
checking if g++ PIC flag -fno-common works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin19.3.0 dyld
(cached) (cached) checking how to hardcode library paths into programs... immediate
configure: creating ./config.status
config.status: creating config.h

run sudo make

I get the following error！

dsymutil .libs/swoole.so || :
creating swoole.la
(cd .libs && rm -f swoole.la && ln -s ../swoole.la swoole.la)
/bin/sh /Users/langrensha0022/Downloads/swoole-src-master/libtool --mode=install cp ./swoole.la /Users/langrensha0022/Downloads/swoole-src-master/modules
cp ./.libs/swoole.so /Users/langrensha0022/Downloads/swoole-src-master/modules/swoole.so
cp ./.libs/swoole.lai /Users/langrensha0022/Downloads/swoole-src-master/modules/swoole.la
----------------------------------------------------------------------
Libraries have been installed in:
   /Users/langrensha0022/Downloads/swoole-src-master/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `DYLD_LIBRARY_PATH' environment variable
     during execution

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

run  make test

I get the following error！
=====================================================================
TIME END 2020-06-22 02:40:58

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   58
---------------------------------------------------------------------

Number of tests :  946                 0
Tests skipped   :  946 (100.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :    0 (  0.0%) (  0.0%)
---------------------------------------------------------------------
Time taken      :   53 seconds
=====================================================================

This report can be automatically sent to the PHP QA team at
http://qa.php.net/reports and http://news.php.net/php.qa.reports
This gives us a better understanding of PHP's behavior.
If you don't want to send the report immediately you can choose
option "s" to save it.	You can then email it to qa-reports@lists.php.net later.
Do you want to send this report now? [Yns]: yes

**4. What version of Swoole are you using (show your `php --ri swoole`)?**

**5. What is your machine environment used (including version of kernel & php & gcc) ?**

php -v
PHP 7.3.11 (cli) (built: Apr 17 2020 19:14:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies

 gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix

**Comment by matyhtf** [comment]
This shows that the compilation has been successful, do not perform tests, which has many dependencies on the environment.

**Comment by saiye** [comment]
sudo make install
Installing shared extensions:     /usr/lib/php/extensions/no-debug-non-zts-20180731/
cp: /usr/lib/php/extensions/no-debug-non-zts-20180731/#INST@26715#: Read-only file system
make: *** [install-modules] Error 1
langrensha0022@langrensha0022deMacBook-Pro swoole-src-master % sudo make install
/bin/sh /Users/langrensha0022/Downloads/swoole-src-master/libtool --mode=install cp ./swoole.la /Users/langrensha0022/Downloads/swoole-src-master/modules
cp ./.libs/swoole.so /Users/langrensha0022/Downloads/swoole-src-master/modules/swoole.so
cp ./.libs/swoole.lai /Users/langrensha0022/Downloads/swoole-src-master/modules/swoole.la
----------------------------------------------------------------------
Libraries have been installed in:
   /Users/langrensha0022/Downloads/swoole-src-master/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `DYLD_LIBRARY_PATH' environment variable
     during execution

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
Installing shared extensions:     /usr/lib/php/extensions/no-debug-non-zts-20180731/
cp: /usr/lib/php/extensions/no-debug-non-zts-20180731/#INST@26920#: Read-only file system



mkdir  /usr/local/lib/php/extension/
sudo cp ./.libs/swoole.so  /usr/local/lib/php/extension/swoole.so
sudo cp ./.libs/swoole.lai  /usr/local/lib/php/extension/swoole.la


php.ini

extension_dir ="/usr/local/lib/php/extension/"

extension=/usr/local/lib/php/extension/swoole.so

php -m
I get the following error

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extension/swoole.so' (tried: /usr/local/lib/php/extension/swoole.so (dlopen(/usr/local/lib/php/extension/swoole.so, 0x0009): symbol '__zval_ptr_dtor' not found, expected in flat namespace by '/usr/local/lib/php/extension/swoole.so'), /usr/local/lib/php/extension///usr/local/lib/php/extension/swoole.so.so (dlopen(/usr/local/lib/php/extension///usr/local/lib/php/extension/swoole.so.so, 0x0009): dlopen(): file not found: /usr/local/lib/php/extension///usr/local/lib/php/extension/swoole.so.so)) in Unknown on line 0

**Comment by matyhtf** [comment]
There may be multiple versions of PHP in your system, please check whether the PHP environment is the same

**Comment by saiye** [comment]
I don't know what to do. Can you give me a clue?

**Comment by matyhtf** [comment]
```shell
which php
```

show output

**Comment by saiye** [comment]
which php-config
/usr/bin/php-config
which php       
/usr/bin/php

**Comment by matyhtf** [comment]
I can't reproduce it, you try to clean up the project and recompile?

```shell
make clean
/usr/bin/php --clean
/usr/bin/phpize
./configure --with-openssl-dir=/usr/local/ssl --enable-sockets --enable-http2 --enable-mysqlnd --with-php-config=/usr/bin/php-config
make -j 8 install
```

**Comment by saiye** [comment]
### **I'm trying to run command**
make clean
sudo ./configure --with-openssl-dir=/usr/local/ssl --enable-sockets --enable-http2 --enable-mysqlnd --with-php-config=/usr/bin/php-config

sudo make -j 8 install

### **The results are as follows**

/bin/sh /Users/langrensha0022/Downloads/swoole-src-master/libtool --mode=install cp ./swoole.la /Users/langrensha0022/Downloads/swoole-src-master/modules
cp ./.libs/swoole.so /Users/langrensha0022/Downloads/swoole-src-master/modules/swoole.so
cp ./.libs/swoole.lai /Users/langrensha0022/Downloads/swoole-src-master/modules/swoole.la

Libraries have been installed in:
   /Users/langrensha0022/Downloads/swoole-src-master/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `DYLD_LIBRARY_PATH' environment variable
     during execution

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.

Installing shared extensions:     /usr/lib/php/extensions/no-debug-non-zts-20180731/
cp: /usr/lib/php/extensions/no-debug-non-zts-20180731/#INST@87106#: Read-only file system
make: *** [install-modules] Error 1
make: *** Waiting for unfinished jobs....
Installing header files:          /usr/include/php/


### **It seems to be related to permissions, so I copy the swoole.so file to this directory and edit php.ini**

mkdir /usr/local/lib/php/extension/
sudo cp ./.libs/swoole.so /usr/local/lib/php/extension/swoole.so
sudo cp ./.libs/swoole.lai /usr/local/lib/php/extension/swoole.la

php.ini

extension_dir ="/usr/local/lib/php/extension/"

extension=/usr/local/lib/php/extension/swoole.so

 php -m

The result is still failure.

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extension/swoole.so' (tried: /usr/local/lib/php/extension/swoole.so (dlopen(/usr/local/lib/php/extension/swoole.so, 0x0009): symbol '__zval_ptr_dtor' not found, expected in flat namespace by '/usr/local/lib/php/extension/swoole.so'), /usr/local/lib/php/extension///usr/local/lib/php/extension/swoole.so.so (dlopen(/usr/local/lib/php/extension///usr/local/lib/php/extension/swoole.so.so, 0x0009): dlopen(): file not found: /usr/local/lib/php/extension///usr/local/lib/php/extension/swoole.so.so)) in Unknown on line 0

**I don't know what to do**

**Comment by twose** [comment]
show the output of `/usr/bin/phpize`

**Comment by saiye** [comment]
```
 ls -l /usr/bin/phpize
-rwxr-xr-x  1 root  wheel  4545 12 14  2019 /usr/bin/phpize
ls -l /usr/bin/php   
-rwxr-xr-x  1 root  wheel  14132944  5 28 08:26 /usr/bin/php
ls -l /usr/bin/php-config
-rwxr-xr-x  1 root  wheel  4033  4 18 10:19 /usr/bin/php-config
```

**Comment by saiye** [comment]
```
 php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' 
(tried: /usr/local/lib/php/extension/swoole.so (dlopen(/usr/local/lib/php/extension/swoole.so, 0x0009):
 open("/usr/local/lib/php/extension/swoole.so", O_RDONLY) failed with errno=13), 
/usr/local/lib/php/extension/swoole.so.so (dlopen(/usr/local/lib/php/extension/swoole.so.so, 0x0009): open("/usr/local/lib/php/extension/swoole.so.so", O_RDONLY) failed with errno=13)) in Unknown on line 0
PHP 7.3.11 (cli) (built: Apr 17 2020 19:14:14) ( NTS )

```

**Comment by twose** [comment]
execute `/usr/bin/phpize` and show it's output

it's like this:
```
$ phpize
Configuring for:
PHP Api Version:         20190128
Zend Module Api No:      20190128
Zend Extension Api No:   420190128
```

**Comment by saiye** [comment]
```
execute /usr/bin/phpize
Configuring for:
PHP Api Version:         20160303
Zend Module Api No:      20160303
Zend Extension Api No:   320160303
Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.

```

**Comment by saiye** [comment]
```
/usr/bin/phpize
Configuring for:
PHP Api Version:         20160303
Zend Module Api No:      20160303
Zend Extension Api No:   320160303
```

**Comment by twose** [comment]
Obviously you have overwritten the old PHP (maybe v7.1) with PHP 7.3, but your `phpize` is still the old version

In general, we do not recommend overwriting the PHP that comes with the system, You should install the new version of PHP in the user workspace

**Comment by saiye** [comment]
Thank you for your advice。
This new macbook Pro.   I'm using PHP on the system.  I installed the latest PHP7.4 and it worked perfectly.

**Comment by prakashjoshidmacq** [comment]
export CPPFLAGS="-I/opt/homebrew/include"
export LDFLAGS="-L/opt/homebrew/lib"
