### ISSUE TITLE
Swoole server not following the spec for flow control (WINDOW_UPDATE frames) in HTTP2 mode

### ISSUE THREAD

**Issue by supersmile2009** [swoole/swoole-src#3415]
1. What did you do? If possible, provide a simple script for reproducing the error.
I'm running a gRPC server with Swoole, which requires use of HTTP2. I'm having problems with some endpoints returning large payloads because Swoole seems to not follow the spec for flow control for HTTP2 requests (though TCP flow control is fine).

Generally steps to reproduce are simple.
- Start Swoole server with HTTP2 enabled.
- Send an HTTP2 request to server and return response with payload larger than 64K (default INITIAL_WINDOW_SIZE)
- Observe swoole sending data without waiting for WINDOW_UPDATE frames from the client.

2. What did you expect to see?
I'm expecting Swoole to follow the spec and wait for the WINDOW_UPDATE frames from the client once window is full. See example log file of a request to a grpc server written in Go. It never sends more data than allowed by the client.
[valid_log_go_server.txt](https://github.com/swoole/swoole-src/files/4813304/valid_log_go_server.txt)

3. What did you see instead?
Swoole is not following the spec and sending data frames without waiting for WINDOW_UPDATE.
See an example log file for the same request as in the previous example with Go. This time server is based on Swoole. You can see client is receiving data packets one after another until all the payload (more than 200K) is transferred even though not a single WINDOW_UPDATE was sent by the client.
[invalid_log_swoole_server.txt](https://github.com/swoole/swoole-src/files/4813351/invalid_log_swoole_server.txt)

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Jun 17 2020 19:43:27
coroutine => enabled
debug => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (including version of kernel & php & gcc) ?
```
php -v
PHP 7.4.6 (cli) (built: May 14 2020 10:03:07) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies
```
```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.2.1-9ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2) 
```

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/pull/3486
