### ISSUE TITLE
Allow use of trailers in HTTP1.1 mode

### ISSUE THREAD

**Issue by supersmile2009** [swoole/swoole-src#3417]
Swoole only supports trailers for HTTP2 responses. I know it's even documented, so treat it as a feature request.
It would be nice to see this feature supported in HTTP1.1 to be more compliant with the spec. There are various use cases for this feature.

A workaround if anyone is looking for a temporary solution:
1. Return trailers as headers.
2. Put nginx in front of swoole. Configure nginx to fetch certain headers and add them as trailers with the `add_trailer` directive.
Of course it has its limitation and won't be suitable for certain advanced use cases. So it would be nice to see a proper support for trailers in Swoole.

What version of Swoole are you using (show your `php --ri swoole`)?
```
php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Jun 17 2020 19:43:27
coroutine => enabled
debug => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

**Comment by huanghantao** [comment]
We already support it in `v4.5.3-alpha`, here's an example of how to use it:

```php
$http->on('request', function (Swoole\Http\Request $request, Swoole\Http\Response $response) {
     $response->header('trailer', 'Content-MD5');
     $data = 'hello world';
     $response->write($data);
     $response->trailer('Content-MD5', md5($data));
     $response->end();
 });
```
