### ISSUE TITLE
[QUESTION] How can I detect if Swoole\Coroutine\Client got disconnected?

### ISSUE THREAD

**Issue by ValiDrv** [swoole/swoole-src#3425]
How can I detect if **Swoole\Coroutine\Client** got **disconnected**?
So I can reconnect the client and be able to send commands to it.

**1. What did you do? If possible, provide a simple script for reproducing the error.**

Pseudo code
```
Client is connected to IP and can send/receive commands.
Network dies, cannot ping IP
Network comes back up, can ping IP
Client needs to send a command
- The ->send works client side, but server does not get anything.
- The ->recv is not called, since the server disconnected.
```

Example
```
$client = new Swoole\Coroutine\Client(SWOOLE_SOCK_TCP);
$client->connect($host, $port, $timeout); # Connect OK
go(function () {  # Wait for data
            while (true) {
                $data = $this->recv();
                if ($data === '' || $data === false) {
                    break;
                }
            }
        });
# *** network gets disconnected ***
# Send some data
if ($client->isConnected()) {  # It's TRUE even after the network disconnected
    $r = $client->send(...$data);   # Returns the number of bytes sent, and $client->errCode is 0
}
```

**2. What did you expect to see?**

I expect either:
```
- $client->isConnected() be FALSE
- $client->send(...$data); return FALSE or 0
- $client->errCode  Return some error if the connection was doped.
```

**3. What did you see instead?**
```
- $client->isConnected() = TRUE
- $client->send(...$data); Returns bytes of $data
- $client->errCode = 0
```

**4. What version of Swoole are you using (show your `php --ri swoole`)?**
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => May 29 2020 03:13:35
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
http2 => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

```

**5. What is your machine environment used (including version of kernel & php & gcc) ?**

`phpswoole/swoole:4.5.2-php7.4`

**Comment by twose** [comment]
`isConnected` can only tell you if a connection has been established
`Swoole\Coroutine\Socket->checkLiveness()`, but it doesn't always work
Maybe learning Linux network programming will help you

**Comment by ValiDrv** [comment]
Thank you.
I thought the **Swoole\Coroutine\Client** had built in support for **open_tcp_keepalive**, **tcp_keepidle**, **tcp_keepcount**, **tcp_keepinterval**, assuming it connects to a server that supports it.

It could make a nice feature to have, with an additional **tcp_keepalive_function** which could be called for the health checks (assuming it's different than the standard keep-alive)

**Comment by jobs-git** [comment]
Try to execute a very simple call to client, if it returns data then its up, if not, then its down.

**Comment by ValiDrv** [comment]
That does not work...

**Swoole\Coroutine\Client->send('ping')** will return the bytes written to the socket, even if the socket is not connected.
(if the buffer is full and it tries to flush it, then you get an error.)

**Swoole\Coroutine\Client->recv(-1)** will wait forever in TCP mode. And if the server disconnected without sending the close packets, it will never know it's disconnected.
If you add a `timeout`, you never know what it should be for some requests. 
Picture a MySQL proxy, most queries take under X seconds, but you can have some that take a long time.

So usually, there is a tcp_keepalive which pings the server every X sec, and changes the connected flag on the socket if it does not get a reply in X pings.

Development would be easier if Swoole\Coroutine\Client would be a bit higher level and implement some of these things, and have the onClose/on[Etc.] events (swoole-ext-async does not work with swoole 4.5)
