### ISSUE TITLE
[ENHANCEMENT] WaitGroup initial count & shortcut function

### ISSUE THREAD

**Issue by ValiDrv** [swoole/swoole-src#3428]
Allot of time when we need wait for a coroutine to finish, we already know how many we will have.
It would be nice if the constructor could take an initial count.

So we can have:
```
$wg = new Swoole\Coroutine\WaitGroup(10);
```

Instead of:
```
$wg = new Swoole\Coroutine\WaitGroup();
$wg->add(10);
```

```
class WaitGroup
{
   ....
-    public function __construct()
+    public function __construct(int $count = 0)
    {
        $this->chan = new Channel(1);
+        $this->count = max(0, $count);
    }
   ....
    public function add(int $delta = 1): void
```

It would also be nice to have a built in function so we don't have to manually call the $wg->done(); and $wg->done();

Example:
```
$r = '0';
wait(function() use ($r) {
  go(function () { 
      co::sleep(4); 
      $r.='4'; 
      go(function () { 
        co::sleep(1); $r.='5'; 
      });
  });
  go(function () { co::sleep(3); $r.='3'; });
  go(function () { co::sleep(2); $r.='2'; });
  $r.='1';
});

$ 012345
```

I'm bringing this up, in case this will ever make it in the C++ code.

**Comment by matyhtf** [comment]
Thanks for your advice

1. It’s a good idea to add parameters to the constructor, I’ll add them soon
2. You should use `Swoole\Coroutine\batch()` or `Swoole\Coroutine\parallel()` , see https://github.com/swoole/library/blob/master/src/core/Coroutine/functions.php

**Comment by matyhtf** [comment]
https://github.com/swoole/library/commit/2fb228b8013ed82734b469d4a765c5394a57ffe1

**Comment by ValiDrv** [comment]
awesome, thank you
