### ISSUE TITLE
how to debug swoole web server in PhpStorm?

### ISSUE THREAD

**Issue by scil** [swoole/swoole-src#343]
In 'Run/Debug configurations' , I set up a `PHP Script` config , but  i could not debug OnRequest callback .

I hope ther is a solution to debug it .

**Comment by bixuehujin** [comment]
Did you have xdebug installed and configured correctly?

Take a look the following link for more information:

https://confluence.jetbrains.com/display/PhpStorm/Debugging+PHP+CLI+scripts+with+PhpStorm

**Comment by Atriedes** [comment]
I can debug it nicely using xdebug, maybe your xdebug configuration is invalid

**Comment by scil** [comment]
Thank you very much!  I had forgot to enable xdebug!
