### ISSUE TITLE
Website documentation section section doesn't work

### ISSUE THREAD

**Issue by idealogica** [swoole/swoole-src#3435]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Open https://www.swoole.co.uk/docs/

2. What did you expect to see?
Navigation on the right works

3. What did you see instead?
All links in the right nav block give "Page not found"
Example https://www.swoole.co.uk/docs/modules/swoole-coroutine

4. What version of Swoole are you using (show your `php --ri swoole`)?
-

5. What is your machine environment used (including version of kernel & php & gcc) ?
-

**Comment by doubaokun** [comment]
@idealogica Can you try it again?

**Comment by idealogica** [comment]
It works, thank you!
