### ISSUE TITLE
Missing / Outdated English Docs for Server Compression

### ISSUE THREAD

**Issue by eldadfux** [swoole/swoole-src#3441]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Trying to find docs about gzip and brotli compression.

2. What did you expect to see?

Updated docs and configuration options

3. What did you see instead?

The server configuration page is lacking any information about `http_compression` and `http_compression_level`. I had to dig a bit in the source code and the Chinese website to try and understand how to enable them.

Also no clear idea what is the difference between `http_gzip_level` and `http_compression_level`. While the Chinese docs mention that you need `libz-dev` installed to enable gzip support, nothing mentions you need `libbrotli-dev` to enable brotli. Took me a couple of hours to understand `brotli` package on debian is not enough (C newbie).

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.5.2
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Jul  2 2020 07:29:20
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
http2 => enabled
zlib => 1.2.11
brotli => E16777223/D16777223
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (including version of kernel & php & gcc) ?

php 7.4 Official Docker image running on MacOS

**Comment by doubaokun** [comment]
`http_compression_level` is the replacement of `http_gzip_level`. It is updated on page https://www.swoole.co.uk/docs/modules/swoole-server/configuration

**Comment by eldadfux** [comment]
Thank you! Love this project ❤️
