### ISSUE TITLE
Coroutine::exec executes the exec command with a high probability of freezing, and generates a defunct process

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/swoole-src#3444]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

**testexec.php:**

```php
<?php

use Swoole\Coroutine;
use Swoole\Runtime;

Runtime::enableCoroutine();

// timeout not work
// Coroutine::set([
//     'socket_connect_timeout'    => 3,
//     'socket_read_timeout'       => 3,
//     'socket_write_timeout'      => 3,
//     'socket_dns_timeout'        => 3,
//     'socket_timeout'            => 3,
// ]);

Co\run(function(){
    var_dump(count(Coroutine::exec('exec php -i')));
});
```

**test.sh:**

```shell
#!/bin/bash
while true
do
    php testexec.php
done
```

You can run `./test.sh`

2. What did you expect to see?

Stopped after outputting several times

```
# ps -aux|grep php
root     32315  0.7  0.1 103624 20632 tty5     S    15:02   0:00 php testexec.php
root     32316  0.9  0.0      0     0 tty5     Z    15:02   0:00 [php] <defunct>
root     32319  0.0  0.0  12896  1104 tty4     S    15:02   0:00 grep --color=auto php
```

3. What did you see instead?

No problem

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.5.2 and compile from master

5. What is your machine environment used (including version of kernel & php & gcc) ?

php 7.3.17

**Comment by twose** [comment]
Unable to reproduce on my mac

**Comment by huanghantao** [comment]
@Yurunsoft

You can try this branch [fix-issue-3444](https://github.com/swoole/swoole-src/tree/fix-issue-3444)

**Comment by Yurunsoft** [comment]
It's OK!
