### ISSUE TITLE
求支持动态worker_num

### ISSUE THREAD

**Issue by renzhenguo** [swoole/swoole-src#3450]
同步 IO业务，能否像php-fpm支持动态worker_num，繁忙时开启更多的worker_num，不忙时关掉

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
