### ISSUE TITLE
Abort trap: 6 on MacOS after a websocket disconnect.

### ISSUE THREAD

**Issue by Reasno** [swoole/swoole-src#3451]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Run the socket.io demo : https://github.com/Reasno/socketio-demo.git
```
php bin/hyperf.php start
```
navigate to localhost:9501/index.html.

The client code issues socket.disconnect after 3 seconds.

Then the server exits with `Abort trap: 6` on MacOS.

2. What did you expect to see?

Server keeps running.

3. What did you see instead?

Server exits with `Abort trap: 6` on MacOS.

4. What version of Swoole are you using (show your `php --ri swoole`)?

```ini
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => May 29 2020 15:42:04
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1g  21 Apr 2020
http2 => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777223/D16777223
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
Darwin bogon 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
```
php 7.4

**Comment by Reasno** [comment]
link to https://github.com/hyperf/hyperf/issues/2029

**Comment by huanghantao** [comment]
@Reasno Did you try the master branch? It seems to have been fixed.

**Comment by matyhtf** [comment]
Fixed in new version
