### ISSUE TITLE
Missing HTTP Payload for Delete Requests

### ISSUE THREAD

**Issue by eldadfux** [swoole/swoole-src#3452]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Sent the Swoole HTTP server an HTTP DELETE request with JSON payload.

2. What did you expect to see?

Be able to fetch the JSON payload from the Swoole HTTP Request object same way as with PATCH, POST or PUT methods.

3. What did you see instead?

The request object was missing the payload data. According to this StackOverflow issue the DELETE method should support request payload like POST, PUT or PATCH. This is also the behaviour with NGINX+FPM. 

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Jul  6 2020 13:51:52
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
http2 => enabled
zlib => 1.2.11
brotli => E16777223/D16777223
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

PHP Official Docker image on MacOS

**Comment by huanghantao** [comment]
@eldadfux 

I noticed that PHP doesn't provide a variable like `$_DELETE`, but PHP can get the original HTTP request in the following way:

```php
file_get_contents('php://input')
```

Similarly, Swoole can also get the original request content through the `getData` method:

```php
$server->on('request', function (Swoole\Http\Request $request, Swoole\Http\Response $response) {
    var_dump($request->getData());
});
```

**Comment by eldadfux** [comment]
@huanghantao thanks for your help, after validating this on my server, I can confirm that both `$request->getData()` and `$request->rawContent()` returns the request payload for DELETE requests correctly. `$request->getContent()` seems to return the entire HTTP request in plain text, including method, URI, headers and payload.
