### ISSUE TITLE
[question] How to run code after Server::send() finishes data transfer in SWOOLE_PROCESS mode?

### ISSUE THREAD

**Issue by idealogica** [swoole/swoole-src#3455]
Hi dear Swoole developers,

Unfortunately there is no afterSend event of Swoole TCP server, so I can't close the connection right after the transfer to a client finishes. Would you please explain how to work around?

2. What did you expect to see?
afterSend event support:

```php
$server->on('afterSend', function (Server $s, int $clientId) use  ($server) {
 $server->close($clientId);
});
$server->send($clientId, "DATA");
```

3. What did you see instead?
There is no afterSend event

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Jul  8 2020 19:48:28
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1g  21 Apr 2020
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

Thank you!

**Comment by huanghantao** [comment]
@idealogica 

I don't think this event callback is necessary, maybe you can do it:

```php
$serv->on('receive', function (Server $server, int $clientId, $reactor_id, $data) {
    if ($server->send($clientId, "DATA")) {
        $server->close($clientId);
    }
});
```

**Comment by idealogica** [comment]
You solution won't work as it will trim the resource and close the connection before send() finishes.
The only one solution I have in mind is to call sleep():
```php
$serv->on('receive', function (Server $server, int $clientId, $reactor_id, $data) {
    if ($server->send($clientId, "DATA")) {
        go(function () {
            System::sleep(2);
            $server->close($clientId);
        });        
    }
});
```
But this solution is unstable and tricky. Any other ideas?

**Comment by huanghantao** [comment]
> You solution won't work as it will trim the resource and close the connection before send() finishes.
> The only one solution I have in mind is to call sleep():
> 
> ```
> $serv->on('receive', function (Server $server, int $clientId, $reactor_id, $data) {
>     if ($server->send($clientId, "DATA")) {
>         go(function () {
>             System::sleep(2);
>             $server->close($clientId);
>         });        
>     }
> });
> ```
> 
> But this solution is unstable and tricky. Any other ideas?

If you want to make sure that the client has received all the data, you can make the client to send a message to the server. When the server receives the message, close it.

**Comment by idealogica** [comment]
In my case the client is internet browser. I can force internet browsers to send additional message for me :)

**Comment by matyhtf** [comment]
Did you use WSL1 ?

**Comment by idealogica** [comment]
`Linux ubuntu-bionic 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
`PHP 7.1.33-16+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 14 2020 08:27:11) ( NTS )`
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
```

**Comment by matyhtf** [comment]
@idealogica 

Have any special kernel parameters been set? Use commands to display them. `sysctl -p`


Swoole will queue up the data sending and closing operations, and will call close to close the connection after the sending is completed

**Comment by idealogica** [comment]
This can be closed. I can't reproduce the issue anymore. Most likely I was testing it with forced close `$server->close($clientId, true);` by mistake. My apologies. Thank you for your job!
