### ISSUE TITLE
process中pipe通信和队列通信可以共用么？

### ISSUE THREAD

**Issue by NewbMiao** [swoole/swoole-src#346]
想用队列通信处理任务，pipe通信作为操作结果回应，但好像不能共用，如何解决或处理？

**Comment by sniperBlank** [comment]
问题描述不清楚。

**Comment by NewbMiao** [comment]
简单点就是，swoole_process中MsgQueuqe和pipe的read&write可以一起使用么，用example中的代码测试好像是不可以

**Comment by sniperBlank** [comment]
@NewbMiao 我测试过。不行。如果用message queue，必须用push pop.

**Comment by matyhtf** [comment]
不能公用。用push/pop就不要再用read/write

**Comment by NewbMiao** [comment]
那这样的话，使用消息队列，如果子进程push，是不是父进程就能收到他的pop？
