### ISSUE TITLE
 undefined symbol: _zval_ptr_dtor_wrapper in Unknown on line 0

### ISSUE THREAD

**Issue by achillesye** [swoole/swoole-src#3465]
system  CentOS Linux release 7.4.1708
php version PHP 5.6.40
php-config --version 7.0.25
 phpize --version
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012

php -m | grep swoole
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php/lib/php/extensions/debug-non-zts-20151012/swoole.so' - /usr/local/php/lib/php/extensions/debug-non-zts-20151012/swoole.so: undefined symbol: _zval_ptr_dtor_wrapper in Unknown on line 0

please help me

**Comment by huanghantao** [comment]
@achillesye 

Seems like you have multiple versions of PHP installed? And you must use `PHP7.0+`.

**Comment by juslintek** [comment]
You cannot use xdebug with swoole, you have to use sdebug. Which has its own bugs as well but doesn't crash with swoole. But yeah when you switch version as well you need to recompile all pecl installed extensions `pecl upgrade -f`

**Comment by matyhtf** [comment]
The version of the build tool used must be the same
