### ISSUE TITLE
Unable to load dynamic library 'swoole.so'

### ISSUE THREAD

**Issue by zhangchunsheng** [swoole/swoole-src#3466]
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/lib64/php/modules/swoole.so (/usr/lib64/php/modules/swoole.so: undefined
symbol: _ZTINSt6thread6_StateE), /usr/lib64/php/modules/swoole.so.so (/usr/lib64/php/modules/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

php --version
PHP 7.2.22 (cli) (built: Aug 28 2019 09:29:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

uname -a
Linux  3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

swoole master branch

./configure --enable-openssl --enable-sockets --enable-http2

sudo yum install centos-release-scl
sudo yum install devtoolset-7
scl enable devtoolset-7 bash

make
make install

**Comment by jobs-git** [comment]
do u have it installed? I dont remember that is the right way of installing it for php. there is somesort of `phpize` along the way

**Comment by huanghantao** [comment]
@zhangchunsheng 

It is a problem with the GCC version. The version of GCC that you used to compile swoole is not the same as the version of GCC that you used to compile the other libraries.

**Comment by juslintek** [comment]
Yes, you have to use the same version for all extensions. Just try to use pecl all the time and for sdebug rebuild.sh script. As well when you upgrade PHP version you need to recompile all pecl libs you've installed just run `pecl upgrade -f` or use all extensions from Linux packages. But guess swoole and sdebug is not yet available in Linux packages repository. Sdebug as well has problems of its own as well.

**Comment by zhangchunsheng** [comment]
I update php to php7.4 and checkout and old branch on swoole, rebuild and load success. Only update php can't load module. I don't know why.
