### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole' (tried: /usr/lib64/php/modules/swoole (/usr/lib64/php/modules/swoole: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/swoole.so (/usr/lib64/php/modules/swoole.so: undefined symbol: _ZN6swoole9hook_callEPPviS0_)) in Unknown on line 0

### ISSUE THREAD

**Issue by gitxiaobin** [swoole/swoole-src#3470]
When I use the master branch , make install error. eg:

Step1: wget https://github.com/swoole/swoole-src/archive/master.tar.gz
 tar -zxvf master.tar.gz
cd swoole-src-master

phpize && \
./configure \
--enable-openssl  \
--enable-http2 && \
make && sudo make install

Step2: 
cd  /etc/php.d
vi  99-swoole.ini

; Enable Swoole extension module
extension=swoole.so

Step3: php -i|grep swoole

It's Warning

PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole' (tried: /usr/lib64/php/modules/swoole (/usr/lib64/php/modules/swoole: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/swoole.so (/usr/lib64/php/modules/swoole.so: undefined symbol: _ZN6swoole9hook_callEPPviS0_)) in Unknown on line 0

**Comment by jobs-git** [comment]
why not use:
```bash
pecl install swoole
```

**Comment by matyhtf** [comment]
@gitxiaobin You should use version 4.5.2, the master branch is still being tested
