### ISSUE TITLE
When using http proxy provided by luminati.io, http client not work.

### ISSUE THREAD

**Issue by kiolygenius** [swoole/swoole-src#3471]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
using Swoole\Coroutine\Http\Client with proxy settings: 
[
            'http_proxy_host' => [luminati proxy host],
            'http_proxy_port' => [luminati proxy port],
            'http_proxy_user' => [luminati provided username],
            'http_proxy_password' => [luminati provided password]
]

2. What did you expect to see?
Everything should work correctly.

3. What did you see instead?
$client->getStatusCode() returns -1 and socket_strerror($client->errCode) is "No error information"

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Jul  7 2020 10:52:35
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1g  21 Apr 2020
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled
Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux ec2a4768d46b 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 Linux
PHP 7.4.7 (cli) (built: Jun 11 2020 19:07:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies

I've found the problem is: when client request a CONNECT cmd, proxy response a "HTTP/1.1 200 OK". But swoole need "HTTP/1.1 200 Connection established"

**Comment by matyhtf** [comment]
Link: https://tools.ietf.org/html/draft-luotonen-web-proxy-tunneling-01#section-3.2

This is a problem with the proxy server, it does not comply with the RFC

**Comment by Algofair** [comment]
This error is still present in swoole 4.6.4-dev on php7.4.12
