### ISSUE TITLE
coroutine http client

### ISSUE THREAD

**Issue by Kapsonfire-DE** [swoole/swoole-src#3477]
Im using coroutine http client, to use as websocket
how can i check, if the client is still connected?

**Comment by huanghantao** [comment]
@Kapsonfire-DE 

If the client closes the connection, the `Server::recv` function will returns an empty string. If the client is offline, you can configure `keepalive` and `tcp_user_timeout` to determine if the connection still exists, for example:

```php
$server->set([
    'open_tcp_keepalive' => 1,
    'tcp_keepidle' => 4,
    'tcp_keepinterval' => 1,
    'tcp_keepcount' => 10,

    'tcp_user_timeout' => 1,
]);
```

**Comment by huanghantao** [comment]
@Kapsonfire-DE 

If the connection is broken, the next client send will fail, which can be determined by the return value.

**Comment by Kapsonfire-DE** [comment]
Ok, but why there is no isConnected like 
Swoole\Coroutine\Client->isConnected
doc says it's there

**Comment by Kapsonfire-DE** [comment]
I know use recv without timeout and check for false to detect broken connection, anything wrong with it?

**Comment by matyhtf** [comment]
@Kapsonfire-DE Check whether the return value of Client::Push() and Client::Recv() methods is false, Use Client::$errCode to get the error code.
