### ISSUE TITLE
Crash bug: Using Protobuf, if the constructor parameter is wrong, the workder will crash, and try catch is useless

### ISSUE THREAD

**Issue by fuzhufang** [swoole/swoole-src#3493]
What did you do? If possible, provide a simple script for reproducing the error.
The content of .proto is as follows
syntax="proto3";
package ClientBody;
message ResCommonResult
{
int32 code=1; // code
string msg=2; // msg
}

pb generates PHP code snippets
class ResCommonResult extends \Google\Protobuf\Internal\Message
{
/**
* code
*
* Generated from protobuf field int32 code = 1;
/
private $code = 0;
/*
* msg
*
* Generated from protobuf field string msg = 2;
*/
private $msg = '';

/**
 * Constructor.
 *
 * @param array $data {
 *     Optional. Data for populating the Message object.
 *
 *     @type int $code
 *           code
 *     @type string $msg
 *           msg
 * }
 */
public function __construct($data = NULL) {
    \GPBMetadata\Client\ClientBody::initOnce();
    parent::__construct($data);
}
What did you expect to see?
First case:
$a1 = new ClientBody\ResCommonResult(['code'=>1, 'msg'=>'hello']);
OK
Second case
$a1 = new ClientBody\ResCommonResult();
$a1->setCode(1); $a1->setMsg('hello');
OK

The third case
$a1 = new ClientBody\ResCommonResult([1,2]);
worker crash , swoole.log :
WARNING swManager_check_exit_status: worker#0[pid=21209] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.4.19, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:

https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

What did you see instead?
Hope it doesn't crash, it should throw an exception of parameter error or something.

What version of Swoole are you using (show your php --ri swoole)?
This problem occurs when using 4.4.19 and 4.5.2 respectively
php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team team@swoole.com
Version => 4.4.19
Built => Jul 23 2020 09:46:57
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

What is your machine environment used (show your uname -a & php -v & gcc -v) ?
uname -a
Linux fzf 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
php -v
PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.2.24-0ubuntu0.18.04.6, Copyright (c) 1999-2018, by Zend Technologies
gcc -v
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by twose** [comment]
Try to run your script without Swoole (protobuf only), or provide the log file of valgrind

**Comment by fuzhufang** [comment]
[valgrind.log](https://github.com/swoole/swoole-src/files/4963570/valgrind.log)

**Comment by fuzhufang** [comment]
[valgrind.log](https://github.com/swoole/swoole-src/files/4963646/valgrind.log)
without Swoole (protobuf only), it also crash

**Comment by fuzhufang** [comment]
Segmentation fault (core dumped)  . maby the protobuf had a crash bug

**Comment by fuzhufang** [comment]
thank you very much
