### ISSUE TITLE
请问使用 pecl 方式安装如何自定义参数呢

### ISSUE THREAD

**Issue by johnw2018** [swoole/swoole-src#3502]
如题，请问，使用 pecl 安装是否支持自定参数？

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by huanghantao** [comment]
for example:

```bash
enable openssl support? [no] : yes --with-openssl-dir=/usr/local/include/openssl
```
