### ISSUE TITLE
swoole_server->addProcess添加的process 内无法调用task方法

### ISSUE THREAD

**Issue by Wellming** [swoole/swoole-src#351]
swoole_server->addProcess(swoole_process $process) 通过这种方式添加的process 会被认为是task worker，
这样就导致无法在这个进程内调用task方法。

我有场景要在这个process中投递任务， 还是我使用方式有问题？

**Comment by matyhtf** [comment]
user process没有onFinish方法，所以不允许调用task。请使用sendmessage接口
