### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by xbc563771383** [swoole/swoole-src#3516]
一个消费kafka的脚本，核心代码，循环调用以下代码，在task进程的协程中执行
$domain = 'api.push.apple.com';
                $cli = new \Swoole\Coroutine\Http2\Client($domain, 443, true);
                $cli->set([
                    'socket_timeout' => -1,
                    'ssl_host_name' => $domain,
                ]);
                $cli->connect();
                $req = new \Swoole\Http2\Request();
                $req->method = 'POST';
                $req->path = '/3/device/'.$appId;
                $req->headers = [
                    "apns-topic" => $app_bundle_id,
                    'Authorization' =>  'bearer ' . $jws,
                    'Connection' => 'Keep-alive'
                ];
                $req->data = $pushData;
                $cli->send($req);
                $response = $cli->recv();

报错Connection reset by peer

swoole版本

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Jul 10 2020 09:39:05
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

解释器版本
PHP 7.2.31 (cli) (built: May 31 2020 16:18:31) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.2.31, Copyright (c) 1999-2018, by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Comment by huanghantao** [comment]
@xbc563771383 

Can you provide a complete, stable, reproducible code？

**Comment by xbc563771383** [comment]
可以，我把代码发到你的邮箱里，你注意查收以下

**Comment by huanghantao** [comment]
@xbc563771383 

我似乎没有收到，我的邮箱是`codinghuang@qq.com`

**Comment by matyhtf** [comment]
@huanghantao 这里的结论是？

**Comment by huanghantao** [comment]
没回复了，用Golang了
