### ISSUE TITLE
multiple https request cause swoole_http_server crash

### ISSUE THREAD

**Issue by zhky04** [swoole/swoole-src#352]
I have multiple clients connecting to swoole_http_server simultaneously, and swoole_http_server crash at SSL_do_handshake sometimes.

I have printed the back trace when swoole crashed, my workstation run Ubuntu 14.04.2 LTS.

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd6c6a700 (LWP 31812)]
0x00007ffff6ce9e39 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
(gdb) 
(gdb) bt
#0  0x00007ffff6ce9e39 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#1  0x00007ffff6ceaac3 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#2  0x00007ffff6ceac29 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#3  0x00007ffff6cec02d in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#4  0x00007ffff6cec664 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#5  0x00007ffff19c9105 in swSSL_accept (conn=conn@entry=0x7fffe34db0b8)
    at /home/ralfchen/swoole/swoole-src-swoole-1.7.19-beta/src/protocol/SSL.c:69
#6  0x00007ffff19c9204 in swSSL_recv (conn=conn@entry=0x7fffe34db0b8, __buf=0x7fffd6c67d20, __n=8180)
    at /home/ralfchen/swoole/swoole-src-swoole-1.7.19-beta/src/protocol/SSL.c:100
#7  0x00007ffff19bfd6e in swConnection_recv (__flags=0, __n=<optimized out>, __buf=<optimized out>, conn=0x7fffe34db0b8)
    at /home/ralfchen/swoole/swoole-src-swoole-1.7.19-beta/include/Connection.h:63
#8  swReactorThread_onReceive_http_request (reactor=<optimized out>, event=<optimized out>)
    at /home/ralfchen/swoole/swoole-src-swoole-1.7.19-beta/src/network/ReactorThread.c:1250
#9  0x00007ffff19b6463 in swReactorEpoll_wait (reactor=0x7ffff0c14410, timeo=<optimized out>)
    at /home/ralfchen/swoole/swoole-src-swoole-1.7.19-beta/src/reactor/ReactorEpoll.c:267
#10 0x00007ffff19c179b in swReactorThread_loop_stream (param=<optimized out>)
    at /home/ralfchen/swoole/swoole-src-swoole-1.7.19-beta/src/network/ReactorThread.c:1719
#11 0x00007ffff4e5c182 in start_thread (arg=0x7fffd6c6a700) at pthread_create.c:312
#12 0x00007ffff63bf47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)

**Comment by zhky04** [comment]
swoole version is 1.7.19 beta, 1.7.18 crash either.

**Comment by matyhtf** [comment]
please use swoole-1.7.22 or later version.
