### ISSUE TITLE
pecl upgrade swoole 安装到最后报错

### ISSUE THREAD

**Issue by aji88** [swoole/swoole-src#3523]
swoole4.4想升级到4.5，运行：pecl upgrade swoole 安装到最后报错
最后报错：

Build process completed successfully
Installing '/usr/include/php/ext/swoole/config.h'
Installing '/usr/lib64/php/modules/swoole.so'
Segmentation fault (core dumped)

但还是能运行的，不知道有没有问题？

php -v
PHP 7.2.27 (cli) (built: Jan 26 2020 15:49:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.27, Copyright (c) 1999-2018, by Zend Technologies

php --ri swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Jul 31 2020 15:05:35
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by huanghantao** [comment]
没记错的话，pecl安装Swoole的时候，是不会跑和Swoole相关的代码，所以这个段错误应该是你PHP本身的问题？

**Comment by matyhtf** [comment]
这可能是 pecl 的bug，替换 swoole.so 时可能发生了错误，建议先移除 swoole，再安装

**Comment by aji88** [comment]
@matyhtf 是的，先移除后安装就没有问题了，谢谢老大。
