### ISSUE TITLE
php: symbol lookup error: /usr/local/sinasrv2/lib/php/extensions/no-debug-non-zts-20100525/swoole.so: undefined symbol: php_http_parser_init

### ISSUE THREAD

**Issue by guojianing** [swoole/swoole-src#355]
php: symbol lookup error: /usr/local/sinasrv2/lib/php/extensions/no-debug-non-zts-20100525/swoole.so: undefined symbol: php_http_parser_init

**Comment by matyhtf** [comment]
去掉 configure 中的 --enable-swoole

**Comment by guojianing** [comment]
已解决，谢谢啦
