### ISSUE TITLE
Swoole 用时使用Swoole\Coroutine和Swoole\Coroutine\MySQL报错“Segmentation fault”

### ISSUE THREAD

**Issue by Frank-JY** [swoole/swoole-src#3554]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
我希望创建一个脚本，使用Swoole\Coroutine创建协程来连接数据库，但是报错“Segmentation fault”

2. What did you expect to see?
按照预想这里应该连接成功

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

Version => 2.0.10

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
（1）uname -a
Linux ocloud-bsp-billing-tag-6b7df8b5b5-2h5ns 4.14.105-19-0009 #1 SMP Sun Jan 19 10:25:18 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
（2）php -v
PHP 5.6.23 (cli) (built: Mar  1 2017 17:00:03) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
(3)gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.6 20110731 (Red Hat 4.4.6-4) (GCC)

**Comment by Frank-JY** [comment]
使用gdp获取core信息：
-----------------------------
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffeceffa000
Core was generated by `/usr/local/services/php-5.6.23/bin/php /data/release/tce_billing/tag/applicatio'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000000000 in ?? ()
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.5-7.el6_0.x86_64 cyrus-sasl-lib-2.1.23-13.el6.x86_64 glibc-2.12-1.49.tl1.x86_64 keyutils-libs-1.4-3.el6.x86_64 krb5-libs-1.9-22.el6_2.1.x86_64 libcom_err-1.41.12-11.el6.x86_64 libcurl-7.19.7-26.el6_2.4.x86_64 libgcc-4.4.6-4.tl1.x86_64 libidn-1.18-2.el6.x86_64 libjpeg-6b-46.el6.x86_64 libpng-1.2.49-1.el6_2.x86_64 libselinux-2.0.94-5.2.el6.x86_64 libssh2-1.2.2-7.el6_2.3.x86_64 libstdc++-4.4.6-4.tl1.x86_64 libxml2-2.7.6-4.el6_2.4.x86_64 nspr-4.8.9-3.el6_2.x86_64 nss-3.13.1-7.el6_2.x86_64 nss-softokn-freebl-3.12.9-11.el6.x86_64 nss-util-3.13.1-3.el6_2.x86_64 openldap-2.4.23-20.el6.x86_64 openssl-1.0.1e-16.tl1.14.x86_64 zlib-1.2.3-27.el6.x86_64
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000884702 in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>)
    at /data/home/tomjrwu/php-5.6.23/Zend/zend_vm_execute.h:608
#2  0x0000000000874690 in execute_ex (execute_data=0x7f80d6352050) at /data/home/tomjrwu/php-5.6.23/Zend/zend_vm_execute.h:363
#3  0x00007f80d6fd6bf1 in sw_coro_resume (sw_current_context=0x7f80d61c2598, retval=0x7f80d6344520, coro_retval=0x7ffecef2f238)
    at /data/siva/swoole_version/swoole_v2.0.10_171115/swoole-src-2.0.10-rc1/swoole_coroutine.c:421
#4  0x00007f80d6ff8567 in swoole_mysql_coro_onConnect (client=<value optimized out>)
    at /data/siva/swoole_version/swoole_v2.0.10_171115/swoole-src-2.0.10-rc1/swoole_mysql_coro.c:845
#5  0x00007f80d6ff8a08 in swoole_mysql_coro_onHandShake (reactor=0x24d7c80, event=0x7ffecef2f310)
    at /data/siva/swoole_version/swoole_v2.0.10_171115/swoole-src-2.0.10-rc1/swoole_mysql_coro.c:986
#6  swoole_mysql_coro_onRead (reactor=0x24d7c80, event=0x7ffecef2f310)
    at /data/siva/swoole_version/swoole_v2.0.10_171115/swoole-src-2.0.10-rc1/swoole_mysql_coro.c:1022
#7  0x00007f80d7033b6f in swReactorEpoll_wait (reactor=0x24d7c80, timeo=<value optimized out>)
    at /data/siva/swoole_version/swoole_v2.0.10_171115/swoole-src-2.0.10-rc1/src/reactor/ReactorEpoll.c:251
#8  0x00007f80d6fd94ba in php_swoole_event_wait ()
    at /data/siva/swoole_version/swoole_v2.0.10_171115/swoole-src-2.0.10-rc1/swoole_event.c:223
#9  0x00000000007f83e6 in zend_call_function (fci=0x7ffecef2f4d0, fci_cache=<value optimized out>)
    at /data/home/tomjrwu/php-5.6.23/Zend/zend_execute_API.c:847
#10 0x00000000007f90e0 in call_user_function_ex (function_table=<value optimized out>, object_pp=<value optimized out>,
    function_name=<value optimized out>, retval_ptr_ptr=<value optimized out>, param_count=<value optimized out>,
    params=<value optimized out>, no_separation=1, symbol_table=0x0) at /data/home/tomjrwu/php-5.6.23/Zend/zend_execute_API.c:617
#11 0x00000000007f9132 in call_user_function (function_table=0x220b490, object_pp=<value optimized out>,
    function_name=<value optimized out>, retval_ptr=0x7ffecef2f590, param_count=<value optimized out>, params=<value optimized out>)
    at /data/home/tomjrwu/php-5.6.23/Zend/zend_execute_API.c:590
#12 0x0000000000709ac7 in user_shutdown_function_call (shutdown_function_entry=0x7f80d634eb40)
    at /data/home/tomjrwu/php-5.6.23/ext/standard/basic_functions.c:4976
#13 0x0000000000813de3 in zend_hash_apply (ht=0x7f80d6340a60, apply_func=0x709a70 <user_shutdown_function_call>)
    at /data/home/tomjrwu/php-5.6.23/Zend/zend_hash.c:641
#14 0x000000000070aef6 in php_call_shutdown_functions () at /data/home/tomjrwu/php-5.6.23/ext/standard/basic_functions.c:5068
#15 0x00000000007a62d5 in php_request_shutdown (dummy=<value optimized out>) at /data/home/tomjrwu/php-5.6.23/main/main.c:1835
#16 0x00000000008abc4f in do_cli (argc=3, argv=0x220a820) at /data/home/tomjrwu/php-5.6.23/sapi/cli/php_cli.c:1177
#17 0x00000000008ad0a8 in main (argc=3, argv=0x220a820) at /data/home/tomjrwu/php-5.6.23/sapi/cli/php_cli.c:1378

**Comment by matyhtf** [comment]
@Frank-JY 这个版本已经不维护了，请使用个 4.4 或者 4.5 版本
