### ISSUE TITLE
Contact?

### ISSUE THREAD

**Issue by Webonaute** [swoole/swoole-src#3556]
Hi. 

I am the lead at a big B2C company. We started using Swoole at beginning of this year to provide Protobuf GRPC service to our frontend developer for our new application. It was a long drive and lot of learning!  We are using  Swoole with symfony 4. Our product is getting to be ready to test in production with our low season traffic. We have some work around we would like to get rid before we kick in our new season in october.

I would like to know if there is some people I can reach to help out improving our performance and help out with bug we can have before we deploy to production.

Here is some stuff we truly needs:
- https://github.com/swoole/swoole-src/pull/3486  we are waiting this fix to be release.
- New Relic implementation (https://discuss.newrelic.com/t/swoole-with-apm/103386) we use this to monitor all our api server. very important to us.
- And looking for someone who can quickly release bug fix regarding swoole, swoole grpc and symfony integration.

At the end of the season (January), we will more than happy to share a success story with Swoole technologie. We had about 175 000 requests per minutes last year in our peak hours with php-fpm and rest api. This represent around 15 millions visitors over 4 months. We want to beat our numbers this year with Swoole!  

You can reach me at mathieu.delisle+github@ugroupmedia.com

**Comment by huanghantao** [comment]
@Webonaute Hello, we will as soon as possible to improve it.

**Comment by huanghantao** [comment]
@Webonaute  Hello, what kind of HTTP server you currently use? `Swoole\Http\Server` or `Swoole\Coroutine\Http\Server`?

**Comment by Webonaute** [comment]
Swoole\Http\Server

**Comment by jobs-git** [comment]
Oh, so you intend to hire a consultant from swoole? I hope they can send you contacts soon!

**Comment by huanghantao** [comment]
> Swoole\Http\Server

We have already supported flow control for Swoole\Http\Server, and we will include it in version 4.5.3. Thank you for your feedback.

**Comment by Webonaute** [comment]
@jobs-git if needed yes.

**Comment by doubaokun** [comment]
@Webonaute I have contacted you via email.
