### ISSUE TITLE
segmentfault 11 on 1.7.18+ about swoole_timer

### ISSUE THREAD

**Issue by AJSoft** [swoole/swoole-src#356]
Here is the call stack:

in __memcpy_ssse3 () from /lib64/libc.so.6
#1  0x00007f8818abf50f in _estrndup ()
#2  0x00007f8818ae5a84 in _zval_copy_ctor_func ()
#3  0x00007f8818ae7c28 in zend_make_printable_zval ()
#4  0x00007f8818aef001 in zend_is_callable_ex ()
#5  0x00007f8818ad680a in zend_call_function ()
#6  0x00007f8818ad741f in call_user_function_ex ()
#7  0x00007f880dbdfa05 in php_swoole_onTimeout (timer=0x7f880de264e0 <SwooleG>, event=0x7f8819928920) at /opt/swoole-src-swoole-1.7.19-rc1/swoole_timer.c:138
#8  0x00007f880dc03f29 in swEventTimer_select (timer=0x7f880de264e0 <SwooleG>) at /opt/swoole-src-swoole-1.7.19-rc1/src/network/EventTimer.c:194
#9  0x00007f880dbf3b59 in swReactor_onTimeout_and_Finish (reactor=0x7f88199813c0) at /opt/swoole-src-swoole-1.7.19-rc1/src/reactor/ReactorBase.c:190
#10 0x00007f880dbf5b49 in swReactorEpoll_wait (reactor=0x7f88199813c0, timeo=<optimized out>) at /opt/swoole-src-swoole-1.7.19-rc1/src/reactor/ReactorEpoll.c:301
#11 0x00007f880dc03ae2 in swWorker_loop (factory=factory@entry=0x7f881994c4b8, worker_id=worker_id@entry=3) at /opt/swoole-src-swoole-1.7.19-rc1/src/network/Worker.c:419
#12 0x00007f880dc01e50 in swManager_spawn_worker (factory=0x7f881994c4b8, worker_id=3) at /opt/swoole-src-swoole-1.7.19-rc1/src/network/Manager.c:433
#13 0x00007f880dc02288 in swManager_start (factory=factory@entry=0x7f881994c4b8) at /opt/swoole-src-swoole-1.7.19-rc1/src/network/Manager.c:121
#14 0x00007f880dbf2fb4 in swFactoryProcess_start (factory=0x7f881994c4b8) at /opt/swoole-src-swoole-1.7.19-rc1/src/factory/FactoryProcess.c:86
#15 0x00007f880dbf9bbd in swServer_start (serv=serv@entry=0x7f881994bfa0) at /opt/swoole-src-swoole-1.7.19-rc1/src/network/Server.c:762
#16 0x00007f880dbe7740 in zim_swoole_http_server_start (ht=<optimized out>, return_value=0x7f87fe5b08e8, return_value_ptr=<optimized out>, this_ptr=0x7f87fe5c5ee0,
    return_value_used=<optimized out>) at /opt/swoole-src-swoole-1.7.19-rc1/swoole_http.c:1413
#17 0x00007f8818ad555b in dtrace_execute_internal ()
#18 0x00007f880de3684a in xdebug_execute_internal () from /usr/lib64/php/modules/xdebug.so
#19 0x00007f8818b8f5b8 in zend_do_fcall_common_helper_SPEC ()
#20 0x00007f8818b23778 in execute_ex ()
#21 0x00007f8818ad5439 in dtrace_execute_ex ()
#22 0x00007f880de35fa2 in xdebug_execute_ex () from /usr/lib64/php/modules/xdebug.so
#23 0x00007f8818b8fa69 in zend_do_fcall_common_helper_SPEC ()
#24 0x00007f8818b23778 in execute_ex ()
#25 0x00007f8818ad5439 in dtrace_execute_ex ()
#26 0x00007f880de35fa2 in xdebug_execute_ex () from /usr/lib64/php/modules/xdebug.so
#27 0x00007f8818ad7223 in zend_call_function ()
#28 0x00007f8818a21523 in zif_call_user_func_array ()
#29 0x00007f8818ad555b in dtrace_execute_internal ()
#30 0x00007f880de3684a in xdebug_execute_internal () from /usr/lib64/php/modules/xdebug.so
#31 0x00007f8818b8f5b8 in zend_do_fcall_common_helper_SPEC ()
#32 0x00007f8818b23778 in execute_ex ()
#33 0x00007f8818ad5439 in dtrace_execute_ex ()
#34 0x00007f880de35fa2 in xdebug_execute_ex () from /usr/lib64/php/modules/xdebug.so
#35 0x00007f8818b8fa69 in zend_do_fcall_common_helper_SPEC ()
#36 0x00007f8818b23778 in execute_ex ()
#37 0x00007f8818ad5439 in dtrace_execute_ex ()
#38 0x00007f880de35fa2 in xdebug_execute_ex () from /usr/lib64/php/modules/xdebug.so
#39 0x00007f8818b8fa69 in zend_do_fcall_common_helper_SPEC ()
#40 0x00007f8818b23778 in execute_ex ()

Running on CentOS7 x64

We have not met this fault on 1.7.17 but on 1.7.18+

**Comment by matyhtf** [comment]
This bug  has been fixed on 1.7.19.

**Comment by idevz** [comment]
:+1:
