### ISSUE TITLE
How to share same resources to all websocket clients?

### ISSUE THREAD

**Issue by ammarfaizi2** [swoole/swoole-src#3561]
Please answer these questions before submitting your issue. Thanks!

## 1. What did you do? If possible, provide a simple script for reproducing the error.
I need to share some resources with all WebSocket clients. But I always get a different value for the different client by using the global variable.

Let say there are client A and client B, and there is a global variable `$bucket = []` (array).

### The story step-by-step: 
1. Client A connects to WebSocket Server.
2. The callback now has `$bucket` with value **an empty array**.
3. The callback pushes a value `1` (fd) to the `$bucket`.
-------
4. Client B connects to WebSocket Server.
5. The callback now has `$bucket` with value **an empty array**. (**Expected array value** here is `[1]`, not empty)
6. The callback pushes a value `2` (fd) to the `$bucket`.
-------
7. Client A re-connects to WebSocket Server.
8. The callback now has `$bucket` with value `[1]`.  (**Expected array value** here is `[1,2]`, not `[1]`)
9. The callback pushes a value `3` (fd) to the `$bucket`.
-------
10. Client B re-connects to WebSocket Server.
11. The callback now has `$bucket` with value `[2]`. (**Expected array value** here is `[1,2,3]`, not `[2]`)
12. The callback pushes a value `4` (fd) to the `$bucket`.
-------
13. Client A re-connects to WebSocket Server.
14. The callback now has `$bucket` with value `[1,3]`. (**Expected array value** here is `[1,2,3,4]`, not `[1,3]`)
15. The callback pushes a value `5` (fd) to the `$bucket`.

... and so on ...

### Why does every client has its own array value?

Below is the simplified code that reproduce the problem:
```php
<?php

use Swoole\WebSocket\Server;
use Swoole\Http\Request;
use Swoole\WebSocket\Frame;

$server = new Server("0.0.0.0", 6001);
$bucket = []; // I want this variable to be accessible for all clients.

$server->on("start", function (Server $server) {
    echo "Listening on 0.0.0.0:6001...\n";
});

$server->on('open', function(Server $server, Swoole\Http\Request $request) {
    global $bucket;
    $bucket[] = $request->fd; // store the fd may be a good example
    echo json_encode($bucket)."\n";
});

$server->on('message', function(Server $server, Frame $frame) {
    // do something
});

$server->on('close', function(Server $server, int $fd) {
    // do something
});

$server->start();

```

## 2. What did you expect to see?
I need the resources consistent and access the same resource (array value).
```
Listening on 0.0.0.0:6001...
[1]  // client A connects
[1,2] // client B connects
[1,2,3] // client A reconnects
[1,2,3,4] // client B reconnects
[1,2,3,4,5] // client A reconnects
[1,2,3,4,5,6] // client B reconnects
```

## 3. What did you see instead?
What I get is every client has its own resource (array value).
```
Listening on 0.0.0.0:6001...
[1] // client A connects
[2] // client B connects (why the array is different with client A?)
[1,3] // client A reconnects
[2,4] // client B reconnects
[1,3,5] // client A reconnects
[2,4,6] // client B reconnects
```

## 4. What version of Swoole are you using (show your `php --ri swoole`)?
```
ammarfaizi2@integral:~$ php -d extension=swoole.so --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Jul 10 2020 16:35:53
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1c  28 May 2019
http2 => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

## 5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
ammarfaizi2@integral:~$ uname -a
Linux integral 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

ammarfaizi2@integral:~$ php -v
PHP 7.4.8 (cli) (built: Aug  1 2020 18:06:15) ( ZTS DEBUG )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

ammarfaizi2@integral:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.2.1-9ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2) 
```

**Comment by huanghantao** [comment]
@ammarfaizi2 

Because you have two worker processes, your practice is not acceptable. You can use directly `Server::connections `:

```php
<?php

use Swoole\WebSocket\Server;

$server = new Server("0.0.0.0", 9501);

$server->set([
    "worker_num" => 2,
]);

$server->on('message', function (Server $server, $frame) {
    foreach ($server->connections as $fd) {
        var_dump($fd);
    }
});

$server->start();
```

**Comment by ammarfaizi2** [comment]
@huanghantao I see now, I just understood that every single process has its own memory and does not share to other processes.

In the real case, I need to share objects too.

I am taking a look and considering to use coroutine server now. Thanks for the response.
