### ISSUE TITLE
RedisServer:  TCP packet sticking in redis server with high concurrency

### ISSUE THREAD

**Issue by zqe** [swoole/swoole-src#3562]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

TCP packet sticking occurs in the concurrent scenario of using `java lettuce redis client` or `redis-benchmark`
server : aliyunECS  4C8G
QPS: 1000+ 

```php
use  Swoole\Redis\Server;
$server = new Server('0.0.0.0', 9561);
$server->on('AUTH', function($server, $fd, $_, $data){
      if(count($data) != 1) {
        return $server->send($fd, Server::format(Server::ERROR, "ERR wrong number of arguments for 'AUTH' command"));
     } 
     return $server->send($fd, Server::format(Server::STATUS, "OK"));
});
$server->start();
```

use redis-benchmark 
```bash
redis-benchmark -n 1000  -c 100  -h 127.0.0.1  -p 9561 -a hky3360728767060:225867e0df292c7ab1fba880cc5cfb33 -k 0
```
log record
```
[2020-08-07 16:44:13] redis-server.INFO: redis request body {"command":"AUTH","args":["hky33607xxxxxxxxx:225867e0df292c7ab1fba8xxxxxx","*21
$4
GET
$16
key:__rand_int__
$3
xxx
$1","
key:__rand_int__
$3
xxx
$16
key:__rand_int__","xxx","key.....
```

2. What did you expect to see?
-

3. What did you see instead?
 ``` ERR wrong number of arguments for 'XXX' command```

4. What version of Swoole are you using (show your `php --ri swoole`)?
```

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.19
Built => Jul 28 2020 07:49:43
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
PHP 7.2.14 (cli) (built: Jul 21 2020 19:13:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by matyhtf** [comment]
Your server did not reply any messages to the client

**Comment by zqe** [comment]
Sorry, my example code is not very complete

The problem here is that the `auth` command parses more parameters in the request received by the log

**Comment by zqe** [comment]
Read the source code of lettuce
It was found to support full synchronous IO and asynchronous IO (NIO)
Since the redis server service is not executed by a single thread, there may be a problem that after the same connection receives packets twice, the later sent packets respond first.

NIO sends requests to the server many times in an asynchronous and non blocking way, and then receives the response from the server in sequence. When assigned to specific services, the benefit is that the same performance can be achieved with fewer connections. Therefore, NIO should be considered to support more

**Comment by twose** [comment]
First, the Swoole Redis Server service is executed by a single thread, but the return order is not guaranteed.
You should arrange them in some ways by yourself (such as queue, channel...)
