### ISSUE TITLE
Cant build actual version (8.0.0beta1)

### ISSUE THREAD

**Issue by Kapsonfire-DE** [swoole/swoole-src#3565]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
I followed these steps
https://github.com/Kapsonfire-DE/OpenTwitchAssistent/wiki/Using-PHP-on-Windows-10-with-linux-binaries-using-WSL

2. What did you expect to see?
working .so at the end :-D

3. What did you see instead?
checking if compiling with clang... no
./configure: line 5547: syntax error near unexpected token `('
./configure: line 5547: `  $as_echo_n "(cached) " >&6'

4. What version of Swoole are you using (show your `php --ri swoole`)?
see above

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux DESKTOP-77QA95M 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 GNU/Linux
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)

I got d6add5e01 earlier with php8.0.0alpha3 running

**Comment by khs1994** [comment]
https://github.com/tideways/php-xhprof-extension/issues/100

wait beta2 release

**Comment by khs1994** [comment]
@matyhtf build with php-src master branch meet error

https://github.com/khs1994-docker/php/runs/984300674?check_suite_focus=true#step:8:631
