### ISSUE TITLE
求支持mangoDB啊！

### ISSUE THREAD

**Issue by ztrombe** [swoole/swoole-src#357]
求支持mangoDB啊！

**Comment by sunjier** [comment]
swoole 和 mangoDB 没毛关系吧?

**Comment by matyhtf** [comment]
暂时不支持原生的异步mongodb，请使用task/finish将mongodb操作异步化。

**Comment by ifeltsweet** [comment]
Could you show an example how to async mongodb operations without a server environment, say in a cli job.

I want to accomplish something like:

```
$cursor = $mongodb->predictor->predictions->find(['matchId' => $matchId]);

foreach ($cursor as $prediction) {
    $process = new swoole_process(function($worker) use ($prediction, $mongodb) {
        $mongodb->predictor->predictions->updateOne(
            ['_id' => $prediction->_id],
            ['$set' => ['win' => 100]]
        );
    });

    $process->start();
}
 
while ($ret = swoole_process::wait()) {}
```

When running code above, mongodb throws a bunch of errors like "Cursor not found" and "Invalid reply to getMore command".
