### ISSUE TITLE
希望支持window XP/2003 32/64位 （支持IOCP）

### ISSUE THREAD

**Issue by wanjochan** [swoole/swoole-src#358]
这是个真诚的希望，因为还有大量的 XP/2003 32-64位的机器在运作，如果可以swoole跑在上面，可以让大量老机焕发新生，用于各种监控进程、自动化程序、鲁棒性分布式应用。
而且 XP/2003已经退出官方支持，反而有很多优化版本推出，现有的 window2003 server由于应用限制，在至少10至15年以内都会维持运作。

现有问题：
cygwin下面的swoole虽然基本可用，但是毕竟经过 cygwin层的翻译，性能下降，加上没有使用到IOCP，在windows下性能无法发挥。

所以希望能编译出支持 XP/2003 32/64的php_swoole扩展

**Comment by acabin** [comment]
我想核心问题是windows不支持fork导致的
要改为使用windows的子进程模式的话程序要大改，现在估计没什么人有精力做这个

**Comment by matyhtf** [comment]
包括Nginx在内实际上大部分Linux软件在Windows上都没有很好的实现。Windows系统与Linux/Unix是完全不同的，兼容Windows不如重新写一套框架。建议仅使用Windows作为体验，实际运行还是应该选择Linux.
