### ISSUE TITLE
HTTP服务器问题

### ISSUE THREAD

**Issue by chomyeong** [swoole/swoole-src#3584]
我搭建一个HTTP服务器 设备主动连接这个服务器发送心跳
设备IP是内网IP 
那么现在我发送请求的的时候，不能IP端口去发送命令 
而且这个连接FD是变化的 因为连接会断开
有什么办法能阻塞 或者 去发送命令呢，或者进程ID之类

**Comment by huanghantao** [comment]
没看明白你要表达啥意思

**Comment by huanghantao** [comment]
没看明白你要表达啥意思

**Comment by chomyeong** [comment]
@huanghantao  就是如果建立一个HTTP服务器监听端口，那么发送数据是不是要HTTP客户端发送这个服务器的IP和端口就行了，这没错，但是问题是  我们现在的HTTP服务器是，硬件设备主动连接的，而且IP还是局域网呢，那么我要给发送数据的时候如何发送呢？

**Comment by huanghantao** [comment]
@chomyeong 加我qq，2812240764。直接qq聊吧，方便点。

**Comment by huanghantao** [comment]
已解决
