### ISSUE TITLE
worker_num可以设置为1且max_request设置为1？

### ISSUE THREAD

**Issue by winerQin** [swoole/swoole-src#359]
情况是这样的。因为，我在本地环境做开发的时候，常常会修改程序脚本。每次重启进程很麻烦。虽然我写了一个便捷的shell，但是，依然太麻烦。于是，我就相。我把worker_num设置为1，max_request也设置为1.这样每次请求就会重启。不用那么麻烦地重启进程了。多好呀。但是，我一旦我这样设置就是自动将max_request优化为1024。请问能支持吗？谢谢！

```php
$server->run(array(
		'worker_num' => 1,  // 开启多少工作进程处理请求。
		'max_request' => 1,  // 每个工作进程处理多少请求自动销毁。
		'pid_file' => $pid_file,  // 进程ID保存目录。
		'max_conn' => 100000,  // swoole保持同时多少个TCL连接。
		'log_file' => WEBPATH . '/logs/error.log' 
)) // swoole扩展日志保存路径。
;
```

**Comment by matyhtf** [comment]
自动优化为1024是什么意思？可以设置为1呀。

**Comment by winerQin** [comment]
@matyhtf 这里面有两个问题：1都设置为1之后，是否以后每次请求得到的PHP脚本都是最新的更新。2我设置为1之后，日志里面会有如下提示。今天看到的跟之前有不同。我贴一下：
```
[2015-08-27 14:21:45 @12265.0]	WARN	swServer_start_check: serv->max_connection is exceed the maximum value[256].
```

**Comment by winerQin** [comment]
@matyhtf 我的目的很简单。就是希望swoole_frame框架（或swoole）提供一种开关，可以实时读取代码的变化。开启的时候生效，关闭就失效。默认关闭。谢谢！

**Comment by sniperBlank** [comment]
@matyhtf  @winerQin的意思是要代码热生效。不用部署了代码还要重启server.

**Comment by smalleyes** [comment]
代码热更新，说以后是会支持的。咱们现在就将就下吧。

**Comment by loyating** [comment]
2.0版本会出工具 、 等待吧

**Comment by matyhtf** [comment]
serv->max_connection is exceed the maximum value[256].
这是因为你的ulimit -n 设置太小
