### ISSUE TITLE
websocket并发超过500时段错误

### ISSUE THREAD

**Issue by AgonyXD** [swoole/swoole-src#3596]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
websocket服务连接数超过500时，发生段错误

2. What did you expect to see?

能更大的并发数

3. What did you see instead?

websocket连接数超过500并发时，段错误

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.4.16

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PHP 7.3.20 (cli)
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Comment by AgonyXD** [comment]
111

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by matyhtf** [comment]
@AgonyXD 是否配置了`max_connection`，试试去掉这个配置。或者调大为与`ulimit -n`一致
