### ISSUE TITLE
swoole 1.7.18 http server mix  ie cookie with firefox cookie (chinese:搞混了ie和火狐的cookie)

### ISSUE THREAD

**Issue by scil** [swoole/swoole-src#360]
I use different browsers to visit  swoole http server,  firefox cookie intrude into ie cookie.
## server env
- ubuntu12 on virtualbox host  ( public ip: 192.168.0.4 )
- php5.6
- swoole 1.7.18
- server script  `server.php` : 

```
<?php
$http = new swoole_http_server("0.0.0.0", 9501);

$http->set(
    array(
        'worker_num' => 1,
        'daemonize' => false,
        'max_request' => 1000,
        'dispatch_mode' => 1
    )
);



$http->on('request', function ($request, $response) {
    $agent = ($request->header['user-agent']);
    $is_ff = strpos($agent, 'Firefox/') !== false;
    $agent_name = $is_ff ? 'ff' : 'ie';

    if(isset($request->cookie['session'])){
        $session=$request->cookie['session'];
        $num= 1+ $request->cookie['num'];
    }else{
        $session=$agent_name;
        $num=1;
    }


    $response->cookie('session',$session,time()+3600);
    $response->cookie('num',$num,time()+3600);


    $response->end($session.' '.$num);
});
$http->start();
```
## client env
- win7
- firefox 40
- ie9
## steps
- start server on ubuntu `php server.php`
- use ie9 ,visit `192.168.0.4:9501`,  web content is `ie 1`
- refresh ie9, web content is `ie 2`
- use firefox,  web content is `ff 1`
- refresh firefox  ,web content is: `ff 2`
- refresh  ie9  ,web content is : `ff 3`
## other
- I have mapped localhost:9501 to virtualhost:9501, when i visit `127.0.0.1:9501`, i got same results.
- I have tried google chrome and opera, everythng is ok.   I have tried QQBrowser which use ie kernel, and got same wrong results.

**Comment by matyhtf** [comment]
Can not reproduce this problem, using IE8 access is normal. Firefox will request for one more favorite.ico.
