### ISSUE TITLE
4.5.3编译安装

### ISSUE THREAD

**Issue by wanghuashun** [swoole/swoole-src#3608]
g++ -I. -I/swoole -DPHP_ATOM_INC -I/swoole/include -I/swoole/main -I/swoole -I/usr/include/php7 -I/usr/include/php7/main -I/usr/include/php7/TSRM -I/usr/include/php7/Zend -I/usr/include/php7/ext -I/usr/include/php7/ext/date/lib -I/swoole -I/swoole/include -I/swoole/thirdparty/hiredis -DHAVE_CONFIG_H -g -O2 -Wall -Wno-unused-function -Wno-deprecated -Wno-deprecated-declarations -std=c++11 -c /swoole/swoole_runtime.cc  -fPIC -DPIC -o .libs/swoole_runtime.o
/swoole/swoole_runtime.cc: In function 'int socket_accept(php_stream*, swoole::coroutine::Socket*, php_stream_xport_param*)':
/swoole/swoole_runtime.cc:570:46: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct php_swoole_netstream_data_t'; use assignment or value-initialization instead [-Wclass-memaccess]
  570 |         memset(abstract, 0, sizeof(*abstract));
      |                                              ^
/swoole/swoole_runtime.cc:109:8: note: 'struct php_swoole_netstream_data_t' declared here
  109 | struct php_swoole_netstream_data_t
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
