### ISSUE TITLE
worker 个数 运行一段时间不知为何变少.

### ISSUE THREAD

**Issue by xcwen** [swoole/swoole-src#3610]
worker 个数 运行一段时间不知为何变少.
-----------
理论上worker 异常退出都会 重启一个worker .
swoole 版本是4.2.3.

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
