### ISSUE TITLE
swoole queue key设置为0的时候，共享内存不释放

### ISSUE THREAD

**Issue by sniperBlank** [swoole/swoole-src#362]
ipcs -q 如下：

![aa589d91-5408-49f9-8b72-1d1148d8f316](https://cloud.githubusercontent.com/assets/1966955/9577335/61bed5fc-5012-11e5-8eb6-96b09c1055a1.jpg)

swoole版本:
swoole support => enabled
Version => 1.7.19
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
Linux Native AIO => enabled
Gcc AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by matyhtf** [comment]
已增加对key为0时的默认使用ftok(__FILE__) 作为消息队列的KEY
