### ISSUE TITLE
Problem  WSS "failed: Error during WebSocket handshake: Unexpected response code: 525"

### ISSUE THREAD

**Issue by emmendoza2794** [swoole/swoole-src#3623]
Hi friends, I just got to know this wonderful tool for php, I am using it to create websockets.
But I have had a problem when trying to implement the secure websocket (WSS).
I'm using Cloudflare as a proxy for my domain and reading their documentation if they support secure websockets, but when implementing it I get the following error on the client side

![image](https://user-images.githubusercontent.com/24445416/92255962-a9d57600-ee98-11ea-93dc-4b2689f04194.png)

my code is the following.

![image](https://user-images.githubusercontent.com/24445416/92256195-0769c280-ee99-11ea-9777-24ff8df8db74.png)

version of Swoole 

![image](https://user-images.githubusercontent.com/24445416/92256350-3aac5180-ee99-11ea-9015-148f35fcea4a.png)

I know the problem is something related to handshake but I don't know how to fix it.
Please, if someone knows how to solve it or can guide me to a possible solution, I would greatly appreciate it.

**Comment by matyhtf** [comment]
@emmendoza2794 

You need to enable SSL

```php
    $server = new Swoole\Websocket\Server("127.0.0.1", 9502, SWOOLE_PROCESS, SWOOLE_SOCK_TCP | SWOOLE_SSL);

      $server ->set(['ssl_key_file' => $your_ssl_key, 'ssl_cert_file' => $your_cert_file, ]);

    $server->on('open', function($server, $req) {
        echo "connection open: {$req->fd}\n";
    });

    $server->on('message', function($server, $frame) {
        echo "received message: {$frame->data}\n";
        $server->push($frame->fd, json_encode(["hello", "world"]));
    });

    $server->on('close', function($server, $fd) {
        echo "connection close: {$fd}\n";
    });

    $server->start();
```

**Comment by emmendoza2794** [comment]
Thank you very much for your reply, I have already enabled my secure websocket.
In addition to this, I took one more step because I didn't have --enable-openssl enabled.

Again thank you very much.
