### ISSUE TITLE
Calling swoole\table->del() in different worker process, produces dirty data !

### ISSUE THREAD

**Issue by smellbee** [swoole/swoole-src#3637]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

without foreach loop，Calling swoole\table->del() in different worker process，produces dirty data .   see details in file：
[https://github.com/smellbee/goodstatic/blob/master/swoole_table_bug.php](https://github.com/smellbee/goodstatic/blob/master/swoole_table_bug.php)

2. What did you expect to see?

 del operation in swoole\table should be atomic, should never produce unexpected result. 

3. What did you see instead?

run the code linked above, changing $num_to_del from a small int (eg 5000) to 65000, you will see, when the number becomes bigger, the result becomes more and more unstable. 

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.3
Built => Aug 30 2020 08:23:05
coroutine => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.4.10 (cli) (built: Sep  1 2020 13:58:08) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies

gcc：
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
x86_64-redhat-linux

**Comment by smellbee** [comment]
![QQ图片20200908194514](https://user-images.githubusercontent.com/1640532/92472417-01167600-f20c-11ea-8cd3-e781e62f61cf.png)

**Comment by matyhtf** [comment]
使用最新的 4.5.4 版本，未能重现此问题。请尝试升级版本，再测试一下，看是否可以重现

**Comment by matyhtf** [comment]
测试代码：

```php
<?php
//测试共享内存
$table= new Swoole\Table(131072);
$table->column('col0', Swoole\Table::TYPE_INT, 4);
$table->column('col1', Swoole\Table::TYPE_INT, 4);
$table->column('col100', Swoole\Table::TYPE_INT, 8);
$table->column('col2', Swoole\Table::TYPE_STRING, 32);
$table->column('col3', Swoole\Table::TYPE_STRING, 32);
$table->column('col4', Swoole\Table::TYPE_STRING, 4);
$table->column('col5', Swoole\Table::TYPE_STRING, 24);
$table->column('col6', Swoole\Table::TYPE_STRING, 255);
$table->column('col7', Swoole\Table::TYPE_INT, 1);
$table->column('col8', Swoole\Table::TYPE_INT, 4);
$table->column('col9', Swoole\Table::TYPE_INT, 4);
$table->column('col10', Swoole\Table::TYPE_INT, 4);
$table->column('col11', Swoole\Table::TYPE_INT, 4);
$table->column('col12', Swoole\Table::TYPE_INT, 4);
$table->column('col13', Swoole\Table::TYPE_INT, 4);
$table->create();

echo "测试开始\n";
echo "模拟插入65535个记录\n";
$s = microtime(true);
//模拟插入65535个记录
for($i = 1; $i < 65536; $i++){
    $data = array(
        'col0' => $i,
        'col1' => $i - 1,
        'col100' => mt_rand(10000000000, 19999999999),
        'col2' => md5("asfsadfasdfsda"),
        'col3' => md5("asfsadfasdfsda"),
        'col4' => 'ew45',
        'col5' => 'wahaha',
        'col6' => 'asdjasdasdasdasdsfdfsdfsdfdsfjlskdfjldkjfasjdhaskjdhakdjfhksjdfhkjsdhfksjdfhjksdfhskfhskjdfhksdjhfkjsdhffsdddsjdhfkjsdhlksdhjlsdkjfh',
        'col7' => 1,
        'col8' => 11231231232,
        'col9' => 15123123123,
        'col10' => 2352342342,
        'col11' => 14232,
        'col12' => 13123123,
        'col13' => 30,
    );
    $table->set("u".$i, $data);
}
echo "插入完成, 用时：".(microtime(true) - $s)."\n";


$workerNum = 4;

while($workerNum--) {
    (new Swoole\Process(function () use ($table) {
        //【请手动调整这个值，从小到大】
        // 从共享内存中删除的key的个数，保证每个worker都删除同样的key，  
        // 当这个值日从小增大到5000+ 以后，删除key的结果变得越来越不稳定，大于65000后，结果很诡异
        $num_to_del = 65000;
        
        for($i = 1; $i <= $num_to_del; $i++){
            $table->del("u".$i);
        }
        
        sleep(2);//等待，确保每个worker的删除工作都完成
        
        echo "worker ".$worker_id." 从共享内存删除".$num_to_del."个key后， 期望剩余".(65535-$num_to_del)." 实际共享内存还剩".$table->count()."个key\n";

    }))->start();
}

$workerNum = 4;
while($workerNum--) {
    Swoole\Process::wait();
}
```

**Comment by smellbee** [comment]
thx , that's fixed !
