### ISSUE TITLE
今天一更新curl相关都报错了

### ISSUE THREAD

**Issue by linjuchen** [swoole/swoole-src#3651]
(CONSOLE)ErrorException: Object of class Swoole\Curl\Handler could not be converted to int
At /data/web/new/vendor/ezimuel/ringphp/src/Client/CurlHandler.php line 109

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
