### ISSUE TITLE
(CONSOLE)ErrorException: Object of class Swoole\Curl\Handler could not be converted to int

### ISSUE THREAD

**Issue by linjuchen** [swoole/swoole-src#3652]
(CONSOLE)ErrorException: Object of class Swoole\Curl\Handler could not be converted to int
At /data/web/new/vendor/ezimuel/ringphp/src/Client/CurlHandler.php line 109

**Comment by sy-records** [comment]
hook curl之后是一个对象，不支持强转为int类型。可以关闭hook，或者替换为其他的协程handler
