### ISSUE TITLE
socket_buffer_size  的疑问

### ISSUE THREAD

**Issue by Niexiawei** [swoole/swoole-src#3654]
swoole 4.5.2 是移除了 socket_buffer_size 这个设置项吗  

在文档中没有看见

[https://wiki.swoole.com/#/server/setting?id=socket_buffer_size](url)

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by sy-records** [comment]
加上了 [socket_buffer_size](https://wiki.swoole.com/#/server/setting?id=socket_buffer_size)
