### ISSUE TITLE
[suggestion] epoll or liburing (linux Kernel >= 5)

### ISSUE THREAD

**Issue by incapdns** [swoole/swoole-src#3655]
Hi, I would like to suggest the use of epoll_create and epoll_wait for better performance of the extension (Swoole) which in turn already has an excellent performance.
Example:

```
int epfd = epoll_create (1);
struct epoll_event event;
event.events = EPOLLIN;
event.data.fd = sockfd;
epoll_ctl (epfd, EPOLL_CTL_ADD, sockfd, & event);
// sockfd: The server socket FD
int nfds;
for (;;) {
   nfds = epoll_wait (epoll_fd, events, MAX_EVENTS, -1);
   for (n = 0; n <nfds; ++ n) {
        accept .... (rest of code)
   }
}
```

If it is possible to use also using the library "liburing" that makes use of the IO_URING that is available from kernel 5 would also be a good option

---------------------------------------------------------------------------------------------------------------------
1. What did you do? If possible, provide a simple script for reproducing the error.
None (Not is an error)

2. What did you expect to see?
LibUring [IO_URING]

3. What did you see instead?
epoll (while true accept)

4. What version of Swoole are you using (show your `php --ri swoole`)?
Version 4.5.2

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
uname: 
Linux 0eaef4e61793 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 GNU/Linux [Docker]

PHP:
PHP 7.2.33 (cli) (built: Aug  6 2020 22:45:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

GCC:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)

SWOOLE:
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Aug 29 2020 12:33:46
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by matyhtf** [comment]
Swoole already uses epoll to implement the event loop, liburing looks good, we can consider supporting it in the future
