### ISSUE TITLE
HTTP connection left stale when worker error occurs

### ISSUE THREAD

**Issue by hvt** [swoole/swoole-src#3664]
1. What did you do? If possible, provide a simple script for reproducing the error.

When a Swoole worker is killed (for example by the kernel when OOM), it seems Swoole does not close the HTTP connection. The connection is still open and the client is waiting indefinitely.

Consider the following script:

```php
<?php

use Swoole\Http\Request;
use Swoole\Http\Response;
use Swoole\Http\Server;

$http_server = new Server('0.0.0.0', $port = 8080);
$http_server->set([
    'worker_num' => 2,
    'dispatch_mode' => 3, // The regular workload is blocking, we emulate that in this minimal example using a sleep
]);
$http_server->on('workererror', function ($server, $worker_id, $worker_pid, $exit_code, $signal) {
    fwrite(\STDOUT, \sprintf("Error occured in Swoole worker %d (pid %d): exit code %d with signal %d\n", $worker_id, $worker_pid, $exit_code, $signal));
});
$http_server->on(
    'request',
    function (Request $request, Response $response) use ($http_server) {
        fwrite(\STDOUT, \sprintf("Request received in worker #%d (pid %d)\n", $http_server->getWorkerId(), $http_server->getWorkerPid()));
        $response->status(200);
        $response->write('o');
        \sleep(10);
        $response->write('k');
        $response->end();
    }
);

$http_server->start();

```

Now start a request:
```sh
curl -v 'http://127.0.0.1:8080'
```

Check the logs for the worker pid that received the request, and kill that process before the sleep ends (i.e. within 10 seconds):

```sh
kill -9 xxx
```

Swoole notices the killed process, nicely executes the `workererror` callback. It also spawns a new worker. The killed worker's HTTP connection however is not closed, i.e. the `curl` call is still open, and stays open.

2. What did you expect to see?

I would expect the HTTP connection to be nicely closed when a `workererror` occurs.

3. What did you see instead?

The HTTP client is stale and waiting forever for the already killed Swoole worker.

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
$ php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Jul 20 2020 11:48:43
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
$ uname -a
Linux test-api-v1-6cfd86dd48-dcskk 5.6.0-0.bpo.2-amd64 #1 SMP Debian 5.6.14-2~bpo10+1 (2020-06-09) x86_64 Linux
$ php -v
PHP 7.4.4 (cli) (built: Mar 24 2020 01:25:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies
```

**Comment by sy-records** [comment]
Http\Server use `SWOOLE_PROCESS` mode by default, the connection is established with the master process

So when the worker process exits abnormally, the connection won't be closed.

**Comment by hvt** [comment]
I see. But is there any way to flag / signal the master process to close this stale connection?

Does this mean the `workererror` callback is handled by the master process? If so, can the `workererror` callback close the connection somehow?

**Comment by matyhtf** [comment]
You should use an nginx server as a proxy gateway, close the connection after the timeout, and reply with HTTP 504 error
