### ISSUE TITLE
how to set the swoole  logfile when we use the process_pool module

### ISSUE THREAD

**Issue by andy-c** [swoole/swoole-src#3678]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
i wanna set the swoole logfile when i use the process_pool,but it can be set in swoole server

2. What did you expect to see?

set the logfile when use the process_pool

3. What did you see instead?

it can't be set

4. What version of Swoole are you using (show your `php --ri swoole`)?

v4.4.18

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux 32ad31dc8b03 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux & 7.1.10 & 4.8.5

**Comment by matyhtf** [comment]
Try to use `swoole_async_set` or `Swoole\Coroutine::set`, and upgrade to verion-4.5.4
