### ISSUE TITLE
为什么报错了擦

### ISSUE THREAD

**Issue by speakphp** [swoole/swoole-src#368]
<?php
$serv = new swoole_server("121.40.120.95", 9501);
$serv->set(array(
    'worker_num' => 8,   //工作进程数量
    'daemonize' => true, //是否作为守护进程
));
$serv->on('connect', function ($serv, $fd){
    echo "Client:Connect.\n";
});
$serv->on('receive', function ($serv, $fd, $from_id, $data) {
    $serv->send($fd, 'Swoole: '.$data);
    $serv->close($fd);
});
$serv->on('close', function ($serv, $fd) {
    echo "Client: Close.\n";
});
$serv->start();

**Comment by speakphp** [comment]
PHP Parse error:  syntax error, unexpected '' => 8,   //工作进程数量' (T_CONSTANT_ENCAPSED_STRING) in /home/wwwroot/server.php on line 7

Parse error: syntax error, unexpected '' => 8,   //工作进程数量' (T_CONSTANT_ENCAPSED_STRING) in /home/wwwroot/server.php on line 7

**Comment by matyhtf** [comment]
PHP语法错误，检查你的PHP源代码。
