### ISSUE TITLE
[Question] Debugging unknown problems

### ISSUE THREAD

**Issue by hakuno** [swoole/swoole-src#3680]
Hey!

People, I've begun with Swoole. Plus, I also took a note on Demin Yin about the #CSP programming that's behind the coroutines. I liked it so!

I'm working on a open source project (but closed yet) to deal with Load Balancing / Failover / NAT'ing on networking.

I've countered some problems that I cannot debug properly.

For instance, I've a class that doesn't run asynchronous.

Within this class I've made HTTP requests that should be executed in order.

But, one of these requests isn't capable of being executed with the other one. It gave me the correct HTTP response at runtime. The third party host keeps without side effect though. (is this the third party's fault?)

So I put a co::sleep between the requests and it was executed on there successfully.

How you all do debug troubles like that?

How do you debug & troubleshooting problems that have no sense?

I wanna keep with Swoole in future projects, however I'm unsure how much it's production ready. (yes, i know big companies run with Swoole btw)

ps. The documentation seems out of date and has mistyped stuff in 😞

**Comment by doubaokun** [comment]
Hi @hakuno Github issues only accept bug report or feature requests. Please join the Slack channel for general questions, community members may answer your questions: https://docs.google.com/forms/d/e/1FAIpQLScqpkPJeFG-ss3P-KhFECDSNLyo1iKmU1DToIQX9YRWbuetjw/viewform
