### ISSUE TITLE
reload不生效

### ISSUE THREAD

**Issue by peterxiemin** [swoole/swoole-src#369]
启动程序后，kill -USR1 managerpid  onWorkerStart函数里面修改的内容不生效。

PHP 5.5.25 (cli) (built: May 18 2015 23:42:41) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

<?php
class HttpServer {
	public $serv = NULL;
	public $a = 0;
	public function __construct() {
		$this->serv = new swoole_http_server ( '0.0.0.0', 80 );
		$this->serv->on ( 'WorkerStart', array (
				$this,
				onWorkerStart 
		) );
		$this->serv->on ( 'Request', array (
				$this,
				onRequest 
		) );
		$this->serv->on ( 'WorkerStop', array (
				$this,
				onWorkerStop 
		) );
		
		$this->serv->set ( array (
				'worker_num' => 8, // 工作进程数量
				'daemonize' => false 
		) ); // 是否作为守护进程
		$this->serv->start ();
	}
	public function __destruct() {
	}
	public function onWorkerStart($serv) {
		echo "onWorkerStart111\n";
	}
	public function onWorkerStop($serv, $worker_id) {
		
	}
	public function onRequest($request, $response) {
		$response->end ( 'bbb' );
	}
}

**Comment by shenzhe** [comment]
我用了你的代码试了一下，是没有问题的。
你归哪个版本的swoole?

**Comment by peterxiemin** [comment]
如果include的话， 改变include的代码， 没有问题，但如过public function onWorkerStart($serv) {
    echo "onWorkerStart111\n";
}这段代码里面，改成onWorkerStart222， reload是不生效的， 这个正常吗？

**Comment by peterxiemin** [comment]
系统是centos6.3 swoole的版本是1.7.19

**Comment by matyhtf** [comment]
只有被include的文件才可以reload，回调函数本身不会重载入。
