### ISSUE TITLE
swoole 4.5.2 get error

### ISSUE THREAD

**Issue by iamhgdabc** [swoole/swoole-src#3693]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

php7.2 use swoole 4.5.2

2. What did you expect to see?

./php server.php to run a htttp server，server.php gets from examples, 

3. What did you see instead?

sometimes show error:
Fatal error: Maximum execution time of 0 seconds exceeded in /opt/php-zts/php-7.2.0/bin/server.php on line 222

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.5.2,but get error:
[root@localhost bin]# php --ri swoole
PHP Warning:  PHP Startup: redis: Unable to initialize module
Module compiled with module API=20131226
PHP    compiled with module API=20100525
These options need to match
 in Unknown on line 0
Extension 'swoole' not present.

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux localhost.localdomain 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.2.0 (cli) (built: Sep 22 2020 16:42:48) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies

使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
