### ISSUE TITLE
直接获取框架里获取真实IP的方法有么

### ISSUE THREAD

**Issue by fengyikang88** [swoole/swoole-src#3697]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by Yurunsoft** [comment]
<http://wiki.swoole.com/#/http_server?id=server>：`$request->server[`remote_addr`]`
