### ISSUE TITLE
swoole不会释放由数据库查询出来的数据所占用的内存吗？

### ISSUE THREAD

**Issue by 1638523919** [swoole/swoole-src#3698]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

![image](https://user-images.githubusercontent.com/47804646/93999523-7c5d5780-fdc8-11ea-88d6-1a4a5bc4bbe2.png)

![image](https://user-images.githubusercontent.com/47804646/93999411-5cc62f00-fdc8-11ea-9847-b278d1fe139f.png)

![image](https://user-images.githubusercontent.com/47804646/93999646-a7e04200-fdc8-11ea-8ea0-4c1e772ee96c.png)

代码像上面那样，通过访问默认http://xxxx:9501/   接口 不断快速的按F5，内存会从启动初始的110M涨到176M，我现在希望，把这多出来的内存，释放掉，但是我不知道应该怎么才能释放由数据库查询出来的数据所占用的内存。这个问题不使用你们的框架效果也一样（使用原生的swoole写个最简版也会出现上面的问题），希望给点建议或者怎么解决这个内存占用的问题，各种unset(),赋值null变量也不能释放查询数据所占的内存。如果这个内存占用的问题得不到解决的话，那么我开启几百个进程来提供服务的话（我的业务需要开很多个进程），服务器应该会内存爆炸。

2. What did you expect to see?

我希望由数据库（目前是mysql，或许有其他的）查询出来的数据，在请求一次之后得到释放。因为这个数据我可能取得比较大，占用的内存就很可观了。还有通过curl访问了es的接口，获取大量的数据之后，用json_decode函数也会占用很大的内存，并且不会得到释放。

3. What did you see instead?
我这边使用的是hyperf框架，就配置了数据库的config然后写了个简单的查询，快速的按F5访问默认接口http://xxxx:9501，大概请求了50次左右，从启动的110M RES 涨到了176M，观察了5分钟，176M也没有被回收到110M的初始值，如果继续快速的访问接口，内存还会涨下去，目前我只能用max_request来搞我的业务了。

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.2
Built => Sep 21 2020 17:30:09
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled
Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux localhost.domain.com 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.4.10 (cli) (built: Sep 11 2020 10:19:29) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

hyperf/cache                         v2.0.9   A cache component for hyperf.
hyperf/command                       v2.0.10  Command for hyperf
hyperf/config                        v2.0.9   An independent component that provides configuration container.
hyperf/contract                      v2.0.9   The contracts of Hyperf.
hyperf/database                      v2.0.12  A flexible database library.
hyperf/db-connection                 v2.0.12  A hyperf db connection handler for hyperf/database.
hyperf/devtool                       v2.0.10  A Devtool for Hyperf.
hyperf/di                            v2.0.10  A DI for Hyperf.
hyperf/dispatcher                    v2.0.10  A HTTP Server for Hyperf.
hyperf/elasticsearch                 v2.0.10  Elasticsearch client for hyperf
hyperf/event                         v2.0.10  an event manager that implements PSR-14.
hyperf/exception-handler             v2.0.10  Exception handler for hyperf
hyperf/framework                     v2.0.11  A coroutine framework that focuses on hyperspeed and flexible, specific...
hyperf/guzzle                        v2.0.11  Swoole coroutine handler for guzzle
hyperf/http-message                  v2.0.11  microservice framework base on swoole
hyperf/http-server                   v2.0.11  A HTTP Server for Hyperf.
hyperf/logger                        v2.0.11  A logger component for hyperf.
hyperf/memory                        v2.0.12  An independent component that use to operate and manage memory.
hyperf/model-listener                v2.0.12  A model listener for Hyperf.
hyperf/paginator                     v2.0.12  A paginator component for hyperf.
hyperf/pool                          v2.0.12  An independent universal connection pool component.
hyperf/process                       v2.0.12  A process component for hyperf.
hyperf/redis                         v2.0.12  A redis component for hyperf.
hyperf/server                        v2.0.9   A base server library for Hyperf.
hyperf/testing                       v2.0.3   Testing for hyperf
hyperf/utils                         v2.0.9   A tools package that could help developer solved the problem quickly.

gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
