### ISSUE TITLE
【疑问】swoole_client　连接后端swoole_server一段时间后连不上？

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#370]
swoole_client连接后端swoole_server运行一段时间（通常几周）后连不上？
需要客户端reload php-fpm　swoole_client才能连上

用的swoole-1.7.17 stable版本　＋　php-5.6.11

架构是:
client-->tcp_proxy server(nginx)->swoole server

很诡异~~ @matyhtf 帮忙看看可能是问题？　请问我怎么定位下，非常感谢～～～

客户端代码：
<pre>
$client = new \swoole_client ( SWOOLE_TCP|SWOOLE_KEEP, SWOOLE_SOCK_SYNC );
$client->set(array(
			        'socket_buffer_size' => 8192, //缓存区大小
			        'open_tcp_nodelay' => true,//关闭Nagle合并算法
			)
$client ->connect('127.0.0.1', 9501, 0.5);
</pre>

**Comment by matyhtf** [comment]
strace跟踪一下

**Comment by yiliaofan** [comment]
好的　非常感谢~  

只能下次出现trace了，现在模拟不能复现。。
线上是一段时间才偶现

**Comment by shenzhe** [comment]
建议也升级到最新版本。
