### ISSUE TITLE
Lose current coroutine when after channel->pop()

### ISSUE THREAD

**Issue by Yurunsoft** [swoole/swoole-src#3703]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```php
<?php
Co\run(function(){
    $channel = new Swoole\Coroutine\Channel(1);
    var_dump('cid:' . Swoole\Coroutine::getCid());
    var_dump($channel->pop());
    var_dump('cid:' . Swoole\Coroutine::getCid());
});
```

2. What did you expect to see?

```
string(5) "cid:1"
bool(false)
string(6) "cid:1"
```

3. What did you see instead?

```
string(5) "cid:1"
bool(false)
string(6) "cid:-1"
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.5.4

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

PHP 7.4.10

**Comment by matyhtf** [comment]
The deadlock coroutine is awakened in the destructor, and the next version will directly throw an error and exit the process.

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/pull/3911
