### ISSUE TITLE
OnShutdown回调未在协程环境

### ISSUE THREAD

**Issue by tw2066** [swoole/swoole-src#3704]
做服务注册 , Shutdown会请求注册中心关闭服务
因为没有在协程环境,回报错误: API must be called in the coroutine
  希望shutdown回调也在协程环境中

**Comment by sy-records** [comment]
http://wiki.swoole.com/#/server/events?id=onshutdown 注意事项有说明

**Comment by matyhtf** [comment]
在 onShutdown 中使用 Co\run
