### ISSUE TITLE
swoole + 国产数据库的适配请教

### ISSUE THREAD

**Issue by NathanFreeman** [swoole/swoole-src#3705]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
你好，我最近在弄国产数据库人大金仓的项目，想用swoole + 人大金仓做项目尝试。

2. What did you expect to see?
我现有有人大金仓关于PHP的PDO扩展，我想知道我可以从用哪些方式知道swoole和人大金仓是否可以一起使用，谢谢。

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by Yurunsoft** [comment]
可以用，但是应该无法协程化的，也就是会阻塞，用都可以用

**Comment by NathanFreeman** [comment]
好的，谢谢

**Comment by matyhtf** [comment]
使用 PDO_mysql，或者 php stream、Swoole\Coroutine\Socket  实现客户端，都可以使用 swoole 协程。

或者不考虑支持协程，使用 Server 同步阻塞模式。
