### ISSUE TITLE
Process::exportSocket() setProtocol() bug

### ISSUE THREAD

**Issue by run0817** [swoole/swoole-src#3706]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

![image](https://user-images.githubusercontent.com/37306014/94360918-57782580-00e3-11eb-896a-61cda97e7fe3.png)
![image](https://user-images.githubusercontent.com/37306014/94360922-5a731600-00e3-11eb-8d5d-a62aa9813ac0.png)
![image](https://user-images.githubusercontent.com/37306014/94360923-5cd57000-00e3-11eb-8b9e-e706a2ccc811.png)

2. What did you expect to see?
  不报错

3. What did you see instead?

  报错

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.5.4

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

PHP 7.2.33 
centos7

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by matyhtf** [comment]
@run0817 请提供一个可以稳定重现的 php demo 代码，或者使用 valgrind 跟踪程序执行，将输出的日志发到这里

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
