### ISSUE TITLE
Swoole\Timer和Swoole\Http\Server不能同时使用

### ISSUE THREAD

**Issue by ttlxihuan** [swoole/swoole-src#3711]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Swoole\Timer::tick(10000, function(){
    var_dump('time');
});
http=newSwoole\Http\Server("127.0.0.1",880);http->on('request', function (request,response) {
    response->end('ok'); 
});
http->start();

2. What did you expect to see?
This code works.

3. What did you see instead?
PHP Warning: Swoole\Server::start(): eventLoop has already been created, unable to start Swoole\Http\Server in test.php on line 11

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole-version 4.5.3

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
php-version 7.3.8
Linux iZuf6bl004hn8g4qtri6lrZ 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

**Comment by sy-records** [comment]
```php
$http = new Swoole\Http\Server('0.0.0.0', 9501);

$http->on('request', function ($request, $response) {
    var_dump($request->server);
    $response->header("Content-Type", "text/html; charset=utf-8");
    $response->end("<h1>Hello Swoole. #".rand(1000, 9999)."</h1>");
});

Swoole\Timer::tick(1000, function(){
    var_dump('time');
});

$http->start();
```
