### ISSUE TITLE
如何设置swoole http客户端的buffer 大小

### ISSUE THREAD

**Issue by almostless** [swoole/swoole-src#3712]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

http请求时，如果响应体过大，会有警告

2. What did you expect to see?
正确的响应格式

3. What did you see instead?
WARNING	decompress_response: http_client::decompress_response failed by buffer error

4. What version of Swoole are you using (show your `php --ri swoole`)?

v4.5.0

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
php 7.3 

检查后发现是swoole_http_client_coro.cc 第689行抛出的警告。

我想知道怎么设置swoole http客户端的buffer 大小？百度，谷歌和swoole文档都试过，没有找到答案

**Comment by matyhtf** [comment]
1. 请升级到 4.5.4 版本
2. 多大的时候会出现这个问题？
