### ISSUE TITLE
Broken pipe问题

### ISSUE THREAD

**Issue by hejingsong** [swoole/swoole-src#3719]
swoole4.4.14，当发生Broken pipe时，能否将该fd移出events？

**Comment by twose** [comment]
Broken pipe说明了你的代码有问题, 在触发Broken pipe之前已经有IO操作返回失败了, 你却仍在尝试操作, 没有判断返回值和处理错误, fd是会复用的, 这种对错误置之不理或是想规避的行为是不好的, 因为你的应用层可能有个fd关联的上下文, 你自己必须明确知道并处理这个错误。
