### ISSUE TITLE
是不是php7环境下得tcp client，recv不到数据，是一个空字符串？

### ISSUE THREAD

**Issue by fucongcong** [swoole/swoole-src#372]
今天测试了一下，在5.6环境下可以正常拿到数据，但是用一台7的client拿数据时，一直拿到的是一个空的字符串。tcp连接会出现，http正常

**Comment by GXhua** [comment]
有代码例子吗？

**Comment by fucongcong** [comment]
$data = 'Ra8{m15{s5"sg_id"s2"90"s3"sid"u3s5"title"s32"包邮晶晶家2015秋装女装修身拼接不规则燕尾长款开衫TB1808"s7"content"s2"as"s4"mids"s7"["263"]"s5"mdids"s13"["261","262"]"s5"ctime"s10"1440569832"s5"mtime"s10"1440569900"s11"reply_count"u0s6"is_del"u0s3"uid"s6"158684"s9"first_pic"s81"http://img9.bcyimg.com/shop/1/post/177f6/3c7e2b504bba11e58f6fe51d527b6899.jpg/2X2"s5"price"s5"49.90"s8"goods_id"s12"520976237680"s4"shop"m6{r4;u3r19;r20;s8"nickname"s7"三维立体旗舰店"s8"password"s32"e10adc3949ba59abbe56e057f20f883e"s9"taobao_id"s4"1212"r13;u0}}m15{r2;s2"87"r4;u3r5;s30"秋季新品女装原创设计宽松裙子长袖显瘦中长款复古棉麻a字连衣裙"r7;s16"aaaaas阿萨德奥神队奥神队啊"r9;s2"-1"r11;s13"["256","259"]"r13;s10"1440554953"r15;s10"1440572101"r17;u9r18;u0r19;r20;r21;s86"http://img4.tbcdn.cn/tfscom/i1/1130573131/TB28ZGMeFXXXXcOXpXXXXXXXXXX_!!1130573131.jpg"r23;s6"190.00"r25;s12"521266342379"r27;m6{r4;u3r19;r20;r29;r30;r31;r32;r33;r34;r13;u0}}m15{r2;s2"83"r4;u3r5;r37;r7;s2"jk"r9;r39;r11;s7"["255"]"r13;s10"1440554610"r15;u0r17;u0r18;u0r19;r20;r21;s75"http://img4.tbcdn.cn/tfscom/i4/TB1K4M4IVXXXXbIaXXXXXXXXXXX_!!0-item_pic.jpg"r23;r44;r25;r45;r27;m6{r4;u3r19;r20;r29;r30;r31;r32;r33;r34;r13;u0}}m15{r2;s2"82"r4;u3r5;r37;r7;r8;r9;r39;r11;s7"["254"]"r13;s10"1440554378"r15;u0r17;u1r18;u0r19;r20;r21;r52;r23;r44;r25;r45;r27;m6{r4;u3r19;r20;r29;r30;r31;r32;r33;r34;r13;u0}}m15{r2;s2"81"r4;u3r5;s30"15秋装新款韩国宽松大码连衣裙中长款七分袖修身显瘦简约A字裙"r7;s5"assas"r9;s25"["250","249","251","253"]"r11;s19"["247","248","252"]"r13;s10"1440499216"r15;s10"1440554317"r17;u0r18;u0r19;r20;r21;s81"http://img5.bcyimg.com/shop/1/post/177f5/cf229b204b1b11e5bb3e035d2fa2db48.jpg/2X2"r23;s5"89.00"r25;s12"521232040924"r27;m6{r4;u3r19;r20;r29;r30;r31;r32;r33;r34;r13;u0}}m15{r2;s2"80"r4;u3r5;s5"香港专柜1"r7;s6"asdasd"r9;r39;r11;s7"["246"]"r13;s10"1440387485"r15;s10"1440387491"r17;u1r18;u0r19;r20;r21;s84"http://img1.tbcdn.cn/tfscom/i2/11601020056002505/T13VXAXttaXXXXXXXX_!!0-item_pic.jpg"r23;s6"169.00"r25;s11"10921325131"r27;m6{r4;u3r19;r20;r29;r30;r31;r32;r33;r34;r13;u0}}m15{r2;s2"79"r4;u3r5;s29"二三四五一二三四五一二三四五一二三四五一二三四五一二三四五"r7;s3"安师大"r9;r39;r11;s7"["245"]"r13;s10"1440386698"r15;s10"1440498846"r17;u0r18;u0r19;r20;r21;s75"http://img2.tbcdn.cn/tfscom/i2/TB1eOG3IVXXXXceXVXXXXXXXXXX_!!0-item_pic.jpg"r23;s5"76.00"r25;s12"521087600182"r27;m6{r4;u3r19;r20;r29;r30;r31;r32;r33;r34;r13;u0}}m15{r2;s2"78"r4;u3r5;s32"雅玛施2015秋冬季新款女装针织衫 韩版修身圆领印花内搭毛衣外套"r7;s3"爱施德"r9;r39;r11;s7"["244"]"r13;s10"1440386590"r15;u0r17;u0r18;u0r19;r20;r21;r89;r23;r90;r25;r91;r27;m6{r4;u3r19;r20;r29;r30;r31;r32;r33;r34;r13;u0}}}z';
    $len = strlen($data);
    $data = pack("N", $len) . $data;
    $serv->send($fd, $data);

**Comment by fucongcong** [comment]
这个数据 recv到得时候是一个空字符串

**Comment by fucongcong** [comment]
在本地是可以的，我在想是不是数据过大了？

**Comment by matyhtf** [comment]
请更新到最新的版本测试一下。
