### ISSUE TITLE
执行finish的时候，回传文件名到data参数，但是不是一个完整的文件名

### ISSUE THREAD

**Issue by diida** [swoole/swoole-src#373]
执行finish的时候，回传文件名到data参数，但是不是一个完整的文件名
而是下面这种，前面多了几个字符，不知道是什么原因。
我的系统是OS X 10.9.5

w^M/tmp/swoole.task.NbLSwJ

怎么判断回传的是不是一个包含内容的路径还是一个内容为文件路径字符串?

**Comment by matyhtf** [comment]
swoole版本是？

**Comment by diida** [comment]
版本是
swoole-src-swoole-1.7.17-stable

**Comment by matyhtf** [comment]
这是一个BUG导致的，你可以升级到1.7.19-stable
