### ISSUE TITLE
Multiple insert queries, got error.

### ISSUE THREAD

**Issue by Troodi** [swoole/swoole-src#3732]
When im trying isert a few rows i got error in second query:
`SQLSTATE[HY000] [115] MySQL client is busy now on state#18, please use recv/fetchAll/nextResult to get all unread data and wait for response then try again`

```php
        $this->db = new \Swoole\Coroutine\MySQL();
        $this->db->connect([
          'host' => '127.0.0.1',
          'user' => '',
          'password' => '',
          'database' => '',
        ]);
        $this->db->setDefer();
        $this->db->query("select * from `users`");
        dump($this->db);
        $this->db->query("select * from `users`");
        dump($this->db);

```

Why? How to resolve this problem?

**Comment by matyhtf** [comment]
A mysql client can only execute 1 SQL query at the same time, you should create 2 mysql objects and execute 2 queries

**Comment by Troodi** [comment]
> A mysql client can only execute 1 SQL query at the same time, you should create 2 mysql objects and execute 2 queries
Same error. Not same time.
$this->db->query("select * from `users`");
dump($this->db);
sleep(1);
$this->db->query("select * from `users`");
dump($this->db);

**Comment by matyhtf** [comment]
Remove setDefer, which means concurrent query
