### ISSUE TITLE
ERROR   zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Swoft\Rpc\Client\Exception

### ISSUE THREAD

**Issue by sandea** [swoole/swoole-src#3736]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

客户端rpc调用,出错内容：

[2020-10-13 09:34:12 *31.3]     ERROR   zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Swoft\Rpc\Client\Exception\RpcClientException: ServiceConnection::recv error, errCode=5001 in /var/www/swoft/vendor/swoft/rpc-client/src/Service/ServiceConnection.php:83
Stack trace:
#0 /var/www/swoft/vendor/swoft/rpc-client/src/Service/ServiceConnection.php(42): Swoft\Rpc\Client\Service\ServiceConnection->recv()
#1 /var/www/swoft/vendor/swoft/framework/src/Event/Listeners/ResourceReleaseListener.php(41): Swoft\Rpc\Client\Service\ServiceConnection->receive()
#2 /var/www/swoft/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Event\Listeners\ResourceReleaseListener->handle(Object(Swoft\Event\Event))
#3 /var/www/swoft/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Event\Listeners\ResourceReleaseListener), 'handle', Array)
#4 /var/www/swoft/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(8): Swoft\Proxy\Handler\AopHandler->invoke('handle', Array)
#5 /var/www/ |  `'|      U[2020-10-13 09:34:12 $7.0]       WARNING swManager_check_exit_status: worker#3 abnormal exit, status=255, signal=0

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
Swoole
Version => 4.2.6

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
uname -a
Linux 0c2d80d9bae0 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64 GNU/Linux

php -v
PHP 7.2.13 (cli) (built: Dec 10 2018 14:21:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologie

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
