### ISSUE TITLE
swoole4.5.4版本报错new \Swoole\Http\Client

### ISSUE THREAD

**Issue by true2009fans** [swoole/swoole-src#3753]
swoole 4.5.4
php 7.1.2
centos 7
new \Swoole\Http\Client('127.0.0.1', '8082', true);
swoole 4.5.4报错\Swoole\Http\Client Class not found，swoole 4.2.1版本使用正常

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
