### ISSUE TITLE
http server 客户端切断连接 worker 异常退出

### ISSUE THREAD

**Issue by gbabook** [swoole/swoole-src#3758]
1. 请详细描述问题的产生过程，贴出相关的代码，最好能提供一份可稳定重现的简单脚本代码。
swoole 版本 4.5.5，未使用 nginx 反向代理，直接启动了一个 http server，worker 数量 1，enable_coroutine => false
客户端在持续不断的通过 http post 提交 json 日志数据，每秒约 4-5w 行 json 字符串
接收到 request 后，使用 json_decode($string, true) 把字符串解析为数组保存到全局变量中，并每隔 10 秒保存到磁盘。
强行切断客户端连接后，worker 异常退出，server 自动拉起新的 worker
swoole 4.4.21 无此问题（4.4.21 修改过 config.h 文件，去掉了 HTTP_100_CONTINUE 的注释，问题版本未修改此注释）

2. 期望的结果是什么？
worker 保持状态

3. 实际运行的结果是什么？
worker 异常退出
swoole.log 输出：
[2020-10-20 23:24:51 *5407.0]	NOTICE	swFactoryProcess_finish (ERRNO 1005): connection[fd=1] does not exists
[2020-10-20 23:24:51 $5406.0]	WARNING	check_worker_exit_status: worker#0[pid=5407] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.5.5, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

4. 你的版本? 贴出 `php --ri swoole` 所打印的内容
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.5
Built => Oct 18 2020 16:51:35
coroutine => enabled
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1g  21 Apr 2020
http2 => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777223/D16777223
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

5. 你使用的机器系统环境是什么（包括内核、PHP、gcc编译器版本信息）？
操作系统：macOS 10.15.7
PHP 通过 homebrew 安装，swoole 通过下载 release 的压缩包编译安装。

$uname -a
Darwin xxxxxx 18.7.0 Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64

$php -v
PHP 7.2.33 (cli) (built: Aug  7 2020 18:28:03) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.33, Copyright (c) 1999-2018, by Zend Technologies

$gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
