### ISSUE TITLE
isConnected()这个方法的作用究竟是什么？

### ISSUE THREAD

**Issue by goukixiao** [swoole/swoole-src#376]
问题描述：
使用过程中，报错：swoole_client::isConnected(): object is not instanceof swoole_client.
如果swoole_client没有connect上服务器，这个isConnected就会报上面的错误 。。

$client = ....
原本是想判断如果没有connected就自动connected的，于是代码是
if( !$client->isConnected() ){
    $client->connect( .... )
}
但如果从来没有连接过服务器，就会直接报：swoole_client::isConnected(): object is not instanceof swoole_client.

**Comment by matyhtf** [comment]
这个函数返回连接是否建立。你可以忽略此错误。

**Comment by goukixiao** [comment]
我都是E_ALL的报错，所以看上去很揪心~

**Comment by matyhtf** [comment]
已去掉此错误报警。
