### ISSUE TITLE
协程中使用redis缓存setbit，进程退出重启

### ISSUE THREAD

**Issue by Leviosa-chen** [swoole/swoole-src#3760]
告警日志
async.c:463: redisProcessCallbacks: Assertion `(c->flags & 0x20 || c->flags & 0x40)' failed.
[2020-10-21 15:01:59 $16898.0]  WARNING swManager_check_exit_status: worker#4 abnormal exit, status=0, signal=6
SIGABRT
php 7.21
swoole 4.0.0-rc1

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by Yurunsoft** [comment]
更新到 Swoole 最新版后再尝试下，版本太旧了
