### ISSUE TITLE
disconnect中耗时操作导致 check_worker_exit_status: worker#1 abnormal exit

### ISSUE THREAD

**Issue by jiangyixiang** [swoole/swoole-src#3761]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```
class WebSocket
{
    public $server;
    function __construct($host='0.0.0.0', $port='8082')
    {
        $this->server = new \Swoole\WebSocket\Server($host, $port);
        $this->server->set([
            'log_level' => SWOOLE_LOG_WARNING,
            'heartbeat_check_interval' => 30,
            'heartbeat_idle_time' => 60,
            'reactor_num' => 1,
            'worker_num' => 2,
        ]);

        $this->server->on('open', [$this, '_onOpen']);
        $this->server->on('close', [$this, '_onClose']);

        $this->server->start();
    }

    public function _onOpen($ws, $request){
        $data = $request->get;
        if($data['token'] != 123){
            $ws->disconnect($request->fd, 1000, '登录已失效,请重新登录。');
        }
    }
    
    public function _onClose($ws, $fd){
        //耗时错误
        sleep(1);
        echo 'quit success'.PHP_EOL;

    }
}

new WebSocket();
```

```
<script>

    var ws = new WebSocket('ws://127.0.0.1:8082?token=1234');
    
    ws.onopen = function (event) {
        console.log('websocket连接成功...');
        console.log(event);
    };
    
    ws.onclose = function (event) {
        console.log('链接关闭');
        console.log(event);
    };

    ws.onerror = function (event) {
        console.log('出错了');
        console.log(event);
    };

</script>
```

2. What did you expect to see?
$ws->disconnect 可以正常返回错误码 和 reason
现在只要 onclose 中有耗时操作就会报错

3. What did you see instead?
![0915980A-1949-45DF-9A9C-689A42A2DA46](https://user-images.githubusercontent.com/20918782/96839139-571d4100-147b-11eb-9b55-0272aa117ca5.png)
![0D62855E-EEBF-44E4-A706-5BDFEA884C17](https://user-images.githubusercontent.com/20918782/96839178-6603f380-147b-11eb-90ba-2d1e509ad540.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?
Version => 4.5.5

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
centos7 php7.2

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by sy-records** [comment]
![image](https://user-images.githubusercontent.com/33931153/96844937-b2066680-1482-11eb-9172-5e319113376d.png)
没复现问题，看下是否有其他扩展影响？

另外问答也回复你了https://wenda.swoole.com/detail/107586

**Comment by jiangyixiang** [comment]
![4E6C0B04-32F1-47F0-A5DA-F8E6E869E23F](https://user-images.githubusercontent.com/20918782/96850927-fcd7ac80-1489-11eb-975f-73e717d5f864.png)

**Comment by GXhua** [comment]
请先用4.4LTS分支  4.5下个小版本修复

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by sy-records** [comment]
@jiangyixiang 你用的是v4.5.5坂本的release版本吗？

**Comment by jiangyixiang** [comment]
pecl上下的4.5.5 稳定版的压缩包
昨天用新华说的4.4.21的不会coredump了
十分感谢~



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 沈唁 <notifications@github.com&gt;
发送时间: 2020年10月23日 07:41
收件人: swoole/swoole-src <swoole-src@noreply.github.com&gt;
抄送: gushi jiang <823787361@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[swoole/swoole-src] disconnect中耗时操作导致 check_worker_exit_status: worker#1 abnormal exit (#3761)
