### ISSUE TITLE
Problems using Process modules in the Coroutine environment

### ISSUE THREAD

**Issue by Alion548** [swoole/swoole-src#3802]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
``` php
<?php
\Co\run(function () {
    $process = new swoole_process(function (swoole_process $process) {
        $process->exec('/bin/sleep', ['999']);
    }, true, 0, false);

    $process->start();
});
```
2. What did you expect to see?
```text
由于在协程空间内 fork 进程会带着其他协程上下文，因此底层禁止了在 Coroutine 中使用 Process 模块，所以该代码是有问题的，但是我只在子进程中调用exec函数，那么会将子进程代码段覆盖掉，那不就可以了？
```

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
