### ISSUE TITLE
Any way to timeout Coroutine::exec()?

### ISSUE THREAD

**Issue by eldadfux** [swoole/swoole-src#3805]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Run this command:

```php
$result = Swoole\Coroutine::exec($command);
```

2. What did you expect to see?

I need a way to timeout a command that take longer than X seconds to run.

3. What did you see instead?

Not sure how can I achieve this behaviour.

4. What version of Swoole are you using (show your `php --ri swoole`)?

```

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.6
Built => Nov  1 2020 21:48:04
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
http2 => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
Eldads-MacBook-Pro-2:base eldadfux$ 
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

php:7.4-cli-alpine image on macbook pro.

**Comment by doubaokun** [comment]
At the moment, there is no way to interrupt an external command running within the coroutine context. It is recommended to use process to manage it and you should be able to kill the process anytime.

**Comment by eldadfux** [comment]
Thanks @doubaokun !
