### ISSUE TITLE
HTTP Server in request callback

### ISSUE THREAD

**Issue by matiux** [swoole/swoole-src#3807]
I'm building a REST API using swoole 4.5.6 on PHP 7.4.11

Currently I'm using an HTTP Server and I think that it could be useful to inject the Swoole\HTTP\Server in the 'request' event callback function as well. This would allow me to then trigger a task worker once I’ve received the http request. Currently I’ve come up with the following solution:

```
$server->on('request', function (Request $request, Response $response) use ($server) {

   call_user_func('MyController::myAction', $response, $request);

   $server->task('..');
});
```

Is this the correct way?

**Comment by doubaokun** [comment]
Please check the example:

```php
<?php
$server = new Swoole\Http\Server("0.0.0.0", 9501, SWOOLE_BASE);
$server->set([
    'worker_num' => 1,
    'task_worker_num' => 2,
]);
$server->on('Request', function ($request, $response) use ($server) {
    $tasks[0] = ['time' => 0];
    $tasks[1] = ['data' => 'www.swoole.co.uk', 'code' => 200];
    $result = $server->taskCo($tasks, 1.5);
    $response->end('<pre>Task Result: '.var_export($result, true));
});
$server->on('Task', function (Swoole\Server $server, $task_id, $worker_id, $data) {
    if ($server->worker_id == 1) {
        sleep(1);
    }
    $data['done'] = time();
    $data['worker_id'] = $server->worker_id;
    return $data;
});
$server->start();
```

Check more on page: https://www.swoole.co.uk/docs/modules/swoole-server-taskCo

**Comment by matiux** [comment]
Thanks @doubaokun but my question is different. 
My question is about `request` event 

```
Swoole\HTTP\Server->on('request', fn)
```

According to the documentation, is the only event that doesn't pass `Server` object in the callback.

```
$http->on('request', function ($request, $response) {
    $response->end("<h1>Hello World. #".rand(1000, 9999)."</h1>");
});
```

So I have to inject `Server` with `use($server)`

```
$server->on('request', function ($request, $response) use ($server) {

});
```

My doubt is about this difference

**Comment by doubaokun** [comment]
That is the correct way and by design.
