### ISSUE TITLE
mac安装报错

### ISSUE THREAD

**Issue by cffycls** [swoole/swoole-src#3808]
Please answer these questions before submitting your issue. Thanks!
ok
1. What did you do? If possible, provide a simple script for reproducing the error.de
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole' (tried: /usr/local/Cellar/php/7.4.12/lib/php/20190902/swoole (dlopen(/usr/local/Cellar/php/7.4.12/lib/php/20190902/swoole, 0x0009): dlopen(): file not found: /usr/local/Cellar/php/7.4.12/lib/php/20190902/swoole), /usr/local/Cellar/php/7.4.12/lib/php/20190902/swoole.so (dlopen(/usr/local/Cellar/php/7.4.12/lib/php/20190902/swoole.so, 0x0009): code signature in (/usr/local/Cellar/php/7.4.12/lib/php/20190902/swoole.so) not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)) in Unknown on line 0

2. What did you expect to see?

more

3. What did you see instead?

?

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.5.6

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
7.4.12

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**
