### ISSUE TITLE
swoole4.5.6 php-8.0beta4 error: no member named 'function_name' in '_php_shutdown_function_entry'

### ISSUE THREAD

**Issue by yawepe** [swoole/swoole-src#3817]
./configure 通过
make 时提示 error: no member named 'function_name' in '_php_shutdown_function_entry'
`swoole-src-4.5.6/ext-src/php_swoole.cc:274:46: error: no member named 'function_name' in
      '_php_shutdown_function_entry'
    function_name = &shutdown_function_entry.function_name;
                     ~~~~~~~~~~~~~~~~~~~~~~~ ^
1 error generated.
make: *** [ext-src/php_swoole.lo] Error 1`

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by twose** [comment]
请升级到PHP8.0-RC3版本
