### ISSUE TITLE
make install is incorrect in docker php:rc-fpm

### ISSUE THREAD

**Issue by haohetao** [swoole/swoole-src#3820]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

2. What did you expect to see?

not copy header files to /usr/local/include/ext/swoole

3. What did you see instead?

cp -a include  /usr/local/include/php/ext/swoole/
cp -a ext-src  /usr/local/include/php/ext/swoole/
cp -a thirdparty  /usr/local/include/php/ext/swoole/

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

swoole 4.5.7
docker php:rc-fpm

**Comment by doubaokun** [comment]
@haohetao Could you send the whole Dockerfile?

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/56b07ae11c8e1c85ce77676f52348f7973508aa3

fixed
