### ISSUE TITLE
question: class names with underscore delimiters?

### ISSUE THREAD

**Issue by c9s** [swoole/swoole-src#383]
The PHP Coding Standards described the camel case class name is suggested. https://github.com/php/php-src/blob/master/CODING_STANDARDS#L154

> 7.  Classes should be given descriptive names. Avoid using abbreviations where
>     possible. Each word in the class name should start with a capital letter,
>     without underscore delimiters (CamelCaps starting with a capital letter).

It will be great If the class names in swoole can be converted to camel case, since it provides more consistency with other PHP components.

**Comment by Atriedes** [comment]
:+1: raised similar issue before, some is fixed by adding alias

**Comment by lscgzwd** [comment]
I agree with this, swoole need to format the code. Swoole is good, but with best code style will be known by more users.

**Comment by matyhtf** [comment]
We'll add class alias in the 1.8.0.

**Comment by matyhtf** [comment]
The version 1.8.1  now has support for namespaces class name.
Edit you php.ini file, append to file end.
```
swoole.use_namespace = On
```

PSR-4 class style sample:
-----
```php
use Swoole\Http\Server;
use Swoole\Http\Request;
use Swoole\Http\Response;

$serv = new Server('127.0.0.1', 9501);

$serv->on('Request', function(Request $req, Response $resp) {
    var_dump($req->header, get_class($req));
    $resp->end("<h1>Hello Swoole</h1>");
});

$serv->start();
```
