### ISSUE TITLE
websocket 消息push到socket缓冲区， 有什么可以监听socket缓冲区的消息有没有发送成功呢？

### ISSUE THREAD

**Issue by 523013183** [swoole/swoole-src#3831]
websocket 消息push到socket缓冲区， 有什么可以监听socket缓冲区的消息有没有发送成功呢？
发送过程是异步的，底层会自动监听可写，将数据逐步发送给客户端，也就是说不是 send 返回后对端就收到数据了。

那需要怎么判断这个对端能收到数据呢？ 除了回执的方法， 还有其他方法么？

**Comment by huanghantao** [comment]
@523013183 如果不在应用层判断ack，那么只能判断tcp层的ack了。我不清楚有没有这样的api操作，但是即使有，也会非常的麻烦吧，你还得知道你发送的数据的seq范围，然后再去判断对端发来的ack。相当于你在应用层实现了tcp协议的一部分了。

**Comment by matyhtf** [comment]
@523013183 请到 https://wenda.swoole.com/ 社区提问
