### ISSUE TITLE
If you try to start more tasks than task_worker_num they vanish in thin air

### ISSUE THREAD

**Issue by rgpublic** [swoole/swoole-src#3833]
I have a WebSockerServer. I set task_worker_num to 8. I'm seeing the following problem: If I start more than 8 tasks, the tasks that are over the limit never arrive in the "ontask" event (that is expected) BUT the $server->task() method in the worker doesn't return false either but is happily returning a task_id (unexpected). It seems there is no way of detecting that the task didn't start in the first place. Currently I'm using an Atomic and count the starting/finishing of tasks myself, but it's not ideal, of course.

What version of Swoole are you using (show your `php --ri swoole`)?
4.5.7

What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux panther 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-10ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)

**Comment by sy-records** [comment]
>  BUT the $server->task() method in the worker doesn't return false either but is happily returning a task_id (unexpected)

In fact, they are lining up, and there is a WARNING prompt.

```
 WARNING timer_callback (ERRNO 9007): No idle task worker is available
```
![image](https://user-images.githubusercontent.com/33931153/99631440-95a41c80-2a76-11eb-9226-a0fc381f2adb.png)

you can use [$ws->stats()['tasking_num']](https://www.swoole.co.uk/docs/modules/swoole-server-stats) to get number of them.

```php
$ws = new Swoole\WebSocket\Server('0.0.0.0', 9501);
$ws->set(['worker_num' => 2, 'task_worker_num' => 4]);

$ws->on('message', function ($ws, $frame) {
    $task_id = $ws->task($frame->data);
    echo "Dispatch AsyncTask: id=$task_id\n";
    echo "Number of tasks currently in queue=" . $ws->stats()['tasking_num'] . PHP_EOL;
    $ws->push($frame->fd, "server: {$frame->data}");
});

$ws->on('task', function ($serv, $task_id, $from_id, $data) {
    echo "New AsyncTask[id=$task_id]".PHP_EOL;
    sleep(10);
    $serv->finish("$data -> OK");
});

$ws->on('finish', function ($serv, $task_id, $data) {
    echo "AsyncTask[$task_id] Finish: $data".PHP_EOL;
});

$ws->on('close', function ($ws, $fd) {
    echo "client-{$fd} is closed\n";
});

$ws->start();
```

**Comment by doubaokun** [comment]
@rgpublic fell free to open this thread if you still have questions, closing for now.
