### ISSUE TITLE
websocket server不能主动断开客户端的连接

### ISSUE THREAD

**Issue by tonyvicky** [swoole/swoole-src#384]
解决办法 修改swoole_websocket.c
static PHP_METHOD(swoole_websocket_server, realclose);

ZEND_BEGIN_ARG_INFO_EX(arginfo_swoole_websocket_server_realclose, 0, 0, 2)
    ZEND_ARG_INFO(0, fd)
ZEND_END_ARG_INFO()

const zend_function_entry swoole_websocket_server_methods[] =
{
    PHP_ME(swoole_websocket_server, on,         arginfo_swoole_websocket_server_on, ZEND_ACC_PUBLIC)
    PHP_ME(swoole_websocket_server, push,       arginfo_swoole_websocket_server_push, ZEND_ACC_PUBLIC)
    PHP_ME(swoole_websocket_server, realclose,       arginfo_swoole_websocket_server_realclose, ZEND_ACC_PUBLIC)
    PHP_FE_END
};

static PHP_METHOD(swoole_websocket_server, realclose)
{
    //zval *zdata;
    long fd = 0;
    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "l", &fd) == FAILURE)
    {
        return;
    }
    swServer *serv = swoole_get_object(getThis());
    serv->factory.end(&serv->factory, fd);
}

之后PHP脚本这样写 $websocketserv->realclose($fd);

**Comment by sukui** [comment]
cool

**Comment by Lucups** [comment]
mark，也许能解决我们的问题
@bixuehujin
