### ISSUE TITLE
swoole-src-swoole-1.7.20-stable upload error【1.7.19没问题】

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#385]
<pre>
[/home/xxx/env-trunk/php/extensions/swoole-src-swoole-1.7.20-stable/src/reactor/ReactorPoll.c:245@swReactorPoll_wait]Event: fd=46|from_id=8|type=11
[/home/xxx/env-trunk/php/extensions/swoole-src-swoole-1.7.20-stable/src/reactor/ReactorPoll.c:245@swReactorPoll_wait]Event: fd=47|from_id=8|type=1
[/home/xxx/env-trunk/php/extensions/swoole-src-swoole-1.7.20-stable/src/network/Server.c:131@swServer_master_onAccept][Master] Accept new connection. maxfd=47|reactor_id=8|conn=56
[/home/xxx/env-trunk/php/extensions/swoole-src-swoole-1.7.20-stable/src/network/ReactorThread.c:1350@swReactorThread_onReceive_http_request]request->method=4
[/home/xxx/env-trunk/php/extensions/swoole-src-swoole-1.7.20-stable/src/network/ReactorThread.c:258@swReactorThread_close]Close Event.fd=56|from=0
[/home/xxx/env-trunk/php/extensions/swoole-src-swoole-1.7.20-stable/src/network/ReactorThread.c:319@swReactorThread_close]set_maxfd=55|close_fd=56

</pre>

<pre>
curl返回：
bool(false)
array(23) {
  ["url"]=>
  string(48) "http://127.0.0.1:8076/v1/show/upload?gt=zhangfan"
  ["content_type"]=>
  NULL
  ["http_code"]=>
  int(0)
  ["header_size"]=>
  int(0)
  ["request_size"]=>
  int(190)
  ["filetime"]=>
  int(-1)
  ["ssl_verify_result"]=>
  int(0)
  ["redirect_count"]=>
  int(0)
  ["total_time"]=>
  float(0.002031)
  ["namelookup_time"]=>
  float(0.001319)
  ["connect_time"]=>
  float(0.001464)
  ["pretransfer_time"]=>
  float(0.001466)
  ["size_upload"]=>
  float(180588)
  ["size_download"]=>
  float(0)
  ["speed_download"]=>
  float(0)
  ["speed_upload"]=>
  float(88915805)
  ["download_content_length"]=>
  float(-1)
  ["upload_content_length"]=>
  float(921944)
  ["starttransfer_time"]=>
  float(0.00156)
  ["redirect_time"]=>
  float(0)
  ["redirect_url"]=>
  string(0) ""
  ["primary_ip"]=>
  string(9) "127.0.0.1"
  ["certinfo"]=>
  array(0) {
  }
}
int(56)
string(41) "Failure when receiving data from the peer"
</pre>

**Comment by matyhtf** [comment]
Fixed https://github.com/swoole/swoole-src/commit/a07f160d85149cdda051aab05cf8e87f3fa43e7f

**Comment by yiliaofan** [comment]
谢谢老大@matyhtf　master编译测试后，没问题了。

**Comment by firedtoad** [comment]
韩老 你能 把 type hint 写全一点么  很多函数没有 type hint 让我这种依赖 zend 智能提示的怎么混 附件是用反射生成的 定义

2015-11-02 15:16 GMT+08:00 yiliaofan <notifications@github.com>:
