### ISSUE TITLE
cURL hook does not properly handle request headers

### ISSUE THREAD

**Issue by filakhtov** [swoole/swoole-src#3850]
Hello 👋 

We have recently started using Swoole and are currently evaluating if that is something feasible for us to use. As part of the evaluation, it was discovered that there is a problem in handling request headers by the Swoole's cURL hook.

We have nailed this problem down to [this block of code](https://github.com/swoole/swoole-src/blame/master/ext-src/php_swoole_library.h#L4025-L4027), but looking into the source code there are likely more problems of the similar kind.

The issue is that `empty($this->headers['Content-Type'])` checking for `Content-Type` key with capital `C` and capital `T`, however that does not cover lower-case `content-type` or crazy case of `CoNtEnT-TyPe` headers. This is a problem, because according to the [RFC 2616 - "Hypertext Transfer Protocol -- HTTP/1.1"](http://www.w3.org/Protocols/rfc2616/rfc2616.html), [Section 4.2, "Message Headers"](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2):

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-**IN**sensitive.

1. What did you do? If possible, provide a simple script for reproducing the error.

```php
$ch = curl_init('http://example.com');
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(['payload' => 'example']));
curl_setopt($ch, CURLOPT_HTTPHEADER, ['content-type: application/json']);
curl_exec($ch);
```

2. What did you expect to see?

Without Swoole, the request looks like following:
```
POST / HTTP/1.1
Host: example.com
Accept: */*
content-type: application/json
Content-Length: 21
```
^ Note a single `content-type` with the desired value.

3. What did you see instead?

The following request is sent if using Swoole:
```
POST / HTTP/1.1
Host: example.com
content-type: application/json
Content-Type: application/x-www-form-urlencoded
Connection: keep-alive
Accept-Encoding: gzip, deflate, br
Content-Length: 21
```
^ Note that there are two content-type headers and the latter overrides former.

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
$ php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.5
Built => Oct 27 2020 16:24:40
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1h  22 Sep 2020
http2 => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
$ uname -a
Darwin XXXXXXXXX 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

```
$ php -v
PHP 7.4.12 (cli) (built: Oct 29 2020 18:37:21) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
    with Sdebug v2.9.3-dev, Copyright (c) 2002-2020, by Derick Rethans
```

```
$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by filakhtov** [comment]
I would be willing to contribute a fix for this issue, however we would need to figure out the best way forward. A couple of possibilities that I can think of right away are:
- store all header names in the same case (lower or upper)
- create a custom data structure that can hold a collection of name-value pairs and handle their insertion and extraction
- keep the case "as is", but maintain a separate mapping in order to quickly resolve keys

I am also open for any other suggestions that you might have.

**Comment by sy-records** [comment]
Thank you for your feedback, We can start by converting it to lowercase.

**Comment by filakhtov** [comment]
Hey @sy-records, what do you think about this approach: swoole/library#76? This way we will consistently use the lower-case header names for all operations and avoid duplicate headers, such as `referer`, `content-type`, `cookie` and so on.

An alternative for this, if we would like to preserve headers case, would be to maintain a mapping between a lower-case representation and the actual array key, but I feel like this would be overkill. Open to feedback and recommendations.

**Comment by sy-records** [comment]
I have discussed this with @twose. If converted to lowercase, a copy of the mapping to the original header needs to be saved.

https://github.com/swoole/library/blob/22396e49b5082be44c314f437a084b4bafed706f/src/core/Curl/Handler.php#L478

**Comment by filakhtov** [comment]
Hey @sy-records, thanks a lot for the feedback. I have just pushed a change with an additional method that is responsible for managing headers in the case-insensitive manner and maintain a mapping between actual header name and its lower case representation. Would that work the way you and the team want?
