### ISSUE TITLE
Http Response header issues

### ISSUE THREAD

**Issue by malacca** [swoole/swoole-src#3851]
根据文档介绍

https://wiki.swoole.com/#/http_server?id=header-1

> 重复设置相同 $key 的 HTTP 头会覆盖，取最后一次

该设定与 RFC 2616 、7230 规范冲突，根据规范，若相同 header 头有多个值，不方便使用逗号分隔，是允许多次发送相同 key 的 header 

比如：

1. 最常见的是  "Set-Cookie" 可以发送多次

2. 理论上 “Cache-Control: no-cache, no-store” 也等价于
 > Cache-Control: no-cache
 > Cache-Control: no-store

3. 另外 Header 也支持  "X-**" 自定义头，存在相同 key 多次发送的可能性

原生 PHP 的 header 函数原型

`header ( string $header [, bool $replace = TRUE [, int $http_response_code ]] )`

很明显的，参数 $replace  可用于调整。 swoole 这个函数太武断了，没有留下任何调整余地。

-------------------------------

举一个实际操作碰到的问题

swoole 设置 cookie

https://wiki.swoole.com/#/http_server?id=cookie-1

这里有一个 goolge 的提案，并且 chrome 已实现并支持

https://tools.ietf.org/html/draft-west-cookie-priority-00

swoole 的 Response->cookie 无法顺利发送包含 priority 的 cookie，退而求其次，自行通过 header 发送，但又因为HTTP 头覆盖的问题而无法实现。

所以： Swoole\Http\Response->header 函数可否增加一个参数，以便更加兼容 HTTP 协议。

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/pull/3854

先增加了对于 cookie priority 的支持，后续考虑优化这里。

**Comment by malacca** [comment]
@matyhtf   google 那个提案目前还没有通过，还未并入协议标准，也就是说后续还有变动的可能性。并且当下只有 chrome 实现了而已，Response->cookie 其实没必要这么激进，当下已经是符合 RFC 标准的。

Response->header 才是问题所在，这个函数不支持发送重复 key 的 header， 堵死了遵循 RFC 协议的操作。建议给这个增加一个参数，这样也可以向后兼容，不会对当前已使用 swoole 的程序造成副作用

**Comment by matyhtf** [comment]
@malacca 这个变动底层要修改的地方较多。在 4.6 版本中会解决
