### ISSUE TITLE
php8-RC5 make error

### ISSUE THREAD

**Issue by yawepe** [swoole/swoole-src#3865]
php version:   php8-RC5
swoole version: 4.5.8

swoole-src-4.5.8/ext-src/php_swoole.h:918:11: error: use of undeclared identifier 'zend_is_callable_at_frame'
    ret = zend_is_callable_at_frame(zcallable, zobject ? Z_OBJ_P(zobject) : NULL, frame, check_flags, &name, fci_cache, error);

**Comment by doubaokun** [comment]
@yawepe This will be fixed when PHP releases the next RC or on the master branch.
