### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by haohetao** [swoole/swoole-src#3867]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

2. What did you expect to see?

php_swoole.h:918:11: error: 'zend_is_callable_at_frame' was not declared in this scope
     ret = zend_is_callable_at_frame(zcallable, zobject ? Z_OBJ_P(zobject) : NULL, frame, check_flags, &name, fci_cache, error);

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
php8.0rc5
swoole4.5.8

**Comment by haohetao** [comment]
Why are there always a few compilation errors in each new version

**Comment by huanghantao** [comment]
> Why are there always a few compilation errors in each new version

@haohetao Because with each PHP version, PHP itself may have an API behavior change.
