### ISSUE TITLE
WARN	swFactoryProcess_finish: sendto to reactor failed. Error: Message too long [90]

### ISSUE THREAD

**Issue by designinlife** [swoole/swoole-src#387]
$serv->send() 仅发送 3100 字节报这个警告，且消息并没有发出去！1.7.20 稳定版

使用 gz 压缩到 1300 字节就可以发出去。问下会是什么原因呢？
在两台不同的虚拟机上测试过，其中一台是 OK 的，另一台始终不行，包括 sysctl.conf 参数设置都同步过，测试还是不行！

**Comment by matyhtf** [comment]
需要修改内核参数，sysctl -w net.local.dgram.maxdgram=8192
