### ISSUE TITLE
ssl的swoole_event_write问题

### ISSUE THREAD

**Issue by tangxunye** [swoole/swoole-src#388]
$fp = stream_socket_client("ssl://127.0.0.1:9511", $code, $msg, 3);

fwrite($fp, $data);
swoole_event_add($fp, function ($fp) {

});

fwrite($fp, $data);
swoole_event_set($fp, function ($fp) {

});

swoole_event_write($fp, $data);

在使用ssl连接的时候，swoole_event_write不能生效，请问是什么原因？

**Comment by matyhtf** [comment]
ssl的write比较复杂，发送操作也可能需要读取，建议不要用swoole_event_write
