### ISSUE TITLE
Unable to cast curl_init to int in >=4.5.4

### ISSUE THREAD

**Issue by grizzm0** [swoole/swoole-src#3883]
1. What did you do? If possible, provide a simple script for reproducing the error.

I've got a dependency on [ezimuel/ringphp](https://github.com/ezimuel/ringphp) which casts `curl_init()` to an int ([see here](https://github.com/ezimuel/ringphp/blob/0b78f89d8e0bb9e380046c31adfa40347e9f663b/src/Client/CurlHandler.php#L109)). 

This was working fine in swoole <=4.5.3 but stopped working with swoole >=4.5.4.

2. What did you expect to see?

3. What did you see instead?
```
ErrorException (E_NOTICE)
Object of class Swoole\Curl\Handler could not be converted to int
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.4
Built => Nov 26 2020 07:16:59
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
Linux 525268495fb3 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64 Linux
PHP 7.4.12 (cli) (built: Nov  5 2020 20:41:34) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

**Comment by sy-records** [comment]
```
Object of class Swoole\Curl\Handler could not be converted to int
```

This is a known problem with Hook Curl, `SWOOLE_HOOK_CURL` is switched on by default from v4.5.4 onwards, You can manually switch off to resolve the problem.

```php
Co::set(['hook_flags'=> SWOOLE_HOOK_ALL ^ SWOOLE_HOOK_CURL]);
```

**Comment by grizzm0** [comment]
Right. So not a bug then. Thanks. :)

**Comment by sy-records** [comment]
@grizzm0 Are there any questions? You can replace guzzle's handler to use Coroutine.

**Comment by grizzm0** [comment]
Thanks @sy-records 

It's a third party dependency of [elastic/elasticsearch-php](https://github.com/elastic/elasticsearch-php) though and I'd rather not override the dependency.
Seems like they'll replace the HTTP transport in a future release here https://github.com/elastic/elasticsearch-php/issues/1028

I guess I'll just have to stay on an older version or disable SWOOLE_HOOK_CURL in [mezzio/mezzio-swoole](https://github.com/mezzio/mezzio-swoole) for now.

I guess this is not fixable in swoole itself? In that case we can close the issue.

**Comment by sy-records** [comment]
It should be these components that go on to modify the code, and in PHP8, curl is not a resource type anymore.

**Comment by CuongPhi** [comment]
Please help me fix this bug in mezzio/mezzio-swoole
Many thanks!

**Comment by grizzm0** [comment]
> Please help me fix this bug in mezzio/mezzio-swoole
> Many thanks!

```php
<?php

declare(strict_types=1);

namespace Core;

use Swoole\Http\Server as SwooleHttpServer;

final class ConfigProvider
{
    public function __invoke(): array
    {
        return [
            'dependencies' => $this->getDependencies(),
        ];
    }

    private function getDependencies(): array
    {
        return [
            'delegators' => [
                SwooleHttpServer::class => [
                    Factory\Delegator\SwooleHttpServerDelegatorFactory::class,
                ],
            ],
        ];
    }
}
```

```php
<?php

declare(strict_types=1);

namespace Core\Factory\Delegator;

use Interop\Container\ContainerInterface;
use Laminas\ServiceManager\Factory\DelegatorFactoryInterface;
use Swoole\Http\Server;

use const SWOOLE_HOOK_ALL;
use const SWOOLE_HOOK_CURL;

final class SwooleHttpServerDelegatorFactory implements DelegatorFactoryInterface
{
    public function __invoke(ContainerInterface $container, $name, callable $callback, ?array $options = null): Server
    {
        /** @var Server $swooleHttpServer */
        $swooleHttpServer = $callback();
        $swooleHttpServer->set([
            'hook_flags' => SWOOLE_HOOK_ALL ^ SWOOLE_HOOK_CURL,
        ]);

        return $swooleHttpServer;
    }
}
```

**Comment by CuongPhi** [comment]
![image](https://user-images.githubusercontent.com/33374839/112602927-e1147000-8e46-11eb-94be-0d670ee4e16e.png)
I've set this option and still error.

**Comment by grizzm0** [comment]
`hook_flags` needs to be in the `options` array.

Didn't know the options was exposed like that. Thanks. In that case there's no need for my delegator.

**Comment by CuongPhi** [comment]
I got it. I will try this. Thank you!
I deleted image attach because of policy.

**Comment by babarinde** [comment]
> `hook_flags` needs to be in the `options` array.
> 
> Didn't know the options was exposed like that. Thanks. In that case there's no need for my delegator.

+1
