### ISSUE TITLE
swoole_timer_add是不是有bug？跑着跑着就不跑了

### ISSUE THREAD

**Issue by hisune** [swoole/swoole-src#389]
swoole版本1.7.18
swoole_timer_add定时20秒，跑了几十天后，突然不跑了。。
我看到swoole-1.7.19-stable里面有一个：
Fixed timer in the system can not recover after the resumption of the operation
是不是和这个bug有关呢？

**Comment by matyhtf** [comment]
是的，和这个BUG有关。你可以升级到最新版本
