### ISSUE TITLE
在php8.0-cli版本上安装扩展 swoole-4.5.9失败

### ISSUE THREAD

**Issue by diankemao** [swoole/swoole-src#3890]
php版本php8.0-cli
swoole版本swoole-4.5.9
报错信息：
In file included from /tmp/swoole/ext-src/php_swoole_cxx.h:19,
                 from /tmp/swoole/ext-src/php_swoole.cc:16:
/tmp/swoole/ext-src/php_swoole.h: In function 'zend_bool sw_zend_is_callable_at_frame(zval*, zval*, zend_execute_data*, uint, char**, size_t*, zend_fcall_info_cache*, char**)':
/tmp/swoole/ext-src/php_swoole.h:918:11: error: 'zend_is_callable_at_frame' was not declared in this scope
     ret = zend_is_callable_at_frame(zcallable, zobject ? Z_OBJ_P(zobject) : NULL, frame, check_flags, fci_cache, error);
           ^~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/swoole/ext-src/php_swoole.h:918:11: note: suggested alternative: 'sw_zend_is_callable_at_frame'
     ret = zend_is_callable_at_frame(zcallable, zobject ? Z_OBJ_P(zobject) : NULL, frame, check_flags, fci_cache, error);
           ^~~~~~~~~~~~~~~~~~~~~~~~~
           sw_zend_is_callable_at_frame
make: *** [Makefile:209: ext-src/php_swoole.lo] Error 1

**Comment by diankemao** [comment]
![image](https://user-images.githubusercontent.com/32607562/100408708-09ad7880-30a6-11eb-976a-d571a5ecb729.png)

**Comment by zhangyu19851112** [comment]
我是php 7.4.13 ，也是编译报错

```
/data/download/swoole-src-4.5.9/ext-src/swoole_redis_server.cc: In function ¡®int redis_onReceive(swServer*, swRecvData*)¡¯:
/data/download/swoole-src-4.5.9/ext-src/swoole_redis_server.cc:127:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
             if (*p == '*' && (p = swRedis_get_number(p, &ret))) {
             ^~
/data/download/swoole-src-4.5.9/ext-src/swoole_redis_server.cc:133:9: note: here
         case SW_REDIS_RECEIVE_LENGTH:
         ^~~~
/data/download/swoole-src-4.5.9/ext-src/swoole_redis_server.cc:144:18: error: this statement may fall through [-Werror=implicit-fallthrough=]
             else if (*p == ':' && (p = swRedis_get_number(p, &ret))) {
                  ^~
/data/download/swoole-src-4.5.9/ext-src/swoole_redis_server.cc:150:9: note: here
         case SW_REDIS_RECEIVE_STRING:
         ^~~~
cc1plus: all warnings being treated as errors
Makefile:240: recipe for target 'ext-src/swoole_redis_server.lo' failed
make: *** [ext-src/swoole_redis_server.lo] Error 1
```

**Comment by twose** [comment]
@diankemao 请展示php -v, 确认不是rc版本

**Comment by diankemao** [comment]
@twose 嗯，是php8.0-rc5-cli版本

**Comment by sy-records** [comment]
用GA版本。https://github.com/php/php-src/releases/tag/php-8.0.0

**Comment by Alion548** [comment]
sdebug 不支持PHP 8，请问PHP 8环境下如何调试代码？

**Comment by haohetao** [comment]
php8.0 docker image hasn't been released yet

**Comment by matyhtf** [comment]
> sdebug 不支持PHP 8，请问PHP 8环境下如何调试代码？

sdebug 会尽快支持

**Comment by Lskcv** [comment]
请问怎么解决的
