### ISSUE TITLE
Sdebug PHP8.0 support.

### ISSUE THREAD

**Issue by evonicgu** [swoole/swoole-src#3892]
PHP8.0 is already released. Is there any information about sdebug to use xdebug3.0 and add PHP8.0 support?

**Comment by matyhtf** [comment]
https://github.com/swoole/yasd

Recommended Use

**Comment by evonicgu** [comment]
Is it xdebug compatible? Can I use it with PhpStorm?

**Comment by sy-records** [comment]
Currently only command line support, PhpStorm will be supported later

**Comment by Rastusik** [comment]
Is there any chance that Sdebug 3.0 would be released until Yasd will support PHPStorm? This problem currently blocks our migration to PHP 8, which is kind of painful. We would gladly migrate to Yasd after there is support for PHPStorm, but until then it feels like there is no workaround. Terminal debugging is quite user unfriendly compared to PHPStorm.

**Comment by huanghantao** [comment]
Yasd support php8, you can try it.



---Original---
