### ISSUE TITLE
编译4.5.9时报g++: fatal error: Killed signal terminated program cc1plus

### ISSUE THREAD

**Issue by longjianghu** [swoole/swoole-src#3893]
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [Makefile:232: ext-src/swoole_mysql_coro.lo] Error 1
make: *** Waiting for unfinished jobs....

**Comment by matyhtf** [comment]
请降低 make -j 的并发数量，这可能是编译时内存不足
