### ISSUE TITLE
unknown type name clock_id_t

### ISSUE THREAD

**Issue by kaysonwu** [swoole/swoole-src#3895]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

我正在编译 `swoole 4.4.22`，我遇到了一个错误：

```shell
/root/tmp/swoole-src-4.4.22/include/swoole.h:2509:26: error: unknown type name ‘clock_id_t’
 int swoole_clock_gettime(clock_id_t which_clock, struct timespec *t);
```

2. What did you expect to see?

顺利编译

3. What did you see instead?

编译错误

4. What version of Swoole are you using (show your `php --ri swoole`)?

1.10.3

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
GCC:                            6.5.0
Linux:                       CentOS release 6.9 (Final)
PHP Version:                7.2.3
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
```

**Comment by kaysonwu** [comment]
翻阅了下 Swoole 的源码，我知道下 `clock_id_t` 是属于哪个库定义的类型？另外，我看可以通过安装 `librt` 库进行解决这个问题，但是 `librt`  的库在哪里下载？

**Comment by kaysonwu** [comment]
[config.log](https://github.com/swoole/swoole-src/files/5610747/config.log)
我估计是因为我的系统有 2 个 gcc 编译器导致的，一个 gcc 4.4.7 (CentOS 自带 yum 源装的)，不符合 swoole 的编译需求，所以我就源码编译了个 6.5.0 的。但是将 6.5.0 软连接到 cc，然后就会出现 `ld: crtbegin.o: No such file: No such file or directory`

**Comment by matyhtf** [comment]
goto https://github.com/swoole/swoole-src/issues/3896

**Comment by kaysonwu** [comment]
本问题论证结束，证明是编译器的问题，解决了编译器的问题，就可以顺利通过编译！

**Comment by matyhtf** [comment]
fixed https://github.com/swoole/swoole-src/commit/e741fbde0a8ca90ea9ba28c6132cf8ffe8471bcc
