### ISSUE TITLE
error: unknown type name 'clock_id_t'

### ISSUE THREAD

**Issue by ryandesign** [swoole/swoole-src#3896]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Build swoole 4.5.9 on OS X 10.11 or earlier.

2. What did you expect to see?

Successful build.

3. What did you see instead?

Build failure. [Full log](https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/126447/steps/install-port/logs/stdio). Relevant errors are:

```
include/swoole.h:533:26: error: unknown type name 'clock_id_t'; did you mean 'clock_t'?
include/swoole.h:538:26: error: use of undeclared identifier 'CLOCK_REALTIME'
```

`clock_gettime` and other realtime clock stuff is not available prior to macOS 10.12.

Your configure script has a check for this:

```
checking for clock_gettime in -lc... no
```

Based on this check, I expected that your build system would use an alternative that did not require `clock_gettime` and friends.

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole 4.5.9

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Problem occurs on OS X 10.11 and earlier. Compiler and PHP version are irrelevant. Problem verified with php 7.1, 7.2, 7.3, 7.4.

```
Darwin hostname-redacted 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64
```
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

This may be the same problem as #3895

**Comment by matyhtf** [comment]
fixed https://github.com/swoole/swoole-src/commit/e741fbde0a8ca90ea9ba28c6132cf8ffe8471bcc
