### ISSUE TITLE
Unable to load dynamic library 'swoole.so' - undefined symbol: socket_ce

### ISSUE THREAD

**Issue by Ahmard** [swoole/swoole-src#3904]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Trying to use swoole

2. What did you expect to see?
To work just fine

3. What did you see instead?
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/lib/php/20200930/swoole.so (/usr/lib/php/20200930/swoole.so: undefined symbol: socket_ce), /usr/lib/php/20200930/swoole.so.so (/usr/lib/php/20200930/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.5.9

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux AhmardPC 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
ahmard@AhmardPC:~$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/lib/php/20200930/swoole.so (/usr/lib/php/20200930/swoole.so: undefined symbol: socket_ce), /usr/lib/php/20200930/swoole.so.so (/usr/lib/php/20200930/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 8.0.0 (cli) (built: Nov 27 2020 12:26:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies
ahmard@AhmardPC:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
![Screenshot from 2020-11-30 21-27-41-cropped](https://user-images.githubusercontent.com/44737217/100662173-d2b0be80-3354-11eb-8d38-8d801f7d4c15.png)

**Comment by ValiDrv** [comment]
You did not install swoole correctly.

```
FROM php:8.0-cli

# Common stuff
RUN apt-get update \
    && apt-get install -yq \
        build-essential \
        git \
       ... whatever you need ...
    && rm -r /var/lib/apt/lists/*

# PHP extensions
# Note: php8.0: `json` if added by default, must remove.
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
   && docker-php-ext-install -j$(nproc) \
        sockets \
        ... whatever php extensions you need ...

# PHP Swoole
ENV EXT_SWOOLE_VERSION=v4.5.9
RUN git clone https://github.com/swoole/swoole-src.git \
  && cd swoole-src \
  && git checkout $EXT_SWOOLE_VERSION \
  && phpize \
  && ./configure \
  --enable-openssl \
  --enable-sockets \
  --enable-http2 \
  --enable-mysqlnd \
  && make && make install \
  && docker-php-ext-enable swoole \
  && cd .. \
  && rm -rf swoole-src
```

**Comment by Ahmard** [comment]
If that's the case, the problem came from "pecl", because I use "pecl install swoole".

I will try your way, thank you.

**Comment by Ahmard** [comment]
Your solution worked.
Thank you.
