### ISSUE TITLE
swoole因post请求包大小，导致处理速度产生波动问题

### ISSUE THREAD

**Issue by Frank-JY** [swoole/swoole-src#3914]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

我使用进行curl包验证系统的时候发现，请求包的字符串大于一定值时，请求会慢一秒钟进入swoole逻辑处理。请问您们你那边有遇到过吗
![image](https://user-images.githubusercontent.com/20394301/101305518-d88b3000-387d-11eb-8885-26f7fe0f3193.png)
![image](https://user-images.githubusercontent.com/20394301/101305624-07090b00-387e-11eb-87eb-737dd1d88f9b.png)
请求包示例：
curl -d '{"version":1,"componentName":"swoole_pricecenter","eventId":237406114,"seqId":"715338660","timestamp":1607000400,"caller":"swoole_pricecenter","interface":{"interfaceName":"qcloud.discount.query","para":{"ReqTime":1607000400,"TransTime":1607000400,"SeqId":"160700040054424","UserId":"100005116726","ActivityId":"0","CommodityList":{"product_2#1000001#1000043#sv_cvm_bandwidth_prepay":{"Business":"cvm","Conditions":{"ownerUin":"1000051167261","monNum":"1"},"Product":"cvm","ProductCodeNew":[{"names":"p_cvm","sub_product_code":"sp_cvm_s2sss"}]}}}}}' 9.223.63.30:61235

2. What did you expect to see?

请求时间不因请求包大小而发生剧烈波动

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.16
Built => Jul 22 2020 20:27:58

![image](https://user-images.githubusercontent.com/20394301/101305787-5fd8a380-387e-11eb-9edb-dced0f17ad8d.png)

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
[root@qbilling-discount-new-dev-0 ~]# uname -a
Linux qbilling-discount-new-dev-0 3.10.107-1-tlinux2_kvm_guest-0051 #1 SMP Sat Dec 7 22:03:22 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@qbilling-discount-new-dev-0 ~]# /usr/local/services/php.7.21/bin/php -v   
PHP 7.2.1 (cli) (built: Jan 11 2018 19:22:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
[root@qbilling-discount-new-dev-0 ~]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 

希望收到您们的答复

**Comment by huanghantao** [comment]
我无法复现你的问题。这是我的代码：

```php
<?php

$host = '127.0.0.1';
$port = 9501;

$server = new Swoole\Http\Server($host, $port, SWOOLE_PROCESS, SWOOLE_SOCK_TCP);

$server->set([
    'worker_num' => 1,
]);

$server->on('Request', function (Swoole\Http\Request $request, Swoole\Http\Response $response) {
    $response->end('hello swoole');
});

$server->start();
```

这是测试结果：

![83E5454B-5CFB-4CCA-B350-675CD087892B](https://user-images.githubusercontent.com/22836925/101308003-c613f500-3883-11eb-9f12-ade41c979a5d.png)

**Comment by huanghantao** [comment]
你用我这份最简单的服务器代码会出现你这个问题吗？

**Comment by Frank-JY** [comment]
可以的，我是容器部署，虚拟机就没有这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "swoole/swoole-src"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 中午12:00
收件人:&nbsp;"swoole/swoole-src"<swoole-src@noreply.github.com&gt;;
抄送:&nbsp;"550507713"<550507713@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [swoole/swoole-src] swoole因post请求包大小，导致处理速度产生波动问题 (#3914)





 
我无法复现你的问题。这是我的代码：
 <?php $host = '127.0.0.1'; $port = 9501; $server = new Swoole\Http\Server($host, $port, SWOOLE_PROCESS, SWOOLE_SOCK_TCP); $server-&gt;set([     'worker_num' =&gt; 1, ]); $server-&gt;on('Request', function (Swoole\Http\Request $request, Swoole\Http\Response $response) {     $response-&gt;end('hello swoole'); }); $server-&gt;start();
 
这是测试结果：

**Comment by Frank-JY** [comment]
如果可以的话，请加我微信：q13650161211




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "swoole/swoole-src"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 中午12:01
收件人:&nbsp;"swoole/swoole-src"<swoole-src@noreply.github.com&gt;;
抄送:&nbsp;"550507713"<550507713@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [swoole/swoole-src] swoole因post请求包大小，导致处理速度产生波动问题 (#3914)





 
你用我这份最简单的服务器代码会出现你这个问题吗？

**Comment by Frank-JY** [comment]
time curl -d '{"version":1,"componentName":"swoole_pricecenter","eventId":632018689,"seqId":"1596831764","timestamp":1607268256,"caller":"swoole_pricecenter","interface":{"interfaceName":"qcloud.discount.query","para":{"ReqTime":1607268256,"TransTime":1607268256,"SeqId":"160726825616308","UserId":"2783211945","ActivityId":"0","CommodityList":{"product_1002358#1002357#sv_snapshot_storagespace_normal":{"Business":"cbs_snapshot","Conditions":{"ownerUin":"2783211945","monNum":"1","goodsType":"cbs_snapshot","goodsSubType":"cbs_snapshot_normal","goodsAction":"","regionId":"22","payMode":"postpay","deviceClass":"","pid":"1002358","activityId":"0","currency":"CNY","zoneId":"0","snapTotalSize":"282.64","sv_snapshot_storagespace_normal":"282.64","storage":"282.64","regionName":"22","rootCbs":"0","rootCbsSsd":"0","rootCbsPremium":"0","rootDisk":"0","cbsSsd":"0","cbsPremium":"0","gpu":"0","cvm":"1","billingCycle":"6","timeSpan":"1","timeUn":"m"},"Product":"cbs_snapshot_normal","ProductCodeNew":[{}]}},"interfaceName":"query_discount"}}}' 9.223.63.30:61235
----
请用这个请求包复现，上面的请求包被我压缩了

**Comment by huanghantao** [comment]
CURL在发送较大的POST请求时会首先发送一个100-continue的请求，当收到服务器的回应才会发送实际的POST数据。然后swoole_http_server并不支持100-continue，因此会导致CURL请求超时。解决的办法时关闭CURL的100-continue。

**Comment by matyhtf** [comment]
这是 curl 100-continue 问题导致的。请添加 curl 配置

```php
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Expect:"));
```

**Comment by Frank-JY** [comment]
其他模块如果使用curl方式调用这个swoole时，如果不关闭的话是否有延时问题，这影响感觉很大，毕竟不能约束调用方。且post请求包比较小时也难以发现这个问题。

**Comment by Frank-JY** [comment]
![image](https://user-images.githubusercontent.com/20394301/101319867-a38ed580-389d-11eb-9616-c87d90328431.png)

![image](https://user-images.githubusercontent.com/20394301/101319856-9e318b00-389d-11eb-953f-b5748336d6ff.png)

**Comment by huanghantao** [comment]
因为这个100-continue是个很古老的设计，在现在没很大的意义。你可以用`golang`来测试，它会直接当作错误来，不会接收`post body`：

```go
package main

import (
	"net/http"
)

func main() {

	//Create the default mux
	mux := http.NewServeMux()

	//Handling the /v1/teachers. The handler is a function here
	mux.HandleFunc("/", teacherHandler)

	//Create the server.
	s := &http.Server{
		Addr:    ":9501",
		Handler: mux,
	}
	s.ListenAndServe()
}

func teacherHandler(res http.ResponseWriter, req *http.Request) {
	data := []byte("V1 of teacher's called")
	res.WriteHeader(200)
	res.Write(data)
}
```

**Comment by Frank-JY** [comment]
谢谢。我还想知道，为什么我虚拟机上的swoole项目没有发生100-continue超时的问题，而容器环境上发生了。
请问你们所有环境当发送较大的POST，都发生100-continue问题了吗？

**Comment by huanghantao** [comment]
你可以看看你的`swoole_config.h`文件，看看这段注释有没有被你们取消：

```cpp
// #define SW_HTTP_100_CONTINUE
```

如果注释被你们取消了，就相当于开启了`Swoole`的`100 continue`功能。

**Comment by Frank-JY** [comment]
看了下确实打开了，但我虚机环境下发送post大包时没有问题。疑惑。
![image](https://user-images.githubusercontent.com/20394301/101326866-d8ecf080-38a8-11eb-8658-bd15d46c7c7b.png)

**Comment by huanghantao** [comment]
> 看了下确实打开了，但我虚机环境下发送post大包时没有问题。疑惑。
> ![image](https://user-images.githubusercontent.com/20394301/101326866-d8ecf080-38a8-11eb-8658-bd15d46c7c7b.png)

打开了注释才不会有curl等待问题，因为此时服务器会响应这个`HTTP/1.1 100 Continue`。

**Comment by Frank-JY** [comment]
那问题来了，容器环境上也是打开了#define SW_HTTP_100_CONTINUE，为何还有Continue问题

**Comment by huanghantao** [comment]
> 那问题来了，容器环境上也是打开了#define SW_HTTP_100_CONTINUE，为何还有Continue问题

微信聊吧

**Comment by luolaifa000** [comment]
我也有些疑问， 同一个请求，一个是1.007 时间， 一个是0.011时间， 为啥多一次 100_CONTINUE 收包，会多这么多的时间。

**Comment by huanghantao** [comment]
> 我也有些疑问， 同一个请求，一个是1.007 时间， 一个是0.011时间， 为啥多一次 100_CONTINUE 收包，会多这么多的时间。

因为`curl`在等一个`100 continue`的响应，但是`Swoole`不会发送这个响应。`curl`一直等待，直到超时（`1s`）。所以会差一秒。`curl`等待超时之后，`curl`会发送这个`post`的`body`。

**Comment by huanghantao** [comment]
> > 我也有些疑问， 同一个请求，一个是1.007 时间， 一个是0.011时间， 为啥多一次 100_CONTINUE 收包，会多这么多的时间。
> 
> 因为`curl`在等一个`100 continue`的响应，但是`Swoole`不会发送这个响应。`curl`一直等待，直到超时（`1s`）。所以会差一秒。`curl`等待超时之后，`curl`会发送这个`post`的`body`。

既然`curl`超时之后，还会发送这个`body`，那这是不是看起来很鸡肋这个功能？干脆一开始就发这个`body`得了。

**Comment by luolaifa000** [comment]
那现在的版本是默认打开了 SW_HTTP_100_CONTINUE  支持100-CONTINUE 了是吗

**Comment by luolaifa000** [comment]
但是我看4.4.16版本上 ， 是默认注释// #define SW_HTTP_100_CONTINUE  这个定义的，那还会出现等待超时吗？

**Comment by huanghantao** [comment]
> 但是我看4.4.16版本上 ， 是默认注释// #define SW_HTTP_100_CONTINUE 这个定义的，那还会出现等待超时吗？

如果注释了，那应该是会等待超时的

**Comment by luolaifa000** [comment]
OK

**Comment by luolaifa000** [comment]
> > 我也有些疑问， 同一个请求，一个是1.007 时间， 一个是0.011时间， 为啥多一次 100_CONTINUE 收包，会多这么多的时间。
> 
> 因为`curl`在等一个`100 continue`的响应，但是`Swoole`不会发送这个响应。`curl`一直等待，直到超时（`1s`）。所以会差一秒。`curl`等待超时之后，`curl`会发送这个`post`的`body`。

这个默认的超时是多少

**Comment by luolaifa000** [comment]
> > 我也有些疑问， 同一个请求，一个是1.007 时间， 一个是0.011时间， 为啥多一次 100_CONTINUE 收包，会多这么多的时间。
> 
> 因为`curl`在等一个`100 continue`的响应，但是`Swoole`不会发送这个响应。`curl`一直等待，直到超时（`1s`）。所以会差一秒。`curl`等待超时之后，`curl`会发送这个`post`的`body`。

这个默认的超时是多少呢？

**Comment by huanghantao** [comment]
> > > 我也有些疑问， 同一个请求，一个是1.007 时间， 一个是0.011时间， 为啥多一次 100_CONTINUE 收包，会多这么多的时间。
> > 
> > 
> > 因为`curl`在等一个`100 continue`的响应，但是`Swoole`不会发送这个响应。`curl`一直等待，直到超时（`1s`）。所以会差一秒。`curl`等待超时之后，`curl`会发送这个`post`的`body`。
> 
> 这个默认的超时是多少呢？

大概是`1`秒
