### ISSUE TITLE
Build failure on Apple Silicon

### ISSUE THREAD

**Issue by ryandesign** [swoole/swoole-src#3917]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Compile swoole 4.5.9 on a Mac with Apple Silicon

2. What did you expect to see?

Successful compile

3. What did you see instead?

Build failure. [Full log](https://build.macports.org/builders/ports-11_arm64-builder/builds/5076/steps/install-port/logs/stdio)

```
thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:45:5: error: unexpected token at start of statement
    @ shift address in A1 to lower 16 byte boundary
    ^
thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:46:9: error: invalid operand for instruction
    bic a1, a1, #15
        ^
thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:48:5: error: unexpected token at start of statement
    @ reserve space for context-data on context-stack
    ^
```

and so on.

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.5.9

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
Darwin REDACTED 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:18 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8020 arm64
```

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: arm64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

PHP version irrelevant; verified with php 8.0, 7.4, 7.3.

**Comment by dixyes** [comment]
try this patch

will it fix the error?

```patch
diff --git a/config.m4 b/config.m4
index 47469cfc6..0aa469086 100644
--- a/config.m4
+++ b/config.m4
@@ -609,9 +609,9 @@ if test "$PHP_SWOOLE" != "no"; then
       [x86_64*], [SW_CPU="x86_64"],
       [x86*], [SW_CPU="x86"],
       [i?86*], [SW_CPU="x86"],
-      [arm*], [SW_CPU="arm"],
       [aarch64*], [SW_CPU="arm64"],
       [arm64*], [SW_CPU="arm64"],
+      [arm*], [SW_CPU="arm"],
       [mips*], [SW_CPU="mips32"],
       [
         SW_USE_ASM_CONTEXT="no"
```

**Comment by ryandesign** [comment]
Thanks, that looks like a reasonable change, but the problem remains. [New log](https://build.macports.org/builders/ports-11_arm64-builder/builds/5694/steps/install-port/logs/stdio) with that patch applied.

**Comment by ryandesign** [comment]
This case statement is using the value of `host_cpu`, which I believe is set by the configure script based on the first of the three dash-separated values in this triple:
```
checking host system type... arm-apple-darwin20.1.0
```
As you can see, on Apple Silicon, the host is "arm" even though yes this is a 64-bit CPU. I suppose you are expecting this instead to be `arm64-apple-darwin20.1.0`. I suppose this is coming from the config.guess / config.sub files bundled with php, which I suppose means that those files have not yet been updated for Apple Silicon. (In php 8.0.0, the `timestamp` variable in those files is `2020-01-01`; Apple Silicon was announced in June 2020.)

php should update to newer config.guess / config.sub files, however I question the strategy of swoole to be making processor determinations at configure time. Normally that should be avoided, because on macOS it is common to want to build a universal binary (one that works on multiple processors) or to cross-compile, so the processor you are configuring on is not necessarily the same as the processor(s) for which you are building.

Look at the file thirdparty/boost/asm/jump_combined_sysv_macho_gas.S. It contains these lines:
```
#if defined(__i386__)
    #include "jump_i386_sysv_macho_gas.S"
#elif defined(__x86_64__)
    #include "jump_x86_64_sysv_macho_gas.S"
#elif defined(__ppc__)
    #include "jump_ppc32_sysv_macho_gas.S"
#elif defined(__ppc64__)
    #include "jump_ppc64_sysv_macho_gas.S"
#else
    #error "No arch's"
#endif
```
This lets it choose the right assembly file at build time, regardless what the processor was at configure time. But note the lack of cases for arm or arm64. Probably cases for arm and arm64 should be added here, and then config.m4 should use jump_combined_sysv_macho_gas.S on macOS regardless of the configure-time processor. Same for make_combined_sysv_macho_gas.S.

This patch worked for me:
```diff
--- config.m4.orig	2020-11-26 21:02:32.000000000 -0600
+++ config.m4	2020-12-17 01:26:37.000000000 -0600
@@ -612,13 +612,7 @@
     )
 
     if test "$SW_OS" = "MAC"; then
-        if test "$SW_CPU" = "arm"; then
-            SW_CONTEXT_ASM_FILE="arm_aapcs_macho_gas.S"
-        elif test "$SW_CPU" = "arm64"; then
-            SW_CONTEXT_ASM_FILE="arm64_aapcs_macho_gas.S"
-        else
             SW_CONTEXT_ASM_FILE="combined_sysv_macho_gas.S"
-        fi
     elif test "$SW_CPU" = "x86_64"; then
         if test "$SW_OS" = "LINUX"; then
             SW_CONTEXT_ASM_FILE="x86_64_sysv_elf_gas.S"
--- thirdparty/boost/asm/jump_combined_sysv_macho_gas.S.orig	2020-11-26 21:02:33.000000000 -0600
+++ thirdparty/boost/asm/jump_combined_sysv_macho_gas.S	2020-12-17 01:25:22.000000000 -0600
@@ -15,6 +15,10 @@
     #include "jump_ppc32_sysv_macho_gas.S"
 #elif defined(__ppc64__)
     #include "jump_ppc64_sysv_macho_gas.S"
+#elif defined(__arm__)
+    #include "jump_arm_aapcs_macho_gas.S"
+#elif defined(__arm64__)
+    #include "jump_arm64_aapcs_macho_gas.S"
 #else
     #error "No arch's"
 #endif
--- thirdparty/boost/asm/make_combined_sysv_macho_gas.S.orig	2020-11-26 21:02:33.000000000 -0600
+++ thirdparty/boost/asm/make_combined_sysv_macho_gas.S	2020-12-17 01:25:22.000000000 -0600
@@ -15,6 +15,10 @@
     #include "make_ppc32_sysv_macho_gas.S"
 #elif defined(__ppc64__)
     #include "make_ppc64_sysv_macho_gas.S"
+#elif defined(__arm__)
+    #include "make_arm_aapcs_macho_gas.S"
+#elif defined(__arm64__)
+    #include "make_arm64_aapcs_macho_gas.S"
 #else
     #error "No arch's"
 #endif
```
Here is [a log of the successful build](https://build.macports.org/builders/ports-11_arm64-builder/builds/5698/steps/install-port/logs/stdio) with that patch.
