### ISSUE TITLE
swoole可否实现选择编译

### ISSUE THREAD

**Issue by sunjier** [swoole/swoole-src#392]
我用在嵌入式中,只需要tcp client, 其余都不需要,而编译swoole后so文件是790K, 即便经过strip之后也有739K, 这在嵌入式硬件宝贵的flash面前太奢侈了.

希望老韩听一下以下建议:
1. 支持 mips , 这个很好解决
2. 支持选择功能模块编译, 而非全部打包编译, 在以后swoole越做越大的情况下, 用户自定义编译也许是个趋势.

**Comment by matyhtf** [comment]
swoole主要的功能是Server，如果仅仅是Client，直接用PHP提供的即可。另外PHP和Swoole 并不适合运行在嵌入式系统，内存占用太大。
