### ISSUE TITLE
Compile Error on Mac Big Sur with PHP 8

### ISSUE THREAD

**Issue by iambudi** [swoole/swoole-src#3926]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Install swoole `pecl install swoole`

2. What did you expect to see?
swoole pecl extension

3. What did you see instead?
Compile termination error
```
In file included from /private/tmp/pear/temp/swoole/ext-src/php_swoole.cc:21:
/usr/local/Cellar/php/8.0.0_1/include/php/ext/pcre/php_pcre.h:23:10: fatal error: 'pcre2.h' file not found
#include "pcre2.h"
         ^~~~~~~~~
1 error generated.
make: *** [ext-src/php_swoole.lo] Error 1
ERROR: `make' failed
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
pecl install swoole
downloading swoole-4.5.9.tgz ...
Starting to download swoole-4.5.9.tgz (1,552,445 bytes)
..................................................................................................................................................................................................................................................................................................................done: 1,552,445 bytes
351 source files, building
running: phpize
Configuring for:
PHP Api Version:         20200930
Zend Module Api No:      20200930
Zend Extension Api No:   420200930
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

> Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_6

> PHP 8.0.0 (cli) (built: Nov 30 2020 13:51:52) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
>     with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies

**Comment by leocavalcante** [comment]
Try installing `pcre2` to the system before:
```bash
brew install pcre2
```
But I guess it can cause Swoole to be compiled with a different version of PCRE library than PHP's.

**Comment by iambudi** [comment]
Hi @leocavalcante,

I already had pcre2 installed before compiling.
```
Warning: pcre2 10.36 is already installed and up-to-date
To reinstall 10.36, run `brew reinstall pcre2`
```

**Comment by iambudi** [comment]
I can get it work by manually symlink the required file.
```bash
ln -s /usr/local/Cellar/pcre2/10.36/include/pcre2.h /usr/local/Cellar/php/8.0.0_1/include/php/ext/pcre/pcre2.h
```

**Comment by leocavalcante** [comment]
Nice! I had a similar problem with OpenSSL, for the OpenSSL question I had to say `yes --with-openssl-dir=/some/path/to/Cellar/openssl`

**Comment by iambudi** [comment]
Thanks for the info, i did not know we could pass `--with-openssl-dir`.

Previously i had to run this before compiling:
```bash
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

**Comment by huanghantao** [comment]
Maybe you just need to do it:

```bash
cp /usr/local/opt/openssl@1.1/lib/pkgconfig/* /usr/local/lib/pkgconfig/
```

**Comment by holtkamp** [comment]
https://github.com/swoole/swoole-src/issues/3926#issuecomment-744763791

For me the paths were different, this worked:

```
ln -s /opt/homebrew/Cellar/pcre2/10.36/include/pcre2.h /opt/homebrew/Cellar/php/8.0.2/include/php/ext/pcre/pcre2.h
```

**Comment by weiqiangxu** [comment]
thanks

ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/include/php/ext/pcre/pcre2lib/pcre2.h  /opt/homebrew/Cellar/php/8.0.3/include/php/ext/pcre/pcre2.h

and then 

```
Build process completed successfully
Installing '/opt/homebrew/Cellar/php/8.0.3/include/php/ext/swoole/config.h'
Installing '/opt/homebrew/Cellar/php/8.0.3/pecl/20200930/swoole.so'
install ok: channel://pecl.php.net/swoole-4.6.4
Extension swoole enabled in php.ini
```

**Comment by mcandylab** [comment]
`ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/include/php/ext/pcre/pcre2lib/pcre2.h /opt/homebrew/Cellar/php/8.0.3/include/php/ext/pcre/pcre2.h`

ITS SAVED ME, THANKS!!!!♥️

**Comment by jamielsharief** [comment]
I had similar problem with PHP 7.4 on Mac M1, but changing the  versions in the code above did not work. The`pcre2.h` file was in a different directory all together, once i found the correct location it compiled.

```
$ ln -s /opt/homebrew/include/pcre2.h /opt/homebrew/Cellar/php@7.4/7.4.16/include/php/ext/pcre/pcre2.h
```

**Comment by gonzunigad** [comment]
This worked for me with PHP 8.0.5 and pcre2 10.36: 
```bash 
ln -s /opt/homebrew/Cellar/pcre2/10.36/include/pcre2.h /opt/homebrew/Cellar/php/8.0.5/include/php/ext/pcre/
```

**Comment by amirjani** [comment]
in my case it solved with: 
php 8.0.6
pcre2 10.36

```sh 
ln -s /opt/homebrew/Cellar/pcre2/10.36/include/pcre2.h /opt/homebrew/Cellar/php/8.0.6_1/include/php/ext/pcre/
```

**Comment by rogebatera** [comment]
> Tive um problema semelhante com o PHP 7.4 no Mac M1, mas alterar as versões no código acima não funcionou. O `pcre2.h`arquivo estava em um diretório diferente, uma vez que encontrei o local correto, ele compilou.
> 
> ```
> $ ln -s /opt/homebrew/include/pcre2.h /opt/homebrew/Cellar/php@7.4/7.4.16/include/php/ext/pcre/pcre2.h
> ```

me ajudou, só achei o caminho e já era... macbook m1 com big sur

**Comment by Mekaeil** [comment]
> [#3926 (comment)](https://github.com/swoole/swoole-src/issues/3926#issuecomment-744763791)
> 
> For me the paths were different, this worked:
> 
> ```
> ln -s /opt/homebrew/Cellar/pcre2/10.36/include/pcre2.h /opt/homebrew/Cellar/php/8.0.2/include/php/ext/pcre/pcre2.h
> ```

Thank you it was helpful, I did it for php 8.0.8_1 and it worked.

1.
```
ln -s /opt/homebrew/Cellar/pcre2/10.37_1/include/pcre2.h /opt/homebrew/Cellar/php/8.0.8_1/include/php/ext/pcre/pcre2.h
```
2. restart apache 
3. sudo pecl install mongodb

**Comment by fabiotnt** [comment]
Thanks, guys. In my case it solved it a symlink:

`ln -s /opt/homebrew/include/pcre2.h /opt/homebrew/Cellar/php@7.4/7.4.24/include/php/ext/pcre/pcre2.h`

All that you need is check your php version and path. In case of pcre2 is not installed, install it with:

`brew install pcre2`

Environment and Case:
Macbook M1 with Big Sur trying to install imagick extension with PHP 7.4

**Comment by wangchengyue** [comment]
> [#3926 (comment)](https://github.com/swoole/swoole-src/issues/3926#issuecomment-744763791)
> 
> For me the paths were different, this worked:
> 
> ```
> ln -s /opt/homebrew/Cellar/pcre2/10.36/include/pcre2.h /opt/homebrew/Cellar/php/8.0.2/include/php/ext/pcre/pcre2.h
> ```

OK ,Thanks ,It work ..

**Comment by carlituxman** [comment]
After install pecr2 and imagick_

ln -s /opt/homebrew/Cellar/pcre2/**PECR2_VERSION**/include/pcre2.h /opt/homebrew/Cellar/php/**PHP_VERSION**/include/php/ext/pcre/pcre2.h

In my case: PECR2_VERSION=10.39 and PHP_VERSION=8.0.12

**Comment by wadimsewo** [comment]
> I had similar problem with PHP 7.4 on Mac M1, but changing the versions in the code above did not work. The`pcre2.h` file was in a different directory all together, once i found the correct location it compiled.
> 
> ```
> $ ln -s /opt/homebrew/include/pcre2.h /opt/homebrew/Cellar/php@7.4/7.4.16/include/php/ext/pcre/pcre2.h
> ```

I had another version path:
`sudo ln -s /opt/homebrew/include/pcre2.h /opt/homebrew/Cellar/php@7.4/7.4.25/include/php/ext/pcre/pcre2.h
`

**Comment by dyriaivn** [comment]
Just to simplify for others, where X - installed php version 
`sudo ln -s /opt/homebrew/include/pcre2.h /opt/homebrew/Cellar/php@X.X/X.X.X/include/php/ext/pcre/pcre2.h`

**Comment by AlexVanderbist** [comment]
If you just installed `php` using Brew without specifying a version, the path might be slightly different (again). This is the command I had to run:

```bash
 sudo ln -s /opt/homebrew/include/pcre2.h /opt/homebrew/Cellar/php/X.X.X/include/php/ext/pcre/pcre2.h 
```

(where `X.X.X` is the PHP version, in my case `8.1.4`)

**Comment by timbogdanov** [comment]
I am still getting this issue after attempting all solutions.
![image](https://user-images.githubusercontent.com/63133890/170322830-5387d827-da3e-4549-9665-c1d6bdb87210.png)

I've installed pcre2 with brew. (It was already installed, so I reinstalled it). Does anyone have any other suggestions?

**Comment by TychaK** [comment]
For my case I did this in my Mac M1:

`brew list pcre2 | grep 'pcre2\.h$'`

This will output the path to pcre2 as shown below:

`/opt/homebrew/Cellar/pcre2/10.40/include/pcre2.h`

Then 

`ln -s /opt/homebrew/Cellar/pcre2/10.40/include/pcre2.h /opt/homebrew/Cellar/php@7.4/7.4.30/include/php/ext/pcre/pcre2.h`

Be sure to replace the php path with your php version && path.

Hopefully this helps someone.

**Comment by aakashk994** [comment]
For pcre2 10.42 and php 8.2 on M1 Mac, this helped: 
 ln -s /opt/homebrew/Cellar/pcre2/10.42/include/pcre2.h /opt/homebrew/Cellar/php/8.2.1_1/include/php/ext/pcre/php_pcre.h

**Comment by ekpono** [comment]
This isn't still working, I am still getting this error after Symblinking

```
/opt/homebrew/Cellar/php@8.1/8.1.16/include/php/ext/pcre/php_pcre.h:23:10: fatal error: 'pcre2.h' file not found
#include "pcre2.h"
         ^~~~~~~~~
1 error generated.
make: *** [src/MongoDB/Cursor.lo] Error 1
ERROR: `make' failed
```


The path exist when I do this 
```
ln -s /opt/homebrew/Cellar/pcre2/10.40/include/pcre2.h /opt/homebrew/Cellar/php@8.1/8.1.16/include/php/ext/pcre/pcre2.h
ln: /opt/homebrew/Cellar/php@8.1/8.1.16/include/php/ext/pcre/pcre2.h: File exists
```

**Comment by aakashk994** [comment]
@ekpono try deleting the existing file and run this command again.

**Comment by prakashjoshidmacq** [comment]
export CPPFLAGS="-I/opt/homebrew/include"
export LDFLAGS="-L/opt/homebrew/lib"
