### ISSUE TITLE
bug websocket  for andorid 

### ISSUE THREAD

**Issue by xcwen** [swoole/swoole-src#393]
有没有好用的andorid websocket 客户端. 
我找的 autobahn-android , android-websocket 都不支持 
swoole websocket server .
在swoole websocket server 返回的消息后,客户端都会 提示  RSV not zero
然后就关闭.
看起来是协议问题.

swoole websocket server 对应的  andorid websocket 客户端  是什么:>
谢谢
=================================
11-10 12:02:19.059 3985-4288/com.leo1v1.admin E/xx: Error!
11-10 12:02:19.059 3985-4288/com.leo1v1.admin E/xx: com.codebutler.android_websockets.HybiParser$ProtocolError: RSV not zero
11-10 12:02:19.059 3985-4288/com.leo1v1.admin E/xx:     at com.codebutler.android_websockets.HybiParser.parseOpcode(HybiParser.java:140)
11-10 12:02:19.059 3985-4288/com.leo1v1.admin E/xx:     at com.codebutler.android_websockets.HybiParser.start(HybiParser.java:112)
11-10 12:02:19.059 3985-4288/com.leo1v1.admin E/xx:     at com.codebutler.android_websockets.WebSocketClient$1.run(WebSocketClient.java:134)
11-10 12:02:19.059 3985-4288/com.leo1v1.admin E/xx:     at java.lang.Thread.run(Thread.java:841)

**Comment by matyhtf** [comment]
swoole websocket server的RCV项一定为0，请使用最新的swoole版本测试。检查程序代码是否正确。
确实使用了 `swoole_websocket_server`

**Comment by matyhtf** [comment]
websocket必须要用push方法向客户端发送数据。

**Comment by xcwen** [comment]
谢谢, 好了
