### ISSUE TITLE
best framework on swoole

### ISSUE THREAD

**Issue by NVD-R** [swoole/swoole-src#3932]
hi, can you tell me about best framework on swoole with huge community and good docs?

**Comment by sy-records** [comment]
you can see https://github.com/swoole/swoole-src#-frameworks--components

**Comment by matyhtf** [comment]
Frameworks & Components
---------------
- Hyperf is a coroutine framework that focuses on hyperspeed and flexibility, specifically used for build microservices or middlewares.
- Swoft is a modern, high-performance AOP and coroutine PHP framework.
- Easyswoole is a simple, high-performance PHP framework, based on Swoole, which makes using Swoole as easy as echo "hello world".
- MixPHP is a powerful single-threaded coroutine framework with a very small footprint, simple and elegant.
- imi is a high-performance coroutine application development framework based on PHP Swoole, which supports the development of HttpApi, WebSocket, TCP, UDP services.
- Saber is a human-friendly, high-performance HTTP client component that has almost everything you can imagine.
- One is a minimalist, high-performance PHP framework that supports the [swoole | php-fpm] environment

**Comment by NVD-R** [comment]
thanks a lot, but wanna know your idea about the best framework?

**Comment by huanghantao** [comment]
There is no best framework, you can try these frameworks, we think they are very good!
