### ISSUE TITLE
channel无法释放内存。

### ISSUE THREAD

**Issue by NathanFreeman** [swoole/swoole-src#3946]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
你好，我这个是一个同步数据的代码，用channel做协程通信，一共有一个生产者和N个消费者。在执行的时候出现了内存不释放的问题。往往同步的过程中消耗了3G左右的内存。于是我简化代码，发现是channel的问题，明明channel已经是空了，但是内存还是不释放。下面是我简化之后的代码。

![图片](https://user-images.githubusercontent.com/33935209/102683843-c8286d00-420e-11eb-9145-7f165ea06c35.png)

我这边已经将能释放的内存全部unset了，但是还是内存不释放，我一共要同步120W条数据。

我看了看swoole关于channel这部分的源码，在push的时候会用Z_TRY_ADDREF_P将引用计数加1，
![图片](https://user-images.githubusercontent.com/33935209/102684673-c7dfa000-4215-11eb-89df-1a1a62cb05df.png)
但是pop的时候是直接efree对应的值，这里还要不要用Z_TRY_DELREF_P将引用计数减一？
![图片](https://user-images.githubusercontent.com/33935209/102684708-09704b00-4216-11eb-8901-1ddeb9e4a8b2.png)

拜托，这个问题困扰我很久了。

2. What did you expect to see?
任务完成后，应该释放内存。

3. What did you see instead?
![图片](https://user-images.githubusercontent.com/33935209/102683695-c14d2a80-420d-11eb-806b-fff4489d64f0.png)
![图片](https://user-images.githubusercontent.com/33935209/102683631-5bf93980-420d-11eb-8576-edb0d10a0ba1.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole4.5.2

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
centos7.8，php73，gcc4.8.5，hyperf。

**Comment by sy-records** [comment]
https://github.com/swoole/swoole-src/issues/3925 两个问题重复了... 先升级到新版本，提供最简复现代码

**Comment by NathanFreeman** [comment]
@sy-records 好的，我先把上一个问题关闭，然后升级一下swoole试试看。谢谢。

**Comment by NathanFreeman** [comment]
@sy-records 已经把swoole版本升级到了4.5.9，但是同步结束后内存还是没有释放。
简化的代码如下，需要unset的变量也已经unset
![图片](https://user-images.githubusercontent.com/33935209/102688181-de92f080-422f-11eb-9073-dde76fddcbb4.png)

**Comment by sy-records** [comment]
用原生swoole代码复现，不要依赖框架。代码发出来，不要截图。

**Comment by NathanFreeman** [comment]
@sy-records 原生代码内存可以回收，用hyperf就不行。唉

**Comment by sy-records** [comment]
那你还是在hyperf这里让 @limingxinleo 看看吧 https://github.com/hyperf/hyperf/issues/2964

**Comment by limingxinleo** [comment]
请先排除db组件的影响，直接使用array代替

**Comment by limingxinleo** [comment]
我查了下，可能是数据库查询的问题。

另外，第二次执行的时候，并没有继续增长内存，所以只要使用得当，问题不是很大。

建议你把代码修改一下，直接使用Db::select 配合循环来做

**Comment by NathanFreeman** [comment]
@limingxinleo 好的谢谢
