### ISSUE TITLE
Hyperf通过kill -15杀掉进程后,出现死锁的问题

### ISSUE THREAD

**Issue by codingheping** [swoole/swoole-src#3949]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

![image](https://user-images.githubusercontent.com/20986749/102741314-021f7d80-438d-11eb-86a0-67083955579e.png)

2. What did you expect to see?

![image](https://user-images.githubusercontent.com/20986749/102741435-46ab1900-438d-11eb-99a2-ef1e83e9dcb0.png)
看这文档写的是当workerstart和workerexit事件执行完成后分别恢复协程。

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.6.0-alpha

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

php 7.4.7
mac 11.0.1

**Comment by matyhtf** [comment]
请忽略死锁检测，这是致命错误之后有泄漏的协程，符合预期的行为，4.6.0-beta  已经修改了 死锁检测，在 fatal error 时不再进行死锁推断。

**Comment by codingheping** [comment]
好的,我现在还是alpha版本
