### ISSUE TITLE
Undefined symbol: socket_ce

### ISSUE THREAD

**Issue by FelixMittermeier** [swoole/swoole-src#3952]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I am trying to install swoole for more than five hours without success. I started with _pecl install swoole_, added _extension=swoole.so_ to the correct php.ini, restarted the server multiple times. I also made sure pecl, pearl and phpize are set to the correct version (8.0), searched very long but did not find any solution for my problem. 

2. What did you expect to see?

A working installation. 
I used the script from https://github.com/hhxsv5/php-sse/blob/master/examples/sse-swoole.php but this actually doesn't matter because the error (see below) happens already in the command line while executing any php command.

3. What did you see instead?

PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/lib/php/20200930/swoole.so (/usr/lib/php/20200930/swoole.so: undefined symbol: socket_ce)

4. What version of Swoole are you using (show your `php --ri swoole`)?

I cannot run the command due to the error happening already before but the latest version has been used while installing (4.5.9).

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**uname -a:** `Linux 4.4.0-1127.8.2.vz7.151.14 #1 SMP Tue Jun 9 12:58:54 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux`

**php -v:** `PHP 8.0.0 (cli) (built: Nov 27 2020 12:25:47) ( NTS )`

**gcc -v:** `Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) `

Any help would be much appreciated, thank you.

**Comment by sy-records** [comment]
Can you try to compile it manually? 

Duplicate with #3904

**Comment by FelixMittermeier** [comment]
Okay, so
`
EXT_SWOOLE_VERSION=v4.5.9
git clone https://github.com/swoole/swoole-src.git \
  && cd swoole-src \
  && git checkout $EXT_SWOOLE_VERSION \
  && phpize \
  && ./configure \
  --enable-openssl \
  --enable-sockets \
  --enable-http2 \
  && make && make install
`
did work for the installation. It now also shows the module when running:
`
# /opt/plesk/php/8.0/bin/php -m | grep swoole
swoole
`
or 
`
# php -m | grep swoole
swoole
`
but unfortunately I am still not able to use the extension in my php scripts. I took https://github.com/hhxsv5/php-sse/blob/master/examples/sse-swoole.php for testing purposes but am still getting an error
`Class "Swoole\Http\Server" not found`.

May it have something to do with Plesk or Nginx? Php8.0-fpm service and the entire server were restarted several times. I am stuck at this issue for 12h+ and don't know what I can still do.

**Comment by sy-records** [comment]
Can only be run in cli mode.

**Comment by billionaire** [comment]
Hi.
I have same issue with swoole on php 8.0.0 (CentOS 8.3.2011).
PHP is installed from repository: https://rpms.remirepo.net/wizard/ (_CentOS 8 => 8.0.0 => Default/Single_).

Extension build log: https://gist.github.com/68618e92f96d932e09ea439a5ad9979d

On build 4.6.0-beta error: /usr/src/swoole-src-4.6.0-beta/modules/swoole.so: undefined symbol: **curl_ce**
On build 4.5.10 error: /usr/src/swoole-src-4.5.10/modules/swoole.so: undefined symbol: **socket_ce**



```
# php --ri swoole
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole' (tried: /usr/lib64/php/modules/swoole (/usr/lib64/php/modules/swoole: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/swoole.so (/usr/lib64/php/modules/swoole.so: undefined symbol: _Z25zend_get_gc_buffer_createv)) in Unknown on line 0
Extension 'swoole' not present.

# uname -a
Linux example.net 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# php -v
PHP 8.0.0 (cli) (built: Nov 24 2020 17:04:03) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies

# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)
```

Can you please tell me what can be wrong and how to fix it?
The openssl-devel and libcurl-devel packages are installed.
Thank you for attention.
Regards.

**Comment by RicardoGuiliani** [comment]
SOLVED! @FelixMittermeier @billionaire 

Hi, I had same issue, so please read carefully.

If php modules are loaded from mods-available folder, don't add `extension=swoole.so` manually to `php.ini`, instead of that you have to add a `swoole.ini` file to php mods-available folder.

`;configuration for php common module`
`;priority=20`
`extension=swoole.so`

and enable it with `sudo phpenmod swoole`

What happens is if you add `extension=swoole.so` manually to `php.ini`, it connects before all the required extensions.
For instance, if you added `--enable-sockets` and so to swoole installation and the swoole extension loads before sockets extension, it will fail, so after I removed `extension=swoole.so` from php.ini, added `swoole.ini` file to php mods-available folder and enabled it with `sudo phpenmod swoole` swoole is working properly.

Hope this may help!

**Comment by letwang** [comment]
```
tee /etc/php/8.0/mods-available/swoole.ini <<EOF
; configuration for php swoole module
; priority=20
extension=swoole.so
EOF

sudo phpenmod swoole

php --ri swoole


```

**Comment by tnsoftbear** [comment]
Hi, I've faced with the same error when installed "event" extension and I want to share solution.
As said there you must set up your extension configuration in separate files, like sockets.ini, swoole.ini, but the main reason is not mentioned there.
The reason why "Undefined symbol: socket_ce" error occurs is the fact, that "sockets" extension is dependency of swoole, and this dependency is not loaded yet when "swoole" extension is loading. To fix that, you have to make sockets be loaded earlier than "swoole" extension ("event" extension in my case). This can be configured by "priority" parameter. 
For instance, set "priority=20" in sockets.ini and set "priority=30" in swoole.ini. And enable priority consideration by removing ";" that comments it out.
So command above should look like this:

$ tee /etc/php/8.0/mods-available/swoole.ini <<EOF
priority=30
extension=swoole.so
EOF

and this:

$ tee /etc/php/8.0/mods-available/sockets.ini <<EOF
priority=20
extension=sockets.so
EOF

Hope this will help anyone who will find this thread in google.

**Comment by MESOLONELY** [comment]
[tnsoftbear](https://github.com/tnsoftbear)'s comment helps a lot
