### ISSUE TITLE
Swoole with JWT and lumen

### ISSUE THREAD

**Issue by brijesh1997** [swoole/swoole-src#3953]
Hello,

I am using swoole with `lumen + jwt` so When I run project via swoole so Jwt isn't working in it I mean my all API's  are access without JWT token but when I run my project without swoole and when I'm trying to access API's so without JWT token I can't access it.

Version Details :- 
```
"laravel/lumen-framework": "^8.0",
"swooletw/laravel-swoole": "^2.6",
"tymon/jwt-auth": "dev-develop"
```

Thank you.

**Comment by sy-records** [comment]
I think you should submit an issue to tymon/jwt-auth

**Comment by brijesh1997** [comment]
> I think you should submit an issue to tymon/jwt-auth

Okay, Thank you for your reply.
