### ISSUE TITLE
 before shutdown event improvement suggestion

### ISSUE THREAD

**Issue by zqe** [swoole/swoole-src#3963]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

We are building a microservice using the `swoole`.  We need to use the service registration discovery service in the process of starting and stopping the microservice. When the code is updated or the service is abnormal, we need to rely on the shutdown to log the service out of the service registration discovery service. We used the `onShutdown` event in the previous project. After consulting the documents and reading the source code, we found that the When `onBeforeShutdo` , processes such as worker task have exited. We need an `onBeforeShutdown` event to prepare for the exit of the program.

thank!

**Comment by sy-records** [comment]
You can try onWorkerStop and onWorkerExit

**Comment by zqe** [comment]
Thanks for your suggestions, but it doesn't seem to solve my problem.
The `onWorkerStop`, `onWokerExit` events will be triggered when the `worker` process exits for whatever reason. It is impossible to know whether the `Worker` process will be restarted by the `Manager` process.
I only want to trigger a piece of logic before exiting the `Master` process to do some finishing work, for example: when the `SIGTERM` signal is received.

**Comment by matyhtf** [comment]
You can set a special request handler to terminate the server program

```php
$http = new Swoole\Http\Server("127.0.0.1", 9501);

$http->on("start", function ($server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$http->on("request", function ($request, $response) use ($http) {
    if ($request->server['request_uri'] == '/shutdown') {
        // offline code ...
        $http->shutdown();
        $response->end("OK");
    }
    $response->header("Content-Type", "text/plain");
    $response->end("Hello World\n");
});

$http->start();
```
