### ISSUE TITLE
swoole4.5.9 在centos7 下面configure 不过去

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [swoole/swoole-src#3965]
centos下linux版本
Linux version 3.10.0-693.2.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Sep 12 22:26:13 UTC 2017

安装包下载地址
http://pecl.php.net/get/swoole-4.5.9.tgz

1.执行解析命令
./configure --with-php-config=/usr/local/webserver/php/bin/php-config

2.出现问题
checking whether to enable swoole coverage support... no
checking whether to enable Swoole developer build flags... no
checking whether to enable Swoole JSON build flags... no
checking if compiling with clang... no
./configure: line 5534: syntax error near unexpected token `-Wbool-conversion,'
./configure: line 5534: `        AX_CHECK_COMPILE_FLAG(-Wbool-conversion,                _MAINTAINER_CFLAGS="$_MAINTAINER_CFLAGS -Wbool-conversion")'

**Comment by matyhtf** [comment]
去掉 `--enable-swoole-dev` 或者更新 `gcc` 版本

**Comment by matyhtf** [comment]
CentOS7 默认安装的是 php5 ，swoole 需要 7.2 或更高版本

**Comment by LeiZhang-Hunter** [comment]
好的，这个问题好像好多年了，当时按照你最开始那个方法好像编译过了，记不清了

**Comment by Ying1131271533** [comment]
2023年的我，遇到了你这个问题，哭死~不知道怎么解决

**Comment by LoveInSky** [comment]
用php7.2以上的phpize重新生成configure
