### ISSUE TITLE
WARNING	check_worker_exit_status: worker#27[pid=2546428] abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by woainixyz1** [swoole/swoole-src#3967]
[2020-12-31 11:29:00 $2545105.0]	WARNING	check_worker_exit_status: worker#27[pid=2546428] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.5.9, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

用yasd调试启动2.0的时候会有以上报错

**Comment by huanghantao** [comment]
> [2020-12-31 11:29:00 $2545105.0] WARNING check_worker_exit_status: worker#27[pid=2546428] abnormal exit, status=0, signal=11
> A bug occurred in Swoole-v4.5.9, please report it.
> The Swoole developers probably don't know about it,
> and unless you report it, chances are it won't be fixed.
> You can read How to report a bug doc before submitting any bug reports:
> 
> > > https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
> > > Please do not send bug reports in the mailing list or personal letters.
> > > The issue page is also suitable to submit feature requests.
> 
> 用yasd调试启动2.0的时候会有以上报错

应该是`yasd`的问题，可以提给`yasd`。
