### ISSUE TITLE
macOS Big Sur中安装swoole出现编译报错

### ISSUE THREAD

**Issue by kongeric** [swoole/swoole-src#3968]
**在执行“make”编译的时候出现如下错误：**

错误信息图片地址：[https://testyao.oss-cn-beijing.aliyuncs.com/0b5e3c65fb2649dc311197decd2634e.png](https://testyao.oss-cn-beijing.aliyuncs.com/0b5e3c65fb2649dc311197decd2634e.png)

PHP版本：7.2.6
系统：macOS Big Sur
处理器：M1

```shell
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:45:5: error: unexpected token at start of statement
    @ shift address in A1 to lower 16 byte boundary
    ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:46:9: error: invalid operand for instruction
    bic a1, a1, #15
        ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:48:5: error: unexpected token at start of statement
    @ reserve space for context-data on context-stack
    ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:49:9: error: invalid operand for instruction
    sub a1, a1, #108
        ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:51:5: error: unexpected token at start of statement
    @ third arg of make_fcontext() == address of context-function
    ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:52:9: error: invalid operand for instruction
    str a3, [a1,#104]
        ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:54:5: error: unexpected token at start of statement
    @ compute abs address of label finish
    ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:55:9: error: invalid operand for instruction
    adr a2, finish
        ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:56:5: error: unexpected token at start of statement
    @ save address of finish as return-address for context-function
    ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:57:5: error: unexpected token at start of statement
    @ will be entered after context-function returns
    ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:58:9: error: invalid operand for instruction
    str a2, [a1,#100]
        ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:60:11: error: unexpected token in argument list
    bx lr @ return pointer to context-data
          ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:63:5: error: unexpected token at start of statement
    @ exit code is zero
    ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:64:9: error: invalid operand for instruction
    mov a1, #0
        ^
/Users/ext/swoole-src/thirdparty/boost/asm/make_arm_aapcs_macho_gas.S:65:5: error: unexpected token at start of statement
    @ exit application
    ^
make: *** [thirdparty/boost/asm/make_arm_aapcs_macho_gas.lo] Error 1
```

**Comment by matyhtf** [comment]
@kongeric 请加我微信单独沟通，19921030512

**Comment by huanBird** [comment]
请问。解决了吗？

**Comment by kajweb** [comment]
请问你解决了php.d的问题吗？

**Comment by kongeric** [comment]
还没有,虽然编译成功,但是重启时,swoole扩展报错:


[12-Jan-2021 01:40:31 UTC] PHP Warning:&nbsp; PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /Applications/MAMP/bin/php/php7.2.22/lib/php/extensions/no-debug-non-zts-20170718/swoole.so (dlopen(/Applications/MAMP/bin/php/php7.2.22/lib/php/extensions/no-debug-non-zts-20170718/swoole.so, 9): Library not loaded: /usr/local/opt/brotli/lib/libbrotlienc.1.dylib
&nbsp; Referenced from: /Applications/MAMP/bin/php/php7.2.22/lib/php/extensions/no-debug-non-zts-20170718/swoole.so
&nbsp; Reason: image not found), /Applications/MAMP/bin/php/php7.2.22/lib/php/extensions/no-debug-non-zts-20170718/swoole.so.so (dlopen(/Applications/MAMP/bin/php/php7.2.22/lib/php/extensions/no-debug-non-zts-20170718/swoole.so.so, 9): image not found)) in Unknown on line 0







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "swoole/swoole-src"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 下午2:30
收件人:&nbsp;"swoole/swoole-src"<swoole-src@noreply.github.com&gt;;
抄送:&nbsp;" "<476385286@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [swoole/swoole-src] macOS Big Sur中安装swoole出现编译报错 (#3968)





 
请问你解决了php.d的问题吗？

**Comment by neptunezx** [comment]
参考别的大神的回答 https://github.com/swoole/swoole-src/issues/3917
最新的M1芯片应该是编译的时候需要指定正确的CPU汇编文件，使用下面的patch就可以正确编译
```--- config.m4.orig	2020-11-26 21:02:32.000000000 -0600
+++ config.m4	2020-12-17 01:26:37.000000000 -0600
@@ -622,13 +622,7 @@
     )
 
     if test "$SW_OS" = "MAC"; then
-        if test "$SW_CPU" = "arm"; then
-            SW_CONTEXT_ASM_FILE="arm_aapcs_macho_gas.S"
-        elif test "$SW_CPU" = "arm64"; then
-            SW_CONTEXT_ASM_FILE="arm64_aapcs_macho_gas.S"
-        else
             SW_CONTEXT_ASM_FILE="combined_sysv_macho_gas.S"
-        fi
     elif test "$SW_CPU" = "x86_64"; then
         if test "$SW_OS" = "LINUX"; then
             SW_CONTEXT_ASM_FILE="x86_64_sysv_elf_gas.S"
--- thirdparty/boost/asm/jump_combined_sysv_macho_gas.S.orig	2020-11-26 21:02:33.000000000 -0600
+++ thirdparty/boost/asm/jump_combined_sysv_macho_gas.S	2020-12-17 01:25:22.000000000 -0600
@@ -15,6 +15,10 @@
     #include "jump_ppc32_sysv_macho_gas.S"
 #elif defined(__ppc64__)
     #include "jump_ppc64_sysv_macho_gas.S"
+#elif defined(__arm__)
+    #include "jump_arm_aapcs_macho_gas.S"
+#elif defined(__arm64__)
+    #include "jump_arm64_aapcs_macho_gas.S"
 #else
     #error "No arch's"
 #endif
--- thirdparty/boost/asm/make_combined_sysv_macho_gas.S.orig	2020-11-26 21:02:33.000000000 -0600
+++ thirdparty/boost/asm/make_combined_sysv_macho_gas.S	2020-12-17 01:25:22.000000000 -0600
@@ -15,6 +15,10 @@
     #include "make_ppc32_sysv_macho_gas.S"
 #elif defined(__ppc64__)
     #include "make_ppc64_sysv_macho_gas.S"
+#elif defined(__arm__)
+    #include "make_arm_aapcs_macho_gas.S"
+#elif defined(__arm64__)
+    #include "make_arm64_aapcs_macho_gas.S"
 #else
     #error "No arch's"
 #endif
```

**Comment by olk** [comment]
Could you provide a pull request for boost.context please!

**Comment by neptunezx** [comment]
> In order to get the fix upstream - could you provide a pull request for boost.context please!

sorry, although it can be compiled normally, it cannot be started.
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/swoole.so' (tried: /usr/local/lib/php/extensions/swoole.so (dlopen(/usr/local/lib/php/extensions/swoole.so, 0x0009): could not use '/usr/local/lib/php/extensions/swoole.so' because it is not a compatible arch), /usr/lib/php/extensions/no-debug-non-zts-20180731//usr/local/lib/php/extensions/swoole.so.so (dlopen(/usr/lib/php/extensions/no-debug-non-zts-20180731//usr/local/lib/php/extensions/swoole.so.so, 0x0009): dlopen(): file not found: /usr/lib/php/extensions/no-debug-non-zts-20180731//usr/local/lib/php/extensions/swoole.so.so)) in Unknown on line 0`

**Comment by kajweb** [comment]
> > In order to get the fix upstream - could you provide a pull request for boost.context please!
> 
> sorry, although it can be compiled normally, it cannot be started.
> `PHP Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/swoole.so' (tried: /usr/local/lib/php/extensions/swoole.so (dlopen(/usr/local/lib/php/extensions/swoole.so, 0x0009): could not use '/usr/local/lib/php/extensions/swoole.so' because it is not a compatible arch), /usr/lib/php/extensions/no-debug-non-zts-20180731//usr/local/lib/php/extensions/swoole.so.so (dlopen(/usr/lib/php/extensions/no-debug-non-zts-20180731//usr/local/lib/php/extensions/swoole.so.so, 0x0009): dlopen(): file not found: /usr/lib/php/extensions/no-debug-non-zts-20180731//usr/local/lib/php/extensions/swoole.so.so)) in Unknown on line 0`

这个应该是osx系统没有相应的header，请问您解决了吗？
