### ISSUE TITLE
swoole进程CPU占用飙升，导致不可用

### ISSUE THREAD

**Issue by Frank-JY** [swoole/swoole-src#3971]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
![image](https://user-images.githubusercontent.com/20394301/103439980-ed8c9080-4c7c-11eb-9fc2-56aa1aa55ff6.png)

CPU突然飙升100，发现swoole进程大量占用CPU
通过strace -cp pid发现在不停调用sched_yield
![image](https://user-images.githubusercontent.com/20394301/103440016-275d9700-4c7d-11eb-9148-576488880fce.png)

![image](https://user-images.githubusercontent.com/20394301/103441631-41ea3d00-4c8a-11eb-9b5c-017113a114de.png)
swooletable->get发生死锁？

2. What did you expect to see?
cpu突然飙升，摘流后也不会自动释放，若不重启，导致服务一直不可用。希望查明原因

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

![image](https://user-images.githubusercontent.com/20394301/103440052-76a3c780-4c7d-11eb-9b75-6fa9184ddad7.png)

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

![image](https://user-images.githubusercontent.com/20394301/103440068-976c1d00-4c7d-11eb-998c-18874e89f786.png)

**Comment by Frank-JY** [comment]
![image](https://user-images.githubusercontent.com/20394301/103441631-41ea3d00-4c8a-11eb-9b5c-017113a114de.png)
swooletable->get发生死锁？

**Comment by sy-records** [comment]
提供最简复现代码

**Comment by Frank-JY** [comment]
![image](https://user-images.githubusercontent.com/20394301/103455548-03578f80-4d29-11eb-88d3-3f750383157f.png)
又复现了，初步判断是由于并发影响。暂时没有最简复现代码

**Comment by Frank-JY** [comment]
![image](https://user-images.githubusercontent.com/20394301/103455563-2d10b680-4d29-11eb-8e6f-e1941a7f90d8.png)
这个是昨晚的

**Comment by matyhtf** [comment]
@Frank-JY 请使用 4.6.1 版本进行测试，看是否存在问题？
