### ISSUE TITLE
业务可以获取每个请求开启的协程到完成响应所耗时

### ISSUE THREAD

**Issue by luolaifa000** [swoole/swoole-src#3982]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

我想在业务上可以获取到onrequest请求每个协程所花费的耗时

2. What did you expect to see?
cid 1 200ms 
cid 2 20ms

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by luolaifa000** [comment]
还有，开启一键协程化后，是否可以检查出每个请求 哪些IO没有调度切换的。

**Comment by sy-records** [comment]
https://wiki.swoole.com/#/coroutine/coroutine?id=getelapsed

**Comment by luolaifa000** [comment]
> https://wiki.swoole.com/#/coroutine/coroutine?id=getelapsed

是的，可以根据ID获取时间，但是我想的可能更多一点，能获取历史或者列表形势的，getelapsed好像只能获取当前存活的协程的时间

**Comment by sy-records** [comment]
onrequest每次请求都是一个协程，你需要历史和列表，自己调用获取自己存储不就可以吗？

**Comment by luolaifa000** [comment]
> onrequest每次请求都是一个协程，你需要历史和列表，自己调用获取自己存储不就可以吗？

好办法。 @
