### ISSUE TITLE
install the swoole 1.7.20-stable on php7.0 RC-7 is failed

### ISSUE THREAD

**Issue by ganxiangdong** [swoole/swoole-src#399]
/usr/local/php7.0/bin/php -m

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php7.0/lib/php/extensions/no-debug-non-zts-20151012/swoole.so' - /usr/local/php7.0/lib/php/extensions/no-debug-non-zts-20151012/swoole.so: undefined symbol: zval_used_for_init in Unknown on line 0

**Comment by matyhtf** [comment]
Command `phpize/php-config` must use absolute path.

Sample
```php
/usr/local/php-7/bin/phpize
./configure --with-php-config=/usr/local/php-7/bin/php-config
```
