### ISSUE TITLE
Swoole Install Fail, Module exist but don't work class

### ISSUE THREAD

**Issue by her0mx** [swoole/swoole-src#3991]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
I am install swoole in diferents versions of Linux

2. What did you expect to see?

I want the module can run

3. What did you see instead?

[Fri Jan 08 16:37:35.288370 2021] [php7:error] [pid 2607] [client 23.227.192.85:55095] PHP Fatal error:  Uncaught Error: Class 'Swoole\\HTTP\\Server' not found in /var/www/html/1.php:2\nStack trace:\n#0 {main}\n  thrown in /var/www/html/1.php on line 2
[Fri Jan 08 16:59:57.746192 2021] [php7:error] [pid 2571] [client 23.227.192.85:55354] PHP Fatal error:  Uncaught Error: Class 'Swoole\\HTTP\\Server' not found in /var/www/html/1.php:2\nStack trace:\n#0 {main}\n  thrown in /var/www/html/1.php on line 2

4. What version of Swoole are you using (show your `php --ri swoole`)?

root@swoole:/var/www/html# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.0
Built => Jan  8 2021 16:29:30
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
dtls => enabled
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
root@swoole:/var/www/html# 

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

root@swoole:/var/www/html# uname -a
Linux swoole 4.19.0-10-cloud-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
root@swoole:/var/www/html# php -v
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
root@swoole:/var/www/html# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6) 
root@swoole:/var/www/html#

**Comment by luffluo** [comment]
Sorry, could you show the code in this file (/var/www/html/1.php)?

**Comment by sy-records** [comment]
You may be using it in fpm mode, but Swoole needs to be run in CLI mode.

```bash
php 1.php
```

**Comment by matyhtf** [comment]
Not the same version of php, or the php.ini settings of the application are different
