### ISSUE TITLE
Wrong minimum PHP version (7.1) with swoole 4.6.0

### ISSUE THREAD

**Issue by mlocati** [swoole/swoole-src#3995]
In the package.xml file we have that the minimum PHP version for swoole 4.6.0 is 7.1 (see https://github.com/swoole/swoole-src/blob/v4.6.0/package.xml#L2029)
But installing swoole 4.6.0 with PHP 7.1 fails with the error "require PHP version 7.2 or later" (see https://github.com/swoole/swoole-src/blob/v4.6.0/ext-src/php_swoole.h#L99-L101)

**Comment by sy-records** [comment]
Sorry, pecl forgot to make the change, fixed via #3979

php7.1 is not supported from 4.6 onwards.

**Comment by mlocati** [comment]
I saw the changelog.
The problem is that automated scripts can't parse human readable documents (like the changelog), that's why we have formalized files like `package.xml`, so that detecting the package requirements can be done programmatically.

Thanks for fixing this issue!

**Comment by mlocati** [comment]
Here you can find sample usage of the min PHP version read from the package.xml file: https://mlocati.github.io/pecl-info/#swoole

Such tools van be created only if the PECL packages follow the rules 😉
