### ISSUE TITLE
m1 编译失败，make_arm_aapcs_macho_gas.S 无法编译

### ISSUE THREAD

**Issue by ZicLemon** [swoole/swoole-src#4003]
![image](https://user-images.githubusercontent.com/24861065/104807930-88f53800-581d-11eb-8259-f3838a8a22dd.png)
打了补丁也无效

**Comment by sy-records** [comment]
加编译选项了吗 --enable-thread-context

**Comment by ZicLemon** [comment]
@sy-records 
忘記加了，難怪  可以了
