### ISSUE TITLE
PHP-Swoole error accept() failed, Error: Too many open files[24]

### ISSUE THREAD

**Issue by MrApr** [swoole/swoole-src#4004]
I have installed php/swoole on my server and configured it using [Laravel swoole](https://github.com/swooletw/laravel-swoole)

Now The problem is everything works fine until total requests per second number increase more than 1000 requests.
Swoole will log an error and not responding to user !
I have set Operating system ulimit number to 50000
But still get same error ! Searching all over internet and find nothing !
Os Centos 7
Server is good enough to handle more than 1k requests per second

If you have any experience about this please share it with me

Note:
When swoole starts, it logs this error too:
set_max_connection: max_connection is exceed the maximum value, it's reset to 1024

**Comment by sy-records** [comment]
Maybe the `ulimit -n` you set only works in the current terminal, not globally.

The default value for `max_connection` is `ulimit -n`

**Comment by MrApr** [comment]
Ok I have figured it out.
lets first say that how I ran PHP-Swoole process: .
I have made a systemd service in centos in order to launch swoole process all the time in any situation..
So the ULimit command sets ulimit for current shell that you are in it. Not the systemd shell that is running swoole starter process..
For that you need to add `LimitNOFILE=100000` option under systemd `[Service]` section block.
And with a restart everything works fine.
Thanks team swoole ! It's super fast
