### ISSUE TITLE
Http2 协议 client 存在不符合预期的超时触发

### ISSUE THREAD

**Issue by starfalling** [swoole/swoole-src#4018]
大致流程如下：

1. 给 http2 连接设置一个超时时间，比如 3s，发送一个成功的请求并受到正确的响应
2. 正好在3s超时接近时，发出一个新的请求 (stream)，请求发出成功并获取到发出的 stream id
3. socket 底层触发超时
3. 新的请求执行 recv 函数时，出现失败，底层 socket 连接已经被前面的超时触发断开

这种情况发生时，服务端能收到请求并正确处理，但是客户端无法收到响应

**Comment by starfalling** [comment]
[http://cn.e.pic.mangatoon.mobi/swoole-test/swoole-http2-client-test2.zip](url)

下载样例代码
```shell
├── swoole-http2-client-test
│   ├── http2-test-client.php
│   └── http2-test-server.php
```

在 client 中共发出 3 个请求，最后一个请求会发送成功，客户端无法收到响应

如果正好卡在超时的时间点发出请求，服务端可以收到请求，但是客户端无法响应
如果超过超时的时间点多一些发出请求，服务端不会收到请求

**Comment by matyhtf** [comment]
HTTP2 client 是在 recv 的时候设置超时的，send 是不会有任何操作。

**Comment by starfalling** [comment]
重试不能从根本上解决问题，因为服务端可能已经收到并执行了请求，重复发送会存在副作用。项目中实际跑下来，这种情况出现的概率不算低，期望 swoole 框架能够在底层处理这种情况

**Comment by starfalling** [comment]
从原理上说，send 函数执行成功了，那么 recv 在这个时候超时可以做一次重置

**Comment by matyhtf** [comment]
@starfalling 你的程序可以改成在 send 完毕之后再 recv，如果必须要分开读写两个协程，那么可以建立一个 chan，写的协程 send 之后向 chan 写入信号，读的协程执行 chan->pop 收到信号后再执行 recv()
