### ISSUE TITLE
WARNING	check_worker_exit_status: worker#22[pid=13051] abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by MrApr** [swoole/swoole-src#4022]
[2021-01-23 23:52:52 $13024.0]	WARNING	check_worker_exit_status: worker#22[pid=13051] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.6.0, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

**Comment by sy-records** [comment]
Please follow the issue template.
