### ISSUE TITLE
[2021-01-24 17:54:27 $53398.0]	WARNING	check_worker_exit_status: worker#12[pid=53411] abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by david0315** [swoole/swoole-src#4023]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
![image](https://user-images.githubusercontent.com/3435608/105626900-1e23ac80-5e6e-11eb-8c43-9dc2d2b0b2f7.png)

并发脚本：

wrk -t2 -c20 -d10s --script=./follow_light_wrk_post.lua --latency http://192.168.50.19:9507/api/v1/follow/light/vote

follow_light_wrk_post.lua: 
```
wrk.method = "POST"
wrk.headers["Content-Type"] = "application/x-www-form-urlencoded"
wrk.headers["access-token"] = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjU5LCJpYXQiOjE2MTE0MTk3MjMsImV4cCI6MjQ3NTQxOTcyMywibmJmIjoxNjExNDE5NzIzLCJqdGkiOiI5YmJkZmExNC1jZTkzLTRhYzYtYTdhMC02YzRjZDFmMTA0NmUifQ.wbfhGVQfW-a6waZj_z_y4Awqmpv3vjoplV-ABHfIxow"
wrk.body = "light_id=2&vote=2&account_id=59"
```
代码仓库

https://github.com/david0315/bus-activity

先 compser install

启动服务
php bin/hyperf.php start

连续执行 wrk 的请求之后就会出现上图的问题

表结构在 ： cli/sql.sql

消费队列
php cli/amqp-consumer.php

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.2
Built => Jan 24 2021 13:14:24
coroutine => enabled with thread context
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1i  8 Dec 2020
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

uname -a: 
Darwin localhost 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

php -v: 

PHP 7.3.25 (cli) (built: Nov 30 2020 14:27:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.25, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.25, Copyright (c) 1999-2018, by Zend Technologies

gcc -v: 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by sy-records** [comment]
不要加enable-thread-context参数编译。

**Comment by david0315** [comment]
你好，我把 enable-thread-context 去掉也是有这样的问题

**Comment by sy-records** [comment]
`make clean` 了吗？`php --ri swoole` 截图

参考说明提交信息：https://github.com/swoole/swoole-src/blob/master/.github/ISSUE-CN.md#%E5%85%B3%E4%BA%8E%E6%AE%B5%E9%94%99%E8%AF%AF%E6%A0%B8%E5%BF%83%E8%BD%AC%E5%82%A8

**Comment by david0315** [comment]
![image](https://user-images.githubusercontent.com/3435608/105657652-da798300-5eff-11eb-882a-0f5512e6a598.png)

刚刚截图的， 连续运行测试了 5 次才出现这个问题

![image](https://user-images.githubusercontent.com/3435608/105657870-45c35500-5f00-11eb-87fa-50f80145ac88.png)


```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.2
Built => Jan 25 2021 11:16:46
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1i  8 Dec 2020
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144
```

**Comment by sy-records** [comment]
提供段错误堆栈截图和内存分析日志，看上面那个链接内容。

**Comment by david0315** [comment]
你好，按照你提供的网址，没有找到 core.xxx 的文件

![image](https://user-images.githubusercontent.com/3435608/105662212-1c0f2b80-5f0a-11eb-8ca5-6d9e2bc03dcb.png)

刚刚按照好 gdb 

我编辑的时候 也添加 这个参数了
```
使用gdb来跟踪swoole前, 需要在编译时添加--enable-debug参数以保留更多信息
```

也开启了 “开启核心转储文件”， ulimit -c unlimited

也没有赵大 core.xxx 类似的文件

**Comment by sy-records** [comment]
到linux复现下吧 mac下是lldb

**Comment by david0315** [comment]
哦， 好的，下午有点忙，晚点复现

**Comment by matyhtf** [comment]
使用`valgrind`跟踪程序执行

```shell
USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php
```

**Comment by huanghantao** [comment]
> 你好，按照你提供的网址，没有找到 core.xxx 的文件
> 
> ![image](https://user-images.githubusercontent.com/3435608/105662212-1c0f2b80-5f0a-11eb-8ca5-6d9e2bc03dcb.png)
> 
> 刚刚按照好 gdb
> 
> 我编辑的时候 也添加 这个参数了
> 
> ```
> 使用gdb来跟踪swoole前, 需要在编译时添加--enable-debug参数以保留更多信息
> ```
> 
> 也开启了 “开启核心转储文件”， ulimit -c unlimited
> 
> 也没有赵大 core.xxx 类似的文件

`macOS`下要生成`core`文件，除了要设置`ulimit`之外，还需要当前用户有写`/cores/`目录的权限。

**Comment by xiangjihan** [comment]
我这边报了一个差不多的错误，但是signal=9。
WARNING	check_worker_exit_status: worker#0[pid=781] abnormal exit, status=0, signal=9
![微信截图_20210716150657](https://user-images.githubusercontent.com/3070542/125906794-b568d218-272b-4fb2-9732-dfee846a36ac.png)

**Comment by guihouchang** [comment]
俺也一样  WARNING check_worker_exit_status: worker#0[pid=24388] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.6.7, please report it.

**Comment by guihouchang** [comment]
俺也一样  WARNING check_worker_exit_status: worker#0[pid=24388] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.6.7, please report it.
