### ISSUE TITLE
Allow Swoole HTTP Server to Set Multiple SSL Settings by Hostname

### ISSUE THREAD

**Issue by nox7** [swoole/swoole-src#4031]
Right now, there is no good and clean way to tell Swoole's HTTP server I want to host multiple SSL configurations for multiple hostnames. I can only set one SSL certificate and key. It limits us to one SSL certificate per IP on a server listening on a port.

```php
$server->set([
	"ssl_cert_file"=>"cert.pem",
	"ssl_key_file"=>"key.pem",
	"open_http2_protocol"=>true,
]);
```

If I want to listen to the "request" event and send a different response based on the "host" (Like a virtual host in Apache) then I can **only do this without SSL on HTTP 1**.

Please allow us to set a SSL based on hostnames. For example,

```php
$server->set([
	"ssl_hosts"=>[
		"www.example.com"=>[
			"ssl_cert_file"=>"cert.pem",
			"ssl_key_file"=>"key.pem",
			"open_http2_protocol"=>true,
		],
		"www.something-else.com"=>[
			"ssl_cert_file"=>"cert2.pem",
			"ssl_key_file"=>"key2.pem",
			"open_http2_protocol"=>false,
		],
	],
]);
```

This would allow Swoole to be closer to production ready in multiple hosting with one Swoole process. This can be done using SNI and sending the hostname to the underlying TLS library of Swoole.

**Comment by sy-records** [comment]
Starting with v4.6.0, Swoole already supports SNI

https://github.com/swoole/swoole-src/blob/master/tests/swoole_http_server/sni/server.phpt

**Comment by nox7** [comment]
Well that's very convenient (and conveniently timed because it got merged last month). I couldn't find it documented on the website docs yet, thanks for pointing that out!

This is a game changer for my production projects. Thanks again.
