### ISSUE TITLE
Process Pool + Coroutine Http Server, how to save websocket connections globally?

### ISSUE THREAD

**Issue by lamboJw** [swoole/swoole-src#4034]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I use process pool start multi coroutine http server, and handle /websocket to use websocket server. I want to save all the websocket connections, I hope the server in process 1 can push data with the connection which in process 2.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.6.1

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux lambojw 4.15.0-132-generic #136-Ubuntu SMP Tue Jan 12 14:58:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
PHP 8.0.1
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by sy-records** [comment]
see https://wiki.swoole.com/#/process/process?id=exportsocket

**Comment by lamboJw** [comment]
> see https://wiki.swoole.com/#/process/process?id=exportsocket

but it just can send string. I use Table save all the fd, but I don't know how to push with fd. Http\Response->push() can't use fd to push data

**Comment by huanghantao** [comment]
Can you describe your problem in pseudocode?

**Comment by lamboJw** [comment]
> Can you describe your problem in specific code?
```
$workerNum = 5;
$pool = new Pool($workerNum, 0, null, true);
$connections = new Table(1024);
$connections->column('is_upgraded', Table::TYPE_INT);
$connections->create();
$pool->on('WorkerStart', function ($pool, $workerId) use ($connections) {
    $server = new Server('0.0.0.0', '8080', false, true);
    Process::signal(SIGTERM, function () use ($server) {
        $server->shutdown();
    });
    $server->handle('/websocket', function (\Swoole\Http\Request $request, \Swoole\Http\Response $ws) use ($connections) {
        $ws->upgrade();
        var_dump($request);
        while (true) {
            $frame = $ws->recv();
            if ($frame === '') {
                $ws->close();
                break;
            } else if ($frame === false) {
                $ws->close();
                break;
            } elseif ($frame->data == 'close' || get_class($frame) === \Swoole\WebSocket\CloseFrame::class) {
                $ws->close();
                break;
            } else {
                $connections->set($frame->fd, ['is_upgraded' => 1]);
                foreach ($connections as $fd => $v) {
                    //TODO create Response to push data
                    var_dump($fd);
                }
            }

        }
    });
    $server->start();
});
$pool->start();
```

**Comment by huanghantao** [comment]
可以用中文。

按照你的写法，目前应该是无解的。或许你可以通过发送通知的方式，通知其他进程来处理各自管理的连接。

**Comment by lamboJw** [comment]
> 可以用中文。
> 
> 按照你的写法，目前应该是无解的。或许你可以通过发送通知的方式，通知其他进程来处理各自管理的连接。

噢~好像可以喔，感谢！
