### ISSUE TITLE
SIGUSR1 信号导致主进程退出问题

### ISSUE THREAD

**Issue by flysion** [swoole/swoole-src#4035]
Please answer these questions before submitting your issue. Thanks!

**1. What did you do? If possible, provide a simple script for reproducing the error.**
示例代码如下：
```php
// http_server1.php
$server = new \Swoole\Server('0.0.0.0', 29999);

$server->on('start', function() {
    swoole_set_process_name("testserver-master");
});

$server->on('receive', function() {

});

$server->on('managerstart', function() {
    swoole_set_process_name("testserver-manager");
});

$server->on('workerstart', function() {
    swoole_set_process_name("testserver-worker");
    echo "worker start\n";
});

$server->on('afterreload', function() {
    echo "afterreload\n";
});

$server->set([
    'reload_async' => true,
    'enable_coroutine' => false,
]);

$server->start();
```

1. 启动服务：php http_server1.php
2. 向master进程发送USR1信号：
```bash
ps -ef | grep testserver-master | awk '{print $2}' | xargs kill -USR1
```

**2. What did you expect to see?**
worker 进程重启并打印：
```bash
worker start
worker start
worker start
worker start
```

**3. What did you see instead?**
所有进程退出并打印：
```bash
用户定义信号 1
```

**4. What version of Swoole are you using (show your `php --ri swoole`)?**
swoole
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.2
Built => Jan 27 2021 14:35:39
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled
Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

**5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?**
$ uname -a
Linux lixx 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$php -v
PHP 7.4.6 (cli) (built: Jun 18 2020 17:36:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

$gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

----

最新进展：向manager进程发送USR1信号能重启worker进程。
总结：
1.向master进程发送USR1信号并没有预想的重启worker进程，而是所有进程都退出了。
2.向manager进程发送USR1信号是正常的（重启worker进程了）
3.已复现swoole版本：4.5.8、4.6.2
4.环境 centos 7（虚拟机）

**Comment by flysion** [comment]
总结一下就是：向master进程发送USR1信号并没有预想的重启worker进程，而是所有进程都退出了。

**Comment by sy-records** [comment]
环境和你一样 没复现

![image](https://user-images.githubusercontent.com/33931153/106421473-bbe33100-6497-11eb-8672-705e8c0a50f9.png)

**Comment by huanghantao** [comment]
@flysion 能否提供一下`strace`信息我们看看？安装一个strace工具。

**Comment by flysion** [comment]
最新进展：向manager进程发送USR1信号能重启worker进程。
总结：
1. 向master进程发送USR1信号并没有预想的重启worker进程，而是所有进程都退出了。
2. 向manager进程发送USR1信号是正常的（重启worker进程了）

**Comment by huanghantao** [comment]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/22836925/106423270-1467fd80-649b-11eb-8214-f253ebe409e0.png">

没能复现，可以按照我这样来操作。然后截图我们看看。

**Comment by flysion** [comment]
> @flysion 能否提供一下`strace`信息我们看看？安装一个strace工具。

$ strace -cp 36220
strace: Process 36220 attached


% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.003531         122        29           epoll_wait
------ ----------- ----------- --------- --------- ----------------
100.00    0.003531                    29           total

**Comment by flysion** [comment]
> @flysion 能否提供一下`strace`信息我们看看？安装一个strace工具。

[pid 36774] <... epoll_wait resumed> [], 4096, 998) = 0
[pid 36774] epoll_wait(14,  <unfinished ...>
[pid 36777] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 36777] futex(0x7fa622795350, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1612162355, tv_nsec=668530317}, 0xffffffff <unfinished ...>
[pid 36775] <... futex resumed> )       = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
[pid 36774] <... epoll_wait resumed> [{EPOLLIN, {u32=31422544, u64=31422544}}], 4096, 998) = 1
[pid 36775] --- SIGUSR1 {si_signo=SIGUSR1, si_code=SI_USER, si_pid=36798, si_uid=1000} ---
[pid 36774] read(15, 0x7fff7c4d7980, 128) = -1 EAGAIN (Resource temporarily unavailable)
[pid 36775] rt_sigaction(SIGUSR1, NULL, {sa_handler=0x76d6e0, sa_mask=~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fa61f655400}, 8) = 0
[pid 36774] clock_gettime(CLOCK_REALTIME,  <unfinished ...>
[pid 36775] rt_sigaction(SIGUSR1, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fa61f655400}, NULL, 8) = 0
[pid 36774] <... clock_gettime resumed> {tv_sec=1612162355, tv_nsec=482171072}) = 0
[pid 36775] rt_sigprocmask(SIG_UNBLOCK, [USR1], NULL, 8) = 0
[pid 36775] kill(36774, SIGUSR1 <unfinished ...>
[pid 36774] stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=556, ...}) = 0
[pid 36775] <... kill resumed> )        = 0
[pid 36774] write(1, "[2021-02-01 14:52:35 #36774.4]\tW"..., 137) = 137
[pid 36774] epoll_wait(14,  <unfinished ...>
[pid 36775] --- SIGUSR1 {si_signo=SIGUSR1, si_code=SI_USER, si_pid=36774, si_uid=1000} ---
[pid 36781] <... epoll_wait resumed> <unfinished ...>) = ?
[pid 36779] <... epoll_wait resumed> <unfinished ...>) = ?
[pid 36781] +++ killed by SIGUSR1 +++
[pid 36779] +++ killed by SIGUSR1 +++
[pid 36775] +++ killed by SIGUSR1 +++
[pid 36782] <... epoll_wait resumed> <unfinished ...>) = ?
[pid 36780] <... epoll_wait resumed> <unfinished ...>) = ?
[pid 36777] <... futex resumed>)        = ?
[pid 36776] <... futex resumed>)        = ?
[pid 36774] <... epoll_wait resumed> <unfinished ...>) = ?
[pid 36776] +++ killed by SIGUSR1 +++
[pid 36782] +++ killed by SIGUSR1 +++
[pid 36780] +++ killed by SIGUSR1 +++
[pid 36777] +++ killed by SIGUSR1 +++
+++ killed by SIGUSR1 +++

**Comment by huanghantao** [comment]
确实有问题

**Comment by matyhtf** [comment]
@flysion 是否安装了一些特殊扩展，在这个扩展中创建了一个线程，但是没有屏蔽线程信号。导致信号在线程内触发，引起了整个进程的退出

**Comment by flysion** [comment]
> @flysion 是否安装了一些特殊扩展，在这个扩展中创建了一个线程，但是没有屏蔽线程信号。导致信号在线程内触发，引起了整个进程的退出

感谢，可能是这样的原因造成的，后来屏蔽调grpc扩展就好了

**Comment by omigafu** [comment]
> @flysion 是否安装了一些特殊扩展，在这个扩展中创建了一个线程，但是没有屏蔽线程信号。导致信号在线程内触发，引起了整个进程的退出

@matyhtf 请问一下，对于要使用 grpc 扩展来体验 opentelemetry-php 的 swoole 应用，除了改动 grpc 扩展本身，还有其他办法可以解决这个 reload 问题吗？
