### ISSUE TITLE
English stub and documentation

### ISSUE THREAD

**Issue by tchiotludo** [swoole/swoole-src#404]
Hello, 

Just for information, I've made an attempt to translate in english the ide stub & generate documentation for swoole (based on the stub) : https://github.com/tchiotludo/swoole-ide-helper & https://cdn.rawgit.com/tchiotludo/swoole-ide-helper/dd73ce0dd949870daebbf3e8fee64361858422a1/docs/index.html.
There is probably an English mistakes since it not my first language, but this is a base that can be improve.
Your extension is really powerful but seems unknown for non chinese people, too bad!
It will be nice if you can maintain this stub and complete it with your knownledge.

Thanks

**Comment by matyhtf** [comment]
Hi, Thank you for your contribution. 
I added the link to the GitHub home page.

**Comment by tchiotludo** [comment]
Hello, 

I've made some modification on the documentation and the link I give you is stick to a commit:
Can you update with this one please : https://rawgit.com/tchiotludo/swoole-ide-helper/english/docs/index.html

It will be the up to date one.

Thanks

**Comment by matyhtf** [comment]
Ok, Thanks.
