### ISSUE TITLE
Requests never finish, after updating to swoole 4.6.3

### ISSUE THREAD

**Issue by acelaya** [swoole/swoole-src#4054]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I have just updated to swoole 4.6.3, and now, any request I make stays loading forever. The body is properly returned, but the connection never closes and the request never finishes.

If you do syncronous requests from a browser, you can actually see the body loaded, but the tab stays in loading state forever.

If the request is asynchronous, it's worst, as the promise never resolves.

I have rolled back to 4.6.2, and it works fine with that version.

2. What did you expect to see?

Requests finish once the body has been transfered, closing the connection after it.

3. What did you see instead?

The requests never finish.

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.3
Built => Feb  9 2021 22:00:23
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

`uname -a`:

```
Linux b383b1a7faee 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 Linux
```

`php -v`:

```
PHP 8.0.2 (cli) (built: Feb  5 2021 04:31:24) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
```

`gcc -v` (not found, as it's Alpine):

```
/bin/sh: gcc: not found
```

**Comment by sy-records** [comment]
You may have set the wrong content-length http header

**Comment by acelaya** [comment]
You are right. My requests are returning a slightly bigger content-length when using v4.6.3 than when using v4.6.2

That probably makes the browser think there's still information left.

The library I'm using to integrate with swoole does this in order to determine the content-length:

```php
$this->bodySize = strlen($this->request->rawContent() ?: '');
```

> The `$this->request` object is a `Swoole\Http\Request` instance.

Is there something different in the `rawContent` method? Should a different approach be used to determine the content-length?

**Comment by acelaya** [comment]
I have done a few more tests to see if there's a pattern, and I have found that, some requests return very different content-lengths.

But not only that. Some requests can return partial responses, like incomplete JSONs.

**Comment by acelaya** [comment]
I can confirm that, if I disable the code calculating the content-length header completely (the one I shared above), then everything works as expected.

In fact, I still get the content-length with the proper value, so I guess swoole is already calculating it somewhere.

**Comment by doubaokun** [comment]
It is not suggested to set content length header until necessary.

**Comment by acelaya** [comment]
I'm wondering why it works with older swoole versions, but it works once that is disabled, so all good, I guess.

Thanks!
