### ISSUE TITLE
Running Swoole server on IPv6 seems not working

### ISSUE THREAD

**Issue by ljfreelancer88** [swoole/swoole-src#4056]
1. What did you do? If possible, provide a simple script for reproducing the error.
`netstat -tlnp` and `netstat -tulpn | grep :9501`

2. What did you expect to see?
I expect port `9501` used the `tcp6`

3. What did you see instead?
I saw port `9501` using `tcp`

4. What version of Swoole are you using (show your `php --ri swoole`)?
`Swoole version 4.5.1`

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
```

Using the following simple script below, I've tried to use IPv6 for Swoole server but seems not using the IPv6.
```php
<?php
$server = new Swoole\HTTP\Server("[::1]", 9501);

$server->on("start", function (Swoole\Http\Server $server) {
    echo "Swoole http server is started";
});

$server->on("request", function (Swoole\Http\Request $request, Swoole\Http\Response $response) {
    $response->header("Content-Type", "text/plain");
    $response->end("Hello World\n");
});

$server->start();
```

**Comment by sy-records** [comment]
Maybe you need to use `::1`?

**Comment by ljfreelancer88** [comment]
Where can I find that configuration in the documentation?

**Comment by sy-records** [comment]
see https://www.swoole.co.uk/docs/modules/swoole-server-construct

**Comment by ljfreelancer88** [comment]
Thank you so much! I think it should be `SWOOLE_SOCK_TCP6` not `SWOOLE_TCP6`.

The documentation should add an example for every different configuration. Like for example for the IPv6. I followed the IPv6 naming convention from NGINX and PHP-FPM. They included the square brackets whereas in Swoole is not.

**Comment by sy-records** [comment]
They're aliases.

**Comment by ljfreelancer88** [comment]
When I added `'worker_num' => swoole_cpu_num()` and used `SWOOLE_BASE`, I got this warning `swReactorProcess_start: The onStart event with SWOOLE_BASE is deprecated`. My question is how will I know when a setting is only for `SWOOLE_PROCESS` and not for `SWOOLE_BASE`?

```php
$server = new Swoole\HTTP\Server("::1", 9501, SWOOLE_BASE, SWOOLE_SOCK_TCP6);

$server->set([
    'worker_num' => swoole_cpu_num()
]);
```

Thank you for your help by the way.

**Comment by sy-records** [comment]
No onStart event in base mode
