### ISSUE TITLE
Coroutine\Http\Client can't use Luminati proxy ! :( 

### ISSUE THREAD

**Issue by miketsl** [swoole/swoole-src#4060]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
$cli->set([
			'http_proxy_host'=> <PROXY_HOST>,
                         'http_proxy_port'=> <PROXY_PORT>,
			'http_proxy_user'=> <PROXY_USER>,
			'http_proxy_password'=> <PROXY_PASS>,
                ]);
$cli->get("/");

2. What did you expect to see?
$cli->statusCode==200

3. What did you see instead?
407 Proxy Authentication required

(These same settings work in normal Guzzle without coroutine and also in Curl also without coroutine)

4. What version of Swoole are you using (show your `php --ri swoole`)?
php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.4-dev
Built => Feb 18 2021 05:34:16
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
dtls => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux adda5117fb18 4.19.130-boot2docker #1 SMP Mon Jun 29 23:52:55 UTC 2020 x86_64 GNU/Linux

PHP 7.4.2 (cli) (built: Feb  1 2020 19:33:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)

**Comment by miketsl** [comment]
This is a TCPDUMP of using Curl without coroutine hook:
GET http://dynupdate.no-ip.com/ip.php HTTP/1.1
Host: dynupdate.no-ip.com
Proxy-Authorization: Basic bHVtLWN1c3RvbWVyLWNfYTNjOTc3MGQtem9uZS1ucDItaXAtMTc4LjE3MS44MC41ODoyN2c2NmNyMTdhN2g=
Accept: */*
Proxy-Connection: Keep-Alive

works....


Now if you change this to use the Coroutine hook:
Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL);
go(function() {

The TCPDUMP looks like this:
GET http://dynupdate.no-ip.com:80/ip.php HTTP/1.1
Host: dynupdate.no-ip.com
Connection: keep-alive


Notice how the Proxy-Authorization is totally missing when its used with the coroutine hook???  why?

**Comment by matyhtf** [comment]
Thanks for your feedback, it has been fixed
