### ISSUE TITLE
[Doc] Process的callback属性是private私有的，应该是无法修改的。

### ISSUE THREAD

**Issue by NathanFreeman** [swoole/swoole-src#4067]
文档链接：https://wiki.swoole.com/#/process/process?id=__construct
文档说明：
    callable $function
    功能：子进程创建成功后要执行的函数【底层会自动将函数保存到对象的 callback 属性上。如果希望更改执行的函数，可赋值新的函数到对象的 callback 属性】
    默认值：无
    其它值：无

但是swoole_process.cc中callback的属性定义是这样的：
zend_declare_property_null(swoole_process_ce, ZEND_STRL("callback"), ZEND_ACC_PRIVATE);
这里应该是没办法直接复制新的函数到对象的 callback 属性

**Comment by sy-records** [comment]
感谢反馈，已修正。
