### ISSUE TITLE
Swoole\Client::recv(): recv() failed. Error: Interrupted system call [4]

### ISSUE THREAD

**Issue by doushen11** [swoole/swoole-src#4069]
php 版本：
PHP 7.1.33 (cli) (built: Feb 20 2021 01:53:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33, Copyright (c) 1999-2018, by Zend Technologies

swoole版本：
[hannan@dlkepu01 ~]$ php --ri swoole

swoole

swoole support => enabled
Version => 1.10.5
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => 1 => 1
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

client为 ： new \swoole\client(SWOOLE_SOCK_TCP | SWOOLE_KEEP)
调用方式为循环调用：
`
foreach ($list as $uuid) {
            // 这里使用了 \swoole\client(SWOOLE_SOCK_TCP | SWOOLE_KEEP)   同步客户端
            $downloadInfo = TextYaf::instance('res')->setClass('ResourceDraft')->getDownUrl([$uuid]);
        }
`

然后就报错了：
Swoole\Client::recv(): recv() failed. Error: Interrupted system call [4]

**Comment by sy-records** [comment]
建议升级版本...

**Comment by matyhtf** [comment]
这是有信号发生中断了 `recv()`，可以重试。最新版本中已经在中断后自动重试了
