### ISSUE TITLE
date_default_timezone_set对协程级别无效

### ISSUE THREAD

**Issue by DlenoDing** [swoole/swoole-src#4071]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

date_default_timezone_set($timezone);
这个函数在PHP里是进程级别的作用范围，而swoole服务是协程级别的；fpm下正常，swoole下就有问题了。
如果一个服务存在不同时区同时并发时，就会存在时间时区混乱问题。
我知道可以有其他方式处理时区，但也只能在自身系统内去处理，如果使用了composer引用其他第三方包，而其他任何第三方使用了时间相关函数，就还是会存在这个问题。

2. What did you expect to see?

官方能否hook下php的时间函数，将date_default_timezone_set的作用范围变成协程级别的，未设置时，默认跟着work进程的时区走。

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.1
Built => Jan 16 2021 05:16:31
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
uname -a
Linux localhost.localdomain 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
php -v
PHP 7.4.14 (cli) (built: Jan  5 2021 10:45:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by twose** [comment]
可以是可以
但是直接将作用范围改成协程级别会造成想改全局时区的人无法修改
当然也可以提供配置开关 就是会有些奇怪 而且必然会影响协程的切换性能(虽然很小) 不管你开不开它

**Comment by DlenoDing** [comment]
那这个你们还改么？
从实际应用来说的话，需要协程级别的时区作用范围，一般不会再去修改进程全局的时区了。
或者能否只在协程下使用了date_default_timezone_set后且在协程下调用时间函数时才hook，没有使用date_default_timezone_set或非协程下就不hook。

**Comment by DlenoDing** [comment]
主协程继承进程的，子协程继承父协程的

**Comment by DlenoDing** [comment]
希望官方能解决下这个问题，我们目前在线上使用，且必须有时区概念；而且这个问题还只能swoole才能解决。
这个问题在同进程下并发的协程越多，问题就越大。目前只能增加work进程数来减少一点问题的频率

**Comment by AlvisZhang** [comment]
我理解你应该是为每个连接添加个时间偏移缓存信息，系统还是统一时区，服务特定连接时，通过连接缓存信息修正系统时间，改 date_default_timezone_set() 这个只是系统的基准时区

**Comment by DlenoDing** [comment]
> 我理解你应该是为每个连接添加个时间偏移缓存信息，系统还是统一时区，服务特定连接时，通过连接缓存信息修正系统时间，改 date_default_timezone_set() 这个只是系统的基准时区

这种方式只能解决自身系统的时间问题，但引用的那么多第三方composer组件里的时间调用还是会有问题，因为我们改不了那么多第三方包，别人也不会来专门兼容这个问题

**Comment by DlenoDing** [comment]
> 我理解你应该是为每个连接添加个时间偏移缓存信息，系统还是统一时区，服务特定连接时，通过连接缓存信息修正系统时间，改 date_default_timezone_set() 这个只是系统的基准时区

我们是每个请求都会带上客户端所在的时区标识，然后业务处理前date_default_timezone_set设置为请求给的时区；
后续程序里就不用再管时区问题，这种在fpm下好像没问题；但在swoole协程下就有问题了。
这个可以利用php的DateTime相关类处理自身代码的时区问题，但确处理不了引用进来的第三方composer包代码里的时区问题。

**Comment by matyhtf** [comment]
“date_default_timezone_set($timezone);
这个函数在PHP里是进程级别的作用范围，而swoole服务是协程级别的；”

这个函数无论是在 PHP 还是在 swoole 中都是进程级的。

**Comment by matyhtf** [comment]
你可以在 php.ini 中配置好时区，然后 disable_functions 中配置 `date_default_timezone_set` 禁止调用此函数。

**Comment by fanuser** [comment]
用这个   可以不用设置全部时区

**Comment by fanuser** [comment]
用这个可以不用设置全局时区 可以在协程中使用 (new DateTime())->setTimestamp($timestamp)->setTimezone((new DateTimeZone("UTC")))->format('M.d, Y H:i:s')
