### ISSUE TITLE
$response->cookie() does not allow null for samesite

### ISSUE THREAD

**Issue by dominikzogg** [swoole/swoole-src#4077]
I filled this issue based on a issue i received on one of my library: https://github.com/chubbyphp/chubbyphp-swoole-request-handler/issues/3

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
My library calls $response->cookie (https://github.com/chubbyphp/chubbyphp-swoole-request-handler/blob/master/src/SwooleResponseEmitter.php#L41) will null for $samesite. Based on the signature in https://github.com/swoole/ide-helper/blob/master/output/swoole/namespace/Http/Response.php#L35 $samesite is nullable.

2. What did you expect to see?
No error at all

3. What did you see instead?
Fatal error: Uncaught TypeError: Swoole\Http\Response::cookie(): Argument #8 ($samesite) must be of type string, null given in /vendor/chubbyphp/chubbyphp-swoole-request-handler/src/SwooleResponseEmitter.php:41

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.6.0

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
8.0

**Comment by sy-records** [comment]
see https://www.swoole.co.uk/docs/modules/swoole-http-response-cookie

can be set to an empty string instead of null

**Comment by dominikzogg** [comment]
@sy-records thx
