### ISSUE TITLE
mac下php8的环境编译安装swoole报错

### ISSUE THREAD

**Issue by shine96** [swoole/swoole-src#4081]
![image](https://user-images.githubusercontent.com/58157887/110114366-7ba50480-7def-11eb-8aa4-8c1f774f801c.png)

**Comment by LuvTian** [comment]
也遇到同样无法编译swoole的问题 #4075
好像只能pecl安装

**Comment by shine96** [comment]
> 也遇到同样无法编译swoole的问题[＃4075](https://github.com/swoole/swoole-src/issues/4075)
> 好像只能pecl安装

我连pecl都装不进去，也是报这个错

**Comment by matyhtf** [comment]
可能是环境的问题，错误信息并不是出现在 swoole 代码中，与swoole 无关的错误。请重新安装或更新 gcc/clang 编译器
