### ISSUE TITLE
(/usr/lib/php/20190902/swoole.so: undefined symbol: curl_CURLFile_class

### ISSUE THREAD

**Issue by lxhanhan** [swoole/swoole-src#4085]
开启 swoole curl 编译安装  之后
执行php 会报错

PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/lib/php/20190902/swoole.so (/usr/lib/php/20190902/swoole.so: undefined symbol: curl_CURLFile_class), /usr/lib/php/20190902/swoole.so.so (/usr/lib/php/20190902/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  Module 'json' already loaded in Unknown on line 0

**Comment by matyhtf** [comment]
请调整扩展加载顺序，先加载 curl.so 后加载 swoole.so

**Comment by jucci1887** [comment]
怎么调整phpenmod的加载顺序

**Comment by NathanFreeman** [comment]
> 
> 
> 怎么调整phpenmod的加载顺序

php配置文件中
```shell
extension=curl.so
extension=swoole.so
```

**Comment by jingjingxyk** [comment]
debian 或者 ubuntu 调整顺序,  使用数字优先级配置

1. 先查看 配置 ini 配置 执行 ` php --ini `  找到 类似 ` /etc/php/8.2/cli/conf.d` 目录
1. 目录中，你会看到很多数字开头的配置文件，数字实际是优先级配置，数字越小，优先级越大
1. 创建swoole 配置文件 ，比如以 30 开头 `30-swoole.ini` 

```bash
php --ini

cd  /etc/php/8.2/cli/conf.d
ls -lha .


vi 30-swoole.ini
; configuration for php swoole module 
; priority=30 
extension=swoole.so 
 


```
