### ISSUE TITLE
Swoole Atomic is returning NULL.

### ISSUE THREAD

**Issue by sauriio** [swoole/swoole-src#4090]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I tried to use the swoole atomic as a shared var in the server and event handlers of the server, but when i tried to access the value saved on the atomic object it returns NULL.
```php
<?php

namespace Proxy\Atomics;

use Swoole\Atomic;

class BlockedSwitchAtomic
{
    protected $blockFlag;
    
    public function __construct()
    {
        $this->blockFlag = new Atomic(0);
    }

    public function isBlocked()
    {
        return $this->blockFlag->get();
    }

    public function lock()
    {
         $this->blockFlag->set(1);
    }

    public function unlock()
    {
        $this->blockFlag->set(0);
    }
}

```
```php
<?php

namespace Proxy\Atomics;

use Swoole\Atomic;

class TimeStampAtomic
{
    protected $lastCommunicationFromSocket;
    
    public function __construct()
    {
        $this->lastCommunicationFromSocket = new Atomic(0);    
    }

    public function get()
    {
         $this->lastCommunicationFromSocket->get();
    }

    public function update()
    {
        $this->lastCommunicationFromSocket->set(time());
    }
}

```php
<?php

namespace Proxy\Server;

use Proxy\Events\ConnectEvent;
use Proxy\Events\ReceiveEvent;
use Configuration\ServerConfig;
use Proxy\Atomics\BlockedSwitchAtomic;
use Proxy\Atomics\TimeStampAtomic;
use Proxy\Stan\StanController;
use Swoole\Server;

class TCPServer
{
    private $proxyServer;

    public $blockSwitch;

    public $stanController;

    public $lastConnection;

    public function __construct()
    {
            $this->serverConf = new ServerConfig();
            $this->proxyServer = new Server(
                $this->serverConf->getServerHost(),
                $this->serverConf->getServerPort(),
                SWOOLE_PROCESS,SWOOLE_SOCK_TCP);
            $this->proxyServer->set($this->serverConf->getServerSettings());
            $this->stanController = new StanController();
            $this->blockSwitch = new BlockedSwitchAtomic();
            //añadimos el atomic para la ultima conexion.
            $this->lastConnection = new TimeStampAtomic();
            $this->setEvents();
            $this->proxyServer->start();
    }
    public function getServer()
    {
        return $this->proxyServer;
    }

    private function setEvents()
    {
        ConnectEvent::set($this);
        ReceiveEvent::set($this);
    }
}
```
```php

<?php

namespace Proxy\Events;

use Proxy\Events\Base\BaseEvent;
use Proxy\Server\TCPServer;

class ConnectEvent implements BaseEvent
{
    public static function set(TCPServer $proxyServer)
    {
        $proxyServer->getServer()->on('connect', function($server, $client) use ($proxyServer){
            $oData = [
                'status' => 'success',
                //this is where I get a null value instead of the timestamp
                'last_communication' => $proxyServer->lastConnection->get(),
            ];        
            $server->send($client,
               json_encode($oData)
            );
            
        });
    }

}

```
2. What did you expect to see?
json response with the timestamp set.

3. What did you see instead?
nc localhost 8300
{"status":"success","last_communication":null}

and some other classes that are using a Atomic Object has the same problem.

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.3
Built => Mar  3 2021 00:29:31
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1f  31 Mar 2020
dtls => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
uname -a
Linux mario-hitss 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

php -v
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

**Comment by sy-records** [comment]
I don't understand your code where it calls update?

**Comment by sauriio** [comment]
could be called on the ConnectEventClass on line 19, the result from two different connections is the same, NULL.

nc localhost 8300
{"status":"success","last_communication":null}

on the second call is the same.

**Comment by sy-records** [comment]
Please change your code.

```diff
class TimeStampAtomic
{
    protected $lastCommunicationFromSocket;

    public function __construct()
    {
        $this->lastCommunicationFromSocket = new Atomic(0);
    }

    public function get()
    {
-         $this->lastCommunicationFromSocket->get();
+        $data = $this->lastCommunicationFromSocket->get();
+        if ($data === 0) {
+            return $this->update();
+       }

+        return $data;
    }

    public function update()
    {
+        $date = time();
        $this->lastCommunicationFromSocket->set($date);

+        return $date;
    }
}
```

**Comment by sauriio** [comment]
the addition only returns the date generated by the update function, I need to trigger it with a signal, and then it will be mostly read by the ConnectEvent (the workers too).

**Comment by sauriio** [comment]
in a practical case, i will only save the first connection timestamp, and the subsequents will take the timestamp on the Atomic object to return it to the client.

**Comment by sy-records** [comment]
You need to ensure that the value is set...

```php
    public function get()
    {
        $data = $this->lastCommunicationFromSocket->get();
        if ($data === 0) {
            $this->update();
            $data = $this->lastCommunicationFromSocket->get();
        }

        return $data;
    }

    public function update()
    {
        $this->lastCommunicationFromSocket->set(time());
    }
```

**Comment by matyhtf** [comment]
```php

class TimeStampAtomic
{
    protected $lastCommunicationFromSocket;
    
    public function __construct()
    {
        $this->lastCommunicationFromSocket = new Atomic(0);    
    }

    public function get()
    {
         $this->lastCommunicationFromSocket->get(); 
         // ? You did not return any content here
    }

    public function update()
    {
        $this->lastCommunicationFromSocket->set(time());
    }
}
```
