### ISSUE TITLE
PDO and Too many connections issue

### ISSUE THREAD

**Issue by Draghmar** [swoole/swoole-src#4094]
1. What did you do? If possible, provide a simple script for reproducing the error.
I'm in the middle of testing Swoole and one of the main thing is get one of my scripts up and running. It uses my custom PDO wrapper that simplify some of the common tasks, mostly preparing statement, beginning transaction, binding and committing. I'm really struggling with getting db connection being reliable...
For reference: my normal setup is Apache with php-fpm and MariaDB and it manage to pass test fine, although slower.

2. What did you expect to see?
Well...normal behaviour but faster ;)

3. What did you see instead?
I'm using `ab` to test out speed and limits. If I use some small batch everything will go smoothly. But getting into higher numbers gets me `SQLSTATE[HY000] [1040] Too many connections`. 

To present this as simple as possible I'll try to explain what I tried...
The base code block is:
```php
require_once('config.php');
// SWOOLE_HOOK_ALL because that's easier then sitting and thinking which one I should put there ;)
Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_ALL);
$srv = new Swoole\HTTP\Server('127.0.0.1', 9502);
$srv->set([
	'log_level' => 0,
	'reload_async' => true,
	'http_compression_level' => 5,
	'http_gzip_level' => 5,
]);
$srv->on('request', function($request, $response) use ($srv, $config) {
	// many, many lines of code :P
});
```
At first I tried the simplest thing I could think of, which is putting `PDO` connection right into `request` block, like so:
```php
$srv->on('request', function($request, $response) use ($srv, $config) {
	try {
		$db = new DB($config);
	} catch(Exception $e) {
		var_dump($e->getMessage());
	}
	// Some other stuff that uses above connection
});
```
This however creates `SQLSTATE[HY000] [1040] Too many connections` error.
I also tried to use something like this, although this was mostly blind experimenting because I don't have enough Swoole knowledge ;)
```php
$dbpool = new ConnectionPool(function() use ($config) {
	// DB returns PDO object so I based it on PDOPool code
	return new DB($config);
});
// And next all the server code like above, with addition of $db = $dbpool->get();
$srv->on('request', function($request, $response) use ($srv, $config, $dbpool) {
	$db = $dbpool->get();
	// Some other stuff that uses this pool
});
```
This one can't even finish `ab` because of timeout. :(

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.3
Built => Mar 10 2021 08:29:16
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1j  16 Feb 2021
dtls => enabled
http2 => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
Linux 5.10.12-arch1-1 #1 SMP PREEMPT Sun, 31 Jan 2021 00:41:06 +0000 x86_64 GNU/Linux
```
```
PHP 8.0.3 (cli) (built: Mar  4 2021 05:33:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Xdebug v3.0.2, Copyright (c) 2002-2021, by Derick Rethans
```
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC)
```

**Comment by Draghmar** [comment]
I found some other stuff that potentially helps with my issue.
First one is adding this:
```php
$dbpool->put($db);
```
at the end of the script. With this I can go with high numbers in `ab` and it manage to go through. As far as I understand this method simply takes active connection and `put` it back into the pool again. It helps probably because having app in Swoole makes all the connections not end like they would normally would do which means they are wasted.
I'm not sure if that's safe though, when dealing with requests from different clients that is. Anyone?
I think it would be better to actually end database connection but unfortunately I'm not sure how (`PDO` doesn't have anything like `close` and setting `null` didn't work as far as tests go.

Another interesting bit I found which is `new Swoole\Coroutine\Http\Server`. It has interesting approach to work and at the first tests it worked great...until I did test with bigger script, which easily exhausted available memory. I wonder if it needs some different approach to coding stuff...

**Comment by ValiDrv** [comment]
On each request, you need to get and then put back the connection to your pool.

Also, if you have X workers, each of them will have up to N connections per worker, so your database must handle X*N connections.

This is not really Swoole related.

**Comment by Draghmar** [comment]
Yeah, the test I've made  indicated the same thing: setting second parameter for `ConnectionPool` to the max connections MariaDB can handle, solved the issue. I wasn't sure about the approach though, because there was no mention about this in documentation. So thanks for clarification. :)

As for the coroutine - I thought that doing `onRequest` actually creates coroutine...I'm pretty sure I read somewhere about that...If that's not the case then your suggestion is to wrap everything like this?
```php
use function Swoole\Coroutine\run;
Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_ALL);
run(function() use ($config) {
	$dbpool = new ConnectionPool(function() use ($config) {
		return new DB($config['users']);
	}, 500);
	$srv = new Swoole\HTTP\Server('127.0.0.1', 9502);
	$srv->set([
		'log_level' => 0,
		'reload_async' => true,
		'http_compression_level' => 5,
		'http_gzip_level' => 5,
	]);
	$srv->on('request', function($request, $response) use ($srv, $config) {
		go(function() {
			// many, many lines of code :P
		});
	});
});

**Comment by Draghmar** [comment]
I must doing something wrong when trying this because I'm getting:
```
Warning: Swoole\Server::start(): eventLoop has already been created
```
I also tried `Swoole\Coroutine\Http\Server` but this one exhausts allowed memory.

**Comment by JetDevices** [comment]
Maybe you need to use tasks? Pass all I/O operations to the task (coroutine tasks)

**Comment by embluk** [comment]
@DanielRuf When using a Swoole HTTP server you don't need to wrap it inside a `Co\run` as the server does that for you. Yes, the `onRequest` event does create a coroutine context for you, you can then add more calls to `go()` to run things concurrently. Try placing your connection pool startup inside your `onWorkerStart` event and make sure to return your PDO connections.

Checkout https://www.swoole.co.uk/docs/modules/mysqli-connection-pool for more info on DB pools.

**Comment by DanielRuf** [comment]
Hi, I think you mentioned me by accident.

**Comment by embluk** [comment]
> Hi, I think you mentioned me by accident.

Yes, sorry about that.

**Comment by Draghmar** [comment]
> When using a Swoole HTTP server you don't need to wrap it inside a `Co\run` as the server does that for you. Yes, the `onRequest` event does create a coroutine context for you, you can then add more calls to `go()` to run things concurrently. Try placing your connection pool startup inside your `onWorkerStart` event and make sure to return your PDO connections.
> 
> Checkout https://www.swoole.co.uk/docs/modules/mysqli-connection-pool for more info on DB pools.

Thanks for suggestion. Is there anything I could gain from wrapping `ConnectionPool` into `WorkerStart`?
I'm already fighting with that BTW - you can check that [here](https://github.com/swoole/swoole-src/issues/4131) if you're interested.
