### ISSUE TITLE
并发情况下task[2270537] is invalid

### ISSUE THREAD

**Issue by dd01wangzhenzhen** [swoole/swoole-src#4100]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

并发情况下$server->taskCo($data, $timeout);

2. What did you expect to see?
并发情况下运行正常

3. What did you see instead?

task[2270537] is invalid

4. What version of Swoole are you using (show your `php --ri swoole`)?

v4.3.3

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

unbuntu 18.04 64位

6 我在源码中找到了这个,不是很懂,可以解释下,什么情况下会出现这个错误吗
![image](https://user-images.githubusercontent.com/39894147/111140755-ac3e2880-85bd-11eb-95b1-2da1673e1ae2.png)

**Comment by matyhtf** [comment]
有可能 Worker 进程退出了，但是 Task 进程执行完成后，在新的 Worker 进程中触发了回调，但底层已经找不到对应的 task 上下文了。

**Comment by dd01wangzhenzhen** [comment]
感谢指点,本来我以为是并发压力导致,但是我检查了各项资源,发现都很平稳.

我在日志中找到了这两条

第二条日志中显示worker退出了,我的疑问是如何排查是什么导致了worker的退出,自身业务也没有发信号kill,而且业务相对平稳

第一条日志和第二条有什么联系吗?


第一条:2021-03-16 07:35:24  WARNING\tswProcessPool_dispatch: send 2072 bytes to worker#7 failed"

第二条:2021-03-16 07:35:26 WARNING\tswManager_check_exit_status: worker#7[pid=41] abnormal exit, status=0, signal=9

**Comment by dd01wangzhenzhen** [comment]
@matyhtf
