### ISSUE TITLE
swoole 发送苹果apns的时候worker中断

### ISSUE THREAD

**Issue by burtgit** [swoole/swoole-src#4103]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

使用stream_socket_client发送苹果的apns信息时，发送是成功了，但是worker却出现了错误，源码如下：
![image](https://user-images.githubusercontent.com/17825436/111285247-e5d56900-867b-11eb-918e-d3cd40d688bf.png)

2. What did you expect to see?
成功发送stream请求

3. What did you see instead?
发送是成功了，但是出现了错误，worker异常退出，图片如下：
![image](https://user-images.githubusercontent.com/17825436/111285507-2a610480-867c-11eb-90f1-8f13d448875a.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?

![image](https://user-images.githubusercontent.com/17825436/111285616-495f9680-867c-11eb-9fd5-f9075cd3f007.png)

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
![image](https://user-images.githubusercontent.com/17825436/111285801-7ca22580-867c-11eb-9e98-374350ac8b99.png)

**Comment by matyhtf** [comment]
@burtgit 请更新至 4.6.4 测试一下，如果还有问题请使用 valgrind 跟踪程序执行，将日志发到这里

**Comment by burtgit** [comment]
可以了，谢谢
