### ISSUE TITLE
swoole tcp server onReceive can’t get the value of fd or data

### ISSUE THREAD

**Issue by zoucan666** [swoole/swoole-src#4106]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

   

> 

- **swoole tcp server onReceive 偶尔无法获取fd 及 data**
       `        // 创建Server对象
        $server = new \Swoole\Server('0.0.0.0', env('TCP_SOCKET_PORT', 9501));

        // 监听连接进入事件
        $server->on('Connect', [$this, 'onConnect']);

        // 监听数据接收事件
        $server->on('Receive', [$this, 'onReceive']);

        // 监听连接关闭事件
        $server->on('Close', [$this, 'onClose']);

        // 启动服务器
        $server->start();`

      public function onConnect($server, $fd)
      {
        logger('New TCP connection', [$fd]);
      }

      public function onReceive($server, $fd, $from_id, $data)
      {
        logger('TCP Received data', [$fd, $data]);
      }`
- 
<img width="1920" alt="QQ20210318-115038@2x" src="https://user-images.githubusercontent.com/50316386/111570688-4bdb0100-87e0-11eb-8c41-fb0fe4746ad0.png">

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

    swoole
    
    Swoole => enabled
    Author => Swoole Team <team@swoole.com>
    Version => 4.5.9
    Built => Dec  4 2020 09:55:57
    coroutine => enabled
    epoll => enabled
    eventfd => enabled
    signalfd => enabled
    cpu_affinity => enabled
    spinlock => enabled
    rwlock => enabled
    pcre => enabled
    zlib => 1.2.7
    mutex_timedlock => enabled
    pthread_barrier => enabled
    futex => enabled
    async_redis => enabled
    
    Directive => Local Value => Master Value
    swoole.enable_coroutine => On => On
    swoole.enable_library => On => On
    swoole.enable_preemptive_scheduler => Off => Off
    swoole.display_errors => On => On
    swoole.use_shortname => On => On
    swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
    [root@shanghai logs]# uname -a
    Linux shanghai 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
    [root@shanghai logs]# php -v
    PHP Warning:  Module 'sockets' already loaded in Unknown on line 0
    PHP 7.2.16 (cli) (built: Mar 10 2019 21:22:49) ( NTS )
    Copyright (c) 1997-2018 The PHP Group
    Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
        with Zend OPcache v7.2.16, Copyright (c) 1999-2018, by Zend Technologies
    您在 /var/spool/mail/root 中有邮件
    [root@shanghai logs]# gcc -v
    使用内建 specs。
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
    目标：x86_64-redhat-linux
    配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
    线程模型：posix
    gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

**Comment by matyhtf** [comment]
@zoucan666  请使用最新的 4.6.4 版本，另外，这里传入的是一个数组，$fd 如果是空的，那么也应该是 0，而不是空白吧？

**Comment by zoucan666** [comment]
是的，我用swoole tcp client 模拟了一些数据没有出现 fd 和 data 为空的情况，这是在生产环境由通信终端cat1 和服务器连接出现的空白，现在不太确定是swoole本身的问题还是通信终端的问题

**Comment by zoucan666** [comment]
> @zoucan666 请使用最新的 4.6.4 版本，另外，这里传入的是一个数组，$fd 如果是空的，那么也应该是 0，而不是空白吧？

@matyhtf  是的，我用swoole tcp client 模拟了一些数据没有出现 fd 和 data 为空的情况，这是在生产环境由通信终端cat1 和服务器连接出现的空白，现在不太确定是swoole本身的问题还是通信终端的问题

**Comment by matyhtf** [comment]
@zoucan666 需要进一步调试追踪，得到更多线索

**Comment by zoucan666** [comment]
> @zoucan666 需要进一步调试追踪，得到更多线索
@matyhtf  那这个receive方法 是一定有数据传入才会执行的对吗，会不会因为某种原因错误的进入？我追踪了最近几天的日志，connect方法是100%会打印出fd,然而接下来的receive就是空白，这就让我很困惑

**Comment by matyhtf** [comment]
你可以试试添加函数参数

```php
public function onReceive($server,  int $fd, int $from_id, string $data)
{
  logger('TCP Received data', [$fd, $data]);
}`
```

**Comment by zoucan666** [comment]
> 你可以试试添加函数参数类型限定
> 
> ```
> public function onReceive($server,  int $fd, int $from_id, string $data)
> {
>   logger('TCP Received data', [$fd, $data]);
> }
> ```

经过一段时间的调试追踪，基本定位了问题的原因，data字符串中出现中文或者全角符号导致乱码，这需要作何设置呢？

**Comment by matyhtf** [comment]
json_encode 必须要求传入的字符串为 utf-8 编码，你可以检查 data 字符串的编码是否合法。
