### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'EasySwoole\EasySwoole\Command\CommandContainer' not found 

### ISSUE THREAD

**Issue by wxiaofan** [swoole/swoole-src#4112]
PHP Fatal error:  Uncaught Error: Class 'EasySwoole\EasySwoole\Command\CommandContainer' not found 
#0 /home/biduoduo-api/biduoduo-api/vendor/easyswoole/easyswoole/bin/easyswoole(23): require_once()

**Comment by sy-records** [comment]
请前往easyswoole的repo提交issue。
