### ISSUE TITLE
\Swoole\Coroutine\run missing in apache2

### ISSUE THREAD

**Issue by diyism** [swoole/swoole-src#4122]
/etc/apache2/mods-enabled/php7.4.load       LoadModule php7_module /usr/lib/apache2/modules/libphp7.4.so
pecl install swoole
echo 'extension=swoole.so' > /etc/php/7.4/apache2/conf.d/25-swoole.ini
service apache2 restart

index.php:
```
<?php
var_export(swoole_version());
var_export(class_exists('Swoole\Coroutine'));
var_export(class_exists('Co'));
var_export(function_exists('Co\run'));
var_export(function_exists('Swoole\Coroutine\run'));
?>

```
visit "http://127.0.0.1/index.php"  it shows:
'4.6.4' true true false false

run "php index.php" it shows:
'4.6.4' true true true true

Can I use "Co\run()" in apache2 ?

**Comment by diyism** [comment]
And I found that Swoole\Coroutine\run()  won't work in nginx+php7.4-fpm either.
Is there any way to enable Swoole\Coroutine\run() in php7.4-fpm?
Because eanbleing an old project running in php-cli is very complex, I prefer run Co\run() in php7.4-fpm.

**Comment by sy-records** [comment]
Coroutine can only run in CLI mode

**Comment by diyism** [comment]
OK, close this issue, I found symfony swoole bundle: https://github.com/k911/swoole-bundle
