### ISSUE TITLE
Call to undefined method Swoole\Coroutine\MySQL\Statement::bind_param()

### ISSUE THREAD

**Issue by ljfreelancer88** [swoole/swoole-src#4128]
I'm trying to get rid of using `escape()`using the combination of `prepare()` and `bind_param()` but `bind_param()` seems not available in Swoole or did I missed during compilation?

```php
$statement = $db->prepare("INSERT INTO `post` (`title`, `content`, `seen`) VALUES (?, ?, ?)");
$statement->bind_param($title, $content, 0);
```

**Comment by NathanFreeman** [comment]
Swoole\Coroutine\MySQL\Statement do not support bind_param function.
 The alternative method is:
$statement = $db->prepare("INSERT INTO `post` (`title`, `content`, `seen`) VALUES (?, ?, ?)");
$statement->execute( [$title, $content, 0] );

**Comment by ljfreelancer88** [comment]
Thank you so much. Should add that in the wiki or documentation.

**Comment by embluk** [comment]
The documentation has been updated to make this more clear: https://www.swoole.co.uk/docs/modules/swoole-coroutine-mysql
