### ISSUE TITLE
[Feature Request]Automatically turn global variables/sessions into \Co::getContext()['request'], just like one-line-coroutinization(\Co::enableCoroutine())

### ISSUE THREAD

**Issue by diyism** [swoole/swoole-src#4129]
I've found two projects: symfony swoole server(https://github.com/k911/swoole-bundle) and laravel shadowfax swoole server(https://github.com/huang-yi/shadowfax)
It seems the two can run old symfony and laravel projects on the swoole http server,
but both of them require the programmers to modify all codes about global varables/sessions.

Is there any possibility to modify the php interpreter itselft to automatically turn global variables/sessions into \Co::getContext()['request'], just like one-line-coroutinization(\Co::enableCoroutine())?

So that we don't have to modify the old php project to get the super power of swoole.

**Comment by diyism** [comment]
I've tried to overwrite session_start(),_SESSION, session_write_close(), _COOKIE, header(),_POST, _GET, _SERVER with namespace global_functions, but it's ugly. (https://github.com/diyism/go2php/blob/master/go2php_server.php)

**Comment by twose** [comment]
We have discussed this issue many times long before and we won't implement such specific behaviors in the kernel, some frameworks implement this feature with ArrayObject (change these globals vars to ArrayObject), you can try it too.

**Comment by matyhtf** [comment]
Swoole should not change the behavior of php.
