### ISSUE TITLE
$serv->close($fd); 服务端主动断开客户端有问题！

### ISSUE THREAD

**Issue by designinlife** [swoole/swoole-src#413]
onClose() 事件的确被触发，但触发事件时并不在 fd 所属的工作进程！看我截的图。
![swoole-error-1](https://cloud.githubusercontent.com/assets/120458/11530235/f9bf8c0c-992d-11e5-90e0-63c1153cc440.png)

使用版本: swoole-1.7.21-stable

**Comment by matyhtf** [comment]
贴出你的Server设置

**Comment by designinlife** [comment]
![2015-12-04_211451](https://cloud.githubusercontent.com/assets/120458/11590574/1eafe5ee-9acc-11e5-9761-ba70dfd1fe89.png)

这是我的设置

**Comment by matyhtf** [comment]
19758 进程是不是异常退出了？另外使用的是SWOOLE_BASE模式吗？

**Comment by designinlife** [comment]
使用的 SWOOLE_PROCESS 模式

**Comment by matyhtf** [comment]
已解决，问题原因与 #722 相同。因为是在 Task进程 执行了close
