### ISSUE TITLE
reactor_num设为24， 但cpu只使用了12个。

### ISSUE THREAD

**Issue by peterxiemin** [swoole/swoole-src#414]
这是top截图
![default](https://cloud.githubusercontent.com/assets/3784412/11549172/bc7d2914-999e-11e5-8883-362deac2f992.jpg)

这是我在程序做的设置

![default](https://cloud.githubusercontent.com/assets/3784412/11549140/7196ba82-999e-11e5-8b61-227bea8ef927.jpg)

**Comment by matyhtf** [comment]
CPU使用与reactor数量没有关系，你可以使用 pstree -a 主进程ID查看reactor线程个数。
