### ISSUE TITLE
PDOPool does not reconnect on connection timeout.

### ISSUE THREAD

**Issue by intellent** [swoole/swoole-src#4141]
### 1. What did you do? If possible, provide a simple script for reproducing the error.

Created a MySQL `PDOPool` to fetch connections with `PDOPool::get()` and put them back with `PDOPool::put($con)` after the HTTP response has been served. `wait_timeout` of the DBMS is very low (60 seconds), but this problem also occurs with larger values, only later.

### 2. What did you expect to see?

I expect `PDOPool::get()` to return a working connection and check for terminated connections.

### 3. What did you see instead?

After some successful connections and waiting for the connection timeout to occur `PDOPool::get()` returns a terminated connection resulting in *error 2006 MySQL server has gone away*

### 4. What version of Swoole are you using?

> Swoole => enabled
> Author => Swoole Team <team@swoole.com>
> Version => 4.6.4
> Built => Apr  8 2021 18:15:20
> coroutine => enabled with boost asm context
> epoll => enabled
> eventfd => enabled
> signalfd => enabled
> spinlock => enabled
> rwlock => enabled
> mutex_timedlock => enabled
> pthread_barrier => enabled
> async_redis => enabled
> 
> Directive => Local Value => Master Value
> swoole.enable_coroutine => On => On
> swoole.enable_library => On => On
> swoole.enable_preemptive_scheduler => Off => Off
> swoole.display_errors => On => On
> swoole.use_shortname => On => On
> swoole.unixsock_buffer_size => 8388608 => 8388608

### 5. What is your machine environment used?

> Linux 1100dd632f36 4.19.121-linuxkit #1 SMP Thu Jan 21 15:36:34 UTC 2021 x86_64 Linux
> 
> PHP 8.0.3 (cli) (built: Apr  1 2021 15:27:33) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v4.0.3, Copyright (c) Zend Technologies

**Comment by intellent** [comment]
I’ve tried working around this issue by catching the `PDOException 2006 MySQL server has gone away`. How can I remove a terminated connection from PDOPool?

**Comment by sy-records** [comment]
If an exception occurs, you can put `null` back into the pool.

```php
try {

} catch (\Throwable $e) {
    $pool->put(null);
}
```

**Comment by TorstenDittmann** [comment]
@intellent just wanna mention how I solved this exact problem here https://github.com/swoole/swoole-src/issues/4131#issuecomment-904760366
