### ISSUE TITLE
socket_create()创建的资源使用swoole_event_add()报错

### ISSUE THREAD

**Issue by momaer** [swoole/swoole-src#415]
php 版本:5.6.10
swoole版本：1.7.20

测试代码如下：

    $ip = '127.0.0.1';
    $port = 80;

    $h = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
    if($h === false) {
        echo 'socket create failed.', PHP_EOL;
        exit();
    }
    socket_set_nonblock($h);

    $ret = swoole_event_add($h, null, function() use($h) {
        //连接上来了
        swoole_event_del($h);

        socket_write($h, "HEAD / HTTP/1.1\r\nHost: www.actself.me\r\n\r\n");

        swoole_event_add($h, function() use($h) {

            $data = socket_read($h, 1024);
            echo $data, PHP_EOL;
            //socket_write($h, "HEAD / HTTP/1.1\r\nHost: www.actself.me\r\n\r\n");

        }, null, SWOOLE_EVENT_READ);

    }, SWOOLE_EVENT_WRITE);

    var_dump($ret);

    socket_connect($h, $ip, $port);

    echo "finish\n";

结果如下：
PHP Warning:  swoole_event_add(): fd argument must be valid PHP stream resource in /home/gaoshijie/swoole_load3.php on line 28
PHP Warning:  swoole_event_add(): unknow type. in /home/gaoshijie/swoole_load3.php on line 28
bool(false)
finish

请问是不是bug？还是我姿势不对？谢谢！

**Comment by matyhtf** [comment]
编译swoole需要增加 --enable-sockets

**Comment by momaer** [comment]
谢谢！明白了，我是使用pecl直接安装。我再增加这个参数编译一下。
