### ISSUE TITLE
How to increase TCP window size

### ISSUE THREAD

**Issue by ggolda** [swoole/swoole-src#4151]
In documentation it is said that by default TCP buffer size is set to 64kb. How to increase it?

I tried changing different parameters from this article: https://www.swoole.co.uk/docs/modules/swoole-server/configuration
and they take no effect at all.

Thanks!

**Comment by matyhtf** [comment]
The recv buffer size cannot be set at the application layer. Do not modify it, you can merge data at the php code layer.
