### ISSUE TITLE
纯异步的Server有打算支持max_request吗？

### ISSUE THREAD

**Issue by redfoxli** [swoole/swoole-src#416]
从文档上看

```
注意：max_request只能用于同步阻塞的服务器，纯异步的Server不应当设置max_request
```

异步的server，内存方面是个问题，咋解决呢？

**Comment by matyhtf** [comment]
有。1.8.0 有这个开发计划

**Comment by zhangjunlei26** [comment]
试了一下1.8.5，还是不支持纯异步server的，所以类似tsf这样基于swoole的纯异步server的实现也是有问题的，达到max_request极值的最后一个请求，是无法得到响应。韩大神，有什么解决方案，或哪个版本可以支持到异步？

**Comment by haytoo1** [comment]
同等解决办法。

**Comment by matyhtf** [comment]
底层确实尝试了支持异步reload，但是过于复杂还是会存在问题，可以在worker进程内监听信号，自行实现异步Worker进程的重启。
