### ISSUE TITLE
M1  mach-o, but wrong architecture

### ISSUE THREAD

**Issue by shuliangfu** [swoole/swoole-src#4161]
dreamer@192 20170718 % ll
total 8808
-rw-r--r--  1 root  admin  1800935  1 26 19:13 mongodb.so
-rw-r--r--  1 root  admin  2705328  4 21 21:18 swoole.so
dreamer@192 20170718 % php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /opt/homebrew/lib/php/pecl/20170718/swoole.so (dlopen(/opt/homebrew/lib/php/pecl/20170718/swoole.so, 9): no suitable image found.  Did find:
	/opt/homebrew/lib/php/pecl/20170718/swoole.so: mach-o, but wrong architecture
	/opt/homebrew/lib/php/pecl/20170718/swoole.so: mach-o, but wrong architecture), /opt/homebrew/lib/php/pecl/20170718/swoole.so.so (dlopen(/opt/homebrew/lib/php/pecl/20170718/swoole.so.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /opt/homebrew/lib/php/pecl/20170718/swoole.so (dlopen(/opt/homebrew/lib/php/pecl/20170718/swoole.so, 9): no suitable image found.  Did find:
	/opt/homebrew/lib/php/pecl/20170718/swoole.so: mach-o, but wrong architecture
	/opt/homebrew/lib/php/pecl/20170718/swoole.so: mach-o, but wrong architecture), /opt/homebrew/lib/php/pecl/20170718/swoole.so.so (dlopen(/opt/homebrew/lib/php/pecl/20170718/swoole.so.so, 9): image not found)) in Unknown on line 0
PHP 7.2.34 (cli) (built: Dec 15 2020 20:10:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.34, Copyright (c) 1999-2018, by Zend Technologies

**Comment by matyhtf** [comment]
Your php may be of x86 architecture, please compile swoole on x86 platform, then copy swoole.so to your machine

**Comment by shuliangfu** [comment]
No, no, my computer is the latest Apple M1

**Comment by siwazeng** [comment]
请问你解决了问题了吗？能请求一下解决方法吗

**Comment by JackSeven** [comment]
> Your php may be of x86 architecture, please compile swoole on x86 platform, then copy swoole.so to your machine

M1 遇到楼主同样的问题，手动make安装即可，解决如下：
背景：
1，php7.4。pecl install swoole 失败，brew安装 openssl，提示路径ssl等路径找不到错误。
2，换编辑安装，编译指定ssl参数就行了。

编译：
./configure --with-php-config=/opt/homebrew/opt/php@7.4/bin/php-config --enable-sockets=yes --enable-openssl=yes --with-openssl-dir=/opt/homebrew/opt/openssl@1.1 --enable-http2=yes --enable-mysqlnd=yes --enable-swoole-json=yes --enable-swoole-curl=yes

**Comment by JackSeven** [comment]
> Your php may be of x86 architecture, please compile swoole on x86 platform, then copy swoole.so to your machine

M1 遇到楼主同样的问题，手动make安装即可，解决如下：
背景：
1，php7.4。pecl install swoole 失败，brew安装 openssl，提示路径ssl等路径找不到错误。
2，换编辑安装，编译指定ssl参数就行了。

编译：
./configure --with-php-config=/opt/homebrew/opt/php@7.4/bin/php-config --enable-sockets=yes --enable-openssl=yes --with-openssl-dir=/opt/homebrew/opt/openssl@1.1 --enable-http2=yes --enable-mysqlnd=yes --enable-swoole-json=yes --enable-swoole-curl=yes
