### ISSUE TITLE
If the program opens the coroutine container twice in a row, signal listening fails

### ISSUE THREAD

**Issue by chinawilon** [swoole/swoole-src#4169]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
use PHPUnit\Framework\TestCase;
use Swoole\Process;
use function Co\run;

class SignalTest extends TestCase
{
    /**
     * Test Run once
     */
    public function testRunSignal1(): void
    {
        run(static function (){
            $running = true;
            Process::signal(SIGUSR1, function() use(&$running) {
                $running = false;
                echo 'sigusr1 one'.PHP_EOL;
            });
            go(static function () use(&$running) {
                while ($running) {
                    sleep(1);
                }
            });
        });
    }

    /**
     * Test Run Twice
     */
    public function testRunSignal2(): void
    {
        run(static function (){
            Process::signal(SIGUSR1, function(){
                echo 'sigusr1 one'.PHP_EOL;
            });
        });
        run(static function (){
            $running = true;
            Process::signal(SIGUSR1, function() use(&$running) {
                $running = false;
                echo 'sigusr1 twice'.PHP_EOL;
            });
            go(static function () use(&$running) {
                while ($running) {
                    sleep(1);
                }
            });
        });
    }
}
```

2. What did you expect to see?
The test case TestRunSignal2 cannot listen for a signal

3. What did you see instead?
⬆️

4. What version of Swoole are you using (show your `php --ri swoole`)?
# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.5
Built => Apr  9 2021 15:28:41
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1k  25 Mar 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
# uname -a
Linux 3aed3db17385 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 Linux

# php -v
PHP 7.4.16 (cli) (built: Apr  1 2021 16:06:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/pull/4170
