### ISSUE TITLE
Static compile with php一些参数问题

### ISSUE THREAD

**Issue by crazywhalecc** [swoole/swoole-src#4173]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
在把swoole放入ext/和php一起编译的时候，发现参数列表的文档以及编译选项不够全。

首先这样的情况无法控制比如 `--enable-http2` 这几个参数。目前最新的 git 版本我只找到了 `coverage, json, dev` 等这几个enable的选项，且官方文档并无具体说明。

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by matyhtf** [comment]
可以控制这些参数，使用方法与单独编译 swoole 的一致
