### ISSUE TITLE
Bug in http server

### ISSUE THREAD

**Issue by pradeepsingh01** [swoole/swoole-src#4177]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
i created a reverse proxy server by using swoole http server and swoole http client, it works fine but sometime it throws segmentation fault. 

2. What did you expect to see?
http server should keep running without throwing error.

3. What did you see instead?
WARNING wait: worker#0 abnormal exit, status=0, signal=11

4. What version of Swoole are you using (show your `php --ri swoole`)?
v4..6.5

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux ip-172-31-16-59 5.4.0-1045-aws #47~18.04.1-Ubuntu SMP Tue Apr 13 15:58:14 UTC 2021 x86_64 x86_64 x86_64 
GNU/Linux

PHP 7.2.24-0ubuntu0.18.04.7 (cli) (built: Oct  7 2020 15:24:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.2.24-0ubuntu0.18.04.7, Copyright (c) 1999-2018, by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by sy-records** [comment]
provide a simple script for reproducing the error.

**Comment by matyhtf** [comment]
```shell
USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php
```

**Comment by pradeepsingh01** [comment]
Yesterday i increased ram on server to 8GB (its AWS instance) and also changed few settings
worker_num - 20
max_request - 5000
Since then i have not seen any crash.

Earlier also this error was coming occasionally. most of the time it worked smoothly.

What i m doing is
its  a simple reverse proxy server. i m running a http server which accepts the request
and then using swoole http client i forward that request to application server and get the response
then return this response.

**Comment by pradeepsingh01** [comment]
currently it is working fine, since i increased resources in server.
