### ISSUE TITLE
Swoole\ExitException getFlags 在http/server中使用的 返回值与文档不一致

### ISSUE THREAD

**Issue by hbbzy** [swoole/swoole-src#4181]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
在尝试使用swoole http server时，我使用Swoole\ExitException获取  exit 退出时所处的环境信息掩码。发现打印的getFlags()
的值与文档描述的并不一致：
```php
<?php
$http = new Swoole\Http\Server('127.0.0.1', 9501);

$http->on('start', function ($server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$http->on('request', function ($request, $response) {
    try {
        exit(123);
        $response->header('Content-Type', 'text/plain');
        $response->end('Hello World');
    } catch (\Swoole\ExitException $e) {
        var_dump($e->getFlags());
        var_dump('SWOOLE_EXIT_IN_COROUTIME:' . SWOOLE_EXIT_IN_COROUTINE);
        var_dump('SWOOLE_EXIT_IN_SERVER:' . SWOOLE_EXIT_IN_SERVER);
    }
});

$http->start();
```

2. What did you expect to see?
我希望能得到和文档一致的结果，即$e->getFlags() === SWOOLE_EXIT_IN_COROUTINE，然而实际并不是。
我期望能明白这个现象的原因，是swoole的bug还是文档是过时的。

3. What did you see instead?
实际$e->getFlags() 的值是6.

4. What version of Swoole are you using (show your `php --ri swoole`)?
`swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.6
Built => Apr 25 2021 07:11:14
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1i  8 Dec 2020
dtls => enabled
http2 => enabled
json => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608`

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
`Linux ubuntudev 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

`PHP 7.3.27-7+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Feb 19 2021 15:41:31) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-7+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies`

`Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)`

**Comment by sy-records** [comment]
6 应该是表示在Server的协程环境中退出，回调是自动创建协程的，你可以通过设置关闭

```php 
$http->set(['enable_coroutine' => false]);
```

**Comment by hbbzy** [comment]
谢谢。
我使用\Swoole\ExitException 的本意是通过一种手段确定当前所属环境是在Server还是协程中。
由于getFlags的值和文档不一致导致了我的困扰，我阅读了\Swoole\ExitException的源码，\Swoole\ExitException的flags的常量值只有SWOOLE_EXIT_IN_COROUTINE和SWOOLE_EXIT_IN_SERVER。在flags不仅仅是SWOOLE_EXIT_IN_COROUTINE和SWOOLE_EXIT_IN_SERVER的情况下，有没有办法提供一下flags的列表，或者别的手段确定退出的环境

**Comment by twose** [comment]
http://wiki.swoole.com/#/coroutine/coroutine?id=getcid
