### ISSUE TITLE
How to exit swoole safely using Ctrl+C / 如何用Ctrl+C安全地退出Swoole

### ISSUE THREAD

**Issue by crazywhalecc** [swoole/swoole-src#4186]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Swoole 文档中提到了给 Master 进程发送 SIGTERM 可以安全地按照正常流程退出服务器，但是如果使用键盘的 Ctrl+C 就不可以了。

按照我的理解，正常发送 SIGTERM 关闭的流程：
- Master 通知 Manager 要关了
- Manager 通知 Worker 要关了
- 如果 Worker 还忙就 `onWorkerExit()`，关闭后执行 `onWorkerStop()`
- Manager 执行 `onManagerStop()`
- 最后一切都关闭后 Master 执行 `onShutdown()`

如果正常未做任何进程的干预（比如使用 `Process::signal()` 等方式监听信号），使用 Ctrl+C 是这样的：
- Master，Manager，Worker，TaskWorker 都在同一时间内直接全部退出，无任何回调
- 进程内所有的常驻内存的数据未经保存丢失

我找到一种解决办法，但是比较别扭且需要外部依赖：
- `onStart` 事件中使用 `Process:signal(SIGINT)` 监听 Ctrl+C 信号，然后使用 `Process::kill($master_pid, SIGTERM)` 强制让 Swoole 走正常流程
- `onManagerStart` 中使用 `pcntl_signal(SIGINT)` 并回调中不执行任何其他代码，只输出 log（这么做的原因是 Manager 进程不支持使用 `Process::signal()`，同时如果不监听 Manager 的 SIGINT 信号的话 Ctrl+C 会让 Worker 进程变成僵尸进程）
- `onWorkerStart` 中使用 `Process::signal(SIGINT)` 并回调中不执行任何其他代码

同时为了让每次使用 `server->reload()` 或向 Master 进程发送 SIGUSR1 的方法重载 Worker 进程也达到同样安全地存储 Worker 内的数据，做了以下工作：
- `onWorkerStart` 中使用 `Process::signal(SIGUSR1)`，回调内杀掉所有计时器、被手动 `suspend` 的协程和连接
- `onBeforeReload` 使用 `Process::kill(worker{i}_pid, SIGUSR1)`，调用上方的代码，并 sleep 1s 左右

总感觉这样不是很合适的方法，请问有没有更好的方法来让 Ctrl+C 安全地退出？

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by matyhtf** [comment]
你的解决办法是对的。设置 SIGINT 信号处理器有副作用，会影响 gdb 等调试工具。因此底层不对 SIGINT 进行任何处理

**Comment by crazywhalecc** [comment]
> 你的解决办法是对的。设置 SIGINT 信号处理器有副作用，会影响 gdb 等调试工具。因此底层不对 SIGINT 进行任何处理

现在的主要问题是，Manager 进程下需要引入 pcntl 扩展，有没有什么办法不依赖 pcntl 在 Manager 进程阻断 Ctrl+C？
