### ISSUE TITLE
Problem with ioncube and swoole

### ISSUE THREAD

**Issue by pradeepsingh01** [swoole/swoole-src#4187]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
i was executing a script to process some documents. when i run same script in production with ioncube and php7.2 it throws segmentation error.

2. What did you expect to see?
Process should be completed without error

3. What did you see instead?
Segmentation fault
[New LWP 2119]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php crons/cron_fetch_ocr.php'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f69125a23b9 in ?? ()
(gdb) bt
#0  0x00007f69125a23b9 in ?? ()
#1  0x00007f692b62b167 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#2  0x00007f692b62ddcc in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#3  0x00007f692b62f371 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#4  0x00007f692b62b167 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#5  0x00007f692b62ddcc in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#6  0x00007f692b62f371 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#7  0x00007f692b62b167 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#8  0x00007f692b62ddcc in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#9  0x00007f692b62f371 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#10 0x00007f692b62b167 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#11 0x00007f692b62ddcc in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#12 0x00007f692b62f371 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#13 0x00007f692b62b167 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#14 0x00007f692b62ddcc in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#15 0x00007f692b62f371 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#16 0x00007f692b62b167 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#17 0x00007f692b62ddcc in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#18 0x00007f692b62f371 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#19 0x00007f692b62b167 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#20 0x00007f692b62ddcc in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#21 0x00007f692b62f371 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#22 0x00007f692b62b167 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#23 0x00007f692b62ddcc in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#24 0x00007f692b62f371 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#25 0x00007f692b62b167 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#26 0x00007f692b62ddcc in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#27 0x00007f692b62f371 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#28 0x00007f692b62b167 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#29 0x00007f692b62ddcc in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#30 0x00007f692b62f371 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#31 0x00007f692b62b167 in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#32 0x00007f692b62ddcc in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#33 0x0000556c1e79acac in execute_ex ()
#34 0x00007f691ef3cce8 in tideways_execute_ex () from /usr/lib/php/20170718/tideways.so
#35 0x00007f692b62dcfe in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#36 0x0000556c1e79a99c in execute_ex ()
#37 0x00007f691ef3cce8 in tideways_execute_ex () from /usr/lib/php/20170718/tideways.so
#38 0x00007f692b62dcfe in ?? () from /usr/lib/php/7.2/ioncube_loader_lin_7.2.so
#39 0x00007f691d63fc1c in swoole::PHPCoroutine::main_func (arg=0x7f690d3bcb90) at /usr/src/swoole-src/ext-src/swoole_coroutine.cc:733
#40 0x00007f691d6cfb4d in std::function<void (void*)>::operator()(void*) const (__args#0=0x7f690d3bcb90, this=0x556c1f57d780) at /usr/include/c++/5/functional:2267
#41 swoole::coroutine::Context::context_func (arg=0x556c1f57d780) at /usr/src/swoole-src/src/coroutine/context.cc:141
#42 0x00007f691d73b9c1 in make_fcontext () at /usr/src/swoole-src/thirdparty/boost/asm/make_x86_64_sysv_elf_gas.S:64
#43 0x0000000000000000 in ?? ()

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.6
Built => Apr 25 2021 12:56:47
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1g  21 Apr 2020
dtls => enabled
http2 => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.8
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux ip-172-31-10-166 4.4.0-1067-aws #77-Ubuntu SMP Mon Aug 27 13:22:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.2.34-18+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb 23 2021 15:07:41) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.2.34-18+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)

**Comment by huanghantao** [comment]
This is the encryptor's problem, not Swoole's.

**Comment by pradeepsingh01** [comment]
How it can be encryptor's problem. same encrypted code works in php cli. but when i run with coroutine it throws segmentation fault.

**Comment by huanghantao** [comment]
You should either report the problem back to the IonCube or use the swoole compiler.
