### ISSUE TITLE
表单验证，希望能完善，类似laravel的required_with 

### ISSUE THREAD

**Issue by zhoufei666** [swoole/swoole-src#4201]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

在使用表单验证的时候，我的场景：B、C、D字段的验证规则强烈的依赖A字段，如required 规则
我希望用validate 就能完成这样的工作
2. What did you expect to see?
隔壁框架laravel ,这个表单验证就很完善，希望能在es中用得上

![image](https://user-images.githubusercontent.com/20034765/117786261-e3f0e600-b277-11eb-818a-02291bf168c1.png)

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by sy-records** [comment]
goto https://github.com/easy-swoole/easyswoole
