### ISSUE TITLE
Is this project going to be maintained in next years?

### ISSUE THREAD

**Issue by amfolgar** [swoole/swoole-src#4203]
Hi, this is more a question than an issue.

I'm about to choose this project to implement an API in production. The project looks nice and I'm wondering if it will be maintained in the next years, as I don't know C++ to fix bugs or make improvements on it.

Thanks.

**Comment by sy-records** [comment]
sure, you can see https://github.com/swoole/swoole-src/blob/master/SUPPORTED.md

**Comment by amfolgar** [comment]
Oh great, thank you!
