### ISSUE TITLE
Compile-time Configuration Params Issue

### ISSUE THREAD

**Issue by fakharak** [swoole/swoole-src#4205]
1. What did you do? If possible, provide a simple script for reproducing the error.
After cloning, I ran:
./configure --enable-openssl --enable-sockets --enable-http2 --enable-mysqlnd --enable-swoole-json --enable-swoole-curl --enable-swoole-debug --enable-swoole-trace --enable-openssl --enable-async-redis --enable-timewheel --enable-ringbuffer

2. What did you expect to see?
Expected all params to work but got warning as mentioned below:

3. What did you see instead?
At the end of configuration, i get:

configure: WARNING: unrecognized options: --enable-swoole-debug, --enable-swoole-trace, --enable-async-redis, --enable-timewheel, --enable-ringbuffer

4. What version of Swoole are you using (show your `php --ri swoole`)?
Latest as i am cloning from:
https://github.com/swoole/swoole-src.git

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

PHP 8.0.5
Ubuntu 18.04
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by sy-records** [comment]
see https://github.com/swoole/swoole-src/blob/master/config.m4

```diff
- --enable-swoole-debug --enable-swoole-trace
+ --enable-debug-log --enable-trace-log
```

These were removed `--enable-async-redis, --enable-timewheel, --enable-ringbuffer`
