### ISSUE TITLE
Installation Issue: recipe for target 'ext-src/swoole_curl.lo' failed

### ISSUE THREAD

**Issue by fakharak** [swoole/swoole-src#4206]
1. What did you do? If possible, provide a simple script for reproducing the error.

Used command below:
pecl install -D 'enable-sockets="no" enable-openssl="yes" enable-http2="yes" enable-mysqlnd="yes" enable-swoole-json="no" enable-swoole-curl="yes"' swoole

2. What did you expect to see?

Succesful installation.

3. What did you see instead?
The installation ends up on: 

In file included from /tmp/pear/temp/swoole/ext-src/swoole_curl.cc:17:0:
/tmp/pear/temp/swoole/ext-src/php_swoole_curl.h:25:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:229: recipe for target 'ext-src/swoole_curl.lo' failed
make: *** [ext-src/swoole_curl.lo] Error 1
ERROR: `make' failed

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole-4.6.6

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

-- Ubuntu 18.04
-- PHP 8.0.5
-- gcc version 7.5.0

**Comment by fakharak** [comment]
This solved the issue: 
sudo apt-get install libcurl4-openssl-dev

**Comment by sy-records** [comment]
1. #include <curl/curl.h>

```bash
sudo apt-get install libcurl4-openssl-dev
```

2. You need to load the curl extension before the swoole extension

**Comment by fakharak** [comment]
Thanks. You have identified the root cause correctly as i have tested by updating php.ini.

But i want to mention that i do not have anything like below after installation
/etc/php/7.2/cli/conf.d/XY-swoole.ini

Therefore, at the time of writing i tested by enabling curl in php.ini which worked (I think which is to test the solution only, but not a preferred approach)


After resolving curl_ce, i got "undefined symbol: socket_ce" in error message, so i uncommented socket extensin in php.ini which worked but as socket is also loading from mod_available therefore, i get:

PHP Warning:  Module "curl" is already loaded in Unknown on line 0
PHP Warning:  Module "sockets" is already loaded in Unknown on line 0

I am now working on 

A) Create XY-swoole.ini (like, 60-swoole.ini) inside /etc/php/7.2/cli/conf.d/
B) execute:
    ln -s  /etc/php/7.2/mods-available/swoole.ini /etc/php/7.2/cli/conf.d/20-swoole.ini 
C) Close / Comment /disable extensions "socket" and "curl" in /etc/php/8.0/cli/php.ini

Swoole is great, i further appreciate if future release may automate that process.

Great thanks.

**Comment by fakharak** [comment]
In order to execute three steps mentioned below, using bash (cli) ... 
A) Create XY-swoole.ini (like, 60-swoole.ini) inside /etc/php/8.0/cli/conf.d/
B) execute:
ln -s /etc/php/7.2/mods-available/swoole.ini /etc/php/7.2/cli/conf.d/60-swoole.ini
C) Close / Comment /disable extensions "socket" and "curl" in /etc/php/8.0/cli/php.ini

I performed actions below in bash:

sudo chmod g+rw- 
sudo chmod g+rw- conf.d /etc/php/8.0/mods-available
sudo printf "; configuration for swoole module\n; priority=60\nextension=swoole.so" > /etc/php/8.0/mods-available/swoole.ini
ln -s  /etc/php/8.0/mods-available/swoole.ini /etc/php/8.0/cli/conf.d/60-swoole.ini
sudo chmod g+r-w+x conf.d
cd /etc/php/8.0
sudo chmod g+r-w+x mods-available

- Add Run-time Configurations in php.ini
swoole.enable_preemptive_scheduler

Let me know if there is a better way. (I missed out taking default permissions of "mod-available" folder) so i sppreciate if these are provided.
Thanks
