### ISSUE TITLE
missing CURLOPT_RESOLVE  on curl hook

### ISSUE THREAD

**Issue by ermya** [swoole/swoole-src#4219]
it seems CURLOPT_RESOLVE is missing in SWOOLE_HOOK_CURL

PHP Fatal error:  Uncaught Swoole\Curl\Exception: swoole_curl_setopt(): option[10203] is not supported in @swoole-src/library/core/Curl/Handler.php:622
Stack trace:
#0 @swoole-src/library/core/Curl/Handler.php(158): Swoole\Curl\Handler->setOption()
#1 @swoole-src/library/ext/curl.php(21): Swoole\Curl\Handler->setOpt()
#2 [internal function]: swoole_curl_setopt()
#3 /swooleTest/test.php(36): curl_setopt()
#4 {main}
  thrown in @swoole-src/library/core/Curl/Handler.php on line 622

do you have any plan to add it ?

**Comment by sy-records** [comment]
You can use a higher version of the Swoole extension, Use [SWOOLE_HOOK_NATIVE_CURL](https://www.swoole.co.uk/docs/runtime-hooks/swoole-hook-native-curl) instead of SWOOLE_HOOK_CURL

**Comment by ermya** [comment]
Yes, but unfortunately SWOOLE_HOOK_NATIVE_CURL is not suitable for use inside coroutine

**Comment by sy-records** [comment]
Why not?

**Comment by ermya** [comment]
Based on the tests I have done, it seems it will block coroutine on I/O

**Comment by sy-records** [comment]
No, it supports coroutine.

show your `php --ri swoole`

**Comment by ermya** [comment]
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7
Built => May 17 2021 19:07:58
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by ermya** [comment]
I tested it with this piece of code:
`
<?php

Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_NATIVE_CURL);
//Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_CURL);

use Swoole\Coroutine as Co;

Co\run(function() {
    $url = 'http://google.com';
    //foreach ($rows as $row) {
    for ($i = 0; $i < 50; $i++) {
        go(function() use($url, $i) {
            echo $i . PHP_EOL;

            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            //curl_setopt($ch, CURLOPT_HTTPHEADER, $headerArray);
            curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
            //curl_setopt($ch, CURLOPT_DNS_USE_GLOBAL_CACHE, false);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            //curl_setopt($ch, CURLOPT_RESOLVE, $resolveArr);
            curl_setopt($ch, CURLOPT_TIMEOUT, 70);
            curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 50);
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            $response = curl_exec($ch);
        });
    }
});
`
you can test with both version and check the output result

**Comment by sy-records** [comment]
You need to recompile swoole, add --enable-swoole-curl option to compile.

see https://www.swoole.co.uk/docs/get-started/installation
