### ISSUE TITLE
swoole接口响应慢，很多epoll_wait

### ISSUE THREAD

**Issue by cs686** [swoole/swoole-src#4223]
Please answer these questions before submitting your issue. Thanks!

使用 strace 跟踪很多epoll_wait，接口响应慢，求教如何处理

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.7.0-dev
Built => May 18 2021 22:45:53
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

![image](https://user-images.githubusercontent.com/11469578/118683721-3318b700-b834-11eb-94fb-376e02149983.png)

**Comment by matyhtf** [comment]
这与epoll_wait 无关，请跟踪你的 worker 进程
