### ISSUE TITLE
When using http proxy provided by luminati.io, the response body is not in english language

### ISSUE THREAD

**Issue by odrads** [swoole/swoole-src#4224]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
using Swoole\Coroutine\Http\Client with proxy settings:
[
'http_proxy_host' => [luminati proxy host],
'http_proxy_port' => [luminati proxy port],
'http_proxy_user' => [luminati provided username],
'http_proxy_password' => [luminati provided password]
]

2. What did you expect to see?
["body"]=>
  string(134) "{"responseCode":0,"responseMessage":"Success","success":true}"

3. What did you see instead?
["body"]=>
  string(131) "�V*J-.��+Nu�OIU�2Ё
                                 �'�Ŕ�K���%�b(˪��4UG)7�(;�$85'5�$3?�3E���������$Y�Z�dedld4673�54�Q�OI)v�/�M,i1�Gl�Q�"

4. What version of Swoole are you using (show your `php --ri swoole`)?
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7-dev
Built => May 13 2021 14:01:11
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
dtls => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux  4.19.0 #1 SMP Tue Jun 9 12:58:54 MSK 2020 x86_64 GNU/Linux
PHP 7.4.2 (cli) (built: Feb  1 2020 19:33:30) ( NTS )
gcc version 8.3.0 (Debian 8.3.0-6)

**Comment by matyhtf** [comment]
Missing zlib library, Try disable http compression, or install zlib-dev and recompile swoole.

```php
$client->setHeaders(['Accept-Encoding' => null, ]);
```
