### ISSUE TITLE
master和worker进程内存占用问题

### ISSUE THREAD

**Issue by DlenoDing** [swoole/swoole-src#4225]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
worker进程都只有1个
在docker内运行（alpine3.12）,之前主机有8G内存，在主机上运行了接近20个docker，docker内都是运行的swoole,
看了下每个docker内的master和worker基本初始要占用250-300M内存，这个时候内存占用达到80%多了。
然后给主机升级了内存到16G，这个时候再看，每个docker内的master和worker基本初始却变成占用350-450M内存了。
这是个什么情况呢，进程初始占用的内存会根据系统总内存去动态分配吗？能否设置让进程初始占用内存最小？（没看到文档上有相关的东西）

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7
Built => May 17 2021 12:50:31
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1k  25 Mar 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux 12a2752fcb04 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 Linux
PHP 7.4.14 (cli) (built: Apr 12 2021 19:57:51) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies

**Comment by matyhtf** [comment]
虚拟内存还是物理内存，请贴出详细的 ps 命令输出内容
