### ISSUE TITLE
aws/aws-sdk-php using swoole shows error / Aws S3上传组件使用Swoole时报错

### ISSUE THREAD

**Issue by crazywhalecc** [swoole/swoole-src#4226]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
- 引入 `composer require aws/aws-sdk-php`
- 使用 `Runtime::enableCoroutine(true, SWOOLE_HOOK_ALL);`
- 使用 S3Client，连接 Minio，代码如下：
```php
go(function(){
    $s3 = new Aws\S3\S3Client([
        "version" => 'latest',
        "region" => "cn-north-1",
        "endpoint" => "http://127.0.0.1:8080",
        "use_path_style_endpoint" => true,
        "credentials" => [
            "key" => "My Key",
            "secret" => "My Secret"
        ]
    ]);
    echo "Client AWS success.".$s3->getEndpoint().PHP_EOL;
    $file_name = uuidgen().".jpg"; // Just for generating a uuid name, can be replaced
    var_dump($s3->putObject([
        "Bucket" => "test1",
        "Key" => $file_name,
        "Body" => file_get_contents("/tmp/shaozi.jpg")
    ]));
    echo "路径：".$s3->getObjectUrl('test1', $file_name).PHP_EOL;
});
```
- Minio 是最新的从 Docker 启动的，创建了个 test1 的容器

2. What did you expect to see?
正常的话会输出 `路径：http://xxxxxxxx/yyyyy`，上传成功

3. What did you see instead?
上传失败，显示如下报错
![image](https://user-images.githubusercontent.com/20330940/118770940-7d417d00-b8b4-11eb-9aaa-1fd2cc554673.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?
![image](https://user-images.githubusercontent.com/20330940/118770969-86cae500-b8b4-11eb-97c4-9660fea21693.png)

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
PHP 8.0.5 NTS，使用 pecl 安装的 swoole。

根据进一步测试，发现可能是 Swoole 的 `SWOOLE_HOOK_CURL` 导致的问题。在启动框架之前，使用的语句改为 `Runtime::enableCoroutine(true, SWOOLE_HOOK_ALL & (~SWOOLE_HOOK_CURL))` 没有问题，可以上传了，可能是 Hook 了 curl 导致一系列的问题。

服务器之前上面装的是旧版本的 Swoole，HOOK_ALL 没有自动 Hook curl，所以一直没啥问题，今天更新了 Swoole 版本发现 Aws S3 不能正常工作了。

**Comment by sy-records** [comment]
高版本 Swoole 可以在编译的时候打开`--enable-swoole-cur`l参数，使用`SWOOLE_HOOK_NATIVE_CURL`。
