### ISSUE TITLE
task在工作的时候， kill -15 主进程pid 无法停止程序

### ISSUE THREAD

**Issue by peterxiemin** [swoole/swoole-src#423]
PHP 5.5.25 (cli) (built: Dec  3 2015 21:51:01) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

swoole 版本 1.7.21 stable

程序很简单：
 worker_num = 8
 task_num  = 8
 用户请求-》worker 进程  =》task 进程 (sleep 10) =》 worker进程 =》用户
 
我用ab压力测试的时候， kill -15 主进程id 无法停止
这个现象正常吗？

**Comment by matyhtf** [comment]
正常，shutdown需要等待所有子进程结束。
