### ISSUE TITLE
\Swoole\Process\Pool::getProcess  方法在某个子进程重启后，获取到的对象不对

### ISSUE THREAD

**Issue by yunwuxin** [swoole/swoole-src#4231]
## 问题一
使用\Swoole\Process\Pool创建两个子进程A、B 
A进程退出重启后，B中通过\Swoole\Process\Pool::getProcess($workerId)获取A进程的对象还是旧的(A进程重启前已经获取过一次)
直到B进程也退出重启后才能正确获取到
应该是 单例 模式造成的

---
## 问题二
在上面B进程中向主进程发送SIGUSR1信号
A、B中都监听了SIGTERM信号，A进程执行了exit方法退出了进程并自动重启，B进程没做任何操作，进程没退出
然后B进程继续向主进程发送SIGUSR1信号
这时只有B进程会收到SIGTERM信号，重启后的A进程不会收到SIGTERM信号了
这个是设计如此吗

**Comment by matyhtf** [comment]
感谢你的反馈。

问题1，可以通过清理 `$pool->workers[]`属性，清理掉单例的对象。“对象还是旧的” 这里没有理解，`Process`对象不是进程退出就销毁了，一个`Process`对象包含管道、消息队列、进程 PID 等多个信息，进程 PID 是可以变化的。

这里是否可以理解为是 `PID` 未能更新？

问题2
请给出一个演示的 demo

**Comment by yunwuxin** [comment]
问题1
A进程重启后，B进程中通过getProcess获取到的Process的PID  没有更新    还是A进程之前的PID

**Comment by yunwuxin** [comment]
demo 代码如下
```
<?php

use Swoole\Constant;

$pool = new \Swoole\Process\Pool(2, SWOOLE_IPC_UNIXSOCK, null, true);

$pool->on(Constant::EVENT_WORKER_START, function (\Swoole\Process\Pool $pool, $workerId) {
    if ($workerId === 0) {
        //A进程
        var_dump('A 进程启动,PID:' . $pool->getProcess()->pid);
        Swoole\Process::signal(SIGTERM, function () use ($pool) {
            var_dump('A SIGTERM');
            //主进程受到SIGUSR1信号后，会向子进程发送SIGTERM信号
            //A进程退出，然后会自动重启
            $pool->getProcess()->exit();
        });
        while (true) {
            Co::sleep(2);
        }
    } else {
        //B进程
        var_dump('B 进程启动,PID:' . $pool->getProcess()->pid);
        Swoole\Process::signal(SIGTERM, function () {
            //不做任何处理,B进程不会退出
            var_dump('B SIGTERM');
        });
        while (true) {
            var_dump('A pid:' . $pool->getProcess(0)->pid);
            //向主进程发送SIGUSR1信号，让他的子进程重启
            \Swoole\Process::kill($pool->master_pid, SIGUSR1);
            Co::sleep(2);
        }
    }
});
$pool->start();


```
输出如下
![image](https://user-images.githubusercontent.com/2168125/119215442-5081a580-bb00-11eb-99e8-866919b25f8e.png)


可以看到A进程重启后就不会再收到SIGTERM信号了，
B进程中获取到的A进程的PID也一直是第一次的

**Comment by matyhtf** [comment]
进程 PID 更新的问题已解决。

**Comment by matyhtf** [comment]
第二个问题，这里是底层的一个保护机制，如果 reload 时需要重启两个进程，但是其中另外一个进程始终没有退出，那么 reload 动作就不会完成，底层会拒绝执行新的 reload 指令。

除非 B 进程退出，才会接受新的 reload 指令
