### ISSUE TITLE
Adding shared swoole array with supporting built in php array functions.

### ISSUE THREAD

**Issue by XDRiVE888** [swoole/swoole-src#4233]
Can you create an some shared swoole array that can be safely manipulated from any swoole process with built-in php array functions?

P.S. I mean to create some swoole array with shared functionality like a swoole table, but without the need to pre-specify the types of keys, the size of the array, and so on, and as much as possible with support for the functions of the built-in php array.

**Comment by matyhtf** [comment]
If you want to share data between different processes, there are 4 ways:

1. `Swoole\Table`
2. UnixSocket
3. Redis
4. /dev/shm
