### ISSUE TITLE
如何主动关闭某个协程？  比如：一个协程内 websocket连接持续获取数据， 某个时刻连接断了, 需要退出当前协程， 重新开启一个协程获取数据。

### ISSUE THREAD

**Issue by xybingbing** [swoole/swoole-src#4235]
如何主动关闭某个协程？  比如：一个协程内 websocket连接持续获取数据， 某个时刻连接断了, 需要退出当前协程， 重新开启一个新协程获取数据。 如何退出老协程。

**Comment by matyhtf** [comment]
不支持主动关闭协程，你可以设计一种机制，通知老的协程退出
