### ISSUE TITLE
Cant increment receive buffer

### ISSUE THREAD

**Issue by Druid33** [swoole/swoole-src#4237]
Hi,

With [Coroutine\Client](https://www.swoole.co.uk/docs/modules/swoole-coroutine-client) I try to recevie data greater then 65 500bytes. Is there any option to change default value?

Thanks

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
// SERVER
declare(strict_types = 1);

// Create a new server, listening on IP and port
$server = new Swoole\Server('127.0.0.1', 9501);

// Setup the receive event callback function
$server->on('Receive', function ($server, $fd, $reactor_id, $data) {
    $msg = random_bytes(100000);
    echo "Send data length: " . strlen($msg) . "\n";
    $server->send($fd, "Server: {$msg}");
});

// Start the Swoole Server and accept requests
$server->start();
```

```php
<?php
// CLIENT
declare(strict_types = 1);

use function Swoole\Coroutine\go;

go(function () {
    $client = new Swoole\Coroutine\Client(SWOOLE_SOCK_TCP);
    $client->set([
        'package_max_length'    => 2000000,
        'socket_buffer_size'     => 2000000
    ]);

    if (!$client->connect('127.0.0.1', 9501, 0.5)) {
        exit("connect failed. Error: {$client->errCode}\n");
    }
    $client->send("hello world\n");
    $data = $client->recv();
    echo "Received data length: " . strlen($data) . "\n";
    $client->close();
});
```

2. What did you expect to see?

Client should receive 100 000 bytes of data.

3. What did you see instead?

Client receive 65 503 bytes of data.
Set this options has no affect:
```php
$client->set([
        'package_max_length'    => 2000000,
        'socket_buffer_size'     => 2000000
    ]);
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7
Built => May 18 2021 13:11:12
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**bash-5.1$ uname -a**
Linux 5f582379e099 5.4.0-73-generic #82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021 x86_64 GNU/Linux
**bash-5.1$ php -v**
PHP 8.0.6 (cli) (built: May  7 2021 20:48:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.6, Copyright (c) Zend Technologies
**bash-5.1$ gcc -v**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/10.2.1/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-10.2.1_pre1/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 10.2.1_pre1' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,d,objc,go,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.1 20201203 (Alpine 10.2.1_pre1)

**Comment by sy-records** [comment]
No communication protocol set, recv returns up to 64K data. So you need to set the communication protocol, for example:

```php
$server->set(
    [
        'open_length_check' => true,
        'package_length_type' => 'N',
        'package_length_offset' => 0,
        'package_body_offset' => 4,
    ]
);

$client->set(
    [
        'open_length_check' => true,
        'package_length_type' => 'N',
        'package_length_offset' => 0,
        'package_body_offset' => 4,
    ]
);
```

you can see https://www.swoole.co.uk/docs/modules/swoole-coroutine-client-set
![image](https://user-images.githubusercontent.com/33931153/119446373-e74c9d00-bd60-11eb-9608-664161037d03.png)


```php
function tcp_unpack(string $data): string
{
    return substr($data, 4, unpack('N', substr($data, 0, 4))[1]);
}
function tcp_pack(string $data): string
{
    return pack('N', strlen($data)) . $data;
}

// Server
$server = new Swoole\Server('127.0.0.1', 9501);
$server->set(
    [
        'open_length_check' => true,
        'package_length_type' => 'N',
        'package_length_offset' => 0,
        'package_body_offset' => 4,
    ]
);

$server->on('Receive', function ($server, $fd, $reactor_id, $data) {
    $msg = random_bytes(100000);
    $send = tcp_pack($msg);
    echo "Send data length: " . strlen($send) . "\n";
    $server->send($fd, $send);
});

$server->start();

// Client
use Swoole\Coroutine;

Coroutine::create(function () {
    $client = new Swoole\Coroutine\Client(SWOOLE_SOCK_TCP);
    $client->set(
        [
            'open_length_check' => true,
            'package_length_type' => 'N',
            'package_length_offset' => 0,
            'package_body_offset' => 4,
        ]
    );
    
    if (!$client->connect('127.0.0.1', 9501, 0.5)) {
        exit("connect failed. Error: {$client->errCode}\n");
    }
    $client->send(tcp_pack("hello world"));
    $data = $client->recv();
    echo "Received data length: " . strlen($data) . "\n";
    $client->close();
});
```
