### ISSUE TITLE
The configuration of the old version is reporting an error in the new version

### ISSUE THREAD

**Issue by shuliangfu** [swoole/swoole-src#4241]
old version settings
'options' => [
                'host' => '0.0.0.0',
                'port' => 8545,
                'process_name' => "test-socket",
                'open_tcp_nodelay' => true,
                'daemonize' => 1,
                'worker_num' => 1,
                'task_worker_num' => 1,
                'task_max_request' => 0,
                'pidfile' => 'runtime/tmp/socket.pid';,
                'task_tmpdir' => 'runtime/tmp/socket/task',
                'log_file' => 'runtime/logs/socket.log',
                'log_size' => 2048000,
                'client_timeout' => 30,
                'heartbeat_check_interval' => 60,
                'heartbeat_idle_time' => 120,
                'debug' => true,
            ]

The configuration of the old version is reporting an error in the new version, how should I change it? Please write an example with my parameters, thank you

**Comment by sy-records** [comment]
```php
use Swoole\Server\Helper;

function checkOptions(array $options)
{
    if (class_exists(Helper::class)) {
        $constOptions = Helper::GLOBAL_OPTIONS + Helper::SERVER_OPTIONS + Helper::PORT_OPTIONS + Helper::HELPER_OPTIONS;
        foreach ($options as $k => $v) {
            if (!array_key_exists(strtolower($k), $constOptions)) {
                unset($options[$k]);
            }
        }
    }
    return $options;
}

$options = [
    'host' => '0.0.0.0',
    'port' => 8545,
    'process_name' => "test-socket",
    'open_tcp_nodelay' => true,
    'daemonize' => 1,
    'worker_num' => 1,
    'task_worker_num' => 1,
    'task_max_request' => 0,
    'pidfile' => 'runtime/tmp/socket.pid',
    'task_tmpdir' => 'runtime/tmp/socket/task',
    'log_file' => 'runtime/logs/socket.log',
    'log_size' => 2048000,
    'client_timeout' => 30,
    'heartbeat_check_interval' => 60,
    'heartbeat_idle_time' => 120,
    'debug' => true,
];

$setting = checkOptions($options);
var_dump($setting, array_diff($options, $setting));
```

see https://wiki.swoole.com/#/server/setting
