### ISSUE TITLE
taskworker的问题

### ISSUE THREAD

**Issue by iyidan** [swoole/swoole-src#425]
我在使用中遇到两个问题：
1. 往taskworker投递任务，但taskworker未能及时处理，放入缓存区，当reload后，任务丢失
2. 如何判断taskworker满负荷？以防止task会塞满缓存区，导致worker进程发生阻塞

有办法解决吗？谢谢

**Comment by peterxiemin** [comment]
同问

**Comment by ewenlaz** [comment]
投投递到 taskworker 的异步任务会有onFinish回调， 可以处理taskworker 负荷情况， 任务丢失可以自己在发送前将数据写入缓存，告诉task 相应的key 让期取出来处理就可

**Comment by iyidan** [comment]
昨天发现，$serv->stats()里面有个tasking_num，表示正在执行的任务数，应该可以用这个来判断负载情况吧？

**Comment by iyidan** [comment]
当taskworker在执行中被kill掉（或者产生错误退出），tasking_num并不能被正确地减少，所以还是需要自己实现
