### ISSUE TITLE
Call to undefined method Swoole\Server::getSocket()

### ISSUE THREAD

**Issue by Sun-FreePort** [swoole/swoole-src#4255]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I follow the tutorial: https://www.swoole.co.uk/docs/modules/swoole-server-getSocket

我跟随这个教程学习如何“多播”。

I want to "Multi Cast" in UDP server, but when i run server, this error has throw.

当我在 UDP 服务器中尝试“多播”行为，但每当我运行服务器，就会获得这个错误。

2. What did you expect to see?

send message to all online player -- UDP server.

通过 UDP 服务，发送消息给所有的在线玩家。

3. What did you see instead?

Call to undefined method Swoole\Server::getSocket()

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.5.5-alpha

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

WSL2 - Ubuntu 64x;
PHP 7.4.3 - NTS;
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

![20210606205547](https://user-images.githubusercontent.com/19473984/120925126-b0d03400-c709-11eb-835e-dd3a875951bf.png)

**Comment by sy-records** [comment]
编译 Swoole 时需要开启 --enable-sockets 选项 http://wiki.swoole.com/#/server/methods?id=getsocket

**Comment by Sun-FreePort** [comment]
大佬，我看文档上：

> Swoole 内置的 Coroutine\Socket 可以完成大部分事情

是否能使用它完成组播？

**Comment by sy-records** [comment]
可以的
