### ISSUE TITLE
swoole form-data的content-type请求头bug

### ISSUE THREAD

**Issue by SugarShen** [swoole/swoole-src#4261]
gcc版本4.8.5  php版本7.2.31 swoole版本4.6.7  系统centos7
传入form-data参数时，不能正确解析post参数
这样的请求可以访问，content-type中只有一项时可以解析post参数
curl --location --request POST 'http://127.0.0.1:9501' -H 'Content-Type:multipart/form-data;' --form 'token=33333'
当content-type中加入其它信息时解析就会失败
curl --location --request POST 'http://127.0.0.1:9501' -H 'Content-Type:multipart/form-data;charset=UTF-8' --form 'token=33333'
报错 WARNING	http_request_on_body (ERRNO 9010): parse multipart body failed

**Comment by NathanFreeman** [comment]
swoole在multipart/form-data中只支持boundary，具体可以看看multipart/form-data的规范《RFC 1867: Form-based File Upload in HTML》。里面其实就只有boundary这个，没有charset。

**Comment by hhxsv5** [comment]
这个问题有计划兼容吗？

**Comment by matyhtf** [comment]
@hhxsv5 已实现兼容
