### ISSUE TITLE
swoole atomic long 在M1芯片下无反应

### ISSUE THREAD

**Issue by Stitch-June** [swoole/swoole-src#4263]

**Comment by Stitch-June** [comment]
```
<?php
$atomicLong = new Swoole\Atomic\Long();
$atomic = new Swoole\Atomic();

$serv = new Swoole\Server('127.0.0.1', '9501');
$serv->set([
    'worker_num' => 1,
    'log_file' => '/dev/null'
]);
$serv->on("start", function ($serv) {
});
$serv->on("Receive", function () use ($atomic, $atomicLong) {
    echo 'Atomic:' . $atomic->add(1) . PHP_EOL;
    echo 'AtomicLong:' . $atomicLong->add(1) . PHP_EOL;
});
$serv->start();
```

**Comment by Stitch-June** [comment]
![7681FAF8-ADC4-409F-A858-56FC519C0D72](https://user-images.githubusercontent.com/44792981/121772486-38092600-cba8-11eb-82d1-dbf6e626ef21.png)

**Comment by Stitch-June** [comment]
swoole version 4.6.7

**Comment by Stitch-June** [comment]
@sy-records @matyhtf

**Comment by matyhtf** [comment]
移除 `'log_file' => '/dev/null'` 设置，看一下有什么错误信息

**Comment by Stitch-June** [comment]
![截屏2021-06-21 下午9 38 26](https://user-images.githubusercontent.com/44792981/122771559-237c0a80-d2d9-11eb-9bcf-c99578d32065.png)

**Comment by matyhtf** [comment]
signal=10 是 SIGBUS，可能存在异常的内存操作。可能在 m1 平台下 AtomicLong 指令有一些特殊限制，我们确认一下

**Comment by Stitch-June** [comment]
谢谢

**Comment by dixyes** [comment]
arm64 linux复现

arm64下的gcc `__sync_add_and_fetch`实现要求传入指针对齐导致此问题

复现代码
```php
<?php
$atomicLong = new Swoole\Atomic\Long();
var_dump($atomicLong->add(1));
```

可能的解决方案：

1. 要求allocator返回地址都对齐到SW_DEFAULT_ALIGNMENT
2. 在atomic和atomiclong实现中进行对齐
