### ISSUE TITLE
swoole HTTP服务器控制http请求转发到哪个worker进程处理

### ISSUE THREAD

**Issue by dongzitai** [swoole/swoole-src#4264]
请教一下 swoole HTTP服务器能否控制将http请求转发到哪些worker下处理，或者不转发到某些worker下处理？

**Comment by matyhtf** [comment]
可设置 dispatch_func 或者 dispatch_mode 控制任务投递逻辑

**Comment by dongzitai** [comment]
> 可设置 dispatch_func 或者 dispatch_mode 控制任务投递逻辑

感谢
