### ISSUE TITLE
taskworker假死，一直处于read状态

### ISSUE THREAD

**Issue by iyidan** [swoole/swoole-src#427]
程序版本：
docker+php5.4+swoole1.7.21-stable

调用栈如下：
(gdb) bt
#0  0x00007fd0b7fcad2d in read () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fd0a8656bad in read (__nbytes=8192, __buf=0x7fff7657d008, __fd=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/unistd.h:45
#2  swProcessPool_worker_loop (pool=0x7fd0a78081c0, worker=0x7fd0a780a648) at /usr/local/src/swoole-src-swoole-1.7.21-stable/src/network/ProcessPool.c:310
#3  0x00007fd0a865759b in swProcessPool_spawn (worker=0x7fd0a780a648) at /usr/local/src/swoole-src-swoole-1.7.21-stable/src/network/ProcessPool.c:234
#4  0x00007fd0a86576f9 in swProcessPool_start (pool=0x7fd0a78081c0) at /usr/local/src/swoole-src-swoole-1.7.21-stable/src/network/ProcessPool.c:106
#5  0x00007fd0a865da22 in swManager_start (factory=0x304a300) at /usr/local/src/swoole-src-swoole-1.7.21-stable/src/network/Manager.c:138
#6  0x00007fd0a864c5b4 in swFactoryProcess_start (factory=0x304a300) at /usr/local/src/swoole-src-swoole-1.7.21-stable/src/factory/FactoryProcess.c:86
#7  0x00007fd0a8653a31 in swServer_start (serv=0x3049dd0) at /usr/local/src/swoole-src-swoole-1.7.21-stable/src/network/Server.c:586
#8  0x00007fd0a862f50f in zif_swoole_server_start (ht=<optimized out>, return_value=0x7fd0a77456d8, return_value_ptr=<optimized out>, this_ptr=<optimized out>,
    return_value_used=<optimized out>) at /usr/local/src/swoole-src-swoole-1.7.21-stable/swoole_server.c:2006
#9  0x00007fd0b7d84552 in xdebug_execute_internal (current_execute_data=0x7fd0ba8db4e0, return_value_used=0) at /build/buildd/xdebug-2.2.3/build-php5/xdebug.c:1547
#10 0x000000000074eaa1 in ?? ()
#11 0x000000000070858f in execute ()
#12 0x00007fd0b7d840d2 in xdebug_execute (op_array=0x7fd0ba911e70) at /build/buildd/xdebug-2.2.3/build-php5/xdebug.c:1435
#13 0x000000000074f1de in ?? ()
#14 0x000000000070858f in execute ()
#15 0x00007fd0b7d840d2 in xdebug_execute (op_array=0x7fd0ba911838) at /build/buildd/xdebug-2.2.3/build-php5/xdebug.c:1435
#16 0x000000000074f1de in ?? ()
#17 0x000000000070858f in execute ()
#18 0x00007fd0b7d840d2 in xdebug_execute (op_array=0x7fd0ba90e688) at /build/buildd/xdebug-2.2.3/build-php5/xdebug.c:1435
#19 0x00000000006a7648 in zend_execute_scripts ()
#20 0x00000000006468d3 in php_execute_script ()
#21 0x0000000000750d1f in ?? ()
#22 0x000000000042d337 in ?? ()
#23 0x00007fd0b81fa76d in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#24 0x000000000042d3cd in _start ()

(gdb) f 2
#2  swProcessPool_worker_loop (pool=0x7fd0a78081c0, worker=0x7fd0a780a648) at /usr/local/src/swoole-src-swoole-1.7.21-stable/src/network/ProcessPool.c:310
310	            n = read(worker->pipe_worker, &out.buf, sizeof(out.buf));

**Comment by matyhtf** [comment]
read状态不是正常的吗？

**Comment by iyidan** [comment]
恩，我分析错了
貌似是worker处理函数中有error错误产生，导致tasking_num没有减少，而我的worker又根据tasking_num来判断负载情况，就没有投递出任务
swoole能不能在task出错的时候也能正常维护tasking_num呢？
-------------
PHP Error[8]: Undefined index: noexists

**Comment by matyhtf** [comment]
index 的问题已经在新版本中修复了。strace进程在阻塞read是符合预期的。
