### ISSUE TITLE
如何消除server端警告

### ISSUE THREAD

**Issue by liulangzhe** [swoole/swoole-src#428]
swoole-src-swoole-1.7.21-stable    PHP 5.6.9  
server 一直报警告，可能是client send数据量有关，
$ss = range(0,100000,1);
if (!$client->send(json_encode($ss))){
    die("send failed.");
}

WARN    swReactorEpoll_set#200: reactor#1->set(fd=13|type=0|events=5) failed. Error: No such file or directory[2].

**Comment by matyhtf** [comment]
请发给我一个可以稳定复现的demo
