### ISSUE TITLE
How to enable all flags, except  `SWOOLE_HOOK_NATIVE_CURL` and `SWOOLE_HOOK_CURL` ?

### ISSUE THREAD

**Issue by ttodua** [swoole/swoole-src#4280]
How to enable all flags, except  `SWOOLE_HOOK_NATIVE_CURL` and `SWOOLE_HOOK_CURL` ?
When I try: 
```
$swooleHooks = \Swoole\Runtime::getHookFlags();  
if (!empty($swooleHooks)) \Swoole\Runtime::setHookFlags( $swooleHooks - SWOOLE_HOOK_NATIVE_CURL - SWOOLE_HOOK_CURL );
```
it shows:
` Swoole\Runtime::setHookFlags(): cannot enable both hooks HOOK_NATIVE_CURL and HOOK_CURL at same time `

**Comment by sy-records** [comment]
```php
\Swoole\Runtime::setHookFlags( SWOOLE_HOOK_ALL ^ SWOOLE_HOOK_CURL ^ SWOOLE_HOOK_NATIVE_CURL );
```

**Comment by ttodua** [comment]
That is not correct. The reason is that,  because in my above example, I showed that the script does not know what flags are set, and gets  them using `\Swoole\Runtime::getHookFlags();` and after that, it should disable `curl` (if it was in the flags already, it if was not in enabled flags, then it mistakenly enables it).  So, to ensure failsafe approach,   you might need to implement a method named `\Swoole\Runtime::disableHookFlags( ...smth..)` , so, when one script (i.e. `example.php` ) turns on specific flags, and then `second-script.php` want to disable only `curl` , it could do the following "fail-safe" way:

```
$swooleHooks = \Swoole\Runtime::getHookFlags(); 
\Swoole\Runtime::disableHookFlags( SWOOLE_HOOK_CURL); // So, in case if HOOK_CURL was enabled, it disables. If HOOK_CURL was not enabled, nothing happens
....
....
// run your codes here, i.e. native php curl
....
....

\Swoole\Runtime::setHookFlags($swooleHooks); 

```

so, as you see from example, you can have a robust, fail-safe way to disable only specific flag when executing your custom functions, without affecting the global scope (because, if you use your example  `\Swoole\Runtime::setHookFlags( SWOOLE_HOOK_ALL ^ SWOOLE_HOOK_CURL ^ SWOOLE_HOOK_NATIVE_CURL );`  you will override the flags that may have been set by parent, because in parent `SWOOLE_HOOK_ALL`  might not have been set, and I dont want to override the global scope ).

Hope I explained it...

**Comment by sy-records** [comment]
Actually when you turn on `SWOOLE_HOOK_NATIVE_CURL` at compile time, `SWOOLE_HOOK_CURL` is already turned off.
