### ISSUE TITLE
php 8.1.0 alpha2 error: 'php_shutdown_function_entry' 

### ISSUE THREAD

**Issue by crackfan** [swoole/swoole-src#4281]
#5 1223.4 /tmp/pear/temp/swoole/ext-src/php_swoole.cc: In function 'void php_swoole_register_shutdown_function(const char*)':
#5 1223.4 /tmp/pear/temp/swoole/ext-src/php_swoole.cc:304:29: error: 'php_shutdown_function_entry' {aka 'struct _php_shutdown_function_entry'} has no member named 'arg_count'
#5 1223.4   304 |     shutdown_function_entry.arg_count = 0;
#5 1223.4       |                             ^~~~~~~~~
#5 1223.4 /tmp/pear/temp/swoole/ext-src/php_swoole.cc:305:29: error: 'php_shutdown_function_entry' {aka 'struct _php_shutdown_function_entry'} has no member named 'arguments'
#5 1223.4   305 |     shutdown_function_entry.arguments = NULL;
#5 1223.4       |                             ^~~~~~~~~
#5 1223.4 /tmp/pear/temp/swoole/ext-src/php_swoole.cc:306:46: error: 'php_shutdown_function_entry' {aka 'struct _php_shutdown_function_entry'} has no member named 'function_name'
#5 1223.4   306 |     function_name = &shutdown_function_entry.function_name;
#5 1223.4       |                                              ^~~~~~~~~~~~~
#5 1223.6 make: *** [Makefile:202: ext-src/php_swoole.lo] Error 1
#5 1223.7 ERROR: `make' failed

**Comment by NathanFreeman** [comment]
The php_shutdown_function_entry struct  of php8.1 is diffrent from php8.0.
