### ISSUE TITLE
Process\Poll进程池通过pool->set设置enable_coroutine与new Pool()设置第4个参数表现不一致

### ISSUE THREAD

**Issue by SETSESSION** [swoole/swoole-src#4282]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
  
   代码如下：
```php
<?php
  use Swoole\Process;
  use Swoole\Coroutine;
  
  //第一方式：通过pool->set设置启用协程，kill -15 {managerpid} 表现为不可正常退出，使用第二种方式可正常退出
  $pool = new Process\Pool(4, SWOOLE_IPC_UNIXSOCK,0);
  $pool->set([
      'enable_coroutine' => true
  ]);
  
  #第二方式
  //$pool = new Process\Pool(4, SWOOLE_IPC_UNIXSOCK,0,true);  #通过此方式kill -15 可以正常退出并执行workerstop
  
  $pool->on('workerStart', function (Swoole\Process\Pool $pool, int $workerId) {
      $process = $pool->getProcess(0);
      $socket = $process->exportSocket();
      $running = true;
      Process::signal(SIGTERM,function() use($workerId,&$running) {
         echo "{$workerId} term\n";
         $running = false;
      });
      while($running) {
          if ($workerId == 0) {
              echo $socket->recv();
          } else {
              $socket->send("hello proc0 {$workerId}\n");
          }
  
          Coroutine::sleep(1);
      }
  
      $socket->close();
  
  });
  
  
  $pool->on('workerStop',function(Process\Pool $pool,$workerId) {
      echo "worker {$workerId} stop".PHP_EOL;
  });
  
  $pool->start();
```

2. What did you expect to see?
通过使用第一种方式时，kill -15 期望可以正常退出

3. What did you see instead?
卡死不退出
![image](https://user-images.githubusercontent.com/2141817/123739688-a1dc3c00-d8d9-11eb-8a8e-478fc7da5d01.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7
Built => May 14 2021 15:46:29
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1k  25 Mar 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
uname -a 
Linux 72cf7d878d8f 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 Linux

php -v
PHP 7.2.34 (cli) (built: Dec 17 2020 10:26:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/9.3.0/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-9.3.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 9.3.0' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,d,objc,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
gcc version 9.3.0 (Alpine 9.3.0)

**Comment by matyhtf** [comment]
将构造方法的第三个参数设置为 `SWOOLE_IPC_NONE`

**Comment by SETSESSION** [comment]
> 将构造方法的第三个参数设置为 `SWOOLE_IPC_NONE`

Swoole\Process\Pool::__construct(int $worker_num, int $ipc_type = 0, int $msgqueue_key = 0, bool $enable_coroutine = false);

构造方法的第三个参数是msgqueue_key，您是指这个吗

**Comment by matyhtf** [comment]
@SETSESSION 说错了，那应该是第二个参数。如果这个参数不为 `SWOOLE_IPC_NONE`，底层会进入`onMessage`的消息接收循环。最新的 4.7 版本将会优化一下这里，使用`set()`方法设置开启协程时，不进入`onMessage`

**Comment by SETSESSION** [comment]
> @SETSESSION 说错了，那应该是第二个参数。如果这个参数不为 `SWOOLE_IPC_NONE`，底层会进入`onMessage`的消息接收循环。最新的 4.7 版本将会优化一下这里，使用`set()`方法设置开启协程时，不进入`onMessage`

大大，但是设置SWOOLE_IPC_NONE后就不可以使用exportSocket进行进程间通信了

**Comment by matyhtf** [comment]
@SETSESSION 是的，如果要用 `exportSocket` ，那 4.6 版本还是设置 construct 第 4个参数吧

**Comment by SETSESSION** [comment]
> @SETSESSION 是的，如果要用 `exportSocket` ，那 4.6 版本还是设置 construct 第 4个参数吧。新的版本会解决这个兼容问题。

好的，收到，谢谢大大

**Comment by mifei077** [comment]
@SETSESSION   您好，我是昆山识沃的工作人员，为了感谢您对我司产品的支持和信赖，并在使用过程中进行了有效反馈，请加微信13524075254联系领取我司为您准备的定制小礼物一份，谢谢！
