### ISSUE TITLE
how to set aio_worker_num

### ISSUE THREAD

**Issue by chrisye909** [swoole/swoole-src#4286]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```php

如何设置 aio_worker_num ？

<?php

use Swoole\Coroutine;
use function Swoole\Coroutine\run;

Coroutine::set([
    'aio_worker_num' => 2,  // 该配置不起作用
]);

run(function(){
    file_get_contents('https://baidu.com/');

    var_dump(Coroutine::getOptions());
    var_dump(Coroutine::stats());   // aio_worker_num = 4 ，主机cpu核心数
});


```

2. What did you expect to see?

如何设置 aio_worker_num 数量？我们有生产应用是容器部署在云服务上，主机核心数是 90，aio_worker_num 开的线程太多了

3. What did you see instead?

aio_worker_num 配置不起作用

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7
Built => Jun 22 2021 11:31:38
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1k  25 Mar 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Darwin ChrisdeMacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64 i386 MacBookPro14,1 Darwin

PHP 7.4.19 (cli) (built: May 13 2021 06:28:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.19, Copyright (c), by Zend Technologies

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by twose** [comment]
Solution: `swoole_async_set(['aio_worker_num' => 4]);`

`aio_core_worker_num` is min worker num.
`aio_worker_num`  is max worker num.

See: https://github.com/swoole/swoole-src/blob/master/ext-src/swoole_async_coro.cc#L44

@sy-records 帮忙完善一下文档

**Comment by sy-records** [comment]
加上了 https://wiki.swoole.com/#/functions?id=swoole_async_set

**Comment by sy-records** [comment]
加上了 https://wiki.swoole.com/#/functions?id=swoole_async_set

**Comment by twose** [comment]
这个应该和系统环境无关的，你得自己确认下你容器里的代码是不是更新了
