### ISSUE TITLE
How to react SIGTERM for safe exit when using timer tick in Master process

### ISSUE THREAD

**Issue by crazywhalecc** [swoole/swoole-src#4298]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
有个疑问，如果我在 onStart 事件中给 Master 进程注册了计时器，那么我就无法通过 SIGTERM 来正常中断关闭服务器。我怎么才能使用 SIGTERM 同时让 Master 进程的计时器删除掉，或者可以自定义监听关闭的事件？

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
Swoole 4.6.7

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
PHP 8.0.6

**Comment by twose** [comment]
不应该在master中使用定时器

**Comment by crazywhalecc** [comment]
那在 Manager 可以吗，主要是不想新建个进程

**Comment by twose** [comment]
需求是什么

**Comment by crazywhalecc** [comment]
Worker 退出时不影响计时器就行

**Comment by twose** [comment]
根据进程职责，master和manager都不应该有额外的工作，类似的工作就应该有单独进程来执行

**Comment by crazywhalecc** [comment]
好的👌那最佳方案还是多开进程。

那这种情况的话，应该从哪个进程 fork 新进程比较好呢

**Comment by twose** [comment]
从manager里fork

**Comment by crazywhalecc** [comment]
好，感谢解答 😄
