### ISSUE TITLE
sendfile 和 gzip压缩冲突

### ISSUE THREAD

**Issue by peterxiemin** [swoole/swoole-src#430]
我在http服务使用sendfile，并同时设置       
$response->gzip(1);
$response->header('Content-Encoding', 'gzip');

客户端curl获取的数据为空。

不知道这是不是异常情况。

**Comment by yangchaogit** [comment]
把输出打出来看下吧。内容应该没有经过zip编码的

Sent from my iPhone

**Comment by matyhtf** [comment]
sendfile不支持gzip压缩。
