### ISSUE TITLE
undefined symbol: curl_CURLFile_class

### ISSUE THREAD

**Issue by ericayo** [swoole/swoole-src#4301]
Please answer these questions before submitting your issue. Thanks!

PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/swoole.so (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/swoole.so: undefined symbol: curl_CURLFile_class), /usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/swoole.so.so (/usr/local/php/lib/php/extensions/no-debug-non-zts-20190902/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Comment by sy-records** [comment]
https://github.com/swoole/swoole-src/issues/4085

**Comment by matyhtf** [comment]
When compiling, `swoole-curl` is enabled, curl needs to be installed first, and swoole must be loaded after curl
