### ISSUE TITLE
使用swoole lock 在上锁的同时尝试使用lockwait(1)超时1秒，会出现超时两秒的情况

### ISSUE THREAD

**Issue by Txhua** [swoole/swoole-src#4304]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
    我在使用swoole lock 在上锁的同时尝试使用lockwait(1)超时1秒，会出现超时两秒的情况

2. What did you expect to see?

3. What did you see instead?

### <?php
$lock = new Swoole\Lock();
$lock->lock();
$start = microtime(true);
$lock->lockwait(1);
$end = microtime(true);
$lock->unlock();
var_dump("耗时:" .(($end - $start)*1000)."ms");

"耗时:2000.7531642914ms"

4. What version of Swoole are you using (show your `php --ri swoole`)?

### Swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7
Built => Jun 28 2021 15:14:56
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1k  FIPS 25 Mar 2021
dtls => enabled
http2 => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

### # php -v
PHP 7.4.20 (cli) (built: Jun 28 2021 12:43:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans

 ### #uname -a
Linux Txhua 4.18.0-315.el8.x86_64 #1 SMP Mon Jun 28 19:09:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### #gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
目标：x86_64-redhat-linux
配置为：../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 8.5.0 20210514 (Red Hat 8.5.0-2) (GCC)

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/pull/4302

已解决，请下载 master 代码编译安装

**Comment by mifei077** [comment]
@Txhua    您好，我是识沃科技的工作人员，为了感谢您的反馈，请加微信13524075254联系领取我司为您准备的定制小礼物一份，谢谢！
