### ISSUE TITLE
curl_multi_add_handle 返回值是null，正确返回值是0

### ISSUE THREAD

**Issue by lizhichao** [swoole/swoole-src#4305]
swoole 4.6.7
curl_multi_add_handle 返回值是null，正确返回值是0
https://www.php.net/manual/zh/function.curl-multi-add-handle.php
关闭协成就好了

**Comment by lizhichao** [comment]
用的库 https://github.com/php-curl-class/php-curl-class

**Comment by matyhtf** [comment]
@lizhichao 请贴出 php --ri swoole 的信息，按照 issue 模版提交，使用的是 curl-native hook 吗？

**Comment by matyhtf** [comment]
可能是参数错误，或者使用的是 非 curl-native hook，不支持 curl multi，建议使用  curl-native hook，参数返回值是 long

**Comment by lizhichao** [comment]
ok
