### ISSUE TITLE
What is correct way to use curl_multi_init ?

### ISSUE THREAD

**Issue by ttodua** [swoole/swoole-src#4307]
When we use function  that rely on `curl_multi_init`, we always get:

`Fatal error: Uncaught TypeError: curl_multi_add_handle(): Argument #2 ($handle) must be of type CurlHandle, Swoole\Curl\Handler given in ...`

A) Does Swoole support multi-curl (what are examples) ?
B) If it doesn't support, then should we disable  (`Swoole\Runtime::setHookFlags(0);`) within coroutine (before executing multi-curl) and then re-enable (`Swoole\Runtime::setHookFlags(SWOOLE_HOOK_ALL);`) after executing multi-curl?

**Comment by sy-records** [comment]
You can use `SWOOLE_HOOK_NATIVE_CURL` to support `curl_multi_*` if you are using a version larger than v4.6.0.

Need to add `--enable-swoole-curl` option when compiling Swoole

**Comment by ttodua** [comment]
Thanks for answer. Strange, all of them I've did (--enable-swoole-curl && SWOOLE_HOOK_NATIVE_CURL enabled) but still got error. I will recheck...

**Comment by sy-records** [comment]
Can you provide code for php --ri swoole and recoverable questions?

**Comment by deminy** [comment]
@ttodua I added [an example](https://github.com/deminy/swoole-by-examples/blob/master/examples/hooks/native-curl.php) on how to hook _curl_multi_*_ functions in Swoole. Hope it helps.

**Comment by ttodua** [comment]
Tons of thanks to you all (@sy-records  @deminy ), I've been testing things and re-installed docker, it is strange, I have 4.6.7 version (installed month ago), but when I re-compiled from github source freshly, it no longer triggers error. 
Kudos !

**Comment by ttodua** [comment]
@deminy  
I use excellent [Multi-Curl ](https://github.com/chuyskywalker/rolling-curl) in our project, so, your example is very appreciated, but I might stay still on multi-curl (Rolling version) which is superb. I even recommend you to look at that.
