### ISSUE TITLE
WARNING check_worker_exit_status: worker#3[pid=30853] abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by tim1116** [swoole/swoole-src#4310]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

an WARNING message was occurred in swoole log 

![image](https://user-images.githubusercontent.com/9588681/125226969-8aca2080-e2c1-11eb-9536-3d0eec8246e5.png)

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.10
Built => Jun 23 2021 15:11:52
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux VM-32-13-centos 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.3.28 (cli) (built: Jun 23 2021 14:56:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.28, Copyright (c) 1998-2018 Zend Technologies

gcc version 4.8.5 20150623

**Comment by tim1116** [comment]
WARNING 是否和上面的内存问题有关呢

**Comment by sy-records** [comment]
升级最新版本后复现问题，使用`valgrind`追踪

```bash
USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php your_file.php
```

**Comment by twose** [comment]
可能和内存不足导致的致命错误有关，看起来可能是一个边缘性的问题，需要你按照上面的流程操作一下，否则我们没办法继续定位问题。
