### ISSUE TITLE
Socket#X has already been bound to another coroutine#Y

### ISSUE THREAD

**Issue by Draghmar** [swoole/swoole-src#4313]
1. What did you do? If possible, provide a simple script for reproducing the error.
I have simple API server that listens for requests and do stuff according to some variables. It uses MariaDB and ConnectionPool with some modifications to fight different issue where connection can go away if not used for longer period of time. 
To completely honest I'm pretty sure I did something wrong...some error on my part. But I don't know what to look for.
Below is simplified code:
```php
	use Swoole\HTTP\Server;
	use Swoole\ConnectionPool;
	use Swoole\Runtime;
	Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_ALL);

	class ConnectionPoolExt extends ConnectionPool {
		public function __construct(callable $constructor, int $size = self::DEFAULT_SIZE, ?string $proxy = null) {
			$this->maxretries = 10;
			parent::__construct($constructor, $size, $proxy);
		}

		public function get($retry = 0) {
			if($this->pool === null) {
				throw new RuntimeException('Pool has been closed');
			}
			if($this->pool->isEmpty() && $this->num < $this->size) {
				$this->make();
			}
			try {
				$out = $this->pool->pop();
				if(!$out || $out == null) {
					$this->make();
					$out = $this->pool->pop();
					error_log('['.__FILE__.':'.__LINE__.'] '.$out);
				}
				$r = $out->q('SELECT 1');
				if(!$r || $r->irow == 0) throw new Exception('SELECT 1 failed - No connection');
			} catch(Swoole\Error | DBException | Exception $e) {
				$this->make();
				$out = $this->pool->pop();
				try {
					error_log('['.__FILE__.':'.__LINE__.'] '.$out);
				} catch(Swoole\Error | DBException | Exception $e) {
					if($retry < $this->maxretries) {
						return $this->get(++$retry);
					}
					error_log('['.__FILE__.':'.__LINE__.'=>'.basename($e->getFile()).':'.$e->getLine().'] '.$e->getMessage());
					return false;
				}
			}
			return $out;
		}
	}

	$dbpool = new ConnectionPoolExt(function() use ($config) {
		return new DB($config); // This is wrapper around PDO, nothing too fancy there.
	}, 500);

	$srv = new Server('X.X.X.X', 9501);
	$srv->set([
		'log_level' => 0,
		'log_file' => '/var/log/swoole/swoole.log',
		'log_rotation' => SWOOLE_LOG_ROTATION_DAILY,
		'reload_async' => true,
		'http_compression_level' => 5,
		'http_gzip_level' => 5,
		'http_parse_post' => true,
	]);

	$srv->on('request', function($request, $response) use ($dbpool) {
		$db = $dbpool->get();
		// Do some important stuff that uses $db
		go(function() use ($dbpool) {
			$db = $dbpool->get();
			// Do some less important stuff in "background"
			$dbpool->put($db);
		});
		$dbpool->put($db);
	});
```

2. What did you expect to see?
Nothing actually. ;) Everything should work fine.

3. What did you see instead?
Sometimes I'm getting `Socket#X has already been bound to another coroutine#Y` from within `go()` function. And I have no idea why. I'm getting there fresh connection from the pool so this shouldn't happen...And I'm getting this error at `$dbpool->get()` and some DB query as well, which is especially weird because if I've got connection from the pool why it's bound somewhere else?
Additional weirdness: I've seen this happening within `go()` but not at the first DB query! So I could have something like this:
```php
		go(function() use ($dbpool) {
			$db = $dbpool->get();
			$db->query('SELECT 1 FROM whatever'); // This had to worked
			// Do some stuff
			$db->query('SELECT 2 FROM somethingelse'); // Because this one threw Swoole\Error
			$dbpool->put($db);
		});
```
where the first query would work and the second wouldn't.

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.6.7

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
php: 8.0.5
gcc version 11.1.1 20210430 (GCC)
Linux 5.10.37-1

**Comment by twose** [comment]
I can not find any problem with the code you provided here for now... And it seems that you have already known about coroutine socket binding things, so maybe I can trust you that you would not make simple mistakes here.
Before you provide a simple script for reproducing the error, it may be difficult for me to continue to help you track the real problem...

**Comment by Draghmar** [comment]
The code I'm using doesn't differ from this simplified sample. It's exactly like that...Maybe there's one additional thing that I'm doing but I'm not sure if it's related - see the sample below. 
Also there's no specific way for reproducing error. It doesn't happen all the time but from time to time and I can't find a way to trigger it "manually". Sometimes it triggers directly from within `go()` but sometimes when doing `$dbpool->get()` and testing connection from within `ConnectionPoolExt` extended class.
I think it's related to the fact I see it only on production server, where there is more traffic then on dev. That's why I'm trying to understand why it can happen, so maybe this way I could "blindly" prevent it.

```php
$srv->on('request', function($request, $response) use ($dbpool) {
	$db = $dbpool->get();
	$path = $request->server['request_uri'];
	$router = new Router($path); // It parser the requested path to trigger function

	// Do some important stuff that uses $db

	$router->add('/requested/path', function() use ($db, $dbpool) {
		//Do some more stuff with $db
		go(function() use ($dbpool) {
			$db = $dbpool->get();
			$db->query('SELECT 1 FROM whatever'); // This had to worked

			// Do some stuff
			
			// Triggers different biding, where `$this` relates to `$router`
			// Maybe I should do this in nested coroutine?
			$this->trigger('/some/path/to/trigger');

			$db->query('SELECT 2 FROM somethingelse'); // Because this one threw Swoole\Error
			$dbpool->put($db);
		});
	});

	$router->add('/some/path/to/trigger', function() use ($db, $dbpool) {
		//Do some more stuff with $db
		go(function() use ($dbpool) {
			$db = $dbpool->get();
			$db->query('SELECT 1 FROM whatever'); // This had to worked
			// Do some stuff
			$db->query('SELECT 2 FROM somethingelse'); // Because this one threw Swoole\Error
			$dbpool->put($db);
		});
	});

	$router->go(); // It triggers bound Closure
	$dbpool->put($db);
});
```
What the `$router->add()` does is:
```php
public function add($path, $fn, $bubble = null) {
	$this->events[$path] = [
		'call'=>Closure::bind($fn,$this),
		'bubble'=>$bubble ?? $this->bubble,
	];
}
```
And then `$router->go()` (as well as `$router->trigger()`) simply invokes what's in the `call`.

I tried yesterday to remove all the `go()` functions and all those stuff, that I wanted to do in "background", I did in a normal run. At the moment it looks like I didn't get more of those errors, which would suggests the error is related to getting DB connection in coroutine...

BTW Don't trust me with knowing anything about socket binding. ;) I do know that there is something like that but I don't know the details so it's quite possible I did some basic mistake. One of the reasons I'm asking here is to get some tips on what could trigger this error to try to find out if I did that mistake. :P

**Comment by twose** [comment]
However... socket binding checks never make mistakes. The only thing you should know is that if you are reading or writing on the socket, you can not use the socket in another coroutine anymore before the reading or writing was done...
I still can't see the problem from the limited info you provided... Did you create a new coroutine in `$this->trigger()`, then it read or write on the socket when the socket is working on `$db->query('SELECT 2 FROM somethingelse');`?

**Comment by fakharksa** [comment]
Is not it possible that two DB connections in the DBPool, at some point in time, start pointing to the same Socket ? For example, in some KeepAlive setup when a Socket is in disconnected mode due to Timeout, and at this status the ConnectionPool tries to bring in a new Connection in the Pool which somehow points to this inactive (disactive/passive) Socket.

May be checking the Timeout setting when you create DB Connection in the DBPool help ? 

Plus, a good approach  is to use try-catch and inside catch return the connection to the pool, and also use coroutine::defer(function() {
  /// return connection to pool
})

.. at the start of your function. This ensures that connection is returned to the Pool after coroutine is finished (even if it finishes with some crash not catchable in catch block)

In your code for Connection Pool make sure you disconnect / close the connection if it is timedout, or reconnects it if it is using KeepAlive setting with Database.
