### ISSUE TITLE
http2 client does not return response with non-ssl/non http2 sites

### ISSUE THREAD

**Issue by tolgaulas** [swoole/swoole-src#4319]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Trying to fetch a non ssl content via http2 client

2. What did you expect to see?
site content as i receive http client

3. What did you see instead?
no response displayed despite the client->send succeeded.

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.6.7

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Debian 10 buster, 
PHP 8.0.8 (cli) (built: Jul  1 2021 16:14:13) ( NTS )
gcc version 8.3.0

-----------
Despite the http/client get works fine, the same setting does not return result with http2

```php

Co\run(function()
{
    // The domain we want to connect to
    $domain = 'httpbin.org';
    $client = new Swoole\Coroutine\Http\Client($domain, 80, false);
    $client->set(['timeout' => -1]);
    $client->get('/ip');
    var_dump($client->body);
  
    $client2 = new Swoole\Coroutine\Http2\Client($domain, 80, false);
    $client2->set([
        'timeout' => -1,
    ]);
    $client2->connect();

    // Create and build a request that will be sent...
    $request = new Swoole\Http2\Request();
    $request->method = 'GET';
    $request->path = '/ip';

    var_dump($client2->send($request));
    var_dump($response = $client2->recv());
});

```

**Comment by tolgaulas** [comment]
I guess this can be intentional and there can be no reason to fall back to http/1.1 for swoole, though it should be nifty to have it.

**Comment by twose** [comment]
Although the standard itself does not require the use of encryption, all major browser implementations (i.e. Firefox, Chrome, Safari, Opera, IE, Edge) have decided that they will only support HTTP/2 over TLS. So the almost all HTTP2 servers require will require the client to enable SSL.
