### ISSUE TITLE
ext-postgresql Insert long SQL, it will be stuck all the time

### ISSUE THREAD

**Issue by c2498168786** [swoole/swoole-src#4320]
Please answer these questions before submitting your issue. Thanks!
https://github.com/swoole/ext-postgresql/tree/v4.4.16
ext-postgresql 插入超长sql，会一直卡住。帮忙看看。
1. What did you do? If possible, provide a simple script for reproducing the error.
```
<?php
use Swoole\Coroutine\PostgreSQL;
use function Swoole\Coroutine\run;

run(function () {
    $pg = new PostgreSQL();
    $conn = $pg->connect("host=127.0.0.1 port=5432 dbname=test user=root password=");
    // Super long, such as 1000 lines，once inserted
    $result = $pg->query("insert into table(\"id\"......) value(........)");
    $arr = $pg->fetchAll($result);
    var_dump($arr);
});


```

2. What did you expect to see?
3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
v4.4.16

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

php7.2.34

**Comment by matyhtf** [comment]
请给我表结构，以及一条具体的用于测试的 SQL 吧

**Comment by c2498168786** [comment]
> 请给我表结构，以及一条具体的用于测试的 SQL 吧

CREATE SEQUENCE "apidata"."request_reports_temp_id_seq" INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE TABLE "apidata"."request_reports_temp" (
  "id" int8 NOT NULL DEFAULT nextval( '"apidata".request_reports_temp_id_seq' :: regclass ),
  "profile_id" int8 NOT NULL,
  "is_merge" int2 NOT NULL DEFAULT 0,
  "record_type" VARCHAR ( 32 ) COLLATE "pg_catalog"."default" NOT NULL,
  "request_date" DATE NOT NULL,
  "report_date" DATE NOT NULL,
  "original_report_date" DATE NOT NULL,
  "report_id" VARCHAR ( 128 ) COLLATE "pg_catalog"."default" NOT NULL,
  "status" VARCHAR ( 16 ) COLLATE "pg_catalog"."default" NOT NULL,
  "metrics" VARCHAR ( 400 ) COLLATE "pg_catalog"."default",
  "statusDetails" VARCHAR ( 128 ) COLLATE "pg_catalog"."default",
  "is_down" int2 NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP ( 0 ) DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP ( 0 ) DEFAULT CURRENT_TIMESTAMP,
  "retry_times" int2 DEFAULT 0,
  "is_save" int2 NOT NULL DEFAULT 0,
  "downloads" int2 DEFAULT 0,
  "sponsored_type" VARCHAR ( 16 ) COLLATE "pg_catalog"."default",
  "amzapi_id" int2 DEFAULT 0,
  "cron_type" VARCHAR ( 64 ) COLLATE "pg_catalog"."default" DEFAULT 'report' :: CHARACTER VARYING,
  "request_rid" VARCHAR ( 128 ) COLLATE "pg_catalog"."default",
  "weight" int2 DEFAULT 0,
  "meta" jsonb,
  "file_size" float8,
  "department_id" int8 DEFAULT 0,
  PRIMARY KEY ( "id" ) 
);


You can't comment at this time — your comment is too long (maximum is 65536 characters).
太长了。
$sql 如下：value里面 记得搞到一千行哦
INSERT INTO "apidata"."request_reports_temp"("profile_id", "is_merge", "record_type", "request_date", "report_date", "original_report_date", "report_id", "status", "metrics", "statusDetails", "is_down", "created_at", "updated_at", "retry_times", "is_save", "downloads", "sponsored_type", "amzapi_id", "cron_type", "request_rid", "weight", "meta", "file_size", "department_id") 
VALUES 
(12345678, 0, 'campaigns', '2021-07-10', '2021-07-08', '2021-07-08', '841b435-4503-4303-9a08-44605a338b58', 'SUCCESS', NULL, NULL, 0, '2021-07-10 11:57:15', '2021-07-10 11:57:15', 0, 0, 0, NULL, 0, 'report', NULL, 0, '[]', '0', 0);

**Comment by matyhtf** [comment]
@c2498168786  通过上传文件方式，把 原始的SQL 发给我吧。注意删除敏感信息

**Comment by c2498168786** [comment]
> @c2498168786 通过上传文件方式，把 原始的SQL 发给我吧。注意删除敏感信息

**Comment by c2498168786** [comment]
> @c2498168786 通过上传文件方式，把 原始的SQL 发给我吧。注意删除敏感信息
包含了 ddl 和dml。不知道是不是底层通过socket？包大小问题？

[
[test.txt](https://github.com/swoole/swoole-src/files/6827399/test.txt)
](url)

**Comment by matyhtf** [comment]
无法重现这个问题，我在本机测试可以正常的。请添加微信 19921030512 沟通

![2021-07-16 15-40-26 的屏幕截图](https://user-images.githubusercontent.com/2017766/125910898-a4071f22-64ab-4005-a108-380a6f75408b.png)
![2021-07-16 15-40-43 的屏幕截图](https://user-images.githubusercontent.com/2017766/125910910-0bc666c1-143b-4bfa-9a56-81c9b7f3cabb.png)

**Comment by c2498168786** [comment]
v4.7.0  修复了，峰哥牛逼
