### ISSUE TITLE
Is it safe to "run" inside "run"

### ISSUE THREAD

**Issue by ttodua** [swoole/swoole-src#4322]
I want the whole application's entypoint (index.php) to be run under Swoole Coroutine, like:

```
run(  
    go (  function(){ require(__DIR__.'/index.php'; }  
 ) );
```

However, in that application, there are many places where there are again bunch of occasions, like `XYZ()` function imagine inside `index.php` itself :
```
function XYZ()
{
	$array=range(1,5);
	foreach($array as $e)
	{
		go( function(){    
			do_curl("https://site.com/page-$i");  
			do_smth(); 
			...
		} );
	} 
}
```

So, are there any possible drawbacks, when there are nested "run/go" (`go`s inside `go`) used?

**Comment by NathanFreeman** [comment]
Hi, run/go can be nested a lot run/go.
But these run/go functions are disordered during the running of program.

**Comment by matyhtf** [comment]
The `Swoole\Coroutine\run` is main function, it cannot be nested. But the `Swoole\Coroutine\go` function can be nested
