### ISSUE TITLE
WARNING Server::check_worker_exit_status() error

### ISSUE THREAD

**Issue by godhelpjun** [swoole/swoole-src#4328]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

git clone https://github.com/hyperf/hyperf-skeleton hyperf
cd hyperf

#install all components, if composer asks you, just hit y
composer install

#vi config/auload/config_center.php ,make it return empty array; just return [];
php bin/hyperf.php start

2. What did you expect to see?
it should not report this.

3. What did you see instead?
[DEBUG] Event Hyperf\Framework\Event\OnManagerStart handled by Hyperf\Server\Listener\InitProcessTitleListener listener.
[2021-07-20 10:51:07 $125025.0] WARNING Server::check_worker_exit_status(): worker(pid=125035, id=3) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.7.0-dev, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

4. What version of Swoole are you using (show your `php --ri swoole`)?

adam@adam:/www/wwwroot/hyperf$ php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.7.0
Built => Jul 20 2021 09:22:56
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

adam@adam:/www/wwwroot/hyperf$ uname -a
Linux adam 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

adam@adam:/www/wwwroot/hyperf$ php -v
PHP 7.3.29 (cli) (built: Jul 13 2021 02:33:51) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.29, Copyright (c) 1998-2018 Zend Technologies
    with Yasd v0.3.9-alpha, Our Copyright, by codinghuang

adam@adam:/www/wwwroot/hyperf$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by sy-records** [comment]
请使用`valgrind`进行追踪

```bash
USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php bin/hyperf.php start
```

复现问题后将`/tmp/valgrind.log`上传到这里

**Comment by godhelpjun** [comment]
valgrind.log

链接: https://pan.baidu.com/s/1t0eLT3LQUxbvXbR1LxtJJw 提取码: q62t 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by godhelpjun** [comment]
如果有问题 可以加我QQ 408805521
我可以远程给你演示

**Comment by matyhtf** [comment]
如果是使用 git pull 更新，请首先进行 make clean 操作，重新编译

**Comment by godhelpjun** [comment]
@matyhtf  感谢老师 我经常测试最新版swoole,想省事,确实是git pull下来make的.
make clean 后再make ,已经正常.
swoole真是一个牛逼扩展,我喜欢它

**Comment by godhelpjun** [comment]
make clean && make && make install 搞定
