### ISSUE TITLE
WARNING	Server::check_worker_exit_status(): worker(pid=23369, id=1) abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by as2252258** [swoole/swoole-src#4333]
==24780== Conditional jump or move depends on uninitialised value(s)
==24780==    at 0x8559D2: zend_string_equal_val (zend_string.c:403)
==24780==    by 0x7B5563: zend_string_equal_content (zend_string.h:346)
==24780==    by 0x7B5563: zend_string_equals (zend_string.h:351)
==24780==    by 0x7B5563: zend_is_assign_to_self (zend_compile.c:3055)
==24780==    by 0x7C21C1: zend_compile_assign (zend_compile.c:3102)
==24780==    by 0x7BA4A4: zend_compile_expr_inner (zend_compile.c:9512)
==24780==    by 0x7BA4A4: zend_compile_expr (zend_compile.c:9629)
==24780==    by 0x7C2CD4: zend_compile_stmt (zend_compile.c:9471)
==24780==    by 0x7C3C66: zend_compile_stmt_list (zend_compile.c:5992)
==24780==    by 0x7C2E8D: zend_compile_stmt (zend_compile.c:9383)
==24780==    by 0x7C5BE1: zend_compile_if (zend_compile.c:5237)
==24780==    by 0x7C3087: zend_compile_stmt (zend_compile.c:9423)
==24780==    by 0x7C3C66: zend_compile_stmt_list (zend_compile.c:5992)
==24780==    by 0x7C2E8D: zend_compile_stmt (zend_compile.c:9383)
==24780==    by 0x7C43D3: zend_compile_func_decl (zend_compile.c:6990)
==24780== 
==24780== Conditional jump or move depends on uninitialised value(s)
==24780==    at 0x4094EC0: ??? (in /tmp/#1179896 (deleted))
==24780==    by 0xEBC8AF7: ???
==24780==    by 0xEBC8AF7: ???
==24780==    by 0xEBC8AF8: ???
==24780==    by 0xEE001DF: ???
==24780==    by 0xEBC8AF7: ???
==24780== 
==24780== Conditional jump or move depends on uninitialised value(s)
==24780==    at 0x4094EC0: ??? (in /tmp/#1179896 (deleted))
==24780==    by 0xEBC9D57: ???
==24780==    by 0xEBC9D57: ???
==24780==    by 0xEBC9D58: ???
==24780==    by 0xEE001DF: ???
==24780==    by 0xEBC9D57: ???
==24780== 
==24780== Conditional jump or move depends on uninitialised value(s)
==24780==    at 0x4094EC0: ??? (in /tmp/#1179896 (deleted))
==24780==    by 0xEBC85B7: ???
==24780==    by 0xEBC85B7: ???
==24780==    by 0xEBC85B8: ???
==24780==    by 0xEE001DF: ???
==24780==    by 0xEBC85B7: ???
==24780== 
==24780== Conditional jump or move depends on uninitialised value(s)
==24780==    at 0x4094EC0: ??? (in /tmp/#1179896 (deleted))
==24780==    by 0xEBCA837: ???
==24780==    by 0xEBCA837: ???
==24780==    by 0xEBCA838: ???
==24780==    by 0xEE001DF: ???
==24780==    by 0xEBCA837: ???
==24780== 
==24767== Invalid write of size 8
==24767==    at 0x4097DB4: ??? (in /tmp/#1179896 (deleted))
==24767==    by 0x10000006FD0: ???
==24767==    by 0x15D0: ???
==24767==    by 0x25FFFFFFFFD0: ???
==24767==    by 0x2A2A2EFFFFFFFFD0: ???
==24767==    by 0x202A202020201FDA: ???
==24767==    by 0x73694C2072617610: ???
==24767==    by 0x74614472656E6544: ???
==24767==    by 0x202020200A5D5B31: ???
==24767==    by 0x107D9800002F29F0: ???
==24767==    by 0x99343FFFFFFFFFDF: ???
==24767==    by 0x7FFFFFFFFFFFFFE0: ???
==24767==  Address 0x1fff001000 is not stack'd, malloc'd or (recently) free'd
==24767== 
==24767== 
==24767== Process terminating with default action of signal 11 (SIGSEGV)
==24767==  Access not within mapped region at address 0x1FFF001000
==24767==    at 0x4097DB4: ??? (in /tmp/#1179896 (deleted))
==24767==    by 0x10000006FD0: ???
==24767==    by 0x15D0: ???
==24767==    by 0x25FFFFFFFFD0: ???
==24767==    by 0x2A2A2EFFFFFFFFD0: ???
==24767==    by 0x202A202020201FDA: ???
==24767==    by 0x73694C2072617610: ???
==24767==    by 0x74614472656E6544: ???
==24767==    by 0x202020200A5D5B31: ???
==24767==    by 0x107D9800002F29F0: ???
==24767==    by 0x99343FFFFFFFFFDF: ???
==24767==    by 0x7FFFFFFFFFFFFFE0: ???
==24767==  If you believe this happened as a result of a stack
==24767==  overflow in your program's main thread (unlikely but
==24767==  possible), you can try to increase the size of the
==24767==  main thread stack using the --main-stacksize= flag.
==24767==  The main thread stack size used in this run was 8388608.

**Comment by matyhtf** [comment]
这个 valgrind 信息不可读，建议重新编译安装 swoole ，并开启 --enable-debug，修改 Makefile 去掉 -O2 优化，改为 -O0 ，然后重新使用 valgrind 跟踪程序的问题
