### ISSUE TITLE
Swoole closes request silently when file larger than 2MB is uploaded

### ISSUE THREAD

**Issue by Ahmard** [swoole/swoole-src#4338]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

Uploading files larger than 2MB

2. What did you expect to see?

To work just fine or throw an exception

3. What did you see instead?
A warning was logged to console

4. What version of Swoole are you using (show your `php --ri swoole`)?

version 4.6.7

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux amdell 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.0.8 (cli) (built: Jul  1 2021 15:26:46) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.8, Copyright (c), by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

**Comment by NathanFreeman** [comment]
Hi, you can look at increasing package_max_length config.

**Comment by Ahmard** [comment]
I think Swoole should throw an exception or provide an API to let programmers handle the error instead of closing the connection automatically.

**Comment by Ahmard** [comment]
> Hi, you can look at increasing package_max_length config.

I've seen it, but it's not what I'm looking for, check my latest comment.

**Comment by sy-records** [comment]
You need to set the `package_max_length` option.

```php
$http = new Swoole\Http\Server('0.0.0.0', 9501);

$http->set(['package_max_length' => 65]);

$http->on('Request', function ($request, $response) {
    $response->header('Content-Type', 'text/html; charset=utf-8');
    $response->end('<h1>Hello Swoole. #' . rand(1000, 9999) . '</h1>');
});

$http->start();
```

Here a WARNING error message will be thrown.

```
[2021-07-26 09:22:58 #52593.5]  WARNING Port_onRead_http() (ERRNO 7102): Request Entity Too Large: header-length (347) + content-length (536709) is greater than the package_max_length(65536) from session#1 on 0.0.0.0:9501
```
