### ISSUE TITLE
关于同一请求的多次执行时，多个task如何区分请求归属的疑问

### ISSUE THREAD

**Issue by xuanskyer** [swoole/swoole-src#434]
如题。
可能描述的不清楚。具体的说就是，现在我有一个比较耗时的请求A，想要拆成N个task去异步并发。然后把这N个task的结果汇总，作为一个结果返回给请求A。

我的问题是：如果在短时间内连续发送了M个同样的A请求。这样task的总数就是：M * N 。那么在异步的情况下，怎么来标识某个task是属于哪一个A请求的呢？

现在处理方法是使用毫秒时间给每个A请求的task都打上标记。但是感觉这样很麻烦。不知道有没有什么好的办法。

**Comment by matyhtf** [comment]
task的数据里加一项属于哪个请求不就可以了。onFinish里再合并同一个请求的所有Task，直到全部Task返回你再执行对应操作。

不需要考虑多个请求问题，单个请求逻辑对了就没问题。

**Comment by xuanskyer** [comment]
但是task 的执行顺序是不定的啊，有可能下一次的某个task会先执行成功。
这样不区分多个请求的话，合并的task可能来自不同的请求，结果肯定不对啊。

**Comment by matyhtf** [comment]
$tmp[$requestId][$taskIndex] 做缓存，然后检测是否全部完成。
