### ISSUE TITLE
swoole/ext-src/swoole_atomic.cc:247:46: error: 'zend_class_serialize_deny' was not declared in this scope; did you mean 'zend_ce_serializable'?

### ISSUE THREAD

**Issue by crackfan** [swoole/swoole-src#4340]
php 8.1 beta1

#5 473.2 In file included from /tmp/pear/temp/swoole/ext-src/swoole_atomic.cc:17:
#5 473.2 /tmp/pear/temp/swoole/ext-src/swoole_atomic.cc: In function 'void php_swoole_atomic_minit(int)':
#5 473.2 /tmp/pear/temp/swoole/ext-src/swoole_atomic.cc:247:46: error: 'zend_class_serialize_deny' was not declared in this scope; did you mean 'zend_ce_serializable'?
#5 473.2   247 |     SW_SET_CLASS_SERIALIZABLE(swoole_atomic, zend_class_serialize_deny, zend_class_unserialize_deny);
#5 473.2       |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
#5 473.2 /tmp/pear/temp/swoole/ext-src/php_swoole_private.h:638:30: note: in definition of macro 'SW_SET_CLASS_SERIALIZABLE'
#5 473.2   638 |     module##_ce->serialize = _serialize;                                                                               \
#5 473.2       |                              ^~~~~~~~~~
#5 473.2 /tmp/pear/temp/swoole/ext-src/swoole_atomic.cc:247:73: error: 'zend_class_unserialize_deny' was not declared in this scope; did you mean 'zend_unserialize_data'?
#5 473.2   247 |     SW_SET_CLASS_SERIALIZABLE(swoole_atomic, zend_class_serialize_deny, zend_class_unserialize_deny);
#5 473.2       |                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
#5 473.2 /tmp/pear/temp/swoole/ext-src/php_swoole_private.h:639:32: note: in definition of macro 'SW_SET_CLASS_SERIALIZABLE'
#5 473.2   639 |     module##_ce->unserialize = _unserialize
#5 473.2       |                                ^~~~~~~~~~~~
#5 473.3 make: *** [Makefile:211: ext-src/swoole_atomic.lo] Error 1
#5 473.3 ERROR: `make' failed

**Comment by sy-records** [comment]
You can use the master code for installation. 

Fixed via #4335
