### ISSUE TITLE
haproxy做tcp代理websocket服务,怎么拿到客户端真实IP

### ISSUE THREAD

**Issue by DlenoDing** [swoole/swoole-src#4343]
Please answer these questions before submitting your issue. Thanks!

使用websocket服务，前面使用了haproxy做tcp代理，这种要怎么在握手的时候获取客户端IP地址呢。
http的可以，但tcp的始终不行，swoole里一直拿到的是haproxy 的地址

**Comment by matyhtf** [comment]
HaProxy 无法得到真实 IP ，可以考虑使用 LVS 或者其他 SLB 软件。
