### ISSUE TITLE
Uncaught Error: Cannot use object of type Swoole\Table as array

### ISSUE THREAD

**Issue by sauriio** [swoole/swoole-src#4344]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
I was trying to update the version of swoole to the most recent version, but when i was running my app, this error came.

2. What did you expect to see?
tables working as expected on the docs.

3. What did you see instead?
Uncaught Error: Cannot use object of type Swoole\Table as array

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.7.0
Built => Jul 28 2021 15:28:51
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
dtls => enabled
http2 => enabled
json => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
PC 5.10.36-amd64-desktop #2 SMP Mon Apr 26 11:56:35 CST 2021 x86_64 GNU/Linux

PHP 7.3.19-1+eagle (cli) (built: Nov 18 2020 07:21:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1+eagle, Copyright (c) 1999-2018, by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Uos 8.3.0.3-3+rebuild' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Uos 8.3.0.3-3+rebuild)

**Comment by sauriio** [comment]
i fixed this problem on my project, is more to update the docs on https://www.swoole.co.uk/docs/modules/swoole-table where they are using the table as array.

**Comment by sy-records** [comment]
Thank you for your feedback, we will make changes to the document.

**Comment by claylo** [comment]
I've run into this problem as well. Is ArrayAccess no longer supported by Swoole\Table? That's a pretty major change to chalk up as a documentation bug.

**Comment by sy-records** [comment]
Yes, it has been removed since v4.7.0 https://github.com/swoole/swoole-src/pull/4297

**Comment by claylo** [comment]
Can you point to any discussion around this change? 

It's coming as quite a shock after an upgrade to 4.7.0. The release notes didn't mention that change, the examples directory in the extension release still includes ArrayAccess usage ... this is a significant backward compatibility break to anyone using Swoole\Table the way it's documented.

**Comment by sauriio** [comment]
Sure it is, I was as shocked as you, I have my app on CI so it was something a little hard to find.

**Comment by sy-records** [comment]
Yes, the release log missed this change.

cc @huanghantao @doubaokun

**Comment by doubaokun** [comment]
@claylo we will improve the development process in the future, seems nobody informed this important BC change. It is noted on the document now. Thanks.
