### ISSUE TITLE
为什么上传的文件获取文件名是：swoole.upfile.xxx

### ISSUE THREAD

**Issue by Funny-dot** [swoole/swoole-src#4345]
为什么上传的文件获取文件名是：swoole.upfile.xxx

**Comment by NathanFreeman** [comment]
你好，临时文件是通过mktemp生成的，文件名命名规则就是参数必须是以"自订名称.XXXXXX"的格式。
我猜测这样做的做法可能是因为reactor线程作为收集客户端的数据，并将这些数据通过unixsocket转发给worker进程。但是文件上传数据太大，没有必要通过unixsocket全部转给worker进程，所以写在临时文件，将临时文件的文件名发送给worker进程，由worker进程读取，这样能够加快效率。

但是这样引出一个问题，文件名会有重名的可能，因此使用mktemp来生成随机的文件名，这样就能保证worker进程之间的数据不会混淆。

**Comment by Funny-dot** [comment]
那我咋获取上传的文件，我获取上传的文件还要重新上传到另一个接口去

**Comment by NathanFreeman** [comment]
> 
> 
> 那我咋获取上传的文件，我获取上传的文件还要重新上传到另一个接口去

http server 中的$request->files就是文件上传的信息，和$_FILES相同。
https://wiki.swoole.com/#/http_server?id=files
