### ISSUE TITLE
电脑配置不好，不能安装虚拟机，docker

### ISSUE THREAD

**Issue by ShuiPingYang** [swoole/swoole-src#4354]
团队成员你好！
我从相关信息里面看到由于swoole使用了很多linux特性，因此swoole不容易做到在windows下部署。但是我想问一个问题，如果仅仅是在windows下面开发，但是实际上是在linux上部署，这样有什么办法做到吗？我的笔记本电脑有些卡，但是丢掉又挺可惜，毕竟只用了两三年，我相信大部分开发人员需要的仅仅是在windows下面开发即可。swow可以直接部署，能否不改变目前用到swoole项目代码的情况下直接加拓展行不行？我们目前有几个遗留项目使用的easy-swoole框架。

**Comment by Yurunsoft** [comment]
可以搞一台服务器，通过IDE的ssh插件去连接，远程调试开发，体验跟本地差不多的

**Comment by sy-records** [comment]
goto https://github.com/swow/swow/issues/85
