### ISSUE TITLE
升级4.7.0 配置enable-swoole-curl 上传稍大一点的文件阿里云失败

### ISSUE THREAD

**Issue by cpj555** [swoole/swoole-src#4355]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
升级4.7.0 配置enable-swoole-curl 上传稍大一点的文件阿里云超时，
回退回4.6.0 (无enable-swoole-curl)正常,使用的组件为
        "hyperf/filesystem": "2.1.*",
        "xxtime/flysystem-aliyun-oss": "^1.5"
2. What did you expect to see?
上传成功

3. What did you see instead?
上传超时

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.7.0
Built => Aug  6 2021 14:11:33
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1k  25 Mar 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
本地mac,apline容器 均稳定重现

**Comment by sy-records** [comment]
提供一个复现代码

**Comment by cpj555** [comment]
$fileFactory = $this->container->get(FilesystemFactory::class);
        $local = $fileFactory->get('local');
        $local->createDir('/');
        $this->getAdapter()->output();

        $oss = $fileFactory->get('oss');
        $ossConfig = $oss->getConfig();
        $filename = $exportData->getTempExportFilename();
        $res = $oss->writeStream($ossConfig->get('export_path') . $filename, $local->readStream($filename));

这是代码片段，没法直接用,主要代码是组件里的代码
在hyperf中使用 filesystem,xxtime/flysystem-aliyun-oss,主要逻辑是从本地拿xlsx文件上传到oss,(少量数据时无问题),这个组件的默认超时设置的还是3600秒线上cpu瞬间打满了- -,回退回老的镜像就正常了

**Comment by matyhtf** [comment]
@cpj555 请添加微信 19921030512，另外提供一个可以稳定复现的 demo 代码包给我们
