### ISSUE TITLE
运行过程中服务突然死掉了，错误见内容

### ISSUE THREAD

**Issue by bupt1987** [swoole/swoole-src#436]
NU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 22788]
[New LWP 22790]
[New LWP 22789]
[New LWP 22791]
[New LWP 22792]
[New LWP 22786]
[New LWP 22787]
[New LWP 22793]
[New LWP 22784]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php /www/royal/script/web_socket/start.php'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f10a20098b7 in swReactorThread_onReceive_websocket (reactor=reactor@entry=0x7f10a11b3d38, event=event@entry=0x7f102565fde0)
    at /home/junjie/swoole-src-swoole-1.7.21-stable/src/network/ReactorThread.c:1188
1188                    switch (opcode)
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
(gdb) bt
#0  0x00007f10a20098b7 in swReactorThread_onReceive_websocket (reactor=reactor@entry=0x7f10a11b3d38, event=event@entry=0x7f102565fde0)
    at /home/junjie/swoole-src-swoole-1.7.21-stable/src/network/ReactorThread.c:1188
#1  0x00007f10a2009feb in swReactorThread_onReceive_http_request (reactor=0x7f10a11b3d38, event=0x7f102565fde0) at /home/junjie/swoole-src-swoole-1.7.21-stable/src/network/ReactorThread.c:1278
#2  0x00007f10a2000753 in swReactorEpoll_wait (reactor=0x7f10a11b3d38, timeo=<optimized out>) at /home/junjie/swoole-src-swoole-1.7.21-stable/src/reactor/ReactorEpoll.c:267
#3  0x00007f10a200be4b in swReactorThread_loop_stream (param=<optimized out>) at /home/junjie/swoole-src-swoole-1.7.21-stable/src/network/ReactorThread.c:1777
#4  0x00007f10a994c182 in start_thread (arg=0x7f1025660700) at pthread_create.c:312
#5  0x00007f10a9c5c47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) f 1
#1  0x00007f10a2009feb in swReactorThread_onReceive_http_request (reactor=0x7f10a11b3d38, event=0x7f102565fde0) at /home/junjie/swoole-src-swoole-1.7.21-stable/src/network/ReactorThread.c:1278
1278            return swReactorThread_onReceive_websocket(reactor, event);
(gdb) f 0
#0  0x00007f10a20098b7 in swReactorThread_onReceive_websocket (reactor=reactor@entry=0x7f10a11b3d38, event=event@entry=0x7f102565fde0)
    at /home/junjie/swoole-src-swoole-1.7.21-stable/src/network/ReactorThread.c:1188
1188                    switch (opcode)
(gdb) f 2
#2  0x00007f10a2000753 in swReactorEpoll_wait (reactor=0x7f10a11b3d38, timeo=<optimized out>) at /home/junjie/swoole-src-swoole-1.7.21-stable/src/reactor/ReactorEpoll.c:267
267                 ret = handle(reactor, &event);
(gdb) f 3
#3  0x00007f10a200be4b in swReactorThread_loop_stream (param=<optimized out>) at /home/junjie/swoole-src-swoole-1.7.21-stable/src/network/ReactorThread.c:1777
1777        reactor->wait(reactor, NULL);
(gdb) f 4
#4  0x00007f10a994c182 in start_thread (arg=0x7f1025660700) at pthread_create.c:312
312 pthread_create.c: No such file or directory.
(gdb) f 5
#5  0x00007f10a9c5c47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
111 ../sysdeps/unix/sysv/linux/x86_64/clone.S: No such file or directory.

**Comment by bupt1987** [comment]
版本 swoole-1.7.21-stable

**Comment by matyhtf** [comment]
WebSocket部分已重构，新版本已解决。
