### ISSUE TITLE
swoole-cygwin版本怎么添加自己的扩展，比如添加redis

### ISSUE THREAD

**Issue by web80qs** [swoole/swoole-src#4361]
我把php_redis.dll 放到了 D:\swoole-cygwin\lib\php\20180731 扩展目录。
并且在php.ini配置了
extension=php_redis.dll
提示
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_redis.dll' (tried: /usr/lib/php/20180731/php_redis.dll (Exec format error), /usr/lib/php/20180731/php_redis.dll.dll (No such file or directory)) in Unknown on line 0

**Comment by sy-records** [comment]
应该是有安装redis扩展的，https://github.com/swoole/swoole-src/blob/master/.github/workflows/cygwin.yml#L20

不过看了下ci，确实丢了redis扩展，https://github.com/swoole/swoole-src/runs/3084920415?check_suite_focus=true#step:4:599

你可以试试能不能使用cygwin的setup.exe安装

**Comment by web80qs** [comment]
@sy-records 
非常感谢，能否提供一个编译好的redis.dll 文件下载地址，我这边本身的cygwin的php环境也有点问题。

**Comment by sy-records** [comment]
https://share.weiyun.com/IJu1hmrp 这里下载吧

`redis` 关闭了 `--disable-redis-json`
