### ISSUE TITLE
log_date_with_microseconds seems to default to true and should be padded

### ISSUE THREAD

**Issue by rgpublic** [swoole/swoole-src#4371]
Contrary to what is stated here:

https://www.swoole.co.uk/docs/modules/swoole-server/configuration#log_date_with_microseconds

My log in fact shows microseconds even though I never specified that anywhere in my Swoole\WebSocket\Server.
In addition, if there's only one digit after the decimal point, a zero should be added IMHO:

![grafik](https://user-images.githubusercontent.com/17726950/129186367-9b0de686-78d6-485a-bb51-469deaf87480.png)

**Comment by zmyWL** [comment]
After the decimal point is the worker process ID, which is not a subtle timestamp

**Comment by zmyWL** [comment]
[2021-08-18 10:11:01<.650780> $135459.0]

< > The time stamp is in parentheses

**Comment by rgpublic** [comment]
Aaah, got it now. Facepalm. Sorry for the confusion.
