### ISSUE TITLE
Swoole-v4.7.1-dev postgresql 多并发insert 报错。

### ISSUE THREAD

**Issue by c2498168786** [swoole/swoole-src#4373]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```
<?php
use Swoole\Coroutine\PostgreSQL;
use function Swoole\Coroutine\run;

run(function () {
    $pg = new PostgreSQL();
    $conn = $pg->connect("host=127.0.0.1 port=5432 dbname=test user=root password=");
    //  Super long, such as 1000 lines，once inserted
    $result = $pg->query("insert into table(\"id\"......) value(........)");
    $arr = $pg->fetchAll($result);
    var_dump($arr);
});
```
![12](https://user-images.githubusercontent.com/16474195/129360649-5b44a34f-4343-4a5c-b6f5-022e094bad6c.jpg)
![121](https://user-images.githubusercontent.com/16474195/129360805-00db764d-33e9-4181-9406-a0e4b37f0830.jpg)

![1211](https://user-images.githubusercontent.com/16474195/129360815-324d0558-f607-4b6b-b242-d347a36baa56.jpg)

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.7.1-dev

swoole_postgresql

Swoole PostgreSQL => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.7.1-dev
Built => Aug 13 2021 19:34:18
trace_log => enabled

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux .qcd.ak.lan 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.2.34 (cli) (built: Aug 13 2021 15:40:51) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by matyhtf** [comment]
https://github.com/swoole/ext-postgresql

**Comment by matyhtf** [comment]
This problem has been fixed
