### ISSUE TITLE
swoole4.7.1 在PHP8下报错

### ISSUE THREAD

**Issue by sayid** [swoole/swoole-src#4380]
[2021-08-20 10:11:54 $18297.0]  WARNING Server::check_worker_exit_status(): worker(pid=18741, id=4) abnormal exit, status=0, signal=6
dyld: lazy symbol binding failed: Symbol not found: __Z25php_swoole_socket_set_sslPN6swoole9coroutine6SocketEP12_zval_struct
  Referenced from: /usr/local/lib/php/pecl/20200930/swoole.so
  Expected in: flat namespace

dyld: Symbol not found: __Z25php_swoole_socket_set_sslPN6swoole9coroutine6SocketEP12_zval_struct
  Referenced from: /usr/local/lib/php/pecl/20200930/swoole.so
  Expected in: flat namespace

[2021-08-20 10:11:54 $18297.0]  WARNING Server::check_worker_exit_status(): worker(pid=18742, id=1) abnormal exit, status=0, signal=6
[2021-08-20 10:11:54 $18297.0]  WARNING Server::check_worker_exit_status(): worker(pid=18739, id=6) abnormal exit, status=0, signal=6
dyld: lazy symbol binding failed: Symbol not found: __Z25php_swoole_socket_set_sslPN6swoole9coroutine6SocketEP12_zval_struct
  Referenced from: /usr/local/lib/php/pecl/20200930/swoole.so
  Expected in: flat namespace

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.7.1
Built => Aug 20 2021 09:51:09
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Darwin macdeMacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

PHP 8.0.9 (cli) (built: Jul 29 2021 17:21:21) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.9, Copyright (c), by Zend Technologies

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by huanghantao** [comment]
看起来是一个编译问题，之前你开了`--enable-openssl`，编译过一次`swoole`，然后又关了`openssl`，编译了一次。

执行`make clean`后重新编译`swoole`试试。

**Comment by sayid** [comment]
重新编译后好了

**Comment by bh013** [comment]
```Swoole http server is started at http://127.0.0.1:80
[2021-09-04 22:23:49 $37.0]     WARNING Server::check_worker_exit_status(): worker(pid=39, id=0) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.7.1, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Linux 5.10.23-0-virt #1-Alpine SMP Mon, 15 Mar 2021 06:55:22 +0000 x86_64
GCC_VERSION: 10.3.1 20210625
PHP_VERSION : 8.1.0RC1```



do you need more info ?!
