### ISSUE TITLE
swWebSocket_pack_close_frame: the max length of close reason is 125

### ISSUE THREAD

**Issue by flysion** [swoole/swoole-src#4381]
swoole-version：4.6.7

对于一个websocket的server，当disconnect时reason太长的就会报警告：
> swWebSocket_pack_close_frame: the max length of close reason is 125

然后我就试图修改`./include/swoole_websocket.h`的代码，把reason搞长一点：
> // ./include/swoole_websocket.h
> #define SW_WEBSOCKET_CLOSE_REASON_MAX_LEN 125

重新编译以后，调用disconnect方法关闭客户端：
> $server->disconnect($fd, 4004, "检测您未满18周岁，根据《关于防止未成年人沉迷网络游戏的通知》每日在22：00-08：00期间无法为您提供游戏服务，对您造成的不便敬请谅解。");

客户端报错：
> WebSocket connection to 'ws://sdkv8_ws/' failed: Invalid frame header

我看到源码有这样一个逻辑针对超过125位的reason的处理，不知道是不是这里处理出了毛病：
> if (length < 126) {
> header->LENGTH = length;
> } else if (length < 65536) {
> header->LENGTH = SW_WEBSOCKET_EXT16_LENGTH;
> uint16_t *length_ptr = (uint16_t *) (frame_header + pos);
> *length_ptr = htons(length);
> pos += sizeof(*length_ptr);
> } else {
> header->LENGTH = SW_WEBSOCKET_EXT64_LENGTH;
> uint64_t *length_ptr = (uint64_t *) (frame_header + pos);
> *length_ptr = swoole_hton64(length);
> pos += sizeof(*length_ptr);
> }

**Comment by NathanFreeman** [comment]
你好，我想可能是websocket 协议决定的，一个websocket数据帧的payload大小是127，disconnect只发一个关闭数据帧过去客户端。所以发不过去。
你可以push再disconnect。

**Comment by flysion** [comment]
> 你好，我想可能是websocket 协议决定的，一个websocket数据帧的payload大小是127，disconnect只发一个关闭数据帧过去客户端。所以发不过去。
> 你可以push再disconnect。

我看到`./src/protocol/websocket.cc`有这么一段逻辑，所以，我不确信这是websocket标准所决定的，希望还是有一个明确的答案
> if (length < 126) {
>     header->LENGTH = length;
> } else if (length < 65536) {
>     header->LENGTH = SW_WEBSOCKET_EXT16_LENGTH;
>     uint16_t *length_ptr = (uint16_t *) (frame_header + pos);
>     *length_ptr = htons(length);
>     pos += sizeof(*length_ptr);
> } else {
>     header->LENGTH = SW_WEBSOCKET_EXT64_LENGTH;
>     uint64_t *length_ptr = (uint64_t *) (frame_header + pos);
>     *length_ptr = swoole_hton64(length);
>     pos += sizeof(*length_ptr);
> }

**Comment by flysion** [comment]
https://datatracker.ietf.org/doc/html/rfc6455 有这么一句话：
> All control frames MUST have a payload length of 125 bytes or less  and MUST NOT be fragmented.

而神秘是 control frames 呢？协议也有说明：
> 0x8 (Close), 0x9 (Ping), and 0xA (Pong)

**Comment by NathanFreeman** [comment]
> 
> 
> https://datatracker.ietf.org/doc/html/rfc6455 有这么一句话：
> 
> > All control frames MUST have a payload length of 125 bytes or less  and MUST NOT be fragmented.
> 
> 而什么是 control frames 呢？协议也有说明：
> 
> > 0x8 (Close), 0x9 (Ping), and 0xA (Pong)

你好，我把SW_WEBSOCKET_CLOSE_REASON_MAX_LEN调整到了12500，可以成功输出。
![图片](https://user-images.githubusercontent.com/33935209/130319523-d1d01d1c-f7dd-4c13-9b67-502ab88b2578.png)

你尝试make clean后再编译试试看结果。
