### ISSUE TITLE
Server response goes blank after page refresh.

### ISSUE THREAD

**Issue by Ahzam-Lathiya** [swoole/swoole-src#4388]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Hello, I'm trying to make my core PHP MVC project asynchronous. What I have done is, I've created a server instance in the front controller file(index.php) and in this index.php I have defined all the app routes against controllers and their respective methods and called a function $app->run() which executes the respective method according to the request. My project worked fine but since I have used Swoole server, I'm having issues, the main one of which is when an endpoint serves an HTML page, it only serves once. Meaning if I call on that endpoint again or refresh that endpoint the page is blank. In the network tab I see the response code 200, also there isn't any error echoed on the command line.
I've tested with simple text data, and it works fine, I've even made an endpoint for a server-side-event, I've tested against that and even that runs ok asynchronously with other requests.

Sample code for the front controller, index.php:
```php
<?php

require_once "Application.php";
require_once "controllers/SiteController.php";

use Swoole\Http\Server as HttpServer;
use Swoole\Coroutine;

//enable Hooks
Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_ALL);

$app = new Application();

$app->routes['GET']['/'] = [SiteController::class, 'home'];
$app->routes['GET']['/home'] = [SiteController::class, 'home'];
$app->routes['GET']['/contact'] = [SiteController::class, 'contact'];
$app->routes['GET']['/about'] = [SiteController::class, 'about'];
$app->routes['GET']['/stuck'] = [SiteController::class, 'stuck'];

$server = new HttpServer('127.0.0.1', 8000);

$server->on('start', function ($server) {
    echo "Server started at http://127.0.0.1:8000\n";
});

$server->on('Request', function (Swoole\Http\Request $request, Swoole\Http\Response $response) use ($app){
  //$response->header('Content-Type', 'text/html');

 // run() resolves the request according to its respective controllers with call_user_func()
  $response->end($app->run($request, $response));
});

$server->start();
?>
```

and my Application.php:

```php
<?php

use Swoole\Http\Response;
use Swoole\Http\Request;

class Application
{
  public array $routes = [];
  public $controller;
  
  public function run(Request $request, Response $response)
  {
    $path = $request->server['request_uri'];
    $method = $request->server['request_method'];
    
    $callback = $this->routes[$method][$path] ?? false;
    
    $controller = new $callback[0]();
    return call_user_func([ $controller, $callback[1] ], $request, $response);
  }
}

?>
```

Also in my controller methods I'm using ob_start() and ob_get_clean() to store the html and return it.

2. What did you expect to see?
I was expecting normal results. Just like when the page is served first time before reload.

3. What did you see instead?

Same as answer 1.

4. What version of Swoole are you using (show your `php --ri swoole`)?

`Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.7.0
Built => Aug 18 2021 18:11:03
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1  11 Sep 2018
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608`

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux  5.4.0-80-generic #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Thank you

**Comment by sy-records** [comment]
This is automatically added by Google Chrome, You can use the following code to ignore

```php
$server->on('Request', function (Swoole\Http\Request $request, Swoole\Http\Response $response) use ($app){
    if ($request->server['path_info'] == '/favicon.ico' || $request->server['request_uri'] == '/favicon.ico') {
        $response->end();
        return;
    }

  //$response->header('Content-Type', 'text/html');

 // run() resolves the request according to its respective controllers with call_user_func()
  $response->end($app->run($request, $response));
});
```

**Comment by Ahzam-Lathiya** [comment]
I'm stuck with the same issue, the page is served only on the first request, afterwards if reloaded, the response is blank. 
Before this the '/favicon.ico' request was not producing any fatal error just a warning, I was just looking for a way to deal with it.

Thanks anyway.
