### ISSUE TITLE
WARN    zm_deactivate_swoole: Fatal error: swoole_http_server::start(): fail to parse multipart body

### ISSUE THREAD

**Issue by mysteriouss** [swoole/swoole-src#439]
使用了[nginx-upload-module](https://github.com/vkholodkov/nginx-upload-module/tree/2.2)， swoole-1.7.17-stable

nginx配置：

    location /api/v1/upload {
        upload_pass @php;
        upload_store /tmp/nginx_upload;
        upload_store_access user:rw group:rw all:rw;
        set $upload_field_name "file";

       # Set specified fields in request body
        upload_set_form_field $upload_field_name.name "$upload_file_name";
        upload_set_form_field $upload_field_name.content_type "$upload_content_type";
        upload_set_form_field $upload_field_name.path "$upload_tmp_path";

        # Inform backend about hash and size of a file
        upload_aggregate_form_field "$upload_field_name.md5" "$upload_file_md5";
        upload_aggregate_form_field "$upload_field_name.size" "$upload_file_size";

        upload_pass_form_field "^submit$|^description$";
        upload_limit_rate 128K;
        upload_cleanup 400 404 499 500-505;
        upload_pass_args on;
    }

    location @php {
        proxy_pass http://127.0.0.1:8884;
    }

swoole_http_server配置：

    $http = new swoole_http_server("127.0.0.1", 8884, SWOOLE_BASE);
    $http->set([
    'dispatch_mode' => 1,
    ]);
    $http->on('request', 'no_chunk');
    function no_chunk(swoole_http_request $request, swoole_http_response $response){}
    $http->start();

转发报文：
    
    POST /api/v1/upload/ HTTP/1.0
    Host: host
    X-Real-IP: 123.xxx.xxx.240
    X-Forwarded-For: 123.xxx.xxx.240
    REMOTE_ADD: 123.xxx.xxx.240
    Connection: close
    Content-Length: xxx
    Accept: */*
    Content-Type: multipart/form-data;  boundary=----WebKitFormBoundarydfFYRAyy09xtmGMX
    Cookie: sid=UVRUQw0EBRdaVgtTSEBaV1gPVRNZAV5BDAdYBBhMDVU=
    Accept-Language: zh-cn
    User-Agent: 201512171919 CFNetwork/758.2.8 Darwin/15.0.0
    Accept-Encoding: gzip, deflate

    ------WebKitFormBoundarydfFYRAyy09xtmGMX
    Content-Disposition: form-data; name="file.name"
    
    1450428264273
    ------WebKitFormBoundarydfFYRAyy09xtmGMX
    Content-Disposition: form-data; name="file.content_type"

    image/jpeg
    ------WebKitFormBoundarydfFYRAyy09xtmGMX
    Content-Disposition: form-data; name="file.path"

    /tmp/nginx_upload/0000000001
    ------WebKitFormBoundarydfFYRAyy09xtmGMX
    Content-Disposition: form-data; name="file.md5"

    f53309a9eef5ae39caa44f200e4f3feb
    ------WebKitFormBoundarydfFYRAyy09xtmGMX
    Content-Disposition: form-data; name="file.size"

    151258
    ------WebKitFormBoundarydfFYRAyy09xtmGMX--

**Comment by matyhtf** [comment]
请更新swoole的版本，最新版本已解决。
