### ISSUE TITLE
执行exit()后子进程卡死，不会自动关闭并重新启动

### ISSUE THREAD

**Issue by dignfei** [swoole/swoole-src#4391]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
global $Server;
$Server = new Swoole\Http\Server('0.0.0.0', 16984);  
$Server->on('WorkerStart', function ($server, $worker_id){
    global $argv;
    echo '进程'.$worker_id.'启动。';
   //exit();
    1/0;
   
});
$Server->on('request', function ($request, $response)use($Server) {

});

$Server->start();
```
2. What did you expect to see?

执行exit();或者出现异常后 自动关闭子进程并重新启动

3. What did you see instead?

子进程卡死。

4. What version of Swoole are you using (show your `php --ri swoole`)?

 4.7.1

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
PHP 8.0.8 (cli) (built: Jul  1 2021 22:40:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.8, Copyright (c), by Zend Technologies

**Comment by dignfei** [comment]
有没有人啊？

**Comment by sy-records** [comment]
这里是PHP8的一些变化，PHP8的exit是一个异常，而不是longjmp了

#4185
