### ISSUE TITLE
PHP4.7.1 在PHP8.0下报错

### ISSUE THREAD

**Issue by woainixyz1** [swoole/swoole-src#4392]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

![image](https://user-images.githubusercontent.com/22805416/132127851-c508333f-8ca4-4624-b8eb-15f23f9398ce.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?

![image](https://user-images.githubusercontent.com/22805416/132127883-bf4d9f8d-d43f-4b46-87a2-b65f8e94856b.png)

**Comment by NathanFreeman** [comment]
可以提供一下复现代码吗，或者试试不用hyperf，看看能不能重现这个bug。

**Comment by woainixyz1** [comment]
是在hy框架下使用yasd调试的时候出现的，就是单纯的调用了一下调试接口就出现报错

**Comment by woainixyz1** [comment]
[valgrind.log](https://github.com/swoole/swoole-src/files/7111659/valgrind.log)

**Comment by sy-records** [comment]
goto https://github.com/swoole/yasd/issues/149
