### ISSUE TITLE
swoole_http_server 内存泄漏问题

### ISSUE THREAD

**Issue by xiaoshen** [swoole/swoole-src#440]
我的onRequest代码是这样写的
server.php
$server->onRequest($request,$response){
    ob_start();
    echo '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试';
  $con = ob_get_contents();
 ob_end_clean();
$response->end($con);

}
用上面代码写 php进程的内存没出现异常

出问题的代码如下： 就是将文本内容写在另外一个html页面，然后include它
test.html 页面的代码如下 就一串中文

测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试

server.php
$server->onRequest($request,$response){
    ob_start();
   include 'test.html';
  $con = ob_get_contents();
 ob_end_clean();
$response->end($con);
}
用这种写法 我用pmap -d 进程号 发现 worker的内存会上升上去。虽然量小，但单一个html页面内容多时，占用的内存就高了。

我用的swoole版本是1.7.21

**Comment by xiaoshen** [comment]
我找到解决方法，需要把include修改为include_once就不会造成内存狂飙了。

**Comment by xiaoxintiaoda** [comment]
.。。。。什么鬼
