### ISSUE TITLE
swoole_http_server include和include_once的问题

### ISSUE THREAD

**Issue by xiaoshen** [swoole/swoole-src#441]
我的onRequest代码是这样写的
server.php
$server->onRequest($request,$response){
ob_start();
$a = '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试';
echo $a;
$con = ob_get_contents();
ob_end_clean();
$response->end($con);
}

用上面代码写 php进程的内存没出现异常

出问题的代码如下： 就是将a变量写到另一个test.php页面，然后server.php include它
test.php 页面的代码如下 
$a = '测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试';

server.php
$server->onRequest($request,$response){
ob_start();
include 'test.phpl';
echo $a;
$con = ob_get_contents();
ob_end_clean();
$response->end($con);
}
用这种写法 我用pmap -d 进程号 发现 worker的内存会上升上去。虽然量小，但单test.php的内容多时，占用的内存就高了。
我用的swoole版本是1.7.21

然后我找到一个方法解决 就是把include替换成include_once的时候，内存就不会上升了，但是当重复请求，就会报 $a变量不存在。

请问有什么解决的办法么，毕竟php内部很多include 和include_once 特别是基于mvc的架构，我加载html页面 请求一会儿 内存就狂飙上去。

**Comment by shenzhe** [comment]
加载html页？建议用file_get_contents， include会缓存在内存里。

**Comment by xiaoshen** [comment]
这个用file_get_contents没用的，它无法解析php变量  因为我这边一个框架是在html代码里有嵌入php代码。

**Comment by matyhtf** [comment]
PHP版本多少，可能和 ob_ 缓存有关。

**Comment by williamborba** [comment]
Hello, great project!
我相信我有同样的problemxiaoshen，swoole想用它来运行自己的WILLER框架，并需要作出规定（）的文件'的src / bootstrap.php中“，但是当我这样做，在$响应 - 法>结束（需要（'SRC/ bootstrap.php中'））;它返回的值“1”.........任何意见或建议吗？

我慢慢学习如何swoole的作品，谢谢

**Comment by matyhtf** [comment]
@williamborba Please speak English

**Comment by matyhtf** [comment]
@williamborba 
```php
ob_start();
include 'SRC/bootstrap.php';
$con = ob_get_contents();
ob_end_clean();
$response->end($con);
```
