### ISSUE TITLE
 使用CURLOPT_HTTPHEADER 构造header  时有个键值为空 被过滤了 

### ISSUE THREAD

**Issue by wujingke** [swoole/swoole-src#4411]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

 使用CURLOPT_HTTPHEADER 构造header  时有个键值为空 被过滤了 
![image](https://user-images.githubusercontent.com/565778/133885105-b6182685-2bb4-4060-b9aa-0bd6ea206646.png)

2. What did you expect to see?

需要在header中传空值的键

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by sy-records** [comment]
这里和curl的行为是一致的
