### ISSUE TITLE
API must be called in the coroutine

### ISSUE THREAD

**Issue by ruwmapps** [swoole/swoole-src#4414]
Hi , i wanted to connect redis , but swears at corrutine :
PHP Fatal error:  Uncaught Swoole\Error: API must be called in the coroutine in /var/www/swoole/server.php:36
(.......$redis->connect('127.0.0.1', 6379);.......)

```
.....

Swoole\Runtime::enableCoroutine(true, SWOOLE_HOOK_ALL);
$server = new Server("0.0.0.0", 9501, SWOOLE_BASE);
$server->set([
     'task_worker_num' => 4,
	'enable_coroutine' => true,
]);
$redis = getRedis();
$redis->delete('all_fd'); 
$all_person = $conf['all_person'];
foreach ($all_person as $key => $value) {
	$redis->hmset('uid:' . $value['uid'], $value);
	$redis->sAdd('all_person_uid', $value['uid']);
}

function getRedis() {
	$redis = new Swoole\Coroutine\Redis();
    $redis->connect('127.0.0.1', 6379);
    //$redis->auth('root');
    //$redis->set('key', 'swoole redis work');
    //var_dump($redis->get('key'));
	return $redis;
}
............
```

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7
Built => Sep 24 2021 13:34:27
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

[root@vds2135107 swoole]# uname -a
Linux vds2135107.my-ihor.ru 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@vds2135107 swoole]# php -v
PHP 7.4.24 (cli) (built: Sep 21 2021 11:23:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
[root@vds2135107 swoole]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by twose** [comment]
Try this:

```php
Swoole\Runtime::enableCoroutine(true, SWOOLE_HOOK_ALL);
.....
Co\run(function() {
        $redis = getRedis();
        $redis->delete('all_fd'); 
        $all_person = $conf['all_person'];
        foreach ($all_person as $key => $value) {
	        $redis->hmset('uid:' . $value['uid'], $value);
	        $redis->sAdd('all_person_uid', $value['uid']);
        }
});

function getRedis() {
	$redis = new Swoole\Coroutine\Redis();
    $redis->connect('127.0.0.1', 6379);
    //$redis->auth('root');
    //$redis->set('key', 'swoole redis work');
    //var_dump($redis->get('key'));
	return $redis;
}
............
$server = new Server("0.0.0.0", 9501, SWOOLE_BASE);
$server->set([
     'task_worker_num' => 4,
	'enable_coroutine' => true,
]);
............
$server->start(); // Finish everything else before starting server
```
