### ISSUE TITLE
大并发下 swoole警告

### ISSUE THREAD

**Issue by xiaoshen** [swoole/swoole-src#442]
我这边开启daemon=0 做大并发下的调试。
发现都是这个报错
swFactoryProcess_dispatch:dispatch[type=4] failed,connection#64[session_id=7221] is closed bu server
swReactoryThread_onReceive_http_request#1323:recv from connection#49 failed.Error:socket operation on non-socket[88]

请问这个对网站有影响，目前我测试大并发下，业务逻辑总是有几个报错。不知道跟这个有没有关系。

**Comment by matyhtf** [comment]
可以忽略的错误。
