### ISSUE TITLE
http 主服务，addlistener  TCP 子服务 ,并开启websocket 兼容，但是子服务无法使用push

### ISSUE THREAD

**Issue by shuyabin** [swoole/swoole-src#4420]
我想创建一个http主服务，然后 addlistener TCP 子服务,并开启websocket的兼容. 但是子服务无法使用push  

 

![image](https://user-images.githubusercontent.com/14884581/135563755-d5300708-6fdd-411d-8aa1-65d7aa78d5ad.png)
![image](https://user-images.githubusercontent.com/14884581/135563826-9975b626-ac48-4276-98e5-c79d5a7e40e9.png)

![image](https://user-images.githubusercontent.com/14884581/135563848-68c4610b-e8d6-42e1-a913-0ba5d8abc6c1.png)

 
Darwin localhost 17.7.0 Darwin Kernel Version 17.7.0: Mon Aug 31 22:11:23 PDT 2020; root:xnu-4570.71.82.6~1/RELEASE_X86_64 x86_64
![image](https://user-images.githubusercontent.com/14884581/135563797-adb3ee05-89fd-4e17-b5cd-e6eac8012348.png)

**Comment by Yurunsoft** [comment]
用`Swoole\WebSocket\Server`才可以，Swoole里服务可以降级但不能升级。

比如 WebSocket 依赖 Http 握手，Http 依赖 TCP 协议，你用 `Swoole\WebSocket\Server` 可以兼容 Http、TCP，反过来就不行。

**Comment by shuyabin** [comment]
谢谢大佬解答疑惑
