### ISSUE TITLE
swoole_table->del 后再 incr ，del会无效。

### ISSUE THREAD

**Issue by badxpgy** [swoole/swoole-src#443]
swoole版本 1.7.22-beta

$crontab_table = new swoole_table(1024);
$crontab_table->column('cnt', swoole_table::TYPE_INT, 2);
$crontab_table->create();
$crontab_table->incr('test', 'cnt', 1);
$crontab_table->del('test');
$crontab_table->incr('test', 'cnt', 1);
$r = $crontab_table->get('test');
echo $r['cnt'].PHP_EOL;

预期： 输出1，
实际：输出 2

**Comment by matyhtf** [comment]
最新的 1.7.22-rc1中已修复，请更新版本后重新测试。
