### ISSUE TITLE
mac m1 安装swoolev4.7.1启动--enable-cares安装报错

### ISSUE THREAD

**Issue by jwjanqiu** [swoole/swoole-src#4430]
我是macbook pro m1电脑，启动--enable-cares时报错fatal error: ares.h: No such file or directory，按照官方文档，因为没给出macos系统解决方法，于是我去GitHub[c-ares](https://github.com/c-ares/c-ares) 找到源代码，按照上面进行安装，可依然报同样的错，不知道是我找的这个GitHub地址不对还是什么原因，请大佬解答一下，谢谢

**Comment by huangdijia** [comment]
@sy-records brew 安装了也没用哦

**Comment by shuifa** [comment]
> brew install c-ares
已经下载了，还是报错找不到
<img width="976" alt="截屏2022-08-28 20 26 02" src="https://user-images.githubusercontent.com/53784478/187077331-3a92ae2d-6dbd-4254-8c67-1b6d5b4e2085.png">

**Comment by huangdijia** [comment]
> > brew install c-ares
> 
> 已经下载了，还是报错找不到
> 
> <img width="976" alt="截屏2022-08-28 20 26 02" src="https://user-images.githubusercontent.com/53784478/187077331-3a92ae2d-6dbd-4254-8c67-1b6d5b4e2085.png">
> 
> 
> 
> 
> 
> 

坐等新版本吧

**Comment by NathanFreeman** [comment]
试试brew install c-ares-dev。
如果找不到，全局查找一下libcares.pc的位置，export PKG_CONFIG_PATH=libcares.pc的路径

**Comment by lk0pa** [comment]
@shuifa @huangdijia  在./configure阶段，应该是--enable-cares=c-ares的目录，比如我电脑上的是/opt/homebrew/Cellar/c-ares/1.18.1_1 ，那./configure  --enable-cares=/opt/homebrew/Cellar/c-ares/1.18.1_1 xxx其他东西就能正常的编译安装

**Comment by lk0pa** [comment]
@huangdijia @shuifa brew安装的c-ares不行，需要自己下载手动编译安装c-ares，然后swoole那边才能编译成功

**Comment by liaochao2023** [comment]
5.0.3仍然有这个问题

**Comment by StringKe** [comment]
使用这些声明和手动编译安装 c-ares 也无法正确编译

```
export C_INCLUDE_PATH="/opt/homebrew/Cellar/c-ares/1.19.1/include:$C_INCLUDE_PATH"
export PKG_CONFIG_PATH="/opt/homebrew/Cellar/c-ares/1.19.1/lib/pkgconfig:$PKG_CONFIG_PATH"
export LIBRARY_PATH="/opt/homebrew/Cellar/c-ares/1.19.1/lib:$LIBRARY_PATH"
```

**Comment by ZbinH2O** [comment]
折腾了一下5.0.3版本,需要把c-ares相关东西软链到/usr/local目录下对应文件夹,pecl安装才能正确编译
```
sudo ln -s /opt/homebrew/include/ares* /usr/local/include
sudo ln -s /opt/homebrew/lib/libcares.dylib /usr/local/lib
```
![image](https://github.com/swoole/swoole-src/assets/6178275/7d9517e8-7477-4282-a98c-97a93cd61fac)
