### ISSUE TITLE
 Swoole's admin interface hot-loads code from a third-party server ?

### ISSUE THREAD

**Issue by foremtehan** [swoole/swoole-src#4434]
Hey i just saw this comment : 

https://github.com/heroku/heroku-buildpack-php/issues/297

> Word of warning: Swoole's admin interface hot-loads code from a third-party server; see https://github.com/swoole/swoole-src/blob/1bc39175acb7d339a9d2d046e031dd9561adb1eb/ext-src/php_swoole_library.h#L7260-L7283

> https://pecl.php.net/package/openswoole looks to be a fork that wants to remediate that, but for now, this is a big no-no.

Can you elaborate what does exactly that part of code ?

**Comment by matyhtf** [comment]
https://www.youtube.com/watch?v=AcQvI_g4Abs

**Comment by nhlm** [comment]
@doubaokun a fork under the explained conditions makes no sense. Maintaining something for 4 years doesn't make you a leader. Expecting to become the leader of a (sub-)project after investing work over years is no good behavior to demonstrate your leadership skills. If you would be ready for a project lead, the entire issue here would have been solved differently and with less drama from your side.

I hereby boycott openswoole.

**Comment by nhlm** [comment]
> @nhlm only the 'lead' role can manage the PECL packages. Plus I have the Owner role of this whole organization 'previously'.

Does not change anything. Your decisions lead to a conflict which you were unable to handle appropriate. I recommend to fix the root cause of the issue without creating another realm where the root cause still persists. Learn from it, find a solution that does not require to fork or alter directions of a project. And this time, no public drama please.

**Comment by barbosa89** [comment]
Please fix this, the PHP community will be badly affected 😔😭

**Comment by petk** [comment]
Overall, it is good that this has happened now than in the future when even more projects would depend on Swoole. If anything Swoole project will become one step better and more resilient to such issues, I believe.

If we all leave any personal reasons here aside a bit, @doubaokun has pointed one major issue. Swoole project needs to operate more openly and with a bigger development team in mind. This is not a personal project anymore where Git commits with messages `Add something` and gazillion new features can land in a patch version.

What is needed in Swoole is a semantic versioning a bit and a better communication when something major is introduced in the code. Many projects depend on this extension. And Swoole needs to make sure that those projects will live on with this extension.

Also, all team members need to start respecting each others work here. No matter who started the project and who manages the community announcements on Twitter etc. Discussions and difficulties about changes are normal.

I hope and wish Swoole and OpenSwoole all the best on their way and may both sides resolve the issues as soon as possible.

It is very pleasant to see that @matyhtf is open to collaboration with @doubaokun who contributes on Twitter really a lot. I hope you two can shake hands, say sorry to each other and accept each other as you are one day. Until then, maybe going two separate ways for temporary is not so bad idea. But from community point of view a bit confusing one for sure.
