### ISSUE TITLE
Manager 进程能否调用 sendMessage()

### ISSUE THREAD

**Issue by crazywhalecc** [swoole/swoole-src#4464]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
文档中说是可以在 Manager 进程中调用，但是实际测试时无法调用。
```php
$worker_id = 1;
if (server()->worker_id == $worker_id) {
        self::workerAction($worker_id, $obj);
    } else {
        server()->sendMessage(json_encode($obj), $worker_id);
    }
```

报错内容为：
```
PHP Warning: Swoole\Server::sendMessage(): can't send messages to self
```

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.8.1

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
8.0.10

**Comment by crazywhalecc** [comment]
![image](https://user-images.githubusercontent.com/20330940/140073728-2bfa0232-642c-43e4-a99b-3eb7f098493a.png)

**Comment by NathanFreeman** [comment]
看看$worker_id是不是等于$manager_pid？
