### ISSUE TITLE
编译的时候报php_swoole.h:20:10: fatal error: 'php.h' file not found

### ISSUE THREAD

**Issue by jonny77** [swoole/swoole-src#4469]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
前景描述:
头一天下班前好好的.然后就让服务一直在那里开着(无人访问),第二天唤醒mac后发现控制台报错

 WARNING check_worker_exit_status: worker#2[pid=40416] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.6.7, please report it.

另外想升级到最新版的swoole.编译参数为:
./configure --enable-openssl --enable-debug
make的时候报错了.
./php_swoole.h:20:10: fatal error: 'php.h' file not found
是不是跟我有多个php版本有关?
2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7
Built => Jun 17 2021 09:35:48
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1j  16 Feb 2021
dtls => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
[1] 70312
[2] 70313
Darwin lll.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
[1]-  Done                    uname -a
PHP 7.4.8 (cli) (built: Sep 10 2020 18:59:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Yasd v0.3.7, Our Copyright, by codinghuang
[2]+  Done                    /usr/local/Cellar/php74/7.4.8/bin/php -v

**Comment by matyhtf** [comment]
@jonny77 缺少 php 头文件，需要先安装 php-devel 相关的包，检查 php-config 的配置，是否缺少头文件。

`signal=11` 的问题，请使用 valgrind 跟踪
