### ISSUE TITLE
用swoole_process异步守护进程出现core,请作者有空帮忙看看,感谢

### ISSUE THREAD

**Issue by eyehere** [swoole/swoole-src#447]
(gdb) bt
#0  _zend_mm_free_int (heap=0x1cc8550, p=0x1cc87f8) at /root/workspace/php-5.5.22/Zend/zend_alloc.c:2104
#1  0x00000000007d1770 in _zval_dtor (zval_ptr=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_variables.h:35
#2  i_zval_ptr_dtor (zval_ptr=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_execute.h:81
#3  _zval_ptr_dtor (zval_ptr=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_execute_API.c:423
#4  0x00000000007ed84b in zend_hash_destroy (ht=0x220eaa8) at /root/workspace/php-5.5.22/Zend/zend_hash.c:560
#5  0x00000000007df46b in _zval_dtor_func (zvalue=0x20300f0) at /root/workspace/php-5.5.22/Zend/zend_variables.c:45
#6  0x00000000007d1770 in _zval_dtor (zval_ptr=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_variables.h:35
#7  i_zval_ptr_dtor (zval_ptr=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_execute.h:81
#8  _zval_ptr_dtor (zval_ptr=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_execute_API.c:423
#9  0x00000000007ed84b in zend_hash_destroy (ht=0x214afd8) at /root/workspace/php-5.5.22/Zend/zend_hash.c:560
#10 0x00000000007df46b in _zval_dtor_func (zvalue=0x21a2fc8) at /root/workspace/php-5.5.22/Zend/zend_variables.c:45
#11 0x00000000008546f8 in _zval_dtor (execute_data=0x2236208) at /root/workspace/php-5.5.22/Zend/zend_variables.h:35
#12 i_zval_ptr_dtor (execute_data=0x2236208) at /root/workspace/php-5.5.22/Zend/zend_execute.h:81
#13 i_free_compiled_variables (execute_data=0x2236208) at /root/workspace/php-5.5.22/Zend/zend_execute.c:1510
#14 zend_leave_helper_SPEC (execute_data=0x2236208) at /root/workspace/php-5.5.22/Zend/zend_vm_execute.h:399
#15 0x0000000000853aa0 in execute_ex (execute_data=0x2236208) at /root/workspace/php-5.5.22/Zend/zend_vm_execute.h:363
#16 0x00000000008025b0 in zend_generator_resume (generator=0x21aa9f8) at /root/workspace/php-5.5.22/Zend/zend_generators.c:379
#17 0x0000000000802c5f in zim_Generator_send (ht=<value optimized out>, return_value=0x20e1c78, return_value_ptr=<value optimized out>, 
    this_ptr=<value optimized out>, return_value_used=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_generators.c:540
#18 0x0000000000862223 in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_vm_execute.h:550
#19 0x0000000000853aa0 in execute_ex (execute_data=0x7ff5d264c5f8) at /root/workspace/php-5.5.22/Zend/zend_vm_execute.h:363
#20 0x00000000007d260e in zend_call_function (fci=0x7fffd0f00c00, fci_cache=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_execute_API.c:934
#21 0x00000000006eae2f in zif_call_user_func (ht=<value optimized out>, return_value=0x2103380, return_value_ptr=<value optimized out>, 
    this_ptr=<value optimized out>, return_value_used=<value optimized out>) at /root/workspace/php-5.5.22/ext/standard/basic_functions.c:4788
#22 0x0000000000862223 in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_vm_execute.h:550
#23 0x0000000000853aa0 in execute_ex (execute_data=0x7ff5d264c430) at /root/workspace/php-5.5.22/Zend/zend_vm_execute.h:363
#24 0x00000000007d260e in zend_call_function (fci=0x7fffd0f00ef0, fci_cache=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_execute_API.c:934
#25 0x00000000007d3290 in call_user_function_ex (function_table=<value optimized out>, object_pp=<value optimized out>, function_name=<value optimized out>, 
    retval_ptr_ptr=<value optimized out>, param_count=<value optimized out>, params=<value optimized out>, no_separation=0, symbol_table=0x0)
    at /root/workspace/php-5.5.22/Zend/zend_execute_API.c:722
#26 0x00007ff5cbbc0e5b in php_swoole_event_onRead (reactor=<value optimized out>, event=0x7fffd0f00fe0) at /root/workspace/swoole-1.7.20/swoole_event.c:64
#27 0x00007ff5cbbd7f3f in swReactorEpoll_wait (reactor=0x208e650, timeo=<value optimized out>) at /root/workspace/swoole-1.7.20/src/reactor/ReactorEpoll.c:267
#28 0x00007ff5cbbc0b6e in php_swoole_event_wait () at /root/workspace/swoole-1.7.20/swoole_event.c:165
#29 0x00007ff5cbbc303d in php_swoole_process_start (process=<value optimized out>, object=0x1fd2888) at /root/workspace/swoole-1.7.20/swoole_process.c:444
#30 0x00007ff5cbbc3cf8 in zim_swoole_process_start (ht=<value optimized out>, return_value=0x2018778, return_value_ptr=<value optimized out>, this_ptr=0x1fd2888, 
    return_value_used=<value optimized out>) at /root/workspace/swoole-1.7.20/swoole_process.c:477
#31 0x0000000000862223 in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_vm_execute.h:550
#32 0x0000000000853aa0 in execute_ex (execute_data=0x7ff5d264c2b8) at /root/workspace/php-5.5.22/Zend/zend_vm_execute.h:363
#33 0x00000000007df799 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /root/workspace/php-5.5.22/Zend/zend.c:1327
#34 0x0000000000781239 in php_execute_script (primary_file=0x7fffd0f04720) at /root/workspace/php-5.5.22/main/main.c:2506
#35 0x000000000089035c in do_cli (argc=2, argv=0x1cc8210) at /root/workspace/php-5.5.22/sapi/cli/php_cli.c:994
#36 0x0000000000890af8 in main (argc=2, argv=0x1cc8210) at /root/workspace/php-5.5.22/sapi/cli/php_cli.c:1378
(gdb) source /home/rd/php-5.5.30/.gdbinit
(gdb) zbacktrace 
[0x22360b0] Aha\Log\Logger->_getBackTrace()  /data/webroot/distribute/Aha_src/Aha/Log/Logger.php:160 
[0x2235f68] Aha\Log\Logger->_writeLog(0, array(1)[0x1fdd938])  /data/webroot/distribute/Aha_src/Aha/Log/Logger.php:205 
[0x2214240] Aha\Log\Logger->debug(array(2)[0x21f0698])  /data/webroot/distribute/src/Dtc/Models/Task/Driver.php:71 
[0x2214140] Dtc\Models\Task\Driver::insertTasks(array(1)[0x219ae78], "3811810") 
[0x7ff5d264c5f8] Generator->send(array(3)[0x1ffb790])  /data/webroot/distribute/Aha_src/Aha/Coroutine/Task.php:248 
[0x7fffd0f00b00] Aha\Coroutine\Task->ahaDbCallback(true, object[0x21702e0], 116) 
[0x7ff5d264c430] call_user_func(array(2)[0x210dc58], true, object[0x21702e0], 116)  /data/webroot/distribute/Aha_src/Aha/Storage/Db/Mysqli.php:159 
[0x7fffd0f00df0] Aha\Storage\Db\Mysqli->onQueryResponse(116) 
[0x7ff5d264c2b8] swoole_process->start()  /data/webroot/distribute/src/Dtc/Library/Daemon/Manager.php:64 
[0x7ff5d264c190] Dtc\Library\Daemon\Manager->createDirtributeWorker(object[0x7ff5d2684ee0], 20)  /data/webroot/distribute/src/Dtc/Daemon/Master.php:84 
[0x7ff5d264c0a0] Dtc\Daemon\Master->create()  /data/webroot/distribute/src/Dtc/Daemon/Master.php:215

**Comment by matyhtf** [comment]
有变量被提交unset掉了，这个可能得从PHP代码层面解决一下。无法直接断定是不是swoole引起的

**Comment by matyhtf** [comment]
请升级到最新版本。
