### ISSUE TITLE
swoole-1.7.20 php_swoole_event_onRead 的时候callback的内存会是0X0

### ISSUE THREAD

**Issue by eyehere** [swoole/swoole-src#448]
Program terminated with signal 11, Segmentation fault.
#0  zend_is_callable_ex (callable=0x0, object_ptr=<value optimized out>, check_flags=8, callable_name=0x7fff4984d238, callable_name_len=0x7fff4984d10c, 
    fcc=0x7fff4984d200, error=0x7fff4984d230) at /root/workspace/php-5.5.22/Zend/zend_API.c:3039
3039    /root/workspace/php-5.5.22/Zend/zend_API.c: No such file or directory.
        in /root/workspace/php-5.5.22/Zend/zend_API.c
Missing separate debuginfos, use: debuginfo-install xiaoju-php-5.5.22-20151117115846.x86_64
(gdb) bt
#0  zend_is_callable_ex (callable=0x0, object_ptr=<value optimized out>, check_flags=8, callable_name=0x7fff4984d238, callable_name_len=0x7fff4984d10c, 
    fcc=0x7fff4984d200, error=0x7fff4984d230) at /root/workspace/php-5.5.22/Zend/zend_API.c:3039
#1  0x00000000007d1e03 in zend_call_function (fci=0x7fff4984d280, fci_cache=0x7fff4984d200) at /root/workspace/php-5.5.22/Zend/zend_execute_API.c:781
#2  0x00000000007d3290 in call_user_function_ex (function_table=<value optimized out>, object_pp=<value optimized out>, function_name=<value optimized out>, 
    retval_ptr_ptr=<value optimized out>, param_count=<value optimized out>, params=<value optimized out>, no_separation=0, symbol_table=0x0)
    at /root/workspace/php-5.5.22/Zend/zend_execute_API.c:722
#3  0x00007fd286c91e5b in php_swoole_event_onRead (reactor=<value optimized out>, event=0x7fff4984d370) at /root/workspace/swoole-1.7.20/swoole_event.c:64
#4  0x00007fd286ca8f3f in swReactorEpoll_wait (reactor=0x1575670, timeo=<value optimized out>) at /root/workspace/swoole-1.7.20/src/reactor/ReactorEpoll.c:267
#5  0x00007fd286c91b6e in php_swoole_event_wait () at /root/workspace/swoole-1.7.20/swoole_event.c:165
#6  0x00007fd286c9403d in php_swoole_process_start (process=<value optimized out>, object=0x14fdea8) at /root/workspace/swoole-1.7.20/swoole_process.c:444
#7  0x00007fd286c94cf8 in zim_swoole_process_start (ht=<value optimized out>, return_value=0x14fdfb8, return_value_ptr=<value optimized out>, this_ptr=0x14fdea8, 
    return_value_used=<value optimized out>) at /root/workspace/swoole-1.7.20/swoole_process.c:477
#8  0x0000000000862223 in zend_do_fcall_common_helper_SPEC (execute_data=<value optimized out>) at /root/workspace/php-5.5.22/Zend/zend_vm_execute.h:550
#9  0x0000000000853aa0 in execute_ex (execute_data=0x7fd28d71d2b8) at /root/workspace/php-5.5.22/Zend/zend_vm_execute.h:363
#10 0x00000000007df799 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /root/workspace/php-5.5.22/Zend/zend.c:1327
#11 0x0000000000781239 in php_execute_script (primary_file=0x7fff49850ab0) at /root/workspace/php-5.5.22/main/main.c:2506
#12 0x000000000089035c in do_cli (argc=2, argv=0x11af220) at /root/workspace/php-5.5.22/sapi/cli/php_cli.c:994
#13 0x0000000000890af8 in main (argc=2, argv=0x11af220) at /root/workspace/php-5.5.22/sapi/cli/php_cli.c:1378
(gdb) source /home/rd/php-5.5.30/.gdbinit
(gdb) zbacktrace
[0x7fd28d71d2b8] swoole_process->start()  /data/webroot/distribute/src/Dtc/Library/Daemon/Manager.php:64 
[0x7fd28d71d190] Dtc\Library\Daemon\Manager->createDirtributeWorker(object[0x7fd28d755ee0], 20)  /data/webroot/distribute/src/Dtc/Daemon/Master.php:84 
[0x7fd28d71d0a0] Dtc\Daemon\Master->create()  /data/webroot/distribute/src/Dtc/Daemon/Master.php:215

**Comment by matyhtf** [comment]
是否有可以稳定重现的php demo

**Comment by matyhtf** [comment]
请升级到最新版本。
