### ISSUE TITLE
Swoole Websocket Server swoole::Buffer::append

### ISSUE THREAD

**Issue by morvai88** [swoole/swoole-src#4485]
I have an issue with Swoole Websocket Server and Buffer append. I didn't implement Buffer in my code, so I don't know which part of Swoole WS Server use this module.

The error is the following: 
/tmp/pear/temp/swoole/src/memory/buffer.cc:89: void swoole::Buffer::append(const iovec*, size_t, off_t): Assertion `iov[i].iov_len > 0' failed.

I can't reproduce it in dev or test environment just appear in production environment. Did anyone know what can cause this error?

Swoole version: 4.6.6
PHP: 7.4

**Comment by matyhtf** [comment]
Please upgrade to the latest version, it has been resolved
