### ISSUE TITLE
Admin panel in 4.8.1?

### ISSUE THREAD

**Issue by Draghmar** [swoole/swoole-src#4486]
I've noticed that there's some things related to the admin panel. Are there some docs that would explain what's that? Can I check this panel myself somehow?

**Comment by matyhtf** [comment]
You can use it on dashboard.swoole.com and it will be open source in the future

**Comment by Draghmar** [comment]
> You can use it on https://dashboard.swoole.com/ and it will be open source in the future

Wait...how can I use it when it's remote? Is it some kind of demo you have there? How can I actually look at it? I'm quite interested in what this panel can actually bring. Openlitespeed has web management and it's interesting to manage web server this way even though I'm more use to editing files and looking at logs. ;)

**Comment by deminy** [comment]
The admin panel is not to remotely manage a web server; it receives data reported from the web server and show real-time runtime stats of the server.

The idea of this admin panel is similar to New Relic (a PHP extension), except that you have more visibility and more control over the data reported, and the implementation is open-sourced (for now, only the server part is open source; the remote UI part is not yet).

There is a demo video about it: https://www.youtube.com/watch?v=AcQvI_g4Abs

**Comment by Draghmar** [comment]
> There is a demo video about it: https://www.youtube.com/watch?v=AcQvI_g4Abs
Looks very promising! So when can we expect to gets hands on? :D
