### ISSUE TITLE
能否支持一下通过二进制流上传文件

### ISSUE THREAD

**Issue by yunwuxin** [swoole/swoole-src#4499]
header是
```
  'Content-Type'      => 'application/octet-stream',
  'Transfer-Encoding' => 'chunked',
```

可以动态写入到一个临时文件中，这样就可以支持上传大文件了

![image](https://user-images.githubusercontent.com/2168125/142349234-bb31b772-a5f3-4460-9af9-1fbaf8e24137.png)

或者支持下流式读取`php://input`

**Comment by matyhtf** [comment]
`Http\Server`暂时不支持，可以使用`Server`或者`Coroutine\Server`实现。
