### ISSUE TITLE
运行examples/process/async_master.php出现警告

### ISSUE THREAD

**Issue by sbwdlihao** [swoole/swoole-src#450]
## php版本
PHP 7.0.0RC7 (cli) (built: Nov 12 2015 06:44:42) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.4.0beta1, Copyright (c) 2002-2015, by Derick Rethans
## 操作系统
os x yosemite 10.10.5
## swoole
1.7.21
## 运行结果
> /usr/local/Cellar/php70/7.0.0-rc.7/bin/php /Users/sbwdlihao/PhpstormProjects/swoole-src/examples/process/async_master.php
RECV: Worker#0: hello master
RECV: Worker#1: hello master
RECV: Worker#2: hello master
RECV: Worker#3: hello master
RECV: Worker#4: hello master
RECV: Worker#5: hello master
RECV: Worker#6: hello master
RECV: Worker#7: hello master
RECV: Worker#8: hello master
RECV: Worker#9: hello master
RECV: Worker#0: hello master
RECV: Worker#1: hello master
RECV: Worker#2: hello master
RECV: Worker#3: hello master
RECV: Worker#4: hello master
RECV: Worker#5: hello master
RECV: Worker#6: hello master
RECV: Worker#7: hello master
RECV: Worker#8: hello master
RECV: Worker#9: hello master
RECV: Worker#0: hello master
RECV: Worker#1: hello master
RECV: Worker#2: hello master
RECV: Worker#3: hello master
RECV: Worker#4: hello master
RECV: Worker#5: hello master
RECV: Worker#6: hello master
RECV: Worker#7: hello master
RECV: Worker#8: hello master
RECV: Worker#9: hello master
RECV: Worker#0: hello master
RECV: Worker#1: hello master
RECV: Worker#3: hello master
RECV: Worker#2: hello master
RECV: Worker#4: hello master
RECV: Worker#5: hello master
RECV: Worker#6: hello master
RECV: Worker#7: hello master
RECV: Worker#8: hello master
RECV: Worker#9: hello master
RECV: Worker#0: hello master
RECV: Worker#1: hello master
RECV: Worker#3: hello master
RECV: Worker#2: hello master
RECV: Worker#4: hello master
RECV: Worker#5: hello master

> Warning: swoole_process::read(): failed. Error: Resource temporarily unavailable[35] in /Users/sbwdlihao/PhpstormProjects/swoole-src/examples/process/async_master.php on line 10

> Call Stack:
    0.0310     375240   1. swoole_event_wait() UNKNOWN?:0
    4.0179     752128   2. onReceive() /Users/sbwdlihao/PhpstormProjects/swoole-src/examples/process/async_master.php:0
PHP Warning:  swoole_process::read(): failed. Error: Resource temporarily unavailable[35] in /Users/sbwdlihao/PhpstormProjects/swoole-src/examples/process/async_master.php on line 10
    4.0179     752128   3. swoole_process->read() /Users/sbwdlihao/PhpstormProjects/swoole-src/examples/process/async_master.php:10

> RECV: RECV: Worker#6: hello master
RECV: Worker#7: hello master
PHP Stack trace:
PHP   1. swoole_event_wait() UNKNOWN?:0
PHP   2. onReceive() /Users/sbwdlihao/PhpstormProjects/swoole-src/examples/process/async_master.php:0
PHP   3. swoole_process->read() /Users/sbwdlihao/PhpstormProjects/swoole-src/examples/process/async_master.php:10
RECV: Worker#8: hello master
RECV: Worker#9: hello master

原来的代码
```php
swoole_process::signal(SIGCHLD, function(){
    //表示子进程已关闭，回收它
    $status = swoole_process::wait();
    echo "Worker#{$status['pid']} exit\n";
});

//将子进程的管道加入EventLoop
foreach($workers as $process)
{
    swoole_event_add($process->pipe, 'onReceive');
}
```
调整了监听信号的顺序后代码运行成功
```php
//将子进程的管道加入EventLoop
foreach($workers as $process)
{
    swoole_event_add($process->pipe, 'onReceive');
}

swoole_process::signal(SIGCHLD, function(){
    //表示子进程已关闭，回收它
    $status = swoole_process::wait();
    echo "Worker#{$status['pid']} exit\n";
});
```
## 调整代码后的运行结果
> /usr/local/Cellar/php70/7.0.0-rc.7/bin/php /Users/sbwdlihao/PhpstormProjects/swoole-src/examples/process/async_master.php
RECV: Worker#0: hello master
RECV: Worker#1: hello master
RECV: Worker#2: hello master
RECV: Worker#3: hello master
RECV: Worker#4: hello master
RECV: Worker#5: hello master
RECV: Worker#6: hello master
RECV: Worker#7: hello master
RECV: Worker#8: hello master
RECV: Worker#9: hello master
RECV: Worker#0: hello master
RECV: Worker#1: hello master
RECV: Worker#2: hello master
RECV: Worker#3: hello master
RECV: Worker#4: hello master
RECV: Worker#5: hello master
RECV: Worker#6: hello master
RECV: Worker#7: hello master
RECV: Worker#8: hello master
RECV: Worker#9: hello master
RECV: Worker#0: hello master
RECV: Worker#1: hello master
RECV: Worker#2: hello master
RECV: Worker#3: hello master
RECV: Worker#4: hello master
RECV: Worker#5: hello master
RECV: Worker#6: hello master
RECV: Worker#7: hello master
RECV: Worker#8: hello master
RECV: Worker#9: hello master
RECV: Worker#0: hello master
RECV: Worker#1: hello master
RECV: Worker#2: hello master
RECV: Worker#3: hello master
RECV: Worker#4: hello master
RECV: Worker#5: hello master
RECV: Worker#6: hello master
RECV: Worker#7: hello master
RECV: Worker#8: hello master
RECV: Worker#9: hello master
RECV: Worker#0: hello master
RECV: Worker#1: hello master
RECV: Worker#2: hello master
RECV: Worker#3: hello master
RECV: Worker#4: hello master
Worker#34255 exit
RECV: Worker#5: hello master
RECV: Worker#6: hello master
RECV: Worker#7: hello master
RECV: Worker#9: hello master
RECV: Worker#8: hello master
RECV: Worker#0: hello master
RECV: Worker#2: hello master

**Comment by matyhtf** [comment]
`PHP7`需要在程序末尾增加`swoole_event_wait`
