### ISSUE TITLE
Swoole with MSSQL 

### ISSUE THREAD

**Issue by mantsap89** [swoole/swoole-src#4505]
Hi, i want to use swoole for a new project. Is there a way to use swoole with MSSQL? I read in the docs that you have coroutines for MySql, Postgres, Redis. But I didn't find anything about MSSQL.

**Comment by matyhtf** [comment]
MSSQL does not support running with coroutine environment, if you use `Swoole\Server`, you should use task worker to simulate non-blocking/coroutine MSSQL client
