### ISSUE TITLE
在swoole中如何修改宏开关才能使用Linux Native AIO功能？

### ISSUE THREAD

**Issue by fznply** [swoole/swoole-src#451]
======swoole中还提供了Linux Native AIO的支持，是真正的内核层异步并行文件读写，不过需要通过修改宏开关，重新编译才可以使用。========
我有尝试去找swoole_config.h的宏定义，但并不能确定如何修改，希望指点一下。

**Comment by matyhtf** [comment]
swoole_async_set 可以设置异步IO的运行方式。 http://wiki.swoole.com/wiki/page/182.html
