### ISSUE TITLE
After the subprocess was killed, the pipeline read was blocked and did not exit

### ISSUE THREAD

**Issue by fengzhibin** [swoole/swoole-src#4517]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

The read method has no timeout setting. After I simulate that the child process is killed, the parent process still waits and never times out
![QQ图片20211202112902](https://user-images.githubusercontent.com/12097229/144352678-ee482696-7574-4970-ae2e-5dc3acd03a95.png)

![QQ图片20211202112808](https://user-images.githubusercontent.com/12097229/144352629-d6991164-658f-4b09-8a6b-f1a38fceffae.png)
![QQ图片20211202112804](https://user-images.githubusercontent.com/12097229/144352635-4d23fee4-0b62-4807-9b2b-68bc706c0fa2.png)

2. What did you expect to see?
After the child process exits, read unblocks and returns 0

3. What did you see instead?
After the child process is killed, the read method of the parent process is blocked all the time and will not time out

4. What version of Swoole are you using (show your `php --ri swoole`)?
Version => 4.7.1

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux 4efa46a62ec3 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 Linux

PHP 7.4.23

gcc version 9.3.0 (Alpine 9.3.0)

**Comment by purewater2011** [comment]
me too

**Comment by fengzhibin** [comment]
> me too enviroment: Darwin Kernel Version 19.6.0 ![image](https://user-images.githubusercontent.com/6291208/144421016-59fc368e-b06d-49a9-9a78-4437fc233312.png) ![image](https://user-images.githubusercontent.com/6291208/144421074-329d778a-b57c-4b0c-9138-cef7e498c462.png)

I guess this is a persistent bug in the swoole process module. I can't solve it for the time being. I try to start an asynchronous monitoring subprocess signal. If the subprocess exits abnormally, I try to actively close the pipeline. But unfortunately, the pipeline read blocking has the highest priority. Scheduled tasks or other methods can only run after the read blocking is removed

**Comment by 18010099312** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fengzhibin** [comment]
> me too enviroment: Darwin Kernel Version 19.6.0 ![image](https://user-images.githubusercontent.com/6291208/144421016-59fc368e-b06d-49a9-9a78-4437fc233312.png) ![image](https://user-images.githubusercontent.com/6291208/144421074-329d778a-b57c-4b0c-9138-cef7e498c462.png)

https://wiki.swoole.com/wiki/page/799.html
The timeout setting for pipeline reading can be found in the old spool document

![image](https://user-images.githubusercontent.com/12097229/151282831-8a4c163d-e567-4472-a132-6d5cf52ac67a.png)
