### ISSUE TITLE
PHP Notice:  Undefined property: swoole_websocket_server::$connections

### ISSUE THREAD

**Issue by xujiajun** [swoole/swoole-src#452]
大家好，

发现在外网部署应用，使用swoole 的扩展，使用其中的swoole_websocket_server

出现这个错误：
```
PHP Notice:  Undefined property: swoole_websocket_server::$connections
```

PS：swoole 版本： { 1.7.20 }

打印出 swoole_websocket_server 发现 的确 没有connections 属性 (记得这个swoole 早就支持了啊)
```
object(swoole_websocket_server)#1 (6) {
  ["global":"swoole_http_server":private]=>
  int(0)
  ["master_pid"]=>
  int(24434)
  ["manager_pid"]=>
  int(24435)
  ["worker_id"]=>
  int(0)
  ["taskworker"]=>
  bool(false)
  ["worker_pid"]=>
  int(24437)
}
```

哪一位大侠  给我指点下。在线等。thanks.

**Comment by matyhtf** [comment]
缺少pcre库，所以无法使用connections迭代器。

**Comment by JokerBruceChan** [comment]
@xujiajun 你好，你解决了这个问题吗？ @matyhtf 老大，为什么我 Ubuntu 的系统通过 apt-get install libpcre3 libpcre3-dev 安装了pcre 库，重新编译 swoole ，还是出现这个问题呢？

**Comment by xujiajun** [comment]
@JokerBruceChan     我已经解决了
