### ISSUE TITLE
macOS Monterey系统下安装swoole失败

### ISSUE THREAD

**Issue by etoup** [swoole/swoole-src#4540]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

在mac最新系统（macOS Monterey）下安装swoole失败，具体操作如下：

命令：sudo /usr/local/opt/php@7.4/bin/phpize ./configure --enable-openssl --enable-http2

报错信息：
configure.ac:18: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
build/php.m4:2110: PHP_CONFIG_NICE is expanded from...
configure.ac:18: the top level
config.m4:335: warning: The macro `AC_PROG_CC_C99' is obsolete.
config.m4:335: You should run autoupdate.
./lib/autoconf/c.m4:1659: AC_PROG_CC_C99 is expanded from...
config.m4:335: the top level
configure.ac:161: warning: The macro `AC_LANG_C' is obsolete.
configure.ac:161: You should run autoupdate.
./lib/autoconf/c.m4:72: AC_LANG_C is expanded from...
build/libtool.m4:2727: _LT_AC_LANG_C_CONFIG is expanded from...
build/libtool.m4:2726: AC_LIBTOOL_LANG_C_CONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: The macro `AC_LANG_C' is obsolete.
configure.ac:161: You should run autoupdate.

2. What did you expect to see?
希望正常编译安装。

**Comment by matyhtf** [comment]
日志不完整，请找到 error 项，warning 不影响编译

**Comment by etoup** [comment]
好的，谢谢
