### ISSUE TITLE
Breaking change on `Table` class v4.8.4

### ISSUE THREAD

**Issue by nunomaduro** [swoole/swoole-src#4545]
Seems that the version [v4.8.4](https://github.com/swoole/swoole-src/compare/v4.8.3...v4.8.4) introduces breaking changes on the class `Table`, causing errors on projects that rely on the type definition of that class: https://github.com/laravel/octane/issues/446.

One example is the method `Table::column` that no longer haves the same type API:

```
PHP Fatal error:  SwooleTable::column($name, $type, $size = 0) must be compatible with Swoole\Table::column(string $name, int $type, int $size = 0): bool.
```

**Comment by ValiDrv** [comment]
That's a PHP 8.1 thing, which should probably be fixed in laravel/octane.

https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.core.type-compatibility-internal

Since Swoole 4.8.4 works on PHP 8.1, it also has the same backward incompatible changes.

**Comment by matyhtf** [comment]
@nunomaduro @ValiDrv We will revert this commit with version 4.8.5

**Comment by mahkassem** [comment]
@nunomaduro 
It was solved for me when I removed the Typing from tow method in :
`vendor/laravel/octane/src/Tables/OpenSwooleTable.php`

Line 26:
![image](https://user-images.githubusercontent.com/12067112/146843370-a5bbc741-818c-4f07-82a4-91f001d4ea7a.png)
Line 40:
![image](https://user-images.githubusercontent.com/12067112/146843447-19ee058d-2fd2-48ce-a60a-b2d002cb3c9b.png)

This is a temporary solution for the problem.

**Comment by nunomaduro** [comment]
@matyhtf Sorry to ask, but do you have an ETA for the 4.8.5 release?

**Comment by matyhtf** [comment]
@nunomaduro Before this weekend.

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/685aebe9dc8496181ba2ae22632266b3954d3eb5
https://github.com/swoole/swoole-src/commit/31e9b3006f2da282bd77cdd7e14ef270b5cc51ba
