### ISSUE TITLE
加载swoole扩展错误

### ISSUE THREAD

**Issue by javacty** [swoole/swoole-src#455]
Fedora 24 
icc 16
mysql  Ver 15.1 Distrib 10.1.8-MariaDB, for Linux (x86_64) using readline 5.1
[root@f23s lib]# php -i|grep swoole
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/php7_icc/lib/php/extensions/no-debug-non-zts-20151012/swoole.so' - /opt/php7_icc/lib/php/extensions/no-debug-non-zts-20151012/swoole.so: undefined symbol: zif_swoole_mysql_query in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/opt/php7_icc/lib/php/extensions/no-debug-non-zts-20151012/swoole.so' - /opt/php7_icc/lib/php/extensions/no-debug-non-zts-20151012/swoole.so: undefined symbol: zif_swoole_mysql_query in Unknown on line 0

**Comment by yangchaogit** [comment]
make distclean

重新编译安装

Sent from my iPhone

**Comment by kakuchichi** [comment]
少了个点吧？
extension=swoole.so吧

发自我的 iPhone

**Comment by javacty** [comment]
谢谢，make distclean后，gcc可以编译，加载也正常，
icc编译报错：
 icc -I. -I/opt/swoole-src -DPHP_ATOM_INC -I/opt/swoole-src/include -I/opt/swoole-src/main -I/opt/swoole-src -I/opt/php7_icc/include/php -I/opt/php7_icc/include/php/main -I/opt/php7_icc/include/php/TSRM -I/opt/php7_icc/include/php/Zend -I/opt/php7_icc/include/php/ext -I/opt/php7_icc/include/php/ext/date/lib -I/opt/swoole-src/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /opt/swoole-src/swoole_timer.c  -fPIC -DPIC -o .libs/swoole_timer.o
": internal error: 010101_14247

compilation aborted for /opt/swoole-src/swoole_timer.c (code 4)
Makefile:208: recipe for target 'swoole_timer.lo' failed
make: *** [swoole_timer.lo] Error 1

**Comment by matyhtf** [comment]
暂不支持icc
