### ISSUE TITLE
swoole::String reserve  bug

### ISSUE THREAD

**Issue by ICE-AGE-X** [swoole/swoole-src#4553]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
product  swoole  websocket server  worker onmessage crash

2. What did you expect to see?
worker carsh with core.dump

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.7
Built => Sep 28 2021 09:15:41
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux *** 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.3.5 (cli) (built: May  6 2019 11:38:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Sdebug v2.9.3-dev, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.3.5, Copyright (c) 1999-2018, by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

补充：
我们用的是swoole 4.5.7 版本，swoole_websocket_server.cc 579行，使用了默认构造的swoole::String send_frame ,在ping帧数据过长发生swoole::String reserve 的时候 string.cc 132 行的allocator为nullptr  从而崩溃

![bug](https://user-images.githubusercontent.com/6221654/147205276-856a339f-b89c-4a2b-a17e-e5e9e7edfd1a.png)

**Comment by NathanFreeman** [comment]
可以提供一下代码以供复现该bug使用吗

**Comment by ICE-AGE-X** [comment]
> 可以提供一下代码以供复现该bug使用吗

这个bug 是在我们生产环境 出现的，我们也在尝试复现， 出现的频率也不是很高，我们复现之后会尽快提交过来
还有就是我们使用的是websocket server，但是在swoole的配置中开启了 
        'open_eof_check' => true, 
        'package_eof' => '\r\n',
        'open_eof_split' => true, 
这三个选项，是不是这三个配置引起的呢？

**Comment by twose** [comment]
应该先试试升级版本到最新，可能是已经修过的BUG

**Comment by matyhtf** [comment]
Fixed in the latest version
