### ISSUE TITLE
How to check swoole is up and running ?

### ISSUE THREAD

**Issue by foremtehan** [swoole/swoole-src#4561]
Hey there, How can i determine the swoole http server is up and running ? I have two servers both of them have swoole extension but only one of them actually uses swoole, the `extension_loaded('swoole')` is useless in my case

**Comment by NathanFreeman** [comment]
swoole_set_process_name() can rename process.
You can determine the swoole http server is up and running by their name.

**Comment by twose** [comment]
But why would you enable the Swoole extension on a server that does not use Swoole?
