### ISSUE TITLE
可否在下一版官方提供的cgywin-swoole中增加php支持redis扩展呀？

### ISSUE THREAD

**Issue by huangdeai** [swoole/swoole-src#4567]
可否在下一版官方提供的cgywin-swoole中增加php支持redis扩展呀？
目前cgywin-swoole-4.8.5如何进行增加redis扩展支持？

**Comment by matyhtf** [comment]
@sy-records

**Comment by sy-records** [comment]
Cygwin 编译 Redis 的时候会有一些符号导出的问题，目前没什么好的想法来支持。

![image](https://user-images.githubusercontent.com/33931153/149611977-e169778e-0ec4-4b53-9a67-16cb74b31a04.png)

@dixyes 这边给出的办法是抛弃 cygwin，使用 msys 来重构下

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/releases/download/v4.8.7/swoole-cli-v4.8.7-cygwin64.zip

请使用 swoole-cli
