### ISSUE TITLE
php8.10 swoole 4.8.5 JS上传文件到服务端偶尔会失败。nginx +swoole 前端js 后端swoole

### ISSUE THREAD

**Issue by tomzhaogy** [swoole/swoole-src#4571]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by tomzhaogy** [comment]
[root@35841e1e4240 /]# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.5
Built => Jan  4 2022 09:31:44
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by tomzhaogy** [comment]
[root@35841e1e4240 /]# php --version 
PHP 8.1.0 (cli) (built: Dec 29 2021 06:12:59) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies

**Comment by NathanFreeman** [comment]
请尝试将nginx的一些超时参数调整大一点

**Comment by tomzhaogy** [comment]
一直pending中过了好久才返回504

**Comment by NathanFreeman** [comment]
504就是超时，可能是程序执行时间过久，nginx的超时时间太短

**Comment by tomzhaogy** [comment]
偶尔出现这个问题，升级到4.8.5，PHP 8.1版本才出的这个问题。

**Comment by tomzhaogy** [comment]
偶尔出现这个问题，升级到4.8.5，PHP 8.1版本才出的这个问题。

**Comment by matyhtf** [comment]
@tomzhaogy 查看一下 `dmesg -T` 的信息，是否有 crash，8.1 可能存在某些兼容性问题

**Comment by tomzhaogy** [comment]
@matyhtf 步子迈大了又扯着蛋了，先退会php 7.4.27,谢谢哈。

**Comment by tomzhaogy** [comment]
php 7.4.27 swoole 4.8.5 也不行 @matyhtf

**Comment by tomzhaogy** [comment]
public function voice_to_text_pc($request,$response){
        $cur_day=date("Ymd",time());
        $this->create_record_path($cur_day);

       
        if (isset($request->get)) {
            $request_data=$request->get;
        } else  if (isset($request->post)) {
            $request_data=$request->post;
        } else {
            return json_encode(array('result' => 1, 'msg' =>$this->get_err_msg(1)));
        }

        $session_id=$request_data["session_id"];
        $language=$this->get_language($session_id);
        $queue_name="VOICE_TO_TEXT_QUEUE";
        if ($language!="PTH") {
            $queue_name="VOICE_TO_TEXT_{$language}_QUEUE";
        }
        $this->info(__CLASS__,__FUNCTION__,$queue_name);

        try {
            $files=$request->files;
            $files=$files['file'];
            if (is_null($files)) {
                return json_encode(array('code' => 1, 'msg' => $this->get_err_msg(1)));
            }

            if (!isset( $files["name"]) || !isset( $files["tmp_name"]))
            {
                return json_encode(array('code' => 1, 'msg' => $this->get_err_msg(1)));
            }

            $job_id=GUID::create();
            $filename = basename($files['name']);
            $tmpname = $files['tmp_name'];
            $size=$files['size'];
            if ($size==0) {
                return json_encode(array('code' =>4, 'msg' => $this->get_err_msg(4)));
            }
            if (move_uploaded_file($tmpname,$this->file_path."wav/source/$cur_day/".$job_id.".wav")) {                
                $file_size=filesize($this->file_path."wav/source/$cur_day/".$job_id.".wav");
                if ($file_size!=$size) {
                    echo "job_id={$job_id}  wav size={$size} recv file size={$file_size}\r\n";
                    return json_encode(array('code' => 5, 'msg' => $this->get_err_msg(5)));
                }
                $start_time=$this->getMillisecond();        
                $model=$this->get_model_default();
                $model_id="";
                if (!is_null($model)) {
                    $model_id=$model["model_id"];
                }
                $message = array("job_id"=>$job_id,"model_id"=>$model_id,"format"=>"wav",'file_name' =>$this->file_path."wav/source/$cur_day/".$job_id.".wav",
                    'file_name_wav' =>$this->file_path."wav/source/$cur_day/".$job_id.".wav",'file_name_record' =>$this->file_path."record/$cur_day/".$job_id.".mp3",
                    "file_link"=>$this->ai_voice_web."/wav/source/$cur_day/".$job_id.".wav","record_url"=>$this->ai_voice_web."/record/$cur_day/".$job_id.".mp3",
                    "finish"=>3,"create_time"=>$start_time,"file_size"=>$size,"recv_size"=>$file_size);
                $str_key="voice_to_text_".$job_id;
                //send kafka
                $this->send_message($queue_name,$message);
                $message["user_data"]=json_encode($request_data);
                $this->info(__CLASS__,__FUNCTION__,$message);
                $this->set($str_key,json_encode($message));
                return json_encode(array('code' => 0, 'msg' => "OK",'data' => array('job_id' =>$job_id)));
            }
        } catch (\Exception $ex) {
            echo __CLASS__."  ".__FUNCTION__."   ".__LINE__."\r\n";
            echo $ex->getMessage();
        }

        return json_encode(array('code' => 2, 'msg' => $this->get_err_msg(2)));
    }

**Comment by tomzhaogy** [comment]
代码如上。直接没进函数。偶然失败时候  js 端 一直penging 中

**Comment by NathanFreeman** [comment]
请问前端用的是vue吗，是的话检查一下看看是不是axios设置了超时时间。
如果不是的话麻烦上传一下nginx的配置文件，注意隐藏ip之类的敏感信息。

**Comment by tomzhaogy** [comment]
[root@3908955c0ea7 /]# php --version
PHP 7.3.5 (cli) (built: Aug 19 2019 00:51:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies

swoole

swoole support => enabled
Version => 1.9.0
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

**Comment by tomzhaogy** [comment]
上面这个环境试正常的。

**Comment by matyhtf** [comment]
检查一下 swoole 的 log_file 中是否输出了错误信息
