### ISSUE TITLE
编译源码  php.ini 加载swoole.so  提示 Extension 'swoole' not present.

### ISSUE THREAD

**Issue by zsboss** [swoole/swoole-src#4575]
![image](https://user-images.githubusercontent.com/19493235/149652795-9817fc4e-620e-4106-916a-fc8694232c90.png)
swoole源码的版本 4.8.5
swoole.so 正常编译成功，但是php --ri swoole  提示   Extension 'swoole' not present.
pecl 安装swoole的时候 可以正常加载 使用

系统为：mac m1  
gcc:
`Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

**Comment by matyhtf** [comment]
如果 php 是 x86 模式的，swoole.so 需要使用 x86 架构，建议在其他 x86 mac 的机器上编译好，复制到 m1 机器。

或者在 m1 的机器上编译 php 和 swoole ，全部为 arm64 架构
