### ISSUE TITLE
[Task] Too few arguments to function {closure}(), 2 passed and exactly 4 expected

### ISSUE THREAD

**Issue by Draghmar** [swoole/swoole-src#4576]
So I wanted to try the Tasks, to see how they work and how I could use them. I tried a simplest thing possible:
```php
	$srv->on('Task', function($srv, $tid, $rid, $data) {
		var_dump($tid);
		var_dump($rid);
		var_dump($data);
	});

	$srv->on('Finish', function($srv, $tid, $data) {

	});

	$srv->on('request', function($request, $response) use ($srv) {
		$srv->task((object) ['test'=>1, 'x'=>2],-1,function($srv, $tid, $data) {

		});
	});
```
And with that set up I'm getting:
```
Too few arguments to function {closure}(), 2 passed and exactly 4 expected
```
at line with task defined: `$srv->on('Task', function($srv, $tid, $rid, $data)`.
What am I doing wrong here?

**Comment by leocavalcante** [comment]
Did you enabled `task_enable_coroutine` or `task_use_object`?

Because when you do, the `onTask` listener signature changes to:
```php
function (Swoole\Server $server, Swoole\Server\Task $task): mixed
```

**Comment by Draghmar** [comment]
Oh, yeah. I did enable `task_enable_coroutine` to see what I could do with it. I didn't notice in the Task docs that it will change the `onTask` event. Now I found it in the configuration docs for the server itself. Thanks!
