### ISSUE TITLE
swoole_http_server onRequest里调用 $server->taskwait()方法存在内存泄漏呀

### ISSUE THREAD

**Issue by xiaoshen** [swoole/swoole-src#458]
swoole 1.7.21版本

我的想法是用task进程做 数据库连接池，然后在onRequest方法里 $server->taskwait() 发送一些请求到task进程里进行一些orm操作，然后我就用 pmap -d 进程号打印worker进程的内存使用情况，发现会狂飙。task进程倒没什么内存问题。

**Comment by matyhtf** [comment]
我这里使用最新的1.7.22进行测试，没有发现内存泄漏。你可以循环执行1000次，观察内存是否持续上涨。

**Comment by xiaoshen** [comment]
嗯，可以了。
