### ISSUE TITLE
Event::set() not working correctly

### ISSUE THREAD

**Issue by ging-dev** [swoole/swoole-src#4584]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
<?php

use Swoole\Event;

$fd = \STDIN;
Event::add($fd, function ($fd) {
    echo 'We get here', PHP_EOL;
    $status = Event::set($fd, null, null, SWOOLE_EVENT_READ);
    var_dump($status);
}, null, SWOOLE_EVENT_READ);

Event::wait();
```

2. What did you expect to see?
`$read_callback` has been replace by null

3. What did you see instead?
The previous callback still executes

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.5
Built => Dec 31 2021 08:50:08
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1f  31 Mar 2020
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Ubuntu 20.04, PHP 8.0

**Comment by NathanFreeman** [comment]
When the callback param is null, it means that the callback function would not be modified.

**Comment by ging-dev** [comment]
> When either the read or write callback are set to null, nothing is modified.

Looks like I made a mistake reading the documentation. Will `Event::del()` remove only `read_callback` in this case?, if it clears `write_callback`, what should I do to remove only `read_callback`?

```php
Event::add($fd, function ($fd) {
    Event::del($fd);
}, function ($fd) {...}, ....);
```

**Comment by NathanFreeman** [comment]
Event::del means remove socket so it will remove both of read and write callback function.
