### ISSUE TITLE
Upload still limited even with size_t change.

### ISSUE THREAD

**Issue by Atomzwieback** [swoole/swoole-src#4586]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

I tried to upload a file larger than 4GB via swoole and it seems like it causes some kind of error. Seems like you changed the int to size_t which should allow uploads as large as the memory of the host machine is but that is not the case. May there are parts in the code that can not handle a big size_t

2. What did you expect to see?

I expect swoole to allow uploads as big as the memory is.

3. What did you see instead?

We have a size limit about 4GB, i expect this not to be the case and be able to upload files as big as my memory is.

4. What version of Swoole are you using (show your php --ri swoole)?

swoole‑4.8.6

5. What is your machine environment used (show your uname -a & php -v & gcc -v) ?

Linux 5.4.0-81-generic Ubuntu SMP  x86_64 GNU/Linux

PHP 8.1.1 (cli) (built: Dec 21 2021 20:02:26) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies

gcc version 8.3.0

**Comment by NathanFreeman** [comment]
I will try to reproduce the error as soon as possible.

**Comment by deminy** [comment]
Swoole is an excellent choice to handle intensive, non-blocking IO operations, but not for CPU-intensive or memory-intensive tasks. It's better to use PHP-FPM instead to handle large file upload.

**Comment by NathanFreeman** [comment]
To keep memory from being exhausting, the Maximum package_max_length was limited to 4GB(UNIT32_MAX).
You can try broken-point continuingly-transferring scheme of large files.

**Comment by Atomzwieback** [comment]
> Swoole is an excellent choice to handle intensive, non-blocking IO operations, but not for CPU-intensive or memory-intensive tasks. It's better to use PHP-FPM instead to handle large file upload.

But the upload is only a small part of my application, the rest needs the speed of swoole and i guess im not able split my application in fpm and swoole

**Comment by matyhtf** [comment]
The current implementation of uploading files all use memory to store data. 

If the uploaded file is too large, it may take up a lot of memory. In the future, we will consider writing data to disk. At that time, it is possible to upload files exceeding 4G.

**Comment by ArthurPatriot** [comment]
> The current implementation of uploading files all use memory to store data.
> 
> If the uploaded file is too large, it may take up a lot of memory. In the future, we will consider writing data to disk. At that time, it is possible to upload files exceeding 4G.

Any updates here? Swoole use a lot of memory when upload files. Can they store temp files to drive?
