### ISSUE TITLE
\swoole_server::reload()方法有一定机率报错

### ISSUE THREAD

**Issue by andares** [swoole/swoole-src#459]
我这边记到的日志如下：

    [2015-12-30 17:38:15 $26695.0]	NOTICE	Server is reloading now.
    [2015-12-30 17:38:15 $26695.0]	WARN	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11
    
    [2015-12-30 17:38:15] Worker error: 0 - 0

某个worker会莫名报错，同时workerError事件中也没有$worker_id和$exit_code，传入的$server也是空的（之前会在这里打印$server->worker_pid，结果会导致更严重的错误）。

之后会少掉一个worker，manager也不会再启一下，整个服务架构似乎就运作不正常了。

如果再尝试用client发消息要求reload或是stop（我有一个专门监听本地请求的端口用于管理服务），会返回：

    ➜  ~  swtry --debug reload
     * Check PHP version ......... 5.6.16 - OK.
     * Check Swoole version ...... 1.7.21 - OK.
    << Launcher prepare fail: swoole_client::recv(): recv() failed. Error: Resource temporarily unavailable [11]
    ➜  ~  swtry --debug stop  
     * Check PHP version ......... 5.6.16 - OK.
     * Check Swoole version ...... 1.7.21 - OK.
    << Launcher prepare fail: swoole_client::recv(): recv() failed. Error: Resource temporarily unavailable [11]

fail:后面的文字是swoole_client的输出。

这个问题偶尔会出现，运行环境上面有显示。代码是phar打包的，不过当时reload的时候确认phar包没有更新过（设计时也不考虑phar包更新后swoole进程实时reload更新，这个不靠谱）。

Rango能看看可能是什么原因导致的么。

**Comment by matyhtf** [comment]
开启core dump，找到core文件，使用gdb观察调用栈。
http://wiki.swoole.com/wiki/page/10.html

**Comment by andares** [comment]
好，我先赶个公司进度，现在主要就是reload这块存在问题，而且是偶发性的（机率大约50%吧），开发阶段还能用，之后弄下core dump出来。现在用了phar打包，这块坑还不少。

**Comment by andares** [comment]
[gdb.txt](https://github.com/swoole/swoole-src/files/98797/gdb.txt)

不好意思弄晚了，目前试了几次reload，gdb出来的信息都是一致的。

**Comment by matyhtf** [comment]
可能是由定时器问题导致的，请使用最新的github master代码测试一下，看看是否可以重现。

**Comment by andares** [comment]
线上试了几次未出现该问题，先关掉了。

**Comment by chg365** [comment]
这个问题能解决吗？我是在stop，然后再start时，报的这个错。好像得重启机器才能正常。
