### ISSUE TITLE
SWOOLE_PROCESS模式下上传文件无响应问题

### ISSUE THREAD

**Issue by Mr-ZhongWeiWei** [swoole/swoole-src#4591]
![image](https://user-images.githubusercontent.com/23732151/151472014-3bbb5b39-0e02-437d-b328-2f502678f6fa.png)
不知道什么原因导致上传文件超时 检查过了nginx、php、package_max_length配置都没有问题，日志只有上面那个。是否需要某些配置还是使用的姿势不对？

**Comment by NathanFreeman** [comment]
检查一下max_request是不是设置太小了

**Comment by Mr-ZhongWeiWei** [comment]
@NathanFreeman 
![image](https://user-images.githubusercontent.com/23732151/151474238-0cec82df-a5ca-4115-a048-97f2470b4e6d.png)

**Comment by Mr-ZhongWeiWei** [comment]
@NathanFreeman 本地环境 只要上传文件就会超时 然后就报这个错误

**Comment by NathanFreeman** [comment]
文件是断点续传的方式上传的吗？

**Comment by Mr-ZhongWeiWei** [comment]
@NathanFreeman 不是 就是普通的上传  大小在50k左右基本都能上传成功  更大一点都是会超时

**Comment by Yurunsoft** [comment]
如果是wsl1上传文件是有bug的

**Comment by Mr-ZhongWeiWei** [comment]
@NathanFreeman 重启一下swoole后 首次上传一百多K大小的也能上传成功  第二次开始就还是会超时

**Comment by Mr-ZhongWeiWei** [comment]
@Yurunsoft  ？？ WSL环境不行吗

**Comment by Yurunsoft** [comment]
wsl1可能有bug，上传大文件是会失败的，如果有强迫症一定要本地调试成功，可以用wsl2

**Comment by Mr-ZhongWeiWei** [comment]
@Yurunsoft 关键是我上传的都是几百K的文件.....   系统升级到win11之后好像才出现这个问题的 之前win10是正常的

**Comment by Yurunsoft** [comment]
在 Windows 下执行：`wsl -l -v`
看一下是否是版本1

**Comment by Mr-ZhongWeiWei** [comment]
@Yurunsoft 是1
![image](https://user-images.githubusercontent.com/23732151/151475928-68b38253-65a4-462d-9e28-2e1ce0fc10df.png)
那我升级一下试试看

**Comment by Yurunsoft** [comment]
我也是用的1，需要用到上传的场景很少，所以一直没用2。。。2的ip和端口映射比较麻烦

**Comment by matyhtf** [comment]
@Mr-ZhongWeiWei WSL1 有 bug，unixsock 多进程事件会丢失，建议使用 wsl2 或者 linux 虚拟机
