### ISSUE TITLE
[Feature Request] add `max_request_execution_time` config to HTTP server

### ISSUE THREAD

**Issue by smortexa** [swoole/swoole-src#4594]
Related to laravel/octane#470.

When the execution time for requests being handled by Octane exceeded from `max_execution_time` in the `octane.php` config file, the Octane wouldn't send any response and the request remains in the pending state. According to @sy-records, when the `max_execution_time` is reached, A `SIGKILL` signal is sent directly, so it causes no response and requires Swoole support.

It will be good if Swoole adds `max_request_execution_time` config to the HTTP server like what OpenSwoole added [here](https://openswoole.com/docs/modules/swoole-server/configuration#max_request_execution_time).

**Comment by ValiDrv** [comment]
Maybe it should not kill the process tho.

It would be more useful to have a coroutine max run time ( where it would stop and shutdown the coroutine, not just yield). That could be used as max_request_execution_time

**Comment by matyhtf** [comment]
This just closes the connection early, but cannot terminate the coroutine that is processing the http request.

You can use php code to implement, set a timer, and close the connection when timeout.

```php
$server->on("Request", function ($req, $resp) {
    $max_request_execution_time = 1000; // 1s
    Swoole\Timer::after($max_request_execution_time, function () use ($resp) {
        $resp->end();
    });
});
```

**Comment by smortexa** [comment]
It still does not work. The following error is thrown:
```
PHP Fatal error:  Uncaught ErrorException: Swoole\Http\Response::status(): http response is unavailable (maybe it has been ended or detached)
```
