### ISSUE TITLE
希望\swoole_server::start()可以传入回调方法

### ISSUE THREAD

**Issue by andares** [swoole/swoole-src#460]
现在swoole server启的时候，一旦start()，fork出新进程后原进程就die掉了似乎。

如果启动时要做一些友好性的设计会比较麻烦，希望能在之后版本加一个回调，例如：

    $swoole_server->start(function($errcode) {
        if ($errcode) {echo "fail: $errcode";} else {echo 'success';}
    })；

类似这样，对做封装会更友好。

**Comment by matyhtf** [comment]
设置onStart回调

**Comment by andares** [comment]
主要问题是我封装成一个命令行执行文件了，一旦swoole::start()后，原命令行执行的进程被die了，之后即使设置start事件，也已经是运行在fork出去的master进程里，那里echo只会输出到swoole.log。而因为命令行进程被终结，也无法再行从外部检查进程是否正常启动，也不可能再输出信息到终端提示用户服务已经启了。

**Comment by smalleyes** [comment]
可以保存pid,根据pid获取信息
