### ISSUE TITLE
CURLOPT_SHARE option is not supported

### ISSUE THREAD

**Issue by brightlycolor** [swoole/swoole-src#4606]
My symfony/http-client always return me warning ***ErrorException: Warning: curl_setopt(): CURLOPT_SHARE option is not supported***. Are swoole support this CURL option?
___________

bash-5.1# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.6
Built => Jan 12 2022 05:41:58
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1l  24 Aug 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

Linux a4532ea459e5 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 Linux

PHP 8.0.14 (cli) (built: Dec 18 2021 21:57:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.14, Copyright (c), by Zend Technologies

bash: gcc: command not found  :) its inside Docker container

**Comment by leocavalcante** [comment]
I'm afraid it is not supported. This warning is actually from Swoole itself: https://github.com/swoole/swoole-src/blob/master/thirdparty/php/curl/interface.cc#L1753

**Comment by matyhtf** [comment]
@brightlycolor @leocavalcante I'm working on it, will be supported in the next version (4.8.7)

https://github.com/swoole/swoole-src/tree/support-curl-share

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/4831e3ff16291bb1dcf219db93cfe6075bc3c946
