### ISSUE TITLE
swoole.so.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by veleg** [swoole/swoole-src#4607]
Tell me. Installed phpize, gcc, db, php, php-dev, curl. 
Then I installed pecl install swoole. 
Added a line to php.ini: extension=swoole.so . 
An error pops up. 
Also added in php.ini extension=/path/swoole.so and still an error
```
# php -m|grep swoole
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/lib/php/20170718/swoole.so 
(/usr/lib/php/20170718/swoole.so: undefined symbol: json_globals), /usr/lib/php/20170718/swoole.so.so
 (/usr/lib/php/20170718/swoole.so.so: cannot open shared object file: No such file or directory)) 
in Unknown on line 0
```

**Comment by leocavalcante** [comment]
Make sure that `extension=swoole.so` is **after** the JSON extension.

**Comment by veleg** [comment]
the json field in php.ini?
It should look like this:
`json
extension=swoole.so` ?

**Comment by leocavalcante** [comment]
Try creating an `ext-swoole.ini` file at your `etc/php/8.0/conf.d` instead of editing the `php.ini`.

What is your OS and how did you install PHP?

For example, in Ubuntu using `apt install php8.0`, you can create a `swoole.ini` file at `/etc/php/8.0/mods-available`  then use `phpenmod swoole`.
