### ISSUE TITLE
关于swoole-cli swoole的配置修改

### ISSUE THREAD

**Issue by shimianxiang** [swoole/swoole-src#4610]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

```
使用 v4.8.6 swoole-cli 启动hyperf时
 ./swoole-cli bin/hyperf.php start
```

2. What did you expect to see?

**v4.8.6  swoole-cli怎么修改swoole的配置呀？
例如 swoole.use_shortname 修改为 Off**

3. What did you see instead?

**需要关闭 swoole.use_shortname**
`ERROR Swoole short function names must be disabled before the server starts, please set swoole.use_shortname='Off' in your php.ini.`

4. What version of Swoole are you using (show your `php --ri swoole`)?
./swoole-cli --ri swoole

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.6
Built => Jan 11 2022 11:48:24
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1m  14 Dec 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
c-ares => 1.18.1
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

```

**Comment by leocavalcante** [comment]
`swoole-cli --ini` 的输出是什么?

作为一种解决方法，您可以尝试 `swoole-cli -dswoole.use_shortname=Off bin/hyperf.php`

**Comment by shimianxiang** [comment]
./swoole-cli --ini 的输出是
```
Configuration File (php.ini) Path: /usr/local/lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

```
想要的答案就是这个 `swoole-cli -dswoole.use_shortname=Off bin/hyperf.php `感谢解答
期待swoole5.0 swoole-cli  的正式发布
