### ISSUE TITLE
是否应该启用--enable-mysqlnd？

### ISSUE THREAD

**Issue by Galaxy0419** [swoole/swoole-src#4611]
在[这篇文档](https://wiki.swoole.com/#/environment?id=特殊参数)中，注释声明了

> 如无历史原因不建议启用

但是在[可用hook列表](https://wiki.swoole.com/#/runtime?id=可用列表)里又说只支持

> 使用 mysqlnd 模式的 pdo_mysql、mysqli 扩展，如果未启用 mysqlnd 将不支持协程化

所以想要支持一键化协程支持，是否应该开启--enable-mysqlnd？

**Comment by NathanFreeman** [comment]
可以不开，但是PHP的扩展一定要有mysqlnd，--enable-mysqlnd是为了swoole自带的MySQL协程客户端使用。

**Comment by Galaxy0419** [comment]
@NathanFreeman 感谢回答，我看文档里关于服务器有异步和协程风格的教学，现在推荐用哪个呢？两者有什么区别？

**Comment by twose** [comment]
不需要开，直接开启hook，用PHP自带的PDO、mysqli即可

这个是历史遗留，为了mysql escape方法用的

**Comment by Galaxy0419** [comment]
@twose 嗯嗯，我看[一键协程文档](https://wiki.swoole.com/#/runtime?id=swoole_hook_tcp)，用了异步+HOOK方式使用HTTP服务器，如果我理解没错的话，这是建议的使用方法么？协程是被这种方法代替了么？

**Comment by NathanFreeman** [comment]
异步服务器还是有使用协程的。
具体可以看看协程风格的服务器有啥优缺点。
https://wiki.swoole.com/#/server/co_init?id=%e7%bc%ba%e7%82%b9%ef%bc%9a

**Comment by twose** [comment]
主流方式是 异步服务器(Swoole\Http\Server) + 其它协程客户端组件
