### ISSUE TITLE
自定义服务类中调用redis异步队列报错

### ISSUE THREAD

**Issue by liziwei123** [swoole/swoole-src#4615]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
登录的时候，返回json字符串前，进行了redis异步队列记录日志，结果redis异步队列卡住报错了，注释掉异步队列就没问题了，
关键代码如下：
```php
        return $this->response->json(apiResponse(200,'登录后台成功'));

        function apiResponse($code = 200, $message = '', $data = [])
        {


            (new PlatformLogService)->add();
            

            return [
                'code' => $code,
                'msg' => $msg,
                'data' => $data
            ];
        }
```

```php
<?php
namespace App\Service;


use App\Service\PlatformLogQueueService;
use Hyperf\Di\Annotation\Inject;

/**
 * 平台日志服务
 * Class PlatformLogService
 * @package App\Service
 */
class PlatformLogService
{


    /**
     * @Inject
     * @var PlatformLogQueueService
     */
    protected $service;


    /**
     * @Inject()
     * @var JWT
     */
    protected $jwt;

    public function add()
    {
         $this->service->push(['uname'=>'abc']);

    }


}


<?php
namespace App\Service;



use App\Job\PlatformLogSaveJob;
use Hyperf\AsyncQueue\Driver\DriverFactory;
use Hyperf\AsyncQueue\Driver\DriverInterface;

/**
 * 平台日志队列服务
 * Class PlatformLogService
 * @package App\Service
 */
class PlatformLogQueueService
{


    /**
     * @var DriverInterface
     */
    protected $driver;


    public function __construct(DriverFactory $driverFactory)
    {
        $this->driver = $driverFactory->get('default');
    }

    public function push($params, int $delay = 0): bool
    {
        return $this->driver->push(new PlatformLogSaveJob($params), $delay);

    }


}


<?php

declare(strict_types=1);

namespace App\Job;


use App\Model\PlatformLog;
use Hyperf\AsyncQueue\Job;

class PlatformLogSaveJob extends Job
{

    public $params;

    /**
     * 任务执行失败后的重试次数，即最大执行次数为 $maxAttempts+1 次
     *
     * @var int
     */
    protected $maxAttempts = 2;

    public function __construct($params)
    {
        // 这里最好是普通数据，不要使用携带 IO 的对象，比如 PDO 对象
        $this->params = $params;
    }

    public function handle()
    {
        // 根据参数处理具体逻辑
        // 通过具体参数获取模型等
        // 这里的逻辑会在 ConsumerProcess 进程中执行

        PlatformLog::create(
            $this->params
        );

    }
}
```

2. What did you expect to see?
不报错,redis异步队列正常执行完毕

3. What did you see instead?
 WARNING Server::check_worker_exit_status(): worker(pid=22167, id=2) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.8.0, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64
GCC_VERSION: 4.8.5 20150623 (Red Hat 4.8.5-44)
OPENSSL_VERSION: OpenSSL 1.0.2k-fips  26 Jan 2017
PHP_VERSION : 7.4.24

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.0
Built => Oct 27 2021 16:43:19
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PHP 7.4.24 (cli) (built: Sep 25 2021 15:55:29) ( NTS )
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by NathanFreeman** [comment]
你好，可以尝试升级到4.8.7检查是否还有该问题，如果问题依旧存在，请执行下面的操作
https://wiki.swoole.com/#/other/issue?id=关于段错误核心转储

**Comment by matyhtf** [comment]
请升级版本后重试，如果依然重现可按照上述步骤提交 issue
