### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by veleg** [swoole/swoole-src#4618]
After installing swoole and adding a line extension=swoole.so in php.ini, a warning pops up. How to fight?
PHP8
`PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/lib/php/20210902/swoole.so (/usr/lib/php/20210902/swoole.so: undefined symbol: zend_class_serialize_deny), /usr/lib/php/20210902/swoole.so.so (/usr/lib/php/20210902/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

**Comment by leocavalcante** [comment]
Try following the suggestions at #4598

**Comment by matyhtf** [comment]
The wrong php-config version or php header file may be used, recommend to clean up the environment and recompile swoole
