### ISSUE TITLE
swoole-cli  缺少扩展 pcntl extension

### ISSUE THREAD

**Issue by houlijiang** [swoole/swoole-src#4625]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

swoole-cli bin/hyperf.php 
Fatal error: Uncaught Hyperf\Di\Exception\Exception: Missing pcntl extension. in /cygdrive/e/web/mwj/mwj-api/vendor/hyperf/di/src/ScanHandler/PcntlScanHandler.php:21
Stack trace:
#0 /cygdrive/e/web/mwj/mwj-api/vendor/hyperf/di/src/ClassLoader.php(79): Hyperf\Di\ScanHandler\PcntlScanHandler->__construct()
#1 /cygdrive/e/web/mwj/mwj-api/bin/hyperf.php(17): Hyperf\Di\ClassLoader::init()
#2 /cygdrive/e/web/mwj/mwj-api/bin/hyperf.php(23): {closure}()
#3 {main}
  thrown in /cygdrive/e/web/mwj/mwj-api/vendor/hyperf/di/src/ScanHandler/PcntlScanHandler.php on line 21

2. What did you expect to see?

希望能启动成功

3. What did you see instead?

Fatal error: Uncaught Hyperf\Di\Exception\Exception: Missing pcntl extension. in /cygdrive/e/web/mwj/mwj-api/vendor/hyperf/di/src/ScanHandler/PcntlScanHandler.php:21
Stack trace:
#0 /cygdrive/e/web/mwj/mwj-api/vendor/hyperf/di/src/ClassLoader.php(79): Hyperf\Di\ScanHandler\PcntlScanHandler->__construct()
#1 /cygdrive/e/web/mwj/mwj-api/bin/hyperf.php(17): Hyperf\Di\ClassLoader::init()
#2 /cygdrive/e/web/mwj/mwj-api/bin/hyperf.php(23): {closure}()
#3 {main}
  thrown in /cygdrive/e/web/mwj/mwj-api/vendor/hyperf/di/src/ScanHandler/PcntlScanHandler.php on line 21

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole 4.8.7 (cli) (built: Feb 24 2022 22:04:09) (NTS)

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

windows 10

**Comment by liangfengyuan** [comment]
同样的问题，hyperf框架目前还用不了。

**Comment by leocavalcante** [comment]
作为一种解决方法，您可以将扫描处理程序设置为基于进程的扫描处理程序 (`ProcScanHandler`)

在 `bin/hyperf.php` 文件中，替换：
```php
Hyperf\Di\ClassLoader::init();
```
以:
```php
Hyperf\Di\ClassLoader::init(null, null, new ProcScanHandler());
// or
Hyperf\Di\ClassLoader::init(handler: new ProcScanHandler());
```

**Comment by liangfengyuan** [comment]
那处理函数处理后，又有新问题了。
ERROR Swoole short function names must be disabled before the server starts, please set swoole.use_shortname='Off' in your php.ini.

swoole-cli 中怎么关掉这个？

**Comment by NathanFreeman** [comment]
> 那处理函数处理后，又有新问题了。 ERROR Swoole short function names must be disabled before the server starts, please set swoole.use_shortname='Off' in your php.ini.
> 
> swoole-cli 中怎么关掉这个？

swoole-cli -dswoole.use_shortname=Off

**Comment by matyhtf** [comment]
4.8.8 版本会增加
