### ISSUE TITLE
希望 swoole-cli增加 libxml2、libxml2-dev、soap、gnupg2、mssql-tools、unixodbc-dev 、 libgssapi-krb5-2  、unixodbc-dev 、sqlsrv 、pdo_sqlsrv、xlswriter、mongodb扩展

### ISSUE THREAD

**Issue by 17797964** [swoole/swoole-src#4628]
希望 swoole-cli增加 libxml2、libxml2-dev、soap、gnupg2、mssql-tools、unixodbc-dev 、 libgssapi-krb5-2  、unixodbc-dev 、sqlsrv 、pdo_sqlsrv、xlswriter、mongodb扩展
【libxml2、libxml2-dev、soap】webservice接口
【gnupg2、mssql-tools、unixodbc-dev 、 libgssapi-krb5-2  、unixodbc-dev 、sqlsrv 、pdo_sqlsrv】mssql数据库
【xlswriter】execl操作
【mongodb】mongodb数据库

dockerfile
FROM phpswoole/swoole:4.6.4-php7.4

RUN \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone && \
    cd /usr/local/bin && \
    ./docker-php-ext-install pdo_mysql  && \
    ./docker-php-ext-install mysqli && \
	 apt-get update && \
	 apt install libxml2 && \
	 apt install -y libxml2-dev && \
	 ./docker-php-ext-install soap

RUN \
apt-get install -y gnupg2 
RUN \
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -    
RUN \
curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list   
RUN \
apt-get update &&  ACCEPT_EULA=Y apt-get -y install msodbcsql17  && ACCEPT_EULA=Y apt-get -y install mssql-tools  
RUN \
apt-get  -y install  unixodbc-dev  
RUN \
apt-get -y install   libgssapi-krb5-2  
RUN \
apt-get  -y install  unixodbc-dev 
RUN \
pecl install  sqlsrv pdo_sqlsrv   
RUN \
curl -fsSL "https://pecl.php.net/get/xlswriter-1.3.4.1.tgz" -o xlswriter.tgz
RUN \
mkdir -p /tmp/xlswriter
RUN \
tar -xf xlswriter.tgz -C /tmp/xlswriter --strip-components=1
RUN \
cd /tmp/xlswriter && \
phpize && ./configure --enable-reader && make && make install
RUN \
curl -fsSL "https://pecl.php.net/get/mongodb-1.12.0.tgz" -o mongodb.tgz
RUN \
mkdir -p /tmp/mongodb
RUN \
tar -xf mongodb.tgz -C /tmp/mongodb --strip-components=1
RUN \
cd /tmp/mongodb && \
phpize && ./configure  && make && make install

**Comment by pro911** [comment]
确实，目前没有使用的原因就是不支持mongodb 而我们的业务严重依赖mongodb

**Comment by leocavalcante** [comment]
@pro911 您可以使用 Hyperf 和 https://github.com/Reasno/fastmongo 尝试 Swoole

**Comment by matyhtf** [comment]
xml、soap 扩展已包含在 swoole-cli，其他扩展暂时不会直接在 swoole-cli 提供，等待 swoole-cli 构建工具开源后，可自行添加

**Comment by zhao186** [comment]
请问什么时候可以开源swoole-cli构建工具呢
