### ISSUE TITLE
simultaneous sending of a message through a channel to all coroutines

### ISSUE THREAD

**Issue by veleg** [swoole/swoole-src#4629]
how can I send messages to all 100 conutins at the same time?
```php
Co\run(function () {

    $chan = new Swoole\Coroutine\Channel(30);
    go(function() use ($chan) {
        $cid = Swoole\Coroutine::getuid();
        $i = 0;
        while (1) {
            //co::sleep(1);
            $chan->push(microtime(True));
            $i++;
			if($i>100){$chan->close();}
        }

    });

	for($k=0;$k<100;$k++){
		
		go(function() use ($chan, $k) {
                    $cid = Swoole\Coroutine::getuid();
                while(1) {
                    $data = $chan->pop();
                    echo "$k $cid. $data\n";
                }
            });
	}

});
```

**Comment by veleg** [comment]
Thank you. Is it possible to somehow transfer to all coroutines using other methods? I tried using Co::usleep(1) from the documentation, in order to somehow reduce the delay, but there is an error that there is no such thing.

**Comment by NathanFreeman** [comment]
There is no such method.
Couroutine is similiar to thread.

**Comment by veleg** [comment]
and if you don't use channels, but use global variables?

**Comment by NathanFreeman** [comment]
I guess you want to create many coroutines to increase concurrency.
You can use `sleep` function to yield coroutine if there is no I/O operation in your program.

**Comment by fakharak** [comment]
> how can I send messages to all 100 conutins at the same time? `Co\run(function () {
> 
> ```
> $chan = new Swoole\Coroutine\Channel(30);
> go(function() use ($chan) {
>     $cid = Swoole\Coroutine::getuid();
>     $i = 0;
>     while (1) {
>         //co::sleep(1);
>         $chan->push(microtime(True));
>         $i++;
> 		if($i>100){$chan->close();}
>     }
> 
> });
> 
> for($k=0;$k<100;$k++){
> 	
> 	go(function() use ($chan, $k) {
>                 $cid = Swoole\Coroutine::getuid();
>             while(1) {
>                 $data = $chan->pop();
>                 echo "$k $cid. $data\n";
>             }
>         });
> }
> ```
> 
> });`

--- My Answer ---
After opening the page below, click Ctrl + F in browser and search the string "parallel()". Also check the technique to create multiple Co-routine Contexts within same Worker Process, also check Coroutine Scheduler. One of them surely solve your use case.
https://openswoole.com/docs/modules/swoole-coroutine-run

For Parallel Processing (which is a little more to Asynchrony), you can also make use of Swoole Process in conjunction with Swoole Coroutine:
https://openswoole.com/docs/modules/swoole-multiprocessing

**Comment by veleg** [comment]
solved the issue by adding usleep(1). It turned out to send messages in 1000 coroutines in 4ms

**Comment by ValiDrv** [comment]
You don't need a channel for this.
`Coroutines` are basically `Generator` functions, where they `yield` every time you do some IO (like `sleep`). So they can share global/static variables. And if those change when their code resumes, then you can take action and exit your loop.

This means you can use some flag to "exit" your coroutines in-between their IO.
**Note:** if you have a sleep 4h in your coroutine, it will exit after those 4h, since that's when it's code will run.

```
<?php

use Swoole\Coroutine\Barrier;

go(function () {
    $run   = true;
    $start = microtime(true);
    go(function () use (&$run) {
        Co::sleep(1);
        $run = false;   # Set your global var.
    });

    $barrier = Barrier::make();
    for ($k = 0; $k < 10000; $k++) {
        go(function () use ($k, &$run, $barrier) {
            do {  # Check your global var
                Co::sleep(0.001);   # Emulate some IO
            } while ($run);
            printf("loop: %4s  cid: %8s @ %s\n", $k, Swoole\Coroutine::getuid(), microtime(true));
        });
    }

    printf("Wait for data...\n");
    Barrier::wait($barrier);
    printf("\n\n END: %.4f sec.\n\n", microtime(true) - $start);
});
```

**Comment by matyhtf** [comment]
If you don't have any io operations, you don't need to use channels at all.

Your program only has memory operations, then you can use php array or splqueue

**Comment by veleg** [comment]
We need one parser and 100 coprograms. When a signal appears in the parser, it is necessary to send a signal to all 100 coroutines so that each of them performs a certain action.

**Comment by ClosetMonkey** [comment]
I hate it when people as me this, but what are you trying to do? I understand the basic idea that a single event/task may need to be processed in multiple unique ways thus more than one coroutine, but 100? By parser do you mean some form of scheduler that may choosing between 100 different coroutines?
