### ISSUE TITLE
开启open_eof_split之后,前面几个请求出错

### ISSUE THREAD

**Issue by poisonbian** [swoole/swoole-src#463]
我开启了这个选项为true之后,出现一个很奇怪的现象:
运行的前几次,抛出错误:
php:(此处路径省略)/swoole-src-swoole-1.7.21-stable/src/memory/RingBuffer.c:182: swRingBuffer_free: Assertion `ptr >= object->memory' failed

日志里面显示
[2015-12-30 19:31:35 #13978.0] WARN swProcessPool_wait: worker#1 abnormal exit, status=0, signal=11
但是接收了几次socket client发来的信息之后就好了...
我的server是这样的:

$server = new swoole_server($host, $port, SWOOLE_BASE, SWOOLE_SOCK_TCP);
$server->set(array(
'worker_num' => 4,
'open_eof_check' => true,
'package_eof' => "\r\n\r\n",
'open_eof_split' => true,
'daemonize' => true,
'log_file' => "某个log路径"
));

最后实在没找到原因,我就把它关掉了,然后在receive的回调函数里面自己切分...

**Comment by matyhtf** [comment]
暂时不要用 ringbuffer，此特性还在实验中。
