### ISSUE TITLE
希望swoole-cli 支持 pcntl 等扩展 可以完美支持hyperf框架在win下开发

### ISSUE THREAD

**Issue by huangdeai** [swoole/swoole-src#4631]
Fatal error: Uncaught Hyperf\Di\Exception\Exception: Missing pcntl extension. in /cygdrive/e/project/vendor/hyperf/di/src/ScanHandler/PcntlScanHandler.php:21
Stack trace:
#0 /cygdrive/e/project/vendor/hyperf/di/src/ClassLoader.php(79): Hyperf\Di\ScanHandler\PcntlScanHandler->__construct()
#1 /cygdrive/e/project/bin/hyperf.php(17): Hyperf\Di\ClassLoader::init()
#2 /cygdrive/e/project/bin/hyperf.php(23): {closure}()
#3 {main}
  thrown in /cygdrive/e/project/vendor/hyperf/di/src/ScanHandler/PcntlScanHandler.php on line 21

**Comment by NathanFreeman** [comment]
PHP8.1在cygwin编译pcntl有一点问题，正在处理中😃。

**Comment by sy-records** [comment]
Duplicate with #4625
