### ISSUE TITLE
When static_handler_locations is set, websocket doesn't receive the "Open" event

### ISSUE THREAD

**Issue by dariofinardi** [swoole/swoole-src#4632]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

I'm setting swoole with the below code
   $server->set([
        'daemonize'=>false,
        'user'=>'pi',
        'chroot'=> tapRoot,
        'pid_file'=> pidFile,
        'open_websocket_protocol' => true,
        'websocket_compression' => true,
        'open_websocket_close_frame' => false,
        'open_websocket_ping_frame' => false, // added from v4.5.4
        'open_websocket_pong_frame' => false, // added from v4.5.4
        'document_root' => htmlFolder,
        'enable_static_handler' => true,
        'http_autoindex' => true,
        'http_index_files' => ['index.html'],
        'static_handler_locations' => ['/', '/js', '/css', '/etc'],
        'log_level' => 0,
        'log_file' => logFile,
    ]);

2. What did you expect to see?

The http server should run accessing to files from /, /js, /css, /etc.
The websocket shall run not affected by above settings.

3. What did you see instead?

When I set static_handler_locations the websocket doesn't receive Open events.
I shall disable the static_handler_locations and move all the static files in the same folder (i.e. "/").

4. What version of Swoole are you using (show your `php --ri swoole`)?

I'm using 4.8.5 with php8.1.3

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

**Comment by dariofinardi** [comment]
Doing more investigation, it seems that the issue is because of below lines:
        'http_autoindex' => true,
        'http_index_files' => ['index.html'],

**Comment by NathanFreeman** [comment]
I will reproduce the error as soon as possible.
Thanks!

**Comment by NathanFreeman** [comment]
Please remove `/` from `static_handler_locations` setting.
Now all requests are treated as static file.
