### ISSUE TITLE
swManager_check_exit_status: worker#15[pid=8757] abnormal exit

### ISSUE THREAD

**Issue by lianran111** [swoole/swoole-src#4634]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

WARNING swManager_check_exit_status: worker#15[pid=8757] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.4.1, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/issues/2000
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

单独调接口是正常，但是前端调用接口有时会出现请求超时，看到的是以上内容

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.1
Built => Jul  4 2021 00:54:55
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

PHP 7.2.34

**Comment by NathanFreeman** [comment]
可以的话，提供一下代码以方便我们复现，或者按照下面的步骤提供调用栈，谢谢
https://wiki.swoole.com/#/other/issue?id=关于段错误核心转储

**Comment by matyhtf** [comment]
@lianran111 4.4.1 版本比较古老了，可能存在一些 bug，建议升级至 4.4.25 最新版本
