### ISSUE TITLE
swoole-cli太棒了，提一些意见。

### ISSUE THREAD

**Issue by etjson** [swoole/swoole-src#4636]
swoole-cli真的很棒，现在项目打包部署出去只要两个文件，一个swoole-cli一个php.phar包，连环境都不用装，非常的方便。

类似于python的pyInstaller，nojde的pkg，但是他们都是单个文件，连项目文件一起打包，**非常的希望swoole-cli后面再构建脚本加一个支持项，可以把项目文件一起打包进去**。

另，祝swoole越做越好。

@NathanFreeman

**Comment by NathanFreeman** [comment]
谢谢夸奖，连同项目文件一起打包已经在计划中了，敬请期待。
详情可以看看Jetbrains在哔哩哔哩上的视频。
https://www.bilibili.com/video/BV1Eb4y1n7xE?from=search&seid=6175609993867647941&spm_id_from=333.337.0.0
twosee 在视频中有详细说明这个。

**Comment by jobsssss** [comment]
swoole-cli不支持mac电脑吗？另外，扩展是否可以包含sdebug这样的调试工具进去？

**Comment by NathanFreeman** [comment]
> 

可以在mac使用，你是在mac上使用遇到问题了吗？
建议使用yasd，https://github.com/swoole/yasd

**Comment by NathanFreeman** [comment]
> 我看swoole-cli目前只有linux版本和cywin版本，并没看到有mac版本的啊？

sorry，我的锅，看错了

**Comment by matyhtf** [comment]
swoole-cli 的定位是 runtime，等于 node 或 php ，java jdk 等等，pyInstaller、node pkg 等是打包工具，是其他层面的工具。

swoole-cli macos 版本会在 4.8.9 版本中支持

**Comment by huangdijia** [comment]
> swoole-cli 的定位是 runtime，等于 node 或 php ，java jdk 等等，pyInstaller、node pkg 等是打包工具，是其他层面的工具。
> 
> swoole-cli macos 版本会在 4.8.9 版本中支持

5.0.0 都发了，还是没看到 macOS 版呢

**Comment by jingjingxyk** [comment]
补齐资料：

2022 PHP swoole 新气象

https://blog.jetbrains.com/wp-content/uploads/2022/06/20220113_jetbrains_cn_webinar_swoolenews.pdf
