### ISSUE TITLE
Link in About section leading to other place

### ISSUE THREAD

**Issue by Grubba27** [swoole/swoole-src#4638]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
I tried acessing swoole wesite throught github about. Using this link below as image
[www.swoole.com/coding](https://www.swoole.com/coding)
![Captura de Tela 2022-03-03 às 09 08 46](https://user-images.githubusercontent.com/70247653/156561988-134bba8b-c64b-4b96-8cf2-6ca2233bbaca.png)

2. What did you expect to see?
I was expecting to see swoole's website
![Captura de Tela 2022-03-03 às 09 09 22](https://user-images.githubusercontent.com/70247653/156562053-db52b8e5-69f6-48ef-b2c5-a4ceb9449856.png)

3. What did you see instead?
The admin login panel.
![Captura de Tela 2022-03-03 às 09 09 48](https://user-images.githubusercontent.com/70247653/156562134-8578593e-9124-4a67-b029-a125011b85c2.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?

Not aplied here

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Not aplied here

**Comment by leocavalcante** [comment]
Thanks for the headsup. I've updated the link at repo's description while we don't have an official English website.
