### ISSUE TITLE
swoole-cli 如何修改配置文件 比如关闭swoole.use_shortname

### ISSUE THREAD

**Issue by lotofbadcode** [swoole/swoole-src#4642]
swoole-cli 如何修改配置文件 比如关闭swoole.use_shortname

**Comment by NathanFreeman** [comment]
直接
swoole-cli -dswoole.use_shortname=Off

**Comment by leoSunning001** [comment]
swoole-cli -dswoole.use_shortname=Off

**Comment by leoSunning001** [comment]
swoole-cli -dswoole.use_shortname=Off 设置无效怎么办

> swoole-cli -dswoole.use_shortname=Off 设置无效怎么办 , 直接在cmd 修改无效
