### ISSUE TITLE
swoole-cli socket压测在windows下只有2000个连接，怎么与linux下差别那么大的

### ISSUE THREAD

**Issue by hanweiweb** [swoole/swoole-src#4643]
![压测](https://user-images.githubusercontent.com/93665931/157051229-1d0904ad-a48a-4df5-a8e9-52a60cef8b7a.png)

**Comment by matyhtf** [comment]
Windows 下使用了 select 作爲  IO 复用的基础设施，最高只支持1024个连接，无法支撑太大的并发
