### ISSUE TITLE
mac系统，m1安装swoole拓展安装问题

### ISSUE THREAD

**Issue by wucongxing8150** [swoole/swoole-src#4644]
执行命令：
` pecl install swoole`
报错信息：
`
opt/homebrew/opt/openssl@1.1/lib -lpthread -L/opt/homebrew/opt/openssl@3/lib -lz -lssl -lcrypto -latomic  -pthread -Wl,-rpath -Wl,/opt/homebrew/opt/openssl@3/lib
ld: library not found for -latomic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [swoole.la] Error 1
ERROR: `make' failed`

已安装openssl，安装时在openssl处填写：
`yes --with-openssl-dir="/opt/homebrew/opt/openssl@3"`

请问这是怎么回事

**Comment by marunrun** [comment]
您好 请问您是如何解决这个问题 我现在碰到同样的问题了
