### ISSUE TITLE
PSR-7 兼容

### ISSUE THREAD

**Issue by AlvisZhang** [swoole/swoole-src#4646]
希望：
Swoole\Http\Request 兼容 Psr\Http\Message\ServerRequestInterface
Swoole\Http\Response 兼容 Psr\Http\Message\ResponseInterface

**Comment by sy-records** [comment]
这个在PHP层就可以实现了

**Comment by AlvisZhang** [comment]
> 这个在PHP层就可以实现了

这不是自己懒么，所以官方是没计划兼容 PSR 的了？

**Comment by sy-records** [comment]
PHP已经有一些实现了的 composer 包了，可以直接使用。

更早也有提交需要支持的issue，例如#559，目前应该是没有计划。

**Comment by AlvisZhang** [comment]
oic

**Comment by leocavalcante** [comment]
也许我们可以在 Swoole 的 PHP 层，标准库中拥有这个：https://github.com/swoole/library/pull/146

**Comment by AlvisZhang** [comment]
> 也许我们可以在 Swoole 的 PHP 层，标准库中拥有这个：[swoole/library#146](https://github.com/swoole/library/pull/146)

我看你的那个 pull request 已经好几个月都没合并到 master 了， WHY？

**Comment by leocavalcante** [comment]
将此功能引入 Swoole 并开始实施一些 PSR 将是一项重大责任。 团队需要仔细检查。
