### ISSUE TITLE
swoole 4.8.7 Swoole\Http\Response::end() 响应长报文(超过5M)时，阿里云负载均衡响应空包体

### ISSUE THREAD

**Issue by fdreamsu** [swoole/swoole-src#4647]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

我服务的某些接口返回了超过5M的数据，在v4.7.1毫无问题，已运行数月。
今天下午我更新到swoole 4.8.7之后发生了下面的问题

2. What did you expect to see?

正常响应

3. What did you see instead?

![1d06d622e0cc7dacebab31f9b3f0943d_](https://user-images.githubusercontent.com/9639344/157858986-0d2dda59-1277-4ecb-80f1-a46cfdfd42fa.png)

如图，响应包体是空的，只有300B。

**直接请求**swoole的话**毫无问题**，但是如果中间隔了一层阿里云负载均衡，返回包体就是空的，但是Content-Length明显不为空。  

swoole的log_file和 php的error_log都完全没有报错

回滚到 v4.7.1 之后，问题消失。

5. What version of Swoole are you using (show your `php --ri swoole`)?

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.7
Built => Mar 11 2022 18:28:48
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1g FIPS  21 Apr 2020
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
Linux 7e9a1c96e36c 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
PHP 8.0.10 (cli) (built: Sep 14 2021 04:29:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.10, Copyright (c), by Zend Technologies
```

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)
```

**Comment by NathanFreeman** [comment]
请问是阿里云负载均衡ALB还是传统型负载均衡CLB（原SLB）？

**Comment by fdreamsu** [comment]
SLB


------------------ 原始邮件 ------------------
发件人: MARiA so cute ***@***.***&gt;
发送时间: 2022年3月12日 10:05
收件人: swoole/swoole-src ***@***.***&gt;
抄送: 烈梦 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [swoole/swoole-src] swoole 4.8.7 Swoole\Http\Response::end() 响应长报文(超过5M)时，阿里云负载均衡响应空包体 (Issue #4647)





 
请问是阿里云负载均衡ALB还是传统型负载均衡CLB（原SLB）？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NathanFreeman** [comment]
我这里没法重现这个问题，它是正常工作的。
需要通过tcpdump抓包分析一下客户端 -> LB -> 服务器，客户端 ->服务器查看包传输情况。
如果需要将抓包文件上传到github，请一定要去掉敏感信息!!!!!!!

**Comment by ValiDrv** [comment]
OMG I have been fighting with this for months, thought I was going crazy.
The exact same thing happens with HAProxy infront of Swoole.

If you request Swoole directly, it works. If you request via HAProxy, then a small percentage of request return `net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)` errors in chrome / connection closed in via CURL.

What I nailed it down to, was the use of `dispatch_func` and `dispatch_mode = 3`, even if the php dispatch_func returns 1 (worker number), and with requests over 1MB or so, and without `keep-alive`.

Weird thing is, when it starts to happen, I get `connection: close` and `server: swoole` headers, which I do not set anywhere in haproxy or swoole...

I could not create a test case that can be reproduced 100% of the time tho... and what I found is that if I restart the docker containers (swoole mainly, not haproxy), then the problem goes away temporarily... so take my post as hits of what could probably cause it...


This would work 100% of the time.
`ab -k -n 1000 -c 250 http://swoole`

This would return errors:
`ab -n 1000 -c 250 http://swoole`
(But would work 100% of the time without `dispatch_func`)

Script to "reproduce":
```
<?php

declare(strict_types=1);

use Swoole\Http\Server as Server;
use Swoole\Http\Request as Request;
use Swoole\Http\Response as Response;

# Create some test files
`dd if=/dev/zero of=3mb.file bs=1024 count=3072`;


$http = new Server('0.0.0.0', 8081);
$http->on('request', function (
    Request $request,
    Response $response
) {
//    echo '.';
//    $response->end('OK');
    $GLOBALS['file'] = $GLOBALS['file'] ?? file_get_contents('3mb.file');
    $response->end($GLOBALS['file']);
});

# Settings
$http->set(
    [
        'daemonize'    => false,    # Must be FALSE, else can't kill workers in DEV...
        'log_file'     => null,      # Only works if daemonize is true, so instead we use the STDOUT/STDERR
        'log_level'    => SWOOLE_LOG_ERROR,
        'worker_num'         => 2,   # Number of threads, must be more than 1
        'reactor_num'        => 2,   # Number of events IO threads, must be more than 1, will run dispatch_func in the same thread
        'dispatch_mode'      => 3,   # If not passed, dispatch_func gets called without the $data
        'dispatch_func'      => function (Server $swoole_server, int $fd, int $type, string $data): int {
            echo "-";

            return 1;   # Normally select worker based on some preg_match the request URL
        },
    ]);

echo "\n----------------------\n";
echo `php --ri swoole`;
echo "\n----------------------\n";
echo `php --version`;
echo "\n----------------------\n";
echo `gcc --version`;
echo "\n----------------------\n";

echo $http->start();
$this->server = $http;

```


```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.8
Built => Mar 16 2022 13:16:47
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1k  25 Mar 2021
dtls => enabled
http2 => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

----------------------
PHP 8.1.0 (cli) (built: Nov 30 2021 06:02:01) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.0, Copyright (c), by Zend Technologies

----------------------
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


----------------------

```

Docker file subset
```
FROM php:8.1-cli

# Install some packages and php stuff

# PHP Swoole
ENV EXT_SWOOLE_VERSION=v4.8.8
RUN git clone https://github.com/swoole/swoole-src.git \
  && cd swoole-src \
  && git checkout $EXT_SWOOLE_VERSION \
  && phpize \
  && ./configure \
  --enable-http2 \
  --enable-mysqlnd \
  --enable-openssl \
  --enable-sockets \
  && make && make install \
  && docker-php-ext-enable swoole \
  && cd .. \
  && rm -rf swoole-src

# keeps server running via supervisor
CMD ["/usr/local/bin/php", ".......daemon.php"]
```

**Comment by matyhtf** [comment]
@ValiDrv @fdreamsu I am trying to reproduce this issue

**Comment by fdreamsu** [comment]
> OMG I have been fighting with this for months, thought I was going crazy. The exact same thing happens with HAProxy infront of Swoole.
> 
> If you request Swoole directly, it works. If you request via HAProxy, then a small percentage of request return `net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)` errors in chrome / connection closed in via CURL.
> 
> What I nailed it down to, was the use of `dispatch_func` and `dispatch_mode = 3`, even if the php dispatch_func returns 1 (worker number), and with requests over 1MB or so, and without `keep-alive`.
> 
> Weird thing is, when it starts to happen, I get `connection: close` and `server: swoole` headers, which I do not set anywhere in haproxy or swoole...
> 
> I could not create a test case that can be reproduced 100% of the time tho... and what I found is that if I restart the docker containers (swoole mainly, not haproxy), then the problem goes away temporarily... so take my post as hits of what could probably cause it...
> 
> This would work 100% of the time. `ab -k -n 1000 -c 250 http://swoole`
> 
> This would return errors: `ab -n 1000 -c 250 http://swoole` (But would work 100% of the time without `dispatch_func`)
> 
> Script to "reproduce":
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> use Swoole\Http\Server as Server;
> use Swoole\Http\Request as Request;
> use Swoole\Http\Response as Response;
> 
> # Create some test files
> `dd if=/dev/zero of=3mb.file bs=1024 count=3072`;
> 
> 
> $http = new Server('0.0.0.0', 8081);
> $http->on('request', function (
>     Request $request,
>     Response $response
> ) {
> //    echo '.';
> //    $response->end('OK');
>     $GLOBALS['file'] = $GLOBALS['file'] ?? file_get_contents('3mb.file');
>     $response->end($GLOBALS['file']);
> });
> 
> # Settings
> $http->set(
>     [
>         'daemonize'    => false,    # Must be FALSE, else can't kill workers in DEV...
>         'log_file'     => null,      # Only works if daemonize is true, so instead we use the STDOUT/STDERR
>         'log_level'    => SWOOLE_LOG_ERROR,
>         'worker_num'         => 2,   # Number of threads, must be more than 1
>         'reactor_num'        => 2,   # Number of events IO threads, must be more than 1, will run dispatch_func in the same thread
>         'dispatch_mode'      => 3,   # If not passed, dispatch_func gets called without the $data
>         'dispatch_func'      => function (Server $swoole_server, int $fd, int $type, string $data): int {
>             echo "-";
> 
>             return 1;   # Normally select worker based on some preg_match the request URL
>         },
>     ]);
> 
> echo "\n----------------------\n";
> echo `php --ri swoole`;
> echo "\n----------------------\n";
> echo `php --version`;
> echo "\n----------------------\n";
> echo `gcc --version`;
> echo "\n----------------------\n";
> 
> echo $http->start();
> $this->server = $http;
> ```
> 
> ```
> swoole
> 
> Swoole => enabled
> Author => Swoole Team <team@swoole.com>
> Version => 4.8.8
> Built => Mar 16 2022 13:16:47
> coroutine => enabled with boost asm context
> epoll => enabled
> eventfd => enabled
> signalfd => enabled
> cpu_affinity => enabled
> spinlock => enabled
> rwlock => enabled
> sockets => enabled
> openssl => OpenSSL 1.1.1k  25 Mar 2021
> dtls => enabled
> http2 => enabled
> pcre => enabled
> zlib => 1.2.11
> brotli => E16777225/D16777225
> mutex_timedlock => enabled
> pthread_barrier => enabled
> futex => enabled
> mysqlnd => enabled
> async_redis => enabled
> 
> Directive => Local Value => Master Value
> swoole.enable_coroutine => On => On
> swoole.enable_library => On => On
> swoole.enable_preemptive_scheduler => Off => Off
> swoole.display_errors => On => On
> swoole.use_shortname => On => On
> swoole.unixsock_buffer_size => 8388608 => 8388608
> 
> ----------------------
> PHP 8.1.0 (cli) (built: Nov 30 2021 06:02:01) (NTS)
> Copyright (c) The PHP Group
> Zend Engine v4.1.0, Copyright (c) Zend Technologies
>     with Zend OPcache v8.1.0, Copyright (c), by Zend Technologies
> 
> ----------------------
> gcc (Debian 10.2.1-6) 10.2.1 20210110
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> 
> ----------------------
> ```
> 
> Docker file subset
> 
> ```
> FROM php:8.1-cli
> 
> # Install some packages and php stuff
> 
> # PHP Swoole
> ENV EXT_SWOOLE_VERSION=v4.8.8
> RUN git clone https://github.com/swoole/swoole-src.git \
>   && cd swoole-src \
>   && git checkout $EXT_SWOOLE_VERSION \
>   && phpize \
>   && ./configure \
>   --enable-http2 \
>   --enable-mysqlnd \
>   --enable-openssl \
>   --enable-sockets \
>   && make && make install \
>   && docker-php-ext-enable swoole \
>   && cd .. \
>   && rm -rf swoole-src
> 
> # keeps server running via supervisor
> CMD ["/usr/local/bin/php", ".......daemon.php"]
> ```

I found that `sendFile()` works fine. 
So I put response data into a tmp file and use sendFile() to send reseponse when the response size is more than 409600. So far it works like a charm.
