### ISSUE TITLE
大并发下taskwait() 返回数据错乱

### ISSUE THREAD

**Issue by xiaoshen** [swoole/swoole-src#465]
我测试大并发下的业务，去调test方法，test方法里有2个taskwait方法请求查询，然后打印结果，会发现存在大几率 打印出来$res1的结果是$res2的数据，$res2的数据是$res1的数据。但是当我对taskwait设置timeout参数 1秒，就没这个问题。我想知道为什么。

function onTask($serv,$task_id,$from_id,$data){
   //进行sql数据查询
  
  return $data; //返回数据查询结果
}
 function test(){
  $res1 = $server->taskwait('select * from user where id=1');
 var_dump($res1);
$res2 = $server->taskwait('select * from member where id>3 limit 2');
var_dump($res2);
}

**Comment by matyhtf** [comment]
已修复，可能是并发写入导致的。增加了 Lock逻辑
