### ISSUE TITLE
cpanel installation problem 

### ISSUE THREAD

**Issue by AngusDV** [swoole/swoole-src#4652]
/opt/cpanel/ea-php80/root/usr/bin/pear install swoole-4.8.8.tgz
411 source files, building
running: phpize
enable sockets supports? [no] : yes
enable openssl support? [no] :
enable http2 support? [no] :
enable mysqlnd support? [no] :
enable json support? [no] :
enable curl support? [no] :
building in /root/tmp/pear/pear-build-rootiqkdss/swoole-4.8.8
running: /root/tmp/pear/swoole/configure --with-php-config=/opt/cpanel/ea-php80/root/usr/bin/php-config --enable-sockets=yes --enable-openssl=no --enable-http2=no --enable-mysqlnd=no --enable-swoole-json=no --enable-swoole-curl=no
sh: /root/tmp/pear/swoole/configure: No such file or directory
ERROR: `/root/tmp/pear/swoole/configure --with-php-config=/opt/cpanel/ea-php80/root/usr/bin/php-config --enable-sockets=yes --enable-openssl=no --enable-http2=no --enable-mysqlnd=no --enable-swoole-json=no --enable-swoole-curl=no' failed

**Comment by NathanFreeman** [comment]
Hi.
No execution result of phpize command was found from your log. 
I guess that there is no phpize command in your server or phpize command  execution failed.

```shell
running: phpize
Configuring for:
PHP Api Version:         20200930
Zend Module Api No:      20200930
Zend Extension Api No:   420200930
enable sockets supports? [no] : yes
enable openssl support? [no] : yes
enable http2 support? [no] : yes
enable mysqlnd support? [no] : yes
enable json support? [no] : yes
enable curl support? [no] : yes
```

**Comment by AngusDV** [comment]
hi
solved my problem administration change partition /tmp to /root/tmp for security i am communicate with server provider and change partition /tmp and my problem solved. 
thank you
