### ISSUE TITLE
client is not able to establish the connection to the swoole websocket

### ISSUE THREAD

**Issue by ShawnXU0208** [swoole/swoole-src#4654]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
when i installed swoole on server, i was asked if to enable sockets support, openssl support, http2 support, etc. i went for default option which is no for all of them.
on backend side, i used php to create a websocket server by the following code 
`$server = new swoole_websocket_server("localhost", 8085);`
on client side, i tried to connect to it with javascript:
`const socket = new WebSocket("ws://<domain-name>:8085");`
but once i try to send message, i got 'invalid status' error, looks like the connection can't be established.

3. What did you expect to see?
i want to the client to connect to the websocket server

4. What did you see instead?
 i am not able to send the messag, the ready state of the 'socket' object is 0, and after a while, it raises a timeout error. looks like the client has been trying to connect, but it failed at the end.

5. What version of Swoole are you using (show your `php --ri swoole`)?

[root@srv0063 ~]# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.8
Built => Mar 19 2022 11:28:42
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
[root@srv0063 ~]# 

6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

uname
[root@srv0063 ~]# uname -v
#1 SMP Fri Jan 14 13:59:45 UTC 2022
[root@srv0063 ~]# 

php
[root@srv0063 ~]# php -v
PHP 7.2.34 (cli) (built: Nov 15 2021 09:20:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
[root@srv0063 ~]# 

gcc -v
[root@srv0063 ~]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
[root@srv0063 ~]#

**Comment by NathanFreeman** [comment]
Hi!
Could you please show me your js and php code?

**Comment by ShawnXU0208** [comment]
@NathanFreeman sure, these are the code

### server.php:
```
<?php

  $server = new swoole_websocket_server("localhost", 8085);

  // events
    // open
  $server->on("open",function (swoole_websocket_server $server,$request ){
  echo "User ".$request->fd." connect\n";
  });

  // message

  $server->on("message",function (swoole_websocket_server $server,$frame ){
  echo "User ".$frame->fd." send message ".$frame->data ." \n";
      foreach ($server->connections as $fd) {
      if ($frame->fd != $fd) {
          $server->push($fd,$frame->data);
      }
      }
  });

  // close
  $server->on("close",function($server,$fd ){
  echo "User ".$fd." disconnet\n";
  });
  // start
  
  $server->start();
?>
```

### main.js:

```
const exampleSocket = new WebSocket("ws://<domain-name>:8085");

console.log(exampleSocket);
exampleSocket.onopen = function (event) {
  console.log("user connected");
};
setCookie = (cname, cvalue, exdays) => {
  let d = new Date();
  d.setTime(d.getTime() + exdays * 24 * 60 * 60 * 1000);
  let expires = "expires=" + d.toUTCString();
  document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
};
getCookie = (cname) => {
  let name = cname + "=";
  let decodedCookie = decodeURIComponent(document.cookie);
  let ca = decodedCookie.split(";");
  for (let i = 0; i < ca.length; i++) {
    let c = ca[i];
    while (c.charAt(0) == " ") {
      c = c.substring(1);
    }
    if (c.indexOf(name) == 0) {
      return c.substring(name.length, c.length);
    }
  }
  return "";
};
let Name = getCookie("name");
if (!Name) {
  let timestamp = new Date().getTime();
  Name = "anonymous" + timestamp;
  setCookie("name", "anonymous" + timestamp, 60);
}

sendMessage = () => {
  let messageElem = document.getElementById("message");
  let textMessage = messageElem.value;

  if (textMessage.trim() !== "") {
    let msg = {
      type: "message",
      text: textMessage,
      sender: Name,
      date: Date.now(),
    };

    // exampleSocket.send(JSON.stringify(msg));
    exampleSocket.send("hello");
    messageElem.value = "";

    messageParse(Name, textMessage);
  }
};

exampleSocket.onmessage = function (event) {
  let data = JSON.parse(event.data);
  messageParse(data.sender, data.text);
};

messageParse = (sender, msg) => {
  let html = "";
  if (sender !== Name) {
    html = `<li class="message left appeared">
        <div class="avatar"></div>
        <div class="text_wrapper">
        <div class="text">${msg}</div>
      </div></li>`;
  } else {
    html = `<li class="message right appeared">
        <div class="avatar"></div>
        <div class="text_wrapper">
        <div class="text">${msg}</div>
      </div></li>`;
  }

  document.getElementById("messagesBox").innerHTML += html;
};
```

**Comment by matyhtf** [comment]
The listening address of the server should be `0.0.0.0`. I can't reproduce this problem, please check your firewall settings

![2022-03-23 18-23-28 的屏幕截图](https://user-images.githubusercontent.com/2017766/159678252-45aa215c-1649-48c9-a054-a3be7c7b274c.png)
![2022-03-23 18-23-43 的屏幕截图](https://user-images.githubusercontent.com/2017766/159678269-71f46aba-b3da-438f-bb8c-b122127eed32.png)

**Comment by ShawnXU0208** [comment]
the issue is solved, i need to set up proxy in nginx config like below:

  location /ws {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Proxy "";
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://localhost:8085;
  }

**Comment by fdrbahamit** [comment]
Connection closed: fd 1, error code: 11

i want know error
and fix help me. plase

**Comment by NathanFreeman** [comment]
@fdrbahamit Please provide a minimal code for us to reproduce the issue

**Comment by fdrbahamit** [comment]
@NathanFreeman sure, these are the code

 server config 
`<?php

$log = ROOT_PATH . DIRECTORY_SEPARATOR . 'writeable/logs/server_chat.log';

return [
    'swoole' => [
        // Process
        'max_connection' => 5000,
        'daemonize' => false, 
        'user' => 'www-data',
        'group' => 'www-data',
        'open_cpu_affinity' => true,
        'cpu_affinity_ignore' => [0], 
        'pid_file' => __DIR__ . '/../server.pid',
        'reactor_num' => swoole_cpu_num(), 
        'worker_num' => swoole_cpu_num() * 2, 
        'message_queue_key' => 'mq1',
        'dispatch_mode' => 2,
        'discard_timeout_request' => true,

        // Worker
        'max_request' => 10000,
        'max_request_grace' => 5000,

        // Task worker
        'task_ipc_mode' => 1, 
        'task_max_request' => 5000,
        'task_tmpdir' => '/tmp',
        'task_worker_num' => 4, 
        'task_enable_coroutine' => true,
        'task_use_object' => true,

        'log_level' => 3, // INFO
        'log_file' => $log,

        // TCP Settings
        'input_buffer_size' => 2097152,
        'buffer_output_size' => 32 * 1024 * 1024,
        'tcp_fastopen' => true,
        'max_conn' => 10000,
        'tcp_defer_accept' => 5,
        'open_tcp_keepalive' => true,
        'open_tcp_nodelay' => true,
        'socket_buffer_size' => 128 * 1024 * 1024,

        // Heartbeat Settings
        'heartbeat_check_interval' => 120,
        'heartbeat_idle_time' => 600,
        // Websocket Settings
        'open_websocket_protocol' => true,
        'websocket_compression' => false,
        'open_websocket_ping_frame' => true,
        'open_websocket_pong_frame' => true,

        // Coroutine Settings
        'enable_coroutine' => true,
        'max_coroutine' => 5000, 

        // Compression Settings
        'http_compression' => true,
        'http_compression_level' => 5,
        'compression_min_length' => 20,

        // DNS Settings
        'dns_server' => '8.8.8.8:53',
        'dns_cache_refresh_time' => 60,

        'enable_preemptive_scheduler' => 1,

        'open_http_protocol' => true,
        'open_http2_protocol' => true,
        'enable_static_handler' => true,
        'open_mqtt_protocol' => false,
        'open_redis_protocol' => false,
    ],

    'server' => [
        'host' => '0.0.0.0:24800',
        'port' => 9501,
        'mode' => SWOOLE_PROCESS,
        'sock_type' => SWOOLE_SOCK_TCP
    ],
    'db' => [
        'db_driver' => 'mysql',
        'dbhost' => '172.0.0.1',
        'db_port' => 3306,
        'dbuser' => 'root',
        'dbpassword' => 'sql_oninapp_com',
        'dbname' => 'sql_oninapp_com',
        'charset'  => 'utf8mb4',
        'db_collate'  => 'utf8mb4_unicode_ci',

    ],

];
`

server chat
`
<?php

namespace System\Server\Chat;

use Swoole\WebSocket\Server;
use Swoole\Http\Request;
use System\Server\Handler\MessageHandler;
use System\Server\Handler\ConnectionHandler;
use System\Server\Utils\MySQLPool;
use Swoole\Timer;
use Swoole\Coroutine;
use Swoole\Table;
class ChatServer
{
    protected Server $server;
    protected Table $connectionsTable;
    protected Table $floodTable;
    protected Table $userConnectionsCount;
    protected $config;
    protected $mysqlPool;
    protected $connectionHandler;
    protected $messageHandler;

    public function __construct()
    {
        $this->config = require ROOT_PATH . DIRECTORY_SEPARATOR . 'system' . DIRECTORY_SEPARATOR . 'Server' . DIRECTORY_SEPARATOR . 'Config' . DIRECTORY_SEPARATOR . 'Config.php';
        $serverConfig = $this->config['server'];

        $this->server = new Server(
            $serverConfig['host'],
            $serverConfig['port'],
            $serverConfig['mode'],
            $serverConfig['sock_type']
        );

        // Áp dụng các cấu hình Swoole
        if (isset($this->config['swoole'])) {
            $this->server->set($this->config['swoole']);
        }

        $this->connectionsTable = new Table(10000);
        $this->connectionsTable->column('user_id', Table::TYPE_STRING, 64);    
        $this->connectionsTable->column('device_id', Table::TYPE_STRING, 64);
        $this->connectionsTable->column('fd', Table::TYPE_INT, 8);
        $this->connectionsTable->column('last_activity', Table::TYPE_STRING, 19);
        $this->connectionsTable->create();


        $this->floodTable = new Table(10000);
        $this->floodTable->column('count', Table::TYPE_INT, 4);
        $this->floodTable->column('last_time', Table::TYPE_INT, 8);
        $this->floodTable->create();

        $this->userConnectionsCount = new Table(1024);
        $this->userConnectionsCount->column('count', Table::TYPE_INT, 4);
        $this->userConnectionsCount->create();

        $this->server->on('Start', [$this, 'onStart']);
        $this->server->on('Open', [$this, 'onOpen']);
        $this->server->on('Message', [$this, 'onMessage']);
        $this->server->on('Close', [$this, 'onClose']); 

        $this->server->on('Task', [$this, 'onTask']);
        $this->server->on('Finish', [$this, 'onFinish']);
        $this->server->on('WorkerStart', [$this, 'onWorkerStart']);
    }

    public function start()
    {
        $this->server->start();
    }

    public function onStart($server)
    {
        echo "Swoole server started at {$this->config['server']['host']}:{$this->config['server']['port']}\n";
    }

    public function onOpen(Server $server, Request $request)
    {
        if ($this->connectionHandler) {
            $this->connectionHandler->onOpen($server, $request);
        } else {
            echo "ConnectionHandler chưa được khởi tạo.\n";
            $server->disconnect($request->fd);
        }
    }

    public function onMessage(Server $server, $frame)
    {
        if ($this->messageHandler) {
            $this->messageHandler->onMessage($server, $frame);
        } else {
            echo "MessageHandler chưa được khởi tạo.\n";
            $server->push($frame->fd, json_encode(['error' => 'Server not ready']));
        }
    }

    public function onClose(Server $server, $fd)
    {
        if ($this->connectionHandler) {
            $this->connectionHandler->onClose($server, $fd);
        } else {
            echo "ConnectionHandler chưa được khởi tạo.\n";
        }
    }
    
    public function onTask($server, $taskId, $srcWorkerId, $data) {
        Coroutine::sleep(1);
        
            $result = [
                'fd' => $data['fd'],
                'message' => "Processed: " . $data['message'],
            ];
        
            return $result;
        
    }
    public function onWorkerStart($server, $workerId)
    {
        $this->mysqlPool = new MySQLPool($this->config['db'], 5);

        $this->connectionHandler = new ConnectionHandler(
            $this->connectionsTable,
            $this->floodTable,
            $this->userConnectionsCount,
            $this->mysqlPool
        );

        $this->messageHandler = new MessageHandler(
            $this->connectionsTable,
            $this->floodTable,
            $this->userConnectionsCount,
            $this->mysqlPool
        );

        if ($workerId == 0) {
            Timer::tick(60000, function() use ($server) {
                $now = time();
                $timeout = 600; // 600 seconds timeout (10 minutes)
    
                foreach ($server->connections as $fd) {
                    $row = $server->getClientInfo($fd);  // Lấy thông tin kết nối từ server
    
                    if ($row && isset($row['last_activity']) && ($now - $row['last_activity'] > $timeout)) {
                        if ($server->isEstablished($fd)) {
                            $server->disconnect($fd);
                            echo "Disconnected inactive connection: fd {$fd}, user_id {$row['user_id']}\n";
                        }
                    }
                }
            });
        }
    }

    public function onFinish($server, $taskId, $data)
    {
        if (isset($data['fd']) && $server->isEstablished($data['fd'])) {
            $server->push($data['fd'], json_encode([
                'type' => 'task_result',
                'result' => $data['message'],
            ]));
        }
        echo "Task #{$taskId} finished.\n";
    }

}`

ConnectionHandler.php
`<?php
namespace System\Server\Handler;

use Swoole\WebSocket\Server;
use Swoole\Http\Request;
use Swoole\Coroutine;
use System\Core\AppException;
use Firebase\JWT\JWT;
use Firebase\JWT\Key;
use PDO;

class ConnectionHandler
{
    private $connectionsTable;
    private $floodTable;
    private $userConnectionsCount;
    private $mysqlPool;
    public function __construct($connectionsTable, $floodTable, $userConnectionsCount, $mysqlPool)
    {
        $this->connectionsTable = $connectionsTable;
        $this->floodTable = $floodTable;
        $this->userConnectionsCount = $userConnectionsCount;
        $this->mysqlPool = $mysqlPool;
    }
    public function onOpen(Server $server, Request $request)
    {
        Coroutine::create(function() use ($server, $request) {
            $this->handleOpen($server, $request);
        });
    }

    public function onClose(Server $server, $fd)
    {
        $this->handleClose($server, $fd);
    }

    public function handleOpen($server, $request) {
        $fd = $request->fd;
        $token = $request->get['token'] ?? '';
        $device_id = $request->get['device_id'] ?? '';
        echo "*********************************************\n";
        echo "New connection established: fd {$fd}\n";
        echo "Token: {$token}\n";
        echo "Device Id: Device {$device_id}\n";
    
        // Authenticate user using JWT
        if (empty($token) || empty($device_id)) {
            $server->push($fd, json_encode(['error' => 'Authentication failed: Missing token or device_id']));
            $server->disconnect($fd);
            swoole_clear_error("Authentication failed: Missing token or device_id for fd {$fd}");
            return;
        }
        
        $user_id = $this->authenticateUser($token);
        if (!$user_id) {
            $server->push($fd, json_encode(['error' => 'Authentication failed: Invalid token']));
            $server->disconnect($fd);
            echo "Authentication failed: Invalid token for fd {$fd}\n";
            return;
        }
    
        $this->storeConnection($server, $user_id, $device_id, $fd);
    
        $this->sendPendingMessages($server, $user_id, $fd);
        $this->logCurrentConnections($server); 
    }

    public function handleClose($server, $fd) {
        try {
            $info = $server->getClientInfo($fd);
            echo "*********************************************\n";
            echo "Kết nối bị đóng: fd {$fd}, mã lỗi: {$info['close_errno']}\n";

            // Lấy user_id từ connectionsTable
            $connection = $this->connectionsTable->get($fd);
            if ($connection) {
                $user_id = $connection['user_id'];

                // Giảm số kết nối của user
                $key = (string)$user_id;
                if ($this->userConnectionsCount->exist($key)) {
                    $data = $this->userConnectionsCount->get($key);
                    $data['count']--;
                    if ($data['count'] <= 0) {
                        // Không còn kết nối nào, cập nhật DB
                        $this->setUserOnlineStatus($server, $user_id, 0);
                        $this->userConnectionsCount->del($key);
                    } else {
                        $this->userConnectionsCount->set($key, $data);
                    }
                }
            }

            $this->removeConnection($server, $fd);
            $this->logCurrentConnections($server); 
        } catch (AppException $e) {
            print_r("Exception in handleClose: " . $e->getMessage());
        }
    }


    public function removeConnection($server, $fd) {
        $this->connectionsTable->del($fd);
        echo "Removed connection info for fd {$fd}\n";
    }

    private function authenticateUser($token)
    {
        $secret_key = 'MoviesApiSecretKey@2024';

        try {
            $decoded = JWT::decode($token, new Key($secret_key, 'HS256'));
            echo "JWT decoded successfully. User ID: " . ($decoded->user_id ?? 'Not found');
            return $decoded->user_id ?? false;
        } catch (AppException $e) {
            error_log("JWT decode error: " . $e->getMessage());
            echo "JWT decode error: " . $e->getMessage() . "\n";
            return false;
        }
    }

    private function sendPendingMessages($server, $user_id, $fd) {
        echo "Fetching unread messages for user_id {$user_id}";
    
        $pdo = $this->mysqlPool->getConnection();
        if (!$pdo) {
            $server->push($fd, json_encode(['error' => 'Database connection error']));
            echo "Failed to retrieve PDO connection from pool for sending pending messages to user_id {$user_id}\n";
            return;
        }
    
        try {
            // Query unread messages from database
            $messages = $this->getUnreadMessages($pdo, $user_id);
    
            if ($messages === false) {
                $server->push($fd, json_encode(['error' => 'Failed to fetch messages']));
                echo "Failed to fetch unread messages for user_id {$user_id}\n";
                return;
            }
            
            foreach ($messages as $message) {
                $server->push($fd, json_encode([
                    'action' => 'new_message',
                    'data' => $message
                ]));
    
                // markMessageAsSent($pdo, $message['id']);
                // markMessageAsSentAndDelivered($pdo, $message['id']);
                // notifySenderMessageDelivered($server, $message['sender_id'], $message['id']);
                echo "Sent pending message id {$message['id']} to fd {$fd} for user_id {$user_id}\n";
            }
        } finally {
            // Return connection to pool
            $this->mysqlPool->releaseConnection($pdo);
        }
    }

    private function getUnreadMessages($pdo, $user_id) {
        try {
            $stmt = $pdo->prepare("SELECT * FROM fast_messages WHERE recipient_id = ? AND is_sent = 0");
            if (!$stmt) {
                throw new AppException("PDO prepare error: " . implode(" | ", $pdo->errorInfo()));
            }
            $stmt->execute([$user_id]);
            $messages = $stmt->fetchAll(PDO::FETCH_ASSOC);
            return $messages;
        } catch (AppException $e) {
            error_log("Error in getUnreadMessages: " . $e->getMessage());
            echo "Error in getUnreadMessages: " . $e->getMessage() . "\n";
            return false;
        }
    }
    private function logCurrentConnections($server) {
        echo "\n********** Các Người Dùng Đang Kết Nối **********\n";
        foreach ($this->connectionsTable as $fd => $row) {
            echo "fd: {$fd}, user_id: {$row['user_id']}, device_id: {$row['device_id']}, last_activity: {$row['last_activity']}\n";
        }
    }

    private function storeConnection($server, $user_id, $device_id, $fd) {
        echo "\n*********************************************\n";
        echo "Stored connection for user_id: {$user_id}, device_id: {$device_id}, fd: {$fd}\n";
        $key = (string)$user_id;
        if ($this->userConnectionsCount->exist($key)) {
            $data = $this->userConnectionsCount->get($key);
            $data['count']++;
            $this->userConnectionsCount->set($key, $data);
        } else {
            $this->userConnectionsCount->set($key, ['count' => 1]);
            $this->setUserOnlineStatus($server, $user_id, 1);
        }
        $date = date('Y-m-d H:i:s');
        $this->connectionsTable->set($fd, [
            'user_id' => (string)$user_id,
            'device_id' => $device_id,
            'fd' => $fd,
            'last_activity' => $date,
            'online' => 1
        ]);
    
        $stored = $this->connectionsTable->get($fd);
        echo "Connection stored: " . print_r($stored, true);
    }

    private function setUserOnlineStatus($server, $user_id, $online) {
        $pdo = $this->mysqlPool->getConnection();
        if (!$pdo) {
            echo "Không thể kết nối database để cập nhật trạng thái online.\n";
            return;
        }
    
        try {
            $stmt = $pdo->prepare("UPDATE fast_users SET online = ? WHERE id = ?");
            $stmt->execute([$online, $user_id]);
            if ($stmt->errorCode() !== '00000') {
                error_log("Lỗi khi cập nhật trạng thái online: " . implode(" | ", $stmt->errorInfo()));
            } else {
                echo "Đã cập nhật online = {$online} cho user_id = {$user_id}\n";
            }
        } catch (AppException $e) {
            error_log("Lỗi khi cập nhật trạng thái online: " . $e->getMessage());
        } finally {
            $this->mysqlPool->releaseConnection($pdo);
        }
    }

}
right in the handClose function It has a message ending with fd 1 and error code 11
`

client nextjs connect by websocket
`
import { nanoid } from 'nanoid';

class WebSocketService {
    constructor(baseUrl, token) {
      this.baseUrl = baseUrl;
      this.token = token;
      this.deviceId = nanoid();
      this.socket = null;
      this.listeners = {
          open: [],
          message: [],
          error: [],
          close: [],
      };
    }
    // Kết nối đến WebSocket server
    connect() {
        const urlWithParams = `${this.baseUrl}?token=${encodeURIComponent(this.token)}&device_id=${encodeURIComponent(this.deviceId)}`;
        this.socket = new WebSocket(urlWithParams);
        console.log(this.token);
        this.socket.onopen = (event) => {
        console.log('Đã kết nối đến WebSocket server');
        this.listeners.open.forEach((callback) => callback(event));
      };
  
      this.socket.onmessage = (event) => {
        try {
          const data = JSON.parse(event.data);
          this.listeners.message.forEach((callback) => callback(data));
        } catch (error) {
          console.error('Error parsing message:', error);
        }
      };
  
      // Sự kiện lỗi
      this.socket.onerror = (error) => {
        console.error('WebSocket Error:', error);
        this.listeners.error.forEach((callback) => callback(error));
      };
  
      // Sự kiện khi kết nối đóng
      this.socket.onclose = (event) => {
        console.log('WebSocket connection closed');
        this.listeners.close.forEach((callback) => callback(event));
      };
    }
  
    // Ngắt kết nối WebSocket
    disconnect() {
      if (this.socket) {
        this.socket.close();
      }
    }
  
    // Gửi tin nhắn qua WebSocket
    sendMessage(message) {
      if (this.socket && this.socket.readyState === WebSocket.OPEN) {
        this.socket.send(JSON.stringify(message));
      } else {
        console.error('WebSocket is not open. Ready state:', this.socket.readyState);
      }
    }
  
    // Thêm listener cho sự kiện cụ thể
    addEventListener(event, callback) {
      if (this.listeners[event]) {
        this.listeners[event].push(callback);
      }
    }
  
    // Loại bỏ listener cho sự kiện cụ thể
    removeEventListener(event, callback) {
      if (this.listeners[event]) {
        this.listeners[event] = this.listeners[event].filter((cb) => cb !== callback);
      }
    }
  }
  
  export default WebSocketService;
  


`
