### ISSUE TITLE
使用swoole-cli通过composer安装hyperf项目

### ISSUE THREAD

**Issue by phpyii** [swoole/swoole-src#4656]
here is no 'unzip' nor '7z' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' or '7z' may remediate them.

提示缺少unzip扩展

**Comment by NathanFreeman** [comment]
它是提示你系统缺少unzip命令，系统需要安装unzip

**Comment by phpyii** [comment]
@NathanFreeman  那这个怎么解决 swoole-cli集成了cygwin   怎么在集成的cygwin里安装unzip

**Comment by phpyii** [comment]
我试了下应该是这个导致的 @php -r "file_exists('.env') || copy('.env.example', '.env');   swoole-cli 里没有php的命令

**Comment by phpyii** [comment]
我把composer.json  scripts里的php 改成 swoole-cli可以了
