### ISSUE TITLE
socket_create 方法返回类型问题

### ISSUE THREAD

**Issue by huangdijia** [swoole/swoole-src#4657]
编译 swoole 时设置 `./configure --enable-sockets` 之后， `socket_create()` 方法返回的类型是 `Swoole\Coroutinue\Socket` 对象。现遇到问题，`monolog` 使用 `SyslogUdpHandler` 的时候，对 socket 的判断就会出问题。

判断代码：

https://github.com/Seldaek/monolog/blob/f2f66cd480df5f165391ff9b6332700d467b25ac/src/Monolog/Handler/SyslogUdp/UdpSocket.php#L60-L66

**Comment by limingxinleo** [comment]
已经 fix 了 @huangdijia

**Comment by huangdijia** [comment]
> 已经 fix 了 @huangdijia

坐等发版，感谢
