### ISSUE TITLE
v4.8.8 执行 ./configure    --enable-coroutine-postgresql  时出错

### ISSUE THREAD

**Issue by andy236726493** [swoole/swoole-src#4659]
版本v4.8.8， 执行下面命令时出错 
./configure    --enable-openssl --enable-http2   --enable-coroutine  --enable-coroutine-postgresql  --with-php-config=/www/server/php/74/bin/php-config
出现错误 
 WARNING: unrecognized options: --enable-coroutine, --enable-coroutine-postgresql

**Comment by NathanFreeman** [comment]
试试这样
./configure --enable-openssl --enable-http2 --enable-swoole-pgsql --with-php-config=/www/server/php/74/bin/php-config

如果还不行
./configure --help 查看命令参数

**Comment by andy236726493** [comment]
./configure --help  里没有enable-swoole-pgsql，也没有 enable-coroutine-postgresql  ，开启支持协程postgresql，现在需要怎么弄

**Comment by NathanFreeman** [comment]
你是4.4.8版本的，需要手动编译postgresql的coroutine客户端。
https://wiki.swoole.com/#/coroutine_client/postgresql
https://github.com/swoole/ext-postgresql

**Comment by andy236726493** [comment]
手动编译postgresql的coroutine客户端 这个我知道，原来还需要在 swoole  编译时加--enable-coroutine-postgresql，现在是否不需要这样做了，文档上没有说明

**Comment by NathanFreeman** [comment]
> 手动编译postgresql的coroutine客户端 这个我知道，原来还需要在 swoole 编译时加--enable-coroutine-postgresql，现在是否不需要这样做了，文档上没有说明

新版本的swoole有集成postgresql的协程客户端，在编译swoole的时候加上--enable-swoole-pgsql就可以开启。
老版本不需要，只能编译ext-postgresql这个扩展增强swoole的功能。换句话说老版本是swoole和ext-postgresql是分开编译的。

**Comment by NathanFreeman** [comment]
> 手动编译postgresql的coroutine客户端 这个我知道，原来还需要在 swoole 编译时加--enable-coroutine-postgresql，现在是否不需要这样做了，文档上没有说明

你可以看看swoole postgresqlde README
https://github.com/swoole/ext-postgresql/blob/v4.4.x/README.md

**Comment by andy236726493** [comment]
版本v4.4.8 是最新版本吗   在  ./configire --help 里还没有 --enable-swoole-pgsql，只有  --enable-swoole

**Comment by andy236726493** [comment]
版本v4.8.8 是最新版本吗 在 ./configire --help 里还没有 --enable-swoole-pgsql，只有 --enable-swoole

**Comment by NathanFreeman** [comment]
> 版本v4.4.8 是最新版本吗 在 ./configire --help 里还没有 --enable-swoole-pgsql，只有 --enable-swoole

4.8.8是最新的版本

**Comment by andy236726493** [comment]
我现在用的是v4.8.8， ./configire --help 里还没有 --enable-swoole-pgsql
--disable-option-checking  ignore unrecognized --enable/--with options
  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
  --with-libdir=NAME      Look for libraries in .../NAME rather than .../lib
  --with-php-config=PATH  Path to php-config [php-config]
  --enable-debug-log      Enable swoole debug log
  --enable-trace-log      Enable swoole trace log
  --enable-sockets        Do you have sockets extension?
  --enable-openssl        Use openssl
  --enable-http2          Use http2.0
  --enable-swoole         Enable swoole support
  --enable-mysqlnd        Enable mysqlnd
  --enable-cares          Enable cares
  --with-openssl-dir[=DIR]
                          Include OpenSSL support (requires OpenSSL >= 1.0.2)
  --with-jemalloc-dir[=DIR]
                          Include jemalloc support
  --enable-asan           Enable asan
  --enable-swoole-coverage
                          Enable swoole coverage support
  --enable-swoole-dev     Enable developer flags
  --enable-swoole-json    Enable JSON support
  --enable-swoole-curl    Enable cURL support
  --enable-thread-context Use thread context
  --enable-debug,         compile with debug symbols
  --enable-shared=PKGS    Build shared libraries default=yes
  --enable-static=PKGS    Build static libraries default=yes
  --enable-fast-install=PKGS
                          Optimize for fast installation default=yes
  --with-gnu-ld           Assume the C compiler uses GNU ld default=no
  --disable-libtool-lock  Avoid locking (might break parallel builds)
  --with-pic              Try to use only PIC/non-PIC objects default=use both
  --with-tags=TAGS        Include additional configurations automatic

**Comment by andy236726493** [comment]
你帮忙看一下

**Comment by NathanFreeman** [comment]
> 

sorry，我的锅，msater分支才是集成了postgresql协程客户端。
4.8.8还是要通过编译postgresql协程客户端来使用。
https://github.com/swoole/ext-postgresql

**Comment by andy236726493** [comment]
知道了，谢谢
