### ISSUE TITLE
Swoole Server 在接受UDP报文时worker没有按照预期的轮询方式工作

### ISSUE THREAD

**Issue by jasonhe88** [swoole/swoole-src#466]
Centos 7, php 5.6.12,  swoole  1.7.22 stable

swoole server 监听 UDP 端口, dispatch_mode设置为2. 接受到报文时没有按照设定的轮询方式分发给不同worker进程, 而总是同一个worker进程在处理UDP报文.

**Comment by matyhtf** [comment]
dispatch_mode=2 表示固定分配，轮询要设置为1

**Comment by jasonhe88** [comment]
⊙﹏⊙汗, 不好意思, 这个BUG修好了.
