### ISSUE TITLE
是否可以把 swoole_substr_ 加上 igbinary 和 msgpack 版的

### ISSUE THREAD

**Issue by AlvisZhang** [swoole/swoole-src#4660]
至少加上 igbinary 的吧，好不好

**Comment by matyhtf** [comment]
@AlvisZhang 可以提给 igbinary 和 msgpack 扩展开发者去实现，或者自行修改扩展代码实现，实际上 swoole 提供的 swoole_sbustr unserialize 和 json_decode 实现上也很简单，只是调用了 php 提供的 C API 而已。

**Comment by AlvisZhang** [comment]
这不是自己懒么，而且希望在加载 swoole 扩展时就可用，不用自己再单独搞个扩展。

那就是只能照着你的方法去实现，到时再提个 pull request 来争取合到 swoole 里了吧
