### ISSUE TITLE
cygwin  发生进程退出重启

### ISSUE THREAD

**Issue by hanweiweb** [swoole/swoole-src#4662]
[2022-03-25 10:03:14 $457.0]	WARNING	Server::check_worker_exit_status(): worker(pid=475, id=8) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.8.8, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: CYGWIN_NT-10.0-19043 3.3.4-341.x86_64 2022-01-31 19:35 UTC x86_64
GCC_VERSION: 11.2.0
OPENSSL_VERSION: OpenSSL 1.1.1m  14 Dec 2021
PHP_VERSION : 8.1.1

**Comment by NathanFreeman** [comment]
可以提供一下复现代码或者触发这个bug的流畅吗，谢谢

**Comment by hanweiweb** [comment]
你好，我使用的是easyswoole框架,在主进程注册了自定义进程,并启用了协程.在自定义进程中订阅rabbitmq队列，每次消耗一条rabbitmq消息启动一个协程，代码早docker中跑正常，没有发生多次启动现象，也没有发生退出现象



在 2022-03-25 16:47:07，"MARiA so cute" ***@***.***> 写道：

可以提供一下复现代码或者触发这个bug的流畅吗，谢谢

**Comment by hanweiweb** [comment]
相应的代码已经发送给你了



在 2022-03-25 16:47:07，"MARiA so cute" ***@***.***> 写道：

可以提供一下复现代码或者触发这个bug的流畅吗，谢谢

**Comment by hanweiweb** [comment]
已经在邮箱回复你了

**Comment by hanweiweb** [comment]
已经在邮箱回复你了

**Comment by matyhtf** [comment]
没有新的线索，暂时关闭，若仍然遇到此类错误，可以使用一些工具 strace、gdb 等定位一下，找到引起问题的代码片段，缩小问题范围，重新提交 issue
