### ISSUE TITLE
(Swoole Websocket) Impossible to set cookie, using default handshake method

### ISSUE THREAD

**Issue by dmitryuk** [swoole/swoole-src#4663]
Since [29056](https://github.com/swoole/swoole-src/pull/2906/files) Swoole supports frame compress after handshake.
I have tried it, but faced with the problem, that I cann't send Cookie on connect (session id).
Swoole onOpen event don't receives `Response` object and I see code context also has been ended. 
It's not easy to implement RFC-7692 on php

Please make the feature, for example, `on('beforehandshakeresponse')` event that will be called before https://github.com/swoole/swoole-src/blob/master/ext-src/swoole_websocket_server.cc#L384 with request and response objects, there I will can add response headers.

Please watch my PR https://github.com/swoole/swoole-src/pull/4664

**Comment by NathanFreeman** [comment]
Hi!
Could you please provide the codes for reproducing the error?

**Comment by NathanFreeman** [comment]
Do you mean that you can not send cookie to client server?
You can use onHandshake callback to send cookie to client server if your answer is yes.

**Comment by dmitryuk** [comment]
I can't use onHandshake and websocket_compression together. 

- I can implement onHandshake (without frame compression) and set cookie
- Don't implement onHandshake and finally can't set cookie on connect

**Comment by NathanFreeman** [comment]
Here is my code and work successfully.
```php
<?php
// websocker server
$server = new Swoole\Websocket\Server('127.0.0.1', 8080);
$server->set(['websocket_compression' => true]);
$server->on('handshake', function (\Swoole\Http\Request $request, \Swoole\Http\Response $response) {
    $secWebSocketKey = $request->header['sec-websocket-key'];
    $patten = '#^[+/0-9A-Za-z]{21}[AQgw]==$#';
    if (0 === preg_match($patten, $secWebSocketKey) || 16 !== strlen(base64_decode($secWebSocketKey))) {
        $response->end();
        return false;
    }
    echo $request->header['sec-websocket-key'];
    $key = base64_encode(
        sha1(
            $request->header['sec-websocket-key'] . '258EAFA5-E914-47DA-95CA-C5AB0DC85B11',
            true
        )
    );

    $headers = [
        'Upgrade' => 'websocket',
        'Connection' => 'Upgrade',
        'Sec-WebSocket-Accept' => $key,
        'Sec-WebSocket-Version' => '13',
    ];
    if (isset($request->header['sec-websocket-protocol'])) {
        $headers['Sec-WebSocket-Protocol'] = $request->header['sec-websocket-protocol'];
    }

    foreach ($headers as $key => $val) {
        $response->header($key, $val);
    }
    
    $response->cookie('test', 'test123');
    $response->status(101);
    $response->end();
});


$server->on('start', function ($server) {
    echo "Websocket Server is started at ws://127.0.0.1:8080\n";
});

$server->on('open', function($server, $req) {
    echo "connection open: {$req->fd}\n";
});

$server->on('message', function($server, $frame) {
    echo "received message: {$frame->data}\n";
    $server->push($frame->fd, json_encode(['hello', 'world']));
});

$server->on('close', function($server, $fd) {
    echo "connection close: {$fd}\n";
});

$server->start();
```


```php
// websocker client
<?php
Co\run(function () {
        $cli = new Co\Http\Client('127.0.0.1', 8080);
        $cli->set(['websocket_compression' => true]);
        $cli->upgrade('/');
        var_dump($cli->getCookies());

        $cli->push("hello world");
        var_dump($cli->recv());
});
```
![20220325174508](https://user-images.githubusercontent.com/33935209/160096501-d17111d4-c758-44da-a08e-67ba3f52f436.png)

**Comment by dmitryuk** [comment]
Yes, but frame compression will not work. You kindly set silent flag
The magic goes [here](https://github.com/swoole/swoole-src/blob/master/ext-src/swoole_http_server.cc#L134)
If you set `on('handshake')` event, internal method `swoole_websocket_onHandshake` will not be called (`fci_cache` is not null) and finally no compression goes. In simple words,  `on('handshake')` override internal `swoole_websocket_onHandshake` method.

You can see that your code don't use compression by response. You will not see, for example, `Sec-Websocket-Extensions` header (setting header manually don't help too) and [internal code](https://github.com/swoole/swoole-src/blob/master/ext-src/swoole_websocket_server.cc#L581) (zlib, brotli) will not work at all.
![image](https://user-images.githubusercontent.com/661654/160106276-ddcc35db-8556-46c5-a852-24d8d7a0d8e3.png)

**Comment by NathanFreeman** [comment]
You need to set Sec-Websocket-Extensions manually because you implement onHandshake.
```php
$headers = [
        'Upgrade' => 'websocket',
        'Connection' => 'Upgrade',
        'Sec-WebSocket-Accept' => $key,
        'Sec-WebSocket-Version' => '13',
        'Sec-Websocket-Extensions' => 'permessage-deflate; client_no_context_takeover; server_no_context_takeover'
    ];
    if (isset($request->header['sec-websocket-protocol'])) {
        $headers['Sec-WebSocket-Protocol'] = $request->header['sec-websocket-protocol'];
    }

    foreach ($headers as $key => $val) {
        $response->header($key, $val);
    }
```

**Comment by NathanFreeman** [comment]
You are right.
The conn->websocket_compression attribute is false if implement onHandshake.

**Comment by dmitryuk** [comment]
That's it!

**Comment by Kapsonfire-DE** [comment]
![image](https://user-images.githubusercontent.com/67053124/174881832-f3103a1a-9371-4980-9f21-4f4572066d6e.png)

**Comment by dmitryuk** [comment]
You should use method from https://github.com/swoole/swoole-src/pull/4664, but it it not released yet
