### ISSUE TITLE
疑惑解答

### ISSUE THREAD

**Issue by tw2066** [swoole/swoole-src#4667]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

```
#!/usr/bin/env php
<?php

class HttpController
{
    private string $data = '';

    public function data()
    {
        echo 0;
        if (empty($this->data)){
            echo 1;
            \Swoole\Coroutine\System::sleep(2);
            $this->data = "1";
        }
        return 1;
    }
}

$http = new Swoole\Http\Server('0.0.0.0', 9504);

$httpController = new HttpController();

$http->on('Request', function ($request, $response,)use($httpController) {
    $response->header('Content-Type', 'text/html; charset=utf-8');
    $httpController->data();
    $response->end('<h1>Hello Swoole. #' . rand(1000, 9999) . '</h1>');
});

$http->set([
    'worker_num' => 1,
]);
$http->start();
```
* 通过ab测试
> ab -n 100 -c 20 http://127.0.0.1:9504/
结果
```
01000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

2. What did you expect to see?

希望的结果是 0101010101010...

3.协程测试
```
        for($i=0;$i<20;$i++){
            echo 0;
            go(function (){
                if (empty($this->data)){
                    echo 1;
                    sleep(1);
                    $this->data = "1";
                }
            });
        }
```
这样执行 符合预期

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.1
Built => Nov  5 2021 16:13:16
coroutine => enabled with thread context
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1l  24 Aug 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
[1] 95268
[2] 95269
zsh: command not found: Darwin
[1]  - 95268 exit 127   `uname -a`
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: arm64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
➜  ~ Could not open input file: 8.0.12

[2]  + 95269 exit 1     `php -v`

```

**Comment by NathanFreeman** [comment]
因为cli是常驻内存，你进程里面$httpController就变成共用的。
如果需要输出你想要的结果
```php
$http->on('Request', function ($request, $response,) {
   $httpController = new HttpController();
    $response->header('Content-Type', 'text/html; charset=utf-8');
    $httpController->data();
    $response->end('<h1>Hello Swoole. #' . rand(1000, 9999) . '</h1>');
});
```
下面的协程操作代码没给全，没办法复现。

**Comment by tw2066** [comment]
Controller 一般都是单列的;

在Request回调中 和 直接开go(协程)得到的结果不一样

**Comment by NathanFreeman** [comment]
可以的话给一下开协程的代码吗，因为你上面的代码有个$this，我不知道指的是哪个类。
Request回调中的$httpController在Request回调结束后并不会销毁。因为这个$httpController是在回调之前实例化好并且use进去的，生命周期跟$http这个一样，要等整个程序结束才会释放。

**Comment by sp56** [comment]
> 

他的这个代码在request回调接口上的逻辑代码使用了 **“\Swoole\Coroutine\System::sleep(2)”** ，文档上是说底层会 yield 当前协程，让出时间片，并添加一个异步定时器，当超时时间到达时重新 resume 当前协程，恢复运行。

如按文档所说，逻辑代码执行到 sleep的时候，不应是阻塞的，应该让出cpu处理其他的请求。
但实际是没有让出cpu，一直在这个位置阻塞了。
我的环境是 wsl，使用 strace 追踪：
![image](https://user-images.githubusercontent.com/19342886/160557396-3386ac82-c049-482a-803b-ecc945a0fa5b.png)

我的 ab 是这样的：ab -n 5 -c 2 http://127.0.0.1:9504/，第一个请求过来就阻塞，直到设置的 sleep 计时结束，才开始处理其他请求。

代码如下：
`<?php

class HttpController
{
    private string $data = '';

    public function data()
    {
        echo 0;
        
        //echo "data:",$this->data," | ";

        if (empty($this->data)){
            echo 1;
            \Swoole\Coroutine\System::sleep(10.0);
            $this->data = "1";
        }
        return 1;
    }
}

$http = new Swoole\Http\Server('0.0.0.0', 9504);

$httpController = new HttpController();

$http->on('Request', function ($request, $response) use($httpController) {
    $response->header('Content-Type', 'text/html; charset=utf-8');
    $httpController->data();
    $response->end('<h1>Hello Swoole. #' . rand(1000, 9999) . '</h1>');
});

$http->set([
    'worker_num' => 1,
    'task_worker_num'=>0,
    'enable_coroutine'=>true,
]);
$http->start();`

环境是：
`PHP 7.4.21 (cli) (built: Nov 23 2021 12:19:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies`

扩展版本：
`Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.2
Built => Nov 23 2021 14:46:12
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1f  31 Mar 2020
dtls => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608`

**Comment by NathanFreeman** [comment]
我感觉是ab这个工具的问题，你可以试试wrk。
```shell
wrk -t12 -c100 -d10s http://127.0.0.1:9504/
```

测试发现ab好像是先发出一个请求，等到第一个请求返回后没问题。才会根据-c 指定的参数一组一组的请求服务端。

**Comment by sp56** [comment]
> 我感觉是ab这个工具的问题，你可以试试wrk。
> 
> ```shell
> wrk -t12 -c100 -d10s http://127.0.0.1:9504/
> ```
> 
> 测试发现ab好像是先发出一个请求，等到第一个请求返回后没问题。才会根据-c 指定的参数一组一组的请求服务端。

确实是哈，换一个工具之后结果是预期的，待会去详细看看ab的文档

**Comment by tw2066** [comment]
设置 \Swoole\Coroutine\System::sleep(20);  设置20s
 用浏览器测试 和ab测试 一样的结果
