### ISSUE TITLE
worker 进程会提前意外退出

### ISSUE THREAD

**Issue by jasonhe88** [swoole/swoole-src#467]
Centos 7,  php 5.6.12,  Swoole 1.7.22 table

Swoole server 监听TCP端口, dispatch_mode设为2, 同时启动数个 task 进程, task_ipc_mode 设为2. 发现有一定的几率某个worker进程会提前退出, 而onReceive里没有任何执行语句包括exit或die. 在log里发现如下错误信息:

[2015-12-28 10:04:34 *38404.8]  WARN    zm_deactivate_swoole: worker process is terminated by exit()/die(). 

当task_ipc_mode 设置为1时没有此错误信息, 设为2或3时会发生

strace 某提前退出的worker 进程有如下信息:

44361 write(1, "TCP connection fd: 37, from_id: "..., 34) = 34
44361 epoll_wait(12, {{EPOLLIN, {u32=9, u64=21474836489}}}, 4096, -1) = 1
44361 read(9, "'\0\0\0\0\0\1\0\5\0\0\0", 8192) = 12
44361 write(1, "TCP connection fd: 39, from_id: "..., 34) = 34
44361 epoll_wait(12, {{EPOLLIN, {u32=9, u64=21474836489}}}, 4096, -1) = 1
44361 read(9, "%\0\0\0\22\2\1\0\nhmP\0\0\2\16\204\241I\0\241T\6\241M\332\1\364aaaa"..., 8192) = 542
44361 write(1, "#", 1)                  = -1 EAGAIN (Resource temporarily unavailable)
44361 select(2, [], [1], [], {18446744073709551615, 0}) = -1 EINVAL (Invalid argument)
44361 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
44361 write(4, "[2015-12-28 13:06:12 *44361.1]\tW"..., 104) = 104
44361 close(2)                          = 0
44361 close(1)                          = 0
44361 close(0)                          = 0
44361 munmap(0x7f535e098000, 266240)    = 0
44361 munmap(0x7f5350b1f000, 2130584)   = 0
44361 munmap(0x7f53508d7000, 2389000)   = 0
44361 munmap(0x7f5351498000, 2141096)   = 0
44361 munmap(0x7f5351245000, 2436336)   = 0
44361 munmap(0x7f53516a3000, 2495856)   = 0
44361 munmap(0x7f5351905000, 2188888)   = 0
44361 munmap(0x7f5351b1c000, 2547056)   = 0
44361 munmap(0x7f5350655000, 528384)    = 0
44361 close(12)                         = 0
44361 munmap(0x7f5351d8a000, 2534632)   = 0
44361 munmap(0x7f535e128000, 1052672)   = 0
44361 munmap(0x7f535e229000, 266240)    = 0
44361 munmap(0x7f535e0d9000, 323584)    = 0
44361 exit_group(0)                     = ?
44361 +++ exited with 0 +++

**Comment by greensea** [comment]
我也遇到相同的问题，错误日志中提示：
WARN zm_deactivate_swoole: worker process is terminated by exit()/die().
但是代码中没有任何 die() 或 exit() 语句

**Comment by smalleyes** [comment]
[2016-02-05 21:01:33 $14910.0]  WARN    swSignal_callback: signal[1] callback is null.
[2016-02-05 21:01:33 $14910.0]  WARN    swSignal_callback: signal[1] callback is null.
[2016-02-05 21:01:33 $14910.0]  WARN    swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=1
[2016-02-05 21:01:33 $14910.0]  WARN    zm_deactivate_swoole: worker process is terminated by exit()/die().
意外退出，日志出现这几句。环境出现变化的是当时的网段出现变化，从172.16.2.xxx到192.168.1.xxx

**Comment by smalleyes** [comment]
strace -f -p xxx 
重复出现
[pid 16023] exit_group(0)               = ?
[pid 16023] +++ exited with 0 +++
<... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 16023
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=16023, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fea915beb10) = 16024
strace: Process 16024 attached
[pid  2190] wait4(-1,  <unfinished ...>
[pid 16024] set_robust_list(0x7fea915beb20, 24) = 0
[pid 16024] rt_sigaction(SIGHUP, {0x7fea81737bf0, [], SA_RESTORER, 0x7fea8d9a79f0}, {0x7fea81737bf0, [], SA_RESTORER, 0x7fea8d9a79f0}, 8) = 0
[pid 16024] rt_sigaction(SIGPIPE, {0x7fea81737bf0, [], SA_RESTORER, 0x7fea8d9a79f0}, {SIG_IGN, [], SA_RESTORER, 0x7fea8e07cb20}, 8) = 0
[pid 16024] rt_sigaction(SIGUSR1, {0x7fea81737bf0, [], SA_RESTORER, 0x7fea8d9a79f0}, {0x7fea81737bf0, [], SA_RESTORER, 0x7fea8d9a79f0}, 8) = 0
[pid 16024] rt_sigaction(SIGUSR2, {0x7fea81737bf0, [], SA_RESTORER, 0x7fea8d9a79f0}, {0x7fea81737bf0, [], SA_RESTORER, 0x7fea8d9a79f0}, 8) = 0
[pid 16024] rt_sigaction(SIGTERM, {0x7fea81737bf0, [], SA_RESTORER, 0x7fea8d9a79f0}, {0x7fea81737bf0, [], SA_RESTORER, 0x7fea8d9a79f0}, 8) = 0
[pid 16024] rt_sigaction(SIGALRM, {0x7fea81737bf0, [], SA_RESTORER, 0x7fea8d9a79f0}, {SIG_DFL, [], 0}, 8) = 0
[pid 16024] rt_sigaction(SIGVTALRM, {0x7fea81737bf0, [], SA_RESTORER, 0x7fea8d9a79f0}, {SIG_DFL, [], 0}, 8) = 0
[pid 16024] mmap(NULL, 2101248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fea7dafb000
[pid 16024] open("/dev/urandom", O_RDONLY) = 6
[pid 16024] read(6, "\331\10\243\325", 4) = 4
[pid 16024] epoll_create(512)           = 7
[pid 16024] mmap(NULL, 208896, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fea7dac8000
[pid 16024] fcntl(4, F_GETFL)           = 0x802 (flags O_RDWR|O_NONBLOCK)
[pid 16024] fcntl(4, F_SETFL, O_RDWR|O_NONBLOCK) = 0
[pid 16024] epoll_ctl(7, EPOLL_CTL_ADD, 4, {EPOLLIN, {u32=4, u64=21474836484}}) = 0
[pid 16024] geteuid()                   = 1000
[pid 16024] nanosleep({0, 0}, NULL)     = 0
[pid 16024] write(1, "2189          ", 14) = -1 EIO (Input/output error)
[pid 16024] stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=414, ...}) = 0
[pid 16024] write(3, "[2016-02-15 10:10:28 *16024.0]\tW"..., 104) = 104
[pid 16024] close(2)                    = 0
[pid 16024] close(1)                    = 0
[pid 16024] close(0)                    = 0
[pid 16024] munmap(0x7fea913eb000, 266240) = 0
[pid 16024] munmap(0x7fea7ea79000, 2383352) = 0
[pid 16024] munmap(0x7fea7ecbf000, 2171512) = 0
[pid 16024] munmap(0x7fea7eed2000, 2158888) = 0
[pid 16024] munmap(0x7fea7f0e2000, 2126952) = 0
[pid 16024] munmap(0x7fea7f2ea000, 2130672) = 0
[pid 16024] munmap(0x7fea7f4f3000, 2122944) = 0
[pid 16024] munmap(0x7fea7f6fa000, 2126760) = 0
[pid 16024] munmap(0x7fea7f902000, 2234536) = 0
[pid 16024] munmap(0x7fea7fb24000, 2147240) = 0
[pid 16024] munmap(0x7fea7fd31000, 2359400) = 0
[pid 16024] munmap(0x7fea808bf000, 2131272) = 0
[pid 16024] munmap(0x7fea806aa000, 2180320) = 0
[pid 16024] munmap(0x7fea8046b000, 2351336) = 0
[pid 16024] munmap(0x7fea80186000, 3031840) = 0
[pid 16024] munmap(0x7fea7ff72000, 2175096) = 0
[pid 16024] munmap(0x7fea80ac8000, 2143200) = 0
[pid 16024] munmap(0x7fea80cd4000, 2147584) = 0
[pid 16024] munmap(0x7fea80ee1000, 2113904) = 0
[pid 16024] munmap(0x7fea810e6000, 2109904) = 0
[pid 16024] munmap(0x7fea812ea000, 2105680) = 0
[pid 16024] munmap(0x7fea814ed000, 2114032) = 0
[pid 16024] munmap(0x7fea7df42000, 528384) = 0
[pid 16024] munmap(0x7fea7e7f7000, 528384) = 0
[pid 16024] close(7)                    = 0
[pid 16024] munmap(0x7fea816f2000, 2523816) = 0
[pid 16024] munmap(0x7fea81c2d000, 2145536) = 0
[pid 16024] munmap(0x7fea8195b000, 2955064) = 0
[pid 16024] munmap(0x7fea81e39000, 2184384) = 0
[pid 16024] munmap(0x7fea8204f000, 2147616) = 0
[pid 16024] munmap(0x7fea8225c000, 2109816) = 0
[pid 16024] munmap(0x7fea82460000, 2126736) = 0
[pid 16024] munmap(0x7fea82668000, 2364816) = 0
[pid 16024] munmap(0x7fea828aa000, 2210016) = 0
[pid 16024] munmap(0x7fea82ac6000, 2378880) = 0
[pid 16024] munmap(0x7fea82d0b000, 2139000) = 0
[pid 16024] munmap(0x7fea82f16000, 2109808) = 0
[pid 16024] munmap(0x7fea8311a000, 2147152) = 0
[pid 16024] munmap(0x7fea83327000, 4995456) = 0
[pid 16024] munmap(0x7fea837eb000, 2159376) = 0
[pid 16024] munmap(0x7fea839fb000, 2274152) = 0
[pid 16024] munmap(0x7fea85ba6000, 2180192) = 0
[pid 16024] munmap(0x7fea8592c000, 2594536) = 0
[pid 16024] munmap(0x7fea8570b000, 2232240) = 0
[pid 16024] munmap(0x7fea854d7000, 2306080) = 0
[pid 16024] munmap(0x7fea852ab000, 2273952) = 0
[pid 16024] munmap(0x7fea83e44000, 2430320) = 0
[pid 16024] munmap(0x7fea84096000, 2154984) = 0
[pid 16024] munmap(0x7fea84e41000, 2255616) = 0
[pid 16024] munmap(0x7fea85068000, 2368432) = 0
[pid 16024] munmap(0x7fea84b1a000, 3302728) = 0
[pid 16024] munmap(0x7fea848ed000, 2280032) = 0
[pid 16024] munmap(0x7fea844e4000, 2113936) = 0
[pid 16024] munmap(0x7fea846e9000, 2109808) = 0
[pid 16024] munmap(0x7fea842a5000, 2354528) = 0
[pid 16024] munmap(0x7fea83c27000, 2213960) = 0
[pid 16024] munmap(0x7fea85dbb000, 2109744) = 0
[pid 16024] munmap(0x7fea85fbf000, 2127352) = 0
[pid 16024] munmap(0x7fea863d7000, 2118704) = 0
[pid 16024] munmap(0x7fea861c7000, 2161672) = 0
[pid 16024] munmap(0x7fea865dd000, 2143472) = 0
[pid 16024] munmap(0x7fea9147b000, 1052672) = 0
[pid 16024] munmap(0x7fea9157c000, 266240) = 0
[pid 16024] munmap(0x7fea9142c000, 323584) = 0
[pid 16024] exit_group(0)               = ?

**Comment by Tinywan** [comment]
This problem is solved?

**Comment by matyhtf** [comment]
`[pid 16024] write(1, "2189 ", 14) = -1 EIO (Input/output error)`
标准输出已关闭，错误的输出。导致php退出。需要设置为守护进程。
