### ISSUE TITLE
cygwin 编译sockets 能加入  --enable-fd-setsize=1024 参数吗

### ISSUE THREAD

**Issue by hanweiweb** [swoole/swoole-src#4672]
![image](https://user-images.githubusercontent.com/93665931/161236318-f5a0d85c-5b4f-4b6f-ba75-5899ff44f4fe.png)

报这个错误:
stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 64, but you have descriptors numbered at least as high as 64.
 --enable-fd-setsize=1024 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date.

**Comment by twose** [comment]
理论上开启runtimehook以后用的是Swoole提供的`stream_select`

**Comment by matyhtf** [comment]
@hanweiweb swoole 在 cygwin 下使用 poll，没有并发上限
