### ISSUE TITLE
swoole.so）存在硬编码口令

### ISSUE THREAD

**Issue by ganl** [swoole/swoole-src#4677]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

安全扫描结果存在硬编码口令
![image](https://user-images.githubusercontent.com/11937688/162235794-620a73d9-71e3-4178-b272-dfa66b8c30a1.png)

2. What did you expect to see?

口令不能硬编码在代码中，应该配置文件形式存放可编辑

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by sy-records** [comment]
前三个是配置项名称。后面一个是默认值，用户传入可修改

**Comment by ganl** [comment]
最后一个可否留空？
