### ISSUE TITLE
swReactorThread_onReceive_http_request: http header is too long.

### ISSUE THREAD

**Issue by guzuomuse** [swoole/swoole-src#468]
服务器端总是会提示：

WARN swReactorThread_onReceive_http_request: http header is too long.

即使设置了 'package_max_length'=>104857600,//最大接受100k的字符也无效

同时在php.ini设置了swoole.unixsock_buffer_size=104857600也无效；

谢谢！

**Comment by matyhtf** [comment]
错误的Http请求，底层限定了Http Header最大不得超过8K
