### ISSUE TITLE
pecl install swoole fatal error: 'pcre2.h' file not found

### ISSUE THREAD

**Issue by Lance-93** [swoole/swoole-src#4684]
我已经ln -s 了pcre2.h到对应目录下 为何始终还是提示找不到该文件
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/41180782/162715540-d183788e-f169-4f79-8fab-a8e39eb05522.png">

**Comment by matyhtf** [comment]
使用 apt/yum 安装 libpcre2-dev
