### ISSUE TITLE
子进程使用Message Queue的问题

### ISSUE THREAD

**Issue by jasonhe88** [swoole/swoole-src#469]
Centos 7   php 5.6.12   Swoole  1.76.22 stable

如下一段简单代码, 运行时会报错(错误信息见尾部). 

但是如果删除 $process->useQueue() 这行, 就不会出错

<?php
$process = new swoole_process('callback_function');

$process->useQueue(); // <======如果删除这行就不会出错

$pid = $process->start();
function callback_function(swoole_process $worker)
{
        sleep(1);
}

swoole_process::wait();

========================== 错误信息 ===========================

*** Error in `php': free(): invalid pointer: 0x00007fdef2bb86c8 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7d1fd)[0x7fdef020b1fd]
/usr/local/lib/php/extensions/no-debug-non-zts-20131226/swoole.so(+0x237ae)[0x7fdee67057ae]
php(zend_call_function+0xa26)[0x7583d6]
php(zend_call_method+0x185)[0x77e5a5]
php(zend_objects_destroy_object+0x252)[0x78caf2]
php(zend_objects_store_call_destructors+0x55)[0x792555]
php[0x756d2d]
php(zend_call_destructors+0x34)[0x767564]
php(php_request_shutdown+0x365)[0x706975]
php[0x80daeb]
php[0x43088f]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fdef01afaf5]
php[0x43092d]
======= Memory map: ========
00400000-00d9b000 r-xp 00000000 fd:00 36747951                           /usr/local/bin/php
未完,,,,,还有很多

**Comment by matyhtf** [comment]
确实是底层的问题，和最新的代码修改有关，已修复。
