### ISSUE TITLE
there is a problem with Coroutine-PDO-pool Database connection

### ISSUE THREAD

**Issue by MichonneHsu** [swoole/swoole-src#4692]
1. What did you do? If possible, provide a simple script for reproducing the error.

Did'nt show error in php-error ,eveything is normal,but when i  execute a script ,
for example
this is a script contents
```
Runtime::enableCoroutine();

run(function () {
    $a=(new Brands())->test();
    print_r($a);
});
```
my options param  :
```
  PDO::ATTR_PERSISTENT => true,
```
and other params are not matter .
this test function is going to  print results from datatable .

2. What did you expect to see?
i was expected  the result would be like this:
```
[
   [
       'id'=>1,
       'name'=>'test'
   ]
]
```
3. What did you see instead?
```
[
   [
       'id'=>1,
       'name'=>'test'
   ]
]
zend_mm_heap corrupted
```
with ` zend_mm_heap corrupted` these words in the end.
the weired thing is , postman does'n show `zend_mm_heap corrupted` in the end

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.8.6

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
php 8.0.15

when i set
`
  PDO::ATTR_PERSISTENT => false,
`
and repeat what i did before and problem solved, i don't know this is a bug or not

**Comment by NathanFreeman** [comment]
Hi.
I can not reproduce it.
```php
<?php
use function Swoole\Coroutine\run;
Swoole\Runtime::enableCoroutine();
run(function () {
  $pdo = new \PDO('pgsql:host=127.0.0.1;port=5432;dbname=postgres','postgres',"123456",array(PDO::ATTR_PERSISTENT => true));
  $i = 0;
  while($i <= 3) {
        $result = [];
        $sth = $pdo->prepare('select * from public.email2');
        $sth->execute();
        while($row = $sth->fetch(PDO::FETCH_ASSOC)) {
                $result[] = $row;
        }
        $i++;
        print_r($result);
   }
});
```

**Comment by MichonneHsu** [comment]
> Hi. I can not reproduce it.
> 
> ```
> <?php
> use function Swoole\Coroutine\run;
> Swoole\Runtime::enableCoroutine();
> run(function () {
>   $pdo = new \PDO('pgsql:host=127.0.0.1;port=5432;dbname=postgres','postgres',"123456",array(PDO::ATTR_PERSISTENT => true));
>   $i = 0;
>   while($i <= 3) {
>         $result = [];
>         $sth = $pdo->prepare('select * from public.email2');
>         $sth->execute();
>         while($row = $sth->fetch(PDO::FETCH_ASSOC)) {
>                 $result[] = $row;
>         }
>         $i++;
>         print_r($result);
>    }
> });
> ```

MB,I forgot that i put PDO connection outside ,should intiate it first
