### ISSUE TITLE
thread context和boost asm context区别

### ISSUE THREAD

**Issue by Galaxy0419** [swoole/swoole-src#4695]
coroutine现在的实现可以使用thread context或者是boost asm context。这两个有什么区别？什么时候用哪个？

**Comment by matyhtf** [comment]
默认使用 boost asm context 

thread context 是切换为类似于 Python GIL 技术的伪多线程模式，有两种情况可以使用 thread context ，thread context 仅支持非线程安全（NTS）模式。

1. 调试：线程有比较丰富的调试工具，可以直接使用 gdb 或者 strace 等工具进行追踪
2. 特殊平台支持：C++ thread 是标准库提供的，在几乎所有平台均可使用，而 boost asm context 仅支持有限的平台，如果对应平台不支持 boost asm context，就可以使用 thread context
