### ISSUE TITLE
Can i invoke sleep function in worker process?

### ISSUE THREAD

**Issue by caizhichao** [swoole/swoole-src#4696]
```php
<?php

use Swoole\Server;

$serv = new \swoole_websocket_server('0.0.0.0', '6666', SWOOLE_PROCESS, SWOOLE_SOCK_TCP);

$serv->on('message', function() {

});

$serv->on('pipeMessage', function() {
    $params = func_get_args();
    var_dump($params[2]);

});

$serv->on('workerStart', function() {
    $params = func_get_args();
    /** @var Server $server */
    $server = $params[0];
    $workerId = $params[1];
    if ($server->taskworker) {

    } else {
        if ($server->worker_id === 0) {
            $need = 10000;
            $n = 0;
            while ($need-- > 0) {
                $server->sendMessage('z' . ($n++), 4);
            }
            sleep(1000);
        }
    }

});

$serv->start();


```

when i invoke 'sleep' function,
![image](https://user-images.githubusercontent.com/25865457/163953378-c291b98d-3b79-463c-aec0-ddda1ccb1869.png)

when i delete the 'sleep' line
![image](https://user-images.githubusercontent.com/25865457/163953449-2eecdddd-d095-4527-8163-85731972e9b0.png)

**Comment by caizhichao** [comment]
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.5
Built => Apr 21 2021 16:13:29
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

**Comment by leocavalcante** [comment]
All your 10.000 messages will be sent before the `sleep()` call anyway. That is why you don't see any difference.

**Comment by caizhichao** [comment]
I mean it must be same, but as you see , tow picture's last line is different

**Comment by leocavalcante** [comment]
Okay, now I got it. It didn't reach the end (9999) when there is a `sleep()` call.

This is expected. Remember that `sleep()` is in seconds, so you will make it wait 1000 seconds (~16 minutes), before resuming the dumps.

Change `sleep(1000)` to `sleep(1)` so you can see this effect happening. It will dump about 5500 outputs, wait for a second, then resume to the 9999.

To help you better, why do you want a sleep call there? Or you are just testing?

**Comment by caizhichao** [comment]
As my working need, i write a program in worker process `sendMessage` to task process, and i `sleep` 5s for waiting the Redis task queue empty, i use `var_dump` to watching the progress is running normally , just unexpected, sometime it has no console out, so, i write demo for checking my guess.  By the way, when i use `echo`, the out is what i expected.  Just giving a feedback.

**Comment by NathanFreeman** [comment]
@caizhichao Hi.
The fd of worker process 2 turns to not ready after the worker process 2 has sent some data.
So the rest of data was written to the buffer by worker process 1 and wait for worker process 2 fd to be ready.
The rest of data can only be sent after the worker process 1 is awakened because there is a sleep() call.

**Comment by caizhichao** [comment]
@NathanFreeman If you call `echo` , it's meet expectation.

**Comment by NathanFreeman** [comment]
@caizhichao Hi.
There is not difference between the results of `echo` and `var_dump`.
```php
$serv->on('pipeMessage', function() {
    $params = func_get_args();
    echo $params[2];
});
```
![微信图片_20220421141211](https://user-images.githubusercontent.com/33935209/164386390-e362aca4-8d5f-4466-9ac4-2e8a50fe8ae8.png)

**Comment by caizhichao** [comment]
@NathanFreeman That's not in my expectation.

**Comment by NathanFreeman** [comment]
Maybe Swoole\Server->taskwait() can help you.
The taskwait function will not return unless the task worker has completed and returned a result or if the timeout is reached.

**Comment by caizhichao** [comment]
Thank you, i had change my way to complete work.

**Comment by matyhtf** [comment]
After exceeding the pipe socket buffer, must listen for writable event. 
The sleep function will cause the worekr process to be blocking and cannot join to the event loop
