### ISSUE TITLE
使用微信支付SDK上传超过64K文件报 signal=11

### ISSUE THREAD

**Issue by zhlhuang** [swoole/swoole-src#4698]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
使用我微信支付的sdk上传素材接口只能上传64K的文件。超过64k之后就报
ProcessPool::wait(): worker#3 abnormal exit, status=0, signal=11
下面是我排查的过程。
[https://github.com/wechatpay-apiv3/wechatpay-php/issues/88](https://github.com/wechatpay-apiv3/wechatpay-php/issues/88)
2. What did you expect to see?
这是我gdb获取到的内容，好像没有什么
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Attaching to process 14490
Reading symbols from /www/server/php/74/bin/php...done.
Reading symbols from /lib64/libcrypt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libcrypt.so.1
Reading symbols from /lib64/libresolv.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libresolv.so.2
Reading symbols from /lib64/librt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/librt.so.1
Reading symbols from /lib64/libstdc++.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libstdc++.so.6
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /lib64/libxml2.so.2...Reading symbols from /lib64/libxml2.so.2...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libxml2.so.2
Reading symbols from /usr/local/openssl/lib/libssl.so.1.0.0...(no debugging symbols found)...done.
Loaded symbols for /usr/local/openssl/lib/libssl.so.1.0.0
Reading symbols from /usr/local/openssl/lib/libcrypto.so.1.0.0...(no debugging symbols found)...done.
Loaded symbols for /usr/local/openssl/lib/libcrypto.so.1.0.0
Reading symbols from /lib64/libsqlite3.so.0...Reading symbols from /lib64/libsqlite3.so.0...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libsqlite3.so.0
Reading symbols from /lib64/libz.so.1...Reading symbols from /lib64/libz.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libz.so.1
Reading symbols from /usr/local/curl/lib/libcurl.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/local/curl/lib/libcurl.so.4
Reading symbols from /lib64/libcares.so.2...Reading symbols from /lib64/libcares.so.2...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libcares.so.2
Reading symbols from /lib64/libpng15.so.15...Reading symbols from /lib64/libpng15.so.15...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libpng15.so.15
Reading symbols from /lib64/libwebp.so.4...Reading symbols from /lib64/libwebp.so.4...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libwebp.so.4
Reading symbols from /lib64/libjpeg.so.62...Reading symbols from /lib64/libjpeg.so.62...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libjpeg.so.62
Reading symbols from /lib64/libfreetype.so.6...Reading symbols from /lib64/libfreetype.so.6...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libfreetype.so.6
Reading symbols from /lib64/libicuio.so.50...Reading symbols from /lib64/libicuio.so.50...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libicuio.so.50
Reading symbols from /lib64/libicui18n.so.50...Reading symbols from /lib64/libicui18n.so.50...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libicui18n.so.50
Reading symbols from /lib64/libicuuc.so.50...Reading symbols from /lib64/libicuuc.so.50...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libicuuc.so.50
Reading symbols from /lib64/libicudata.so.50...Reading symbols from /lib64/libicudata.so.50...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libicudata.so.50
Reading symbols from /lib64/libonig.so.5...Reading symbols from /lib64/libonig.so.5...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libonig.so.5
Reading symbols from /lib64/libsodium.so.23...Reading symbols from /lib64/libsodium.so.23...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libsodium.so.23
Reading symbols from /lib64/libgcc_s.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgcc_s.so.1
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/libfreebl3.so...Reading symbols from /lib64/libfreebl3.so...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libfreebl3.so
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /lib64/liblzma.so.5...Reading symbols from /lib64/liblzma.so.5...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/liblzma.so.5
Reading symbols from /lib64/libbz2.so.1...Reading symbols from /lib64/libbz2.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libbz2.so.1
Reading symbols from /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/zip.so...(no debugging symbols found)...done.
Loaded symbols for /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/zip.so
Reading symbols from /lib64/libzip.so.5...Reading symbols from /lib64/libzip.so.5...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libzip.so.5
Reading symbols from /lib64/libssl.so.10...Reading symbols from /lib64/libssl.so.10...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libssl.so.10
Reading symbols from /lib64/libcrypto.so.10...Reading symbols from /lib64/libcrypto.so.10...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libcrypto.so.10
Reading symbols from /lib64/libgssapi_krb5.so.2...Reading symbols from /lib64/libgssapi_krb5.so.2...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libgssapi_krb5.so.2
Reading symbols from /lib64/libkrb5.so.3...Reading symbols from /lib64/libkrb5.so.3...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libkrb5.so.3
Reading symbols from /lib64/libcom_err.so.2...Reading symbols from /lib64/libcom_err.so.2...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libcom_err.so.2
Reading symbols from /lib64/libk5crypto.so.3...Reading symbols from /lib64/libk5crypto.so.3...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libk5crypto.so.3
Reading symbols from /lib64/libkrb5support.so.0...Reading symbols from /lib64/libkrb5support.so.0...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libkrb5support.so.0
Reading symbols from /lib64/libkeyutils.so.1...Reading symbols from /lib64/libkeyutils.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libkeyutils.so.1
Reading symbols from /lib64/libselinux.so.1...Reading symbols from /lib64/libselinux.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libselinux.so.1
Reading symbols from /lib64/libpcre.so.1...Reading symbols from /lib64/libpcre.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libpcre.so.1
Reading symbols from /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/bt_safe.so...done.
Loaded symbols for /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/bt_safe.so
Reading symbols from /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/fileinfo.so...done.
Loaded symbols for /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/fileinfo.so
Reading symbols from /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/imagick.so...done.
Loaded symbols for /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/imagick.so
Reading symbols from /usr/local/ImageMagick-7.1.0/lib/libMagickWand-7.Q16HDRI.so.10...done.
Loaded symbols for /usr/local/ImageMagick-7.1.0/lib/libMagickWand-7.Q16HDRI.so.10
Reading symbols from /usr/local/ImageMagick-7.1.0/lib/libMagickCore-7.Q16HDRI.so.10...done.
Loaded symbols for /usr/local/ImageMagick-7.1.0/lib/libMagickCore-7.Q16HDRI.so.10
Reading symbols from /lib64/libtiff.so.5...Reading symbols from /lib64/libtiff.so.5...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libtiff.so.5
Reading symbols from /lib64/libfontconfig.so.1...Reading symbols from /lib64/libfontconfig.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libfontconfig.so.1
Reading symbols from /lib64/libXext.so.6...Reading symbols from /lib64/libXext.so.6...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libXext.so.6
Reading symbols from /lib64/libXt.so.6...Reading symbols from /lib64/libXt.so.6...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libXt.so.6
Reading symbols from /lib64/libSM.so.6...Reading symbols from /lib64/libSM.so.6...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libSM.so.6
Reading symbols from /lib64/libICE.so.6...Reading symbols from /lib64/libICE.so.6...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libICE.so.6
Reading symbols from /lib64/libX11.so.6...Reading symbols from /lib64/libX11.so.6...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libX11.so.6
Reading symbols from /lib64/libgomp.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgomp.so.1
Reading symbols from /lib64/libjbig.so.2.0...Reading symbols from /lib64/libjbig.so.2.0...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libjbig.so.2.0
Reading symbols from /lib64/libexpat.so.1...Reading symbols from /lib64/libexpat.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libexpat.so.1
Reading symbols from /lib64/libuuid.so.1...Reading symbols from /lib64/libuuid.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libuuid.so.1
Reading symbols from /lib64/libxcb.so.1...Reading symbols from /lib64/libxcb.so.1...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libxcb.so.1
Reading symbols from /lib64/libXau.so.6...Reading symbols from /lib64/libXau.so.6...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Loaded symbols for /lib64/libXau.so.6
Reading symbols from /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/swoole.so...done.
Loaded symbols for /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/swoole.so
Reading symbols from /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/exif.so...done.
Loaded symbols for /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/exif.so
Reading symbols from /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/mcrypt.so...done.
Loaded symbols for /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/mcrypt.so
Reading symbols from /usr/local/lib/libmcrypt.so.4...done.
Loaded symbols for /usr/local/lib/libmcrypt.so.4
Reading symbols from /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/bz2.so...done.
Loaded symbols for /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/bz2.so
Reading symbols from /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/calendar.so...done.
Loaded symbols for /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/calendar.so
Reading symbols from /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/sysvshm.so...done.
Loaded symbols for /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/sysvshm.so
Reading symbols from /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/sysvmsg.so...done.
Loaded symbols for /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/sysvmsg.so
0x00007fee332ef102 in wait () from /lib64/libpthread.so.0
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 c-ares-1.10.0-3.el7.x86_64 expat-2.1.0-14.el7_9.x86_64 fontconfig-2.13.0-4.3.el7.x86_64 freetype-2.8-14.el7_9.1.x86_64 glibc-2.17-325.el7_9.x86_64 jbigkit-libs-2.0-11.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-51.el7_9.x86_64 libICE-1.0.9-9.el7.x86_64 libSM-1.2.2-2.el7.x86_64 libX11-1.6.7-4.el7_9.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXt-1.1.5-3.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libgomp-4.8.5-44.el7.x86_64 libicu-50.2-4.el7_7.x86_64 libjpeg-turbo-1.2.90-8.el7.x86_64 libpng-1.5.13-8.el7.x86_64 libselinux-2.5-15.el7.x86_64 libsodium-1.0.18-1.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libtiff-4.0.3-35.el7.x86_64 libuuid-2.23.2-65.el7_9.1.x86_64 libwebp-0.3.0-10.el7_9.x86_64 libxcb-1.13-1.el7.x86_64 libxml2-2.9.1-6.el7_9.6.x86_64 libzip5-1.5.2-1.el7.remi.x86_64 nss-softokn-freebl-3.67.0-3.el7_9.x86_64 oniguruma-6.8.2-1.el7.x86_64 openssl-libs-1.0.2k-25.el7_9.x86_64 pcre-8.32-17.el7.x86_64 sqlite-3.7.17-8.el7_7.1.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-19.el7_9.x86_64

4. What did you see instead?

5. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.9
Built => Apr 20 2022 23:17:38
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.0.2 15 Mar 2022
dtls => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux VM-20-12-centos 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.4.28 (cli) (built: Apr 19 2022 15:21:42) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by Yurunsoft** [comment]
如果你是wsl1用户可以无视这个问题，wsl1的bug

**Comment by zhlhuang** [comment]
> 如果你是wsl1用户可以无视这个问题，wsl1的bug

不是，我用的是腾讯云的轻量级服务器，CentOS 7.9.2009 x86_64。

**Comment by NathanFreeman** [comment]
请问是上传图片的接口吗

**Comment by zhlhuang** [comment]
> 请问是上传图片的接口吗

是的，就是上传素材的接口。

**Comment by matyhtf** [comment]
可能是因为 libcurl 版本过低导致的，请使用 `curl --version` 查看 curl 版本。
另外可以使用 valgrind 和 gdb 跟踪一下 coredump 的信息，或者也可以提供一份稳定重现的 demo 和 docker 运行环境

**Comment by zhlhuang** [comment]
> 可能是因为 libcurl 版本过低导致的，请使用 `curl --version` 查看 curl 版本。 另外可以使用 valgrind 和 gdb 跟踪一下 coredump 的信息，或者也可以提供一份稳定重现的 demo 和 docker 运行环境

上面信息有gdb的信息，但是好像报错后没有新的信息打印出来。
curl 7.29.0 的。centos提示是最新的。

**Comment by matyhtf** [comment]
```
USE_ZEND_ALLOC=0 valgrind php your_file.php
```
执行并重现你的问题，然后将输出的内容发给我们。另外请添加微信 19921030512 沟通

**Comment by matyhtf** [comment]
低版本 curl 问题
