### ISSUE TITLE
4.8.9版本信号重复注册问题

### ISSUE THREAD

**Issue by raylin666** [swoole/swoole-src#4700]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

<img width="814" alt="image" src="https://user-images.githubusercontent.com/10880431/164661032-f30cef3c-c24a-4f85-a7b0-91b82a56ca91.png">

我在 onWorkerStart 事件里注册`SIGPIPE`和`SIG_IGN`信号, 报错系统已注册该信号 。看官方文档 https://wiki.swoole.com/#/process/process?id=signal 应该是说会覆盖历史设置。

2. What did you expect to see?

是不能重复注册 还是文档没更新？

3. What version of Swoole are you using (show your `php --ri swoole`)?

# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.9
Built => Apr 22 2022 14:53:57
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1n  15 Mar 2022
dtls => enabled
http2 => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

4. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

PHP 7.4.26 (cli) (built: Dec  2 2021 14:29:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by NathanFreeman** [comment]
SIGPIPE这个信号在worker进程初始化的时候就已经被注册了。

**Comment by matyhtf** [comment]
@raylin666 系统设置的信号是不允许覆盖的，`4.8`版本底层已经将`SIGPIPE`设置为`SIGIGN`，应用层可以删除这个信号注册
