### ISSUE TITLE
redis　async　反馈下问题～

### ISSUE THREAD

**Issue by yiliaofan** [swoole/swoole-src#471]
反馈下问题：
<pre>
+$client = new swoole_redis;
 +$client->connect('127.0.0.1', 6379, function (swoole_redis $client, $result) {
 +    $client->execute('SET key swoole', function (swoole_redis $client, $result) {
 +        var_dump($client, $result);
 +        $client->execute('get key', function (swoole_redis $client, $result) {
 +            var_dump($client, $result);
 +            $client->close();
 +        });
 +    });
 +});

</pre>

１、set key value ，用hiredis的话需要考虑下特殊字符，比如空格　如果value里有空格就挂了，当时我们在利用hiredis时候，用它下层的一个方法避免类似问题，具体您查下文档；

２、
+        swoole_php_fatal_error(E_WARNING, "swoole_async_mysql callback handler error.");

+        swoole_php_fatal_error(E_WARNING, "swoole_async_mysql callback handler error.");
 是　redis错误吧？

反馈上面问题，swoole很赞～ 给力～！！

thanks

**Comment by jonnywang** [comment]
swoole_redis_onResult 中依据 reply->str == NULL判定返回结果不对，对于返回数组结构则不适用

**Comment by yiliaofan** [comment]
<pre>
两个函数一样，反馈下：
swoole_hton64　host to network byte order  这个应该需要修改下，感觉
swoole_ntoh64   network to host byete order

thanks
+
 +static sw_inline uint64_t swoole_hton64(uint64_t host)
 +{
 +    uint64_t ret = 0;
 +    uint32_t high, low;
 +
 +    low = host & 0xFFFFFFFF;
 +    high = (host >> 32) & 0xFFFFFFFF;
 +    low = htonl(low);
 +    high = htonl(high);
 +    ret = low;
 +    ret <<= 32;
 +    ret |= high;
 +    return ret;
 +}
 +
 +static sw_inline uint64_t swoole_ntoh64(uint64_t host)
 +{
 +    uint64_t ret = 0;
 +    uint32_t high, low;
 +
 +    low = host & 0xFFFFFFFF;
 +    high = (host >> 32) & 0xFFFFFFFF;
 +    low = ntohl(low);
 +    high = ntohl(high);
 +    ret = low;
 +    ret <<= 32;
 +    ret |= high;
 +    return ret;
 +}
</pre>

**Comment by matyhtf** [comment]
1, 新版本已经用了__call函数方式实现所有Redis命令
2, swoole_hton64实现没问题
