### ISSUE TITLE
process::signal 子进程退出，父进程信号没被执行

### ISSUE THREAD

**Issue by can-as** [swoole/swoole-src#4711]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
<?php
use swoole\process;
swoole_set_process_name("master");
$process = new process(function () {
    \register_shutdown_function(function () {
        file_put_contents('/code/study/log.log', '我被杀死了');
    }
    );
    for ($i = 0; $i < 5; $i++) {
        sleep(1);
    }
}
);
$process->name('php-ps');
$process->start();
process::signal(SIGCHLD, function ($sig) {
    while ($ret = Process::wait(false)) {
        var_dump($ret);
    }
}
);
for (; ;) {
    sleep(1);
}
```
2. What did you expect to see?

父进程process::signal被执行

3. What did you see instead?

父进程process::signal没有被执行

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.7
Built => May  3 2022 12:28:14
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1n  15 Mar 2022
http2 => enabled
json => enabled
pcre => enabled
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
docker
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/10.2.1/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-10.2.1_pre1/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 10.2.1_pre1' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,d,objc,go,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.1 20201203 (Alpine 10.2.1_pre1) 
[1]-  Exit 127                `uname -a`

**Comment by matyhtf** [comment]
`Swoole\Process::signal()` 是异步信号处理，需要在事件循环中才能触发。你代码中的死循环 sleep 会阻塞进程，导致无法执行信号回调。

**Comment by can-as** [comment]
谢谢

Tianfeng.Han ***@***.***> 于2022年5月13日周五 14:38写道：

**Comment by can-as** [comment]
事件循环
<https://wiki.swoole.com/#/learn?id=%e4%bb%80%e4%b9%88%e6%98%afeventloop>
 怎么创建呢

day these ***@***.***> 于2022年5月14日周六 09:36写道：

**Comment by can-as** [comment]
知道了。

use swoole\process;
swoole_set_process_name("master");
$process = new process(function () {
    \register_shutdown_function(function () {
        file_put_contents('/code/study/log.log', '我被杀死了');
    }
    );
    for ($i = 0; $i < 5; $i++) {
        sleep(1);
    }
}
);
$process->name('php-ps');
$process->start();
process::signal(SIGCHLD, function ($sig) {
    while ($ret = Process::wait(false)) {
        var_dump($ret);
    }
}
);
for (; ;) {
    Swoole\Event::dispatch();
}


day these ***@***.***> 于2022年5月14日周六 10:11写道：
