### ISSUE TITLE
浏览器Http一段时间没请求访问就会报错

### ISSUE THREAD

**Issue by linyiyuan** [swoole/swoole-src#4713]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
使用的是Hyperf 2.1框架，主要业务是提供接口给前端Crm系统使用， 在使用过程中，只要浏览器一段时间Http没访问接口就会报 `A bug occurred in Swoole-v4.8.9, please report it` 错误，重新编译安装swoole不能解决问题, 系统是macOs Monterey 12.3.1版本, 具体报错信息如下
 ,

2. What did you expect to see?
正常运行

3. What did you see instead?
WARNING	Server::check_worker_exit_status(): worker(pid=93298, id=6) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.8.9, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
GCC_VERSION: Apple LLVM 13.0.0 (clang-1300.0.27.3)
OPENSSL_VERSION: OpenSSL 1.1.1h  22 Sep 2020
PHP_VERSION : 7.4.11

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.9
Built => May 17 2022 11:26:06
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1h  22 Sep 2020
dtls => enabled
http2 => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Darwin macdeMacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

PHP 7.4.11 (cli) (built: Oct  1 2020 16:55:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.27.3)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by NathanFreeman** [comment]
可以的话上传一下核心转储文件。
https://wiki.swoole.com/#/other/issue?id=关于段错误核心转储
谢谢

**Comment by twose** [comment]
> 可以的话上传一下核心转储文件。 [https://wiki.swoole.com/#/other/issue?id=关于段错误核心转储](https://wiki.swoole.com/#/other/issue?id=%E5%85%B3%E4%BA%8E%E6%AE%B5%E9%94%99%E8%AF%AF%E6%A0%B8%E5%BF%83%E8%BD%AC%E5%82%A8) 谢谢

系统环境没有对齐的话core文件可能是没法调试
并且coredump文件里可能有敏感内存信息，不建议这么做。

还是按照文档说明自己调试，把关键信息贴出来

**Comment by NathanFreeman** [comment]
> > 可以的话上传一下核心转储文件。 [https://wiki.swoole.com/#/other/issue?id=关于段错误核心转储](https://wiki.swoole.com/#/other/issue?id=%E5%85%B3%E4%BA%8E%E6%AE%B5%E9%94%99%E8%AF%AF%E6%A0%B8%E5%BF%83%E8%BD%AC%E5%82%A8) 谢谢
> 
> 系统环境没有对齐的话core文件可能是没法调试 并且coredump文件里可能有敏感内存信息，不建议这么做。
> 
> 还是按照文档说明自己调试，把关键信息贴出来

 😄 写错了，已经修改

**Comment by linyiyuan** [comment]
你好，我在Mac系统使用文档说明去走调试流程，用的是框架Hyperf2.1 使用php watch 触发Bug并没有生成Cores文件，这是因为跟我使用框架有关系
