### ISSUE TITLE
Issue with websocket SSL handshake

### ISSUE THREAD

**Issue by Draghmar** [swoole/swoole-src#4722]
1. What did you do? If possible, provide a simple script for reproducing the error.
I'm trying to set up a websocket server. For now only the basic thing to check how it works. Because I don't know enough about SSL certs I take into account that it may be me, setting it somehow wrong. Those certs were generated with `mkcert` so they are only self signed. But that's for testing so it's fine.
I'm using FF addon `Weasel` as a client but I also tried to set up simple JS script with the same result.
I'm starting the server from cli if that matters.
```php
	use Swoole\Coroutine;
	use Swoole\Runtime;
	use Swoole\WebSocket\Server;
	use Swoole\Http\Request;
	use Swoole\WebSocket\Frame;
	use function Swoole\Coroutine\run;
	Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_ALL ^ SWOOLE_HOOK_TCP);

	// $srv = new Swoole\WebSocket\Server('0.0.0.0', 9509);
	$srv = new Swoole\WebSocket\Server('0.0.0.0', 9509, SWOOLE_PROCESS, SWOOLE_SOCK_TCP | SWOOLE_SSL);
	$srv->set([
		'ssl_cert_file' => '/home/---/ws-cert.pem',
		'ssl_key_file' => '/home/---/ws-privkey.pem',
		'ssl_allow_self_signed' => true,
	]);

	$srv->on('Start', function(Server $srv) {
		var_dump('Start');
	});

	$srv->on('Open', function(Server $srv, Swoole\Http\Request $req) {
		var_dump('Open');
		var_dump($req);
	});

	$srv->on('Message', function(Server $srv, Frame $frame) {
		var_dump('Message');
		var_dump($frame);
	});

	$srv->on('Close', function(Server $srv, int $fd) {
		var_dump('Close');
		var_dump($fd);
	});

	$srv->on('Disconnect', function(Server $srv, int $fd) {
		var_dump('Disconnect');
		var_dump($fd);
	});

	$srv->start();
```

2. What did you expect to see?
Established websocket connection.

3. What did you see instead?
Both FF and Chrome refuse to connect without any specific explanation. On the server side I'm getting this message:
```
WARNING Socket::ssl_accept(): bad SSL client[XXX], reason=1048, error_string=tlsv1 alert unknown ca
```
It doesn't matter if I'm trying through IP address or by domain. 
I did try to use `ws` instead of `wss` with SSL disabled in the server. It works then, so I know it is related to the way I prepared the SSL environment...I just don't know if I did something wrong or is there something missing...

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.8
Built => Mar 16 2022 14:57:14
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1m  14 Dec 2021
dtls => enabled
http2 => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
Linux 5.16.5-arch1-1 #1 SMP PREEMPT Tue, 01 Feb 2022 21:42:50 +0000 x86_64 GNU/Linux

PHP 8.1.6 (cli) (built: May 15 2022 06:10:08) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror --with-build-config=bootstrap-lto --enable-link-serialization=1
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.1.0 (GCC)
```

**Comment by NathanFreeman** [comment]
I can not reproduce it.
Please checking you ca certificate.

**Comment by Draghmar** [comment]
I took mkcert's root CA and installed in my FF. It works then, but that's still not the solution.
I tried to generate certs with:
`openssl req -newkey rsa:4096  -x509  -sha512  -days 365 -nodes -out ws-cert.pem -keyout ws-key.pem`
and using those I'm getting:
`WARNING Socket::ssl_accept(): bad SSL client[XXX], reason=1042, error_string=sslv3 alert bad certificate`

**Comment by NathanFreeman** [comment]
The chorme doesn't trust your ca certificate because it's a self signed certificate.

**Comment by Draghmar** [comment]
So there's basically no way of getting self-signed certs work for dev environment without manually adding them to the browser?
_I'm actually using FF ;)_

**Comment by Draghmar** [comment]
Update:
I used mkcert to generate cert for specific domain (I had wildcard before) and set it in both WebSocket app and in Apache for that domain. Then, if I go to that domain on port 443 and accept exception in my browser, I can connect to the wss. This test happened because I've noticed that when trying to connect with curl I've got `curl: (60) SSL: no alternative certificate subject name matches target host name`. That would suggest that the cert can't be set to wildcard.

**Comment by Draghmar** [comment]
I will close this as I know currently what limitations are and what to do. To sum this up:
- For dev environment with unsigned cert you'll need cert done for specific domain (not wildcard) and be sure to visit that domain in browser to accept the exception.
- For prod environment (signed cert) you'll also need specific domain and make sure that this domain translates directly to the WS sever. For example Load Balancer could catch connection and don't make it transparent to the server.
