### ISSUE TITLE
php8.1.5 install swoole found error

### ISSUE THREAD

**Issue by loyalself** [swoole/swoole-src#4727]
/configure: line 5912: syntax error near unexpected token `-Wbool-conversion,'
./configure: line 5912: `        AX_CHECK_COMPILE_FLAG(-Wbool-conversion,                _MAINTAINER_CFLAGS="$_MAINTAINER_CFLAGS -Wbool-conversion")'

**Comment by NathanFreeman** [comment]
What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`)

**Comment by loyalself** [comment]
uname -a:

**Comment by loyalself** [comment]
uname -a:Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by loyalself** [comment]
uname -a: Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

php -v:
PHP 8.1.5 (cli) (built: May 20 2022 17:25:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies

gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by NathanFreeman** [comment]
```shell
make clean && phpize
```
Try this command to re-generate configure for swoole.

**Comment by loyalself** [comment]
[root@localhost swoole-4.8.6]# make clean && phpize
make: *** 没有规则可以创建目标“clean”。 停止。

**Comment by NathanFreeman** [comment]
那直接phpize重新生成configure脚本

**Comment by loyalself** [comment]
[root@localhost swoole-4.8.6]# phpize
Configuring for:
PHP Api Version:         20100412
Zend Module Api No:      20100525
Zend Extension Api No:   220100525
[root@localhost swoole-4.8.6]# ./configure
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking enable debug log... no
checking enable trace log... no
checking enable sockets support... no
checking enable openssl support... no
checking enable http2.0 support... no
checking swoole support... yes, shared
checking enable mysqlnd support... no
checking enable c-ares support... no
checking dir of openssl... no
checking dir of jemalloc... no
checking enable asan... no
checking whether to enable swoole coverage support... no
checking whether to enable Swoole developer build flags... no
checking whether to enable Swoole JSON build flags... no
checking whether to enable Swoole CURL build flags... no
checking whether to enable thread context... no
checking if compiling with clang... no
checking for cc option to accept ISO C99... -std=gnu99
./configure: line 5912: syntax error near unexpected token `-Wbool-conversion,'
./configure: line 5912: `        AX_CHECK_COMPILE_FLAG(-Wbool-conversion,                _MAINTAINER_CFLAGS="$_MAINTAINER_CFLAGS -Wbool-conversion")'

**Comment by loyalself** [comment]
找到解决办法了

**Comment by NathanFreeman** [comment]
请问怎么解决的

**Comment by loyalself** [comment]
我的 phpize 有问题
