### ISSUE TITLE
compile warnings on centos 7 with PHP 7

### ISSUE THREAD

**Issue by miao606** [swoole/swoole-src#473]
1.
cc -I. -I/opt/download/swoole-src-swoole-1.7.22-stable -DPHP_ATOM_INC -I/opt/download/swoole-src-swoole-1.7.22-stable/include -I/opt/download/swoole-src-swoole-1.7.22-stable/main -I/opt/download/swoole-src-swoole-1.7.22-stable -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/opt/download/swoole-src-swoole-1.7.22-stable/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /opt/download/swoole-src-swoole-1.7.22-stable/swoole_client.c  -fPIC -DPIC -o .libs/swoole_client.o
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_client.c: In function ‘client_select_wait’:
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_client.c:1955:16: warning: ‘dest_element’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             if (dest_element)

2.
 cc -I. -I/opt/download/swoole-src-swoole-1.7.22-stable -DPHP_ATOM_INC -I/opt/download/swoole-src-swoole-1.7.22-stable/include -I/opt/download/swoole-src-swoole-1.7.22-stable/main -I/opt/download/swoole-src-swoole-1.7.22-stable -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/opt/download/swoole-src-swoole-1.7.22-stable/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /opt/download/swoole-src-swoole-1.7.22-stable/swoole_table.c  -fPIC -DPIC -o .libs/swoole_table.o
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_table.c: In function ‘zim_swoole_table_set’:
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_table.c:267:9: warning: variable ‘ktype’ set but not used [-Wunused-but-set-variable]
     int ktype;

3.
 cc -I. -I/opt/download/swoole-src-swoole-1.7.22-stable -DPHP_ATOM_INC -I/opt/download/swoole-src-swoole-1.7.22-stable/include -I/opt/download/swoole-src-swoole-1.7.22-stable/main -I/opt/download/swoole-src-swoole-1.7.22-stable -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/opt/download/swoole-src-swoole-1.7.22-stable/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c  -fPIC -DPIC -o .libs/swoole_http.o
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c: In function ‘swoole_http_request_free’:
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c:1229:18: warning: variable ‘keylen’ set but not used [-Wunused-but-set-variable]
         uint32_t keylen;
                  ^
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c:1227:15: warning: variable ‘key’ set but not used [-Wunused-but-set-variable]
         char *key;
               ^
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c: In function ‘http_build_header’:
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c:1683:13: warning: variable ‘type’ set but not used [-Wunused-but-set-variable]
         int type;
             ^
In file included from /opt/download/swoole-src-swoole-1.7.22-stable/php_swoole.h:132:0,
                 from /opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c:17:
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c: In function ‘multipart_body_on_header_value’:
/opt/download/swoole-src-swoole-1.7.22-stable/php7_wrapper.h:149:96: warning: ‘multipart_header’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 #define sw_add_assoc_stringl(__arg, __key, __str, __length, __duplicate)   add_assoc_stringl_ex(__arg, __key, strlen(__key), __str, __length)
                                                                                                ^
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c:648:15: note: ‘multipart_header’ was declared here
         zval *multipart_header;
               ^
In file included from /usr/include/php/Zend/zend.h:31:0,
                 from /usr/include/php/main/php.h:35,
                 from /opt/download/swoole-src-swoole-1.7.22-stable/php_swoole.h:22,
                 from /opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c:17:
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c: In function ‘multipart_body_on_header_complete’:
/usr/include/php/Zend/zend_types.h:506:37: warning: ‘zerr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 #define Z_LVAL(zval)    (zval).value.lval
                                     ^
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c:724:11: note: ‘zerr’ was declared here
     zval *zerr;
           ^
In file included from /usr/include/php/main/php.h:39:0,
                 from /opt/download/swoole-src-swoole-1.7.22-stable/php_swoole.h:22,
                 from /opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c:17:
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c: In function ‘multipart_body_on_data’:
/usr/include/php/Zend/zend_API.h:400:60: warning: ‘multipart_header’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 #define add_assoc_long(__arg, __key, __n) add_assoc_long_ex(__arg, __key, strlen(__key), __n)
                                                            ^
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c:681:15: note: ‘multipart_header’ was declared here
         zval *multipart_header;
               ^
In file included from /usr/include/php/main/php.h:39:0,
                 from /opt/download/swoole-src-swoole-1.7.22-stable/php_swoole.h:22,
                 from /opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c:17:
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c: In function ‘multipart_body_on_data_end’:
/usr/include/php/Zend/zend_API.h:400:60: warning: ‘multipart_header’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 #define add_assoc_long(__arg, __key, __n) add_assoc_long_ex(__arg, __key, strlen(__key), __n)
                                                            ^
/opt/download/swoole-src-swoole-1.7.22-stable/swoole_http.c:787:11: note: ‘multipart_header’ was declared here
     zval *multipart_header;
           ^

version 1.7.22

**Comment by matyhtf** [comment]
warning,note 的错误信息可以暂时忽略。
