### ISSUE TITLE
Pool error is Swoft\\Connection\\Pool\\AbstractPool::popByChannel(): Send of 5 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by mrainyo** [swoole/swoole-src#4730]
Why is there an error when configuring master/slave replication for mysql in swoft framework? When I cancel this, I will not have this error. Is there something I'm not configuring correctly

{"messages":"trace[RushFileTask.php:76] 异常Pool error is Swoft\\Connection\\Pool\\AbstractPool::popByChannel(): Send of 5 bytes failed with errno=32 Broken pipe file=\/home\/connection-pool\/src\/AbstractPool.php line=289","context":[],"level":300,"level_name":"warning","channel":"swoft","datetime":"2022-06-02 10:00:00","event":"task","tid":5,"cid":5,"traceid":"","spanid":"","parentid":""}
{"messages":"trace[RushFileTask.php:76] 异常Pool error is Swoft\\Connection\\Pool\\AbstractPool::popByChannel(): Send of 5 bytes failed with errno=32 Broken pipe file=\/home\/vendor\/swoft\/connection-pool\/src\/AbstractPool.php line=289","context":[],"level":300,"level_name":"warning","channel":"swoft","datetime":"2022-06-02 10:00:01","event":"task","tid":5,"cid":5,"traceid":"","spanid":"","parentid":""}

**Comment by matyhtf** [comment]
This means that the peer has closed the connection and needs to re-connect
