### ISSUE TITLE
关于http $request->files 疑惑

### ISSUE THREAD

**Issue by topyao** [swoole/swoole-src#4731]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

![image](https://user-images.githubusercontent.com/64066545/172050062-e80a9cec-0bf7-4b4f-831b-706e6b86c4e5.png)
```php
        dump($request->files);
```

3. What did you expect to see?

4. What did you see instead?

```
^ array:1 [
  "file" => array:5 [
    "name" => array:5 [
      "name" => "20211207_20145862_avatar.png.jpg"
      "type" => "image/jpeg"
      "tmp_name" => "/tmp/swoole.upfile.Vyig7l"
      "error" => 0
      "size" => 795559
    ]
    "type" => "image/jpeg"
    "tmp_name" => "/tmp/swoole.upfile.j90Zhn"
    "error" => 0
    "size" => 795559
  ]
]

```

file的name属性被覆盖了。对比fpm的file结构没有问题

```php
^ array:1 [
  "file" => array:6 [
    "name" => array:1 [
      "name" => "20211207_20145862_avatar.png.jpg"
    ]
    "full_path" => array:1 [
      "name" => "20211207_20145862_avatar.png.jpg"
    ]
    "type" => array:1 [
      "name" => "image/jpeg"
    ]
    "tmp_name" => array:1 [
      "name" => "/tmp/phpM46nYa"
    ]
    "error" => array:1 [
      "name" => 0
    ]
    "size" => array:1 [
      "name" => 795559
    ]
  ]
]
```

5. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.5

6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

php8.1

**Comment by twose** [comment]
这是PHP自带Server的特色功能。
