### ISSUE TITLE
pecl install swoole success, php -m load failed

### ISSUE THREAD

**Issue by c608345** [swoole/swoole-src#4733]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
sudo pecl install -D 'enable-sockets="yes" enable-openssl="yes" enable-http2="yes" enable-mysqlnd="no" enable-swoole-json="yes" enable-swoole-curl="yes" ' swoole

2. What did you expect to see?
install swoole and swoole works

3. What did you see instead?
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole' (tried: /usr/
lib/php/20210902/swoole (/usr/lib/php/20210902/swoole: cannot open shared object
 file: No such file or directory), /usr/lib/php/20210902/swoole.so (/usr/lib/php
/20210902/swoole.so: undefined symbol: curl_share_ce)) in Unknown on line 0

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.8.9

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux 5.10.109+  SMP Tue May 24 09:08:48 UTC 2022 x86_64 GNU/Linu
PHP 8.1.6 (cli) (built: May 17 2022 16:48:41) (NTS)

COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6)

**Comment by NathanFreeman** [comment]
Make sure that extension=swoole.so is after the CURL extension.

**Comment by c608345** [comment]
> Make sure that extension=swoole.so is after the CURL extension.

PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole' (tried: /usr/lib/php/20210902/swoole (/usr/lib/php/20210902/swoole: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/swoole.so (/usr/lib/php/20210902/swoole.so: undefined symbol: curl_share_ce)) in Unknown on line 0
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

still load failed

**Comment by NathanFreeman** [comment]
What is your curl version? `curl --version`

**Comment by c608345** [comment]
curl 7.83.0 (x86_64-pc-linux-gnu) libcurl/7.83.0 OpenSSL/1.1.1o zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0 librtmp/2.3 OpenLDAP/2.5.11
Release-Date: 2022-04-27

**Comment by NathanFreeman** [comment]
`php --ri curl` to check curl info.

**Comment by NathanFreeman** [comment]
It look like that there are multiple curl on your server.
How do you install php ?

**Comment by c608345** [comment]
curl

cURL support => enabled
cURL Information => 7.74.0
Age => 7
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => Yes
HTTPS_PROXY => Yes
MULTI_SSL => No
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-pc-linux-gnu
SSL Version => OpenSSL/1.1.1n
ZLib Version => 1.2.11
libSSH Version => libssh2/1.9.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value

https://shell.cloud.google.com/  I use gcp cloud shell.   

sudo apt install php php-dev php-xml php-pear  libcurl4-openssl-dev   php-curl
sudo pecl install -D 'enable-sockets="no" enable-openssl="yes" enable-http2="no" enable-mysqlnd="no" enable-swoole-json="no" enable-swoole-curl="yes" ' swoole

**Comment by NathanFreeman** [comment]
I reproduce it.
Don't add `extension=swoole.so` to `/etc/php/8.1/cli/php.ini`.
Execute `echo "extension=swoole.so" > /etc/php/8.1/cli/conf.d/20-swoole.ini`
Make sure that extension=swoole.so is after the CURL extension.

**Comment by c608345** [comment]
Thanks, it works.
