### ISSUE TITLE
How to ingest logs into Filebeat?

### ISSUE THREAD

**Issue by route33** [swoole/swoole-src#4734]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
Is not actually an error, but a question on how to get rid of INFO label before any stdout log. Is going to be always INFO, or could be any of your log levels?

2. What did you expect to see?
<img width="553" alt="image" src="https://user-images.githubusercontent.com/81183127/172856658-50a466b6-1f14-490b-b2df-e6a42deb85ff.png">

3. What did you see instead?
<img width="654" alt="image" src="https://user-images.githubusercontent.com/81183127/172856588-117eefbb-1571-4af3-95c0-910fdd52e3c4.png">

4. What version of Swoole are you using (show your `php --ri swoole`)?
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.9
Built => Apr 18 2022 16:27:47
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1n  15 Mar 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
bash-5.1# uname -a & php -v & gcc -v
[1] 1734
[2] 1735
Linux a06e0aa238a1 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 Linux
bash: gcc: command not found
[1]-  Done                    uname -a
bash-5.1# PHP 8.0.17 (cli) (built: Apr  5 2022 01:52:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.17, Copyright (c), by Zend Technologies

**Comment by leocavalcante** [comment]
What is you using for logging?

**Comment by route33** [comment]
Monolog\Formatter\JsonFormatter within Laravel Octane
