### ISSUE TITLE
创建一个websocket服务，通过onRequest主动推送消息给客户端，推送完成后，连接就断掉了

### ISSUE THREAD

**Issue by guojijiu** [swoole/swoole-src#4737]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
使用laravel创建了一个websocket服务，客户端向服务端发送消息正常，但是通过调用封装的onRequest，向客户端发送消息，消息发送成功了，但是连接就断掉了。
![企业微信截图_18dbfe29-b3c1-4228-accb-198e82e8cd60](https://user-images.githubusercontent.com/22710046/173517526-0829f7db-4f49-4f62-803b-1085844e0747.png)
![企业微信截图_e5f050d0-6078-4d76-8ab0-f032eb09a4fe](https://user-images.githubusercontent.com/22710046/173517689-3643be76-5e61-4d36-a209-c8ec75455878.png)
![企业微信截图_f22f9249-355a-4936-8d93-38e46894ee47](https://user-images.githubusercontent.com/22710046/173518502-3e11173a-6e21-4ce3-9c04-16abec836f2d.png)

2. What did you expect to see?
主动向客户端推送消息，并且不会断开连接。

3. What did you see instead?
服务端主动推送数据到客户端成功，但是推送完成就断开了连接。

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.7.1
Built => Sep 17 2021 17:27:56
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
macOS：12.1
php：7.2
laravel：6.0

**Comment by NathanFreeman** [comment]
看代码是有异常发生，被catch捕获到了，打印一下异常信息。

**Comment by guojijiu** [comment]
没有发现异常，是连接断掉了，进程没有断掉

**Comment by NathanFreeman** [comment]
我看你的输出有一个close fd: 1，那个是有异常的时候输出的吧。

**Comment by guojijiu** [comment]
![企业微信截图_b6dbf19f-6d65-4538-a54d-61b56889e9b7](https://user-images.githubusercontent.com/22710046/173714472-cddba173-56e1-4221-b411-c8703025de83.png)
尝试捕获了下一场，没得异常信息。

**Comment by NathanFreeman** [comment]
你这里有个异常捕获
![173517689-3643be76-5e61-4d36-a209-c8ec75455878](https://user-images.githubusercontent.com/33935209/173721683-5a7fefa7-8cc8-4bc9-be6b-c437876286ee.png)

**Comment by guojijiu** [comment]
![企业微信截图_de0df9f6-7c74-4482-8b47-80143906334b](https://user-images.githubusercontent.com/22710046/173724438-bd96a07f-ecf4-4e90-b965-dedde5a52e52.png)
感谢，找到原因了。
![企业微信截图_f86a9e7f-d135-4bcf-ab30-e0546c16c315](https://user-images.githubusercontent.com/22710046/173724505-80db2ed4-05f8-44c9-ae96-14a97cf33590.png)
因为我是通过在服务端模拟一个http请求，把推送信息发送到客户端，也就不是一个正常的socket连接，导致报错了，注释掉就好了。
