### ISSUE TITLE
请问一下，以下段代码，做在ab测试时遇到以下问题？

### ISSUE THREAD

**Issue by winfan** [swoole/swoole-src#474]
$fp = stream_socket_client("tcp://127.0.0.1:9503", $code, $msg, 3);
 $data['method'] = "insert";
                    $http_request = json_encode($data);
                    fwrite($fp, $http_request);
                    swoole_event_add($fp, function($fp){
                        swoole_event_del($fp);
                        fclose($fp);
                    });
                    swoole_event_write($fp, $http_request);

PHP Warning:  stream_socket_client(): unable to connect to tcp://127.0.0.1:9503 (Cannot assign requested address)  in xxx.php
PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in xxx.php

**Comment by winfan** [comment]
所有端口都 开在单台机器上面

**Comment by winfan** [comment]
[root@xxxxx ~]# ab -c 500 -n 30000 'http://bxxxx.xxx.xxx/?action=xxx&modules=[{%22xxxe%22:%22xxxx%22,%22xxxx%22:%2214009193%22}]&jefed=669PSTQ0'a
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking bxxxx.xxx.xxx (be patient)
Completed 3000 requests
Completed 6000 requests
Completed 9000 requests
Completed 12000 requests
Completed 15000 requests
apr_socket_recv: Connection timed out (110)
Total of 15810 requests completed

**Comment by matyhtf** [comment]
Cannot assign requested address ，本地端口不足，ab增加-k长连接参数试一下。
