### ISSUE TITLE
Features request: Add origin and replace server response header in WebSocket

### ISSUE THREAD

**Issue by AmitSonkhiya** [swoole/swoole-src#4749]
I would like to have the following two features available in Swoole for WebSocket.

### 1: Add allowed origin

Currently, even a localhost or anonymous server may try to establish a WebSocket connection. **There should be an option to limit origins so that only authorized apps or websites could attempt to create a WebSocket connection.**

For example, an application could be served via a website (say example.com) or a corresponding (Android/iOS) app. In that case, it should have an option to allow WS connection to only that website and the app.

If there is already an option then do let me know.

### 2: Replace server response header

After a successful WebSocket connection, the response header returned by the server contains the _Server: OpenSwoole 4.11.1_ entry.

```
Connection: Upgrade
Sec-WebSocket-Accept: mABCD0joUS/Z/yPYqrqfa3+I2sT=
Sec-WebSocket-Version: 13
Server: OpenSwoole 4.11.1
Upgrade: websocket
```
**Could it have a feature to completely remove this server header line or replace it with a fake name like _Server: XYZ_?**

Both features would strongly enhance security from an end programmer's perspective.

Thanks

**Comment by Draghmar** [comment]
I think you're using OpenSwoole and not Swoole ;)
Anyway, `on('Open')` has `Request` and there's `header` that has `origin` field. Wouldn't that be enough?

As for the `Server` it does show `swoole-http-server` and it would be nice to hide this.

**Comment by AmitSonkhiya** [comment]
My luck.

I thought both are the same.
Thanks for updating and yes it would be nice to hide such information despite the framework.

**Comment by Draghmar** [comment]
At the moment they are quite similar, but there are some differences here and there.

**Comment by AmitSonkhiya** [comment]
Please check my previous comment regarding the `origin` field.
I did update the comment meanwhile you replied.

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/blob/master/tests/swoole_websocket_server/set_cookie_on_before_handshake_response.phpt

You should set the beforeHandShakeResponse event callback, then set the origin and server headers
