### ISSUE TITLE
worker脱离master的情况

### ISSUE THREAD

**Issue by Maplejay** [swoole/swoole-src#4753]
swoole的log,一直出现如下报错
WARNING swReactorEpoll_wait(:259): EPOLLIN handle failed. fd=17, Error: Resource temporarily unavailable[11]
通过ps -efH|grep laravels查询。看到有好几个脱离master的worker。占用很多的cpu资源。
重启应用，脱离的master的worker不会销毁
目前通过kill掉pid解决。
请问如何处理这个问题呢？
版本
swoole:4.5.9
php：7.2.34

**Comment by Maplejay** [comment]
我们使用的【laravels】这个扩展。它是结合laravel+swoole的扩展。我们自己写的应用层是没用用到pcntl_fork 或者 new Process的

**Comment by Maplejay** [comment]
![image](https://user-images.githubusercontent.com/17807750/175905254-a02e0c72-e8ec-4b77-9ef9-d27f89365d99.png)
类似这样的 情况，查询了好多的文章，不知道出现这个问题的原因是什么，跟如何解决~

**Comment by matyhtf** [comment]
可以考虑增加 max_wait_time 配置，超过时间后强制结束进程
