### ISSUE TITLE
信号不支持协程

### ISSUE THREAD

**Issue by can-as** [swoole/swoole-src#4762]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
Swoole\Process::signal(SIGCHLD, function ($sig) {
    while ($ret = Swoole\Process::wait(false)) {
        $user=Db:name('user')->find(1);
    }
});

2. What did you expect to see?
  
正确查询

3. What did you see instead?

HP Fatal error: Uncaught Swoole\Error: API must be called in the coroutine in

4. What version of Swoole are you using (show your `php --ri swoole`)?

bash-5.1# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7
Built => Jul 13 2022 12:05:21
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1q  5 Jul 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by NathanFreeman** [comment]
```php
use function Swoole\Coroutine\run;

run(function() {
    Swoole\Process::signal(SIGCHLD, function ($sig) {
        while ($ret = Swoole\Process::wait(false)) {
            $user=Db:name('user')->find(1);
         }
    });
});
```
试试这样

**Comment by matyhtf** [comment]
可以使用`Swoole\Coroutine\System::waitSingal()`
