### ISSUE TITLE
4.8.11，出现parse multipart body failed

### ISSUE THREAD

**Issue by shuipf** [swoole/swoole-src#4763]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

就swoole版本升级，其它没改版

2. What did you expect to see?

为什么会有这个提示，希望解决它

3. What did you see instead?

[2022-07-14 19:19:46 @13.0]     WARNING http_request_on_body() (ERRNO 9010): parse multipart body failed, 18446744073709551615/300 bytes processed
[2022-07-14 22:28:01 @13.0]     WARNING http_request_on_body() (ERRNO 9010): parse multipart body failed, 18446744073709551615/300 bytes processed
[2022-07-15 12:31:42 @13.0]     WARNING http_request_on_body() (ERRNO 9010): parse multipart body failed, 18446744073709551615/300 bytes processed
[2022-07-15 12:31:59 @13.0]     WARNING http_request_on_body() (ERRNO 9010): parse multipart body failed, 18446744073709551615/300 bytes processed
[2022-07-15 17:43:57 @13.0]     WARNING http_request_on_body() (ERRNO 9010): parse multipart body failed, 18446744073709551615/300 bytes processed
[2022-07-15 22:17:11 @13.0]     WARNING http_request_on_body() (ERRNO 9010): parse multipart body failed, 18446744073709551615/300 bytes processed

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.11
Built => Jul 13 2022 02:12:07
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1f  31 Mar 2020
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux think6-qm-7c89cd6669-8psxt 5.10.84-10.2.al8.x86_64 #1 SMP Thu Feb 10 15:03:09 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.0.20 (cli) (built: Jun 25 2022 08:11:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.20, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.20, Copyright (c), by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by NathanFreeman** [comment]
这看起来像是接受到了一个非法的请求，因为解析出来的长度不对。
是所有的接口都频繁出现这个警告，还是只有单独几个接口会这样。

**Comment by NathanFreeman** [comment]
这个是文件上传的接口吗

**Comment by shuipf** [comment]
我们这个是一个资讯网站，没有提供上传的；当然不排除非法发送数据包，只是升级11前没有，现在突然看到。具体是哪个接口或者地址，我这边也没定位到，这个不是必然出现。

**Comment by matyhtf** [comment]
感谢反馈，因为 multipart parser 重构，某个异常的请求引出了一个新的 warning 信息，我们优化一下错误输出。
