### ISSUE TITLE
突然间死了，麻烦看看什么问题

### ISSUE THREAD

**Issue by YifPhpCoder** [swoole/swoole-src#4766]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
![image](https://user-images.githubusercontent.com/19922673/179952942-b6af5498-5ba4-4be9-9832-9c620c92e69e.png)
![image](https://user-images.githubusercontent.com/19922673/179953120-190710bb-0bed-4ace-95a1-8a1040518df7.png)

开启服务后，客户端连接不上了

2. What did you expect to see?

正常

3. What did you see instead?

正常

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole-v4.8.5

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

OS: Linux 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64
GCC_VERSION: 4.8.5 20150623 (Red Hat 4.8.5-44)
OPENSSL_VERSION: OpenSSL 1.0.2u  20 Dec 2019
PHP_VERSION : 7.4.30

**Comment by NathanFreeman** [comment]
这个是偶发现象还是一启动就进程非正常退出

**Comment by NathanFreeman** [comment]
看起来不关信号SIGHUP的关系，manager进程收到SIGUSR1后重启进程，然后发生了段错误，SIGSEGV
