### ISSUE TITLE
4.8.11编译 无法启用 openssl http2

### ISSUE THREAD

**Issue by figureout** [swoole/swoole-src#4769]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
compile 

2. What did you expect to see?
openssl http2  show in php --ri swoole result  

3. What did you see instead?

openssl http2  not shown in php --ri swoole result  

4. What version of Swoole are you using (show your `php --ri swoole`)?
   4.8.11

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux localhost.localdomain 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.4.0RC5 (cli) (built: Jul 21 2022 14:50:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0RC5, Copyright (c), by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Comment by NathanFreeman** [comment]
有在configure过程中添加--enable-openssl  --enable-http2选项吗
