### ISSUE TITLE
swoole针对400的请求--TRACE Port_onRead_http() (ERRNO 7102): Bad Request: unknown protocol from session#193 on 0.0.0.0:9505

### ISSUE THREAD

**Issue by z6824980** [swoole/swoole-src#4771]
问题描述
TRACE Port_onRead_http() (ERRNO 7102): Bad Request: unknown protocol from session#193 on 0.0.0.0:9505

Swoole版本，PHP版本，以及操作系统版本信息
swoole : 4.8.8
php : 7.2

PHP
你期待的结果是什么？实际看到的错误信息又是什么？
通过nginx转发的请求，正常fpm模式是正常的， 转到swoole模式下报400. 如何能正常解决或者给参数转码传过来，而不报400呢？
下面的连接是线上的请求，可以被fastcgi 转发到php正常处理， 但是通过proxy_pass 转发到swoole http服务就会返回http 400。

请求参数：
/search/miniblog_zhuanji/album.php?xsort=time&key=%E4%B9%B0%E8%BD%A6%20%E6%97%A5%E4%BA%A7&cuid=0&sid=t_wap&sid_group=mobile&us=1&page=1&pagesize=20&socialtime=1&token=Authorization: TAuth2 token=\x22OXPWQTNWWTQTXNXON%3DOUPYOTXOTSVVVNNNOXNXOXRTvdBOFI72\x22&dup=1&isbctruncate=1&nofilter=0&uicode=10000011&cip=118.195.192.178&da_intention={u’fit_timeliness’: 1, u’type’: 16}&timelimit=920&istag=0&ua=Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0&web_degrade=0&seqid=1658734283871287&public=1&api_type=64&hot_weibo_topic=1&position=[]&is_teenager=0&video_search=1&trace=0&is_comment_new_card=0&unify_pagination_gray=0&viewpoint_combined_calculation=0&urgent_filter=0&is_scroll_white=0&unify_scroll_show=0&caller_project=mi&thirdparty_channel=0&product_source=&hot_num_expansion_gray=0&filter_pc_search_info=1&video_album=1&ori_seqid=799348684&query_unify=\xE4\xB9\xB0\xE8\xBD\xA6 \xE6\x97\xA5\xE4\xBA\xA7&query_normal=\xE4\xB9\xB0\xE8\xBD\xA6\xE6\x97\xA5\xE4\xBA\xA7&os_degrade=1&drop_da=0&fit_timeliness=1&intention=16&is_mobile=1&hot_flag=0

**Comment by z6824980** [comment]
![image](https://user-images.githubusercontent.com/18024471/180823403-b70b801c-9c2a-447f-aa95-3f2461f344c9.png)

**Comment by matyhtf** [comment]
请将原始的 HTTP 报文上传到这里

**Comment by z6824980** [comment]
62.135.200.16 - 16588021661060011318 [26/Jul/2022:10:22:46 +0800] "GET /search/miniblog_zhuanji/album.php?xsort=time&key=%E7%94%B7%E5%AD%90%E8%AF%AF%E6%8A%8A%E7%A5%9B%E9%BB%91%E5%A4%B4%E8%86%8F%E5%BD%93%E9%9D%A2%E8%86%9C%E6%B6%82%E8%84%B8&cuid=0&sid=t_wap_ios&sid_group=mobile&us=1&page=1&pagesize=10&socialtime=1&token=Authorization: TAuth2 token=\x22OXPWQTNWWTQTXNXON%3DOUPYOTXOTSVWTTRNPXNXOX9TnxQaVF9S\x22&dup=1&isbctruncate=1&nofilter=0&from=98BB093010&da_intention={u'fit_timeliness': 3, u'type': 576460752336977920}&timelimit=920&istag=2&c=search_weixinminiprogram&web_degrade=0&seqid=1658802166093334&public=1&api_type=64&hot_weibo_topic=1&is_teenager=0&video_search=1&trace=0&is_comment_new_card=1&unify_pagination_gray=0&viewpoint_combined_calculation=0&urgent_filter=0&is_scroll_white=0&unify_scroll_show=0&caller_project=mi&thirdparty_channel=0&product_source=&hot_num_expansion_gray=0&filter_pc_search_info=1&unify_key=\xE7\x94\xB7\xE5\xAD\x90\xE8\xAF\xAF\xE6\x8A\x8A\xE7\xA5\x9B\xE9\xBB\x91\xE5\xA4\xB4\xE8\x86\x8F\xE5\xBD\x93\xE9\x9D\xA2\xE8\x86\x9C\xE6\xB6\x82\xE8\x84\xB8&video_album=1&ori_seqid=1514659986&query_unify=\xE7\x94\xB7\xE5\xAD\x90\xE8\xAF\xAF\xE6\x8A\x8A\xE7\xA5\x9B\xE9\xBB\x91\xE5\xA4\xB4\xE8\x86\x8F\xE5\xBD\x93\xE9\x9D\xA2\xE8\x86\x9C\xE6\xB6\x82\xE8\x84\xB8&query_normal=\xE7\x94\xB7\xE5\xAD\x90\xE8\xAF\xAF\xE6\x8A\x8A\xE7\xA5\x9B\xE9\xBB\x91\xE5\xA4\xB4\xE8\x86\x8F\xE5\xBD\x93\xE9\x9D\xA2\xE8\x86\x9C\xE6\xB6\x82\xE8\x84\xB8&fit_timeliness=3&intention=0&is_mobile=1&sid_num=2&hot_flag=1 HTTP/1.1" - 400 5 0.001

**Comment by z6824980** [comment]
![image](https://user-images.githubusercontent.com/18024471/180909123-3481fedd-91a9-4a71-b2d9-284602a93529.png)

**Comment by z6824980** [comment]
这是nginx的access.log，  对应的swoole 返回TRACE Port_onRead_http() (ERRNO 7102): Bad Request: unknown protocol from session#193 on 0.0.0.0:9505 这个报错。

**Comment by z6824980** [comment]
![image](https://user-images.githubusercontent.com/18024471/180925725-cae2fda9-597a-48aa-95dd-478a208a5efe.png)

这是改了swoole源码，看了下请求协议的入参， 发现确实被截断了。。

**Comment by z6824980** [comment]
大概知道了，swoole对于http协议的解析很严格， 请求 url的path 里面不能有任何空白字符：空格，\f,\n,\r,\t,\v,\x 这些都不行

**Comment by NathanFreeman** [comment]
但是我看你的url的path没看到空白字符：空格，\f,\n,\r,\t,\v,\x 这些。

**Comment by z6824980** [comment]
![image](https://user-images.githubusercontent.com/18024471/181146408-e0e68772-1b01-4512-acc8-e0f17a886968.png)
这些就是呢， 遇到空格，解析就失败了，  外部调用没有把参数urlencode

**Comment by matyhtf** [comment]
需要符合 HTTP URL 的规范，不能存在空格
