### ISSUE TITLE
parse multipart body failed报错

### ISSUE THREAD

**Issue by lizcao** [swoole/swoole-src#4772]
一直WARNING报错：
`[2022-07-27 10:10:25 *21617.0]	WARNING	http_request_on_body() (ERRNO 9010): parse multipart body failed, 18446744073709551615/361 bytes processed`
php版本7.4  swoole版本如下：
`
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.11
Built => Jul 26 2022 23:05:48
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608`

请问这个是什么原因导致的? 有解决办法吗？

**Comment by NathanFreeman** [comment]
https://github.com/swoole/swoole-src/issues/4763

**Comment by matyhtf** [comment]
已修复。大数字实际上是 -1 ，表示是错误的 form-data 格式，已优化错误信息
