### ISSUE TITLE
偶发报错"Swoole\Coroutine\Channel::close(): you must call Channel constructor first"

### ISSUE THREAD

**Issue by Appla** [swoole/swoole-src#4773]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

如下代码只保留核心逻辑, 不代表一定会重现。
相关问题是近期才发现，不确定可能的原因。
```PHP

class A {
    private $ch;

    public function __construct(int $num)
    {
        $this->ch = new \Swoole\Coroutine\Channel($num);
    }

    private function free()
    {
        $this->ch->close();
        $this->ch = null;
    }

    public function __destruct()
    {
        $this->ch && $this->free();
    }
}
```
2. What did you expect to see?
看实现这个错误不应该出现

3. What did you see instead?
```
PHP Fatal error:  Swoole\Coroutine\Channel::close(): you must call Channel constructor first in /path/to/file
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
4.8.7

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
centos 7 [3.10.0-862.9.1.el7.x86_64]
php 7.4.28
gcc version 8.3.0 (GCC)

**Comment by NathanFreeman** [comment]
有可能是多个协程执行了同时执行了关闭了channel的方法。

**Comment by matyhtf** [comment]
析构函数是在协程环境之外执行的，可以通过判断 `Co::getCid()` 是否为负数检测到这种情况。一般是整个程序已进入了 shutdown 阶段，这时不需要再执行 `Channel::close()` 了

**Comment by Appla** [comment]
感谢
