### ISSUE TITLE
协程http server, keep-alive 特性

### ISSUE THREAD

**Issue by lincepro** [swoole/swoole-src#4779]
我看文档里有这样一句话：
https://wiki.swoole.com/#/coroutine/http_server?id=handle
客户端支持 [KeepAlive]，子协程会循环继续接受新的请求，而不退出
但是并没有写如何关闭这个特性

这个特性会导致一个问题， Co::defer()和 Co::getContext()非常受限

先说defer 
例如现在有一个资源池，期望是请求结束就释放资源给其他人用，第一反应是这么写：
```
$resource = $pool->get();
\Co::defer(fn() => $pool->put($resource));
// 使用 $resource
```
但是因为keep-alive特性的存在, 请求结束并不是马上归还的
我本地用浏览器测试，需要等60秒才释放，每个客户端占用资源60秒显然是不行的
只能自己实现一个request生命周期的defer机制， 或者用别的什么手段来实现

再说context
我最开始是想着把一些组件扔进去， 比如 "当前登录用户" 这个组件
```
$context = \Co::getContext();
$context -> currUser ??= new CurrentUser();
```
但是这么写出现了一个问题，就是如果用户连续请求，这个数据是一直不变的
哪怕后台已经把这个用户数据改了，context里依然是旧的数据
这就需要我在每次请求结束之后手段清理掉context的数据，或者自己实现一个request生命周期的context……

**Comment by matyhtf** [comment]
可以在 handler 中创建一个新的独立子协程去处理请求。
