### ISSUE TITLE
too many open files问题

### ISSUE THREAD

**Issue by ronalfei** [swoole/swoole-src#478]
最近服务器经常会出现toomanyopenfile的问题. 出现后及时重启服务, 就好了.或者是日志中出现: WARN swManager_check_exit_status: worker#28 abnormal exit, status=0, signal=9 后, 也会恢复正常.

too many open file的问题一般修改ulimit值可以解决. 我们当前的相关值的设置为: open files (-n) 655350 max user processes (-u) 30720

fs.file-max = 6515112

soft nofile 655360
hard nofile 655360
当服务出现问题的时候, lsof -l 的总数量为5W+, 应该远远没有达到限制.

不知道是不是版本有问题导致未能读取正确的服务器配置? 版本是1.7.7

**Comment by matyhtf** [comment]
1.7.7的版本过老了，建议升级一下。

**Comment by matyhtf** [comment]
另外，直接面向外网的Server需要开启心跳检测。
