### ISSUE TITLE
Method signature changes (setCookie)

### ISSUE THREAD

**Issue by ValiDrv** [swoole/swoole-src#4780]
Hello

In version 5, the `Swoole\Http\Response->setCookie()` changed from:
`->setCookie(name: $name,value: $value, expires: $expires, path: $path, domain: $domain,  secure: $secure, httponly: $httponly);`
to
`->setCookie(name: $name,value: $value, expire: $expires, path: $path, domain: $domain,  secure: $secure, httponly: $httponly);`
(notice the `expire` vs `expires` argument)

Since in PHP8 you can use named arguments, this is a braking change that should probably be documented, since allot of times methods can be called with `->setCookie(...$cookieArray)`, and that can introduce hidden bugs. 

Also, since `swoole/ide-helper` and `wiki.swoole.com` is not being released in the same time as `swoole-src` tag, this adds to most complains people have about Swoole, "the documentation".

**Comment by NathanFreeman** [comment]
https://github.com/swoole/swoole-src/pull/4830

**Comment by matyhtf** [comment]
@ValiDrv The renaming of the parameter name I think is just a typo fix, should not be a breaking change. 

I'll add it to release note later.
