### ISSUE TITLE
Release 5.0 drop support PHP < 8.0

### ISSUE THREAD

**Issue by dmitryuk** [swoole/swoole-src#4782]
I thought that v5 release will drop version support of PHP < 8.0 as described here https://github.com/swoole/ide-helper/pull/35
It will help to clear code and fix some deprecations in swoole-library
Isn't it?

**Comment by pawmaster** [comment]
php:7.4.30-cli-alpine install swoole 5.0.0 build failure

> error: cannot convert 'zend_object*' {aka '_zend_object*'} to 'zval*' {aka '_zval_struct*'}

extract 5.0.0 pecl source to /tmp/swoole

```bash
apk add --no-cache --virtual .build-deps $PHPIZE_DEPS openssl-dev pcre-dev pcre2-dev zlib-dev
docker-php-ext-configure /tmp/swoole --enable-openssl --enable-swoole-curl
docker-php-ext-install -j$(nproc) /tmp/swoole
```

same commands, 8.1.9-cli-alpine build success

**Comment by sy-records** [comment]
swoole 5 only supports PHP 8.x
