### ISSUE TITLE
怎么获取正在执行中go协程的总数量，怎么判断一个go协程使用多少cpu资源呢

### ISSUE THREAD

**Issue by Funny-dot** [swoole/swoole-src#4786]
怎么获取正在执行中go协程的总数量，怎么判断一个go协程使用多少cpu资源呢

**Comment by Yurunsoft** [comment]
可以用`\Swoole\Coroutine::stats()`获取关于协程的一些数据：https://wiki.swoole.com/#/coroutine/coroutine?id=stats

**Comment by matyhtf** [comment]
无法判断 CPU 资源占用，这可能需要使用 C++ 扩展才能做到，需要在协程切换时读取 `/proc/self/status` 信息，得到 CPU 耗时增加的数值，计算协程的 CPU 开销
