### ISSUE TITLE
swoole 怎么连接unix://套接字

### ISSUE THREAD

**Issue by Yii18** [swoole/swoole-src#4789]
![image](https://user-images.githubusercontent.com/34769669/182523757-92946212-d399-4959-baa0-f642af3fe7bf.png)
有像workman一样的客户端吗、我看官网都是stream_socket_client连接
![image](https://user-images.githubusercontent.com/34769669/182523822-cd805fbe-5353-491b-8def-e5f66b724022.png)

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/blob/master/tests/swoole_socket_coro/unix_stream.phpt

**Comment by Yii18** [comment]
谢谢
