### ISSUE TITLE
swore_table 建议

### ISSUE THREAD

**Issue by jasonhe88** [swoole/swoole-src#479]
强烈建议在新版本中对table的__construct的尺寸参数定义做修改, 定义多少行就实际能存储多少行, 不用用户自己去测试能存储的表行数

**Comment by matyhtf** [comment]
table受限于HashTable算法，如果set的数据key冲突过大，确实无法存储太多行数据。所以没办法在构造之处确定到底能存多少行，决定于set进入的数据。
