### ISSUE TITLE
PHP 8.0 环境编译 5.0 出错 no member named 'gethostbyname2_r' in the global namespace

### ISSUE THREAD

**Issue by gbabook** [swoole/swoole-src#4790]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
/usr/local/opt/php\@8.0/bin/phpize

./configure --enable-openssl --with-openssl-dir=/usr/local/opt/openssl\@1.1 --enable-swoole-curl --with-php-config=/usr/local/opt/php\@8.0/bin/php-config

make

3. What did you see instead?

swoole-src-5.0.0/src/network/dns.cc:682:20: error: no member named 'gethostbyname2_r' in
      the global namespace

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

uname -a：
Darwin xxxxx.lan 18.7.0 Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64 x86_64

php -v
PHP 8.0.21 (cli) (built: Aug  1 2022 09:03:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.21, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.21, Copyright (c), by Zend Technologies

gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by jitendra5696** [comment]
Getting same error, any solution for this?

**Comment by salarzaidi** [comment]
any solution yet ?

**Comment by gengyangabc123** [comment]
切换4.8可以，或者把configure后的config.h 里面的  #define HAVE_GETHOSTBYNAME2_R 1 注释掉然后再make

**Comment by Yurunsoft** [comment]
What is your version of gcc? @jitendra5696 @salarzaidi

**Comment by Yurunsoft** [comment]
I've fixed it after talking to the questioner, please try to compile the code for this branch.
https://github.com/swoole/swoole-src/tree/fix-4790
@jitendra5696 @salarzaidi
