### ISSUE TITLE
Swoole Tracker咨询

### ISSUE THREAD

**Issue by z6824980** [swoole/swoole-src#4791]
想问下Swoole Tracker是你们维护的吗？
![image](https://user-images.githubusercontent.com/18024471/182751410-a547e801-1e09-4be5-88b6-e81240c114b9.png)

下载了php7.2下的扩展不能使用，加了客服也不说话呢。

![image](https://user-images.githubusercontent.com/18024471/182751470-f2bec7a4-38ae-400a-b043-b8e81c8d8e34.png)

![image](https://user-images.githubusercontent.com/18024471/182751520-822c8e01-0a75-4fda-b745-5d454c556324.png)

http://tracker.demo.swoole-cloud.com/?log=demo&pwd=tracker_qaz

![image](https://user-images.githubusercontent.com/18024471/182751568-2a5bb80e-0869-4409-a98f-c438d94c2ed4.png)
后台也是报错的。

**Comment by matyhtf** [comment]
@z6824980 请等待客服联系
