### ISSUE TITLE
WARNING MsgQueue::MsgQueue(): msgget() failed, Error: No space left on device[28]

### ISSUE THREAD

**Issue by WindyWilliam** [swoole/swoole-src#4795]
Hey pals,

I don't know why, but when I set task_ipc_mode to 3, after starting the server and stopping it for exactly 40 times, it will not start at all and shows following error in the console. The only solution I found is restarting my computer (even logout doesn't work, only restart works).

Here is the error message:

> [2022-08-08 00:00:00 @1578.0]   WARNING MsgQueue::MsgQueue(): msgget() failed, Error: No space left on device[28]
> [2022-08-08 00:00:00 @1578.0]   WARNING Server::create_task_workers(): [Master] create task_workers failed
> [2022-08-08 00:00:00 @1578.0]   WARNING ProcessFactory::start(): failed to start
> PHP Fatal error:  Swoole\Server::start(): failed to start server. Error: ProcessFactory::start(): failed to start in /tmp/swoole.php on line 10
> 
> Fatal error: Swoole\Server::start(): failed to start server. Error: ProcessFactory::start(): failed to start in /tmp/swoole.php on line 10
> [2022-08-08 00:00:00 @1578.0]   ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Swoole\Server::start(): failed to start server. Error: ProcessFactory::start(): failed to start in /tmp/swoole.php on line 10

This happens all the times, for past few weeks I had to restart my computer for several times a day. I don't know if I need to adjust my operating system's settings or Swoole's settings, but it seems like a bug in Swoole to me.

I'm using macOS Monterey 12.4. No OS settings are changed (everything is on default value).
We are planning to use Linux and BSD for production, I don't know if this error happens on those operating systems too or not.

phpinfo() output:

```
Core

PHP Version => 8.1.8

Swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.0
Built => Aug 20 2022 00:00:00
coroutine => enabled with thread context
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => LibreSSL 3.5.3
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.18.1
zlib => 1.2.11
brotli => E16777225/D16777225
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.display_errors => On => On
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144
swoole.use_shortname => On => On
```

**Comment by NathanFreeman** [comment]
Could you please provide me a simple script for reproducing the error?

**Comment by matyhtf** [comment]
Use `ipcrm` to delete legacy message queues, or set `message_queue_key`  option to use a fixed message queue key instead of creating a new msg-queue each time.

```
ipcs -q
ipcrm -q {msg-queue key or id}
```
