### ISSUE TITLE
swoole_process 建议

### ISSUE THREAD

**Issue by jasonhe88** [swoole/swoole-src#480]
当swoole_process退出时(比如自己定义做了多少个操作后自然退出), swoole会自己重新拉起一个新的进程, 但是在swoole log中会留下如下出错信息: 

WARN	zm_deactivate_swoole: worker process is terminated by exit()/die()

建议除掉此信息, 因为这是合乎自然的情况

**Comment by jonnywang** [comment]
赞

**Comment by matyhtf** [comment]
这个错误信息的级别是notice，你可以忽略它。
