### ISSUE TITLE
WARNING	Worker_reactor_try_to_exit() (ERRNO 9101): worker exit timeout, forced termination

### ISSUE THREAD

**Issue by z6824980** [swoole/swoole-src#4800]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
看文档说明，这个是因为 在约定的时间 ([max_wait_time](https://wiki.swoole.com/#/server/setting?id=max_wait_time) 秒) 内此 Worker 没有退出，Swoole 底层强行终止此进程。

我这边设置了：
 'reload_async'       => true,
'max_wait_time'      => 10,
 'max_request'        => 50000,

2. What did you expect to see?
是不是调大max_wait_time的时间，可以在一定程度上避免这种警告？

3. What did you see instead?
WARNING	Worker_reactor_try_to_exit() (ERRNO 9101): worker exit timeout, forced termination

![image](https://user-images.githubusercontent.com/18024471/183798230-b9f0f97a-ed09-4150-a3f5-f4f0d7d2962f.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?
php7.2
swoole4.8.8

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by NathanFreeman** [comment]
是的，但是最好看一下代码，因为max_wait_time设置为10秒这么长都出现这个警告，而且有死锁发生。

**Comment by matyhtf** [comment]
注册`onWorkerExit`事件回调，然后在这个函数中清理进程内的定时器、任务协程、事件监听等可能会挂起进程的逻辑
