### ISSUE TITLE
 websocket server not working on ubuntu

### ISSUE THREAD

**Issue by dcl1970** [swoole/swoole-src#4804]
### 1. What did you do? If possible, provide a simple script for reproducing the error.
   
    I write a websocket server with swoole to monitor the CPU load from web. It works on centos but not on ubuntu.
    script is like below:

```
    $ws=new Swoole\WebSocket\Server('0.0.0.0',9501);
 	if($par=getopt('',['worker-num:'])){
		$worker_num=$par['worker-num'];	
		$ws->set(array('worker_num'=>$worker_num));
	}   
    $ws->on('Open',function($ws,$request){    ...       }); 
    $ws->on('message',function($ws,$frame){   ...    });
    $ws->on('Close',function($ws,$fd){    ...    });
    $ws->start();
```

### 2. What did you expect to see?
   when start websocket connection, from websocket service monitoring window on server side, see below info:

```
    Start cpu monitor
    execute : php /home/gui/cli/cmds/gui/websocket/_ws_server.php
    websocket server is started
    client-1 is connected:
    new message received:fd=1,msg=start_cpu_monitor
    receive message start_cpu_monitor from cpu-3
```
       
Above is the output on centos

### 3. What did you see instead?
    
    same script works on centos but not on ubuntu. 
    on ubuntu:

```
    Start cpu monitor
    execute : php /home/gui/cli/cmds/gui/websocket/_ws_server.php --worker-num=16
    websocket server is started
```

    
    **Below is trouble shooting details:**

    on centos, 

```
    [root@bbu45 bin]# netstat -apn |grep 9501
    tcp        0      0 0.0.0.0:9501            0.0.0.0:*               LISTEN      238100/php
    tcp        0      0 10.240.224.45:9501      10.238.224.145:50995    ESTABLISHED 238100/php
```

    on ubuntu:

```
    root@bbu05:/home# netstat -apn |grep 9501
    tcp        0      0 0.0.0.0:9501       0.0.0.0:*               LISTEN      47577/php
    root@bbu05:/home#
```

    
    **check firewall, is disabled:**

```
     root@bbu05:/home# ufw status
     Status: inactive
```

    
    **Another weird thing is,** 
    on centos, by default, swoole start one worker process for each CPU plus the master process. 
    but on ubuntu, by default, only see master process. I have to use $ws->set(array('worker_num'=>$worker_num)); 
    to force to run multiple worker process.
    

   One difference between centos and ubuntu is, on centosl PHP ver is 7.4, on ubuntu, php version is 8.1

### 4. What version of Swoole are you using (show your `php --ri swoole`)?

    root@bbu05:/home# php --ri swoole

    swoole

    Swoole => enabled
    Author => Swoole Team <team@swoole.com>
    Version => 5.0.0
    Built => Aug 12 2022 17:21:11
    coroutine => enabled with boost asm context
    epoll => enabled
    eventfd => enabled
    signalfd => enabled
    cpu_affinity => enabled
    spinlock => enabled
    rwlock => enabled
    http2 => enabled
    json => enabled
    pcre => enabled
    zlib => 1.2.12
    mutex_timedlock => enabled
    pthread_barrier => enabled
    futex => enabled
    async_redis => enabled

    Directive => Local Value => Master Value
    swoole.enable_coroutine => On => On
    swoole.enable_library => On => On
    swoole.enable_preemptive_scheduler => Off => Off
    swoole.display_errors => On => On
    swoole.use_shortname => On => On
    swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
    **root@bbu05:/home# uname -a**
    `Linux bbu05 5.15.0-1009-realtime #9-Ubuntu SMP PREEMPT_RT Thu Apr 21 20:33:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
    
   **root@bbu05:/home# cat /etc/lsb-release**
```
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=22.04
    DISTRIB_CODENAME=jammy
    DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
```
    **root@bbu05:/home# php -v**
  ```
  PHP 8.1.2 (cli) (built: Jul 21 2022 12:10:37) (NTS)
    Copyright (c) The PHP Group
    Zend Engine v4.1.2, Copyright (c) Zend Technologies
        with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
```
    **root@bbu05:/home# gcc -v**
```
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
    OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
    OFFLOAD_TARGET_DEFAULT=1
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.2.0-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-gBFGDP/gcc-11-11.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-gBFGDP/gcc-11-11.2.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
    Thread model: posix
    Supported LTO compression algorithms: zlib zstd
    gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)

```
    **root@bbu05:/home# php -m**

```
    [PHP Modules]
    calendar
    Core
    ctype
    date
    dom
    exif
    FFI
    fileinfo
    filter
    ftp
    gettext
    hash
    iconv
    json
    libxml
    openssl
    pcntl
    pcre
    PDO
    Phar
    posix
    readline
    Reflection
    session
    shmop
    SimpleXML
    sockets
    sodium
    SPL
    standard
    swoole
    sysvmsg
    sysvsem
    sysvshm
    tokenizer
    xml
    xmlreader
    xmlwriter
    xsl
    Zend OPcache
    zlib

[Zend Modules]
Zend OPcache
```

**Comment by NathanFreeman** [comment]
From swoole 5..0.0, the default mode of server is SWOOLE_BASE.

**Comment by matyhtf** [comment]
You should set the third parameter of the server constructor to SWOOLE_PROCESS

```php
$ws=new Swoole\WebSocket\Server('0.0.0.0',9501, SWOOLE_PROCESS);
```
