### ISSUE TITLE
[Question] How to specify the buffer size of the tcp coroutine server?

### ISSUE THREAD

**Issue by beef9999** [swoole/swoole-src#4806]
The code is in https://openswoole.com/docs/modules/swoole-coroutine-server#quick-start-example

```
$data = $conn->recv();
```

Looks like the buffer is dynamically allocated. How can I specify the buffer to a fixed size?

**Comment by matyhtf** [comment]
The `$conn` is the `Swoole\Coroutine\Socket` object, the first parameter of recv can set the buffer size
