### ISSUE TITLE
Support for PDO Large Objects (LOBs) as stream resource

### ISSUE THREAD

**Issue by kingIZZZY** [swoole/swoole-src#4810]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

    ```php
    // example shown using Hyperf swoole-based framework
    $pdo = Db::connection('data2')->getPdo()->prepare(...);
    $stmt = $pdo->prepare("INSERT INTO table1 (column1, column2, binary3) VALUES ($1, $2, $3)");
    $stmt->bindParam('$3', $resource, \PDO::PARAM_LOB);

    // ...

    $streamResource = Db::connection('data2')->table('table1')->where('column1', $value)->pluck('binary3')->first();
    ```

    Trying to use INSERT and SELECT on binary columns which PDO usually treats as a stream resource https://www.php.net/manual/en/pdo.lobs.php

2. What did you expect to see?

    Ability to call PDOStatement `bindParam` with `PDO::PARAM_LOB`

4. What did you see instead?
`PHP Error:  Call to undefined method Swoole\Coroutine\PostgreSQLStatement::bindParam()`

5. What version of Swoole are you using (show your `php --ri swoole`)?
    ```
    swoole
        
    Swoole => enabled
    Author => Swoole Team <team@swoole.com>
    Version => 5.0.0
    Built => Aug 12 2022 23:57:16
    coroutine => enabled with boost asm context
    epoll => enabled
    eventfd => enabled
    signalfd => enabled
    cpu_affinity => enabled
    spinlock => enabled
    rwlock => enabled
    sockets => enabled
    openssl => OpenSSL 3.0.2 15 Mar 2022
    dtls => enabled
    http2 => enabled
    json => enabled
    curl-native => enabled
    pcre => enabled
    zlib => 1.2.11
    brotli => E16777225/D16777225
    mutex_timedlock => enabled
    pthread_barrier => enabled
    futex => enabled
    mysqlnd => enabled
    async_redis => enabled
    coroutine_postgresql => enabled
    
    Directive => Local Value => Master Value
    swoole.enable_coroutine => On => On
    swoole.enable_library => On => On
    swoole.enable_preemptive_scheduler => Off => Off
    swoole.display_errors => On => On
    swoole.use_shortname => On => On
    swoole.unixsock_buffer_size => 8388608 => 8388608
    ```

6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
    - `uname -a`:
      - `Linux 4353894d-ea3c-47ed-8bda-63bfda6a0b59 4.4.0-1104-aws #109-Ubuntu SMP Tue May 10 11:27:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
    - `php -v`:
      - ```
        PHP 8.1.9 (cli) (built: Aug  4 2022 11:57:37) (NTS)
        Copyright (c) The PHP Group
        Zend Engine v4.1.9, Copyright (c) Zend Technologies
            with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies```
    - `gcc -v`:
        ```
        Using built-in specs.
        COLLECT_GCC=gcc
        COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
        OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
        OFFLOAD_TARGET_DEFAULT=1
        Target: x86_64-linux-gnu
        Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.2.0-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-gBFGDP/gcc-11-11.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-gBFGDP/gcc-11-11.2.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
        Thread model: posix
        Supported LTO compression algorithms: zlib zstd
        gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)
        ```

**Comment by NathanFreeman** [comment]
```php
$pdo = Db::connection('data2')->getPdo()->prepare(...);
$stmt = $pdo->prepare("INSERT INTO table1 (column1, column2, binary3) VALUES ($1, $2, $3)");
$stmt->execute([$1, $2, $3]);
```

**Comment by kingIZZZY** [comment]
> 1. Trying to use INSERT and SELECT on binary columns which PDO usually treats as a stream resource https://www.php.net/manual/en/pdo.lobs.php

Not possible to have PDO:::PARAM_LOB functionality as documented in php PDO? https://www.php.net/manual/en/pdo.lobs.php

**Comment by matyhtf** [comment]
The `Swoole\Coroutine\PostgreSQL` does not support this method yet.

**Comment by deminy** [comment]
Three new methods added in Swoole 5.0.1 to support Large Objects in PostgreSQL:

* [\Swoole\Coroutine\PostgreSQL::createLOB()](https://github.com/swoole/ide-helper/blob/5.0.1/src/swoole/Swoole/Coroutine/PostgreSQL.php#L61)
* [\Swoole\Coroutine\PostgreSQL::openLOB()](https://github.com/swoole/ide-helper/blob/5.0.1/src/swoole/Swoole/Coroutine/PostgreSQL.php#L73)
* [\Swoole\Coroutine\PostgreSQL::unlinkLOB()](https://github.com/swoole/ide-helper/blob/5.0.1/src/swoole/Swoole/Coroutine/PostgreSQL.php#L84)

**Comment by kingIZZZY** [comment]
In regular PHP PDO I think the fetch*() methods internally automatically return LOBs based on column, is this possible also here in Swoole Coroutine PostgreSQL ? Or will it be limited that you can only interact with LOBs using these custom methods?

I'd very much prefer if it was possible to make Swoole Coroutine PostgreSQL function as close as possible to regular PHP PDO and return LOBs with the fetch*() methods... 🙏
