### ISSUE TITLE
5.0版本短名映射存在异常

### ISSUE THREAD

**Issue by geyouwen** [swoole/swoole-src#4813]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

Argument #1 ($req) must be of type swoole_http_request, Swoole\Http\Request given

```
$server->listen('Request', function (\Swoole\Http\Request $request, \Swoole\Http\Response $response) {
$req = new Request($request);
}
```

` public function __construct(private swoole_http_request $req)`

同样的代码，这个问题在4.8版本上就不存在.

**Comment by NathanFreeman** [comment]
请执行`php --ri swoole`查看swoole.use_shortname是否关闭了

**Comment by matyhtf** [comment]
请认真阅读 ChangeLog，5.0 版本已移除 PSR-0 下划线分割的类名，请检查代码，全部改为命名空间风格。
