### ISSUE TITLE
ext-src/php_swoole_private.h:95:2: error: #error "require PHP version 8.0 or later

### ISSUE THREAD

**Issue by Dchancat** [swoole/swoole-src#4816]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by Dchancat** [comment]
![image](https://user-images.githubusercontent.com/48940578/186372577-7edae552-d252-42f5-bca5-18127e089f51.png)

**Comment by Yurunsoft** [comment]
Swoole 5.0 requires PHP >= 8.0

**Comment by NathanFreeman** [comment]
swoole5 only supports PHP8.0 or later.

**Comment by Dchancat** [comment]
![image](https://user-images.githubusercontent.com/48940578/186607960-2f20df92-3210-45e2-80df-e80344da0964.png)
fine
