### ISSUE TITLE
用swoole连接rabbitmq报错 开启task多进程模式

### ISSUE THREAD

**Issue by winfan** [swoole/swoole-src#482]
怎么用swoole连接rabbitmq?
 放到onWorkerStart 报错
Server channel error: 405, message: RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'swoole_queue_name' in vhost '/'Server channel error: 405, message: RESOURCE_LOCKED

public function onWorkerStart( $serv , $worker_id) {

        if( $worker_id >= $serv->setting['worker_num'] ) {

            //Establish connection to AMQP
            $mq_conn = new AMQPConnection();
            $mq_conn ->setHost('127.0.0.1');
            $mq_conn ->setLogin('guest');
            $mq_conn ->setPassword('guest');
            $mq_conn ->connect();

            //Declare Channel
            $mq_channel = new AMQPChannel($mq_conn);
            try {
                //Declare Exchange

                $mq_exchange = new AMQPExchange($mq_channel);
                $mq_exchange->setType(AMQP_EX_TYPE_DIRECT);
                $mq_exchange->setName($this->mq_exchange_name);
                $mq_exchange->declareExchange();

                $queue = new AMQPQueue($mq_channel);
                $queue->setFlags(AMQP_EXCLUSIVE);
                $queue->setName($this->mq_queue_name);
                $queue->declareQueue();

                $queue->bind($this->mq_exchange_name, $this->mq_router_name);

                $this->mq_exchange = $mq_exchange;
                //$exchange->publish($message,$routing_key);
                //echo " [x] Sent {$severity}:{$message}", PHP_EOL;
            } catch(Exception $ex) {
                echo $ex->getMessage();
            }

        }
    }

**Comment by matyhtf** [comment]
这应该是`AMP`的限制，你可以使用`addProcess`开一个进程专门去队列中取数据
