### ISSUE TITLE
Cannot build swoole 5.0.0 in macos-11.0 src/core/base.cc:70:9: error: use of undeclared identifier 'CCRandomGenerateBytes'

### ISSUE THREAD

**Issue by Blackjack200** [swoole/swoole-src#4829]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
```
OPENSSL_VERSION="1.1.1p"
#in swoole dir

./configure --with-php-config="$INSTALL_DIR/bin/php-config" \
--with-openssl-dir="$OPENSSL_DIR" \
--enable-http2 \
--enable-swoole-json
```
2. What did you expect to see?

ubuntu-18.04: compile success

macos: compile success

3. What did you see instead?

ubuntu-18.04: compile success

macos:
```
/Users/runner/work/php-build-scripts/php-build-scripts/install_data/subdir/php/ext/swoole/src/core/base.cc:70:9: error: use of undeclared identifier 'CCRandomGenerateBytes'
    if (CCRandomGenerateBytes(buffer, size) == kCCSuccess) {
        ^
/Users/runner/work/php-build-scripts/php-build-scripts/install_data/subdir/php/ext/swoole/src/core/base.cc:70:48: error: use of undeclared identifier 'kCCSuccess'
    if (CCRandomGenerateBytes(buffer, size) == kCCSuccess) {
                                               ^
1 warning generated.
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

5.0.0 in github releases

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

PHP: 8.0.22

```
Darwin Mac-1662258959767.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64 x86_64
```

**Comment by deminy** [comment]
I tried to install Swoole 5.0.0 on macOS 11, and it went through well.

Here is the environment:

```text
$ uname -a
Darwin demin-mac-0010 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 29 04:31:06 PDT 2022; root:xnu-7195.141.39~2/RELEASE_X86_64 x86_64

$ php -v
PHP 8.0.23 (cli) (built: Sep  4 2022 07:50:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.23, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.23, Copyright (c), by Zend Technologies

$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

And, here is the script I used to install Swoole 5.0.0 on macOS:

```bash
cd /path/to/swoole-src

make clean

# Install dependencies if needed.
#     brew install libpq
#     brew install openssl

phpize

export LIBPQ_CFLAGS="-I/usr/local/opt/libpq/include"
export LIBPQ_LIBS="-L/usr/local/opt/libpq/lib"

./configure \
    --enable-openssl \
    --with-openssl-dir=/usr/local/opt/openssl@3 \
    --enable-mysqlnd \
    --enable-swoole-pgsql \
    --enable-sockets \
    --enable-swoole-curl

make -j$(nproc)

# NO_INTERACTION=1 make test

make install

printf "extension=swoole.so\n" > "$(php-config --ini-dir)/ext-swoole.ini"

php --ri swoole
php --rc '\Swoole\Coroutine\PostgreSQL'
```

**Comment by Blackjack200** [comment]
> I tried to install Swoole 5.0.0 on **macOS 11.7** (not macOS 11.0), and it went through well.
> 
> Here is the environment:
> 
> ```
> $ uname -a
> Darwin demin-mac-0010 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 29 04:31:06 PDT 2022; root:xnu-7195.141.39~2/RELEASE_X86_64 x86_64
> 
> $ php -v
> PHP 8.0.23 (cli) (built: Sep  4 2022 07:50:44) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v4.0.23, Copyright (c) Zend Technologies
>     with Zend OPcache v8.0.23, Copyright (c), by Zend Technologies
> 
> $ gcc -v
> Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
> Apple clang version 13.0.0 (clang-1300.0.29.30)
> Target: x86_64-apple-darwin20.6.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> ```
> 
> And, here is the script I used to install Swoole 5.0.0 on macOS:
> 
> ```shell
> cd /path/to/swoole-src
> 
> make clean
> 
> # Install dependencies if needed.
> #     brew install libpq
> #     brew install openssl
> 
> phpize
> 
> export LIBPQ_CFLAGS="-I/usr/local/opt/libpq/include"
> export LIBPQ_LIBS="-L/usr/local/opt/libpq/lib"
> 
> ./configure \
>     --enable-openssl \
>     --with-openssl-dir=/usr/local/opt/openssl@3 \
>     --enable-mysqlnd \
>     --enable-swoole-pgsql \
>     --enable-sockets \
>     --enable-swoole-curl
> 
> make -j$(nproc)
> 
> # NO_INTERACTION=1 make test
> 
> make install
> 
> printf "extension=swoole.so\n" > "$(php-config --ini-dir)/ext-swoole.ini"
> 
> php --ri swoole
> php --rc '\Swoole\Coroutine\PostgreSQL'
> ```

my openssl version is "1.1.1p"

**Comment by finallylly** [comment]
I tried to install Swoole 5.0.0 on macOS 10.12, it got the same error.
But I went through by:

`vim swoole-5.0.0/src/core/base.cc` at line 52:

**#include <CommonCrypto/CommonCryptoError.h>
#include <CommonCrypto/CommonRandom.h>**

change to line 49
```
#if defined(__APPLE__) && defined(HAVE_CCRANDOMGENERATEBYTES)
#include <Availability.h>
#include <CommonCrypto/CommonCryptoError.h>
#include <CommonCrypto/CommonRandom.h>
#if (defined(__MAC_OS_X_VERSION_MIN_REQUIRED) && __MAC_OS_X_VERSION_MIN_REQUIRED >= 101000) ||                         \
    (defined(__IPHONE_OS_VERSION_MIN_REQUIRED) && __IPHONE_OS_VERSION_MIN_REQUIRED >= 80000)
#define OPENSSL_APPLE_CRYPTO_RANDOM 1
#endif
#endif
```
