### ISSUE TITLE
尝试获取session失败

### ISSUE THREAD

**Issue by trainyao** [swoole/swoole-src#483]
首先在服务器一个端口的网站进行登录，记录了session，然后访问同一服务器不同端口开启的swoole服务器(用swoole_server_create()初始化的服务器)，进行连接发送消息，在onReceive试图获取$_SESSION数组，提示“Undefined variable: _SESSION in。。。。。”

请问怎么才能获取在网站登录设置的session值呢?

**Comment by matyhtf** [comment]
swoole不支持PHP的session_系列函数，你可以自行实现Session的功能，可以借助Memcache，Redis，MySQL

**Comment by trainyao** [comment]
这样..感激
