### ISSUE TITLE
Unable to build after v4.8.12 has been released

### ISSUE THREAD

**Issue by ahmadateya** [swoole/swoole-src#4834]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
Cloning and enabling latest version of swoole package in my dockerfile by running
`RUN cd / &&  git clone https://github.com/swoole/swoole-src.git \
    && ( \
        cd swoole-src \
        && phpize \
        && ./configure --enable-swoole-debug --enable-mysqlnd \
        && make -j$(nproc) && make install \
        ) \
    && rm -r /swoole-src \
    && docker-php-ext-enable swoole \
    && rm -rf /var/cache/apk/*`

2. What did you expect to see?
to build succefully.

3. What did you see instead?
`configure:8962: error: possibly undefined macro: AC_SWOOLE_HAVE_GETHOSTBYNAME2_R`

4. What version of Swoole are you using (show your `php --ri swoole`)?
v4.8.12

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
bash-5.1# uname -a
Linux bdce659cc878 5.13.0-52-generic # 59-Ubuntu SMP Wed Jun 15 20:17:13 UTC 2022 x86_64 Linux

bash-5.1# php -v
PHP 8.1.1 (cli) (built: Dec 18 2021 01:28:28) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies

bash-5.1# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/10.3.1/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-10.3.1_git20211027/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 10.3.1_git20211027' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,d,objc,go,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.3.1 20211027 (Alpine 10.3.1_git20211027)

**Comment by YoussefAshraf397** [comment]
+1

**Comment by NathanFreeman** [comment]
Have you ever executed `git checkout 4.8.x` to switch branches before compiling swoole?

**Comment by Lrun-web** [comment]
pecl install https://github.com/swoole/swoole-src/archive/v4.8.12.tar.gz
downloading v4.8.12 ...
Starting to download v4.8.12 (Unknown size)
................................................................................done: 1,755,820 bytes
ERROR: file /private/tmp/pear/temp/tmpqtgi3e/swoole-4.8.12/CMakeLists.txt does not exist

**Comment by matyhtf** [comment]
fixed,
