### ISSUE TITLE
swoole_http_response 是否能proxy

### ISSUE THREAD

**Issue by mysteriouss** [swoole/swoole-src#485]
static PHP_METHOD(swoole_http_response, write);
static PHP_METHOD(swoole_http_response, end);
static PHP_METHOD(swoole_http_response, sendfile);
static PHP_METHOD(swoole_http_response, cookie);
static PHP_METHOD(swoole_http_response, rawcookie);
static PHP_METHOD(swoole_http_response, header);
static PHP_METHOD(swoole_http_response, gzip);
static PHP_METHOD(swoole_http_response, status);

write和end方法都会默认加上头部信息

HTTP/1.1 200 OK
Server: swoole-http-server
Content-Type: text/html

不知道是否支持发送raw content, 实现proxy功能

**Comment by mysteriouss** [comment]
$swoole_http_server::send() ?

**Comment by matyhtf** [comment]
支持

**Comment by mysteriouss** [comment]
send完后直接close会不会有问题呀？

**Comment by matyhtf** [comment]
没问题。你可以测试一下，如果有问题可以反馈给我
