### ISSUE TITLE
Invalid "Transfer-Encoding: chunked" header appended

### ISSUE THREAD

**Issue by ignacioalles** [swoole/swoole-src#4857]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

If I send some bytes by `Swoole\Http\Response::write`, `Transfer-Encoding: chunked` header is added to the response, regardless `Content-Length` header was already sent.
```php
$http->on('Request', function (Request $request, Response $response) {
    $response->header('Content-Length', 5);
    $response->write('Hello');
    $response->end();
});
```

However, the header is not added if the bytes are sent with `Swoole\Http\Response::end`
```php
$http->on('Request', function (Request $request, Response $response) {
    $response->header('Content-Length', 5);
    $response->end('Hello');
});
```

2. What did you expect to see?
I expect that no additional headers were added.
```
HTTP/1.1 200 OK
Content-Length: 5
Server: swoole-http-server
Connection: keep-alive
Content-Type: text/html
Date: Wed, 21 Sep 2022 15:49:46 GMT

Hello
```

3. What did you see instead?
`Transfer-Encoding: chunked` header is added to the response

```
HTTP/1.1 200 OK
Content-Length: 5
Server: swoole-http-server
Connection: keep-alive
Content-Type: text/html
Date: Wed, 21 Sep 2022 15:47:19 GMT
Transfer-Encoding: chunked

Hello
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
It happened with both 4.8.10 and 5.0.0

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Docker container based on `Alpine Linux 3.13.7` with:
`uname -a`
```
Linux 20f10e4807a5 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 Linux
```
`php -v`
```
PHP 8.0.13 (cli) (built: Nov 19 2021 22:57:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies
```
`gcc -v`
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/10.2.1/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-10.2.1_pre1/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 10.2.1_pre1' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,d,objc,go,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.1 20201203 (Alpine 10.2.1_pre1) 
```

It was already fixed in openswoole/swoole-src/pull/251 and affects laravel/octane/issues/568

**Comment by NathanFreeman** [comment]
Thank you for your issue.

**Comment by L3o-pold** [comment]
The fix ignore the `Content-Length` header but the original issue state that we need to not add `Transfer-Encoding: chunked` header. By removing the `Content-Length` header, we broke the download progress in browser.
