### ISSUE TITLE
Swoole and PHP 7

### ISSUE THREAD

**Issue by cesarkohl** [swoole/swoole-src#486]
Hello,

Congratulations for the project, it's really a good idea.

Unfortunately I couldn't install Swoole using PHP 7.0.0 or PHP 7.0.2.

```
$ pecl install swoole
Could not open input file: /Applications/MAMP/bin/php/php7.0.0/lib/php/peclcmd.php
```

Are you aware of it or do I need to do an alternate configuration?

Best,
Cesar

**Comment by lscgzwd** [comment]
May be you need run command with sudo or manually build.  On my mac , I install swoole and php7.0.2 by brew , It works ok.

**Comment by cesarkohl** [comment]
Good to know, I'll try again. Thanks!
