### ISSUE TITLE
4.8.10出现段错误 (核心转储)

### ISSUE THREAD

**Issue by allenchwei** [swoole/swoole-src#4860]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
swoole升级到4.8.10，主要是问题复现不了

2. What did you expect to see?
解决这个问题

3. What did you see instead?
core-php-3176-1664628382
`(gdb) bt
#0  0x00005578c2d42b5d in zend_exception_error ()
#1  0x00007f66b698d5f2 in ?? () from /usr/lib/php/20200930/swoole.so
#2  0x00007f66b6a28726 in swoole::Coroutine::resume() () from /usr/lib/php/20200930/swoole.so
#3  0x00007f66b6a5379f in swoole::AsyncThreads::callback(swoole::Reactor*, swoole::Event*) () from /usr/lib/php/20200930/swoole.so
#4  0x00007f66b6a6d80c in swoole::ReactorEpoll::wait(timeval*) () from /usr/lib/php/20200930/swoole.so
#5  0x00007f66b6a96256 in swoole::Server::start_event_worker(swoole::Worker*) () from /usr/lib/php/20200930/swoole.so
#6  0x00007f66b6a73d65 in swoole::Server::spawn_event_worker(swoole::Worker*) () from /usr/lib/php/20200930/swoole.so
#7  0x00007f66b6a74904 in swoole::Manager::start(swoole::Server*) () from /usr/lib/php/20200930/swoole.so
#8  0x00007f66b6a75bef in swoole::Server::start_manager_process() () from /usr/lib/php/20200930/swoole.so
#9  0x00007f66b6a899e8 in swoole::ProcessFactory::start() () from /usr/lib/php/20200930/swoole.so
#10 0x00007f66b6a80f9f in swoole::Server::start() () from /usr/lib/php/20200930/swoole.so
#11 0x00007f66b6a06c79 in ?? () from /usr/lib/php/20200930/swoole.so
#12 0x00005578c2f768d0 in execute_ex ()
#13 0x00005578c2f76d4d in zend_execute ()
#14 0x00005578c2f0874b in zend_execute_scripts ()
#15 0x00005578c2ea4887 in php_execute_script ()
#16 0x00005578c2f9df2c in ?? ()
#17 0x00005578c2d49ff6 in ?? ()
#18 0x00007f66c2e8ac87 in __libc_start_main (main=0x5578c2d49be0, argc=3, argv=0x7fff30fe5128, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fff30fe5118) at ../csu/libc-start.c:310
#19 0x00005578c2d4a6ea in _start ()
(gdb) f 1
#1  0x00007f66b698d5f2 in ?? () from /usr/lib/php/20200930/swoole.so
(gdb) f 0
#0  0x00005578c2d42b5d in zend_exception_error ()`

4. What version of Swoole are you using (show your `php --ri swoole`)?
`swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.10
Built => Jul  6 2022 13:14:08
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1  11 Sep 2018
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608`

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
`Linux iZuf6klve1lap4Z 4.15.0-190-generic #201-Ubuntu SMP Mon Jul 11 20:36:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
[1]-  Done                    uname -a

root@iZuf6klve1lap4Z:/corefile# PHP 8.0.22 (cli) (built: Aug 15 2022 09:39:40) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.22, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.22, Copyright (c), by Zend Technologies`

**Comment by NathanFreeman** [comment]
这个是启动的时候报错吗

**Comment by allenchwei** [comment]
不是的，运行一段时间才有

**Comment by allenchwei** [comment]
core问题重新上传一下
```
(gdb) bt
#0  0x00005578c2d42b5d in zend_exception_error ()
#1  0x00007f66b698d5f2 in ?? () from /usr/lib/php/20200930/swoole.so
#2  0x00007f66b6a28726 in swoole::Coroutine::resume() () from /usr/lib/php/20200930/swoole.so
#3  0x00007f66b6a5379f in swoole::AsyncThreads::callback(swoole::Reactor*, swoole::Event*) () from /usr/lib/php/20200930/swoole.so
#4  0x00007f66b6a6d80c in swoole::ReactorEpoll::wait(timeval*) () from /usr/lib/php/20200930/swoole.so
#5  0x00007f66b6a96256 in swoole::Server::start_event_worker(swoole::Worker*) () from /usr/lib/php/20200930/swoole.so
#6  0x00007f66b6a73d65 in swoole::Server::spawn_event_worker(swoole::Worker*) () from /usr/lib/php/20200930/swoole.so
#7  0x00007f66b6a74904 in swoole::Manager::start(swoole::Server*) () from /usr/lib/php/20200930/swoole.so
#8  0x00007f66b6a75bef in swoole::Server::start_manager_process() () from /usr/lib/php/20200930/swoole.so
#9  0x00007f66b6a899e8 in swoole::ProcessFactory::start() () from /usr/lib/php/20200930/swoole.so
#10 0x00007f66b6a80f9f in swoole::Server::start() () from /usr/lib/php/20200930/swoole.so
#11 0x00007f66b6a06c79 in ?? () from /usr/lib/php/20200930/swoole.so
#12 0x00005578c2f768d0 in execute_ex ()
#13 0x00005578c2f76d4d in zend_execute ()
#14 0x00005578c2f0874b in zend_execute_scripts ()
#15 0x00005578c2ea4887 in php_execute_script ()
#16 0x00005578c2f9df2c in ?? ()
#17 0x00005578c2d49ff6 in ?? ()
#18 0x00007f66c2e8ac87 in __libc_start_main (main=0x5578c2d49be0, argc=3, argv=0x7fff30fe5128, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fff30fe5118) at ../csu/libc-start.c:310
#19 0x00005578c2d4a6ea in _start ()
(gdb) f 1
#1  0x00007f66b698d5f2 in ?? () from /usr/lib/php/20200930/swoole.so
(gdb) f 0
#0  0x00005578c2d42b5d in zend_exception_error ()
```

**Comment by NathanFreeman** [comment]
是有间隔的重复出现吗，是的话要排查一下定时器

**Comment by allenchwei** [comment]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/31726062/193434346-9dc9f196-b298-43d0-bc90-d214aecb4c2d.png">
是有间隔重复出现，但我没有定时器程序，只是开启task_max_request和max_request，这会不会影响？

**Comment by NathanFreeman** [comment]
max_request达到一定次数就会重启，看看onWorkerStart有没有设置

**Comment by allenchwei** [comment]
set中已设置了reload_async和max_wait_time值，我用的hyperf框架，是其他原因吗？
```
'settings' => [
        Constant::OPTION_ENABLE_COROUTINE => true,
        Constant::OPTION_WORKER_NUM => swoole_cpu_num(),
        Constant::OPTION_RELOAD_ASYNC => true,
        Constant::OPTION_MAX_WAIT_TIME => 10,
        Constant::OPTION_PID_FILE => BASE_PATH . '/runtime/hyperf.pid',
        Constant::OPTION_OPEN_TCP_NODELAY => true,
        Constant::OPTION_MAX_COROUTINE => 100000,
        Constant::OPTION_OPEN_HTTP_PROTOCOL => true,
        Constant::OPTION_OPEN_HTTP2_PROTOCOL => true,
        Constant::OPTION_TASK_MAX_REQUEST => 10000,
        Constant::OPTION_MAX_REQUEST => 10000
    ],
```

**Comment by NathanFreeman** [comment]
看起来是异步线程中抛出了异常

**Comment by allenchwei** [comment]
请问这个问题怎么解决呢？

**Comment by matyhtf** [comment]
@allenchwei 请使用 4.8.12 版本，这是因为 fatal error 引起的
