### ISSUE TITLE
swoole v5.0  make  出错 

### ISSUE THREAD

**Issue by andy236726493** [swoole/swoole-src#4861]
swoole v5.0 执行
phpize
./configure --enable-swoole-pgsql    --with-php-config=/www/server/php/80/bin/php-config
make  出现下面错错误

/www/server/swoole-5.0.0/ext-src/swoole_postgresql_coro.cc: 在函数‘void set_error_diag(const PGObject*, const PGresult*)’中:
/www/server/swoole-5.0.0/ext-src/swoole_postgresql_coro.cc:653:41: 错误：‘PG_DIAG_SCHEMA_NAME’在此作用域中尚未声明
                                         PG_DIAG_SCHEMA_NAME,
                                         ^
/www/server/swoole-5.0.0/ext-src/swoole_postgresql_coro.cc:654:41: 错误：‘PG_DIAG_TABLE_NAME’在此作用域中尚未声明
                                         PG_DIAG_TABLE_NAME,
                                         ^
/www/server/swoole-5.0.0/ext-src/swoole_postgresql_coro.cc:655:41: 错误：‘PG_DIAG_COLUMN_NAME’在此作用域中尚未声明
                                         PG_DIAG_COLUMN_NAME,
                                         ^
/www/server/swoole-5.0.0/ext-src/swoole_postgresql_coro.cc:656:41: 错误：‘PG_DIAG_DATATYPE_NAME’在此作用域中尚未声明
                                         PG_DIAG_DATATYPE_NAME,
                                         ^
/www/server/swoole-5.0.0/ext-src/swoole_postgresql_coro.cc:657:41: 错误：‘PG_DIAG_CONSTRAINT_NAME’在此作用域中尚未声明

**Comment by NathanFreeman** [comment]
安装了libpq了吗

**Comment by andy236726493** [comment]
libpq 安装的，没安装的话有提示的

**Comment by andy236726493** [comment]
用这个命令安装的 yum install postgresql-devel，你们文档上的 yum install postgresql10-devel 不能安装

**Comment by andy236726493** [comment]
centos 7.9  用宝塔面板，之前安装过 postgresql v12

**Comment by andy236726493** [comment]
swoole  v4.8 以前  ./configure --with-libpq-dir=   这样是可以的， v5.0,现在   --with-libpq-dir  这个参数好像没了

**Comment by NathanFreeman** [comment]
感觉你存在多个版本的libpq，swoole5已经集成了swoole_postgresql

**Comment by andy236726493** [comment]
yum install postgresql12-devel 重新安装了，make 时错误：‘PG_DIAG_SCHEMA_NAME’在此作用域中尚未声明 还有

**Comment by andy236726493** [comment]
我用干净系统再试一下

**Comment by andy236726493** [comment]
1.安装 yum install postgresql12-devel 完成
2. ./configure  --enable-openssl --with-php-config=/www/server/php/80/bin/php-config  --enable-swoole-pgsql
执行时出下面错误--

libpq headers was not found.
set LIBPQ_CFLAGS and LIBPQ_LIBS environment or
install following package to obtain them:
    libpq-dev (for debian and its varients)
    postgresql-devel (for rhel varients)
    libpq-devel (for newer fedora)
    postgresql-libs (for arch and its varients)
    postgresql-dev (for alpine)
    postgresql (for homebrew)
configure: error: postgresql support needs libpq headers to build

**Comment by NathanFreeman** [comment]
找一下有没有libpq-fe.h这份文件

**Comment by andy236726493** [comment]
我执行了 yum install postgresql-devel ，后 ./configure  上面的错误信息没了，但  make  时 错误：‘PG_DIAG_TABLE_NAME’在此作用域中尚未声明

**Comment by andy236726493** [comment]
现在有两个文件
/usr/include/libpq-fe.h
/usr/pgsql-12/include/libpq-fe.h

**Comment by NathanFreeman** [comment]
你备份一下/usr/include/libpq-fe.h这份文件，然后ln -s /usr/pgsql-12/include/libpq-fe.h /usr/include/libpq-fe.h 试试，注意要先备份。

**Comment by andy236726493** [comment]
ln -s /usr/pgsql-12/include/libpq-fe.h /usr/include/libpq-fe.h   执行了，

make 还有错误

In file included from /www/wwwroot/swoole-src-5.0.0/ext-src/swoole_postgresql_coro.cc:24:0:
/usr/include/libpq-fe.h:582:8: 错误：‘pg_int64’不是一个类型名
 extern pg_int64 lo_lseek64(PGconn *conn, int fd, pg_int64 offset, int whence);
        ^
/usr/include/libpq-fe.h:586:8: 错误：‘pg_int64’不是一个类型名
 extern pg_int64 lo_tell64(PGconn *conn, int fd);
        ^
/usr/include/libpq-fe.h:588:48: 错误：‘pg_int64’未声明
 extern int lo_truncate64(PGconn *conn, int fd, pg_int64 len);

**Comment by NathanFreeman** [comment]
我待会试一下

**Comment by andy236726493** [comment]
ln -s /usr/pgsql-12/include/libpq-fe.h /usr/include/libpq-fe.h 执行后 ，/configure 又出错了

libpq headers was not found.
set LIBPQ_CFLAGS and LIBPQ_LIBS environment or
install following package to obtain them:
    libpq-dev (for debian and its varients)
    postgresql-devel (for rhel varients)
    libpq-devel (for newer fedora)
    postgresql-libs (for arch and its varients)
    postgresql-dev (for alpine)
    postgresql (for homebrew)
configure: error: postgresql support needs libpq headers to build

**Comment by andy236726493** [comment]
小结
1. yum install postgresql-devel  
   /configure  对了，make 出错
2. yum install postgresql12-devel
  ln -s /usr/pgsql-12/include/libpq-fe.h /usr/include/libpq-fe.h 执行了
  /configure  又出错了

**Comment by andy236726493** [comment]
NathanFreeman  有没有试试啊

**Comment by NathanFreeman** [comment]
你按照我这个步骤试试，他可能是找不到正确的头文件。
![微信截图_20221005161922](https://user-images.githubusercontent.com/33935209/194014342-2dd008b1-4efd-4fe9-9e9a-4a80287c7ac3.png)

**Comment by andy236726493** [comment]
可以了，谢谢
