### ISSUE TITLE
onRequest event missing in coroutine style HTTP server

### ISSUE THREAD

**Issue by Meldiron** [swoole/swoole-src#4867]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

I tried to implement a coroutine-style HTTP server that would behave as a simple proxy that forwards requests.

This is the code I wrote:

```php
<?php

run(function () {
    $server = new Server('0.0.0.0', 80, false);
    // TODO: Wildcard endpoint support (star symbol wont work here, but / would work. Only for one endpoint tho
    $server->handle('*', function (SwooleRequest $swooleRequest, SwooleResponse $swooleResponse) {
          $swooleResponse->setStatusCode(200);
          $swooleResponse->header('content-type', 'application/json; charset=UTF-8');
          $swooleResponse->write(\json_encode(['ok' => true]));
          $swooleResponse->end();
    });

    Console::success("Functions proxy is ready.");

    $server->start();
});
```

2. What did you expect to see?

I expected to find a method similar to `->on('request'`. This method is there in async style HTTP server: https://wiki.swoole.com/#/http_server?id=on

3. What did you see instead?

I found the method `–>handle($pattern` that requires a pattern. The problem is that this does not allow listening to all requests nor having dynamic parts in the endpoint.

4. What version of Swoole are you using (show your `php --ri swoole`)?

Using `--branch v4.8.10`.

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.10
Built => Oct 10 2022 09:50:49
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1q  5 Jul 2022
dtls => enabled
http2 => enabled
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Using Gitpod for development. Script runts inside Docker from this [Dockerfile](https://github.com/appwrite/appwrite/blob/master/Dockerfile).

Gitpod environment:

Linux appwrite-appwrite-h1h4tqqsse9 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.1.9 (cli) (built: Aug 15 2022 09:39:52) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by matyhtf** [comment]
@Meldiron Just set the pattern parameter to `/`, Indicates that this handles all requests. 

The `$pattern`  parameter is the same as the location configuration of nginx

```php
<?php

run(function () {
    $server = new Server('0.0.0.0', 80, false);

    $server->handle('/', function (SwooleRequest $swooleRequest, SwooleResponse $swooleResponse) {
          $swooleResponse->setStatusCode(200);
          $swooleResponse->header('content-type', 'application/json; charset=UTF-8');
          $swooleResponse->write(\json_encode(['ok' => true]));
          $swooleResponse->end();
    });

    Console::success("Functions proxy is ready.");

    $server->start();
});
```
