### ISSUE TITLE
ProcessPool::wait(): worker#1 abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by reegle** [swoole/swoole-src#4874]
A bug occurred in Swoole-v5.0.0, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
GCC_VERSION: Apple LLVM 13.1.6 (clang-1316.0.21.2.5)
OPENSSL_VERSION: OpenSSL 1.1.1m  14 Dec 2021
PHP_VERSION : 8.1.8

=======

在Mac下，久了没有访问页面会出现这个错误，或者有时候多点几下页面，会偶发一次这样的报错，导致Nginx反代会显示502错误。不清楚是什么原因

**Comment by matyhtf** [comment]
请提供可以稳定重现的代码包，以及重现的方法
