### ISSUE TITLE
1.8.0 beta在php-7.0.2测试错误

### ISSUE THREAD

**Issue by jonnywang** [swoole/swoole-src#488]
swoole_redis.c  328行 ZVAL_STRINGL(return_value, reply->str, reply->len, 1);  7不适用

swoole_redis.c:266 Segmentation fault: 11 (core dumped)

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/6a5b3f6805e96d11de66d35e05e8ef6a91ad0cdd
已修复。

**Comment by jonnywang** [comment]
1.8.0-rc1
dyld: lazy symbol binding failed: Symbol not found: _swReactorThread_alloc

php7.0.2 example/redis/client.php

Last leak repeated 2 times
=== Total 4 memory leaks detected ===
