### ISSUE TITLE
An error will be reported after running for a while

### ISSUE THREAD

**Issue by rory5515** [swoole/swoole-src#4885]
OS: win10 64bit

pakege: swoole-cli-v5.0.0-cygwin64.zip

After about 20 minutes of running, I got this error in both 4.8.11 and 5.0.0.

`swoole-cli 77 cygwin_exception::open_stackdumpfile: Dumping stack trace to swoole-cli.exe.stackdump`

```
run(function () use ($config){
    $spider = new Spider($config);
    $wg =  new WaitGroup();
    for ($i=0;$i<10;$i++) {
        $wg->add();
        go(function () use($wg,$spider){
            $spider->start();
            $wg->done();
        });
    }
    $wg->wait();
});
```

**Comment by matyhtf** [comment]
@rory5515 Does the same issue exist in Linux ?

**Comment by rory5515** [comment]
> 
No, I haven't tested it on Linux.

**Comment by matyhtf** [comment]
@rory5515 Can you provide a code example that can be reproduced stably?
