### ISSUE TITLE
In your git exampels,you call on("connect", callback()) on WebSocket where onConnect event is not availabel on WebSocket.

### ISSUE THREAD

**Issue by fakharksa** [swoole/swoole-src#4888]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

I saw the example code on your git repo for WebSocket, which is calling on("connect", callback()) on WebSocket server where as on("connect", callback()); event is not available on WebSocket Server. So it looks like a mistake.

The link of exampel is as below:
[Web Socket Example on Git](https://github.com/swoole/swoole-src/blob/master/examples/ssl/websocket_server.php)

2. What did you expect to see?

I expect to see something like $port->on("connect" callback()); 

3. What did you see instead?

$serv->on("connect", callback());

4. What version of Swoole are you using (show your `php --ri swoole`)?

The issue is in code example on your git repo. Link already given above.

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Not Applicable.

**Comment by NathanFreeman** [comment]
```php
<?php
$serv = new Swoole\WebSocket\Server("0.0.0.0", 9502, SWOOLE_BASE);
$ports = $serv->ports;
$ports[0]->on('connect', function () {});
```

**Comment by fakharksa** [comment]
> ```
> <?php
> $serv = new Swoole\WebSocket\Server("0.0.0.0", 9502, SWOOLE_BASE);
> $ports = $serv->ports;
> $ports[0]->on('connect', function () {});
> ```

Thanks for making me aware of another way of registering connect event using $ports[0]. however ...

i think, in the context of example, it should be:

`$port->on('connect', function() { ...});`



just as we can do 

$port = $serv->listen('127.0.0.1', 9501, SWOOLE_SOCK_TCP);
$port->on('receive', function($serv, $fd, $reactor_id, $data){
    var_dump($fd, $reactor_id, $data);
    $serv->send($fd, "Swoole: $data");
});
