### ISSUE TITLE
提供 Coroutine\Http\Server 停止 accept 的接口

### ISSUE THREAD

**Issue by bobyang007** [swoole/swoole-src#4889]
大佬您好！
在使用协程版Http服务，想优雅的停机时，调用shutdown后，进行了强制close所有连接的客户端
期望调用shutdown后，只是不再接受新的连接，此时正在处理请求的连接没有断开，待该请求处理完成并返回时，再关闭套节字
建议添加一个方法，调用可以关闭所有现有连接
为shutdown添加一个bool参数，默认为真，表示要强制关闭所有客户。参数为假时，需要使用者自行调用清理官户端的函数

**Comment by matyhtf** [comment]
@bobyang007 感谢你的提议，我们思考一下。

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/pull/4900

会在 5.0.2 版本中支持

**Comment by bobyang007** [comment]
您好
建议考虑对当前连接中的资源进行判断，如果为空闲连接，可以在在shutdown阶段就直接断开
业务可以感知到，并通过负载均衡或故障转移到其他正常的实例上
