### ISSUE TITLE
SIGTERM doesn't kill master process

### ISSUE THREAD

**Issue by raftx24** [swoole/swoole-src#4893]
I'm using laravel with swoole; we have two main processes(master process and manager process). When I send SIGTERM to the manager it will gracefully kill all workers and tasks, and in the end, it will kill itself. But when I send SIGTERM to the `master process`, nothing will happen. How can I check what prevents the `master process` from being finished?

4. What version of Swoole are you using (show your `php --ri swoole`)? 4.8.12

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?     
  `uname -a` => `Linux a216c359d0d2 5.19.0-76051900-generic #202207312230~1663791054~22.04~28340d4 SMP PREEMPT_DYNAMIC Wed S x86_64 GNU/Linux  `
  `php -v`  =>` PHP 8.1.11`
  `GCC` => `gcc version 8.3.0`

**Comment by NathanFreeman** [comment]
I can not reproduce it, it works successfully on my server.
Please check whether the killed process is the master process .
Are you using laravel octane?

**Comment by NathanFreeman** [comment]
It look like that `SIGTERM` was registered by symfony package.

**Comment by NathanFreeman** [comment]
laravel octane starts a timer when master process start.
So master process will wait for the timer to exit if receives a SIGTERM signal.
