### ISSUE TITLE
服务器使用swoole开启websocket 别人使用原始socket服务，没有装swoole，连接上来的时候，返回400 Bad Request，但又提示说连接成功

### ISSUE THREAD

**Issue by YifPhpCoder** [swoole/swoole-src#4895]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

[2022-11-01 14:43:16<.585919> *3965529.6]	NOTICE	request is illegal and it has been discarded, 392 bytes unprocessed
[2022-11-01 14:43:16<.585972> *3965529.6]	NOTICE	ProcessFactory::finish() (ERRNO 1005): session#4 does not exists
[2022-11-01 14:43:16<.585985> *3965529.6]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#4 is closed

服务器使用swoole开启websocket
别人使用原始socket服务，没有装swoole，连接上来的时候，返回400 Bad Request，但又提示说连接成功

2. What did you expect to see?

正常连接

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.5
Built => Sep  1 2022 10:11:58
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2u  20 Dec 2019
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux VM-16-6-centos 5.4.119-19-0009.3 #1 SMP Wed Apr 20 22:27:43 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.1.9 (cli) (built: Sep  1 2022 10:24:13) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC)

**Comment by NathanFreeman** [comment]
是使用php原生的socket去连接swoole的websocket吗？

**Comment by YifPhpCoder** [comment]
已经解决了 ，谢谢，原来是路径问题

> 是使用php原生的socket去连接swoole的websocket吗？
