### ISSUE TITLE
期望 swoole软件包加入debian 软件仓库

### ISSUE THREAD

**Issue by jingjingxyk** [swoole/swoole-src#4896]
## 起因

>  因在大陆一些地区使用 pecl 安装 swoole 太慢了。有时甚至长时间没有速度，或者直接连接超时。

## 尝试过的办法： 
> 1. 使用源包安装 [download swoole source code ](https://www.swoole.com/download)； [swoole release](https://github.com/swoole/swoole-src/releases)；[gitee tags](https://gitee.com/swoole/swoole/tags)（最有效途径)

> 2. pecl 配置代理进行安装 (途径有效)。 
>>>  麻烦在于，使用的时候，还需要配置代理；所处环境不一定有代理服务

>3.  apt  命令 安装 （找不到包，途径不可用）。
>>> brew search php-swoole也是没有的

>4.  直接拉取swoole 容器镜像（途径有效）。
>>>  麻烦在于，拉取容器镜像的速度让人着急。当然了容器配置上代理拉取也很快；

###  使用配置代理进行安装swoole 
> 没代理，就只能使用源码包安装
```bash

pear config-set http_proxy http://127.0.0.1:8015

pecl channel-update https://pecl.php.net/channel.xml

pecl install swoole 
 
pear config-set http_proxy ""


```
## 期望swoole软件包加入debian 软件仓库，能用 apt 命令直接安装 swoole
> 1 因 debian 的下游共享 debian 的软件仓库，意味着ubuntu也可以使用此软件包

> 2  通过 debian 全球镜像库 分发软件

> 3 使用 apt 命令直接安装 
```bash

 apt install php-swoole

```
## 参考过的文档
[Debian 全球镜像站](https://www.debian.org/mirror/list)

[How to join Debian](https://www.debian.org/devel/join/)

[HowToPackageForDebian](https://wiki.debian.org/HowToPackageForDebian)

**Comment by matyhtf** [comment]
建议使用 swoole-cli 

https://www.swoole.com/download
