### ISSUE TITLE
使用腾讯云SDK时遇到curl问题

### ISSUE THREAD

**Issue by YifPhpCoder** [swoole/swoole-src#4903]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

Fatal error: Uncaught TypeError: curl_multi_add_handle(): Argument #2 ($handle) must be of type CurlHandle, Swoole\Curl\Handler given in /Vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:194

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team [team@swoole.com](mailto:team@swoole.com)
Version => 4.8.5
Built => Sep 1 2022 10:11:58
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2u 20 Dec 2019
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

PHP 8.1.9 (cli) (built: Sep 1 2022 10:24:13) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by Yurunsoft** [comment]
请更新到 4.8.12，然后带上参数编译`--enable-swoole-curl`
https://wiki.swoole.com/#/runtime?id=swoole_hook_native_curl

**Comment by matyhtf** [comment]
使用  curl native
