### ISSUE TITLE
mac os 13 m1 安装swoole 失败

### ISSUE THREAD

**Issue by uyson** [swoole/swoole-src#4904]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

安装swoole 失败： 
操作系统： Mac OS 13
php 版本： 8.1.10 (homebrew 安装)
错误提示： Warning: PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /opt/homebrew/lib/php/pecl/20210902/swoole.so (dlopen(/opt/homebrew/lib/php/pecl/20210902/swoole.so, 0x0009): tried: '/opt/homebrew/lib/php/pecl/20210902/swoole.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/php/pecl/20210902/swoole.so' (no such file), '/opt/homebrew/lib/php/pecl/20210902/swoole.so' (no such file)), /opt/homebrew/lib/php/pecl/20210902/swoole.so.so (dlopen(/opt/homebrew/lib/php/pecl/20210902/swoole.so.so, 0x0009): tried: '/opt/homebrew/lib/php/pecl/20210902/swoole.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/php/pecl/20210902/swoole.so.so' (no such file), '/opt/homebrew/lib/php/pecl/20210902/swoole.so.so' (no such file))) in Unknown on line 0

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

Warning: PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /opt/homebrew/lib/php/pecl/20210902/swoole.so (dlopen(/opt/homebrew/lib/php/pecl/20210902/swoole.so, 0x0009): tried: '/opt/homebrew/lib/php/pecl/20210902/swoole.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/php/pecl/20210902/swoole.so' (no such file), '/opt/homebrew/lib/php/pecl/20210902/swoole.so' (no such file)), /opt/homebrew/lib/php/pecl/20210902/swoole.so.so (dlopen(/opt/homebrew/lib/php/pecl/20210902/swoole.so.so, 0x0009): tried: '/opt/homebrew/lib/php/pecl/20210902/swoole.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/php/pecl/20210902/swoole.so.so' (no such file), '/opt/homebrew/lib/php/pecl/20210902/swoole.so.so' (no such file))) in Unknown on line 0
Extension 'swoole' not present.

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
uname -a：
Darwin Alims-MacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64
php -v：
PHP 8.1.10 (cli) (built: Sep  6 2022 16:52:36)
gcc -v：
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by matyhtf** [comment]
这说明扩展目录中不存在`swoole.so`，请检查编译日志，找到`error`信息

**Comment by uyson** [comment]
> /opt/homebrew/lib/php/pecl/20210902/

非常感谢， pecl 安装的时候php.ini 配置改一下就可以了
