### ISSUE TITLE
will client A see the client B`s result be happened on http request?

### ISSUE THREAD

**Issue by bobshipwood** [swoole/swoole-src#4907]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

I want to use swoole`s coroutine to improve my code`s IO. but i wounder will client A see the client B`s result on http request function?
my code below, thanks !!

public function onRequest (\Swoole\Http\Request $request, \Swoole\Http\Response $response)
{
                $result = [];//结果集
		$channel = new Channel(8);
		for ($c = 3; $c--;) {
			Coroutine::create(function () use ($channel, $c) {
				$pdo = new pdo();
				for ($n = 100; $n--;) {
					$pdo->select('SELECT * FROM `user`');
				}
				$channel->push(['B'.$c => 1]);
			});
		}
		for ($c = 5; $c--;) {
			Coroutine::create(function () use ($channel, $c) {
				$redis = new Redis();
				$res = $redis->get('aaa');
				$channel->push(['A'.$c => $res]);
			});
		}
		for ($i = 0; $i < 8; $i++)
		{
			$result += $channel->pop();
		}  
               $response->end($result);
               return;
}
               

2. What did you expect to see?
i am doubtful, will
client A only see the own result by http request?
client B only see the own result by http request?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.12
Built => Nov  6 2022 16:55:55
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux 192.168.0.188 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by NathanFreeman** [comment]
In `SWOOLE_BASE` mode.
```php
<?php
$channel = new Channel(8);
$http = new Swoole\Http\Server('127.0.0.1', 9501);

$http->on('request', function ($request, $response) use ($channel){
});
$http->start();
```

But in the `SWOOLE_PROCESS`,  you can only use redis or swoole table to exchange the result between client A and client B.

**Comment by bobshipwood** [comment]
> In `SWOOLE_BASE` mode.
> 
> ```
> <?php
> $channel = new Channel(8);
> $http = new Swoole\Http\Server('127.0.0.1', 9501);
> 
> $http->on('request', function ($request, $response) use ($channel){
> });
> $http->start();
> ```
> 
> But in the `SWOOLE_PROCESS`, you can only use redis or swoole table to exchange the result between client A and client B.

thanks a lot,  i used SWOOLE_PROCESS mode in my http server. 

because of the Swoole coroutine  specification。if i wrote down this code below,  i wounder that userA will receive userB result...?  

i expected to see that each users request http server and only get their own result.  it means userB will never get the userA result, userA also will never get userB result,。

```
$http = new Swoole\Http\Server('127.0.0.1', 9501);
$http->on('onWorkerStart', function (swoole_server $server, int $worker_id) {
     //$http->pdo = new \pdo;
     //$http->redis  = new \redis;
 });
$http->on('request', function ($request, $response) {
                //echo Swoole\Coroutine::getCid().PHP_EOL;
                $result = [];//结果集
		$channel = new Channel(8);
		for ($c = 3; $c--;) {
			Coroutine::create(function () use ($channel, $c) {
				$pdo = new \pdo();
				$res = $pdo->select('SELECT * FROM `user`');
				$channel->push(['PDO'.$c => $res]);
			});
		}
		for ($c = 5; $c--;) {
			Coroutine::create(function () use ($channel, $c) {
				$redis = new \Redis();
				$res = $redis->get('aaa');
				$channel->push(['REDIS'.$c => $res]);
			});
		}
		for ($i = 0; $i < 8; $i++)
		{
			$result += $channel->pop();
		}
                $response->end($result);
                return;
 });
 $http->start();

**Comment by NathanFreeman** [comment]
In your code, client A will not receive client B result

**Comment by bobshipwood** [comment]
> In your code, client A will not receive client B result

ths a lot!!  so cute a girl!!!
