### ISSUE TITLE
Getting Warnings related to HTTP2 Configurations of Swoole Server

### ISSUE THREAD

**Issue by fakharksa** [swoole/swoole-src#4910]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

I just moved from OpenSwoole version 4.11.1 to Swoole (compiled using master branch) and ran same code that i was running with OpenSwoole. With Swoole, i get some Warnings related to HTTP2 Configurations of Swoole Server, which i never got on OpenSwoole.
(Warnings are specified in answer of question 3 below)

**Compiled Swoole with commands as below:**
```
sudo mkdir -m777 /source_codes && \
cd /source_codes && git clone https://github.com/swoole/swoole-src.git && \
cd swoole-src && \
git checkout master && \
phpize8.1 clean && \
phpize8.1 && \
./configure --enable-openssl \
        --enable-mysqlnd \
        --enable-sockets \
        --enable-swoole-curl \
        --enable-swoole-pgsql \
        --enable-debug \
        --enable-debug-log \
        --enable-trace-log \
        --enable-thread-context \
        --enable-cares \
        --with-php-config=/usr/bin/php-config8.1 && \
sudo make && sudo make install
```

2. What did you expect to see?

I expected that same code that works fine with OpenSwoole will also work with Swoole without warnings.

3. What did you see instead?

```
PHP Warning:  unsupported option [http2_header_table_size] in @swoole-src/library/core/Server/Helper.php on line 200
#0 [internal function]: Swoole\Server\Helper::checkOptions()
#1 [internal function]: Swoole\Server\Port->set()
#2 /var/www/html/swoole-prac/test_pgsql.php(32): Swoole\Server->set()

PHP Warning:  unsupported option [http2_initial_window_size] in @swoole-src/library/core/Server/Helper.php on line 200
#0 [internal function]: Swoole\Server\Helper::checkOptions()
#1 [internal function]: Swoole\Server\Port->set()
#2 /var/www/html/swoole-prac/test_pgsql.php(32): Swoole\Server->set()

PHP Warning:  unsupported option [http2_max_concurrent_streams] in @swoole-src/library/core/Server/Helper.php on line 200
#0 [internal function]: Swoole\Server\Helper::checkOptions()
#1 [internal function]: Swoole\Server\Port->set()
#2 /var/www/html/swoole-prac/test_pgsql.php(32): Swoole\Server->set()

PHP Warning:  unsupported option [http2_max_frame_size] in @swoole-src/library/core/Server/Helper.php on line 200
#0 [internal function]: Swoole\Server\Helper::checkOptions()
#1 [internal function]: Swoole\Server\Port->set()
#2 /var/www/html/swoole-prac/test_pgsql.php(32): Swoole\Server->set()

PHP Warning:  unsupported option [http2_max_header_list_size] in @swoole-src/library/core/Server/Helper.php on line 200
#0 [internal function]: Swoole\Server\Helper::checkOptions()
#1 [internal function]: Swoole\Server\Port->set()
#2 /var/www/html/swoole-prac/test_pgsql.php(32): Swoole\Server->set()
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.1
Built => Nov 18 2022 19:59:23
coroutine => enabled with thread context
debug => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.0.2 15 Mar 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
c-ares => 1.18.1
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled
coroutine_postgresql => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**uname -a:**
Linux fakhar-HP-Laptop 5.17.5-76051705-generic #202204271406~1651504840~20.04~63e51bd-Ubuntu SMP PREEMPT Wed Ma x86_64 x86_64 x86_64 GNU/Linux

**php -v:**

PHP 8.1.12 (cli) (built: Oct 28 2022 17:39:57) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
    with Zend Ogcc -vPcache v8.1.12, Copyright (c), by Zend Technologies

**gcc -v:**

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)

**Comment by NathanFreeman** [comment]
Swoole does not have these settings.
These settings  are automatically initialized by swoole.
```c++
static sw_inline void init_settings(Settings *settings) {
    settings->header_table_size = SW_HTTP2_DEFAULT_HEADER_TABLE_SIZE;
    settings->window_size = SW_HTTP2_DEFAULT_WINDOW_SIZE;
    settings->max_concurrent_streams = SW_HTTP2_MAX_MAX_CONCURRENT_STREAMS;
    settings->max_frame_size = SW_HTTP2_MAX_MAX_FRAME_SIZE;
    settings->max_header_list_size = SW_HTTP2_DEFAULT_MAX_HEADER_LIST_SIZE;
}
```

**Comment by fakharksa** [comment]
> Swoole does not have these settings. These settings are automatically initialized by swoole.
> 
> ```c++
> static sw_inline void init_settings(Settings *settings) {
>     settings->header_table_size = SW_HTTP2_DEFAULT_HEADER_TABLE_SIZE;
>     settings->window_size = SW_HTTP2_DEFAULT_WINDOW_SIZE;
>     settings->max_concurrent_streams = SW_HTTP2_MAX_MAX_CONCURRENT_STREAMS;
>     settings->max_frame_size = SW_HTTP2_MAX_MAX_FRAME_SIZE;
>     settings->max_header_list_size = SW_HTTP2_DEFAULT_MAX_HEADER_LIST_SIZE;
> }
> ```

Thanks for the prompt response, this is very important information that (i think) must be reflected through Swoole Documentation, too (if possible and necessary). Thank you.

**Comment by matyhtf** [comment]
Supported. 

## code example

```php
Co::set([
    'http2_header_table_size' => 2048,
    'http2_enable_push' => false,
    'http2_max_concurrent_streams' => 128,
    'http2_init_window_size' => 2 ** 24,
    'http2_max_frame_size' => 65536,
    'http2_max_header_list_size' => 2 ** 24,
]);
```
