### ISSUE TITLE
fetch and fetchAll() on Swoole\Coroutine\postgreSQL's Connection object are not working

### ISSUE THREAD

**Issue by fakharksa** [swoole/swoole-src#4911]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

From within Swoole HTTP Server (inside onRequest event's callback), i do below:
```
$connection = new Swoole\Coroutine\PostgreSQL();
$ret = $connection->connect('host=127.0.0.1;port=5432;dbname=swooledb;user=postgres;password=passwd123');
if ($ret === false) {
  throw new \RuntimeException(sprintf('Failed to connect PostgreSQL server: %s', $connection->error));
}
$stat = $connection->query('SELECT * FROM users;');
$arr = $connection->fetchAll($stat);
// $arr = $connection->fetch($stat);
$json = [
    'status'  => $arr,
];
$response->header('Content-Type', 'application/json');
$response->end(json_encode($json));
```

Also, tried code below:

```
co\run(function() {
    $connection = new Swoole\Coroutine\PostgreSQL();
    $ret = $connection->connect('host=127.0.0.1;port=5432;dbname=swooledb;user=postgres;password=passwd123');
    if ($ret === false) {
        throw new \RuntimeException(sprintf('Failed to connect PostgreSQL server: %s', $connection->error));
    }
    $stat = $connection->query('SELECT * FROM users;');
    $arr = $connection->fetchAll($stat);
// $arr = $connection->fetch($stat);
    $json = [
        'status'  => $arr,
    ];
//$response->header('Content-Type', 'application/json');
    var_dump(json_encode($json));
});
```

The code works fine when i switch to OpenSwoole, instead of Swoole.

2. What did you expect to see?

Databe result / row with user record

3. What did you see instead?
`PHP Fatal error:  Uncaught Error: Call to undefined method Swoole\Coroutine\PostgreSQL::fetchAll()`

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.1
Built => Nov 18 2022 19:59:23
coroutine => enabled with thread context
debug => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.0.2 15 Mar 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
c-ares => 1.18.1
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled
coroutine_postgresql => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**uname -a:**
Linux fakhar-HP-Laptop 5.17.5-76051705-generic #202204271406165150484020.04~63e51bd-Ubuntu SMP PREEMPT Wed Ma x86_64 x86_64 x86_64 GNU/Linux

**php -v:**

PHP 8.1.12 (cli) (built: Oct 28 2022 17:39:57) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
with Zend Ogcc -vPcache v8.1.12, Copyright (c), by Zend Technologies

**gcc -v:**

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu122.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu122.04)

**Comment by NathanFreeman** [comment]
Swoole\Coroutine\PostgreSQL::fetchAll() is a new method to Swoole5.

**Comment by NathanFreeman** [comment]
Did you add `--enable-swoole-pgsql` option when executing `configure` command?

**Comment by fakharksa** [comment]
> Did you add `--enable-swoole-pgsql` option when executing `configure` command?

yes, as mentioned in comment of my (resolved) issue / ticket# 4908 [comment here](https://github.com/swoole/swoole-src/issues/4908#issuecomment-1320186277) and also in Point-1 of the description of my ticket / issue# 4901. 
Also, you can see `coroutine_postgresql => enabled` in the output of `php --ri swoole`.

**Comment by NathanFreeman** [comment]
```php
$connection = new Swoole\Coroutine\PostgreSQL();
$ret = $connection->connect('host=127.0.0.1;port=5432;dbname=swooledb;user=postgres;password=passwd123');
if ($ret === false) {
  throw new \RuntimeException(sprintf('Failed to connect PostgreSQL server: %s', $connection->error));
}
$stat = $connection->query('SELECT * FROM users;');
$arr = $stat->fetchAll($stat);
$json = [
    'status'  => $arr,
];
$response->header('Content-Type', 'application/json');
$response->end(json_encode($json));
```


```php
co\run(function() {
    $connection = new Swoole\Coroutine\PostgreSQL();
    $ret = $connection->connect('host=127.0.0.1;port=5432;dbname=swooledb;user=postgres;password=passwd123');
    if ($ret === false) {
        throw new \RuntimeException(sprintf('Failed to connect PostgreSQL server: %s', $connection->error));
    }
    $stat = $connection->query('SELECT * FROM users;');
    $arr = $stat->fetchAll($stat);
    $json = [
        'status'  => $arr,
    ];
    var_dump(json_encode($json));
});
```

**Comment by fakharksa** [comment]
@NathanFreeman 

I had already tried with below before reporting this issue, but that also did not work, and gave same Fatal Error as reported in this issue.

```
co\run (function() {
... Your code here ...
 var_dump(json_encode($json));
}); 
```

**Comment by NathanFreeman** [comment]
Please show me `$connection->error` after executing `$stat = $connection->query('SELECT * FROM users;');`.
Mayby this table `users` does not exist in the `swooledb` database.

**Comment by fakharksa** [comment]
> Please show me `$connection->error` after executing `$stat = $connection->query('SELECT * FROM users;');`. Mayby this table `users` does not exist in the `swooledb` database.

@NathanFreeman 
1. I confirm that the table ' users' exists in "swooledb" database, and also the same code works fine when i switch from "Swoole" to "OpenSwoole" and with OpenSwoole it shows the record of user from swooledb database (i have already mentioned this fact in the very first description on this issue). 

2. Regarding $connection->error, if there was an error in connection then following code would have executed which is not the case here.

```
    if ($ret === false) {
        throw new \RuntimeException(sprintf('Failed to connect PostgreSQL server: %s', $connection->error));
    }
```

**Comment by NathanFreeman** [comment]
I made a pr about it https://github.com/swoole/swoole-src/pull/4912.
You can compile swoole with it to see the detailed error.

**Comment by Yurunsoft** [comment]
The `Swoole\Coroutine\PostgreSQL` has been refactored in Swoole 5.0.

The new way of writing is now more similar to PDO.

Documentation: https://wiki.swoole.com/#/coroutine_client/postgresql
