### ISSUE TITLE
User Warning: swoole_curl_setopt(): CURLOPT_HTTP_VERSION[3] is not supported 

### ISSUE THREAD

**Issue by mrAndersen** [swoole/swoole-src#4920]
Doing curl requests inside swoole workers, getting this

```User Warning: swoole_curl_setopt(): CURLOPT_HTTP_VERSION[3] is not supported in @swoole-src/library/core/Curl/Handler.php:573```

Requested address is HTTPS server. How can i solve this? hook_flags set to SWOOLE_HOOK_ALL

**Comment by deminy** [comment]
There are two types of runtime hooks for curl:

* _SWOOLE_HOOK_NATIVE_CURL_: The new one. It's available when Swoole is installed with option "--enable-swoole-curl" included.
* _SWOOLE_HOOK_CURL_: The old one.

It seems that you were using the old one (runtime hook SWOOLE_HOOK_CURL), which has various limitations. Please switch over using runtime hook SWOOLE_HOOK_NATIVE_CURL instead and try again. In many cases, you can make the switch by reinstalling Swoole with  option "--enable-swoole-curl" included, without making any changes in your PHP script.

[This example](https://github.com/deminy/swoole-by-examples/blob/master/examples/hooks/native-curl.php) shows how the runtime hook _SWOOLE_HOOK_NATIVE_CURL_ works. Hope it helps.

**Comment by mrAndersen** [comment]
@deminy Thx for response, i tried exactly what you mentioned, and result is like in this thread https://github.com/swoole/swoole-src/issues/4827

Moreover switching to guzzle resolves the problem, so i think this is not directly a curl\swoole problem, but symfony's http-client used with swoole problem

**Comment by matyhtf** [comment]
@mrAndersen Can you provide a phpt test script that can reproduce the symfony http-client issue

Reference https://github.com/swoole/swoole-src/blob/master/tests/swoole_curl/symfony.phpt
