### ISSUE TITLE
onWorkerExit evnt not work

### ISSUE THREAD

**Issue by 117311730** [swoole/swoole-src#4931]
<pre><code>
$serv = new Swoole\Http\Server("127.0.0.1", 9505);
$serv->set([
    'reload_async' => true,
    'enable_coroutine' => true,
    'worker_num' => 1,
    'max_request' => 1,
    'max_wait_time' => 30,
    'log_level' => SWOOLE_LOG_TRACE,
    'trace_flags' => SWOOLE_TRACE_ALL
]);
//$serv->on('receive', function (Swoole\Server $serv, $fd, $reactor_id, $data) {
//
//    echo "[#" . $serv->worker_id . "]\tClient[$fd] receive data: $data\n";
//
//    Swoole\Timer::tick(5000, function () {
//        echo 'tick';
//    });
//});
$serv->on('request', function ($request, $response) {
    $response->end('Hi');
});
$serv->on('workerStart', function($server, $workerId) {
    $redis = new Redis();
    $redis->connect('127.0.0.1', 6379);
    $server->redis = $redis;
    printf('Worker %d start.' . PHP_EOL, $workerId);
});
$serv->on('workerExit', function ($server, int $workerId) {
    printf('Worker %d exit.' . PHP_EOL, $workerId);
});
$serv->on('workerStop', function ($server, int $workerId) {
    printf('Worker %d stop.' . PHP_EOL, $workerId);
});

$serv->start();
</code></pre>

### onWorkerExit evnt not work,

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.12
Built => Dec 10 2022 02:07:55
coroutine => enabled with boost asm context
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.0l  10 Sep 2019
dtls => enabled
http2 => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.8
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

PHP 8.0.24 (cli) (built: Oct 13 2022 17:42:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.24, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.24, Copyright (c), by Zend Technologies

**Comment by matyhtf** [comment]
If there is no event listening in the event loop of the process and it can end directly, onWorkerExit will not be `executed`, only the `onWorkerStop` will be executed
