### ISSUE TITLE
Block execution in coroutine context

### ISSUE THREAD

**Issue by mrAndersen** [swoole/swoole-src#4933]
Hello! I have brief question. How i can block execution inside coroutine context in swoole? For example inside onRequest callback when enable_coroutine => on. It seems like sleep, usleep doesn't block at all...

**Comment by leocavalcante** [comment]
You mean you want to block the entire process instead of just the coroutine? Because `Coroutine::sleep()` should work just fine for the current coroutine/request.

How are you trying this?

**Comment by mrAndersen** [comment]
@leocavalcante yeah i want to block whole Process, also ```Coroutine::sleep()``` is same as just ```usleep()``` correct?

**Comment by leocavalcante** [comment]
I see. So, try:
```php
$server->set([
    'hook_flags' => SWOOLE_HOOK_ALL ^ SWOOLE_HOOK_SLEEP,
]);
```
It will active all hooks, except for the Sleep hook, then try regular `sleep()`.

**Comment by mrAndersen** [comment]
@leocavalcante yeah, i am aware of that method, but what if i actually want to use hooked sleep in other places? Can i somehow override that logic having SWOOLE_HOOK_SLEEP enabled ?

**Comment by leocavalcante** [comment]
You may use `Coroutine::sleep()` to have only the coroutine blocked and `sleep()` to have the entire process blocked.
The problem will be with third-party/vendor code that you don't have the control of the inner sleeps.

**Comment by deminy** [comment]
I created two examples about how to block coroutines/processes in Swoole. Please note there are different approaches available. e.g., to block a whole process, we could use method \Swoole\Atomic::wait() and method \Swoole\Atomic::wakeup() together in a multiprocessing environment.

* [block a coroutine](https://github.com/deminy/swoole-by-examples/blob/master/examples/io/block-a-coroutine.php)
* [block a whole process](https://github.com/deminy/swoole-by-examples/blob/master/examples/io/block-a-process.php)

Please feel free to let me know for any issues or if there is a better approach. Thanks
