### ISSUE TITLE
high latency after loop

### ISSUE THREAD

**Issue by 0utc0ntr0l2021** [swoole/swoole-src#4935]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
download content make high ms latency after loop
![1](https://user-images.githubusercontent.com/95451548/209042907-20856fc7-afe4-4523-99db-6ac9af70db8d.jpg)
![2](https://user-images.githubusercontent.com/95451548/209042909-087d99cf-bb93-4777-9340-0f204709a95e.jpg)

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by NathanFreeman** [comment]
Could you please provide a simple script for reproducing the error?

**Comment by matyhtf** [comment]
CPU waiting or io blocking may cause eventloop to pause, affecting the processing speed of network io.

It is recommended to use SWOOLE_PROCESS mode
