### ISSUE TITLE
Memory related question.

### ISSUE THREAD

**Issue by mrAndersen** [swoole/swoole-src#4938]
Good day! I have another, maybe simple question, but i don't fully understand how swoole manages memory stuff. I have Symfony application, and inside that Symfony application i have ```Command``` which is creating ```Swoole\Server``` class to create, setup and start the server, blocking the execution flow, so when the command exits, the server exits also, with all child procceses, pcntl is not used in this application.

I am using N http workers, and also i am attaching J additional Processes to the server with ```$server->addProcess``` calls, this processes has basically ```while(true){sleep(N); do-some-work}``` logic.

However if i am doing ```var_dump(1)``` inside any of my Symfony service classes ```__construct``` method, I am getting ```1``` exactly once. Which means that classes are loaded and Kernel is created only once. But if i am trying to read any kind of statefull data from ```$this``` within one process-worker, that was written in another process worker, i am getting nothing, only available to the same process, which is indeed logical, but does not tie good with ```1``` called once, how does this work under the hood? Why is once instanced kernel having different states for different processes?

I was sure that memory and class states are working per-process\per-http-worker and not per-application, however recently i was using Guzzle client (swoole built with  --enable-hook-curl and server is started in BASE mode with HOOK_ALL flags) which was tied to ```$this``` inside http client service, which was instanced and created once according to ```var_dump``` test. And i've got very unusual results, when process-worker-1 got http response which should have been a response from process-worker-2, how this could be? Is this some kind of bug, or i am not getting something here?

Also the only reason shared memory ```Table``` exists in my view is that class states are not shared across all application, and I am using ```Table``` a lot also to sync data between http workers and process workers. So where should i look up to understand more about that Guzzle issue, also when i fixed the Client to be created for each request, issue of course resolved, however it does not explain the bug...

**Comment by matyhtf** [comment]
The memory between different processes is isolated, for example, the global array in process 1 will not affect another process. The class is loaded once probably because it is executed before the fork child process.
If you want to share between processes, you can use `Swoole\Table`.

There is nothing special about swoole, you can read the documentation on linux multi-process.
