### ISSUE TITLE
运行process时，出现 2 ENOENT +No such file or directory  错误

### ISSUE THREAD

**Issue by zhaoxiong123** [swoole/swoole-src#494]
![image](https://cloud.githubusercontent.com/assets/3273395/12541275/dbe79d86-c34f-11e5-86e0-50a9364ed28f.png)

运行这段代码时出现的，求助啊，偶尔一次正常

**Comment by matyhtf** [comment]
请贴一份可以复现的demo文件，或者 贴出详细的 strace 调试信息。

**Comment by matyhtf** [comment]
无法获得更多信息。
