### ISSUE TITLE
m1 已经正常编译 swoole-src-5.0.1 swoole.so 也生成了，也加到了php.ini 里，但是 php —ri swoole 报错

### ISSUE THREAD

**Issue by zsboss** [swoole/swoole-src#4951]
Please answer these questions before submitting your issue.

4. What version of Swoole are you using (show your `php --ri swoole`)?
Warning: PHP Startup: Unable to load dynamic library 'swoole' (tried: /Applications/MAMP/bin/php/php8.0.0/lib/php/extensions/no-debug-non-zts-20200930/swoole (dlopen(/Applications/MAMP/bin/php/php8.0.0/lib/php/extensions/no-debug-non-zts-20200930/swoole, 0x0009): tried: '/Applications/MAMP/bin/php/php8.0.0/lib/php/extensions/no-debug-non-zts-20200930/swoole' (no such file)), /Applications/MAMP/bin/php/php8.0.0/lib/php/extensions/no-debug-non-zts-20200930/swoole.so (dlopen(/Applications/MAMP/bin/php/php8.0.0/lib/php/extensions/no-debug-non-zts-20200930/swoole.so, 0x0009): tried: '/Applications/MAMP/bin/php/php8.0.0/lib/php/extensions/no-debug-non-zts-20200930/swoole.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')))) in Unknown on line 0

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
php -v
PHP 8.0.0 (cli) (built: Nov 30 2020 13:50:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
gcc -v
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin21.5.0
Thread model: posix

**Comment by matyhtf** [comment]
你的 php 是 x86-64 架构的，swoole 也需要编译为 x86-64
