### ISSUE TITLE
websocket server 内存消耗

### ISSUE THREAD

**Issue by suconghou** [swoole/swoole-src#4952]
使用官网下载的 swoole-cli 和 ws 的 例子

```php
<?php

$server = new Swoole\Websocket\Server('127.0.0.1', 9502, SWOOLE_BASE);

$server->on('start', function ($server) {
    echo "Websocket Server is started at ws://127.0.0.1:9502\n";
});

$server->on('open', function ($server, $req) {
    echo "connection open: {$req->fd}\n";
});

$server->on('message', function ($server, $frame) {
    echo "received message: {$frame->data}\n";
    $server->push($frame->fd, json_encode(['hello', 'world']));
});

$server->on('close', function ($server, $fd) {
    echo "connection close: {$fd}\n";
});

$server->start();

```

使用单进程模式

`swoole-cli ws.php` 开启server

另编写ws 客户端， 实测 server 在链接 1800+ 的链接后， 应128M 内存限制而崩溃

是否合理？ 太占内存了

**Comment by NathanFreeman** [comment]
用的是x86还是aarch64版本的swoole-cli？

**Comment by suconghou** [comment]
测试 swoole-cli-v5.0.1-linux-x64 和 swoole-cli-v4.8.12-linux-x64  均是如此

**Comment by NathanFreeman** [comment]
如果你1800+的连接都没有断开的话，维持的这些连接的也是需要内存的。

**Comment by suconghou** [comment]
按照这个计算2w的链接，就需要1.5G内存了，这个占用是很大的了， 无论对比go还是node都是非常差的数据

**Comment by NathanFreeman** [comment]
你可以写一个php的脚本去压测它。
我的服务器是2核4G的，memory_limit为980M，可以维持14000+连接。

**Comment by matyhtf** [comment]
你可以将 php 栈、c 栈尺寸调小，减少内存占用

**Comment by suconghou** [comment]
请问有什么配置可以调吗，还是需要修改代码，重新编译

**Comment by suconghou** [comment]
配置 `ulimit -s 64` 和 `Swoole\Coroutine::set(['stack_size' => 64*1024, 'c_stack_size' => 64*1024]);`

并没有效果

@matyhtf

**Comment by matyhtf** [comment]
只维持长连接，还是存在消息收发？

**Comment by suconghou** [comment]
每个链接都 有收，有发

**Comment by matyhtf** [comment]
64k 乘以 10000 等于 640M ，大约1万个连接需要600M内存，2万个需要1.2G内存。这仅仅是创建协程的 PHP 栈内存开销，实际上还有很多地方需要内存。

维持连接的开销并不高，但是存在数据收发的活跃连接是需要占用比较多内存的。
