### ISSUE TITLE
在replit上写了一个实时聊天系统，算不算一个案例。

### ISSUE THREAD

**Issue by findnr** [swoole/swoole-src#4955]
地址：https://msghtml.cym504875043.repl.co/
是基于swoole-cli 5.0.1开发的
这是首页：
![image](https://user-images.githubusercontent.com/3909023/212531705-ce6e9f1e-21a3-46ec-90b1-16bc5f7df711.png)
然后登录：
![image](https://user-images.githubusercontent.com/3909023/212531776-6914f0d4-f965-478b-a12d-dd193a50fa8b.png)
然后就可以选择聊天的人进行聊天，都是一对一的。
![image](https://user-images.githubusercontent.com/3909023/212531842-dbca42bf-f755-423c-97cd-7e0ba4b3fb85.png)
然后对方就收到了：
![image](https://user-images.githubusercontent.com/3909023/212531867-b7e9d530-f0fb-47b7-9464-3055f6b6ad19.png)

**Comment by matyhtf** [comment]
https://github.com/swoole/awesome-swoole
可以添加到这里
