### ISSUE TITLE
Bad arginfo / reflection 

### ISSUE THREAD

**Issue by remicollet** [swoole/swoole-src#4967]
in `php --re swoole` output

```
    Function [ <internal:swoole> function swoole_timer_list ] {

      - Parameters [0] {
      }
      - Return [ <C9>^K ]
    }

```

Same affects openswoole, see https://github.com/openswoole/swoole-src/pull/284 for the fix.

**Comment by NathanFreeman** [comment]
Fixed via https://github.com/swoole/swoole-src/pull/4947

**Comment by remicollet** [comment]
Indeed, but (seems related to this change), while changelog states "no backwards incompatible changes" I notice lot of functions have disappeared (which is obviously a BC break)
* swoole_native_socket_*

**Comment by remicollet** [comment]
See reflection diff: https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-swoole5.git/diff/REFLECTION?id=2f5e4a607f906715035f8dba823b304f530e0ba9

**Comment by NathanFreeman** [comment]
It's not a BC break.
`swoole_native_socket_*` were arginfo and were designed to hook `ext-sockets` and we optimize it now.
