### ISSUE TITLE
PostgreSQL does not work with `?` param-notations

### ISSUE THREAD

**Issue by efureev** [swoole/swoole-src#4968]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
```
$dsn='';
$connection = \Swoole\Coroutine\PostgreSQL()
$connection->connect($dsn);

$sql = 'SELECT a.id FROM attributes a WHERE a.id = ?';
$stmt = $connection->prepare($sql);
```
As a result:
```
$stmt === false;
$connection: 

Swoole\Coroutine\PostgreSQL {
  +error: """
    ERROR:  syntax error at end of input
    LINE 1: SELECT a.id FROM attributes a WHERE a.id = ?
    """
  +errCode: 0
  +resultStatus: 7
  +resultDiag: array:17 [
    "severity" => "ERROR"
    "sqlstate" => "42601"
    "message_primary" => "syntax error at end of input"
    "message_detail" => null
    "message_hint" => null
    "statement_position" => "45"
    "internal_position" => null
    "internal_query" => null
    "content" => null
    "schema_name" => null
    "table_name" => null
    "column_name" => null
    "datatype_name" => null
    "constraint_name" => null
    "source_file" => "scan.l"
    "source_line" => "1180"
    "source_function" => "scanner_yyerror"
  ]
  +notices: null
```

2. What did you expect to see?

I expect that code will be execute equal to:
```
$sql =  'SELECT a.id FROM attributes a WHERE a.id = $1';

$stmt === Swoole\Coroutine\PostgreSQLStatement(...);
$connection->error===null;
```

3. What version of Swoole are you using (show your `php --ri swoole`)?
v5.0.1

4. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Docker: Alpine, Ubuntu

[@f32e22c79187] /var/www/app #  >uname -a 
Linux f32e22c79187 5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022 x86_64 Linux

[@f32e22c79187] /var/www/app #  >php -v
PHP 8.2.0 (cli) (built: Dec  8 2022 20:14:26) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.0, Copyright (c) Zend Technologies
    with Yasd v0.3.9-alpha, Our Copyright, by codinghuang

[@f32e22c79187] /var/www/app #  >gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/11.2.1/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-11.2.1_git20220219/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 11.2.1_git20220219' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,d,objc,go,fortran,ada,jit --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --enable-host-shared --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.1 20220219 (Alpine 11.2.1_git20220219) 
[@f32e22c79187] /var/www/app #  🎄 >

**Comment by NathanFreeman** [comment]
pg driver do not support `?` placeholder.
https://www.postgresql.org/docs/15/sql-prepare.html

**Comment by twose** [comment]
Since PDO is an abstract implementation of multiple database drivers, PDO provides additional EMULATE_PREPARES support, but Swoole does not, and there is no plan to provide such a feature.

**Comment by efureev** [comment]
I think so... Thx you for your confirmation
