### ISSUE TITLE
HTML Content-Type是multipart/form-data; boundary时解析不了checkbox提交的数据

### ISSUE THREAD

**Issue by viile** [swoole/swoole-src#497]
修改swoole_http_server.c multipart_body_on_data_end函数
 sw_add_assoc_stringl_ex(zpost, client->current_form_data_name, client->current_form_data_name_len + 1,  swoole_http_form_data_buffer->str, swoole_http_form_data_buffer->length, 1);
改为
        char *name = client->current_form_data_name;
        int len = client->current_form_data_name_len;

        if ((name[len-1] == ']') && (name[len-2] == '['))
        {
            zval *array_value;

            if (sw_zend_hash_find(Z_ARRVAL_P(zpost), name, len + 1, (void **) &array_value) == FAILURE)
            {
                SW_MAKE_STD_ZVAL(array_value);
                array_init(array_value);

                add_assoc_zval(zpost, name, array_value);
                add_next_index_string(array_value, swoole_http_form_data_buffer->str);
            }
            else
            {
                add_next_index_string(array_value, swoole_http_form_data_buffer->str);
            }
        }
        else
        {
            sw_add_assoc_stringl_ex(zpost, client->current_form_data_name, client->current_form_data_name_len + 1,
                swoole_http_form_data_buffer->str, swoole_http_form_data_buffer->length, 1);
        }

**Comment by matyhtf** [comment]
感谢您的贡献，可以`fork`一下`swoole-src`，然后发起`pull request`

**Comment by viile** [comment]
已经pull request了
