### ISSUE TITLE
post可否支持直接读取文件发送或者文件上传无需file参数

### ISSUE THREAD

**Issue by amuluowin** [swoole/swoole-src#4970]
有些时候`post`的`body`比较大可能存放在一个文件里面，希望可以直接底层发送，无需读取到程序内部，占用内存。
例如：clickhouse的csv导入，与上传文件的格式不同，直接是把csv内容当成body来解析，不会解析`file`这些`key`等信息

**Comment by amuluowin** [comment]
> 你的意思是将请求参数放在文件里面，然后直接通过post请求直接发送到服务端，然后服务端发现这是特殊的请求，直接不做处理吗？

我的意思是指swoole的http客户端在发送请求的时候可以读取一个文件作为body从底层发送，而无需把文件读进程序。不是指swoole的服务端的处理。

**Comment by NathanFreeman** [comment]
swoole目前没办法做到这样。
你可以把这个当做一个大文件发送，采用断点续传或者swoole的http客户端的addFile方法。
https://wiki.swoole.com/#/coroutine_client/http_client?id=addfile

**Comment by amuluowin** [comment]
文件发送必填`name`参数，发送出去的body会有变化，不符合目标要求。

**Comment by he426100** [comment]
可以用分片上传的思路解决这个问题，分片后当字符串发，服务端拿原始body再合并
