### ISSUE TITLE
项目升级到 4.8.12 后启用 SWOOLE_HOOK_SOCKETS 出现了segmentation fault错误

### ISSUE THREAD

**Issue by ihekui** [swoole/swoole-src#4972]
Please answer these questions before submitting your issue.

### 1. What did you do? If possible, provide a simple script for reproducing the error.

错误信息：

> xiongxu@HXMBP qcq-api % php(16681,0x16b70f000) malloc: Region cookie corrupted for region 0x118000000 (value is 1)[0x118007ffc]
php(16752,0x16b683000) malloc: Region cookie corrupted for region 0x130000000 (value is 0)[0x130007ffc]
php(16752,0x16b683000) malloc: *** set a breakpoint in malloc_error_break to debug
php(16761,0x16b9cb000) malloc: Region cookie corrupted for region 0x118000000 (value is 0)[0x118007ffc]
php(16855,0x16b70f000) malloc: Corruption of free object 0x107f04130: msizes 16816/0 disagree
php(16855,0x16b70f000) malloc: *** set a breakpoint in malloc_error_break to debug
php(17120,0x16b93f000) malloc: Region cookie corrupted for region 0x140000000 (value is 34ef267b)[0x140007ffc]
php(17120,0x16b93f000) malloc: *** set a breakpoint in malloc_error_break to debug
php(17139,0x16b8b3000) malloc: Region cookie corrupted for region 0x148000000 (value is 34ef267b)[0x148007ffc]
php(17139,0x16b8b3000) malloc: *** set a breakpoint in malloc_error_break to debug
php(17453,0x16b70f000) malloc: Region cookie corrupted for region 0x107f00000 (value is 34ef267b)[0x107f0407c]
php(17453,0x16b70f000) malloc: *** set a breakpoint in malloc_error_break to debug
php(17924,0x16b827000) malloc: Corruption of free object 0x107f04080: msizes 5/0 disagree
php(18446,0x16b70f000) malloc: Region cookie corrupted for region 0x118000000 (value is 1)[0x118007ffc]
xiongxu@HXMBP qcq-api % php(19124,0x16b9cb000) malloc: Region cookie corrupted for region 0x107e00000 (value is 1)[0x107e0407c]
php(22030,0x16b93f000) malloc: Corruption of free object 0x107f04080: msizes 5/0 disagree
php(22030,0x16b93f000) malloc: *** set a breakpoint in malloc_error_break to debug
xiongxu@HXMBP qcq-api % php(33668,0x16b827000) malloc: Corruption of free object 0x107f04150: msizes 4/0 disagree
php(34366,0x16b93f000) malloc: Region cookie corrupted for region 0x107e00000 (value is 1)[0x107e0407c]
php(34366,0x16b93f000) malloc: *** set a breakpoint in malloc_error_break to debug

log_file记录的错误日志：

> [2023-02-08 14:29:11 $64293.0]	WARNING	Server::check_worker_exit_status(): worker(pid=64296, id=0) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.8.12, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

### 3. What did you expect to see?

修复这个问题

### 5. What version of Swoole are you using (show your `php --ri swoole`)?

> [xiongxu@HXMBP swoole-src-4.8.12 % php --ri swoole 
swoole
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.12
Built => Feb  8 2023 14:21:30
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 3.0.7 1 Nov 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
async_redis => enabled
Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144

6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

> xiongxu@HXMBP swoole-src-4.8.12 % uname -a 
Darwin HXMBP 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112 arm64

> xiongxu@HXMBP swoole-src-4.8.12 % php -v 
PHP 8.1.14 (cli) (built: Jan 15 2023 19:11:08) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.14, Copyright (c) Zend Technologies

> xiongxu@HXMBP swoole-src-4.8.12 % gcc -v 
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by matyhtf** [comment]
如何重现此问题，执行什么样的代码出现？另外编译时是否执行了 make clean ？

**Comment by ihekui** [comment]
> 项目一直在swoole开发与运行并跑了2年多了，没有新增什么新的代码，通过埋点调试是执行到swoole启动（server->start()）时就出现这个问题。另外终端中还输出了以下信息：

> xiongxu@HXMBP qcq-api % php(16681,0x16b70f000) malloc: Region cookie corrupted for region 0x118000000 (value is 1)[0x118007ffc]
php(16752,0x16b683000) malloc: Region cookie corrupted for region 0x130000000 (value is 0)[0x130007ffc]
php(16752,0x16b683000) malloc: *** set a breakpoint in malloc_error_break to debug
php(16761,0x16b9cb000) malloc: Region cookie corrupted for region 0x118000000 (value is 0)[0x118007ffc]
php(16855,0x16b70f000) malloc: Corruption of free object 0x107f04130: msizes 16816/0 disagree
php(16855,0x16b70f000) malloc: *** set a breakpoint in malloc_error_break to debug
php(17120,0x16b93f000) malloc: Region cookie corrupted for region 0x140000000 (value is 34ef267b)[0x140007ffc]
php(17120,0x16b93f000) malloc: *** set a breakpoint in malloc_error_break to debug
php(17139,0x16b8b3000) malloc: Region cookie corrupted for region 0x148000000 (value is 34ef267b)[0x148007ffc]
php(17139,0x16b8b3000) malloc: *** set a breakpoint in malloc_error_break to debug
php(17453,0x16b70f000) malloc: Region cookie corrupted for region 0x107f00000 (value is 34ef267b)[0x107f0407c]
php(17453,0x16b70f000) malloc: *** set a breakpoint in malloc_error_break to debug
php(17924,0x16b827000) malloc: Corruption of free object 0x107f04080: msizes 5/0 disagree
php(18446,0x16b70f000) malloc: Region cookie corrupted for region 0x118000000 (value is 1)[0x118007ffc]
xiongxu@HXMBP qcq-api % php(19124,0x16b9cb000) malloc: Region cookie corrupted for region 0x107e00000 (value is 1)[0x107e0407c]
php(22030,0x16b93f000) malloc: Corruption of free object 0x107f04080: msizes 5/0 disagree
php(22030,0x16b93f000) malloc: *** set a breakpoint in malloc_error_break to debug
xiongxu@HXMBP qcq-api % php(33668,0x16b827000) malloc: Corruption of free object 0x107f04150: msizes 4/0 disagree
php(34366,0x16b93f000) malloc: Region cookie corrupted for region 0x107e00000 (value is 1)[0x107e0407c]
php(34366,0x16b93f000) malloc: *** set a breakpoint in malloc_error_break to debug

**Comment by ihekui** [comment]
> 如何重现此问题，执行什么样的代码出现？另外编译时是否执行了 make clean ？

项目一直在swoole开发与运行并跑了2年多了，没有新增什么新的代码，通过埋点调试是执行到swoole启动（server->start()）时就出现这个问题。另外终端中还输出了以下信息：

xiongxu@HXMBP qcq-api % php(16681,0x16b70f000) malloc: Region cookie corrupted for region 0x118000000 (value is 1)[0x118007ffc]
php(16752,0x16b683000) malloc: Region cookie corrupted for region 0x130000000 (value is 0)[0x130007ffc]
php(16752,0x16b683000) malloc: *** set a breakpoint in malloc_error_break to debug
php(16761,0x16b9cb000) malloc: Region cookie corrupted for region 0x118000000 (value is 0)[0x118007ffc]
php(16855,0x16b70f000) malloc: Corruption of free object 0x107f04130: msizes 16816/0 disagree
php(16855,0x16b70f000) malloc: *** set a breakpoint in malloc_error_break to debug
php(17120,0x16b93f000) malloc: Region cookie corrupted for region 0x140000000 (value is 34ef267b)[0x140007ffc]
php(17120,0x16b93f000) malloc: *** set a breakpoint in malloc_error_break to debug
php(17139,0x16b8b3000) malloc: Region cookie corrupted for region 0x148000000 (value is 34ef267b)[0x148007ffc]
php(17139,0x16b8b3000) malloc: *** set a breakpoint in malloc_error_break to debug
php(17453,0x16b70f000) malloc: Region cookie corrupted for region 0x107f00000 (value is 34ef267b)[0x107f0407c]
php(17453,0x16b70f000) malloc: *** set a breakpoint in malloc_error_break to debug
php(17924,0x16b827000) malloc: Corruption of free object 0x107f04080: msizes 5/0 disagree
php(18446,0x16b70f000) malloc: Region cookie corrupted for region 0x118000000 (value is 1)[0x118007ffc]
xiongxu@HXMBP qcq-api % php(19124,0x16b9cb000) malloc: Region cookie corrupted for region 0x107e00000 (value is 1)[0x107e0407c]
php(22030,0x16b93f000) malloc: Corruption of free object 0x107f04080: msizes 5/0 disagree
php(22030,0x16b93f000) malloc: *** set a breakpoint in malloc_error_break to debug
xiongxu@HXMBP qcq-api % php(33668,0x16b827000) malloc: Corruption of free object 0x107f04150: msizes 4/0 disagree
php(34366,0x16b93f000) malloc: Region cookie corrupted for region 0x107e00000 (value is 1)[0x107e0407c]
php(34366,0x16b93f000) malloc: *** set a breakpoint in malloc_error_break to debug

**Comment by ihekui** [comment]
> 好的，感谢反馈，我们测试一下这种情况。
> 
> 在什么位置添加了 `\Swoole\Coroutine::set(['hook_flags' => SWOOLE_HOOK_ALL]);` ?
> 
> 在 Server 中需要将 `\Swoole\Coroutine::set(['hook_flags' => SWOOLE_HOOK_ALL]);` 修改为 `$server->set(['hook_flags' => SWOOLE_HOOK_ALL])` ，在 Worker 进程启动后设置 hook

非常感谢，我的代码是在worker启动前放置的`\Swoole\Coroutine::set(['hook_flags' => SWOOLE_HOOK_ALL]);`
按照您的提示，将其放到worker进程启动后就可以了。
![image](https://user-images.githubusercontent.com/6247202/217486781-3bcac1b0-1fe9-452c-9e12-23b7fb6cf9f5.png)

另外我取消`SWOOLE_HOOK_ALL`，逐个对hook_flag单独启用，发现原来是启用`SWOOLE_HOOK_SOCKETS`是才报错，其他的flag都正常。
