### ISSUE TITLE
Streaming multiple files to a response results in excessive memory usage

### ISSUE THREAD

**Issue by cmollekopf** [swoole/swoole-src#4974]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

```
<?php

#$server = new Swoole\Http\Server("0.0.0.0", 9501, SWOOLE_BASE);
$server = new Swoole\Http\Server("0.0.0.0", 9501, SWOOLE_PROCESS);

$server->set([
    'dispatch_mode' => 2,
    'worker_num' => 1,
    'task_worker_num' => 0,
    'max_request' => 10,
    'reactor_num' => 2,
    'send_yield' => true,
    'package_max_length' => 1024 * 1024 * 10,
    'socket_buffer_size' => 1024 * 1024 * 10,
]);

$server->on('Request', function ($request, $swooleResponse) use ($server) {
    print("on request {$server->worker_id}\n");

    // Output data directly
    // for ($i = 0; $i < 100; $i++) {
    //     $stream = fopen("/tmp/testcontent", 'rb');
    //     $swooleResponse->write(stream_get_contents($stream));
    //     fclose($stream);
    // }


    // Output data via outputbuffering
    ob_start(function ($data) use ($swooleResponse) {
        if (strlen($data) > 0) {
            $swooleResponse->write($data);
        }
        unset($data);

        return '';
    }, 1);

    for ($i = 0; $i < 200; $i++) {
        $stream = fopen("/tmp/testcontent", 'rb');
        fpassthru($stream);
        fclose($stream);
    }

    ob_end_clean();

    $swooleResponse->end();
});

$data = str_pad("", 1024 * 1024 * 10, "X");
file_put_contents("/tmp/testcontent", $data);

print("Starting on 9501, trigger the request using \n curl localhost:9501 --output /dev/null\n");
$server->start();
```

Invoking it like so:
php -dmemory_limit=512M minimalswooletest.php

Triggering the request like so:
curl localhost:9501 --output /dev/null

2. What did you expect to see?
~2GB file transfer, no excessive memory usage.

3. What did you see instead?

The workers memory grows quickly in memory and then crashes.

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
bash-5.1# php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.1
Built => Feb  3 2023 15:35:32
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1q  FIPS 5 Jul 2022
dtls => enabled
http2 => enabled
json => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
bash-5.1# uname -a
Linux 6a69bebdfbd8 6.1.9-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb  2 00:21:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
bash-5.1# php -v
PHP 8.0.26 (cli) (built: Nov 22 2022 17:44:09) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.26, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.26, Copyright (c), by Zend Technologies

```

A bit of background info:
This is a contrived example from a real application which offers large files for download. The files are stored in chunks on the server, and we want to reassemble the file by streaming many chunks to a single response.
This seems to work fine in e.g. apache.

The application is built with laravel using octane, so we're normally running swoole in the SWOOLE_PROCESS mode (and I was unable to get octane to work with the SWOOLE_BASE mode), but I've tried anyways for this example.

In process mode it seems to me the memory of the worker just grows to ~roughly the filesize. If the file is small enough, it will grow with subsequent requests (can be worked around via max_requets to restart the worker). If the file is larger than memory (in total) the worker will crash.

SWOOLE_BASE mode seems to be much faster, but again, memory grows with subsequent requests and eventually a process crashes (there doesn't seem to be a master/worker process architecture in this case?)

Our application uses the outputbuffering appraoch that you can see above, but it also doesn't work without the output buffering (see the commented section).

**Comment by matyhtf** [comment]
There was a memory leak when send yield occurred, fixed
