### ISSUE TITLE
Http服务器当响应内容超过160K时，不能发送response响应

### ISSUE THREAD

**Issue by landso** [swoole/swoole-src#4984]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

swoole版本4.8.12
在Swoole\Http\Server中调用$response->end()发送响应时，当数据较大时，浏览器无法获取到body，但是能获取到header，浏览器一直转圈等待响应。用抓包工具查看，服务器只发送了header，没有body。
当时我是发送一个200多k的网页，后来经过抽离，复现代码如下：

> use Swoole\Http\Request;
use Swoole\Http\Response;
use Swoole\Http\Server;
$http_server = new Server('0.0.0.0', 9503);
$http_server->set([
    'enable_coroutine'      => true,
    'reactor_num'           => 1,
    'worker_num'            => 4,
    'hook_flags'            => SWOOLE_HOOK_ALL,
    'log_rotation'          => SWOOLE_LOG_ROTATION_SINGLE,
    'log_file'              => __DIR__ . '/test.log',
    'buffer_output_size'    => 32 * 1024 * 1024,
]);
$http_server->on('request', function (Request $request, Response $response) {
    $len = 159 * 1024; // 159K正常 160K无法发送body
    $content = str_repeat('1', $len);
    $response->end($content);
});
$http_server->start();`

2. What did you expect to see?

获取正常响应

3. What did you see instead?

无法获取body，浏览器一直处于等待响应。

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.12
Built => Feb  4 2023 10:48:18
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1f  31 Mar 2020
dtls => enabled
http2 => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

> Linux T480S 4.4.0-19041-Microsoft #2311-Microsoft Tue Nov 08 17:09:00 PST 2022 x86_64 x86_64 x86_64 GNU/Linux

> Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

> PHP 7.4.3-4ubuntu2.17 (cli) (built: Jan 10 2023 15:37:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3-4ubuntu2.17, Copyright (c), by Zend Technologies

**Comment by NathanFreeman** [comment]
我没法复现这个问题，请检查一下客户端和服务端之间是否有个中间件，该中间件限制了返回的请求体大小。

**Comment by Yurunsoft** [comment]
这是wsl1下独有的bug

**Comment by landso** [comment]
> 这是wsl1下独有的bug

@Yurunsoft 感谢yurun回复 原来是这样 一开始以为是我的代码问题  昨天晚上排查到3点多🤣 最后用分段发送解决了  现在看来无需担心了

**Comment by landso** [comment]
> 我没法复现这个问题，请检查一下客户端和服务端之间是否有个中间件或者网关，该中间件或网关限制了返回的响应体大小。

@NathanFreeman 谢谢 应该就是yurun提及的wsl1的bug 这个issue我关了
