### ISSUE TITLE
Does sleep accept decimal instead of integer

### ISSUE THREAD

**Issue by ttodua** [swoole/swoole-src#4987]
Per swoole docs: https://openswoole.com/docs/modules/swoole-coroutine-sleep  the function accepts only integer. I remind in the past (2 years ago) I was using i.e. `sleep(0.2)` and it will sleep for 0.2 seconds (200 milliseconds). Has API changed since then and now `sleep` only works with integers (i.e. `sleep(0.2)` will now be turned into same as `sleep(0)`) ?

**Comment by matyhtf** [comment]
@ttodua the openswoole is a branch of swoole, and the parameter type may be changed.

swoole has two sleep functions, one is runtime hook sleep, which is consistent with php sleep, and the other is `Co::sleep`, which allows float parameters to be passed in, which will be converted to milliseconds and then sleep


```php
// php sleep
sleep(0.1);

co\run(function() {
    // runtime hook sleep, the behavior is consistent with php sleep
    sleep(0.1);
    // sleep 100ms
    Co::sleep(0.1);
});

```

**Comment by ttodua** [comment]
Thanks for the answer.  lets say, we provide integers (not floats).
  it doesnt matter which one we use inside `run` in the below example, right?
```
co\run(function() {
    sleep(1);
    Co::sleep(1);
});
```
so, both function (inside `run`) will execute with similar swoole async mode right?  or `Co::sleep` is the only true asynchronous way?
