### ISSUE TITLE
在定时器自动创建的协程中获取到的Pcid是-1

### ISSUE THREAD

**Issue by yunwuxin** [swoole/swoole-src#4992]
> 在协程环境下 [Swoole\Timer::after](https://wiki.swoole.com/#/timer?id=after) 回调中会自动创建一个协程

这里自动创建的协程中通过`Coroutine::getPcid()`获取父协程的id  获取到的是-1  并不是预期的 创建这个定时器协程的ID  

这个是设计如此  还是bug？

**Comment by matyhtf** [comment]
定时器协程是在 eventloop 中创建的，因此 pcid 就是 -1
