### ISSUE TITLE
Unable to load dynamic library 'swoole.so' and swoole.so.so no such file

### ISSUE THREAD

**Issue by rehack** [swoole/swoole-src#4993]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
我按照官网文档进行了编译安装
`phpize --clean`
`phpize`
`./configure -enable-swoole --enable-swoole-curl --with-php-config=/usr/local/webserver/php/bin/php-config`
`make && sudo make install`
`将extension=swoole.so 写入php.ini配置文件尾部`
经过以上步骤然后执行php -m和php —ri swoole 出现了错误

2. What did you expect to see?
期望是swoole扩展能正确的被php加载

3. What did you see instead?
通过php -m 和php --ri swoole都会看到如下错误：
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so (dlopen(/usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so, 0x0009): symbol not found in flat namespace '_BrotliDecoderCreateInstance'), /usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so.so (dlopen(/usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so.so, 0x0009): tried: '/usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so.so' (no such file), '/usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so.so' (no such file))) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so (dlopen(/usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so, 0x0009): symbol not found in flat namespace '_BrotliDecoderCreateInstance'), /usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so.so (dlopen(/usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so.so, 0x0009): tried: '/usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so.so' (no such file), '/usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so.so' (no such file))) in Unknown on line 0
```

* php目录下有/usr/local/webserver/php/lib/php/extensions/no-debug-non-zts-20220829/swoole.so 和/usr/local/webserver/php/include/php/ext/swoole 这信息说明swoole扩展编译是正常的，为什么会no such file
* 不明白的是上述报错信息中swoole.so.so' (no such file), 为什么会多了.so的扩展名

4. What version of Swoole are you using (show your `php --ri swoole`)?
`php --ri swoole `会出现上述错误信息

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

* swoole version : https://github.com/swoole/swoole-src/archive/refs/tags/v5.0.2.tar.gz
* php version: 8.2.3
* uname -a: Darwin iMac.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64
* gcc version 14.0.0

**Comment by NathanFreeman** [comment]
```shell
apt install libbrotli-dev
```

**Comment by rehack** [comment]
> 看起来少了个libbrotli

brotil是一个压缩的模块，可选项，我在配置的时候也是加上的，完整的：
./configure -enable-swoole --enable-swoole-curl --enable-debug --enable-openssl --enable-sockets --enable-brotli --enable-mysqlnd --enable-trace-log --with-openssl-dir=/usr/local/devenv/openssl --with-php-config=/usr/local/webserver/php/bin/php-config --with-brotli-dir=/usr/local/devenv/brotli

**Comment by twose** [comment]
看起来像是编译加了libbrotli，但运行的时候并没有链接到libbrotli导致的，感觉libbrotli装的有问题

可以 otool -L swoole.so 看看

**Comment by rehack** [comment]
> 看起来像是编译加了libbrotli，但运行的时候并没有链接到libbrotli导致的，感觉libbrotli装的有问题
> 
> 可以 otool -L swoole.so 看看

```
rehack@iMac php % otool -L ./lib/php/extensions/debug-non-zts-20220829/swoole.so 
./lib/php/extensions/debug-non-zts-20220829/swoole.so:
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
        /usr/local/devenv/openssl/lib/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /usr/local/devenv/openssl/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.36.0)
rehack@iMac php % 
```

**Comment by matyhtf** [comment]
可以使用 `--with-brotli-dir` 设置 brotli 的安装路径

**Comment by rehack** [comment]
@matyhtf `--with-brotli-dir=/usr/local/devenv/brotli --enable-brotli ` 这2个配置项我是添加上了的，上面我给出了完整的配置信息。安装过程没有报错，php -v / php -m就会报错
