### ISSUE TITLE
Swoole Coroutine模式下会导致guzzlehttp获取到的html Header标识变成小写

### ISSUE THREAD

**Issue by aboutboy** [swoole/swoole-src#4995]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

在laravel框架（9.*）中使用了simps/mqtt包，mqtt客户端订阅消息。
部分代码如下：
```php
Coroutine\run(function () use ($config) {
            $myconfig = new ClientConfig();
            $myconfig->setUserName($config['username'])
                ->setPassword($config['password'])
                ->setClientId(Client::genClientID())
                ->setKeepAlive(10)
                ->setDelay(3000) // 3s
                ->setMaxAttempts(5)
                ->setProperties([
                    'session_expiry_interval' => 60,
                    'receive_maximum' => 65535,
                    'topic_alias_maximum' => 65535,
                ])
                ->setProtocolLevel(5)
                ->setSwooleConfig(self::SWOOLE_MQTT_CONFIG);
            $client = new Client($config['host'], $config['port'], $myconfig, Client::SYNC_CLIENT_TYPE);
```
在监听到消息后，会使用$this->call()发起一个爬虫命令。结果发现偶尔存在异常。
分析发现，Swoole Coroutine会导致guzzlehttp获取网页后header标识符变成小写，如下：
本来应该是Content-Type，变成了content-type
```php
  'age' => 
  array (
    0 => '3116',
  ),
  'cache-control' => 
  array (
    0 => 'public, max-age=7200',
  ),
  'connection' => 
  array (
    0 => 'keep-alive',
  ),
  'content-type' => 
  array (
    0 => 'image/jpeg',
  ),
  'date' => 
  array (
    0 => 'Sun, 05 Mar 2023 14:34:37 GMT',
  ),
  'expires' => 
  array (
    0 => 'Sun, 05 Mar 2023 16:34:37 GMT',
  ),
```
因为我的爬虫脚本要使用Content-Type判断文件类型，所以这样就会导致异常。
我注释掉Coroutine后，正常。

```php
//Coroutine\run(function () use ($config) {
            $myconfig = new ClientConfig();
            $myconfig->setUserName($config['username'])
                ->setPassword($config['password'])
                ->setClientId(Client::genClientID())
                ->setKeepAlive(10)
                ->setDelay(3000) // 3s
                ->setMaxAttempts(5)
                ->setProperties([
                    'session_expiry_interval' => 60,
                    'receive_maximum' => 65535,
                    'topic_alias_maximum' => 65535,
                ])
                ->setProtocolLevel(5)
                ->setSwooleConfig(self::SWOOLE_MQTT_CONFIG);
            $client = new Client($config['host'], $config['port'], $myconfig, Client::SYNC_CLIENT_TYPE);
```

想知道是什么原因导致上述问题。

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

php 8.2
laravel 9.*

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.11
Built => Dec 31 2022 13:56:00
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 3.0.2 15 Mar 2022
dtls => enabled
http2 => enabled
json => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by NathanFreeman** [comment]
你看看你编译的swoole的时候有没有开启`--enable-swoole-curl`

**Comment by aboutboy** [comment]
> 你看看你编译的swoole的时候有没有开启`--enable-swoole-curl`

感觉，确实是这个问题。
我加上这个编译选项，重新编译，现在正常了。
