### ISSUE TITLE
编译报错 ld: library not found for -lrt

### ISSUE THREAD

**Issue by robbinhan** [swoole/swoole-src#5]
configuration完毕，make出错
机器环境：
- php5.5.1
- macos x 10.8.4
- clang:

``` shell
➜  swoole-swoole-1.5.5  clang -v
Apple LLVM version 4.2 (clang-425.0.24) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin12.4.0
Thread model: posix
```

错误信息：

``` shell
/bin/sh /Users/robbin/Downloads/swoole-swoole-1.5.5/libtool --mode=link cc -DPHP_ATOM_INC -I/Users/robbin/Downloads/swoole-swoole-1.5.5/include -I/Users/robbin/Downloads/swoole-swoole-1.5.5/main -I/Users/robbin/Downloads/swoole-swoole-1.5.5 -I/Users/robbin/.phpenv/versions/5.5.1/include/php -I/Users/robbin/.phpenv/versions/5.5.1/include/php/main -I/Users/robbin/.phpenv/versions/5.5.1/include/php/TSRM -I/Users/robbin/.phpenv/versions/5.5.1/include/php/Zend -I/Users/robbin/.phpenv/versions/5.5.1/include/php/ext -I/Users/robbin/.phpenv/versions/5.5.1/include/php/ext/date/lib -I/include  -DHAVE_CONFIG_H  -g -O2   -o swoole.la -export-dynamic -avoid-version -prefer-pic -module -rpath /Users/robbin/Downloads/swoole-swoole-1.5.5/modules  swoole.lo src/core/Base.lo src/core/RingQueue.lo src/core/Chan.lo src/memory/ShareMemory.lo src/memory/MemPool.lo src/factory/Factory.lo src/factory/FactoryThread.lo src/factory/FactoryProcess.lo src/reactor/ReactorBase.lo src/reactor/ReactorSelect.lo src/reactor/ReactorPoll.lo src/reactor/ReactorEpoll.lo src/reactor/ReactorKqueue.lo src/pipe/PipeBase.lo src/pipe/PipeEventfd.lo src/pipe/PipeUnsock.lo src/pipe/PipeMsg.lo src/lock/Semaphore.lo src/lock/Mutex.lo src/lock/RWLock.lo src/lock/FileLock.lo src/network/Server.lo src/network/Client.lo src/network/buffer.lo -lrt
cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/swoole.so -bundle  .libs/swoole.o src/core/.libs/Base.o src/core/.libs/RingQueue.o src/core/.libs/Chan.o src/memory/.libs/ShareMemory.o src/memory/.libs/MemPool.o src/factory/.libs/Factory.o src/factory/.libs/FactoryThread.o src/factory/.libs/FactoryProcess.o src/reactor/.libs/ReactorBase.o src/reactor/.libs/ReactorSelect.o src/reactor/.libs/ReactorPoll.o src/reactor/.libs/ReactorEpoll.o src/reactor/.libs/ReactorKqueue.o src/pipe/.libs/PipeBase.o src/pipe/.libs/PipeEventfd.o src/pipe/.libs/PipeUnsock.o src/pipe/.libs/PipeMsg.o src/lock/.libs/Semaphore.o src/lock/.libs/Mutex.o src/lock/.libs/RWLock.o src/lock/.libs/FileLock.o src/network/.libs/Server.o src/network/.libs/Client.o src/network/.libs/buffer.o  -lrt
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [swoole.la] Error 1
```

**Comment by huangxiaoye** [comment]
PHP 5.5.17-1~dotdeb.1 (cli) (built: Sep 19 2014 02:19:26) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
这个环境下执行 pecl upgrade swoole 报错了如下：
libtool: compile:  cc -I. -I/tmp/pear/temp/swoole -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/include -I/tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/main -I/tmp/pear/temp/swoole -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /tmp/pear/temp/swoole/swoole_http.c  -fPIC -DPIC -o .libs/swoole_http.o
/bin/bash /tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/libtool --mode=compile cc  -I. -I/tmp/pear/temp/swoole -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/include -I/tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/main -I/tmp/pear/temp/swoole -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /tmp/pear/temp/swoole/src/core/Base.c -o src/core/Base.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/swoole -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/include -I/tmp/pear/temp/pear-build-rootOkmrku/swoole-1.7.9/main -I/tmp/pear/temp/swoole -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /tmp/pear/temp/swoole/src/core/Base.c  -fPIC -DPIC -o src/core/.libs/Base.o
/tmp/pear/temp/swoole/src/core/Base.c:17:20: fatal error: swoole.h: No such file or directory
compilation terminated.
make: *** [src/core/Base.lo] Error 1
ERROR: `make' failed
