### ISSUE TITLE
有计划对 rdkafka 增加 hook 不？

### ISSUE THREAD

**Issue by huangdijia** [swoole/swoole-src#5000]
`swoole/kafka` 已经没有维护了，比较主流的 kafka 扩展只有 rdkafka 了，不过测试下来貌似不支持协程，峰哥有计划 hook 一下不？

**Comment by twose** [comment]
rdkafka 不支持 多路复用。

解释一下，cURL可以是因为 libcurl 支持多路复用模式，pgsql 可以是因为 libpq 支持多路复用模式，MongoDB不可以是因为 libmongoc 只支持多线程模式不支持多路复用模式，kafka 不可以是因为 rdkafka 或其他 C 库不支持多路复用模式。

除了看源码、文档，还有一个简单的办法可以快速判断，就是通过关键字搜索看 nodejs、libuv、libev 等社区是如何接入这些库的，如果没有相关的接入信息，而是自行实现的协议解析，那就是因为对应的库不支持多路复用模式。

**Comment by matyhtf** [comment]
在 swoole 中实现低成本实现客户端协程化有`4`个方案

1. 基于 `PhpStream` 或者 `ext-sockets` 实现的网络客户端，无需做任何事情，直接就支持，例如 `mysqli`、`pdo_mysql`、`redis`、`soap`
2. `swoole_socket_hook.h`：使用 `C++` 宏替换阻塞 IO 的系统调用函数，如 `hiredis`、`swoole zookeeper`
3. `swoole::coroutine::async()` 使用 `AIO` 线程池将同步阻塞的函数模拟实现异步非阻塞，例如 `gethostbyname()`、`FileStream`
4. 基于第三库的异步 `API` 实现协程化，例如 `swoole_curl`、`swoole_postgresql`，`libcurl` 和 `libpq` 本身提供了异步 `API`

如果无法使用上述的方法实现协程化，就只能基于 `PhpStream` 或者 `Swoole\Coroutine\Socket` 来实现协议处理，这个维护成本非常高。
