### ISSUE TITLE
通过\Swoole\Process\Pool创建的进程之间通讯时没法自己处理数据包边界

### ISSUE THREAD

**Issue by yunwuxin** [swoole/swoole-src#5002]
如下图 会一直卡在recvPacket那个地方

![image](https://user-images.githubusercontent.com/2168125/223683725-2166435b-4824-405b-9496-e05e3d96c73a.png)

**Comment by matyhtf** [comment]
`Process\Pool` 创建的是 `unix socket dgram`，所以并不支持 `recvPacket()` ，建议使用 `swoole_coroutine_socketpair()` 创建管道。

**Comment by matyhtf** [comment]
IPC 目前是搭配 `Pool onMessage` 回调使用的。并不支持进程之间通信。
