### ISSUE TITLE
can not make test, error

### ISSUE THREAD

**Issue by warpkwd** [swoole/swoole-src#5003]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

make test script does not work property.
kawada@plt-batman-y13001:~/app/swoole-src/tests$ ./start.sh base|head

=====================================================================
PHP         : /usr/bin/php
PHP_SAPI    : cli
PHP_VERSION : 8.1.2
ZEND_VERSION: 4.1.2
PHP_OS      : Linux - Linux plt-batman-y13001.i1.dev.v6.internal-gmo 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64
INI actual  : /etc/php/8.1/cli/php.ini
More .INIs  : /etc/php/8.1/cli/conf.d/10-opcache.ini,/etc/php/8.1/cli/conf.d/10-pdo.ini,/etc/php/8.1/cli/conf.d/15-xml.ini,/etc/php/8.1/cli/conf.d/20-bcmath.ini,/etc/php/8.1/cli/conf.d/20-calendar.ini,/etc/php/8.1/cli
/conf.d/20-ctype.ini,/etc/php/8.1/cli/conf.d/20-dom.ini,/etc/php/8.1/cli/conf.d/20-exif.ini,/etc/php/8.1/cli/conf.d/20-ffi.ini,/etc/php/8.1/cli/conf.d/20-fileinfo.ini,/etc/php/8.1/cli/conf.d/20-ftp.ini,/etc/php/8.1/cl
i/conf.d/20-gettext.ini,/etc/php/8.1/cli/conf.d/20-iconv.ini,/etc/php/8.1/cli/conf.d/20-mbstring.ini,/etc/php/8.1/cli/conf.d/20-phar.ini,/etc/php/8.1/cli/conf.d/20-posix.ini,/etc/php/8.1/cli/conf.d/20-readline.ini,/et
c/php/8.1/cli/conf.d/20-shmop.ini,/etc/php/8.1/cli/conf.d/20-simplexml.ini,/etc/php/8.1/cli/conf.d/20-sockets.ini,/etc/php/8.1/cli/conf.d/20-sysvmsg.ini,/etc/php/8.1/cli/conf.d/20-sysvsem.ini,/etc/php/8.1/cli/conf.d/2
0-sysvshm.ini,/etc/php/8.1/cli/conf.d/20-tokenizer.ini,/etc/php/8.1/cli/conf.d/20-xmlreader.ini,/etc/php/8.1/cli/conf.d/20-xmlwriter.ini,/etc/php/8.1/cli/conf.d/20-xsl.ini
CWD         : /home/kawada/app/swoole-src/tests
kawada@plt-batman-y13001:~/app/swoole-src/tests$ ./start.sh base|head -30
=====================================================================
Running selected tests.
TEST 1/1104 [swoole_atomic/atomic.phpt]

========DIFF========
001+ Warning: require(/home/kawada/app/swoole-src/tests/include/lib/vendor/autoload.php): Failed to open stream: No such file or directory in /home/kawada/app/swoole-src/tests/include/bootstrap.php on line 53
003+ Fatal error: Uncaught Error: Failed opening required '/home/kawada/app/swoole-src/tests/include/lib/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/kawada/app/swoole-src/tests/include/bootstrap.ph
p:53
004+ Stack trace:
005+ #0 /home/kawada/app/swoole-src/tests/swoole_atomic/atomic.php(2): require()
006+ #1 {main}
007+   thrown in /home/kawada/app/swoole-src/tests/include/bootstrap.php on line 53
========DONE========
[FAIL] swoole_atomic: add/sub/get/cmpset [swoole_atomic/atomic.phpt]
TEST 2/1104 [swoole_atomic/dtor_in_child.phpt]

2. What did you expect to see?

tests/include/lib/vendor/autoload.php  files does not exist.

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by NathanFreeman** [comment]
```shell
cd ./test/include/lib
composer install
```
