### ISSUE TITLE
Connect EVENT: "Invalid frame header"

### ISSUE THREAD

**Issue by tengdengming** [swoole/swoole-src#5004]
### Invalid frame header
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
客户端连接时，突然发现报“**Invalid frame header**”

服务端直接进入 Close事件

2. What did you expect to see?
当时啥都正常，不过这个问题之前也出现多很多次，Invalid frame header，后来解决了，忘记怎么解决了。（各种搜也是没有结果，所以今天提一个issue记录一下最后解决办法，以备后查。）

3. What did you see instead?
连接提示“Error”

4. What version of Swoole are you using (show your `php --ri swoole`)?
Version => 4.4.17
Built => Jun 29 2020 18:34:48
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
都很标准的环境，昨天可以，今天就不行。

**Comment by tengdengming** [comment]
### 注意注意，不是配置问题，不是逻辑问题。
是通讯事件编程正常逻辑理解的问题。在Connect，或者OnOpen事件注册逻辑中，有时候为了做一些测试或者同步阻塞的操作时，将业务逻辑写到了默认事件中，导致上下文句柄逻辑生命周期怪圈。

比如我在测试的时候为了测回一个包，简单的将send发送写在了OnOpen事件处理域的协程处理单元，在协程又global全局调用主类的send方法。导致连接事件中去执行一个基于连接以后的发送调用。是不是有点奇怪，（它是不会明确的告诉你错在哪里）

拿掉后即可恢复正常，这个问题碰到过2次以上，但是时间久了，写别的去了就忘记了。

**Comment by matyhtf** [comment]
不要使用 `Server::send()` 方法，这是原始的 `tcp send`，改为使用 `Server::push()`

**Comment by tengdengming** [comment]
学习了，TCP层面的用Server::push()。 @matyhtf 。另外请教一下，可以在哪里看到这种异常信息日志？
