### ISSUE TITLE
swoole5.0.1  workerStart中使用$server->push报错

### ISSUE THREAD

**Issue by mf04** [swoole/swoole-src#5006]
PHP Warning:  Swoole\WebSocket\Server::push(): the connected client of connection[1] is not a websocket client or closed in

**Comment by NathanFreeman** [comment]
`workerStart`事件发生的时候，`worker`才进程刚刚启动，都没有客户端连接，所以不能用这个函数

**Comment by mf04** [comment]
4.8.9可以，莫名奇妙升级之后，就不好使了。workerStart中异步获取的数据，不存在你说的没有客户端连接的问题

**Comment by NathanFreeman** [comment]
还有可能就是这个连接已经不存在或者没有经过websocket handshake，所以就会这个报错。
或者提供可复现的最小化代码，我这边看看。

**Comment by matyhtf** [comment]
请注意查看更新日志，5.0 之后默认运行模式改为了 SWOOLE_BASE
