### ISSUE TITLE
ext-src/php_swoole_private.h:96:2: error: #error "require PHP version 8.0 or later"

### ISSUE THREAD

**Issue by laraws** [swoole/swoole-src#5007]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

```bash
git clone https://github.com/swoole/swoole-src.git && \
cd swoole-src
phpize && \
./configure && \
make && make install
```

2. What did you expect to see?

install successfuly.

4. What did you see instead?

Install error.

6. What version of Swoole are you using (show your `php --ri swoole`)?

latest code version for github.

8. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

System info: Ubuntu 20.04

GCC info: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

```bash
php -v
PHP 8.0.28 (cli) (built: Feb 14 2023 18:32:57) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.28, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.28, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans
```

**Comment by NathanFreeman** [comment]
Swoole5 require PHP 8 or later.
Please check the `phpize` version.
```shell
phpize -v
```

**Comment by laraws** [comment]
> Swoole5 require PHP 8 or later. Please check the `phpize` version.
> 
> ```shell
> phpize -v
> ```

The phpize version is below.
```
phpize -v
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
```

**Comment by laraws** [comment]
After updating the `phpize`, I installed swoole successfuly. Thx.
