### ISSUE TITLE
为什么协程中可以共用一个guzzle httpclient，但不能共用一个symfony httclient？

### ISSUE THREAD

**Issue by pengxuxu** [swoole/swoole-src#5008]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
        $client = \Symfony\Component\HttpClient\HttpClient::create([]);

        go(function () use ($client) {
            $ret = $client->request('GET', 'http://www.baidu.com/');
            var_dump("a:pcid:" . Coroutine::getPcid());
            var_dump("a:uid:" . Coroutine::getuid());
            var_dump("a:code:" . $ret->getStatusCode());
        });
        go(function () use ($client) {
            $ret = $client->request('GET', 'http://www.baidu.com/');
            var_dump("b:pcid:" . Coroutine::getPcid());
            var_dump("b:uid:" . Coroutine::getuid());
            var_dump("b:code:" . $ret->getStatusCode());
        });

        
        $cli = new \GuzzleHttp\ClientClient();

        go(function () use ($cli) {
            $ret = $cli->get('http://www.baidu.com/');
            var_dump("a:pcid:" . Coroutine::getPcid());
            var_dump("a:uid:" . Coroutine::getuid());
            var_dump("a:code:" . $ret->getStatusCode());
        });
        go(function () use ($cli) {
            $ret = $cli->get('http://www.baidu.com/');
            var_dump("b:pcid:" . Coroutine::getPcid());
            var_dump("b:uid:" . Coroutine::getuid());
            var_dump("b:code:" . $ret->getStatusCode());
        });
```
2. What did you expect to see?
在协程中共用一个guzzle或者symfony httpclient客户端

3. What did you see instead?
测试在协程中共用一个http客户端，共用guzzle httpclient时正常，但是共用symfony httpclient时报错，[guzzlehttp/guzzle版本7.5.0，symfony/http-client版本6.0.20，php版本8.0.25，guzzle使用的默认的handler，extension_loaded('curl')为true]。报错信息如下：
string(8) "a:pcid:2"
string(7) "a:uid:3"
string(8) "b:pcid:2"
string(7) "b:uid:4"
PHP Fatal error:  Uncaught Swoole\Error: cURL is executing, cannot be operated in /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/CurlResponse.php:366
Stack trace:
#0 /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/CurlResponse.php(366): curl_multi_select()
#1 /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/TransportResponseTrait.php(305): Symfony\Component\HttpClient\Response\CurlResponse::select()
#2 /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/CommonResponseTrait.php(149): Symfony\Component\HttpClient\Response\CurlResponse::stream()
#3 /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/TransportResponseTrait.php(53): Symfony\Component\HttpClient\Response\CurlResponse::initialize()
#4 /data/project/hyperf-skeleton/runtime/container/proxy/App_Controller_IndexController.proxy.php(45): Symfony\Component\HttpClient\Response\CurlResponse->getStatusCode()
#5 /data/project/hyperf-skeleton/vendor/hyperf/utils/src/Coroutine.php(67): App\Controller\IndexController->App\Controller\{closure}()
#6 {main}
  thrown in /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/CurlResponse.php on line 366

Fatal error: Uncaught Swoole\Error: cURL is executing, cannot be operated in /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/CurlResponse.php:366
Stack trace:
#0 /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/CurlResponse.php(366): curl_multi_select()
#1 /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/TransportResponseTrait.php(305): Symfony\Component\HttpClient\Response\CurlResponse::select()
#2 /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/CommonResponseTrait.php(149): Symfony\Component\HttpClient\Response\CurlResponse::stream()
#3 /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/TransportResponseTrait.php(53): Symfony\Component\HttpClient\Response\CurlResponse::initialize()
#4 /data/project/hyperf-skeleton/runtime/container/proxy/App_Controller_IndexController.proxy.php(45): Symfony\Component\HttpClient\Response\CurlResponse->getStatusCode()
#5 /data/project/hyperf-skeleton/vendor/hyperf/utils/src/Coroutine.php(67): App\Controller\IndexController->App\Controller\{closure}()
#6 {main}
  thrown in /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/CurlResponse.php on line 366
[2023-03-13 02:30:31 *19.0]     ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught Swoole\Error: cURL is executing, cannot be operated in /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/CurlResponse.php:366
Stack trace:
#0 /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/CurlResponse.php(366): curl_multi_select()
#1 /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/TransportResponseTrait.php(305): Symfony\Component\HttpClient\Response\CurlResponse::select()
#2 /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/CommonResponseTrait.php(149): Symfony\Component\HttpClient\Response\CurlResponse::stream()
#3 /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/TransportResponseTrait.php(53): Symfony\Component\HttpClient\Response\CurlResponse::initialize()
#4 /data/project/hyperf-skeleton/runtime/container/proxy/App_Controller_IndexController.proxy.php(45): Symfony\Component\HttpClient\Response\CurlResponse->getStatusCode()
#5 /data/project/hyperf-skeleton/vendor/hyperf/utils/src/Coroutine.php(67): App\Controller\IndexController->App\Controller\{closure}()
#6 {main}
  thrown in /data/project/hyperf-skeleton/vendor/symfony/http-client/Response/CurlResponse.php on line 366
* Closing connection 1
* Closing connection 0
[2023-03-13 02:30:34 $18.0]     WARNING Server::check_worker_exit_status(): worker(pid=19, id=0) abnormal exit, status=255, signal=0

4. What version of Swoole are you using (show your `php --ri swoole`)?
/data/project/hyperf-skeleton # php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.2
Built => Feb  6 2023 10:14:40
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1s  1 Nov 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux 15744f9ff0b2 5.10.104-linuxkit#1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 Linux

**Comment by twose** [comment]
那得去问 guzzle 和 symfony 分别是怎么实现的…

guzzle 本身就支持 async，所以应该是考虑过这种共用场景的，比如自动分配新的 cURL handle。Symfony 应该只考虑了阻塞场景，可能就是只做了一对一的简单实现。

**Comment by twose** [comment]
PS：本身就支持异步特性的库基本都支持协程，因为协程只是一种将异步编程变得更好用的技术而已，它们本身都需要考虑到全局变量、静态变量和资源竞争的各种问题。

**Comment by pengxuxu** [comment]
> PS：本身就支持异步特性的库基本都支持协程，因为协程只是一种将异步编程变得更好用的技术而已，它们本身都需要考虑到全局变量、静态变量和资源竞争的各种问题。

谢谢大佬解释，那里有guzzle和symfony httpclient的对比就好了
