### ISSUE TITLE
Swoole 5.0.1 在User Process中遍历 $server->connections 为空，而在onReceive遍历不为空，这是Bug吗？

### ISSUE THREAD

**Issue by MsZhu** [swoole/swoole-src#5011]

**Comment by NathanFreeman** [comment]
进程不一样，onReceive的时候是在worker进程，User Process是用户进程，跨进程数据不共享

**Comment by matyhtf** [comment]
5.0 默认使用 BASE 模式，你可以改为 PROCESS

**Comment by MsZhu** [comment]
我是照文档示例写的demo：
$server = new Swoole\Server('127.0.0.1', 9501);

/**
 * 用户进程实现了广播功能，循环接收unixSocket的消息，并发给服务器的所有连接
 */
$process = new Swoole\Process(function ($process) use ($server) {
    $socket = $process->exportSocket();
    while (true) {
        $msg = $socket->recv();
        // 这里遍历connections为空
        foreach ($server->connections as $conn) {
            $server->send($conn, $msg);
        }
    }
}, false, 2, 1);

$server->addProcess($process);

$server->on('receive', function ($serv, $fd, $reactor_id, $data) use ($process) {
    //群发收到的消息
    $socket = $process->exportSocket();
    $socket->send($data);
});

$server->start();

**Comment by MsZhu** [comment]
嗯，改了就对了，得回头多理解下下，谢谢大神解答！~
