### ISSUE TITLE
swoole redis链接后存在大量close_wait，然后服务器内存爆满

### ISSUE THREAD

**Issue by Funny-dot** [swoole/swoole-src#5014]
swoole redis链接池，链接后存在大量close_wait，然后服务器内存爆满，这个怎么解决呢

**Comment by NathanFreeman** [comment]
请问用的是swoole redis客户端还是swoole redis服务器

**Comment by Funny-dot** [comment]
> 请问用的是swoole redis客户端还是swoole redis服务器？ Swoole和PHP版本是多少？

客户端 
PHP7.4
![image](https://user-images.githubusercontent.com/27287970/227714048-b0ff4ff2-a1cb-4d58-938d-1a7cc77582e0.png)

![image](https://user-images.githubusercontent.com/27287970/227714048-b0ff4ff2-a1cb-4d58-938d-1a7cc77582e0.png)

**Comment by NathanFreeman** [comment]
有没有可供复现的代码或者执行了swoole redis客户端的什么函数

**Comment by Funny-dot** [comment]
> 有没有可供复现的代码或者执行了swoole redis客户端的什么函数

没有的，使用的thinkphp6+think-swoole扩展，对redis的操作都是普通的set、get操作

**Comment by NathanFreeman** [comment]
我这边复现看看

**Comment by Funny-dot** [comment]
> 我这边复现看看

好的

**Comment by NathanFreeman** [comment]
```php
<?php
use function Swoole\Coroutine\run;
use function Swoole\Coroutine\go;
use Swoole\Coroutine\Redis;

run(function() {
    $redis = new Redis();
    $redis->connect('127.0.0.1', 6379);
    while(1) {
        var_dump($redis->set('a', str_pad("", 1024 * 1024 * 10, "X")));
    }
});
```
我这边没有测出内存泄漏，出现大量close_wait应该是服务端主动断开redis的连接了

**Comment by Funny-dot** [comment]
> 

redis主动关闭导致的大量close_wait吗

**Comment by Funny-dot** [comment]
那为啥redis主动关闭了，服务端链接redis没有关闭呢，导致了大量close_wait

**Comment by NathanFreeman** [comment]
有可能是客户端不是正常退出的，服务端没办法检测这种异常退出而没有调用close，导致大量close_wait，没有释放socket

**Comment by Funny-dot** [comment]
> 有可能是客户端不是正常退出的，服务端没有检测到这种异常退出而没有调用close，导致大量close_wait，没有释放socket

请问有检测方法吗

**Comment by NathanFreeman** [comment]
你的redis服务端是自己写的吗？

**Comment by NathanFreeman** [comment]
如果你有服务监控的话，你可以看看服务端的socket是不是光增长不下降，然后去检查一下是不是服务端的代码有问题

**Comment by Funny-dot** [comment]
> 

我redis timeout设置的60  php代码timeout设置的2,这个有没有问题哎

**Comment by Funny-dot** [comment]
> 有可能，redis配置文件中的timeout开启之后，如果客户端在规定的时间段内没有发送数据过来，redis会关闭这个链接，但是在php中这个连接还没过完生命周期，无法关闭这个连接。你可以设置成0试试。

php链接池设置的timeout为2 为啥没用呢

**Comment by Funny-dot** [comment]
> > 有可能，redis配置文件中的timeout开启之后，如果客户端在规定的时间段内没有发送数据过来，redis会关闭这个链接，但是在php中这个连接还没过完生命周期，无法关闭这个连接。你可以设置成0试试。
> 
> php链接池设置的timeout为2 为啥没用呢

以前redis配置文件timeout设置的0，产生大量的time_wait，然后就出现了Cannot assign requested address，redis的timeout设置成60产生大量的close_wait。。。不知道怎么设置了

**Comment by NathanFreeman** [comment]
> > 有可能，redis配置文件中的timeout开启之后，如果客户端在规定的时间段内没有发送数据过来，redis会关闭这个链接，但是在php中这个连接还没过完生命周期，无法关闭这个连接。你可以设置成0试试。
> 
> php链接池设置的timeout为2 为啥没用呢

你可以贴一下你的连接池配置，不过这个应该跟心跳间隔有关，跟超时没什么关系。

**Comment by Funny-dot** [comment]
> > > 有可能，redis配置文件中的timeout开启之后，如果客户端在规定的时间段内没有发送数据过来，redis会关闭这个链接，但是在php中这个连接还没过完生命周期，无法关闭这个连接。你可以设置成0试试。
> > 
> > 
> > php链接池设置的timeout为2 为啥没用呢
> 
> 你可以贴一下你的连接池配置，不过这个我认为应该跟心跳间隔有关，跟超时没什么关系。
框架是tp6
config/cache.php
![image](https://user-images.githubusercontent.com/27287970/230335181-355a90ee-8a5b-4e72-a863-76147b2e4bb1.png)


config/swoole.php
![image](https://user-images.githubusercontent.com/27287970/230334969-420fbee1-2fe7-4367-9f40-4d80ce738c96.png)

**Comment by NathanFreeman** [comment]
我看了think-swoole的代码，他其实是有心跳和超过空闲时间杀掉连接的设计。
你的代码里面有阻塞代码或者实例化原生Redis的功能吗？
能看看你使用redis的代码吗？
