### ISSUE TITLE
swoole tcp server结合框架使用出错,请指导

### ISSUE THREAD

**Issue by trainyao** [swoole/swoole-src#502]
将swoole tcp server的创建语句放到TP的一个Action里,用cli模式运行,,server正常启动,语句如下:
controller {
    public function test() {
        $serv = new \swoole_server(C('TASK_SERVER_IP'), C('TASK_SERVER_PORT'));
        $serv->set(array('task_worker_num' => 4));
        $serv->on('connect', function($serv, $fd) {
                echo "connect\n";
        });
        $serv->on('receive', function($serv, $fd, $from_id, $data) {
                echo "message\n";
                echo $data . "\n";
        });
        $serv->on('task', function($serv, $fd, $from_id, $data) {
                echo "task\n";
        });
        $serv->start();
    }
}
问题来了..我在另外的一个action初始化一个client,用在connect函数链接这个服务器,出现了无返回情况(更奇怪的是有时候可以,有时候无返回,无返回时chrome报"net::ERR_EMPTY_RESPONCE"),请求方式是用浏览器请求这个action,然后action里的脚本进行新建client对象,语句如下:

controller2{
    public function test() {
        $client = new \swoole_client(SWOOLE_SOCK_TCP, SWOOLE_SOCK_SYNC);
        $client->connect('127.0.0.1', 9503);
        $client->send('test');
        $data = $client->recv();
        $client->close();
        dump($data);
    }
}

但是将这段脚本拷到TP外的单独的php文件,用cli运行,执行结果没有问题...
请问这是tp不允许这么写...还是swoole的client对象不能通过浏览器请求新建  还是什么问题?

**Comment by matyhtf** [comment]
swoole_server不能用于web环境。

**Comment by trainyao** [comment]
但是同样的代码经测试在nginx上可以运行很奇怪...apache不行....

**Comment by weijer** [comment]
我也遇到这个问题！ apache服务器 在cli下使用正常在apache下浏览器就没有反应了 我试试nginx

**Comment by fatrbaby** [comment]
哥们儿没写过命令行程序么？

**Comment by weijer** [comment]
就是没写过啊！ @fatrbaby 求指教

**Comment by lchjczw** [comment]
我自学的，只会命令行，框架还不熟

**Comment by weijer** [comment]
swoole扩展中swoole_server只能在cli模式下使用，在其他模式下会抛出致命错误。 而swoole_client和swoole_event是可以用在php-fpm或apache+mod_php5中的。  

不是说**swoole_client**可以在php-fpm或apache+mod_php5中使用么！

**Comment by fatrbaby** [comment]
`swoole_client`当然可以。这哥们儿的问题是把`swoole_server`写到控制器里面去了。虽然我没用过tp，但就我所知的是tp不支持在命令行下运行控制器，所以他会连接不上。另外，初始化`swoole_client`的时候，加上了`SWOOLE_SOCK_SYNC`选项的话，就不能在php-fpm或apache+mod_php5中使用了。

**Comment by fatrbaby** [comment]
什么叫“在命令行下运行”？
就是在window的cmd，或者mac里的终端，或者是linux的黑窗口中使用`php`命令去执行一个php脚本，而不是用浏览器去访问这个页面执行。
举个栗子：`php example.php`
![fd0af0de-c98a-4b50-a31c-d783b644995b](https://cloud.githubusercontent.com/assets/4350262/13245486/9b0f79a4-da48-11e5-8278-3a92898d9f9c.png)

![ac6237fa-660b-491e-89fe-e7606914f748](https://cloud.githubusercontent.com/assets/4350262/13245495/a5da0c96-da48-11e5-87aa-73ab24f25811.png)

**Comment by weijer** [comment]
唉~ 换成ngnix 可以了~

**Comment by wanyaxing** [comment]
同样遇到这个问题。
swoole_client在命令行下可以运行，用浏览器访问就卡死。
请教有人知道原因吗，谢谢。
