### ISSUE TITLE
同一时间大量ProcessFactory::finish() (ERRNO 1004): send 16 bytes failed, because session#37834232 is closed ，并且cpu瞬间拉满

### ISSUE THREAD

**Issue by XyBob** [swoole/swoole-src#5020]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

    最近线上使用grpc的业务，会不定期发生一瞬间cpu爆满，并在同一时内抛出大量的
   “NOTICE	ProcessFactory::finish() (ERRNO 1004): send 16 bytes failed, because session#37834232 is closed”
   ![image](https://user-images.githubusercontent.com/20701944/230522455-5c1eedd7-a6df-4a67-a527-8386eaac1132.png)
   ![image](https://user-images.githubusercontent.com/20701944/230522509-dc905b47-8ab2-43fe-ad2d-873af4ce1eb6.png)
在业务层并无循环发送, 感觉像是 底层在这个链接不可用时 还在循环发送数据，
我尝试重写ResponseEmitter，在response不可用的时候中断，
![image](https://user-images.githubusercontent.com/20701944/230522715-30ef9431-9009-44c0-bfad-ce8903ae0b5a.png)
但是实验下来还是会发送这种情况

2. What did you expect to see?
     防止cpu瞬间拉满

3. What did you see instead?
    这台机器cpu瞬间爆满，线上使用弹性伸缩

4. What version of Swoole are you using (show your `php --ri swoole`)?
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.6
Built => Jan 12 2022 05:41:55
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1l  24 Aug 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```
5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
   来源于docker 镜像 `hyperf/hyperf:8.0-alpine-v3.12-swoole`
```
uname -a
Linux iZbp1ijpks95uxuaakli81Z 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 Linux

php -v
PHP 7.4.26 (cli) (built: Nov 20 2021 07:13:08) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.26, Copyright (c), by Zend Technologies
```

**Comment by NathanFreeman** [comment]
你这个像是被压测服务器了，有很多连接在数据发送之前就已经断开了

**Comment by matyhtf** [comment]
可以调整一下日志等级，或者使用 5.0 以上版本。当连接断开时不再抛出此错误日志了。
