### ISSUE TITLE
swoole4.8.12 使用php-amqplib报错

### ISSUE THREAD

**Issue by bingcool** [swoole/swoole-src#5022]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

swoole-cli-v4.8.12，在使用php-amqplib这个类库时出现Falt error:
swoole_socket_set_option(): Argument #1 ($socket) must be of type Swoole\Coroutine\Socket, Socket given in file @swoole-src/library/ext/sockets.php on line 157string(103) "swoole_socket_set_option(): Argument #1 ($socket) must be of type Swoole\Coroutine\Socket, Socket given"

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/12829386/230751286-84fd0d85-bd3f-493b-8f01-35f9d8b5ee1c.png">

3. What did you expect to see?

不报错，正常输出, 但swoole-cli-5.0.2 正常

4. What did you see instead?

5. What version of Swoole are you using (show your `php --ri swoole`)?

<img width="673" alt="image" src="https://user-images.githubusercontent.com/12829386/230751297-113befef-2545-45d3-9fe2-b5b6bb7a65f4.png">

6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

/home/wwwroot/swoolefy # uname -a
Linux 08c8cd6c89b8 5.10.124-linuxkit #1 SMP PREEMPT Thu Jun 30 08:18:26 UTC 2022 aarch64 Linux

/home/wwwroot/swoolefy # php -v
PHP 8.1.9 (cli) (built: Aug  5 2022 23:55:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies

/home/wwwroot/swoolefy # gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-alpine-linux-musl/11.2.1/lto-wrapper
Target: aarch64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-11.2.1_git20220219/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=aarch64-alpine-linux-musl --host=aarch64-alpine-linux-musl --target=aarch64-alpine-linux-musl --with-pkgversion='Alpine 11.2.1_git20220219' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,d,objc,go,fortran,ada,jit --with-arch=armv8-a --with-abi=lp64 --disable-libquadmath --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --enable-host-shared --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.1 20220219 (Alpine 11.2.1_git20220219)

**Comment by matyhtf** [comment]
可以关闭 ext-sockets hook ，或者升级到最新版 5.0 。

4.8 因为要同时支持 PHP7，暂时无法变更。 在 PHP8 中所有资源都变成对象了，swoole 的底层实现修改成让 Swoole\Coroutine\Socket 与 php 的 ext-sockets 对象具有亲缘性，绕过了参数检查。
