### ISSUE TITLE
Transfer-encode and content-length ignored

### ISSUE THREAD

**Issue by ImanST** [swoole/swoole-src#5026]
i using storage::disk('s3')->download() for downloading files, file will be download but it can not be open because it's corrupted i guess files more than 8kb will be corrupted.
how can i fix it? 
using laravel 9 

and log will be shown is set transfer-encoding, content-length is ignored  complete log is : 

production.ERROR: Swoole\Http\Response::write(): You have set 'Transfer-Encoding', 'Content-Length' is ignored {"userId":595,"exception":"[object] (ErrorException(code: 0): Swoole\\Http\\Response::write(): You have set 'Transfer-Encoding', 'Content-Length' is ignored 
[stacktrace]
#0 /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /vendor/laravel/octane/src/Swoole/SwooleClient.php(240): Swoole\\Http\\Response->write()
#3 [internal function]: Laravel\\Octane\\Swoole\\SwooleClient->Laravel\\Octane\\Swoole\\{closure}()
#4 16/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(300): fpassthru()
#5 vendor/symfony/http-foundation/StreamedResponse.php(92): Illuminate\\Filesystem\\FilesystemAdapter->Illuminate\\Filesystem\\{closure}()
#6 vendor/laravel/octane/src/Swoole/SwooleClient.php(246): Symfony\\Component\\HttpFoundation\\StreamedResponse->sendContent()
#7 vendor/laravel/octane/src/Swoole/SwooleClient.php(168): Laravel\\Octane\\Swoole\\SwooleClient->sendResponseContent()
#8 vendor/laravel/octane/src/Worker.php(103): Laravel\\Octane\\Swoole\\SwooleClient->respond()
#9 vendor/laravel/octane/bin/swoole-server(124): Laravel\\Octane\\Worker->handle()
#10 [internal function]: {closure}()
#11 vendor/laravel/octane/bin/swoole-server(170): Swoole\\Server->start()
#12 {main}
"} 

1. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.13
Built => Apr 11 2023 16:51:41
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

2. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux irapardaz-app 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.1.17 (cli) (built: Mar 16 2023 14:38:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.17, Copyright (c), by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)

**Comment by NathanFreeman** [comment]
```php
// vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php
public function response($path, $name = null, array $headers = [], $disposition = 'inline')
 {
        $response = new StreamedResponse;

        if (! array_key_exists('Content-Length', $headers)) {
            $headers['Content-Length'] = $this->size($path);
        }

        return $response;
 }
`Content-Length` is set here.
```

```php
if ($octaneResponse->response instanceof StreamedResponse) {
      ob_start(function ($data) use ($swooleResponse) {
          if (strlen($data) > 0) {
               $swooleResponse->write($data);
           }

                return '';
       }, 1);
```
`Swoole\Http\Response::write()` set `Transfer-Encoding` to `chunked`.
These two parameters are conflicting so Swoole will throw a warning.

**Comment by ImanST** [comment]
What should I do for fixing this ? Should I upgrade swoole to latest version or downgrade to lower version ?

**Comment by ImanST** [comment]
@NathanFreeman actually process was worked fine untill I updated server packages and swoole has been updated, this problem happend.

**Comment by ImanST** [comment]
How can I add these changes to my source, I should upgrade swoole to latest version ?
I'm on 4.8.13
