### ISSUE TITLE
Server::check_worker_exit_status(): worker(pid=89131, id=4) abnormal exit, status=0, signal=11 A bug occurred in Swoole-v5.0.0

### ISSUE THREAD

**Issue by Gitchenjiangbin** [swoole/swoole-src#5031]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
在运行hyperf微服务grpc时出现的问题。
操作和hyperf文档一般无二 [hyper-grpc](https://hyperf.wiki/3.0/#/zh-cn/grpc)
127.0.0.1:9501/hello 调用了grpc client 调用
如下为client代码：
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/37992814/232305504-1470349a-d42d-4917-abf1-acf2ec07ca84.png">

2. What did you expect to see?
原先以为能调用成功，返回9503grpc服务的sayhello消息

3. What did you see instead?
<img width="932" alt="image" src="https://user-images.githubusercontent.com/37992814/232305723-4ece4f21-6574-4bec-8eed-d5dbb2fe17e7.png">

4. What version of Swoole are you using (show your `php --ri swoole`)?
<img width="425" alt="image" src="https://user-images.githubusercontent.com/37992814/232305753-93cfb855-4e11-462b-9537-274bbe06fdbe.png">

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
OS: 
Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64
GCC_VERSION: 
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
PHP_VERSION : 
PHP 8.1.17 (cli) (built: Mar 16 2023 13:07:08) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.17, Copyright (c), by Zend Technologies

**Comment by NathanFreeman** [comment]
这个是偶发性的错误吗，是的话看看能不能提供一下复现代码或者用valgrind检查一下

**Comment by Gitchenjiangbin** [comment]
不是偶发的
代码：https://github.com/Gitchenjiangbin/grpc-demo
我的mac不支持valgrind和gdb，我在尝试用windows来试试

**Comment by Gitchenjiangbin** [comment]
用windows和docker环境都无法重现错误，尝试过升级和降级swoole都没有效果。
可能是m1芯片对有些东西兼容不好，暂时用docker环境代替了。
以下是Dockerfile有需要的可以做个参考：
```
FROM php:8.1
# 安装必要的工具和依赖
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
        libssl-dev \
        zlib1g-dev \
        libzip-dev \
        autotools-dev \
        automake \
        libtool \
        protobuf-compiler \
        cmake \
        vim \
        net-tools \
    && rm -rf /var/lib/apt/lists/*

# 安装 Swoole、Redis、grpc 扩展，将多个RUN合成一个，减少镜像的大小
RUN pecl install swoole && docker-php-ext-enable swoole \
    && echo "swoole.use_shortname='Off'" >> /usr/local/etc/php/conf.d/docker-php-ext-swoole.ini \
    && pecl install redis && docker-php-ext-enable redis && docker-php-ext-install pcntl \
    && pecl install grpc && docker-php-ext-enable grpc \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && docker-php-ext-enable grpc \
    && echo 'grpc.enable_fork_support=1' >> /usr/local/etc/php/conf.d/docker-php-ext-grpc.ini \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# 设置工作目录
WORKDIR /var/www/html

# 暴露端口
EXPOSE 9501
```

```
docker build -t env-grpc .
docker run -it -p 9501:9501  -v 宿主机工作目录:/var/www/html --name test  -d env-grpc 
```
