### ISSUE TITLE
undefined symbol: curl_multi_ce

### ISSUE THREAD

**Issue by Rodots** [swoole/swoole-src#5041]
`PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/lib64/php/modules/swoole.so (/usr/lib64/php/modules/swoole.so: undefined symbol: curl_multi_ce), /usr/lib64/php/modules/swoole.so.so (/usr/lib64/php/modules/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

Swoole：5.0.3
系统：AlmaLinux 9.1
Linux内核：5.14.0-162.23.1.el9_1.x86_64
PHP：8.2.5
GCC：Package gcc-11.3.1-2.1.el9.alma.x86_64 is already installed.
OpenSSL：Package openssl-1:3.0.1-47.el9_1.x86_64 is already installed.
Curl：Package libcurl-7.76.1-19.el9_1.2.x86_64 is already installed.
我已经安装了openssl和curl软件包，PHP也加载了这两个模块，但是当我将swoole.so引入php.ini后，输入PHP -m命令报错以上内容

编译安装选项 --enable-openssl --enable-swoole-curl --enable-brotli --enable-debug

**Comment by Rodots** [comment]
编译安装的用我的选项是--enable-openssl --enable-swoole-curl --enable-brotli --enable-debug

**Comment by jingjingxyk** [comment]
尝试一下 去掉这个参数  `--enable-swoole-curl `

**Comment by NathanFreeman** [comment]
不用在php.ini里面写`extension=swoole.so`，跟其它用pecl安装的扩展一样，写一份独立的swoole.ini，让php.ini自动引用就行，其中要保证curl要在swoole之前加载

**Comment by matyhtf** [comment]
把 extension=swoole.so 放到 extension=curl.so 后面

**Comment by fundawang** [comment]
我觉得开启了`enable-swoole-curl`的时候，应该链接到 libcurl，不能指望 php-curl 的extension把curl装进来。

**Comment by jingjingxyk** [comment]
@fundawang  这是 链接顺序的问题。先链接liubcurl ，swoole 才能连接到 libcurl
