### ISSUE TITLE
swoole-cli 5.0.3 macos 执行错误

### ISSUE THREAD

**Issue by zhangyu19851112** [swoole/swoole-src#5048]
- 系统版本
Darwin MacBook-Pro-2.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

- 运行 ./swoole-cli -v
Swoole 5.0.2 (cli) (built: Feb 17 2023 19:08:08) (NTS)

- 运行 ./swoole-cli -v        
dyld[46489]: Library not loaded: /usr/local/opt/libunistring/lib/libunistring.2.dylib
  Referenced from: <9CC1ED9F-DBE0-33D7-8398-ABDF1E32F32A> /Users/z/gitlab/api/swoole-cli
  Reason: tried: '/usr/local/opt/libunistring/lib/libunistring.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libunistring/lib/libunistring.2.dylib' (no such file), '/usr/local/opt/libunistring/lib/libunistring.2.dylib' (no such file), '/usr/local/lib/libunistring.2.dylib' (no such file), '/usr/lib/libunistring.2.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/libunistring/1.1/lib/libunistring.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/libunistring/1.1/lib/libunistring.2.dylib' (no such file), '/usr/local/Cellar/libunistring/1.1/lib/libunistring.2.dylib' (no such file), '/usr/local/lib/libunistring.2.dylib' (no such file), '/usr/lib/libunistring.2.dylib' (no such file, not in dyld cache)
[1]    46489 abort      ./swoole-cli -v

**Comment by matyhtf** [comment]
5.0.3 mac 版本存在一些问题，正在解决。稍后会重新上传
