### ISSUE TITLE
BUG：http_server 当客户端 post 的数据包长度大于1024时，服务端收不到任何响应

### ISSUE THREAD

**Issue by yelo-17133** [swoole/swoole-src#505]
setting: {"daemonize":false,"dispatch_mode":3,"worker_num":4,"max_request":1024,"open_tcp_nodelay":true,"open_tcp_keepalive":false,"open_http_protocol":true,"package_max_length":2097152,"user":"www-data","group":"www-data"}

当 curl_setopt($curl, CURLOPT_POSTFIELDS, $postData) 中的 $postData 长度超过 1024 时，服务端无任何反应。onRequest 进不去

已测试不是客户端代码问题，换到其他http server上都可以正常接收。

**Comment by matyhtf** [comment]
swoole版本多少？

**Comment by matyhtf** [comment]
贴出你的uname、PHP版本等信息

**Comment by yelo-17133** [comment]
ubuntu 12.04 x64, php 5.6.17, swoole 1.8.0

Linux ubuntu 3.11.0-15-generic #25~precise1-Ubuntu SMP Thu Jan 30 17:39:31 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

php.ini post_max_size 8M

**Comment by yelo-17133** [comment]
是否已确认是bug？ 如果是，当有解决办法时请告诉我； 如果不是，请告诉我要如何调整配置。3x~~

**Comment by matyhtf** [comment]
请使用最新的github master分支代码测试，看看是否有问题。
我这里经过测试，POST大数据没问题。

**Comment by matyhtf** [comment]
请使用最新的 1.8.2 代码

**Comment by koog** [comment]
最新的1.8.13稳定版还是有这个bug
libcurl在post数据大于1024个字节的时候，会有个100 continue逻辑，应该是swoole没有实现这个逻辑
参考：  http://www.cnblogs.com/zhengyun_ustc/p/100continue.html

**Comment by matyhtf** [comment]
修改curl配置去掉100continue
