### ISSUE TITLE
咨询一下，nginx stream负载到swoole tcp server， 如何能拿到实际客户端Ip

### ISSUE THREAD

**Issue by netyum** [swoole/swoole-src#5051]
咨询一下，nginx 负载到swoole tcp server， 如何能拿到实际客户端Ip

**Comment by jingjingxyk** [comment]
办法一：  nginx Stream Transparent Proxy  （nginx 四层透明代理） 
办法二：  TCP over TCP  ; 
办法三：  TCP over UDP  ;

从OSI模型 看 TCP 工作传输层 :     https://blog.csdn.net/dianqicyuyan/article/details/121798895
TCP/IP的四元组 五元组 七元组：  https://blog.csdn.net/AAA821/article/details/76022315


简述：
办法一 ：
> 参考地址： https://www.nginx.com/blog/ip-transparency-direct-server-return-nginx-plus-transparent-proxy/

> 数据包到达  nginx  ，`nginx ` 对数据报文进行处理并转发。

> nginx 处理内容： 替换报文的目标地址、目标端口 。替换为 为 `swoole tcp serer`  IP地址和端口 。 （备注：此时报文的 源地址和源端口 ，仍然还是客户端的信息）

> 报文到达  `swoole tcp server`  处理 并返回； 修改路由规则，让swoole tcp 返回的报文 ，到达nginx.

>nginx 接收到 swoole tcp 返回的报文 ，修改报文的源地址和源端口号为 nginx 地址和端口号 

> 使用 （nftables/iptables ） 和 iproute2  实现

![image](https://github.com/swoole/swoole-src/assets/6836228/ee10e2d1-648f-4a85-9410-e8aae83b8e67)


办法二 和 办法三 ：
原理： 生成新的报文，把 源报文塞到 新报文里。

![image](https://github.com/swoole/swoole-src/assets/6836228/874bf74f-4b1a-43b9-bd20-1bcc073e68b1)



![image](https://github.com/swoole/swoole-src/assets/6836228/49d9fa93-c756-4eac-b9fd-d22af584628b)


参考文档： 

https://blog.crazytaxii.com/posts/an_introduction_2_tunnel/
https://zhuanlan.zhihu.com/p/32486650

**Comment by matyhtf** [comment]
七层代理无法得到真实的客户端 IP 地址，因此一般只将 nginx 作为 7层代理的 http 网关，在 HTTP 头中增加 X_REAL_IP 作为客户端 IP。

**Comment by netyum** [comment]
都试过，没成功， 感觉swoole底层可以判断proxy protocol进行解析。
