### ISSUE TITLE
swoole mqtt subscribe.php 使用一段时间后 $buffer = $client->recv();  接收不到mqtt消息了

### ISSUE THREAD

**Issue by dengweicai** [swoole/swoole-src#5052]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

我使用 swoole mqtt的subscribe.php 在后台运行一段时间(1-2天)后，就会死掉，下面的ping 还是执行，但是 recv函数收不到 消息。
运行这个程序，我使用  docker exec -it emqtt-bench ./emqtt_bench conn -h xxx  -p 1883 -c -20000 --username xxx --password xxx 进行压力测试的话，大概到 15000左右就会报错，同时后面 subscribe.php中的 recv 接收不了新的数据了

2. What did you expect to see?

我希望 报错后可以继续运行， recv 可以继续收到后面的消息

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.12
Built => Oct 15 2022 15:04:22
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.10.0
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux iZwz92v9xcjoph6qyuhvp9Z 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
PHP 7.3.13 (cli) (built: Oct 28 2022 11:10:13) ( NTS )

**Comment by matyhtf** [comment]
检查 Client recv 返回值和错误码，增加断线重连的逻辑
