### ISSUE TITLE
build on mac 10.11.3 EI Capitan with jemalloc

### ISSUE THREAD

**Issue by lscgzwd** [swoole/swoole-src#506]
System: MacOS 10.11.3 EI Captian
swoole: 1.8.0 1.8.1
php:7.0.2

config params:

./configure --enable-swoole --with-swoole --enable-async-mysql --enable-sockets --enable-async-redis --enable-async-httpclient --enable-openssl --enable-jemalloc

make

sudo make install
then run php command :  php -m

segmentfault ....

run any php command will segmentfault, like: php -i php --ini php -a
all with segmentfault.

Reading symbols for shared libraries .................................................................................................................................................................... done
#0  0x00007fff82b99f01 in free ()
(gdb) bt
#0  0x00007fff82b99f01 in free ()
#1  0x00007fff6539ddb0 in ?? ()
#2  0x00007fff653a537f in ?? ()
#3  0x00007fff94b2274d in dlclose ()
#4  0x00000001036a8996 in module_destructor ()
#5  0x00000001036a14d9 in module_destructor_zval ()
#6  0x00000001036b34b2 in zend_hash_graceful_reverse_destroy ()
#7  0x00000001036a163a in zend_shutdown ()
#8  0x000000010364be90 in php_module_shutdown ()
#9  0x0000000103728700 in main ()

./configure --enable-swoole --with-swoole --enable-async-mysql --enable-sockets --enable-async-redis --enable-async-httpclient --enable-openssl   without jemalloc is ok.

so, i think swoole not work with jemalloc on mac os

**Comment by matyhtf** [comment]
可能与swoole扩展无关，建议编译debug版本的PHP，查看core信息。
