### ISSUE TITLE
http get请求中带有中文参数，请求失败

### ISSUE THREAD

**Issue by maliangbin** [swoole/swoole-src#5060]
http get请求中带有中文参数，请求失败,查询日志提示：
![image](https://github.com/swoole/swoole-src/assets/21885927/605d8c1a-f756-402e-9593-8d1366f280fc)

1. What did you do? If possible, provide a simple script for reproducing the error.

> 首先在服务器上启动了一个简单的服务，代码如下

```php
<?php

declare(strict_types=1);
$http = new Swoole\Http\Server('127.0.0.1', 9501);

$http->on('start', function ($server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$http->on('request', function ($request, $response) {
    var_dump($request);
    $response->header('Content-Type', 'text/plain');
    $response->end('Hello World');
});

$http->start();
``` 
当在命令行使用curl get请求中带有中文参数时，请求失败，命令如下:
`curl 'http://127.0.0.1:9501?search_text=中文'`
错误如下：
![image](https://github.com/swoole/swoole-src/assets/21885927/95e9ca23-3807-42b8-bd1c-a888a12335f4)

2. What did you expect to see?

> 期望结果是curl get请求结果输出 `Hello World`

3. What did you see instead?

> 当curl get请求中带有中文参数时，目前实际运行结果是空白，且http status code ：400

4. What version of Swoole are you using (show your `php --ri swoole`)?

> ![image](https://github.com/swoole/swoole-src/assets/21885927/8cad7ec8-c610-4ed8-8fdf-608a74848a25)

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

> 相关版本信息如下：

1.  linux版本：`Linux plusmapifast2 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
2. php版本：
![image](https://github.com/swoole/swoole-src/assets/21885927/0efc95e3-6072-4510-82ed-50422c23bddb)
3. gcc编译器版本信息：
![image](https://github.com/swoole/swoole-src/assets/21885927/2e6ab2b5-88b9-4ba3-bc66-a81775e54840)

**Comment by matyhtf** [comment]
You should urlencode first
