### ISSUE TITLE
WARNING	Server::check_worker_exit_status(): worker(pid=2410, id=5) abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by vijay7777777** [swoole/swoole-src#5061]
$curl = curl_init();
        
        curl_setopt($curl, CURLOPT_URL, $url);
     
        curl_setopt($curl, CURLOPT_HEADER, 0);
     
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
       
        curl_setopt($curl, CURLOPT_POST, 1);
    
        $post_data = $array;
        curl_setopt($curl, CURLOPT_POSTFIELDS, $post_data);
      
        $data = curl_exec($curl);

        curl_close($curl);

        return json_decode($data, true);

[2023-05-29 20:14:03 $2404.0]	WARNING	Server::check_worker_exit_status(): worker(pid=2410, id=5) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v5.0.3, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 x86_64
GCC_VERSION: Apple LLVM 14.0.3 (clang-1403.0.22.14.1)
OPENSSL_VERSION: OpenSSL 1.1.1s  1 Nov 2022
PHP_VERSION : 8.0.27

[INFO] Worker#5 started.

**Comment by vijay7777777** [comment]
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.3
Built => May 29 2023 13:40:54
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1s  1 Nov 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.17.1
zlib => 1.2.11
brotli => E16777225/D16777225
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

**Comment by matyhtf** [comment]
@vijay7777777 上面的代码只是一个片段，请提供一份完整的可稳定重现的代码

**Comment by bafeiyu** [comment]
[2023-10-19 09:34:42 $20.0]     WARNING Server::check_worker_exit_status(): worker(pid=1711, id=2) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v5.0.3, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Linux 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64
GCC_VERSION: 10.3.1 20210424
OPENSSL_VERSION: OpenSSL 1.1.1l  24 Aug 2021
PHP_VERSION : 8.0.12

[INFO] Worker#2 started.

**Comment by indextank** [comment]
我在WSL2环境下也出现这样的错误，环境重装也无效。 代码之前在Linux下都是正常的，在WSL2+docker-desktop环境下启动就报错。
于是，我换成了官方的hyperf-skeleton，直接运行：php bin/hyperf.php start，也是出现这样的错误。

![1](https://github.com/swoole/swoole-src/assets/6389841/73a124aa-23b6-45a2-99c0-c6235ccfa6f3)
![2](https://github.com/swoole/swoole-src/assets/6389841/4f831a99-a15e-4b36-8fb6-a2182dc04242)

**Comment by chunio** [comment]
vi /usr/local/php/etc/php.ini >> ;zend_extension = xdebug.so;

**Comment by matyhtf** [comment]
Please update to the latest version and check whether the relevant dependent libraries are correct. If this problem still exists, please resubmit the issue
