### ISSUE TITLE
::exec 执行一个90s的外部程序 ，在67s就异常退出了,怎么设置运行时间，PHP8.2.6+5.0.3

### ISSUE THREAD

**Issue by mdys** [swoole/swoole-src#5062]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
如题，centos7.9  PHP8.2.6+swoole 5.0.3，需要在task中执行一个 exec 外部程序，外部程序完成时间不定，最长可能120S。但在swoole下最多只能执行67s就返回了空值，想问下如何调整加长执行时间

2. What did you expect to see?
```php
$serv->set([
                         'worker_num'      => swoole_cpu_num()*2,
                         'max_request'     => 4000,                        
                         'enable_static_handler' => true,  
                         'enable_coroutine' => true,
                         'task_enable_coroutine'=> true, 
             		  'task_use_object' => true, 
                         'task_worker_num' => swoole_cpu_num()*2,                         ' 
                         'hook_flags'=> SWOOLE_HOOK_ALL                          
                       ]);

public function onTask($serv, $task) {
    $asr_output_arr = Co::exec("/home/bin/onnx --quantize true --wav-path /home/test.mp3",true);
    var_dump($asr_output_arr);
   // 这个exec 时间可能最长120s，目前只能执行最多67s就失败了，请问如何设置能加长超时时间
}
```
直接用 php  是可以正常返回结果的。

```php
<?php
$asr_output_arr = shell_exec("/home/bin/onnx --quantize true --wav-path /home/test.mp3");
var_dump($asr_output_arr);
?>
```

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
gcc (GCC) 11.2.1

**Comment by NathanFreeman** [comment]
你是用https://github.com/onnx/onnx这个执行命令的吗？

**Comment by mdys** [comment]
> 你是用 https://github.com/onnx/onnx 这个执行命令的吗？
感谢回复！
不是的 ，/usr/bin/onnx 只是我一个例子  ，我意思 task协程下 若我 exec（“/usr/bin/onnx”） 执行时间比较长的话 ，这个bin程序输出的结果 我就获取不到了， 但不用task协程的话是可以获取到的。只是不用协程的话 我没法做并发了。

**Comment by NathanFreeman** [comment]
可以在$serv->set()中加上['socket_read_timeout' => 200]这个配置加大超时时间

**Comment by mdys** [comment]
感谢 感谢 ，解决问题了！
