### ISSUE TITLE
为什么think-swoole设置的链接池为100，最后链接数据会超过100？

### ISSUE THREAD

**Issue by Funny-dot** [swoole/swoole-src#5071]
thinkphp6
swoole版本 Version => 4.8.11
thinkphp config/swoole.php 设置
` 
  'coroutine'=>[
        'enable'=>true,
        'flags' => SWOOLE_HOOK_ALL
    ],
//连接池
    'pool'       => [
        'db'    => [
            'enable'        => true,
            'max_active'    => 100,
            'max_wait_time' => 5,
        ],
        'cache' => [
            'enable' => true,
            'max_active' => 100,
            'max_wait_time' => 20,
        ],
        //自定义连接池
    ],`

项目运行2天后去查看tcp链接数量
[root@php-swoole-54999bf74c-vl4cz /]# netstat -n | awk '/^tcp/ {++S[$NF]} END {for(a in S) print a, S[a]}'
ESTABLISHED 1758
TIME_WAIT 878

redis链接的内部服务器，使用命令查询
`netstat -nat | grep 192.168.0.230:6379`

查看链接6379端口的链接跟查询tcp链接数量相差不大

为什么会超过链接池设置的大小呢？我看think-swoole扩展也是使用的swoole的链接池

**Comment by he426100** [comment]
max_active * worker_num
