### ISSUE TITLE
从5.0.2版本开始，Process::signal收到不信号回调

### ISSUE THREAD

**Issue by bobyang007** [swoole/swoole-src#5080]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
Process::signal(SIGTERM, function () {
                echo '收到退出信号';
                $this->pool->getProcess()->exit();
            });

2. What did you expect to see?
从5.0.2版本开始，该注册收不到信号回调，切回5.0.1,或4版本均正常

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.1
Built => Jun 26 2023 16:56:00
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.0.2 15 Mar 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
c-ares => 1.18.1
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled
coroutine_postgresql => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by NathanFreeman** [comment]
麻烦提供一下复现代码。

**Comment by bobyang007** [comment]
<?php

use Swoole\Process;
use Swoole\Coroutine;

echo 'Main Process kill -15 ' . posix_getpid() . "\n" . 'swoole version:' . swoole_version() . "\n";
$pool = new Process\Pool(5);
$pool->set(['enable_coroutine' => true]);
$pool->on('WorkerStart', function (Process\Pool $pool, $workerId) {
    /**
     * 当前是 Worker 进程
     */
    static $running = true;
    Process::signal(SIGTERM, function () use (&$running) {
        $running = false;
        echo "TERM\n";
    });
    echo "[Worker #{$workerId}] WorkerStart, pid: " . posix_getpid() . "\n";
    while ($running) {
        Coroutine::sleep(1);
        echo 'sleep 1';
    }
    echo "[Worker #{$workerId}] WorkerStart, pid: " . posix_getpid() . " over\n";
});
$pool->on('WorkerStop', function (\Swoole\Process\Pool $pool, $workerId) {
    echo "[Worker #{$workerId}] WorkerStop\n";
});
$pool->start();


![image](https://github.com/swoole/swoole-src/assets/54702711/79c03c8d-00c9-4074-b984-6de5f013b2f3)

![image](https://github.com/swoole/swoole-src/assets/54702711/b1db0b91-c2f9-474f-b042-62f792c11fb3)

![image](https://github.com/swoole/swoole-src/assets/54702711/1e0a9798-1be3-4b0b-a180-e8ca2a3dcab6)

![image](https://github.com/swoole/swoole-src/assets/54702711/da1c6805-b2e0-4365-95e8-86e9c8e22f3e)

![image](https://github.com/swoole/swoole-src/assets/54702711/70770208-1b8f-4e01-b8ca-96bf4787df15)

**Comment by NathanFreeman** [comment]
我没法复现出来，在master分支，V5.0.1版本上，发送`SIGTERM`给主进程可以终止程序运行，发送`SIGTERM`给子进程，子进程可以退出并且被父进程重新拉起。

**Comment by bobyang007** [comment]
5.0.2及之后，是可以结束子进程
但是在些版本之前，使用Process::signal注册的信号回调，是会被执行的
5.0.2及之后，这个回调不会被执行，进程是直接被干死了，就实现不了优雅退出服务了

**Comment by bobyang007** [comment]
你看我上面发的图，5.0.1及之前的版本，收到15信号后，是会输出TERM,及进程循环退出时打印的输出
5.0.2及之后，是进程直接死了，没有退出信号输出，没有进程结束输出

**Comment by bobyang007** [comment]
![Uploading image.png…]()
5.0.2版本之后，这里的没有执行

**Comment by bobyang007** [comment]
![image](https://github.com/swoole/swoole-src/assets/54702711/df825889-a682-4f1d-b0d7-7fa852e05cff)
5.0.2版本之后，这里的没有执行

**Comment by NathanFreeman** [comment]
![微信截图_20230627144848](https://github.com/swoole/swoole-src/assets/33935209/262c50d3-f846-4f05-95f1-cf8da0754210)
![微信截图_20230627145108](https://github.com/swoole/swoole-src/assets/33935209/b915f5a1-c3de-42d7-ae85-102b48c13892)

我这里测试了可以执行，你是在linux环境下的测试的吗？

**Comment by bobyang007** [comment]
buntu 22.04

**Comment by NathanFreeman** [comment]
复现出来了，我看看是为啥

**Comment by NathanFreeman** [comment]
Fixed by https://github.com/swoole/swoole-src/pull/5081
