### ISSUE TITLE
swoole-1.8.0-stable 发现 segfault 问题!

### ISSUE THREAD

**Issue by designinlife** [swoole/swoole-src#509]
swoole-1.8.0-stable 出现如下问题：
使用 ulimit -c unlimited 命令之后没有发现 core 文件信息.

Jan 29 11:01:20 centos-vps-104 kernel: show_signal_msg: 5392 callbacks suppressed
Jan 29 11:01:20 centos-vps-104 kernel: php[6518]: segfault at 7f174881afa8 ip 00007f17a14b5e10 sp 00007ffccd0ef278 error 4 in swoole.so[7f17a147f000+6b000]
Jan 29 11:01:20 centos-vps-104 kernel: php[6520]: segfault at 7f174881afa8 ip 00007f17a14b5e10 sp 00007ffccd0ef278 error 4 in swoole.so[7f17a147f000+6b000]
Jan 29 11:01:20 centos-vps-104 kernel: php[6522]: segfault at 7f174881afa8 ip 00007f17a14b5e10 sp 00007ffccd0ef278 error 4 in swoole.so[7f17a147f000+6b000]
Jan 29 11:01:20 centos-vps-104 kernel: php[6524]: segfault at 7f174881afa8 ip 00007f17a14b5e10 sp 00007ffccd0ef278 error 4 in swoole.so[7f17a147f000+6b000]
Jan 29 11:01:20 centos-vps-104 kernel: php[6527]: segfault at 7f174881afa8 ip 00007f17a14b5e10 sp 00007ffccd0ef278 error 4 in swoole.so[7f17a147f000+6b000]
Jan 29 11:01:20 centos-vps-104 kernel: php[6529]: segfault at 7f174881afa8 ip 00007f17a14b5e10 sp 00007ffccd0ef278 error 4 in swoole.so[7f17a147f000+6b000]
Jan 29 11:01:20 centos-vps-104 kernel: php[6531]: segfault at 7f174881afa8 ip 00007f17a14b5e10 sp 00007ffccd0ef278 error 4 in swoole.so[7f17a147f000+6b000]
Jan 29 11:01:20 centos-vps-104 kernel: php[6523]: segfault at 7f174881afa8 ip 00007f17a14b5e10 sp 00007ffccd0ef278 error 4 in swoole.so[7f17a147f000+6b000]
Jan 29 11:01:20 centos-vps-104 kernel: php[6530]: segfault at 7f174881afa8 ip 00007f17a14b5e10 sp 00007ffccd0ef278 error 4 in swoole.so[7f17a147f000+6b000]
Jan 29 11:01:20 centos-vps-104 kernel: php[6533]: segfault at 7f174881afa8 ip 00007f17a14b5e10 sp 00007ffccd0ef278 error 4 in swoole.so[7f17a147f000+6b000]

**Comment by matyhtf** [comment]
http://wiki.swoole.com/wiki/page/10.html
http://wiki.swoole.com/wiki/page/p-server/sysctl.html

**Comment by matyhtf** [comment]
1.8.x 分支目前确实存在一些问题，最新版本已经修复。

**Comment by designinlife** [comment]
发现部分机器会有问题!

**Comment by matyhtf** [comment]
可以先用1.7.22版本，1.8.x需要再迭代几个版本才会比较稳定。
