### ISSUE TITLE
协程TCP。怎么在其他业务类中给对应连接单独推送消息

### ISSUE THREAD

**Issue by yangtiejiang** [swoole/swoole-src#5102]
我使用的是4.8.12版本的协程TCP，硬件会订阅这个TCP连接，我需要在项目中其他业务类里指定对应的硬件TCP链接推送消息  有什么办法可以在其他业务类中也能主动给对应硬件单独推送消息

**Comment by NathanFreeman** [comment]
你可以把客户端对应的`fd`保存起来，在其他业务中指定`fd`用`Swoole\Server::send()`发送

**Comment by yangtiejiang** [comment]
> 你可以把客户端对应的`fd`保存起来，在其他业务中指定`fd`用`Swoole\Server::send()`发送

这个我明白，但是文档里"服务端(异步风格)"我实在找不到其他业务类能通过fd发回给客户端的方法

**Comment by NathanFreeman** [comment]
https://wiki.swoole.com/#/server/port?id=httpwebsocket

你可以试试启动一个http server 先，然后使用多端口监听的方式启动一个tcp server，这样其他业务就能够通过http接口访问tcp server。

代码大概是这样的
```php
<?php
$globalFd = 0;
$http = new Swoole\Http\Server('127.0.0.1', 9501);
$tcp_server = $http_server->listen('127.0.0.1', 9999, SWOOLE_SOCK_TCP);
$tcp_server->set([]);
$tcp_server->on('receive', function ($server, $fd, $threadId, $data) {
	global $globalFd;
    $globalFd = $fd;
});

$http->on('request', function ($request, $response) use ($http) {
	global $globalFd;
	$tcp_server->send($globalFd, "test");
});

$http->start();
```
