### ISSUE TITLE
MAC M1芯片，用swoole-cli，CURL请求或者携程请求一直会报DNS超时

### ISSUE THREAD

**Issue by fengyikang88** [swoole/swoole-src#5103]
```
[DEBUG] Event Hyperf\FramTe0    getimagesize(https://st1o/ 1oroe6fla7d7314d.png
[ERROR] ErrorException: getimagesize(r-r."hund /2820-03/16/16f5e6f77314d. mno): Failed to open stream: DS LookuD resolve timeout in /users/ fy/Desktop/w/cataboard _hyperf/app/comand/itmicomand.,pip:33Stack trace:dler\Listener\{closure}(2,'getimagesize(ht...",'/users/fyk/Desk...', 33)
#0 [internal function]: Hyperf Exception
#1 /Users/fyk/Desktop/WWW/dataBoard_hyperf/app/Commo(33): getimagesize( https://static
#2 /Users/fyk/Desktop/WWw/dataBoard_hyperf/ved.php(428): App\Command\HtmLCommand->handle()
#3[internal function]: Hyperf\Command\Command->Hyperf\Command\{closure}()
#4 [main}
```
，用这个函数getimagesize或者其他带有curl请求都会报超时，自己编译的swoole版本没问题。

**Comment by matyhtf** [comment]
查看一下 /etc/resole.conf 配置，通过 nslookup 命令，查看是否可以正常解析

**Comment by fengyikang88** [comment]
nslookup可以解析，但是用swoole-cli还是不行，用自己编译到本地swoole.so是可以的。用的版本是@MacBook server % swoole5 -v                                                    
Swoole 5.0.3 (cli) (built: May  9 2023 11:27:01) (NTS

**Comment by fengyikang88** [comment]
> 

![image](https://github.com/swoole/swoole-src/assets/54435163/16e42fcc-c1a8-48ae-bd9f-0cb18b7b3d23)

swoole5 % otool -L  ./swoole-cli
./swoole-cli:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
	/usr/lib/libsasl2.2.dylib (compatibility version 3.0.0, current version 3.15.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
	/usr/lib/libnetwork.dylib (compatibility version 1.0.0, current version 1.0.0)
fyk@MacBook swoole5 % file ./swoole-cli
./swoole-cli: Mach-O 64-bit executable arm64

**Comment by jingjingxyk** [comment]
@fengyikang88 
本地试试这个代码，看看是否也报错
```php
<?php

\Co\run(function() {
    go(function () {
        $filename='https://www.swoole.com/dist/skin1/images/project-0.png';
        $size = getimagesize($filename);
        var_dump($size);
    });
});

```

getimagesize 函数用法：https://www.php.net/manual/zh/function.getimagesize.php

**Comment by fengyikang88** [comment]
> @fengyikang88 本地试试这个代码，看看是否也报错
> 
> ```
> <?php
> 
> \Co\run(function() {
>     go(function () {
>         $filename='https://www.swoole.com/dist/skin1/images/project-0.png';
>         $size = getimagesize($filename);
>         var_dump($size);
>     });
> });
> ```
> 
> getimagesize 函数用法：https://www.php.net/manual/zh/function.getimagesize.php
> 
> 此函数要求 filename 是有效的图像文件。如果提供的是非图像，可能会错误的识别为图像且函数会成功返回，但数组可能包含无意义的值。

@MacBook Desktop % swoole5 index.php
Warning: getimagesize(https://www.swoole.com/dist/skin1/images/project-0.png): Failed to open stream: DNS Lookup resolve timeout in /Users/fyk/Desktop/index.php on line 6
bool(false) 
还是不行报错，我的电脑是M1pro的芯片，macbook pro14寸的，就是用swoole-cli不行，自己编译swoole拓展到本地的php是没问题的。

**Comment by jingjingxyk** [comment]
@fengyikang88 ，我没有 M1pro 。

提议，你可以自己编译 swoole-cli  ， 看看自己编译出来的是否也有同样的错误

```shell
git clone -b main --recursive  https://github.com/swoole/swoole-cli.git 

cd swoole-cli
composer update 
php prepare.php
bash make.sh all-library
bash make.sh config 
bash make.sh build 

# 编译好
./bin/swoole-cli -v 
./bin/swoole-cli --ri swoole 

```

**Comment by matyhtf** [comment]
无法重现。
