### ISSUE TITLE
Deprecated: stream_select(): Passing null to parameter #5 ($microseconds) of type ?int is deprecated

### ISSUE THREAD

**Issue by ging-dev** [swoole/swoole-src#5104]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
```php
<?php
use function Co\run;


run(function () {
    $socket1 = stream_socket_server("tcp://0.0.0.0:8000");
    $socket2 = stream_socket_client("tcp://example.com:80");
    
    stream_set_blocking($socket1, 0);
    stream_set_blocking($socket2, 0);
    
    while (true) {
      $read = [$socket1, $socket2];
      $write = [$socket2];
      $except = null;
      $timeout = null;
      stream_select($read, $write, $except, $timeout, null);
    
      if (in_array($socket1, $read)) {
        $client = stream_socket_accept($socket1);
        fwrite($client, "Hello world!\n");
        fclose($client);
      }
      if (in_array($socket2, $read)) {
        $response = fread($socket2, 1024);
        echo $response;
      }
      if (in_array($socket2, $write)) {
        fwrite($socket2, "GET / HTTP/1.1\r\nHost: example.com\r\n\r\n");
      }
    }
});
```

2. What did you expect to see?
No error message

3. What did you see instead?
`Deprecated: stream_select(): Passing null to parameter #5 ($microseconds) of type ?int is deprecated`

4. What version of Swoole are you using (show your `php --ri swoole`)?
`Swoole 5.0.3 (cli) (built: Apr 26 2023 10:10:48) (NTS)`

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
`php 8.1`

**Comment by NathanFreeman** [comment]
Fix by https://github.com/swoole/swoole-src/pull/5112
