### ISSUE TITLE
Debian vs Alpine images

### ISSUE THREAD

**Issue by ipejasinovic** [swoole/swoole-src#5105]
I wanted to ask, is there some big difference between this two official images, because for development I've used Debian, but for production is Alpine, and now after entering production, several things pops up:
1. Server just stops responding, but totally random. Sometimes in few hours, sometimes in few days, but it always has around 500.000 REST requests per day. Service is very simple, passing REST to GRPC service, no DB, Curl or Redis used.
2. is_integer fails on Alpine, when number is bigger than 32-bit integer, even host is 64-bit
3. bcmath isn't included in Alpine image by default, but in Debian it is

GRPC service is tested, handled all possible problems: unable to connect, no response, broken connection, grpc error etc...
Swoole used is 5.0.3, PHP 8.1, process mode

**Comment by matyhtf** [comment]
Please set php `error_log` , set the `log_file` for swoole, whether there is a fatal error and observe the `dmesg` log of the OS, whether there is a crash
