### ISSUE TITLE
swoole http server 重定向BUG

### ISSUE THREAD

**Issue by viile** [swoole/swoole-src#511]
POST提交到一个页面,然后服务器返回重定向,会报错,下面是日志

[/data/php/swoole-src/src/reactor/ReactorPoll.c:245@swReactorPoll_wait]Event: fd=13|from_id=1|type=11
[/data/php/swoole-src/src/reactor/ReactorPoll.c:245@swReactorPoll_wait]Event: fd=14|from_id=1|type=1
[/data/php/swoole-src/src/network/Server.c:131@swServer_master_onAccept][Master] Accept new connection. maxfd=14|reactor_id=1|conn=16
[/data/php/swoole-src/src/network/Port.c:489@swPort_onRead_http]request->method=4
[/data/php/swoole-src/src/network/ReactorThread.c:1184@swReactorThread_dispatch]send string package, size=1473 bytes.
[/data/php/swoole-src/src/network/ReactorThread.c:1243@swReactorThread_dispatch]dispatch, type=10|len=1473

[/data/php/swoole-src/swoole_http_server.c:1009@http_onReceive]httpRequest 1473 bytes:
---------------------------------------
POST /create/create/postAdd HTTP/1.0
Host: admin.template.start.wang
X-Real-IP: 192.168.216.1
X-Forwarded-For: 192.168.216.1
Connection: close
Content-Length: 856
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryBhFK2fQCgCnB0Gal
Origin: http://admin.template.start.wang
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
Referer: http://admin.template.start.wang/create/create/add
Accept-Language: en-us
Accept-Encoding: gzip, deflate

------WebKitFormBoundaryBhFK2fQCgCnB0Gal
Content-Disposition: form-data; name="title"

123
------WebKitFormBoundaryBhFK2fQCgCnB0Gal
Content-Disposition: form-data; name="descrip"

------WebKitFormBoundaryBhFK2fQCgCnB0Gal
Content-Disposition: form-data; name="schedule_count"

------WebKitFormBoundaryBhFK2fQCgCnB0Gal
Content-Disposition: form-data; name="schedule_curr"

------WebKitFormBoundaryBhFK2fQCgCnB0Gal
Content-Disposition: form-data; name="uid"

------WebKitFormBoundaryBhFK2fQCgCnB0Gal
Content-Disposition: form-data; name="display"

1
------WebKitFormBoundaryBhFK2fQCgCnB0Gal
Content-Disposition: form-data; name="type"

1
------WebKitFormBoundaryBhFK2fQCgCnB0Gal
Content-Disposition: form-data; name="cover"; filename=""
Content-Type: application/octet-stream

------WebKitFormBoundaryBhFK2fQCgCnB0Gal--

[/data/php/swoole-src/src/factory/FactoryProcess.c:246@swFactoryProcess_finish][Worker] send: sendn=286|type=0|content=HTTP/1.1 200 OK
Content-Length: 125
Server: swoole-http-server
Connection: close
Date: Thu, 28 Jan 2016 16:26:58 GMT
Content-Type: text/html

            <script>
            alert("----------");
            location.href = "/create/create/lists";
</script>

[/data/php/swoole-src/src/factory/FactoryProcess.c:246@swFactoryProcess_finish][Worker] send: sendn=12|type=4|content=(null)
[/data/php/swoole-src/src/network/ReactorThread.c:231@swReactorThread_close]Close Event.fd=16|from=0
[/data/php/swoole-src/src/network/ReactorThread.c:299@swReactorThread_close]set_maxfd=15|close_fd=16

[/data/php/swoole-src/src/reactor/ReactorPoll.c:245@swReactorPoll_wait]Event: fd=13|from_id=1|type=11
[/data/php/swoole-src/src/reactor/ReactorPoll.c:245@swReactorPoll_wait]Event: fd=14|from_id=1|type=1
[/data/php/swoole-src/src/network/Server.c:131@swServer_master_onAccept][Master] Accept new connection. maxfd=14|reactor_id=1|conn=16
[/data/php/swoole-src/src/network/Port.c:489@swPort_onRead_http]request->method=2
[/data/php/swoole-src/src/network/ReactorThread.c:1184@swReactorThread_dispatch]send string package, size=471 bytes.
[/data/php/swoole-src/src/network/ReactorThread.c:1243@swReactorThread_dispatch]dispatch, type=10|len=471

[/data/php/swoole-src/swoole_http_server.c:1009@http_onReceive]httpRequest 471 bytes:
---------------------------------------
GET /create/create/lists HTTP/1.0
Host: admin.template.start.wang
X-Real-IP: 192.168.216.1
X-Forwarded-For: 192.168.216.1
Connection: close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
Accept-Language: en-us
Referer: http://admin.template.start.wang/create/create/postAdd
Accept-Encoding: gzip, deflate

[2016-01-29 00:27:00 $54132.0]	WARN	swManager_check_exit_status: worker#1 abnormal exit, status=0, signal=11
[/data/php/swoole-src/src/memory/ShareMemory.c:66@sw_shm_free]check:

[/data/php/swoole-src/src/memory/ShareMemory.c:66@sw_shm_free]check:

**Comment by wfleurant** [comment]
something missing. log from PHP-7. related swReactorThread 
```
so, gdb:
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php vendor/bin/start-laravelfly-server'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000101010101010 in swReactorThread_onRead (reactor=xxx, event=xxx)
    at /tmp/pear/temp/swoole/src/network/ReactorThread.c:745
745    /tmp/pear/temp/swoole/src/network/ReactorThread.c: No such file or directory.
(gdb) bt
#0  0x0000101010101010 in swReactorThread_onRead (reactor=xxx, event=xxx)
    at /tmp/pear/temp/swoole/src/network/ReactorThread.c:745
#1  0x0000101010101010 in swReactorEpoll_wait (reactor=xxx, timeo=xxx)
    at /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c:263
#2  0x0000101010101010 in swReactorThread_loop_stream (param=xxx)
    at /tmp/pear/temp/swoole/src/network/ReactorThread.c:1100
#3  0x0000101010101010 in start_thread (arg=0x7fa53ce12700) at pthread_create.c:309
#4  0x0000101010101010 in __libc_ifunc_impl_list (name=<optimized out>, array=xxx, max=<optimized out>)
    at ../sysdeps/x86_64/multiarch/ifunc-impl-list.c:110
#5  0x0000000000000000 in ?? ()
(gdb) f 0
#0  0x00007fa559406184 in swReactorThread_onRead (reactor=xxx, event=xxx)
    at /tmp/pear/temp/swoole/src/network/ReactorThread.c:745
745    in /tmp/pear/temp/swoole/src/network/ReactorThread.c
(gdb) f 1
#1  0x00007fa5593f98ff in swReactorEpoll_wait (reactor=xxx, timeo=xxx)
    at /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c:263
263    /tmp/pear/temp/swoole/src/reactor/ReactorEpoll.c: No such file or directory.
(gdb) f 2
#2  0x00007fa5594074ea in swReactorThread_loop_stream (param=xxx)
    at /tmp/pear/temp/swoole/src/network/ReactorThread.c:1100
1100    /tmp/pear/temp/swoole/src/network/ReactorThread.c: No such file or directory.
(gdb) f 3
#3  0x00007fa55e29c0a4 in start_thread (arg=0x7fa53ce12700) at pthread_create.c:309
309    pthread_create.c: No such file or directory.
(gdb) f 4
#4  0x00007fa55e59704d in __libc_ifunc_impl_list (name=<optimized out>, array=xxx, max=<optimized out>)
    at ../sysdeps/x86_64/multiarch/ifunc-impl-list.c:110
110    ../sysdeps/x86_64/multiarch/ifunc-impl-list.c: No such file or directory.
(gdb) f 5
#5  0x0000000000000000 in ?? ()
```

**Comment by matyhtf** [comment]
关闭debug日志，贴出你的测试脚本。
