### ISSUE TITLE
Intermittent 'Connect' Event Reception Issue in HTTP + Websocket Server

### ISSUE THREAD

**Issue by peliz** [swoole/swoole-src#5124]
With an http + websocket server, the 'Connect' event is not received on every connection, only occasionally, making it impossible to ban IPs at the moment of connection. And when performing a post upload of a file, the event is also not received.

`
declare(strict_types=1);

use OpenSwoole\WebSocket\Server;

$server = new Server('0.0.0.0', 8080);

$ipsBloqueadas = [
    '127.0.0.2', // Agrega más direcciones IP aquí
];

$server->on('Connect', function ($server, $fd) use ($ipsBloqueadas) {
    $clienteInfo = $server->getClientInfo($fd);
    $ipCliente = $clienteInfo['remote_ip'];
    if (in_array($ipCliente, $ipsBloqueadas)) {
        $server->close($fd);
        echo "Conexión desde la IP bloqueada {$ipCliente} cerrada.\n";
    } else {
        echo "Cliente con IP {$ipCliente} conectado.\n";
    }
});

$server->on('Receive', function (Server $server, $fd, $fromId, $data) {
    // Verificar si el tamaño del archivo excede el límite (por ejemplo, 100 MB)
    $maxFileSize = 100 * 1024; // 10 MB en bytes
    if (strlen($data) > $maxFileSize) {
        // Cierra la conexión con el cliente
        $server->close($fd);
        echo "Connection closed due to file size limit exceeded." . PHP_EOL;
    } else {
        echo 'todo ok' . PHP_EOL;
    }
});
`

I expect to see 'Client with IP {$ipClient} connected.' in the console every time I refresh the web client with an F5. But that doesn't happen.

The 'connect' event is only received occasionally.

`
openswoole

Open Swoole => enabled
Author => Open Swoole Group <hello@openswoole.com>
Version => 22.0.0
Built => Dec 22 2022 13:01:47
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.0.2 15 Mar 2022
dtls => enabled
http2 => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
postgresql => enabled

Directive => Local Value => Master Value
openswoole.enable_coroutine => On => On
openswoole.enable_preemptive_scheduler => Off => Off
openswoole.display_errors => On => On
openswoole.unixsock_buffer_size => 8388608 => 8388608
`

`
Linux manu-iMac 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.1.21 (cli) (built: Jul  8 2023 07:10:19) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.21, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.21, Copyright (c), by Zend Technologies
`

**Comment by NathanFreeman** [comment]
The connect event is only triggered once because the web client uses keepalive connection.

**Comment by peliz** [comment]
$response->header("Connection", "close");

yes it's
