### ISSUE TITLE
Application Crashes While Attempting to Save Metrics Periodically

### ISSUE THREAD

**Issue by peliz** [swoole/swoole-src#5125]
Hello, I have an issue when trying to save the metrics every x time. Initially, I want to store them in a file and later do it in a database. However, the application crashes.

1. What did you do? If possible, provide a simple script for reproducing the error.

declare(strict_types=1);

use OpenSwoole\WebSocket\Server;

class MetricsCollector {

    private $server_service;
    private $metricsId;

    public function __construct($server) {
        $this->server_service = $server;
    }

    public function startMetricsCollection($interval = 1000) {
        $this->metricsId = $this->server_service->tick($interval, function () {
            $metrics = $this->server_service->stats();
            $this->storeMetrics($metrics);
        });
    }

    private function storeMetrics($metrics) {
        file_put_contents('metrics.txt', json_encode($metrics) . PHP_EOL, FILE_APPEND);
    }

    public function stopMetricsCollection() {
        if ($this->metricsId) {
            $this->server_service->clearTimer($this->metricsId);
            $this->metricsId = null;
        }
    }
}

$server = new Swoole\Http\Server('127.0.0.1', 1111);

$metricsCollector = new MetricsCollector($server);
$metricsCollector->startMetricsCollection();

$server->on('request', function ($request, $response) {
    $response->header('Content-Type', 'text/plain');
    $response->end('Hello, Swoole!');
});

$server->start();

2. What did you expect to see?

I want to save the metrics every second to a file.

3. What did you see instead?

crash, segmentation fault

4. What version of Swoole are you using (show your `php --ri swoole`)?

openswoole

Open Swoole => enabled
Author => Open Swoole Group <hello@openswoole.com>
Version => 22.0.0
Built => Dec 22 2022 13:01:47
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.0.2 15 Mar 2022
dtls => enabled
http2 => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
postgresql => enabled

Directive => Local Value => Master Value
openswoole.enable_coroutine => On => On
openswoole.enable_preemptive_scheduler => Off => Off
openswoole.display_errors => On => On
openswoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by peliz** [comment]
`    public function registerMetrics(int $time = 1000) {
        $server = $this->server;
        $this->process = new OpenSwoole\Process(function ($process) use ($server, $time) {
                    Swoole\Util::setProcessName("php metrics process");
                    $server->metricsId = OpenSwoole\Timer::tick($time, function ($timerId) use ($process, $server) {
                                static $cont = 0;
                                //$server->task('test');
                                echo 'funciona ' . (++$cont) . PHP_EOL;
                                //print_r($server->stats());
                                if ($cont > 10) {
                                    echo 'enviando' . PHP_EOL;
                                    $process->write('unregistermetrics');
                                }
                            });

                    OpenSwoole\Event::add($process->pipe, function ($fp) {
                        //$var = inotify_read($fd);
                        echo fread($fp, 1024);
                        OpenSwoole\Event::del($fp);
                    });
                    OpenSwoole\Event::wait();
                    $server->process = null;
                }
        );
        $this->server->addProcess($this->process);
    }

    public function unregisterMetrics() {
        if ($this->process) {
            $this->process->write('unregistermetrics');
        }
    }`

With a parallel process, it seems to work well, but it never manages to exit the process.

**Comment by NathanFreeman** [comment]
`Swoole\Server::tick()` and `Swoole\Server::after()` can not use before  `Swoole\Server::start()`.
