### ISSUE TITLE
HTTP连接池使用Swoole\Coroutine\Http\Client，请求结束后有清理内存的方法吗？

### ISSUE THREAD

**Issue by omigafu** [swoole/swoole-src#5126]
如果使用Swoole\Coroutine\Http\Client对象，请求结束后放入连接池中，那么响应的body等数据是否会一直在内存中直到下次使用的时候才释放上次请求的内存？如果是这样的话，有没有方法可以在请求结束的时候先释放掉内存再把连接放入连接池？

**Comment by NathanFreeman** [comment]
在下次请求之前，会自动将这些数据全部重置为默认值。
