### ISSUE TITLE
php8.2版本 swoole 5.0.3 使用mysqlipool 会报错 mysql server has gone away in @swoole/library/core/Database/MysqliProxy.php(51)

### ISSUE THREAD

**Issue by Mrzhang05204130** [swoole/swoole-src#5143]
在PHP 8.0中，该@运算符不会抑制在PHP 8.0之前已静音的某些类型的错误

E_ERROR -致命的运行时错误.
E_CORE_ERROR -PHP的初始启动中发生致命错误.
E_COMPILE_ERROR -致命的编译时错误.
E_USER_ERROR-用户触发的trigger_error()功能错误.
E_RECOVERABLE_ERROR -可捕获的致命错误.
E_PARSE -编译时解析错误.

是不是和这个问题有关系呢

**Comment by jingjingxyk** [comment]
出现这个` mysql server has gone away  `
应该查这些地方：
 1. mysql 服务器端长连接超时设置
 2.  client 端 超时 重试机制
 3. 排查网络问题（比如网络不稳定，出现丢包 ）

**Comment by Mrzhang05204130** [comment]
MysqliProxy 文件
第51行:
$ret = @$this->__object->{$name}(...$arguments);
@ 错误抑制符号无效
依然抛出异常 

thrown in @swoole/library/core/Database/MysqliProxy.php on line 51

Fatal error: uncaught mysqli_sql_excepltion: MySQL server has gone away in @swoole/library/core/Database/MysqliProxy.php(51)

错误码为 2006

**Comment by jingjingxyk** [comment]
这个问题应该定位为重试机制问题
搜索参考文档： 
 https://www.google.com/search?q=has+gone+away+swoole
https://www.google.com/search?q=has+gone+away+site%3Aswoole.com
https://www.google.com/search?q=has+gone+away+site%3Agithub.com

搜到的参考文档：（意义： 这个问题遇到过很多次了，很多有代表性的一个问题）
https://topic.alibabacloud.com/a/swoole-project-thinking-transformation-mysql-server-gone-away_1_41_30080069.html

https://haydenjames.io/mysql-server-has-gone-away-error-solutions/

https://github.com/swoole/swoole-src/issues/1896

https://haydenjames.io/mysql-server-has-gone-away-error-solutions/
https://blog.51cto.com/u_15057855/4280565

https://github.com/swoole/swoole-src/issues/4131

https://wiki.swoole.com/wiki/page/350.html

https://wenda.swoole.com/detail/106787

https://wenda.swoole.com/detail/107973

https://wenda.swoole.com/detail/107419

**Comment by jingjingxyk** [comment]
https://github.com/swoole/swoole-src/issues/4131#issuecomment-815353916

**Comment by matyhtf** [comment]
需要捕获 Pdo 异常，然后重新创建一个新的连接对象。实现断线重连
