### ISSUE TITLE
Core dump in swWebScoket_encode(), 1.8.0

### ISSUE THREAD

**Issue by AJSoft** [swoole/swoole-src#515]
#0  0x00007fc5693db5d7 in raise () from /lib64/libc.so.6
#1  0x00007fc5693dccc8 in abort () from /lib64/libc.so.6
#2  0x00007fc56941be07 in __libc_message () from /lib64/libc.so.6
#3  0x00007fc569421c67 in malloc_printerr () from /lib64/libc.so.6
#4  0x00007fc569425b17 in _int_realloc () from /lib64/libc.so.6
#5  0x00007fc569426702 in realloc () from /lib64/libc.so.6
#6  0x00007fc5558b7cf1 in swString_extend (str=0x7fc53e3b1b40, new_size=4096) at /root/swoole-src/src/core/string.c:120
#7  0x00007fc5558b7e6e in swString_append_ptr (str=str@entry=0x7fc53e3b1b40,
    append_str=append_str@entry=0x7fc5304b7112 " image/gif;q=0.9, */*;q=0.8\r\nAccept-Charset:mage/webp)\r\nAccept-Encoding: gzip,deflate\r\n\r\nger/6.3.11.49_rc8fa17]}7,\"end\"]}2,0]}3]}3,0,-9.66,0,-9.66,\"end\"]}.93]}.93,1.93,-3.86,3.86,-3.86]}", length=length@entry=44) at /root/swoole-src/src/core/string.c:107
#8  0x00007fc5558d3047 in swWebSocket_encode (buffer=buffer@entry=0x7fc53e3b1b40,
    data=data@entry=0x7fc5304b7112 " image/gif;q=0.9, */*;q=0.8\r\nAccept-Charset:mage/webp)\r\nAccept-Encoding: gzip,deflate\r\n\r\nger/6.3.11.49_rc8fa17]}7,\"end\"]}2,0]}3]}3,0,-9.66,0,-9.66,\"end\"]}.93]}.93,1.93,-3.86,3.86,-3.86]}", length=length@entry=44, opcode=opcode@entry=10 '\n', fin=fin@entry=1, isMask=isMask@entry=0) at /root/swoole-src/src/protocol/WebSocket.c:124

先记录下这个issue, 更多的信息以及重现环境我稍后在QQ上提供。

**Comment by matyhtf** [comment]
请使用github master分支最新的代码进行测试，是否可以重现。

**Comment by matyhtf** [comment]
已修复。
