### ISSUE TITLE
 WARNING Server::check_worker_exit_status(): worker(pid=1005, id=1) abnormal exit

### ISSUE THREAD

**Issue by xuchuandi** [swoole/swoole-src#5153]
[2023-09-20 05:59:07 #842.0]    WARNING Server::check_worker_exit_status(): worker(pid=1005, id=1) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v5.0.3, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64
GCC_VERSION: 11.2.1 20220219
OPENSSL_VERSION: OpenSSL 1.1.1t  7 Feb 2023
PHP_VERSION : 8.1.17

**Comment by xuchuandi** [comment]
Error thrown during file import of xlswriter in Docker environment

**Comment by xuchuandi** [comment]
$config = ['path' => RUNTIME_BASE_PATH . '/home/viest'];
        $excel = new \Vtiful\Kernel\Excel($config);
        $fileName = 'test.xlsx';
        $sheetList = $excel->openFile($fileName)->sheetList();
        var_dump($sheetList);

**Comment by NathanFreeman** [comment]
我没法复现这个问题，可以的话，提供一下gdb之后的错误信息，它提示没有这个`openFile`函数。

**Comment by xuchuandi** [comment]
hyperf框架 您安装好xlswriter扩展 并composer require viest/php-ext-xlswriter-ide-helper:dev-master 使用上述环境中运行代码片段即可

**Comment by NathanFreeman** [comment]
我没法复现这个问题，请用gdb跟踪一下程序，贴一下gdb的错误信息

**Comment by matyhtf** [comment]
建议反馈给 xlswriter 扩展的维护者
