### ISSUE TITLE
函数返回之前数组数据是完整的 接收返回值的时候缺了几百个元素

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [swoole/swoole-src#5154]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
我有个方法返回了一个三维数组  加一起元素有三万多 在返回之前是数据是对的 接收重新赋值的时候会有几率丢失几百个元素

我是个小白 不清楚是swoole还是php的问题 所以我先在这里问问

function test(){
	$a = [
		data => [
			list1=>[],
			list2=>[],
			list3=>[]
		]
	]
	var_dump(a);//这时候数据是全的 加一起元素有三万多
	return a;
}

$a = test();
$a = $a['data'];
var_dump($a)//这时候有几率丢失几百个元素 有时候丢失有时候不会

2. What did you expect to see?

返回对的数据

3. What did you see instead?

缺失数据

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.12
Built => Dec  8 2022 21:27:53
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1n  15 Mar 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux 304928c4d90b 5.4.0-152-generic #169-Ubuntu SMP Tue Jun 6 22:23:09 UTC 2023 x86_64 GNU/Linux

PHP 7.4.30 (cli) (built: Sep 13 2022 11:06:19) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6)

**Comment by NathanFreeman** [comment]
你不用swoole试试看，排除一下问题是不是swoole引起的

**Comment by ZhangTianyi-1998** [comment]
> 你不用swoole试试看，排除一下问题是不是swoole引起的

尴尬了  项目是用swoole跑的  不用他起不来

**Comment by NathanFreeman** [comment]
你用sizeof算一下返回的数量是不是一致的

**Comment by ZhangTianyi-1998** [comment]
我加了之后容器重新创建了 就没复现出来😞 我先把问题关了
