### ISSUE TITLE
请问怎么通过request类 判断是否为https请求

### ISSUE THREAD

**Issue by zhuchonglin** [swoole/swoole-src#5156]
请问怎么通过request类 判断是否为https请求

**Comment by NathanFreeman** [comment]
`Swoole\Http\Server`构造函数中启用`SWOOLE_SSL`就会接收https请求。
http服务器可以接收https请求，但是没法处理HTTPS请求的加密和身份验证功能

**Comment by zhuchonglin** [comment]
> 我开启了ssl访问 但是我无法判断请求是否使用了https 谢谢你的解答  我最后选择使用端口验证来判断是否为https的请求

**Comment by NathanFreeman** [comment]
你不需要判断呀，当你开启了ssl，如果客户端不是https请求的话，根本不会调用onRequest的回调函数，而是直接在这之前返回错误给客户端了
