### ISSUE TITLE
reload错误 

### ISSUE THREAD

**Issue by jonnywang** [swoole/swoole-src#516]
```php
<?php

$server = new swoole_server('127.0.0.1', 9501);
$server->set(array(
    'worker_num' => 1,
    'task_worker_num' => 2,
    'log_file'   => './swoole.log'
));

$server->on('workerStart', function($serv, $worker_id){
    echo 'worker start :' . $worker_id . ',pid :' . getmypid() . PHP_EOL;
});

$server->on('task', function($serv, $task_id, int $from_id, string $data){
    echo 'on task  :' . $task_id . ',pid :' . getmypid() . PHP_EOL;
});

$server->on('finish', function($serv, $task_id, string $data){
    echo 'on finish  :' . $task_id . ',pid :' . getmypid() . PHP_EOL;
});

$server->on('receive', function ($serv, $fd, $from_id, $data) {
    $serv->reload(true);
});

$server->start();
```

worker start :1,pid :7818
worker start :0,pid :7817
worker start :2,pid :7819
zend_mm_heap corrupted
zend_mm_heap corrupted
worker start :1,pid :7828
worker start :2,pid :7829

[2016-02-01 15:02:09 $7816.0]	NOTICE	Server is reloading now.
[2016-02-01 15:02:09 $7816.0]	WARN	swManager_check_exit_status: worker#1 abnormal exit, status=0, signal=11
[2016-02-01 15:02:09 $7816.0]	WARN	swManager_check_exit_status: worker#2 abnormal exit, status=0, signal=11

**Comment by matyhtf** [comment]
Swoole版本多少，我在本地使用 最新的github master分支代码进行测试，未发现问题。

**Comment by jonnywang** [comment]
php 7.0.2
osx Darwin 10.11.2
最新swoole master代码
编译参数
./configure --enable-sockets --enable-openssl --enable-jemalloc --enable-swoole --enable-async-redis --enable-async-mysql --enable-async-httpclient

**Comment by jonnywang** [comment]
是mongodb问题，关闭mongodb再测试就可以，抱歉打扰了
