### ISSUE TITLE
PHP 8.3 extension support

### ISSUE THREAD

**Issue by driesvints** [swoole/swoole-src#5182]
I hope I got this repo right because I didn't immediately know where to submit this...

1. What did you do? If possible, provide a simple script for reproducing the error.

We're trying to run our Laravel Octane build against PHP 8.3 but it seems the Swore extension isn't ready for this yet. See https://github.com/laravel/octane/actions/runs/6614196028/job/18482816811?pr=753#step:4:1

[OpenSwoole has just released a PHP 8.3 compatible version](https://github.com/openswoole/ext-openswoole/releases/tag/v22.1.0) so it would be great to see a Swoole one as well soon since PHP 8.3 is almost being released.

2. What did you expect to see?

The Swoole extension being available and installable on GitHub actions

3. What did you see instead?

```
Run php --ri swoole
  php --ri swoole
  shell: /usr/bin/bash -e {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
/home/runner/work/_temp/0105a930-f702-4453-b058-62804b61ddc7.sh: line 1: 10797 Segmentation fault      (core dumped) php --ri swoole
Error: Process completed with exit code 139.
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

See the above.

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

https://github.com/laravel/octane/actions/runs/6614196028/job/18482816811?pr=753#step:1:2

```
Image: ubuntu-22.04
  Version: 20231030.2.0
````

**Comment by leocavalcante** [comment]
Can you confirm that v5.1 is the version being installed at https://github.com/laravel/octane/pull/753/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fL33?
![image](https://github.com/swoole/swoole-src/assets/183722/174f4484-6b50-483d-a3d1-5eca8e1a3db7)

**Comment by driesvints** [comment]
Right now it fails to install anything: https://github.com/laravel/octane/actions/runs/6614196028/job/18482816811?pr=753#step:3:23

I don't know what version is being attempted to install, sorry.

**Comment by driesvints** [comment]
@shivammathur there also appear to be some seg faults in the install script here: https://github.com/laravel/octane/actions/runs/6614196028/job/18482816811?pr=753#step:3:21

```
/home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/extensions/add_extensions.sh: line 9: 10563 Segmentation fault      (core dumped) php -m > "$extension_list"
/home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/extensions/add_extensions.sh: line 79: 10572 Segmentation fault      (core dumped) php -d'error_reporting=0' "${src:?}"/scripts/extensions/extension_map.php /tmp/map"$version".orig > /dev/null 2>&1
```

```
/home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/tools/add_tools.sh: line 28: 10763 Segmentation fault      (core dumped) php -r "try {\$p=new Phar('$tool_path.phar', 0);exit(0);} catch(Exception \$e) {exit(1);}"
```

**Comment by leocavalcante** [comment]
It is using 5.0 for other runs: https://github.com/laravel/octane/actions/runs/6614196028/job/18482816186?pr=753#step:4:14

Can you test it like this: https://github.com/laravel/octane/pull/753#discussion_r1386662962 ?

**Comment by driesvints** [comment]
@leocavalcante thank you. It seems it cannot find that: https://github.com/laravel/octane/actions/runs/6799722561/job/18486632381?pr=753#step:4:1

**Comment by shivammathur** [comment]
@leocavalcante setup-php is trying to build swoole-5.1.0 with PHP 8.3. But most likely it doesn't work with the nightly builds of PHP 8.3 we have and something might have changed since 5.1.0 was released.

Build logs - https://github.com/shivammathur/test-setup-php/actions/runs/6799912278/job/18487268457#step:2:602

**Comment by NathanFreeman** [comment]
I will test it later.

**Comment by driesvints** [comment]
Thanks @shivammathur.

@NathanFreeman thanks!

**Comment by NathanFreeman** [comment]
@driesvints @shivammathur 
It conflicts with xdebug. I will create a new pull request to handle it later.

**Comment by driesvints** [comment]
@NathanFreeman thanks for that. It does seem we're still getting a segmentation fault: https://github.com/laravel/octane/actions/runs/6865443369/job/18669470246?pr=753#step:4:9

**Comment by driesvints** [comment]
I guess these changes still need to be released? Any idea when the next release is?

**Comment by NathanFreeman** [comment]
A new version will be released either this week or next week.

**Comment by NathanFreeman** [comment]
Swoole v5.1.1 has released. https://github.com/swoole/swoole-src/releases

**Comment by driesvints** [comment]
We have a passing build now, thank you all! 🙂

**Comment by NathanFreeman** [comment]
@driesvints I think pecl needs to clear the cache. The GitHub action `PHP8.3 - Laravel 10 -swoole` still shows that the version is swoole 5.1.0.

**Comment by NathanFreeman** [comment]
@driesvints 
I executed `pecl clear-cache`, and now the downloaded version is swoole 5.1.1.
