### ISSUE TITLE
Swoole 5.1.0 with Cygwin release

### ISSUE THREAD

**Issue by janreges** [swoole/swoole-src#5189]
Hi,

I made this useful tool with Swoole Coroutines - https://github.com/janreges/siteone-website-crawler

It works great on Linux/macOS, but it is quite unstable on Cygwin version (crashes).

In the last Swoole versions, you stopped releasing ready-made binaries for multiple platforms.

Would it be possible to recreate them, at least for the latest version of Swoole 5.1.0? Especially a version with the current version of Cygwin would help me a lot - I assume that the tool will be more stable on Windows then.

Thank you very much for your work on Swoole. We love it and recommend it everywhere ❤️

**Comment by jingjingxyk** [comment]
参考:

https://github.com/swoole/swoole-cli/blob/main/sapi/scripts/cygwin/README.md
https://github.com/swoole/swoole-cli/blob/main/docs/Cygwin.md

**Comment by sy-records** [comment]
Hi, @janreges

If you're going to use 5.1.0, you may need to build it yourself, refer to the reply above.

When swoole v5.1.1 is released, it will probably be accompanied by a cygwin release.

**Comment by janreges** [comment]
@jingjingxyk, @sy-records - Thank you, you are amazing! 💪 

I believe that I can handle the instructions myself. But if the next versions also come out with ready-made releases for different platforms again, including Cygwin, that will be great 😊
