### ISSUE TITLE
error: enumerator value '2147483648' is outside the range of underlying type 'long int' on arm v7

### ISSUE THREAD

**Issue by FacuM** [swoole/swoole-src#5198]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
I was cross-compiling the latest stable release (5.1.0) of Swoole from PECL using Docker to compile arm v7 binaries from a amd64 host.

2. What did you expect to see?
A compiled set of binaries.

3. What did you see instead?
A crashed compiler with the error attached below.

4. What version of Swoole are you using (show your `php --ri swoole`)?
N/A

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
php8.2 docker image

[error.log](https://github.com/swoole/swoole-src/files/13414871/error.log)

**Comment by matyhtf** [comment]
32-bit systems are no longer supported since version 5.1, it is recommended to use 4.8 or 5.0

**Comment by FacuM** [comment]
> 32-bit systems are no longer supported since version 5.1, it is recommended to use 4.8 or 5.0

Oh, got it. Yes, I'll stick to v5.0.3 for now. Thanks for the input!
