### ISSUE TITLE
swoole-redis和swoole-server不能一起用?

### ISSUE THREAD

**Issue by wangxiao2663** [swoole/swoole-src#520]
php代码：
$g_bExit = 0;
function connect(swoole_redis $redis)
{
//连接相关的回调函数
}
$redis = new swoole_redis;
connect($redis);
$serv = new swoole_server("127.0.0.1", 9501); 

会报错：
connectPHP Fatal error:  swoole_server::__construct(): eventLoop has been created. Unable to create swoole_server

如果我先创建swoole_server,再创建swoole_redis,再连接redis-server
会没有响应。

**Comment by matyhtf** [comment]
可以一起用，但必须在 `onWorkerStart` 之后
