### ISSUE TITLE
WARNING check_worker_exit_status: worker#2[pid=104] abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by huanglietao** [swoole/swoole-src#5207]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
$http = new \Swoole\Http\Server('0.0.0.0', $port);
        $http->on("start", function (\Swoole\Server $server)  {
            echo 'success'.PHP_EOL;
        });
        $http->on('request', $grpc->handler());

        $http->set([
            'enable_coroutine' => true,
            'worker_num' => 3,
            'open_http2_protocol' => true,
            //'log_file' => '/var/log/swoole.log',
            //'daemonize' => true
        ]);

        swoole_set_process_name("grpc_server_".$strClasses);
        $http->start();
        
    

2. What did you expect to see?

要怎么调整才能 正常返回json串

3. What did you see instead?

想返回一个60多kb的json，但出现了
WARNING check_worker_exit_status: worker#2[pid=104] abnormal exit, status=0, signal=11

A bug occurred in Swoole-v4.6.7, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7
Built => Dec 20 2022 09:10:32
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1d  10 Sep 2019
dtls => enabled
http2 => enabled
curl-native => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

php7.4.0

利用gdb分析后，得到了以下：
#0  0x00007f28bd970094 in __waitpid (pid=-1, stat_loc=0x7ffe6647579c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007f28ba2d6da0 in swoole::wait_process (options=<optimized out>, _pid=-1) at /tmp/pear/temp/swoole/include/swoole_process_pool.h:81
#2  zim_swoole_process_wait (execute_data=<optimized out>, return_value=0x7ffe66475800) at /tmp/pear/temp/swoole/ext-src/swoole_process.cc:424
#3  0x000055f44fd886a0 in execute_ex ()
#4  0x000055f44fd89593 in zend_execute ()
#5  0x000055f44fd03463 in zend_execute_scripts ()
#6  0x000055f44fca30a0 in php_execute_script ()
#7  0x000055f44fd8b67e in ?? ()
#8  0x000055f44fa3cb0b in ?? ()
#9  0x00007f28bd9a309b in __libc_start_main (main=0x55f44fa3c6c0, argc=4, argv=0x7ffe66479198, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe66479188)
    at ../csu/libc-start.c:308
#10 0x000055f44fa3d24a in _start ()

**Comment by matyhtf** [comment]
升级一下版本，使用 4.8 或者 5.1 ，建议使用 valgrind 跟踪程序运行。
