### ISSUE TITLE
coredump Assertion 'iov[i].iov_len > 0' failed  php v8.0.8 Swoole 4.6.7 server shutdown

### ISSUE THREAD

**Issue by tinyan-s** [swoole/swoole-src#5212]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

systemd-coredump[2337615]: Process 2337503 (php) of user 1000 dumped core.#012#012Stack trace of thread 2337505:#012#0  0x00007f83fda9fa4f raise (libc.so.6)#012#1  0x00007f83fda72db5 abort (l       ibc.so.6)#012#2  0x00007f83fda72c89 __assert_fail_base.cold.0 (libc.so.6)#012#3  0x00007f83fda983a6 __assert_fail (libc.so.6)#012#4  0x00007f83fadbcfb8 _ZN6swoole6Buffer6appendEPK5iovecml (swoole.so)#012#5  0x00007f83fadda0b0 _ZNKS       t8functionIFvPN6swoole6BufferEEEclES2_ (swoole.so)#012#6  0x00007f83fadda54e _ZN6swoole7Reactor7_writevEPS0_PNS_7network6SocketEPK5iovecm (swoole.so)#012#7  0x00007f83fadf6923 _Z19swoole_event_writevPN6swoole7network6SocketEPK5iove       cm (swoole.so)#012#8  0x00007f83fadead7c process_sendto_worker (swoole.so)#012#9  0x00007f83fadeae32 process_send_packet (swoole.so)#012#10 0x00007f83fadeb66b _ZN6swoole14ProcessFactory8dispatchEPNS_8SendDataE (swoole.so)#012#11 0x       00007f83fadeeb3a _ZN6swoole6Server13dispatch_taskEPNS_8ProtocolEPNS_7network6SocketEPKcj (swoole.so)#012#12 0x00007f83fadd957b _Z26swWebSocket_dispatch_framePN6swoole8ProtocolEPNS_7network6SocketEPKcj (swoole.so)#012#13 0x00007f83f       add16ca _ZN6swoole8Protocol25recv_with_length_protocolEPNS_7network6SocketEPNS_6StringE (swoole.so)#012#14 0x00007f83fade8571 Port_onRead_check_length (swoole.so)#012#15 0x00007f83fadef8c8 ReactorThread_onRead (swoole.so)#012#16 0x       00007f83faddc161 _ZN6swoole12ReactorEpoll4waitEP7timeval (swoole.so)#012#17 0x00007f83fadf67df _ZN6swoole7Reactor4waitEP7timeval (swoole.so)#012#18 0x00007f83fadee5e8 ReactorThread_loop (swoole.so)#012#19 0x00007f83fa9d8ba3 execute       _native_thread_routine (libstdc++.so.6)#012#20 0x00007f83fd83917f start_thread (libpthread.so.0)#012#21 0x00007f83fda8ad83 __clone (libc.so.6)#012#012Stack trace of thread 2337508:#012#0  0x00007f83fdb809f7 epoll_wait (libc.so.6)#0       12#1  0x00007f83faddbff4 _ZN6swoole12ReactorEpoll4waitEP7timeval (swoole.so)#012#2  0x00007f83fadf67df _ZN6swoole7Reactor4waitEP7timeval (swoole.so)#012#3  0x00007f83fadee5e8 ReactorThread_loop (swoole.so)#012#4  0x00007f83fa9d8ba3        execute_native_thread_routine (libstdc++.so.6)#012#5  0x00007f83fd83917f start_thread (libpthread.so.0)#012#6  0x00007f83fda8ad83 __clone (libc.so.6)#012#012Stack trace of thread 2337509:#012#0  0x00007f83fdb809f7 epoll_wait (libc       .so.6)#012#1  0x00007f83faddbff4 _ZN6swoole12ReactorEpoll4waitEP7timeval (swoole.so)#012#2  0x00007f83fadf67df _ZN6swoole7Reactor4waitEP7timeval (swoole.so)#012#3  0x00007f83fadee5e8 ReactorThread_loop (swoole.so)#012#4  0x00007f83       fa9d8ba3 execute_native_thread_routine (libstdc++.so.6)#012#5  0x00007f83fd83917f start_thread (libpthread.so.0)#012#6  0x00007f83fda8ad83 __clone (libc.so.6)#012#012Stack trace of thread 2337507:#012#0  0x00007f83fdb809f7 epoll_wa       it (libc.so.6)#012#1  0x00007f83faddbff4 _ZN6swoole12ReactorEpoll4waitEP7timeval (swoole.so)#012#2  0x00007f83fadf67df _ZN6swoole7Reactor4waitEP7timeval (swoole.so)#012#3  0x00007f83fadee5e8 ReactorThread_loop (swoole.so)#012#4  0x       00007f83fa9d8ba3 execute_native_thread_routine (libstdc++.so.6)#012#5  0x00007f83fd83917f start_thread (libpthread.so.0)#012#6  0x00007f83fda8ad83 __clone (libc.so.6)#012#012Stack trace of thread 2337503:#012#0  0x00007f83fdb809f7        epoll_wait (libc.so.6)#012#1  0x00007f83faddbff4 _ZN6swoole12ReactorEpoll4waitEP7timeval (swoole.so)#012#2  0x00007f83fadf67df _ZN6swoole7Reactor4waitEP7timeval (swoole.so)#012#3  0x00007f83fadef1f1 _ZN6swoole6Server21start_reactor       _threadsEv (swoole.so)#012#4  0x00007f83fade63ad _ZN6swoole6Server5startEv (swoole.so)#012#5  0x00007f83fad8908d zim_swoole_server_start (swoole.so)#012#6  0x00000000007da54f ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER (php)#012#7  0x       00000000007db964 zend_execute (php)#012#8  0x0000000000778341 zend_execute_scripts (php)#012#9  0x0000000000718e52 php_execute_script (php)#012#10 0x00000000007ff098 do_cli (php)#012#11 0x0000000000472f16 main (php)#012#12 0x00007f       83fda8bca3 __libc_start_main (libc.so.6)#012#13 0x000000000047364e _start (php)#012#012Stack trace of thread 2337506:#012#0  0x00007f83fdb809f7 epoll_wait (libc.so.6)#012#1  0x00007f83faddbff4 _ZN6swoole12ReactorEpoll4waitEP7timeva       l (swoole.so)#012#2  0x00007f83fadf67df _ZN6swoole7Reactor4waitEP7timeval (swoole.so)#012#3  0x00007f83fadee5e8 ReactorThread_loop (swoole.so)#012#4  0x00007f83fa9d8ba3 execute_native_thread_routine (libstdc++.so.6)#012#5  0x00007f       83fd83917f start_thread (libpthread.so.0)#012#6  0x00007f83fda8ad83 __clone (libc.so.6)#012#012Stack trace of thread 2337511:#012#0  0x00007f83fdb4b678 __nanosleep (libc.so.6)#012#1  0x00007f83fdb4b57e sleep (libc.so.6)#012#2  0x00       007f83fadedd3f operator() (swoole.so)#012#3  0x00007f83fa9d8ba3 execute_native_thread_routine (libstdc++.so.6)#012#4  0x00007f83fd83917f start_thread (libpthread.so.0)#012#5  0x00007f83fda8ad83 __clone (libc.so.6)#012#012Stack trac       e of thread 2337510:#012#0  0x00007f83fdb809f7 epoll_wait (libc.so.6)#012#1  0x00007f83faddbff4 _ZN6swoole12ReactorEpoll4waitEP7timeval (swoole.so)#012#2  0x00007f83fadf67df _ZN6swoole7Reactor4waitEP7timeval (swoole.so)#012#3  0x00       007f83fadee5e8 ReactorThread_loop (swoole.so)#012#4  0x00007f83fa9d8ba3 execute_native_thread_routine (libstdc++.so.6)#012#5  0x00007f83fd83917f start_thread (libpthread.so.0)#012#6  0x00007f83fda8ad83 __clone (libc.so.6)   

2. What did you expect to see?
Assertion 'iov[i].iov_len > 0' failed

The production environment will prompt coredump online, causing the entire swoole service to hang up abnormally.

4. What did you see instead?

5. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7
Built => Jul  2 2021 02:38:13
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1g FIPS  21 Apr 2020
dtls => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

php -v
PHP 8.0.8 (cli) (built: Jul  2 2021 02:32:32) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.8, Copyright (c), by Zend Technologies

**Comment by matyhtf** [comment]
这个分支已经不在维护了，可能存在bug，请升级至 4.8 或 5.1
