### ISSUE TITLE
Task worker 非正常退出 swoole 1.8.1 stable

### ISSUE THREAD

**Issue by zgr0629** [swoole/swoole-src#522]
请问在server的task中new一个同步client连接另一个server，得到结果之后client->close()。
然而此次task在client->close之后就立即退出了，这是为什么？
这个问题在1.7.17中不存在，更新到1.8.1后就出现了。

**Comment by matyhtf** [comment]
1.8.0 的BUG，请使用 最新的 `1.8.2-rc2` 测试一下。
