### ISSUE TITLE
Swoole\Table::set(): failed to set('36998'), unable to allocate memory

### ISSUE THREAD

**Issue by daironghua521** [swoole/swoole-src#5225]
Swoole\Table::set(): failed to set('36998'), unable to allocate memory，This problem will always exist no matter how large the size is set.

**Comment by sy-records** [comment]
Duplicate of #3109

see [table doc](https://wiki.swoole.com/#/memory/table?id=__construct:~:text=%E5%A6%82%E6%9E%9C%E4%BD%A0%E7%9A%84%E6%95%B0%E6%8D%AE%20Key%20%E5%92%8C%20Hash%20%E5%86%B2%E7%AA%81%E7%8E%87%E8%B6%85%E8%BF%87%2020%25%EF%BC%8C%E9%A2%84%E7%95%99%E7%9A%84%E5%86%B2%E7%AA%81%E5%86%85%E5%AD%98%E5%9D%97%E5%AE%B9%E9%87%8F%E4%B8%8D%E8%B6%B3%EF%BC%8Cset%20%E6%96%B0%E7%9A%84%E6%95%B0%E6%8D%AE%E5%B0%B1%E4%BC%9A%E6%8A%A5%20Unable%20to%20allocate%20memory%20%E9%94%99%E8%AF%AF%EF%BC%8C%E5%B9%B6%E8%BF%94%E5%9B%9E%20false%EF%BC%8C%E5%AD%98%E5%82%A8%E5%A4%B1%E8%B4%A5%EF%BC%8C%E6%AD%A4%E6%97%B6%E9%9C%80%E8%A6%81%E8%B0%83%E5%A4%A7%20%24size%20%E5%80%BC%E5%B9%B6%E9%87%8D%E5%90%AF%E6%9C%8D%E5%8A%A1%E3%80%82)

**Comment by daironghua521** [comment]
I have set it to the largest size but there is still Unable to allocate memory. Is there any good solution?

**Comment by NathanFreeman** [comment]
Do you use Docker?

**Comment by daironghua521** [comment]
How to calculate the maximum allocable value for the initial allocation table capacity of a 16-core 32G server. The swoole version is 4.6.7, the php version is 7.3, and the server is linux
