### ISSUE TITLE
swoole 4.8-5.0版本使用redis异常

### ISSUE THREAD

**Issue by sh512953070** [swoole/swoole-src#5227]
php版本切换过8.0.2-8.2，swoole版本4.8和5.0都提示这个，windows10下面出现的 swoole-cli-v5.0.2-cygwin-x64、swoole-cli-v5.0.1、swoole-cli-v4.8.13-cygwin-x64

[2023-12-30 23:27:58 $49.0]     WARNING Server::check_worker_exit_status(): worker(pid=50, id=0) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v5.0.2, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: CYGWIN_NT-10.0-18363 3.4.5-1.x86_64 2023-01-19 19:09 UTC x86_64
GCC_VERSION: 11.3.0
OPENSSL_VERSION: OpenSSL 1.1.1s  1 Nov 2022
PHP_VERSION : 8.1.12

**Comment by NathanFreeman** [comment]
用的是php原生的redis扩展还是swoole自带的redis协程客户端？

**Comment by sh512953070** [comment]
php的redis扩展




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MARiA so ***@***.***&gt;; 
发送时间: 2023年12月31日(星期天) 中午12:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [swoole/swoole-src] swoole 4.8-5.0版本使用redis异常 (Issue #5227)





 
用的是php原生的redis扩展还是swoole自带的redis协程客户端？

**Comment by NathanFreeman** [comment]
是window下的swoole-cli报这个错误吗

**Comment by sh512953070** [comment]
出现这个情况，redis和mysql数据库都不能操作，都提示这个







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MARiA so ***@***.***&gt;; 
发送时间: 2023年12月31日(星期天) 中午1:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [swoole/swoole-src] swoole 4.8-5.0版本使用redis异常 (Issue #5227)





 
是window下的swoole-cli报这个错误吗
