### ISSUE TITLE
abnormal exit

### ISSUE THREAD

**Issue by BeyCoder** [swoole/swoole-src#5230]
Hi, I faced with very high response time of my Laravel + Swoole server after reaching 200+ users in same time.

[2024-01-02 17:11:25 #47317.0]	WARNING	Server::check_worker_exit_status(): worker(pid=47350, id=8) abnormal exit, status=0, signal=9

1. What version of Swoole are you using (show your `php --ri swoole`)?
![image](https://github.com/swoole/swoole-src/assets/31037730/baf9d6b9-2f0d-4142-98fa-2abb674d328a)

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.2.14 (cli) (built: Dec 21 2023 20:19:50) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.14, Copyright (c), by Zend Technologies
    
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

**Comment by BeyCoder** [comment]
dmesg is nothing about SIGKILL

**Comment by NathanFreeman** [comment]
https://github.com/laravel/octane/blob/398c986842089fbb1b37f96cdcdbaec884e3ef82/src/Swoole/Actions/EnsureRequestsDontExceedMaxExecutionTime.php#L34

Are you using Laravel Octane? If so, it seems like there is a timeout issue.

**Comment by BeyCoder** [comment]
> https://github.com/laravel/octane/blob/398c986842089fbb1b37f96cdcdbaec884e3ef82/src/Swoole/Actions/EnsureRequestsDontExceedMaxExecutionTime.php#L34
> 
> Are you using Laravel Octane? If so, it seems like there is a timeout issue.

Yes. Thank you!
