### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by zhaozhatian** [swoole/swoole-src#5233]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
ubuntu系统中 php8源码编译安装swoole扩展，make test时发生错误

2. What did you expect to see?
编译正常，执行php -ri swoole 正常

3. What did you see instead?
编译完成后，执行make test 错误，错误如下

![image](https://github.com/swoole/swoole-src/assets/48541450/7d199c7e-80f6-4892-8dba-6ecd37a0de8f)

4. What version of Swoole are you using (show your `php --ri swoole`)?
无法输出php -rf swoole , swoole版本最新5.1.1

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux LAPTOP-RUEHAMBH 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.2.8 (cli) (built: Jul 17 2023 10:43:39) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies

gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1)

**Comment by NathanFreeman** [comment]
在你的/usr/local/swoole/test/include/lib目录下面执行 composer install

**Comment by zhaozhatian** [comment]
solved！
