### ISSUE TITLE
MySQL server fails connection at ./init of test

### ISSUE THREAD

**Issue by junwha0511** [swoole/swoole-src#5235]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

$ ./configure && make -j`nproc` 
modified php.ini with extension=swoole
$ sudo make install
$ cd tests
$ php ./init

2. What did you expect to see?
I expected the mySQL server is completely ready, and being able to run unit tests.

3. What did you see instead?
$ php ./init 
```
[DB-init] initialization MySQL database...

Deprecated: Method Swoole\Coroutine\MySQL::__construct() is deprecated in /home/qbit/swoole-src/tests/init on line 42
[DB-init] Connect failed! Error#2002: SQLSTATE[HY000] [2002] Connection refused

Fatal error: Uncaught Swoole\ExitException: swoole exit in /home/qbit/swoole-src/tests/init:52
Stack trace:
#0 [internal function]: {closure}()
#1 {main}
  thrown in /home/qbit/swoole-src/tests/init on line 52
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
5.1.1

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux 6.5.0-14-generic 
Ubuntu 22.04.1 x86_64
php 8.4.0
clang-15.0.6

Thank you!

**Comment by matyhtf** [comment]
You need to modify the `tests/include/config.php` file, Set database username and password
