### ISSUE TITLE
Urgent Request for 'curl' Bug Fix Release 

### ISSUE THREAD

**Issue by jhmoon2000** [swoole/swoole-src#5238]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

**Using a custom image built with alpine:edge, including php83, php83-pecl-swoole, etc. Accessing S3 bucket with aws-sdk-php.**

2. What did you expect to see?

**Normal API operation**

3. What did you see instead?

Irregular curl exceptions occurring

4. What version of Swoole are you using (show your `php --ri swoole`)?

/var/www/html # php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.1.1
Built => Nov 28 2023 19:25:22
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.1.4 24 Oct 2023
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
c-ares => 1.25.0
zlib => 1.3
brotli => E16781312/D16781312
mutex_timedlock => enabled
pthread_barrier => enabled
mysqlnd => enabled
async_redis => enabled
coroutine_pgsql => enabled
coroutine_sqlite => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

/var/www/html # uname -a
Linux 7f2a9345e6d0 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 Linux
/var/www/html # php -v
PHP 8.3.2 (cli) (built: Jan 16 2024 20:25:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.2, Copyright (c) Zend Technologies

Since we use swoole as a package distributed by pecl, bug fixes for curl have been made in the master branch, but have not been officially released, resulting in the currently distributed swoole package being in a buggy state. It's challenging to maintain normal service operations until a new version is released, so we urgently request a swift bug fix release.

**Comment by matyhtf** [comment]
fixed

**Comment by jhmoon2000** [comment]
5.1.2 is released, but the pecl repository does not have the updated version. Can you please update the **pecl** release?
