### ISSUE TITLE
CURLOPT_SHARE option is not supported in Swoole 5.0.3

### ISSUE THREAD

**Issue by karevan** [swoole/swoole-src#5245]
When I want to use OpenTelementry on event "Receive" of TCP  Swoole socket
It shows me this error:
OpenTelemetry: [error] Export failure [exception] swoole_curl_setopt(): option[10100] is not supported

**Comment by NathanFreeman** [comment]
When compiling swoole, add --enable-swoole-curl to use the native curl.
