### ISSUE TITLE
Server::check_worker_exit_status(): worker(pid=3169, id=1) abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by xiechenghua01** [swoole/swoole-src#5258]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
使用hyperf框架调用接口时报错，新增数据库后触发事件，监听器内异步调用耗时方法：
<img width="498" alt="image" src="https://github.com/swoole/swoole-src/assets/110524397/a611534b-632e-41e0-8d10-74491ad95540">
<img width="732" alt="image" src="https://github.com/swoole/swoole-src/assets/110524397/ca455579-fcca-49bc-996f-b8e1c99e7eb2">
<img width="703" alt="image" src="https://github.com/swoole/swoole-src/assets/110524397/556b5e9f-66b6-4802-b901-bf9eb9c16966">

2. What did you expect to see?
接口调用成功

3. What did you see instead?
[2024-02-20 09:43:42 $1689.0]   WARNING [valgrind.log](https://github.com/swoole/swoole-src/files/14339110/valgrind.log)
A bug occurred in Swoole-v5.1.1, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Linux 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64
GCC_VERSION: 11.4.0
OPENSSL_VERSION: OpenSSL 3.0.2 15 Mar 2022
PHP_VERSION : 8.2.6

4. What version of Swoole are you using (show your `php --ri swoole`)?
<img width="409" alt="image" src="https://github.com/swoole/swoole-src/assets/110524397/4b746176-a4fc-4523-93e8-737517321fc1">

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
<img width="1049" alt="image" src="https://github.com/swoole/swoole-src/assets/110524397/92821bae-55a3-4798-97ce-ace12b4c3a6f">

valgrind.log 日志分析
[valgrind.log](https://github.com/swoole/swoole-src/files/14339120/valgrind.log)

**Comment by NathanFreeman** [comment]
异步操作里面是不是有个文件操作

**Comment by xiechenghua01** [comment]
> 异步操作里面不是有一个文件操作

没有文件操作，有一个调用第三方接口的封装，使用guzzle发起
<img width="1667" alt="image" src="https://github.com/swoole/swoole-src/assets/110524397/de7cb55b-8484-411e-8194-38b928645f0c">

<img width="1071" alt="image" src="https://github.com/swoole/swoole-src/assets/110524397/8a3c76f8-2d27-4d62-8ef7-10172634c6bf">

**Comment by NathanFreeman** [comment]
`php --ri swoole` 看看输出有没有`curl-native => enabled`

**Comment by xiechenghua01** [comment]
> `php --ri swoole` 看看输出有没有`curl-native => enabled`
有的
<img width="475" alt="image" src="https://github.com/swoole/swoole-src/assets/110524397/6492795a-b721-4ae3-b216-a6f14decd8f3">

**Comment by NathanFreeman** [comment]
偶发性还是每次调用都会出现这个问题？

**Comment by xiechenghua01** [comment]
偶发，有时候又是其他接口调用触发，比如：查询某个列表接口

**Comment by xiechenghua01** [comment]
> 偶发性还是每次调用都会出现这个问题？

偶发，有时候又是其他接口调用触发，比如：查询某个列表接口

**Comment by abnegate** [comment]
Getting this randomly too, just started in the last couple of days:

```
appwrite  | [2024-02-22 08:33:10 $1.0]  WARNING Server::check_worker_exit_status(): worker(pid=31, id=23) abnormal exit, status=0, signal=11
appwrite  | A bug occurred in Swoole-v5.1.2, please report it.
appwrite  | The Swoole developers probably don't know about it,
appwrite  | and unless you report it, chances are it won't be fixed.
appwrite  | You can read How to report a bug doc before submitting any bug reports:
appwrite  | >> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
appwrite  | Please do not send bug reports in the mailing list or personal letters.
appwrite  | The issue page is also suitable to submit feature requests.
appwrite  | 
appwrite  | OS: Linux 6.6.12-linuxkit #1 SMP Thu Feb  8 06:36:34 UTC 2024 aarch64
appwrite  | GCC_VERSION: 13.2.1 20231014
appwrite  | OPENSSL_VERSION: OpenSSL 3.1.4 24 Oct 2023
appwrite  | PHP_VERSION : 8.2.14
```

php --ri swoole
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.1.2
Built => Feb 16 2024 01:46:07
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.1.4 24 Oct 2023
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
zlib => 1.3.1
brotli => E16781312/D16781312
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

uname -a && php -v && gcc -v
```
Linux 6f2b9a16a4ab 6.6.12-linuxkit #1 SMP Thu Feb  8 06:36:34 UTC 2024 aarch64 Linux
PHP 8.2.14 (cli) (built: Dec 27 2023 23:13:43) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.14, Copyright (c), by Zend Technologies
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-alpine-linux-musl/13.2.1/lto-wrapper
Target: aarch64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-13-20231014/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=aarch64-alpine-linux-musl --host=aarch64-alpine-linux-musl --target=aarch64-alpine-linux-musl --enable-checking=release --disable-cet --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-languages=c,c++,d,objc,go,fortran,ada --enable-link-serialization=2 --enable-linker-build-id --with-arch=armv8-a --with-abi=lp64 --disable-libquadmath --disable-libssp --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-bugurl=https://gitlab.alpinelinux.org/alpine/aports/-/issues --with-system-zlib --with-linker-hash-style=gnu --with-pkgversion='Alpine 13.2.1_git20231014'
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 13.2.1 20231014 (Alpine 13.2.1_git20231014)

**Comment by xiechenghua01** [comment]
重装PHP后，没有再出现以上问题了

**Comment by marcelorcastro** [comment]
@xiechenghua01 what means "reinstall php"? I have the same issue open here: https://github.com/swoole/swoole-src/issues/5709

It means using a new version or update some lib/modules?

Thanks,

**Comment by NathanFreeman** [comment]
@abnegate Attempt to upgrade the version to 5.1.3, as there is a bug in parsing messages in version 5.1.2.
