### ISSUE TITLE
请求兼容micro运行环境，出现`Swoole\Http\Server can only be used in CLI mode`异常

### ISSUE THREAD

**Issue by etjson** [swoole/swoole-src#5263]
请在提交问题之前回答这些问题。

1.你做了什么？ 如果可能，请提供一个简单的脚本来重现错误。

使用[https://github.com/crazywhalecc/static-php-cli](https://github.com/crazywhalecc/static-php-cli)构建二进制执行出现`Swoole\Http\Server can only be used in CLI mode`异常，`php_sapi_name`函数输出为`micro`

2. 你希望看到什么？

兼容micro运行环境

3. 你看到了什么？

出现`Swoole\Http\Server can only be used in CLI mode`异常

4. 您使用的 Swoole 版本是什么（显示您的 `php --ri swoole`）？

5.1.2

5. 您使用的机器环境是什么（显示您的 `uname -a` & `php -v` & `gcc -v`）？

micro

@NathanFreeman @matyhtf

**Comment by etjson** [comment]
`micro`环境中还会出现`Fatal error: Uncaught Error: Class "Swoole\Constant" not found`异常

**Comment by NathanFreeman** [comment]
```c++
if (strcmp("cli", sapi_module.name) == 0 || strcmp("phpdbg", sapi_module.name) == 0 ||
   strcmp("embed", sapi_module.name) == 0) {
   SWOOLE_G(cli) = 1;
}
```
`swoole`目前没有加上`micro`这个，我稍后处理一下，急用的话可以用`swoole-cli`代替一下

**Comment by he426100** [comment]
static-php可以加 `--with-micro-fake-cli` 伪装 cli 的
