### ISSUE TITLE
hyperf启动报错，worker进程异常退出

### ISSUE THREAD

**Issue by pizsd** [swoole/swoole-src#5276]
Please answer these questions before submitting your issue.

1.  执行 php bin/hyperf.php start

2. 框架无法启动

3. 工作进程退出，错误信息如下
[2024-03-15 10:01:51 $11760.0]	WARNING	Server::check_worker_exit_status(): worker(pid=12373, id=8) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v5.1.1, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112 x86_64
GCC_VERSION: Apple LLVM 15.0.0 (clang-1500.1.0.2.5)
OPENSSL_VERSION: OpenSSL 3.2.0 23 Nov 2023
PHP_VERSION : 8.1.27

5. What version of Swoole are you using (show your `php --ri swoole`)?

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.1.1
Built => Jan 13 2024 19:48:05
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.2.0 23 Nov 2023
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.12
brotli => E16781312/D16781312
async_redis => enabled
coroutine_pgsql => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

uname -a：
Darwin MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112 arm64

php - v：
PHP 8.1.27 (cli) (built: Dec 19 2023 20:35:55) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.27, Copyright (c) Zend Technologies
    with Xdebug v3.3.1, Copyright (c) 2002-2023, by Derick Rethans
    with Zend OPcache v8.1.27, Copyright (c), by Zend Technologies

gcc -v：
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

php-ext：

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
grpc
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
swoole
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache

**Comment by NathanFreeman** [comment]
估计是xdebug的问题，尝试把xdebug屏蔽掉

**Comment by pizsd** [comment]
> 估计是xdebug的问题，尝试把xdebug屏蔽掉

[2024-03-18 11:57:43 $69673.0]	WARNING	Server::check_worker_exit_status(): worker(pid=69677, id=3) abnormal exit, status=0, signal=10 ， 禁用掉xdebug，直接进程退出，我看好像只链接pgsql的时候会这样

**Comment by pizsd** [comment]
> 估计是xdebug的问题，尝试把xdebug屏蔽掉

我找到问题原因了，应该是swoole-pgsql的问题，开始swoole的协程pgsql就会出现上面的问题，目前我禁用了swoole-pgsql

**Comment by NathanFreeman** [comment]
我稍后看一下

**Comment by matyhtf** [comment]
swoole-pgsql 要废弃了，建议使用 pdo-pgsql

**Comment by pizsd** [comment]
这个问题又出现了😂，扩展什么的都没有动，感觉还是有兼容问题
