### ISSUE TITLE
Question: Coroutine\Http\Server Settings

### ISSUE THREAD

**Issue by xuanyanwow** [swoole/swoole-src#5284]
### 已知：
- 异步风格 Server 文档中有详细的每一项配置的说明和默认值介绍
- 协程风格 TCP Server 有set参数的说明（指向了 https://wiki.swoole.com/#/coroutine_client/socket?id=setprotocol ） 
- 协程风格 HTTP Server / Websocket Server  `由于 HTTP 解析性能原因使用 C++ 编写，因此并非由 PHP 编写的 [Co\Server](https://wiki.swoole.com/#/coroutine/server) 的子类。` ，既不继承 也无 settings 的说明

### 想了解的问题：
协程风格下是否支持 keep-alive 等参数的配置，进行 [维持长连接](https://wiki.swoole.com/#/question/use?id=swoole%e5%a6%82%e4%bd%95%e7%bb%b4%e6%8c%81tcp%e9%95%bf%e8%bf%9e%e6%8e%a5)

**Comment by Daixs020** [comment]
我不到啊！

**Comment by NathanFreeman** [comment]
协程服务端是看客户端的请求头中的Connection来设置长链接的，不用手动设置

**Comment by xuanyanwow** [comment]
https://wiki.swoole.com/#/server/setting?id=open_tcp_keepalive

最终要解决的问题是`检测死连接`，通过这几个参数控制调整自己业务所能容忍的检测周期

**Comment by NathanFreeman** [comment]
这几个参数协程化服务端没法设置

**Comment by xuanyanwow** [comment]
那目前协程服务端在检测死连接的问题有做相关的处理么

**Comment by NathanFreeman** [comment]
目前不支持

**Comment by xuanyanwow** [comment]
有在计划中？

另一个问题：协程风格websocket server::close无法传参code和reason

```php
// 异步风格
Swoole\WebSocket\Server->disconnect(int $fd, int $code = SWOOLE_WEBSOCKET_CLOSE_NORMAL, string $reason = ''): bool
```
【根据 RFC6455，对于应用程序关闭连接状态码，取值范围为 1000 或 4000-4999 之间】

**Comment by matyhtf** [comment]
1. 协程 Server 建议使用 PHP 代码创建一个定时器，轮询切断超时的连接
2. `Response::push()` 可以支持发送 `SWOOLE_WEBSOCKET_OPCODE_CLOSE` 类型的 frame，传递 code 和 reason
