### ISSUE TITLE
worker内部代码错误导致无限重启

### ISSUE THREAD

**Issue by yelo-17133** [swoole/swoole-src#529]
如果 worker 的启动代码中有严重错误，会导致 worker crash，被管理进程自动重启。但重启后立刻又crash，这样会进入死循环，cpu 100%只有重启机器能解决。

你可以在 manager进程中加个判断，一秒内worker重启次数太过频繁就不再启动worker，直接终止整个server。

**Comment by matyhtf** [comment]
使用PHP的致命错误捕获，防止类似问题发生。
