### ISSUE TITLE
mac 通过swoole-cli运行项目无法导出数据

### ISSUE THREAD

**Issue by Sheldon1024** [swoole/swoole-src#5292]
通过php index.php启动项目的方式可以正常导出excel数据但是通过swoole-cli index.php的方式启动项目会无法导出Excel提示文件找不到

![20240410-140722](https://github.com/swoole/swoole-src/assets/63155170/6c8c9bd4-a44c-40d9-886f-27304af12801)

**Comment by NathanFreeman** [comment]
你用的是xlswriter这个扩展吗，看看`swoole-cli -m`有没有这个扩展

用的swoole-cli是cygwin版本的吗

**Comment by NathanFreeman** [comment]
或者输出一下__FILE__这个常量看一下执行的index.php的完整文件路径

**Comment by Sheldon1024** [comment]
> 你用的是xlswriter这个扩展吗，看看`swoole-cli -m`有没有这个扩展

通过swoole-cli -m 没有找到对应的xlswriter拓展但是通过php -m是有这个拓展的
<img width="536" alt="image" src="https://github.com/swoole/swoole-src/assets/63155170/561924c4-5a0d-4455-909c-c3748240dd33">



我是通过下载的文件直接执行的./swoole-cli 如何配置变量全局可用

**Comment by NathanFreeman** [comment]
swoole-cli是静态编译的，没法动态加载so文件，只能重新手动编译xslwriter到swoole-cli

**Comment by jingjingxyk** [comment]
@Sheldon1024  使用swoole-cli  main 分支，自己编译swoole-cli ，编译时 如下配置：

```shell

 php preapre.php +xlswriter

```

这样编译出来的swoole-cli 就包含了 xlswriter 扩展
