### ISSUE TITLE
swoole 5.1.2编译安装提示error: ‘gettid’ was not declared in this scope; did you mean ‘getuid’

### ISSUE THREAD

**Issue by hanwei88** [swoole/swoole-src#5299]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

thirdparty/php83/Zend/zend_call_stack.cc:106:28: error: ‘gettid’ was not declared in this scope; did you mean ‘getuid’?
  106 |         return getpid() == gettid();
      |                            ^~~~~~
      |                            getuid
make: *** [Makefile:573：thirdparty/php83/Zend/zend_call_stack.lo] 错误 1

**Comment by NathanFreeman** [comment]
麻烦提供一下编译的环境参数

**Comment by hanwei88** [comment]
> 麻烦提供一些编译的环境参数

./configure --with-php-config=/media/hanwei/68477DFF36C47279/php/83/bin/php-config --enable-openssl --enable-swoole-curl --enable-cares --enable-brotli --enable-swoole-pgsql --enable-swoole-sqlite --enable-mysqlnd --enable-sockets

**Comment by hanwei88** [comment]
> 麻烦提供一些编译的环境参数

./configure --with-php-config=/media/hanwei/68477DFF36C47279/php/83/bin/php-config --enable-openssl --enable-swoole-curl --enable-cares --enable-brotli --enable-swoole-pgsql --enable-swoole-sqlite --enable-mysqlnd --enable-sockets && make -j8 && make -j8 install

**Comment by NathanFreeman** [comment]
服务器是什么类型的服务器，php的版本是多少

**Comment by hanwei88** [comment]
deepin 23 beta3 ，php版本是 php-8.3

**Comment by hanwei88** [comment]
> 服务器是什么类型的服务器，php的版本是多少
这与系统没啥关系吧，swoole 5.1.1版本可以编译的

**Comment by NathanFreeman** [comment]
`deepin`的系统我得下载一个看看，可能真的没`gettid`这个函数

**Comment by hanwei88** [comment]
> `deepin`我得下载一个看看，可能真的没有`gettid`这个函数

我在/media/hanwei/68477DFF36C47279/软件包/编程/php/swoole-src-5.1.2/thirdparty/php83/Zend/zend_call_stack.cc头部加上这个就可以编译通过了:
![image](https://github.com/swoole/swoole-src/assets/93665931/da570ff8-0e24-4d5c-8fc1-73e415c043e0)
![image](https://github.com/swoole/swoole-src/assets/93665931/0881a416-33b0-45f5-9504-33566efc7b97)

#include <sys/syscall.h>
#define gettid() syscall(__NR_gettid)

**Comment by matyhtf** [comment]
已移除 gettid 相关代码
