### ISSUE TITLE
Websocket connection failed. SSL related Issue?

### ISSUE THREAD

**Issue by kwanweijeat** [swoole/swoole-src#5307]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
A customer service chatbox app with thinkphp framework that deployed on aapanel. 
Free SSL from Cloudflare (doesn't work)
Free SSL from Aapanel( Let's Encrypt) doesn't work 

2. What did you expect to see?
The server and websocket is connected

3. What did you see instead?
websocket connection failed. socket connect error. server connection failed. 

4. What version of Swoole are you using (show your `php --ri swoole`)?
Php 8.0, swoole4 and swoole5

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Centos

**Comment by NathanFreeman** [comment]
Please provide a simple script for reproducing the error.
