### ISSUE TITLE
Can allow_redirects be supported on the HTTP/WebSocket?

### ISSUE THREAD

**Issue by Mxmilu666** [swoole/swoole-src#5312]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
support allow_redirects on the HTTP/WebSocket
 
2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by NathanFreeman** [comment]
请描述一下你想要支持`allow_redirects`的实现什么功能

**Comment by Mxmilu666** [comment]
就最简单的 比如说get() download()支持302跟随
因为我现在需要下载文件，但是下载的地址是302过去的，如果download()的话就无法下载到目标文件

**Comment by Mxmilu666** [comment]
可能我描述的不是很清楚，是HTTP/WebSocket客户端

**Comment by NathanFreeman** [comment]
HTTP/WebSocket客户端不支持这么操作，看看能否通过HTTP/WebSocket客户端的`getHeaders()`判断状态码是否302，是的话直接访问响应头的`Location`指向的地址。

**Comment by Mxmilu666** [comment]
但是我302跳转可能是三个302或者两个302 那没办法的话我只能自己写逻辑了:(

**Comment by twose** [comment]
你说的是 Coroutine HTTP Client 吧，现在都不用那个了，直接用 cURL 就有，社区库用 guzzle 就可以。

**Comment by Mxmilu666** [comment]
那我看看别的库什么的
