### ISSUE TITLE
WARN    swSSL_recv: SSL_read(40, 4294967294) failed, errno=1.

### ISSUE THREAD

**Issue by mysteriouss** [swoole/swoole-src#532]
日志挤爆硬盘，如下

    [2016-02-24 04:16:56 #16399.0]  WARN    swSSL_recv: SSL_read(40, 4294967294) failed, errno=1.
    [2016-02-24 04:16:56 #16399.0]  WARN    swSSL_recv: SSL_read(44, 4294967294) failed, errno=1.
    [2016-02-24 04:16:56 #16399.0]  WARN    swSSL_recv: SSL_read(40, 4294967294) failed, errno=1.
    [2016-02-24 04:16:56 #16399.0]  WARN    swSSL_recv: SSL_read(44, 4294967294) failed, errno=1.
    [2016-02-24 04:16:56 #16399.0]  WARN    swSSL_recv: SSL_read(40, 4294967294) failed, errno=1.
    ...
    毫秒级WARN，持续了半个小时，产生10GB以上的数据，雪崩
...

求关闭WARN方法

swoole-1.7.22-stable
php-5.6.13

**Comment by matyhtf** [comment]
客户端还是服务器端？什么样的代码？

**Comment by mysteriouss** [comment]
服务端，代码与  [#409](https://github.com/swoole/swoole-src/issues/409) 一致, 去掉了心跳检测，异常之前日志: 等我一下

**Comment by mysteriouss** [comment]
从这个客户端连入的时间来看是正常的，每5秒重连一次，但是这个hex数据有异常

不存在对  300c020101600702010204008000 的处理，这段数据也不会从客户端发出来，还有

4f5054494f4e53207369703a6e6d205349502f322e300d0a5669613a205349502f322e302f544350206e6d3b6272616e63683d666f6f0d0a46726f6d3a203c7369703a6e6d406e6d3e3b7461673d726f6f74

实际是
OPTIONS sip:nm SIP/2.0
Via: SIP/2.0/TCP nm;branch=foo
From: <sip:nm@nm>;tag=root

**Comment by mysteriouss** [comment]
补充
证书是PositiveSSL Wildcard
颁发机构是 COMODO CA Limited 
颁发机构名称是 COMODO RSA Domain Validation Secure Server CA
TrustCA地址是 http://crt.comodoca.com/COMODORSAAddTrustCA.crt 
http://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt (自带槽点)

**Comment by mysteriouss** [comment]
最近的改动(大概是前天) 执行了$server->after, 延迟执行代码，先去掉观察，很有可能是这里的问题吧 @matyhtf

**Comment by matyhtf** [comment]
去掉`after`后没有问题吗，这个可能和`after`没有关系。

**Comment by mysteriouss** [comment]
运行正常，after执行的日志没有异常

读了以下更早的log，fd=40,44没有异常

    Client@[217:1]: Connect from 14.18.17.180.
    16-02-24 04:15:59       [#14515]
    Client@[218:2]: Connect from 14.18.17.180.
    16-02-24 04:16:04       [#14516]
    Client@[219:3]: Connect from 14.18.17.180.
    16-02-24 04:16:09       [#14513]

这三个没有onClose回调. 

目前不知道是什么造成的swConnection_recv死循环.

**Comment by matyhtf** [comment]
最新的1.8.3 master分支代码已解决。

**Comment by mysteriouss** [comment]
CPU 100%问题又发生了但是这次没有任何日志

监控项: cpu
- 条件: > 90 %
- 状态: 告警
- 近期监控数据: [98.5]

![屏幕快照 2016-05-07 下午2.19.24.png](https://ooo.0o0.ooo/2016/05/07/572d8a45e0872.png)

手动重启了

**Comment by mysteriouss** [comment]
又出现了，这期间我有测试其它的Swoole Server实例(ctrl + c结束重启)不知道是否有关系

```bash
15300 <... epoll_wait resumed> {{EPOLLIN, {u32=30, u64=30}}, {EPOLLIN, {u32=34, u64=34}}}, 4096, -1) = 2
15296 futex(0x7f899aad3150, FUTEX_WAKE, 1 <unfinished ...>
15301 <... epoll_wait resumed> {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15300 epoll_wait(22,  <unfinished ...>
15296 <... futex resumed> )             = 0
15301 epoll_wait(21,  <unfinished ...>
15300 <... epoll_wait resumed> {{EPOLLIN, {u32=30, u64=30}}, {EPOLLIN, {u32=34, u64=34}}}, 4096, -1) = 2
15296 nanosleep({0, 100000000},  <unfinished ...>
15301 <... epoll_wait resumed> {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15300 close(22 <unfinished ...>
15301 epoll_wait(21, {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15300 <... close resumed> )             = 0
15301 epoll_wait(21, {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15301 epoll_wait(21,  <unfinished ...>
15300 madvise(0x7f89932fd000, 10465280, MADV_DONTNEED <unfinished ...>
15301 <... epoll_wait resumed> {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15301 epoll_wait(21,  <unfinished ...>
15300 <... madvise resumed> )           = 0
15301 <... epoll_wait resumed> {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15301 epoll_wait(21,  <unfinished ...>
**15300 _exit(0)                          = ?**
15301 <... epoll_wait resumed> {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15301 epoll_wait(21, {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
**15300** +++ exited with 0 +++
15301 epoll_wait(21, {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15301 epoll_wait(21, {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15301 epoll_wait(21, {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15301 epoll_wait(21, {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15301 epoll_wait(21, {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15301 epoll_wait(21, {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15301 epoll_wait(21, {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15301 epoll_wait(21, {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
15301 epoll_wait(21, {{EPOLLIN, {u32=35, u64=35}}}, 4096, -1) = 1
```

**Comment by matyhtf** [comment]
WebSocket服务器吗？如果是请更新到 `1.8.5-rc2 `

**Comment by mysteriouss** [comment]
不是的，是mqtt， [#655](https://github.com/swoole/swoole-src/issues/655)

**Comment by mysteriouss** [comment]
很容易复现，我再另外多开一个Swoole TCP Server (open_mqtt_protocol + 相同的ssl key cert启动另外一个端口)，然后Ctrl+C结束(kill -2)这个新开的，原来运行的受影响出现上面死循环

**Comment by matyhtf** [comment]
请重新提交一个issue，把可复现的demo程序上传到issue页面中。

**Comment by mysteriouss** [comment]
ok
