### ISSUE TITLE
MACOS M1 SIGRTMIN

### ISSUE THREAD

**Issue by daady-zh** [swoole/swoole-src#5336]
/Users/daady/swoole-src/src//server/master.cc:915:34: error: use of undeclared identifier 'SIGRTMIN'
        swoole_kill(worker->pid, SIGRTMIN);
                                 ^
/Users/daady/swoole-src/src//server/master.cc:918:38: error: use of undeclared identifier 'SIGRTMIN'
        swoole_kill(gs->manager_pid, SIGRTMIN);
                                     ^
2 errors generated.
make: *** [src//server/master.lo] Error 1

**Comment by NathanFreeman** [comment]
what is your swoole version?

**Comment by daady-zh** [comment]
> what is your swoole version?
The latest version install on Mac M1
