### ISSUE TITLE
面向aop开发

### ISSUE THREAD

**Issue by wheakerd** [swoole/swoole-src#5353]
使用swoole开发的框架很多，我希望能够像java一样能够完美的实现aop、动态代理。但是php无法对堆管理器进行操作，而java能够操作jvm的字节码来实现动态代理。而我已知的知识中，想要在php中实现这样的功能，必须在类引入前生成替换原类的缓存文件来替换引入类进行动态代理，或者像hyperf一样使用trait类增加代理行为，但其本身仍然要生成缓存。
于是我找到了匿名类的资料，希望一个匿名类能够动态的继承一个实例的超类，来满足依赖注入的所需类型，并且增加代理行为来对类信息进行捕获注解信息增加连接点和切点等，扩展继续开发的简便性。然而这存在了诸多问题，面临的第一个问题是无法对php的底层堆管理器进行操作，因此我需要考虑使用文件缓存，但对原文件的修改并不能够确保作用是一致的，最后我使用eval函数，这个函数实现了我想法的同时也意味着必须删减php自身的一些内容，比如final定义，也许后面会更多，同时附带着此函数是不安全的，我无法保证使用的开发者是否也会考虑安全方面，类似序列化注入等攻击司空见惯。
最终，我想到了一个方式，也可能我的技术水平并不是很高，提出的这个想法不是很好。如下：
现在我希望能够在进程中创建线程来生成类文件缓存来替代缓存，从此线程中完全完成类的实例化代理，创建新的线程池，来接受请求的处理，协程加快线程处理。但是这样貌似必须线程和进程是隔离的，swoole6.0开始貌似可以。
我有像php的官方提出此想法，但是以“类的动态继承的想法拒绝，php官方貌似并不了解什么是动态代理”。所以我在swoole的issue中提出了这个想法。也希望能够得到大牛的一些建议和想法。谢谢。

**Comment by wheakerd** [comment]
或者借助于swoole能够实现动态代理吗？

**Comment by jingjingxyk** [comment]
1. https://github.com/nikic/PHP-Parser

**Comment by matyhtf** [comment]
https://github.com/open-telemetry/opentelemetry-php-instrumentation
