### ISSUE TITLE
server.pid file is not created

### ISSUE THREAD

**Issue by fakharksa** [swoole/swoole-src#5356]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

I am trying to apply the [solution](https://github.com/swoole/swoole-src/issues/2788#issuecomment-532075712) you gave on this [issue](https://github.com/swoole/swoole-src/issues/2788) 

My swoole server configuration are as below:

        'daemonize'             => 1,
        'user' => 'www-data',
        'group' => 'www-data',
        'pid_file' => __DIR__.'/server.pid',

i started http server (through script) and tested, all works fine but server.pid file is not created.

Note: I also tried without 'user' and 'group' setting but issue persisted.

2. What did you expect to see?

server.pid file in my prpoject root ( which is the path from __DIR__)

3. What did you see instead?

no server.pid found 

4. What version of Swoole are you using (show your `php --ri swoole`)?

version 5.1.2

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

PHP 8.3.7 (cli) (built: May 23 2024 12:36:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.7, Copyright (c), by Zend Technologies
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

**Comment by NathanFreeman** [comment]
Please check if the code is running using `ps aux | grep php`. If it is running, please use `find ./ -name server.pid` to locate the file.
