### ISSUE TITLE
onFinish回调的疑似内存泄漏

### ISSUE THREAD

**Issue by szyhf** [swoole/swoole-src#536]
你好：
       在使用server的onFinish回调中发现了一个疑似的内存泄漏情况。

### 环境：
    lsb_release -a
        LSB Version:	:core-4.1-amd64:core-4.1-noarch
        Distributor ID:	CentOS
        Description:	CentOS Linux release 7.2.1511 (Core) 
        Release:	7.2.1511
        Codename:	Core

       php7.0.2
       swoole1.8.1  默认编译无设置参数。

swoole配置：
```
worker_num               => 2
max_conn                 => 65535
task_worker_num          => 4
task_ipc_mode            => 2
task_tmpdir              => /Runtimes/Temp
dispatch_mode            => 2
message_queue_key        => 856752448
backlog                  => 128
log_file                 => /Log/NewServer.log
heartbeat_check_interval => 6
heartbeat_idle_time      => 12
open_length_check        => 1
package_length_type      => L
package_max_length       => 10485760
open_tcp_nodelay         => 1
buffer_output_size       => 10485760
discard_timeout_request  => 1
```
### OnReceive回调中
```
$data = (string)time();
$Server->task('hello task');
$Server->send($fd,$data);
```
### OnTask回调中
```
echo $msg.PHP_EOL；
$server->finish('finish');
```
### 其他：
设置了100个客户端持续向服务发送心跳包（自己定义的协议，无特殊功能，仅触发Receive用）
### 现象：
只要在OnTask中调用了finish方法，哪怕在worker的OnFinish回调中什么都不做，在worker进程中调用memory_get_usage(true)和memory_get_peak_usage(true)这两个方法获得的内存量都会缓慢上升，关闭客户端以后停止上升，运行一段时间不会下降（未被回收），从nomon也能看到系统内存持续下降的现象。如果使用kill -10重载服务，则内存恢复正常，但如果继续触发OnFinish，则又会慢慢上升。
从我目前观察的情况，上升的规律很诡异的是每次2M，就是刚启动的时候是2m，第一次上升就变成4m，再上升就是6、8、10。。。这样
如果不调用onFinish方法，则内存保持稳定无明显变化。

**Comment by matyhtf** [comment]
感谢反馈，这个问题我确认一下。

**Comment by szyhf** [comment]
不客气，补充一下我这里的情况是从memory_get_usage看到的上升是周期性的，运行了一段时间（此时我并发了很多客户端发心跳包）以后会忽然从2m变4m，再过一段时间会忽然变6m；如果不在Task进程调用finish方法就不会。
内存增长的周期长度我暂时没找出什么规律，一般是3~5分钟的样子，似乎更并发量有关（不确定）

**Comment by matyhtf** [comment]
已修复，确实存在内存泄漏
