### ISSUE TITLE
free(): invalid pointer when curl support is on

### ISSUE THREAD

**Issue by mlocati** [swoole/swoole-src#5365]
As reported at https://github.com/swoole/docker-swoole/issues/45, swoole caused a segmentation fault.
That issue has been closed, but swoole 5.1.3 still causes an error.

In order to replicate this issue, start a docker image with

```sh
docker run --rm -it php:8.2-cli-bookworm bash
```

Inside that container, run:

```
$ apt-get update -q

$ apt-get install -qy libcurl4-gnutls-dev

$ MAKE="make -j$(nproc)" pecl install swoole
enable sockets supports? no
enable openssl support? no
enable mysqlnd support? no
enable curl support? yes
enable cares support? no
enable brotli support? no
enable PostgreSQL database support? no
enable ODBC database support? no
enable Oracle database support? no
enable Sqlite database support? no

$ docker-php-ext-enable swoole

$ php --ri swoole
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.1.3
Built => Jun  7 2024 14:49:53
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
json => enabled
curl-native => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

$ php -r 'var_dump(curl_exec(curl_init("http://127.0.0.1")));'
free(): invalid pointer
Aborted
```

If we don't enable the curl support, we have:

```
$ php -r 'var_dump(curl_exec(curl_init("http://127.0.0.1")));'
bool(false)
```

**Comment by NathanFreeman** [comment]
Try replacing `libcurl4-gnutls-dev` with `libcurl4-openssl-dev` and try again.

**Comment by NathanFreeman** [comment]
Try replacing `libcurl4-gnutls-dev` with `libcurl4-openssl-dev` and try again.

**Comment by mlocati** [comment]
> Try replacing `libcurl4-gnutls-dev` with `libcurl4-openssl-dev` and try again.

That works.

Can the support for libcurl4-gnutls-dev be fixed?

**Comment by NathanFreeman** [comment]
I need to research that. I haven't used the `libcurl4-gnutls-dev` dependency much.

**Comment by mhkarimi1383** [comment]
@NathanFreeman 
When will the problem be fixed?
We are not able to  build our PHP base images (enabling curl support will make composer to get core dump error)

**Comment by NathanFreeman** [comment]
Fix this issue this week, try replacing `libcurl4-gnutls-dev` with `libcurl4-openssl-dev` @mhkarimi1383

**Comment by mhkarimi1383** [comment]
> Fix this issue this week, try replacing `libcurl4-gnutls-dev` with `libcurl4-openssl-dev` @mhkarimi1383 

Thanks, solved the problem

I think it should be added as a notice somewhere until problem solves

**Comment by NathanFreeman** [comment]
This appears to be due to PHP depending on libcurl4-openssl-dev, and then installing libcurl4-gnutls-dev, causing dependency confusion.

**Comment by matyhtf** [comment]
The versions of header files and dynamic link libraries must be exactly the same

**Comment by mlocati** [comment]
So, the only solution is to use `libcurl4-openssl-dev`?

> This appears to be due to PHP depending on libcurl4-openssl-dev, and then installing libcurl4-gnutls-dev, causing dependency confusion

There are many other PHP extensions that work with `libcurl4-gnutls-dev` without any problems...
