### ISSUE TITLE
不支持apache2.4+php7么？

### ISSUE THREAD

**Issue by weijer** [swoole/swoole-src#537]
客户端在ngnix1.9 +php7下 可以连接

在apache2.4+php7下没反应

apache需要什么特需配置么

**Comment by weijer** [comment]
可以了~ 重新编译了下apache

**Comment by yhl54199** [comment]
@weijer ,你是怎么编译的呢，我这边发现apache2.4 new swoole_client也没有任何反应

**Comment by matyhtf** [comment]
不支持Apache多线程模式
