### ISSUE TITLE
WARNING Server::check_worker_exit_status(): worker(pid=8162, id=13) abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by jasonccs** [swoole/swoole-src#5388]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

[DEBUG] Event Hyperf\Process\Event\BeforeProcessHandle handled by Hyperf\Process\Listener\LogBeforeProcessStartListener listener.
[DEBUG] Event Hyperf\Process\Event\BeforeProcessHandle handled by Hyperf\Server\Listener\InitProcessTitleListener listener.
[2024-06-29 22:42:51 $7647.0]   WARNING Server::check_worker_exit_status(): worker(pid=8162, id=13) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v5.1.3, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64
GCC_VERSION: 10.3.1 20211027
PHP_VERSION : 8.3.8

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.1.3
Built => Jun 29 2024 19:22:14
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
json => enabled
pcre => enabled
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
OS: Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64
GCC_VERSION: 10.3.1 20211027
PHP_VERSION : 8.3.8

**Comment by jasonccs** [comment]
![image](https://github.com/swoole/swoole-src/assets/17975766/9e732eb1-59e4-4803-b3f4-10254d63eb31)
Hyperf 启动 一直反复打印这个

**Comment by NathanFreeman** [comment]
请检查一下是否有xdebug这个扩展，是的话先屏蔽掉，虽然swoole5可以兼容xdebug，但是xdebug中的某个配置会触发swoole进程不断重启，除非找到是具体哪个xdebug配置引起的问题。而且xdebug引发的错误信息还不会输出到终端中

**Comment by matyhtf** [comment]
```shell
USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php your_file.php
```

**Comment by jasonccs** [comment]
这是来自QQ邮箱的假期自动回复邮件！
    您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，第一时间给您回复。
