### ISSUE TITLE
problem with variable value

### ISSUE THREAD

**Issue by 0utc0ntr0l2021** [swoole/swoole-src#5392]
when a variable value = myhamilton.ca it make issue and worker exit !!!
[2024-07-01 07:39:19 $704.0]	WARNING	Server::check_worker_exit_status(): worker(pid=881, id=0) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v5.1.3, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Linux 6.1.0-22-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64
GCC_VERSION: 12.2.0
OPENSSL_VERSION: OpenSSL 3.0.13 30 Jan 2024
PHP_VERSION : 8.3.8

**Comment by 0utc0ntr0l2021** [comment]
i have list of domains in txt file
i make loop to take every line and run class get information's of domain and store it in data base
when it reach to line has this value worker exit and not write any thing in php log just in swoole log

**Comment by NathanFreeman** [comment]
Please check if the xdebug extension is installed. If yes, please disable it. Although swoole5 is compatible with xdebug, a specific xdebug configuration can cause swoole processes to restart continuously until we identify which xdebug configuration is causing the issue.

**Comment by matyhtf** [comment]
```shell
USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php your_file.php
```

Check whether the output contains invalid read/write memory overrun errors
