### ISSUE TITLE
6.0开启线程，打开文件过多

### ISSUE THREAD

**Issue by yunxiao522** [swoole/swoole-src#5398]
6.0版本，以线程开启http服务，过一段时间后提示打开文件过多

**Comment by NathanFreeman** [comment]
可以的话提交一下错误截图和复现代码

**Comment by yunxiao522** [comment]
![Uploading Snipaste_2024-07-09_02-49-02.png…]()

**Comment by yunxiao522** [comment]
还有一种报错也是提示打开文件过多的报错
` WARNING Server::accept_connection(): accept() failed, Error: Too many open files[24]`

**Comment by LIngMax** [comment]
每个线程  都是unixSocket通信on事件的

  如果线程过多   不建议用SWOOLE_THREAD   自己创建

**Comment by matyhtf** [comment]
调整 `ulimit -n` 设置，减少 `worker_num` 工作线程数量
