### ISSUE TITLE
swoole5.1.3 运行时异常退出

### ISSUE THREAD

**Issue by ren-jimmy** [swoole/swoole-src#5402]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

hyperf启动后，发起HTTP请求时，swoole进程异常退出。
![image](https://github.com/swoole/swoole-src/assets/25098996/71f3ef1f-216e-40a7-8732-366dcf248b3c)
<img width="674" alt="image" src="https://github.com/swoole/swoole-src/assets/25098996/9696badd-6d8c-4f92-8df6-df16f0ba2dd7">

2. What did you expect to see?

正常运行

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

<img width="674" alt="image" src="https://github.com/swoole/swoole-src/assets/25098996/c4b27f40-4f33-4c47-88aa-47a686c50cf7">

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

![image](https://github.com/swoole/swoole-src/assets/25098996/ff02a81d-2ecf-40e7-91e9-668eb3ca2977)
![image](https://github.com/swoole/swoole-src/assets/25098996/240109d1-d294-4393-bbfc-ffac1e9d2d50)
![image](https://github.com/swoole/swoole-src/assets/25098996/7996c9a2-8a1c-4cf3-97b7-56590906c561)

**Comment by jingjingxyk** [comment]
看报错提示，应该是依赖库冲突

用swoole-cli 试试，看看是否也报这个错。https://github.com/swoole/swoole-cli/releases/tag/v5.1.3.0

**Comment by ren-jimmy** [comment]
我降到swoole 5.1.2就可以了
![image](https://github.com/swoole/swoole-src/assets/25098996/6e54cab5-3eef-4673-9239-9202e84d935f)

**Comment by NathanFreeman** [comment]
可以的话用valgrind抓一下错误信息
https://wiki.swoole.com/zh-cn/#/other/issue?id=内存分析-强烈推荐

**Comment by ren-jimmy** [comment]
valgrind 好像不支持M1，brew无法安装

**Comment by matyhtf** [comment]
试试 make clean 后重新编译，也可能是依赖库存在问题，建议使用 swoole-cli
