### ISSUE TITLE
swoole v6.0.0-dev 版本的swoole-cli   异常

### ISSUE THREAD

**Issue by LIngMax** [swoole/swoole-src#5404]
这边拿到手测试了一下 swoole v6.0.0-dev 版本的swoole-cli    发现几个问题
https://github.com/jingjingxyk/swoole-cli/releases/tag/swoole-cli-v0.0.6
```
Swoole 6.0.0-dev (cli) (built: Jul  5 2024 18:53:54) (ZTS)
new Swoole\WebSocket\Server('0.0.0.0', 888,SWOOLE_THREAD );
```

1.   swoole6 多线程send()  靠unixSocket 传输数据?   性能限制挺大的  用Swoole\Thread\Queue 通信吧
我设置线程1000  报错提示 unixSocket 不够用  
```
 failed to start server. Error: UnixSocket::UnixSocket(): socketpair() failed, Error: No file descriptors available[24]
```

2.   设置SWOOLE_THREAD  worker_num=2  创建了3个线程都执行bootstrap  其中一个是主线程   线程数与设置预期不一致  去掉主线程执行bootstrap  或者减少一个线程

3.  设置SWOOLE_THREAD   open  message    WorkerStart 都没有回调  失灵了  只有bootstrap的执行 

4. 线程创建如果不用detach 无法创建>2个线程  WSL1
```
for ($i=0; $i <100; $i++) { 
    $t = new Swoole\Thread(__DIR__."/1.php", $map , $i+0);
    $t->detach();
}
```
5.  Queue 小数据传输性能很低  1千多次每秒  WSL1     内存数组操作则很快 千万起步  共享内存应该也很快才对    
 看着性能像unixsocket
```
$str = str_pad("",1024*1024,"a");
for ($i=0; $i <10000; $i++) { 
    $ags[0]['quqe']->push($str);
    $ags[0]['quqe']->pop(-1);
}
```

**Comment by matyhtf** [comment]
1. 多线程只是用线程替换了进程，依然需要使用 unixsocket 作为通信管道
2. 除了主线程之外，还有管理线程，因此 3次 是符合预期的
3. 你的设置可能存在一些问题，可以提交相关代码，单独提交 issue
4. 你未保存 Thread 对象，这样它会原地析构，析构函数会自动 join，等待子线程退出，正确的做法你应该存到数组或者使用 detach
5. 你这里的数据是 1M，而 push/pop 是需要拷贝内存的，1千万次开小时比较大

**Comment by LIngMax** [comment]
3.设置SWOOLE_THREAD open message WorkerStart 都没有回调 失灵了 只有bootstrap的执行
是因为独立了bootstrap 启动文件 没有执行start
