### ISSUE TITLE
V6.0 配置了bootstrap后 没有执行$server->on和$server->start   事件就会失效

### ISSUE THREAD

**Issue by LIngMax** [swoole/swoole-src#5406]
设置SWOOLE_THREAD open message WorkerStart 都没有回调 失灵了 只有bootstrap的执行

V6.0 配置了bootstrap 是空php文件后 没有执行$server->on和$server->start   貌似事件就会失效   

是正常的?

**Comment by matyhtf** [comment]
bootstrap 配置为 server.php ，否则将不会执行任何代码，线程直接退出，又重启

**Comment by matyhtf** [comment]
你对 bootstrap 的理解错了，主线程没有办法传递事件回调函数给子线程。所以 `bootstrap` 它应该是包含 `new Server` 代码的，也就是子线程依然需要再次执行一遍：

- `new Server`
- `Server::on()`
- `Server::start()`


否则工作线程无法设置事件回调函数。
