### ISSUE TITLE
Http2 Server/Response does not support streaming (gRPC Server Streaming RPC / Bidirectional Streaming RPC)

### ISSUE THREAD

**Issue by ytake** [swoole/swoole-src#5425]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

I've been working on implementing a gRPC stream server and discovered that currently, Swoole only supports Unary RPC.

To implement Server Streaming RPC / Bidirectional Streaming RPC, HTTP/2 frames need to be utilized. However,  
when I attempt to use the write method of Swoole\Http\Response,  
I receive the following error message: HTTP2 client does not support HTTP-CHUNK,  
and the operation fails. 

The relevant part of the code is here: [swoole_http_response.cc#L220-L222](https://github.com/swoole/swoole-src/blob/master/ext-src/swoole_http_response.cc#L220-L222).

While I can return a response once using the end method, this only allows for Unary RPC, not streaming.  
The following code works in OpenSwoole, enabling stream functionality,  
but it results in an error in Swoole, preventing the implementation of a stream server: [Server.php#L159-L179](https://github.com/openswoole/grpc/blob/master/src/Server.php#L159-L179).

Could you provide guidance on how to implement Server Streaming RPC / Bidirectional Streaming RPC with Swoole,  
or inform us if there are any plans to support this feature in the future?  

Alternatively, is there a method other than using the write method to achieve a stream server in Swoole?

2. What did you expect to see?

Response streamed to client (Server Streaming RPC / Bidirectional Streaming RPC). No warning from Swoole.

3. What did you see instead?

```
Swoole\Http\Response::write(): HTTP2 client does not support HTTP-CHUNK
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.1.3
Built => Jun 13 2024 00:08:15
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
http2 => enabled
json => enabled
pcre => enabled
zlib => 1.2.12
brotli => E16781312/D16781312
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 262144 => 262144
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
$ uname -a
Darwin ****** 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64
```

```
$ php -v
PHP 8.3.9 (cli) (built: Jul  2 2024 14:10:14) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.9, Copyright (c), by Zend Technologies
```

```
$ gcc -v
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/42f866440889197b8129fc084e14c8cba5680b3e
