### ISSUE TITLE
swoole6  设置dispatch_mode平均分配工作线程无效

### ISSUE THREAD

**Issue by LIngMax** [swoole/swoole-src#5427]
swoole6  dispatch_mode分配工作线程无效
`

$server = new Swoole\WebSocket\Server(UNIX_SOCKET,0, SWOOLE_THREAD, SWOOLE_UNIX_STREAM );

$server->set([
'worker_num'            => 2,#CPU核数的1-4倍 默认值：CPU 核数 迎接Swoole 6多线程版本
    // 'bootstrap'             => __DIR__."/1.php",
    // 通过init_arguments实现线程间的数据共享。
    'init_arguments' => function (){
        global $map;
        return [$map];
    },
    'dispatch_mode'        =>1,#1平均分配 2按FD取模固定分配 3抢占式分配
    'enable_coroutine'      => true,#启用协程
    'task_enable_coroutine' => true,#Task启用协程
});

$server->on('WorkerStart', function ($server, $worker_id){
    Swoole\Runtime::enableCoroutine($flags = SWOOLE_HOOK_ALL);
    $GLOBALS['worker_id'] = $worker_id;#进程序号
    $GLOBALS['worker_id_only'] = ($worker_id+(int)WORK_HOST)*-1;#进程序号 唯一
    echo WORK_NUM."WorkerStart     {$GLOBALS['worker_id']} \n";
});

$server->on('open', function (){
    echo "open     {$GLOBALS['worker_id']} \n";
        sleep(5);
        throw new Exception("Error Processing Request", 1);

});
$server->on('message',function (){
    
    echo "message     {$GLOBALS['worker_id']} \n";
});
    Swoole\Runtime::enableCoroutine($flags = SWOOLE_HOOK_ALL);
$server->start();

`

1.每次链接都是同一个线程  感觉默认2绑定fd了
dispatch_mode无效

2.线程中work无法使用协程   无法启用 sleep真卡死了 无法处理别的请求  
dispatch_mode无效 整个线程不处理任务 相同ip的任务都被分配同一个 线程卡死
enable_coroutine无效  Swoole\Runtime::enableCoroutine($flags = SWOOLE_HOOK_ALL);无效

**Comment by NathanFreeman** [comment]
dispatch_mode只能用在SWOOLE_PROCESS

**Comment by LIngMax** [comment]
> dispatch_mode只能用在SWOOLE_PROCESS

多线程目前不支持协程
多线程模式依旧保持BASE绑定fd的话   
其中一个线程卡住阻塞  或者sleep  导致这个线程绑定的fd都会死掉无法处理

把SWOOLE_PROCESS的功能改线程版 用竞争分配模式？

**Comment by matyhtf** [comment]
多线程支持协程
