### ISSUE TITLE
多线程模式server达到max_request后进程终止；kill -USR1无法重启子线程

### ISSUE THREAD

**Issue by warmbook** [swoole/swoole-src#5428]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
A: 多线程模式设置max_request，然后通过客户端模拟请求。
B: 对主进程kill -USR1。

2. What did you expect to see?
A: 请求数达到max_request后重启子线程，依次回调WorkerExit、WorkerStart。
B: kill -USR1后重启全部子线程，逐个回调WorkerExit、WorkerStart。

3. What did you see instead?
A: 请求数达到max_request的约四分之一子线程就全部退出了，成功触发WorkerExit，但没有触发WorkerStart，重点是主进程也退出了。
B: WorkerExit、WorkerStart都没有触发，整个进程都没有反应，似乎没收到重启信号。

4. What version of Swoole are you using (show your `php --ri swoole`)?
6.0.0，https://github.com/jingjingxyk/swoole-cli/releases/tag/swoole-cli-v0.0.6
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 6.0.0-dev
Built => Jul  5 2024 18:52:12
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
thread => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.1.4+quic 24 Oct 2023
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
c-ares => 1.24.0
zlib => 1.3.1
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
coroutine_pgsql => enabled
coroutine_odbc => enabled
coroutine_sqlite => enabled

Directive => Local Value => Master Value
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Using built-in specs.
COLLECT_GCC=gcc
-bash: Swoole: command not found
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --disable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20200825 (Alibaba 10.2.1-3 2.32) (GCC)

**Comment by NathanFreeman** [comment]
我稍后看看

**Comment by matyhtf** [comment]
更新至 master 最新代码，重试一下
