### ISSUE TITLE
1.7.22升级到1.8.1后，所有的ssl异步tcp client连接后都直接断开了，触发on close事件

### ISSUE THREAD

**Issue by tangxunye** [swoole/swoole-src#543]
ssl_method使用SWOOLE_TLSv1_2_METHOD
在1.7.22下无问题
在1.8.1不使用SWOOLE_SSL连接时无问题

**Comment by matyhtf** [comment]
最新的 `1.8.2` 代码测试没问题。你可以使用新版本进行测试。
