### ISSUE TITLE
V6 chown函数异常

### ISSUE THREAD

**Issue by warmbook** [swoole/swoole-src#5437]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
chown($logFile,'nobody');

2. What did you expect to see?
文件所有者应改为 nobody

3. What did you see instead?
文件所有者依然是root，并出现以下提示：
Warning: chown(): Unable to find uid for nobody in ......
open(......) failed. Error: Permission denied[13]

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole V6

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux iZuf68ujmphbn8maxiqqp6Z 5.10.134-12.2.al8.x86_64 #1 SMP Thu Oct 27 10:07:15 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by NathanFreeman** [comment]
检查一下是否有nobody这个用户

**Comment by warmbook** [comment]
@NathanFreeman  nobody 是一个特殊的id，问题是在5.1.3上是好的， @jingjingxyk 基于6.0构建的这个[swoole-cli](https://github.com/jingjingxyk/swoole-cli/releases/tag/swoole-cli-v0.0.6)后就出问题了

**Comment by jingjingxyk** [comment]
在你的运行环境中，执行如下shell 命令 确认是否有输出
```bash

id -u  nobody 

```

swoole-cli v6 
https://github.com/jingjingxyk/swoole-cli/releases/tag/swoole-cli-v0.0.8

swoole v6 最大的区别就是  需要PHP 启用 ZTS (Zend Thread Safe) 环境

**Comment by jingjingxyk** [comment]
试试 把 nobody 换成 nobody 对应的uid 

chown https://www.php.net/manual/zh/function.chown.php

**Comment by warmbook** [comment]
@jingjingxyk 把 nobody 换成 nobody 对应的uid确实不报错了，但是感觉这不是长久之计吧？每台设备都要单独改代码

**Comment by jingjingxyk** [comment]
> @jingjingxyk 把 nobody 换成 nobody 对应的uid确实不报错了，但是感觉这不是长久之计吧？每台设备都要单独改代码

使用 `posix_getpwnam("nobody")`  
```php 

$uid = 0;
$userinfo = posix_getpwnam("nobody");
if ($userinfo !== false) {
    var_dump($userinfo);
    $uid = $userinfo ['uid'];
} else {
    throw new Exception(' no found user nobody ! ');
}


```

**Comment by warmbook** [comment]
不行，PHP代码中调用posix_getpwnam返回值是false，但是控制台执行id -u  nobody有值 @jingjingxyk

**Comment by warmbook** [comment]
@matyhtf 麻烦再开一下呢，问题还没有解决

**Comment by matyhtf** [comment]
建议 `strace` 追踪一下，swoole 中没有影响 `posix_getpwnam`、`chown` 的逻辑
