### ISSUE TITLE
V6 chown、函数异常

### ISSUE THREAD

**Issue by warmbook** [swoole/swoole-src#5449]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
chown($logFile,'nobody');
$userinfo = posix_getpwnam("nobody");

2. What did you expect to see?
文件所有者应改为 nobody，$userinfo不应该为FALSE

3. What did you see instead?
文件所有者依然是root，并出现以下提示：
Warning: chown(): Unable to find uid for nobody in ......
open(......) failed. Error: Permission denied[13]

4. What version of Swoole are you using (show your `php --ri swoole`)?
swoole V6

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux iZuf68ujmphbn8maxiqqp6Z 5.10.134-12.2.al8.x86_64 https://github.com/swoole/swoole-src/issues/1 SMP Thu Oct 27 10:07:15 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/issues/5437
