### ISSUE TITLE
Swoole build for PHP-8.4 ZEND_EXIT has been removed 

### ISSUE THREAD

**Issue by petk** [swoole/swoole-src#5451]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

```
# PHP 8.4 phpize
phpize
./configure
make
```

2. What did you expect to see?

Successful build.

3. What did you see instead?

```
/swoole-src/ext-src/swoole_coroutine.cc:990:57: error: 'ZEND_EXIT' was not declared in this scope; did you mean 'ZEND_CAST'?
  990 |         ori_exit_handler = zend_get_user_opcode_handler(ZEND_EXIT);
      |                                                         ^~~~~~~~~
      |                                                         ZEND_CAST
```

4. What version of Swoole are you using (show your `php --ri swoole`)?

master branch

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux, GCC, PHP 8.4

This is related to the recent RFC being merged to PHP 8.4 (current php-src master branch)
https://github.com/php/php-src/pull/13483

**Comment by NathanFreeman** [comment]
I will fix it later.

**Comment by NathanFreeman** [comment]
https://github.com/swoole/swoole-src/pull/5462
