### ISSUE TITLE
在协程里面先进行TCP请求然后MySQL操作，会导致TCP请求耗时大幅增加

### ISSUE THREAD

**Issue by netcccyun** [swoole/swoole-src#5452]
相关PHP代码如下：
```php
$num = 300; //每秒执行300次TCP连接
$target = '127.0.0.1';

Co::set(['hook_flags'=> SWOOLE_HOOK_ALL]);
Co\run(function() use($num, $target) {
    while(true){
        sleep(1);
        for($i=0; $i<$num; $i++) {
            go(function () use($target) {
                global $DB;
                try{
                    $usetime = check_by_tcp($target, 2);
                    echo 'TCP time: '.$usetime."\n";
                    $DB->insert('mchecks', ['did'=>1, 'status'=>0, 'delay'=>$usetime, 'date'=>'NOW()']); //将每次请求的耗时记录到数据库
                } catch (Exception $e) {
                    echo $e->getMessage()."\n";
                }
            });
        }
    }
});

// 返回TCP连接耗时
function check_by_tcp($target, $timeout){
	$port = 80;
	$starttime = getMillisecond();
	$fp = @fsockopen($target, $port, $errCode, $errStr, $timeout);
	if ($fp) {
		fclose($fp);
	}
	$endtime = getMillisecond();
    $usetime = $endtime-$starttime;
	return $usetime;
}

// 返回当前毫秒
function getMillisecond()
{
    list($s1, $s2) = explode(' ', microtime());
    return (int)sprintf('%.0f', (floatval($s1) + floatval($s2)) * 1000);
}
```

输出内容如下：
```
TCP time: 195
TCP time: 195
TCP time: 197
TCP time: 199
TCP time: 200
TCP time: 201
......
```

CPU占用不高，只有不超过30%，不存在客户端资源占满的情况。

假如把“将每次请求的耗时记录到数据库”这一行代码去掉，也就是不进行MySQL操作，输出的内容如下：
```TCP time: 9
TCP time: 9
TCP time: 10
TCP time: 10
TCP time: 10
.....
```

也就是协程内加入MySQL操作，会导致TCP连接的耗时大幅增加。有没有办法能拿到TCP请求真实的耗时信息？

**Comment by matyhtf** [comment]
TCP 耗时增加，若实际的网络情况未发生变化，那就是调度器的效率降低了，说明存在阻塞 IO 或者 密集计算，影响了调度器。建议使用 strace 追踪，是否存在阻塞 IO，另外检查当前进程的 CPU 占用，如果是多核 CPU ，30% 并不能说明当前进程没有负载

**Comment by netcccyun** [comment]
在mysql插入这一步是有阻塞发生的的，但是插入MySQL也是应用了一键协程化，不知道如何解决这个阻塞？

**Comment by matyhtf** [comment]
你的 mysql 资源必须在 hook 之后创建，否则依然是阻塞的，不会协程化

**Comment by netcccyun** [comment]
随着每秒执行TCP连接请求次数的增加，每次TCP请求耗时也会随之增加，但如果把这些TCP请求分到多个进程下运行就没有延迟增加的情况了（说明没有达到机器网络瓶颈，疑似单个进程的某个瓶颈），这个如何解决？

**Comment by matyhtf** [comment]
阻塞了，你需要先解决阻塞的问题。按照上面说的

**Comment by netcccyun** [comment]
我使用strace -T命令执行之后，延迟直接增加到了800~1000ms。而且我看输出的结果，也没法分辨出哪些是阻塞，哪些是正常的io操作。
另外从以上php代码，看不出来还有什么阻塞了，除非是swoole本身的阻塞

**Comment by netcccyun** [comment]
请问这个问题怎么解决？

**Comment by NathanFreeman** [comment]
@netcccyun 尝试用stream_set_blocking将fsockopen设置为非阻塞模式，默认情况下fsockopen将以阻塞模式开启套接字连接。

**Comment by netcccyun** [comment]
> @netcccyun 尝试用stream_set_blocking将fsockopen设置为非阻塞模式，默认情况下fsockopen将以阻塞模式开启套接字连接。

但是我的代码里面是先fsockopen，然后紧接着直接close了，stream_set_blocking是在fsockopen之后才能设置，也就是不能减少fsockopen建立连接的耗时

**Comment by NathanFreeman** [comment]
你可以尝试一下这个方法，因为代码阻塞的话，只有fsockopen默认是阻塞模式的

**Comment by netcccyun** [comment]
> 你可以尝试一下这个方法，因为代码阻塞的话，我这边看php的文档提及fsockopen默认是阻塞模式的

我试了不行，延迟没有变化
