### ISSUE TITLE
开启 OPcache 恐使 SWOOLE_HOOK_SLEEP 失效

### ISSUE THREAD

**Issue by pinerge** [swoole/swoole-src#5457]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

代码：

```php
<?php

use function Co\run;

run(function () {
    $cid[] = go(function () {
        sleep(1);
    });
    $cid[] = go(function () {
        sleep(1);
    });

    \Swoole\Coroutine::join($cid);
});
```

2. What did you expect to see?

![图片](https://github.com/user-attachments/assets/d0a26fa3-172a-44f1-8212-4996bd8d3bc8)

3. What did you see instead?

![图片](https://github.com/user-attachments/assets/9c1639a5-40df-4e98-a237-9f17934ba5e9)

如图所见，当启用 OPcache 时，sleep hook 似乎失效了，即使在 php.ini 中配置启用 swoole 和 opcache 结果也是和命令行启用扩展一样，于是我将代码改成了以下内容：

```php
<?php

use function Co\run;

run(function () {
    $cid[] = go(function () {
        \Swoole\Coroutine\System::sleep(1);
    });
    $cid[] = go(function () {
        \Swoole\Coroutine\System::sleep(1);
    });

    \Swoole\Coroutine::join($cid);
});
```

此时，OPcache 的启用与否皆不影响执行耗时为 1 秒。

所以断定是 OPcache 影响了 SWOOLE_HOOK_SLEEP，至于其他的 hook，还暂时未测试。

4. What version of Swoole are you using (show your `php --ri swoole`)?

![图片](https://github.com/user-attachments/assets/bf403605-5217-4d2b-a46d-557fc87b0fdd)

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

![图片](https://github.com/user-attachments/assets/ffcb5fa0-c1c4-4836-a5d6-280e37a3c0e7)

**Comment by pinerge** [comment]
![图片](https://github.com/user-attachments/assets/571e836b-9b1a-480d-b642-2b9ba2cd1f84)

补一张 OPcache 的配置。

**Comment by matyhtf** [comment]
配置的问题，参考 https://www.php.net/manual/zh/opcache.configuration.php#ini.opcache.jit

```
opcache.jit=1205
```

## 第三位：
```
T（触发）
0: 在脚本加载时编译所有函数。
1: 在第一次执行时编译函数。
2：第一次请求时分析函数，然后编译最热门函数。
3：动态分析和编译热门函数。
4：目前未使用。
5：使用追踪 JIT。动态分析和为热门代码段编译追踪。
```

配置 0 会导致编译后无法改变函数，导致 `Hook` 不生效。
