### ISSUE TITLE
http协议服务器，怎么设置请求超时呢？

### ISSUE THREAD

**Issue by lushaobo** [swoole/swoole-src#5459]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

类似于 php-fpm 的 max_execution_time 配置，能够控制请求的时间

2. What did you expect to see?

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by matyhtf** [comment]
没有类似的设置，建议增加一个定时器，在超时后执行 `Response::end()` ，但无法终止正在执行的 `onRequest` 任务

**Comment by lushaobo** [comment]
好的，多谢。
