### ISSUE TITLE
HTTP client does not support response headers with multiple occurrences

### ISSUE THREAD

**Issue by janreges** [swoole/swoole-src#5460]
1. What did you do? If possible, provide a simple script for reproducing the error.

Hi,

I'm the author of https://crawler.siteone.io/ and the main part is based on Swoole. It uses `Swoole\Coroutine\Http\Client`.

I'm implementing cache headers parsing and analysis now and I've encountered a big problem - when the server response returns `Cache-Control: max-age=123456` and `Cache-Control: public` (as two separate headers), in the client instance in `$client->headers` or `$client->getHeaders()`, only `['cache-control'] = 'public'` appears, but unfortunately I'm not able to get to the `max-age` any more.

Do you have any workaround to get to those values?

2. What did you expect to see?

I would expect the value of `cache-control` to be an array with the values `public` and `max-age=123456`.

Or that in the case of multiple occurrences of a single header, the Swoole client will automatically concatenate multiple values using a comma. This is also back-compatible, without datatype change.

3. What did you see instead?

I only see the value of last header occurrence.

4. What version of Swoole are you using (show your `php --ri swoole`)?

I tried 5.1.3 and 4.8.13 - the result is the same. I use builds from swoole-cli repo.

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/f4df7c9ca203721e2d4d4254321aaacacfb1d101

implemented
