### ISSUE TITLE
求 swoole-tracker 扩展下载

### ISSUE THREAD

**Issue by landso** [swoole/swoole-src#5469]
swoole开发的项目目前由轻微内存泄露，开发中已极尽努力避免泄露可能，目前检查无果。

swoole-tracker 官方的获取地址 https://business.swoole.com/SwooleTracker/apply 现在打不开了

求一个swoole-tracker 扩展下载，谢谢！

**Comment by NathanFreeman** [comment]
你的内存泄漏是内存使用一直在增长还是增长到一个值之后就不增长了

**Comment by landso** [comment]
> 你的内存泄漏是内存使用一直在增长还是增长到一个值之后就不增长了

一直增长
最后一次启动到现在13小时，请求数3305517，同一个worker，内存从启动时的10M，缓慢增长到90M，大概3天左右到512M，然后worker内存不足

**Comment by NathanFreeman** [comment]
swoole的版本是多少，php的memory_limit是多少，可以的话提供一下复现代码

**Comment by landso** [comment]
> ══════════════════════════════════════════════════════════
>                      coroutine_stats                      
> ──────────────────────┬───────────────────────────────────
>  event_num            │  7                               
> ──────────────────────┼───────────────────────────────────
>  signal_listener_num  │  1                               
> ──────────────────────┼───────────────────────────────────
>  aio_task_num         │  0                               
> ──────────────────────┼───────────────────────────────────
>  aio_worker_num       │  4                               
> ──────────────────────┼───────────────────────────────────
>  aio_queue_size       │  0                               
> ──────────────────────┼───────────────────────────────────
>  c_stack_size         │  2097152                         
> ──────────────────────┼───────────────────────────────────
>  coroutine_num        │  59                              
> ──────────────────────┼───────────────────────────────────
>  coroutine_peak_num   │  75                              
> ──────────────────────┼───────────────────────────────────
>  coroutine_last_cid   │  4129420
> ──────────────────────┴───────────────────────────────────

**Comment by landso** [comment]
关键是缓慢增长，无法从有限次的请求排查到问题所在😂

所以如果能提供一份swoole-tracker，我自行调试下最好，感谢🤞

**Comment by landso** [comment]
不是，面对开发者的求助就直接粗暴地close了？

**Comment by NathanFreeman** [comment]
你的memory_limit有点小，cli模式下对内存占用多，有可能一个数据库的大结果集就超过了512M，你可以尝试开到2048M，再观察下内存使用情况。

**Comment by NathanFreeman** [comment]
或者你看看
https://chat.swoole.com/#/chat?uuid=26ed48a5-2079-4351-82ef-f9dcaf5fc735
定时用gc_mem_caches()处理一下

**Comment by landso** [comment]
> 或者你看看 https://chat.swoole.com/#/chat?uuid=26ed48a5-2079-4351-82ef-f9dcaf5fc735 定时用gc_mem_caches()处理一下

使用gc_mem_caches()无效，内存还是持续增加，统计了所有的static变量，加起来才保存了十几M的数据，并且都没有持续增加。

实在不知道该如何调试了。。。

下图是一天内内存占用增长图表：

![memory_chart](https://github.com/user-attachments/assets/cb098bae-179d-4753-bcf3-b9bc0faa8cfb)

**Comment by landso** [comment]
而且突然发现，图中几处内存陡然升高的地方，增加的数值是成2倍的关系，从5M到10M、20M、40M，这是否是PHP或者swoole的某种内存管理机制？ 该图中纵坐标数据为进程内存使用量，是用 `round(memory_get_usage() / 1024 / 1024)` 计算的。

![821b995a65f033bccd847bd165f60e9](https://github.com/user-attachments/assets/4d79d840-1397-4b83-b37c-8ca9774ed50a)

**Comment by NathanFreeman** [comment]
你这张内存图很像是往数组里面不断添加数据，然后达到内存临界值之后这个数组自动扩容了成原本的两倍了。

**Comment by NathanFreeman** [comment]
这几条线段斜率不变，证明是往某个数组添加数据，结果达到临界值就自动扩容了

**Comment by NathanFreeman** [comment]
@landso 我猜可能是数组的扩容导致的问题

**Comment by landso** [comment]
> @landso 我猜可能是数组的扩容导致的问题

数组扩容确实会有这种特性，数组扩容后，即便删除数组中的所有值，数组结构所需的内存依旧占用。

我考虑了这种可能性，也做了一些实验，当数组的key从150000个增加到300000个，删除数组内所有值，内存占用从13M增加到23M，增幅为10M，以此规律，继续增加key的数量，数组结构内存增幅会以20M、40M等倍增。

但是我的应用中，最大常驻内存数组，峰值key数量也就1000多个，而且设计有过期GC机制，完全达不到以几M几十M扩容倍增，以至于占满所有512M内存的情况。

而且为这个内存泄露问题写了一些监测工具，显示所有的静态变量、object总量，都在设计范围，并无无序增长的情况。

并且审查了几乎所有代码，没有内存泄露可能，这些天觉都没睡好😂

最后在今天凌晨，将线上环境升级到了swoole5.1.4+php8.2，运行到现在12个多小时，300W次请求，内存占用稳定在12M左右，内存泄露问题消失了。

> 内存占用：12.34 MB / 29.44 MB / 128 MB
> 
> Server 启动时间：2024-09-19 07:16:57  12小时48分钟52秒
> 
> Worker 启动时间：2024-09-19 07:16:57  12小时48分钟52秒

> dispatch_count         │  3177608                         
> ────────────────────────
>  request_count          │  3177604                         
> ────────────────────────
>  response_count         │  3179181                         
> ────────────────────────
>  total_recv_bytes       │  2883514195                      
> ────────────────────────
>  total_send_bytes       │  6863970291                      

所以，这个问题应该存在于swoole 4.8.13版本，是否是一个已知问题，在5.1中修复了，而4.8中依然遗留？

**Comment by matyhtf** [comment]
可能是 PHP 层面改进，也可能 swoole-src 的 mem leak fix，版本差异较大，无法验证。

4.8 可通过 valgrind 或者 debug 版本的 php 来查看是否存在内存泄漏。除此之外，也可以设置 max_request 或自行退出 worker 进程，以及 docker、k8s 等容器管理组件，实现定期重启以回收内存

此 git repo 仅接收 swoole-src 问题反馈，其他问题勿在此提交

**Comment by landso** [comment]
好的，谢谢



在 2024-09-20 08:28:49，"Tianfeng.Han" ***@***.***> 写道：

可能是 PHP 层面改进，也可能 swoole-src 的 mem leak fix，版本差异较大，无法验证。

4.8 可通过 valgrind 或者 debug 版本的 php 来查看是否存在内存泄漏。除此之外，也可以设置 max_request 或自行退出 worker 进程，以及 docker、k8s 等容器管理组件，实现定期重启以回收内存

此 git repo 仅接收 swoole-src 问题反馈，其他问题勿在此提交
