### ISSUE TITLE
swoole日志出现 received the wrong data[619 bytes] from socket #12913707 报错

### ISSUE THREAD

**Issue by Evil-9527** [swoole/swoole-src#5472]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

背景：抓包可以在swoole服务端看到请求（swoole已收到请求），业务层没有处理。（偶现，不稳定复现，全天均有，swoole运行700多天）

swoole日志报错：
WARNING swWorker_discard_data (ERROR 1007): [1]received the wrong data[916 bytes] from socket #5573675
WARNING swWorker_discard_data (ERROR 1007): [1]received the wrong data[660 bytes] from socket #2427947
WARNING swWorker_discard_data (ERROR 1007): [1]received the wrong data[1428 bytes] from socket #6622251
WARNING swWorker_discard_data (ERROR 1007): [1]received the wrong data[619 bytes] from socket #12913707

2. What did you expect to see?
swoole接受到请求后，业务层处理请求，并正常返回。

3. What did you see instead?

观察swoole日志：

WARNING swWorker_discard_data (ERROR 1007): [1]received the wrong data[916 bytes] from socket #5573675
WARNING swWorker_discard_data (ERROR 1007): [1]received the wrong data[660 bytes] from socket #2427947
WARNING swWorker_discard_data (ERROR 1007): [1]received the wrong data[1428 bytes] from socket #6622251
WARNING swWorker_discard_data (ERROR 1007): [1]received the wrong data[619 bytes] from socket #12913707

4. What version of Swoole are you using (show your `php --ri swoole`)?

=========\

swoole:
swoole support => enabled
Version => 2.0.10
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
openssl => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
=========
php :
PHP 5.6.24 (cli) (built: Sep  9 2016 18:46:13) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

cat /etc/redhat-* : CentOS Linux release 6.2 (Final)
uname -a : Linux XXX 4.14.105-19-0019 #1 SMP Fri Jan 15 11:39:34 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by matyhtf** [comment]
这表示执行了 Server::close() 之后，依然收到了来自客户端发送的数据，底层会丢弃，并抛出此错误。
如果是 HTTP 服务器，可能是错误的不符合 HTTP RFC 的请求。

此错误可忽略。

**Comment by Evil-9527** [comment]
> 这表示执行了 Server::close() 之后，依然收到了来自客户端发送的数据，底层会丢弃，并抛出此错误。 如果是 HTTP 服务器，可能是错误的不符合 HTTP RFC 的请求。
> 
> 此错误可忽略。

如何复现这个报错？
如何修复这个问题？如何确定修复策略有效？（观察到swoole高版本源码（如4.0.X版本），报错的逻辑没有变更。）

补充信息：
报错类型：偶现报错、不稳定复现、swoole运行700多天
client感知：client不添加超时时间，client会一直等。

**Comment by matyhtf** [comment]
比如 content-length 与实际 body 不一致，就会有类似的问题。建议你前置一个 nginx 来挡掉非正常请求
