### ISSUE TITLE
swoole2.0.10 base模式下 work 偶尔崩溃重启

### ISSUE THREAD

**Issue by fishdemon** [swoole/swoole-src#5475]
swoole2.0.10 base模式下 work 偶尔崩溃重启
下面的work进程崩溃日志
<img width="1620" alt="image" src="https://github.com/user-attachments/assets/c8bf5d59-1bb6-43d3-b50c-639b515eac3c">

php 5.6.24

大佬，这可能是什么原因呢

**Comment by matyhtf** [comment]
版本太古老了，已经不再维护，建议升级到最新
