### ISSUE TITLE
运行官方进程 process的例子 引发coredump,【附带gdb信息】

### ISSUE THREAD

**Issue by lilien1010** [swoole/swoole-src#548]
直接复制的这个例子【http://wiki.swoole.com/wiki/page/290.html】
引发了下面的coredump信息

产生的core文件如下

```
(gdb) bt
#0  0x000000346fe32925 in raise () from /lib64/libc.so.6
#1  0x000000346fe34105 in abort () from /lib64/libc.so.6
#2  0x000000346fe70837 in __libc_message () from /lib64/libc.so.6
#3  0x000000346fe76166 in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f4fa9e5ec66 in zim_swoole_process___destruct (ht=<value optimized out>, return_value=<value optimized out>, return_value_ptr=<value optimized out>, 
    this_ptr=<value optimized out>, return_value_used=<value optimized out>) at /tmp/pear/temp/swoole/swoole_process.c:191
#5  0x00000000007387ad in zend_call_function (fci=0x7fffeb769780, fci_cache=<value optimized out>) at /usr/local/src/php5.4-201206232330/Zend/zend_execute_API.c:980
#6  0x000000000075c987 in zend_call_method (object_pp=0x7fffeb7698a0, obj_ce=<value optimized out>, fn_proxy=0x7fffeb7698a8, function_name=0xb9a1bd "__destruct", 
    function_name_len=<value optimized out>, retval_ptr_ptr=0x0, param_count=0, arg1=0x0, arg2=0x0) at /usr/local/src/php5.4-201206232330/Zend/zend_interfaces.c:97
#7  0x0000000000766452 in zend_objects_destroy_object (object=0x7f4fb1189300, handle=<value optimized out>) at /usr/local/src/php5.4-201206232330/Zend/zend_objects.c:123
#8  0x000000000076b9ce in zend_objects_store_call_destructors (objects=0xf2a840) at /usr/local/src/php5.4-201206232330/Zend/zend_objects_API.c:57
#9  0x000000000073a5fd in shutdown_destructors () at /usr/local/src/php5.4-201206232330/Zend/zend_execute_API.c:219
#10 0x0000000000745694 in zend_call_destructors () at /usr/local/src/php5.4-201206232330/Zend/zend.c:925
#11 0x00000000006e8945 in php_request_shutdown (dummy=<value optimized out>) at /usr/local/src/php5.4-201206232330/main/main.c:1723
#12 0x00000000007ede00 in do_cli (argc=2, argv=0x7fffeb76b208) at /usr/local/src/php5.4-201206232330/sapi/cli/php_cli.c:1174
#13 0x00000000007ef238 in main (argc=2, argv=0x7fffeb76b208) at /usr/local/src/php5.4-201206232330/sapi/cli/php_cli.c:1361
```

From Master: hello worker[6521]

From Master: hello worker[6522]

*** glibc detected *** php: free(): invalid next size (fast): 0x00007f4b3575b2b0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x346fe76166]
/lib64/libc.so.6[0x346fe78c93]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20100525/swoole.so(+0x22c66)[0x7f4b2e42dc66]
php(zend_call_function+0x8dd)[0x7387ad]
php(zend_call_method+0x1c7)[0x75c987]
php(zend_objects_destroy_object+0x2b2)[0x766452]
php(zend_objects_store_call_destructors+0x4e)[0x76b9ce]
php[0x73a5fd]
php[0x745694]
php(php_request_shutdown+0x365)[0x6e8945]
php[0x7ede00]
php[0x7ef238]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x346fe1ed1d]
php[0x42dbb9]
======= Memory map: ========
00400000-00c53000 r-xp 00000000 fd:03 1844253                            /usr/local/php/bin/php
00e52000-00f0a000 rw-p 00852000 fd:03 1844253                            /usr/local/php/bin/php
00f0a000-00f2b000 rw-p 00000000 00:00 0 
01ea7000-0211b000 rw-p 00000000 00:00 0                                  [heap]
346fa00000-346fa20000 r-xp 00000000 fd:00 3670140                        /lib64/ld-2.12.so
346fc1f000-346fc20000 r--p 0001f000 fd:00 3670140                        /lib64/ld-2.12.so
346fc20000-346fc21000 rw-p 00020000 fd:00 3670140                        /lib64/ld-2.12.so
346fc21000-346fc22000 rw-p 00000000 00:00 0 
346fe00000-346ff8b000 r-xp 00000000 fd:00 3670272                        /lib64/libc-2.12.so
346ff8b000-347018a000 ---p 0018b000 fd:00 3670272                        /lib64/libc-2.12.so
347018a000-347018e000 r--p 0018a000 fd:00 3670272                        /lib64/libc-2.12.so
347018e000-347018f000 rw-p 0018e000 fd:00 3670272                        /lib64/libc-2.12.so
347018f000-3470194000 rw-p 00000000 00:00 0 
3470200000-3470202000 r-xp 00000000 fd:00 3670511                        /lib64/libdl-2.12.so
3470202000-3470402000 ---p 00002000 fd:00 3670511                        /lib64/libdl-2.12.so
3470402000-3470403000 r--p 00002000 fd:00 3670511                        /lib64/libdl-2.12.so
3470403000-3470404000 rw-p 00003000 fd:00 3670511                        /lib64/libdl-2.12.so
3470600000-3470617000 r-xp 00000000 fd:00 3670435                        /lib64/libpthread-2.12.so
3470617000-3470817000 ---p 00017000 fd:00 3670435                        /lib64/libpthread-2.12.so
3470817000-3470818000 r--p 00017000 fd:00 3670435                        /lib64/libpthread-2.12.so
3470818000-3470819000 rw-p 00018000 fd:00 3670435                        /lib64/libpthread-2.12.so
3470819000-347081d000 rw-p 00000000 00:00 0 
3470a00000-3470a83000 r-xp 00000000 fd:00 3670508                        /lib64/libm-2.12.so
3470a83000-3470c82000 ---p 00083000 fd:00 3670508                        /lib64/libm-2.12.so
3470c82000-3470c83000 r--p 00082000 fd:00 3670508                        /lib64/libm-2.12.so
3470c83000-3470c84000 rw-p 00083000 fd:00 3670508                        /lib64/libm-2.12.so
3470e00000-3470e07000 r-xp 00000000 fd:00 3670506                        /lib64/librt-2.12.so
3470e07000-3471006000 ---p 00007000 fd:00 3670506                        /lib64/librt-2.12.so
3471006000-3471007000 r--p 00006000 fd:00 3670506                        /lib64/librt-2.12.so
3471007000-3471008000 rw-p 00007000 fd:00 3670506                        /lib64/librt-2.12.so
3471600000-3471615000 r-xp 00000000 fd:00 3670510                        /lib64/libz.so.1.2.3
3471615000-3471814000 ---p 00015000 fd:00 3670510                        /lib64/libz.so.1.2.3
3471814000-3471815000 r--p 00014000 fd:00 3670510                        /lib64/libz.so.1.2.3
3471815000-3471816000 rw-p 00015000 fd:00 3670510                        /lib64/libz.so.1.2.3
3471a00000-3471a1d000 r-xp 00000000 fd:00 3670513                        /lib64/libselinux.so.1
3471a1d000-3471c1c000 ---p 0001d000 fd:00 3670513                        /lib64/libselinux.so.1
3471c1c000-3471c1d000 r--p 0001c000 fd:00 3670513                        /lib64/libselinux.so.1
3471c1d000-3471c1e000 rw-p 0001d000 fd:00 3670513                        /lib64/libselinux.so.1
3471c1e000-3471c1f000 rw-p 00000000 00:00 0 
3472200000-3472216000 r-xp 00000000 fd:00 3670444                        /lib64/libresolv-2.12.so
3472216000-3472416000 ---p 00016000 fd:00 3670444                        /lib64/libresolv-2.12.so
3472416000-3472417000 r--p 00016000 fd:00 3670444                        /lib64/libresolv-2.12.so
3472417000-3472418000 rw-p 00017000 fd:00 3670444                        /lib64/libresolv-2.12.so
3472418000-347241a000 rw-p 00000000 00:00 0 
3474200000-3474225000 r-xp 00000000 fd:03 533657                         /usr/lib64/libpng12.so.0.49.0
3474225000-3474425000 ---p 00025000 fd:03 533657                         /usr/lib64/libpng12.so.0.49.0
3474425000-3474426000 rw-p 00025000 fd:03 533657                         /usr/lib64/libpng12.so.0.49.0
3475200000-3475298000 r-xp 00000000 fd:03 533655                         /usr/lib64/libfreetype.so.6.3.22
3475298000-3475497000 ---p 00098000 fd:03 533655                         /usr/lib64/libfreetype.so.6.3.22
3475497000-347549d000 rw-p 00097000 fd:03 533655                         /usr/lib64/libfreetype.so.6.3.22
347a200000-347a348000 r-xp 00000000 fd:03 533710                         /usr/lib64/libxml2.so.2.7.6
347a348000-347a547000 ---p 00148000 fd:03 533710                         /usr/lib64/libxml2.so.2.7.6
347a547000-347a551000 rw-p 00147000 fd:03 533710                         /usr/lib64/libxml2.so.2.7.6
347a551000-347a552000 rw-p 00000000 00:00 0 
347aa00000-347aa32000 r-xp 00000000 fd:00 3670374                        /lib64/libidn.so.11.6.1
347aa32000-347ac31000 ---p 00032000 fd:00 3670374                        /lib64/libidn.so.11.6.1
347ac31000-347ac32000 rw-p 00031000 fd:00 3670374                        /lib64/libidn.so.11.6.1
347b200000-347b25d000 r-xp 00000000 fd:00 3670459                        /lib64/libfreebl3.so
347b25d000-347b45c000 ---p 0005d000 fd:00 3670459                        /lib64/libfreebl3.so
347b45c000-347b45d000 r--p 0005c000 fd:00 3670459                        /lib64/libfreebl3.so
347b45d000-347b45e000 rw-p 0005d000 fd:00 3670459                        /lib64/libfreebl3.so
347b45e000-347b462000 rw-p 00000000 00:00 0 
347b600000-347b607000 r-xp 00000000 fd:00 3670518                        /lib64/libcrypt-2.12.so
347b607000-347b807000 ---p 00007000 fd:00 3670518                        /lib64/libcrypt-2.12.so
347b807000-347b808000 r--p 00007000 fd:00 3670518                        /lib64/libcrypt-2.12.so
347b808000-347b809000 rw-p 00008000 fd:00 3670518                        /lib64/libcrypt-2.12.so
347b809000-347b837000 rw-p 00000000 00:00 0 
347ba00000-347ba16000 r-xp 00000000 fd:00 3670447                        /lib64/libgcc_s-4.4.7-20120601.so.1
347ba16000-347bc15000 ---p 00016000 fd:00 3670447                        /lib64/libgcc_s-4.4.7-20120601.so.1
347bc15000-347bc16000 rw-p 00015000 fd:00 3670447                        /lib64/libgcc_s-4.4.7-20120601.so.1
347be00000-347be03000 r-xp 00000000 fd:00 3670133                        /lib64/libcom_err.so.2.1
347be03000-347c002000 ---p 00003000 fd:00 3670133                        /lib64/libcom_err.so.2.1Worker Exit, PID=6521
Worker Exit, PID=6522
*** glibc detected *** php: free(): invalid next size (fast): 0x00007f4b3575b2b0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x346fe76166]
/lib64/libc.so.6[0x346fe78c93]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20100525/swoole.so(+0x22c66)[0x7f4b2e42dc66]
php(zend_call_function+0x8dd)[0x7387ad]
php(zend_call_method+0x1c7)[0x75c987]
php(zend_objects_destroy_object+0x2b2)[0x766452]
php(zend_objects_store_del_ref_by_handle_ex+0x26f)[0x76bf6f]
php(zend_objects_store_del_ref+0x13)[0x76bfa3]
php(_zval_ptr_dtor+0x37)[0x7379f7]
php[0x7519c5]
php(zend_hash_reverse_apply+0x59)[0x751ad9]
php[0x73a5e5]
php[0x745694]
php(php_request_shutdown+0x365)[0x6e8945]
php[0x7ede00]
php[0x7ef238]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x346fe1ed1d]
php[0x42dbb9]
======= Memory map: ========
00400000-00c53000 r-xp 00000000 fd:03 1844253                            /usr/local/php/bin/php
00e52000-00f0a000 rw-p 00852000 fd:03 1844253                            /usr/local/php/bin/php
00f0a000-00f2b000 rw-p 00000000 00:00 0 
01ea7000-0211b000 rw-p 00000000 00:00 0                                  [heap]
346fa00000-346fa20000 r-xp 00000000 fd:00 3670140                        /lib64/ld-2.12.so
346fc1f000-346fc20000 r--p 0001f000 fd:00 3670140                        /lib64/ld-2.12.so
346fc20000-346fc21000 rw-p 00020000 fd:00 3670140                        /lib64/ld-2.12.so
346fc21000-346fc22000 rw-p 00000000 00:00 0 
346fe00000-346ff8b000 r-xp 00000000 fd:00 3670272                        /lib64/libc-2.12.so
346ff8b000-347018a000 ---p 0018b000 fd:00 3670272                        /lib64/libc-2.12.so
347018a000-347018e000 r--p 0018a000 fd:00 3670272                        /lib64/libc-2.12.so
347018e000-347018f000 rw-p 0018e000 fd:00 3670272                        /lib64/libc-2.12.so
347018f000-3470194000 rw-p 00000000 00:00 0 
3470200000-3470202000 r-xp 00000000 fd:00 3670511                        /lib64/libdl-2.12.so
3470202000-3470402000 ---p 00002000 fd:00 3670511                        /lib64/libdl-2.12.so
3470402000-3470403000 r--p 00002000 fd:00 3670511                        /lib64/libdl-2.12.so
3470403000-3470404000 rw-p 00003000 fd:00 3670511                        /lib64/libdl-2.12.so
3470600000-3470617000 r-xp 00000000 fd:00 3670435                        /lib64/libpthread-2.12.so
3470617000-3470817000 ---p 00017000 fd:00 3670435                        /lib64/libpthread-2.12.so
3470817000-3470818000 r--p 00017000 fd:00 3670435                        /lib64/libpthread-2.12.so
3470818000-3470819000 rw-p 00018000 fd:00 3670435                        /lib64/libpthread-2.12.so
3470819000-347081d000 rw-p 00000000 00:00 0 
3470a00000-3470a83000 r-xp 00000000 fd:00 3670508                        /lib64/libm-2.12.so
3470a83000-3470c82000 ---p 00083000 fd:00 3670508                        /lib64/libm-2.12.so
3470c82000-3470c83000 r--p 00082000 fd:00 3670508                        /lib64/libm-2.12.so
3470c83000-3470c84000 rw-p 00083000 fd:00 3670508                        /lib64/libm-2.12.so
3470e00000-3470e07000 r-xp 00000000 fd:00 3670506                        /lib64/librt-2.12.so
3470e07000-3471006000 ---p 00007000 fd:00 3670506                        /lib64/librt-2.12.so
3471006000-3471007000 r--p 00006000 fd:00 3670506                        /lib64/librt-2.12.so
3471007000-3471008000 rw-p 00007000 fd:00 3670506                        /lib64/librt-2.12.so
3471600000-3471615000 r-xp 00000000 fd:00 3670510                        /lib64/libz.so.1.2.3
3471615000-3471814000 ---p 00015000 fd:00 3670510                        /lib64/libz.so.1.2.3
3471814000-3471815000 r--p 00014000 fd:00 3670510                        /lib64/libz.so.1.2.3
3471815000-3471816000 rw-p 00015000 fd:00 3670510                        /lib64/libz.so.1.2.3
3471a00000-3471a1d000 r-xp 00000000 fd:00 3670513                        /lib64/libselinux.so.1
3471a1d000-3471c1c000 ---p 0001d000 fd:00 3670513                        /lib64/libselinux.so.1
3471c1c000-3471c1d000 r--p 0001c000 fd:00 3670513                        /lib64/libselinux.so.1
3471c1d000-3471c1e000 rw-p 0001d000 fd:00 3670513                        /lib64/libselinux.so.1
3471c1e000-3471c1f000 rw-p 00000000 00:00 0 
3472200000-3472216000 r-xp 00000000 fd:00 3670444                        /lib64/libresolv-2.12.so
3472216000-3472416000 ---p 00016000 fd:00 3670444                        /lib64/libresolv-2.12.so
3472416000-3472417000 r--p 00016000 fd:00 3670444                        /lib64/libresolv-2.12.so
3472417000-3472418000 rw-p 00017000 fd:00 3670444                        /lib64/libresolv-2.12.so
3472418000-347241a000 rw-p 00000000 00:00 0 
3474200000-3474225000 r-xp 00000000 fd:03 533657                         /usr/lib64/libpng12.so.0.49.0
3474225000-3474425000 ---p 00025000 fd:03 533657                         /usr/lib64/libpng12.so.0.49.0
3474425000-3474426000 rw-p 00025000 fd:03 533657                         /usr/lib64/libpng12.so.0.49.0
3475200000-3475298000 r-xp 00000000 fd:03 533655                         /usr/lib64/libfreetype.so.6.3.22
3475298000-3475497000 ---p 00098000 fd:03 533655                         /usr/lib64/libfreetype.so.6.3.22
3475497000-347549d000 rw-p 00097000 fd:03 533655                         /usr/lib64/libfreetype.so.6.3.22
347a200000-347a348000 r-xp 00000000 fd:03 533710                         /usr/lib64/libxml2.so.2.7.6
347a348000-347a547000 ---p 00148000 fd:03 533710                         /usr/lib64/libxml2.so.2.7.6
347a547000-347a551000 rw-p 00147000 fd:03 533710                         /usr/lib64/libxml2.so.2.7.6
347a551000-347a552000 rw-p 00000000 00:00 0 
347aa00000-347aa32000 r-xp 00000000 fd:00 3670374                        /lib64/libidn.so.11.6.1
347aa32000-347ac31000 ---p 00032000 fd:00 3670374                        /lib64/libidn.so.11.6.1
347ac31000-347ac32000 rw-p 00031000 fd:00 3670374                        /lib64/libidn.so.11.6.1
347b200000-347b25d000 r-xp 00000000 fd:00 3670459                        /lib64/libfreebl3.so
347b25d000-347b45c000 ---p 0005d000 fd:00 3670459                        /lib64/libfreebl3.so
347b45c000-347b45d000 r--p 0005c000 fd:00 3670459                        /lib64/libfreebl3.so
347b45d000-347b45e000 rw-p 0005d000 fd:00 3670459                        /lib64/libfreebl3.so
347b45e000-347b462000 rw-p 00000000 00:00 0 
347b600000-347b607000 r-xp 00000000 fd:00 3670518                        /lib64/libcrypt-2.12.soAborted (core dumped)

**Comment by lilien1010** [comment]
php swoole 版本信息
```
PHP 5.4.5-dev (cli) (built: Feb 25 2014 17:39:55) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2012 Zend Technologies
```
```
swoole

swoole support => enabled
Version => 1.7.22
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
Linux Native AIO => enabled
Gcc AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608
```

**Comment by matyhtf** [comment]
在最新的版本中已经修复了此问题。

**Comment by lilien1010** [comment]
1.8.0已经 生产环境可用了么

**Comment by matyhtf** [comment]
1.8.2-rc1可以用。
