### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by LaySoft** [swoole/swoole-src#5482]
I tried to install swoole with pecl, but the following error occured:
`/tmp/pear/temp/swoole/ext-src/swoole_coroutine.cc:992:57: error: 'ZEND_EXIT' was not declared in this scope; did you mean 'ZEND_CAST'?
  992 |         ori_exit_handler = zend_get_user_opcode_handler(ZEND_EXIT);
      |                                                         ^~~~~~~~~
      |                                                         ZEND_CAST
make: *** [Makefile:228: ext-src/swoole_coroutine.lo] Error 1
ERROR: `make' failed`

**Comment by NathanFreeman** [comment]
Fixed by https://github.com/swoole/swoole-src/pull/5465
