### ISSUE TITLE
Swoole\Thread\ArrayList和Queue  是否可以考虑下清空并返回剩余的数据?

### ISSUE THREAD

**Issue by LIngMax** [swoole/swoole-src#5487]
Swoole\Thread\Map()->clean(): void
Swoole\Thread\ArrayList()->clean()
Swoole\Thread\Queue()->clean(): void
ArrayList和Queue  清空返回剩余的数据

**Comment by matyhtf** [comment]
Map 和 ArrayList 可以使用 toArray 转为数组。Queue 无法遍历
