### ISSUE TITLE
branch 4.8.x  static_handler.cc  line 292 SW_STR_ISTARTS_WITH not defined

### ISSUE THREAD

**Issue by byronwind** [swoole/swoole-src#5497]
Compile error
branch :4.8.x 
fstatic_handler.cc  line 292 SW_STR_ISTARTS_WITH not defined  (in swoole.h  master branch)

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/5bb8cae93372ebb34aa69fee2c89caeb9eb6af58
