### ISSUE TITLE
Support PIE (PHP Installer for Extensions)

### ISSUE THREAD

**Issue by davisenra** [swoole/swoole-src#5501]
A new official installer for PHP extensions is currently under development at [php/pie](https://github.com/php/pie), it'll (hopefully) replace `pecl` eventually. Extensions are gonna be hosted at Packagist servers, so `pear` will probably also be sunsetted at some point.

An alpha release is expected to come out soon, but some popular extensions already support it, [as can be seen on this list](https://packagist.org/extensions). Some notable examples are `phpredis`, `xdebug` and `mongodb-extension`.

A guide for extension maintainers on how to support `pie` is available here: https://github.com/php/pie/blob/main/docs/extension-maintainers.md.

**Comment by NathanFreeman** [comment]
Okay, thank you. We will support it as soon as possible.
