### ISSUE TITLE
6.0.0 beta pecl version

### ISSUE THREAD

**Issue by LaySoft** [swoole/swoole-src#5531]
When will be the pecl version on the https://pecl.php.net/package/swoole page?

**Comment by NathanFreeman** [comment]
Sorry. there is a bit of a conflict because PECL does not allow uploading two versions with the same version number for Swoole, which prevents me from uploading swoole6.0-beta. I need to think about how to resolve this issue. 

In the meantime, I have uploaded swoole-6.0.0.tgz to GitHub (https://github.com/swoole/swoole-src/releases/tag/v6.0.0-beta), so you can download it directly from there and install swoole6.0-beta using pecl install ./swoole-6.0.0.tgz.

 Alternatively, you can also try using the latest PHP extension tool, Pie, to install swoole6.0-beta. (https://github.com/php/pie)

**Comment by LaySoft** [comment]
I tried your suggestion, but he following error occured:
`ERROR: file /tmp/pear/temp/tmpAKamHB/swoole-6.0.0/CMakeLists.txt does not exist`

**Comment by NathanFreeman** [comment]
Can you show me the commands you executed and the complete log output?

**Comment by LaySoft** [comment]
I downloaded the source from here: https://github.com/swoole/swoole-src/archive/refs/tags/v6.0.0-beta.tar.gz
and execute:
```
37af15aaa114:/app# pecl install ./v6.0.0-beta.tar.gz 
ERROR: file /tmp/pear/temp/tmpjPPpLb/swoole-6.0.0/CMakeLists.txt does not exist
37af15aaa114:/app# 
```

**Comment by NathanFreeman** [comment]
It's not this file; it's the file named swoole-6.0.0.tgz in this link that is the package that can only be installed via pecl.
https://github.com/swoole/swoole-src/releases

**Comment by LaySoft** [comment]
I tried this, because your first command does not work:
```
37af15aaa114:/app# pecl install ./swoole-6.0.0.tgz
Attempting to discover channel "."...
Attempting fallback to https instead of http on channel "."...
unknown channel "." in "./swoole-6.0.0.tgz"
invalid package name/package file "./swoole-6.0.0.tgz"
install failed
37af15aaa114:/app# 
```
But in the meantime I found the solution:
`pecl install swoole-6.0.0.tgz`
Thank you for your help!

**Comment by remicollet** [comment]
> Sorry. there is a bit of a conflict because PECL does not allow uploading two versions with the same version number for Swoole, which prevents me from uploading swoole6.0-beta. I need to think about how to resolve this issue.

Simply use the same version scheme that all other extensions, using "6.0.0beta1", "6.0.0beta2", "6.0.0RC1" as version
and the proper "stability" in package.xml

**Comment by LaySoft** [comment]
Thanks for the clarification!

**Comment by remicollet** [comment]
BTW, this is obviously too late for 6.0.0...

**Comment by remicollet** [comment]
See https://pecl.php.net/package/swoole

**6.0.0RC1** is there, but 6.0.0 (alpha) still there, so pecl is confused

```
# pecl list-upgrades
pecl.php.net Available Upgrades (stable):
=========================================
Channel      Package Local            Remote        Size
pecl.php.net swoole  6.0.0RC1 (alpha) 6.0.0 (alpha) 2152kB
```

I think v6.0.0 should be removed
Especially as it will block the real 6.0.0 GA when released

**Comment by remicollet** [comment]
> @remicollet Excuse me, how can I remove this package? Can I operate directly on PECL?

Yes, after login, you have the "[edit info]" which displays a list of all releases with an X link to remove one (Actions column)

**Comment by NathanFreeman** [comment]
@remicollet Thank you for your guidance. I have re-uploaded the new installation package to PECL.
