### ISSUE TITLE
cygwin 环境下 native_id 未申明 

### ISSUE THREAD

**Issue by jingjingxyk** [swoole/swoole-src#5543]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
错误详情： https://github.com/swoole/swoole-cli/actions/runs/11503982580/job/32022484018#step:11:1084
![图片](https://github.com/user-attachments/assets/73611cb7-f5aa-48b6-b03b-17e361ae0d5d)

搜索报错位置：
https://github.com/swoole/swoole-src/blob/master/include/swoole_thread.h#L56
https://github.com/search?q=repo%3Aswoole%2Fswoole-src%20cygwin&type=code

3. What did you expect to see?

4. What did you see instead?

5. What version of Swoole are you using (show your `php --ri swoole`)?

6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by matyhtf** [comment]
fixed https://github.com/swoole/swoole-src/commit/a102d0f0f662e1712a2ea31e4fd6aab12d152ccd
