### ISSUE TITLE
"PHP Deprecated" warning

### ISSUE THREAD

**Issue by mozart77** [swoole/swoole-src#5545]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

Running code:
```php

namespace test;

use Swoole\Runtime;

Runtime::enableCoroutine(true, SWOOLE_HOOK_TCP);

go(function () {
  $redis = new \Redis();

  if (!$redis->connect('127.0.0.1', 6379)) {
    throw new \RedisException("Unable to connect to Redis", 2);
  }

  echo "Redis connected\n";
});
```

2. What did you expect to see?

> Redis connected

3. What did you see instead?

> PHP Deprecated:  Swoole\Event::rshutdown(): Event::wait() in shutdown function is deprecated in Unknown on line 0
>
> Deprecated: Swoole\Event::rshutdown(): Event::wait() in shutdown function is deprecated in Unknown on line 0
> Redis connected

4. What version of Swoole are you using (show your `php --ri swoole`)?

**`> php --ri swoole`**
> 
> swoole
> 
> Swoole => enabled
> Author => Swoole Team <team@swoole.com>
> Version => 5.1.4
> Built => Sep 17 2024 22:29:47
> coroutine => enabled with boost asm context
> eventfd => enabled
> kqueue => enabled
> cpu_affinity => enabled
> spinlock => enabled
> rwlock => enabled
> http2 => enabled
> json => enabled
> zlib => 1.3
> mutex_timedlock => enabled
> pthread_barrier => enabled
> mysqlnd => enabled
> async_redis => enabled
> 
> Directive => Local Value => Master Value
> swoole.enable_coroutine => On => On
> swoole.enable_library => Off => Off
> swoole.enable_fiber_mock => Off => Off
> swoole.enable_preemptive_scheduler => On => On
> swoole.display_errors => On => On
> swoole.use_shortname => On => On
> swoole.unixsock_buffer_size => 2621440 => 2621440

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**`> uname -a`**
> FreeBSD web 14.1-RELEASE-p5 FreeBSD 14.1-RELEASE-p5 GENERIC amd64

**`> php -v`**
> PHP 8.3.12 (cli) (built: Sep 29 2024 01:11:14) (NTS)
> Copyright (c) The PHP Group
> Zend Engine v4.3.12, Copyright (c) Zend Technologies
>     with Zend OPcache v8.3.12, Copyright (c), by Zend Technologies

**`> gcc -v`**
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc13/gcc/x86_64-portbld-freebsd14.0/13.3.0/lto-wrapper
> Target: x86_64-portbld-freebsd14.0
> Configured with: /wrkdirs/usr/ports/lang/gcc13/work/gcc-13.3.0/configure --enable-multilib --with-build-config=bootstrap-debug --disable-nls --enable-gnu-indirect-function --enable-host-shared --enable-plugin --libdir=/usr/local/lib/gcc13 --libexecdir=/usr/local/libexec/gcc13 --program-suffix=13 --with-as=/usr/local/bin/as --with-gmp=/usr/local --with-gxx-include-dir=/usr/local/lib/gcc13/include/c++/ --with-gxx-libcxx-include-dir=/usr/include/c++/v1 --with-ld=/usr/local/bin/ld --with-pkgversion='FreeBSD Ports Collection' --with-system-zlib --without-zstd --enable-languages=c,c++,objc,fortran,jit --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/share/man --infodir=/usr/local/share/info/gcc13 --build=x86_64-portbld-freebsd14.0
> Thread model: posix
> Supported LTO compression algorithms: zlib
> gcc version 13.3.0 (FreeBSD Ports Collection)

**Comment by NathanFreeman** [comment]
```php

namespace test;

use Swoole\Runtime;
use function Swoole\Coroutine\run;
use function Swoole\Coroutine\go;

Runtime::enableCoroutine(true, SWOOLE_HOOK_TCP);

run(function(){
    $redis = new \Redis();
    if (!$redis->connect('127.0.0.1', 6379)) {
        throw new \RedisException("Unable to connect to Redis", 2);
    }
    echo "Redis connected\n";
});
```

Try it like this.

**Comment by mozart77** [comment]
> ```
> use Swoole\Runtime;
> use function Swoole\Coroutine\run;
> use function Swoole\Coroutine\go;
> 
> Runtime::enableCoroutine(true, SWOOLE_HOOK_TCP);
> 
> run(function(){
>     $redis = new \Redis();
>     if (!$redis->connect('127.0.0.1', 6379)) {
>         throw new \RedisException("Unable to connect to Redis", 2);
>     }
>     echo "Redis connected\n";
> });
> ```

The result:

> PHP Fatal error:  Uncaught Error: Call to undefined function Swoole\Coroutine\run() in /usr/local/www/test/q.php:11
> Stack trace:
> #0 {main}
>   thrown in /usr/local/www/test/q.php on line 11
> 
> Fatal error: Uncaught Error: Call to undefined function Swoole\Coroutine\run() in /usr/local/www/test/q.php:11
> Stack trace:
> #0 {main}
>   thrown in /usr/local/www/test/q.php on line 11

**Comment by mozart77** [comment]
That's it! Works! Thank you!

**Comment by NathanFreeman** [comment]
I need to supplement this section with details in the Swoole documentation.
