### ISSUE TITLE
Please explain in simple word difference between Swoole Client and Corotine Client and Swoole Server and Corotine server

### ISSUE THREAD

**Issue by deba12** [swoole/swoole-src#5549]
I am starting new project - simple tcp proxy, i see there are two kinds of implementations
Swoole and coroutine both for client and server. The documentation does not explain 
very well which one should be used in new projects. I see that the swoole client is second class citizen
no async, no http_proxy authorization.

Please tell me for new projects which one implementation is recommended to be used Coroutines one or Swoole one?

**Comment by matyhtf** [comment]
You should read the document

https://wiki.swoole.com/en/#/
