### ISSUE TITLE
Try to connect with TLS and valid cert

### ISSUE THREAD

**Issue by BhryanS2** [swoole/swoole-src#5552]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
To reproduce the error, simply clone the repository: [repo](https://github.com/BhryanS2/hyperf-skeleton)
Then upload the container and run the commands `php bin/hyperf.php test` to see the error happening.

2. What did you expect to see?
I expected to see a successful connection, but I got the error described in the repository's readme and in topic 3.

3. What did you see instead?

I got an error return, and access was denied for the user using SSL with trust certificates.
![hyperf-conn](https://github.com/user-attachments/assets/b8f0bc1a-6c10-4a4d-9d76-49ce522263a6)

4. What version of Swoole are you using (show your `php --ri swoole`)?
```sh
swoole
 
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.1.4
Built => Sep  5 2024 03:28:04
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 3.1.7 3 Sep 2024
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.27.0
zlib => 1.3.1
brotli => E16781312/D16781312
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled
coroutine_pgsql => enabled
coroutine_odbc => enabled
coroutine_sqlite => enabled
 
Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
uname:
```sh
Linux f706b138186c 4.18.0-553.22.1.el8_10.x86_64 #1 SMP Wed Sep 11 18:02:00 EDT 2024 x86_64 Linux
```
php version:
```sh
PHP 8.3.8 (cli) (built: Jun  6 2024 17:04:22) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.8, Copyright (c), by Zend Technologies
```
gcc not found.

--------
I created an [issue in hyperf](https://github.com/hyperf/hyperf/issues/7086), which is the framework in which I found the problem, then together with the community, an investigation was carried out to find out the root cause of the problem. Initially, it was suspected that the problem was related to the Hyperf framework, since it only manifests itself when used in conjunction with Swoole. We observed that the connection is successfully established in scenarios where PHP is run without Swoole.
During one of the discussions in the Hyperf repository, it was pointed out that the problem occurs when using Coroutine, while running outside of a Coroutine does not present this failure.
[Reference to comment](https://github.com/hyperf/hyperf/issues/7086#issuecomment-2398849216).
After some investigation, we concluded that the root cause of the problem seems to be more related to Swoole than to Hyperf itself. For this reason, I'm bringing this discussion here.

**Comment by marcelorcastro** [comment]
Good morning guys. Why this issue was closed?
