### ISSUE TITLE
cygwin 环境下 新增的功能TCP_INFO option in Co\Socket::getOption 缺少适配

### ISSUE THREAD

**Issue by jingjingxyk** [swoole/swoole-src#5556]
错误详情： https://github.com/swoole/swoole-cli/actions/runs/11717432997/job/32637083793#step:11:1078
<img width="1417" alt="image" src="https://github.com/user-attachments/assets/d6f8b831-74d9-4173-b75c-12fab342e4df">

原因：新增的功能[Add support for the TCP_INFO option in Co\Socket::getOption](https://github.com/swoole/swoole-src/commit/06df6ad66072b41702ecd19e95a757344697f0d1#)缺少cygwin 环境适配

https://github.com/swoole/swoole-src/blame/master/ext-src/swoole_socket_coro.cc#L1957

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/f975ae77433170e6fe77e524816b3f4b3ff6c141
