### ISSUE TITLE
V6 的变量内存共享函数 有问题    toArray函数  

### ISSUE THREAD

**Issue by LIngMax** [swoole/swoole-src#5559]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

```
<?php
$LURDATE   = new \Swoole\Thread\Map;

$time = 'abc';
$LURDATE[$time] =  new \Swoole\Thread\Map(["saaa"=>1111]);
$ls = $LURDATE[$time]->toArray();#BUG 复现
// $ls = unserialize(serialize($LURDATE[$time]->toArray()));#BUG 解决方案
foreach ($ls as $k => $v) {
    unset($LURDATE[$time][$k]);
}
unset($LURDATE[$time]);


```

2. What did you expect to see?
正常运行

3. What did you see instead?

zend_mm_heap corrupted
Aborted

4. What version of Swoole are you using (show your `php --ri swoole`)?
最新版本 2024年11月11日

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 6.0.0-dev
Built => Nov 11 2024 16:41:08
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
thread => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
json => enabled
zlib => 1.2.11
brotli => E16777223/D16777223
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux iZt4n4e0twd92nczt3ivrlZ 5.4.0-196-generic #216-Ubuntu SMP Thu Aug 29 13:26:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.3.4 (cli) (built: Sep 20 2024 12:00:30) (ZTS)
Copyright (c) The PHP Group
Zend Engine v4.3.4, Copyright (c) Zend Technologies

**Comment by matyhtf** [comment]
感谢你的反馈，toArray 函数的实现存在一个 BUG，数组的 key 必须从原有的 map 对象中复制出来

**Comment by matyhtf** [comment]
@LIngMax 请添加一下我的微信，保持沟通 19921030512
