### ISSUE TITLE
v6 Map类无法 删除嵌套的数字键 就算传字符串数字也不行

### ISSUE THREAD

**Issue by LIngMax** [swoole/swoole-src#5560]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
```

$LURDATE   = new \Swoole\Thread\Map;

$LURDATE['5'] = new \Swoole\Thread\Map(["saaa"=>1111,'6'=>2222,"ccc"=>1111]);


unset($LURDATE['5']['6']);#无法删除 6 字符串数字索引 ###BUG
var_dump($LURDATE['5']->toArray());
$ls = $LURDATE['5'];
unset($ls['6']);#无法删除 6   字符串数字索引  ###BUG
unset($ls['ccc']);#正常删除 ccc  字符串索引
var_dump($ls->toArray());

unset($LURDATE[5]);
var_dump($LURDATE->toArray());#无法删除 5  数字索引   ###BUG

unset($LURDATE['5']);
var_dump($LURDATE->toArray());#可以删除5  字符串数字索引
```

2. What did you expect to see?
希望与原生php一致 正常删除变量 无论是数字还是字符串键 都支持
需要:  尽量与PHP原生持平 实在不行 内部强制统一转字符串就好  

不然以后不知道  同事能搞出啥幺蛾子

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

**Comment by matyhtf** [comment]
感谢你的反馈，现在已重构了对 key 的处理，与 PHP 原生的 Array 完全保持一致。

允许 key 为下列类型：

- true/false
- 浮点型
- 数字字符串，将转为整数
- null，转为空字符串
- 资源类型，转为整数
- 其他类型抛出 `Illegal offset type` 异常
