### ISSUE TITLE
自定义进程中不能监听到信号

### ISSUE THREAD

**Issue by chenjian-cpu** [swoole/swoole-src#5563]
<img width="635" alt="微信图片_20241115234358" src="https://github.com/user-attachments/assets/5996c21a-61c9-4b8f-8916-34986148bb49">
如图所示，我直接kill -15 pid，没有任何输出，进程也没有被kill,  帮忙看下是不是使用的方式不对？

**Comment by NathanFreeman** [comment]
需要设置`$http->set(['hook_flags' => SWOOLE_HOOK_ALL]);`，否则sleep是阻塞函数，会导致信号的回调函数无法执行。
