### ISSUE TITLE
\Swoole\Coroutine\System::gethostbyname($domainName, AF_INET6, 5);触发信号11的错误进程奔溃

### ISSUE THREAD

**Issue by zhang768617998** [swoole/swoole-src#5564]
请在提交问题之前回答这些问题.

1. 你做了什么？如果可能，提供一个简单的脚本来重现错误.
    \Swoole\Coroutine\System::gethostbyname($domainName, AF_INET6, 5);  // 使用gethostbyname进行IPV6的DNS查询的时候偶发性报错.触发信号11的错误进程奔溃，valgrind记录的错误信息详见“错误内容”，使用\Swoole\Coroutine\System::dnsLookup($domainName, 5,AF_INET6);可以绕开这个问题，但dnsLookup速度比gethostbyname要慢不少

2. 你期望看到什么?
    期望这个问题能得到解决

3. 你看到了什么?
答：我看到了报错，错误内容：
       ==19== Memcheck, a memory error detector
==19== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==19== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==19== Command: php cmd1.php server start false
==19== Parent PID: 12
==19==
==19== Conditional jump or move depends on uninitialised value(s)
==19==    at 0x893E203: swoole::coroutine::Socket::~Socket() (socket.cc:1758)
==19==    by 0x88571A1: zim_swoole_coroutine_system_exec (swoole_coroutine_system.cc:289)
==19==    by 0x6E712C: execute_ex (in /usr/local/bin/php)
==19==    by 0x666FDC: zend_call_function (in /usr/local/bin/php)
==19==    by 0x8877AF8: swoole::PHPCoroutine::main_func(void*) (swoole_coroutine.cc:754)
==19==    by 0x894A186: operator() (std_function.h:591)
==19==    by 0x894A186: swoole::coroutine::Context::context_func(transfer_t) (context.cc:149)
==19==    by 0x8972DEE: swoole_make_fcontext (make_x86_64_sysv_elf_gas.S:135)
==19==
==27==
==27== HEAP SUMMARY:
==27==     in use at exit: 17,192,238 bytes in 40,849 blocks
==27==   total heap usage: 1,158,924 allocs, 1,118,075 frees, 94,504,065,014 bytes allocated
==27==
==27== LEAK SUMMARY:
==27==    definitely lost: 58,000 bytes in 1,240 blocks
==27==    indirectly lost: 8,932 bytes in 235 blocks
==27==      possibly lost: 5,524,750 bytes in 22,401 blocks
==27==    still reachable: 11,600,556 bytes in 16,973 blocks
==27==                       of which reachable via heuristic:
==27==                         newarray           : 376 bytes in 1 blocks
==27==         suppressed: 0 bytes in 0 blocks
==27== Rerun with --leak-check=full to see details of leaked memory
==27==
==27== Use --track-origins=yes to see where uninitialised values come from
==27== For lists of detected and suppressed errors, rerun with: -s
==27== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
==24==
==24== HEAP SUMMARY:
==24==     in use at exit: 5,424,428 bytes in 33,813 blocks
==24==   total heap usage: 71,170 allocs, 37,357 frees, 19,380,338 bytes allocated
==24==
==24== LEAK SUMMARY:
==24==    definitely lost: 37,120 bytes in 1,160 blocks
==24==    indirectly lost: 40 bytes in 1 blocks
==24==      possibly lost: 2,964,278 bytes in 21,218 blocks
==24==    still reachable: 2,422,990 bytes in 11,434 blocks
==24==                       of which reachable via heuristic:
==24==                         newarray           : 376 bytes in 1 blocks
==24==         suppressed: 0 bytes in 0 blocks
==24== Rerun with --leak-check=full to see details of leaked memory
==24==
==24== Use --track-origins=yes to see where uninitialised values come from
==24== For lists of detected and suppressed errors, rerun with: -s
==24== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
# ==19== Memcheck, a memory error detector
==19== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==19== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==19== Command: php cmd1.php server start false
==19== Parent PID: 12
==19==
==19== Conditional jump or move depends on uninitialised value(s)
==19==    at 0x893E203: swoole::coroutine::Socket::~Socket() (socket.cc:1758)
==19==    by 0x88571A1: zim_swoole_coroutine_system_exec (swoole_coroutine_system.cc:289)
==19==    by 0x6E712C: execute_ex (in /usr/local/bin/php)
==19==    by 0x666FDC: zend_call_function (in /usr/local/bin/php)
sh: 7: ==19==: not found
==19==    by 0# x8877AF8: swoole::PHPCoroutine::main_func(void*) (swoole_coroutine.cc:754)
sh: 8: Syntax error: "(" unexpected
# sh: 8: ==19==: not found
sh: 8: rerun: not found
# sh: 9: ==19==: not found
# sh: 10: ==19==: not found
# sh: 11: ==19==: not found
# sh: 12: Syntax error: "(" unexpected
# sh: 12: Syntax error: "(" unexpected
# sh: 12: Syntax error: "(" unexpected
# sh: 12: Syntax error: "(" unexpected
# sh: 12: Syntax error: "(" unexpected
# sh: 12: Syntax error: "(" unexpected
# ==19==    by 0x894A186: operator() (std_function.h:591)
==19==    by 0x894A186: swoole::coroutine::Context::context_func(transfer_t) (context.cc:149)
==19==    by 0x8972DEE: swoole_make_fcontext (make_x86_64_sysv_elf_gas.S:135)
==19==
==27==
sh: 12: Syntax error: "(" unexpected
# sh: 12: Syntax error: "(" unexpected
# ==27== HEAP SUMMARY:
==27==     in use at exit: 17,192,238 bytes in 40,849 blocks
==27==   total heap usage: 1,158,924 allocs, 1,118,075 frees, 94,504,065,014 bytes allocated
sh: 12: Syntax error: "(" unexpected
# sh: 12: ==19==: not found
# sh: 13: ==27==: not found
# sh: 14: ==27==: not found
# sh: 15: ==27==: not found
# sh: 16: ==27==: not found
# ==27==
==27== LEAK SUMMARY:
==27==    definitely lost: 58,000 bytes in 1,240 blocks
==27==    indirectly lost: 8,932 bytes in 235 blocks
==27==      possibly lost: 5,524,750 bytes in 22,401 blocks
==27==    still reachable: 11,600,556 bytes in 16,973 blocks
==27==                       of which reachable viash: 17:  heuristic:
==27==                         newarray     ==27==: not found      : 376 bytes in 1 blocks

==27==         suppressed: 0 bytes in 0 blocks
==27== Rerun with --leak-check=full to se# e details of leaked memory
sh: 18: ==27==: not found
# sh: 19: ==27==: not found
# sh: 20: ==27==: not found
# sh: 21: ==27==: not found
# sh: 22: ==27==: not found
# sh: 23: ==27==: not found
# sh: 24: ==27==: not found
# sh: 25: ==27==: not found
# sh: 26: ==27==: not found
# ==27==
==27== Use --track-origins=yes to see where uninitialised values come from
==27== For lists of detected and suppressed errors, rerun with: -s
==27== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
==24==
==24== HEAP SUMMARsh: 27: ==27==: not found
# sh: 28: ==27==: not found
# sh: 29: ==27==: not found
# sh: 30: Syntax error: "(" unexpected
# Y:
==24==     in use at exit: 5,424,428 bytes in 33,813 blocks
==24==   total heap usage: 71,170 allocs, 37,357 frees, 19,380,338 bytes allocated
==24==
==24== LEAK SUMMARY:
==24==    definitely lost: 37,120 bytes in 1,160 blocks
sh: 30: ==24==: not found
==24==    indirectly lost: 40 bytes in 1 blocks
# ==24==      possibly lost: 2,964,278 bytes in 21,218 blocks
sh: 31: ==24==: not found
# sh: 32: ==24==: not found
# sh: 33: ==24==: not found
# sh: 34: ==24==: not found
# sh: 35: ==24==: not found
# sh: 36: ==24==: not found
# sh: 37: ==24==: not found
# sh: 38: ==24==: not found
# ==24==    still reachable: 2,422,990 bytes in 11,434 blocks
==24==                       of which reachable via heuristic:
sh: 39: ==24==: not found
# sh: 40: ==24==: not found
# ==24==                         newarray           : 376 bytes in 1 blocks
sh: 41: ==24==: not found
# ==24==         suppressed: 0 bytes in 0 blocks
==24== Rerun with --leak-check=full to see details of leaked memory
==24==
==24== Use --track-origins=yes to see where uninitialised values come from
==24== For lists of detected and suppressed errorsh: 42: s, rerun with: -s
==24== ERROR SUMMARY: 1 errors==24==: not found from 1 contexts (suppressed: 0 f
rom 0)# sh: 43: ==24==: not found
# sh: 44: ==24==: not found
# sh: 45: ==24==: not found
# sh: 46: ==24==: not found

4. 您使用的是哪个版本的Swoole（显示您的php-ri-Swoole）?
答：swoole5.1 和 swoole6.0 都有这个问题

5. 您使用的机器环境是什么（显示您的`uname-a `、`php-v`和`gcc-v`）?
  docker、ubuntu22.04 、ubuntu24 都测试过都有该问题

**Comment by matyhtf** [comment]
最新版本已修复

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/issues/5547
