### ISSUE TITLE
PHP 8.4.1下静态编译出错

### ISSUE THREAD

**Issue by hkargc** [swoole/swoole-src#5581]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

/usr/local/src/php-8.4.1/ext/swoole/ext-src/swoole_coroutine.cc: In function ‘void php_swoole_coroutine_rinit()’:
/usr/local/src/php-8.4.1/ext/swoole/ext-src/swoole_coroutine.cc:994:57: error: ‘ZEND_EXIT’ was not declared in this scope; did you mean ‘ZEND_CAST’?
  994 |         ori_exit_handler = zend_get_user_opcode_handler(ZEND_EXIT);
      |                                                         ^~~~~~~~~
      |                                                         ZEND_CAST
make: *** [Makefile:3822: ext/swoole/ext-src/swoole_coroutine.lo] Error 1
make: *** Waiting for unfinished jobs....

2. What did you expect to see?

Fixed by https://github.com/swoole/swoole-src/pull/5465
这里说已经解决了，应该只是解决了动态编译的情况

3. What did you see instead?

4. What version of Swoole are you using (show your `php --ri swoole`)?

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
uname -a  : Linux  5.14.0-503.14.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 15 12:04:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

gcc -v : gcc version 11.5.0 20240719 (Red Hat 11.5.0-2) (GCC)

**Comment by NathanFreeman** [comment]
5.1.*不支持8.4，6.0之后的才支持8.4

**Comment by hkargc** [comment]
原来如此，谢谢
