### ISSUE TITLE
PSR-7 implement for swoole HTTP server

### ISSUE THREAD

**Issue by ParkFramework** [swoole/swoole-src#559]
It would be good if PSR-7 implement API (Request, Response, ...)

More info at http://www.php-fig.org/psr/psr-7/
Example of implementation https://github.com/zendframework/zend-diactoros/

Thank.

**Comment by GromNaN** [comment]
In PSR-7 : 
> HTTP Messages are considered immutable; all methods that might change state MUST
> be implemented such that they retain the internal state of the current
> message and return an instance that contains the changed state.

This requires that the controller returns the response instead of modifying the object that is injected:
```php
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;

$serv = new swoole_http_server("127.0.0.1", 9502);

$serv->on('Request', function(RequestInterface $request, ResponseInterface $response) {
    $newResponse = $response->withStatus(301);

    return $response;
});
```

**Comment by kcloze** [comment]
good idea

**Comment by lvht** [comment]
I dont know how to implement an interface defined by user space php code in an zend kernel space extension. Could you @ParkFramework @GromNaN offer some clue? Thanks :smile:

**Comment by coollider** [comment]
@lvht i can help you, i can write extenshion with psr7 interface and then you can use it C module. Ok?

**Comment by mindplay-dk** [comment]
There is already a third-party PSR-7 server implementation for Swoole:

https://github.com/mcfog/lit-swan

**Comment by sinasalek** [comment]
There is also this https://github.com/JanHuang/http

**Comment by mhf-ir** [comment]
All psr implemented by good C extension: may be helpfull:
https://github.com/jbboehr/php-psr 💚 
PSR is great move for all php extensions and packages. 💟
