### ISSUE TITLE
php 8.4.1 安装 swoole 5.1.5 出现警告

### ISSUE THREAD

**Issue by wheakerd** [swoole/swoole-src#5590]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

phpize

2. What did you expect to see?

Configuring for:
PHP Version:             8.4
PHP Api Version:         20240924
Zend Module Api No:      20240924
Zend Extension Api No:   420240924

3. What did you see instead?

Configuring for:
PHP Version:             8.4
PHP Api Version:         20240924
Zend Module Api No:      20240924
Zend Extension Api No:   420240924
config.m4:554: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:554: the top level
config.m4:555: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:555: the top level
config.m4:556: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:556: the top level
config.m4:557: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:557: the top level
config.m4:558: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:558: the top level
config.m4:559: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:559: the top level
config.m4:560: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:560: the top level
config.m4:561: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:561: the top level
config.m4:562: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:562: the top level
config.m4:563: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:563: the top level
config.m4:564: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:564: the top level
config.m4:565: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:565: the top level
config.m4:566: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:566: the top level
config.m4:567: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:567: the top level
config.m4:568: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:568: the top level
config.m4:569: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:569: the top level
config.m4:570: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:570: the top level
config.m4:571: warning: The macro 'PHP_DEF_HAVE' is obsolete. Use AC_DEFINE.
build/php.m4:34: PHP_DEF_HAVE is expanded from...
config.m4:128: PDO_ODBC_CHECK_HEADER is expanded from...
config.m4:571: the top level

4. What version of Swoole are you using (show your `php --ri swoole`)?

Extension 'swoole' not present.

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
uname -a :
Linux wheakerd 6.11.10-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Nov 23 00:51:20 UTC 2024 x86_64 GNU/Linux
php -v :
PHP 8.4.1 (cli) (built: Nov 25 2024 22:09:44) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.1, Copyright (c) Zend Technologies
gcc -v :
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/14/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
目标：x86_64-redhat-linux
配置为：../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,m2,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-libstdcxx-backtrace --with-libstdcxx-zoneinfo=/usr/share/zoneinfo --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-14.2.1-build/gcc-14.2.1-20240912/obj-x86_64-redhat-linux/isl-install --enable-offload-targets=nvptx-none,amdgcn-amdhsa --enable-offload-defaulted --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux --with-build-config=bootstrap-lto --enable-link-serialization=1
线程模型：posix
支持的 LTO 压缩算法：zlib zstd
gcc 版本 14.2.1 20240912 (Red Hat 14.2.1-3) (GCC)

**Comment by matyhtf** [comment]
5.1.x 不会支持 8.4，对于PHP高版本的支持视为新特性，而 5.1.x 是 release 版本分支，不会引入新的特性。

参考： https://github.com/swoole/swoole-src/blob/master/docs/SUPPORTED.md
