### ISSUE TITLE
请教，子进程Process中使用task执行任务结束后无法释放主进程创建的RedisPool和MysqliPool

### ISSUE THREAD

**Issue by mdys** [swoole/swoole-src#5593]
Please answer these questions before submitting your issue.
子进程Process中使用task执行任务结束后无法释放主进程创建的RedisPool和MysqliPool

1. What did you do? If possible, provide a simple script for reproducing the error.
server.php
 
```php
$redis_pool = new RedisPool((new RedisConfig)
			  ->withHost('127.0.0.1')
			  ->withPort(6379)
			  ->withAuth('')
			  ->withDbIndex(0)
			  ->withTimeout(1)			      
);
$mysql_pool = new MysqliPool((new MysqliConfig)

			->withHost('127.0.0.1')
			->withPort(3306)
			->withDbName('db')
			->withCharset('utf8mb4')
			->withUsername('root')
			->withPassword('12345') 
); 

$this->redis_pool = $redis_pool;

$this->mysql_pool = $mysql_pool;

//用子进程实现定时器投送task
$process = new Swoole\Process(function ($process) use ($serv) {
cli_set_process_title('Swoole_process_timer1'); 
$timer_id = Swoole\Timer::tick(2000,function ($timer_id) use($serv){ 
	 $taskData = [
            'action' => 'cdr_task_test',
            'cdrData' => $cdr_data,							           
	 ];		
	$task_rs = $serv->task($taskData); 
});   
}, false, 2, 1);
$serv->addProcess($process); 
//Swoole\Process::wait();
//Swoole\Event::wait();   
$this -> serv->start();
```
 
task.php ，在子进程调用的$redis_pool->put($redis); 无法释放连接，使用worker进程可以正常释放，请教子进程Process如何释放主进程中的$redis_pool？感谢！
> class cdr_task {
>  public static function test($serv,$mysql_pool,$redis_pool,$data) {   
>    	$redis = $redis_pool->get(); 
>   	$mysqli = $mysql_pool->get(); 
>   	  $redis_pool->put($redis); 
>    	$mysql_pool->put($mysqli); 
 >    }
> }
 
3. What did you expect to see?
4. What did you see instead?
5. What version of Swoole are you using (show your `php --ri swoole`)?
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.1.5
Built => Nov 21 2024 19:44:14
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.10.0
zlib => 1.2.7
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

6. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux myserver 3.10.0-1160.119.1.el7.x86_64 #1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.3.8 (cli) (built: Jun  4 2024 14:53:17) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.3.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.8, Copyright (c), by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-8/root/usr --mandir=/opt/rh/devtoolset-8/root/usr/share/man --infodir=/opt/rh/devtoolset-8/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-8.3.1-20190311/obj-x86_64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)

**Comment by matyhtf** [comment]
连接池是进程间隔离的，不存在可以跨进程使用的连接池，每个进程的连接池都是独立的一份。
