### ISSUE TITLE
WARNING Server::check_worker_exit_status(): worker(pid=18067, id=1) abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by mengzhuowei** [swoole/swoole-src#5596]
[2024-11-29 09:56:50 $18061.0]  WARNING Server::check_worker_exit_status(): worker(pid=18068, id=2) abnormal exit, status=0, signal=11
A bug occurred in Swoole-v5.0.2, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md 
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.

OS: Linux 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64
GCC_VERSION: 10.3.1 20211027
OPENSSL_VERSION: OpenSSL 1.1.1t  7 Feb 2023
PHP_VERSION : 8.1.1

请帮助确认一下是否存在bug

**Comment by NathanFreeman** [comment]
请使用gdb或者valgrind获取一下错误的栈信息
https://wiki.swoole.com/zh-cn/#/other/issue?id=关于段错误核心转储

**Comment by matyhtf** [comment]
升级一下吧，5.0.2已经是非常老的版本了
