### ISSUE TITLE
swoole 1.7.22版本swoole_http_server bug

### ISSUE THREAD

**Issue by danchaofan** [swoole/swoole-src#560]
register_shutdown_function
发生fatal错误后，第一次可以执行注册的shutdownfunction，之后worker进程无法响应新的请求

**Comment by danchaofan** [comment]
经测试1.8.0版本没有此bug。。

**Comment by matyhtf** [comment]
建议使用 1.8.2 或更高版本，早期的1.8.0,1.8.1都有一些问题。
