### ISSUE TITLE
进程池监听了message事件后，子进程无法接受信号，主进程也无法被kill -15停止

### ISSUE THREAD

**Issue by yunwuxin** [swoole/swoole-src#5600]
示例代码如下

![image](https://github.com/user-attachments/assets/e2ff6f33-fe80-496b-8c4a-c8c936316284)

进程池监听了message事件后子进程监信号时会报warning
![image](https://github.com/user-attachments/assets/a58dde39-1012-4da3-82f9-2520165c0256)

而且主进程无法被`kill -15  {PID}` 停止  使用`kill -9 {PID}`可以关掉主进程，但两个子进程还在

**Comment by matyhtf** [comment]
1. onmessage 是同步阻塞模式，无法使用异步和协程的特性，包括 process::signal / while(true) + co::sleep 
2. 使用 onmessage 之后onworkerstart 内不得死循环，否则无法进入onmessage循环
3. 无需监听sig_term，底层已经监听了此信号，kill主进程会关闭整个服务，kill工作进程会关闭对应进程，主进程会重启新的进程
4. kill 主进程，要等待所有工作进程退出，主进程才会退出
