### ISSUE TITLE
Fatal error: Cannot redefine class constant PDO::PGSQL_ATTR_DISABLE_PREPARES

### ISSUE THREAD

**Issue by mrVrAlex** [swoole/swoole-src#5602]
1. What did you do? If possible, provide a simple script for reproducing the error.

`php -v`
Just installed latest swoole 6.0-RC1 with pdo_pgsql in official php docker image

Steps to reproduce
Run php docker image:
 `docker run -it php:8.4.1-zts-alpine3.20 sh`
Install dependencies:
```
apk update \
&& apk upgrade --available && sync \
&& apk add --no-cache --no-progress --virtual BUILD_DEPS ${PHPIZE_DEPS} linux-headers oniguruma-dev \
&& apk add --no-cache --no-progress \
    bash \
    binutils \
    coreutils \
    git \
    libltdl \
    libpq \
    libressl \
    libstdc++ \
    liburing \
    liburing-dev \
    c-ares \
&& apk add --no-cache --no-progress postgresql-client postgresql-libs \
&& apk add --no-cache --no-progress --virtual BUILD_DEPS_PHP_PGSQL postgresql-dev \
&& docker-php-ext-install pdo_pgsql pgsql
```
Then install swoole:
```
mkdir -p ~/build && \
cd ~/build && \
git clone https://github.com/swoole/swoole-src.git && \
cd swoole-src && \
git checkout v6.0.0-rc1 && \
phpize && \
./configure \
--enable-swoole-thread --enable-iouring --enable-swoole-pgsql && \
make && make install
```

enable extension: 
`echo "extension=swoole" >> /usr/local/etc/php/conf.d/99-swoole.ini`

2. What did you expect to see?

php is working as usual

3. What did you see instead?

`Fatal error: Cannot redefine class constant PDO::PGSQL_ATTR_DISABLE_PREPARES in Unknown on line 0`

Main question: Should I use `--enable-swoole-pgsql` options if I want get coroutine support hook for pdo_pgsql?

**Comment by mrVrAlex** [comment]
Maybe problem here:
https://github.com/swoole/swoole-src/blob/master/ext-src/swoole_pgsql.cc#L206C79-L206C106
because in PHP 8.4 const PDO_PGSQL_ATTR_DISABLE_PREPARES now just is alias, look in docs - https://www.php.net/manual/en/ref.pdo-pgsql.php#pdo.constants.pgsql-attr-disable-prepares

**Comment by NathanFreeman** [comment]
`echo "extension=swoole" >> /usr/local/etc/php/conf.d/docker-php-ext-swoole.ini`
Ensure that Swoole is loaded after pdo_pgsql.

**Comment by NathanFreeman** [comment]
`Main question: Should I use --enable-swoole-pgsql options if I want get coroutine support hook for pdo_pgsql?`
Yes, you need to do it this way.

**Comment by mrVrAlex** [comment]
Thanks you, it's works!
I never would have thought that the order in which extensions are listed in the configuration play such a big role.
Maybe in documentation should comment about it.
In official docker php in config in directory /usr/local/etc/php/conf.d/ read in alphabet order. so "pdo_xxx" will be under swoole.ini  In my example 99-swoole.ini included first)
