### ISSUE TITLE
How to close() a Swoole\Coroutine\PostgreSQL connection / object.

### ISSUE THREAD

**Issue by mohsin-devdksa** [swoole/swoole-src#5603]
### Issue Description:
In one of our swoole based commercial apps, we are using your [Connection Pool (Swoole Channel)](https://wiki.swoole.com/en/#/coroutine/conn_pool) class for `Swoole\Coroutine\PostgreSQL`, 
 
We want to close / disconnect all the PostgreSQL Connections in the Pool (in order to make sure that there remains no PostgreSQL Connections / Objects in the memory after closing the ConnectionPool. We want to avoid memory leaks in our Swoole based Websocket server) 

**however ...** 

... We don't find any such function (`close()` / `disconnect()`) on `Swoole\Coroutine\PostgreSQL` 

Please let us know how to **->close()** a `Swoole\Coroutine\PostgreSQL` connection / object.

Looking for urgent help.

### What version of Swoole are you using (show your php --ri swoole)?

```
Swoole => enabled
Author => Swoole Team <[team@swoole.com](mailto:team@swoole.com)>
Version => 5.1.2
Built => Aug 15 2024 12:06:11
coroutine => enabled with thread context
debug => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.0.2 15 Mar 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.18.1
zlib => 1.2.11
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled
coroutine_pgsql => enabled
Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608


```

### What is your machine environment used (show your uname -a & php -v & gcc -v) ?

- PHP 8.3.12 (cli) (built: Sep 27 2024 03:53:05) (NTS)
- gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1 22.04)
- Linux directlv16-ThinkPad-E15-Gen-4 6.8.0-45-generic 45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by NathanFreeman** [comment]
```php
$pg = new Swoole\Coroutine\PostgreSQL();
$conn = $pg->connect("host=127.0.0.1 port=5432 dbname=test user=postgre password=");
$conn = null;
```
Try setting `$conn = null` to reduce the reference count and close the connection.

**Comment by NathanFreeman** [comment]
Generally, there is no need to close it manually because when the reference count is 0, PHP will automatically garbage collect and close the connection.

**Comment by NathanFreeman** [comment]
You need to handle the reconnection of the database connection by yourself.
