### ISSUE TITLE
请教，php8 +sw5.1.6，使用memory_tracker检查，在Swoole\Server->start()和onMessage会有内存泄漏。

### ISSUE THREAD

**Issue by mdys** [swoole/swoole-src#5612]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
php8 +sw5.1.6，做websocket 二进制数据传输，使用memory_tracker看到会有如下内存泄漏信息

>public function __construct() {
	$this->serv = new Swoole\Websocket\Server($this->host, $this->port,SWOOLE_PROCESS);
	$this->serv->set([
	 "worker_num"      => swoole_cpu_num()*20,
	 "max_request"     => 0,   
	 "open_http_protocol" => true,
	 "enable_static_handler" => true,
	 "open_websocket_protocol" => true,
	 "open_http_protocol" => true,          
	 "daemonize" => false,
	 "enable_coroutine" => true,
	 "task_enable_coroutine"=> true,  
	 "task_use_object" => true, 
	 "task_worker_num" => swoole_cpu_num()*20,
	 "aio_core_worker_num" => swoole_cpu_num(),
	 "aio_worker_num" => swoole_cpu_num()*80,                   
	 "heartbeat_idle_time"      => 180,
	 "heartbeat_check_interval" => 60,
	 "socket_read_timeout" => 900,                         
	 "reactor_num" => swoole_cpu_num()*2,
	 "open_cpu_affinity" => true, 
	 "package_max_length" => 1024 * 1024 * 100,
	 "cpu_affinity_ignore" => [0,1], 
	 "open_tcp_nodelay" => true,
	 "hook_flags"=> SWOOLE_HOOK_ALL,
	 "max_wait_time" => 900,
	 "reload_async" => true,
	 "task_max_request" => 100,
	 "enable_preemptive_scheduler" => false,
	 "enable_deadlock_check" => true,
	 "display_errors" => true,    
	]); 
    }
 public function start()  {
      $this -> serv->start();   
    }
    $server = new sw_server();
    $server->start();
 

当收到客户端open连接时候会看到如下

> [Round#21059] leak 128.05 KB bytes, alloc 72 times at /home/wwwroot/html_80001/sw_server_o.php:487
#0 /home/wwwroot/html_80001/sw_server_o.php(487): Swoole\Server->start()
#1 /home/wwwroot/html_80001/sw_server_o.php(2628): sw_server->start()
 
当开始传输二进制时候可以看到如下 

> [Round#40515] leak 968.00 B bytes, alloc 77 times at /home/wwwroot/html_88001/sw_server_o.php:2036
#0 [internal function]: sw_server->onMessage(Object(Swoole\WebSocket\Server), Object(Swoole\WebSocket\Frame))
 
4. What version of Swoole are you using (show your `php --ri swoole`)?

> Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.1.6
Built => Dec  2 2024 14:14:42
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.10.0
zlib => 1.2.7
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled
Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_fiber_mock => Off => Off
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux myserver 3.10.0-1160.119.1.el7.x86_64 #1 SMP Tue Jun 4 14:43:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.3.8 (cli) (built: Jun  4 2024 14:53:17) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.3.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.8, Copyright (c), by Zend Technologies

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-8/root/usr --mandir=/opt/rh/devtoolset-8/root/usr/share/man --infodir=/opt/rh/devtoolset-8/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-8.3.1-20190311/obj-x86_64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)

**Comment by NathanFreeman** [comment]
不一定是泄漏，连接的建立都需要申请内存直到这个连接关闭才被释放，这些是正常的。
内存泄漏还得观察内存是否持续不断上涨

**Comment by mdys** [comment]
感谢 ，这边持续观察一下！

**Comment by drttcrh** [comment]
memory_tracker 哪里可以下载
