### ISSUE TITLE
Need example for Swoole\Coroutine\Server

### ISSUE THREAD

**Issue by deba12** [swoole/swoole-src#5620]
Hello,
the ```Swoole\Coroutine\Server``` documentations says

> Differences from the Server module:
> 
>     Dynamically creating and destroying - ports can be dynamically listened to, and servers can be dynamically closed during runtime.
>     The process of handling connections is fully synchronous, allowing programs to sequentially handle Connect, Receive, and Close events.

could you please give example for ```Swoole\Coroutine\Server``` how open/close new ports during runtime ?
Or example how to listen on multiple ports.

Thanks

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/blob/master/examples/coroutine/server/tcp.php
