### ISSUE TITLE
Proposal Detecting pcre2

### ISSUE THREAD

**Issue by fundawang** [swoole/swoole-src#5625]
当前 swoole 仍然在检查和使用 pcre 这个库，也即 pcre 1.x。这个库现在已经很少有软件再依赖它了，希望将有关函数引用尽快升级到 pcre2。

**Comment by fundawang** [comment]
php 自己的有关链接：  https://wiki.php.net/rfc/pcre2-migration

**Comment by matyhtf** [comment]
swoole 并不依赖和使用 pcre，这实际上是 php-src 自身的问题，它没有处理好编译配置。swoole 的部分类实现了 iterator、arrayaccess 等接口，这些接口的 php 头文件依赖了 pcre，而 php-src 又没有处理好依赖关系，导致可能出现 swoole 编译时出现 `pcre_match` 函数不存在的编译错误，因此在 swoole 中必须检测系统是否有 pcre 库才能开启相关的特性。

**Comment by fundawang** [comment]
不，我的意思是 php 自 7.3 起已经不再使用 pcre 1.x 了，swoole 6并没有php 8.0.x 或更低版本的兼容性包袱。应该和 php 一样，检测 pcre2 而不是 pcre 1.x。
