### ISSUE TITLE
Why I need to configure swoole as an example with --enable-swoole-pgsql if my php has pgsql drivers already

### ISSUE THREAD

**Issue by kvelaro** [swoole/swoole-src#5626]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

./configure --help to see additional options

2. What did you expect to see?

expect to see supported options

3. What did you see instead?

supported options

4. What version of Swoole are you using (show your `php --ri swoole`)?

latest

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

linux_x64

**Comment by kvelaro** [comment]
There are also another options which come unclear to me, is there any pure documentation on these options?

**Comment by NathanFreeman** [comment]
If you want to use coroutine-based PDO for PostgreSQL, you need to specify --enable-swoole-pgsql. If you don't need to use it, you can omit this specification.

**Comment by NathanFreeman** [comment]
https://wiki.swoole.com/en/#/environment?id=general-parameters
You can see the documentation, but some content related to Swoole 6.0 is still under writing and will be updated later.

**Comment by kvelaro** [comment]
Thank you so much
Closing this issue as answer received
