### ISSUE TITLE
http_server worker异常退出 swoole版本：1.7.22 php版本：5.5.31 操作系统：centos 7

### ISSUE THREAD

**Issue by danchaofan** [swoole/swoole-src#563]
server配置：
$serv->set(array(
    'worker_num'    => 1,
    'daemonize'     => true,
    'dispatch_mode' => 3,
    'reactor'       => 1,
    'max_request'   => 10000,
));
strace worker 进程获得如下信息

27789 14:26:18.773771 epoll_wait(7, {{EPOLLIN, {u32=4, u64=21474836484}}}, 4096, -1) = 1
27789 14:26:18.882867 read(4, "\26\1\0\0[\5\0\0\n\7\0\0POST /filterrpc/Irpi"..., 8192) = 1383
27789 14:26:18.883288 sendto(12, "\1\0\0\0\16", 5, MSG_DONTWAIT, NULL, 0) = 5
27789 14:26:18.883339 poll([{fd=12, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=12, revents=POLLIN}])
27789 14:26:18.883529 recvfrom(12, "\7\0\0\1\0\0\0\2\0\0\0", 22, MSG_DONTWAIT, NULL, NULL) = 11
27789 14:26:18.883576 sendto(12, "9\3\0\0\3SELECT id , limit_time as l"..., 829, MSG_DONTWAIT, NULL, 0) = 829
27789 14:26:18.883605 poll([{fd=12, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=12, revents=POLLIN}])
27789 14:26:18.884461 recvfrom(12, "\1\0\0\1\2'\0\0\2\3d", 11, MSG_DONTWAIT, NULL, NULL) = 11
27789 14:26:18.884488 poll([{fd=12, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=12, revents=POLLIN}])
27789 14:26:18.884512 recvfrom(12, "ef\5kkgoo\1u\7kk_user\2id\2id\f?\0\n\0\0\0\3"..., 82, MSG_DONTWAIT, NULL, NULL) = 82
27789 14:26:18.884535 poll([{fd=12, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=12, revents=POLLIN}])
27789 14:26:18.884559 recvfrom(12, "\3\0\0\0\0\0\5\0\0\4\376\0\0\2\0\10\0\0\5\00580630\0010\t\0\0\6\6"..., 82, MSG_DONTWAIT, NULL, NULL) = 82
27789 14:26:18.884591 write(2, "zend_mm_heap corrupted\n", 23) = 23
27789 14:26:18.886683 exit_group(1)     = ?
27789 14:26:18.888340 +++ exited with 1 +++

**Comment by matyhtf** [comment]
`lsof -p 进程ID` 查看 12 是什么，此错误可能与swoole无关。

**Comment by danchaofan** [comment]
@matyhtf  12是mysql链接

**Comment by danchaofan** [comment]
@matyhtf  使用的mysqli扩展
