### ISSUE TITLE
Add partitioned cookie support

### ISSUE THREAD

**Issue by jamesRUS52** [swoole/swoole-src#5645]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
I am trying to set partitioned cookie via Laravel Octane

2. What did you expect to see?
Set-Cookie header should be with "partitioned"

3. What did you see instead?
Set-Cookie header withou "partitioned"

4. What version of Swoole are you using (show your `php --ri swoole`)?
6.0.0

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux dbb271a627bd 6.12.4-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Dec  9 20:01:35 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

PHP 8.3.14 (cli) (built: Nov 25 2024 18:07:16) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.14, Copyright (c), by Zend Technologies
    with Xdebug v3.4.0, Copyright (c) 2002-2024, by Derick Rethans

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

**Comment by NathanFreeman** [comment]
```php
use Swoole\Http\Cookie;
$http->on('request', function ($request, $response) {
    $cookie = new Cookie();
    $cookie->withName('test')
        ->withValue('123456789')
        ->withExpires(time() + 3600)
        ->withPath('/path')
        ->withDomain('example.com')
        ->withSecure(true)
        ->withHttpOnly(true)
        ->withSameSite('None')
        ->withPartitioned(true);
    $response->cookie($cookie);
    $response->end("<h1>Hello Swoole. #".rand(1000, 9999)."</h1>");
});


```
