### ISSUE TITLE
无限循环创建子进程时子进程无法回收

### ISSUE THREAD

**Issue by iyaozhen** [swoole/swoole-src#566]
可能是我使用上的问题，对这块不是很了解。先说一下我的使用场景吧：
我使用 PHP 脚本从 kafka 订阅数据，为了提高并发，我使用一个主进程不停订阅数据（kafka 规定一个 Partition 只能被一个 Consumer 消费），然后将数据分发给子进程处理。
代码大概如下：
```PHP
$consumer = new RdKafka\KafkaConsumer($conf);
$consumer->subscribe(['test']);

$workers = [];  // 工作进程
while (true) {
    $message = $consumer->consume(10e3);
    switch ($message->err) {
        case RD_KAFKA_RESP_ERR_NO_ERROR:
            $message = (array)$message;

            $process = new swoole_process('worker_callback', false, true);
            $pid = $process->start();
            $workers[$pid] = $process;
            $process->write($message['payload']);  // 进程间通讯, 向子进程发送数据

            $ret =  swoole_process::wait();
            print_r($ret);

            break;
        case RD_KAFKA_RESP_ERR__PARTITION_EOF:
            $logger->warning("No more messages, will wait for more");
            break;
        case RD_KAFKA_RESP_ERR__TIMED_OUT:
            $logger->warning("Consume timeout");
            break;
        default:
            throw new \Exception($message->errstr(), $message->err);
            break;
    }
}

function worker_callback(swoole_process $worker)
{
    $message = $worker->read(); // 读取父进程发送过来的数据
    ……
    $worker->exit(0);
}
```

我创建完一个子进程后`swoole_process::wait()`但没获取到任何结果，试了异步 wait 也没有获取到结果（我的需求是异步的）。
又看了下文档，在 http://wiki.swoole.com/wiki/page/215.html 发现：

>因为子进程会继承父进程的内存和IO句柄，所以如果父进程要创建多个子进程，务必要等待创建完毕后再使用swoole_event_add/异步swoole_client/定时器/信号等异步IO函数。

感觉是这个原因，但我无法一下子创建完呀，这个该怎么办？

我是需要事先就生成 100 个子进程？然后给按照某个分配机制给他们分发数据？

C/C++ 的功底几乎没有，没搞过多进（线）程编程。写的时候想的是像 js ajax 一样异步 callback。可能有点想当然了，还请见谅。

PHP7 + swoole 1.8.2

**Comment by jonnywang** [comment]
为什么要在得到一个消息时create一个process呢，还使用wait了， 用法明显不对哦

**Comment by iyaozhen** [comment]
@jonnywang 嗯，是的用法可能有点不对。一般是怎么用呢？

代码是个示例，我想的是获取到 100 个消息后创建一个子进程做处理，然后异步 wait 回收。

**Comment by RamboLau** [comment]
改为 $ret =  swoole_process::wait(false);试试

**Comment by iyaozhen** [comment]
@RamboLau 没啥效果，还是一样的。应该是我的用法不对。

我还是先创建好一定数量的子进程，然后主进程给这些子进程分配数据。

**Comment by wenjun1055** [comment]
@iyaozhen 我刚做了一个类似你的这个的东西，不过我的做法跟你的有点不同，我也是从kafka中拉取数据。然后扔给子进程推送到接收方。跟你的做法不同的是，我的主进程不负责从kafka获取数据，只是单纯的监听一些信号以及做定时器。而我将子进程分为了两种，一种只负责从kafka拉取数据。另一张接收到数据后推送给接收方。如果感兴趣的话，可以hi上私聊我

**Comment by iyaozhen** [comment]
@wenjun1055 Hi上群里的就是我呀。😂

**Comment by wenjun1055** [comment]
@iyaozhen 我知道啊，所以我让你hi上私我
