### ISSUE TITLE
worker_num issue

### ISSUE THREAD

**Issue by lscgzwd** [swoole/swoole-src#567]
http://group.swoole.com/question/106261

当worker_num大于某个值时，worker进程异常退出

**Comment by matyhtf** [comment]
贴出  `new swoole_server`和`$sever->set`的参数。

**Comment by lscgzwd** [comment]
'setting' => [
        'user'  => 'fdjzlm',
        'group' => 'nginx',
        'worker_num' => 200,
        'max_request' => 5000,
        'daemonize' => 1,
        'log_file' => '/home/fdjzlm/logs/swoole-egg.log',
        'log_level' => 1
    ],


$this->server = new swoole_http_server($this->listens['http']['host'], $this->listens['http']['port']);
$this->server->setGlobal(HTTP_GLOBAL_ALL, HTTP_GLOBAL_GET | HTTP_GLOBAL_POST | HTTP_GLOBAL_COOKIE);

**Comment by matyhtf** [comment]
1.8.3 最新代码已修复此问题。
