### ISSUE TITLE
WARNING swManager_check_exit_status: worker#11 abnormal exit, status=0, signal=11

### ISSUE THREAD

**Issue by lscgzwd** [swoole/swoole-src#574]
swoole 1.8.2 
php 7.0.4

详细BUG描述：http://group.swoole.com/question/106264?item_id=901&rf=false

**Comment by lscgzwd** [comment]
gdb -p pid

然后bt回车得到如下堆栈：

#0  0x0000003568ce8f13 in __epoll_wait_nocancel () at ../sysdeps/unix/syscall-template.S:82
#1  0x00007f328176d46b in swReactorEpoll_wait (reactor=0x18c99d0, timeo=<value optimized out>)
    at /usr/src/debug/php70-php-pecl-swoole-1.8.2/NTS/src/reactor/ReactorEpoll.c:231
#2  0x00007f328177b9dd in swWorker_loop (factory=<value optimized out>, worker_id=<value optimized out>)
    at /usr/src/debug/php70-php-pecl-swoole-1.8.2/NTS/src/network/Worker.c:446
#3  0x00007f3281779553 in swManager_spawn_worker (factory=0x1894550, worker_id=15)
    at /usr/src/debug/php70-php-pecl-swoole-1.8.2/NTS/src/network/Manager.c:440
#4  0x00007f3281779ab7 in swManager_loop (factory=0x1894550)
    at /usr/src/debug/php70-php-pecl-swoole-1.8.2/NTS/src/network/Manager.c:298
#5  swManager_start (factory=0x1894550) at /usr/src/debug/php70-php-pecl-swoole-1.8.2/NTS/src/network/Manager.c:177
#6  0x00007f328176a45a in swFactoryProcess_start (factory=0x1894550)
    at /usr/src/debug/php70-php-pecl-swoole-1.8.2/NTS/src/factory/FactoryProcess.c:86
#7  0x00007f3281770295 in swServer_start (serv=0x1894120)
    at /usr/src/debug/php70-php-pecl-swoole-1.8.2/NTS/src/network/Server.c:568
#8  0x00007f3281753782 in zim_swoole_http_server_start (execute_data=0x7f328f013820, return_value=0x7f328f013810)
    at /usr/src/debug/php70-php-pecl-swoole-1.8.2/NTS/swoole_http_server.c:1562
#9  0x00000000005d4049 in dtrace_execute_internal (execute_data=<value optimized out>, return_value=<value optimized out>)
    at /usr/src/debug/php-7.0.4/Zend/zend_dtrace.c:107
#10 0x0000000000659132 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f328f013780)
    at /usr/src/debug/php-7.0.4/Zend/zend_vm_execute.h:844
#11 0x00000000006215d0 in execute_ex (ex=<value optimized out>) at /usr/src/debug/php-7.0.4/Zend/zend_vm_execute.h:417
#12 0x00000000005d418e in dtrace_execute_ex (execute_data=0x7f328f013780) at /usr/src/debug/php-7.0.4/Zend/zend_dtrace.c:83
#13 0x0000000000658faa in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f328f0133a0)
    at /usr/src/debug/php-7.0.4/Zend/zend_vm_execute.h:800
#14 0x00000000006215d0 in execute_ex (ex=<value optimized out>) at /usr/src/debug/php-7.0.4/Zend/zend_vm_execute.h:417
#15 0x00000000005d418e in dtrace_execute_ex (execute_data=0x7f328f0133a0) at /usr/src/debug/php-7.0.4/Zend/zend_dtrace.c:83
#16 0x0000000000658faa in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f328f0130d0)
    at /usr/src/debug/php-7.0.4/Zend/zend_vm_execute.h:800
#17 0x00000000006215d0 in execute_ex (ex=<value optimized out>) at /usr/src/debug/php-7.0.4/Zend/zend_vm_execute.h:417
#18 0x00000000005d418e in dtrace_execute_ex (execute_data=0x7f328f0130d0) at /usr/src/debug/php-7.0.4/Zend/zend_dtrace.c:83
#19 0x0000000000658faa in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7f328f013030)
    at /usr/src/debug/php-7.0.4/Zend/zend_vm_execute.h:800
---Type <return> to continue, or q <return> to quit---
#20 0x00000000006215d0 in execute_ex (ex=<value optimized out>) at /usr/src/debug/php-7.0.4/Zend/zend_vm_execute.h:417
#21 0x00000000005d418e in dtrace_execute_ex (execute_data=0x7f328f013030) at /usr/src/debug/php-7.0.4/Zend/zend_dtrace.c:83
#22 0x000000000067440b in zend_execute (op_array=0x7f328f083000, return_value=<value optimized out>)
    at /usr/src/debug/php-7.0.4/Zend/zend_vm_execute.h:458
#23 0x00000000005e2af3 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/src/debug/php-7.0.4/Zend/zend.c:1427
#24 0x0000000000584480 in php_execute_script (primary_file=0x7ffed0b66600) at /usr/src/debug/php-7.0.4/main/main.c:2484
#25 0x00000000006786df in do_cli (argc=3, argv=0x1697c20) at /usr/src/debug/php-7.0.4/sapi/cli/php_cli.c:974
#26 0x0000000000678eea in main (argc=3, argv=0x1697c20) at /usr/src/debug/php-7.0.4/sapi/cli/php_cli.c:1345

**Comment by lscgzwd** [comment]
不知道该怎么使用gdb

http://wiki.swoole.com/wiki/page/442.html

按这个教程，只有bt有输入，输入c回车，直接显示Continuing. 
按ctrl+c
显示：
Program received signal SIGINT, Interrupt.
0x0000003568ce8f13 in __epoll_wait_nocancel () at ../sysdeps/unix/syscall-template.S:82
82	T_PSEUDO (SYSCALL_SYMBOL, SYSCALL_NAME, SYSCALL_NARGS)

我怎么样才能抓 到异常的错误段？

**Comment by lscgzwd** [comment]
好像是出在epoll等待？

**Comment by matyhtf** [comment]
设置ulimit -c unlimited，抓取core dump文件，使用gdb php core 分析

**Comment by lscgzwd** [comment]
经测试.1.8.3 rc.1无此BUG

**Comment by lscgzwd** [comment]
1.8.3测试无此BUG，已经修复，关闭
