### ISSUE TITLE
使用swoole_websocket_server的问题

### ISSUE THREAD

**Issue by shizenghua** [swoole/swoole-src#578]
使用swoole_websocket_server创建的服务，当浏览器刷新的时候，服务端的close回调在open，message之后才执行。因为每次刷新fd在变，这样导致了不能及时更新在线用户跟fd的对应关系。
请问这个问题怎么解决？

**Comment by jonnywang** [comment]
服务器使用connect，页面使用beforeunload

**Comment by matyhtf** [comment]
Chrome浏览器的处理顺序是这样的，建议在PHP代码中自行解决。
