### ISSUE TITLE
swoole_http_client 内存泄漏问题

### ISSUE THREAD

**Issue by badxpgy** [swoole/swoole-src#582]
环境：php7.0.3
swoole:master最新
在高并发测试下，内存不降，并出现以下提示
ERROR	zm_deactivate_swoole (ERROR 103): Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /data/wwwroot/mfproxy/mfproxy/MfService.php on line 34.
[code.zip](https://github.com/swoole/swoole-src/files/179246/code.zip)

**Comment by badxpgy** [comment]
static PHP_METHOD(swoole_http_client, __destruct)
{
   printf("__destruct_chenlb\n");
    http_client_set_cb(getThis(), ZEND_STRL("finish"), NULL TSRMLS_CC);
    http_client_set_cb(getThis(), ZEND_STRL("close"), NULL TSRMLS_CC);
    http_client_set_cb(getThis(), ZEND_STRL("error"), NULL TSRMLS_CC);

    http_client_callback *hcc = swoole_get_property(getThis(), 0);

    int i;
    for (i = 0; i < hcc->gc_idx; i++)
    {
        zval *zcb = hcc->gc_list[i];
        sw_zval_ptr_dtor(&zcb);
    }
    efree(hcc);
    swoole_set_property(getThis(), 0, NULL);

    http_client *http = swoole_get_object(getThis());
    if (http)
    {
        http_client_free(getThis(), http);
    }
}

__destruct有运行，但http_client_free 方法未运行，

**Comment by jonnywang** [comment]
和swoole_client一样有内存泄露
