### ISSUE TITLE
swoole 1.8.2报出Segmentation fault

### ISSUE THREAD

**Issue by jishipu** [swoole/swoole-src#584]
在进行大量请求压力测试后，即使重启server也还是异常退出。必须重启操作系统，才正常
gdb信息如下：
Program terminated with signal 11, Segmentation fault.
#0  0x00007f3f12e6e856 in php_swoole_server_get_callback (serv=0x7f3f0e69f000, req=0x7fff59df0bd0) at /home/jishipu/swoole-src-swoole-1.8.2-stable/swoole_server.c:170
170	    swoole_server_port_property *property = port->ptr;
Missing separate debuginfos, use: debuginfo-install php-cli-5.4.21-2.el6.remi.x86_64
(gdb) bt
#0  0x00007f3f12e6e856 in php_swoole_server_get_callback (serv=0x7f3f0e69f000, req=0x7fff59df0bd0) at /home/jishipu/swoole-src-swoole-1.8.2-stable/swoole_server.c:170
#1  php_swoole_onReceive (serv=0x7f3f0e69f000, req=0x7fff59df0bd0) at /home/jishipu/swoole-src-swoole-1.8.2-stable/swoole_server.c:592
#2  0x00007f3f12e9ac58 in swWorker_onTask (factory=<value optimized out>, task=0x7fff59df0bd0) at /home/jishipu/swoole-src-swoole-1.8.2-stable/src/network/Worker.c:163
#3  0x00007f3f12e9ad8b in swWorker_onPipeReceive (reactor=<value optimized out>, event=0x7fff59df2c40) at /home/jishipu/swoole-src-swoole-1.8.2-stable/src/network/Worker.c:499
#4  0x00007f3f12e8e8a1 in swReactorEpoll_wait (reactor=0x7f3f0e731000, timeo=<value optimized out>) at /home/jishipu/swoole-src-swoole-1.8.2-stable/src/reactor/ReactorEpoll.c:263
#5  0x00007f3f12e9b759 in swWorker_loop (factory=<value optimized out>, worker_id=<value optimized out>) at /home/jishipu/swoole-src-swoole-1.8.2-stable/src/network/Worker.c:446
#6  0x00007f3f12e99810 in swManager_spawn_worker (factory=0x7f3f0e69f430, worker_id=0) at /home/jishipu/swoole-src-swoole-1.8.2-stable/src/network/Manager.c:440
#7  0x00007f3f12e99b01 in swManager_start (factory=0x7f3f0e69f430) at /home/jishipu/swoole-src-swoole-1.8.2-stable/src/network/Manager.c:134
#8  0x00007f3f12e8bb82 in swFactoryProcess_start (factory=0x7f3f0e69f430) at /home/jishipu/swoole-src-swoole-1.8.2-stable/src/factory/FactoryProcess.c:86
#9  0x00007f3f12e913ad in swServer_start (serv=0x7f3f0e69f000) at /home/jishipu/swoole-src-swoole-1.8.2-stable/src/network/Server.c:568
#10 0x00007f3f12e6f6f7 in zim_swoole_server_start (ht=<value optimized out>, return_value=0x7f3f0e904800, return_value_ptr=<value optimized out>, this_ptr=0x7f3f0e9047a0, 
    return_value_used=<value optimized out>) at /home/jishipu/swoole-src-swoole-1.8.2-stable/swoole_server.c:1771
#11 0x000000000065e12c in ?? ()
#12 0x000000000064b878 in execute ()
#13 0x00000000005e17b0 in zend_execute_scripts ()
#14 0x0000000000584548 in php_execute_script ()
#15 0x000000000068d163 in ?? ()
#16 0x000000000068d928 in ?? ()
#17 0x00007f3f22425d5d in __libc_start_main () from /lib64/libc.so.6
#18 0x0000000000424219 in _start ()

**Comment by matyhtf** [comment]
新的1.8.3版本中已经解决此问题。
