### ISSUE TITLE
WARNING	swSystemTimer_signal_set: setitimer() failed. Error: Invalid argument[22]

### ISSUE THREAD

**Issue by czd13142006** [swoole/swoole-src#587]
$serv->on('task', function ($_server, $worker_id, $task_id, $data)
        {

            $fd = $data['s_id'];
            $_server->tick(4000, function($id) use ($fd, $_server,$data) {

                $pay =  getOrderPayStatus($data['order'], $data['uid']);

                if($pay==1){
                     $_server->clearTimer($id);
                     $ret = $_server->push($fd, '1');
                  //   $_server->close($fd);
                }elseif($pay==3){

                     $_server->clearTimer($id);
                    $ret = $_server->push($fd, '2');
                    // $_server->close($fd,true);
                }  
            });

            return ;
        });

**Comment by czd13142006** [comment]
Close czd: 2tick czd:
[/home/swoole-src-swoole-1.8.3-stable/src/factory/FactoryProcess.c:246@swFactoryProcess_finish][Worker] send: sendn=12|type=4|content=(null)
[/home/swoole-src-swoole-1.8.3-stable/src/network/ReactorThread.c:281@swReactorThread_close]Close Event.fd=29|from=1
[2016-03-23 13:32:50 ^13539.5]	WARNING	swSystemTimer_signal_set: setitimer() failed. Error: Invalid argument[22]
[/home/swoole-src-swoole-1.8.3-stable/src/network/ReactorThread.c:349@swReactorThread_close]set_maxfd=28|close_fd=29

[2016-03-23 13:32:54 ^13539.5]	WARNING	swSystemTimer_signal_set: setitimer() failed. Error: Invalid argument[22]

**Comment by jonnywang** [comment]
task进程不能使用tick/after定时器
http://wiki.swoole.com/wiki/page/414.html

**Comment by czd13142006** [comment]
增加Task进程对tick/after定时器的支持，底层基于高精度的setitimer+信号实现

**Comment by matyhtf** [comment]
请执行 
```shell
strace -s 1000 -o s.log php your_program.php
```
重现后贴出s.log 中 `setitimer` 前后的日志。你的操作系统是否为MacOS

**Comment by czd13142006** [comment]
CentOS release 6.6 (Final)
PHP Version 5.6.9 Swoole版本 1.8.3 stable

**Comment by czd13142006** [comment]
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL, si_value={int=0, ptr=0x100000000}} ---
restart_syscall(<... resuming interrupted call ...>) = 0
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 1 ([{fd=3, revents=POLLIN}])
write(1, "[/home/swoole-src-swoole-1.8.3-stable/src/reactor/ReactorPoll.c:245@swReactorPoll_wait]Event: fd=24|from_id=4|type=11\n", 118) = 118
write(1, "[/home/swoole-src-swoole-1.8.3-stable/src/reactor/ReactorPoll.c:245@swReactorPoll_wait]Event: fd=3|from_id=4|type=1\n", 116) = 116
accept4(3, {sa_family=AF_INET, sin_port=htons(35948), sin_addr=inet_addr("192.168.17.228")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 29
write(1, "[/home/swoole-src-swoole-1.8.3-stable/src/network/Server.c:131@swServer_master_onAccept][Master] Accept new connection. maxfd=3|reactor_id=4|conn=29\n", 149) = 149
epoll_ctl(26, EPOLL_CTL_ADD, 29, {EPOLLIN, {u32=29, u64=29}}) = 0
accept4(3, 0x7fff1f13fc10, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)

**Comment by czd13142006** [comment]
setsockopt(18, SOL_SOCKET, SO_SNDBUF, [8388608], 4) = 0
setsockopt(18, SOL_SOCKET, SO_RCVBUF, [8388608], 4) = 0
setsockopt(19, SOL_SOCKET, SO_SNDBUF, [8388608], 4) = 0
setsockopt(19, SOL_SOCKET, SO_RCVBUF, [8388608], 4) = 0
socketpair(PF_LOCAL, SOCK_DGRAM, 0, [20, 21]) = 0
setsockopt(20, SOL_SOCKET, SO_SNDBUF, [8388608], 4) = 0
setsockopt(20, SOL_SOCKET, SO_RCVBUF, [8388608], 4) = 0
setsockopt(21, SOL_SOCKET, SO_SNDBUF, [8388608], 4) = 0
setsockopt(21, SOL_SOCKET, SO_RCVBUF, [8388608], 4) = 0
socketpair(PF_LOCAL, SOCK_DGRAM, 0, [22, 23]) = 0
setsockopt(22, SOL_SOCKET, SO_SNDBUF, [8388608], 4) = 0
setsockopt(22, SOL_SOCKET, SO_RCVBUF, [8388608], 4) = 0
setsockopt(23, SOL_SOCKET, SO_SNDBUF, [8388608], 4) = 0
setsockopt(23, SOL_SOCKET, SO_RCVBUF, [8388608], 4) = 0
access("/tmp", R_OK)                    = 0
mmap(NULL, 2097240, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0) = 0x7f8d3d612000
mmap(NULL, 2097240, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0) = 0x7f8d3d411000
mmap(NULL, 2097240, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0) = 0x7f8d3d210000
mmap(NULL, 2097240, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0) = 0x7f8d3d00f000
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f8d4c6a3a90) = 1692
mmap(NULL, 266240, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8d3cfce000
signalfd4(-1, [USR1 USR2 ALRM TERM CHLD VTALRM], 8, O_NONBLOCK|O_CLOEXEC) = 24
rt_sigprocmask(SIG_BLOCK, [USR1 USR2 ALRM TERM CHLD VTALRM], NULL, 8) = 0
write(1, "[/home/swoole-src-swoole-1.8.3-stable/src/reactor/ReactorPoll.c:104@swReactorPoll_add]fd=24, fdtype=11\n", 103) = 103
write(1, "[/home/swoole-src-swoole-1.8.3-stable/src/reactor/ReactorPoll.c:104@swReactorPoll_add]fd=3, fdtype=1\n", 101) = 101
mmap(NULL, 10489856, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f8d3c5cd000
mprotect(0x7f8d3c5cd000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f8d3cfccf30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8d3cfcd9d0, tls=0x7f8d3cfcd700, child_tidptr=0x7f8d3cfcd9d0) = 1693
mmap(NULL, 10489856, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f8d375ff000
mprotect(0x7f8d375ff000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f8d37ffef30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8d37fff9d0, tls=0x7f8d37fff700, child_tidptr=0x7f8d37fff9d0) = 1694
mmap(NULL, 10489856, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f8d36bfe000
mprotect(0x7f8d36bfe000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f8d375fdf30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8d375fe9d0, tls=0x7f8d375fe700, child_tidptr=0x7f8d375fe9d0) = 1695
mmap(NULL, 10489856, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f8d361fd000
mprotect(0x7f8d361fd000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f8d36bfcf30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f8d36bfd9d0, tls=0x7f8d36bfd700, child_tidptr=0x7f8d36bfd9d0) = 1696
futex(0x20e1f48, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)

**Comment by matyhtf** [comment]
`setitimer`在Task进程执行的，想办法使用strace跟踪这个函数的执行。

**Comment by czd13142006** [comment]
28626 09:58:27.766771 poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000 <unfinished ...>
28638 09:58:28.525586 <... read resumed> 0x7fff8ac8e798, 65548) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
28638 09:58:28.525679 --- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL, si_value={int=0, ptr=0x100000000}} ---
28638 09:58:28.525751 rt_sigreturn()    = -1 EINTR (Interrupted system call)
28638 09:58:28.525873 setitimer(ITIMER_REAL, {it_interval={0, 18446744073709550616}, it_value={0, 18446744073709550616}}, 0) = -1 EINVAL (Invalid argument)
28638 09:58:28.526015 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
28638 09:58:28.526162 write(1, "[2016-03-24 09:58:28 ^28626.4]\tWARNING\tswSystemTimer_signal_set: setitimer() failed. Error: Invalid argument[22]\n", 113) = 113
28638 09:58:28.526297 read(16,  <unfinished ...>
28626 09:58:28.768062 <... poll resumed> ) = 0 (Timeout)
28626 09:58:28.768259 poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
28626 09:58:29.769707 poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)

**Comment by czd13142006** [comment]
28631 09:58:24.546975 read(11,  <unfinished ...>
28638 09:58:24.547078 <... setitimer resumed> 0) = -1 EINVAL (Invalid argument)
28631 09:58:24.547123 <... read resumed> "\1\0\0\0\0\0\1\0\4\0\0\0", 65548) = 12
28631 09:58:24.547187 epoll_ctl(26, EPOLL_CTL_DEL, 29, NULL) = 0
28631 09:58:24.547326 write(1, "[/home/swoole-src-swoole-1.8.3-stable/src/network/ReactorThread.c:281@swReactorThread_close]Close Event.fd=29|from=1\n", 117 <unfinished ...>
28638 09:58:24.547373 stat("/etc/localtime",  <unfinished ...>
28631 09:58:24.547416 <... write resumed> ) = 117
28638 09:58:24.547451 <... stat resumed> {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
28631 09:58:24.547497 futex(0x7f272530f150, FUTEX_WAIT, 2, NULL <unfinished ...>
28638 09:58:24.547614 write(1, "[2016-03-24 09:58:24 ^28626.4]\tWARNING\tswSystemTimer_signal_set: setitimer() failed. Error: Invalid argument[22]\n", 113) = 113
28638 09:58:24.547931 futex(0x7f272530f150, FUTEX_WAKE, 1) = 1
28631 09:58:24.548036 <... futex resumed> ) = 0
28638 09:58:24.548076 read(16,  <unfinished ...>
28631 09:58:24.548111 write(1, "[/home/swoole-src-swoole-1.8.3-stable/src/network/ReactorThread.c:349@swReactorThread_close]set_maxfd=28|close_fd=29\n\n", 118) = 118
28631 09:58:24.548272 futex(0x7f272530f150, FUTEX_WAKE, 1) = 0
28631 09:58:24.548417 close(29)         = 0
28631 09:58:24.548601 read(11, 0x7f27216d9c10, 65548) = -1 EAGAIN (Resource temporarily unavailable)
28631 09:58:24.548894 epoll_wait(26,  <unfinished ...>
28626 09:58:24.762213 <... poll resumed> ) = 0 (Timeout)
28626 09:58:24.762391 poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
28626 09:58:25.763829 poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Ti

**Comment by czd13142006** [comment]
poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
30128 10:07:23.300800 poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000 <unfinished ...>
30138 10:07:24.142194 <... read resumed> 0x7fff05098c38, 65548) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
30138 10:07:24.142370 --- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL, si_value={int=0, ptr=0x100000000}} ---
30138 10:07:24.142485 rt_sigreturn()    = -1 EINTR (Interrupted system call)
30138 10:07:24.142684 setitimer(ITIMER_REAL, {it_interval={0, 18446744073709550616}, it_value={0, 18446744073709550616}}, 0) = -1 EINVAL (Invalid argument)
30138 10:07:24.142905 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=388, ...}) = 0
30138 10:07:24.143130 write(1, "[2016-03-24 10:07:24 ^30128.4]\tWARNING\tswSystemTimer_signal_set: setitimer() failed. Error: Invalid argument[22]\n", 113) = 113
30138 10:07:24.143323 read(16,  <unfinished ...>
30128 10:07:24.311504 <... poll resumed> ) = 0 (Timeout)
30128 10:07:24.311730 poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
30128 10:07:25.313069 poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)

**Comment by czd13142006** [comment]
正常
30138 10:06:36.131870 setitimer(ITIMER_REAL, {it_interval={4, 0}, it_value={4, 0}},  <unfinished ...>
30135 10:06:36.131899 epoll_wait(3,  <unfinished ...>
30138 10:06:36.131918 <... setitimer resumed> NULL) = 0
错误
30138 10:07:20.149492 setitimer(ITIMER_REAL, {it_interval={0, 18446744073709541616}, it_value={0, 18446744073709541616}}, 0) = -1 EINVAL (Invalid argument)

**Comment by jonnywang** [comment]
问题出在

if (!tnode)
    {
        timer->set(timer, -1);
    }
    else
    {
        timer->set(timer, tnode->exec_msec - now_msec);
    }

**Comment by czd13142006** [comment]
ok
close(3)          = 0
16595 14:35:08.171720 write(1, "1", 1)  = 1
16595 14:35:08.171892 write(1, "\r\n", 2) = 2
16595 14:35:08.172167 write(10, "\1\0\0\0\3\0\1\0\0\0f\22\201\0011", 15) = 15
16588 14:35:08.172315 <... epoll_wait resumed> {{EPOLLIN, {u32=11, u64=21474836491}}}, 4096, -1) = 1
16588 14:35:08.172377 read(11, "\1\0\0\0\3\0\1\0\0\0f\22\201\0011", 8192) = 15
16588 14:35:08.172539 sendto(29, "\201\0011", 3, 0, NULL, 0 <unfinished ...>
16595 14:35:08.172580 <... write resumed> ) = 128
16588 14:35:08.172691 <... sendto resumed> ) = 3
16595 14:35:08.172741 write(1, "Close czd: 1tick czd:", 21 <unfinished ...>
16588 14:35:08.172786 read(11,  <unfinished ...>
16595 14:35:08.172866 <... write resumed> ) = 21
16588 14:35:08.172905 <... read resumed> 0x7ff70300bc20, 8192) = -1 EAGAIN (Resource temporarily unavailable)
16595 14:35:08.172945 write(1, "\r\n", 2 <unfinished ...>
16588 14:35:08.172987 epoll_wait(26,  <unfinished ...>
16595 14:35:08.173049 <... write resumed> ) = 2
16595 14:35:08.173156 write(10, "\1\0\0\0\0\0\1\0\4\0*\1", 12) = 12
16588 14:35:08.173290 <... epoll_wait resumed> {{EPOLLIN, {u32=11, u64=21474836491}}}, 4096, -1) = 1
16595 14:35:08.173340 setitimer(ITIMER_REAL, {it_interval={0, 0}, it_value={0, 0}},  <unfinished ...>
16588 14:35:08.173381 read(11,  <unfinished ...>
16595 14:35:08.173419 <... setitimer resumed> NULL) = 0
16588 14:35:08.173446 <... read resumed> "\1\0\0\0\0\0\1\0\4\0*\1", 8192) = 12
16595 14:35:08.173483 read(16,  <unfinished ...>
16588 14:35:08.173516 epoll_ctl(26, EPOLL_CTL_DEL, 29, NULL) = 0
16588 14:35:08.173693 close(29)         = 0
16588 14:35:08.173898 read(11, 0x7ff70300bc20, 8192) = -1 EAGAIN (Resource temporarily unavailable)
16588 14:35:08.174061 epoll_wait(26,  <unfinished ...>
16585 14:35:09.150218 <... poll resumed> ) = 0 (Timeout)
16585 14:35:09.150413 poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
16585 14:35:10.151886 poll([{fd=24, events=POLLIN}, {fd=3, events=POLLIN}], 2, 1000) = 0 (Timeout)
