### ISSUE TITLE
websocket收到close消息，并不会关闭连接

### ISSUE THREAD

**Issue by pantaovay** [swoole/swoole-src#590]
在https://github.com/swoole/swoole-src/blob/master/src/network/Port.c#L199

解析了CLOSE消息，然后给客户端返回一个code为1000的close消息，但是服务端没有关闭连接，直接`return SW_ERR`了。onPackage的return并没有被调用方处理，所以服务端不会关闭连接。
```c
 case WEBSOCKET_OPCODE_CONNECTION_CLOSE:
        if (0x7d < (length - 2))
        {
            return SW_ERR;
        }
        send_frame.str[0] = 0x88;
        send_frame.str[1] = 0x00;
        send_frame.length = 2;
        swConnection_send(conn, send_frame.str, 2, 0);
        return SW_ERR;
```

根据rfc：https://tools.ietf.org/html/rfc6455#section-5.3

> After both sending and receiving a Close message, an endpoint
   considers the WebSocket connection closed and MUST close the
   underlying TCP connection.  **The server MUST close the underlying TCP
   connection immediately**; the client SHOULD wait for the server to
   close the connection but MAY close the connection at any time after
   sending and receiving a Close message, e.g., if it has not received a
   TCP Close from the server in a reasonable time period.

应该关闭连接，并且`return SW_OK`吧？

不会改😭

**Comment by pantaovay** [comment]
@jonnywang @matyhtf

**Comment by matyhtf** [comment]
会关闭连接，`return SW_ERR` 后更底层的函数会直接触发`onClose`事件，然后关闭此连接。

**Comment by pantaovay** [comment]
我看代码不是很明白，调用onPackage的地方，并没有处理返回值啊 @matyhtf

**Comment by pantaovay** [comment]
我实际测试并没有触发onClose😭
