### ISSUE TITLE
WARN	swSignal_callback: signal[13] callback is null.

### ISSUE THREAD

**Issue by winfan** [swoole/swoole-src#596]
版本：swoole 1.7.21 stable
这是什么问题,异步往另外一个端口转发消息，为什么会缺少回调呢？
$serv->fp 在 workstart里面连接好了，
A
 $http_request = json_encode($data);
 swoole_event_write($serv->fp, $http_request);

另外一端口 9603接收部分
B
    public function onReceive(swoole_server $serv, $fd, $from_id, $data){
        $serv->task($data);
    }

我的需求是：swoole 9501端口接收到request数据后，放另外一端口发送啊。不需要 什么回调啊！

问题：

 server A 往 另外一个 server B端口发消息时
如果先（start）启动A,然后启动(start)B  A会报错 call back is null …..
错误如下
WARN	swSignal_callback: signal[13] callback is null.

**Comment by winfan** [comment]
@matyhtf 请韩哥，帮看看

**Comment by kong36088** [comment]
建议发一下完整代码

**Comment by matyhtf** [comment]
此错误可以忽略。你没有检查一些操作的返回值，signal 13表示向错误的socket发送数据。
