### ISSUE TITLE
定时器执行完后如何自动退出程序

### ISSUE THREAD

**Issue by andot** [swoole/swoole-src#600]
现在程序里面只要调用了 `swoole_timer_after` 或者 `swoole_timer_tick`，不管定时器是否已经执行结束，程序都不会退出。这样的话，在客户端程序或者 Web 页面中就无法使用定时器了，因为使用之后，整个程序卡死在那里，不能结束了。能否像 `event` 或 `libevent` 扩展一样，当定时器上的任务都执行完之后，自动结束事件循环，退出程序啊？

另外，`event` 和 `libevent` 的定时器精度是微秒级的（microseconds），`swoole` 的定时器能否也做成微秒级的啊。

还有 `event` 和 `libevent` 都允许将等待时间设置为 0，这样就可以实现 `nextTick` 的功能了，`swoole` 能否加上设置为 0 的支持。

**Comment by matyhtf** [comment]
目前不支持微妙。时间为0你可以用 `swoole_event_after `，退出使用 `swoole_event_exit`

**Comment by andot** [comment]
`swoole_event_after` 设置为 0 时，会有一个警告信息：

```
Warning: swoole_timer_after(): Timer must be greater than 0 ...
```

因为不知道事件循环中的所有事件何时会执行完，所以没办法手动调用 `swoole_event_exit` 结束。
