### ISSUE TITLE
task进程fread资源的时候，一直卡在读取的地方

### ISSUE THREAD

**Issue by niozhanghuawei** [swoole/swoole-src#601]
strace -f -p 24151
查看task进程一直在不停的循环读取资源，这个代码单独在php命令行下能够正确使用，放入task进程类就不行了。

![image](https://cloud.githubusercontent.com/assets/2196735/14080398/6ed1c036-f537-11e5-89f6-1cdbf2892920.png)

**Comment by niozhanghuawei** [comment]
swoole 版本 Constant [ string SWOOLE_VERSION ] { 1.8.3 }

**Comment by matyhtf** [comment]
lsof -p 24151，查看 4 是socket

**Comment by niozhanghuawei** [comment]
php     13521 root    9u  unix 0xffff880206cd0480      0t0 3619222813 socket
是读取socket长链接的流。

**Comment by niozhanghuawei** [comment]
好像在task内执行读取网络打开的socket流会很慢，我单独执行脚本就没什么问题，放到task任务进程内就出现卡死的现象。

**Comment by matyhtf** [comment]
无进一步的跟踪信息，暂时关闭，待重现后继续跟踪解决。
