### ISSUE TITLE
只要swoole一执行 我的cpu就100%了...什么情况

### ISSUE THREAD

**Issue by jonny77** [swoole/swoole-src#605]
就弄了个简单的timer ,模拟定时访问某一个接口程序
服务器是腾讯云的  1核一g的配置. 
<?php 
class Crontab_check_domain{
	protected $serv = null;
	public function __construct(){
		$this->serv =  new swoole_server("127.0.0.1", 9504);
		$this->serv->set(array('daemonize'=>1,'worker_num'=>1));
		$this->serv->on('WorkerStart',array($this,'WorkerStart'));
		$this->serv->on('Receive',array($this,'Receive'));
		$this->serv->on('Timer',array($this,'onTimer'));
		$this->serv->start();
	}
	
	public function onTimer($serv){

		echo file_get_contents('http://www.123.com/check_phonenum/');
	}
	
	public function WorkerStart($serv){
		$serv->addtimer(120000);
	}
	
	public function Receive($serv){
	
	}
	public function Close($serv){
		
	}
}
new Crontab_check_domain();

**Comment by jonny77** [comment]
swoole:1.8.3
php:5.6.3
系统   CentOS release 6.7 (Final)

**Comment by matyhtf** [comment]
不支持addtimer，致命错误了。
