### ISSUE TITLE
swoole_http_server->listen的问题

### ISSUE THREAD

**Issue by gowandering** [swoole/swoole-src#606]
$http = new swoole_http_server("0.0.0.0", 9501);
    $http->on('request', function ($request, $response)
    {
        $response->end("<h1>Hello Swoole. #".rand(1000, 9999)."</h1>");
    });

    $tunnel = $http->listen('0.0.0.0', 5555, SWOOLE_SOCK_TCP);
    $tunnel->on('receive', function ($serv, $fd, $from_id, $data) use($http) {
        $http->send($fd, 'Swoole: '.$data);
        $http->close($fd);
    });

    $http->start();

=======================

$tunnel->on('receive', ...) 这一行无效，我翻阅文档后，知道 swoole_http_server 不接受 onReceive，但在 http->listen 之后是我的目的是使用四层TCP链接，我想知道这个是算BUG，还是正确的设计?

PHP7.0.2 / swoole 1.8.2

**Comment by matyhtf** [comment]
1. 请使用1.8.3版本
2. 新增了端口，但是未设定任何协议处理会继承主Server的设置也就是`http`协议。你可以调用`$tunnel->set()`方法设置`open_length_check`或`open_eof_check`等选项实现独立的协议处理。
