### ISSUE TITLE
无法处理 file_get_contents('php://input')

### ISSUE THREAD

**Issue by zxz054321** [swoole/swoole-src#609]
很多composer库用到了file_get_contents('php://input')
swoole的setGlobal( )不处理这个
虽然可以在回调通过$request->rawContent()获取数据，但不兼容第三库

**Comment by matyhtf** [comment]
底层实现原理不同所以无法支持 file_get_contents('php://input')，建议使用PHP代码做兼容。

**Comment by xuhuaiqu** [comment]
微信支付回调遇到了相同的问题。谢谢

**Comment by 52fhy** [comment]
$GLOBALS['HTTP_RAW_POST_DATA'] = $request->rawContent();

**Comment by twose** [comment]
@52fhy 这样会产生严重问题, 不管是异步还是协程全局变量都不会随之切换, 如果代码中间有IO事件, 会造成污染读错数据, 所以你这个方法是错误的

**Comment by 52fhy** [comment]
@twose 打算在request回调里中调用。这么一说，还是直接从`$request->rawContent()`取比较好，不去修改`$GLOBALS['HTTP_RAW_POST_DATA']`。
