### ISSUE TITLE
可以提交项目到文档的“周边开源项目”吗

### ISSUE THREAD

**Issue by zxz054321** [swoole/swoole-src#611]
新做了一个项目，想提交项目到文档的“周边开源项目”
不知是否符合要求，还差什么条件
[https://github.com/zxz054321/aurora](https://github.com/zxz054321/aurora)

**Comment by matyhtf** [comment]
可以。请给出一段介绍的文字。

**Comment by zxz054321** [comment]
Aurora 是一个建立在 [Lightning](https://github.com/zxz054321/lightning) 之上的高性能高并发框架，为追求极限性能而打造，底层由[Phalcon ](https://github.com/phalcon/cphalcon) + [Swoole](https://github.com/swoole/swoole-src)组合驱动，适用于需要支持高并发的场景，如API 接口、微服务等。

**Comment by matyhtf** [comment]
已添加，微博已分享。

**Comment by zxz054321** [comment]
感谢
