### ISSUE TITLE
swoole_http_client 内存泄漏及报错问题

### ISSUE THREAD

**Issue by badxpgy** [swoole/swoole-src#612]
版本：swoole1.8.4-beta
php7 继续存在泄漏问题，
php5 无法使用，swoole_http_client  get时不处理任何请求，
如果用变量保存住 swoole_http_client  对像，则直接报错,进程退出。
错误行号：swoole_http_client.c  513行，

**Comment by matyhtf** [comment]
贴出你的测试代码

**Comment by badxpgy** [comment]
`<?php

$serv = new swoole_server("0.0.0.0", 9501, SWOOLE_PROCESS, SWOOLE_SOCK_TCP);
$serv->set(array(
	'worker_num' => 1, //工作进程数量
	'open_eof_check' => true, //打开EOF检测
	'package_eof' => "\r\n", //设置EOF
));
$serv->on('receive', function ($serv, $fd, $from_id, $data) {
	$cli = isset($GLOBALS['cli']) ? $GLOBALS['cli'] : false;
	if (!$cli || !$cli->isConnected()) {
		$cli = new swoole_http_client('14.215.177.38', 80);
		$cli->setHeaders([
			'Host' => "www.baidu.com",
			"User-Agent" => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36',
			'Accept' => 'text/html,application/xhtml+xml,application/xml',
			'Accept-Encoding' => 'gzip',
		]);
		$GLOBALS['cli'] = $cli;
	}
	$cli->get('/', function ($cli)use($fd) {
		var_dump($cli->body);
		$serv->send($fd, 'ok');
	});
});
$serv->on('WorkerStart', function ($serv, $worker_id) {
	
});
$serv->on('close', function ($serv, $fd) {
	
});
$serv->on('connect', function ($serv, $fd) {
	
});
$serv->start();
`

**Comment by badxpgy** [comment]
环境：php 5.4.9  下载最新 swoole_1.8.4_rc1，  测了一下上面代码，还是报错
ERROR	zm_deactivate_swoole (ERROR 103): Fatal error: swoole_http_client::get(): Operation now in progress phase 2. in
WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=255, signal=0

**Comment by matyhtf** [comment]
已解决，请使用最新的master分支代码进行测试。

**Comment by yesterday679** [comment]
用官网上默认的测试代码
在unbuntu on windows 上测试暴多

[2016-08-02 22:05:44 @29932.0]  WARNING swPipeUnsock_create: socketpair() failed. Error: Socket type not supported [94]
[2016-08-02 22:05:44 @29932.0]  WARNING swFactoryProcess_start: swFactoryProcess_manager_start failed.
PHP Fatal error:  swoole_server::start(): start server failed. Error: swFactoryProcess_start: swFactoryProcess_manager_start failed. in /var/www/html/swoole.p
hp on line 16
[2016-08-02 22:05:44 @29932.0]  ERROR   zm_deactivate_swoole (ERROR 103): Fatal error: swoole_server::start(): start server failed. Error: swFactoryProcess_st
art: swFactoryProcess_manager_start failed. in /var/www/html/swoole.php on line 16.

**Comment by yesterday679** [comment]
最新版本 1.8.8 @matyhtf

**Comment by matyhtf** [comment]
请勿在一个issue中发布多条主题
