### ISSUE TITLE
swoole_http_server共享http连接

### ISSUE THREAD

**Issue by sanwv** [swoole/swoole-src#618]
全异步的swoole_http_server下如何把swoole_http_response共享给task或者其他woker处理并返回呢?
虽然可以遍历connection_list,但如何构建swoole_http_response对象呢?

```
function onTask($server,$taskId,$fromId,$data){
//只传递fd会报错http client is not exist
$res=new swoole_http_response();
$res->fd=$data['fd'];
$res->end('ok');
//直接传递response对象也报同样的错误
$data['http_response']->end('ok');
}
```

我的场景是通过http提交一个长时间的任务job由woker+task或者新建进程处理返回一个job_id,用户随时可以通过http带job_id查询job进度.前后的请求可能分配在不同的woker上,如果可以通过共享fd之类的其他woker或者task可以处理http请求会很方便

谢谢

**Comment by matyhtf** [comment]
将`response`对象保存到worker进程的全局变量数组中，task进程返回结果后会回调worker进程的`onFinish`，这时再从全局变量数组中取出来执行end

**Comment by sanwv** [comment]
可否建议这个feature在以后版本实现呢,像WebSocket的push方法也只能在当前worker中调用,在wokrer/task间来回通信稍有不便,相对TcpServer的send方法只需要一个fd简真太方便了

按我的理解应该可以通过两个方式实现:1.通过fd sock之类显式new出对象2.在server上添加getResponseByFd($fd)之类的方法由低层构建对象

期待评估,多谢

**Comment by matyhtf** [comment]
http-server在设计上是有上下文关联的，所以无法实现上述的功能。

**Comment by sanwv** [comment]
了解了,多谢

**Comment by safecat** [comment]
我使用的方式是worker发到task，task执行完之后再回给worker，然后worker response

但是如果使用了max_request配置，worker在执行完（发到task）之后就会结束，task回过来的时候发现存储在worker里的response对象不见了，因为worker整个进程都重启了。。。

请问@matyhtf 这个情况怎么办比较好
