### ISSUE TITLE
swoole cant run on windows

### ISSUE THREAD

**Issue by leonova** [swoole/swoole-src#621]
Hi,

I followed this:
Install from source

git clone https://github.com/swoole/swoole-src.git
then extracted inside htdocs swoole folder
cd swoole-src
phpize
./configure
make && make install

I've tried all the steps you mentioned on your git but unfortunately im still having errors below:

Notice: Use of undefined constant SWOOLE_PROCESS - assumed 'SWOOLE_PROCESS' in C
:\xampp\htdocs\swoole\server.php on line 20

Notice: Use of undefined constant SWOOLE_SOCK_TCP - assumed 'SWOOLE_SOCK_TCP' in
 C:\xampp\htdocs\swoole\libs\Swoole\Network\Server.php on line 185

Fatal error: Class 'swoole_server' not found in C:\xampp\htdocs\swoole\libs\Swoo
le\Network\Server.php on line 190

let me know if im doing it wrong.
I cant also find the swoole.so which will be placed in xampp/php/ext  and enable the extension in php.ini right?

**Comment by matyhtf** [comment]
Swoole is not support the windows platform, you can use cygwin.

**Comment by amarjitbh** [comment]
> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> ###              #############_**`
Duplicate of #`**_
