### ISSUE TITLE
swoole 1.8.3 stable, swoole_clent 服务端断开，定时重连问题？

### ISSUE THREAD

**Issue by niozhanghuawei** [swoole/swoole-src#624]
swoole_client 长连接服务端，当服务端连接端口后，客户端内部通过swoole_timer_tick 定时检测当前连接是否断开，如果断开执行重连操作。
但是每次connect的时候都报错，错误代码（connect(0, {sa_family=AF_INET, sin_port=htons(40000), sin_addr=inet_addr("61.147.72.238")}, 16) = -1 ENOTSOCK (Socket operation on non-socket)）
![qq 20160409233805](https://cloud.githubusercontent.com/assets/2196735/14404557/3a1ba702-feac-11e5-9626-ab5caa0caded.jpg)
经过调试发现，这里根本进不到  goto create_socket 这里，所有socket一直没有创建出来。
我就在else 最后一行加了一个 goto create_socket，然后重新编译后，发现可以正常执行重连操作。

请问韩大师是我代码的问题吗？我按照文档，如果客户端被迫断开连接，我释放对象，又重连创建对象，执行重连操作，但是不行。
我在1.7.22版本的时候，没有这个问题，最近升级后，就发现这个问题了。服务端发布新颁布后，swooole_client不能自动执行重连操作。

麻烦解答。

**Comment by matyhtf** [comment]
是swoole底层的BUG，请使用1.8.4最新的代码进行测试。
