### ISSUE TITLE
1.8.3 swoole_http_request获取POST数据出错

### ISSUE THREAD

**Issue by censhen** [swoole/swoole-src#629]
![image](https://cloud.githubusercontent.com/assets/8320855/14516900/59055bea-023a-11e6-9634-7cbdd3cca97f.png)

使用swoole_http_sever, 获取request的post数据，第一次请求正常，但是之后的请求都会出现上述情况，第一个参数看起来会带上一次response返回的内容。 swoole版本是1.8.3。

**Comment by matyhtf** [comment]
是底层BUG，1.8.4版本已解决。
