### ISSUE TITLE
Unix domain Socket套接字文件属性如何更改？

### ISSUE THREAD

**Issue by stcer** [swoole/swoole-src#636]
增加linux domain socket的支持
$serv->addlistener("/var/run/myserv.sock", 0, SWOOLE_UNIX_STREAM);

本机fpm模式(nobody用户)下，php无法通过 /var/run/myserv.sock 连接服务
/var/run/myserv.sock文件只有root用户才具有读写权限，如何改变此文件属性，让其它用户可以连接

**Comment by matyhtf** [comment]
可以在`onStart`回调函数中修改`unixsock`文件的权限。
```php
chmod('/var/run/myserv.sock', 0777);
```

**Comment by stcer** [comment]
ok, thanks
