### ISSUE TITLE
stop会报端口无法绑定错误

### ISSUE THREAD

**Issue by diaosj** [swoole/swoole-src#639]
版本号1.8.4

报错信息如下

WARNING	swSocket_bind: bind(0.0.0.0:9502) failed. Error: Address already in use [48]
PHP Fatal error:  swoole_server::__construct(): listen server port failed.

start的时候要绑定端口容易理解，stop的时候报这个错实在是想不通

**Comment by matyhtf** [comment]
stop是给程序内部调的，不能重新new swoole_server去执行stop，你应该使用kill发信号给Server进程关闭服务器。
