### ISSUE TITLE
cmake for c++， make error

### ISSUE THREAD

**Issue by javacty** [swoole/swoole-src#641]
CentOS Linux release 7.2.1511 (Core)
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
<pre>
[ 96%] Building C object CMakeFiles/unittest.dir/src/memory/FixedPool.o
[ 96%] Building C object CMakeFiles/unittest.dir/src/memory/Table.o
[ 97%] Building C object CMakeFiles/unittest.dir/src/memory/MemoryGlobal.o
Linking C executable bin/unittest
CMakeFiles/unittest.dir/tests/main.o: In function `main':
/opt/swoole-src/tests/main.c:8: multiple definition of `main'
CMakeFiles/unittest.dir/tests/hpack/main.o:/opt/swoole-src/tests/hpack/main.c:12: first defined here
CMakeFiles/unittest.dir/tests/int/main.o: In function `main':
/opt/swoole-src/tests/int/main.c:36: multiple definition of `main'
CMakeFiles/unittest.dir/tests/hpack/main.o:/opt/swoole-src/tests/hpack/main.c:12: first defined here
CMakeFiles/unittest.dir/tests/ds.o: In function `linkedlist_pop':
/opt/swoole-src/tests/ds.c:185: undefined reference to `swLinkedList_pop_node'
CMakeFiles/unittest.dir/tests/ds.o: In function `swUnitTest_linkedlist_test':
/opt/swoole-src/tests/ds.c:208: undefined reference to `swLinkedList_insert'
CMakeFiles/unittest.dir/tests/hpack/main.o: In function `main':
main.c:(.text+0x20): undefined reference to `nghttp2_hd_inflate_new'
main.c:(.text+0x33): undefined reference to `nghttp2_strerror'
CMakeFiles/unittest.dir/tests/hpack/main.o: In function `inflate_header_block':
main.c:(.text+0x18b): undefined reference to `nghttp2_hd_inflate_hd'
main.c:(.text+0x265): undefined reference to `nghttp2_hd_inflate_end_headers'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/unittest] Error 1
make[1]: *** [CMakeFiles/unittest.dir/all] Error 2
make: *** [all] Error 2
</pre>

**Comment by matyhtf** [comment]
C++版本官方不再支持。
