### ISSUE TITLE
1.7.22 swoole_client同步短连接模式内存泄露

### ISSUE THREAD

**Issue by qiaodandedidi** [swoole/swoole-src#643]
我用client短连接调用server，随着时间推移，php-fpm的woker进程内存消耗越来越多，遂用valgrind检查了一下内存泄露，错误如下

> [root@10 swoole-src-swoole-1.7.22-stable]# valgrind --leak-check=full   /data/local/php5421/bin/php /data/php_tair_proxy/example/ptair_t.php
==14457== Memcheck, a memory error detector
==14457== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==14457== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==14457== Command: /data/local/php5421/bin/php /data/php_tair_proxy/example/ptair_t.php
==14457==
put success
==14457==
==14457== HEAP SUMMARY:
==14457==     in use at exit: 4,618 bytes in 20 blocks
==14457==   total heap usage: 18,327 allocs, 18,307 frees, 3,556,413 bytes allocated
==14457==
==14457== 200 bytes in 1 blocks are definitely lost in loss record 14 of 20
==14457==    at 0x4C27A2E: malloc (vg_replace_malloc.c:270)
==14457==    by 0xCBA27AD: swClient_create (Client.c:91)
==14457==    by 0xCB6E49E: client_create_socket (swoole_client.c:897)
==14457==    by 0xCB6EBCE: zim_swoole_client_connect (swoole_client.c:1046)
==14457==    by 0x85C8B7: zend_do_fcall_common_helper_SPEC (zend_vm_execute.h:643)
==14457==    by 0x85D30A: ZEND_DO_FCALL_BY_NAME_SPEC_HANDLER (zend_vm_execute.h:756)
==14457==    by 0x85B945: execute (zend_vm_execute.h:410)
==14457==    by 0x819513: zend_execute_scripts (zend.c:1319)
==14457==    by 0x762D1A: php_execute_script (main.c:2502)
==14457==    by 0x8D3803: do_cli (php_cli.c:989)
==14457==    by 0x8D4A67: main (php_cli.c:1365)
==14457==
==14457== LEAK SUMMARY:
==14457==    definitely lost: 200 bytes in 1 blocks
==14457==    indirectly lost: 0 bytes in 0 blocks
==14457==      possibly lost: 0 bytes in 0 blocks
==14457==    still reachable: 4,418 bytes in 19 blocks
==14457==         suppressed: 0 bytes in 0 blocks
==14457== Reachable blocks (those to which a pointer was found) are not shown.
==14457== To see them, rerun with: --leak-check=full --show-reachable=yes
==14457==
==14457== For counts of detected and suppressed errors, rerun with: -v
==14457== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 6 from 6)

看了一下代码(swoole-src/src/network/Client.c)，在同步模式中会sw_malloc，

> if(async)
    {
        cli->socket = swReactor_get(SwooleG.main_reactor, sockfd);
    }
    else
    {
        cli->socket = sw_malloc(sizeof(swConnection));
    }

但是没找到会释放cli->socket的地方，所以在swClient_close函数中加入了sw_free

> if (cli->async)
    {
        ret = swReactor_close(SwooleG.main_reactor, fd);
    }
    else
    {
        bzero(cli->socket, sizeof(swConnection));
        ret = close(fd);
    }
    if (cli->type == SW_SOCK_UNIX_DGRAM)
    {
        unlink(cli->socket->info.addr.un.sun_path);
    }
    sw_free(cli->socket);
    return ret;

这才不会爆内存错误了，看了一下最新的代码还是没有释放的地方，不知道这里有没有什么问题

**Comment by matyhtf** [comment]
此问题已修复，确实存在内存泄漏。 
https://github.com/swoole/swoole-src/commit/bdce9d7cbc668ab1f7ff3ae697e2599ec873e7d3
