### ISSUE TITLE
swoole_http_client  使用长连接时，高并发测试情况下，在onclose时会出现core问题

### ISSUE THREAD

**Issue by badxpgy** [swoole/swoole-src#645]
环境：php5.4.9 swoole-1.8.4-stable
代码如下：

[http_client.zip](https://github.com/swoole/swoole-src/files/240073/http_client.zip)

测试方法：
/usr/local/php/bin/php c10k.php -c 1000 -n 10000 -s 127.0.0.1:9501 
多测几次就会出现core，并且是在处理完请求后，http_client触发 close时出现的。

core信息如下：

#1  0x00002ac837b9639b in http_client_onClose (cli=0x2ac83b72fbe0) at /tools/php7/swoole-src-swoole-1.8.4-stable/swoole_http_client.c:355

**Comment by badxpgy** [comment]
`<?php

include dirname(__FILE__) . '/Common.php';

class HttpProxy {

	/**
	 * 请求队列
	 * @var type 
	 */
	public static $requestQueue = array();
	public static $httpClientList = array();
	public static $serv = false;

	const MAX_CLIENT_CNT = 5;

	/**
	 * 初始化httpclient对像
	 * @param type $serv
	 */
	public static function Init($serv) {
		for ($i = 0; $i < self::MAX_CLIENT_CNT; $i++) {
			self::$httpClientList[$i] = new HttpClient();
		}
		self::$serv = $serv;
	}

	/**
	 * 处入队列并开始处理
	 * @param type $fd
	 * @param type $data
	 */
	public static function AddQueueAndRun($fd, $data) {
		$expTime = time() + 20;
		array_push(self::$requestQueue, array($fd, $data, $expTime));
		self::RunQueue();
	}

	/**
	 * 处理队列
	 */
	public static function RunQueue() {
		$httpClient = false;
		for ($i = 0; $i < self::MAX_CLIENT_CNT; $i++) {
			if (!self::$httpClientList[$i]->IsBusy()) {
				$httpClient = self::$httpClientList[$i];
				break;
			}
		}		
		if ($httpClient) {
			do {				
				$info = array_shift(HttpProxy::$requestQueue);
				if ($info) {
					if (HttpProxy::$serv->connection_info($info[0])) {
						//检测客户端连接是否还在
						$httpClient->Request($info[0], $info[1], $info[2]);
						return;
					}
				} else {
					return;
				}
			} while (true);
		}
	}

}

class HttpClient {

	private $client = false;

	/**
	 * 当前任务信息
	 * @var type 
	 */
	private $requestInfo = false;

	/**
	 * 检测当前是否处于处理状态
	 * @return boolean
	 */
	public function IsBusy() {
		if (!$this->client) {
			//当前还未创建连接或已被关闭
			return false;
		} else if (!$this->requestInfo) {
			//连接空闲中--
			return false;
		} else {
			if (time() > $this->requestInfo["expire"]) {
				//上次处理任务执行超时，删掉不做处理--
				$this->Reset();
				return false;
			}
		}
		return true;
	}

	/**
	 * 重置数据，清空连接数据
	 * @param type $close_client
	 */
	private function Reset() {
		$this->requestInfo = false;
		$this->client = false;
	}

	/**
	 * 创建一个swoole_http_client对像
	 */
	private function CreateClient() {
		$this->client = new swoole_http_client(Common::$Config['MFOA-Ip'], Common::$Config['MFOA-PORT']);
		$this->client->setHeaders([
			'Host' => Common::$Config['MFOA-Domain'],
			'Accept-Encoding' => 'gzip',
		]);
		$this->client->set(array('keep_alive' => 1));
		$this->client->on('close', function ($cli) {
			$this->CloseAndReset();
		});
		$this->client->on('error', function (swoole_client $socket) {
			$this->CloseAndReset();
		});
	}

	/**
	 * 关闭事件，关闭事件后，会触发新任务处理
	 */
	private function CloseAndReset() {
		echo "close1-" . $GLOBALS['work_id'] . "\r\n";
		$requestInfo = $this->requestInfo;
		$this->Reset();
		//如果断开了，检测包有没有超时，如果没有超时重新请求,只尝试一次
		if ($requestInfo && (!$requestInfo["again"]) && ($requestInfo["expire"] > time())) {
			$this->Request($requestInfo["fd"], $requestInfo["data"], $requestInfo["expire"], true);
		} else {
			HttpProxy::RunQueue();
		}
	}

	/**
	 * 接收并回复客户端,回复后会再次触发新任务处理
	 * @param type $data
	 */
	private function Receive($data) {
		$client_fd = $this->requestInfo['clientfd'];
		$fd = $this->requestInfo["fd"];
		//如果客户端已断开，就不回了
		if (HttpProxy::$serv->connection_info($fd)) {
			$package = Common::WriteMfPackage($client_fd, $data);
			HttpProxy::$serv->send($fd, $package);
		}
		$this->requestInfo = false;
		HttpProxy::RunQueue();
	}

	/**
	 * 处理请求
	 * @param type $fd
	 * @param type $data
	 * @param type $expireTime
	 * @param type $again
	 * @return type
	 */
	public function Request($fd, $data, $expireTime, $again = false) {
		
		if (!$this->client || (!$this->client->isConnected())) {
			$this->CreateClient();
		}
		$info = Common::ReadCmsPackage($data);
		if (strpos($info['url'], "http") !== false) {
			$info['url'] = substr($info['url'], strpos($info['url'], "/", 10));
		}
		if (!$info['url']) {
			$info['url'] = "/";
		}
		$this->requestInfo = array(
			"fd" => $fd,
			"data" => $data,
			"expire" => $expireTime,
			"again" => $again,
			"clientfd" => $info['fd']
		);		
		if ($info['method'] == 1) {
			$ret = $this->client->get($info['url'], function ($cli) {
				$this->Receive($cli->body);
			});
		} else {
			$ret = $this->client->post($info['url'], $info['data'], function ($cli) {
				$this->Receive($cli->body);
			});
		}
		if (!$ret) {
			$this->Reset();
			return;
		}
	}

}

$serv = new swoole_server("0.0.0.0", 9501, SWOOLE_PROCESS, SWOOLE_SOCK_TCP);
$serv->set(array(
	'worker_num' => 1,
	'dispatch_mode' => 3,
	'max_request' => 0,
	'open_length_check' => true, //打开EOF检测
	'package_length_type' => "N", //设置EOF
	'package_body_offset' => 4,
	'heartbeat_idle_time' => 600,
	'heartbeat_check_interval' => 60,
));

$serv->on('receive', function ($serv, $fd, $from_id, $data) {
	HttpProxy::AddQueueAndRun($fd, $data);
});
$serv->on('WorkerStart', function ($serv, $worker_id) {
	$GLOBALS['work_id'] = $worker_id;
	HttpProxy::Init($serv);
	global $argv;
	swoole_set_process_name(implode(' ', $argv) . ' work_pid_' . $serv->master_pid);
	/*$serv->tick(2000, function($tid) {
		echo $GLOBALS['work_id'] . "-count-:" . count(HttpProxy::$requestQueue) . PHP_EOL;
	});*/
});
$serv->on('close', function ($serv, $fd, $from_id) {
	
});
$serv->on('connect', function ($serv, $fd) {
	
});
$serv->start();
`

**Comment by matyhtf** [comment]
本地暂时无法重现，请使用最新的master分支代码进行测试。

**Comment by badxpgy** [comment]
@matyhtf 
我把测试代码简化了一下，也同时用最新版本测试了，百分之百重现

**Comment by badxpgy** [comment]
`<?php

class Server {

	private $serv;

	public function __construct() {
		$this->serv = new swoole_server("0.0.0.0", 9501);
		$this->serv->set(array(
			'worker_num' => 1, //一般设置为服务器CPU数的1-4倍  
			'dispatch_mode' => 2,
			'open_length_check' => true, //打开EOF检测
			'package_length_type' => "N", //设置EOF
			'package_body_offset' => 4,
			'heartbeat_idle_time' => 600,
			'heartbeat_check_interval' => 60,
		));
		$this->serv->on('Receive', array($this, 'onReceive'));
		$this->serv->on('WorkerStart', array($this, 'onWorkerStart'));
		$this->serv->start();
	}

	public $clients = array();

	public function Request($data, $fd) {
		$uuid = uniqid("", true);
		$client = new swoole_http_client("59.37.96.63", 80);
		$client->setHeaders([
			'Host' => "www.qq.com",
			'Accept-Encoding' => 'gzip',
		]);
		$client->on('close', function ($cli)use($uuid) {
			if (isset($this->clients[$uuid])) {
				unset($this->clients[$uuid]);
			}
		});
		$client->on('error', function (swoole_client $socket)use($uuid) {
			if (isset($this->clients[$uuid])) {
				unset($this->clients[$uuid]);
			}
		});
		$this->clients[$uuid] = $client;
		$client->get("/", function ($cli)use($data, $fd, $uuid) {
			if ($this->serv->connection_info($fd)) {
				$this->serv->send($fd, $data);
			}
		});
	}

	public function onWorkerStart($serv, $worker_id) {
		$GLOBALS['work_id'] = $worker_id;
	}

	public function onReceive(swoole_server $serv, $fd, $from_id, $data) {
		$this->Request($data, $fd);
	}

}

new Server();

`

**Comment by matyhtf** [comment]
确实存在问题，对象的引用计数错误导致提前被销毁了。已解决。
