### ISSUE TITLE
swSSL_accept: swSSL_accept() failed. Error: DH lib[5]

### ISSUE THREAD

**Issue by nosun** [swoole/swoole-src#649]
部署好的wss 也就是在ssl下的 webscoket 在页面上是正常的 但是我用了阿里云的slb转发 转发中部署的有端口健康状态监听，他会去访问我这个端口 他们的访问是非ssl的，导致服务端大量的报这个警告 

环境：centos 6.5
版本： master分支 1.8.5 beta
阿里云：slb 转发
php ：5.6

**Comment by nosun** [comment]
阿里云，检测的发包是这样的 “HEAD /HTTP/1.0\r\n\r\n"，一次发8个

**Comment by matyhtf** [comment]
SSL端口必须使用SSL协议才能访问。

**Comment by matyhtf** [comment]
你可以监听一个非SSL的明文端口。

**Comment by nosun** [comment]
关键的问题是，master进程会挂掉…

**Comment by matyhtf** [comment]
挂掉是指core dump吗，请贴出core信息。
非SSL访问SSL端口底层会报`WARNING	swSSL_accept: bad SSL client[127.0.0.1:53505]`

**Comment by matyhtf** [comment]
WebSocket的多端口监听有BUG, 请试试 `1.8.5-beta`
