### ISSUE TITLE
ubuntu + php 7 swoole_http_server 报错

### ISSUE THREAD

**Issue by kcloze** [swoole/swoole-src#654]
WARNING swFactoryProcess_dispatch: dispatch[type=10] failed, connection#9 is not active

代码：

```

$serv = new swoole_http_server("0.0.0.0", 9502);

$serv->on('Request', function ($request, $response) {
    var_dump($request->get);
    var_dump($request->post);
    var_dump($request->cookie);
    var_dump($request->files);
    var_dump($request->header);
    var_dump($request->server);

    $response->cookie("User", "Swoole");
    $response->header("X-Server", "Swoole");
    $response->end("<h1>Hello Swoole!</h1>");
});

$serv->start();

```

**Comment by matyhtf** [comment]
贴出PHP， Swoole版本信息。

**Comment by kcloze** [comment]
Linux ubuntu 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.0.4 (cli) (built: Mar 28 2016 23:43:16) ( NTS )

挺奇怪，连基本的测试都不通过，换了台机器，linux内核高一点

**Comment by kcloze** [comment]
换成低版本内核，正常了
Linux VM_179_233_centos 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by matyhtf** [comment]
使用 `strace -f -s.log php server.php` 跟踪程序的执行。
