### ISSUE TITLE
swoole-1.8.4-stable 编译后无法在PHP 7.0.5载入swoole扩展！

### ISSUE THREAD

**Issue by dsphper** [swoole/swoole-src#656]
Hi，大家好！
我在我的虚拟机中编译好swoole扩展，并加入到.ini文件中后PHP运行会爆出#错误信息。
运行`php -m`查看不到swoole扩展
我的环境信息：
PHP信息：
`PHP 7.0.5 (cli) (built: Apr  2 2016 12:34:17) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
`
Swoole版本：`swoole-1.8.4-stable`
内核信息：`Linux version 2.6.32-504.16.2.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) ) #1 SMP Wed Apr 22 06:48:29 UTC 2015
`
发行版信息：`CentOS release 6.6 (Final)
Kernel \r on an \m
`
#### 错误信息
```bash
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/swoole.so' - /usr/lib64/php/modules/swoole.so: undefined symbol: zval_used_for_init in Unknown on line 0
```
切换到`swoole-1.7.22-stable`问题解决！

**Comment by dsphper** [comment]
新

**Comment by dsphper** [comment]
沙发

**Comment by matyhtf** [comment]
指定php-config的绝对路径，然后重新编译swoole
