### ISSUE TITLE
swoole_http_server 无响应

### ISSUE THREAD

**Issue by vlike** [swoole/swoole-src#660]
使用swoole_http_server创建的http服务，
当程序出运行过程中出了问题时导致当前worker重启，会导致当前这个http请求一直没有响应，
在onWorkerError里想执行一下response->end，但发现response似乎已经被清除了，

希望当程序出问题后能返回给用户http 500 这样的错误而不是一直等待响应

**Comment by matyhtf** [comment]
将$response对象保存起来，然后捕获PHP致命错误，输出错误页面。
`onWorkerError` 是在Manager进程内执行的，没有$response对象
