### ISSUE TITLE
swoole-1.8.5-rc1 swoole_websocket_server 回调报错

### ISSUE THREAD

**Issue by tiaodeng** [swoole/swoole-src#664]
####今天拉了最新版测试websocket crash问题。

 /usr/local/servers/php7/bin/php -c /usr/local/servers/php7/etc/php.ini -v
PHP 7.0.4 (cli) (built: Mar 12 2016 14:12:16) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

swoole：
swoole-1.8.5-rc1

/data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket
/usr/local/servers/php7/bin/php -c /usr/local/servers/php7/etc/php.ini server.php
/usr/local/servers/php7/bin/php -c /usr/local/servers/php7/etc/php.ini client.php -c 10 -n 10

回调函数无法正常工作，报错如下：
server-》
PHP Warning:  Invalid callback , no array or string given in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/server.php on line 138

Warning: Invalid callback , no array or string given in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/server.php on line 138
PHP Warning:  swoole_http_server::start(): onRequest handler error in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/server.php on line 138

Warning: swoole_http_server::start(): onRequest handler error in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/server.php on line 138
PHP Warning:  swoole_http_server::start(): onMessage handler error in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/server.php on line 138

Warning: swoole_http_server::start(): onMessage handler error in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/server.php on line 138
client 1 closed

client-》
Array
(
    [c] => 10
    [n] => 10
)
PHP Warning:  swoole_client::recv(): recv() failed. Error: Resource temporarily unavailable [11] in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/WebSocketClient.php on line 113

Warning: swoole_client::recv(): recv() failed. Error: Resource temporarily unavailable [11] in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/WebSocketClient.php on line 113
PHP Notice:  Undefined property: swoole_client::$errMsg in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/WebSocketClient.php on line 116

Notice: Undefined property: swoole_client::$errMsg in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/WebSocketClient.php on line 116
Error: PHP Warning:  swoole_client::recv(): recv() failed. Error: Resource temporarily unavailable [11] in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/WebSocketClient.php on line 113

Warning: swoole_client::recv(): recv() failed. Error: Resource temporarily unavailable [11] in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/WebSocketClient.php on line 113
PHP Notice:  Undefined property: swoole_client::$errMsg in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/WebSocketClient.php on line 116

Notice: Undefined property: swoole_client::$errMsg in /data/tools/swoole-src-swoole-1.8.5-rc1/examples/websocket/WebSocketClient.php on line 116
Error: 
======
finish

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/3e55560d70cc62fd103ec65be4c54f1c0a6a843e
PHP7的问题，已经修复。
