### ISSUE TITLE
PHP Warning: swoole_http_server::start(): onOpen handler error

### ISSUE THREAD

**Issue by braveryhui** [swoole/swoole-src#667]
PHP Warning: swoole_http_server::start(): onOpen handler error in /App/banyar/swoole/banyarWebServer.php on line 42

不明白为什么开 swoole_websocket_server 提示swoole_http_server的错误 
代码如下 最后一行为42行
`
$serv = new swoole_websocket_server(SERVER_IP, 9443);
$time=date("y-m");
$com = date("d");
$dir="./data/log/".$time .'/'. $com;
if(!file_exists($dir)){
//如果不创建，递归创建
mkdir($dir,0777,true);
}
$serv->set(array(
'worker_num' => 8,
'daemonize' => true,
'max_request' => 1000,
'max_conn' => 650000,
'dispatch_mode' => 2,
'debug_mode'=> 1,
'task_worker_num'=>100,
'log_file' => $dir."/swoole.log",
'buffer_output_size' => 32 * 1024 *1024,
//'heartbeat_check_interval'=>30,
//'heartbeat_idle_time' => 60, //默认是heartbeat_check_interval的2倍,超过此设置客户端没有回应则强制断开链接
));
$serv->on('Start', array($this, 'onStart'));
$serv->on('open', array($this, 'onOpen'));
$serv->on('message', array($this, 'onMessage'));
$serv->on('Task',array($this,'onTask'));
$serv->on('Finish',array($this,'onFinish'));
$serv->on('close', array($this, 'onClose'));
#42 行 $serv->start();

**Comment by matyhtf** [comment]
请给出一个 完整的demo 程序

**Comment by braveryhui** [comment]
框架用的是swooleFramework ，server文件如下：
`
<?php
define('DEBUG', 'on');
define("WEBPATH", str_replace("\\","/", __DIR__));
define("SERVER_IP", '111.111.111.111);
require __DIR__ . '/libs/lib_config.php';
use LogServer\AbnormalOrderSender;

class WebSocket{

    private $serv;
    public function __construct() {
        $serv = new swoole_websocket_server(SERVER_IP, 9443);

        $time=date("y-m");
        $com = date("d");
        $dir="./data/log/".$time .'/'. $com;
        if(!file_exists($dir)){
            //如果不创建，递归创建
            mkdir($dir,0777,true);
        }

        $serv->set(array(
            'worker_num' => 8,
            'daemonize' => true,
            'max_request' => 1000,
            'max_conn' => 650000,
            'dispatch_mode' => 2,
            'debug_mode'=> 1,
            'task_worker_num'=>100,
            'log_file'    => $dir."/swoole.log",
            'buffer_output_size' => 32 * 1024 *1024,
            //'heartbeat_check_interval'=>30,
            //'heartbeat_idle_time' => 60, //默认是heartbeat_check_interval的2倍,超过此设置客户端没有回应则强制断开链接
        ));

        $serv->on('Start', array($this, 'onStart'));
        $serv->on('open', array($this, 'onOpenCall'));
        $serv->on('message', array($this, 'onMessageCall'));
        $serv->on('Task',array($this,'onTask'));
        $serv->on('Finish',array($this,'onFinish'));
        $serv->on('close', array($this, 'onClose'));
        $serv->start();

    }
   /* public function startListen()
    { 
        $this->serv->start();
    }
   */
    public function onStart( $serv ) {
        echo "Start\n";
        swoole_set_process_name("swoole_server");
    }

    public function onOpenCall(swoole_websocket_server $server, $request){
        $fd = $request->fd;
        echo "onClient Callled===:fd: {$fd}\n";
        if($fd == 1){
            //开启timer进行紧急派工
//            $server->tick(60000, function($id) use ($server) {
//                $server->Task('timer');
//            });
            swoole_timer_tick(60000,function($id) use ($server) {
                $server->Task('timer');
            });
        }
        $server->push($fd,json_encode(array('ip'=>SERVER_IP,'fd'=>$fd,'info'=>'onConnect OK ...','status'=>200,'inname'=>'onConnect')));

        require_once "reload.php";
        reload();
    }

    public function onMessageCall(swoole_websocket_server $server, $frame){
        $data = $frame->data;
        $fd = $frame->fd;
        echo 'onReceiveData----->'.$data."\n";

        $data = json_decode($data,true);

        if($data['inname'] == 'onConnect'){
            $server->push($fd,json_encode(array('ip'=>SERVER_IP,'fd'=>$fd,'info'=>'onConnect OK ...','status'=>200,'inname'=>'onConnect')));
            return false;
        }

        //判断逻辑
        $ComParse = model('ComParse');
        $ComParse->Index($server, $data,$fd);
    }

    public function onTask($serv, $task_id, $from_id, $data){
        echo "Task:from_id---->".$from_id."\n";
        echo "Task:task_id---->".$task_id."\n";
        if($data == 'timer'){
            $Emergency = model('Emergency');
            $Emergency->Emergency_Dispatch($serv);
        }else{
            echo "Grab_Order\n";
            sleep(10);
            //var_dump($data);
            $serv->Finish($data);
        }
    }

    public function onFinish($serv, $task_id, $data){
        //抢单完成
        $orders = model('Orders');
        $orders->Grab_Finish($serv, $task_id, $data);
    }

    /**
     * 下线时，通知所有人
     */
    public function onClose( $serv, $fd, $from_id ) {
        $orders = model('Orders');
        $orders->Online($fd,0,$serv);
        //$serv->close($fd);
        echo "onClose===:Client {$fd} closed connection\n";
    }
}

new WebSocket();
`

**Comment by braveryhui** [comment]
swoole_websocket_server.c 中也调用了swoole_http_server 

swoole_websocket_server.c 299行所在函数
`
void swoole_websocket_init(int module_number TSRMLS_DC)
{
    SWOOLE_INIT_CLASS_ENTRY(swoole_websocket_server_ce, "swoole_websocket_server", "Swoole\\WebSocket\\Server", swoole_websocket_server_methods);
    swoole_websocket_server_class_entry_ptr = sw_zend_register_internal_class_ex(&swoole_websocket_server_ce, swoole_http_server_class_entry_ptr, "swoole_http_server" TSRMLS_CC);

    SWOOLE_INIT_CLASS_ENTRY(swoole_websocket_frame_ce, "swoole_websocket_frame", "Swoole\\WebSocket\\Frame", NULL);
    swoole_websocket_frame_class_entry_ptr = zend_register_internal_class(&swoole_websocket_frame_ce TSRMLS_CC);

    REGISTER_LONG_CONSTANT("WEBSOCKET_OPCODE_TEXT", WEBSOCKET_OPCODE_TEXT_FRAME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("WEBSOCKET_OPCODE_BINARY", WEBSOCKET_OPCODE_BINARY_FRAME, CONST_CS | CONST_PERSISTENT);

    REGISTER_LONG_CONSTANT("WEBSOCKET_STATUS_CONNECTION", WEBSOCKET_STATUS_CONNECTION, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("WEBSOCKET_STATUS_HANDSHAKE", WEBSOCKET_STATUS_HANDSHAKE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("WEBSOCKET_STATUS_FRAME", WEBSOCKET_STATUS_ACTIVE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("WEBSOCKET_STATUS_ACTIVE", WEBSOCKET_STATUS_ACTIVE, CONST_CS | CONST_PERSISTENT);
}`

swoole_websocket_server.c 371行所在函数
`static PHP_METHOD(swoole_websocket_server, on)
{
    zval *callback;
    zval *event_name;

    if (SwooleGS->start > 0)
    {
        php_error_docref(NULL TSRMLS_CC, E_WARNING, "Server is running. Unable to set event callback now.");
        RETURN_FALSE;
    }

    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "zz", &event_name, &callback) == FAILURE)
    {
        return;
    }

    swServer *serv = swoole_get_object(getThis());

    char *func_name = NULL;
    if (!sw_zend_is_callable(callback, 0, &func_name TSRMLS_CC))
    {
        php_error_docref(NULL TSRMLS_CC, E_ERROR, "Function '%s' is not callable", func_name);
        efree(func_name);
        RETURN_FALSE;
    }
    efree(func_name);

    serv->listen_list->open_websocket_protocol = 1;

    if (strncasecmp("open", Z_STRVAL_P(event_name), Z_STRLEN_P(event_name)) == 0)
    {
        zend_update_property(swoole_websocket_server_class_entry_ptr, getThis(), ZEND_STRL("onOpen"), callback TSRMLS_CC);
        websocket_callbacks[0] = sw_zend_read_property(swoole_websocket_server_class_entry_ptr, getThis(), ZEND_STRL("onOpen"), 0 TSRMLS_CC);
    }
    else if (strncasecmp("message", Z_STRVAL_P(event_name), Z_STRLEN_P(event_name)) == 0)
    {
        zend_update_property(swoole_websocket_server_class_entry_ptr, getThis(), ZEND_STRL("onMessage"), callback TSRMLS_CC);
        websocket_callbacks[1] = sw_zend_read_property(swoole_websocket_server_class_entry_ptr, getThis(), ZEND_STRL("onMessage"), 0 TSRMLS_CC);
    }
    else
    {
        zval *obj = getThis();
        sw_zend_call_method_with_2_params(&obj, swoole_http_server_class_entry_ptr, NULL, "on", &return_value, event_name, callback);
    }
}
`

**Comment by braveryhui** [comment]
@matyhtf  这个问题 如果用官方的webscoket_server 就没问题 比如这个demo就没有问题 ,不明白为什么1.8.4可以但是1.8.5用楼上的代码就用不了 
<?php
namespace StatsCenter;
use Swoole;
class workOrderServer
{
	const PORT= 9906;
	const EOF="\r\n";
        protected $serv;
	function run($_setting=array())
	{
	    $serv = new \swoole_websocket_server("139.129.192.246", self::PORT);
	    $serv->set(array(
		'daemonize'=>false,
	    ));
	    $serv->on('Open',array($this,'onOpen'));
	    $serv->on('Message',array($this,'onMessage'));
	    $serv->on('Close',array($this,'onClose'));
	    $this->serv=$serv;
	    $this->serv->start();
	}
	function onOpen($server, $req)
	{        swoole_set_process_name("workOrderServer");
		echo "connection open: ".$req->fd;
	}
	function onMessage($server, $frame)
	{
		echo "message: ".$frame->data;
		$msgArray = explode("|",$frame->data);
		var_dump($msgArray);
		switch ($msgArray[0]) {
			case 'HandleWorkOrder':{
					HandleWorkOrder\HandleAbnormalOrder::handleOrder($msgArray[1],$msgArray[2]);
			}
				break;
			case 'HandleServiceOrder':{
				  HandleWorkOrder\HandleServiceOrder::handleOrder($msgArray);
			}
				break;
			default:
				break;
		}

    		// $server->push($frame->fd, json_encode(["hello", "world"]));
	}
	function onClose($server, $fd)
	{
		echo "connection close: ".$fd;
	}
}

**Comment by matyhtf** [comment]
PHP7的问题，已经修复。

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/3e55560d70cc62fd103ec65be4c54f1c0a6a843e

**Comment by braveryhui** [comment]
@matyhtf  谢谢！
