### ISSUE TITLE
swoole http async client 连接失败的情况下没有调用 callback

### ISSUE THREAD

**Issue by roxma** [swoole/swoole-src#675]
测试代码，9929端口没有部署任何服务，所以应该失败才对，可是没有调用我的 callback，我怎么能检测到连接失败？

```
<?php

$reqClient = new swoole_http_client("127.0.0.1", 9929, 0);
$callback = function($cli) {
  var_dump($cli);
};
$reqClient->get("/", $callback);

?>
```

BTW，   swoole_http_client 可以设置超时吗，我看文档里面没有。。？

**Comment by roxma** [comment]
更新下测试代码，on errer 也是不行
···
[mayuanpeng@196sandbox http_async_proxy]$ cat http_hello_server.php 
<?php

$cli = new swoole_http_client("127.0.0.1", 9929, 0);
$cli->set(
    array("timeout" => 1)
);
$callback = function($cli) {
    echo "callback";
};
$cli->on("error",function($cli) {
    echo "error\n";
});
$cli->on("close",function($cli) {
    echo "close\n";
});
$cli->get("/", $callback);


?>
[mayuanpeng@196sandbox http_async_proxy]$ php http_hello_server.php 

···

**Comment by matyhtf** [comment]
感谢反馈，底层错误的逻辑导致 `onError` 回调未被执行，已修复。
