### ISSUE TITLE
http server中，worker进程halt后应该自动关闭socket

### ISSUE THREAD

**Issue by huye** [swoole/swoole-src#681]
之前试了下手，在worker进程出错中止后socket没有关闭，服务端这个工作进程都退出了，浏览器还在那死等，希望修复这个问题，能在子进程异常退出时同时把这个连接也关闭了

**Comment by badxpgy** [comment]
你试试nginx，访问时直接把nginx kill掉，应该也会有同样问题吧，这个跟swoole应该没关系吧。

**Comment by huye** [comment]
你只看nginx为什么不看看apache呢，nginx用的是cgi，swoole又没用cgi。这本来就是bug，为什么你会这么认为？

**Comment by shenzhe** [comment]
这个用心跳，可一定程度是缓解。
worker出错，会有worker_error的事件回调，你也可以在这里做相关的操作。
比如，onRequest的时候，把request存起起，在收到worker error的时候，遍历发送end或close

**Comment by matyhtf** [comment]
默认使用PROCESS模式，连接是在master进程中维持的，Worker进程退出不会关闭连接。你可以使用register_shutdown_function+error_get_last，捕获Worker进程退出的致命错误事件，然后调用 $resp->end 将错误信息发给浏览器。
