### ISSUE TITLE
浏览器访问有问题

### ISSUE THREAD

**Issue by dada20042030** [swoole/swoole-src#682]
swoole 1.7.19版本可以在浏览器正常运行，
swoole 1.7.20以上版本不能,浏览器返回, 返回192.168.1.123 未发送任何数据

测试代码:

server.php

$serv = new swoole_server("0.0.0.0", 9502);
$serv->set(array('task_worker_num' => 4));
$serv->on('Receive', function($serv, $fd, $from_id, $data) {
    $task_id = $serv->task("Async");
    echo "Dispath AsyncTask: id=$task_id\n";
});
$serv->on('Task', function ($serv, $task_id, $from_id, $data) {
    echo "New AsyncTask[id=$task_id]".PHP_EOL;
    $serv->finish("$data -> OK");
});
$serv->on('Finish', function ($serv, $task_id, $data) {
    echo "AsyncTask[$task_id] Finish: $data".PHP_EOL;
});
$serv->start();

client.php
`$client = new swoole_client(SWOOLE_SOCK_TCP);

$client->connect('127.0.0.1', 9502, 1);
$client->send("123");`

访问
http://192.168.123/swoole/client.php

**Comment by matyhtf** [comment]
请使用最新的 `1.8.5` 版本。
