### ISSUE TITLE
1.8.5 Connection.c:201 段错误

### ISSUE THREAD

**Issue by koolob** [swoole/swoole-src#684]
GDB信息如下：

Program terminated with signal 11, Segmentation fault.
#0  swConnection_get_port (conn=0x0) at swoole-1.8.5/src/network/Connection.c:201
201	    if (conn->socket_type == SW_SOCK_TCP)

没有更多的信息了。错误来自worker进程。

代码使用了多协议监听，主服务是websocket，额外监听了一个TCP。

worker进程做的事就是接收请求后同步向redis放一条数据，以及将数据传递给task进程。

**Comment by matyhtf** [comment]
贴出完整的gdb信息

**Comment by matyhtf** [comment]
另外，是否可以稳定重现，如果可以请贴一个PHP的demo程序。

**Comment by koolob** [comment]
#0  swConnection_get_port (conn=0x0) at /home/dong/swoole/swoole-1.8.5/src/network/Connection.c:201
#1  0x00007f58dddbf4e0 in zim_swoole_server_connection_info (ht=<value optimized out>, return_value=0x1f81390, return_value_ptr=<value optimized out>, this_ptr=<value optimized out>,
    return_value_used=<value optimized out>) at /home/dong/swoole/swoole-1.8.5/swoole_server.c:2603
#2  0x00000000005d55c9 in dtrace_execute_internal ()
#3  0x0000000000664575 in ?? ()
#4  0x0000000000654048 in execute_ex ()
#5  0x00000000005d56fe in dtrace_execute_ex ()
#6  0x0000000000664be4 in ?? ()
#7  0x0000000000654048 in execute_ex ()
#8  0x00000000005d56fe in dtrace_execute_ex ()
#9  0x0000000000664be4 in ?? ()
#10 0x0000000000654048 in execute_ex ()
#11 0x00000000005d56fe in dtrace_execute_ex ()
#12 0x00000000005d8163 in zend_call_function ()
#13 0x00000000005d8df0 in call_user_function_ex ()
#14 0x00007f58dddc214f in php_swoole_onClose (serv=<value optimized out>, info=<value optimized out>) at /home/dong/swoole/swoole-1.8.5/swoole_server.c:1212
#15 0x00007f58ddde6237 in swFactoryProcess_end (factory=0x7f58d50b5430, fd=<value optimized out>) at /home/dong/swoole/swoole-1.8.5/src/factory/FactoryProcess.c:294
#16 0x00007f58dddf6d37 in swWorker_onTask (factory=0x7f58d50b5430, task=0x7fff526b8530) at /home/dong/swoole/swoole-1.8.5/src/network/Worker.c:253
#17 0x00007f58dddf72bb in swWorker_onPipeReceive (reactor=<value optimized out>, event=0x7fff526ba5a0) at /home/dong/swoole/swoole-1.8.5/src/network/Worker.c:542
#18 0x00007f58ddde92e1 in swReactorEpoll_wait (reactor=0x7f58d51f7000, timeo=<value optimized out>) at /home/dong/swoole/swoole-1.8.5/src/reactor/ReactorEpoll.c:258
#19 0x00007f58dddf8083 in swWorker_loop (factory=<value optimized out>, worker_id=<value optimized out>) at /home/dong/swoole/swoole-1.8.5/src/network/Worker.c:489
#20 0x00007f58dddf5140 in swManager_spawn_worker (factory=0x7f58d50b5430, worker_id=106) at /home/dong/swoole/swoole-1.8.5/src/network/Manager.c:682
#21 0x00007f58dddf5bf9 in swManager_start (factory=0x7f58d50b5430) at /home/dong/swoole/swoole-1.8.5/src/network/Manager.c:135
#22 0x00007f58ddde6502 in swFactoryProcess_start (factory=0x7f58d50b5430) at /home/dong/swoole/swoole-1.8.5/src/factory/FactoryProcess.c:86
#23 0x00007f58dddebece in swServer_start (serv=0x7f58d50b5000) at /home/dong/swoole/swoole-1.8.5/src/network/Server.c:634
#24 0x00007f58dddd1fb9 in zim_swoole_http_server_start (ht=<value optimized out>, return_value=0x7f58e42697f8, return_value_ptr=<value optimized out>, this_ptr=0x7f58e4266238,
    return_value_used=<value optimized out>) at /home/dong/swoole/swoole-1.8.5/swoole_http_server.c:1677
#25 0x00000000005d55c9 in dtrace_execute_internal ()
#26 0x0000000000664575 in ?? ()
#27 0x0000000000654048 in execute_ex ()
#28 0x00000000005d56fe in dtrace_execute_ex ()
#29 0x00000000005e4e4c in zend_execute_scripts ()
#30 0x00000000005832ba in php_execute_script ()
#31 0x000000000068c663 in ?? ()
#32 0x000000000068ce68 in ?? ()
#33 0x000000324461ed5d in __libc_start_main () from /lib64/libc.so.6
#34 0x0000000000422d29 in _start ()

**Comment by matyhtf** [comment]
已修复。
