### ISSUE TITLE
swReactorThread_send2worker (data=0x7fa513ffca98, len=118, target_worker_id=<value optimized out>)master突然挂掉

### ISSUE THREAD

**Issue by ht-kahn** [swoole/swoole-src#686]
Program terminated with signal 11, Segmentation fault.
#0  swReactorThread_send2worker (data=0x7fa513ffca98, len=118, target_worker_id=<value optimized out>)
    at /root/swoole-src-swoole-1.8.5-stable/src/network/ReactorThread.c:477
477	        int pipe_fd = worker->pipe_master;
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.23-13.el6_3.1.x86_64 freetype-2.3.11-15.el6_6.1.x86_64 glibc-2.12-1.166.el6_7.7.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-42z1.el6_7.x86_64 libcom_err-1.41.12-22.el6.x86_64 libcurl-7.19.7-46.el6.x86_64 libidn-1.18-2.el6.x86_64 libselinux-2.0.94-5.8.el6.x86_64 libssh2-1.4.2-1.el6.x86_64 libxml2-2.7.6-20.el6_7.1.x86_64 nspr-4.10.6-1.el6_5.x86_64 nss-3.16.1-4.el6_5.x86_64 nss-softokn-freebl-3.14.3-10.el6_5.x86_64 nss-util-3.16.1-1.el6_5.x86_64 openldap-2.4.23-34.el6_5.1.x86_64 openssl-1.0.1e-42.el6_7.4.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) where
#0  swReactorThread_send2worker (data=0x7fa513ffca98, len=118, target_worker_id=<value optimized out>)
    at /root/swoole-src-swoole-1.8.5-stable/src/network/ReactorThread.c:477
#1  0x00007fa544c8ca53 in swReactorThread_dispatch (conn=0x7fa53fe080f8, 
    data=0x7fa528420004 "\001\001{\"data\":{\"playerId\":-1,\"token\":\"\"},\"sign\":\"b31d71589e27bf7628ad71367828b064\",\"unique_id\":1,\"msgId\":1001}n: Upgrade\r\nSec-WebSocket-Key: LtiHTG1fgKzbMf8fmDdyNg==\r\nOrigin: http://127.0.0.1\r\nSec-We"..., 
    length=<value optimized out>) at /root/swoole-src-swoole-1.8.5-stable/src/network/ReactorThread.c:1305
#2  0x00007fa544c93ad5 in swPort_websocket_onPackage (conn=0x7fa53fe080f8, 
    data=0x7fa528420000 "\201\350\346\276\001\001{\"data\":{\"playerId\":-1,\"token\":\"\"},\"sign\":\"b31d71589e27bf7628ad71367828b064\",\"unique_id\":1,\"msgId\":1001}n: Upgrade\r\nSec-WebSocket-Key: LtiHTG1fgKzbMf8fmDdyNg==\r\nOrigin: http://127.0.0.1\r\nSe"..., length=<value optimized out>) at /root/swoole-src-swoole-1.8.5-stable/src/network/Port.c:197
#3  0x00007fa544c96b19 in swProtocol_recv_check_length (protocol=0x7fa543d023a8, conn=0x7fa53fe080f8, buffer=0x7fa52841b060)
    at /root/swoole-src-swoole-1.8.5-stable/src/protocol/Base.c:157
#4  0x00007fa544c93b7e in swPort_onRead_check_length (reactor=0x7fa543d04f6c, port=0x7fa543d022e0, event=0x7fa513ffecc0)
    at /root/swoole-src-swoole-1.8.5-stable/src/network/Port.c:338
#5  0x00007fa544c84ba1 in swReactorEpoll_wait (reactor=0x7fa543d04f6c, timeo=<value optimized out>)
    at /root/swoole-src-swoole-1.8.5-stable/src/reactor/ReactorEpoll.c:258
#6  0x00007fa544c8daa0 in swReactorThread_loop_stream (param=<value optimized out>)
    at /root/swoole-src-swoole-1.8.5-stable/src/network/ReactorThread.c:1160
#7  0x00007fa54b53aaa1 in start_thread () from /lib64/libpthread.so.0
#8  0x00000035694e893d in clone () from /lib64/libc.so.6

**Comment by fznply** [comment]
这种情况是发生在程序刚启动的时候吗？一般来说worker进程未完成启动可能会遇到这样的情况。

**Comment by matyhtf** [comment]
goto #734
