### ISSUE TITLE
启用http2的时候应该自动启用openssl

### ISSUE THREAD

**Issue by huye** [swoole/swoole-src#700]
#error "Enable http2 support, require --enable-openssl."

这个错误提示我觉得没必要吧，你都知道http2是要ssl的，为什么不自动启用，还一定要--enable-openssl呢，我觉得这个可以优化。。。

**Comment by matyhtf** [comment]
感谢你的建议，这个问题无关紧要。增加此逻辑反而会造成swoole的逻辑混乱，带来BUG
