### ISSUE TITLE
多协议监听 (websock && tcp) tcp收到不到消息

### ISSUE THREAD

**Issue by kaykay012** [swoole/swoole-src#701]
多协议监听，websocket的message可以收到消息 而 tcp的receive收不到？ php5.5.34 && swoole-1.8.[ 3 - 5 ] 都有这个问题 而 swoole-1.8.2 却没有问题

**Comment by matyhtf** [comment]
需要调用 set 方法 覆盖掉主服务器的协议设置。否则会继承主服务器的设置，也会按照WebSocket处理。

**Comment by ZavierZh** [comment]
set 那些参数?
