### ISSUE TITLE
swoole_http_server非标准upload格式导致worker coredump

### ISSUE THREAD

**Issue by qysf12345** [swoole/swoole-src#703]
![image](https://cloud.githubusercontent.com/assets/19568341/15534412/3dc97d94-229b-11e6-9b90-b8d06e09dc83.png)
如图，向swoole_http_server 提交 worker还没触发onrequest 就coredump了 。
1.8.4和1.8.5 试用均crash了

**Comment by matyhtf** [comment]
请将测试的代码贴出来。

**Comment by qysf12345** [comment]
![image](https://cloud.githubusercontent.com/assets/19568341/15538612/e56f0dc0-22af-11e6-9144-3a8fb37de5d6.png)
就是调用 下函数

**Comment by qysf12345** [comment]
<?php
** php 发送流文件
* @param  String  $url  接收的路径
* @param  String  $file 要发送的文件
* @return boolean
*/
function sendStreamFile($url, $file){

    if(file_exists($file)){

        $opts = array(
            'http' => array(
                'method' => 'POST',
          //      'header' => 'content-type:application/octet-stream',
                'header' => 'content-type:multipart/form-data',
                'content' => file_get_contents($file)
            )
        );

        $context = stream_context_create($opts);
        $response = file_get_contents($url, false, $context);
        return $response;

    }else{
        return false;
    }

}

$ret = sendStreamFile('http://localhost:9522/wdelivery', 't.php');
var_dump($ret);

exit();

**Comment by qysf12345** [comment]
/** php 发送流文件
* @param  String  $url  接收的路径
* @param  String  $file 要发送的文件
* @return boolean
*/
function sendStreamFile($url, $file){

    if(file_exists($file)){

        $opts = array(
            'http' => array(
                'method' => 'POST',
          //      'header' => 'content-type:application/octet-stream',
                'header' => 'content-type:multipart/form-data',
                'content' => file_get_contents($file)
            )
        );

        $context = stream_context_create($opts);
        $response = file_get_contents($url, false, $context);
        return $response;

    }else{
        return false;
    }

}

$ret = sendStreamFile('http://localhost:9522/wdelivery', 't.php');
var_dump($ret);

exit();

**Comment by matyhtf** [comment]
已修复。因为是错误的form-data，底层解释时发生了异常。
