### ISSUE TITLE
could swoole support current existing rpc framework like dubbo etc ?

### ISSUE THREAD

**Issue by bwzhang2011** [swoole/swoole-src#708]
we're encountering the problem that how to best integrate the php for front side and the java for back-end services. as the back-end services are based on distributed rpc framework like dubbo, so the php should have the ability to access the register center like zookeeper and so it is the way that php could access the special protocol for the rpc framework. we knew that swoole did a lot of work for enhancement for php, but how could it support like the title decribed ? any way for such extension.

**Comment by lscgzwd** [comment]
PHP support zookeeper, if dubbo supply http rest rpc,  php can support it, but if you want support dubbo tcp service, maybe can not . And I want php support dubbo , rocketmq also, because in my company, the OP just supply the dubbo with zookeeper and rocketmq.

**Comment by matyhtf** [comment]
Swoole is just a networking communication engine. This is an application-level code to do. You can use php code to implement these logic.

There is a rpc server and client that you can use it. 

https://github.com/swoole/framework/blob/master/examples/soa_server.php
https://github.com/swoole/framework/blob/master/examples/soa_client.php
