### ISSUE TITLE
swFactoryProcess_finish (ERROR 1004): because session#227378 is closed.

### ISSUE THREAD

**Issue by minr** [swoole/swoole-src#710]
[2016-05-31 23:59:50 *13261.15]	ERROR	swFactoryProcess_finish (ERROR 1004): send 195 byte failed, because session#227378 is closed.

出现大量如上错误，master进程存在，但是已经无法正常工作。

环境是：

swoole 1.8.4
php 5.6.16

swoole论坛上也有相关信息，但是却没人提出解决方案。

http://group.swoole.com/question/106324

**Comment by matyhtf** [comment]
这是连接已经关闭了，无法发送数据。

**Comment by meijing0114** [comment]
@range 我这边也遇到了同样的情况，php5.5.30 swoole1.8.4 
上游是nginx，客户端连接关闭是因为达到了nginx的超时时间，但是为什么在这么长的时间里swoole没有把请求处理完的原因是什么呢？

**Comment by matyhtf** [comment]
没有处理完可能是你的Worker进程数量少，无法处理太多请求导致的。也可能是你的PHP代码确实很慢
