### ISSUE TITLE
ab -n 100000 -c 100 http://xx.xxx.com http服务的时候出现警告

### ISSUE THREAD

**Issue by hppking** [swoole/swoole-src#711]
WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=11
gdb:
#0  zend_mm_free_heap (ptr=0x2f46950, heap=0x7f93c5800040) at /mnt/php-7.0.2/Zend/zend_alloc.c:1400
#1  _efree (ptr=0x2f46950) at /mnt/php-7.0.2/Zend/zend_alloc.c:2458
#2  0x00007f93bee4af75 in _mongoc_counters_cleanup ()
    at /mnt/mongodb-1.1.3/src/libmongoc/src/mongoc/mongoc-counters.c:132
#3  0x00007f93c8eddbb0 in pthread_once () from /lib64/libpthread.so.0
#4  0x00007f93cc400a1a in _dl_fini () from /lib64/ld-linux-x86-64.so.2
#5  0x00007f93c9328e69 in __run_exit_handlers () from /lib64/libc.so.6
#6  0x00007f93c9328eb5 in exit () from /lib64/libc.so.6
#7  0x00007f93bebcc6c7 in swManager_spawn_worker (factory=0x3285350, worker_id=0)
    at /mnt/swoole-src-swoole-1.8.4-stable/src/network/Manager.c:683
#8  0x00007f93bebccad7 in swManager_start (factory=factory@entry=0x3285350)
    at /mnt/swoole-src-swoole-1.8.4-stable/src/network/Manager.c:135
#9  0x00007f93bebbe662 in swFactoryProcess_start (factory=0x3285350)
    at /mnt/swoole-src-swoole-1.8.4-stable/src/factory/FactoryProcess.c:86
#10 0x00007f93bebc4ba9 in swServer_start (serv=serv@entry=0x3284f20)
    at /mnt/swoole-src-swoole-1.8.4-stable/src/network/Server.c:620
#11 0x00007f93bebaf317 in zim_swoole_http_server_start (execute_data=0x7f93c58134e0, 
    return_value=0x7f93c58134c0) at /mnt/swoole-src-swoole-1.8.4-stable/swoole_http_server.c:1674
#12 0x00000000008164d3 in ZEND_DO_FCALL_SPEC_HANDLER () at /mnt/php-7.0.2/Zend/zend_vm_execute.h:842
#13 0x00000000007da92b in execute_ex (ex=<optimized out>) at /mnt/php-7.0.2/Zend/zend_vm_execute.h:414
#14 0x00000000007933d7 in zend_call_function (fci=0x7ffffa5b74e0, fci_cache=0x7f93ba407068)
    at /mnt/php-7.0.2/Zend/zend_execute_API.c:860
#15 0x00007f93bdb5549e in zephir_call_user_func_array_noex ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#16 0x00007f93bdc1a25f in zim_Phalcon_Cli_Dispatcher_callActionMethod ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#17 0x00007f93bdb57407 in zephir_call_function_opt ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#18 0x00007f93bdb546cf in zephir_call_user_function ()
---Type <return> to continue, or q <return> to quit---
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#19 0x00007f93bdb551ae in zephir_call_class_method_aparams ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#20 0x00007f93bdbb0be2 in zim_Phalcon_Dispatcher__dispatch ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#21 0x00007f93bdb57407 in zephir_call_function_opt ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#22 0x00007f93bdb546cf in zephir_call_user_function ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#23 0x00007f93bdb551ae in zephir_call_class_method_aparams ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#24 0x00007f93bdbae6e8 in zim_Phalcon_Dispatcher_dispatch ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#25 0x00007f93bdb57407 in zephir_call_function_opt ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#26 0x00007f93bdb546cf in zephir_call_user_function ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#27 0x00007f93bdb551ae in zephir_call_class_method_aparams ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#28 0x00007f93bdc16262 in zim_Phalcon_Cli_Console_handle ()
   from /usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
#29 0x00000000008164d3 in ZEND_DO_FCALL_SPEC_HANDLER () at /mnt/php-7.0.2/Zend/zend_vm_execute.h:842
#30 0x00000000007da92b in execute_ex (ex=<optimized out>) at /mnt/php-7.0.2/Zend/zend_vm_execute.h:414
#31 0x0000000000821761 in zend_execute (op_array=0x7f93c587f000, op_array@entry=0x7f93ba404ab0, 
    return_value=return_value@entry=0x7f93c5813120) at /mnt/php-7.0.2/Zend/zend_vm_execute.h:458
#32 0x00000000007a0898 in zend_execute_scripts (type=type@entry=8, retval=0x7f93c5813120, retval@entry=0x0, 
    file_count=file_count@entry=3) at /mnt/php-7.0.2/Zend/zend.c:1427
#33 0x00000000007458f0 in php_execute_script (primary_file=primary_file@entry=0x7ffffa5bade0)
    at /mnt/php-7.0.2/main/main.c:2471
---Type <return> to continue, or q <return> to quit---
#34 0x0000000000823174 in do_cli (argc=3, argv=0x2eb7d50) at /mnt/php-7.0.2/sapi/cli/php_cli.c:974
#35 0x000000000043f9d5 in main (argc=3, argv=0x2eb7d50) at /mnt/php-7.0.2/sapi/cli/php_cli.c:1345

**Comment by matyhtf** [comment]
MongoDB Client 崩溃了，你可能需要反馈给Mongo官方，或者尝试升级客户端版本。
