### ISSUE TITLE
coredump 

### ISSUE THREAD

**Issue by lscgzwd** [swoole/swoole-src#713]
> Core was generated by `php swoole.php work process           '.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000aa7d01 in _zval_dtor_func (zvalue=0x7ffc1cbf8b20, 
    __zend_filename=0x10d41b0 "/root/php-5.6.22/Zend/zend_object_handlers.c", 
    __zend_lineno=599) at /root/php-5.6.22/Zend/zend_variables.c:36
36				CHECK_ZVAL_STRING_REL(zvalue);
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.23-15.el6_6.2.x86_64 glibc-2.12-1.192.el6.x86_64 hiredis-0.10.1-3.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-57.el6.x86_64 libcom_err-1.41.12-22.el6.x86_64 libcurl-7.19.7-52.el6.x86_64 libgcc-4.4.7-17.el6.x86_64 libicu-4.2.1-14.el6.x86_64 libidn-1.18-2.el6.x86_64 libmcrypt-2.5.8-9.el6.x86_64 libpng-1.2.49-2.el6_7.x86_64 libselinux-2.0.94-7.el6.x86_64 libssh2-1.4.2-2.el6_7.1.x86_64 libstdc++-4.4.7-17.el6.x86_64 libxml2-2.7.6-21.el6.x86_64 nspr-4.11.0-1.el6.x86_64 nss-3.21.0-8.el6.x86_64 nss-softokn-freebl-3.14.3-23.el6_7.x86_64 nss-util-3.21.0-2.el6.x86_64 openldap-2.4.40-12.el6.x86_64 openssl-1.0.1e-48.el6_8.1.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x0000000000aa7d01 in _zval_dtor_func (zvalue=0x7ffc1cbf8b20, 
    __zend_filename=0x10d41b0 "/root/php-5.6.22/Zend/zend_object_handlers.c", 
    __zend_lineno=599) at /root/php-5.6.22/Zend/zend_variables.c:36
#1  0x0000000000ae3069 in _zval_dtor (zvalue=0x7ffc1cbf8b20, 
    __zend_filename=0x10d41b0 "/root/php-5.6.22/Zend/zend_object_handlers.c", 
    __zend_lineno=599) at /root/php-5.6.22/Zend/zend_variables.h:35
#2  0x0000000000ae517d in zend_std_write_property (object=0x7fc42e2b90b8, 
    member=0x7fc42e269e58, value=0x2fbddd8, key=0x7fc42e269e58)
    at /root/php-5.6.22/Zend/zend_object_handlers.c:599
#3  0x0000000000aee140 in zend_assign_to_object (retval=0x0, object_ptr=0x146b680, 
    property_name=0x7fc42e269e58, value_type=16, value_op=0x7fc42e266e78, 
    execute_data=0x7fc434a69778, opcode=136, key=0x7fc42e269e58)
    at /root/php-5.6.22/Zend/zend_execute.c:769
#4  0x0000000000b35bc5 in ZEND_ASSIGN_OBJ_SPEC_UNUSED_CONST_HANDLER (
    execute_data=0x7fc434a69778) at /root/php-5.6.22/Zend/zend_vm_execute.h:25532
#5  0x0000000000af1343 in execute_ex (execute_data=0x7fc434a69778)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:363
#6  0x0000000000af13c6 in zend_execute (op_array=0x7fc42e24ec58)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:388
#7  0x0000000000a95cb8 in zend_call_function (fci=0x7ffc1cbf8e90, fci_cache=0x7ffc1cbf8d10)
    at /root/php-5.6.22/Zend/zend_execute_API.c:829
#8  0x0000000000a94ede in call_user_function_ex (function_table=0x2b12770, object_pp=0x0, 
    function_name=0x7fc42e24ca88, retval_ptr_ptr=0x7ffc1cbf8f38, param_count=2, 
    params=0x7ffc1cbf8f20, no_separation=0, symbol_table=0x0)
    at /root/php-5.6.22/Zend/zend_execute_API.c:617
#9  0x00007fc42e812d35 in http_onReceive (serv=0x2ce6c90, req=0x7ffc1cbf9288)
    at /root/swoole-src/swoole_http_server.c:1183
#10 0x00007fc42e8509a5 in swWorker_onTask (factory=0x2ce70c0, task=0x7ffc1cbf9288)
    at /root/swoole-src/src/network/Worker.c:192
#11 0x00007fc42e8351f1 in swFactory_dispatch (factory=0x2ce70c0, task=0x7ffc1cbf9280)
    at /root/swoole-src/src/factory/Factory.c:65
#12 0x00007fc42e84baf1 in swReactorThread_dispatch (conn=0x7fc42bfb1a60, 
    data=0x2dc7000 "GET /staff/list?test=569620096733945907 HTTP/1.1\r\nHost: 192.168.2.3:9501\r\nConnection: keep-alive\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.26"..., length=495)
    at /root/swoole-src/src/network/ReactorThread.c:1289
#13 0x00007fc42e855456 in swPort_onRead_http (reactor=0x2ce7508, port=0x7fc42e3cc2e0, 
    event=0x7ffc1cbfd460) at /root/swoole-src/src/network/Port.c:477
#14 0x00007fc42e84a2c8 in swReactorThread_onRead (reactor=0x2ce7508, event=0x7ffc1cbfd460)
---Type <return> to continue, or q <return> to quit---
    at /root/swoole-src/src/network/ReactorThread.c:790
#15 0x00007fc42e83c17a in swReactorEpoll_wait (reactor=0x2ce7508, timeo=0x7ffc1cbfd4e0)
    at /root/swoole-src/src/reactor/ReactorEpoll.c:258
#16 0x00007fc42e84d0b1 in swReactorProcess_loop (pool=0x7fc42e3cc240, worker=0x7ffc1cbfd560)
    at /root/swoole-src/src/network/ReactorProcess.c:374
#17 0x00007fc42e84c437 in swReactorProcess_start (serv=0x2ce6c90)
    at /root/swoole-src/src/network/ReactorProcess.c:102
#18 0x00007fc42e83f6d8 in swServer_start (serv=0x2ce6c90)
    at /root/swoole-src/src/network/Server.c:643
#19 0x00007fc42e8152c9 in zim_swoole_http_server_start (ht=0, return_value=0x7fc42e2ba590, 
    return_value_ptr=0x7fc434a686f8, this_ptr=0x7fc42e2ba9e8, return_value_used=0)
    at /root/swoole-src/swoole_http_server.c:1621
#20 0x0000000000af1cdd in zend_do_fcall_common_helper_SPEC (execute_data=0x7fc434a68d90)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:558
#21 0x0000000000af24b8 in ZEND_DO_FCALL_BY_NAME_SPEC_HANDLER (execute_data=0x7fc434a68d90)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:693
#22 0x0000000000af1343 in execute_ex (execute_data=0x7fc434a68d90)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:363
#23 0x0000000000af13c6 in zend_execute (op_array=0x7fc434a9d910)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:388
#24 0x0000000000aab9ad in zend_execute_scripts (type=8, retval=0x0, file_count=3)
    at /root/php-5.6.22/Zend/zend.c:1341
#25 0x0000000000a11522 in php_execute_script (primary_file=0x7ffc1cc00e80)
    at /root/php-5.6.22/main/main.c:2613
#26 0x0000000000b62fdd in do_cli (argc=3, argv=0x2b11b50)
    at /root/php-5.6.22/sapi/cli/php_cli.c:994
#27 0x0000000000b64072 in main (argc=3, argv=0x2b11b50)
    at /root/php-5.6.22/sapi/cli/php_cli.c:1378

**Comment by matyhtf** [comment]
已迁移至另外一个issue #716
