### ISSUE TITLE
coredump 

### ISSUE THREAD

**Issue by lscgzwd** [swoole/swoole-src#714]
#0  0x0000000000ad8256 in zval_mark_grey (pz=0x20ffab7)
    at /root/php-5.6.22/Zend/zend_gc.c:420
#1  0x0000000000ad82b5 in zval_mark_grey (pz=0x20fe620)
    at /root/php-5.6.22/Zend/zend_gc.c:427
#2  0x0000000000ad81d1 in zval_mark_grey (pz=0x2442208)
    at /root/php-5.6.22/Zend/zend_gc.c:402
#3  0x0000000000ad81d1 in zval_mark_grey (pz=0x7fffec5707f8)
    at /root/php-5.6.22/Zend/zend_gc.c:402
#4  0x0000000000ad81d1 in zval_mark_grey (pz=0x7fffec5725d8)
    at /root/php-5.6.22/Zend/zend_gc.c:402
#5  0x0000000000ad82b5 in zval_mark_grey (pz=0x7fffec51f3e8)
    at /root/php-5.6.22/Zend/zend_gc.c:427
#6  0x0000000000ad81d1 in zval_mark_grey (pz=0x7fffec50f350)
    at /root/php-5.6.22/Zend/zend_gc.c:402
#7  0x0000000000ad858f in gc_mark_roots () at /root/php-5.6.22/Zend/zend_gc.c:496
#8  0x0000000000ad9184 in gc_collect_cycles () at /root/php-5.6.22/Zend/zend_gc.c:790
#9  0x0000000000ad76ee in gc_zval_possible_root (zv=0x24aafd8)
    at /root/php-5.6.22/Zend/zend_gc.c:163
#10 0x0000000000a93047 in gc_zval_check_possible_root (z=0x24aafd8)
    at /root/php-5.6.22/Zend/zend_gc.h:183
#11 0x0000000000a931ec in i_zval_ptr_dtor (zval_ptr=0x24aafd8, 
    __zend_filename=0x10d00b0 "/root/php-5.6.22/Zend/zend_variables.c", __zend_lineno=188)
    at /root/php-5.6.22/Zend/zend_execute.h:86
#12 0x0000000000a943e6 in _zval_ptr_dtor (zval_ptr=0x3014460, 
    __zend_filename=0x10d00b0 "/root/php-5.6.22/Zend/zend_variables.c", __zend_lineno=188)
    at /root/php-5.6.22/Zend/zend_execute_API.c:424
#13 0x0000000000aa8278 in _zval_ptr_dtor_wrapper (zval_ptr=0x3014460)
    at /root/php-5.6.22/Zend/zend_variables.c:188
#14 0x0000000000abc27d in i_zend_hash_bucket_delete (ht=0x30113b0, p=0x3014448)
    at /root/php-5.6.22/Zend/zend_hash.c:182
#15 0x0000000000abdc91 in zend_hash_del_key_or_index (ht=0x30113b0, arKey=0x0, nKeyLength=0, 
    h=25, flag=1) at /root/php-5.6.22/Zend/zend_hash.c:526
#16 0x0000000000b60029 in ZEND_UNSET_DIM_SPEC_CV_CV_HANDLER (execute_data=0x7ffff6331ab0)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:41168
#17 0x0000000000af1343 in execute_ex (execute_data=0x7ffff6331ab0)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:363
#18 0x0000000000af13c6 in zend_execute (op_array=0x17b8098)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:388
#19 0x0000000000a95cb8 in zend_call_function (fci=0x7fffffff5ee0, fci_cache=0x7fffffff5eb0)
---Type <return> to continue, or q <return> to quit---
    at /root/php-5.6.22/Zend/zend_execute_API.c:829
#20 0x00000000008e04fb in zif_call_user_func_array (ht=2, return_value=0x2ef5e28, 
    return_value_ptr=0x7ffff632d650, this_ptr=0x0, return_value_used=1)
    at /root/php-5.6.22/ext/standard/basic_functions.c:4786
#21 0x0000000000af1cdd in zend_do_fcall_common_helper_SPEC (execute_data=0x7ffff632d928)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:558
#22 0x0000000000af24b8 in ZEND_DO_FCALL_BY_NAME_SPEC_HANDLER (execute_data=0x7ffff632d928)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:693
#23 0x0000000000af1343 in execute_ex (execute_data=0x7ffff632d928)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:363
#24 0x0000000000af13c6 in zend_execute (op_array=0x7fffefb24cb8)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:388
#25 0x0000000000a95cb8 in zend_call_function (fci=0x7fffffff6200, fci_cache=0x7fffffff6080)
    at /root/php-5.6.22/Zend/zend_execute_API.c:829
#26 0x0000000000a94ede in call_user_function_ex (function_table=0x146f7b0, object_pp=0x0, 
    function_name=0x7fffefb335a0, retval_ptr_ptr=0x7fffffff62a8, param_count=2, 
    params=0x7fffffff6290, no_separation=0, symbol_table=0x0)
    at /root/php-5.6.22/Zend/zend_execute_API.c:617
#27 0x00007ffff00d4d35 in http_onReceive (serv=0x1643cd0, req=0x7fffffff65f8)
    at /root/swoole-src/swoole_http_server.c:1183
#28 0x00007ffff0112995 in swWorker_onTask (factory=0x1644100, task=0x7fffffff65f8)
    at /root/swoole-src/src/network/Worker.c:192
#29 0x00007ffff00f71e5 in swFactory_dispatch (factory=0x1644100, task=0x7fffffff65f0)
    at /root/swoole-src/src/factory/Factory.c:65
#30 0x00007ffff010dae1 in swReactorThread_dispatch (conn=0x7fffed873e80, 
    data=0x1723fe0 "GET /staff/list?test=596874199211929855 HTTP/1.1\r\nHost: 192.168.2.3:9501\r\nConnection: keep-alive\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.26"..., length=495)
    at /root/swoole-src/src/network/ReactorThread.c:1289
#31 0x00007ffff0117446 in swPort_onRead_http (reactor=0x1644548, port=0x7fffefc8e2e0, 
    event=0x7fffffffa7d0) at /root/swoole-src/src/network/Port.c:477
#32 0x00007ffff010c2b8 in swReactorThread_onRead (reactor=0x1644548, event=0x7fffffffa7d0)
    at /root/swoole-src/src/network/ReactorThread.c:790
#33 0x00007ffff00fe16e in swReactorEpoll_wait (reactor=0x1644548, timeo=0x7fffffffa850)
    at /root/swoole-src/src/reactor/ReactorEpoll.c:258
#34 0x00007ffff010f0a1 in swReactorProcess_loop (pool=0x7fffefc8e240, worker=0x7fffffffa8d0)
    at /root/swoole-src/src/network/ReactorProcess.c:374
#35 0x00007ffff010e427 in swReactorProcess_start (serv=0x1643cd0)
    at /root/swoole-src/src/network/ReactorProcess.c:102
---Type <return> to continue, or q <return> to quit---
#36 0x00007ffff01016cc in swServer_start (serv=0x1643cd0)
    at /root/swoole-src/src/network/Server.c:643
#37 0x00007ffff00d72c9 in zim_swoole_http_server_start (ht=0, return_value=0x7fffefb7ddd8, 
    return_value_ptr=0x7ffff632a6f8, this_ptr=0x7fffefb7dd60, return_value_used=0)
    at /root/swoole-src/swoole_http_server.c:1621
#38 0x0000000000af1cdd in zend_do_fcall_common_helper_SPEC (execute_data=0x7ffff632af10)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:558
#39 0x0000000000af24b8 in ZEND_DO_FCALL_BY_NAME_SPEC_HANDLER (execute_data=0x7ffff632af10)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:693
#40 0x0000000000af1343 in execute_ex (execute_data=0x7ffff632af10)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:363
#41 0x0000000000af13c6 in zend_execute (op_array=0x7ffff635fa70)
    at /root/php-5.6.22/Zend/zend_vm_execute.h:388
#42 0x0000000000aab9ad in zend_execute_scripts (type=8, retval=0x0, file_count=3)
    at /root/php-5.6.22/Zend/zend.c:1341
#43 0x0000000000a11522 in php_execute_script (primary_file=0x7fffffffe1f0)
    at /root/php-5.6.22/main/main.c:2613
#44 0x0000000000b62fdd in do_cli (argc=3, argv=0x146eb90)
    at /root/php-5.6.22/sapi/cli/php_cli.c:994
#45 0x0000000000b64072 in main (argc=3, argv=0x146eb90)
    at /root/php-5.6.22/sapi/cli/php_cli.c:1378

**Comment by matyhtf** [comment]
已迁移至另外一个issue #718
