### ISSUE TITLE
扩展没有执行RSHUTDOWN

### ISSUE THREAD

**Issue by muyilangjun1** [swoole/swoole-src#717]
最近在使用swoole的过程中,发现一个比较大的问题,我们写扩展的时候(比如mysql,redis),每个请求都会调用RINIT和RSHUTDOWN,但swoole模式下,只有第一个请求执行了RINIT,这样mysql,redis扩展在使用过程中,就有一些不确定性,也就是说所有现有的扩展如果在swoole中使用了,是有隐患的,不知道我的这个担忧是否成立,望解答

**Comment by matyhtf** [comment]
内存和资源的销毁，是按照变量的生命周期处理的。按照Zend VM的引用计数GC方式，当变量的引用计数为0时就会回收对应的内存和资源。扩展不以来`RSHUTDOWN`回收资源。
