### ISSUE TITLE
Mac系统压测的时候，遇到的并发问题

### ISSUE THREAD

**Issue by diida** [swoole/swoole-src#718]
ab -c 150 -n 10000 http://127.0.0.1:7071/
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
apr_socket_recv: Connection reset by peer (54)
Total of 300 requests completed

压测用的额命令，没有带-k，超过100之后，就无法正常压测，报错如上面所示，同时压Nginx，Nginx表现正常。

`ab -c 150 -n 10000 http://127.0.0.1:7071/`

有的时候swoole会输出下面错误

./bin/php test/swoole.php
[2016-06-06 11:58:28 #77741.1]  WARNING swReactorKqueue_wait: kqueue event unknow filter=-1
[2016-06-06 11:58:29 #77741.0]  WARNING swFactoryProcess_dispatch: dispatch[type=4] failed, connection#20[session_id=721] is closed by server.

用的是php7 + swoole 1.8.5稳定版本

系统环境是OS X 10.9.5
测试代码如下

<?php
function error($code,$msg) {
    $a = [];
    $a['code'] = $code;
    $a['msg']=$msg;
    return json_encode($a);
}
$http = new swoole_http_server("0.0.0.0", 7071);

$http->set(array('worker_num' => 2));
$http->on('request', function ($request, $response) {
            $response->header("Content-Type", "text/html; charset=utf-8");
                $response->end(error(100,'it work'));
                });

$http->start();

**Comment by matyhtf** [comment]
贴出操作系统版本号码

**Comment by diida** [comment]
系统环境是：OS X 10.9.5  
苹果的Mac Pro

**Comment by andot** [comment]
OS X 10.11.6
同样有这个问题

**Comment by wanjochan** [comment]
@diida 这个应该是 OSX的socket堆栈问题
