### ISSUE TITLE
能不能开发视频聊天功能

### ISSUE THREAD

**Issue by bmqmingqi** [swoole/swoole-src#720]
能不能开发视频聊天基本功能

**Comment by firedtoad** [comment]
视频P2p聊天涉及很多知识比如 udp hole  等业务领域的不适合做成通用的模块

2016-06-07 17:14 GMT+08:00 bmqmingqi <notifications@github.com>:

**Comment by matyhtf** [comment]
底层的音视频流媒体处理有很多C/C++的开源产品可用，没必要使用PHP+Swoole开发，即使能实现，性能也较差。
建议只使用PHP+Swoole实现一些上层的功能逻辑。

**Comment by bmqmingqi** [comment]
谢谢！！
