### ISSUE TITLE
WebSocket onClose 中调$serv->task(), 服务端主动关闭时报'Swoole\Server::task(): The method can only be used in the worker process.'

### ISSUE THREAD

**Issue by immusen** [swoole/swoole-src#722]
场景: APP作为WebSocket client,  当Client offline时发广播给在线client.

解决方案: onClose中执行 $serv->task(),  task执行广播.

PHP 5.6.17
Swoole 1.8.5 (1.8.2也一样)
Ubuntu 14.04.3 LTS

问题: 当APP被关闭或退到后台休眠, 被动关闭连接, $serv->task()和离线广播正常;
         当在其他Task进程中主动调用$serv->close($fd)关闭连接时, 报错:
PHP Fatal error:  Uncaught exception 'yii\base\ErrorException' with message 'Swoole\Server::task(): The method can only be used in the worker process.' in /data/webroot/server/console/controllers/WebsocketController.php:186
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'Swoole\\Server::...', '/data/webroot/t...', 186, Array)
#1 /data/webroot/server/console/controllers/WebsocketController.php(186): Swoole\Server->task(Array)
#2 [internal function]: console\controllers\WebsocketController->onClose(Object(Swoole\WebSocket\Server), 5, 0)
#3 /data/webroot/server/console/controllers/WebsocketController.php(101): Swoole\Server->close(5)
#4 [internal function]: console\controllers\WebsocketController->onTask(Object(Swoole\WebSocket\Server), 7, 0, Array)
#5 /data/webroot/server/console/controllers/WebsocketController.php(22): Swoole\Http\Server->start()

**Comment by matyhtf** [comment]
task方法只能在Worker进程内使用。

**Comment by immusen** [comment]
http://wiki.swoole.com/wiki/page/p-event/onClose.html

**Comment by immusen** [comment]
http://wiki.swoole.com/wiki/page/p-event/onClose.html 
"无论由客户端发起close还是服务器端主动调用$serv->close()关闭连接，都会触发此事件。因此只要连接关闭，就一定会回调此函数"
遇到的情况是服务器的task_worker中主动$serv->close($fd), onClose里面用task方法,就报错; 但是客户端直接关闭连接(关闭客户端程序, 断网) onClose里面用task就完全正常呢. 难道task_worker中主动$serv->close($fd), onClose回调不在worker进程中?

**Comment by immusen** [comment]
问题解决, 让$serv->close($fd)运行在worker进程中, 这样onClose就能正常$serv->task(); 但task进程中 $serv->close($fd)会报错: 'Swoole\Server::task(): The method can only be used in the worker process.'

**Comment by matyhtf** [comment]
确实存在BUG，主动close时没有判断当前是否为Task进程。导致onClose在task进程中被执行了。
