### ISSUE TITLE
 warning: cast from pointer to integer of different size

### ISSUE THREAD

**Issue by bmqmingqi** [swoole/swoole-src#724]
/home/youhuo/swoole-src-swoole-1.8.5-stable/src/network/Manager.c: In function ‘swManager_loop_async’:
/home/youhuo/swoole-src-swoole-1.8.5-stable/src/network/Manager.c:314:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                     new_pid = (pid_t) swHashMap_find_int(pidMap, pid);
                               ^
/home/youhuo/swoole-src-swoole-1.8.5-stable/src/network/Manager.c:364:74: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
                         swHashMap_add_int(pidMap, reload_workers[i].pid, (void*) new_pid);

**Comment by matyhtf** [comment]
fixed .
