### ISSUE TITLE
swoole_http_client 异步访问https 不可用

### ISSUE THREAD

**Issue by qysf12345** [swoole/swoole-src#728]
1，
<?php
// 访问appstore
//https://sandbox.itunes.apple.com
$cli;
$url = 'sandbox.itunes.apple.com';
swoole_async_dns_lookup($url, function($host,$ip)
{
        if($ip)
        {
                global $cli;
                $cli = new \swoole_http_client($ip, 443, true);
                $cli->get('/verifyReceipt', function($cli){echo $cli->body.'::::::'.PHP_EOL;exit();});
        }
        else
        {
                echo 'false';
        }
});

没有任何返回， 没有触发回调函数， 没有任何输出

2， 
<?php
//访问https://www.baidu.com
$cli;
$url = 'www.baidu.com';
swoole_async_dns_lookup($url, function($host,$ip)
{
        if($ip)
        {
                global $cli;
                $cli = new \swoole_http_client($ip, 443, true);
                $cli->get('/index.php', function($cli){echo $cli->body.'::::::'.PHP_EOL;exit();});
        }
        else
        {
                echo 'false';
        }
});

返回如下：
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>bfe/1.0.8.14</center>
</body>
</html>

https 访问是还要设置什么么？

**Comment by matyhtf** [comment]
你的Swoole编译开启enable-openssl了吗？

**Comment by qysf12345** [comment]
还以为1.8.6中 和 MySQL-client ，http-client 一样 都默认了呢。。刚编译完 测试OK了
谢谢韩总！
