### ISSUE TITLE
swoole_1.8.6_stable 下 swoole_client异步时 触发on_error事件时会产生core情况

### ISSUE THREAD

**Issue by badxpgy** [swoole/swoole-src#729]
测试主要代码
```php
class ASClient {

	private $requestList = array();
	public $client = false;
	private $working = false;
	public $ip;
	public $port;
	public static $Request_Cnt = 0;
	public static $Response_Cnt = 0;
	public static $Error_Cnt = 0;
	public static $Connect_cnt = 0;
	public static $workid = 0;

	public function __construct($ip, $port, $work_id) {
		$this->ip = $ip;
		$this->port = $port;
		self::$workid = $work_id;
	}
	private function CreateClient() {
		$this->working = false;
		$this->client = new swoole_client(SWOOLE_SOCK_TCP, SWOOLE_SOCK_ASYNC);
		$this->client->set(array(
			'open_length_check' => true,
			'package_length_type' => 's',
			'package_length_offset' => 6,
			'package_body_offset' => 13,
			'package_max_length' => 200000,
		));
		$this->client->on('connect', function (swoole_client $socket) {
			$this->working = true;
			$this->DoWrite();
		});
		$this->client->on('error', function (swoole_client $socket) {
			$this->client = false;
			$err = swoole_strerror($socket->errCode);
		});
		$this->client->on('close', function (swoole_client $socket) {
			$this->client = false;
		});
		$this->client->on('receive', function (swoole_client $socket, $data) {
			$this->DoWrite();
		});
		if (!$this->client->connect($this->ip, $this->port)) {
			$this->client = false;
		}
	}
	public function DoWrite() {
		if (count($this->requestList) > 0) {
			$info = array_shift($this->requestList);
			$ret = $this->client->send($info);
			//发送失败直接断开连接并清理数据
			if (!$ret) {
			}
		}
	}

	private $flowid = 1;

	public function DoRequest() {
		$data="test";
		array_push($this->requestList, $data);
		if (!$this->client) {
			$this->CreateClient();
		} else if ($this->working) {
			$this->DoWrite();
		}
	}
}
```

**Comment by badxpgy** [comment]
core信息如下：
(gdb) bt
#0  zend_std_write_property (object=0x2aec63c2d530, member=0x2aec63dc8cd8, value=0x2aec63b44b20, key=0x0) at /tools/php-5.4.9/Zend/zend_object_handlers.c:520
#1  0x000000000073925a in zend_update_property (scope=<value optimized out>, object=0x2aec63c2d530, name=0x2aec613b2ed4 "errCode", name_length=7, 
    value=0x2aec63b44b20) at /tools/php-5.4.9/Zend/zend_API.c:3614
#2  0x00002aec6137a1ce in client_onError (cli=0x2aec63c2e620) at /data/gameserver/Poker/phpserver/swoole-src-1.8.6-stable/swoole_client.c:242
#3  0x00002aec613a081b in swClient_onError (reactor=<value optimized out>, event=<value optimized out>)
    at /data/gameserver/Poker/phpserver/swoole-src-1.8.6-stable/src/network/Client.c:714
#4  0x00002aec6139c45a in swReactorEpoll_wait (reactor=0x1494cc58, timeo=<value optimized out>)
    at /data/gameserver/Poker/phpserver/swoole-src-1.8.6-stable/src/reactor/ReactorEpoll.c:282
#5  0x00002aec613a66a9 in swReactorProcess_loop (pool=<value optimized out>, worker=0x2aec621f1d80)
    at /data/gameserver/Poker/phpserver/swoole-src-1.8.6-stable/src/network/ReactorProcess.c:374
#6  0x00002aec613a2837 in swProcessPool_spawn (worker=0x2aec621f1d80) at /data/gameserver/Poker/phpserver/swoole-src-1.8.6-stable/src/network/ProcessPool.c:238
#7  0x00002aec613a2d19 in swProcessPool_start (pool=0x2aec621f1240) at /data/gameserver/Poker/phpserver/swoole-src-1.8.6-stable/src/network/ProcessPool.c:106
#8  0x00002aec613a69ec in swReactorProcess_start (serv=<value optimized out>)
    at /data/gameserver/Poker/phpserver/swoole-src-1.8.6-stable/src/network/ReactorProcess.c:164
#9  0x00002aec6139edd0 in swServer_start (serv=0x1494c6c0) at /data/gameserver/Poker/phpserver/swoole-src-1.8.6-stable/src/network/Server.c:643
#10 0x00002aec61374e07 in zim_swoole_server_start (ht=<value optimized out>, return_value=0x2aec5bf6a360, return_value_ptr=<value optimized out>, 
    this_ptr=0x2aec5bf66d18, return_value_used=<value optimized out>) at /data/gameserver/Poker/phpserver/swoole-src-1.8.6-stable/swoole_server.c:1786
#11 0x0000000000763246 in zend_do_fcall_common_helper_SPEC (execute_data=0x2aec5bf34060) at /tools/php-5.4.9/Zend/zend_vm_execute.h:642
#12 0x0000000000768ced in execute (op_array=0x2aec5bf67610) at /tools/php-5.4.9/Zend/zend_vm_execute.h:410
#13 0x0000000000736c38 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /tools/php-5.4.9/Zend/zend.c:1309
#14 0x00000000006dbc5d in php_execute_script (primary_file=0x7fff922c34a0) at /tools/php-5.4.9/main/main.c:2482
#15 0x00000000007d99ed in do_cli (argc=2, argv=0x7fff922c3888) at /tools/php-5.4.9/sapi/cli/php_cli.c:988
#16 0x00000000007da0b8 in main (argc=2, argv=0x7fff922c3888) at /tools/php-5.4.9/sapi/cli/php_cli.c:1364
(gdb) f 2
#2  0x00002aec6137a1ce in client_onError (cli=0x2aec63c2e620) at /data/gameserver/Poker/phpserver/swoole-src-1.8.6-stable/swoole_client.c:242
242	    zend_update_property_long(swoole_client_class_entry_ptr, zobject, ZEND_STRL("errCode"), SwooleG.error TSRMLS_CC);
(gdb) list
237	{
238	#if PHP_MAJOR_VERSION < 7
239	    TSRMLS_FETCH_FROM_CTX(sw_thread_ctx ? sw_thread_ctx : NULL);
240	#endif
241	    zval *zobject = cli->object;
242	    zend_update_property_long(swoole_client_class_entry_ptr, zobject, ZEND_STRL("errCode"), SwooleG.error TSRMLS_CC);
243	    if (!cli->released)
244	    {
245	        php_swoole_client_free(zobject, cli TSRMLS_CC);
246	    }
(gdb)

**Comment by matyhtf** [comment]
`Linux LOCAL-97-55.boyaa.com 2.6.18-402.el5 #1 SMP Tue Feb 10 17:49:04 EST 2015 x86_64 x86_64 x86_64 GNU/Linux`

低版本Linux内核存在BUG，已解决。

https://github.com/swoole/swoole-src/commit/e1092fdb186ca69f4e25e2ff86acf5ea4f63f1a0
