### ISSUE TITLE
运行一段时候后，tasker进程会异常 无法接受到pipeMessage 1.8.5版本

### ISSUE THREAD

**Issue by wheelswang** [swoole/swoole-src#730]
poll([{fd=101, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {3889194, 223690779}) = 0
clock_gettime(CLOCK_MONOTONIC, {3889194, 223709624}) = 0
clock_gettime(CLOCK_MONOTONIC, {3889194, 223741761}) = 0
poll([{fd=101, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 1000) = 0 (Timeout)
poll([{fd=101, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {3889195, 224911239}) = 0
clock_gettime(CLOCK_MONOTONIC, {3889195, 224930123}) = 0
clock_gettime(CLOCK_MONOTONIC, {3889195, 224948556}) = 0
poll([{fd=101, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 1000) = 0 (Timeout)
poll([{fd=101, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {3889196, 226092142}) = 0
clock_gettime(CLOCK_MONOTONIC, {3889196, 226110068}) = 0
clock_gettime(CLOCK_MONOTONIC, {3889196, 226127580}) = 0

**Comment by wheelswang** [comment]
这是strace takser进程的系统调用

**Comment by fznply** [comment]
建议使用最新的master分支，再进行一次测试，因为1.8.5并非一个稳定的版本；如果最新的分支依然存在你说的问题，请把精简一下测试代码后贴出来，这样方便定位问题。

**Comment by matyhtf** [comment]
使用`lsof`查看101的socket是什么。这个可能是你PHP程序的问题。

**Comment by wheelswang** [comment]
write(98, "\0\0\0\0Y\2 \0\17\0\0\0{\"cmd\":\"sendToUsers\""..., 613) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=98, events=POLLOUT}], 1, 1000) = 0 (Timeout)
write(98, "\0\0\0\0Y\2 \0\17\0\0\0{\"cmd\":\"sendToUsers\""..., 613) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=98, events=POLLOUT}], 1, 1000) = 0 (Timeout)
write(98, "\0\0\0\0Y\2 \0\17\0\0\0{\"cmd\":\"sendToUsers\""..., 613) = -1 EAGAIN (Resource temporarily unavailable)

**Comment by wheelswang** [comment]
sendMessage向tasker发送的数据比较大会有问题，上面这是strace跟踪到的

**Comment by matyhtf** [comment]
你第一段贴的strace信息和第二段是两个不同的问题。
1. 建议使用`lsof`查看对应的fd是什么连接，存在超时问题
2. sendMessage数据较大，从你的strace信息看只有613字节并不大
3. 你应该是指sendMessage过多，对应的Worker进程或Task进程处于阻塞状态，无法处理消息。这里就会卡住。

**Comment by wheelswang** [comment]
上面是我的worker进程阻塞造成的错误
还有一个问题，server运行一段时间后会报too many open file
lsof查看发现master进程有大量下面这样的的sock句柄，而server实际端口占用的句柄并不多
php     16828 root  211u  sock                0,7       0t0 10226647 can't identify protocol

**Comment by matyhtf** [comment]
修改 ulimit -n ，设置为 65535或更高。
