### ISSUE TITLE
swoole_server->close调用会阻塞

### ISSUE THREAD

**Issue by wheelswang** [swoole/swoole-src#741]
write(114, "\327\236a\0\0\0\2\0\4\346uv", 12) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=114, events=POLLOUT}], 1, 1000) = 0 (Timeout)
write(114, "\327\236a\0\0\0\2\0\4\346uv", 12) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=114, events=POLLOUT}], 1, 1000) = 0 (Timeout)
write(114, "\327\236a\0\0\0\2\0\4\346uv", 12) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=114, events=POLLOUT}], 1, 1000) = 0 (Timeout)
write(114, "\327\236a\0\0\0\2\0\4\346uv", 12) = -1 EAGAIN (Resource temporarily unavailable)

**Comment by matyhtf** [comment]
在Task进程内调用了close，而且你的Worker进程存在阻塞无法即时处理。Task进程没有EventLoop，只能阻塞等待。

**Comment by wheelswang** [comment]
我在new swoole_process生成的进程里close一个连接，有办法可以不用等待worker进程响应么？

**Comment by matyhtf** [comment]
可以调用`write`向Worker进程发指令。

**Comment by wheelswang** [comment]
swoole_websocket_server->push 有可能会阻塞么 我在线上业务上看日志 push给八百个fd，耗时6s
