### ISSUE TITLE
swoole_websocket_server->push 有可能会阻塞么 看日志显示push给八百个fd，耗时6s

### ISSUE THREAD

**Issue by wheelswang** [swoole/swoole-src#743]
swoole_websocket_server->push 有可能会阻塞么 看日志显示push给八百个fd，耗时6s

**Comment by matyhtf** [comment]
Worker进程中没有阻塞，Task进程如果管道缓存区满了可能会阻塞，但Reactor线程效率非常高，不太能出现。

**Comment by wheelswang** [comment]
我是在swoole_process创建的进程中调用swoole_websocket_server->push，每次push之前会只调用一次本地redis get请求和一次swoole_server->exist
kill掉该进程，swoole自动重新fork一个新的出来后执行就恢复正常了

**Comment by matyhtf** [comment]
需要strace跟踪出问题的进程
