### ISSUE TITLE
多个一次性定时器以某种顺序设置会触发时间错乱。

### ISSUE THREAD

**Issue by x-xiang** [swoole/swoole-src#744]
PHP 7.0.8 Swoole 1.8.6

       Test script:
       ---------------
        <?php
        $serv = new swoole_server("127.0.0.1", 9501);

        $serv->on('WorkerStart', function ($serv, $worker_id) {
            if (!$serv->taskworker) {
                if($worker_id == 0) {
                    foreach (array(6, 2, 4) as $value) {
                        echo "$value set at ".microtime(TRUE).', Should Run After '.($value * 2).PHP_EOL;
                        $serv->after($value * 2000, function() use($value) {
                            echo "$value run at ".microtime(TRUE).PHP_EOL;
                        });
                    }
                }
            }
        });

        $serv->on('Receive', function ($serv, $fd, $from_id, $data) {
        });

        $serv->start();
        ?>

        Expected result:
        ----------------
        6 set at 1467256086.4878, Should Run After 12
        2 set at 1467256086.4881, Should Run After 4
        4 set at 1467256086.4882, Should Run After 8
        2 run at 1467256090.4964
        4 run at 1467256094.4965
        6 run at 1467256098.4926

        Actual result:
        --------------
        6 set at 1467256086.4878, Should Run After 12
        2 set at 1467256086.4881, Should Run After 4
        4 set at 1467256086.4882, Should Run After 8
        2 run at 1467256094.4964
        4 run at 1467256094.4965
        6 run at 1467256098.4926

**Comment by matyhtf** [comment]
已修复。https://github.com/swoole/swoole-src/commit/316d19252d48c12d93e209cbab3d45e743da5d68

**Comment by x-xiang** [comment]
速度啊 昨天发群里无人问津 还是发这里反馈快
