### ISSUE TITLE
[Feature request] add socket close errorno to onClose() or the array result of connection_info()/getClientInfo()

### ISSUE THREAD

**Issue by ufosaga** [swoole/swoole-src#746]
The current onClose() is:
function onClose(swoole_server $server, int $fd, int $from_id);

the desired one:
function onClose(swoole_server $server, int $fd, int $from_id, int $errorno);

or the desired array resusts for connection_info():
    array (
         'from_id' => 0,
          'from_fd' => 12,
           'connect_time' => 1392895129,
          'last_time' => 1392895137,
          'from_port' => 9501,
          'remote_port' => 48918,
          'remote_ip' => '127.0.0.1',

          'errorno' => 17, // EEXIST
 )

Under some circumstance, the server application needs to the exact close errorno of the specific fd.
e.g. : ENOENT, EINTR, EEXIST

to better distinguishing the problem.

**Comment by matyhtf** [comment]
Good idea.
The next version will add a close_errno.

**Comment by ufosaga** [comment]
Thx!
