### ISSUE TITLE
kill http server problem

### ISSUE THREAD

**Issue by xcl3721** [swoole/swoole-src#747]
Envirment:
1.8.6 swoole stable && master of swoole github
Centos 7.1
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

-------
code:https://github.com/xcl3721/Dora-RPC
step1: cd test/
step2: php demoserver.php

another console:
step1:cd test/
step2:cat dorarpc.pid |xargs kill
step3:ps aux|grep dora

process named :dora|Monitor alived

-------
next step:remove the process when the server start (process monitor report process)

do step again..

and dora|Master process will Alived

**Comment by matyhtf** [comment]
UserProcess进程收到信号未退出。设置信号回调函数，退出进程。
