### ISSUE TITLE
环境：swoole 1.8.7 php7.0.6，http close 时会发生崩溃

### ISSUE THREAD

**Issue by tmtbe** [swoole/swoole-src#748]
![qq 20160630155230](https://cloud.githubusercontent.com/assets/5286367/16480894/2dc32600-3edb-11e6-9984-dc9d7a36ea97.jpg)
重现方式
1.请求返回尽可能大一些
2.ab压测中中断
3.就有可能出现dump

**Comment by matyhtf** [comment]
最新的版本已经修复，请使用1.8.9
