### ISSUE TITLE
编译成功但是php startup报错

### ISSUE THREAD

**Issue by cindyming** [swoole/swoole-src#765]
/Applications/MAMP/bin/php/php5.6.10/bin/phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
./configure  --with-php-config=/Applications/MAMP/bin/php/php5.6.10/bin/php-config --enable-async-mysql
HP Warning:  PHP Startup: swoole: Unable to initialize module
Module compiled with module API=20121212
PHP    compiled with module API=20131226
These options need to match
 in Unknown on line 0

这个是什么原因呢

**Comment by firedtoad** [comment]
api 版本不对 你没phpize

2016-07-15 10:00 GMT+08:00 King King <notifications@github.com>:

**Comment by matyhtf** [comment]
`swoole.so`编译时的PHP和运行时的PHP不一致。

**Comment by atefBB** [comment]
Hey, how can I fix this issue? Thanks.
