### ISSUE TITLE
dispatch_mode = 2 时，分配worker有问题

### ISSUE THREAD

**Issue by breath-co2** [swoole/swoole-src#766]
文档里说：

> 2.固定模式，根据连接的文件描述符分配worker。这样可以保证同一个连接发来的数据只会被同一个worker处理。

但是我实际测试后发现并不是这样：
```php
$serv = new swoole_server("127.0.0.1", 8100);
$serv->set(['worker_num' => 3, 'daemonize' => false, 'dispatch_mode' => 2]);
$serv->on('receive', function(swoole_server $serv, $fd, $from_id, $data)
{
    echo '$worker_id = '.$serv->worker_id . ', $fd = ' . $fd . ', $data = '. $data;
});
$serv->start();
```
执行(或用 telnet 127.0.0.1 8100 发送完毕后退出再发送)
```bash
echo "a" > /dev/tcp/127.0.0.1/8100
echo "b" > /dev/tcp/127.0.0.1/8100
echo "c" > /dev/tcp/127.0.0.1/8100
echo "d" > /dev/tcp/127.0.0.1/8100
```
结果如下：
```
$worker_id = 2, $fd = 1, $data = a
$worker_id = 2, $fd = 2, $data = b
$worker_id = 2, $fd = 3, $data = c
$worker_id = 2, $fd = 4, $data = d
```
fd 会不断的增加，但是被分配到的 worker id 始终是同一个。这样会导致worker进程不能够平均分摊任务的问题。

由于这样的问题导致了我的服务出现了个别 worker 负载特别高，其它 worker 永远分配不到的问题，加worker数也不行（由于服务的特殊情况，只能选择按 fd 分配worker）

连接我的 swoole 服务器只有少数几个（4个）客户端，每次客户端连接都是 tcp 连接后发送很多数据（几k - 几M不等）后断开，再重新连接发送，虽然客户端不多但请求非常的频繁（同步数据）。
这时候即便我开了30个worker进程，但也是只有id是26，27，28，29的4个进程会被onReceive，其它worker都白费，直接导致了这几个进程一直要满负荷处理数据，而其它的进程都一直是空闲状态，加再多worker也无济于事~~

**Comment by matyhtf** [comment]
PHP层的fd不是真正的文件描述符。你的测试中，多次telnet实际上是同一个文件描述符，所以只会分配到一个Worker进程。请并发多个连接进行测试。

**Comment by breath-co2** [comment]
@matyhtf 此问题只是表象，最终的结果就是在只有少数几个连接却大量使用短连接请求会导致个别worker 爆满，其它worker空闲这样负载不均衡的问题

**Comment by matyhtf** [comment]
`dispatch_mode=2/4/5` 这些固定分配的模式，如果并发客户端数量比Worker进程少，一定是无法利用所有Worker进程的。
