### ISSUE TITLE
swoole_http_server coredump.

### ISSUE THREAD

**Issue by chenxiaofa** [swoole/swoole-src#768]
```php
$serv = new swoole_http_server("0.0.0.0", 9502);

class tt{
	public $req = null;
}
$a = [];
$serv->on('Request', function($request, $response) {
	global $a;
	$t = new tt();
	$t->req = $request;
	$a[] = $t;
	$response->end(1);

});

$serv->on('WorkerStart',function()use($server){
	swoole_timer_tick(100, function(){
		global $a;
		foreach($a as $t)
		{
			$t->req = null;
		}
		$a = [];
	});
});
$serv->set(array(
		'worker_num' => 1,    //worker process num
));

$serv->start();
```

以上代码在1.8.8分支代码上运行,在chrome浏览器中打开,然后按住F5一值刷新,会出现coredump.

以下为个人调试结果:
发现多个http请求共同使用了一个http_context
 
![qq 20160718103443](https://cloud.githubusercontent.com/assets/5044824/16905082/43f8fd18-4cd3-11e6-823e-503fbe0e1063.png)

导致ctx->request->zdata  被释放了两次.破坏了alloc_globals.mm_heap.free_slot.
第一次释放(sw_zval_ptr_dtor(&req->zdata);)的时候正常,第二次的时候,由于内存块已经还给php管理了,内存块的前8个字节变成了一个zend_mm_free_slot *指针next_free_slot;
第二次释放时候大概是有一个GC--的操作吧,把这个指针-1了

**Comment by firedtoad** [comment]
double free 这里竟然也会有

在 2016年7月18日 上午10:42，陈晓发 <notifications@github.com>写道：

**Comment by matyhtf** [comment]
WorkerStart 里的定时器 影响了zend mm的内存管理。改变了request的生存周期。
