### ISSUE TITLE
当redis失效导致500［Bug］

### ISSUE THREAD

**Issue by lovefcaaa** [swoole/swoole-src#770]
vendor/matyhtf/swoole_framework/libs/Swoole/Redis.php:90（注释掉：redis不可用时导致框架500错误，应将此种故障交由上层业务try处理，而不应该用如下错误从而停止）
    //\Swoole::$php->log->error(__CLASS__ . " Swoole Redis Exception" . var_export($e, 1));

**Comment by matyhtf** [comment]
不是swoole扩展的问题。

**Comment by lovefcaaa** [comment]
是 swoole_framework 中的问题
