### ISSUE TITLE
当mysql故障时导致500［Bug］

### ISSUE THREAD

**Issue by lovefcaaa** [swoole/swoole-src#771]
vendor/matyhtf/swoole_framework/libs/Swoole/Database/MySQLi.php:60（增加try：避免mysql死掉之后框架500）
    try{
      parent::connect(
        $host,
        $db_config['user'],
        $db_config['password'],
        $db_config['name'],
        $db_config['port']
      );
    }catch(\Exception $e){
      return false;
    }

**Comment by matyhtf** [comment]
不是swoole扩展的问题。
