### ISSUE TITLE
Multi-port and mixed protocol示例代码无法运行 swoole1.8.7稳定版

### ISSUE THREAD

**Issue by Corzcode** [swoole/swoole-src#775]
`$serv = new swoole_http_server("127.0.0.1", 9501, SWOOLE_BASE);

$port2 = $serv->listen("0.0.0.0", 9502, SWOOLE_SOCK_TCP);
$port2->on('receive', function (swoole_server $serv, $fd, $from_id, $data) {
    var_dump($data);
    $serv->send($fd, $data);    
});

$serv->on('request', function($req, $resp) {
    $resp->end("Hello World");
});

$serv->start();`
里只有http协议有回应 tcp没反应

**Comment by matyhtf** [comment]
未调用 $port->set 方法，因此监听的端口会继承 主服务器的设置，也就是 新监听的端口也是Http服务器，同样也会触发 onRequest，而不是 onReceive
