### ISSUE TITLE
php7 引用$request->files后coredump

### ISSUE THREAD

**Issue by chenxiaofa** [swoole/swoole-src#776]
code:
<?php
$serv = new swoole_http_server("0.0.0.0", 9502);

$tmp = [];

$serv->on('Request', function($request, $response) {
	global $tmp;
	$tmp[] = &$request->files;
});

$serv->set(array(
		'worker_num' => 1,    //worker process num
));

$serv->start();

![image](https://cloud.githubusercontent.com/assets/5044824/17075482/4965cd24-50c7-11e6-92da-42e42c1f7ec0.png)

**Comment by matyhtf** [comment]
PHP7可能存在BUG，引用一个为NULL的属性后，这个属性变成一个引用类型了。暂时使用 IS_ARRAY判断解决问题。
