### ISSUE TITLE
undefined symbol: SSLv3_server_method

### ISSUE THREAD

**Issue by douyu** [swoole/swoole-src#778]
Ubuntu 14.04.4 LTS
./configure --enable-swoole-debug --enable-openssl
make
make test

PHP Warning:  PHP Startup: Unable to load dynamic library '/root/swoole-src-1.8.7-stable/modules/swoole.so' - /root/swoole-src-1.8.7-stable/modules/swoole.so: undefined symbol: SSLv3_server_method in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/root/swoole-src-1.8.7-stable/modules/swoole.so' - /root/swoole-src-1.8.7-stable/modules/swoole.so: undefined symbol: SSLv3_server_method in Unknown on line 0

**Comment by fznply** [comment]
先进行一下库的正确性检查吧：
执行命令：`locate ssl | grep libssl` ，查看是否存在libssl.so
假设找到`/usr/lib64/libssl.so`库, 执行命令`strings /usr/lib64/libssl.so | grep SSLv3_server_method`，查看是否有对应symbol存在。
如果对应的so库不存在，或者对应so库没有SSLv3_server_method函数符号，说明你机器的so库有问题，重新安装一下openssl库就好了。

如果是自己编译的openssl库，或者openssl库没有配置到系统库目录，也可以在编译swoole的时候指定以下参数：export LDFLAGS="-Wl,-rpath,$LIBRARY_PATH" 其中LIBRARY_PATH需要包含你openssl库所在目录。

**Comment by douyu** [comment]
root@ubuntu:~# locate ssl | grep "libssl.so"
/lib/x86_64-linux-gnu/libssl.so.1.0.0

已经安装了openssl和libssl-dev

**Comment by fznply** [comment]
执行命令`strings /usr/lib64/libssl.so | grep SSLv3_server_method`，查看是否有对应symbol存在，如果不存在说明你的so有问题。
执行命令`ldconfig -p | grep libssl.so`，查看so库是否配置到了系统库目录。

**Comment by douyu** [comment]
谢谢，问题已经解决，系统里面安装了libssl.so.1.0.2 导致的，改回libssl.1.0.0就好了

**Comment by matyhtf** [comment]
新的版本已提供`--with-openssl`选项，可以设置`openssl`的路径
