### ISSUE TITLE
examples/client/long_tcp.php  长连接有问题

### ISSUE THREAD

**Issue by byargv** [swoole/swoole-src#78]
Warning: swoole_client::connect(): connect to server[192.168.0.1:9501] failed. Error: Transport endpoint is already connected [106] in /wwwroot/swoole/examples/client/long_tcp.php on line 5
connect failed

经过多次试验,证明长连接跑不起来
CentOS 6.5 64BIT + PHP 5.4.28 + swoole 1.7.3

**Comment by matyhtf** [comment]
请使用最新版本测试。
