### ISSUE TITLE
Qustion. Route clients to specific worker

### ISSUE THREAD

**Issue by coollider** [swoole/swoole-src#783]
Hi, can i somthing route users to specific worker.

Example: when client come first time, i will set cookie "worker_id = %worker_id%". After that all requests from this user will routed to worker %worker_id%.

**Comment by coollider** [comment]
No answer?(

**Comment by matyhtf** [comment]
That cannot implement. The reactor thread dispatch mode must be determined before the data is received.

**Comment by matyhtf** [comment]
PHP code cannot be run in a multi-thread environment, You can write an c function to parse the data, select the destination worker process.

**Comment by coollider** [comment]
Ty for answer, i understand.
