### ISSUE TITLE
在read的函数中读取不超过限制的时候，是否保证接受到的是完整的一个或者多个包？？

### ISSUE THREAD

**Issue by nick-william** [swoole/swoole-src#789]
swoole_process->write： “管道通信默认的方式是流式，write写入的数据在read可能会被底层合并。可以设置swoole_process构造函数的第三个参数为2改变为数据报式。”
在swoole_process->read的函数中读取数据在不超过限制的时候，是否保证接受到的都是完整的一个或者多个包？？

**Comment by matyhtf** [comment]
数据包模式下，read读取是完整的。
