### ISSUE TITLE
swoole_client $type 参数会被修改的问题

### ISSUE THREAD

**Issue by andot** [swoole/swoole-src#792]
```php
$conn = new swoole_client($client->type, SWOOLE_SOCK_ASYNC);
```

此处的 `$client->type` 在执行完之后会被修改。

而且 

```php
$type = $client->type;
$conn = new swoole_client($type, SWOOLE_SOCK_ASYNC);
```

这样执行之后，`$client->type` 都会变化。而 `$type` 在这里并不是 `$client->type` 的引用。

这里 `swoole_client` 对这个变量没有采用写时复制的操作，违反了 php 修改变量的原则，应该算是一个 bug 吧。

**Comment by matyhtf** [comment]
fixed.
PR #793
