### ISSUE TITLE
swoole server服务运行两天。不能处理业务了。使用strace有请求过来提示如下。知道这是什么原因引起的吗？

### ISSUE THREAD

**Issue by ssdphp** [swoole/swoole-src#795]
'task_worker_num' => 20,//配置的工作进程数量

accept4(3, {sa_family=AF_INET, sin_port=htons(49762), sin_addr=inet_addr("192.168.2.1")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 61
epoll_ctl(57, EPOLL_CTL_ADD, 61, {EPOLLOUT, {u32=61, u64=61}}) = 0
accept4(3, 0x7fff47ea68c0, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)

**Comment by matyhtf** [comment]
* 贴出PHP和Swoole, Linux环境的信息
* 使用`strace -f `进行跟踪
* 信息贴多一些

**Comment by ssdphp** [comment]
和swoole没有任何关系。swoole服务正常。是我的处理mysql的时候。cli使用mysql连接 未对mysql连接资源的过期异常处理。导致业务数据不能入库。。
