### ISSUE TITLE
redis清空数据时报错

### ISSUE THREAD

**Issue by jocky4012** [swoole/swoole-src#797]
你好，我是用redis来存放一些信息的，只把redis当做内存缓存来使用，所以在启动swoole_server后，会调用redis的flushdb方法来清空整个redis数据（只在worker 0进程中执行一次），但是在使用时发生了fatal error错误：

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 7815263096 bytes)

部分代码如下：
$config = Config::$redis;

$redis = new swoole_redis();

$redis->connect($config[ 'host' ], $config[ 'port' ], function ($redis, $result) use ($config, $flush_db) {

        if($result){

                //redis密码验证

                $redis->auth($config[ 'password' ], function ($redis, $result) use ($flush_db) {

                        if ( $result ) {

                            if ( $flush_db ) $redis->__call('flushdb', 'Common::flushdb');

                            //to do other thing

		        } 

                  });

           }

});

请帮忙看下，谢谢

**Comment by matyhtf** [comment]
不要直接调用`__call`方法，第二个参数应该是数组。

**Comment by jocky4012** [comment]
@matyhtf  你好，感谢你的回复，还有一个问题请教一下，像这种没有参数的命令，如果我第一个参数直接是回调函数会报错，如果第一个参数为空字符串没有报错，但是打印的结果为false，到redis-cli中查看，数据还是存在的。redis文档中不是说flushdb或flushall不会返回失败的结果吗？

`$redis->flushdb('',function($redis,$result){
						var_dump($result);//打印出来的是false
					});`

**Comment by firedtoad** [comment]
内存超了 应该是 dump堆栈的时候

**Comment by matyhtf** [comment]
```php
$redis->flushdb(function($redis,$result){ 
    var_dump($result);
});
```
