### ISSUE TITLE
segmentfault when siege in violent

### ISSUE THREAD

**Issue by wanjochan** [swoole/swoole-src#801]
When I tried violently siege:
siege -c 64 -b -q -t 36000s http://127.0.0.1:9501/
on a very raw swoole_http_server, I experienced a Segment Fault.

As I'm not familiar with debugging that, so I just report the issue here first, for a record only.

**Comment by wanjochan** [comment]
CHN: 用的是最简单的 swoole_http_server 
```
$port=8888;
$http = new swoole_http_server("0.0.0.0", $port);
$http->on('request', function ($request, $response) {
	$response->end(rand());
});
$http->start();
```
经过以下的暴力烤机
·```
while true; do
siege -c 64 -b -q -t 36000s http://127.0.0.1:8888/
done
```
一般大概2-3天左右，这个server就会Segment Fault，而且没有 dump出core之类的东西来的，所以暂时不知道有什么好办法研究出解决方案。。。

**Comment by wanjochan** [comment]
CHN： 在 server启动的外体 增加 一些 高可用的脚本当然可以临时解决问题，不过追求完美是应该总要解决这个问题呢

**Comment by matyhtf** [comment]
贴出你使用的PHP和Swoole版本号

**Comment by wanjochan** [comment]
ubuntu16.06TLS
php 7.0.9
swoole 是（当时）最新的从github clone出的。一开始发现时以为是自己的代码有内存泄漏之类的。
后来用的上面的最简单的暴力烤鸡式测试案例。因为一般要烤 两轮十几个小时才会seg fault。

或者指导一下如何启动测试案例能有core dump之类的？（因为不太熟悉怎么样解决这个 segment fault问题）。

**Comment by wanjochan** [comment]
看到发布了1.8.9-stable，那么周末或者抽个时间烤一下！

**Comment by matyhtf** [comment]
使用 siege 测试未能重现，请遇到此问题后使用gdb跟踪，重新反馈。
