### ISSUE TITLE
Tcp主进程内存不释放，导致内存泄漏

### ISSUE THREAD

**Issue by yaoxiaofeng1989** [swoole/swoole-src#807]
我是用PHP7+Swoole1.8.6起的tcp server（做弹幕服务），设置的process模式，16个rector，32个worker，32个task

服务器是centos系统，8核16G，

做压测的逻辑是这样子的，先挂5000个连接上去，然后再起40个并发发消息，发现没一会儿工夫master进程就已经占用了75%左右的内存了，重启子进程貌似也没有多大效果，内存一直被主进程占用，只有restart内存才释放，照这样的话生产环境不太现实。求解答！

**Comment by matyhtf** [comment]
主进程内存占用过高一般是有大量数据未发送保存在内存缓存区中，请开启心跳检测功能，剔除坏连接。

**Comment by shenzhe** [comment]
是不是只有send, 客户端没有recv

**Comment by yaoxiaofeng1989** [comment]
谢谢韩哥、半桶水，系统里已有心跳检测功能。还想请问下，剔除了坏连接内存就释放了吗？ @matyhtf @shenzhe

**Comment by matyhtf** [comment]
close时会释放所有连接相关的内存资源。
