### ISSUE TITLE
2.0协程版本破坏php程序调用栈

### ISSUE THREAD

**Issue by chenxiaofa** [swoole/swoole-src#809]
测试来看,目前版本的协程.在call_user_func这类函数时,是会破坏堆栈的
这是使用协程前
![image](https://cloud.githubusercontent.com/assets/5044824/17610593/fdb42960-6071-11e6-850a-00a997b15940.png)

协程回来后
![image](https://cloud.githubusercontent.com/assets/5044824/17610570/ce15a9ea-6071-11e6-9d03-4f9c4d37fc0b.png)

测试代码
![image](https://cloud.githubusercontent.com/assets/5044824/17610563/c2f6c4a4-6071-11e6-8b88-a7ac6854300d.png)

**Comment by yangxikun** [comment]
这个问题正在修复中。

**Comment by xyzhu1120** [comment]
如果是php5的话需要使用协程库提供的\Swoole\Coroutine::call_user_func代替，call_user_func_array同样，在php7里面已经解决了这个问题，可以使用原生的call_user_func
