### ISSUE TITLE
swoole在php7.0.9下报错zend_mm_heap corrupted

### ISSUE THREAD

**Issue by alawnchen** [swoole/swoole-src#812]
swoole版本是1.8.7稳定版，打开心跳包检测和守护进程化后，启动websocket服务的时候就会报错zend_mm_heap corrupted。我尝试了一下保留心跳包或者守护进程任意一项都不行。不知道大伙有没有什么好的解决办法？谢谢

**Comment by matyhtf** [comment]
是否安装了OpCache

**Comment by alawnchen** [comment]
@matyhtf 谢谢提点，已经安装了。我查了一下Google，大概找到的方案是export USE_ZEND_ALLOC = 0 还不知道有没有用 待会试试再反馈

**Comment by matyhtf** [comment]
去掉opcache模块再测试一下

**Comment by cq-z** [comment]
php 7.0.10，swoole 1.8.10
环境是ubuntu 运行docker ：php:7-fpm-alpine
也出现这个情况
开启opcache会输出zend_mm_heap corrupted
关闭后不输出但是一样无法启动就是不输出

**Comment by cq-z** [comment]
加大opcache内存就ok了。。。

**Comment by pantaovay** [comment]
PHP 7.0.12, Swoole 1.8.12
Ubuntu 12.04.5 x64

打开OpCache的情况下，启动直接报错：会输出zend_mm_heap corrupted
关闭OpCache的情况下，没有问题

**Comment by matyhtf** [comment]
是Opcache的BUG导致，修改Php.ini加入`opcache.enable_cli=off`关闭opcache
