### ISSUE TITLE
同步阻塞客户端web访问的话就会报错

### ISSUE THREAD

**Issue by zhangya4548** [swoole/swoole-src#819]
`
linux + Apache/2.4.18 (Unix) +  PHP/7.0.4 + swoole version 1.8.8

客户端如果换成是异步非阻塞cli方式运行正常返回mysql连接池返回数据

但是换成是同步阻塞客户端web访问的话就会报错
	
客户端web执行报错
Warning: swoole_client::send(): object is not instanceof swoole_client. in /usr/local/apache/htdocs/swool/lianjiechi_web.php on line 21

Warning: swoole_client::recv(): object is not instanceof swoole_client. in /usr/local/apache/htdocs/swool/lianjiechi_web.php on line 22
bool(false)

客户端代码
<?php
$cli = new swoole_client(SWOOLE_SOCK_TCP, SWOOLE_SOCK_SYNC);
$cli->connect('127.0.0.1',9503,0.5,0);
$cli->send("show tables");
$data = $cli->recv();
var_dump($data);
`

**Comment by matyhtf** [comment]
Apache使用了什么运行模式，可能和内存隔离有关。建议使用php-fpm

**Comment by matyhtf** [comment]
请检查connect、send、recv的返回值
