### ISSUE TITLE
开启了swoole扩展后，php  SSL connect error

### ISSUE THREAD

**Issue by chenyeyuze** [swoole/swoole-src#820]
服务环境是centos apache+php5.3.29
开启了swoole扩展，使用curl请求https的网站就不行了，curl 错误信息：SSL connect error，curl 错误号码35
关闭swoole扩展,就没事了
有没有其他网友出现过这种情况啊
swoole版本：1.8.7

**Comment by matyhtf** [comment]
和swoole无关，是否连接的 openssl 库版本不一致导致的，请使用ldd命令来确认一下。

**Comment by kcloze** [comment]
我这边也遇到这种问题，swole 1.8.13
其他项目也有相同问题：https://github.com/HanSon/vbot/issues/218
