### ISSUE TITLE
swoole_http_server 经过nginx反向  （版本1.8.9-stable）

### ISSUE THREAD

**Issue by Corzcode** [swoole/swoole-src#824]
测试代码使用
https://github.com/swoole/proxy-server/blob/master/http-proxy.php

直接
 curl "http://127.0.0.1:9501/"正常

如果在nginx 做了proxy_pass
curl "http://127.0.0.1/" -H "Host:proxytest.com" 就 coredump

而且coredump内容如下
Core was generated by `php http-proxy.php'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f3c9f5f39cb in ?? ()
"/tmp/php.core.15320" is a core file.
Please specify an executable to debug.
(gdb) bt
#0  0x00007f3c9f5f39cb in ?? ()
#1  0x00007f3c00000000 in ?? ()
#2  0x0000000000000000 in ?? ()

降回1.8.8并没有此问题

**Comment by matyhtf** [comment]
nginx 反向代理 到proxy，proxy又去请求 80端口，产生了 递归死循环

**Comment by Corzcode** [comment]
没有 示例命令是这样写 其实是没循环的curl "http://127.0.0.1/" -H "Host:xxx.com"的

**Comment by matyhtf** [comment]
fixed 
https://github.com/swoole/swoole-src/commit/8a56711d17b81ca2029a7376b8f88e66731152ee
