### ISSUE TITLE
这是是不是应该写2呢，要不然会插入多条记录的

### ISSUE THREAD

**Issue by ColerYu** [swoole/swoole-src#831]
function save()
	{
        if ($this->_change == 0 or $this->_change == 1)
        {
            $ret = $this->db->insert($this->_data, $this->table);
            if ($ret === false)
            {
                return false;
            }
            //改变状态
            $this->_change = 1; // 这是是不是应该写2呢，要不然会插入多条记录的
            $this->_current_id = $this->db->lastInsertId();
        }
        elseif ($this->_change == 2)
        {
            $update = $this->_update;
            unset($update[$this->primary]);
            return $this->db->update($this->_current_id, $update, $this->table, $this->primary);
        }
        return true;
	}

**Comment by matyhtf** [comment]
https://github.com/swoole/framework/commit/0047c92777cfe424e7ebd7e08764783ee94e99ea
