### ISSUE TITLE
Record __destruct 的问题

### ISSUE THREAD

**Issue by ColerYu** [swoole/swoole-src#832]
通过Model的get获得一个Record ，get的定义如下：
	public final function get($object_id = 0, $where = '')
	{
		return new Record($object_id, $this->db, $this->table, $this->primary, $where, $this->select);
	}

function addGood(){
      $a = ...->get()
     $a->content = "content ";
    $a->save();
      $this->goods[$a->_current_id] = $a;
}

当调用 addGood后 会执行两个insert 语句， $a的__destruct 会被调用会执行一次，在__destruct 里会执行一次 save 。save定义如下

	function save()
	{
        if ($this->_change == 0 or $this->_change == 1)
        {
            $ret = $this->db->insert($this->_data, $this->table);
            if ($ret === false)
            {
                return false;
            }
            //改变状态
            $this->_change = 1;
            $this->_current_id = $this->db->lastInsertId();
        }
        elseif ($this->_change == 2)
        {
            $update = $this->_update;
            unset($update[$this->primary]);
            return $this->db->update($this->_current_id, $update, $this->table, $this->primary);
        }
        return true;
	}

因为$this->_change  = 1，所以第二次调用save时还是执行了insert。

问题：1：为什么会执行__destruct呢，有把应用放到数组了的（$this->goods[$a->_current_id] = $a;）
问题：2：为什么会执行2次insert呢

是不是用的不对，正确的用法应该是什么样的呢，谢谢！

**Comment by matyhtf** [comment]
swoole/framework的BUG，在另外一个项目中提交issue
此问题已修复，请更新框架代码。
