### ISSUE TITLE
swoole_http_response::sendfile()  Too many open files[24]

### ISSUE THREAD

**Issue by JetKing** [swoole/swoole-src#833]
用 swoole_http_server 做了一个http服务器（主要是静态文件下载），在测试时发现当收到较长多的请求后会出现 ` Too many open files[24]` 错误。

相关软件环境：
CentOS 7, ulimit -n  1024 ， php: 5.4.16 ，swoole:  1.8.6  

用PHP写了个脚本 **每隔10秒**运行 ` ab -n 200 -c 50 `  一次：
```
date_default_timezone_set('Asia/Shanghai');

for ($i=0; $i < 20; $i++) { 
    $cmd = 'ab -n 200 -c 50 http://127.0.0.1:9600/Data/Files/2016-08-24/1472026786-26717-57bd58a231d27.jpg';
    $r = passthru($cmd); var_dump($r);
    echo date('H:i:s').' -- i='.$i.' sleep '.PHP_EOL;
    sleep(10); // 暂停10秒防止服务器还没处理完上一轮请求
}
```

当执行到第11次时，报 `Too many open files` 错误：
```
PHP Warning:  swoole_http_response::sendfile(): open(/mnt/hgfs/.../ .jpg) failed. Error: Too many open files[24]. in /mnt/hgfs/web/HttpServer.php on line 52
```

服务端相关代码如下：
```
private function sendImage($response, $uri){
        $file = PATH_ROOT.$uri;
        if( !file_exists($file) ){
            $this->writeError($response,404,'404. file:'.$file);
            return false;
        }
        $response->status(200);
        $response->header('Content-Type', 'image/jpeg');
        $response->sendfile($file);  // （52行），提示这一行错误
    }
```

但，如果客户端访问的是不是一个静态文件（ 服务器不会执行 $response->sendfile() ）时， 使用 ab 进行更高更频繁的测试也不会遇到该问题。

难道是 $response->sendfile() 发送文件时打开文件后没有释放吗？ 
还是我在代码中哪里处理错了？

**Comment by matyhtf** [comment]
你可以使用`lsof`查看该进程有哪些fd

**Comment by JetKing** [comment]
用 `lsof` 查看到每访问一次，这个PHP进程就会打开一次文件，一直累加。
![swoole-http-lsof](https://cloud.githubusercontent.com/assets/2010313/18078141/88719742-6ebc-11e6-8bc7-eabbdf84d0c5.jpg)

**Comment by matyhtf** [comment]
新版本中已经修复了这个问题，你可以使用1.8.10, 1.8.11 测试一下。
