### ISSUE TITLE
异步mysql的查询操作，结果集中会返回不明的字符

### ISSUE THREAD

**Issue by nick-william** [swoole/swoole-src#834]
array (
    'userinfoId' => '3789598',
  ),
  10472 => 
  array (
    'userinfoId' => '4101140',
  ),
  10473 => 
  array (
    'userinfoId' => '4882485',
  ),
  10474 => 
  array (
    '?-' => '1357896',
  ),
  10475 => 
  array (
    '?-' => '5486266',
  ),

**Comment by nick-william** [comment]
查询的结果集过多的时候：
[/usr/local/src/swoole-src-1.8.10-stable/swoole_mysql.h:563@mysql_decode_row]n=0, fname=userinfoId, name_length=10

[/usr/local/src/swoole-src-1.8.10-stable/swoole_mysql.h:563@mysql_decode_row]n=0, fname=?-, name_length=10

[/usr/local/src/swoole-src-1.8.10-stable/swoole_mysql.h:563@mysql_decode_row]n=0, fname=userinfoId, name_length=10

**Comment by nick-william** [comment]
多字段的时候，有时候会出现：
2671 => 
  array (
    'friendUserinfoId' => '902083',
    'userinfoId' => '19  ,
  ),
  8210 => 
  array (
    '943571' => '902083',
    '1314635' => '4400525',
  ),

**Comment by nick-william** [comment]
韩老师，能不能解答下上面的问题、、、现在功能卡在这个地方.....

**Comment by matyhtf** [comment]
请贴出你的表结构，以及查询的SQL语句

**Comment by nick-william** [comment]
查询sql：
select friendUserinfoId,userinfoId from friend where friendUserinfoId=902083 and isAttention=1 
表结构：
![image](https://cloud.githubusercontent.com/assets/12269209/18053107/7e15d934-6e30-11e6-9661-fb3a4412512d.png)

这是针对friendUserinfoId=902083这个条件，查询的条数大于10000; 如果加上limit的限制条数的话，或者并发小一点的时候，就不出现上述问题；
不过不管怎样这个问题也是存在，同时也需要获取全部数据。

**Comment by matyhtf** [comment]
这个问题我会跟踪一下。

**Comment by nick-william** [comment]
多谢~~

**Comment by matyhtf** [comment]
fixed https://github.com/swoole/swoole-src/commit/1d4c2f86317c168da76b0cb16831516220f1aabc
