### ISSUE TITLE
swoole-src-1.8.10-stable 没有参数 --enable-async-mysql 

### ISSUE THREAD

**Issue by zanedeng** [swoole/swoole-src#836]
在用到异步数据库的时候用到一个 swoole_get_mysqli_sock 方法。查阅得知需要在编译的时候加入
--enable-async-mysql 参数。但是编译结果显示：
 configure: WARNING: unrecognized options: --enable-async-mysql
求解。。。。。。
谢谢

**Comment by chaegumi** [comment]
1.8.6版本已移除对mysqli和mysqlnd扩展的依赖，并改为内置，无需额外的编译参数开启

**Comment by matyhtf** [comment]
已经内置了，不需要这个编译参数。
