### ISSUE TITLE
动态编译的sockets扩展不能被识别

### ISSUE THREAD

**Issue by garveen** [swoole/swoole-src#837]
最小docker file

```Dockerfile
FROM php:7-fpm-alpine

RUN apk update

RUN apk --no-cache add bash ca-certificates

RUN apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS linux-headers && \
    docker-php-ext-install sockets && \
    pecl bundle -d /tmp/swoole-src swoole && \
    cd /tmp/swoole-src/swoole && \
    phpize && \
    ./configure --enable-sockets && \
    make
```
`docker-php-ext-install`脚本的作用是编译未被内联的扩展成`.so`，然后在`php.ini`里面附加这个文件，并未修改`php_config.h`，所以无法识别

**Comment by matyhtf** [comment]
只有sockets.so是无法编译成功的，必须要有ext/sockets/php_sockets.h头文件。所以建议编译php时设置为`--enable-sockets`

**Comment by garveen** [comment]
使用`pecl`安装的`sockets`扩展会在include目录下加入该文件，是找得到的。除非直接复制so才没有那个头文件。

只要在configure的时候预先测试是否已经有该头文件，并且这个扩展已经开启，就可以先自行
```
#define HAVE_SOCKETS 1
```
然后就能成功和sockets配合了

**Comment by jiahuanle** [comment]
@garveen 你的解决办法能详细一些嘛  我的情况是和你一样的，但我没明白该如何处理，谢谢你了

**Comment by twose** [comment]
@jiahuanle 这个东西开了没什么用
