### ISSUE TITLE
指定swoole错误日志文件如果删掉就不会写了

### ISSUE THREAD

**Issue by iou402** [swoole/swoole-src#839]
经过测试log_file设置的日志文件,如果删除了, 错误日志文件就不会生成了,也就看不到错误日志
如果php中使用rename重命名日志文件 ,那么日志会写到新的名字中,而不是设置的日志文件名

**Comment by matyhtf** [comment]
这是Linux操作系统的特性，你删除文件后，因为有进程引用此文件所以不会真的删除。rename操作只是改变了文件名，但底层的inode仍然是同一个，所以继续写入。

**Comment by matyhtf** [comment]
最新版本增加了重新打开日志文件的特性，你可以向主进程发送 SIGRTMIN 信号，让swoole重新打开日志文件。

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/3f0707529bad35acdd3c3ff7546d23cc5c69df3b
