### ISSUE TITLE
swoole的协议长度处理建议

### ISSUE THREAD

**Issue by lchjczw** [swoole/swoole-src#840]
swoole可以解决大部分协议问题：
- eof结尾
- 固定包头包尾

固定包头包尾，其中可以设置pack的NL参数等来解析数据中的长度字段，但是有些长度可能不是直接存起来的，而是通过计算的，就好像modbus协议，存储的是24个字，其实长度是48字节，并且是数据部分48字节，在加上头部和校验部分，就是56个字节，所以建议：
**package_length_type这个获得的长度值，支持回调函数处理，这样基本上可以实现任何自定义协议类型了**

帮助手册中的说明：
http://wiki.swoole.com/wiki/page/463.html

**Comment by matyhtf** [comment]
无法使用回调函数因为PHP非线程安全，而swoole的reactor线程是运行与多线程环境的。

**Comment by lchjczw** [comment]
哦，要是能设置这个值，可以兼容市面上的协议了，如果这样的话我遇到的这种情况，你们有没有什么解决方式

**Comment by lchjczw** [comment]
能不能通过设置，实现对长度经行操作的，比如添加一个opertion参数 operation=“+12”，表示数据长度+12这种方式来实现呢

**Comment by lchjczw** [comment]
或者添加一个操作的配置选项，具体操作的函数还是用C写，配置选项只是把参数传入
比如说写一个add函数，
int  add(int num){
length += num; //num支持负数
return length;
}

**Comment by lchjczw** [comment]
我之前用你们swoole开发了一个工业设备监测和控制的系统，运行良好，后来遇到一个要用modbus协议的就实现不了了，只能用golang实现了，希望swoole越来越好

**Comment by matyhtf** [comment]
如果swoole不支持，只是你需要自行实现协议解析，并不是说不能用swoole

**Comment by lchjczw** [comment]
这样的话，出现tcp占包什么的，这种密集型计算的，php有点慢，我现在写的里面php还要负责解析二进制数据

**Comment by matyhtf** [comment]
那其实你的建议提供PHP回调函数也需要解析数据才能计算出长度。

**Comment by lchjczw** [comment]
type这个设置选项里面底层应该是做了类似unpack("n",$data)这种功能，也就是长度这个swoole已经解析出来了，比如说是24byte，现在只需要对这个长度值，调用一个函数，做一次修改即可24*2+8=56byte，swoole底层用修改后的这个长度56byte去从socket里面读取数据,这样的话就可以兼容市面上所有 固定包头包体的协议了

**Comment by lchjczw** [comment]
我说的这个回调函数，只是用来修改 帮助手册
http://wiki.swoole.com/wiki/page/463.html

中type获取到的长度值

设置type为n，通过这个n可以得到每次从socket中读取的长度是length，回调函数的功能只是对这个length做一个修改，修改为真实的长度

比如说modbus中长度字段存储的是：数据部分的_字数_，这个通过设置type使可以获取到的，
但是 真实的长度= 数据字数*2+包头长度+校验码

回调函数的作用就是得到真实的长度

比如说：
包头（010002030506）+数据（data）+crc
包头中最后一个字节06表示包体的字长度是6个字，也就是数据部分是12个字节
数据的真实长度是：包头长度+数据长度+校验长度

但是通过swoole设置type=c，设置偏移量为6 得到的是数据部分的长度6个字

不知道描述的清楚不

**Comment by andot** [comment]
@lchjczw 你遇到的这个问题我原来也反馈过，在这里可以查到：https://github.com/swoole/swoole-src/issues/293

**Comment by matyhtf** [comment]
@lchjczw 无法基于配置实现如此复杂的长度解析，近期有一个新的commit，可以写一个C++函数来实现长度解析。

请参考 ： https://github.com/swoole/swoole-src/blob/master/examples/cpp_module/test.cpp

**Comment by lchjczw** [comment]
我写两个通过配置字符串实现修改长度的函数，望采纳

第一个看起来简单容易配置：
第二个更快，配置要麻烦写：

`
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
/**
 * 解析字符串进行计算
 * @param  length 长度
 * @param  oper   操作字符串 在php中只需按照 "+12|*20|-5|*3"，这种形式配置即可
 * @return        无符号整形长度
 */
unsigned int oper(int length, char const * oper){

	int count = strlen(oper);
	char operation;
	
	int oper_num;
	for (int i = 0,j=0; i+j < count; ++i)
	{
		char tmp[4]= {0,0,0,0};
		operation = *(oper+i+j);

		for (++i,j = 0; (*(oper+i+j) != '|')  && (i+j < count) ; ++j) {
			tmp[j] = *(oper+i+j);
		}
		if (i+j > count) { return length; }

		i = i+j;j=0;

		oper_num = atoi(tmp);
		
		switch (operation){
	        case '+':
	        	length += oper_num;
	        	break;
	        case '-':
	        	length -= oper_num;
	        	if (length < 0) { return 0; }
	        	break;
	        case '*':
	        	length *= oper_num;
	        	if (length < 0) { return 0; }
	        	break;

	        default:printf("error\n");
    	}

	}

	return length;
}

/**
 * 解析字符串进行计算
 * @param  length 长度
 * @param  oper   操作字符串 在php中只需按照 "+\xc*\x14-\x5*\x3"，这种形式配置即可
 * @return        无符号整形长度
 */
unsigned int oper_fast(int length, char const * oper){

	int count = strlen(oper);
	char operation;
	
	int oper_num;
	for (int i = 0,j=0; i < count; ++i)
	{
		operation = *(oper+i);
		++i;
		oper_num = (int)*(oper+i);

		switch (operation){
	        case '+':
	        	length += oper_num;
	        	break;
	        case '-':
		        length -= oper_num;
		        if (length < 0) { return 0; }
		        break;
	        case '*':length *= oper_num;
	        	if (length < 0) { return 0; }
		        break;

	        default:printf("error\n");
    	}
		// ++i;

	}

	return length;
}

int main(int argc, char const *argv[])
{
	int length = 10;
	// 传入参数10 通过操作：+12|*20|-5|*3 获得结果：(((10+12)*20)-5)*3 = 1305

	printf("10+12|*20|-5|*3=%d\n", oper(length,"+12|*20|-5|*3"));
	printf("10+12=%d\n",oper(length,"+12"));
	printf("10-2=%d\n",oper(length,"-2"));
	printf("10*2=%d\n",oper(length,"*2"));


	printf("10+12|*20|-5|*3=%d\n", oper2(length,"+\xc*\x14-\x5*\x3"));
	printf("10+12=%d\n",oper2(length,"+\xc"));
	printf("10-2=%d\n",oper2(length,"-\x2"));
	printf("10*2=%d\n",oper(length,"*\x2"));
	return 0;
}

`
