### ISSUE TITLE
基于字符串配置实现复杂的长度解析 望采纳

### ISSUE THREAD

**Issue by lchjczw** [swoole/swoole-src#843]
希望swoole越来越完善````，加班写了两种方式，通过配置字符串，实现复杂的长度解析

我写两个通过配置字符串实现修改长度的函数，望采纳

第一个看起来简单容易配置：
第二个速度更快，配置要麻烦些：

`
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
/**
 * 解析字符串进行计算
 * @param  length 长度
 * @param  oper   操作字符串 在php中只需按照 "+12|*20|-5|*3"，这种形式配置即可
 * @return        无符号整形长度
 */
unsigned int oper(int length, char const * oper){

	int count = strlen(oper);
	char operation;
	
	int oper_num;
	for (int i = 0,j=0; i+j < count; ++i)
	{
		char tmp[4]= {0,0,0,0};
		operation = *(oper+i+j);

		for (++i,j = 0; (*(oper+i+j) != '|')  && (i+j < count) ; ++j) {
			tmp[j] = *(oper+i+j);
		}
		if (i+j > count) { return length; }

		i = i+j;j=0;

		oper_num = atoi(tmp);
		
		switch (operation){
	        case '+':
	        	length += oper_num;
	        	break;
	        case '-':
	        	length -= oper_num;
	        	if (length < 0) { return 0; }
	        	break;
	        case '*':
	        	length *= oper_num;
	        	if (length < 0) { return 0; }
	        	break;

	        default:printf("error\n");
    	}

	}

	return length;
}

/**
 * 解析字符串进行计算
 * @param  length 长度
 * @param  oper   操作字符串 在php中只需按照 "+\xc*\x14-\x5*\x3"，这种形式配置即可
 * @return        无符号整形长度
 */
unsigned int oper_fast(int length, char const * oper){

	int count = strlen(oper);
	char operation;
	
	int oper_num;
	for (int i = 0,j=0; i < count; ++i)
	{
		operation = *(oper+i);
		++i;
		oper_num = (int)*(oper+i);

		switch (operation){
	        case '+':
	        	length += oper_num;
	        	break;
	        case '-':
		        length -= oper_num;
		        if (length < 0) { return 0; }
		        break;
	        case '*':length *= oper_num;
	        	if (length < 0) { return 0; }
		        break;

	        default:printf("error\n");
    	}
		// ++i;

	}

	return length;
}

int main(int argc, char const *argv[])
{
	int length = 10;
	// 传入参数10 通过操作：+12|*20|-5|*3 获得结果：(((10+12)*20)-5)*3 = 1305

	printf("10+12|*20|-5|*3=%d\n", oper(length,"+12|*20|-5|*3"));
	printf("10+12=%d\n",oper(length,"+12"));
	printf("10-2=%d\n",oper(length,"-2"));
	printf("10*2=%d\n",oper(length,"*2"));

	printf("10+12|*20|-5|*3=%d\n", oper_fast(length,"+\xc*\x14-\x5*\x3"));
	printf("10+12=%d\n",oper_fast(length,"+\xc"));
	printf("10-2=%d\n",oper_fast(length,"-\x2"));
	printf("10*2=%d\n",oper_fast(length,"*\x2"));
	return 0;
}

`

**Comment by lchjczw** [comment]
代码中有星号的地方好像被隐藏了，代码应该不能执行了，我明天发一份到qq群吧

**Comment by matyhtf** [comment]
请勿删除issue

**Comment by lchjczw** [comment]
@matyhtf 你能看到完整的代码吗？

**Comment by franktom93** [comment]
I guess couldn't

**Comment by matyhtf** [comment]
@lchjczw 参考https://github.com/swoole/swoole-src/tree/master/examples/c_module ，提供一个C的函数来处理这个长度吧

**Comment by lchjczw** [comment]
通过这个连接下载：https://pan.baidu.com/s/1bK0BLW

**Comment by lchjczw** [comment]
@matyhtf 通过上面的链接下载，直接编译可以执行

**Comment by lchjczw** [comment]
第一种配置采用：操作符+字符， | 分割， 
"+5|-2"：表示先加5再减2，按照顺序执行，没有优先级
第二种采用： 操作符+数值（assic码值对应的数值，通过转义字符直接实现）， 
"+\x5-\x2"：表示先加5再减2，按照顺序执行，没有优先级

**Comment by lchjczw** [comment]
只需要把test_get_length这个函数，换成我发给你这个函数，获取配置，就可以实现在php层面，配置了，功能上稍微简单一些 只支持：加减乘

**Comment by lchjczw** [comment]
我这现在可以通过这个办法解决，不过大部分php程序员，不会搞php扩展
