### ISSUE TITLE
swoole运行两天，在kill进程的时候。出现如下看起来是内存泄漏

### ISSUE THREAD

**Issue by ssdphp** [swoole/swoole-src#844]
/*****************php信息*************/
PHP 7.0.9 (cli) (built: Aug  3 2016 11:12:27) ( NTS DEBUG )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
/*****************end**************************/

/home/download/php/php-7.0.9/Zend/zend_hash.c(135) :  Freeing 0x7F1061264100 (264 bytes)
/home/download/php/swoole-src-1.8.7-stable/swoole_server.c(1327) :  Freeing 0x7F1061266C90 (16 bytes)
/home/download/php/swoole-src-1.8.7-stable/swoole_server.c(262) :  Freeing 0x7F1061266CC0 (16 bytes)
/home/download/php/php-7.0.9/Zend/zend_string.h(121) :  Freeing 0x7F106128C980 (88 bytes)
/home/download/php/php-7.0.9/Zend/zend_string.h(121) :  Freeing 0x7F10612B8320 (40 bytes)
/home/download/php/php-7.0.9/Zend/zend_API.c(1061) :  Freeing 0x7F10612C1AE0 (56 bytes), 
/home/download/php/php-7.0.9/Zend/zend_objects.c(162) :  Freeing 0x7F10612C20F0 (40 bytes), 

/home/download/php/php-7.0.9/Zend/zend_string.h(121) :  Freeing 0x7F10612C9FA0 (40 bytes), 
=== Total 24 memory leaks detected ===

**Comment by matyhtf** [comment]
少量信息无意义，建议进行大规模压测，看看是否存在很大次数的内存泄漏。比如压测请求1万次，泄漏是1万的倍数。
