### ISSUE TITLE
使用 if (new_fd >= serv->max_connection) 来做 too many connection 的判断存在一些问题

### ISSUE THREAD

**Issue by starfalling** [swoole/swoole-src#846]
mcrypt_module_open，mcrypt_module_close 函数看起来不会释放所申请的资源句柄ID，在swoole中如果使用到就会导致 too many connection 而拒绝服务

我是使用下面类似的代码来判定 mcrypt_module_close 不释放句柄 ID 的

```
var_dump(fopen('/tmp/test.txt', 'r'));
for($i=0; $i<10000; $i++){
  $cipher = mcrypt_module_open(MCRYPT_RIJNDAEL_128, '', MCRYPT_MODE_ECB, '');
  mcrypt_module_close($cipher);
}
var_dump(fopen('/tmp/test.txt', 'r'));
```

不知是否有解决办法？

**Comment by matyhtf** [comment]
测试 mcrypt_module_open / mcrypt_module_close 都没有内存泄漏。你fopen的文件需要执行fclose，可以使用lsof -p 来确认fd是否释放。

**Comment by starfalling** [comment]
不是内存泄漏，是 fd 值被放大了，按预期，第一行的  fd 值为5，最后一行的fd值应该为6。但是运行下来，第一行的fd值为5，最后一行的fd值为 10006



**Comment by starfalling** [comment]
如果在请求当中使用了  mcrypt_module_open / mcrypt_module_close ，可能会导致 accept 的 fd 值变大，很快就超出 max_connection 设定，因为没有测试过，我是因为遇到了 too many connection 然后从代码里面猜测的
