### ISSUE TITLE
swoole-table引起的core问题

### ISSUE THREAD

**Issue by badxpgy** [swoole/swoole-src#848]
线上服务偶尔出进程core掉，从core信息来看基本都是指向swoole_table，截取了两个core的信息，
环境：swoole1.8.7  php7.0.4，线上偶尔出现，自测模拟很难重现
1.第一例
   (gdb) bt
   #0  swTable_iterator_forward (table=0x7faff30e93e8) at /tools/swoole-      v1.8.7_by_v8/src/memory/Table.c:303
   #1  0x00000000007ec528 in zend_call_function (fci=0x7fff6c0a3f50, fci_cache=0x7fff6c0a3fa0) at /tools/php7/php-7.0.4/Zend/zend_execute_API.c:879
   #2  0x00000000008175a7 in zend_call_method (object=0x7faff54882d8, obj_ce=<value optimized out>, fn_proxy=<value optimized out>, function_name=0xaeb867 "next", function_name_len=<value optimized out>, retval_ptr=0x0, param_count=0, 
    arg1=0x0, arg2=0x0) at /tools/php7/php-7.0.4/Zend/zend_interfaces.c:104
   #3  0x0000000000817aca in zend_user_it_move_forward (_iter=0x7faff54882a0) at /tools/php7/php-7.0.4/Zend/zend_interfaces.c:234
   #4  0x0000000000872e65 in ZEND_FE_FETCH_R_SPEC_VAR_HANDLER (execute_data=0x7faff5414600) at /tools/php7/php-7.0.4/Zend/zend_vm_execute.h:15890
   #5  0x0000000000837fe0 in execute_ex (ex=<value optimized out>) at /tools/php7/php-7.0.4/Zend/zend_vm_execute.h:417
   #6  0x00000000007ec4b8 in zend_call_function (fci=0x7fff6c0a4210, fci_cache=0x7fff6c0a4190) at /tools/php7/php-7.0.4/Zend/zend_execute_API.c:860
   #7  0x00000000007eca1a in call_user_function_ex (function_table=<value optimized out>, object=<value optimized out>, function_name=<value optimized out>, retval_ptr=<value optimized out>, param_count=<value optimized out>, 
    params=<value optimized out>, no_separation=0, symbol_table=0x0) at /tools/php7/php-7.0.4/Zend/zend_execute_API.c:685
   #8  0x00007faff3e77879 in sw_call_user_function_ex (serv=0x2b441a0, req=<value optimized out>) at /tools/swoole-v1.8.7_by_v8/php7_wrapper.h:229
   #9  php_swoole_onTask (serv=0x2b441a0, req=<value optimized out>) at /tools/swoole-v1.8.7_by_v8/swoole_server.c:777
   #10 0x00007faff3ea8f25 in swProcessPool_worker_loop (pool=0x7faff30e91c0, worker=0x7faff30eb048) at /tools/swoole-v1.8.7_by_v8/src/network/ProcessPool.c:345
   #11 0x00007faff3ea81f7 in swProcessPool_spawn (worker=0x7faff30eb048) at /tools/swoole-v1.8.7_by_v8/src/network/ProcessPool.c:243
   #12 0x00007faff3ead558 in swManager_loop_sync (factory=0x2b445d0) at /tools/swoole-v1.8.7_by_v8/src/network/Manager.c:570
   #13 0x00007faff3eae0b8 in swManager_start (factory=0x2b445d0) at /tools/swoole-v1.8.7_by_v8/src/network/Manager.c:183
   #14 0x00007faff3e9ec72 in swFactoryProcess_start (factory=0x2b445d0) at /tools/swoole-v1.8.7_by_v8/src/factory/FactoryProcess.c:86
   #15 0x00007faff3ea441e in swServer_start (serv=0x2b441a0) at /tools/swoole-v1.8.7_by_v8/src/network/Server.c:645
   #16 0x00007faff3e783fe in zim_swoole_server_start (execute_data=<value optimized out>, return_value=0x7faff54141e0) at /tools/swoole-v1.8.7_by_v8/swoole_server.c:1799
   #17 0x000000000086f988 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7faff5414120) at /tools/php7/php-7.0.4/Zend/zend_vm_execute.h:842
   #18 0x0000000000837fe0 in execute_ex (ex=<value optimized out>) at /tools/php7/php-7.0.4/Zend/zend_vm_execute.h:417
   #19 0x000000000088a91b in zend_execute (op_array=0x7faff547e000, return_value=<value optimized out>) at /tools/php7/php-7.0.4/Zend/zend_vm_execute.h:458
   #20 0x00000000007f9423 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /tools/php7/php-7.0.4/Zend/zend.c:1427
   #21 0x000000000079bf00 in php_execute_script (primary_file=0x7fff6c0a9d30) at /tools/php7/php-7.0.4/main/main.c:2484
   #22 0x000000000088eca3 in do_cli (argc=6, argv=0x29394a0) at /tools/php7/php-7.0.4/sapi/cli/php_cli.c:974
   #23 0x000000000088f44a in main (argc=6, argv=0x29394a0) at /tools/php7/php-7.0.4/sapi/cli/php_cli.c:1345
(gdb) f 0
   #0  swTable_iterator_forward (table=0x7faff30e93e8) at /tools/swoole-v1.8.7_by_v8/src/memory/Table.c:303
   303	                row = row->next;
   (gdb) list
   298	        else
   299	        {
   300	            int i = 0;
   301	            for (;; i++)
   302	            {
   303	                row = row->next;
   304	                if (i == table->iterator->collision_index)
   305	                {
   306	                    if (row == NULL)
   307	                    {
   (gdb) 

2.第二例(出现过3次)：
(gdb) bt
#0  php_swoole_table_row2array (table=0x7faff30e93e8, row=0x0, return_value=0x7faff54b5300) at /tools/swoole-v1.8.7_by_v8/swoole_table.c:154
#1  0x00000000007ec528 in zend_call_function (fci=0x7fff6c0a3fb0, fci_cache=0x7fff6c0a4000) at /tools/php7/php-7.0.4/Zend/zend_execute_API.c:879
#2  0x00000000008175a7 in zend_call_method (object=0x7faff54b52d8, obj_ce=<value optimized out>, fn_proxy=<value optimized out>, function_name=0x897190 "current", function_name_len=<value optimized out>, retval_ptr=0x7faff54b5300, 
    param_count=0, arg1=0x0, arg2=0x0) at /tools/php7/php-7.0.4/Zend/zend_interfaces.c:104
#3  0x0000000000817c1c in zend_user_it_get_current_data (_iter=<value optimized out>) at /tools/php7/php-7.0.4/Zend/zend_interfaces.c:190
#4  0x0000000000872e93 in ZEND_FE_FETCH_R_SPEC_VAR_HANDLER (execute_data=0x7faff5414600) at /tools/php7/php-7.0.4/Zend/zend_vm_execute.h:15904
#5  0x0000000000837fe0 in execute_ex (ex=<value optimized out>) at /tools/php7/php-7.0.4/Zend/zend_vm_execute.h:417
#6  0x00000000007ec4b8 in zend_call_function (fci=0x7fff6c0a4270, fci_cache=0x7fff6c0a41f0) at /tools/php7/php-7.0.4/Zend/zend_execute_API.c:860
#7  0x00000000007eca1a in call_user_function_ex (function_table=<value optimized out>, object=<value optimized out>, function_name=<value optimized out>, retval_ptr=<value optimized out>, param_count=<value optimized out>, 
    params=<value optimized out>, no_separation=0, symbol_table=0x0) at /tools/php7/php-7.0.4/Zend/zend_execute_API.c:685
#8  0x00007faff3e77879 in sw_call_user_function_ex (serv=0x2b441a0, req=<value optimized out>) at /tools/swoole-v1.8.7_by_v8/php7_wrapper.h:229
#9  php_swoole_onTask (serv=0x2b441a0, req=<value optimized out>) at /tools/swoole-v1.8.7_by_v8/swoole_server.c:777
#10 0x00007faff3ea8f25 in swProcessPool_worker_loop (pool=0x7faff30e91c0, worker=0x7faff30eb048) at /tools/swoole-v1.8.7_by_v8/src/network/ProcessPool.c:345
#11 0x00007faff3ea81f7 in swProcessPool_spawn (worker=0x7faff30eb048) at /tools/swoole-v1.8.7_by_v8/src/network/ProcessPool.c:243
#12 0x00007faff3ea86d9 in swProcessPool_start (pool=0x7faff30e91c0) at /tools/swoole-v1.8.7_by_v8/src/network/ProcessPool.c:106
#13 0x00007faff3eae0cf in swManager_start (factory=0x2b445d0) at /tools/swoole-v1.8.7_by_v8/src/network/Manager.c:135
#14 0x00007faff3e9ec72 in swFactoryProcess_start (factory=0x2b445d0) at /tools/swoole-v1.8.7_by_v8/src/factory/FactoryProcess.c:86
#15 0x00007faff3ea441e in swServer_start (serv=0x2b441a0) at /tools/swoole-v1.8.7_by_v8/src/network/Server.c:645
#16 0x00007faff3e783fe in zim_swoole_server_start (execute_data=<value optimized out>, return_value=0x7faff54141e0) at /tools/swoole-v1.8.7_by_v8/swoole_server.c:1799
#17 0x000000000086f988 in ZEND_DO_FCALL_SPEC_HANDLER (execute_data=0x7faff5414120) at /tools/php7/php-7.0.4/Zend/zend_vm_execute.h:842
#18 0x0000000000837fe0 in execute_ex (ex=<value optimized out>) at /tools/php7/php-7.0.4/Zend/zend_vm_execute.h:417
#19 0x000000000088a91b in zend_execute (op_array=0x7faff547e000, return_value=<value optimized out>) at /tools/php7/php-7.0.4/Zend/zend_vm_execute.h:458
#20 0x00000000007f9423 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /tools/php7/php-7.0.4/Zend/zend.c:1427
#21 0x000000000079bf00 in php_execute_script (primary_file=0x7fff6c0a9d30) at /tools/php7/php-7.0.4/main/main.c:2484
#22 0x000000000088eca3 in do_cli (argc=6, argv=0x29394a0) at /tools/php7/php-7.0.4/sapi/cli/php_cli.c:974
#23 0x000000000088f44a in main (argc=6, argv=0x29394a0) at /tools/php7/php-7.0.4/sapi/cli/php_cli.c:1345
(gdb) f 0
#0  php_swoole_table_row2array (table=0x7faff30e93e8, row=0x0, return_value=0x7faff54b5300) at /tools/swoole-v1.8.7_by_v8/swoole_table.c:154
154	                memcpy(&lval, row->data + col->index, 4);
(gdb) list
149	            case SW_TABLE_INT16:
150	                memcpy(&lval, row->data + col->index, 2);
151	                sw_add_assoc_long_ex(return_value, col->name->str, col->name->length + 1, (int16_t) lval);
152	                break;
153	            case SW_TABLE_INT32:
154	                memcpy(&lval, row->data + col->index, 4);
155	                sw_add_assoc_long_ex(return_value, col->name->str, col->name->length + 1, (int32_t) lval);
156	                break;
157	            default:
158	                memcpy(&lval, row->data + col->index, 8);

**Comment by matyhtf** [comment]
迭代器BUG导致的，现在已经修复了。请使用最新的swoole版本。
