### ISSUE TITLE
swoole client网络断线问题

### ISSUE THREAD

**Issue by jocky4012** [swoole/swoole-src#850]
swoole的朋友们，我在开发过程中遇到一些问题，特来请教

问题描述：
我在swoole server中开启了一个子进程，该子进程会创建一个swoole client来连接第三方提供的tcp socket服务，当我手动关闭网络后要隔一段时间才触发onclose事件，而在onclose事件中，当我试图去重连接远程socket服务时，会报一个php warning的警告：
PHP Warning:  swoole_client::connect(): connect to server[ip,port] failed. Error: Network is unreachable[51].

开发环境：
系统：Mac OS X EI Captian
php： php-7.0.6
swoole： swoole-src-1.8.11-stable

问题：
1：如何在网络断开的瞬间，就能在onclose中捕获到这个事件？
2：onerror事件一般都是哪几种原因触发的（我之前以为上面的情况会触发onerror事件，并在该事件中做一些逻辑处理，结果发现该事件并没有被调用）？

感谢各位的解答，谢谢

**Comment by WeijiaNing** [comment]
MAC上面怎么搭建环境呢 哥们

**Comment by WeijiaNing** [comment]
我刚开始接触Mac  以前用的是window 和 linux

**Comment by matyhtf** [comment]
网络断线是无法发出FIN包的，服务器端收不到onClose，onError表示连接失败。
