### ISSUE TITLE
websocket client发往server的数据应该被mask

### ISSUE THREAD

**Issue by jhasheng** [swoole/swoole-src#851]
[RFC6455](https://tools.ietf.org/html/rfc6455#section-5.1)
- The server MUST close the connection upon receiving a frame that is not masked

**Comment by matyhtf** [comment]
感谢你的反馈，已增加一个`websocket_mask`的选项来开启。swoole的WebSocket Client一般是用来连接swoole_websocket_server。swoole_websocket_server是兼容mask和非mask两种格式的。启用mask实际上会有一定的性能消耗，如果仅作为Server间通信没必要使用mask.
