### ISSUE TITLE
open_length_check = true,用 websocket 连接出现 swProtocol_recv_check_length: package is too big  

### ISSUE THREAD

**Issue by ColerYu** [swoole/swoole-src#856]
您好！
我开启了open_length_check = true后用websocket连接服务器会 提示WARNING swProtocol_recv_check_length: package is too big, remote_addr=192.168.1.126:61204, length=1195725860.然会就被关掉了

配置服务器
        $this->serv = new swoole_server("0.0.0.0", 9501);
        $this->serv->set(array(
            'worker_num' => 8,
            'daemonize' => false,
            'max_request' => 10000,
            'dispatch_mode' => 2,
            'package_max_length' => 8192,
            'open_length_check'=> false,
            'package_length_offset' => 0,
            'package_body_offset' => 4,
            'package_length_type' => 'N'
        ));

在php理用 new swoole_client(SWOOLE_SOCK_TCP); 去连接是正常的
设置 open_length_check = false 再用websocket连接服务器收到的信息是：
Client 1 connect
Length = 1195725856
Get Message From Client 1:GET / HTTP/1.1
Host: 192.168.1.136:9501
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: http://192.168.1.126
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-CN,zh;q=0.8
Cookie: PHPSESSID=c57e79beb330da806cb1f11cb5fa6004
Sec-WebSocket-Key: 5Yyiw+6az0EjoTcRPRj8+A==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

谢谢！（用的是 1.8.5 stable）

**Comment by matyhtf** [comment]
websocket使用`swoole\websocket\server`不要使用`open_length_check`
