### ISSUE TITLE
Error in `php': double free or corruption (!prev)

### ISSUE THREAD

**Issue by yongchuan** [swoole/swoole-src#861]
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fc1f9729067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007fc1f9729067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fc1f972a448 in __GI_abort () at abort.c:89
#2  0x00007fc1f97671b4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fc1f985c210 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007fc1f976c98e in malloc_printerr (action=1, str=0x7fc1f985c318 "double free or corruption (!prev)", ptr=<optimized out>) at malloc.c:4996
#4  0x00007fc1f976d696 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007fc1fbddf58d in CRYPTO_free () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#6  0x00007fc1fbe690f7 in sk_free () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#7  0x00007fc1fbb499a9 in SSL_SESSION_free () from /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
#8  0x00007fc1fbe69b3c in lh_doall_arg () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#9  0x00007fc1fbb4af27 in SSL_CTX_flush_sessions () from /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
#10 0x00007fc1fbb23e41 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
#11 0x00007fc1f6f014ee in swSSL_accept (conn=0x7fc1f3fabc88) at /soft/swoole-src-1.8.11-stable/src/protocol/SSL.c:344
#12 0x00007fc1f6ef5431 in swReactorThread_verify_ssl_state (port=<optimized out>, conn=<optimized out>, reactor=<optimized out>)
    at /soft/swoole-src-1.8.11-stable/src/network/ReactorThread.c:88
#13 swReactorThread_onRead (reactor=0x7fc1f5f364b0, event=0x7fc1f3175e00) at /soft/swoole-src-1.8.11-stable/src/network/ReactorThread.c:813
#14 0x00007fc1f6eec133 in swReactorEpoll_wait (reactor=0x7fc1f5f364b0, timeo=0x26df) at /soft/swoole-src-1.8.11-stable/src/reactor/ReactorEpoll.c:259
#15 0x00007fc1f6ef7091 in swReactorThread_loop_stream (param=0x26dd) at /soft/swoole-src-1.8.11-stable/src/network/ReactorThread.c:1190
#16 0x00007fc1f94df0a4 in start_thread (arg=0x7fc1f3176700) at pthread_create.c:309
#17 0x00007fc1f97dc62d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
swoole ssl这个问题有人遇到过吗？

**Comment by matyhtf** [comment]
升级一下openssl的版本试试。

**Comment by yongchuan** [comment]
OpenSSL 1.0.1t  3 May 2016
这个版本的openssl应该算是新的了

**Comment by matyhtf** [comment]
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
