### ISSUE TITLE
段错误(jemalloc)

### ISSUE THREAD

**Issue by yongchuan** [swoole/swoole-src#863]
#0  0x00007f7e30e9f35a in free () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#1  0x00007f7e3112dcd8 in swPort_free (port=0x7f7e3014d358) at /soft/swoole-src-1.8.11-stable/src/network/Port.c:540
#2  0x00007f7e3111e938 in swServer_free (serv=0x7f7e2fccc400) at /soft/swoole-src-1.8.11-stable/src/network/Server.c:784
#3  0x00007f7e3111f92b in swServer_start (serv=0x7f7e2fccc400) at /soft/swoole-src-1.8.11-stable/src/network/Server.c:663
#4  0x00007f7e310f087d in zim_swoole_server_start (ht=<optimized out>, return_value=0x7f7e30c77300, return_value_ptr=<optimized out>, this_ptr=<optimized out>, 
    return_value_used=<optimized out>) at /soft/swoole-src-1.8.11-stable/swoole_server.c:1864
#5  0x00000000006e29ca in dtrace_execute_internal ()
#6  0x00000000007a2c30 in ?? ()
#7  0x0000000000730fc0 in execute_ex ()
#8  0x00000000006e2868 in dtrace_execute_ex ()
#9  0x00000000007a3173 in ?? ()
#10 0x0000000000730fc0 in execute_ex ()
#11 0x00000000006e2868 in dtrace_execute_ex ()
#12 0x00000000006f53b0 in zend_execute_scripts ()
#13 0x0000000000690c90 in php_execute_script ()
#14 0x00000000007a4be0 in ?? ()
#15 0x0000000000462a5d in main ()

**Comment by matyhtf** [comment]
jemalloc导致的，已修复。
