### ISSUE TITLE
websocket异步客户端生成的sec-websocket-key不正确

### ISSUE THREAD

**Issue by zszyue** [swoole/swoole-src#864]
客户端数据
[requestHeaders] => Array
        (
            [Connection] => Upgrade
            [Upgrade] => websocket
            [Sec-WebSocket-Key] => AHFOUlFybT1BXXBjKUlsSQA=
        )
Sec-WebSocket-Key 解出来成17位的值了

**Comment by matyhtf** [comment]
PHP7吗？
