### ISSUE TITLE
使用websocket server 报错： php: /home/ubuntu/swoole-src-1.8.10-stable/src/protocol/Base.c:172: swProtocol_recv_check_length: Assertion `remaining_length < sizeof(swap)' failed.

### ISSUE THREAD

**Issue by xujiajun** [swoole/swoole-src#872]
hi，

在使用websocket server 的时候  报错：

![image](https://cloud.githubusercontent.com/assets/6065007/19256538/7550d96c-8f9a-11e6-8a69-dda232f0f361.png)

谁给我点帮助  谢谢。

**Comment by matyhtf** [comment]
连接关闭导致的，已修复。
https://github.com/swoole/swoole-src/commit/403e9a74022265c4671bcfa3e335a6ee06bda70d

**Comment by matyhtf** [comment]
使用 `1.8.13-alpha` 测试一下
