### ISSUE TITLE
异步客户端启用长度检测后，协议长度支持最大2M但是当收到的数据长度大于65535时就会报错。

### ISSUE THREAD

**Issue by TrailHuang** [swoole/swoole-src#874]
swoole 版本1..8.12

SW_BUFFER_SIZE 这个长度为65535

php: /home/langdi/web/swoole-src-1.8.12-stable/src/protocol/Base.c:176: swProtocol_recv_check_length: Assertion `remaining_length < sizeof(swap)' failed.
[2016-10-11 10:49:38 $28199.0]  WARNING swManager_check_exit_status: worker#0 abnormal exit, status=0, signal=6

**Comment by matyhtf** [comment]
由于连接关闭导致的，现在已经解决了。

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/403e9a74022265c4671bcfa3e335a6ee06bda70d
see Issue#873
