### ISSUE TITLE
PHP 7.0.5 swoole zend_mm_heap corrupted 

### ISSUE THREAD

**Issue by domyway** [swoole/swoole-src#880]
@matyhtf  
和#678这个问题一样，我下载的最新1.8.12版本，我这里跑还是报错。
https://github.com/swoole/swoole-src/issues/678

PHP 7.0.5 (cli) (built: Apr 23 2016 17:36:25) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

php -r "echo SWOOLE_VERSION;"
1.8.12

Linux test 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

test.php文件
[test.php.zip](https://github.com/swoole/swoole-src/files/528648/test.php.zip)

**Comment by domyway** [comment]
我发现只要我在配置的时候设置 dispatch_mode 或者 debug_mode 任何一个参数，就会报错，我看了文档dispatch_mode默认是2，我设置成2也不行。  但是只要我这2个参数都不设置，demo就正常start了

**Comment by domyway** [comment]
我发现只要我在配置的时候设置 dispatch_mode 或者 debug_mode 任何一个参数，就会报错，我看了文档dispatch_mode默认是2，我设置成2也不行。  但是只要我这2个参数都不设置，demo就正常start了

**Comment by matyhtf** [comment]
opcache的BUG导致，修改php.ini加入`opcache.enable_cli=0 `关闭opcache
