### ISSUE TITLE
PHP 7.0.12, Swoole 1.8.12 启动报错：zend_mm_heap corrupted

### ISSUE THREAD

**Issue by pantaovay** [swoole/swoole-src#881]
## 环境

PHP 7.0.12, Swoole 1.8.12
Ubuntu 12.04.5 x64

## 现象

打开OpCache的情况下，启动直接报错：会输出zend_mm_heap corrupted
关闭OpCache的情况下，没有问题

**Comment by matyhtf** [comment]
opcache的BUG导致，修改php.ini加入`opcache.enable_cli=0 `关闭opcache
