### ISSUE TITLE
SIGRTMIN not create a new log file

### ISSUE THREAD

**Issue by pbromb** [swoole/swoole-src#884]
Hi,
Run server daemonize mode and save print to log file.

When deleted log file and send signal 
`kill -SIGRTMIN pid_master`

not create a new file

**Comment by matyhtf** [comment]
Is there writable?

**Comment by pbromb** [comment]
Yes.

Example server:
<?php

$serv = new swoole_server("127.0.0.1", 9501);
$serv->set(array(
    'worker_num' => 1, 
    'daemonize' => true, 
    'log_file' => 'test.log'
));
$serv->on('connect', function ($serv, $fd){
    echo "Client:Connect.\n";
});
$serv->on('receive', function ($serv, $fd, $from_id, $data) {
    $serv->send($fd, 'Swoole: '.$data);
    $serv->close($fd);
});
$serv->on('close', function ($serv, $fd) {
    echo "Client: Close.\n";
});

$serv->addprocess(new swoole_process(function (swoole_process $worker) {
	swoole_timer_tick(5000, function () {
		echo 'print' . PHP_EOL;
	});
}, false));

$serv->start();
?>

When is running server, creating test.log, but next delete this file and send signal not recreated file.
