### ISSUE TITLE
swoole_client_select 不修改输入参数 $read 

### ISSUE THREAD

**Issue by cecil2** [swoole/swoole-src#885]
在PHP 7.0.10 (cli) 环境中执行如下代码 (swoole version 1.8.12)，无论swoole_client_select返回的个数是多少，输入参数的$read 的count个数都不会改变，这是正确的行为吗？

<?php
$clients = array();

for($i=0; $i< 200; $i++)
{
    $client = new swoole_client(SWOOLE_SOCK_TCP, SWOOLE_SOCK_SYNC); //同步阻塞
    $ret = $client->connect('www.qq.com', 80, 0.5, 0);
    if(!$ret)
    {
        echo "Connect Server fail.errCode=".$client->errCode;
    }
    else
    {
        $client->send("HELLO WORLD\n");
        $clients[$client->sock] = $client;
    }
}

while (!empty($clients))
{
    $write = $error = array();
    $read = array_values($clients);
    $n = swoole_client_select($read, $write, $error);
    if ($n > 0)
    {
        //  这里 count ($read) 的返回不会改变，这是对的吗？
        echo $n . "\t" . count($read) . "\t" . count($write) . "\t" . count($error) . PHP_EOL;
        foreach ($read as $index => $c)
        {
            // echo "Recv #{$c->sock}: " . $c->recv() . "\n";
            unset($clients[$c->sock]);
        }
    }
}

**Comment by matyhtf** [comment]
PHP7下存在BUG，已修复。
