### ISSUE TITLE
centos6.6+swoole1.8.10+php7.08环境下碰到一个问题会让master进程挂掉,以下是GDB抓到的信息

### ISSUE THREAD

**Issue by eifeldeng** [swoole/swoole-src#886]
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb61fc700 (LWP 12248)]
swReactorThread_onRead (reactor=0x7fffebfd99a0, event=<value optimized out>) at /var/tmp/swoole-src-1.8.13-alpha/src/network/ReactorThread.c:811
811     return port->onRead(reactor, port, event);
(gdb)
(gdb)
(gdb)
(gdb)
(gdb)
(gdb)
(gdb)
(gdb)
(gdb) bt
#0  swReactorThread_onRead (reactor=0x7fffebfd99a0, event=<value optimized out>) at /var/tmp/swoole-src-1.8.13-alpha/src/network/ReactorThread.c:811
#1  0x00007fffec220700 in swReactorEpoll_wait (reactor=0x7fffebfd99a0, timeo=<value optimized out>) at /var/tmp/swoole-src-1.8.13-alpha/src/reactor/ReactorEpoll.c:258
#2  0x00007fffec22a180 in swReactorThread_loop_stream (param=<value optimized out>) at /var/tmp/swoole-src-1.8.13-alpha/src/network/ReactorThread.c:1182
#3  0x00007ffff54989d1 in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff5bb38fd in clone () from /lib64/libc.so.6

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/commit/7f53d1e1f3a404910c6ddc3f7b9fbed0bbf16f08
