### ISSUE TITLE
Empty $post property in swoole_http_request

### ISSUE THREAD

**Issue by zeran86** [swoole/swoole-src#887]
I got empty $post property in **swoole_http_request** when handling **POST** request with **swoole_http_server**.

_PHP Notice:  Undefined property: swoole_http_request::$post_
Example: http://joxi.ru/4AkpzQ7IMv8yRr

**$post** property exists only if content-type = application/x-www-form-urlencoded
So i can not send custom body (for example **JSON**)

Also there are no POSTed body in any property of swoole_http_request
Would be great to have access to raw POSTed body, like file_get_contents('php://input')

**Comment by matyhtf** [comment]
Use the `$request->rawContent()` method.
