### ISSUE TITLE
设置open_eof_check ，服务端还是多次收到Receive回调

### ISSUE THREAD

**Issue by zouli0731** [swoole/swoole-src#888]

**Comment by zouli0731** [comment]
设置了eof参数
'open_eof_check' => true, //打开EOF检测
 'package_eof' => "\r\n", //设置EOF

client->send($data2k.'\r\n');
还是出现接受到多次调用onReceive的情况
1.8.12

**Comment by zouli0731** [comment]
服务端
#!/usr/bin/env php
<?php
$serv = new swoole_server('127.0.0.1', 9513);
$eof = "__END";
$serv->set([
    'worker_num' => 4,
    'open_eof_check' => true, //打开EOF检测
    'package_eof' => $eof, //设置EOF
]);

$serv->on('Receive', function (swoole_server $serv, $fd, $from_id, $data) {
    var_dump($fd);
    var_dump(strlen($data));
});
$serv->start();


客户端

#!/usr/bin/env php
<?php
$client = new \swoole_client(SWOOLE_SOCK_TCP);
if (!$client->connect('127.0.0.1', 9513, 1)) {
    echo "can't connect swoole server";
} else {
    $eof = "__END";
    $data = array();
    for ($i = 1; $i < 10000; $i++) {
        $data[$i] = rand(000000,999999);
    }
    $dataString = json_encode($data);
    var_dump(strlen($dataString));

    $client->send($dataString . $eof);
    echo $client->recv() . "\n";
}
exit();
执行客户端 会出现  多次触发 Receive 

客户端输出   （app/client.php ）

int(137754)
PHP Warning:  swoole_client::recv(): recv() failed. Error: Resource temporarily unavailable [35] in /Users/zouli/www/edusoho/app/client.php on line 16

Warning: swoole_client::recv(): recv() failed. Error: Resource temporarily unavailable [35] in /Users/zouli/www/edusoho/app/client.php on line 16

服务端输出
int(1)
int(2036)
int(1)
int(2036)
int(1)
int(2036)
int(1)
int(2036)
int(1)
int(2036)
int(1)
int(2036)
int(1)
int(2036)
int(1)
int(2036)
int(1)
int(2036)
int(1)
int(2036)
int(1)
int(2036)
int(1)
int(2036)
.....

swoole版本
swoole

swoole support => enabled
Version => 1.8.12
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
rwlock => enabled
async http/websocket client => enabled
pcre => enabled
zlib => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by zouli0731** [comment]
这个是用法有问题吗？要怎么使用？

**Comment by matyhtf** [comment]
请使用`'open_eof_split' => true`
