### ISSUE TITLE
suse系统，运行swoole_table时存在问题，不支持foreach

### ISSUE THREAD

**Issue by badxpgy** [swoole/swoole-src#890]
环境：php7.0.4+swoole.1.8.7
系统版本：
Linux version 2.6.32.57-tlinux_xenU-1.1.rc8-default (root@test) (gcc version 4.1.2 20070115 (prerelease) (SUSE Linux)) #1 SMP Wed Feb 20 15:20:53 CST 2013
示例代码：
`$admin_table = new swoole_table(200);
$admin_table->column('cnt', swoole_table::TYPE_INT, 8); //mid
$admin_table->create();
$admin_table->set("aa", ['cnt'=>1]);
$admin_table->set("bb", ['cnt'=>1]);
$admin_table->set("cc", ['cnt'=>1]);
foreach ($admin_table as $id=>$val){
	var_dump($id,$val);
}
echo "exit";`

var_dump不会有任何东西输出

**Comment by matyhtf** [comment]
检查是否有pcre支持，`php --ri swoole`

**Comment by badxpgy** [comment]
@matyhtf 确实是pcre的问题，重新安装pcre-devel就可以了，
