### ISSUE TITLE
Asynchronous mysql return error of the result set

### ISSUE THREAD

**Issue by nick-william** [swoole/swoole-src#891]
> SHOW CREATE TABLE test_table 
> 
> CREATE TABLE `test_table`(
>   `id` int(11) NOT NULL AUTO_INCREMENT,
>   `userinfoId` int(11) NOT NULL ,
>   `fanUserinfoId` int(11) NOT NULL ,
>   `isAttention` tinyint(1) NOT NULL DEFAULT '1',
>   `isDisturb` tinyint(1) unsigned NOT NULL DEFAULT '1' ,
>   `extend` text NOT NULL ,
>   `createTime` int(11) NOT NULL,
>   `updateTime` int(11) NOT NULL,
>   PRIMARY KEY (`id`,`userinfoId`),
>   UNIQUE KEY `userinfoId_2` (`userinfoId`,`fanUserinfoId`),
>   KEY `userinfoId` (`userinfoId`,`isAttention`),
>   KEY `updateTime` (`updateTime`)
> ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

The query statement is :  select \* from test_table where userinfoId = 100 and isAttention = 1

Incorrect results show as follows, when the result set returned data is greater than 2000。

> array (
>   'id' => '134920940',
>   'userinfoId' => '100',
>   'fanUserinfoId' => '663568',
>   'isAttention' => '1',
>  'extend' => '',
>   'createTime' => '1477291126',
>   'updateTime' => '23561190',
> )
> array(
>   'id' => '134920940',
>   'userinfoId' => '100',
>   'fanUserinfoId' => '663568',
>   'isAttention' => '1',
>   'isDisturb' => '1',
>   'extend' => '',
>   'createTime' => '1477291126',
>   'updateTime' => '23561190',
> )
> .....(skip)
> array (
>   '' => '530185',
>   'usQ' => '100',
>   'isAttention' => '1',
>   'isDisturb' => '1',
>   'extend' => '',
>   'createTime' => '1477291126',
>   'updateTime' => '23563305',
> )
> array (
>   '' => '639249',
>   'usQ' => '100',
>   'isAttention' => '1',
>   'isDisturb' => '1',
>   'extend' => '',
>   'createTime' => '1477291126',
>   'updateTime' => '23566263',
> )

**Comment by matyhtf** [comment]
What is your swoole version?

**Comment by nick-william** [comment]
swoole

swoole support => enabled
Version => 1.8.12
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
sockets => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => 1 => 1
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by nick-william** [comment]
PHP 7.0.7 (cli) (built: May 28 2016 08:26:36) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by nick-william** [comment]
I have closed the opcode

**Comment by matyhtf** [comment]
`Unknown column 'fanUserinfoId' in 'field list' `

**Comment by matyhtf** [comment]
I cannot reproduce this bug.

**Comment by nick-william** [comment]
sorry about that ; I have revised the table structure， show as follows：

> CREATE TABLE `test_table`(
> id int(11) NOT NULL AUTO_INCREMENT,
> userinfoId int(11) NOT NULL ,
> fanUserinfoId int(11) NOT NULL ,
> isAttention tinyint(1) NOT NULL DEFAULT '1',
> isDisturb tinyint(1) unsigned NOT NULL DEFAULT '1' ,
> extend text NOT NULL ,
> createTime int(11) NOT NULL,
> updateTime int(11) NOT NULL,
> PRIMARY KEY (id,userinfoId)
> ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

And, data in table test_table, there are 162065638 rows; 

In debug mode some output like this :

[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=0, fname=id, name_length=2
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=1, fname=userinfoId, name_length=10
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=2, fname=fanUserinfoId, name_length=13
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=3, fname=isAttention, name_length=11
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=4, fname=isDisturb, name_length=9
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=5, fname=extend, name_length=6
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=6, fname=createTime, name_length=10
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=7, fname=updateTime, name_length=10




[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=0, fname=, name_length=2
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=1, fname=usQ, name_length=10
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=2, fname=fanUserinfoId, name_length=13
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=3, fname=isAttention, name_length=11
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=4, fname=isDisturb, name_length=9
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=5, fname=extend, name_length=6
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=6, fname=createTime, name_length=10
[/usr/local/src/swoole-src-1.8.12-stable/swoole_mysql.h:564@mysql_decode_row]n=7, fname=updateTime, name_length=10

**Comment by nick-william** [comment]
The php script show as follow ：

> $handle = new \Swoole\MySQL;
> $handle->connect([
>     'host' => '127.0.0.1',
>     'user' => 'root',
>     'port' => '3306',
>     'password' => '123456',
>     'database' => 'test',
> ], function ($db, $r) {
>     if ($r === false) {
>         var_dump($db->connect_errno, $db->connect_error);
>         die;
>     }
>     $sql = 'select * from test_table where userinfoId = 1 and isAttention = 1';
>     $db->query($sql, function (\Swoole\MySQL $_db, $_rows) use ($sql) {
>         foreach ($_rows as $row) {
>             file_put_contents('debug.log', var_export($row, true), FILE_APPEND);
>         }
>     });
> });
>

**Comment by matyhtf** [comment]
Try add `limit 2000`

**Comment by nick-william** [comment]
OK, Wait a moment~~
I'll try now

**Comment by nick-william** [comment]
Well, Query with limit 2000 is ok;
But ,If I use two asynchronous query executed in parallel, there are still some problems:
array (
  '' => '11288',
  'usQ' => '28514',
  'isAttention' => '1',
  'isDisturb' => '1',
  'extend' => '',
  'createTime' => '1477290973',
  'updateTime' => '10178',
)
array (
  '' => '7003',
  'usQ' => '9354',
  'isAttention' => '1',
  'isDisturb' => '1',
  'extend' => '',
  'createTime' => '1477290973',
  'updateTime' => '10179',
)

**Comment by nick-william** [comment]
php script like this :

$handle = new \Swoole\MySQL;
$handle->connect([
    'host' => '127.0.0.1',
    'user' => 'root',
    'port' => '3306',
    'password' => '123456',
    'database' => 'test',
], function ($db, $r) {
    if ($r === false) {
        var_dump($db->connect_errno, $db->connect_error);
        die;
    }
    $sql = 'select * from test_table limit 2000';
    $db->query($sql, function (\Swoole\MySQL $_db, $_rows) use ($sql) {
        foreach ($_rows as $row) {
            file_put_contents('debug.log', var_export($row, true), FILE_APPEND);
        }
    });
});
$handle2 = new \Swoole\MySQL;
$handle2->connect([
    'host' => '127.0.0.1',
    'user' => 'root',
    'port' => '3306',
    'password' => '123456',
    'database' => 'test',
], function ($db, $r) {
    if ($r === false) {
        var_dump($db->connect_errno, $db->connect_error);
        die;
    }
    $sql = 'select * from test_table  limit 2000';
    $db->query($sql, function (\Swoole\MySQL $_db, $_rows) use ($sql) {
        foreach ($_rows as $row) {
            file_put_contents('debug.log', var_export($row, true), FILE_APPEND);
        }
    });
});

**Comment by nick-william** [comment]
This is a bug, or my operation problem ?
If this is my question, please let me know.
 @matyhtf
