### ISSUE TITLE
work proces高并发长期出现TASK_UNINTERRUPTIBLE状态

### ISSUE THREAD

**Issue by liugaohua** [swoole/swoole-src#893]
`
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND

root     11155  0.0  0.8 296692  8532 ?        D    04:26   0:00 worker process
`
长期处在这个状态,无法结束

**Comment by matyhtf** [comment]
检查磁盘状态，D的状态表示等待系统资源，一般是无法写入磁盘。

**Comment by liugaohua** [comment]
谢谢,是的,是多个请求写日志,造成的.

**Comment by liugaohua** [comment]
swoole有没有异步写日志功能?asyncio现在可以生产环境?

**Comment by matyhtf** [comment]
虽然有但是解决不了你的问题，AsyncIO也是用多线程同步阻塞模拟的。
