### ISSUE TITLE
2.0协程例子跑不通,是BUG吗？

### ISSUE THREAD

**Issue by sexdon** [swoole/swoole-src#898]
`$tarIp="127.0.0.1";
$server = new Swoole\Http\Server("127.0.0.1", 80, SWOOLE_BASE);
$server->set([
    'worker_num' => 1,
]);
 
swoole_async_dns_lookup("test.com", function($host, $ip) use($tarIp){
    $tarIp=$ip;
    echo "target: $ip";
});
 
$server->on('Request', function($request, $response) use($tarIp){                                                                    
    $httpclient = new Swoole\Coroutine\Http\Client($tarIp, 80);
    $httpclient->setHeaders(['Host' => 'test.com']);
    $httpclient->set(['timeout' => 1]);
    $httpclient->setDefer();
    $httpclient->get('/huodong/test/testFun', function($cli) use($httpclient){
        print_r($cli->body);
    }); 
 
    $http_res = $httpclient->recv();
    $response->end('Test End');
 
 
});
 
$server->start();`

 报错：
`ERROR	swServer_create (ERROR 9001): The swoole_server must create before client
PHP Fatal error:  Swoole\Http\Server::start(): create server failed. Error: swServer_create (ERROR 9001): The swoole_server must create before client in /var/www/workspace/Rclient.php on line 29

Fatal error: Swoole\Http\Server::start(): create server failed. Error: swServer_create (ERROR 9001): The swoole_server must create before client in /var/www/workspace/Rclient.php on line 29`

环境是：ubuntu14.04 php56.27 swoole2.01

**Comment by seumadwolf** [comment]
server启动之前不可以用协程

**Comment by sexdon** [comment]
把$server->start(); 放到前面去也报错啊

挪到on之前 $server->start();
`
PHP Fatal error:  Swoole\Http\Server::start(): require onRequest callback in /var/www/workspace/Rclient.php on line 14

Fatal error: Swoole\Http\Server::start(): require onRequest callback in /var/www/workspace/Rclient.php on line 14
`

**Comment by matyhtf** [comment]
swoole_async_dns_lookup 必须放到回到函数中。
