### ISSUE TITLE
段错误

### ISSUE THREAD

**Issue by wangdianwen** [swoole/swoole-src#899]
Core was generated by `php soa_client.php'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f2ea6f22a7a in php_swoole_client_new (object=0x7f2eb1c14490, host=<value optimized out>, host_len=<value optimized out>, port=<value optimized out>) at /usr/local/src/swoole-src/swoole_client.c:721
721	    zend_update_property_long(swoole_client_class_entry_ptr, object, ZEND_STRL("sock"), cli->socket->fd TSRMLS_CC);
Missing separate debuginfos, use: debuginfo-install php70w-cli-7.0.11-1.w6.x86_64
(gdb) bt
#0  0x00007f2ea6f22a7a in php_swoole_client_new (object=0x7f2eb1c14490, host=<value optimized out>, host_len=<value optimized out>, port=<value optimized out>) at /usr/local/src/swoole-src/swoole_client.c:721
#1  0x00007f2ea6f253e4 in zim_swoole_client_connect (execute_data=0x7f2eb1c14470, return_value=0x7f2eb1c14160) at /usr/local/src/swoole-src/swoole_client.c:855
#2  0x00000000005d60f9 in dtrace_execute_internal ()
#3  0x000000000065c832 in ?? ()
#4  0x0000000000624430 in execute_ex ()
#5  0x00000000005d623e in dtrace_execute_ex ()
#6  0x000000000065c6aa in ?? ()
#7  0x0000000000624430 in execute_ex ()
#8  0x00000000005d623e in dtrace_execute_ex ()
#9  0x000000000065c6aa in ?? ()
#10 0x0000000000624430 in execute_ex ()
#11 0x00000000005d623e in dtrace_execute_ex ()
#12 0x000000000065c6aa in ?? ()
#13 0x0000000000624430 in execute_ex ()
#14 0x00000000005d623e in dtrace_execute_ex ()
#15 0x000000000065c6aa in ?? ()
#16 0x0000000000624430 in execute_ex ()
#17 0x00000000005d623e in dtrace_execute_ex ()
#18 0x0000000000677c1b in zend_execute ()
#19 0x00000000005e4bd3 in zend_execute_scripts ()
#20 0x0000000000585b50 in php_execute_script ()
#21 0x000000000067befa in ?? ()
#22 0x000000000067c6fa in ?? ()
#23 0x00000030f781ed5d in __libc_start_main () from /lib64/libc.so.6
#24 0x0000000000429519 in _start ()
(gdb) f 1
#1  0x00007f2ea6f253e4 in zim_swoole_client_connect (execute_data=0x7f2eb1c14470, return_value=0x7f2eb1c14160) at /usr/local/src/swoole-src/swoole_client.c:855
855	    cli = php_swoole_client_new(getThis(), host, host_len, port);
(gdb) f 0
#0  0x00007f2ea6f22a7a in php_swoole_client_new (object=0x7f2eb1c14490, host=<value optimized out>, host_len=<value optimized out>, port=<value optimized out>) at /usr/local/src/swoole-src/swoole_client.c:721
721	    zend_update_property_long(swoole_client_class_entry_ptr, object, ZEND_STRL("sock"), cli->socket->fd TSRMLS_CC);
(gdb)

**Comment by matyhtf** [comment]
swoole，php 版本多少

**Comment by matyhtf** [comment]
本地无法重现，git pull后需要Make clean清理历史的文件，重新编译。
