### ISSUE TITLE
swoole 缺少判断 当前connection 的发送缓冲区是否可用的一个属性

### ISSUE THREAD

**Issue by liaozibo** [swoole/swoole-src#900]
[http://wiki.swoole.com/wiki/page/440.html](http://wiki.swoole.com/wiki/page/440.html)
根据文档所说：
> 发送缓冲区塞满导致send失败，只会影响当前fd的客户端，其他客户端不受影响
服务器有大量TCP连接时，最差的情况下将会占用serv->max_connection * buffer_output_size字节的内存

这里假设的是用swoole来做代理（比如ss代理），客户端接收消息的情况带宽情况等服务端是获取不到的，只有通过缓冲区来判断 数据收发情况。
当 当前 连接的 fd 发送端缓冲区满后 ，我服务端做了暂停send之后，swoole未能提供一个 “属性” 来判断当前发送缓冲区的数据是否已经发送完毕，可以再次调用send向客户端发送数据。(我在文档里面找很久也未见)
求指教...

**Comment by matyhtf** [comment]
1.9.0 增加了缓存区事件，可以基于事件通知实现缓存区控制。
