### ISSUE TITLE
v1.8.14-alpha 最新版 bufferFull bufferEmpty 服务端，客户端均提示无此回调函数

### ISSUE THREAD

**Issue by liaozibo** [swoole/swoole-src#903]
最新版 buffer 回调貌似没有效果，启动的时候 就已提示“Unknown event types..."
[http://wiki.swoole.com/wiki/page/p-1.9.0.html](http://wiki.swoole.com/wiki/page/p-1.9.0.html)
官方wiki上的demo 也直接提示此警告。
![1](http://t1.qpic.cn/mblogpic/952d5a84f455f60bfcac/2000)
![2](http://t1.qpic.cn/mblogpic/f110e1ad437b3f393abc/2000)
![3](http://t1.qpic.cn/mblogpic/811f41f99689d7e9acc0/2000)

**Comment by matyhtf** [comment]
使用github master分支的代码。
