### ISSUE TITLE
taskWaitMulti()方法执行task导致死循环

### ISSUE THREAD

**Issue by chaojidan** [swoole/swoole-src#904]
我服务器启了5个task_worker进程，使用taskWaitMulti()方法，客户端每次连接服务器并发创建5个task，这5个task做的事情是用curl远程获取一些数据，超时时间是5秒，客户端第一次请求的时候服务器正确返回了数据，然后客户端关闭连接，看上去没有任何问题。客户端第二次请求时却不返回数据了，服务器没有执行任何onTask事件，然后我用strace命令查看task_worker进程，发现进程陷入了死循环，一直在执行下面命令：

13:40:44.697520 poll([{fd=10, events=POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}])
13:40:44.697558 write(10, "\1\0\0\0\0\0\0\0", 8) = 8
13:40:44.697590 poll([{fd=10, events=POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}])
13:40:44.697631 write(10, "\1\0\0\0\0\0\0\0", 8) = 8
13:40:44.697660 poll([{fd=10, events=POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}])
13:40:44.697785 write(10, "\1\0\0\0\0\0\0\0", 8) = 8
13:40:44.697823 poll([{fd=10, events=POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}])
13:40:44.697863 write(10, "\1\0\0\0\0\0\0\0", 8) = 8
13:40:44.697894 poll([{fd=10, events=POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}])
13:40:44.697934 write(10, "\1\0\0\0\0\0\0\0", 8) = 8
13:40:44.697965 poll([{fd=10, events=POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}])
13:40:44.698007 write(10, "\1\0\0\0\0\0\0\0", 8) = 8
13:40:44.698037 poll([{fd=10, events=POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}])
13:40:44.698076 write(10, "\1\0\0\0\0\0\0\0", 8) = 8
13:40:44.698108 poll([{fd=10, events=POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}])
13:40:44.698147 write(10, "\1\0\0\0\0\0\0\0", 8) = 8
13:40:44.698177 poll([{fd=10, events=POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}])
13:40:44.698216 write(10, "\1\0\0\0\0\0\0\0", 8) = 8
13:40:44.698247 poll([{fd=10, events=POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}])
13:40:44.698287 write(10, "\1\0\0\0\0\0\0\0", 8) = 8
13:40:44.698316 poll([{fd=10, events=POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}])
13:40:44.698357 write(10, "\1\0\0\0\0\0\0\0", 8) = 8

请问是怎么回事？swoole版本是1.8.13

**Comment by matyhtf** [comment]
使用gdb -p 跟踪进程，输入bt打印函数调用栈。

**Comment by matyhtf** [comment]
感谢反馈，这是taskwait底层的BUG
