### ISSUE TITLE
swoole_http_server-----表单POST上传文件，不能识别

### ISSUE THREAD

**Issue by wgpqys** [swoole/swoole-src#913]
当上传一个文件时:
form action="http://192.168.3.101:8080/" method="post"    enctype="multipart/form-data"
    input type="text"  name="height"
    input type="text" name="age"
    input type="file" name="phone"
    input type="submit" value="submit"
form

在请求回调函数里调用$request->files时报错: 
 $http->on('request', function ($request, $response) {
        print_r($request->files);
}
信息：PHP Notice:  Undefined property: Swoole\Http\Request::$files

用swoole_http_client来post文件时，又是正常的。

**Comment by matyhtf** [comment]
无法重现，请使用chrome抓包工具，贴出详细的请求响应。
