### ISSUE TITLE
缺相关文档

### ISSUE THREAD

**Issue by afu110** [swoole/swoole-src#914]
Hi 各位大神，swoole目前缺相关安装的文档，虽然php扩展安装非常简单，但是至少描述下各个版本的依赖，都需要安装哪些库，需要升级到什么版本，支持什么系统，系统的最小版本是什么之类的，现在翻遍网站也没找到，网上也没有相关的描述，好不容易找到一篇还是swoole1.7版本的，希望能有个官方的这类描述文档，减少入门的难度，多谢！

**Comment by matyhtf** [comment]
http://wiki.swoole.com/wiki/page/7.html
http://wiki.swoole.com/wiki/page/6.html
