### ISSUE TITLE
v1.9.0编译报错Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"... Abort trap: 6

### ISSUE THREAD

**Issue by springleng** [swoole/swoole-src#915]
大神编译成功之后为啥总有这种报错？见最后两行

./configure --with-php-config=/usr/local/bin/php-config --enable-sockets --enable-ringbuffer --enable-async-redis --enable-openssl --enable-http2 --enable-thread --enable-jemalloc --enable-hugepage --enable-swoole --with-swoole

silen@Silen-MacBook-Pro ~/Downloads/swoole-src-1.9.0-stable$ php --ri swoole

swoole

swoole support => enabled
Version => 1.9.0
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
sockets => enabled
openssl => enabled
http2 => enabled
ringbuffer => enabled
pcre => enabled
zlib => enabled
jemalloc => enabled
hugepage => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
Abort trap: 6

**Comment by springleng** [comment]
经测试jemalloc的问题，关闭后重新编译就OK了，我使用的版本是jemalloc v4.2.1_1，macOS 10.12.1 (16B2555)
./configure --with-php-config=/usr/local/bin/php-config --enable-sockets --enable-ringbuffer --enable-async-redis --enable-openssl --enable-http2 --enable-thread --enable-hugepage --enable-swoole --with-swoole

silen@Silen-MacBook-Pro ~/Downloads/swoole-src-1.9.0-stable$ php --ri swoole

swoole

swoole support => enabled
Version => 1.9.0
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
rwlock => enabled
async redis client => enabled
async http/websocket client => enabled
sockets => enabled
openssl => enabled
http2 => enabled
ringbuffer => enabled
pcre => enabled
zlib => enabled
hugepage => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.message_queue_key => 0 => 0
swoole.unixsock_buffer_size => 8388608 => 8388608
silen@Silen-MacBook-Pro ~/Downloads/swoole-src-1.9.0-stable$ ls -las /usr/local/Cellar/jemalloc/4.2.1_1/
total 112
 0 drwxr-xr-x  11 silen  admin    374 11  5 01:49 .
 0 drwxr-xr-x   3 silen  admin    102 11  5 01:49 ..
 0 drwxr-xr-x   3 silen  admin    102  6  9 02:44 .brew
 8 -rw-r--r--   1 silen  admin   1703  6  9 02:44 COPYING
88 -rw-r--r--   1 silen  admin  44664  6  9 02:44 ChangeLog
 8 -rw-r--r--   1 silen  admin    442 11  5 01:49 INSTALL_RECEIPT.json
 8 -rw-r--r--   1 silen  admin   1084  6  9 02:44 README
 0 drwxr-xr-x   5 silen  admin    170 11  5 01:49 bin
 0 drwxr-xr-x   3 silen  admin    102  6  9 02:44 include
 0 drwxr-xr-x   7 silen  admin    238  6  9 02:44 lib
 0 drwxr-xr-x   4 silen  admin    136  6  9 02:44 share

**Comment by matyhtf** [comment]
有些编译原因是实验性质，正常使用请不要添加。
