### ISSUE TITLE
WARNING: unrecognized options: --enable-coroutine

### ISSUE THREAD

**Issue by similarJ** [swoole/swoole-src#919]
在编译时增加--enable-coroutine，--enable-async-redis是官方文档的说明。加上后出现如上错误，在开启命名空间的时候
```
new Swoole\Coroutine\Redis();
```
提示找不到Redis类。php redis扩展hiredis也都安装了。
我的环境：centos7.2,php7.0,swoole1.9.0

**Comment by matyhtf** [comment]
coroutine是2.0的特性，1.9.0不支持。

**Comment by urn2** [comment]
swoole2.0.6 centos php7.1
先编译安装hiredis，并执行了ldconfig
接着使用参数 ./configure --enable-async-redis=/usr/local --enable-coroutine 通过编译并安装
出现同样的状况，无法找到Redis类
使用ide-helper仅仅发现Server\Redis没有其他的redis类存在
![image](https://cloud.githubusercontent.com/assets/5161853/22915605/63f8d18e-f2b3-11e6-9093-d4b568887a87.png)
