### ISSUE TITLE
opcode缓存对于swoole-http-server是不是没有作用了？

### ISSUE THREAD

**Issue by wgpqys** [swoole/swoole-src#920]
如题，swoole-http-serve一直都在运行没有退出，也就是代码不需要重新语法分析、编译opcode过程，这样的话是不是各种opcode缓存方案对于swoole来说就没什么作用了？如果有作用，开启opcode加速对swoole的作用大吗？

**Comment by matyhtf** [comment]
作用不太大。可以关闭opcache
