### ISSUE TITLE
swoole 

### ISSUE THREAD

**Issue by xhh0168** [swoole/swoole-src#922]
Program terminated with signal 11, Segmentation fault.
#0  0x00007f4560d4387c in zim_swoole_server_port_on (ht=<value optimized out>, return_value=0x1af6280, return_value_ptr=<value optimized out>, this_ptr=0x178d478, 
    return_value_used=<value optimized out>) at /root/swoole-src-1.8.13-stable/swoole_server_port.c:415
415                 else if (i == SW_SERVER_CB_onClose && SwooleG.serv->onClose == NULL)

**Comment by matyhtf** [comment]
最新的版本无法重现此问题。
