### ISSUE TITLE
swoole_pop and swoole_push

### ISSUE THREAD

**Issue by yhl54199** [swoole/swoole-src#923]
前提：$process->useQueue(0, 1);
PHP_METHOD(swoole_process, push) 和PHP_METHOD(swoole_process, pop) 中
message.type = process->id;
这样对一个进程独享一个消息队列，和子进程通过type来存取时，这样是OK的，但是对于多个进程共享一个消息队列，在队列中，和各自的子进程通过type来存取时，就会发生错乱，因为不同进程可能具有相同的id，所以建议这里改成**message.type = process->pid;**

**Comment by matyhtf** [comment]
$process对象与进程不是绑定关系，只要$process对象不销毁，就可以使用管道，进程意外退出可以继续用start方法启用新的进程。
