### ISSUE TITLE
难道是hiredis没装对吗 囧

### ISSUE THREAD

**Issue by trylife** [swoole/swoole-src#925]
![hiredis](https://cloud.githubusercontent.com/assets/8101926/20699027/fe99c12c-b63f-11e6-9b46-7e4067a1b2c7.png)

```
./configure \                            
--enable-swoole-debug \
--enable-sockets \
--enable-async-redis

make
```
![swoole](https://cloud.githubusercontent.com/assets/8101926/20699048/20405d86-b640-11e6-9ac5-5b009263a118.png)

**Comment by trylife** [comment]
MAC 10.12.1 编译不过

**Comment by matyhtf** [comment]
安装`hiredis`后，执行`ldconfig`，再编译swoole。
