### ISSUE TITLE
taskWaitMulti能否返回没有超时的task数据？

### ISSUE THREAD

**Issue by chaojidan** [swoole/swoole-src#927]
我测试taskWaitMulti()方法时发现好像只要有一个task执行超时，taskWaitMulti()就会返回false，能否实现只有超时的task返回false，没超时的task返回相应数据？

**Comment by matyhtf** [comment]
感谢你的反馈，`taskWaitMulti()` 预期就是如所描述，当前的版本存在BUG，已修复。

**Comment by chaojidan** [comment]
如果task全部超时，程序好像就中断了，不会继续执行

**Comment by matyhtf** [comment]
已修复。
