### ISSUE TITLE
swoole_mysql.c 的问题

### ISSUE THREAD

**Issue by Sprite-sy** [swoole/swoole-src#928]
连接mysql的可能是unix socket.
调用setsockopt(cli->socket->fd, IPPROTO_TCP, TCP_NODELAY, (const void *) &tcp_nodelay, sizeof(int))
会出错.
Error: Operation not supported on socket[102].
这里需要加个判断  type!=SW_SOCK_UNIX_STREAM

**Comment by matyhtf** [comment]
感谢你的建议。
