### ISSUE TITLE
addProcess 应该是单独进程为什么也要继承master监听端口?

### ISSUE THREAD

**Issue by liugaohua** [swoole/swoole-src#931]

**Comment by matyhtf** [comment]
addProcess的子进程TCP监听端口不会继承，但会保留UDP端口，因为可能需要向对端发送数据。UDP的实现与TCP不同，UDP是直接在当前进程内发送数据到对端的，不需要经过master进程的reactor线程。

**Comment by liugaohua** [comment]
但是我的addProcess就是继承了swoole server的端口, 本想server shutdown之后,让系统回收addProces,但是现在addProces还在,端口占用,server就起不来了.

**Comment by GXhua** [comment]
swoole是先创建管理进程主进程再去监听 管理再去创建addprocess的进程所以理论上是不应该的   可是把你的代码贴上  还有版本   另外确认下reuse开没

**Comment by liugaohua** [comment]
swoole support => enabled
Version => 1.8.12
这个版本没有reuse的,况且我的内核版本2.6
我用losf 检测占用端口,addproces是在的
