### ISSUE TITLE
addProces继承master,监听端口;master shutdown之后,端口占用还在,server无法启动(伪代码)

### ISSUE THREAD

**Issue by liugaohua** [swoole/swoole-src#932]
下面就是伪代码,addproces继承master监听, 导致server关闭后,addproces还在,端口监听还在,所以server起不来
,我用losf 检测占用端口,addproces是在的
swoole support => enabled
Version => 1.8.12

`$swConfig =   array(
    'task_worker_num' => 0,
    'worker_num' => 3,
    'max_request' => 1000,
    'dispatch_mode' => 2,
    'debug_mode' => 1,
    'log_file' =>'swoole.log',
    'daemonize' => false //是否作为守护进程
    'open_tcp_keepalive' => true,
);
$http = new swoole_http_server( '0.0.0.0', 9501, SWOOLE_BASE );
$http->set( $swConfig  );
$http->on( 'Start', function( $http )
{
} );
$http->on( 'Shutdown', function() use ( $http )
{
} );
$http->on( 'workerStop', function( swoole_server $server, $worker_id )
{
} );
$http->on( 'WorkerStart', function( swoole_server $server, $worker_id ) use ( $swConfig )
{
    
} );

$http->on( 'managerStart', function()
{
} );
$http->on( 'managerStop', function()
{
} );

$http->on( 'request',  function( swoole_http_request $request, swoole_http_response $response ) use ( $http )
{
    //请求过滤
    if( $request->server[ 'path_info' ] == '/favicon.ico' || $request->server[ 'request_uri' ] == '/favicon.ico' )
    {
        $response->end();
        return;
    }
} );

$http->table = self::_getSwooleTable();
$http->addProcess( self::_getSwooleProcess() );
$http->start();
`

**Comment by GXhua** [comment]
不用 base模式试下？base模式是用来调试的

**Comment by liugaohua** [comment]
不用base模式,master和addProcess是无法结束的.

**Comment by GXhua** [comment]
<?php
$swConfig = array(
'task_worker_num' => 0,
'worker_num' => 1,
'max_request' => 1000,
'dispatch_mode' => 2,
'log_file' =>'swoole.log',
'daemonize' => 1, //是否作为守护进程
'open_tcp_keepalive' => true
);
$table = new swoole_table(1024);
$table->create();
        
$http = new swoole_http_server('0.0.0.0', 9501,SWOOLE_PROCESS);
$http->set($swConfig);
$http->on('Start', function( $http ) {
    
});
$http->on('Shutdown', function() use ( $http ) {
    
});
$http->on('workerStop', function( swoole_server $server, $worker_id ) {
    
});
$http->on('WorkerStart', function( swoole_server $server, $worker_id ) use ( $swConfig ) {
    
});

$http->on('managerStart', function() {
    
});
$http->on('managerStop', function() {
    
});

$http->on('request', function( swoole_http_request $request, swoole_http_response $response ) use ( $http ) {
//请求过滤
    if ($request->server['path_info'] == '/favicon.ico' || $request->server['request_uri'] == '/favicon.ico') {
        $response->end();
        return;
    }
});

$http->table = $table;

$process = new swoole_process(function($process) use ($http) {
echo 111111;sleep(10000);
});

$http->addProcess($process);
$http->start();


我用你的伪码写了简单修改了下    kill -15 主进程id   是能够结束的

**Comment by GXhua** [comment]
`
<?php
$swConfig = array(
'task_worker_num' => 0,
'worker_num' => 1,
'max_request' => 1000,
'dispatch_mode' => 2,
'log_file' =>'swoole.log',
'daemonize' => 1, //是否作为守护进程
'open_tcp_keepalive' => true
);
$table = new swoole_table(1024);
$table->create();
        
$http = new swoole_http_server('0.0.0.0', 9501,SWOOLE_PROCESS);
$http->set($swConfig);
$http->on('Start', function( $http ) {
    
});
$http->on('Shutdown', function() use ( $http ) {
    
});
$http->on('workerStop', function( swoole_server $server, $worker_id ) {
    
});
$http->on('WorkerStart', function( swoole_server $server, $worker_id ) use ( $swConfig ) {
    
});

$http->on('managerStart', function() {
    
});
$http->on('managerStop', function() {
    
});

$http->on('request', function( swoole_http_request $request, swoole_http_response $response ) use ( $http ) {
//请求过滤
    if ($request->server['path_info'] == '/favicon.ico' || $request->server['request_uri'] == '/favicon.ico') {
        $response->end();
        return;
    }
});

$http->table = $table;

$process = new swoole_process(function($process) use ($http) {
echo 111111;sleep(10000);
});

$http->addProcess($process);
$http->start();
`

**Comment by GXhua** [comment]
,<?php
$swConfig = array(
'task_worker_num' => 0,
'worker_num' => 1,
'max_request' => 1000,
'dispatch_mode' => 2,
'log_file' =>'swoole.log',
'daemonize' => 1, //是否作为守护进程
'open_tcp_keepalive' => true
);
$table = new swoole_table(1024);
$table->create();
        
$http = new swoole_http_server('0.0.0.0', 9501,SWOOLE_PROCESS);
$http->set($swConfig);
$http->on('Start', function( $http ) {
    
});
$http->on('Shutdown', function() use ( $http ) {
    
});
$http->on('workerStop', function( swoole_server $server, $worker_id ) {
    
});
$http->on('WorkerStart', function( swoole_server $server, $worker_id ) use ( $swConfig ) {
    
});

$http->on('managerStart', function() {
    
});
$http->on('managerStop', function() {
    
});

$http->on('request', function( swoole_http_request $request, swoole_http_response $response ) use ( $http ) {
//请求过滤
    if ($request->server['path_info'] == '/favicon.ico' || $request->server['request_uri'] == '/favicon.ico') {
        $response->end();
        return;
    }
});

$http->table = $table;

$process = new swoole_process(function($process) use ($http) {
echo 111111;sleep(10000);
});

$http->addProcess($process);
$http->start();
,

**Comment by liugaohua** [comment]
是的,这样是可以的,
但是如果我在addProces里面处理其他swoole_process创建销毁 , 就不起作用了

**Comment by GXhua** [comment]
swoole_process是用来代替pcntl fork的  和swoole_server的addProcess的进程是两套东西，addProcess的进程是会被管控起来的

**Comment by liugaohua** [comment]
我的情况是addProcess里面有管理其他的swoole_proces进程

[root@xxx:src]#ps axu| grep xxxx
root     13194  0.0  0.7 376400  8068 ?        Ssl  10:49   0:00 xxxx: master process 13194
root     13195  0.0  0.7 300164  7788 ?        S    10:49   0:00 xxxx: manager 13195
root     13197  0.0  0.7 298340  7916 ?        S    10:49   0:00 xxxx: worker process 13197
root     13198  0.0  0.7 298340  7916 ?        S    10:49   0:00 xxxx: worker process 13198
root     13199  0.0  0.7 298340  7916 ?        S    10:49   0:00 xxxx: worker process 13199
root     13200  0.2  0.8 301052  9052 ?        S    10:49   0:00 xxxx: cron process 13200
root     13201  0.0  0.7 301004  7544 ?        S    10:49   0:00 xxxx: job process 13201
root     13209  0.0  0.7 301004  7556 ?        S    10:49   0:00 xxxx: job process 13209
root     13216  0.0  0.0 103252   868 pts/2    S+   10:49   0:00 grep xxxx
[root@xxx:src]#pstree -alp 13194
php,13194
  ├─php,13195
  │   ├─php,13197
  │   ├─php,13198
  │   ├─php,13199
  │   └─php,13200
  │       ├─php,13201
  │       │   └─usleep,13202 32413000
  │       ├─php,13209
  │       │   └─usleep,13210 27996000
  │       └─php,13217
  │           └─usleep,13218 8703000
  └─{php},13196
[root@xxx:src]#kill -15 13194
[root@xxx:src]#ps axu| grep xxxx
root     13194  0.0  0.7 376400  8104 ?        Ssl  10:49   0:00 xxxx: master process 13194
root     13195  0.0  0.7 300164  7796 ?        S    10:49   0:00 xxxx: manager 13195
root     13200  0.1  0.8 301052  9076 ?        S    10:49   0:00 xxxx: cron process 13200
root     13223  0.0  0.7 301004  7536 ?        S    10:49   0:00 xxxx: job process 13223
root     13228  0.0  0.7 301004  7536 ?        S    10:49   0:00 xxxx: job process 13228
root     13289  0.0  0.0 103252   868 pts/2    S+   10:50   0:00 grep xxxx
[root@xxx:src]#pstree -alp 13194
php,13194
  ├─php,13195
  │   └─php,13200
  │       ├─php,13223
  │       │   └─usleep,13224 31386000
  │       └─php,13228
  │           └─usleep,13229 24676000
  └─{php},13196

kill SIGTERM master之后,只有worker 进程结束了,,其他的都没有

**Comment by liugaohua** [comment]
你的那种写法,在swoolebase下还是不行的
