### ISSUE TITLE
http server, SWOOLE_BASE 模式下为什么要所有的进程都会监听端口, 而 SWOOLE_PROCESS只有master在监听端口,?

### ISSUE THREAD

**Issue by liugaohua** [swoole/swoole-src#933]
swoole base 可不可以也只让master进程监听端口?

**Comment by matyhtf** [comment]
那不就变成PROCESS模式了。

**Comment by liugaohua** [comment]
我的情况是addProcess里面有管理其他的swoole_proces进程
在SWOOLE_PROCESS模式下,kill -15 masterPid之后 , 只有worker进程结束了,其他的都还在.

[root@xxx:src]#ps axu| grep xxxx
root 13194 0.0 0.7 376400 8068 ? Ssl 10:49 0:00 xxxx: master process 13194
root 13195 0.0 0.7 300164 7788 ? S 10:49 0:00 xxxx: manager 13195
root 13197 0.0 0.7 298340 7916 ? S 10:49 0:00 xxxx: worker process 13197
root 13198 0.0 0.7 298340 7916 ? S 10:49 0:00 xxxx: worker process 13198
root 13199 0.0 0.7 298340 7916 ? S 10:49 0:00 xxxx: worker process 13199
root 13200 0.2 0.8 301052 9052 ? S 10:49 0:00 xxxx: cron process 13200
root 13201 0.0 0.7 301004 7544 ? S 10:49 0:00 xxxx: job process 13201
root 13209 0.0 0.7 301004 7556 ? S 10:49 0:00 xxxx: job process 13209
root 13216 0.0 0.0 103252 868 pts/2 S+ 10:49 0:00 grep xxxx
[root@xxx:src]#pstree -alp 13194
php,13194
├─php,13195
│ ├─php,13197
│ ├─php,13198
│ ├─php,13199
│ └─php,13200
│ ├─php,13201
│ │ └─usleep,13202 32413000
│ ├─php,13209
│ │ └─usleep,13210 27996000
│ └─php,13217
│ └─usleep,13218 8703000
└─{php},13196
[root@xxx:src]#kill -15 13194
[root@xxx:src]#ps axu| grep xxxx
root 13194 0.0 0.7 376400 8104 ? Ssl 10:49 0:00 xxxx: master process 13194
root 13195 0.0 0.7 300164 7796 ? S 10:49 0:00 xxxx: manager 13195
root 13200 0.1 0.8 301052 9076 ? S 10:49 0:00 xxxx: cron process 13200
root 13223 0.0 0.7 301004 7536 ? S 10:49 0:00 xxxx: job process 13223
root 13228 0.0 0.7 301004 7536 ? S 10:49 0:00 xxxx: job process 13228
root 13289 0.0 0.0 103252 868 pts/2 S+ 10:50 0:00 grep xxxx
[root@xxx:src]#pstree -alp 13194
php,13194
├─php,13195
│ └─php,13200
│ ├─php,13223
│ │ └─usleep,13224 31386000
│ └─php,13228
│ └─usleep,13229 24676000
└─{php},13196

kill SIGTERM master之后,只有worker 进程结束了,,其他的都没有

**Comment by GXhua** [comment]
你需要在addProcess进程里面监听sigterm信号  收到信号后向所有的swoole_process发送结束进程的信号

**Comment by liugaohua** [comment]
这个倒是无所谓的,就算不给结束信号,,,这些swoole_proces也会被1进程接管,,
我只想让master和manager这些正常结束,,,目前的情况只有worker结束了,master和manger没有结束而且也没有走shutdown,更何况是addProces了,这是很纳闷的
