### ISSUE TITLE
高并发下的socket如何处理

### ISSUE THREAD

**Issue by wgpqys** [swoole/swoole-src#934]
场景是这样的：
用swoole作http server，提供RESTful API给客户使用，在http server的 request异步调用里我需要用php的socket连接另外的一台服务器进行认证、发送信息、等待发送报告、处理报告状态显示给客户看这4个步骤，现在设计要求支持800请求每秒，第三步骤等报告的时间是5分钟之内的随机时间里会发送到我这边先前经过认证的socket，请问一下这个怎么处理，swoole有没有全局共享的socket，这样的话只要做一次socket认证就可以了，发送信息和等待报告重复使用这个socket；或者每一个请求都走上述4个步骤，到第三步时把socket发送到task池里，这样的话，服务器是不是会有很多socket挂在那里等报告？

**Comment by RamboLau** [comment]
swoole task应该可以支持你的这个需求。

**Comment by wgpqys** [comment]
那TASK里会挂非常多的socket，不知道一个task进程是不是只能处理一个等待读取报告的socket

**Comment by wgpqys** [comment]
我看了下，socket是资源类型还没法投到task里去

**Comment by wgpqys** [comment]
像这种要等待时间的socket怎么解决比较好，发task又发不过去，阻塞在那里等又不行，求解？

**Comment by matyhtf** [comment]
使用`addProcess`添加一个异步的进程维持这些Socket
