### ISSUE TITLE
1.8.10稳定版swReactorThread_onRead  coredump

### ISSUE THREAD

**Issue by Corzcode** [swoole/swoole-src#935]
线上环境随机发生
swoole 1.8.10
PHP 5.6.15
使用的是http_server 

(gdb) bt
#0  swReactorThread_onRead (reactor=0x7f0e59f7b8a0, event=<value optimized out>) at /usr/src/swoole-src-1.8.10-stable/src/network/ReactorThread.c:812
#1  0x00007f0e5a3d0860 in swReactorEpoll_wait (reactor=0x7f0e59f7b8a0, timeo=<value optimized out>) at /usr/src/swoole-src-1.8.10-stable/src/reactor/ReactorEpoll.c:258
#2  0x00007f0e5a3da250 in swReactorThread_loop_stream (param=<value optimized out>) at /usr/src/swoole-src-1.8.10-stable/src/network/ReactorThread.c:1183
#3  0x00007f0e6116faa1 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003c56ae893d in clone () from /lib64/libc.so.6

**Comment by matyhtf** [comment]
请贴出gcc uname 的版本信息

**Comment by Corzcode** [comment]
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) 

Linux xxx 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by matyhtf** [comment]
在 1.8.10或更早之前的版本确实发现过在 gcc4.4 版本存在偶发core的问题，请测试 1.8.13 或更高版本是否还存在此问题。

**Comment by Corzcode** [comment]
好的试试更新版本看看还会不会
