### ISSUE TITLE
异步时有时候client send后server不能立即receive到  

### ISSUE THREAD

**Issue by weiok550** [swoole/swoole-src#937]
我的qq：  124538659；

client 与 server 在一个机器上，异步时有时候client send后server不能立即receive到

**client：**
//每分钟发送一批请求
 $res = $client->connect("127.0.0.1", 9501, 10);
        if($res) {
               循环{
               $client->send($task.‘zweof’);
               }
        }

**server:**

        $serv = new swoole_server("127.0.0.1", 9501);

        //设置异步任务的工作进程数量
        $serv->set(array(
            'task_worker_num' => 48,
            'open_eof_split' => true,
            'package_eof' => 'zweof',
            'open_length_check' => true,
            'dispatch_mode' => 3
        ));

        $serv->on('receive', function($serv, $fd, $from_id, $data) {
            //投递异步任务
            $task_id = $serv->task($data);
        });

        //处理异步任务
        $serv->on('task', function ($serv, $task_id, $from_id, $data) {
               处理逻辑
        }

**Comment by haytoo1** [comment]
发送数据的流程是：
发送者：写入自己的缓存区，等待发送
接收者：从自己的读缓存区里读取

如果发送频率比较快，
就可能发送者的缓冲区满了，阻塞住不能及时发出去
还有可能接收者的缓冲区满了，新数据投递不进来

我猜你的问题有可能是这个

**这几天粗糙的学习到的，要是不对还请各位爷指正么么哒**

**Comment by weiok550** [comment]
@haytoo1   那可以通过什么方式解决呢？

**Comment by xiaochun0223** [comment]
最近用swoole的task进程有奇怪的问题出现，于是我把队列改用worker进程+redis的list做了

**Comment by matyhtf** [comment]
死循环会导致task队列塞满。
