### ISSUE TITLE
使用swoole_websocket_server, 客户端主动断开连接, 该连接依然存在于$server->connections中

### ISSUE THREAD

**Issue by koiding** [swoole/swoole-src#938]
> 无论由客户端发起close还是服务器端主动调用$serv->close()关闭连接，都会触发此事件。因此只要连接关闭，就一定会回调此函数
1.7.7+版本以后onClose中依然可以调用connection_info方法获取到连接信息，在onClose回调函数执行完毕后才会调用close关闭TCP连接

请问哪个方法可以过滤掉该连接?还是说该连接程序里自己处理掉.

**Comment by matyhtf** [comment]
onClose回调完成后就会清理此链接。
