### ISSUE TITLE
centos7 php7.1.0

### ISSUE THREAD

**Issue by lizigeng111** [swoole/swoole-src#941]
版本号 swoole1.9.1  php 7.1.0 操作系统 centos7.1 安装完毕后 php web 访问 phpinfo swoole显示正常
cli 执行 php-m 提示 PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php/lib/php/extensions/no-debug-non-zts-20160303/swoole.so' - /usr/local/php/lib/php/extensions/no-debug-non-zts-20160303/swoole.so: undefined symbol: sapi_globals_id in Unknown on line 0
这是php的编译选项
php.ini 及php-cli.ini配置都一样
./configure --prefix=/usr/local/php --with-config-file-path=/usr/local/php/ --with-gd  --with-jpeg-dir --with-png-dir --with-zlib-dir --with-freetype-dir=/usr/include/freetype2/freetype --enable-fpm --enable-mbstring  --enable-json --enable-libxml --enable-gd-native-ttf  --enable-gd-jis-conv --with-iconv-dir=/usr/local/libiconv --enable-bcmath --enable-dom --enable-filter --enable-xml --enable-xmlreader --enable-xmlwriter --with-openssl --enable-calendar --enable-soap --with-mhash --with-mcrypt  --with-curl  --enable-sockets  --with-gettext --with-libdir=lib64 --without-pear --enable-opcache --disable-ipv6  --enable-shmop --with-pcre-dir=/usr/local/pcre --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd  --with-pdo-pgsql=/usr/local/pgsql/bin --enable-ftp --with-xmlrpc --enable-pcntl --enable-sockets --without-pear

**Comment by matyhtf** [comment]
重新编译安装swoole
