### ISSUE TITLE
关于zm_deactivate_swoole (ERROR 9003): worker process is terminated by exit()/die().

### ISSUE THREAD

**Issue by liugaohua** [swoole/swoole-src#943]
[2016-12-11 14:17:20 @2071.0]	ERROR	zm_deactivate_swoole (ERROR 9003): worker process is terminated by exit()/die().

这个问题有很多答案,,很多说的都是 swoole内的进程不允许结束,,结束之后,master会重新fork出进程.

但是addProces里面也存在这种情况,而且addProcess里面的子进程结束之后也存在这种情况, 如果仅仅是addProces本身的话倒是很有必要,但是addProces里面的子进程也这样处理, 是不是不太好?
不知道swoole这样设计是不是不合理?

个人认为, 父进程只管理好子进程的问题就可以了, 孙子进程就还交给孙子进程的父进程处理.

**Comment by matyhtf** [comment]
此信息只是一个提示，不影响功能，请使用`Swoole\Event::exit`或者在进程中`return`，代替`exit/die`

**Comment by kimkit** [comment]
在使用`addProcess`的时候有这个错误日志，@matyhtf 上面的解释没看明白。

代码如下：
```
<?php

$server = new swoole_http_server('127.0.0.1', 7788);

$server->on('request', function ($request, $response) {
    $response->end('hello world');
});

$server->set([
    'daemonize' => true,
    'log_file' => '/tmp/test.log',
]);
$server->addProcess(new swoole_process(function () {
    $data = new ArrayObject();
    $data['exit'] = false;

    echo "worker start\n";
    pcntl_signal(15, function () use ($data) {
        $data['exit'] = true;
    });

    while (true) {
        pcntl_signal_dispatch();
        if ($data['exit']) {
            break;
        }
        echo date("Y-m-d H:i:s\n");
        sleep(2);
    }
    echo "worker stop\n";
}));

$server->start();
```

日志如下：
```
worker start
2017-03-19 10:22:27
2017-03-19 10:22:29
2017-03-19 10:22:31
2017-03-19 10:22:33
2017-03-19 10:22:35
2017-03-19 10:22:37
2017-03-19 10:22:39
[2017-03-19 10:22:41 #32572.0]	NOTICE	Server is shutdown now.
worker stop
[2017-03-19 10:22:41 @32582.0]	ERROR	zm_deactivate_swoole (ERROR 9003): worker process is terminated by exit()/die().
```

**Comment by Dragonbuf** [comment]
`class WebWorker extends Worker {
	
	public function run() {
		echo "this one\n";
	}
	
}

class WebWork extends Threaded {

	public function run() {
		echo "webWork\n";
	}
}





$http->on("request", function ($request, $response) {
    $response->header("Content-Type", "text/plain");


    $pool = new Pool(8, 'WebWorker');
   
    $pool->submit(new WebWork());
    $pool->submit(new WebWork());
    $pool->submit(new WebWork());
    $pool->submit(new WebWork());


    $response->end("Hello World\n");
});

$http->start();`

在 swoole 最新版本中，使用 pthreads 扩展也会出现这个问题。
