### ISSUE TITLE
error: 'O_CLOEXEC' undeclared

### ISSUE THREAD

**Issue by xzj675** [swoole/swoole-src#948]
Hi
    when I make , there is following error:
    cc -I. -I/home/work/opbin/odp5.4/var/pear/temp/swoole -DPHP_ATOM_INC -I/home/work/opbin/odp5.4/var/pear/temp/pear-build-workqJfwE1/swoole-1.9.1/include -I/home/work/opbin/odp5.4/var/pear/temp/pear-build-workqJfwE1/swoole-1.9.1/main -I/home/work/opbin/odp5.4/var/pear/temp/swoole -I/home/work/opbin/odp5.4/php/include/php -I/home/work/opbin/odp5.4/php/include/php/main -I/home/work/opbin/odp5.4/php/include/php/TSRM -I/home/work/opbin/odp5.4/php/include/php/Zend -I/home/work/opbin/odp5.4/php/include/php/ext -I/home/work/opbin/odp5.4/php/include/php/ext/date/lib -I/home/work/opbin/odp5.4/var/pear/temp/swoole -I/home/work/opbin/odp5.4/var/pear/temp/swoole/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /home/work/opbin/odp5.4/var/pear/temp/swoole/src/core/base.c  -fPIC -DPIC -o src/core/.libs/base.o
/home/work/opbin/odp5.4/var/pear/temp/swoole/src/core/base.c: In function 'swoole_fcntl_set_option':
/home/work/opbin/odp5.4/var/pear/temp/swoole/src/core/base.c:703:23: error: 'O_CLOEXEC' undeclared (first use in this function)
/home/work/opbin/odp5.4/var/pear/temp/swoole/src/core/base.c:703:23: note: each undeclared identifier is reported only once for each function it appears in

anyone knows how to fix this?

**Comment by matyhtf** [comment]
What is the OS version, show `uname -a` infos.

**Comment by xzj675** [comment]
uname -a :
Linux instance-uow2rcjt 2.6.32_1-14-0-0 #1 SMP Mon Mar 31 10:42:09 CST 2014 x86_64 x86_64 x86_64 GNU/Linux
