### ISSUE TITLE
swoole的异步mysql的问题

### ISSUE THREAD

**Issue by wgpqys** [swoole/swoole-src#951]
请问一下创建的异步mysql连接是长连接吗？，放在swoole_client的receive里应该怎么重复使用异步mysql连接以及如何判断连接失效重连问题？因为该项目场景里，我这边的swoole_client每秒会接收100次左右的数据，然后更新到数据库里，client连接的server是其它单位的非swoole服务器，1.9.0版本

**Comment by wgpqys** [comment]
还有一个问题：swoole_process创建的子进程，如何调用已创建的swoole_client的send方法发送数据，我现在直接在process的回调函数里用global $client; $client->send($data) 调用会出错

**Comment by matyhtf** [comment]
提问请在<group.swoole.com>，github issue仅用于反馈BUG、提交改进建议。
