### ISSUE TITLE
异步mysql客户端 如果密码错误会多次回调callback

### ISSUE THREAD

**Issue by keaixiaou** [swoole/swoole-src#952]
异步mysql客户端 如果密码错误会多次回调callback，请验证

**Comment by matyhtf** [comment]
贴出你的代码。

**Comment by keaixiaou** [comment]
//直接使用swoole_mysql

$db = new \swoole_mysql;
$server = array(
    'host' => '127.0.0.1',
    'user' => 'test',
    'password' => '123456',//密码错的
    'database' => 'test',
);

$db->connect($server, function ($db, $r) {
    if ($r === false) {
        var_dump($db->connect_errno, $db->connect_error);
        echo 'connenct fail!'."\n";
    }

});

**Comment by matyhtf** [comment]
贴出运行结果。

**Comment by matyhtf** [comment]
无法重现。

**Comment by keaixiaou** [comment]
1045#28000Access denied for user 'remoteLink'@'101.68.64.86' (using password: YES)
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
54Connection reset by peer
（就是不断地产生回调，然后我这边就是不断输出"54Connection reset by peer"）

**Comment by keaixiaou** [comment]
IP和端口对的，只是密码不对

**Comment by matyhtf** [comment]
连接失败后请直接`return`，不要执行`query`。

**Comment by keaixiaou** [comment]
没有query，你看上面的代码

**Comment by matyhtf** [comment]
失败后加一句 `$db->close()` 吧，最新的代码已修复此问题，底层自动执行close

**Comment by keaixiaou** [comment]
/php-7.0.12/Zend/zend_execute_API.c:842: zend_call_function:     Assertion `((zend_object*)func->op_array.prototype)->gc.u.v.type == 8' failed.
最新代码会崩溃

**Comment by matyhtf** [comment]
有没有make clean

**Comment by matyhtf** [comment]
请再git pull，更新一下代码吧。
