### ISSUE TITLE
进程启动后第一次调用swoole_async_dns_lookup 没有回调

### ISSUE THREAD

**Issue by caoliaoyinyue** [swoole/swoole-src#953]
如题，使用的1.8.13稳定版 遇到这个问题

**Comment by matyhtf** [comment]
贴出代码。

**Comment by caoliaoyinyue** [comment]
swoole_async_dns_lookup($this->url, function($host, $ip) {
    ....
});

**Comment by matyhtf** [comment]
如果你的程序是同步阻塞的，请使用 `gethostbyname`

**Comment by caoliaoyinyue** [comment]
回调函数里用了Swoole\Http\Client异步发的post请求, 我启动程序后先执行一次swoole_async_dns_lookup试试

**Comment by matyhtf** [comment]
无法重现，请提供一个可稳定复现的demo
