### ISSUE TITLE
swoole_http_response->header设置ETag的bug

### ISSUE THREAD

**Issue by huangnaiang** [swoole/swoole-src#956]
swoole_http_response->header设置ETag，最终变成了Etag

**Comment by matyhtf** [comment]
底层会进行一次首字母大写转换。

**Comment by huangnaiang** [comment]
但Etag转错了啊，标准应该是 ETag

**Comment by millken** [comment]
这里我也发现了有些问题，比如request都会转换为小写，这个转换应该是由用户来控制的，而不是底层来强行改变。

**Comment by matyhtf** [comment]
ETag大小写都可以吧，你使用的什么软件需要依赖 大写的 `ETag` ?
另外，`1.9.2`header方法增加了一个参数可以控制不对header进行大写转换。

**Comment by matyhtf** [comment]
经过测试 Chrome 对Etag大小写是不敏感的。无需担心 转为大写影响逻辑。
