### ISSUE TITLE
swoole_http_response默认设置Content-Type 和Content-Length？

### ISSUE THREAD

**Issue by huangnaiang** [swoole/swoole-src#959]
swoole_http_response是不是默认会设置 Content-Type 和Content-Length？
我调用swoole_http_response->header 没有设置这两个字段，response头里出现 Content-Type:text/html Content-Length:0

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/issues/958

**Comment by huangnaiang** [comment]
这个能不默认设置吗 有些http的response我们不想带这两个 比如304的请求

**Comment by matyhtf** [comment]
感谢你的建议，这个可以支持。
