### ISSUE TITLE
swoole_http_request->$server["request_uri"]和$_SERVER["REQUEST_URI"]不一致

### ISSUE THREAD

**Issue by huangnaiang** [swoole/swoole-src#961]
php的原生$_SERVER["REQUEST_URI"]是有带query string的，如“/index.php?name=hello”
swoole的swoole_http_request->$server["request_uri"]是不带query_string的
建议统一一下向官方靠拢

**Comment by matyhtf** [comment]
swoole和fpm是完全不同的，需要特殊处理。
