### ISSUE TITLE
SSL Client randomly returns ssl_error_ssl when SWOOLE_SOCK_ASYNC

### ISSUE THREAD

**Issue by piramix** [swoole/swoole-src#962]
I have Issue with SSL Client it randomly returns ssl_error_ssl - connection with openssl s_client -connect 127.0.0.1:9443 - works everytime

swoole: 1.9.2
libssl-dev:amd64               1.0.1t-1+deb8u3

Example:
[2016-12-20 09:57:56 @9412.0]	WARNING	swSSL_connect: SSL_connect() failed. Error: (null)[1]
Connection close
root@acid:/home/acid# php client.php 
[2016-12-20 09:57:57 @9414.0]	WARNING	swSSL_connect: SSL_connect() failed. Error: (null)[1]
Connection close
root@acid:/home/acid# php client.php 
[2016-12-20 09:57:58 @9415.0]	WARNING	swSSL_connect: SSL_connect() failed. Error: (null)[1]
Connection close
root@acid:/home/acid# php client.php 
[2016-12-20 09:57:58 @9416.0]	WARNING	swSSL_connect: SSL_connect() failed. Error: (null)[1]
Connection close
root@acid:/home/acid# php client.php 
Connected
Received: {"version":"0.1"}

I'm starting connection like this:
$this->client = new swoole_client(SWOOLE_SOCK_TCP | SWOOLE_SSL, SWOOLE_SOCK_ASYNC);
$this->client->set(array('open_eof_check' => true, 'package_eof' => "\n"));
$this->client->on("connect", [$this, 'onconnect']);
$this->client->on("receive", [$this, 'onreceive']);
$this->client->on("error", [$this, 'onerror']);
$this->client->on("close", [$this, 'onclose']);
$this->client->connect('127.0.0.1', 9443);

Tested on 1.9.5-alpha and I have still the same problem:

Example code:
[swoolesslbug.zip](https://github.com/swoole/swoole-src/files/708244/swoolesslbug.zip)

**Comment by emdfreeman** [comment]
How to enable ssl_tls_sni in swoole?

**Comment by matyhtf** [comment]
将超时时间设置为 5 秒，在最新的代码中未能重现。

```php
$client->connect('127.0.0.1', 9501, 5.0);
```
