### ISSUE TITLE
RFC: Code Change process need clarify: Post RFC first . then make PR ,no direct change code please!!

### ISSUE THREAD

**Issue by netroby** [swoole/swoole-src#969]
Code Change process need clarify: Post RFC first . then make PR ,no direct change code please!!

## Problem

The easy change code. the easy to import bugs with code.

## Tuning

We need to clarify how code can be changed.

1. Need post RFC to discuss what change will make . like ( Tuning the memory usage of the connections pool)
2. Need send PR, not just push code change to master branch
3. The PR need reviewed by at least 2 developer?
4. Merge request. then close issue and PR?
5. The change already put in master branch.

## Benefit

The right process will make swoole more stable and more robust. 

The current change very unstable. not like to see the working like this kind(direct change code base)

**Comment by matyhtf** [comment]
Your advice is very good, But we do not have too many resources to implement.
We can gradually improve.

**Comment by netroby** [comment]
yeah . i am looking for how to improve it. from the RFC / PR progress . 
As a temp resolution. Can we create an testing branch, to rapid commit your unstable code. 
Then go RFC->PR->Review->Merge to master branch?

The current way direct commit code to master. seems not very stable .. and may be a bit dangerous?

**Comment by matyhtf** [comment]
No one can help me review the code now, This is a helpless thing. 
![xxx](http://www.fuhaodq.com/fhimg/1/bqfh22.png)

**Comment by netroby** [comment]
Sounds like very sad ....

**Comment by matyhtf** [comment]
Now, We create a rfc proposal and voting system. Welcome to submit a proposal to us.
