### ISSUE TITLE
RFC: Adjust the file naming rules

### ISSUE THREAD

**Issue by netroby** [swoole/swoole-src#970]
The current naming rules contains two kinds of file name
![naming](https://cloud.githubusercontent.com/assets/278153/21449578/ad4315ec-c929-11e6-80a3-0d09724ae284.PNG)

```
Channel.c
UnitTest.c
```
And
```
array.c
hashmap.c
```

Why not just using one kind of naming rules?

```
Channel.c
UnitTest.c
Array.c
HashMap.c
```

looks well know

But other opensource project. like openssh, it using name-with-arg.c this kind naming rules.

https://github.com/openssh/openssh-portable/tree/master/openbsd-compat

**Comment by twose** [comment]
```php
Coroutine::gethostbyname
swoole_async_dns_lookup_coro
```
😂 same question...

**Comment by netroby** [comment]
Really nice move, good to see the changes.
