### ISSUE TITLE
compile error in centos6.8/php7.0.14

### ISSUE THREAD

**Issue by TsuiJie** [swoole/swoole-src#973]
system:
Linux version 2.6.32-573.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Thu Jul 23 15:44:03 UTC 2015

php:
PHP 7.0.14 (cli) (built: Dec 10 2016 11:58:43) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.14, Copyright (c) 1999-2016, by Zend Technologies

swoole version:
v1.9.3-stable

error message:
```
/home/swoole-src-1.9.3-stable/swoole_http_client.c: In function ‘http_client_onReceive’:
/home/swoole-src-1.9.3-stable/swoole_http_client.c:689: warning: implicit declaration of function ‘inflateEnd’
/home/swoole-src-1.9.3-stable/swoole_http_client.c:689: error: ‘http_client’ has no member named ‘gzip_stream’
/home/swoole-src-1.9.3-stable/swoole_http_client.c: In function ‘http_client_free’:
/home/swoole-src-1.9.3-stable/swoole_http_client.c:1131: error: ‘http_client’ has no member named ‘gzip_stream’
make: *** [swoole_http_client.lo] Error 1
```

have no idea what package is missing

**Comment by matyhtf** [comment]
Please install zlib-devel.
