### ISSUE TITLE
1.8.5-stable版本开启http_server服务时，运行一段时间会连接被拒绝

### ISSUE THREAD

**Issue by liupdhc** [swoole/swoole-src#976]
最近线上环境连续两天会出现server突然无法连接。master、manager和worker进程都在，直接kill -9再重启后就正常。不是必现，有好几台机器，只有一台会有这个问题，这台跟其他的唯一区别是多了一个networkbench.so扩展。。出现问题时，有coredump文件产生。。大致信息如下：

`[root@hz0538 corefile]# gdb php core-php-11-0-0-50179-1482646071
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-90.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/php...done.
[New Thread 50185]
[New Thread 50187]
[New Thread 50189]
[New Thread 50197]
[New Thread 50186]
[New Thread 50182]
[New Thread 50183]
[New Thread 50188]
[New Thread 50179]
[New Thread 50184]
Missing separate debuginfo for /usr/lib/libmcrypt.so.4
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/d5/39276e62897aaa23b8e655e74d69b928096dfd
Missing separate debuginfo for /usr/lib/libpng12.so.0
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/0b/a6b675f43abec4fa2ed5ae83da53a2e32842fb
Missing separate debuginfo for /usr/lib/libjpeg.so.62
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/05/6b2c6a8cb0b42dda3d57a1b5d3670ab99c83bd
Missing separate debuginfo for /usr/local/lib/libiconv.so.2
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/1d/d77f87f631f4bdc98a31d0db35065dabe198d5
Missing separate debuginfo for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/opcache.so
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/a3/43bfa6047c75d4e217eccc908bbb599732dad3
Missing separate debuginfo for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/memcache.so
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/73/56645f9ca4241075a4514885f2d3e126e41c26
Missing separate debuginfo for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/redis.so
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/53/512d3ed64bc7f6660130e75817bb34c0b7c77a
Missing separate debuginfo for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/gearman.so
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/fb/35c9be0e71b41fcaaa093fe00700083b051a93
Missing separate debuginfo for /usr/local/lib/libgearman.so.8
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/c9/619007548ccdeb8ebda46d4aa33c449100ee1c
Missing separate debuginfo for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/protobuf.so
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/6a/bf37aa28cc5ce3371eafbe8f9235030f687408
Missing separate debuginfo for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/igbinary.so
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/21/2702b9e4b5330f848af15dab0c8ead2604bbd6
Missing separate debuginfo for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/swoole.so
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/f9/2ec996028ca797c61bc44ea6858ede6a912021
Missing separate debuginfo for /usr/local/lib/libjemalloc.so.2
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/01/80e55a1bcf905359742e65b19b96eef21174c5
Missing separate debuginfo for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/memcached.so
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/98/c6415ff8a49cb5ebd1c06dd5036cff80eeb5bc
Missing separate debuginfo for /usr/local/libmemcached/lib/libmemcached.so.11
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/0b/c67b2cd89036897ea0fa38c91313a6ef7a2f38
Missing separate debuginfo for /usr/local/libmemcached/lib/libmemcachedutil.so.2
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/07/bdf65599a340b58a98e780c009fc262f6b0870
Missing separate debuginfo for 
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/ec/37397b4ecc9f347891ceff84a05131bf10bfc3
Reading symbols from /lib64/libcrypt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libcrypt.so.1
Reading symbols from /lib64/libz.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libz.so.1
Reading symbols from /lib64/librt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/librt.so.1
Reading symbols from /usr/lib/libmcrypt.so.4...done.
Loaded symbols for /usr/lib/libmcrypt.so.4
Reading symbols from /usr/lib/libpng12.so.0...Missing separate debuginfo for /usr/lib/libpng12.so.0
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/0b/a6b675f43abec4fa2ed5ae83da53a2e32842fb.debug
(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libpng12.so.0
Reading symbols from /usr/lib/libjpeg.so.62...Missing separate debuginfo for /usr/lib/libjpeg.so.62
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/05/6b2c6a8cb0b42dda3d57a1b5d3670ab99c83bd.debug
(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libjpeg.so.62
Reading symbols from /usr/lib64/libcurl.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libcurl.so.4
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /lib64/libnsl.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnsl.so.1
Reading symbols from /usr/lib64/libxml2.so.2...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libxml2.so.2
Reading symbols from /usr/lib64/libssl.so.10...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libssl.so.10
Reading symbols from /usr/lib64/libcrypto.so.10...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libcrypto.so.10
Reading symbols from /usr/lib64/libfreetype.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libfreetype.so.6
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/libresolv.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libresolv.so.2
Reading symbols from /usr/lib64/libfreebl3.so...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libfreebl3.so
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /lib64/libidn.so.11...(no debugging symbols found)...done.
Loaded symbols for /lib64/libidn.so.11
Reading symbols from /lib64/libldap-2.4.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libldap-2.4.so.2
Reading symbols from /lib64/libgssapi_krb5.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgssapi_krb5.so.2
Reading symbols from /lib64/libkrb5.so.3...(no debugging symbols found)...done.
Loaded symbols for /lib64/libkrb5.so.3
Reading symbols from /lib64/libk5crypto.so.3...(no debugging symbols found)...done.
Loaded symbols for /lib64/libk5crypto.so.3
Reading symbols from /lib64/libcom_err.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libcom_err.so.2
Reading symbols from /usr/lib64/libssl3.so...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libssl3.so
Reading symbols from /usr/lib64/libsmime3.so...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libsmime3.so
Reading symbols from /usr/lib64/libnss3.so...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libnss3.so
Reading symbols from /usr/lib64/libnssutil3.so...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libnssutil3.so
Reading symbols from /lib64/libplds4.so...(no debugging symbols found)...done.
Loaded symbols for /lib64/libplds4.so
Reading symbols from /lib64/libplc4.so...(no debugging symbols found)...done.
Loaded symbols for /lib64/libplc4.so
Reading symbols from /lib64/libnspr4.so...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnspr4.so
Reading symbols from /usr/lib64/libssh2.so.1...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libssh2.so.1
Reading symbols from /lib64/liblber-2.4.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/liblber-2.4.so.2
Reading symbols from /usr/lib64/libsasl2.so.2...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libsasl2.so.2
Reading symbols from /lib64/libkrb5support.so.0...(no debugging symbols found)...done.
Loaded symbols for /lib64/libkrb5support.so.0
Reading symbols from /lib64/libkeyutils.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libkeyutils.so.1
Reading symbols from /lib64/libselinux.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libselinux.so.1
Reading symbols from /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/opcache.so...done.
Loaded symbols for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/opcache.so
Reading symbols from /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/memcache.so...done.
Loaded symbols for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/memcache.so
Reading symbols from /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/redis.so...done.
Loaded symbols for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/redis.so
Reading symbols from /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/gearman.so...done.
Loaded symbols for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/gearman.so
Reading symbols from /usr/local/lib/libgearman.so.8...done.
Loaded symbols for /usr/local/lib/libgearman.so.8
Reading symbols from /lib64/libuuid.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libuuid.so.1
Reading symbols from /usr/lib64/libstdc++.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libstdc++.so.6
Reading symbols from /lib64/libgcc_s.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgcc_s.so.1
Reading symbols from /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/protobuf.so...done.
Loaded symbols for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/protobuf.so
Reading symbols from /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/igbinary.so...done.
Loaded symbols for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/igbinary.so
Reading symbols from /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/swoole.so...done.
Loaded symbols for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/swoole.so
Reading symbols from /usr/local/lib/libjemalloc.so.2...done.
Loaded symbols for /usr/local/lib/libjemalloc.so.2
Reading symbols from /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/memcached.so...done.
Loaded symbols for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/memcached.so
Reading symbols from /usr/local/libmemcached/lib/libmemcached.so.11...done.
Loaded symbols for /usr/local/libmemcached/lib/libmemcached.so.11
Reading symbols from /usr/local/libmemcached/lib/libmemcachedutil.so.2...done.
Loaded symbols for /usr/local/libmemcached/lib/libmemcachedutil.so.2
Reading symbols from /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/networkbench.so...done.
Loaded symbols for /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/networkbench.so
Core was generated by `user_rpc_Master                                               '.
Program terminated with signal 11, Segmentation fault.
#0  swReactorThread_onRead (reactor=0x7fa11a37a0a8, event=<value optimized out>)
    at /tmp/rpc-scripts/php/swoole-src-swoole-1.8.5-stable/src/network/ReactorThread.c:806
806         return port->onRead(reactor, port, event);
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.23-15.el6_6.2.x86_64 freetype-2.3.11-17.el6.x86_64 glibc-2.12-1.192.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-57.el6.x86_64 libcom_err-1.41.12-22.el6.x86_64 libcurl-7.19.7-52.el6.x86_64 libgcc-4.4.7-17.el6.x86_64 libidn-1.18-2.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libssh2-1.4.2-2.el6_7.1.x86_64 libstdc++-4.4.7-17.el6.x86_64 libuuid-2.17.2-12.24.el6.x86_64 libxml2-2.7.6-21.el6.x86_64 nspr-4.11.0-1.el6.x86_64 nss-3.21.0-8.el6.x86_64 nss-softokn-freebl-3.14.3-23.el6_7.x86_64 nss-util-3.21.0-2.el6.x86_64 openldap-2.4.40-12.el6.x86_64 openssl-1.0.1e-48.el6_8.1.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  swReactorThread_onRead (reactor=0x7fa11a37a0a8, event=<value optimized out>)
    at /tmp/rpc-scripts/php/swoole-src-swoole-1.8.5-stable/src/network/ReactorThread.c:806
#1  0x00007fa11b3507a1 in swReactorEpoll_wait (reactor=0x7fa11a37a0a8, timeo=<value optimized out>)
    at /tmp/rpc-scripts/php/swoole-src-swoole-1.8.5-stable/src/reactor/ReactorEpoll.c:258
#2  0x00007fa11b3596a0 in swReactorThread_loop_stream (param=<value optimized out>)
    at /tmp/rpc-scripts/php/swoole-src-swoole-1.8.5-stable/src/network/ReactorThread.c:1160
#3  0x0000003072807aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x00000030720e8aad in clone () from /lib64/libc.so.6
(gdb) `

**Comment by matyhtf** [comment]
https://github.com/swoole/swoole-src/issues/966

底层的BUG导致master进程退出，新版本已修复。可以

- 更新至1.9.3版本
- 基于commit制作patch重新编译https://github.com/swoole/swoole-src/commit/f092787d8fded00abae4cd44722b7849e5b1f24a

**Comment by liupdhc** [comment]
好的，感谢，先更新到新版本验证下

**Comment by liupdhc** [comment]
尝试更新了1.9.3，启动http server后，基于该版本的http应用通过nginx代理都会返回499的状态吗，用curl方式去请求会等很久。。基于1.8.5的机器无此现象。。目前尝试采取patch的方式更新到1.8.5

**Comment by liupdhc** [comment]
验证1.9.2无此现象

**Comment by matyhtf** [comment]
499 表示用户取消
