### ISSUE TITLE
php7编译swoole1.9.3，报下面的错误

### ISSUE THREAD

**Issue by birdy0815** [swoole/swoole-src#991]
/bin/sh /home/swoole-src-1.9.3-stable/libtool --mode=compile cc  -I. -I/home/swoole-src-1.9.3-stable -DPHP_ATOM_INC -I/home/swoole-src-1.9.3-stable/include -I/home/swoole-src-1.9.3-stable/main -I/home/swoole-src-1.9.3-stable -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/home/swoole-src-1.9.3-stable -I/home/swoole-src-1.9.3-stable/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /home/swoole-src-1.9.3-stable/swoole_http_client.c -o swoole_http_client.lo
libtool: compile:  cc -I. -I/home/swoole-src-1.9.3-stable -DPHP_ATOM_INC -I/home/swoole-src-1.9.3-stable/include -I/home/swoole-src-1.9.3-stable/main -I/home/swoole-src-1.9.3-stable -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/home/swoole-src-1.9.3-stable -I/home/swoole-src-1.9.3-stable/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /home/swoole-src-1.9.3-stable/swoole_http_client.c  -DDLL_EXPORT -DPIC -o .libs/swoole_http_client.o
/home/swoole-src-1.9.3-stable/swoole_http_client.c: 在函数‘http_client_onReceive’中:
/home/swoole-src-1.9.3-stable/swoole_http_client.c:689:9: 警告：隐式声明函数‘inflateEnd’ [-Wimplicit-function-declaration]
         inflateEnd(&http->gzip_stream);
         ^
/home/swoole-src-1.9.3-stable/swoole_http_client.c:689:25: 错误：‘http_client {或称 struct <匿名>}’没有名为‘gzip_stream’的成员
         inflateEnd(&http->gzip_stream);
                         ^
/home/swoole-src-1.9.3-stable/swoole_http_client.c: 在函数‘http_client_free’中:
/home/swoole-src-1.9.3-stable/swoole_http_client.c:1131:25: 错误：‘http_client {或称 struct <匿名>}’没有名为‘gzip_stream’的成员
         inflateEnd(&http->gzip_stream);
                         ^
make: *** [Makefile:223：swoole_http_client.lo] 错误 1

**Comment by matyhtf** [comment]
请安装zlib-dev
