### ISSUE TITLE
编译的时候，提示make: *** [Makefile:368：swoole.la] 错误 1

### ISSUE THREAD

**Issue by birdy0815** [swoole/swoole-src#995]
.libs/swoole_http_client.o:swoole_http_client.c:(.rdata$.refptr.swoole_zlib_buff                                                                                                                                                                                      er[.refptr.swoole_zlib_buffer]+0x0): undefined reference to `swoole_zlib_buffer'
collect2: error: ld returned 1 exit status
make: *** [Makefile:368：swoole.la] 错误 1

**Comment by matyhtf** [comment]
什么版本？

**Comment by matyhtf** [comment]
请使用stable的稳定版本。
