### ISSUE TITLE
文档建议。

### ISSUE THREAD

**Issue by liaozibo** [swoole/swoole-src#999]
都到2.0了为swoole 团队开发效率点赞
建议韩老大团队发布每一个大版本的时候 ，swoole的新特性，能在 http://wiki.swoole.com/ 里面 有个各个版本新增 特性概览 目录 ，这样一目了然，不用去Google 每个版本之间 又增加了哪些新功能了。毕竟 http://wiki.swoole.com/ 是官网。

**Comment by matyhtf** [comment]
http://wiki.swoole.com/wiki/page/p-project/change_log.html
